### ISSUE TITLE
Issue with HTTP streaming and undefined encoding method for StreamingBuffer

### ISSUE THREAD

**Issue by vojtad** [rails/rails#12001]
Does anyone have issue with error undefined method `encoding' for #<ActionView::StreamingBuffer:0x0000000533a130> with enabled HTTP streaming? Here is whole callstack:

```
ActionView::Template::Error (undefined method `encoding' for #<ActionView::StreamingBuffer:0x0000000533a130>):
    57: 
    58: <% cache_unless user_signed_in?, ['header'] do %>
    59:     <header id="sl-fixedHeader">
    60:       <%= link_to root_path, :id => 'sl-header-logo' do %>
    61:           <div id="sl-header-logoImage"></div>
    62:       <% end %>
    63: 
  /home/vojta/.gem/ruby/2.0.0/bundler/gems/rails-998d9c89e42d/actionview/lib/action_view/helpers/capture_helper.rb:197:in `with_output_buffer'
  /home/vojta/.gem/ruby/2.0.0/bundler/gems/rails-998d9c89e42d/actionview/lib/action_view/helpers/capture_helper.rb:38:in `capture'
  /home/vojta/.gem/ruby/2.0.0/bundler/gems/rails-998d9c89e42d/actionview/lib/action_view/helpers/tag_helper.rb:97:in `content_tag'
  /home/vojta/.gem/ruby/2.0.0/bundler/gems/rails-998d9c89e42d/actionview/lib/action_view/helpers/url_helper.rb:183:in `link_to'
  /home/vojta/dev/sl/sl_web_ruby/app/views/layouts/application.html.erb:60:in `block in _app_views_layouts_application_html_erb___108349764833722706_47082760'
  /home/vojta/.gem/ruby/2.0.0/bundler/gems/rails-998d9c89e42d/actionview/lib/action_view/helpers/cache_helper.rb:133:in `cache_if'
  /home/vojta/.gem/ruby/2.0.0/bundler/gems/rails-998d9c89e42d/actionview/lib/action_view/helpers/cache_helper.rb:146:in `cache_unless'
  /home/vojta/dev/sl/sl_web_ruby/app/views/layouts/application.html.erb:58:in `_app_views_layouts_application_html_erb___108349764833722706_47082760'
  /home/vojta/.gem/ruby/2.0.0/bundler/gems/rails-998d9c89e42d/actionview/lib/action_view/template.rb:143:in `block in render'
  /home/vojta/.gem/ruby/2.0.0/bundler/gems/rails-998d9c89e42d/activesupport/lib/active_support/notifications.rb:161:in `instrument'
  /home/vojta/.gem/ruby/2.0.0/bundler/gems/rails-998d9c89e42d/actionview/lib/action_view/template.rb:337:in `instrument'
  /home/vojta/.gem/ruby/2.0.0/bundler/gems/rails-998d9c89e42d/actionview/lib/action_view/template.rb:141:in `render'
  /home/vojta/.gem/ruby/2.0.0/bundler/gems/rails-998d9c89e42d/actionview/lib/action_view/renderer/streaming_template_renderer.rb:70:in `block (2 levels) in delayed_render'
```

When I comment out the line calling encoding on output_buffer in capture_helper.rb everything works like a charm. I've tried rails 4.0.0, 4.0-stable branch and also master.

**Comment by Gonzih** [comment]
Have same issue with rails 4.2. Is there a fix for that?
