### ISSUE TITLE
Additional select columns are removed when using `inludes`

### ISSUE THREAD

**Issue by dnagir** [rails/rails#12423]
Repro:

``` ruby
gem 'activerecord', '4.0.0'
require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.establish_connection(
  :adapter  => 'postgresql',
  :database => 'x'
)

ActiveRecord::Schema.define do
  create_table :blogs, :force => true do |t|
  end

  create_table :posts, :force => true do |t|
    t.integer :blog_id
  end
end

class Blog < ActiveRecord::Base
  has_many :posts, :dependent => :destroy
end

class Post < ActiveRecord::Base
  belongs_to :blog
end

class TestMe < MiniTest::Unit::TestCase
  def test_includes_with_additional_column
    blog = Blog.create!
    blogs = Blog.select(Blog.column_names + ["'foo' as foo"]).references(:posts).includes(:posts).order('foo').to_a
    assert_equal [blog], blogs
    assert_equal 'foo', blogs.first.foo
  end
end
```

Test fails with:

```
-- create_table(:blogs, {:force=>true})
D, [2013-10-02T17:55:54.494325 #57438] DEBUG -- :    (1.6ms)  DROP TABLE "blogs"
D, [2013-10-02T17:55:54.496579 #57438] DEBUG -- :    (2.1ms)  CREATE TABLE "blogs" ("id" serial primary key) 
   -> 0.0163s
-- create_table(:posts, {:force=>true})
D, [2013-10-02T17:55:54.498144 #57438] DEBUG -- :    (0.7ms)  DROP TABLE "posts"
D, [2013-10-02T17:55:54.499617 #57438] DEBUG -- :    (1.3ms)  CREATE TABLE "posts" ("id" serial primary key, "blog_id" integer) 
   -> 0.0030s
MiniTest::Unit::TestCase is now Minitest::Test. From tmp/test.rb:29:in `<main>'
Run options: --seed 30747

# Running:

D, [2013-10-02T17:55:54.531233 #57438] DEBUG -- :    (0.1ms)  BEGIN
D, [2013-10-02T17:55:54.536553 #57438] DEBUG -- :   SQL (0.5ms)  INSERT INTO "blogs" DEFAULT VALUES RETURNING "id"
D, [2013-10-02T17:55:54.536987 #57438] DEBUG -- :    (0.1ms)  COMMIT
D, [2013-10-02T17:55:54.545380 #57438] DEBUG -- :   SQL (0.4ms)  SELECT "blogs"."id" AS t0_r0, "posts"."id" AS t1_r0, "posts"."blog_id" AS t1_r1 FROM "blogs" LEFT OUTER JOIN "posts" ON "posts"."blog_id" = "blogs"."id" ORDER BY foo
E, [2013-10-02T17:55:54.545437 #57438] ERROR -- : PG::UndefinedColumn: ERROR:  column "foo" does not exist
LINE 1: ...IN "posts" ON "posts"."blog_id" = "blogs"."id"  ORDER BY foo
                                                                    ^
: SELECT "blogs"."id" AS t0_r0, "posts"."id" AS t1_r0, "posts"."blog_id" AS t1_r1 FROM "blogs" LEFT OUTER JOIN "posts" ON "posts"."blog_id" = "blogs"."id"  ORDER BY foo
E

Finished in 0.018798s, 53.1971 runs/s, 0.0000 assertions/s.

  1) Error:
TestMe#test_includes_with_additional_column:
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "foo" does not exist
LINE 1: ...IN "posts" ON "posts"."blog_id" = "blogs"."id"  ORDER BY foo
                                                                    ^
: SELECT "blogs"."id" AS t0_r0, "posts"."id" AS t1_r0, "posts"."blog_id" AS t1_r1 FROM "blogs" LEFT OUTER JOIN "posts" ON "posts"."blog_id" = "blogs"."id"  ORDER BY foo
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_no_cache'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:138:in `block in exec_query'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:425:in `block in log'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:420:in `log'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:885:in `select'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/relation/finder_methods.rb:206:in `find_with_associations'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/relation.rb:585:in `exec_queries'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/relation.rb:471:in `load'
    /Users/dnagir/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/relation.rb:220:in `to_a'
    tmp/test.rb:32:in `test_includes_with_additional_column'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by vmeyet** [comment]
still not working in Rails `4.2.3`. Ping for updates?

That's kind of an annoying bug :cry:

**Comment by kshnurov** [comment]
Broken in Rails 4.2.5:
```
2.2.3 :018 > Review.select('MAX(reviews.id) as max_id').first['max_id']
  Review Load (9.8ms)  SELECT  MAX(reviews.id) as max_id FROM `reviews`  ORDER BY `reviews`.`id` ASC LIMIT 1
 => 11149 
2.2.3 :019 > Review.select('MAX(reviews.id) as max_id').includes(:replies).references(:replies).first['max_id']
  SQL (40.1ms)  SELECT  DISTINCT `reviews`.`id` FROM `reviews` LEFT OUTER JOIN `review_replies` ON `review_replies`.`review_id` = `reviews`.`id`  ORDER BY `reviews`.`id` ASC LIMIT 1
  SQL (0.5ms)  SELECT MAX(reviews.id) as max_id, `reviews`.`id` AS t0_r0, `reviews`.`user_id` AS t0_r1, `reviews`.`operator_id` AS t0_r2, `reviews`.`reservation_id` AS t0_r3, `reviews`.`message` AS t0_r4, `reviews`.`score` AS t0_r5, `reviews`.`created_at` AS t0_r6, `reviews`.`confirmed_at` AS t0_r7, `reviews`.`place_id` AS t0_r8, `reviews`.`status` AS t0_r9, `review_replies`.`id` AS t1_r0, `review_replies`.`review_id` AS t1_r1, `review_replies`.`user_id` AS t1_r2, `review_replies`.`message` AS t1_r3, `review_replies`.`user_name` AS t1_r4, `review_replies`.`user_post` AS t1_r5, `review_replies`.`user_type` AS t1_r6, `review_replies`.`created_at` AS t1_r7, `review_replies`.`updated_at` AS t1_r8 FROM `reviews` LEFT OUTER JOIN `review_replies` ON `review_replies`.`review_id` = `reviews`.`id` WHERE `reviews`.`id` IN (1)  ORDER BY `reviews`.`id` ASC
 => nil 
```

**Comment by runephilosof** [comment]
It seems to have been fixed in Rails 5.
I tested using this query, which failed in 3.2.22.
```
Post.joins(:category).includes(:user).joins(:user).joins('left join comments on comments.post_id = posts.id').group('posts.id').select('categories.id').having('count(comments.id) > 0 or categories.id = 2')
SELECT categories.id, `posts`.`id` AS t0_r0, `posts`.`user_id` AS t0_r1, `posts`.`title` AS t0_r2, `posts`.`created_at` AS t0_r3, `posts`.`updated_at` AS t0_r4, `posts`.`category_id` AS t0_r5, `users`.`id` AS t1_r0, `users`.`name` AS t1_r1, `users`.`created_at` AS t1_r2, `users`.`updated_at` AS t1_r3 FROM `posts` INNER JOIN `categories` ON `categories`.`id` = `posts`.`category_id` INNER JOIN `users` ON `users`.`id` = `posts`.`user_id` left join comments on comments.post_id = posts.id GROUP BY posts.id HAVING (count(comments.id) > 0 or categories.id = 2)
```
