### ISSUE TITLE
Callback bug where `after_update` runs inappropriately on associated model

### ISSUE THREAD

**Issue by nfm** [rails/rails#13360]
I think I've hit a pretty obscure callback related issue.

After creating a record that references an associated model in its `after_create` callback, the associated model's `after_update` callback can be run, even if that model was not updated.

```ruby
gem 'activerecord', '4.0.2'
require 'active_record'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table :users do |t|
  end

  create_table :posts do |t|
    t.integer :user_id
  end

  create_table :comments do |t|
    t.integer :post_id
  end
end

class User < ActiveRecord::Base
  has_many :posts

  after_update :this_should_not_run

  def this_should_not_run
    puts "But it does, even though the user wasn't updated"
  end
end

class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

class Comment < ActiveRecord::Base
  after_create :reference_user

  has_one :user, through: :post
  belongs_to :post

  def reference_user
    puts "If I load my user its after_update callback runs! #{self.user.id}"
  end
end

user = User.create
post = user.posts.create
comment = post.comments.build
comment.save
```

Running the above script will output the strings from both callbacks. The user isn't being touched or modified, just referenced from the comment's callback. If you remove the `self.user.id` call from the comment's callback, the user's callback doesn't run.

The `has_one through` association is required to reproduce the bug. Moving the `after_update` callback to the post model, and referencing the post from the comment's `after_create` doesn't trigger the bug.

My current workaround is to define the `after_create` callback *after* the comment model's associations. This somehow avoids the `after_update` callback being triggered inappropriately.

I initially hit this bug on 3.2.16, but it looks like it's still present on 4.0.2.

Not sure where to dig in and get started on this, it's pretty obscure. Does anyone have any thoughts?

**Comment by magikid** [comment]
I can't reproduce this error with the ActiveRecord 4.2.6.

**Comment by nfm** [comment]
@magikid I think you're right :) It seems to be have been fixed in 4.2.0. The bug reproduces in 4.1.15 for me using the above script, but 4.2.0+ behaves correctly. I haven't tracked down the commit that fixes the issue though.

**Comment by zmoazeni** [comment]
I don't think this issue is resolved. @yukideluxe and I tested this with versions 4.2.5.2, 4.2.6, 4.2.7, and 5.0.0.

Here's an updated script to illustrate the behavior:

```ruby
gem 'activerecord', '5.0.0'
require 'active_record'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define(version: 20160718165350) do
  create_table "accounts", force: :cascade do |t|
    t.integer  "bank_id"
    t.integer  "person_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "accounts", ["bank_id"], name: "index_accounts_on_bank_id"
  add_index "accounts", ["person_id"], name: "index_accounts_on_person_id"

  create_table "banks", force: :cascade do |t|
    t.string   "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "people", force: :cascade do |t|
    t.string   "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
end

class Person < ActiveRecord::Base
end

class Bank < ActiveRecord::Base
  has_many :accounts
  has_many :people, through: :accounts
end

class Account < ActiveRecord::Base
  belongs_to :bank
  belongs_to :person

  after_update :this_should_not_run

  def this_should_not_run
    raise "when did I ever update an account?"
  end
end

person = Person.create!(name: "William")
Bank.create!(name: "Stacks of Money", person_ids: [person.id])
```

Running this with any of those rails versions produces a stack trace like this:

```
∴ bundle exec ruby callback_explosion.rb
-- create_table("accounts", {:force=>:cascade})
   -> 0.0165s
-- add_index("accounts", ["bank_id"], {:name=>"index_accounts_on_bank_id"})
   -> 0.0003s
-- add_index("accounts", ["person_id"], {:name=>"index_accounts_on_person_id"})
   -> 0.0004s
-- create_table("banks", {:force=>:cascade})
   -> 0.0003s
-- create_table("people", {:force=>:cascade})
   -> 0.0003s
-- initialize_schema_migrations_table()
   -> 0.0033s
callback_explosion.rb:46:in `this_should_not_run': when did I ever update an account? (RuntimeError)
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:207:in `block in halting_and_conditional'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:456:in `block in call'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:456:in `each'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:456:in `call'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_update_callbacks'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/callbacks.rb:306:in `_update_record'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/timestamp.rb:81:in `_update_record'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/persistence.rb:534:in `create_or_update'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/callbacks.rb:298:in `block in create_or_update'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:126:in `call'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:455:in `call'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/callbacks.rb:298:in `create_or_update'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/persistence.rb:152:in `save!'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/validations.rb:50:in `save!'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:324:in `block in save!'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:211:in `transaction'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:324:in `save!'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/suppressor.rb:45:in `save!'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/has_many_through_association.rb:89:in `save_through_record'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/has_many_through_association.rb:47:in `insert_record'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/autosave_association.rb:400:in `block in save_collection_association'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/autosave_association.rb:391:in `each'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/autosave_association.rb:391:in `save_collection_association'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/autosave_association.rb:185:in `block in add_autosave_association_callbacks'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/autosave_association.rb:158:in `instance_eval'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/autosave_association.rb:158:in `block in define_non_cyclic_method'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:207:in `block in halting_and_conditional'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:456:in `block in call'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:456:in `each'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:456:in `call'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/callbacks.rb:302:in `_create_record'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/timestamp.rb:68:in `_create_record'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/persistence.rb:534:in `create_or_update'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/callbacks.rb:298:in `block in create_or_update'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:126:in `call'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:455:in `call'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/callbacks.rb:298:in `create_or_update'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/persistence.rb:152:in `save!'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/validations.rb:50:in `save!'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:324:in `block in save!'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:211:in `transaction'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:324:in `save!'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/suppressor.rb:45:in `save!'
  from /Users/zmoazeni/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/persistence.rb:51:in `create!'
  from callback_explosion.rb:51:in `<main>'
```

**Comment by zmoazeni** [comment]
Let me know if you folks would rather a new issue to be created for this. It looks like one difference from @nfm's original report is that this script now uses `has_many :through`.

**Comment by zmoazeni** [comment]
Doh, sorry for the comment spam, but one other interesting tidbit about this is that within the callback, `changes` is an empty hash and `previous_changes` is filled:

```ruby
# changes
{}

# previous_changes
{"id"=>[nil, 1], "bank_id"=>[nil, 1], "person_id"=>[nil, 1], "created_at"=>[nil, 2016-07-18 17:41:17 UTC], "updated_at"=>[nil, 2016-07-18 17:41:17 UTC]}
```

And you can see the previous changes were from the creation: `"id"=>[nil, 1]`

**Comment by nfm** [comment]
Interesting. Your script reproduces the bug for me (on 5.0.0).

I think it's different bug though as my initial bug report script no longer reproduces the error (as of 4.2.0). I'm not sure which commit fixed my bug, but I think the fix for yours will be related!

I'd open a new issue to avoid confusion.

**Comment by nfm** [comment]
I've had a quick look, and these commits look interesting: 068f092ced8483e557725542dd919ab7c516e567 and 719d52db42a0eeebf0f1fa2f8ac3173544dd521e. Related issue: #17209.
