### ISSUE TITLE
ActiveRecord JSON arrays as columns not working

### ISSUE THREAD

**Issue by alexhanh** [rails/rails#14484]
I'm on 4.1.0.rc2.

``` ruby
create_table :venues do |t|
  # t.hstore :slots, array: true, :default => []
  # HStore arrays seem to work after the https://github.com/rails/rails/pull/11444 patch

  t.json :slots, array: true, :default => []
end
```

Migrating results in the following:

```
PG::InvalidTextRepresentation: ERROR:  missing dimension value
: CREATE TABLE "venues" ("id" serial primary key, "slots" json[] DEFAULT '[]') /Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.1.0.rc2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/connection_adapters/postgresql/database_statements.rb:127:in `execute'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/connection_adapters/abstract/schema_statements.rb:205:in `create_table'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:649:in `block in method_missing'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:621:in `block in say_with_time'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:621:in `say_with_time'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:641:in `method_missing'
/Users/alexanderhanhikoski/Code/gizlo/db/migrate/20140226060153_create_tables.rb:6:in `change'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:595:in `exec_migration'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:578:in `block in migrate'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:577:in `migrate'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:752:in `migrate'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:992:in `block in execute_migration_in_transaction'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:1038:in `block in ddl_transaction'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `block in transaction'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/connection_adapters/abstract/database_statements.rb:219:in `within_new_transaction'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/transactions.rb:208:in `transaction'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:1038:in `ddl_transaction'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:991:in `execute_migration_in_transaction'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:953:in `block in migrate'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:949:in `each'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:949:in `migrate'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:807:in `up'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/migration.rb:785:in `migrate'
/Users/alexanderhanhikoski/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.0.rc2/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
```

**Comment by sorich87** [comment]
Using `t.json :slots, default: []` (without the `array: true`) works for me.

**Comment by kamipo** [comment]
This works on 5-1-stable and 5-0-stable.
