### ISSUE TITLE
ActiveRecord fails, when querying multiple tables, passing a hash to order and using limit.

### ISSUE THREAD

**Issue by ushis** [rails/rails#15405]
ActiveRecord fails, when searching over a related table, in combination with ```order(attr: :asc)``` and ```limit``` (See trace).

It works fine, when passing a string to ```order```, removing the ```limit``` or searching the "target" table only.

Trace:

```ruby
> Event.includes(:attendees).where('attendees.id = 1').references(:attendees).order(title: :asc).limit(10).to_a
NoMethodError: undefined method `to_sql' for {:title=>:asc}:Hash
	from /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.0.5/lib/active_record/connection_adapters/postgresql/schema_statements.rb:489:in `block in columns_for_distinct'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.0.5/lib/active_record/connection_adapters/postgresql/schema_statements.rb:487:in `map'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.0.5/lib/active_record/connection_adapters/postgresql/schema_statements.rb:487:in `columns_for_distinct'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.0.5/lib/active_record/relation/finder_methods.rb:249:in `construct_limited_ids_condition'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.0.5/lib/active_record/relation/finder_methods.rb:238:in `apply_join_dependency'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.0.5/lib/active_record/relation/finder_methods.rb:227:in `construct_relation_for_association_find'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.0.5/lib/active_record/relation/finder_methods.rb:206:in `find_with_associations'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.0.5/lib/active_record/relation.rb:585:in `exec_queries'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.0.5/lib/active_record/relation.rb:471:in `load'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.0.5/lib/active_record/relation.rb:220:in `to_a'
	from (irb):13
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.5/lib/rails/commands/console.rb:90:in `start'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.5/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.5/lib/rails/commands.rb:62:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `block in require'
... 3 levels...
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `load'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `block in load'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `load'
	from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.0/lib/spring/commands/rails.rb:6:in `call'
	from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.0/lib/spring/command_wrapper.rb:38:in `call'
	from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.0/lib/spring/application.rb:171:in `block in serve'
	from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.0/lib/spring/application.rb:146:in `fork'
	from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.0/lib/spring/application.rb:146:in `serve'
	from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.0/lib/spring/application.rb:121:in `block in run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.0/lib/spring/application.rb:115:in `loop'
	from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.0/lib/spring/application.rb:115:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.0/lib/spring/application/boot.rb:16:in `<top (required)>'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by monteirobrena** [comment]
@antulik thank you for the tip. This corrected the error `NoMethodError: undefined method `to_sql' for` but not ordered my collection.

**Comment by rafaelfranca** [comment]
Rails 4.0 is not supported anymore.
