### ISSUE TITLE
AR 3.1 / pgbouncer / PostgreSQL issue with prepared statements

### ISSUE THREAD

**Issue by underley** [rails/rails#1627]
Using exec_cache with pgbouncer in transaction mode, as the connections pool can cause random problems.

Scenario:
- the application performs a query through ActiveRecord:

Something.find 2
Something Load (0.9ms) SELECT "somethings" .* FROM "somethings" WHERE "somethings." Id "= $ 1 LIMIT 1 [[" id ", 2]]

- pgbouncer connects to the backend (lets call it PG-1)
- ActiveRecord creates a prepared statement
- pgbouncer prepares for the backend PG-1 prepared statement called a3:

2011-06-10 9:34:04 EDT LOG: duration: 0.505 ms parse a3: SELECT "somethings" .* FROM "somethings" WHERE "somethings." Id "= $ 1 LIMIT 1

- ActiveRecord execute prepared statement
- pgbouncer performs pg backend EXECUTE a3 (...) on PG-1

> 2011-06-10 9:34:04 EDT LOG: duration: 0.048 ms bind a3: SELECT "somethings" .* FROM "somethings" WHERE "somethings." Id "= $ 1 LIMIT 1
> 2011-06-10 9:34:04 GMT DETAIL: parameters: $ 1 = '2 '
> 2011-06-10 9:34:04 EDT LOG: duration: 0.045 ms execute a3: SELECT "somethings" .* FROM "somethings" WHERE "somethings." Id "= $ 1 LIMIT 1
> 2011-06-10 9:34:04 GMT DETAIL: parameters: $ 1 = '2 '

- the application receives the result

> Something Id: 2, symbol: "sss2", description: nil, created_at: "2011-06-10 07:19:34", updated_at: "2011-06-10 07:19:34"

- at this time a different application process connects to pgbouncer, goes to the backend PG-1 and takes it (for example - with begin transaction)
- the first application process once again executes the same query, with other parameters

Something.find 3

- pgbouncer connects to the backend (but this time it goes to the PG-2, because the PG-1 is busy)
- ActiveRecord has prepared statement in exec_cache (called a3)
- ActiveRecord execute prepared statemnet a3

> Something Load (1.2ms) SELECT "somethings" .* FROM "somethings" WHERE "somethings." Id "= $ 1 LIMIT 1 [[" id ", 3]]

- pgbouncer performs  EXECUTE a3 (...) on backend PG-2
- Fail - the PG-2 has no such prepared statement

> PGError: ERROR: Prepared statement "a3" does not exist

Solutions:
- switching pgbouncer mode to session - bad, because it increases the consumption of resources
- wrapping request in transaction - wrong - also increases consumption of resources, with additional side effec - there may be long-lasting transactions that will cause deadlocks
- add option to not use ActiveRecord exec_cache - fix all issues with pgbouncer and additionaly another described [here](http://www.depesz.com/index.php/2008/05/10/prepared-statements-gotcha/)

**Comment by dwbutler** [comment]
We just experienced this exact problem in production. Glad to see we're not alone. I vote for incrementing the counter in `next_key`.

**Comment by kapso** [comment]
+1 just experienced it in production

```ruby
gem 'rails', '4.2.0'
gem 'puma', '2.11.0'
gem 'pg', '0.18.1'
gem 'postgres_ext', '2.4.0'
```


```
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in `prepare': PG::DuplicatePstatement: ERROR:  prepared statement "a3" already exists
: SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1 (ActiveRecord::StatementInvalid)
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in `prepare_statement'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `exec_cache'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:336:in `select'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:39:in `find_by_sql'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/statement_cache.rb:107:in `execute'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/core.rb:186:in `find_by'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/dynamic_matchers.rb:70:in `find_by_id'
	from vendor/bundle/ruby/2.2.0/gems/sorcery-0.9.0/lib/sorcery/adapters/active_record_adapter.rb:85:in `find_by_id'
```

**Comment by yellowaj** [comment]
+1 running into this error in production on Heroku

```
gem 'rails', '4.2.0'
gem 'puma', '2.11.0'
gem 'pg', '0.18.1'
gem 'rack-timeout', '0.2.0'
```

```
ActiveRecord::StatementInvalid: PG::DuplicatePstatement: ERROR: prepared statement "a665" already exists
: SELECT "posts".* FROM "posts" WHERE "posts"."user_id" = $1 ORDER BY "posts"."created_at" ASC, "posts"."created_at" DESC
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb" line 637 in prepare
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb" line 637 in prepare_statement
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb" line 596 in exec_cache
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb" line 585 in execute_and_clear
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb" line 160 in exec_query
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb" line 336 in select
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb" line 32 in select_all
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb" line 68 in block in select_all
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb" line 83 in cache_sql
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb" line 68 in select_all
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/querying.rb" line 39 in find_by_sql
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb" line 638 in exec_queries
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/association_relation.rb" line 19 in exec_queries
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb" line 514 in load
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb" line 243 in to_a
File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb" in to_ary
```

**Comment by rud** [comment]
@yellowaj this ticket is probably never going to be fixed as the issue is correctly blamed on `rack-timeout`. 

The suggested fix is to remove `rack-timeout` from your `Gemfile` (it raises exceptions on the main thread and is completely unsafe) and then fix any long-running database requests as best you can.

Hope this helps you forward.

**Comment by yellowaj** [comment]
@rud thanks for the suggestion!

**Comment by dwbutler** [comment]
We ended up turning off prepared statements. It didn't make any noticeable performance difference.

**Comment by jdurand** [comment]
I hit this when switching from unicorn to puma. Removing rack-timeout "fixed" it for me.
