### ISSUE TITLE
Error in relation/merger.rb on 4.1 when dynamic scoping and ordering are used together

### ISSUE THREAD

**Issue by jcoglan** [rails/rails#16863]
I'm a little unsure of what exactly what is going on here, but this is the smallest reproduction I've managed to extract from [our](https://github.com/futurelearn) application. I have this schema:

```rb
ActiveRecord::Schema.define(version: 20140910122939) do
  create_table "comments", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "post_id"
    t.integer  "author_id"
    t.integer  "parent_id"
  end

  create_table "posts", force: true do |t|
  end

  create_table "users", force: true do |t|
  end
end
```

and these models:

```rb
class User < ActiveRecord::Base
  has_many :comments, -> { merge Comment.order('created_at DESC') }, foreign_key: :author_id
end


class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :author, class_name: User.name
  belongs_to :parent, class_name: name, inverse_of: :replies
  has_many   :replies, class_name: name, foreign_key: :parent_id, inverse_of: :parent

  scope :replies_to, -> (user) do
    parent_ids = user.comments.map(&:id)
    where(parent_id: parent_ids)
  end
end
```

When I try to call `post.comments.replies_to(author)`, this happens:

```
alice = User.create
bob   = User.create
post  = Post.create

comment = Comment.create(post: post, author: alice)
comment = Comment.create(post: post, author: bob, parent: comment)

post.comments.replies_to(alice)
NoMethodError: undefined method `first' for nil:NilClass
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation/merger.rb:125:in `block in merge_multi_values'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation/merger.rb:123:in `map!'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation/merger.rb:123:in `merge_multi_values'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation/merger.rb:76:in `merge'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation/spawn_methods.rb:44:in `merge!'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation/spawn_methods.rb:33:in `merge'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/associations/association.rb:86:in `scope'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/associations/collection_association.rb:404:in `scope'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/associations/collection_proxy.rb:36:in `initialize'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation/delegation.rb:106:in `new'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation/delegation.rb:106:in `create'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/associations/collection_association.rb:36:in `reader'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/associations/builder/association.rb:110:in `comments'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/app/models/comment.rb:8:in `block in <class:Comment>'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/scoping/named.rb:151:in `call'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/scoping/named.rb:151:in `block (2 levels) in scope'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation.rb:285:in `scoping'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/scoping/named.rb:151:in `block in scope'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation/delegation.rb:94:in `public_send'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation/delegation.rb:94:in `block in method_missing'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/associations/collection_proxy.rb:876:in `block in scoping'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation.rb:285:in `scoping'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/associations/collection_proxy.rb:876:in `scoping'
        from /home/jcoglan/projects/futurelearn/dynamic_scope/.bundle/ruby/2.0.0/gems/activerecord-4.1.5/lib/active_record/relation/delegation.rb:94:in `method_missing'
```

This code works on 4.0.9 but not on 4.1.5 (or any other 4.1 release up to 4.1.6.rc2).

Removing the `-> { merge Comment.order('created_at DESC') }` clause from `User.comments` stops the error from happening, as does calling `author.comments` beforehand, i.e.:

```rb
alice.comments
post.comments.replies_to(alice) # => no error
```

So it seems like an interaction between using `Comment.order` and two concurrent scoped queries on `Comment`; if `alice.comments` is not called before `post.comments.replies_to(alice)` as above, then the call to `user.comments` inside the `Comment.replies_to` scope will be scoped by `post.comments`. Rewriting that scope like this also fixes the problem:

```rb
class Comment
  scope :replies_to, -> (user) do
    parent_ids = Comment.unscoped.where(author_id: user.id).map(&:id)
    where(parent_id: parent_ids)
  end
end
```

I'm not sure if this is a sound enough understanding of the problem to write a test, or if this is a duplicate of other issues; #15244 and #16324 report a similar kind of error, but for different reasons. If this is a good enough explanation and is not a duplicate I'm happy to try writing a test for it.

**Comment by rafaelfranca** [comment]
Since Rails 4.2 fix the issue I'll close it. Rails 4.1 is not our priority maintenance version anymore
