### ISSUE TITLE
#take on has_many doesn't work if association is loaded

### ISSUE THREAD

**Issue by willbryant** [rails/rails#16934]
If a has_many is loaded, calling #take on it raises the following error:

```
       undefined method `first' for nil:NilClass
     # /Users/will/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/bundler/gems/rails-c31a580dabcc/activerecord/lib/active_record/relation/finder_methods.rb:458:in `find_take'
     # /Users/will/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/bundler/gems/rails-c31a580dabcc/activerecord/lib/active_record/relation/finder_methods.rb:98:in `take'
```

**Comment by rafaelfranca** [comment]
Closed by #16935
