### ISSUE TITLE
NoMethodError - undefined method `build' on ActiveRecord::PredicateBuilder (Class)

### ISSUE THREAD

**Issue by ghazel** [rails/rails#17091]
ActveRecord bug, or rubinius bug?

I'm using rbx with Puma, so there are threads involved.

```
ArgumentError - A copy of ActiveRecord::PredicateBuilder has been removed from the module tree but is still active!:
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:465:in `load_missing_constant'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:180:in `const_missing'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/predicate_builder.rb:113:in `__script__'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/predicate_builder.rb:2:in `__script__'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/predicate_builder.rb:1:in `__script__'
        kernel/common/code_loader.rb:243:in `require'
        kernel/common/autoload.rb:55:in `resolve'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/query_methods.rb:569:in `where!'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/query_methods.rb:559:in `where'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/finder_methods.rb:81:in `find_by'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/querying.rb:7:in `find_by'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/dynamic_matchers.rb:70:in `find_by_id'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/dynamic_matchers.rb:24:in `find_by_id (method_missing)'
```

Later:

```
NameError - uninitialized constant ActiveRecord::PredicateBuilder::RelationHandler:
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/predicate_builder.rb:113:in `__script__'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/predicate_builder.rb:2:in `__script__'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/predicate_builder.rb:1:in `__script__'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/query_methods.rb:569:in `where!'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/query_methods.rb:0:in `where'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/finder_methods.rb:81:in `find_by'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/querying.rb:7:in `find_by'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/dynamic_matchers.rb:70:in `find_by_id'
```

Later and then continuously:

```
NoMethodError - undefined method `build' on ActiveRecord::PredicateBuilder (Class):
        kernel/delta/kernel.rb:78:in `build (method_missing)'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/predicate_builder.rb:66:in `expand'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/predicate_builder.rb:43:in `build_from_hash'
        kernel/common/hash.rb:342:in `each'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/query_methods.rb:950:in `build_where'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/query_methods.rb:572:in `where!'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/query_methods.rb:559:in `where'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/relation/finder_methods.rb:81:in `find_by'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/querying.rb:7:in `find_by'
        /home/ghazel/.rvm/gems/rbx-2.2.10/gems/activerecord-4.1.5/lib/active_record/dynamic_matchers.rb:70:in `find_by_id'
```

**Comment by p8** [comment]
Is this issue something that should not longer occur with Zeitwerk?

**Comment by fxn** [comment]
@p8 From what I recall, AS autoloading was not involved in this ticket. This was reported in a non-Rails project using Active Record, which uses pure Ruby `Module#autoload`.

**Comment by p8** [comment]
Thanks @fxn! Good to know. I'll leave the ticket open then..

**Comment by byroot** [comment]
Rubinius is no longer a thing, and from what I understand of this issue with was specific to Rubinius, so I think we can close it.
