### ISSUE TITLE
A has_many through association causes ArgumentError: wrong number of arguments (2 for 1) due to differences in build_association method signature between AbstractReflection and AssociationReflection when using protected_attributes

### ISSUE THREAD

**Issue by cofiem** [rails/rails#18121]
(this may be an issue with the protected_attributes gem, I'm not sure)

protected_attributes version 1.0.8
activerecord version 4.2.0

I have a model:

    class AudioEvent < ActiveRecord::Base
    ....
        attr_accessible ... :tags_attributes ...
        has_many :tags, through: :taggings
    ....
    end

I'm trying to use `tags_attributes` to assign attributes to tags using POST to the create action. The create action is  not relevant here - it doesn't get that far.
Rspec test (using `rspec_api_documentation`) that perfoms the json POST: [code](https://github.com/QutBioacoustics/baw-server/blob/develop/spec/acceptance/audio_events_spec.rb#L1101)
It works fine for `:tag_ids`: [code](https://github.com/QutBioacoustics/baw-server/blob/develop/spec/acceptance/audio_events_spec.rb#L1143)

Whenever I do that, I get the error below. It is raised from `activerecord-4.2.0/lib/active_record/reflection.rb:130` due to the arguments not matching the method signature. The error only occurs when `reflection` in the line `reflection.build_association(attributes, options) do |record|` in `protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:5` is `ActiveRecord::Reflection::AbstractReflection` (method signature is `build_association(attributes, &block)`), rather than `ActiveRecord::Reflection::AssociationReflection` (method signature is `build_association(*options, &block)`).

That's as much as I can work out. Help?

````
ArgumentError:
       wrong number of arguments (2 for 1)
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/reflection.rb:130:in `build_association'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:5:in `build_record'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:72:in `build_record'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:19:in `build'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/nested_attributes.rb:117:in `block in assign_nested_attributes_for_collection_association'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/nested_attributes.rb:112:in `each'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/nested_attributes.rb:112:in `assign_nested_attributes_for_collection_association'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/nested_attributes.rb:37:in `tags_attributes='
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:54:in `public_send'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:67:in `block in assign_attributes'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_controller/metal/strong_parameters.rb:183:in `each_pair'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_controller/metal/strong_parameters.rb:183:in `each_pair'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:61:in `assign_attributes'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/core.rb:8:in `init_attributes'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/core.rb:280:in `initialize'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:61:in `new'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:61:in `new'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/reflection.rb:5:in `build_association'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:5:in `build_record'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:19:in `build'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:55:in `build'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/cancancan-1.9.2/lib/cancan/controller_resource.rb:85:in `build_resource'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/cancancan-1.9.2/lib/cancan/controller_resource.rb:66:in `load_resource_instance'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/cancancan-1.9.2/lib/cancan/controller_resource.rb:32:in `load_resource'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/cancancan-1.9.2/lib/cancan/controller_resource.rb:25:in `load_and_authorize_resource'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/cancancan-1.9.2/lib/cancan/controller_resource.rb:10:in `block in add_before_filter'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `instance_exec'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `block in make_lambda'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:145:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:308:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:308:in `block (2 levels) in halting'
     # ./app/controllers/application_controller.rb:432:in `set_then_reset_user_stamper'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:427:in `block in make_lambda'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:307:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:307:in `block in halting'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in `process'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_controller/metal.rb:195:in `dispatch'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_controller/metal.rb:236:in `block in action'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:42:in `serve'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:43:in `block in serve'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `each'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `serve'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:802:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/exception_notification-4.0.1/lib/exception_notification/rack.rb:28:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/bullet-4.14.0/lib/bullet/rack.rb:10:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-cors-0.2.9/lib/rack/cors.rb:54:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/etag.rb:24:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/conditionalget.rb:38:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/middleware/flash.rb:260:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/middleware/cookies.rb:560:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/query_cache.rb:36:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/rack/logger.rb:22:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/lock.rb:17:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-rewrite-1.5.0/lib/rack/rewrite.rb:24:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-test-0.6.2/lib/rack/mock_session.rb:30:in `request'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-test-0.6.2/lib/rack/test.rb:230:in `process_request'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rack-test-0.6.2/lib/rack/test.rb:66:in `post'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/rack_test_client.rb:38:in `do_request'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/client_base.rb:42:in `process'
     # /home/mark/.rvm/gems/ruby-2.1.5/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/client_base.rb:16:in `post'
     # ./spec/acceptance/audio_events_spec.rb:1108:in `block (3 levels) in <top (required)>'
````

**Comment by genreil** [comment]
Hi,

I am getting a similar error with the following code (while running tests during upgrade to Rails 4.2):

class Tenant < ActiveRecord::Base
  has_many :tenant_addresses, :dependent => :destroy
  has_many :addresses, :through => :tenant_addresses
...
Then while building:

hash = {:street => sample_address, :city => city, :state => state,   :country => country, :zip => zip }
[2] pry(#<Tenant>)> addresses.build(hash)
ArgumentError: wrong number of arguments (2 for 1)
from /home/gen/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/reflection.rb:130:in `build_association'

Env:
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
Rails 4.2.0

**Comment by sgrif** [comment]
The issue has already been fixed, it'll be released with 4.1

**Comment by sgrif** [comment]
Er 4.2.1 rather

**Comment by genreil** [comment]
Thanks for the prompt response! When is the 4.2.1 release comes out? Is there a way to patch it until then?

**Comment by sgrif** [comment]
We have not made any announcements about when 4.2.1 will be released. You can point your app at the `4-2-stable` branch.

**Comment by genreil** [comment]
Thanks a lot!

**Comment by rafaelfranca** [comment]
Usually I do a release every month, so I'd expect it to be released near to January 20.

**Comment by genreil** [comment]
Thank you. I just wanted to clarify. I just tried to point to 4-2-stable branch as following:
gem 'rails', :github => 'rails/rails', :branch => '4-2-stable'

And then to run the following command with the output below:
bundle update protected_attributes | grep "git://github.com/rails/rails.git"
Using activesupport 4.2.0 from git://github.com/rails/rails.git (at 4-2-stable)
Using actionview 4.2.0 from git://github.com/rails/rails.git (at 4-2-stable)
Using actionpack 4.2.0 from git://github.com/rails/rails.git (at 4-2-stable)
Using activejob 4.2.0 from git://github.com/rails/rails.git (at 4-2-stable)
Using actionmailer 4.2.0 from git://github.com/rails/rails.git (at 4-2-stable)
Using activemodel 4.2.0 from git://github.com/rails/rails.git (at 4-2-stable)
Using activerecord 4.2.0 from git://github.com/rails/rails.git (at 4-2-stable)
Using railties 4.2.0 from git://github.com/rails/rails.git (at 4-2-stable)
Using rails 4.2.0 from git://github.com/rails/rails.git (at 4-2-stable)

Looks good to me. However, when I rerun the tests I got the same error. Am I doing something wrong, or something is missing on the stable branch.

Thanks!

**Comment by genreil** [comment]
I have also tried to run:
bundle update rails | grep "git://github.com/rails/rails.git"
Updating git://github.com/rails/rails.git
...... Here the same as above.....

**Comment by sgrif** [comment]
You might need to point at protected attributes master as well

**Comment by genreil** [comment]
Thanks, Sean! That resolved it.

**Comment by jduarte** [comment]
Hey guys, it's still missing the 1.0.9 tag in the repo!

Thanks

**Comment by dandlezzz** [comment]
Hello all, I am on rails 4-2-stable with the latest version of protected attributes and am still getting build_record error. Any ideas?


  ArgumentError (wrong number of arguments (2 for 1)):
  /Users/danielamiller/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-eb53536a1ccd/activerecord/lib/active_record/associations/through_association.rb:95:in `build_record'
  protected_attributes (1.0.8) lib/active_record/mass_assignment_security/associations.rb:72:in `build_record'
  protected_attributes (1.0.8) lib/active_record/mass_assignment_security/associations.rb:19:in `build'
  protected_attributes (1.0.8) lib/active_record/mass_assignment_security/associations.rb:55:in `build'

**Comment by sgrif** [comment]
@dandlezzz As multiple replies have already stated, you need to point at protected_attributes master and 4-2-stable until new versions are released.
