### ISSUE TITLE
ActiveRecord calculations fail if using abstract model with custom connection

### ISSUE THREAD

**Issue by skladd** [rails/rails#18359]
Hi,
I stumpled upon this after upgrading (standalone) ActiveRecord. Calculations like #count and #average fail on models inherited from abstract classes with custom connections.
The shown code works fine for ActiveRecord 4.1.8, but fails for 4.2.0:

```ruby
gem 'activerecord', '4.2.0' #'4.1.8' works
require 'active_record'
require 'minitest/autorun'
require 'logger'

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)
ActiveRecord::Base.logger = Logger.new(STDOUT)

class AbstractModel < ActiveRecord::Base
  self.abstract_class = true
  establish_connection(adapter: 'sqlite3', database: ':memory:')
end

ActiveRecord::Schema.define do
  @connection = AbstractModel.connection
  create_table :posts do |t|
  end
end

class Post < AbstractModel
end

class BugTest < Minitest::Test
  def test_count
    Post.create!
    assert_equal 1, Post.all.length
    assert_equal 1, Post.count
  end
end
```

It raises a ConnectionNotEstablished exception:
```
BugTest#test_count:
ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base
    /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:564:in `retrieve_connection'
    /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
    /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
    /usr/local/rvm/gems/ruby-2.1.5/gems/arel-6.0.0/lib/arel/nodes/node.rb:48:in `to_sql'
    /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:388:in `column_name_for_operation'
    /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:257:in `execute_simple_calculation'
    /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:221:in `perform_calculation'
    /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:127:in `calculate'
    /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:42:in `count'
    /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/querying.rb:13:in `count'
:in `test_count'
```

Apparently the calculation methods like #count try to check out a connection from the pool of ActiveRecord::Base instead of AbstractModel. I checked the changelog, but did not find anything which explained this behavior. Thus it looks like a regression for me.

Thanks!

**Comment by brainopia** [comment]
@skladd Hello,

It is indeed a regression. Thank you for reproduction!
#18377 has a fix
