### ISSUE TITLE
ActionMailer issues with Rails 4.2.0

### ISSUE THREAD

**Issue by slavingia** [rails/rails#18532]
Since upgrading from Rails 4.1.7.1 to Rails 4.2.0, I've gotten this error. Nothing has changed besides a bunch of Gem upgrades.

```
`method_missing': undefined method `action_mailer' for #<Rails::Application::Configuration:0x0000000b4960f0>
```

It seems as though ActionMailer isn't being included as part of the app. Any ideas? ```config.action_view``` and others still work fine.

**Comment by carlosantoniodasilva** [comment]
How are your requires at the beginning of `config/application.rb`, have they changed from the defaults? Are you requiring `rails/all` or specific frameworks instead? Also, can you show the entire stack trace please?

**Comment by slavingia** [comment]
My requires:

```
require File.expand_path('../boot', __FILE__)
require "rails/all"
require "socket"
require "syslog/logger"
require "sprockets/railtie"
```

**Comment by slavingia** [comment]
The stack trace:

```
/home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `action_mailer' for #<Rails::Application::Configuration:0x0000000bcd8330> (NoMethodError)
	from /vagrant/config/application.rb:77:in `<class:Application>'
	from /vagrant/config/application.rb:14:in `<module:Blog>'
	from /vagrant/config/application.rb:13:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/vagrant/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
