### ISSUE TITLE
add_foreign_key generate error with postgresql

### ISSUE THREAD

**Issue by cheunghy** [rails/rails#18581]
The migration is like this.
``add_foreign_key`` is new in Rails 4.2 right?
``` ruby
class AddColumnsToHerbs < ActiveRecord::Migration
  def change
    add_column :herbs, :gained_from, :text
    add_column :herbs, :taste, :string
    add_column :herbs, :gwai, :string
    add_column :herbs, :usage, :integer
    add_column :herbs, :usage_description, :text
    add_reference :herbs, :formal_name, index: true
    add_foreign_key :herbs, :formal_names
    add_reference :herbs, :processed_from, index: true
    add_foreign_key :herbs, :processed_froms
  end
end
```

It works fine with sqlite3.
When I deploy, I got 
``` 
rake db:migrate
== 20150118065114 AddColumnsToHerbs: migrating ================================
-- add_column(:herbs, :gained_from, :text)
   -> 0.0011s
-- add_column(:herbs, :taste, :string)
   -> 0.0005s
-- add_column(:herbs, :gwai, :string)
   -> 0.0004s
-- add_column(:herbs, :usage, :integer)
   -> 0.0005s
-- add_column(:herbs, :usage_description, :text)
   -> 0.0004s
-- add_reference(:herbs, :formal_name, {:index=>true})
   -> 0.0118s
-- add_foreign_key(:herbs, :formal_names)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "formal_names" does not exist
: ALTER TABLE "herbs" ADD CONSTRAINT "fk_rails_1dd41bdfcf"
FOREIGN KEY ("formal_name_id")
  REFERENCES "formal_names" ("id")
/var/herbology/db/migrate/20150118065114_add_columns_to_herbs.rb:9:in `change'
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "formal_names" does not exist
: ALTER TABLE "herbs" ADD CONSTRAINT "fk_rails_1dd41bdfcf"
FOREIGN KEY ("formal_name_id")
  REFERENCES "formal_names" ("id")
/var/herbology/db/migrate/20150118065114_add_columns_to_herbs.rb:9:in `change'
PG::UndefinedTable: ERROR:  relation "formal_names" does not exist
/var/herbology/db/migrate/20150118065114_add_columns_to_herbs.rb:9:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
