### ISSUE TITLE
Setting invalid JSON terminally breaks ActiveRecord object

### ISSUE THREAD

**Issue by lawso017** [rails/rails#18629]
As illustrated in this minimal test case against edge:

https://gist.github.com/lawso017/1095d2e8ba868fdd8a6c

attempting to set an AR object's JSON or JSONB attribute to an invalid (non-JSON) value results in a JSON::ParserError.

However, subsequent attempts to reset the value fail with the same ParserError, as the object keeps attempting to parse the previously-submitted invalid input:

````
BugTest#test_setting_invalid_json_terminally_breaks_activerecord_object:
JSON::ParserError: 795: unexpected token at 'foo'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-14599a575850/activesupport/lib/active_support/json/decoding.rb:26:in `decode'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-14599a575850/activerecord/lib/active_record/connection_adapters/postgresql/oid/json.rb:14:in `type_cast_from_database'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-14599a575850/activerecord/lib/active_record/type/mutable.rb:5:in `type_cast_from_user'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-14599a575850/activerecord/lib/active_record/attribute.rb:108:in `type_cast'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-14599a575850/activerecord/lib/active_record/attribute.rb:42:in `original_value'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-14599a575850/activerecord/lib/active_record/attribute.rb:37:in `value'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-14599a575850/activerecord/lib/active_record/attribute_set.rb:31:in `fetch_value'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-14599a575850/activerecord/lib/active_record/attribute_methods/read.rb:73:in `_read_attribute'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-14599a575850/activerecord/lib/active_record/attribute_methods.rb:408:in `clone_attribute_value'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-14599a575850/activerecord/lib/active_record/attribute_methods/dirty.rb:122:in `old_attribute_value'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-14599a575850/activerecord/lib/active_record/attribute_methods/dirty.rb:94:in `write_attribute'
    /Users/williamlawson/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-14599a575850/activerecord/lib/active_record/attribute_methods/write.rb:33:in `__temp__36f6e64756e647='
    bugreport.rb:41:in `test_setting_invalid_json_terminally_breaks_activerecord_object'
````

First experienced in Rails 4.2 although test case is against edge. Believe you need at least Postgresql 9.2 to test JSON fields, and Postgresql 9.4 to test JSONB. Same behavior occurs with both.

Thanks for any insight -- doesn't seem like desirable behavior but wanted to confirm as I go digging further.

**Comment by rafaelfranca** [comment]
cc @sgrif

**Comment by lawso017** [comment]
Even better. Thanks, gentlemen. Looking forward to 4.2.1.

**Comment by viguza** [comment]
Hi @sgrif I encountered with the same issue, but I was **intentionally** trying to store a simple string value.

It may seem weird why try to save a string into a json column, but in my use case I don't know what the values will be and I think it is a waste to store a full hash or array structure if the value can be a simple number or string.

Also, since Postgres itself allows this, why not ActiveRecord support it?
`INSERT INTO settings VALUES('my_key','"my string value"');`

**Comment by ktimothy** [comment]
But how to catch json parsing error?
