### ISSUE TITLE
Rails 4.2 change_table with foreign key issue on upgrade

### ISSUE THREAD

**Issue by pzula** [rails/rails#18630]
Hello!

I have an old migration that up until now has worked with prior Rails upgrades, but now in upgrading from Rails 4.1 => 4.2, fails during the initial `rake db:migrate` process.

The migration in question is below:

```
class AddInterviewForeignKeys < ActiveRecord::Migration
  def change
    InterviewTemplate.reset_column_information

    change_table :interview_templates do |t|
      t.foreign_key :organizations
      t.foreign_key :jobs
      t.foreign_key :users, :column => :modified_by_id
      t.foreign_key :users, :column => :created_by_id
      t.foreign_key :interview_types
    end

    change_table :interview_template_sections do |table|
      t.foreign_key :interview_templates, :dependent => :delete
      t.foreign_key :interview_sections
    end

    change_table :interview_section_questions do |table|
      t.foreign_key :interview_sections, :dependent => :delete
      t.foreign_key :interview_questions
    end

    change_table :interview_question_answers do |table|
      t.foreign_key :interview_questions, :dependent => :delete
      t.foreign_key :interview_answers
    end

  end
end

```

The resulting error looks like this:

```
no implicit conversion of nil into String/Users/pzula/hireology/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/utils.rb:24:in `quote_ident'
/Users/pzula/hireology/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/utils.rb:24:in `quoted'
/Users/pzula/hireology/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/quoting.rb:31:in `quote_table_name'
/Users/pzula/hireology/app/vendor/bundle/ruby/2.0.0/gems/foreigner-1.6.1/lib/foreigner/connection_adapters/sql2003.rb:24:in `add_foreign_key'
/Users/pzula/hireology/app/vendor/bundle/ruby/2.0.0/gems/foreigner-1.6.1/lib/foreigner/connection_adapters/abstract/table.rb:23:in `foreign_key'
/Users/pzula/hireology/app/db/migrate/20140205103941_add_interview_foreign_keys.rb:6:in `block in change'
/Users/pzula/hireology/app/vendor/bundle/ruby/2.0.0/gems/activ/Users/pzula/spzula app (APP-1223) ✨  no implicit conversion of nil into String/Users/pzula/hireology/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/utils.rb:24:in `quote_ident'
/Users/pzula/hireology/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/utils.rb:24:in `quoted'
/Users/pzula/hireology/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/quoting.rb:31:in `quote_table_name'
/Users/pzula/hireology/app/vendor/bundle/ruby/2.0.0/gems/foreigner-1.6.1/lib/foreigner/connection_adapters/sql2003.rb:24:in `add_foreign_key'
/Users/pzula/hireology/app/vendor/bundle/ruby/2.0.0/gems/foreigner-1.6.1/lib/foreigner/connection_adapters/abstract/table.rb:23:in `foreign_key'
/Users/pzula/hireology/app/db/migrate/20140205103941_add_interview_foreign_keys.rb:6:in `block in change'
```

Do you have any suggestions on how to handle this problem without altering the migration?

**Comment by rafaelfranca** [comment]
Seems you are using `foreigner` and seems to be a old version that may not work with Rails 4.2. Could you try to upgrade it?

**Comment by pzula** [comment]
Thank you! I think that this won't be resolved based on this issue I found: https://github.com/matthuhiggins/foreigner/pull/159 Thank you for looking into this!
