### ISSUE TITLE
`include?` does not respect explicit references (regression)

### ISSUE THREAD

**Issue by afn** [rails/rails#18632]
Suppose we have these models:

```ruby
class Item < ActiveRecord::Base
  belongs_to :list
  belongs_to :user
end

class List < ActiveRecord::Base
  has_many :items, -> { includes(:user).order('users.id').references(:users) }
end

class User < ActiveRecord::Base
end
```

Calling `include?` on List#items results in a query that has an `ORDER` clause without the join.

Rails 4.2 (and `4-2-stable`):

```
Loading development environment (Rails 4.2.0)
2.2.0 :001 > l = List.create
   (0.0ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "lists" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2015-01-21 21:07:23.022014"], ["updated_at", "2015-01-21 21:07:23.022014"]]
   (1.4ms)  commit transaction
 => #<List id: 1, created_at: "2015-01-21 21:07:23", updated_at: "2015-01-21 21:07:23">
2.2.0 :002 > i = l.items.create
   (0.0ms)  begin transaction
  SQL (0.2ms)  INSERT INTO "items" ("list_id", "created_at", "updated_at") VALUES (?, ?, ?)  [["list_id", 1], ["created_at", "2015-01-21 21:07:33.324877"], ["updated_at", "2015-01-21 21:07:33.324877"]]
   (1.3ms)  commit transaction
 => #<Item id: 1, list_id: 1, created_at: "2015-01-21 21:07:33", updated_at: "2015-01-21 21:07:33", position: nil, type: nil, user_id: nil>
2.2.0 :003 > l.reload.items
  List Load (0.2ms)  SELECT  "lists".* FROM "lists" WHERE "lists"."id" = ? LIMIT 1  [["id", 1]]
  SQL (0.1ms)  SELECT "items"."id" AS t0_r0, "items"."list_id" AS t0_r1, "items"."created_at" AS t0_r2, "items"."updated_at" AS t0_r3, "items"."position" AS t0_r4, "items"."type" AS t0_r5, "items"."user_id" AS t0_r6, "users"."id" AS t1_r0, "users"."created_at" AS t1_r1, "users"."updated_at" AS t1_r2 FROM "items" LEFT OUTER JOIN "users" ON "users"."id" = "items"."user_id" WHERE "items"."list_id" = ?  ORDER BY users.id  [["list_id", 1]]
 => #<ActiveRecord::Associations::CollectionProxy [#<Item id: 1, list_id: 1, created_at: "2015-01-21 21:07:33", updated_at: "2015-01-21 21:07:33", position: nil, type: nil, user_id: nil>]>
2.2.0 :004 > l.reload.items.include?(i)
  List Load (0.2ms)  SELECT  "lists".* FROM "lists" WHERE "lists"."id" = ? LIMIT 1  [["id", 1]]
  Item Exists (0.4ms)  SELECT "items".* FROM "items" WHERE "items"."list_id" = ? AND "items"."id" = ?  ORDER BY users.id  [["list_id", 1], ["id", 1]]
SQLite3::SQLException: no such column: users.id: SELECT "items".* FROM "items" WHERE "items"."list_id" = ? AND "items"."id" = ?  ORDER BY users.id
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: users.id: SELECT "items".* FROM "items" WHERE "items"."list_id" = ? AND "items"."id" = ?  ORDER BY users.id
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `initialize'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `new'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `prepare'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activerecord-4.2.0/lib/active_record/connection_adapters/sqlite3_adapter.rb:310:in `block in exec_query'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activerecord-4.2.0/lib/active_record/connection_adapters/sqlite3_adapter.rb:297:in `exec_query'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:336:in `select'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:38:in `select_one'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:43:in `select_value'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:314:in `exists?'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:373:in `include?'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/activerecord-4.2.0/lib/active_record/associations/collection_proxy.rb:852:in `include?'
	from (irb):4
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/afn/.rvm/gems/ruby-2.2.0@closing_time/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Rails 4.1.9:

```
Loading development environment (Rails 4.1.9)
2.2.0 :001 > l = List.create
   (0.0ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "lists" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2015-01-21 21:11:49.392376"], ["updated_at", "2015-01-21 21:11:49.392376"]]
   (1.1ms)  commit transaction
 => #<List id: 3, created_at: "2015-01-21 21:11:49", updated_at: "2015-01-21 21:11:49">
2.2.0 :002 > i = l.items.create
   (0.0ms)  begin transaction
  SQL (0.2ms)  INSERT INTO "items" ("created_at", "list_id", "updated_at") VALUES (?, ?, ?)  [["created_at", "2015-01-21 21:11:54.903490"], ["list_id", 3], ["updated_at", "2015-01-21 21:11:54.903490"]]
   (1.2ms)  commit transaction
 => #<Item id: 2, list_id: 3, created_at: "2015-01-21 21:11:54", updated_at: "2015-01-21 21:11:54", position: nil, type: nil, user_id: nil>
2.2.0 :003 > l.reload.items
  List Load (0.2ms)  SELECT  "lists".* FROM "lists"  WHERE "lists"."id" = ? LIMIT 1  [["id", 3]]
  SQL (0.1ms)  SELECT "items"."id" AS t0_r0, "items"."list_id" AS t0_r1, "items"."created_at" AS t0_r2, "items"."updated_at" AS t0_r3, "items"."position" AS t0_r4, "items"."type" AS t0_r5, "items"."user_id" AS t0_r6, "users"."id" AS t1_r0, "users"."created_at" AS t1_r1, "users"."updated_at" AS t1_r2 FROM "items" LEFT OUTER JOIN "users" ON "users"."id" = "items"."user_id" WHERE "items"."list_id" = ?  ORDER BY users.id  [["list_id", 3]]
 => #<ActiveRecord::Associations::CollectionProxy [#<Item id: 2, list_id: 3, created_at: "2015-01-21 21:11:54", updated_at: "2015-01-21 21:11:54", position: nil, type: nil, user_id: nil>]>
2.2.0 :004 > l.reload.items.include?(i)
  List Load (0.1ms)  SELECT  "lists".* FROM "lists"  WHERE "lists"."id" = ? LIMIT 1  [["id", 3]]
  Item Exists (0.1ms)  SELECT  1 AS one FROM "items" LEFT OUTER JOIN "users" ON "users"."id" = "items"."user_id" WHERE "items"."list_id" = ? AND "items"."id" = 2 LIMIT 1  [["list_id", 3]]
 => true
```

**Comment by afn** [comment]
Awesome — thanks for the quick turnaround! :)
