### ISSUE TITLE
Assigning hstore['size'] with a bigint raises exception

### ISSUE THREAD

**Issue by namor** [rails/rails#18653]
Basic information

Asset is an ActiveRecord Model (Postgres)  with a hstore named metadata

```ruby
a = Asset.new
a.metadata["size"] = "2318821467"
a.save
```

Stacktrace

```
RangeError: 2318821467 is out of range for ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer with limit 4
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/type/integer.rb:41:in `ensure_in_range'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/type/integer.rb:34:in `cast_value'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/type/value.rb:93:in `type_cast'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/type/numeric.rb:15:in `type_cast'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/type/value.rb:34:in `type_cast_from_user'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/attribute.rb:110:in `type_cast'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/attribute.rb:42:in `original_value'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/attribute.rb:37:in `value'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/attribute.rb:46:in `value_for_database'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/attribute_methods/dirty.rb:168:in `store_original_raw_attribute'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/attribute_methods/dirty.rb:97:in `write_attribute'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/attribute_methods.rb:50:in `__temp__6696c656f53796a756'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/attribute_assignment.rb:54:in `public_send'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/attribute_assignment.rb:35:in `each'
... 24 levels...
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/activerecord/lib/active_record/transactions.rb:285:in `save'
	from (irb):36
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/railties/lib/rails/commands/console.rb:110:in `start'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/railties/lib/rails/commands/console.rb:9:in `start'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/railties/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/railties/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/railties/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/railties/lib/rails/app_rails_loader.rb:45:in `require'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/railties/lib/rails/app_rails_loader.rb:45:in `block in exec_app_rails'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/railties/lib/rails/app_rails_loader.rb:34:in `loop'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/railties/lib/rails/app_rails_loader.rb:34:in `exec_app_rails'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/railties/lib/rails/cli.rb:5:in `<top (required)>'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/railties/bin/rails:9:in `require'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bundler/gems/rails-62e9e61f2d1b/railties/bin/rails:9:in `<top (required)>'
	from /home/mvdev/apps/overmind2/shared/bundle/ruby/2.1.0/bin/rails:23:in `load'
	from /homa = Asset.new(Asset.last.attributes)
```

**Comment by rafaelfranca** [comment]
Could you create an reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by thomasharatyk** [comment]
I have a similar issue with [the changes introduced in 4.2.0][1], **the active record type cast and range check occurs before the model validation**. 

    class RangeTest < ActiveRecord::Base
        validates :count, numericality: { less_than: 100}
    end

The assignment of a value that isn't in the range of the `count` attribute throws an exception, even if it is supposed to be correctly handled in the model validation : 

    a = RangeTest.new
    a.count = 3_000_000_000

    RangeError: 3000000000 is out of range for ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer with limit 4
            from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/activerecord-4.2.0/lib/active_record/type/integer.rb:41:in `ensure_in_range'
            from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/activerecord-4.2.0/lib/active_record/type/integer.rb:34:in `cast_value'
            from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/activerecord-4.2.0/lib/active_record/type/value.rb:89:in `type_cast'

  [1]: http://metaskills.net/2015/01/06/activerecord-42s-type-casting/

**Comment by sgrif** [comment]
Yeah, this needs a reproduction script. This shouldn't ever happen with just hstore, and the stack trace provided implies that something else is going on with that model.

**Comment by sgrif** [comment]
@thomasharatyk Your issue is unrelated. In the future, you should open a new issue, rather than reporting in the comments for an existing one. In this case, however, I've already fixed it in https://github.com/rails/rails/commit/7c6f3938dee47f0932c2a1d4924adaebc25517ac

**Comment by sgrif** [comment]
This issue was likely fixed by that commit as well, but I'd like to get a reproduction script so that I can be sure.

**Comment by namor** [comment]
Couldn't recreate the problem in the reproduction script..   
Its definitely a bug on my end.. 

It seems there was a before_save that writes to an int4 column but it does't come out in the stack trace when it fails ...

Sorry for taking up your time guyss.

**Comment by sgrif** [comment]
Thank you for following up.
