### ISSUE TITLE
Count query grouped by association may raise a ActiveRecord::RecordNotFound exception

### ISSUE THREAD

**Issue by jplang** [rails/rails#18717]
When doing a count query grouped by an association, a ActiveRecord::RecordNotFound exception is raised if the result consists of a nil group only. This issue exists since the early versions of Rails (maybe 1.x or even before :-).

Here is a test case that illustrates the issue: https://gist.github.com/jplang/d4f6c0b74af13a105ce5

**Comment by jplang** [comment]
And here is the output:

```
  1) Error:
BugTest#test_group_result_with_nil_group_only:
ActiveRecord::RecordNotFound: Couldn't find Post without an ID
    c:/utils/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/
relation/finder_methods.rb:433:in `find_with_ids'
    c:/utils/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/
relation/finder_methods.rb:71:in `find'
    c:in `find'
    c:/utils/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/
core.rb:131:in `find'
    c:/utils/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/
relation/calculations.rb:324:in `execute_grouped_calculation'
    c:/utils/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/
relation/calculations.rb:219:in `perform_calculation'
    c:/utils/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/
relation/calculations.rb:127:in `calculate'
    c:/utils/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/
relation/calculations.rb:42:in `count'
    test.rb:48:in `test_group_result_with_nil_group_only'

1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
```
