### ISSUE TITLE
ActiveJob: RuntimeError: Circular dependency detected while autoloading constant Company

### ISSUE THREAD

**Issue by TrevorHinesley** [rails/rails#18725]
Ruby: 2.1.0
Rails: 4.2.0

I have three lines that run in succession inside a webhook controller, they are as follows:

```ruby
StripeMailer.stripe_connect_charge_party_receipt(payment).deliver_later if payment.party.email?
StripeMailer.stripe_connect_charge_succeeded(payment).deliver_later
StripeMailer.admin_stripe_connect_charge_succeeded(payment).deliver_later
```

I can run these one after another in an IRB or Pry console just fine. However, when they're triggered in succession from the controller, sometimes this happens:

```
StripeMailer#stripe_connect_charge_succeeded: processed outbound mail in 25.4ms
    [ActiveJob] [ActionMailer::DeliveryJob] [5c2a847c-d79a-4fe6-b2c1-62a092b58af5] Performed ActionMailer::DeliveryJob from SuckerPunch(mailers) in 25.68ms
    ActiveJob::QueueAdapters::SuckerPunchAdapter::JobWrapper crashed!
    RuntimeError: Circular dependency detected while autoloading constant Company
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:492:in `load_missing_constant'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:526:in `load_missing_constant'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:263:in `const_get'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:263:in `block in constantize'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259:in `each'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259:in `inject'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259:in `constantize'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:304:in `safe_constantize'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:572:in `safe_get'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:603:in `safe_constantize'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:154:in `block in compute_type'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:153:in `each'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:153:in `compute_type'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/reflection.rb:271:in `compute_class'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/reflection.rb:267:in `klass'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/reflection.rb:505:in `automatic_inverse_of'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/reflection.rb:494:in `block in inverse_name'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/reflection.rb:490:in `fetch'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/reflection.rb:490:in `inverse_name'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/reflection.rb:387:in `has_inverse?'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/reflection.rb:336:in `check_validity_of_inverse!'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/reflection.rb:331:in `check_validity!'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/associations/association.rb:25:in `initialize'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/associations.rb:161:in `new'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/associations.rb:161:in `association'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activerecord-4.2.0/lib/active_record/associations/builder/association.rb:115:in `company'
      /Users/Trevor/Work/myapp/myapp/app/models/user.rb:14:in `organization'
      /Users/Trevor/Work/myapp/myapp/app/models/bond.rb:20:in `organization'
      /Users/Trevor/Work/myapp/myapp/app/models/payment.rb:17:in `organization'
      /Users/Trevor/Work/myapp/myapp/app/mailers/stripe_mailer.rb:205:in `relevant_payment_emails'
      /Users/Trevor/Work/myapp/myapp/app/mailers/stripe_mailer.rb:54:in `stripe_connect_charge_succeeded'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:198:in `process_action'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in `process'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionmailer-4.2.0/lib/action_mailer/base.rb:596:in `block in process'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionmailer-4.2.0/lib/action_mailer/base.rb:593:in `process'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionmailer-4.2.0/lib/action_mailer/base.rb:584:in `initialize'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionmailer-4.2.0/lib/action_mailer/message_delivery.rb:25:in `new'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionmailer-4.2.0/lib/action_mailer/message_delivery.rb:25:in `__getobj__'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionmailer-4.2.0/lib/action_mailer/message_delivery.rb:34:in `message'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionmailer-4.2.0/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/actionmailer-4.2.0/lib/action_mailer/delivery_job.rb:10:in `perform'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activejob-4.2.0/lib/active_job/execution.rb:32:in `block in perform_now'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:338:in `block (2 levels) in simple'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activejob-4.2.0/lib/active_job/logging.rb:23:in `call'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activejob-4.2.0/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activejob-4.2.0/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activejob-4.2.0/lib/active_job/logging.rb:43:in `block in tag_logger'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activejob-4.2.0/lib/active_job/logging.rb:43:in `tag_logger'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activejob-4.2.0/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:436:in `instance_exec'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:436:in `block in make_lambda'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:337:in `call'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:337:in `block in simple'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_perform_callbacks'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activejob-4.2.0/lib/active_job/execution.rb:31:in `perform_now'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activejob-4.2.0/lib/active_job/execution.rb:21:in `execute'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/activejob-4.2.0/lib/active_job/queue_adapters/sucker_punch_adapter.rb:35:in `perform'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
      /Users/Trevor/.rvm/gems/ruby-2.1.0@myapp/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

This is not an open source application, so I can't post it. The line it's breaking on (`/Users/Trevor/Work/myapp/myapp/app/mailers/stripe_mailer.rb:205:in 'relevant_payment_emails'`) is here:

```ruby
[@payment.organization.owner.email, @payment.processor.email].uniq
```
 
And here are the relevant models' associations (and none of these associations are invalid or wrongly declared, they work fine everywhere else and outside of enqueueing, and even sometimes when queued).

payment.rb
```ruby
class Payment < ActiveRecord::Base
  belongs_to :bond
  belongs_to :party
  belongs_to :processor, class_name: "User", foreign_key: :processor_id
  delegate :organization, to: :bond
end
```

bond.rb
```ruby
class Bond < ActiveRecord::Base
  belongs_to :agent
  delegate :company, to: :agent
  delegate :organization, to: :agent
end
```

company.rb
```ruby
class Company < ActiveRecord::Base
  belongs_to :organization
  has_many :users
  has_many :agents
  has_many :bonds, through: :agents
  validates_presence_of :organization, :name
end
```

organization.rb
```ruby
class Organization < ActiveRecord::Base
  has_many :companies, dependent: :destroy
  has_many :agents, through: :companies
  has_many :office_managers, through: :companies
  belongs_to :owner, class_name: "User", foreign_key: :owner_id
  has_many :users, through: :companies
  has_many :parties
  has_many :bonds, through: :companies
  has_many :payments, through: :bonds
end
```

UPDATE:

Sometimes I'll get `Circular dependency detected while autoloading constant Bond` and it will fail here: `delegate :organization, to: :bond`, on the first association call. But again, ONLY in an enqueued ActiveJob. Maybe it's something with `delegate`?

**Comment by sgrif** [comment]
This is a thread safety issue with autoloading, which is well known. `config.eager_load = true` is required for threaded code.

**Comment by TrevorHinesley** [comment]
Apologies, I did plenty of searching and never once saw that. Thanks.
