### ISSUE TITLE
update or update_attributes gives me an undefined method error

### ISSUE THREAD

**Issue by lucianosousa** [rails/rails#18947]
Using the rails 4.2 here I'm receiving the following error:

```
Started PATCH "/users/1" for 127.0.0.1 at 2015-02-15 16:08:35 -0300
  ActiveRecord::SchemaMigration Load (0.6ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by UsersController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"1R/1+FXdNY4VVVagSBIbyGPD/+webQ5CsSsywsuotQdVeEMFhMZBxC1XyNyA8qu9RhsLPWiEeaTAgOe4X1NNPw==", "commit"=>"Update User", "user"=>{"name"=>"xxx", "email"=>"xx@xxx.xxx"}"id"=>"1"}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."name" ASC LIMIT 1  [["id", 1]]
   (0.3ms)  BEGIN
  SQL (0.4ms)  UPDATE "users" SET "name" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["name", "xxx"], ["updated_at", "2015-02-15 19:08:36.186214"], ["id", 1]]
   (13.9ms)  COMMIT
Completed 500  in 109ms

NoMethodError - undefined method `each' for nil:NilClass:
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/transaction.rb:100:in `ensure in commit_records'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/transaction.rb:100:in `commit_records'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/transaction.rb:157:in `commit'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/transaction.rb:179:in `commit_transaction'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/transaction.rb:198:in `within_new_transaction'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  activerecord (4.2.0) lib/active_record/transactions.rb:220:in `transaction'
  activerecord (4.2.0) lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
  activerecord (4.2.0) lib/active_record/persistence.rb:248:in `update'
  app/controllers/users_controller.rb:12:in `update'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:57:in `call'
  rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.0.3) lib/quiet_assets.rb:23:in `call_with_quiet_assets'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
  thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
  thin (1.5.1) lib/thin/connection.rb:54:in `process'
  thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.5) lib/eventmachine.rb:187:in `run'
  thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
  thin (1.5.1) lib/thin/server.rb:159:in `start'
  rack (1.6.0) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.0) lib/rack/server.rb:286:in `start'
  railties (4.2.0) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.0) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `<main>'
```

Just following this error, I found a problem here:

```
      def commit_records
        ite = records.uniq
        while record = ite.shift
          begin
            record.committed!
          rescue => e
            raise if ActiveRecord::Base.raise_in_transactional_callbacks
            record.logger.error(e) if record.respond_to?(:logger) && record.logger
          end
        end
      ensure
        ite.each do |i| #this is nil
          i.committed!(false)
        end
      end
```
I've 3 has many relationships in this model, and always when I just comment these lines it works. Of course I do not want to do this, then, I need to now it's a real bug or another problem in my code.

Cheers

**Comment by sgrif** [comment]
It's likely a bug in your code. The only reason `ite` would be `nil` is if `records.uniq` raised an exception. When you comment out the `ensure` block, do you get another exception?

**Comment by lucianosousa** [comment]
```
TypeError - no implicit conversion of String into Integer:
```

**Comment by sgrif** [comment]
Going to need more information than that. A stack trace would be a good place to start.

**Comment by lucianosousa** [comment]
```
TypeError: no implicit conversion of String into Integer
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:70:in `uniq'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:70:in `rollback_records'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:145:in `rollback'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:177:in `rollback_transaction'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `rescue in within_new_transaction'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:199:in `within_new_transaction'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/activerecord-4.2.0/lib/active_record/persistence.rb:248:in `update'
	from (irb):2
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/luciano/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
```

I'm just following these errors, but my code looks really OK.

**Comment by sgrif** [comment]
The only reason that you'd be receiving that error is if the `hash` method on your model was returning a string. Have you by chance defined a method called `hash` on any of your models, or have a column/association/etc with that name?

**Comment by lucianosousa** [comment]
Yes man!
It's a legacy code I'm working. I removed this and everything is fine.
Now I need to know what to do with this method! ;)

Thank's so much!
