### ISSUE TITLE
Connection left open after Application.initialize!

### ISSUE THREAD

**Issue by jkuchta** [rails/rails#18953]
I'm supporting a rails application using jruby and receiving an abandoned connection trace from Tomcat shortly after startup. I created a sample rails app (barebones) and adding some debugging statements to ActiveRecord and a stack trace from the def checkout method. It looks like a connection is checked out but never checked back in (after initialization finishes).

```
vagrant@precise64:/tmp/jeff$ jruby -S trinidad --threadsafe
Deploying from /tmp/jeff as /

Initializing ProtocolHandler ["http-bio-127.0.0.1-3000"]
jruby 1.7.9 (1.9.3p392) 2013-12-06 87b108a on OpenJDK 64-Bit Server VM 1.7.0_55-b14 [linux-amd64]
using a shared (threadsafe!) runtime
Connecting to database specified by database.yml

***def checkout (activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb)****

/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:241:in `backtrace'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:241:in `checkout'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:103:in `connection'
/home/vagrant/.rvm/rubies/jruby-1.7.9/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `connection'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:418:in `retrieve_connection'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activerecord-3.2.19/lib/active_record/model_schema.rb:310:in `clear_cache!'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activerecord-3.2.19/lib/active_record/railtie.rb:103:in `_callback_before_7'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:421:in `_run__1493766132__prepare__781975967__callbacks'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:390:in `_run_prepare_callbacks'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/actionpack-3.2.19/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/actionpack-3.2.19/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/railties-3.2.19/lib/rails/application/finisher.rb:47:in `Finisher'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `run_initializers'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
/home/vagrant/.rvm/gems/jruby-1.7.9/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
/tmp/jeff/config/environment.rb:5:in `(root)'
file:/home/vagrant/.rvm/gems/jruby-1.7.9/gems/jruby-rack-1.1.13.3/lib/jruby-rack-1.1.13.3.jar!/jruby/rack/rails/environment3.rb:1:in `require'
file:/home/vagrant/.rvm/gems/jruby-1.7.9/gems/jruby-rack-1.1.13.3/lib/jruby-rack-1.1.13.3.jar!/jruby/rack/rails/environment3.rb:1:in `(root)'
file:/home/vagrant/.rvm/gems/jruby-1.7.9/gems/jruby-rack-1.1.13.3/lib/jruby-rack-1.1.13.3.jar!/jruby/rack/rails/environment3.rb:25:in `load_environment'
file:/home/vagrant/.rvm/gems/jruby-1.7.9/gems/jruby-rack-1.1.13.3/lib/jruby-rack-1.1.13.3.jar!/jruby/rack/rails_booter.rb:79:in `load_environment'

*** Received conn from def checkout #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x6ad6e3d9>***
```

**Comment by jkuchta** [comment]
I've opened a pull request for my suggested fix (https://github.com/rails/rails/pull/18955).

**Comment by rafaelfranca** [comment]
Does it happen with Rails 4? Rails 3 is not supported anymore.

**Comment by jkuchta** [comment]
I'm not sure, I know the connection libraries are quite a bit different between rails 3 and 4. I patched 3-2-stable, even though it's no longer supported it seems to still be somewhat maintained with new 3.2.x releases.

**Comment by jkuchta** [comment]
@rafaelfranca I've just tested Rails 4.2, the issue does not occur - the initialization code is much better.

**Comment by eileencodes** [comment]
@jkuchta thanks for getting back to us that this is not an issue in Rails 4 anymore. I'm going to close this. :smile:
