### ISSUE TITLE
Version bump of ActiveRecord gem needed for Ruby 2.2

### ISSUE THREAD

**Issue by mattheworiordan** [rails/rails#18991]
A lot of people are experiencing the following error with Ruby 2.2 and this ActiveRecord 3.2.21:
```
NoMethodError: undefined method `name' for nil:NilClass
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/has_many_association.rb:58:in `cached_counter_attribute_name'
```

After specifying the `3-2-stable` branch in my production environment Gemfile, the issue has since gone away, so I believe this issue is fixed.  I therefore recommend you bump the tiny / patch version so that people get this fix with Ruby 2.2.

Here is the issue in the wild:

* https://github.com/activescaffold/active_scaffold/issues/380
* http://stackoverflow.com/questions/23568084/create-with-has-many-through-association-gets-nomethoderror-undefined-method-n
* http://stackoverflow.com/questions/28061409/weird-issue-has-many-through-association-in-updated-rails

I was unable to recreate the issue locally, but could in production, here is the log:

```
irb(main):006:0> s.destroy
  Theme Load (2.5ms)  SELECT "themes".* FROM "themes" WHERE "themes"."id" = 13477 LIMIT 1
  Backlog Load (2.2ms)  SELECT "backlogs".* FROM "backlogs" WHERE "backlogs"."id" = 3133 LIMIT 1
   (1.9ms)  BEGIN
  Story Load (4.1ms)  SELECT "stories".* FROM "stories" WHERE "stories"."id" = $1 LIMIT 1  [["id", 37587]]
  SprintStory Load (5.5ms)  SELECT "sprint_stories".* FROM "sprint_stories" WHERE "sprint_stories"."story_id" = 37587 LIMIT 1
  AcceptanceCriterion Load (2.5ms)  SELECT "acceptance_criteria".* FROM "acceptance_criteria" WHERE "acceptance_criteria"."story_id" = 37587 ORDER BY position
  Theme Load (2.5ms)  SELECT "themes".* FROM "themes" WHERE "themes"."id" = 13477 LIMIT 1
  Backlog Load (2.2ms)  SELECT "backlogs".* FROM "backlogs" WHERE "backlogs"."id" = 3133 LIMIT 1
  AcceptanceCriterion Load (6.0ms)  SELECT "acceptance_criteria".* FROM "acceptance_criteria" WHERE "acceptance_criteria"."id" = $1 LIMIT 1  [["id", 98120]]
  Story Load (8.7ms)  SELECT "stories".* FROM "stories" WHERE "stories"."id" = 37587 LIMIT 1
  SprintStory Load (4.1ms)  SELECT "sprint_stories".* FROM "sprint_stories" WHERE "sprint_stories"."story_id" = 37587 LIMIT 1
  SQL (7.0ms)  DELETE FROM "acceptance_criteria" WHERE "acceptance_criteria"."id" = $1  [["id", 98120]]
  SQL (5.0ms)  UPDATE "acceptance_criteria" SET position = (position - 1) WHERE ("acceptance_criteria"."story_id" = 37587 AND position > 1)
  AcceptanceCriterion Load (2.0ms)  SELECT "acceptance_criteria".* FROM "acceptance_criteria" WHERE "acceptance_criteria"."id" = $1 LIMIT 1  [["id", 98121]]
  Story Load (2.1ms)  SELECT "stories".* FROM "stories" WHERE "stories"."id" = 37587 LIMIT 1
  SprintStory Load (2.1ms)  SELECT "sprint_stories".* FROM "sprint_stories" WHERE "sprint_stories"."story_id" = 37587 LIMIT 1
  SQL (1.9ms)  DELETE FROM "acceptance_criteria" WHERE "acceptance_criteria"."id" = $1  [["id", 98121]]
  SQL (1.9ms)  UPDATE "acceptance_criteria" SET position = (position - 1) WHERE ("acceptance_criteria"."story_id" = 37587 AND position > 1)
   (6.7ms)  ROLLBACK
NoMethodError: undefined method `name' for nil:NilClass
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/has_many_association.rb:58:in `cached_counter_attribute_name'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/has_many_association.rb:81:in `inverse_updates_counter_cache?'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/has_many_association.rb:91:in `delete_records'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/collection_association.rb:466:in `remove_records'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/collection_association.rb:459:in `block in delete_or_destroy'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/collection_association.rb:149:in `block in transaction'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/collection_association.rb:148:in `transaction'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/collection_association.rb:459:in `delete_or_destroy'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/collection_association.rb:231:in `delete'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/collection_association.rb:157:in `delete_all'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/collection_proxy.rb:46:in `delete_all'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/builder/has_many.rb:42:in `block in define_destroy_dependency_method'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:429:in `_run__3549756381873116311__destroy__3268714506285921020__callbacks'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_destroy_callbacks'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:254:in `destroy'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:254:in `block in destroy'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
	from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:254:in `destroy'
	from /app/lib/modules/lockable.rb:9:in `destroy'
	from (irb):6
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-3.2.21/lib/rails/commands/console.rb:47:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-3.2.21/lib/rails/commands/console.rb:8:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-3.2.21/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from scriBacklog.find(3133)^Cb(main):007:0> theme = b.themes.first
```

**Comment by rafaelfranca** [comment]
Rails 3 is not supported anymore. 3-2-stable branch is working with Ruby 2.2 but we don't promise any new release

**Comment by mattheworiordan** [comment]
But it's not working with the current Gem version which almost everyone relies on. I'm not sure I follow what you mean, are you saying no more patch releases will be made even though commits are indeed still being added to the branch?

**Comment by rafaelfranca** [comment]
Yes. There is no guarantee that will be a patch release for Rails 3
anymore.

**Comment by stratigos** [comment]
Just ran into this issue today. Thanks for clarifying, I may try to resolve this with `3-2-stable`.
