### ISSUE TITLE
activerecord is unable to load schema.rb into postrges when dumped on mysql with a boolean

### ISSUE THREAD

**Issue by grosser** [rails/rails#19080]
I ran a migration:

```
add_column :users, :foo, :boolean, default: false, null: false
```

and now my schema.rb reads:

```
    t.boolean  "foo", limit: 1, default: false, null: false
```

which loads fine in mysql, but in postgres I end up with this:

```
PG::SyntaxError: ERROR:  syntax error at or near "("
LINE 1: SELECT 'boolean(1)'::regtype::oid
               ^
CONTEXT:  invalid type name "boolean(1)"
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:393:in `lookup_cast_type'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:120:in `type_for_column'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:33:in `type_for_column'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:97:in `quote_value'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:84:in `add_column_options!'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:25:in `add_column_options!'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:33:in `visit_ColumnDefinition'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:8:in `visit_ColumnDefinition'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:40:in `block in visit_TableDefinition'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:40:in `map'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:40:in `visit_TableDefinition'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:206:in `create_table'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/home/travis/build/zendesk/samson/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/home/travis/build/zendesk/samson/db/schema.rb:135:in `block in <top (required)>'
```

**Comment by morgoth** [comment]
@grosser I think it was fixed in https://github.com/rails/rails/pull/19066

**Comment by rafaelfranca** [comment]
Yes.

**Comment by grosser** [comment]
sweet, thanks!
