### ISSUE TITLE
MySQL 5.7.6-m16 default optimizer_switch derived_merge=on causes Error: You can't specify target table 'pets' for update in FROM clause:

### ISSUE THREAD

**Issue by yahonda** [rails/rails#19281]
[MySQL 5.7.6-m16](http://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-6.html) has been released. 
Since upgrading my environments to this version, some of mysql and mysql2 test cases get errors.

These errors can be resolved by setting `optimizer_switch=derived_merge=off` in /etc/my.cnf.
Then I'm not sure these errors can be addressed in Rails yet.

- Testcases
```ruby
for i in mysql mysql2
do 
echo $i
ARCONN=$i ruby -Itest test/cases/scoping/relation_scoping_test.rb -n test_delete_all_default_scope_filters_on_joins
ARCONN=$i ruby -Itest test/cases/persistence_test.rb -n /test_delete_all_with_joins_and_where_part_is/
done
```

- Environments
```
Server version: 5.7.6-m16 MySQL Community Server (GPL)
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
$ gem list |grep mysql
mysql (2.9.1)
mysql2 (0.3.18)
```

- Errors
```ruby
mysql
Using mysql
Run options: -n test_delete_all_default_scope_filters_on_joins --seed 55970

# Running:

E

Finished in 0.121025s, 8.2627 runs/s, 8.2627 assertions/s.

  1) Error:
RelationScopingTest#test_delete_all_default_scope_filters_on_joins:
ActiveRecord::StatementInvalid: Mysql::Error: You can't specify target table 'developers' for update in FROM clause: DELETE FROM `developers` WHERE `developers`.`id` IN (SELECT id FROM (SELECT `developers`.`id` FROM `developers` INNER JOIN `developers_projects` ON `developers_projects`.`developer_id` = `developers`.`id` INNER JOIN `projects` ON `projects`.`id` = `developers_projects`.`project_id` WHERE `projects`.`name` = ?) __active_record_temp)
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:405:in `prepare'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:405:in `block in exec_stmt'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:493:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:487:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:400:in `exec_stmt'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:257:in `exec_query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:382:in `exec_delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:119:in `delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:509:in `delete_all'
    /home/yahonda/git/rails/activerecord/lib/active_record/querying.rb:8:in `delete_all'
    test/cases/scoping/relation_scoping_test.rb:206:in `test_delete_all_default_scope_filters_on_joins'

1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
Using mysql
Run options: -n /test_delete_all_with_joins_and_where_part_is/ --seed 35938

# Running:

EE

Finished in 0.135492s, 14.7610 runs/s, 14.7610 assertions/s.

  1) Error:
PersistenceTest#test_delete_all_with_joins_and_where_part_is_hash:
ActiveRecord::StatementInvalid: Mysql::Error: You can't specify target table 'pets' for update in FROM clause: DELETE FROM `pets` WHERE `pets`.`pet_id` IN (SELECT pet_id FROM (SELECT `pets`.`pet_id` FROM `pets` INNER JOIN `toys` ON `toys`.`pet_id` = `pets`.`pet_id` WHERE `toys`.`name` = ?) __active_record_temp)
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:405:in `prepare'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:405:in `block in exec_stmt'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:493:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:487:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:400:in `exec_stmt'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:257:in `exec_query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:382:in `exec_delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:119:in `delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:509:in `delete_all'
    test/cases/persistence_test.rb:87:in `test_delete_all_with_joins_and_where_part_is_hash'


  2) Error:
PersistenceTest#test_delete_all_with_joins_and_where_part_is_not_hash:
ActiveRecord::StatementInvalid: Mysql::Error: You can't specify target table 'pets' for update in FROM clause: DELETE FROM `pets` WHERE `pets`.`pet_id` IN (SELECT pet_id FROM (SELECT `pets`.`pet_id` FROM `pets` INNER JOIN `toys` ON `toys`.`pet_id` = `pets`.`pet_id` WHERE (toys.name = 'Bone')) __active_record_temp)
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:339:in `query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:339:in `block in exec_without_stmt'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:493:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:487:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:338:in `exec_without_stmt'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:255:in `exec_query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:382:in `exec_delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:119:in `delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:509:in `delete_all'
    test/cases/persistence_test.rb:95:in `test_delete_all_with_joins_and_where_part_is_not_hash'

2 runs, 2 assertions, 0 failures, 2 errors, 0 skips
mysql2
Using mysql2
Run options: -n test_delete_all_default_scope_filters_on_joins --seed 350

# Running:

E

Finished in 0.137439s, 7.2759 runs/s, 7.2759 assertions/s.

  1) Error:
RelationScopingTest#test_delete_all_default_scope_filters_on_joins:
ActiveRecord::StatementInvalid: Mysql2::Error: You can't specify target table 'developers' for update in FROM clause: DELETE FROM `developers` WHERE `developers`.`id` IN (SELECT id FROM (SELECT `developers`.`id` FROM `developers` INNER JOIN `developers_projects` ON `developers_projects`.`developer_id` = `developers`.`id` INNER JOIN `projects` ON `projects`.`id` = `developers_projects`.`project_id` WHERE `projects`.`name` = 'Active Controller') __active_record_temp)
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:375:in `query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:375:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:493:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:487:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:375:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:214:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `exec_delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:119:in `delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:509:in `delete_all'
    /home/yahonda/git/rails/activerecord/lib/active_record/querying.rb:8:in `delete_all'
    test/cases/scoping/relation_scoping_test.rb:206:in `test_delete_all_default_scope_filters_on_joins'

1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
Using mysql2
Run options: -n /test_delete_all_with_joins_and_where_part_is/ --seed 61229

# Running:

EE

Finished in 0.135806s, 14.7269 runs/s, 14.7269 assertions/s.

  1) Error:
PersistenceTest#test_delete_all_with_joins_and_where_part_is_hash:
ActiveRecord::StatementInvalid: Mysql2::Error: You can't specify target table 'pets' for update in FROM clause: DELETE FROM `pets` WHERE `pets`.`pet_id` IN (SELECT pet_id FROM (SELECT `pets`.`pet_id` FROM `pets` INNER JOIN `toys` ON `toys`.`pet_id` = `pets`.`pet_id` WHERE `toys`.`name` = 'Bone') __active_record_temp)
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:375:in `query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:375:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:493:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:487:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:375:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:214:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `exec_delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:119:in `delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:509:in `delete_all'
    test/cases/persistence_test.rb:87:in `test_delete_all_with_joins_and_where_part_is_hash'


  2) Error:
PersistenceTest#test_delete_all_with_joins_and_where_part_is_not_hash:
ActiveRecord::StatementInvalid: Mysql2::Error: You can't specify target table 'pets' for update in FROM clause: DELETE FROM `pets` WHERE `pets`.`pet_id` IN (SELECT pet_id FROM (SELECT `pets`.`pet_id` FROM `pets` INNER JOIN `toys` ON `toys`.`pet_id` = `pets`.`pet_id` WHERE (toys.name = 'Bone')) __active_record_temp)
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:375:in `query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:375:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:493:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:487:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:375:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:214:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `exec_delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:119:in `delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:509:in `delete_all'
    test/cases/persistence_test.rb:95:in `test_delete_all_with_joins_and_where_part_is_not_hash'

2 runs, 2 assertions, 0 failures, 2 errors, 0 skips
```

- They reproduce when `optimizer_switch=derived_merge=on`
```sql
optimizer_switch=derived_merge=on


mysql> SELECT @@optimizer_switch\G
*************************** 1. row ***************************
@@optimizer_switch: index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,engine_condition_pushdown=on,index_condition_pushdown=on,mrr=on,mrr_cost_based=on,block_nested_loop=on,batched_key_access=off,materialization=on,semijoin=on,loosescan=on,firstmatch=on,subquery_materialization_cost_based=on,use_index_extensions=on,condition_fanout_filter=on,derived_merge=on
1 row in set (0.00 sec)

mysql>
```

- They do NOT reproduce by setting `optimizer_switch=derived_merge=off`
```sql
mysql> SELECT @@optimizer_switch\G
*************************** 1. row ***************************
@@optimizer_switch: index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,engine_condition_pushdown=on,index_condition_pushdown=on,mrr=on,mrr_cost_based=on,block_nested_loop=on,batched_key_access=off,materialization=on,semijoin=on,loosescan=on,firstmatch=on,subquery_materialization_cost_based=on,use_index_extensions=on,condition_fanout_filter=on,derived_merge=off
1 row in set (0.00 sec)

mysql>
```

**Comment by morgo** [comment]
@yahonda did you mind filing a bug on bugs.mysql.com?  This looks like a case that we would need to either fix or document as an incompatibility for upgrades to 5.7.

**Comment by yahonda** [comment]
@morgo Sure. Let me create a bug report to bugs.mysql.com. Will update the bug# when it is created.

**Comment by yahonda** [comment]
@morgo https://bugs.mysql.com/bug.php?id=76259 has been opened.

**Comment by morgo** [comment]
Thanks!  I've verified it on the MySQL side.

**Comment by morgo** [comment]
The developer has responded that this behavior will be documented as intentional.  This means that the issue should be addressed in rails, as the initial issue description suggests.

**Comment by yahonda** [comment]
@morgo Thanks for the update. Also I've checked https://bugs.mysql.com/bug.php?id=76259 
I understand this is an expected behavior in MySQL 5.7.6 (and later).

Quote from mysql bug#76259.
```
Possible workarounds:

- Use optimizer_switch='derived_merge=off';

- Force the derived table to be materialized, e.g by adding DISTINCT after SELECT, or adding a LIMIT.
```
Let me discuss the second workaround first.
- Current SQL which cause `You can't specify target table` error.

```sql
DELETE FROM developers WHERE developers.id IN (SELECT id FROM (SELECT developers.id FROM developers INNER JOIN developers_projects ON developers_projects.developer_id = developers.id INNER JOIN projects ON projects.id =  developers_projects.project_id WHERE projects.name = 'Active Controller') __active_record_temp);
```

- Modified SQL to surpress error adding DISTINCT in the subquery

```sql
DELETE FROM developers WHERE developers.id IN (SELECT id FROM (SELECT DISTINCT developers.id FROM developers INNER JOIN developers_projects ON developers_projects.developer_id = developers.id INNER JOIN projects ON projects.id =  developers_projects.project_id WHERE projects.name = 'Active Controller') __active_record_temp);
```

This workaround is easy if writing (raw) sql statent directly, but this sql statement is generated by Arel and ActiveRecord. It looks hard to add DISTINCT statement within subquery. Since each statement do not know if it will be executed as subquery in advance when each query statement generated. (I may be wrong.)

Then I'm thinking about the first workaround. To execute `SET optimizer_switch='derived_merge=off';` if the MySQL version is 5.7.6 or higher. I'm going to prepare a pull request.


@rafaelfranca 
Wanted to know your opinion about this since you commit this method. https://github.com/rails/rails/commit/6f6c2909dcf32fca71ccc645a36469864b97894a

**Comment by rafaelfranca** [comment]
I think we know about the subselect in that code. Can't we just use distinct?

**Comment by yahonda** [comment]
@rafaelfranca You are right. Thanks for the suggestion. We know which sub-sub-query needs distinct. Opened a pull request #19359
