### ISSUE TITLE
"undefined local variable or method `hello=' when Rails 4.2 and ruby 2.2.1 used

### ISSUE THREAD

**Issue by yahonda** [rails/rails#19297]
One test at `4-2-stable` branch always get failure when ruby 2.2.1 is used.

```ruby
$ cd activerecord
$ ruby -Itest test/cases/attribute_methods_test.rb
Using sqlite3
Run options: --seed 53001

# Running:

.............F.....................................................................

Finished in 1.463643s, 56.7078 runs/s, 277.3901 assertions/s.

  1) Failure:
AttributeMethodsTest#test_bulk_update_raise_unknown_attribute_error [test/cases/attribute_methods_test.rb:739]:
[ActiveRecord::UnknownAttributeError] exception expected, not
Class: <NameError>
Message: <"undefined local variable or method `hello=' for #<Topic:0x00000002a8cad0>">
---Backtrace---
/home/yahonda/git/rails/activemodel/lib/active_model/attribute_methods.rb:433:in `method_missing'
/home/yahonda/git/rails/activerecord/lib/active_record/attribute_assignment.rb:54:in `public_send'
/home/yahonda/git/rails/activerecord/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
/home/yahonda/git/rails/activerecord/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
/home/yahonda/git/rails/activerecord/lib/active_record/attribute_assignment.rb:35:in `each'
/home/yahonda/git/rails/activerecord/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
/home/yahonda/git/rails/activerecord/lib/active_record/core.rb:560:in `init_attributes'
/home/yahonda/git/rails/activerecord/lib/active_record/core.rb:281:in `initialize'
/home/yahonda/git/rails/activerecord/lib/active_record/inheritance.rb:61:in `new'
/home/yahonda/git/rails/activerecord/lib/active_record/inheritance.rb:61:in `new'
test/cases/attribute_methods_test.rb:740:in `block in test_bulk_update_raise_unknown_attribute_error'
---------------

83 runs, 406 assertions, 1 failures, 0 errors, 0 skips
$
```

It reproduces when ALL of these conditions are satisfied:

- Rails 4.2 from v4.2.0 to the latest 4-2-stable branch whose latest commit is 6f158c9293adb3e660d0c7a8180dfa79de81881b)

- Use Ruby 2.2.1
```ruby
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```
- Executed entire `rake test_<adapter>` such as `rake test_sqlite3` or 
`ruby -Itest test/cases/attribute_methods_test.rb`

Then it does not reproduce when:

- Use ruby 2.2.0 
```
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
```

- Use Rails `master` branch

- Use -n option to specify the `test_bulk_update_raise_unknown_attribute_error` test
```ruby
$ ruby -Itest test/cases/attribute_methods_test.rb -n test_bulk_update_raise_unknow
```

**Comment by rafaelfranca** [comment]
It is something related to the fixture loading code. If you change this line to https://github.com/rails/rails/blob/6f158c9293adb3e660d0c7a8180dfa79de81881b/activerecord/test/cases/attribute_methods_test.rb#L32 `t = Topic.new` everything pass.

**Comment by senny** [comment]
I'll have a look at it.

**Comment by senny** [comment]
This was caused by a bug in Ruby 2.2.1. I opened an issue on the ruby-lang tracker: https://bugs.ruby-lang.org/issues/10969 and pushed a temporary fix to `4-2-stable`.

**Comment by yahonda** [comment]
Thanks. Confirmed it is fixed and started watching https://bugs.ruby-lang.org/issues/10969 .
