### ISSUE TITLE
Getting "RuntimeError: @routes is nil" for static pages

### ISSUE THREAD

**Issue by jasnow** [rails/rails#19354]
On March 3, 2015, I created a Rails 5.0/alpha version of Rails Tutorial's "sample_app"
app based on my Rails 4.2 version (4 lines changed).
    
The repo is at https://bitbucket.org/jasnow/sample_app_5_0_rt .
    
The test suite runs cleanly with the "master" branch.

But the test suite broke two days ago.
    
To reproduce the issue:
  1. Start with the "master" branch
  2. Run "bundler update rails". I created "runtime-error" branch to demo the issue.
  3. Run "rake" and you get:
```
    Progress: |[0m[1000D[KERROR["test_should_get_about", StaticPagesControllerTest, 0.097099426]
     test_should_get_about#StaticPagesControllerTest (0.10s)
    RuntimeError:         RuntimeError: @routes is nil: make sure you set it in your test's setup method.
                test/controllers/static_pages_controller_test.rb:21:in `block in <class:StaticPagesControllerTest>'
            test/controllers/static_pages_controller_test.rb:21:in `block in <class:StaticPagesControllerTest>'
    
    ======================[0m[1000D[KERROR["test_should_get_home", StaticPagesControllerTest, 0.101805958]
     test_should_get_home#StaticPagesControllerTest (0.10s)
    RuntimeError:         RuntimeError: @routes is nil: make sure you set it in your test's setup method.
                test/controllers/static_pages_controller_test.rb:9:in `block in <class:StaticPagesControllerTest>'
            test/controllers/static_pages_controller_test.rb:9:in `block in <class:StaticPagesControllerTest>'
    
    [0m[1000D[KERROR["test_should_get_help", StaticPagesControllerTest, 0.106120407]
     test_should_get_help#StaticPagesControllerTest (0.11s)
    RuntimeError:         RuntimeError: @routes is nil: make sure you set it in your test's setup method.
                test/controllers/static_pages_controller_test.rb:15:in `block in <class:StaticPagesControllerTest>'
            test/controllers/static_pages_controller_test.rb:15:in `block in <class:StaticPagesControllerTest>'
    
    [0m[1000D[KERROR["test_should_get_contact", StaticPagesControllerTest, 0.110265348]
     test_should_get_contact#StaticPagesControllerTest (0.11s)
    RuntimeError:         RuntimeError: @routes is nil: make sure you set it in your test's setup method.
                test/controllers/static_pages_controller_test.rb:27:in `block in <class:StaticPagesControllerTest>'
            test/controllers/static_pages_controller_test.rb:27:in `block in <class:StaticPagesControllerTest>'

    ================================================================|
    
    Finished in 0.11275s
    4 tests, 0 assertions, 0 failures, 4 errors, 0 skips
    [Minitest results] 4 tests
```
 5. Here is the "git diff" output for the "runtime-error" branch:
```
    diff --git a/Gemfile.lock b/Gemfile.lock
    index eeee582..ad9949f 100644
    --- a/Gemfile.lock
    +++ b/Gemfile.lock
    @@ -6,7 +6,7 @@ GIT
     
     GIT
       remote: git://github.com/rails/rails.git
    -  revision: 4e7217027f1933d5860ba459b3d23f454272f709
    +  revision: a5a4b56029f1a83cfc81852f8ca76f9161abcbaa
       specs:
         actionmailer (5.0.0.alpha)
           actionpack (= 5.0.0.alpha)
    @@ -20,13 +20,13 @@ GIT
           rack (~> 1.6)
           rack-test (~> 0.6.3)
           rails-dom-testing (~> 1.0, >= 1.0.5)
    -      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    +      rails-html-sanitizer (~> 1.0, >= 1.0.2)
         actionview (5.0.0.alpha)
           activesupport (= 5.0.0.alpha)
           builder (~> 3.1)
           erubis (~> 2.7.0)
           rails-dom-testing (~> 1.0, >= 1.0.5)
    -      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    +      rails-html-sanitizer (~> 1.0, >= 1.0.2)
         activejob (5.0.0.alpha)
           activesupport (= 5.0.0.alpha)
           globalid (>= 0.3.0)
    @@ -163,7 +163,7 @@ GEM
           activesupport (>= 4.2.0.beta, < 5.0)
           nokogiri (~> 1.6.0)
           rails-deprecated_sanitizer (>= 1.0.1)
    -    rails-html-sanitizer (1.0.1)
    +    rails-html-sanitizer (1.0.2)
           loofah (~> 2.0)
         rails_12factor (0.0.3)
           rails_serve_static_assets
    @@ -200,7 +200,7 @@ GEM
           sprockets (>= 2.8, < 4.0)
         sqlite3 (1.3.10)
         thor (0.19.1)
    -    thread_safe (0.3.4)
    +    thread_safe (0.3.5)
         tilt (1.4.1)
         timers (4.0.1)
           hitimes
```
EOF

**Comment by jasnow** [comment]
Fixed the **runtime-error" branch by rebuilding Gemfile.lock file and pushing branch to Github.

**Comment by kaspth** [comment]
@jasnow does this mean you fixed your issue? If so you can go ahead and close this :heart:

**Comment by jasnow** [comment]
No, the "main" branch shows the eariler working code and the "runtime-error" branch shows the updated/newer code that triggered the above error messages during a "rake" run.

**Comment by kaspth** [comment]
> Fixed the **runtime-error" branch by rebuilding Gemfile.lock file and pushing branch to Github.

Then what does this mean? Was the branch unable to demonstrate the error?

**Comment by jonatack** [comment]
This issue appears to be related to 044f9ab7a.

**Comment by jonatack** [comment]
@jasnow try using `setup do` instead of `def setup` in StaticPagesControllerTest.

**Comment by jasnow** [comment]
Did @jonatack change and now "rake" run is back to green. Also added comment to https://github.com/rails/rails/commit/044f9ab7a4d6646ddce4560bb83b58cdc0baa751. THANKS.

**Comment by jonatack** [comment]
@jasnow Thanks for the bug report. The commit was reverted and `def setup` works again.

**Comment by jasnow** [comment]
I undid my change to my repos and they work - verified.
