### ISSUE TITLE
enum nil value casts to empty string:  PG::InvalidTextRepresentation ERROR: invalid input value for enum: ""

### ISSUE THREAD

**Issue by afdev82** [rails/rails#19389]
I saw [here](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/postgresql/oid/enum.rb) that you cast the enum to string, but if the value is nil I get an empty string, that usually is not a enum value, so I ge the error from PG.

I extended the method to be:  
```ruby
def type_cast(value)
   unless value.nil?
     value.to_s
   end
end
```
It's ok?

**Comment by arthurnn** [comment]
Can you write a broken test to better illustrate the error you are having?
Seems like we missed the `if` check indeed, but we need to simulate the error before fixing it.
thanks

**Comment by edwinv** [comment]
I'm experiencing the same issue: when a enum can be `null` in the database, ActiveRecord makes it impossible to reset to a `null` value when the value was present first.

Gist to reproduce: https://gist.github.com/edwinv/5a9aafcb4d37e253784b

This throws this exception:

```
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input value for enum post_types: ""
: UPDATE "posts" SET "post_type" = $1 WHERE "posts"."id" = $2
    .../activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
    .../activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
    .../activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
    .../activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    .../activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
    .../activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
    .../activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
    .../activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:173:in `exec_delete'
    .../activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:114:in `update'
    .../activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
    .../activerecord-4.2.0/lib/active_record/relation.rb:88:in `_update_record'
    .../activerecord-4.2.0/lib/active_record/persistence.rb:512:in `_update_record'
    .../activerecord-4.2.0/lib/active_record/locking/optimistic.rb:70:in `_update_record'
    .../activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:123:in `_update_record'
    .../activerecord-4.2.0/lib/active_record/callbacks.rb:310:in `block in _update_record'
    .../activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
    .../activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
    .../activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_update_callbacks'
    .../activerecord-4.2.0/lib/active_record/callbacks.rb:310:in `_update_record'
    .../activerecord-4.2.0/lib/active_record/timestamp.rb:70:in `_update_record'
    .../activerecord-4.2.0/lib/active_record/persistence.rb:501:in `create_or_update'
    .../activerecord-4.2.0/lib/active_record/callbacks.rb:302:in `block in create_or_update'
    .../activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
    .../activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
    .../activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_save_callbacks'
    .../activerecord-4.2.0/lib/active_record/callbacks.rb:302:in `create_or_update'
    .../activerecord-4.2.0/lib/active_record/persistence.rb:120:in `save'
    .../activerecord-4.2.0/lib/active_record/validations.rb:37:in `save'
    .../activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:21:in `save'
    .../activerecord-4.2.0/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
    .../activerecord-4.2.0/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
    .../activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    .../activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
    .../activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    .../activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
    .../activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
    .../activerecord-4.2.0/lib/active_record/transactions.rb:286:in `block in save'
    .../activerecord-4.2.0/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
    .../activerecord-4.2.0/lib/active_record/transactions.rb:285:in `save'
    .../activerecord-4.2.0/lib/active_record/persistence.rb:239:in `update_attribute'
    bugreport.rb:39:in `test_enum_null'
```

ActiveRecord should not typecast and set the value to `null` in this case.

**Comment by sgrif** [comment]
Backported in 67470f9

**Comment by afdev82** [comment]
Thanks!

**Comment by edwinv** [comment]
This issue is still present in the last version of Rails. I've updated the gist with the code to reproduce:

https://gist.github.com/edwinv/5a9aafcb4d37e253784b

**Comment by edwinv** [comment]
Correction: Rails 4.2.4 works like a charm!
