### ISSUE TITLE
ActiveRecord: stack level too deep when certain conditions are present

### ISSUE THREAD

**Issue by mdesantis** [rails/rails#19409]
The issue is present on ActiveRecord 4.1.9, 4.2.0, master.

### Conditions

1. The model has a polymorphic `has_many` association
2. The model defines a default scope with `def self.default_scope` (and not `default_scope { }`)
3. The model defines a class method which calls `all.inspect`
4. There is at least one record with at least one associated record 
5. A query including the association is performed
6. The method defined at point 3. is called against the returned relation

### Issue

A `SystemStackError: stack level too deep` is raised:

```
Finished in 0.586922s, 1.7038 runs/s, 0.0000 assertions/s.

  1) Error:
IssueTest#test_issue:
SystemStackError: stack level too deep
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/runtime_registry.rb:18:in `connection_id'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/connection_handling.rb:91:in `connection_id'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:439:in `current_connection_id'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:261:in `connection'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:560:in `retrieve_connection'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/connection_handling.rb:87:in `connection'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/model_schema.rb:216:in `table_exists?'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/core.rb:215:in `inspect'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activemodel/lib/active_model/attribute_methods.rb:219:in `inspect'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activemodel/lib/active_model/attribute_methods.rb:219:in `inspect'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activemodel/lib/active_model/attribute_methods.rb:219:in `inspect'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activemodel/lib/active_model/attribute_methods.rb:219:in `attribute_alias?'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation/query_methods.rb:256:in `block in _select!'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation/query_methods.rb:255:in `map!'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation/query_methods.rb:255:in `_select!'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:140:in `build_scope'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/collection_association.rb:9:in `build_scope'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:28:in `scope'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:36:in `query_scope'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:32:in `records_for'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:116:in `block in load_slices'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:115:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:115:in `each_slice'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:115:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:115:in `flat_map'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:115:in `load_slices'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:91:in `associated_records_by_owner'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/collection_association.rb:13:in `preload'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:20:in `run'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:146:in `block (2 levels) in preloaders_for_one'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:144:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:144:in `map'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:144:in `block in preloaders_for_one'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:143:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:143:in `flat_map'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:143:in `preloaders_for_one'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:125:in `block in preloaders_for_hash'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:124:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:124:in `flat_map'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:124:in `preloaders_for_hash'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:113:in `preloaders_on'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:103:in `block in preload'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:102:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:102:in `flat_map'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:102:in `preload'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation.rb:661:in `block in exec_queries'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation.rb:660:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation.rb:660:in `exec_queries'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation.rb:546:in `load'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation.rb:244:in `to_a'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation/delegation.rb:45:in `to_ary'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:115:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:115:in `each_slice'
[...]
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation/delegation.rb:45:in `to_ary'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:115:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:115:in `each_slice'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:115:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:115:in `flat_map'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:115:in `load_slices'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:91:in `associated_records_by_owner'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/singular_association.rb:9:in `preload'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader/association.rb:20:in `run'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:146:in `block (2 levels) in preloaders_for_one'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:144:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:144:in `map'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:144:in `block in preloaders_for_one'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:143:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:143:in `flat_map'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:143:in `preloaders_for_one'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:115:in `preloaders_on'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:129:in `block (2 levels) in preloaders_for_hash'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:128:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:128:in `flat_map'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:128:in `block in preloaders_for_hash'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:124:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:124:in `flat_map'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:124:in `preloaders_for_hash'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:113:in `preloaders_on'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:103:in `block in preload'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:102:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:102:in `flat_map'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/associations/preloader.rb:102:in `preload'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation.rb:661:in `block in exec_queries'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation.rb:660:in `each'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation.rb:660:in `exec_queries'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation.rb:546:in `load'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation.rb:244:in `to_a'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation.rb:646:in `inspect'
    issue.rb:53:in `all_inspect'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation/delegation.rb:93:in `public_send'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation/delegation.rb:93:in `block in method_missing'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation.rb:321:in `scoping'
    /home/maurizio/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-dfdb08f0923d/activerecord/lib/active_record/relation/delegation.rb:93:in `method_missing'
    issue.rb:70:in `test_issue'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips

```

### Failing test

Set `MASTER` envvar in order to run the test against rails master. 

```ruby
if ENV['MASTER']
  unless File.exist?('Gemfile')
    File.write('Gemfile', <<-GEMFILE)
source 'https://rubygems.org'
gem 'rails', github: 'rails/rails'
gem 'arel', github: 'rails/arel'
gem 'sqlite3'
    GEMFILE
    system 'bundle'
  end

  require 'bundler'
  Bundler.setup(:default)
else
  require 'fileutils'
  FileUtils.rm_f ['Gemfile', 'Gemfile.lock']

  gem 'activerecord', '4.2.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.belongs_to :commentable, polymorphic: true
  end
end

class Post < ActiveRecord::Base
  has_many :comments, as: :commentable

  # In order to reproduce the issue, `default_scope` has to be defined
  # using `def` instead of `default_scope { }`
  def self.default_scope
    order(:id)
  end

  # In order to reproduce the issue, `all.inspect` has to be called
  # inside a class method
  def self.all_inspect
    all.inspect
  end
end

class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

class IssueTest < Minitest::Test
  def test_issue
    # At least one post with one comment has to be present
    post = Post.create!
    post.comments.create!

    # Works
    Post.all.inspect
    # Raises SystemStackError: stack level too deep
    Post.includes(comments: :commentable).all_inspect
  end
end
```

**Comment by sgrif** [comment]
You are defining a recursive eager load. Your test passes if changed to `Post.includes(:comments).all_inspect`, which is the correct way to write that.

**Comment by mdesantis** [comment]
The test passes also if I implement default_scope using `default_scope {}`, or if I remove `default_scope`.

**Comment by sgrif** [comment]
Given that the issue can only be reproduced with an incorrect usage of Active Record, it does matter.

**Comment by mdesantis** [comment]
Is this "incorrect usage" even documented? I'm not monekypatching anything, I'm just making a query call using Rails APIs.

It would be more acceptable for me if you say "Rails does not support eager loading on polymorphic associations", and even in this case I have something to say: when Rails tries to eager load a polymorphic resource, at least it raises a justifiable exception:

```ruby
Post.eager_load(comments: :commentable)
#=> Cannot eagerly load the polymorphic association :commentable (ActiveRecord::EagerLoadPolymorphicError)
```

Instead of entering in a recursive loop provoked by library code, and not by user code.

I understand that Rails team has *a lot* of things to do, with more than 300 issues opened and more than 400 pull requests is perfectly understandable, but saying that a plain Rails API usage which leads to a recursive loop is an "incorrect usage" seems hasty to me.

**Comment by sgrif** [comment]
It is nearly impossible to detect when you are referencing associations to eager load recursively, especially if one of them is polymorphic. The post is the commentable, but we can't know when constructing the joins that we're looping in that way.

> but saying that a plain Rails API usage which leads to a recursive loop is an "incorrect usage" seems hasty to me.

You're working with a Turing complete programming language, we can't prevent everything bad that you might try to do.

**Comment by mdesantis** [comment]
Could you explain what is bad in

```ruby
Post.includes(comments: :commentable).all.inspect
```

It seems to me normal code.

**Comment by sgrif** [comment]
The post is the commentable. It should not be eager loaded as it's where
we're starting from. So it loads the posts, then loads the comments, then
loads the commentables, sees that its the posts, and tries to eager load
the comments, etc

**Comment by mdesantis** [comment]
So how is it possible to work in some other cases, for example when `default_scope` is defined as a proc (that is the way I solved this issue in my app)? It's really weird, don't you think?

**Comment by sgrif** [comment]
Yes, it's weird. If you can demonstrate the bug without circular eager loading, please open a new issue.

**Comment by amitfriedman12** [comment]
Not sure if this is related but thought i'll mention it here in case anyone comes across this:
https://github.com/rails/rails/issues/1264
and the fix: https://github.com/rails/rails/commit/c69111ba5fde8445237f682c88b927bcde1588d4
