### ISSUE TITLE
Timeout on load page after upgrade on rails 4.2.1

### ISSUE THREAD

**Issue by diospi** [rails/rails#19476]
Hi everyone,
I have a rails 4.1.9 application and want to upgrade it to 4.2.0 (and now to 4.2.1) but I get on some machines a timeout error on my developer machine and on the server and staging server but on other machine all works fine and after some time it worked on staging server, but not on production server. 
The error is not really reproducable because on my machine sometimes it works and sometimes not and on some it first didn't work but after some time it worked.
I already tried this when version 4.2.0 was out and now with 4.2.1 again the same. The error happens in development and production environment, when I enter a page all I get on the console (or the log file) is: 

```
Started GET "/" for 127.0.0.1 at 2015-03-23 11:26:09 -0500
Processing by Hds::StaticController#main as HTML
```
A background job is running and working correctly, but if I want to access a page in the browser I get a timeout.
I found an error that seams related to my problem, but the solution didn't help me: https://github.com/rails/rails/issues/18703
Can this be something related to my problem? Does anyone have an advise to help me investigate this error, or should I wait on version 4.2.2. 

Thanks in advance,

Dominik

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by rafaelfranca** [comment]
> The error is not really reproducable because on my machine sometimes it works and sometimes not and on some it first didn't work but after some time it worked.

If it is not reproducible, I'm sorry, there is no much that we can help you.

Maybe you could provide more information about where the error happen and what you are using on that actions.

**Comment by diospi** [comment]
It's at the beginning, when I start the server, I get this normal output on WEBrick:

```
=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2015-03-23 12:20:43] INFO  WEBrick 1.3.1
[2015-03-23 12:20:43] INFO  ruby 2.0.0 (2014-10-27) [x86_64-linux]
[2015-03-23 12:20:43] INFO  WEBrick::HTTPServer#start: pid=11172 port=3000

```

and when I access the first page,whatever page i choose, it shows these two lines:

```
Started GET "/" for 127.0.0.1 at 2015-03-23 11:26:09 -0500
Processing by Hds::StaticController#main as HTML
```

and then is working until it gets a timeout.
I tried it with different version of ruby (2.0.0-p594, 2.0.0-p598, 2.2.0) and in all versions occurs the error.

When I stop the server while running without responding I get the following error, maybe this helps:

```
/home/friedheim/.rvm/gems/ruby-2.0.0-p594/gems/rack-1.6.0/lib/rack/handler/webrick.rb:49:in `shutdown': undefined method `shutdown' for nil:NilClass (NoMethodError)
	from /home/friedheim/.rvm/gems/ruby-2.0.0-p594/gems/rack-1.6.0/lib/rack/server.rb:280:in `block in start'
	from /home/friedheim/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/webrick/server.rb:198:in `call'
	from /home/friedheim/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/webrick/server.rb:198:in `join'
	from /home/friedheim/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/webrick/server.rb:198:in `block (2 levels) in start'
	from /home/friedheim/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/webrick/server.rb:198:in `each'
	from /home/friedheim/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/webrick/server.rb:198:in `block in start'
	from /home/friedheim/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/webrick/server.rb:32:in `start'
	from /home/friedheim/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/webrick/server.rb:160:in `start'
	from /home/friedheim/.rvm/gems/ruby-2.0.0-p594/gems/rack-1.6.0/lib/rack/handler/webrick.rb:35:in `run'
	from /home/friedheim/.rvm/gems/ruby-2.0.0-p594/gems/rack-1.6.0/lib/rack/server.rb:286:in `start'
	from /home/friedheim/.rvm/gems/ruby-2.0.0-p594/gems/railties-4.2.1/lib/rails/commands/server.rb:80:in `start'
	from /home/friedheim/.rvm/gems/ruby-2.0.0-p594/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /home/friedheim/.rvm/gems/ruby-2.0.0-p594/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/friedheim/.rvm/gems/ruby-2.0.0-p594/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/friedheim/.rvm/gems/ruby-2.0.0-p594/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/friedheim/.rvm/gems/ruby-2.0.0-p594/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

And here are my Gemfile and Gemfile.lock:
```
source 'http://rubygems.org'

gem 'rails', '4.2.1'
gem 'bcrypt-ruby'
gem 'rake'

gem 'ransack', github: 'activerecord-hackery/ransack', branch: 'rails-4.2'

gem 'jquery_datepicker', github: 'diospi/jquery_datepicker', branch: 'rails4'

gem 'best_in_place', github: 'bensewell/best_in_place', branch: 'rails-4'

gem 'paper_trail'#, '~> 3.0.0'

gem 'mysql2'


gem 'will_paginate'

gem 'prawn','1.0.0'#, git: 'https://github.com/prawnpdf/prawn'

gem 'paperclip'#, '3.5.2'

gem 'simple_enum'


gem 'simple-navigation'

gem 'whenever', require: false

gem 'barby'

gem 'chunky_png'

gem 'hookup'

gem 'devise', github: 'plataformatec/devise', branch: 'lm-rails-4-2'

gem 'cancancan'

gem 'spreadsheet'

gem 'dalli'

gem 'rserve-simpler'

gem 'date_validator'

gem 'coffee-rails', '~> 4.0.0'

gem 'uglifier'

gem 'sass'


gem 'jquery-rails'
gem 'jquery-ui-rails'

gem 'exception_notification'

gem 'time_diff'

group :development, :test do
  gem 'rack-mini-profiler'

  gem 'factory_girl_rails'
  gem 'annotate'#,'>=2.5.0.pre1'
  gem 'capistrano-conditional', require: false
  gem 'capistrano-ext'
  gem 'rvm-capistrano'
end

group :development do
  gem 'rails-erd'
  gem 'railroady'
  gem 'web-console', '~> 2.0'
end
group :test do
  gem 'turn', :require => false
  gem 'faker'

  gem 'capybara'
  gem 'capybara_minitest_spec'

  gem 'capybara-webkit'
  gem 'rack_session_access'
  gem 'capybara-screenshot'
  gem 'minitest-metadata'
  gem 'poltergeist'
  gem 'phantomjs'

  gem 'database_cleaner'

  gem 'ci_reporter'
  gem 'timecop'
 end



group :production do
  gem 'libv8', '~> 3.16.14', platforms: :ruby
  gem 'therubyracer', '~> 0.12.0', platforms: :ruby
  gem 'unicorn'
end
```

Gemfile.lock:

```
GIT
  remote: git://github.com/activerecord-hackery/ransack.git
  revision: b7d44452e649e48f8df193d0c05f405b6cb77cc6
  branch: rails-4.2
  specs:
    ransack (1.2.4)
      actionpack (>= 4.1)
      activerecord (>= 4.1)
      activesupport (>= 4.1)
      i18n
      polyamorous (~> 1.1)

GIT
  remote: git://github.com/bensewell/best_in_place.git
  revision: 735ec9818b559a9b6aa226720e89b8641f16fb97
  branch: rails-4
  specs:
    best_in_place (2.1.1)
      jquery-rails
      rails (~> 4)

GIT
  remote: git://github.com/diospi/jquery_datepicker.git
  revision: 5e5fea2941ed78da581aaa371afb4f911164181b
  branch: rails4
  specs:
    jquery_datepicker (0.4)

GIT
  remote: git://github.com/plataformatec/devise.git
  revision: 1d8890b77372b9c4fd3ec8e9b4963d76774ed33c
  branch: lm-rails-4-2
  specs:
    devise (3.3.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)

GEM
  remote: http://rubygems.org/
  specs:
    actionmailer (4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.1)
      actionview (= 4.2.1)
      activesupport (= 4.2.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    activejob (4.2.1)
      activesupport (= 4.2.1)
      globalid (>= 0.3.0)
    activemodel (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
    activerecord (4.2.1)
      activemodel (= 4.2.1)
      activesupport (= 4.2.1)
      arel (~> 6.0)
    activesupport (4.2.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.5)
    annotate (2.6.1)
      activerecord (>= 2.3.0)
      rake (>= 0.8.7)
    ansi (1.4.3)
    arel (6.0.0)
    barby (0.5.1)
    bcrypt (3.1.7)
    bcrypt (3.1.7-x86-mingw32)
    bcrypt-ruby (3.1.5)
      bcrypt (>= 3.1.3)
    bcrypt-ruby (3.1.5-x86-mingw32)
      bcrypt (>= 3.1.3)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    builder (3.2.2)
    cancancan (1.7.1)
    capistrano (2.15.5)
      highline
      net-scp (>= 1.0.0)
      net-sftp (>= 2.0.0)
      net-ssh (>= 2.0.14)
      net-ssh-gateway (>= 1.1.0)
    capistrano-conditional (0.0.4)
      capistrano (~> 2.5)
      git
    capistrano-ext (1.2.1)
      capistrano (>= 1.0.0)
    capybara (2.2.1)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-screenshot (0.3.16)
      capybara (>= 1.0, < 3)
      launchy
    capybara-webkit (1.1.0)
      capybara (~> 2.0, >= 2.0.2)
      json
    capybara_minitest_spec (1.0.1)
      capybara (>= 2)
      minitest (>= 2)
    choice (0.1.6)
    chronic (0.10.2)
    chunky_png (1.2.9)
    ci_reporter (1.9.1)
      builder (>= 2.1.2)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cliver (0.3.2)
    cocaine (0.5.4)
      climate_control (>= 0.0.3, < 1.0)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.6.3)
    dalli (2.7.0)
    database_cleaner (1.2.0)
    date_validator (0.7.0)
      activemodel (>= 3)
    debug_inspector (0.0.2)
    erubis (2.7.0)
    exception_notification (4.0.1)
      actionmailer (>= 3.0.4)
      activesupport (>= 3.0.4)
    execjs (2.0.2)
    factory_girl (4.3.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.3.0)
      factory_girl (~> 4.3.0)
      railties (>= 3.0.0)
    faker (1.2.0)
      i18n (~> 0.5)
    git (1.2.6)
    globalid (0.3.3)
      activesupport (>= 4.1.0)
    highline (1.6.20)
    hike (1.2.3)
    hookup (1.2.3)
    i18n (0.7.0)
    jquery-rails (3.1.0)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (4.2.0)
      railties (>= 3.2.16)
    json (1.8.2)
    kgio (2.9.2)
    launchy (2.4.2)
      addressable (~> 2.3)
    libv8 (3.16.14.3)
    loofah (2.0.1)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.4.3)
    mini_portile (0.6.2)
    minitest (5.5.1)
    minitest-metadata (0.3.0)
      minitest (>= 2.12)
    multi_json (1.11.0)
    mysql2 (0.3.15)
    net-scp (1.1.2)
      net-ssh (>= 2.6.5)
    net-sftp (2.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.8.0)
    net-ssh-gateway (1.2.0)
      net-ssh (>= 2.6.5)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    nokogiri (1.6.6.2-x86-mingw32)
      mini_portile (~> 0.6.0)
    orm_adapter (0.5.0)
    paper_trail (3.0.1)
      activerecord (>= 3.0, < 5.0)
      activesupport (>= 3.0, < 5.0)
    paperclip (4.1.1)
      activemodel (>= 3.0.0)
      activesupport (>= 3.0.0)
      cocaine (~> 0.5.3)
      mime-types
    pdf-core (0.2.5)
    phantomjs (1.9.2.1)
    poltergeist (1.5.0)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    polyamorous (1.1.0)
      activerecord (>= 3.0)
    prawn (1.0.0)
      pdf-core (~> 0.2.2)
      ttfunk (~> 1.1.1)
    rack (1.6.0)
    rack-mini-profiler (0.9.1)
      rack (>= 1.1.3)
    rack-test (0.6.3)
      rack (>= 1.0)
    rack_session_access (0.1.1)
      builder (>= 2.0.0)
      rack (>= 1.0.0)
    railroady (1.1.1)
    rails (4.2.1)
      actionmailer (= 4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      activemodel (= 4.2.1)
      activerecord (= 4.2.1)
      activesupport (= 4.2.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.6)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-erd (1.1.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      choice (~> 0.1.6)
      ruby-graphviz (~> 1.0.4)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    railties (4.2.1)
      actionpack (= 4.2.1)
      activesupport (= 4.2.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    raindrops (0.13.0)
    rake (10.4.2)
    ref (1.0.5)
    responders (2.0.2)
      railties (>= 4.2.0.alpha, < 5)
    rserve-client (0.3.1)
    rserve-simpler (0.0.6)
      rserve-client (~> 0.3.0)
    ruby-graphviz (1.0.9)
    ruby-ole (1.2.11.8)
    rvm-capistrano (1.5.1)
      capistrano (~> 2.15.4)
    sass (3.3.4)
    simple-navigation (3.13.0)
      activesupport (>= 2.3.2)
    simple_enum (1.6.8)
      activesupport (>= 3.0.0)
    spreadsheet (0.9.7)
      ruby-ole (>= 1.0)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.2.4)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    therubyracer (0.12.1)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    time_diff (0.3.0)
      activesupport
      i18n
    timecop (0.7.1)
    ttfunk (1.1.1)
    turn (0.9.6)
      ansi
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.5.0)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unicorn (4.8.2)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    warden (1.2.3)
      rack (>= 1.0)
    web-console (2.0.0)
      activemodel (~> 4.0)
      binding_of_caller (>= 0.7.2)
      railties (~> 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    websocket-driver (0.3.2)
    whenever (0.9.2)
      activesupport (>= 2.3.4)
      chronic (>= 0.6.3)
    will_paginate (3.0.5)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby
  x86-mingw32

DEPENDENCIES
  annotate
  barby
  bcrypt-ruby
  best_in_place!
  cancancan
  capistrano-conditional
  capistrano-ext
  capybara
  capybara-screenshot
  capybara-webkit
  capybara_minitest_spec
  chunky_png
  ci_reporter
  coffee-rails (~> 4.0.0)
  dalli
  database_cleaner
  date_validator
  devise!
  exception_notification
  factory_girl_rails
  faker
  hookup
  jquery-rails
  jquery-ui-rails
  jquery_datepicker!
  libv8 (~> 3.16.14)
  minitest-metadata
  mysql2
  paper_trail
  paperclip
  phantomjs
  poltergeist
  prawn (= 1.0.0)
  rack-mini-profiler
  rack_session_access
  railroady
  rails (= 4.2.1)
  rails-erd
  rake
  ransack!
  rserve-simpler
  rvm-capistrano
  sass
  simple-navigation
  simple_enum
  spreadsheet
  therubyracer (~> 0.12.0)
  time_diff
  timecop
  turn
  uglifier
  unicorn
  web-console (~> 2.0)
  whenever
  will_paginate
```

I already tried to make a application para reproduce the error but didn't achieve it. I will try it another time. 
The other question is, if you have a suspicion what could cause this problem, if it's somthing related to the assets or something else, what could help me investigate, because I don't know well the depths of rails.

Thanks,

Dominik

**Comment by rafaelfranca** [comment]
Are you precompiling the assets in production? Or you are generating them on demand?

**Comment by diospi** [comment]
I'm precompiling the assets, I deploy with capistrano and have an nginx server with unicorn.
in my environments/production.rb:


```
config.assets.compile = true 
```
as fallback.

**Comment by rafaelfranca** [comment]
If you precompile and serve them with unicorn in production I don't see how this timeout can be related with assets.

**Comment by rafaelfranca** [comment]
Could you try to remove all the calls to assets in the page you are getting this problem, so we can isolate just the controller processing.

**Comment by diospi** [comment]
I removed the calls on the assets in my application.html.erb but it doesn't change, the problem is still occurring

**Comment by rafaelfranca** [comment]
Ok, so it may be one of your dependencies.

**Comment by diospi** [comment]
O.K., thanks for your help!

**Comment by rafaelfranca** [comment]
Try to remove the usage of all dependencies you for that controller and action. That way you may find the reason
