### ISSUE TITLE
InvalidAuthenticityToken problem 

### ISSUE THREAD

**Issue by alec-c4** [rails/rails#19615]
Hi,
I'm expecting strange behaviour of my rails app.

I've deployed my app on staging and on attempt to submit any form i see 

```
I, [2015-04-01T16:44:40.745717 #8869]  INFO -- : [9430a6c7-4135-4c8a-aa3e-91a0d4f04278] Started POST "/organizations" for 91.219.24.73 at 2015-04-01 16:44:40 -0400
I, [2015-04-01T16:44:40.787311 #8869]  INFO -- : [9430a6c7-4135-4c8a-aa3e-91a0d4f04278] Processing by OrganizationsController#create as HTML
I, [2015-04-01T16:44:40.787619 #8869]  INFO -- : [9430a6c7-4135-4c8a-aa3e-91a0d4f04278]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"WfTK72CJ0J9vfAomtla75lUhPTefrv9QBuzEH6eY5hv34SU5BH2b/5dZzzULs+C6TTx13Osit/wKG1UhJR4O8w==", "organization"=>{"name"=>"", "slug"=>""}}
W, [2015-04-01T16:44:40.796054 #8869]  WARN -- : [9430a6c7-4135-4c8a-aa3e-91a0d4f04278] Can't verify CSRF token authenticity
I, [2015-04-01T16:44:40.796971 #8869]  INFO -- : [9430a6c7-4135-4c8a-aa3e-91a0d4f04278] Completed 422 Unprocessable Entity in 9ms (ActiveRecord: 0.0ms)
F, [2015-04-01T16:44:40.799064 #8869] FATAL -- : [9430a6c7-4135-4c8a-aa3e-91a0d4f04278]
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  actionpack (4.2.1) lib/action_controller/metal/request_forgery_protection.rb:181:in `handle_unverified_request'
  actionpack (4.2.1) lib/action_controller/metal/request_forgery_protection.rb:209:in `handle_unverified_request'
  devise (3.4.1) lib/devise/controllers/helpers.rb:251:in `handle_unverified_request'
  actionpack (4.2.1) lib/action_controller/metal/request_forgery_protection.rb:204:in `verify_authenticity_token'
  activesupport (4.2.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.1) lib/active_support/callbacks.rb:164:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:164:in `block in halting'
  activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
```

but the same configuration on development environment works fine. When i've disabled 

```
protect_from_forgery with: :exception
```

everything works fine.

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is the expected behavior. Your page is sending the wrong authenticity token. Is the page cached? This could explain why it is working fine at development.

If the page is not cached could you provide a way to reproduce this problem? Otherwise there is nothing that we can do.

Thanks.

**Comment by alec-c4** [comment]
you know - there are no caching enabled :( i've tried following: 
- i've disabled nginx on server
- i've did service memcached stop
- i've tried to run app in development and staging modes, but on staging server 
- i've tried to rewrite config/environments/staging.rb with config/environments/development.rb 
- i've tried to run app on passenger (originally i'm using puma) in both staging and development

but i have the same error :(

**Comment by rafaelfranca** [comment]
:shipit:

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by alec-c4** [comment]
@rafaelfranca i've found a problem - it was my mistake :) i've forgotten to update 

```
Rails.application.config.session_store :cookie_store, key: '_app_session', :domain => ".#{ENV['domain']}"
```

with correct value of ENV['domain']

thanks a lot for your support :)
