### ISSUE TITLE
HABTM new records error when saving when partial writes are off

### ISSUE THREAD

**Issue by malmckay** [rails/rails#19663]
Example spec fail here - https://gist.github.com/malmckay/1262766f0d8980db6fe7

When I disable partial_writes my HABTM association error on save (in some cases).

PrimaryKey#id_was raises, because the join table does not have a primary key.

**Comment by pixeltrix** [comment]
This is blowing up in [`ActiveRecord::Persistence#_update_record`][1] but the only difference when partial writes is enabled/disabled is the attribute names passed to the method. This leads me to believe that the attribute names array is empty when partial writes are enabled - maybe there are no dirty attributes at the point the method is being called?

[1]: https://github.com/rails/rails/blob/v4.2.0/activerecord/lib/active_record/persistence.rb#L512

**Comment by pixeltrix** [comment]
Backtrace:

```
TypeError: nil is not a symbol nor a string
    activemodel-4.2.0/lib/active_model/dirty.rb:181:in `attribute_was'
    activerecord-4.2.0/lib/active_record/attribute_methods/primary_key.rb:45:in `id_was'
    activerecord-4.2.0/lib/active_record/persistence.rb:512:in `_update_record'
    activerecord-4.2.0/lib/active_record/locking/optimistic.rb:70:in `_update_record'
    activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:123:in `_update_record'
    activerecord-4.2.0/lib/active_record/callbacks.rb:310:in `block in _update_record'
    activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
    activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
    activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_update_callbacks'
    activerecord-4.2.0/lib/active_record/callbacks.rb:310:in `_update_record'
    activerecord-4.2.0/lib/active_record/timestamp.rb:70:in `_update_record'
    activerecord-4.2.0/lib/active_record/persistence.rb:501:in `create_or_update'
    activerecord-4.2.0/lib/active_record/callbacks.rb:302:in `block in create_or_update'
    activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
    activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
    activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
    activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
    activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
    activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
    activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
    activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_save_callbacks'
    activerecord-4.2.0/lib/active_record/callbacks.rb:302:in `create_or_update'
    activerecord-4.2.0/lib/active_record/persistence.rb:142:in `save!'
    activerecord-4.2.0/lib/active_record/validations.rb:43:in `save!'
    activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
    activerecord-4.2.0/lib/active_record/transactions.rb:291:in `block in save!'
    activerecord-4.2.0/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
    activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
    activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
    activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
    activerecord-4.2.0/lib/active_record/transactions.rb:291:in `save!'
    activerecord-4.2.0/lib/active_record/associations/has_many_through_association.rb:112:in `save_through_record'
    activerecord-4.2.0/lib/active_record/associations/has_many_through_association.rb:66:in `insert_record'
    activerecord-4.2.0/lib/active_record/autosave_association.rb:358:in `block in save_collection_association'
    activerecord-4.2.0/lib/active_record/autosave_association.rb:349:in `each'
    activerecord-4.2.0/lib/active_record/autosave_association.rb:349:in `save_collection_association'
    activerecord-4.2.0/lib/active_record/autosave_association.rb:186:in `block in add_autosave_association_callbacks'
    activerecord-4.2.0/lib/active_record/autosave_association.rb:157:in `instance_eval'
    activerecord-4.2.0/lib/active_record/autosave_association.rb:157:in `block in define_non_cyclic_method'
    activesupport-4.2.0/lib/active_support/callbacks.rb:427:in `block in make_lambda'
    activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `call'
    activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `block in halting_and_conditional'
    activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
    activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
    activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_create_callbacks'
    activerecord-4.2.0/lib/active_record/callbacks.rb:306:in `_create_record'
    activerecord-4.2.0/lib/active_record/timestamp.rb:57:in `_create_record'
    activerecord-4.2.0/lib/active_record/persistence.rb:501:in `create_or_update'
    activerecord-4.2.0/lib/active_record/callbacks.rb:302:in `block in create_or_update'
    activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
    activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
    activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
    activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
    activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
    activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_save_callbacks'
    activerecord-4.2.0/lib/active_record/callbacks.rb:302:in `create_or_update'
    activerecord-4.2.0/lib/active_record/persistence.rb:142:in `save!'
    activerecord-4.2.0/lib/active_record/validations.rb:43:in `save!'
    activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
    activerecord-4.2.0/lib/active_record/transactions.rb:291:in `block in save!'
    activerecord-4.2.0/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
    activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
    activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
    activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
    activerecord-4.2.0/lib/active_record/transactions.rb:291:in `save!'
    test.rb:43:in `test_association_stuff'
```

**Comment by pixeltrix** [comment]
Looks like an internal callback is trying to save the record again after it has been created.

**Comment by pixeltrix** [comment]
Looking at the log confirms this to be the case - through record has already been inserted before it blows up: 

```
D, [2015-04-06T08:12:57.155114 #4436] DEBUG -- :    (0.0ms)  begin transaction
D, [2015-04-06T08:12:57.156934 #4436] DEBUG -- :   SQL (0.1ms)  INSERT INTO "posts" DEFAULT VALUES
D, [2015-04-06T08:12:57.157580 #4436] DEBUG -- :   SQL (0.0ms)  INSERT INTO "authors" DEFAULT VALUES
D, [2015-04-06T08:12:57.159721 #4436] DEBUG -- :   SQL (0.1ms)  INSERT INTO "authors_posts" ("post_id", "author_id") VALUES (?, ?)  [["post_id", 1], ["author_id", 1]]
D, [2015-04-06T08:12:57.160289 #4436] DEBUG -- :    (0.1ms)  rollback transaction
```

**Comment by meinac** [comment]
I've found the problem and created a pr which will fix this.

**Comment by arthurnn** [comment]
this should be fixed by @meinac patch. https://github.com/rails/rails/commit/a0a37d9fd3c35f44fa58439fa41b4cdff2d25a98
