### ISSUE TITLE
Fails to force_ssl_redirection if session_store is disabled.

### ISSUE THREAD

**Issue by supercaracal** [rails/rails#19679]
#### application log

```
NoMethodError (undefined method `flash' for #<ActionDispatch::Request:0x007fe54d753e80>):
actionpack (4.2.1) lib/action_controller/metal/flash.rb:9:in `flash'
actionpack (4.2.1) lib/action_controller/metal/force_ssl.rb:92:in `force_ssl_redirect'
actionpack (4.2.1) lib/action_controller/metal/force_ssl.rb:66:in `block in force_ssl'
```

#### config/application.rb

```ruby
require File.expand_path('../boot', __FILE__)

require 'action_controller/railtie'
require 'action_mailer/railtie'
require 'rails/test_unit/railtie'
require 'sprockets/railtie'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Hogehoge
  class Application < Rails::Application
    # some settings
  end
end
```

#### config/initializers/session_store.rb

```ruby
Rails.application.config.session_store nil, key: '_hogehoge_session'
```

#### bin/rake middleware

```
use Rack::Sendfile
use ActionDispatch::Static
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007f4b976b8bb0>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use BetterErrors::Middleware
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use NewRelic::Rack::DeveloperMode
use NewRelic::Rack::BrowserMonitoring
use NewRelic::Rack::AgentHooks
run Hogehoge::Application.routes
```

**Comment by supercaracal** [comment]
It's not a bug. It's a feature.

**Comment by supercaracal** [comment]
?
