### ISSUE TITLE
Create table fails on db:migrate task in ActiveRecord 4.2.1 if database adapter not support foreign_keys.

### ISSUE THREAD

**Issue by zjuanma** [rails/rails#19794]
After migration to ActiveRecord 4.21 using DB2 adapter (https://github.com/ibmdb/ruby-ibmdb 2.5.26) the task db:migrate fails on create_table:

```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `each_pair' for nil:NilClass/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:216:in `create_table'
/ruby_gems/2.1/gems/ibm_db-2.5.26/lib/active_record/connection_adapters/ibm_db_adapter.rb:843:in `create_table'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/home/app/db/migrate/20150416143244_devise_create_users.rb:3:in `change'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `each_pair' for nil:NilClass
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:216:in `create_table'
/ruby_gems/2.1/gems/ibm_db-2.5.26/lib/active_record/connection_adapters/ibm_db_adapter.rb:843:in `create_table'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/home/app/db/migrate/20150416143244_devise_create_users.rb:3:in `change'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/ruby_gems/2.1/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
```
DB2 adapter not support foreign_keys:

https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Adapter/ibm_db/lib/active_record/connection_adapters/ibm_db_adapter.rb#L756

Error is in this file:

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L216

Before iterate td.foreign_keys check that database adapter support foreign_keys.

**Comment by senny** [comment]
This is something, which needs fixing on the DB2 adapter side. I've committed a test-case to the Active Record suite to make sure `create_table` with `foreign_key: true` definitions and an adapter without foreign key support does result in a no-op. This is already the case for our `SQLite3Adapter`.

The root of the problem is the [`TableDefinition`](https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Adapter/ibm_db/lib/active_record/connection_adapters/ibm_db_adapter.rb#L410) of the DB2 adapter. Even if it doesn't support foreign keys it's expected to have the same interface as the [`TableDefinition`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L211) that ships with Active Record.

@zjuanma thank you for reporting :yellow_heart:, please open an issue on the DB2 adapter project. If they are running against our test-suite, they will now have the test-case to ensure compatibility.

**Comment by zjuanma** [comment]
This is mi migration. Where I have to add the foreign_key ?


class DeviseCreateUsers < ActiveRecord::Migration
  def change
    create_table(:users) do |t|
      t.string :username, null: false
      t.string :email, null: true

      ## Rememberable
      t.datetime :remember_created_at

      ## Trackable
      t.integer  :sign_in_count, default: 0, null: false
      t.datetime :current_sign_in_at
      t.datetime :last_sign_in_at
      t.string   :current_sign_in_ip
      t.string   :last_sign_in_ip

     

      t.timestamps
    end
 end
end

**Comment by senny** [comment]
@zjuanma in your migration there are no foreign keys involved. It's a compatibility issue with the Rails 4.2. and the DB2 adapter gem.
