### ISSUE TITLE
[master] NameError: uninitialized constant Rake::TestTask

### ISSUE THREAD

**Issue by marutosi** [rails/rails#19997]
https://bitbucket.org/marutosi/rails5-sandbox/src/ae93553ea31d/lib/tasks/redmine.rake#cl-155

```
$ rake -T
rake aborted!
NameError: uninitialized constant Rake::TestTask
/xxx/lib/tasks/redmine.rake:155:in `block (3 levels) in <top (required)>'
/xxx/lib/tasks/redmine.rake:153:in `block (2 levels) in <top (required)>'
/xxx/lib/tasks/redmine.rake:109:in `block in <top (required)>'
/xxx/lib/tasks/redmine.rake:18:in `<top (required)>'
/home/yyy/.rvm/gems/ruby-2.2.2/bundler/gems/rails-71669370ae78/railties/lib/rails/engine.rb:652:in `load'
/home/yyy/.rvm/gems/ruby-2.2.2/bundler/gems/rails-71669370ae78/railties/lib/rails/engine.rb:652:in `block in run_tasks_blocks'
/home/yyy/.rvm/gems/ruby-2.2.2/bundler/gems/rails-71669370ae78/railties/lib/rails/engine.rb:652:in `each'
/home/yyy/.rvm/gems/ruby-2.2.2/bundler/gems/rails-71669370ae78/railties/lib/rails/engine.rb:652:in `run_tasks_blocks'
/home/yyy/.rvm/gems/ruby-2.2.2/bundler/gems/rails-71669370ae78/railties/lib/rails/application.rb:444:in `run_tasks_blocks'
/home/yyy/.rvm/gems/ruby-2.2.2/bundler/gems/rails-71669370ae78/railties/lib/rails/engine.rb:453:in `load_tasks'
/xxx/Rakefile:6:in `<top (required)>'
```

```
$ ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

$ bundle exec rake --version
rake, version 10.4.2
```

**Comment by rafaelfranca** [comment]
The error seems right. You are expecting rails to require `Rake::TestTask` when you should not. To fix this just require it in the file you are expecting it to be defined.

**Comment by marutosi** [comment]
Sorry, I cannot understand what you said.
This is Rails 5 regression.

https://bitbucket.org/marutosi/rails5-sandbox/src/41ed7be0b397d/lib/tasks/redmine.rake

lib/tasks/redmine.rake
```ruby
namespace :redmine do
  namespace :plugins do
    namespace :test do
      desc 'Runs the plugins unit tests.'
      Rake::TestTask.new do |t|
      end
    end
  end
end
```

On Rails 4:
```diff
diff --git a/Gemfile b/Gemfile
--- a/Gemfile
+++ b/Gemfile
@@ -2,7 +2,8 @@ source 'https://rubygems.org'


 # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
-gem "rails", :github => 'rails/rails', :branch => 'master'
+# gem "rails", :github => 'rails/rails', :branch => 'master'
+gem "rails"
 gem 'arel', github: 'rails/arel'
 # Use sqlite3 as the database for Active Record
 gem 'sqlite3'

```

```
$ rake -T | grep redmine
rake redmine:plugins:test:test          # Run tests
```

**Comment by rafaelfranca** [comment]
It is not a regression. I know that rails is not requiring `Rake::TestTask` anymore in master but this is because we don't need it anymore.

What I said is: You are expecting Rails to require `Rake::TestTask` when you should not. If you want to use that in your own rake files you should require it.

**Comment by marutosi** [comment]
OK. I see.

```diff
diff --git a/lib/tasks/redmine.rake b/lib/tasks/redmine.rake
--- a/lib/tasks/redmine.rake
+++ b/lib/tasks/redmine.rake
@@ -15,6 +15,8 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

+require "rake/testtask.rb"
+
 namespace :redmine do
   namespace :plugins do
     namespace :test do
```

**Comment by rafaelfranca** [comment]
Yeah, that is it. This behavior changed at https://github.com/rails/rails/commit/8017e6af31caa58a58787274ff0ca01397219e49. Like I said we don't need to require that anymore, so we removed.

**Comment by jonatack** [comment]
Working version for current Rails master, if helpful for anyone:

```ruby
# lib/tasks/minitest.rake or in your Rakefile
namespace :test do
  desc "Run only the tests in the `test/features` directory"
  task :features  => "test:prepare" do
    $: << "test"
    Rails::TestRunner.run(["test/features"])
  end
end
```
