### ISSUE TITLE
NameError: uninitialized constant ActionView::Helpers::ActiveModelHelper

### ISSUE THREAD

**Issue by moorem** [rails/rails#20135]
We are getting following error while precompile

```
[root@hugpets current]# rake assets:precompile
rake aborted!
NameError: uninitialized constant ActionView::Helpers::ActiveModelHelper
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/actionview-4.2.1/lib/action_view/helpers.rb:40:in `<module:Helpers>'
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/actionview-4.2.1/lib/action_view/helpers.rb:4:in `<module:ActionView>'
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/actionview-4.2.1/lib/action_view/helpers.rb:3:in `<top (required)>'
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/actionview-4.2.1/lib/action_view/base.rb:5:in `<top (required)>'
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/actionview-4.2.1/lib/action_view/view_paths.rb:1:in `<top (required)>'
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/abstract_controller/rendering.rb:4:in `<top (required)>'
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_controller/base.rb:204:in `<class:Base>'
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_controller/base.rb:164:in `<module:ActionController>'
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_controller/base.rb:5:in `<top (required)>'
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/responders-2.1.0/lib/responders/controller_method.rb:37:in `<top (required)>'
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/responders-2.1.0/lib/responders.rb:15:in `<module:Responders>'
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/responders-2.1.0/lib/responders.rb:9:in `<top (required)>'
/home/deploy/hugpets-staging/shared/bundle/ruby/2.1.0/gems/devise-3.4.1/lib/devise.rb:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `require'
/usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `require'
/usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.9.7/lib/bundler.rb:134:in `require'
/home/deploy/hugpets-staging/releases/20150513061447/config/application.rb:7:in `<top (required)>'
/home/deploy/hugpets-staging/releases/20150513061447/Rakefile:4:in `require'
/home/deploy/hugpets-staging/releases/20150513061447/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
[root@hugpets current]#
```

Help much appreciated!

**Comment by jkuchta** [comment]
What version of rack are you using?

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
