### ISSUE TITLE
number_to_currency NoMethodError 

### ISSUE THREAD

**Issue by PeteMichaud** [rails/rails#20163]
Whenever I use the number_to_currency method with a number that has no decimal places, or with only zeroes in the decimals places, the method throws a NoMethodError. I think the problem is in number_to_rounded_converter.rb:32, when it calls `rounded_number.to_s('F') + '0'*precision` -- that line will cause any number without nonzero decimal places to just have zeros tacked on the end, but no decimal.

```
/Users/pete/.rbenv/versions/2.2.2/bin/ruby -e at_exit{sleep(1)};$stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-debug-ide-0.4.23.beta1/bin/rdebug-ide --disable-int-handler --port 49697 --dispatcher-port 49698 -- /Users/pete/Projects/code/beastmode/bin/rails console development
Fast Debugger (ruby-debug-ide 0.4.23.beta1, debase 0.1.3) listens on 127.0.0.1:49697
Loading development environment (Rails 4.2.1)
Switch to inspect mode.
>> include ActionView::Helpers::NumberHelper
Object

>> number_to_currency("9.09")
"$9.09"

>> number_to_currency("9.00")
NoMethodError: undefined method `[]' for nil:NilClass
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/number_helper/number_to_rounded_converter.rb:34:in `convert'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/number_helper/number_converter.rb:132:in `execute'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/number_helper/number_converter.rb:118:in `convert'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/number_helper/number_to_currency_converter.rb:15:in `convert'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/number_helper/number_converter.rb:132:in `execute'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/number_helper/number_converter.rb:118:in `convert'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/number_helper.rb:86:in `number_to_currency'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/number_helper.rb:388:in `public_send'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/number_helper.rb:388:in `block in delegate_number_helper_method'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/number_helper.rb:412:in `wrap_with_output_safety_handling'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/number_helper.rb:387:in `delegate_number_helper_method'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/number_helper.rb:108:in `number_to_currency'
	from (irb):5
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/pete/Projects/code/beastmode/bin/rails:4:in `require'
	from /Users/pete/Projects/code/beastmode/bin/rails:4:in `<top (required)>'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-debug-ide-0.4.23.beta1/lib/ruby-debug-ide.rb:86:in `debug_load'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-debug-ide-0.4.23.beta1/lib/ruby-debug-ide.rb:86:in `debug_program'
	from /Users/pete/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-debug-ide-0.4.23.beta1/bin/rdebug-ide:110:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

**Comment by meinac** [comment]
As far as I can see from your description you are using Rails 4.2.1. I've tried this with Rails 4.2.1 but could not reproduce the error. Can you please provide a test case to reproduce the error using [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/generic_master.rb)

**Comment by dasibre** [comment]
unable to reproduce either. using Ruby 2.2.2 with rails 4.2.1

**Comment by rafaelfranca** [comment]
Thank you for the issue. Please give us more information about the problem so we can help

**Comment by PeteMichaud** [comment]
I'm working on getting a not-passing test case running. The test doesn't fail when I use the template, but it does fail when I use my normal testing apparatus. It's something about my application environment that's triggering the error, but I have not located the exact issue yet. I suspect one of my gems hijacked BigDecimal, but I haven't found the smoking gun yet. Will update when I have something.

**Comment by PeteMichaud** [comment]
I figured it out, and it's totally my fault. I wrote a gem a while back that monkey patches BigDecimal's to_s to not show the decimal if it's a whole number, eg:

```
#original
big_decimal = BigDecimal.new(1)
big_decimal.to_s #=> '1.0'

#patched
big_decimal = BigDecimal.new(1)
big_decimal.to_s #=> '1'
```

That was causing the bug because number_to_rounded_converter.rb:32 assumes `s` will have a decimal. Feel free to close this report!

**Comment by cdpalmer** [comment]
Thanks for putting this out here!  My company actually has done the same patch to `BigDecimal`, and it was causing the same issue on my end for `number_to_currency`
