### ISSUE TITLE
Live streaming with MySQL and rspec

### ISSUE THREAD

**Issue by piton4eg** [rails/rails#20223]
I'm using live streaming with MySQL for stream products. I have a model Product and controller with next code:
```
class ProductsController < ApplicationController
  include ActionController::Live

  def index
    response.headers['Content-Type'] = 'text/event-stream'
    response.stream.write "Test"
    Product.all do |product|
      response.stream.write "#{product.to_json},\n"
    end
  ensure
    response.stream.close
  end
end
```

I have a test for this controller: 
```
require "rails_helper"

RSpec.describe ProductsController, type: :controller do
  describe 'GET #index' do
    subject(:dispatch) { get :index }
    it "stream closed after response" do
      dispatch
      expect(response.stream.closed?).to be_truthy
    end
  end
end
```

When i'm trying to run my rspec i get next errors: 
```
rspec spec/controllers/products_controller_spec.rb

  An error occurred in an `around(:example)` hook
    ActiveRecord::StatementInvalid: Mysql2::Error: This connection is in use by: #<Thread:0x007f947b4486a0@/Users/alexeymarkov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/live.rb:269 sleep>: ROLLBACK
    occurred at /Users/alexeymarkov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'

F

Failures:

  1) ProductsController GET #index stream closed after response
     Failure/Error: expect(response.stream.closed?).to be_truthy
       expected: truthy value
            got: false
     # ./spec/controllers/products_controller_spec.rb:8:in `block (3 levels) in <top (required)>'

Finished in 0.01153 seconds (files took 2.88 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/controllers/products_controller_spec.rb:6 # ProductsController GET #index stream closed after response
```

When i removed line `response.stream.write "Test"` from my controller, then it works fine.
When i change strings:
```
    Product.all do |product|
      response.stream.write "#{product.to_json},\n"
    end
```
to `response.stream.write "Test2"` then it works too.

**Comment by arthurnn** [comment]
Not sure how to simulate this locally in order to fix the issue. Can you create a test app that shows the problem in isolation? or even better a running script?

thanks

**Comment by piton4eg** [comment]
@arthurnn created test app https://github.com/piton4eg/live

**Comment by meinac** [comment]
This is not a bug. As the nature of `ActionController::Live` it sends the response whenever you call `write` method of the `response.stream`.
In your test case you are expecting stream to be closed but your assertion works before `stream.close`.
Try to add `sleep` gap before the assertion. This test case works on my environment with 0.01 seconds sleep.
