### ISSUE TITLE
Rails Test: SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by manish-shrivastava** [rails/rails#20363]
I downloaded and tested rails by running `bundle exec rake test`,  I got some errors as below.

```
ApplicationTests::MiddlewareExceptionsTest#test_url_generation_error_when_action_dispatch.show_exceptions_is_set_raises_an_exception:
SystemStackError: stack level too deep
```
Trace lines as below:

```   
/home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/core_ext/time/operators.rb:12:in `<=>'
    /home/manish/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/ext/time.rb:13:in `<=>'

...
...(above line multiple times)
...
    /home/manish/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/ext/time.rb:13:in `<=>'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/core_ext/time/operators.rb:12:in `<=>'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/file_update_checker.rb:114:in `<'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/file_update_checker.rb:114:in `block in max_mtime'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/file_update_checker.rb:114:in `reject'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/file_update_checker.rb:114:in `max_mtime'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/file_update_checker.rb:102:in `updated_at'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/file_update_checker.rb:47:in `initialize'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/i18n_railtie.rb:56:in `new'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/i18n_railtie.rb:56:in `initialize_i18n'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/i18n_railtie.rb:21:in `block in <class:Railtie>'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/lazy_load_hooks.rb:36:in `call'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/lazy_load_hooks.rb:44:in `each'
    /home/manish/Desktop/projects/rails/manish/rails/activesupport/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
    /home/manish/Desktop/projects/rails/manish/rails/railties/lib/rails/application/finisher.rb:55:in `block in <module:Finisher>'
    /home/manish/Desktop/projects/rails/manish/rails/railties/lib/rails/initializable.rb:30:in `instance_exec'
    /home/manish/Desktop/projects/rails/manish/rails/railties/lib/rails/initializable.rb:30:in `run'
    /home/manish/Desktop/projects/rails/manish/rails/railties/lib/rails/initializable.rb:55:in `block in run_initializers'
    /home/manish/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
    /home/manish/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    /home/manish/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
    /home/manish/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
    /home/manish/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
    /home/manish/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
    /home/manish/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
    /home/manish/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
    /home/manish/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
    /home/manish/Desktop/projects/rails/manish/rails/railties/lib/rails/initializable.rb:54:in `run_initializers'
    /home/manish/Desktop/projects/rails/manish/rails/railties/lib/rails/application.rb:352:in `initialize!'
    /tmp/d20150529-9297-103tev/app/config/environment.rb:5:in `<top (required)>'
    /home/manish/Desktop/projects/rails/manish/rails/railties/test/isolation/abstract_unit.rb:54:in `require'
    /home/manish/Desktop/projects/rails/manish/rails/railties/test/isolation/abstract_unit.rb:54:in `app'
    test/application/middleware/exceptions_test.rb:78:in `block in <class:MiddlewareExceptionsTest>'

8 runs, 0 assertions, 0 failures, 8 errors, 0 skips
rake aborted!
Command failed with status (1): [/home/manish/.rvm/rubies/ruby-2.2.2/bin/ru...]
/home/manish/Desktop/projects/rails/manish/rails/railties/Rakefile:21:in `block (3 levels) in <top (required)>'
/home/manish/Desktop/projects/rails/manish/rails/railties/Rakefile:12:in `each'
/home/manish/Desktop/projects/rails/manish/rails/railties/Rakefile:12:in `block (2 levels) in <top (required)>'
Tasks: TOP => test => test:isolated
(See full trace by running task with --trace)

```

At the end of test It also says :
```
Errors in actionview, activerecord, railties
/home/manish/Desktop/projects/rails/manish/rails/Rakefile:26:in `block (2 levels) in <top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by repinel** [comment]
Related to #19878
