### ISSUE TITLE
Model.where(id: 123456789013333333332345) raises RangeError: 123456789013333333332345 is out of range for ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer with limit 4

### ISSUE THREAD

**Issue by joevandyk** [rails/rails#20428]
```
Loading development environment (Rails 4.2.2.beta)
irb(main):001:0> huge = 123456789013333333332345
=> 123456789013333333332345

# An exception of ActiveRecord::RecordNotFound right to me
irb(main):002:0> Product.find(huge)
ActiveRecord::RecordNotFound: Couldn't find Product with an out of range value for 'id'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/core.rb:159:in `rescue in find'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/core.rb:128:in `find'
	from (irb):2
	from /disk/tanga/current/shared/gems/rails/railties/lib/rails/commands/console.rb:110:in `start'
	from /disk/tanga/current/shared/gems/rails/railties/lib/rails/commands/console.rb:9:in `start'
	from /disk/tanga/current/shared/gems/rails/railties/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /disk/tanga/current/shared/gems/rails/railties/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /disk/tanga/current/shared/gems/rails/railties/lib/rails/commands.rb:17:in `<top (required)>'
	from ./bin/rails:4:in `require'
	from ./bin/rails:4:in `<main>'

# This also looks good to me
irb(main):003:0> Product.find_by(id: huge)
=> nil

# This doesn't look as good. Seems like you'd expect it to match the behavior of `find_by` ?
irb(main):004:0> Product.where(id: huge)
RangeError: 123456789013333333332345 is out of range for ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer with limit 4
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/type/integer.rb:45:in `ensure_in_range'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/type/integer.rb:23:in `type_cast_for_database'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:13:in `quote'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:116:in `block in compile'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:116:in `map'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:116:in `compile'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:13:in `to_sql'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/querying.rb:39:in `find_by_sql'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/relation.rb:638:in `exec_queries'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/relation.rb:514:in `load'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/relation.rb:243:in `to_a'
	from /disk/tanga/current/shared/gems/rails/activerecord/lib/active_record/relation.rb:629:in `inspect'
	from /disk/tanga/current/shared/gems/rails/railties/lib/rails/commands/console.rb:110:in `start'
	from /disk/tanga/current/shared/gems/rails/railties/lib/rails/commands/console.rb:9:in `start'
	from /disk/tanga/current/shared/gems/rails/railties/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /disk/tanga/current/shared/gems/rails/railties/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /disk/tanga/current/shared/gems/rails/railties/lib/rails/commands.rb:17:in `<top (required)>'
	from ./bin/rails:4:in `require'
	from ./bin/rails:4:in `<main>'irb(main):005:0>
```

**Comment by joevandyk** [comment]
I'm not sure if this should be considered a bug or not. But it was suprising.

**Comment by chancancode** [comment]
This is basically a "bug" that we have no good way to completely fix, and the current situation is a compromise: see #19717 and the original issues linked within. Let's keep the discussion there.

Basically I agree that it's not ideal, but unfortunately we don't have a better solution at the moment

**Comment by joevandyk** [comment]
Thanks!

**Comment by CarlosCD** [comment]
I know the issue was closed some time ago, and there was a fix by @sgrif for the case of `find` and `find_by_id` (issues #17380, #17459), and it was also discussed in detail at #19717. I've just wanted to point out that unfortunately the issue still happens for `where(id: ?)`, generating a 500 instead a 404.

Yesterday someone manually build an URI with a very large id to hit our Rails 4.2.5 site (call me paranoid, but probably looking for ways to hack the site). Of course, got a 500 (RangeError). This person tried 7 times.

My guess is that the only option to prevent this is to check the validity of the params within the app. Adding a fix today.

Thanks!

**Comment by maurosbu** [comment]
Same issue here! 
Wouldn't be better to return an empty relation set when filtering by an integer that is out of the range?

Thanks!

**Comment by RachelScodes** [comment]
hey @CarlosCD, how did you validate the params? Having a similar issue.

**Comment by PikachuEXE** [comment]
My stupid way

```ruby
def with_ids_only(ids)
  processed_ids = ids.map do |id|
    id_in_int = if id.is_a?(::String)
      next nil unless id =~ /^\d$/
      Integer(id)
    else
      id
    end

    (1..2_147_483_647).cover?(id_in_int) ? id_in_int : nil
  end.compact

  where(id: processed_ids)
end
```

Only works for id with integer type, limit 4
