### ISSUE TITLE
Rails 4.2, engine skeleton testing issues warning: previous definition of STATS_DIRECTORIES was here

### ISSUE THREAD

**Issue by jrochkind** [rails/rails#20510]
~~~bash
$ rails -v
Rails 4.2.1
$ rails plugin new --mountable rails42_mountable_engine

[...]

$ cd rails42_mountable_engine/
$ bundle exec rake test
/Users/jrochkind/.gem/ruby/2.2.2/gems/railties-4.2.1/lib/rails/tasks/statistics.rake:4: warning: already initialized constant STATS_DIRECTORIES
/Users/jrochkind/.gem/ruby/2.2.2/gems/railties-4.2.1/lib/rails/tasks/statistics.rake:4: warning: previous definition of STATS_DIRECTORIES was here
/Users/jrochkind/code/rails42_mountable_engine/test/dummy/db/schema.rb doesn't exist yet. Run `rake db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/jrochkind/code/rails42_mountable_engine/test/dummy/config/application.rb to limit the frameworks that will be loaded.
Run options: --seed 2894

# Running:

.

Finished in 0.003765s, 265.5704 runs/s, 265.5704 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
~~~

Note warning otuput in the above: `railties-4.2.1/lib/rails/tasks/statistics.rake:4: warning: already initialized constant STATS_DIRECTORIES...   railties-4.2.1/lib/rails/tasks/statistics.rake:4: warning: previous definition of STATS_DIRECTORIES was here`

This seems like something ain't right, I should not need to look at that warning in my output every time I run engine tests.

**Comment by fenec** [comment]
The thing is 'rails/tasks/statistics.rake' now loaded for engines. That was introduced here: https://github.com/rails/rails/commit/b71f5f4f55f50bf215a650c0555f6603a3bed84b
And when you run rake:test, Rakefile in dummy app calls Rails.application.load_tasks which loads the same task again.
I'm looking for a solution now.

**Comment by fenec** [comment]
So I didn't find any adequate solutions for this. Not sure if memoization will work in this case.

**Comment by jrochkind** [comment]
Some ideas...

Is it possible to somehow move the `STATS_DIRECTORIES` definition to another file, that gets `require`ed by the Rake task?  If it were possible, then even if the rake task itself were loaded twice, the file that's `require`ed should only be loaded once (since that's what `require` ensures), avoiding the constant being defined twice and generated the warning. 

I'm not sure if there's any way to do that with a Rake task that won't be a mess though. 

Alternately, why does `STATS_DIRECTORIES` have to be a contant?  If you even made it a global `$stats_directories` instead, that would avoid the constant redefinition warning too. 

Or, the simplest hackiest way to avoid definining `STATS_DIRECTORIES` twice is to initialize it as `STATS_DIRECTORIES ||= ....` instead.  This does work on constants. 

All of this, though, is just focused at avoiding definining a constant twice when you load the same Rake task twice, to avoid the warning.  But I worry there may be other more subtle unfortunate side effects of loading the same rake file twice -- most rake files aren't really designed to be loaded twice, I wonder if there's other hidden global state somewhere that will get in a mess.  But there doesn't seem to be any good way of avoiding that in this situation, without getting into more complex refactorings of rake itself.

**Comment by trendwithin** [comment]
I stumbled across this post since I am having the same issue while following a tutorial and am unsure what to do about this.  Including the output of `rake db:migrate`, `rake routes --trace` and `rake --trace` in case it is of assistance.

```
~/p/shop_engine_playground code ✖ rails -v
Rails 4.2.3
~/p/shop_engine_playground code ✖ rake db:migrate
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/tasks/statistics.rake:4: warning: already initialized constant STATS_DIRECTORIES
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/tasks/statistics.rake:4: warning: previous definition of STATS_DIRECTORIES was here
```

```
~/p/shop_engine_playground code ✖ rake routes --trace
** Invoke load_app (first_time)
** Execute load_app
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/tasks/statistics.rake:4: warning: already initialized constant STATS_DIRECTORIES
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/tasks/statistics.rake:4: warning: previous definition of STATS_DIRECTORIES was here
rake aborted!
Don't know how to build task 'routes'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task_manager.rb:62:in `[]'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:149:in `invoke_task'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

```
~/p/shop_engine_playground code ✖ rake --trace
** Invoke load_app (first_time)
** Execute load_app
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/tasks/statistics.rake:4: warning: already initialized constant STATS_DIRECTORIES
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/tasks/statistics.rake:4: warning: previous definition of STATS_DIRECTORIES was here
** Invoke default (first_time)
** Invoke test (first_time)
** Execute test
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:392:in `check_pending!':  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

	bin/rake db:migrate RAILS_ENV=test

	from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:405:in `load_schema_if_pending!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:411:in `block in maintain_test_schema!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:639:in `suppress_messages'
	from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:416:in `method_missing'
	from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:411:in `maintain_test_schema!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/test_help.rb:19:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/Strawman/playground/shop_engine_playground/test/test_helper.rb:7:in `<top (required)>'
	from /Users/Strawman/playground/shop_engine_playground/test/controllers/shop_engine_playground/categories_controller_test.rb:1:in `require'
	from /Users/Strawman/playground/shop_engine_playground/test/controllers/shop_engine_playground/categories_controller_test.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:10:in `require'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:9:in `each'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:9:in `block in <main>'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test"  "/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/**/*_test.rb" ]
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/testtask.rb:108:in `block (3 levels) in define'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/file_utils.rb:57:in `call'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/file_utils.rb:57:in `sh'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `sh'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/file_utils.rb:96:in `ruby'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `ruby'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/testtask.rb:104:in `block (2 levels) in define'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/file_utils_ext.rb:58:in `verbose'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/testtask.rb:100:in `block in define'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => default => test
```

**Comment by nsarno** [comment]
Like @fenec suggested, memoization seems like a good fix.

I replaced `STATS_DIRECTORIES = ...` with `STATS_DIRECTORIES ||= ...` locally and it works well.

Any reason not to do this?

**Comment by trendwithin** [comment]
Arnaud,

Thank you for the response.  It wasn’t clear to me how to achieve this.  I wasn’t sure if this had to be altered
in a gem (and which one) or could be done in the Rakefile, so I put it on the back burner since I was just trying to follow along with
a tutorial.  Now that I’m reminded of this I’ll ask questions at the meet up I’m going to tomorrow.

Regards,
Michael

**Comment by earksiinni** [comment]
I've run into this problem, as well. I've written a patch to fix this, but this is my first time working on the Rails codebase and I don't know what the protocol is for committing code. Should I post the patch here first before issuing a pull request...?

**Comment by earksiinni** [comment]
To add more detail, the problem is that the test app invokes `railties/lib/rails/tasks.rb`, which in turn loads `statistics.rake`, before the engine's `Rakefile` can load `statistics.rake`. The precedence doesn't have any bearing on the warning, because regardless of which call comes first the `STATS_DIRECTORIES` constant is attempting to be defined twice.

However, the precedence does make it trickier to solve if you want to prevent the test app from loading the `statistics.rake` altogether, which I believe is the correct solution. `tasks.rb` needs to be aware of when it's being run from within the engine's context vs. when it's being run within its own context.

My solution is to only load the statistics file if `Rake.application.current_scope.empty?` evaluates to true. When the app is a test app under the engine, the Rake's current scope evaluates to `'app'`.
