### ISSUE TITLE
Arel - RuntimeError - unsupported: Hash: when using select on associations

### ISSUE THREAD

**Issue by derrickmar** [rails/rails#20639]
Upgrading from Rails 4.1 to 4.2.2 leads to an error when using Active Record Query Interface ```select``` on associations.

```ruby
QuestionSubmission.joins(:rubric_item_evaluations).select({rubric_item_evaluations: [:present, :rubric_item_id]})
```

Does anyone know a fix?

Full stack trace
```
02:36:35 guard.1       | RuntimeError - unsupported: Hash:
02:36:35 guard.1       |   arel (6.0.0) lib/arel/visitors/to_sql.rb:729:in `unsupported'
02:36:35 guard.1       |   arel (6.0.0) lib/arel/visitors/reduce.rb:13:in `visit'
02:36:35 guard.1       |   arel (6.0.0) lib/arel/visitors/to_sql.rb:241:in `block in visit_Arel_Nodes_SelectCore'
02:36:35 guard.1       |   arel (6.0.0) lib/arel/visitors/to_sql.rb:240:in `visit_Arel_Nodes_SelectCore'
02:36:35 guard.1       |   arel (6.0.0) lib/arel/visitors/to_sql.rb:210:in `block in visit_Arel_Nodes_SelectStatement'
02:36:35 guard.1       |   arel (6.0.0) lib/arel/visitors/to_sql.rb:209:in `visit_Arel_Nodes_SelectStatement'
02:36:35 guard.1       |   arel (6.0.0) lib/arel/visitors/reduce.rb:13:in `visit'
02:36:35 guard.1       |   arel (6.0.0) lib/arel/visitors/reduce.rb:7:in `accept'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/database_statements.rb:12:in `to_sql'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/querying.rb:39:in `find_by_sql'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/relation.rb:638:in `exec_queries'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/relation.rb:514:in `load'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/relation.rb:243:in `to_a'
02:36:35 guard.1       |   bullet (4.14.7) lib/bullet/active_record42.rb:29:in `to_a'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/relation/delegation.rb:46:in `each'
02:36:35 guard.1       |   app/controllers/rubric_items_controller.rb:52:in `block in update'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/transactions.rb:220:in `transaction'
02:36:35 guard.1       |   app/controllers/rubric_items_controller.rb:51:in `update'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
02:36:35 guard.1       |   actionpack (4.2.2) lib/abstract_controller/base.rb:198:in `process_action'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
02:36:35 guard.1       |   actionpack (4.2.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/callbacks.rb:92:in `_run_callbacks'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
02:36:35 guard.1       |   actionpack (4.2.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
02:36:35 guard.1       |   actionpack (4.2.2) lib/abstract_controller/base.rb:137:in `process'
02:36:35 guard.1       |   actionview (4.2.2) lib/action_view/rendering.rb:30:in `process'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_controller/metal.rb:196:in `dispatch'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_controller/metal.rb:237:in `block in action'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
02:36:35 guard.1       |   omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
02:36:35 guard.1       |   omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
02:36:35 guard.1       |   omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
02:36:35 guard.1       |   omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
02:36:35 guard.1       |   omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
02:36:35 guard.1       |   meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
02:36:35 guard.1       |   meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
02:36:35 guard.1       |   bullet (4.14.7) lib/bullet/rack.rb:12:in `call'
02:36:35 guard.1       |   rack-livereload (0.3.15) lib/rack/livereload.rb:23:in `_call'
02:36:35 guard.1       |   rack-livereload (0.3.15) lib/rack/livereload.rb:14:in `call'
02:36:35 guard.1       |   rack (1.6.2) lib/rack/etag.rb:24:in `call'
02:36:35 guard.1       |   rack (1.6.2) lib/rack/conditionalget.rb:38:in `call'
02:36:35 guard.1       |   rack (1.6.2) lib/rack/head.rb:13:in `call'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
02:36:35 guard.1       |   rack (1.6.2) lib/rack/session/abstract/id.rb:225:in `context'
02:36:35 guard.1       |   rack (1.6.2) lib/rack/session/abstract/id.rb:220:in `call'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/query_cache.rb:36:in `call'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
02:36:35 guard.1       |   activerecord (4.2.2) lib/active_record/migration.rb:378:in `call'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
02:36:35 guard.1       |   bugsnag (2.7.1) lib/bugsnag/rack.rb:36:in `call'
02:36:35 guard.1       |   better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
02:36:35 guard.1       |   better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
02:36:35 guard.1       |   better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
02:36:35 guard.1       |   rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
02:36:35 guard.1       |   meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
02:36:35 guard.1       |   railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
02:36:35 guard.1       |   railties (4.2.2) lib/rails/rack/logger.rb:22:in `call'
02:36:35 guard.1       |   config/initializers/quiet_assets.rb:7:in `call_with_quiet_assets'
02:36:35 guard.1       |   request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
02:36:35 guard.1       |   rack (1.6.2) lib/rack/methodoverride.rb:22:in `call'
02:36:35 guard.1       |   rack (1.6.2) lib/rack/runtime.rb:18:in `call'
02:36:35 guard.1       |   activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
02:36:35 guard.1       |   rack (1.6.2) lib/rack/lock.rb:17:in `call'
02:36:35 guard.1       |   actionpack (4.2.2) lib/action_dispatch/middleware/static.rb:113:in `call'
02:36:35 guard.1       |   rack (1.6.2) lib/rack/sendfile.rb:113:in `call'
02:36:35 guard.1       |   railties (4.2.2) lib/rails/engine.rb:518:in `call'
02:36:35 guard.1       |   railties (4.2.2) lib/rails/application.rb:164:in `call'
02:36:35 guard.1       |   rack (1.6.2) lib/rack/content_length.rb:15:in `call'
02:36:35 guard.1       |   unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
02:36:35 guard.1       |   unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
02:36:35 guard.1       |   unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
02:36:35 guard.1       |   unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
02:36:35 guard.1       |   unicorn-rails (2.2.0) lib/unicorn_rails.rb:33:in `run'
02:36:35 guard.1       |   rack (1.6.2) lib/rack/server.rb:286:in `start'
02:36:35 guard.1       |   railties (4.2.2) lib/rails/commands/server.rb:80:in `start'
02:36:35 guard.1       |   railties (4.2.2) lib/rails/commands/commands_tasks.rb:80:in `block in server'
02:36:35 guard.1       |   railties (4.2.2) lib/rails/commands/commands_tasks.rb:75:in `server'
02:36:35 guard.1       |   railties (4.2.2) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
02:36:35 guard.1       |   railties (4.2.2) lib/rails/commands.rb:17:in `<top (required)>'
02:36:35 guard.1       |   bin/rails:8:in `<top (required)>'
02:36:35 guard.1       |   spring (1.3.4) lib/spring/client/rails.rb:28:in `call'
02:36:35 guard.1       |   spring (1.3.4) lib/spring/client/command.rb:7:in `call'
02:36:35 guard.1       |   spring (1.3.4) lib/spring/client.rb:26:in `run'
02:36:35 guard.1       |   spring (1.3.4) bin/spring:48:in `<top (required)>'
02:36:35 guard.1       |   spring (1.3.4) lib/spring/binstub.rb:11:in `<top (required)>'
02:36:35 guard.1       |   bin/spring:13:in `<top (required)>'
02:36:35 guard.1       |   bin/rails:3:in `<main>'
```

**Comment by sgrif** [comment]
We do not support passing a hash to `select`. For feature requests, feel free to ping the rails core mailing list.

**Comment by derrickmar** [comment]
Thank you @sgrif

**Comment by ddfznt** [comment]
@sgrif is there any particular reason to remove support for hashes? despite not being properly document the use of hashes was an excellent approach to mitigate SQL injection, sad to read this.
