### ISSUE TITLE
v4.2.3 `has_transactional_callbacks?` returns false then one of Oracle enhanced unit test gets failed

### ISSUE THREAD

**Issue by yahonda** [rails/rails#20730]
This issue has been reported as https://github.com/rsim/oracle-enhanced/issues/640 
One of Oracle enhanced adapter unit tests fail after upgrading from v4.2.2 to v4.2.3.

Doing git bisect and found by reverting https://github.com/rails/rails/commit/9ddb9553e336219dcdfe2bdda6120359e33300ee this test successfully finishes. https://github.com/rails/rails/issues/15549

Although I do not have a testcase without using Oracle enhanced adapter, here are what I've found so far.

In v4.2.2

- `has_transactional_callbacks?` returns `true` since `!_create_callbacks.empty?` is true.
Both `!_rollback_callbacks.empty?` and `!_commit_callbacks.empty?` returns false.

- Always `@reflects_state = [false]`

v4.2.3

- `has_transactional_callbacks?` returns `false` since `!_create_callbacks.empty?` has gone
from `has_transactional_callbacks?`. Both `!_rollback_callbacks.empty?` and `!_commit_callbacks.empty?` returns false.

- `@reflects_state = [false]` since `depth == 0` always satisfied in this test case.

Then I think it gets failed in v4.2.3 when `!_create_callbacks.empty?` is true and `depth == 0`

Here is Oracle enhanced testcase.
```ruby
$ rspec ./spec/active_record/connection_adapters/
==> Loading config from ENV or use default
==> Running specs with MRI version 2.2.2
==> Selected Rails version 4.0-master
==> Effective ActiveRecord version 4.2.3
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb"=>[177]}}
F

Failures:

  1) OracleEnhancedAdapter custom methods for create, update and destroy should rollback record when exception is raised in after_create callback
     Failure/Error: @employee.id.should == nil
       expected: nil
            got: 1 (using ==)
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-expectations-2.99.2/lib/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-expectations-2.99.2/lib/rspec/matchers/operator_matcher.rb:57:in `fail_with_message'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-expectations-2.99.2/lib/rspec/matchers/operator_matcher.rb:98:in `__delegate_operator'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-expectations-2.99.2/lib/rspec/matchers/operator_matcher.rb:89:in `eval_match'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-expectations-2.99.2/lib/rspec/matchers/operator_matcher.rb:38:in `block in use_custom_matcher_or_delegate'
     # ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:189:in `block (2 levels) in <top (required)>'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_exec'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_eval_with_args'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example.rb:116:in `block in run'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example.rb:248:in `with_around_each_hooks'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example.rb:113:in `run'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:515:in `block in run_examples'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:511:in `map'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:511:in `run_examples'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:496:in `run'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:24:in `block (2 levels) in run'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:24:in `map'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:24:in `block in run'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/reporter.rb:58:in `report'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:21:in `run'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
     # /home/yahonda/.rvm/gems/ruby-2.2.2@rails42/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `block in autorun'

Finished in 0.47619 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb:177 # OracleEnhancedAdapter custom methods for create, update and destroy should rollback record when exception is raised in after_create callback
$
```

**Comment by chancancode** [comment]
cc @arthurnn

**Comment by arthurnn** [comment]
I dont think this is a Rails issue, lets move the conversation to https://github.com/rsim/oracle-enhanced/issues/640 , and I will explain there.

**Comment by arthurnn** [comment]
Actually, nvm. I need to simulate this error better to see if it is not a Rails bug indeed.

**Comment by yahonda** [comment]
Thanks for the update. What I can say is this issue has been triggered by https://github.com/rails/rails/commit/9ddb9553e336219dcdfe2bdda6120359e33300ee . Wanted to know how to address it whichever Rails or Oracle enhanced adapter.

**Comment by yahonda** [comment]
Closing since it does not reproduce anymore. Thanks.
