### ISSUE TITLE
Subselect with polymorphic association produces invalid query in version 4.2.3

### ISSUE THREAD

**Issue by yossi-shasho** [rails/rails#20863]
After upgrading to 4.2.3 (using ruby 2.2.2), several queries have stopped working.These queries all involved a subselect on a polymorphic table. This is looks like a regression.

I've created a canonical rails project that demonstrates the bug: https://github.com/yossi-shasho/railsbug
it contains a single rspec that fails, but it passes when downgrading Rails back to 4.1.6.

### The models
```ruby
class User < ActiveRecord::Base
  has_many :projects

  # This method used to work before the upgrade
  def self.users_with_own_tasks
    User
    .where(
        Project
        .joins(:tasks)
        .where('users.email = tasks.email')
        .exists
    )
    .distinct
  end
end

class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, as: :taskable
end

class Task < ActiveRecord::Base
  belongs_to :taskable, polymorphic: true
end
```

### The failing spec that demonstrates the problem
`#user_spec.rb`
```ruby
require 'rails_helper'
RSpec.describe User, type: :model do
  before :each do
    @user = User.create! email: 'rails@bug.com'
    @project = Project.create! user: @user
  end

  # fails when using Rails 4.2.3, works on 4.1.6
  describe '#user_with_own_tasks' do
    it 'should find a user that has a project with a task that has it\'s own email' do
      @task = Task.create! taskable: @project, email: @user.email
      expect(User.user_with_own_tasks).to eq [@user]
    end
  end
end
```
### The error message
`$ rspec spec/models/user_spec.rb`
```rspec
F

Failures:

  1) User#user_with_own_tasks should find a user that has a project with a task that has it's own email
     Failure/Error: expect(User.user_with_own_tasks(@user.email)).to eq [@user]
     ActiveRecord::StatementInvalid:
       PG::ProtocolViolation: ERROR:  bind message supplies 0 parameters, but prepared statement "" requires 1
       : SELECT DISTINCT "users".* FROM "users" WHERE (EXISTS (SELECT "projects".* FROM "projects" INNER JOIN "tasks" ON "tasks"."taskable_id" = "projects"."id" AND "tasks"."taskable_type" = $1 WHERE (users.email = tasks.email)))
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `async_exec'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `block in exec_no_cache'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `exec_no_cache'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:588:in `execute_and_clear'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:351:in `select'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/querying.rb:39:in `find_by_sql'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/relation.rb:638:in `exec_queries'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/relation.rb:514:in `load'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/relation.rb:243:in `to_a'
     # /Users/yossishasho/.rvm/gems/ruby-2.2.2@rails4.2.3/gems/activerecord-4.2.3/lib/active_record/relation.rb:611:in `=='
     # ./spec/models/user_spec.rb:13:in `block (3 levels) in <top (required)>'

Finished in 0.06929 seconds (files took 1.51 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/models/user_spec.rb:11 # User#user_with_own_tasks should find a user that has a project with a task that has it's own email
```
This demo project is available here: https://github.com/yossi-shasho/railsbug

**Comment by tal-moshayov** [comment]
+1

**Comment by sgrif** [comment]
@yossi-shasho Thanks for the report, I'll look into it. For future reference, bug reports that use [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) are preferable for bugs such as this.

@tal-moshayov Please do not +1 issues, they do not achieve anything, and add unnecessary noise to our already crowded inboxes.

**Comment by sgrif** [comment]
This isn't a supported use case. The `exists` method isn't part of the public API for `Relation`. It's forwarding it to Arel, but that is considered internal, and relying on it may break between versions without warning. The only supported methods are those documented at api.rubyonrails.org.

**Comment by ippeiukai** [comment]
@yossi-shasho 
I encountered a similar incompatibility with `relation.where(relation2.exists)` usage upgrading to Rails 4.2.3 + PostgreSQL. One easy alternative is to write `relation.where("EXISTS (#{relation2.to_sql})")`. In fact that's how I used to write before started using this trick.

BTW, the error is probably more to do with having binding values in both parent relation and subquery arel, not just type columns of polymorphic association:

```Ruby
relation = User.where(display_name: 'ippei'); nil
relation2 = UserGithubAccount.where(login: 'ippeiukai').where('user_github_accounts.user_id = users.id'); nil
puts relation.arel.to_sql
 # SELECT "users".* FROM "users" WHERE "users"."display_name" = $1
puts relation2.arel.to_sql
 # SELECT "user_github_accounts".* FROM "user_github_accounts" WHERE "user_github_accounts"."login" = $1 AND (user_github_accounts.user_id = users.id)
puts relation.where(relation2.exists).arel.to_sql
 # SELECT "users".* FROM "users" WHERE "users"."display_name" = $1 AND (EXISTS (SELECT "user_github_accounts".* FROM "user_github_accounts" WHERE "user_github_accounts"."login" = $2 AND (user_github_accounts.user_id = users.id)))
relation.where(relation2.exists).exists?
 # !! ActiveRecord::StatementInvalid: PG::ProtocolViolation: ERROR:  bind message supplies 1 parameters, but prepared statement "a1" requires 2
relation.where("EXISTS (#{relation2.to_sql})").exists?
 # => true
```

**Comment by ippeiukai** [comment]
A permanent solution seems already on its way: #16959
