### ISSUE TITLE
capistrano deployment error - NameError: uninitialized constant Rails::Application::YAML

### ISSUE THREAD

**Issue by goodviber** [rails/rails#20875]
When following my normal capistrano deployment process with rails 4.2.1, I encountered this error. Adding require 'yaml' in various config files did not resolve the error.

```
INFO [9c9515ab] Running ~/.rvm/bin/rvm default do bundle exec rake assets:precompile as deploy@46.101.62.128
DEBUG [9c9515ab] Command: cd /home/deploy/bonzer/releases/20150714050947 && ( RAILS_ENV=production ~/.rvm/bin/rvm default do bundle exec rake assets:precompile )
DEBUG [9c9515ab] 	[32mRVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	you can ignore these warnings with 'rvm rvmrc warning ignore /home/deploy/bonzer/releases/20150714050947/Gemfile'.
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	[0m
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	rake aborted!
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	NameError: uninitialized constant Rails::Application::YAML
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/application.rb:391:in `secrets'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/releases/20150714050947/config/environments/production.rb:76:in `block in <top (required)>'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `instance_eval'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `configure'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/releases/20150714050947/config/environments/production.rb:1:in `<top (required)>'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/engine.rb:597:in `each'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/engine.rb:597:in `block in <class:Engine>'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `each'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/releases/20150714050947/config/environment.rb:5:in `<top (required)>'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/application.rb:328:in `require'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/railti
DEBUG [9c9515ab] 	es-4.2.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	/home/deploy/bonzer/shared/bundle/ruby/2.1.0/gems/sprockets-rails-2.3.1/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	Tasks: TOP => environment
DEBUG [9c9515ab] 	
DEBUG [9c9515ab] 	(See full trace by running task with --trace)
```

On the server, at ~/my_app/shared/bundle/ruby/2.1.0/gems/railties-4.2.1/lib/rails/application.rb I have added **require "yaml"** at line 390. This resolves the error.

    def secrets
      @secrets ||= begin
        secrets = ActiveSupport::OrderedOptions.new
        yaml = config.paths["config/secrets"].first
        if File.exist?(yaml)
          require "yaml"
          require "erb"
          all_secrets = YAML.load(ERB.new(IO.read(yaml)).result) || {}
          env_secrets = all_secrets[Rails.env]
          secrets.merge!(env_secrets.symbolize_keys) if env_secrets
        end

        # Fallback to config.secret_key_base if secrets.secret_key_base isn't set
        secrets.secret_key_base ||= config.secret_key_base
        # Fallback to config.secret_token if secrets.secret_token isn't set
        secrets.secret_token ||= config.secret_token

        secrets
      end
    end

**Comment by rafaelfranca** [comment]
Make sure you are using Rails 4.2.3 that fixes this issue
