### ISSUE TITLE
Errors in initializer causes `rails server` to fail with unknown command

### ISSUE THREAD

**Issue by brightbits** [rails/rails#20914]
The error is swallowed and `rails server` shows usage/invalid params error

```
➜  rails server -p 5100
=> Booting Puma
=> Rails 4.2.0 application starting in development on http://0.0.0.0:5100
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
Error: Command '-p' not recognized
Usage: rails COMMAND [ARGS]
```

Easy way to reproduce is to `require` an invalid file in an initializer.

**Comment by rafaelfranca** [comment]
I tried to reproduce with a new Rails 4.2.3 application and puma and could not. Let us know if you find an way to reproduce it.

**Comment by aledalgrande** [comment]
Not an initializer case, but try to install `delayed_job` in the `Gemfile`, setup a class as a subclass of `ActiveJob::Base`, then comment out `delayed_job` in the `Gemfile`.

If you run `rails s -p 5000`:
```
=> Booting WEBrick
=> Rails 4.2.4 application starting in development on http://localhost:5000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
bin/rails:6: warning: already initialized constant APP_PATH
/Users/xxx/bin/rails:6: warning: previous definition of APP_PATH was here
Error: Command '-p' not recognized
Usage: rails COMMAND [ARGS]

The most common rails commands are:
 generate    Generate new code (short-cut alias: "g")
 console     Start the Rails console (short-cut alias: "c")
 server      Start the Rails server (short-cut alias: "s")
 dbconsole   Start a console for the database specified in config/database.yml
             (short-cut alias: "db")
 new         Create a new Rails application. "rails new my_app" creates a
             new application called MyApp in "./my_app"

In addition to those, there are:
 destroy      Undo code generated with "generate" (short-cut alias: "d")
 plugin new   Generates skeleton for developing a Rails plugin
 runner       Run a piece of code in the application environment (short-cut alias: "r")
```

If you run `rails c`:
```
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require': No such file to load -- delayed_job (LoadError)
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:238:in `block in load_dependency'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:238:in `load_dependency'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activejob-4.2.4/lib/active_job/queue_adapters/delayed_job_adapter.rb:1:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:238:in `block in load_dependency'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:238:in `load_dependency'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:263:in `const_get'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:263:in `block in constantize'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `inject'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activejob-4.2.4/lib/active_job/queue_adapter.rb:31:in `load_adapter'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activejob-4.2.4/lib/active_job/queue_adapter.rb:23:in `queue_adapter='
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activejob-4.2.4/lib/active_job/railtie.rb:18:in `block (3 levels) in <class:Railtie>'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activejob-4.2.4/lib/active_job/railtie.rb:18:in `each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activejob-4.2.4/lib/active_job/railtie.rb:18:in `block (2 levels) in <class:Railtie>'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activejob-4.2.4/lib/active_job/base.rb:66:in `<class:Base>'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activejob-4.2.4/lib/active_job/base.rb:56:in `<module:ActiveJob>'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activejob-4.2.4/lib/active_job/base.rb:10:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:238:in `block in load_dependency'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:238:in `load_dependency'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/xxx/app/jobs/compliance_updater_job.rb:1:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `load'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:456:in `load_file'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:317:in `depend_on'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:233:in `require_dependency'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:471:in `each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:471:in `block in eager_load!'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:469:in `each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:469:in `eager_load!'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:346:in `eager_load!'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/application/finisher.rb:56:in `each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
	from /Users/xxx/config/environment.rb:5:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:92:in `preload'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:143:in `serve'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by utilum** [comment]
I tried to reproduce with Rails 4.2.0, both with an initializer and with the delayed job... could not reproduce.

**Comment by aledalgrande** [comment]
Did you also add `config.active_job.queue_adapter = :delayed_job` to the configuration?

**Comment by utilum** [comment]
I did. Also ran bundle install after commenting out `gem "delayed_job"`. In fact, the server starts as happy as ever. Will you provide a demo?

**Comment by aledalgrande** [comment]
Let me see if I can strip down this app so it can be a minimal repro case.
