### ISSUE TITLE
NameError: instance variable @version not defined when tested with MySQL  5.7.7-rc

### ISSUE THREAD

**Issue by yahonda** [rails/rails#20969]
Tested with MySQL  5.7.7-rc, `test_quoted_date_precision_for_gte_564` and `test_quoted_date_precision_for_lt_564` get errors. Here are steps to reproduce.

### Environment

- ruby 2.2.2
```ruby
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
```
- MySQL 5.7.7.rc
```sql
mysql> select @@version;
+-----------+
| @@version |
+-----------+
| 5.7.7-rc  |
+-----------+
1 row in set (0.00 sec)

mysql>
```

- Rails master branch

### Steps to reproduce

- mysql adapter
```ruby
cd activerecord
ARCONN=mysql ruby -w -I"lib:test"  "/home/yahonda/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/cases/primary_keys_test.rb" "test/cases/adapters/mysql/quoting_test.rb"
```
- mysql adapter results
```rub
Using mysql
Run options: --seed 51358

# Running:

.................................EE

Finished in 1.231732s, 28.4153 runs/s, 38.9695 assertions/s.

  1) Error:
MysqlQuotingTest#test_quoted_date_precision_for_gte_564:
NameError: instance variable @version not defined
    /home/yahonda/git/rails/activerecord/test/cases/adapters/mysql/quoting_test.rb:18:in `remove_instance_variable'
    /home/yahonda/git/rails/activerecord/test/cases/adapters/mysql/quoting_test.rb:18:in `test_quoted_date_precision_for_gte_564'


  2) Error:
MysqlQuotingTest#test_quoted_date_precision_for_lt_564:
NameError: instance variable @version not defined
    /home/yahonda/git/rails/activerecord/test/cases/adapters/mysql/quoting_test.rb:25:in `remove_instance_variable'
    /home/yahonda/git/rails/activerecord/test/cases/adapters/mysql/quoting_test.rb:25:in `test_quoted_date_precision_for_lt_564'

35 runs, 48 assertions, 0 failures, 2 errors, 0 skips
```
- mysql2 adapter
```ruby
ARCONN=mysql2 ruby -w -I"lib:test"  "/home/yahonda/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/cases/primary_keys_test.rb" "test/cases/adapters/mysql2/quoting_test.rb"
```
- mysql2 adapter results
```ruby
Using mysql2
Run options: --seed 53748

# Running:

...............................EE

Finished in 1.289287s, 25.5955 runs/s, 35.6786 assertions/s.

  1) Error:
Mysql2QuotingTest#test_quoted_date_precision_for_lt_5.6.4:
NameError: instance variable @version not defined
    /home/yahonda/git/rails/activerecord/test/cases/adapters/mysql2/quoting_test.rb:17:in `remove_instance_variable'
    /home/yahonda/git/rails/activerecord/test/cases/adapters/mysql2/quoting_test.rb:17:in `block in <class:Mysql2QuotingTest>'


  2) Error:
Mysql2QuotingTest#test_quoted_date_precision_for_gte_5.6.4:
NameError: instance variable @version not defined
    /home/yahonda/git/rails/activerecord/test/cases/adapters/mysql2/quoting_test.rb:10:in `remove_instance_variable'
    /home/yahonda/git/rails/activerecord/test/cases/adapters/mysql2/quoting_test.rb:10:in `block in <class:Mysql2QuotingTest>'

33 runs, 46 assertions, 0 failures, 2 errors, 0 skips

```

### These errors do NOT reproduce

- Switch the order of quoting_test.rb and primary_keys_test.rb
```ruby
ARCONN=mysql ruby -w -I"lib:test"  "/home/yahonda/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/cases/adapters/mysql/quoting_test.rb" "test/cases/primary_keys_test.rb" 
```
```ruby
ARCONN=mysql2 ruby -w -I"lib:test"  "/home/yahonda/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/cases/adapters/mysql2/quoting_test.rb" "test/cases/primary_keys_test.rb" 
```

- Remove rake_test_loader.rb
```ruby
ARCONN=mysql ruby -w -Itest "test/cases/primary_keys_test.rb" "test/cases/adapters/mysql/quoting_test.rb"
```
```ruby
ARCONN=mysql2 ruby -w -Itest "test/cases/primary_keys_test.rb" "test/cases/adapters/mysql2/quoting_test.rb"
```

- Test `quoting_test.rb` only
```ruby
ARCONN=mysql ruby -w -Itest "test/cases/adapters/mysql/quoting_test.rb"
```
```ruby
ARCONN=mysql2 ruby -w -Itest "test/cases/adapters/mysql2/quoting_test.rb"
```

**Comment by yahonda** [comment]
Closed as fixed by #21030 and https://github.com/rails/rails/commit/430b7c8b518fc628f2647323ba2bbb8dbb6cdd35
