### ISSUE TITLE
threading error when using `ActiveRecord with_connection do` (Puma)

### ISSUE THREAD

**Issue by duttski** [rails/rails#21053]
First off, apologies if this is the wrong place or just a mistake on my part. I'm pretty new to this world of Rails, so any help directing this better would be really appreciated.

Ref: http://stackoverflow.com/questions/31535545/postgresql-threading-error-when-using-activerecord-with-connection-do-puma

I have a controller set up with `ActionController::Live` and the following GET request (reduced for brevity, but with the same constituent parts):

      def events
        _user_id = @user.id #user from DB object
    
        response.headers["Content-Type"] = "text/event-stream"
        sse = SSE.new(response.stream)
    
        data = { :something => "value" }
        sse.write( data, {:event => :message})
    
        ActiveRecord::Base.connection_pool.release_connection
        begin
          redis = Redis.new
          redis.subscribe([:heartbeat, :other_event]) do |on|
            on.message do |event, data|
              logger.info {"Started event #{event} (user_id #{_user_id})"}
              ActiveRecord::Base.connection_pool.with_connection do
                ActiveRecord::Base.connection.query_cache.clear
                user = User.find(_user_id)
                case event
                  when :heartbeat
                    data = { :something => user.name }
                    sse.write( data, {:event => :heartbeat})
                  when :other_event
                    data = { :something => user.name }
                    sse.write( data, {:event => :other_event})
                  else
                end
              end
              logger.info "Finished event #{event}"
            end
          end
        rescue IOError
          logger.info 'IOError -- something like dropped connection on events stream'
        rescue ClientDisconnected
          logger.info 'ClientDisconnected -- something like dropped connection on events stream'
        ensure
          logger.info 'Ensuring event stream is closed'
          sse.close
        end
        render nothing: true
      end

There is a scope on the database call that limits the response but otherwise I think it's all pretty vanilla.

After running for several days without problems, all of a sudden the rails application locked up completely and couldn't process any requests, the only way to recover was to kill the root process and start again. The application logs were showing new requests starting but not finishing. The Puma logs showed the following (mixture of) messages (e.g.):

    message type 0x44 arrived from server while idle
    message type 0x43 arrived from server while idle
    message type 0x5a arrived from server while idle
    message type 0x54 arrived from server while idle

The issue is 'reliably' reproduced by constantly refreshing this request (but not when refreshing others while clients are connected here). That said, it's not a load issue, it happens under very light load -- so it look timing based and the repeated requests simply increase that chance sufficiently.

`heartbeat` is triggered every 15s through Redis on a separate thread.

While trying to work out/fix this at the application level I have tried:
I have tried:

 1. moving the `sse.write` to outside the `with_connection` block (and making it write just a bit of non-db text). The issue still occurred.
 2. removing all database queries from the `on.message do` block. Not yet seen a problem (it seemed worth that check)

During try 1., I found the following buried in the application logs. This happens a few hundredths of a second after the `...arrived from server while idle` message in the Puma logs.

    F, [2015-07-23T15:10:05.291268 #32287] FATAL -- : 
    IOError (closed stream):
      /var/lib/gems/2.1.0/gems/actionpack-4.2.1/lib/action_dispatch/http/response.rb:89:in `write'
      /var/lib/gems/2.1.0/gems/actionpack-4.2.1/lib/action_controller/metal/live.rb:138:in `write'
      /var/lib/gems/2.1.0/gems/actionpack-4.2.1/lib/action_controller/metal/live.rb:282:in `rescue in block in process'
      /var/lib/gems/2.1.0/gems/actionpack-4.2.1/lib/action_controller/metal/live.rb:295:in `block in process'
    
    
    F, [2015-07-23T15:10:05.291435 #32287] FATAL -- : 
    ActiveRecord::StatementInvalid (PG::DuplicatePstatement: ERROR:  prepared statement "a6" already exists

(sometimes second bit has other messages, including:)

    ActiveRecord::StatementInvalid (PG::UnableToSend: lost synchronization with server: got message type "?", length 0

Environment info:
 - OS: `Linux hostname 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:56:17 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux` -- single core virtual machine with 2GB RAM
 - Ruby: `ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]`
 - Rails: 4.2.1
 - pg (gem): 0.18.2
 - redis (gem): 3.2.1
 - PostgresSQL: 9.4.4
 - Nginx: nginx/1.6.2 (Ubuntu)
 - Puma: 2.11.3 -- running 1 worker and 1-16 threads
 - libpq-dev: 9.4.4-0ubuntu0.14.10  amd64
 - libpq5:amd64: 9.4.4-0ubuntu0.14.10  amd64
 - Also upgraded to Ubuntu 15.04 and Rails 4.2.3 to encounter the same problem

------

So, it looks like there is something strange happening around the connection pool; that it is managing to shared connections between threads that Puma has set up. 

Please do let me know if there's anything I can do to clarify this.

**Comment by duttski** [comment]
To clarify, I have this happening without Redis; by simply holding open the connection:
class StreamingController < ApplicationController
  
    include ActionController::Live
    def events
      response.headers["Content-Type"] = "text/event-stream"
      sse = SSE.new(response.stream)
  
      data = Task.all.first
      sse.write( {:data => data.caption} , {:event => :version_heartbeat})
  
      ActiveRecord::Base.connection_pool.release_connection
  
      begin
        while true do
          ActiveRecord::Base.connection_pool.with_connection do |conn|
            ActiveRecord::Base.connection.query_cache.clear
            conn.execute 'SELECT pg_sleep(10)'
            data = Task.all.first
            sse.write( {:data => data.caption}, {:event => :version_heartbeat})
          end
          sleep 1
        end
      rescue IOError
        logger.info 'IOError -- something like dropped connection on events stream'
          # TODO: do something!
      rescue ClientDisconnected
        logger.info 'ClientDisconnected -- something like dropped connection on events stream'
          # TODO: do something!
      ensure
        logger.info 'Ensuring event stream is closed'
        sse.close
      end
      render nothing: true
    end
  end

Same issue happens. I added the `pg_sleep` to try to force some gaps in which I could see the concurrency error. Not sure if it makes any actual difference though.

**Comment by duttski** [comment]
Take 2... So I tried it with MySQL rather than PostgreSQL. This time the server survives the error (presumably MySQL lib is a bit more resilient the PostgreSQL). However it looks to me that this error message is the same root as the `message type 0x44 arrived from server while idle`. 

    F, [2015-07-30T14:12:07.078215 #15606] FATAL -- : 
    ActiveRecord::StatementInvalid (Mysql2::Error: This connection is in use by: #<Thread:0x007f563b2faa88@/home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/live.rb:269 sleep>: SELECT  `tasks`.* FROM `tasks`  ORDER BY `tasks`.`id` ASC LIMIT 1):
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `query'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `exec_query'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:351:in `select'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/querying.rb:39:in `find_by_sql'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation.rb:638:in `exec_queries'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation.rb:514:in `load'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation.rb:243:in `to_a'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:500:in `find_nth_with_limit'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:484:in `find_nth'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:127:in `first'
      /var/apps/issue-test/app/controllers/streaming_controller.rb:18:in `block in events'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
      /var/apps/issue-test/app/controllers/streaming_controller.rb:15:in `events'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
      /home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/live.rb:278:in `block in process'

PS. Yes I have been switching Ruby/Rails versions around. The problem hasn't not happened yet with a combination. Next up, Rubinius.
