### ISSUE TITLE
Threading error when using `ActiveRecord with_connection do` & Puma

### ISSUE THREAD

**Issue by duttski** [rails/rails#21209]
Source: http://stackoverflow.com/questions/31535545/threading-error-when-using-activerecord-with-connection-do-puma

**Summary:**  When using Puma and running long-running connections I am consistently receiving errors related to ActiveRecord connections crossing threads. This manifests itself in message like `message type 0x## arrived from server while idle` and a locked (crashed) server.

What isn't clear is what conditions could cause the connection to be crossed between threads, i.e. am I, or is Puma, doing something wrong and needs correcting, or is the connection_pool getting confused. If you think this is better placed somewhere else then please let me know. I'm trying to do leg work on this but pretty much out of ideas!

---------------------
The set up:

 - Ubuntu 15
 - PostgreSQL (9.4) / MySQL (`mysqld 5.6.25-0ubuntu0.15.04.1`)
 - Ruby - MRI `2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]` / Rubinius `rbx-2.5.8`
 - Rails (`4.2.3`, `4.2.1`)
 - Puma (`2.12.2`, `2.11`)
 - pg (`pg-0.18.2`) / mysql2
 
Note, not all combinations of the above versions have been tried. First listed version is what I'm currently testing against.

 - `rails new issue-test`
 - Add a route `get 'events' => 'streaming#events'`
 - Add a controller `streaming_controller.rb`
 - Set up database stuff (`pool: 2`, but seen with different pool sizes)

Code:

	class StreamingController < ApplicationController

	  include ActionController::Live

	  def events
		begin
		  response.headers["Content-Type"] = "text/event-stream"
		  sse = SSE.new(response.stream)
		  sse.write( {:data => 'starting'} , {:event => :version_heartbeat})
		  ActiveRecord::Base.connection_pool.release_connection
		  while true do
			ActiveRecord::Base.connection_pool.with_connection do |conn|
			  ActiveRecord::Base.connection.query_cache.clear
			  logger.info 'START'
			  conn.execute 'SELECT pg_sleep(3)'
			  logger.info 'FINISH'
			  sse.write( {:data => 'continuing'}, {:event => :version_heartbeat})
			  sleep 0.5
			 end
		  end
		rescue IOError
		rescue ClientDisconnected
		ensure
		  logger.info 'Ensuring event stream is closed'
		  sse.close
		end
		render nothing: true
	  end
	end

Puma configuration:

	workers 1
	threads 2, 2
    #...
	bind "tcp://0.0.0.0:9292"

	#...
	activate_control_app

	on_worker_boot do
	  require "active_record"
	  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
	  ActiveRecord::Base.establish_connection(YAML.load_file("#{app_dir}/config/database.yml")[rails_env])
	end

 - Run the server `puma -e production -C path/to/puma/config/production.rb`

Test script:

	#!/bin/bash

	timeout 30 curl -vS http://0.0.0.0/events &
	timeout 5 curl -vS http://0.0.0.0/events &
	timeout 30 curl -vS http://0.0.0.0/events

This reasonably consistently results in a complete lock of the application server (in PostgreSQL, see notes). The scary message comes from `libpq`:

    message type 0x44 arrived from server while idle
    message type 0x43 arrived from server while idle
    message type 0x5a arrived from server while idle
    message type 0x54 arrived from server while idle

In the 'real-world' I have quite a few extra elements and the issue presents itself at random. My research indicates that this message comes from `libpq` and is subtext for *'communication problem, possibly using connection in different threads'*. Finally, while writing this up, I had the server lock up without a single message in any log.

--------------
I don't see the issue happen if I change the controller block to look like:

	begin
	  #...
	  while true do
		t = Thread.new do #<<<<<<<<<<<<<<<<<
			ActiveRecord::Base.connection_pool.with_connection do |conn|
	  		    #...
			end
		 end
		 t.join #<<<<<<<<<<<<<<<<<
	  end
	  #...
	rescue IOError
	#...

But I don't know whether this has actually solved the problem or just made it extremely unlikely. Nor can I really fathom why this would make a difference.

--------------
**MySQL**

If running MySQL, the message is a bit different, and the application recovers (though I'm not sure if it is then in some undefined state):

	F, [2015-07-30T14:12:07.078215 #15606] FATAL -- : 
	ActiveRecord::StatementInvalid (Mysql2::Error: This connection is in use by: #<Thread:0x007f563b2faa88@/home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/live.rb:269 sleep>: SELECT  `tasks`.* FROM `tasks`  ORDER BY `tasks`.`id` ASC LIMIT 1):

**Comment by duttski** [comment]
I tried this time with OS X, [Puma, Rainbows], PostgreSQL -- I get the same problems (locked process) but nothing in the logs whatsoever. My guess is the lack of log is to do with differences in libpq.

So Rails is now the only component I haven't been able to swap out and still get this issue.

Ideas welcome... As I say, happy to do legwork when/where I can, but am totally stuck!

**Comment by matthewd** [comment]
I'll try to come back and look into this properly, but for now I can only offer some vague thoughts:

* AC::Live spawns a new thread to handle the request, *and copies the thread locals from the original request thread*
* the connection pool tracks ownership by thread
* *maybe* at the start of your `events` action, there are actually two threads that believe they hold the lease to the same connection?
  * normally, that's okay, because only one is running user code, and only one will return it to the pool
  * but if they both release that connection, at different times, the second release could occur after the connection has already been re-allocated to some other thread
    * now thread 3 has the connection and is using it, while the pool thinks it's been returned, and hands it to thread 4, which also starts using it
    * :boom:

If you're up for some investigation, maybe that's enough to point you in the right direction?

**Comment by duttski** [comment]
@matthewd, thanks! After a bunch of testing and lots of reading Rails code it looks like your synopsis is correct. I can see that those conditions consistently cause an error, and have some logs showing the connections being checked in multiple times. That also accords with the fact that I don't get the issue when the `with_connection` is in a new thread. 

Putting some logs in AR meant I could see that there were more released connections than used connections. And this trace seems to be the culprit:

	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:362:in `checkin'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:282:in `block in release_connection'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:280:in `release_connection'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:555:in `each'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:555:in `clear_active_connections!'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_handling.rb:129:in `clear_active_connections!'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:658:in `block in call'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:18:in `call'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:18:in `close'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:16:in `close'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:16:in `close'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.12.3/lib/puma/server.rb:693:in `ensure in handle_request'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.12.3/lib/puma/server.rb:695:in `handle_request'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.12.3/lib/puma/server.rb:388:in `process_client'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.12.3/lib/puma/server.rb:270:in `block in run'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.12.3/lib/puma/thread_pool.rb:106:in `call'
	 /Users/me/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.12.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'


Basically I can see that the system returns to here before the `with_connection` block is finished:

        response = @app.call(env)
        response[2] = ::Rack::BodyProxy.new(response[2]) do
          ActiveRecord::Base.clear_active_connections! unless testing
        end

(`connection_pool.rb'`)

I also had a look to see the AC::Live is duplicating locals into the new thread -- on the AR front there are lots of log related things and then:
` [:"ActiveRecord::RuntimeRegistry", 
 #<ActiveRecord::RuntimeRegistry:0x007f9be2f785c0 @connection_id=70153752315220>]`. 

So when I get chance next, I'll be looking to try and examine the connection check-out/in cycles a bit more closely and try to get more of a handle on what seem to be the mischievous aspects:
 a) how the connections are not being refreshed / cleanly tied to one thread
 b) I am not sure why @app.call is returning before the `while true; with_connection` block exits.

**Comment by scambra** [comment]
I have same issue using passenger, not puma. I wasn't using release_connection and with_connection, and it happened too often, when I added release_connection and with_connection to the action using response.stream, it happened but not often.

Also, I have other actions in same controller which doesn't use release_connection and with_connection, they don't use response.stream either. Does anyone know if I should use that too or have them in different controller?

**Comment by duttski** [comment]
@scambra - I've not been able to investigate further I'm afraid so have to bump proper answers to the real experts. Though hopefully the following will help  somehow. (And I am so glad no longer to be alone with this issue!)

However, the following I can see:
 
 * The spawning of new threads (and hence attaching the connection_id to a second thread) happens regardless of the use of the SSE tools. So `include ActionController::Live` would at least expose some risk to the issue. As @matthewd points out, the issue is that two threads believe they own the connection at the point we enter this `AC::Live` mode,  and the original thread is within contract to check in the connection again, which then causes the problem. I can imagine all sorts of configurations that could then cause this to blow up, so my pragmatic side says to just avoid that whole area.
 * Since wrapping the database work in `t = Thread.new do` ... `t.join` I have not once had the problem (and I've been looking for it, believe me!).
 * The PostgreSQL adapter/underlying libs ultimately causes a thread locking. Standard MySQL stack survives the problem, but I wouldn't assume that it's in a defined state at that point

My layman advice would be to keep a separate controller for those routes that are definitely using the streaming functionality, thus reducing your susceptibility to any issue. Then in your streaming methods being careful to manually manage threads, thus forcing AR to take control of the pool again.

I don't know what the root-cause fix would be here. It seems to me to have some design considerations, as AC::Live seems to be breaking the contract with AR that states connections exist in one thread.

**Comment by scambra** [comment]
I'm using MySQL, and no problem since wrapping with thread the action which uses response.stream. I didn't wrap other actions with thread, but I don't have problem anyway, maybe because they are not so long.

**Comment by scambra** [comment]
I got issue, not so often as previously. I finally created a new controller for live actions, so every action is wrapped with release_connection, new thread, with_connection. I didn't have issue anymore.

```ruby
ActiveRecord::Base.connection_pool.release_connection
t = Thread.new do
    ActiveRecord::Base.connection_pool.with_connection do
      ....
    end
end
t.join

**Comment by lloeki** [comment]
I've had this issue with `ActionController::Live` blindly copying thread locals for a while, and traced it to here:

https://github.com/rails/rails/blob/1512cf2ba578282c898b8eb68ac401ea5243b7b5/actionpack/lib/action_controller/metal/live.rb#L261-L263

Context: we (previously Sqreen, now Datadog) create a context object to track current HTTP request information across instrumentation points. Since requests in Ruby are typically handled either at the process (Unicorn), thread (Thin, Puma), or fiber (Falcon) level this means the context object can safely be stored in a thread local and be oblivious to concurrency safety, because that's part of the design of thread locals.

A third party bluntly taking ownership, assuming they're static when they are most probably not, and copying such objects to another thread is not very friendly ;)

**Comment by franmago** [comment]
sql in mysql: [22001][1292] Data truncation: Incorrect date value: '1/2/2017' for column 'absence_date' at row 1
