### ISSUE TITLE
url_for throws UrlGenerationError in view spec after upgrading to Rails 4.0

### ISSUE THREAD

**Issue by agis-** [rails/rails#21398]
*This is cross-posted to https://github.com/rspec/rspec-rails/issues/1451*.

Not sure if this is a Rails or an RSpec issue but here I go.

In the process of upgrading to Rails 4.0.12 from 3.2, I've encountered some test failures that I believe are related to https://github.com/rails/rails/commit/dc663dd52c99ab6e6c633b54d1a0e836f379bf9f.

I have the following (stripped down) view:

```erb
# app/views/categories/show/_page_item.html.erb
<% url_for("controller"=>"categories", "action"=>"show", "category_id"=>"40", "category_name"=>"foo", "page"=>2) %>
```

and the corresponding spec:

```ruby
# spec/views/categories/show/_page_item.html.erb_spec.rb
require 'spec_helper'

describe 'categories/show/_page_item.html.erb' do
  it "does not explode" do
    render 'page_item.html.erb'
  end
end
```

and finally the relevant route:

```
category GET          /c/:category_id/:category_name(/m/:manufacturer_id/:manufacturer)(/s/:shop_id/:shop)(/f/:filter_id/:filter).html(.:format) categories#show {:category_id=>/\d+/, :category_name=>/[^\/]+/, :manufacturer_id=>/[0-9_]+/, :manufacturer=>/[^\/]+/, :shop_id=>/[0-9_]+/, :shop=>/[^\/]+/, :filter_id=>/[0-9_]+/, :filter=>/[^\/]+/}
```

This tests fails after upgrading to Rails 4.0 like so:

```shell
ActionView::Template::Error:
  No route matches {:action=>"show", :category_id=>"40", :category_name=>"kinhta-thlefwna", :controller=>"categories/categories", :page=>2}
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_dispatch/journey/formatter.rb:39:in `generate'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:597:in `generate'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:627:in `generate'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:663:in `url_for'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_dispatch/routing/url_for.rb:155:in `url_for'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/routing_url_for.rb:83:in `url_for'
# ./app/views/categories/show/_page_item.html.erb:2:in `_app_views_categories_show__page_item_html_erb__151325937655746978_70288869015880'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/template.rb:143:in `block in render'
# /Users/agis/.gem/ruby/2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/template.rb:141:in `render'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:47:in `render_template'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:17:in `render'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/renderer.rb:42:in `render_template'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/renderer.rb:23:in `render'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/helpers/rendering_helper.rb:24:in `render'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/test_case.rb:195:in `render'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/test_case.rb:115:in `render'
# ./spec/views/categories/show/_page_item.html.erb_spec.rb:14:in `block (2 levels) in <top (required)>'
```

The same test passes in Rails 3.2. Also, in development the view works normally and the url helpers work in both development & test when I call them from the console, so I suspect it's this might be related with RSpec and how it sets the view context.

After some digging, I've seen that when `ActionDispatch::Routing::UrlFor#url_for` is eventually called by ActionView at [this point](https://github.com/rails/rails/blob/v4.0.12/actionpack/lib/action_view/routing_url_for.rb#L82), `ActionView::RoutingUrlFor#url_options` seems to return the wrong result (not sure though)

In fact this is returned by:

```ruby
From: /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/routing_url_for.rb @ line 93 ActionView::RoutingUrlFor#url_options:

    91: def url_options #:nodoc:
    92:   return super unless controller.respond_to?(:url_options)
 => 93:   controller.url_options
    94: end

[18] pry(#<#<Class:0x007ffaeee411a0>>)> controller.url_options
=> {:host=>"test.host",
 :port=>nil,
 :protocol=>"http://",
 :_recall=>{:controller=>"categories/show"}}

[19] pry(#<#<Class:0x007ffaeee411a0>>)>controller.lookup_context.prefixes
=> ["", "categories/show"]
```

So it seems that either RSpec does not setup the controller object correctly or it's something in Rails.

Note: The issue also happens in 4.1.12.

Thanks!

**Comment by agis-** [comment]
I've found out that by prefixing the controller with a slash, this goes away. However this doesn't make much sense, since the controller is not namespaced anyways.

This seems related to #18838. I think it might be a bug.

@pixeltrix What do you think?

**Comment by pixeltrix** [comment]
@agis- any chance you can reproduce the issue using the [action pack bug template][1] ? Often these are due to a lack of an existing request in view spec but there may be something further, thanks.

[1]: https://raw.githubusercontent.com/rails/rails/4-2-stable/guides/bug_report_templates/action_controller_gem.rb
