### ISSUE TITLE
Bug with has_one association (NoMethodError: undefined method `find_all' for #)

### ISSUE THREAD

**Issue by heaven** [rails/rails#21466]
Having the next 3 models:

``` ruby
class User < ActiveRecord::Base
  belongs_to :owned_customer, :class_name => "Customer", :inverse_of => :owner, :foreign_key => :customer_id
  has_many :owned_programs, :class_name => "Program", :inverse_of => :owner, :through => :owned_customer, :source => :programs
end

class Customer < ActiveRecord::Base
  has_one :owner, -> { where(:role => User.roles[:customer]) }, :class_name => "User", :inverse_of => :owned_customer, :dependent => :destroy
  has_many :programs, :inverse_of => :customer, :dependent => :restrict_with_exception
end

class Program < ActiveRecord::Base
  belongs_to :customer, :inverse_of => :programs
  has_one :owner, :class_name => "User", :through => :customer, :inverse_of => :owned_programs
end
```

Now, if try to save a Program:

``` ruby
program = Program.last
program.save
# => true
```

But if to load program owner:

``` ruby
program = Program.last
program.owner
# => #<User id: ...
program.save
# => NoMethodError: undefined method `find_all' for #<Program:0x007fea19d51a78>
```
- All associations do work as expected.
- If change from has_one to has_many – everything seems ok.
- Rails 4.2.3 (4.2.4 produces the same).
- The full backtrace attached below.

```
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activemodel-4.2.3/lib/active_model/attribute_methods.rb:433:in `method_missing'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/autosave_association.rb:276:in `associated_records_to_validate_or_save'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/autosave_association.rb:311:in `validate_collection_association'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/autosave_association.rb:217:in `block in define_autosave_validation_callbacks'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/autosave_association.rb:157:in `instance_eval'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/autosave_association.rb:157:in `block in define_non_cyclic_method'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430:in `block in make_lambda'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:190:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:190:in `block in simple'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `block in call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `each'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activemodel-4.2.3/lib/active_model/validations.rb:395:in `run_validations!'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activemodel-4.2.3/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activemodel-4.2.3/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activemodel-4.2.3/lib/active_model/validations.rb:334:in `valid?'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/validations.rb:58:in `valid?'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/validations.rb:83:in `perform_validations'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/validations.rb:37:in `save'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:286:in `block in save'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:285:in `save'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/autosave_association.rb:413:in `save_has_one_association'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/autosave_association.rb:189:in `block in add_autosave_association_callbacks'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430:in `block in make_lambda'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:226:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:226:in `block in halting_and_conditional'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:504:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:504:in `block in call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:504:in `each'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:504:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/callbacks.rb:310:in `_update_record'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/timestamp.rb:70:in `_update_record'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/persistence.rb:504:in `create_or_update'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/callbacks.rb:302:in `create_or_update'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/persistence.rb:120:in `save'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/validations.rb:37:in `save'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:286:in `block in save'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
/Users/heaven/.rvm/gems/ruby-2.1.2@mudita/gems/activerecord-4.2.3/lib/active_record/transactions.rb:285:in `save'
(irb):62:in `irb_binding'
```

**Comment by senny** [comment]
@heaven thanks for reporting, I'll have a look.

**Comment by al2o3cr** [comment]
@heaven - I've attempted to reproduce the bug [here](https://gist.github.com/al2o3cr/31ab2450c2f61c51dd72) but without any success - other than tripping on the issue in #21002, which isn't related as far as I can tell.

**Comment by charlesdg** [comment]
thanks @al2o3cr, remove the `inverse_of:` in a `has_one ..., through: ...` did the trick

**Comment by hishammalik** [comment]
I encountered the same issue in activerecord/Rails 5.2.1 version. 

The issue occurs when I have 'has_one through' relation and use inverse_of. Removing inverse_of as per @charlesdg gets rids of the exception. So this issue still needs fixing.
