### ISSUE TITLE
Application fails to start when `SECRET_KEY_BASE` is a String containing only digits

### ISSUE THREAD

**Issue by jperville** [rails/rails#21463]
I have a rails 4.2.3 applications which I configured with a `ENV['SECRET_KEY_BASE'] = '1' * 128` (for demo purpose, not for production). This `SECRET_KEY_BASE` is valid (it is a 128 character long string), even if it somewhat lacks randomness.

When I boot my application, it fails with the following stacktrace:

```
/home/app/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/key_generator.rb:21:in `pbkdf2_hmac_sha1': no implicit conversion of Bignum into String (TypeError)
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/key_generator.rb:21:in `generate_key'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/key_generator.rb:38:in `generate_key'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/application.rb:206:in `message_verifier'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/globalid-0.3.6/lib/global_id/railtie.rb:25:in `block (2 levels) in <class:Railtie>'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /usr/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /usr/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /usr/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /usr/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `public_send'
	from /home/app/current/vendor/bundle/ruby/2.1.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `method_missing'
	from /home/app/current/config/environment.rb:5:in `<top (required)>'
	from bin/worker:3:in `require_relative'
	from bin/worker:3:in `<main>'
```

The reason of the bug is probably that:
 * the `SECRET_KEY_BASE` is actually used in `config/secrets.yaml` using ERB interpolation
 * YAML implicitly casts the values to the most likely type: my SECRET_KEY_BASE containing only `1`s is cast into a Bignum instance instead of remaining a String as expected
 * at some point the value (with the incorrect type) is used by code which expects a String instance and we get the above stacktrace.

If I were familiar with the rails code base I would write fix the issue like this:

```diff
diff --git a/lib/active_support/key_generator.rb b/lib/active_support/key_generator.rb
index 51d2da3..8a4a132 100644
--- a/lib/active_support/key_generator.rb
+++ b/lib/active_support/key_generator.rb
@@ -18,7 +18,7 @@ module ActiveSupport
     # to be compatible with the default settings of ActiveSupport::MessageVerifier.
     # i.e. OpenSSL::Digest::SHA1#block_length
     def generate_key(salt, key_size=64)
-      OpenSSL::PKCS5.pbkdf2_hmac_sha1(@secret, salt, @iterations, key_size)
+      OpenSSL::PKCS5.pbkdf2_hmac_sha1(String(@secret), salt, @iterations, key_size)
     end
   end
 
```

This issue is unlikely to happen in the real world but still theoretically possible.

**Comment by al2o3cr** [comment]
What happens with casting with `String(@secret)` when the string is all-digits starting with leading zeros? I'm guessing "not what was intended"...

An alternative would be to enclose the ERB interpolation in quotes, so something like this in `config/secrets.yml`:
```
production:
  secret_key_base: "<%= ENV["SECRET_KEY_BASE"] %>"
```
This will force YAML to interpret the value as a string.

**Comment by jperville** [comment]
Indeed :)

**Comment by hattwj** [comment]
So can't this be closed? Yaml was fed a big-int, but if you feed it a string there us no problem.
