### ISSUE TITLE
RuntimeError while destroying a record with has_many association

### ISSUE THREAD

**Issue by alexandrz** [rails/rails#22030]
Rails > 4.2

`RuntimeError: Can't modify frozen hash`

``` ruby
class Driver < ActiveRecord::Base
  belongs_to :car
end

class Car < ActiveRecord::Base
  has_many :drivers,
    :dependent => :destroy,
    :after_remove => :destroy_if_no_good_drivers

  def destroy_if_no_good_drivers(driver_id)
    good_drivers = drivers.where(:good => true)
    self.destroy if good_drivers.empty?
  end

end
```

```
> driver1 = Driver.create good: true
> driver2 = Driver.create good: false
> car = Car.create driver_ids: [driver1.id, driver2.id]
> car.driver_ids = [driver2.id]
  Driver Load (0.2ms)  SELECT  "drivers".* FROM "drivers" WHERE "drivers"."id" = ? LIMIT 1  [["id", 2]]
  Driver Load (0.2ms)  SELECT "drivers".* FROM "drivers" WHERE "drivers"."car_id" = ?  [["car_id", 3]]
   (0.1ms)  begin transaction
  SQL (0.5ms)  DELETE FROM "drivers" WHERE "drivers"."id" = ?  [["id", 1]]
   (0.2ms)  SELECT COUNT(*) FROM "drivers" WHERE "drivers"."car_id" = ? AND "drivers"."good" = ?  [["car_id", 3], ["good", "t"]]
  SQL (0.1ms)  DELETE FROM "drivers" WHERE "drivers"."id" = ?  [["id", 2]]
   (0.1ms)  SELECT COUNT(*) FROM "drivers" WHERE "drivers"."car_id" = ? AND "drivers"."good" = ?  [["car_id", 3], ["good", "t"]]
  SQL (0.2ms)  DELETE FROM "cars" WHERE "cars"."id" = ?  [["id", 3]]
   (100.8ms)  rollback transaction
RuntimeError: Can't modify frozen hash
  from lib/active_record/attribute_set/builder.rb:43:in `[]='
  from lib/active_record/attribute_set.rb:39:in `write_from_user'
  from lib/active_record/attribute_methods/write.rb:74:in `write_attribute_with_type_cast'
  from lib/active_record/attribute_methods/write.rb:56:in `write_attribute'
  from lib/active_record/attribute_methods/dirty.rb:96:in `write_attribute'
  from lib/active_record/attribute_methods.rb:373:in `[]='
  from lib/active_record/associations/association.rb:195:in `block in set_owner_attributes'
  from lib/active_record/associations/association.rb:195:in `each'
  from lib/active_record/associations/association.rb:195:in `set_owner_attributes'
  from lib/active_record/associations/has_many_association.rb:35:in `insert_record'
  from lib/active_record/associations/collection_association.rb:563:in `block (2 levels) in concat_records'
...
```

**Comment by senny** [comment]
@alexandrz thank you for your bug report.

To debug the issue efficiently it's extremely helpful if you provide an executable test-case that illustrates the issue. You can use [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as a starting point.

**Comment by rajcybage** [comment]
Yes I got the same error

The script is below

``````

begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :drivers, force: true do |t|
    t.integer :car_id
    t.boolean :good
  end

  create_table :cars, force: true do |t|
    
  end


end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class Driver < ActiveRecord::Base
  belongs_to :car
end

class Car < ActiveRecord::Base
  has_many :drivers,
    :dependent => :destroy,
    :after_remove => :destroy_if_no_good_drivers

  def destroy_if_no_good_drivers(driver_id)
    good_drivers = drivers.where(:good => true)
    self.destroy if good_drivers.empty?
  end

end

class BugTest < Minitest::Test
  def test_association_stuff
    driver1 = Driver.create good: true
    driver2 = Driver.create good: false
    car = Car.create driver_ids: [driver1.id, driver2.id]
    
    assert_equal car.drivers, [driver1, driver2]
    car.driver_ids = [driver2.id]
    assert_equal car.drivers, [driver2]
  end
end

````

**Comment by alexandrz** [comment]
@rajcybage thank you!

**Comment by alexandrz** [comment]
@rajcybage 

Although, it's not correct:

```
    car.driver_ids = [driver2.id]
    assert_equal car.drivers, [driver2]
```

After running the `destroy_if_no_good_drivers` callback both drivers and car records should be destroyed. At least it worked that way in earlier versions of AR.

**Comment by alexandrz** [comment]
Updated example:

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :drivers, force: true do |t|
    t.integer :car_id
    t.boolean :good
  end

  create_table :cars, force: true do |t|

  end
end

class Driver < ActiveRecord::Base
  belongs_to :car
end

class Car < ActiveRecord::Base
  has_many :drivers,
    :dependent => :destroy,
    :after_remove => :destroy_if_no_good_drivers

  def destroy_if_no_good_drivers(driver_id)
    good_drivers = drivers.where(:good => true)
    self.destroy if good_drivers.empty?
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    driver1 = Driver.create good: true
    driver2 = Driver.create good: false
    car = Car.create driver_ids: [driver1.id, driver2.id]

    assert_equal car.drivers, [driver1, driver2]
    car.driver_ids = [driver2.id]
    assert Car.all.empty?
    assert Driver.all.empty?
  end
end
```

**Comment by rajcybage** [comment]
@alexandrz  it is working if I ignore `after_remove`
