### ISSUE TITLE
Exception when SECRET_KEY_BASE is a large number

### ISSUE THREAD

**Issue by kuon** [rails/rails#22072]
### Summary

If ENV var `SECRET_KEY_BASE` is composed only of digits, like `12387368712638765823746812735` it will be treated as a Bignum instead of a String.

### Stack trace

```
ERROR -- : no implicit conversion of Bignum into String (TypeError)
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/key_generator.rb:21:in `pbkdf2_hmac_sha1'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/key_generator.rb:21:in `generate_key'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/key_generator.rb:38:in `generate_key'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:206:in `message_verifier'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/globalid-0.3.6/lib/global_id/railtie.rb:25:in `block (2 levels) in <class:Railtie>'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:36:in `call'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `each'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/Users/kuon/Repositories/memoways/comet/config/environment.rb:5:in `<top (required)>'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
config.ru:4:in `block in <main>'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `call'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:632:in `init_worker_process'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:655:in `worker_loop'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:540:in `maintain_worker_count'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:294:in `join'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
/Users/kuon/.rbenv/versions/2.2.3/bin/unicorn:23:in `load'
/Users/kuon/.rbenv/versions/2.2.3/bin/unicorn:23:in `<main>'
```

### Expected behaviour

Either crash "properly" with a warning or cast the key to a string.

**Comment by arunagw** [comment]
What if you explicitly add `to_s` in `secrets.yml` ?

```
secret_key_base: <%= ENV["SECRET_KEY_BASE"].to_s %>
```

**Comment by kuon** [comment]
This won't work, what would work is: 

```yaml
secret_key_base: "<%= ENV["SECRET_KEY_BASE"] %>"
```

But checking the sanity of the provided key seems important, as with today configuration manager (puppet, chef, ansible...), you may end with an ENV var that might not be what you want. I had a string in my tests and it was crashing on the server because of the technique used to generate the key by the devops team.

Changing the default `secrets.yml` to quote the value would workaround this issue, but you might consider adding a length check (and a `to_s`) when feeding the key to hmac.

**Comment by arunagw** [comment]
ahh. I am going to ping @NZKoz here.

**Comment by arunagw** [comment]
@kuon this has been fixed in master by https://github.com/rails/rails/commit/7a9ce69ce081a0c186a23806c1af1f71c697ea77

**Comment by kuon** [comment]
Yep, I saw that, great!
