### ISSUE TITLE
bin/rake environment fails

### ISSUE THREAD

**Issue by SxDx** [rails/rails#22113]
```
Rails 4.2.4
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux-gnu]
```

Fresh rails app, default gems + capistrano for deployment

```
deploy@www1:/var/sites/app_name/releases/20151029084523# bin/rake environment --trace
** Invoke environment (first_time)
** Execute environment
rake aborted!
SystemStackError: stack level too deep
 # Line below multiple times (100+)
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/helpers/controller_helper.rb:21:in `logger'
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/railtie.rb:39:in `block in <class:Railtie>'
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/usr/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.2.0/tsort.rb:345:in `each'
/usr/lib/ruby/2.2.0/tsort.rb:345:in `call'
/usr/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/usr/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/var/sites/app_name/releases/20151029084523/config/environment.rb:5:in `<top (required)>'
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/2.2.0/rake/application.rb:75:in `run'
bin/rake:8:in `<main>'
Tasks: TOP => environment
```

The line
```
/var/sites/app_name/shared/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/helpers/controller_helper.rb:21:in `logger'
```
is hundreds of times in the backtrace.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by atul-shimpi** [comment]
@SxDx 
You have mentioned ruby 2.2.3p173, but deployment is referring ruby 2.2.0 (/usr/lib/ruby/2.2.0/)

**Comment by SxDx** [comment]
@rafaelfranca I can't seem to reproduce it now, simply created a new app and copied the configuration over.
Feel free to close this.
