### ISSUE TITLE
Can't create an edge application - thor/group (LoadError)

### ISSUE THREAD

**Issue by olistik** [rails/rails#22198]
As per https://github.com/rails/rails/issues/21422#issuecomment-135893639 (/cc @rafaelfranca) I've tried to create an edge application but encountered a `LoadError`.

```shell
ಠ_ಠ rvm --version
rvm 1.26.11 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ಠ_ಠ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
ಠ_ಠ bundle --version
Bundler version 1.10.6
ಠ_ಠ rake --version
rake, version 10.4.2
ಠ_ಠ git clone git@github.com:/rails/rails.git
Cloning into 'rails'...
remote: Counting objects: 505904, done.
remote: Total 505904 (delta 0), reused 0 (delta 0), pack-reused 505903
Receiving objects: 100% (505904/505904), 116.76 MiB | 1.42 MiB/s, done.
Resolving deltas: 100% (370680/370680), done.
Checking connectivity... done.
ಠ_ಠ cd rails
ಠ_ಠ ./railties/exe/rails new --edge shiny
/home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- thor/group (LoadError)
	from /home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/olistik/projects/lab/rails-5-test/rails/railties/lib/rails/generators.rb:4:in `<top (required)>'
	from /home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/olistik/projects/lab/rails-5-test/rails/railties/lib/rails/commands/application.rb:1:in `<top (required)>'
	from /home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/olistik/projects/lab/rails-5-test/rails/railties/lib/rails/cli.rb:14:in `<top (required)>'
	from /home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./rails/railties/exe/rails:9:in `<main>'
```

I've not commented on Issue [#21422](https://github.com/rails/rails/issues/21422) because I think it's a different kind of error.

**Comment by arnvald** [comment]
@olistik after entering `rails` directory, you need to run `bundle install`, then you'll be able to create new edge application.

**Comment by olistik** [comment]
@arnvald Thanks, it worked :-)
