### ISSUE TITLE
Stucked sidekiq thread

### ISSUE THREAD

**Issue by penso** [rails/rails#22208]
Hi,

I have a stucked thread inside a sidekiq worker, a TTIN gives me the following backtrace:

```
2015-11-07T09:30:13.806Z 7609 TID-5wdv4 WARN: /data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `query'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `block in execute'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `execute'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `execute'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/mysql2_adapter.rb:226:in `exec_query'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `select'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:25:in `select_all'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/query_cache.rb:64:in `select_all'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/querying.rb:36:in `find_by_sql'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation.rb:587:in `exec_queries'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/association_relation.rb:19:in `exec_queries'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation.rb:471:in `load'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation.rb:220:in `to_a'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation/finder_methods.rb:316:in `find_take'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation/finder_methods.rb:66:in `take'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/associations/singular_association.rb:42:in `find_target'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/associations/association.rb:147:in `load_target'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/associations/association.rb:54:in `reload'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/associations/singular_association.rb:9:in `reader'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/associations/builder/association.rb:70:in `user'
/data/www/faast/releases/20151107091049/app/models/rss_feedr/parser_extension.rb:203:in `block in read_one_local_rss_zirra_from_memory'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation/delegation.rb:13:in `each'
/data/www/faast/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation/delegation.rb:13:in `each'
/data/www/faast/releases/20151107091049/app/models/rss_feedr/parser_extension.rb:202:in `read_one_local_rss_zirra_from_memory'
/data/www/faast/releases/20151107091049/app/worker/rss_parser_worker.rb:9:in `perform'
```

Which seems to be a rails issue, my code is just fetching an `object.something` to get `belongs_to` relationship. Anything I could do to trace this further?

**Comment by penso** [comment]
Oops wrong project, sorry about that.
