### ISSUE TITLE
RoR 4.2.5: Fail to start 'rails new'

### ISSUE THREAD

**Issue by Sega100500** [rails/rails#22286]
RoR 4.2.5: Fail to start 'rails new test_app':

```
        create  vendor/assets/javascripts/.keep
        create  vendor/assets/stylesheets
        create  vendor/assets/stylesheets/.keep
         run  bundle install
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- bundler (LoadError)
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/generators/app_base.rb:330:in `bundle_command'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/generators/app_base.rb:346:in `run_bundle'
        from (eval):1:in `run_bundle'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/application.rb:17:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/cli.rb:14:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/bin/rails:9:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/bin/rails:23:in `load'
        from /home/ruby/.rbenv/versions/2.2.3/bin/rails:23:in `<main>'
```

but
bundler is installed
in test_app run: 'bundle install' - all OK

with --skip-bundle
all Ok

**Comment by mattbrictson** [comment]
I am running into this problem as well. It is due to rubygems 2.5.0. In short: `rails new` fails when using rubygems 2.5.0. I've reproduced this on two different environments with fresh Ruby installations.

Downgrading to rubygems 2.4.8 is the only workaround I've found.

```
gem update --system 2.4.8
```

As far as I can tell, this is not specific to the version of Rails. Rails 4.2.4 fails as well. It is a rubygems 2.5.0 issue.

**Comment by Sega100500** [comment]
@mattbrictson 
How report of that bug to fix rubygems?
Can you help me?

**Comment by Sega100500** [comment]
@mattbrictson 

Howbeit

```
rails new test_app --skip-bundle
cd test_app
bundle install
bundle update
```

All work fine!

**Comment by mattbrictson** [comment]
@Sega100500 Can you also test whether downgrading rubygems with `gem update --system 2.4.8` fixes the original problem? This independent verification will help if it is indeed a rubygems bug.

**Comment by Sega100500** [comment]
@mattbrictson 
Yes
After downgrade to rubygems 2.4.8 all work fine!
Apparently, indeed this is the problem in rubygems 2.5.0

**Comment by Sega100500** [comment]
@mattbrictson 
You can report about this bug to developers of rubygems?
I don't now how do it.

**Comment by timbreitkreutz** [comment]
Should be able to report it here: https://github.com/rubygems/rubygems/issues

**Comment by mattbrictson** [comment]
@Sega100500 I further investigated the problem and determined it is due to a bug in how rubygems 2.5.0 resolves dependencies; I logged the issue here: https://github.com/rubygems/rubygems/issues/1381 . There is an open pull request to fix the bug, here: https://github.com/rubygems/rubygems/pull/1383

**Comment by Sega100500** [comment]
RubyGems updated 2.5.1
All works fine!
