### ISSUE TITLE
`rake db:dump` fails when `schema_search_path` is set

### ISSUE THREAD

**Issue by jnimety** [rails/rails#22346]
I just tried upgrading to 4.2.5 (from 4.2.4) and rake db:migrate fails with the error below.  I tracked down changes to `lib/active_record/tasks/postgresql_database_tasks.rb` as the culprit and provided a potential fix as a comment on this commit: 19509eebe7abfe0e7580c841247f292ac45048fe

```
$ rake db:migrate
pg_dump: No matching schemas were found
rake aborted!
failed to execute:
pg_dump -i -s -x -O -f /home/jnimety/workspace/control/db/structure.sql --schema=public --schema=data_warehouse control_jnimety

Please check the output above for any errors and make sure that `pg_dump` is installed in your PATH and has proper permissions.

/home/jnimety/.rvm/gems/ruby-2.2.3@control/gems/activerecord-4.2.5/lib/active_record/tasks/postgresql_database_tasks.rb:90:in `run_cmd'
/home/jnimety/.rvm/gems/ruby-2.2.3@control/gems/activerecord-4.2.5/lib/active_record/tasks/postgresql_database_tasks.rb:55:in `structure_dump'
/home/jnimety/.rvm/gems/ruby-2.2.3@control/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:182:in `structure_dump'
/home/jnimety/.rvm/gems/ruby-2.2.3@control/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:279:in `block (3 levels) in <top (required)>'
/home/jnimety/.rvm/gems/ruby-2.2.3@control/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:53:in `block (2 levels) in <top (required)>'
/home/jnimety/.rvm/gems/ruby-2.2.3@control/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:45:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:structure:dump
(See full trace by running task with --trace)
```

**Comment by GUI** [comment]
@jnimety: Here's a pull request I opened that should fix this: https://github.com/rails/rails/pull/22345
