### ISSUE TITLE
Rails test runner fails when minitest-rails gem is present

### ISSUE THREAD

**Issue by chriskottom** [rails/rails#22455]
I have an existing application that I'm in the process of porting over from 4.2 to edge Rails, and it uses the minitest-rails gem.

The test runner dies on startup with the following exception:

```bash
railties/lib/rails/test_unit/minitest_plugin.rb:17:in `plugin_rails_options': uninitialized constant Minitest::Rails::TestUnitReporter (NameError)
        from /home/ck1/Projects/minitest_cookbook/code/minishop5/vendor/bundle/ruby/2.2.0/gems/minitest-5.8.3/lib/minitest.rb:193:in `block (2 levels) in process_args'
        from /home/ck1/Projects/minitest_cookbook/code/minishop5/vendor/bundle/ruby/2.2.0/gems/minitest-5.8.3/lib/minitest.rb:191:in `each'
        from /home/ck1/Projects/minitest_cookbook/code/minishop5/vendor/bundle/ruby/2.2.0/gems/minitest-5.8.3/lib/minitest.rb:191:in `block in process_args'
        from /home/ck1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/optparse.rb:917:in `initialize'
        from /home/ck1/Projects/minitest_cookbook/code/minishop5/vendor/bundle/ruby/2.2.0/gems/minitest-5.8.3/lib/minitest.rb:165:in `new'
        from /home/ck1/Projects/minitest_cookbook/code/minishop5/vendor/bundle/ruby/2.2.0/gems/minitest-5.8.3/lib/minitest.rb:165:in `process_args'
        from /home/ck1/Projects/minitest_cookbook/code/minishop5/vendor/bundle/ruby/2.2.0/gems/minitest-5.8.3/lib/minitest.rb:116:in `run'
        from /home/ck1/Projects/minitest_cookbook/code/minishop5/vendor/bundle/ruby/2.2.0/bundler/gems/rails-e57daaae6e79/railties/lib/rails/commands/test.rb:9:in `<top (required)>'
        from /home/ck1/Projects/minitest_cookbook/code/minishop5/vendor/bundle/ruby/2.2.0/bundler/gems/rails-e57daaae6e79/railties/lib/rails/commands/commands_tasks.rb:128:in `require_command!'
        from /home/ck1/Projects/minitest_cookbook/code/minishop5/vendor/bundle/ruby/2.2.0/bundler/gems/rails-e57daaae6e79/railties/lib/rails/commands/commands_tasks.rb:86:in `test'
        from /home/ck1/Projects/minitest_cookbook/code/minishop5/vendor/bundle/ruby/2.2.0/bundler/gems/rails-e57daaae6e79/railties/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /home/ck1/Projects/minitest_cookbook/code/minishop5/vendor/bundle/ruby/2.2.0/bundler/gems/rails-e57daaae6e79/railties/lib/rails/commands.rb:18:in `<top (required)>'
        from /home/ck1/Projects/minitest_cookbook/code/minishop5/bin/rails:9:in `<top (required)>'
        from /home/ck1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/ck1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
```

The plugin in question is referencing Rails::TestUnitReporter from within the Minitest module which would be perfectly fine if minitest-rails didn't define Minitest::Rails as a module.

Explicitly referencing Rails here using the global namespace seems to solve the problem, at least in this instance.

**Comment by jonatack** [comment]
Nice one, Chris, just stumbled on this as well.

**Comment by atstockland** [comment]
This got me too.  Ruby 2.5.0, rails 5.2.0.beta2, minitest 3.0.
