### ISSUE TITLE
undefined local variable or method `has_secure_pasword' for User in Rails 5.0.0.alpha API with ActiveRecord

### ISSUE THREAD

**Issue by matixmatix** [rails/rails#22505]
I'm running a Rails app created with `--api` flag and I can't get `ActiveModel::SecurePassword` to work in my User model.

Gemfile:
`gem 'bcrypt-ruby', '~> 3.0.0'`

User.rb
```
include ActiveModel::SecurePassword

class User < ActiveRecord::Base
  has_secure_pasword
end
```

If I open Rails console and simply type `User`, I get the following:

```
2.2.2 :002 > User
NameError: undefined local variable or method `has_secure_pasword' for User (call 'User.connection' to establish a connection):Class
	from /Users/jurgen/development/rails/activerecord/lib/active_record/dynamic_matchers.rb:21:in `method_missing'
	from /Users/jurgen/development/red-green-api/app/models/user.rb:5:in `<class:User>'
	from /Users/jurgen/development/red-green-api/app/models/user.rb:3:in `<top (required)>'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/dependencies.rb:492:in `load'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/dependencies.rb:492:in `block in load_file'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/dependencies.rb:682:in `new_constants_in'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/dependencies.rb:491:in `load_file'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/dependencies.rb:388:in `block in require_or_load'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/concurrency/share_lock.rb:115:in `exclusive'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/dependencies.rb:369:in `require_or_load'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/dependencies.rb:529:in `load_missing_constant'
	from /Users/jurgen/development/rails/activesupport/lib/active_support/dependencies.rb:212:in `const_missing'
	from (irb):2
	from /Users/jurgen/development/rails/railties/lib/rails/commands/console.rb:65:in `start'
	from /Users/jurgen/development/rails/railties/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/jurgen/development/rails/railties/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/jurgen/development/rails/railties/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/jurgen/development/rails/railties/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in 
```

My requires in `application.rb`:

````
require File.expand_path('../boot', __FILE__)

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
```

How do I get it working?

**Comment by masterkain** [comment]
`has_secure_password` instead of `has_secure_pasword` might help there

**Comment by Elektron1c97** [comment]
You have a typo in `has_secure_pasword` it should be `has_secure_password` lke @masterkain said.

**Comment by matixmatix** [comment]
@masterkain @Elektron1c97 Oh man, I am so ashamed! Thank you.
