### ISSUE TITLE
Counter caches for associations with non-primary keys do not work. increment_counters only takes a primary key

### ISSUE THREAD

**Issue by amalagaura** [rails/rails#22602]
Counter caches for associations with string keys have issues in at least 4.1. In 4.2 we noticed it because they throw exceptions when they try to use the string key to lookup the record on its primary key. This causes out of range exceptions if we have large numbers as string keys. Linked are test cases to reproduce. Throws exceptions in 4.2 and have test case failures in 4.1.

[string_keys_and_counter_cache_4-1.rb](https://gist.github.com/amalagaura/7de9a6716748b818e8f6)
[string_keys_and_counter_cache_4-2.rb](https://gist.github.com/amalagaura/e426722f80dc4a0ec690)

I tested 4.2.0 - 4.2.5. All with same behavior.

**Comment by amalagaura** [comment]
This is the same issue. The string part just creates the exception in Rails 4.2

https://github.com/rails/rails/issues/22602

**Comment by amalagaura** [comment]
I was looking into the issue (sticking to 4-2 for now, the exception is very helpful to see what is going on) and this gets executed:

```
/active_record/associations/builder/belongs_to.rb:44:in `belongs_to_counter_cache_after_update'
/active_record/associations/builder/belongs_to.rb:58:in `add_counter_cache_callbacks'
/active_record/counter_cache.rb:104:in `increment_counter'
```

So `increment_counter(counter_name, id)` only takes the primary_key id, not the primary key for the relation. It calls `update_counters(id, counter_name => 1)`

This works on creates on association because the counter gets updated in memory. 

What is a strategy to deal with this? The final update is `unscoped.where(primary_key => id).update_all`

Changing the method signature of these two methods is necessary to fix this. Otherwise counter_caches only work with primary keys. Is this something that Rails needs to support? I feel like it should. This has only come up recently because of the exception that 4.2 is throwing, otherwise it was just broken before on updates (only working on creates).

**Comment by amalagaura** [comment]
I did some work on this and creating a new method to leave the old method signatures alone is ok. The proper primary_key can be passed along and it is working and tests are passing.

There is a separate problem in `reflection.counter_cache_column` in `with_cache_name` in `belongs_to_association.rb`  https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/associations/belongs_to_association.rb#L48

It picks up the wrong reflection. It seems to be picking up the first association or at least the primary key one. So the counter name is wrong but the primary key and foreign keys are correct.

**Comment by amalagaura** [comment]
I feel like this behavior of counter_caches not working for non-primary keys should be in the documentation. It will require kind of a large rework of the internals to get it working and I don't know if it is desired.

A colleague has used callbacks to create a simple alternative counter_cache implementation which actually works for non-primary keys. It is very short. The complicated parts of activerecord is actually getting it to work so that the counter increments in place without a reload. We have ignored that to get something working.
