### ISSUE TITLE
Polymorphic Associations with touch true raises NameError: wrong constant name

### ISSUE THREAD

**Issue by okashino** [rails/rails#22654]
I found an issue with polymorphic associations with touch enabled that raises a 'NameError: wrong constant name' error. Below is a code sample similar to my use case:
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'rack', github: 'rack/rack'
  gem 'sprockets', github: 'rails/sprockets'
  gem 'sprockets-rails', github: 'rails/sprockets-rails'
  gem 'sass-rails', github: 'rails/sass-rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection 'sqlite3::memory:'

ActiveRecord::Schema.define do
  create_table :comments do |t|
    t.string :body
    t.string :commentable_type, null: false, default: ''
    t.integer :commentable_id, null: false, default: 0
    t.timestamps
  end

  create_table :books do |t|
    t.string :title
    t.timestamps
  end
end

class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true, touch: true
end

class Book < ActiveRecord::Base
  has_many :comments, as: :commentable, dependent: :destroy
end

class BugTest < Minitest::Test
  def test_polymorphic_with_touch
    comment = Comment.create(body: 'Comment on Book 1')
    book = Book.create(title: 'Book 1')
    book.comments << comment # Fails here with error NameError: wrong constant name
    assert_equal 1, book.comments.count
  end
end
``` 
Tested and reproduced in 4.2.5

**Comment by al2o3cr** [comment]
Here's a full stack trace from the test failure:
```
  1) Error:
BugTest#test_polymorphic_with_touch:
NameError: wrong constant name 
    activesupport/lib/active_support/inflector/methods.rb:252:in `const_get'
    activesupport/lib/active_support/inflector/methods.rb:252:in `constantize'
    activesupport/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
    activerecord/lib/active_record/associations/builder/belongs_to.rb:78:in `touch_record'
    activerecord/lib/active_record/associations/builder/belongs_to.rb:109:in `block in add_touch_callbacks'
    activesupport/lib/active_support/callbacks.rb:398:in `instance_exec'
    activesupport/lib/active_support/callbacks.rb:398:in `block in make_lambda'
    activesupport/lib/active_support/callbacks.rb:207:in `call'
    activesupport/lib/active_support/callbacks.rb:207:in `block in halting_and_conditional'
    activesupport/lib/active_support/callbacks.rb:456:in `call'
    activesupport/lib/active_support/callbacks.rb:456:in `block in call'
    activesupport/lib/active_support/callbacks.rb:456:in `each'
    activesupport/lib/active_support/callbacks.rb:456:in `call'
    activesupport/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
    activesupport/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
    activerecord/lib/active_record/callbacks.rb:298:in `create_or_update'
    activerecord/lib/active_record/suppressor.rb:41:in `create_or_update'
    activerecord/lib/active_record/persistence.rb:125:in `save'
    activerecord/lib/active_record/validations.rb:44:in `save'
    activerecord/lib/active_record/attribute_methods/dirty.rb:22:in `save'
    activerecord/lib/active_record/transactions.rb:319:in `block (2 levels) in save'
    activerecord/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
    activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:220:in `transaction'
    activerecord/lib/active_record/transactions.rb:211:in `transaction'
    activerecord/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    activerecord/lib/active_record/transactions.rb:319:in `block in save'
    activerecord/lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
    activerecord/lib/active_record/transactions.rb:318:in `save'
    activerecord/lib/active_record/associations/has_many_association.rb:48:in `insert_record'
    activerecord/lib/active_record/associations/collection_association.rb:576:in `block (2 levels) in concat_records'
    activerecord/lib/active_record/associations/collection_association.rb:419:in `replace_on_target'
    activerecord/lib/active_record/associations/collection_association.rb:412:in `add_to_target'
    activerecord/lib/active_record/associations/collection_association.rb:575:in `block in concat_records'
    activerecord/lib/active_record/associations/collection_association.rb:573:in `each'
    activerecord/lib/active_record/associations/collection_association.rb:573:in `concat_records'
    activerecord/lib/active_record/associations/has_many_association.rb:129:in `concat_records'
    activerecord/lib/active_record/associations/collection_association.rb:177:in `block in concat'
    activerecord/lib/active_record/associations/collection_association.rb:192:in `block in transaction'
    activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:222:in `block in transaction'
    activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:183:in `within_new_transaction'
    activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:222:in `transaction'
    activerecord/lib/active_record/transactions.rb:211:in `transaction'
    activerecord/lib/active_record/associations/collection_association.rb:191:in `transaction'
    activerecord/lib/active_record/associations/collection_association.rb:177:in `concat'
    activerecord/lib/active_record/associations/collection_proxy.rb:993:in `<<'
    test_touch.rb:52:in `test_polymorphic_with_touch'
```

The relevant line points [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/builder/belongs_to.rb#L78) in `ActiveRecord::Associations::Builder::BelongsTo.touch_record`.

The issue here is that the schema has defaults for `commentable_type` and `commentable_id`, which trigger an attempt to resolve the "old" object when saving the updated `Comment`. Removing the defaults and making the columns nullable makes the test pass.

This test exhibits the issue without defaults:
```ruby
  def test_polymorphic_with_junk
    comment = Comment.create(body: 'Comment on Book 1', commentable_type: 'ClassNotAppearingInThisFile', commentable_id: 0)
    book = Book.create(title: 'Book 1')
    book.comments << comment # Fails here with error NameError: wrong constant name
    assert_equal 1, book.comments.count
  end
```

I think most people would classify the `test_polymorphic_with_junk` failure as "stop putting garbage that doesn't make sense into the DB". I'd consider the issue here similarly - the defaults result in data that doesn't satisfy the invariants `belongs_to` expects.

**Comment by sgrif** [comment]
> I think most people would classify the test_polymorphic_with_junk failure as "stop putting garbage that doesn't make sense into the DB". I'd consider the issue here similarly - the defaults result in data that doesn't satisfy the invariants belongs_to expects.

I concur.
