### ISSUE TITLE
(erb):2:in `block in template': undefined method `push' for "":String (NoMethodError)

### ISSUE THREAD

**Issue by krunal** [rails/rails#22679]
Steps I followed to create a new rails 5 applications. (Rails 5.0.0.beta1)
1) gem install rails --pre 
2) rails new my_blog -d mysql -T --api
3) rake db:create
4) rails g scaffold user email:string password:string auth_token:string (Getting error with this command)

Getting following error while executing scaffold command with rails 5.

Command - rails g scaffold user email:string password:string auth_token:string
Exception -
```Running via Spring preloader in process 8825
      invoke  active_record
   identical    db/migrate/20151218221428_create_users.rb
(erb):2:in `block in template': undefined method `push' for "":String (NoMethodError)
	from /home/krunal/.rvm/gems/ruby-head@my_blog/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:305:in `block in capture'
	from /home/krunal/.rvm/gems/ruby-head@my_blog/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:310:in `with_output_buffer'
	from /home/krunal/.rvm/gems/ruby-head@my_blog/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:305:in `capture'
	from /home/krunal/.rvm/gems/ruby-head@my_blog/gems/railties-5.0.0.beta1/lib/rails/generators/named_base.rb:43:in `module_namespacing'
	from (erb):1:in `template'
	from /home/krunal/.rvm/rubies/ruby-head/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /home/krunal/.rvm/rubies/ruby-head/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /home/krunal/.rvm/gems/ruby-head@my_blog/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /home/krunal/.rvm/gems/ruby-head@my_blog/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
	from /home/krunal/.rvm/gems/ruby-head@my_blog/gems/thor-0.19.1/lib/thor/actions/create_file.rb:46:in `identical?'
	from /home/krunal/.rvm/gems/ruby-head@my_blog/gems/thor-0.19.1/lib/thor/actions/create_file.rb:72:in `on_conflict_behavior'
	from /home/krunal/.rvm/gems/ruby-head@my_blog/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:113:in `invoke_with_conflict_check'
	from /home/krunal/.rvm/gems/ruby-head@my_blog/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /home/krunal/.rvm/gems/ruby-head@my_blog/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'```

**Comment by kkoci** [comment]
Hi, which ruby version are you using?

Are you "behind" rvm?

**Comment by yui-knk** [comment]
Maybe you use ruby 2.3.0-dev.
I will create an issue for Ruby Issue Tracking System about this.

**Comment by kkoci** [comment]
I'm using rails 5.0.0.beta1 with ruby 2.2.4, no problems here

**Comment by yui-knk** [comment]
This bug occurs when use ruby 2.3.0-dev.

**Comment by kkoci** [comment]
Got it

**Comment by yui-knk** [comment]
https://bugs.ruby-lang.org/issues/11842

**Comment by kkoci** [comment]
Awesome, gonna see if I can collaborate on that one

**Comment by kkoci** [comment]
Look I just did all your steps with ruby-2.3.0-preview1 and rails 5beta1, no problems here, I think yui-knk is right, this must be some dev version issue

**Comment by krunal** [comment]
I am getting above error with ruby-head. (ruby 2.3.0dev (2015-12-19 trunk 53195) [x86_64-linux]
)

**Comment by sgrif** [comment]
Appears to not be a Rails issue.
