### ISSUE TITLE
 NameError(undefined local variable or method `data' for ApplicationCable::Connection

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails#22674]
_From @kroehre on October 3, 2015 1:5_

Seeing this in logs when trying to connect. It doesn't happen every time though, which is odd. 

```
 There was an exception - NameError(undefined local variable or method `data' for #<ApplicationCable::Connection:0x007fa52e583f60>)
 /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
 E, [2015-10-02T23:34:45.821266 #7] ERROR -- : Actor crashed!
 /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
 Celluloid::DeadTaskError: cannot resume a dead task (dead fiber called)
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:29:in `rescue in deliver'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `deliver'
 /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
 /app/vendor/bundle/ruby/2.2.0/bundler/gems/actioncable-98855fea634a/lib/action_cable/server/worker.rb:12:in `invoke'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:96:in `resume'
 /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
 /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
 /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
 /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/responses.rb:11:in `dispatch'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:40:in `block in initialize'
 /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
 /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
 /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
 /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:19:in `handle_message'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:280:in `handle_message'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:154:in `block in run'
    /app/vendor/bundle/ruby/2.2.0/gems/timers-4.0.1/lib/timers/group.rb:52:in `wait'
 Finished "/?id=fe0c10ed5851b1fd520d5629ca45ce00" [Websocket] for 69.80.108.212 at 2015-10-02 23:34:45 +0000
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:150:in `run'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
    /app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
```

_Copied from original issue: rails/actioncable#82_

**Comment by rafaelfranca** [comment]
_From @jeremy on October 3, 2015 1:10_

Similar errors:

* https://github.com/celluloid/celluloid/issues/109
* https://github.com/celluloid/reel/issues/33

**Comment by rafaelfranca** [comment]
_From @maikokuppe on October 9, 2015 7:26_

+1

**Comment by arthurnn** [comment]
Was this a celluloid issue? If so, I guess we can close this as we dont depend on it anymore.
cc @matthewd

**Comment by maclover7** [comment]
Action Cable no longer depends on Celluloid (and this appears to be a Celluloid error), so I'm going to close this issue.
