### ISSUE TITLE
ActiveSupport::Logger undefined local variable or method broadcast_messages 

### ISSUE THREAD

**Issue by dammer** [rails/rails#22720]
After update on 5.0.0.beta1 have this error on puma/webrick: 
```ruby
[2015-12-21 02:20:40] INFO  WEBrick 1.3.1
[2015-12-21 02:20:40] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
[2015-12-21 02:20:40] INFO  WEBrick::HTTPServer#start: pid=14710 port=3000
[2015-12-21 02:20:43] ERROR NameError: undefined local variable or method `broadcast_messages' for #<RailsStdoutLogging::StdoutLogger:0x00558acf7bdec8>
	/home/damir/project/.bundle/gems/gems/activesupport-5.0.0.beta1/lib/active_support/logger.rb:14:in `block (2 levels) in broadcast'
	/home/damir/.rbenv/versions/2.2.2/lib/ruby/2.2.0/logger.rb:400:in `debug'
	/home/damir/project/.bundle/gems/gems/railties-5.0.0.beta1/lib/rails/rack/logger.rb:35:in `call_app'
	/home/damir/project/.bundle/gems/gems/railties-5.0.0.beta1/lib/rails/rack/logger.rb:24:in `block in call'
	/home/damir/project/.bundle/gems/gems/activesupport-5.0.0.beta1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
	/home/damir/project/.bundle/gems/gems/activesupport-5.0.0.beta1/lib/active_support/tagged_logging.rb:26:in `tagged'
	/home/damir/project/.bundle/gems/gems/activesupport-5.0.0.beta1/lib/active_support/tagged_logging.rb:70:in `tagged'
	/home/damir/project/.bundle/gems/gems/railties-5.0.0.beta1/lib/rails/rack/logger.rb:24:in `call'
	/home/damir/project/.bundle/gems/gems/actionpack-5.0.0.beta1/lib/action_dispatch/middleware/request_id.rb:24:in `call'
	/home/damir/project/.bundle/gems/bundler/gems/rack-f4562619c3c6/lib/rack/method_override.rb:22:in `call'
	/home/damir/project/.bundle/gems/bundler/gems/rack-f4562619c3c6/lib/rack/runtime.rb:22:in `call'
	/home/damir/project/.bundle/gems/gems/activesupport-5.0.0.beta1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
	/home/damir/project/.bundle/gems/gems/actionpack-5.0.0.beta1/lib/action_dispatch/middleware/load_interlock.rb:13:in `call'
	/home/damir/project/.bundle/gems/gems/actionpack-5.0.0.beta1/lib/action_dispatch/middleware/static.rb:132:in `call'
	/home/damir/project/.bundle/gems/bundler/gems/rack-f4562619c3c6/lib/rack/sendfile.rb:111:in `call'
	/home/damir/project/.bundle/gems/gems/railties-5.0.0.beta1/lib/rails/engine.rb:522:in `call'
	/home/damir/project/.bundle/gems/bundler/gems/rack-f4562619c3c6/lib/rack/handler/webrick.rb:86:in `service'
	/home/damir/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/home/damir/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/home/damir/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```
using debugger i see 

```ruby 
[10, 19] in /home/damir/project/.bundle/gems/gems/activesupport-5.0.0.beta1/lib/active_support/logger.rb
   10:     # Broadcasts logs to multiple loggers.
   11:     def self.broadcast(logger) # :nodoc:
   12:       Module.new do
   13:         define_method(:add) do |*args, &block|
   14:           debugger
=> 15:           logger.add(*args, &block) if broadcast_messages
   16:           super(*args, &block)
   17:         end
   18: 
   19:         define_method(:<<) do |x|
(byebug) broadcast_messages
*** NameError Exception: undefined local variable or method `broadcast_messages' for #<RailsStdoutLogging::StdoutLogger:0x005620bd6542d8>

nil
(byebug) logger
#<ActiveSupport::Logger:0x005620be392ad0 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x005620be392a58 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x005620bd6605b0 @datetime_format=nil, @thread_key="activesupport_tagged_logging_tags:47349308261080">, @logdev=#<Logger::LogDevice:0x005620be392a08 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x005620be3929e0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x005620be392990>>>, @broadcast_messages=true>

```
just change 

``` ruby 
- logger.add(*args, &block) if broadcast_messages
+ logger.add(*args, &block) if logger.broadcast_messages
```
and all work.

**Comment by dammer** [comment]
Sorry rails_stdout_logging-0.0.4 was included to Gemfile.lock as dependency rails_12factor gem.
