### ISSUE TITLE
Undefined method `polymorphic_path' in version 5.0.0.beta1

### ISSUE THREAD

**Issue by dlupu** [rails/rails#22794]
Hello, 

Just came over an issue when trying to switch from Rails 4.2.5 to Rails 5.0.0.beta1. The following code:

          <%= form_for [:admin, page] do |f| %>
                  ....
          <% end %>

generates the following error :

     ActionView::Template::Error: undefined method `polymorphic_path' for #<#<Class:0x007fca909d03e8>:0x007fca93446f78>

With the backtrace: 

       actionview-5.0.0.beta1/lib/action_view/helpers/form_helper.rb:472:in `apply_form_for_options!'
       actionview-5.0.0.beta1/lib/action_view/helpers/form_helper.rb:440:in `form_for'

**Comment by dlupu** [comment]
Seems related to  issue #22512, I stumbled upon a comment from @pixeltrix stating this case as a bordercase for that issue.

**Comment by eileencodes** [comment]
Hey @dlupu thanks for the report! Can you make an executable script using these templates that reproduces that issue (https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb)? It will be easier to track down what's causing this if we have that.

**Comment by hansondr** [comment]
Hope this isn't bad form but I created a script using the template that seems to reproduce the issue:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'rack', github: 'rack/rack'
  gem 'sprockets', github: 'rails/sprockets'
  gem 'sprockets-rails', github: 'rails/sprockets-rails'
  gem 'sass-rails', github: 'rails/sass-rails'
  gem 'sqlite3'
end

require 'action_controller/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/' => 'test#index'
  end
end

require 'active_record'
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Schema.define do
  create_table :pages, force: true do |t|
  end
end

class Page < ActiveRecord::Base
end

class TestController < ActionController::Base
  def index
    render inline: "<%= form_for [:admin, page] do |f| %><% end %>", locals: { page: Page.new }
  end
end

require 'minitest/autorun'
require 'rack/test'

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get '/'
    assert last_response.ok?
  end

  private
  def app
    Rails.application
  end
end
```

**Comment by dlupu** [comment]
Hy @hansondr . Thanks for the help. I confirm the script triggers the same error!

**Comment by maclover7** [comment]
Would you be willing to do a git bisect to find where the error was introduced?

**Comment by alse** [comment]
I think that script is missing `include Rails.application.routes.url_helpers` and the namespaced route declaration.

This passes for me:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'rack', github: 'rack/rack'
  gem 'sprockets', github: 'rails/sprockets'
  gem 'sprockets-rails', github: 'rails/sprockets-rails'
  gem 'sass-rails', github: 'rails/sass-rails'
  gem 'sqlite3'
end

require 'action_controller/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/' => 'test#index'

    namespace :admin do
      resources :pages
    end
  end
end

require 'active_record'
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Schema.define do
  create_table :pages, force: true do |t|
  end
end

class Page < ActiveRecord::Base
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
  def index
    render inline: "<%= form_for [:admin, page] do |f| %><% end %>", locals: { page: Page.new }
  end
end

require 'minitest/autorun'
require 'rack/test'

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get '/'
    assert last_response.ok?
  end

  private
  def app
    Rails.application
  end
end
```

**Comment by maclover7** [comment]
Using a sample app I created myself, and using the test script from @alse, I am unable to reproduce the bug you are seeing. Please try upgrading to Rails master and see if you can reproduce again.

**Comment by fredmcgroarty** [comment]
I'm having the same issue. Removing 'rails-controller-testing' gem fixes the issue with 'polymorphic_path', but obviously 'rails-controller-testing' is needed for controller specs.
