### ISSUE TITLE
update_attribute fails for Array column type

### ISSUE THREAD

**Issue by Javix** [rails/rails#22817]
I tried to call `update_attribute` on one of my model:
```
class Quiz < ActiveRecord::Base
  belongs_to :level
  belongs_to :subject
  belongs_to :theme
  serialize :question_ids, Array
  serialize :answer_ids, Array
end
``` 
as follows:
```
Loading development environment in sandbox (Rails 4.2.4)
Any modifications you make will be rolled back on exit
[1] pry(main)> q = Quiz.first
  Quiz Load (1.6ms)  SELECT  "quizzes".* FROM "quizzes"  ORDER BY "quizzes"."id" ASC LIMIT 1
=> #<Quiz:0x007fb3bf57e5e8
 id: 9,
 user_id: 1,
 level_id: 2,
 subject_id: 4,
 theme_id: 6,
 question_ids: ["16", "17", "18"],
 answer_ids: [],
 score: nil,
 total: nil,
 date: nil,
 created_at: Mon, 28 Dec 2015 18:13:45 UTC +00:00,
 updated_at: Mon, 28 Dec 2015 18:13:55 UTC +00:00>
[2] pry(main)> id = "1"
=> "1"
[3] pry(main)> q.update_attribute(:answer_ids, *id)
ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be a Array, but was a String. -- "1"
from /Users/serge-mac/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/coders/yaml_column.rb:17:in `dump'
[4] pry(main)> arr = *id
=> ["1"]
[5] pry(main)> q.update_attribute(:answer_ids, arr)
ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be a Array, but was a String. -- "1"
from /Users/serge-mac/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/coders/yaml_column.rb:17:in `dump'
``` 
If I just assign the attribute and save it, it works:
```
[5] pry(main)> q.answer_ids = ["1", "2"]
=> ["1", "2"]
[6] pry(main)> q.save
   (0.3ms)  SAVEPOINT active_record_1
  SQL (0.6ms)  UPDATE "quizzes" SET "answer_ids" = $1, "updated_at" = $2 WHERE "quizzes"."id" = $3  [["answer_ids", "---\n- '1'\n- '2'\n"], ["updated_at", "2015-12-28 20:18:26.387163"], ["id", 9]]
   (0.3ms)  RELEASE SAVEPOINT active_record_1
=> true
[7] pry(main)> q
=> #<Quiz:0x007fb3bd74e208
 id: 9,
 user_id: 1,
 level_id: 2,
 subject_id: 4,
 theme_id: 6,
 question_ids: ["16", "17", "18"],
 answer_ids: ["1", "2"],
 score: nil,
 total: nil,
 date: nil,
 created_at: Mon, 28 Dec 2015 18:13:45 UTC +00:00,
 updated_at: Mon, 28 Dec 2015 20:18:26 UTC +00:00>
```
What is wrong with that ? Thank you.
Ruby `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]` 
Rails `4.2.4` 
Postgresql `9.3.4.2`

**Comment by prathamesh-sonpatki** [comment]
Confirmed that this issue exists on master too - https://gist.github.com/8dd4cb2bf364e6d9885d
cc @sgrif

**Comment by sblackstone** [comment]
I don't think this is a rails issue - with pure ruby the behavior is the same.. 

```
def example(key, value)
  puts value.class
end

id = "1"

example(:question_ids, *id)

arr = *id

example(:question_ids, *id)
```

```
frodo:~ sblackstone$ ruby example.rb
String
String
```

Tried it with 2.2.1, 2.2.3, 2.3.0

**Comment by rafaelfranca** [comment]
Yes, you should be using `Array(id)` not splat operator.

**Comment by Javix** [comment]
Thank you guys ! It is clear now.
