### ISSUE TITLE
database table attribute column problem

### ISSUE THREAD

**Issue by peterwillcn** [rails/rails#22810]
```
desc radgroupreply;
+-----------+------------------+------+-----+---------+----------------+
| Field     | Type             | Null | Key | Default | Extra          |
+-----------+------------------+------+-----+---------+----------------+
| id        | int(11) unsigned | NO   | PRI | NULL    | auto_increment |
| groupname | varchar(64)      | NO   | MUL |         |                |
| attribute | varchar(64)      | NO   |     |         |                |
| op        | char(2)          | NO   |     | =       |                |
| value     | varchar(253)     | NO   |     |         |                |
+-----------+------------------+------+-----+---------+----------------+
```

```
 Radgroupreply.last
  Radgroupreply Load (0.3ms)  SELECT  `radgroupreply`.* FROM `radgroupreply`  ORDER BY `radgroupreply`.`id` DESC LIMIT 1
ActiveRecord::DangerousAttributeError: attribute is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods.rb:115:in `instance_method_already_implemented?'
	from web/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.5/lib/active_model/attribute_methods.rb:288:in `block in define_attribute_method'
	from web/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.5/lib/active_model/attribute_methods.rb:285:in `each'
	from web/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.5/lib/active_model/attribute_methods.rb:285:in `define_attribute_method'
	from web/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.5/lib/active_model/attribute_methods.rb:252:in `block in define_attribute_methods'
	from web/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.5/lib/active_model/attribute_methods.rb:252:in `each'
	from web/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.5/lib/active_model/attribute_methods.rb:252:in `define_attribute_methods'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods.rb:86:in `block in define_attribute_methods'
	from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/2.2.0/mutex_m.rb:73:in `synchronize'
	from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/2.2.0/mutex_m.rb:73:in `mu_synchronize'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods.rb:83:in `define_attribute_methods'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/core.rb:113:in `allocate'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/persistence.rb:69:in `instantiate'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/querying.rb:50:in `block (2 levels) in find_by_sql'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/result.rb:51:in `block in each'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/result.rb:51:in `each'
... 3 levels...
	from web/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/querying.rb:49:in `find_by_sql'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/relation.rb:639:in `exec_queries'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/relation.rb:515:in `load'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/relation.rb:243:in `to_a'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/relation/finder_methods.rb:511:in `find_last'
	from web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/relation/finder_methods.rb:160:in `last'
	fromweb/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/querying.rb:3:in `last'
	from (irb):1
	from web/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
	from web/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from web/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from web/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from web/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
use gem safe_attributes fix this problem.
see https://github.com/bjones/safe_attributes/blob/master/lib/safe_attributes/base.rb  # fix merge rails master tree ?

But ruby-grape   /use/vpn/web/vendor/bundle/ruby/2.2.0/gems/grape-entity-0.4.8/lib/grape_entity/entity.rb:588:in `delegate_attribute'
see https://github.com/ruby-grape/grape-entity/issues/197  # Haven't find a way to repair！

**Comment by sevenseacat** [comment]
what exactly is the problem?

**Comment by peterwillcn** [comment]
@sevenseacat  

Please see https://github.com/ruby-grape/grape-entity/issues/197  
NoMethodError (private method `attribute' called for #<Radgroupreply:0x007ffbe8e63390>):
  /use/vpn/web/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.5/lib/active_model/attribute_methods.rb:430:in `method_missing'

**Comment by rafaelfranca** [comment]
attribute is not a valid column name because there is a method with same name on Active Record.

**Comment by peterwillcn** [comment]
oh no....https://github.com/FreeRADIUS/freeradius-server/issues/1472 <'If other languages get confused by SQL column names, then those languages are broken.'>
