### ISSUE TITLE
ActionCable stuffs on API-only apps

### ISSUE THREAD

**Issue by ashishbista** [rails/rails#22868]
I created an API app with Rails 5.0.0.beta1. I can see that ActionCable stuffs inside `app/channels` directory, even after passing `--skip-action-cable` option. It also gets loaded in `rails console`. For my project, I don't want ActionCable at all. I believe that this would the case for many API-only apps.

**Comment by matthewd** [comment]
I'm believe this is already fixed on master.

**Comment by joyvuu-dave** [comment]
`--skip-action-cable` still causes an error when `--api` option is used.

```
$ bundle exec rails new  ~/my-test-app --dev --skip-action-cable --api
      create
      create  README.md
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/javascripts/application.js
      create  app/assets/javascripts/cable.coffee
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/update
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/secrets.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/active_record_belongs_to_required_by_default.rb
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/callback_terminator.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/per_form_csrf_tokens.rb
      create  config/initializers/request_forgery_protection.rb
      create  config/initializers/session_store.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/favicon.ico
      create  public/robots.txt
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  tmp
      create  tmp/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
      remove  app/assets
      remove  lib/assets
      remove  tmp/cache/assets
      remove  vendor/assets
      remove  app/helpers
      remove  test/helpers
      remove  app/views
      remove  app/assets/javascripts
      remove  config/initializers/assets.rb
      remove  config/cable.yml
      remove  app/assets/javascripts/cable.coffee
      remove  app/channels
        gsub  app/views/layouts/application.html.erb
/Users/a/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:231:in `binread': No such file or directory @ rb_sysopen - /Users/a/my-test-app/app/views/layouts/application.html.erb (Errno::ENOENT)
	from /Users/a/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:231:in `gsub_file'
	from /Users/a/rails/railties/lib/rails/generators/rails/app/app_generator.rb:321:in `delete_action_cable_files_skipping_action_cable'
	from /Users/a/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/a/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/a/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/a/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/a/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/a/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/a/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/a/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/a/rails/railties/lib/rails/commands/application.rb:17:in `<top (required)>'
	from /Users/a/rails/railties/lib/rails/cli.rb:14:in `require'
	from /Users/a/rails/railties/lib/rails/cli.rb:14:in `<top (required)>'
	from /Users/a/rails/railties/exe/rails:9:in `require'
	from /Users/a/rails/railties/exe/rails:9:in `<top (required)>'
	from /Users/a/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/rails:23:in `load'
	from /Users/a/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/rails:23:in `<main>'
```

Looks like it's trying to remove the main layout, which doesn't exist at this point. 
This is using master branch (f3cf476f8cb920bb83ad8c48321d138b0fa55464).

**Comment by joyvuu-dave** [comment]
Adding `unless options[:api]` to the end of https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/app_generator.rb#L321 fixes it.

**Comment by prathamesh-sonpatki** [comment]
@joyvuu-dave Thanks, fixed it in https://github.com/rails/rails/issues/23205

**Comment by joyvuu-dave** [comment]
Doh! Just opened #23206 to do the same thing. You guys are fast! I'll close mine.

**Comment by prathamesh-sonpatki** [comment]
@joyvuu-dave Wait, I closed mine :) As you found out the issue, lets keep yours open :smile:
