### ISSUE TITLE
Error when starting rails server

### ISSUE THREAD

**Issue by lalithr95** [rails/rails#22884]
There was a problem when I start the server
'rails s' throws me with following error
```bash
Starting Rails4
/Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'mysql2'. (Bundler::GemRequireError)
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/Lalith/Documents/Intern/hackerrank/config/application.rb:7:in `<top (required)>'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:79:in `require'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:79:in `block in server'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```
bundle install works
Mysql 5.7.10 installed through brew
Rails 4.1.7
mysql2 gem 0.3.16

**Comment by rafaelfranca** [comment]
That looks like an error in your mysql2 gem installation.

**Comment by matthewd** [comment]
Update to Rails 4.1.14
