### ISSUE TITLE
uninitialized constant ActiveRecord::ConnectionAdapters::SchemaStatements::ReferenceDefinition

### ISSUE THREAD

**Issue by polysaturate** [rails/rails#22916]
When trying to add a reference to an existing table:

```bin/rails g migration AddOrganizationRefToUsers organization:references```

```ruby
    class AddOrganizationRefToUsers < ActiveRecord::Migration[5.0]
      def change
        add_reference :users, :organization, index: true, foreign_key: true
      end
    end
```
```
== 20160104212402 AddOrganizationRefToUsers: migrating ========================
-- add_reference(:users, :organization, {:index=>true, :foreign_key=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant ActiveRecord::ConnectionAdapters::SchemaStatements::ReferenceDefinition/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/connection_adapters/abstract/schema_statements.rb:801:in `add_reference'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:817:in `block in method_missing'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:786:in `block in say_with_time'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:786:in `say_with_time'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:806:in `method_missing'
/Users/rrace/Sites/standup_app/db/migrate/20160104212402_add_organization_ref_to_users.rb:3:in `change'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:760:in `exec_migration'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:744:in `block (2 levels) in migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:743:in `block in migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:742:in `migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:922:in `migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1174:in `block in execute_migration_in_transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1220:in `block in ddl_transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/connection_adapters/abstract/database_statements.rb:222:in `block in transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/connection_adapters/abstract/transaction.rb:183:in `within_new_transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/connection_adapters/abstract/database_statements.rb:222:in `transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/transactions.rb:211:in `transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1220:in `ddl_transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1173:in `execute_migration_in_transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1160:in `block in migrate_without_lock'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1156:in `each'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1156:in `migrate_without_lock'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1104:in `migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:977:in `up'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:955:in `migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
-e:1:in `<main>'
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::SchemaStatements::ReferenceDefinition
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/connection_adapters/abstract/schema_statements.rb:801:in `add_reference'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:817:in `block in method_missing'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:786:in `block in say_with_time'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:786:in `say_with_time'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:806:in `method_missing'
/Users/rrace/Sites/standup_app/db/migrate/20160104212402_add_organization_ref_to_users.rb:3:in `change'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:760:in `exec_migration'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:744:in `block (2 levels) in migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:743:in `block in migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:742:in `migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:922:in `migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1174:in `block in execute_migration_in_transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1220:in `block in ddl_transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/connection_adapters/abstract/database_statements.rb:222:in `block in transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/connection_adapters/abstract/transaction.rb:183:in `within_new_transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/connection_adapters/abstract/database_statements.rb:222:in `transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/transactions.rb:211:in `transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1220:in `ddl_transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1173:in `execute_migration_in_transaction'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1160:in `block in migrate_without_lock'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1156:in `each'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1156:in `migrate_without_lock'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:1104:in `migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:977:in `up'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/migration.rb:955:in `migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/Users/rrace/.rvm/gems/ruby-2.3.0@standup_r5/gems/activerecord-5.0.0.beta1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by polysaturate** [comment]
The following monkey patch(from 4.2.5 version of the file allowed me to use the add_reference migration:

```ruby
module ActiveRecord
  module ConnectionAdapters # :nodoc:
    module SchemaStatements
      include ActiveRecord::Migration::JoinTable

    def add_reference(table_name, ref_name, options = {})
      polymorphic = options.delete(:polymorphic)
      index_options = options.delete(:index)
      type = options.delete(:type) || :integer
      foreign_key_options = options.delete(:foreign_key)
      if polymorphic && foreign_key_options
        raise ArgumentError, "Cannot add a foreign key to a polymorphic relation"
      end
      add_column(table_name, "#{ref_name}_id", type, options)
      add_column(table_name, "#{ref_name}_type", :string, polymorphic.is_a?(Hash) ? polymorphic : options) if polymorphic
      add_index(table_name, polymorphic ? %w[type id].map{ |t| "#{ref_name}_#{t}" } : "#{ref_name}_id", index_options.is_a?(Hash) ? index_options : {}) if index_options
      if foreign_key_options
        to_table = Base.pluralize_table_names ? ref_name.to_s.pluralize : ref_name
        add_foreign_key(table_name, to_table, foreign_key_options.is_a?(Hash) ? foreign_key_options : {})
      end
    end
      alias :add_belongs_to :add_reference

    end
  end
end
```

Not entirely sure how the rails team will attack the issue though :)

**Comment by adavia** [comment]
Still having the same issue with beta1.1. Fix it with the suggested patch from 4.2.5

**Comment by maclover7** [comment]
@adavia Can you test with Rails master and see if the issue is resolved? Not sure if the PR made it into the beta.

**Comment by adavia** [comment]
@maclover7 Not yet

**Comment by maclover7** [comment]
I am not able to reproduce this bug on master --> bug script available here --> https://gist.github.com/maclover7/d1eee6995f2ee3bd3b65. This should be out in 5.0.0.beta2 soon.
