### ISSUE TITLE
Request IDs don't show on every line for errors

### ISSUE THREAD

**Issue by schneems** [rails/rails#22979]
Requests tagged with `:request_id` do not show up on ever line when there is an error. Example: 

```
[7f8f84ce-d134-4b77-88dc-bac10b54a410]
2016-01-08T20:38:23.835130+00:00 app[web.3]: ActionView::Template::Error (undefined method `new_user_registration_path' for #<ActionDispatch::Routing::RoutesProxy:0x007fece81b1548>):
2016-01-08T20:38:23.835131+00:00 app[web.3]:     3: <% end -%>
2016-01-08T20:38:23.835132+00:00 app[web.3]:     4:
2016-01-08T20:38:23.835133+00:00 app[web.3]:     5: <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
2016-01-08T20:38:23.835134+00:00 app[web.3]:     6:   <%= link_to "Sign up", new_registration_path(resource_name) %><br />
2016-01-08T20:38:23.835134+00:00 app[web.3]:     7: <% end -%>
2016-01-08T20:38:23.835135+00:00 app[web.3]:     8:
2016-01-08T20:38:23.835136+00:00 app[web.3]:     9: <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
2016-01-08T20:38:23.835137+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/routes_proxy.rb:36:in `method_missing'
2016-01-08T20:38:23.835138+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/devise-3.5.2/lib/devise/controllers/url_helpers.rb:51:in `block (4 levels) in generate_helpers!'
2016-01-08T20:38:23.835139+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/devise-3.5.2/app/views/devise/shared/_links.html.erb:6:in `_vendor_bundle_ruby_______gems_devise_______app_views_devise_shared__links_html_erb__2183085242633923340_70327838930360'
2016-01-08T20:38:23.835140+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/actionview-4.2.5/lib/action_view/template.rb:145:in `block in render'
2016-01-08T20:38:23.835141+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
2016-01-08T20:38:23.835142+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/actionview-4.2.5/lib/action_view/template.rb:333:in `instrument'
2016-01-08T20:38:23.835143+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/actionview-4.2.5/lib/action_view/template.rb:143:in `render'
2016-01-08T20:38:23.835144+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/actionview-4.2.5/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
2016-01-08T20:38:23.835144+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/actionview-4.2.5/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
2016-01-08T20:38:23.835145+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/actionview-4.2.5/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
2016-01-08T20:38:23.835146+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'
2016-01-08T20:38:23.835147+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2016-01-08T20:38:23.835147+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
2016-01-08T20:38:23.835148+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/actionview-4.2.5/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
2016-01-08T20:38:23.835149+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/actionview-4.2.5/lib/action_view/renderer/partial_renderer.rb:309:in `render'
2016-01-08T20:38:23.835150+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/actionview-4.2.5/lib/action_view/renderer/renderer.rb:47:in `render_partial'
2016-01-08T20:38:23.835150+00:00 app[web.3]:   vendor/bundle/ruby/2.3.0/gems/actionview-4.2.5/lib/action_view/helpers/rendering_helper.rb:35:in `render'
```

versus

```
2016-01-08T20:38:28.672073+00:00 app[web.1]: [547856d7-3f24-484c-8f40-0cd9b9d26c2b] Processing by PagesController#index as HTML
2016-01-08T20:38:28.685667+00:00 app[web.1]: [547856d7-3f24-484c-8f40-0cd9b9d26c2b]   Rendered application/_github.html.slim (0.2ms)
2016-01-08T20:38:28.758460+00:00 app[web.1]: [547856d7-3f24-484c-8f40-0cd9b9d26c2b]   Rendered repos/_repo.html.slim (39.8ms)
2016-01-08T20:38:28.762702+00:00 app[web.1]: [547856d7-3f24-484c-8f40-0cd9b9d26c2b]   Rendered pages/index.html.slim within layouts/application (84.9ms)
2016-01-08T20:38:28.765791+00:00 app[web.1]: [547856d7-3f24-484c-8f40-0cd9b9d26c2b]   Rendered application/_flashes.html.slim (0.2ms)
2016-01-08T20:38:28.770927+00:00 app[web.1]: [547856d7-3f24-484c-8f40-0cd9b9d26c2b]   Rendered application/_nav.html.slim (4.7ms)
2016-01-08T20:38:28.776329+00:00 app[web.1]: [547856d7-3f24-484c-8f40-0cd9b9d26c2b]   Rendered application/_footer.html.slim (4.1ms)
```

**Comment by vipulnsward** [comment]
Looks like due to https://github.com/rails/rails/blob/da5acae03266808fdbc9a59f43cf8cf7cf25a24e/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L158-L163

@schneems questions is should we do this? With current logging, it gives display of error more horizontal real estate.

**Comment by schneems** [comment]
@vijaydev the reason we want tagged logging is so we can find a request, and then search for everything that happened with that request. If those lines aren't tagged, and two exceptions happen at the same time with different line numbers how will we know which backtrace is correct?

**Comment by vipulnsward** [comment]
```log
[eef02d57-1877-4d1e-9d83-41c5e946c01d] Started GET "/" for 127.0.0.1 at 2016-01-19 01:06:49 +0530
[eef02d57-1877-4d1e-9d83-41c5e946c01d] Processing by HomeController#index as HTML
[eef02d57-1877-4d1e-9d83-41c5e946c01d] _url is /
[eef02d57-1877-4d1e-9d83-41c5e946c01d] _url is after removing .html /
[eef02d57-1877-4d1e-9d83-41c5e946c01d] No redirect url was found for /. before_action check is done. Now controller will handle the request.
[eef02d57-1877-4d1e-9d83-41c5e946c01d]   Rendered home/_heading.html.erb (1.3ms)
[eef02d57-1877-4d1e-9d83-41c5e946c01d]   Rendered home/index.html.erb within layouts/application (3.2ms)
[eef02d57-1877-4d1e-9d83-41c5e946c01d] Completed 500 Internal Server Error in 33ms (ActiveRecord: 0.0ms)
[eef02d57-1877-4d1e-9d83-41c5e946c01d]
ActionView::Template::Error ():
     7:              Awesome Company
     8:           </h1>
     9:           <p>
    10:          <%=raise %>
    11:              Home page
    12:           </p>
    13:        </div>
  app/views/home/_heading.html.erb:10:in `_app_views_home__heading_html_erb__1353240560602087639_70253821972340'
  app/views/home/index.html.erb:1:in `_app_views_home_index_html_erb___3857452698237435190_70253822296220'
  app/controllers/home_controller.rb:4:in `index'
```

It shows this for me, which can be referred by id above. 
I assume, you are referring to the case, when two different requests flush logs and are interleaved when they get written.

**Comment by schneems** [comment]
Yes, the interleaved problem is exactly what request IDs are designed to deal with

```
[eef02d57-1877-4d1e-9d83-41c5e946c01d]
ActionView::Template::Error ():
     7:              Awesome Company
     8:           </h1>
[asdf-asdf-4d1e-asdf-asdf]
ActionView::Template::Error ():
     9:           <p>
     7:              Awesome Company
     8:           </h1>
    10:          <%=raise %>
     9:           <p>
    10:          <%=raise %>
    11:              Home page
    12:           </p>
    11:              Home page
    13:        </div>
    12:           </p>
  app/views/home/_heading.html.erb:10:in 
  app/views/home/index.html.erb:1:in `_app_views_home_index_html_erb___3857452698237435190_70253822296220'
`_app_views_home__heading_html_erb__1353240560602087639_70253821972340'
  app/views/home/index.html.erb:1:in 
  app/views/home/_heading.html.erb:10:in `_app_views_home__heading_html_erb__1353240560602087639_70253821972340'
`_app_views_home_index_html_erb___3857452698237435190_70253822296220'
  app/controllers/home_controller.rb:4:in `index'
    app/controllers/home_controller.rb:4:in `index'
```

**Comment by vipulnsward** [comment]
Got it. Going to work on this.

**Comment by vipulnsward** [comment]
How does this look - https://gist.github.com/vipulnsward/a592a222f8ae3114d725

**Comment by schneems** [comment]
That's great, i think that's exactly what we're looking for :heart:
