### ISSUE TITLE
MySQL test breakage: Mysql2JSONTest raises StatementInvalid

### ISSUE THREAD

**Issue by bronson** [rails/rails#22980]
I'm getting broken mysql2 tests on master.  Travis shows the tests pass: https://travis-ci.org/rails/rails/jobs/101135300

Is the issue is that mariadb isn't supported anymore?
```
$ mysql --version
mysql  Ver 15.1 Distrib 10.1.8-MariaDB, for osx10.10 (x86_64) using readline 5.1
```

No doubt related to https://github.com/rails/rails/pull/21110.   

Here's an example failure, full log is at https://gist.github.com/bronson/19223ccf09aec3941bd6

```
  2) Error:
Mysql2JSONTest#test_select_multikey:
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json, `settings` json) ENGINE=InnoDB' at line 1: CREATE TABLE `json_data_type` (`id` int AUTO_INCREMENT PRIMARY KEY, `payload` json, `settings` json) ENGINE=InnoDB
    /Users/bronson/.gem/ruby/2.2.2/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `_query'
    /Users/bronson/.gem/ruby/2.2.2/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `block in query'
    /Users/bronson/.gem/ruby/2.2.2/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `handle_interrupt'
    /Users/bronson/.gem/ruby/2.2.2/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `query'
    /Users/bronson/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:386:in `block in execute'
    /Users/bronson/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:534:in `block in log'
    /Users/bronson/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /Users/bronson/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:528:in `log'
    /Users/bronson/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:386:in `execute'
    /Users/bronson/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:128:in `execute'
    /Users/bronson/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:269:in `create_table'
    /Users/bronson/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:578:in `create_table'
    /Users/bronson/rails/activerecord/test/cases/adapters/mysql2/json_test.rb:18:in `setup'
```

**Comment by rafaelfranca** [comment]
We only need to keep that test if using mariadb. Mind to open a PR?

**Comment by bronson** [comment]
Happy to but I don't quite understand...  The PR would disable those tests when on Maria?
