### ISSUE TITLE
Rails 5 + collection cache

### ISSUE THREAD

**Issue by kesha-antonov** [rails/rails#23063]
Hey guys!

I used this cache collection in Rails 4 and worked fine. Now I've got an error:

articles/index.html.haml
```
- cache([I18n.locale, @articles]) do
  .static-page.articles
  ...
```

controllers/articles_controller.rb
```
def index
    @articles = Article.published.includes(:category, :user).order(published_at: :desc).paginate(page: params[:page])
end
```

Trace:
```
NoMethodError - undefined method `[]' for nil:NilClass:
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activerecord/lib/active_record/collection_cache_key.rb:20:in `collection_cache_key'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activerecord/lib/active_record/relation.rb:329:in `cache_key'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/cache.rb:94:in `retrieve_cache_key'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/cache.rb:95:in `block in retrieve_cache_key'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/cache.rb:95:in `retrieve_cache_key'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/cache.rb:95:in `block in retrieve_cache_key'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/cache.rb:95:in `retrieve_cache_key'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/cache.rb:87:in `expand_cache_key'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/caching/fragments.rb:67:in `fragment_cache_key'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/caching/fragments.rb:88:in `read_fragment'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/helpers/cache_helper.rb:238:in `read_fragment_for'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/helpers/cache_helper.rb:234:in `fragment_for'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/helpers/cache_helper.rb:169:in `cache'
  app/views/articles/index.html.haml:4:in `_app_views_articles_index_html_haml__1711303327448566922_70207311347160'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/template.rb:159:in `block in render'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/notifications.rb:166:in `instrument'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/template.rb:353:in `instrument'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/template.rb:157:in `render'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/notifications.rb:164:in `instrument'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/renderer/template_renderer.rb:14:in `render'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/renderer/renderer.rb:42:in `render_template'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/renderer/renderer.rb:23:in `render'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/rendering.rb:103:in `_render_template'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/streaming.rb:217:in `_render_template'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/rendering.rb:83:in `render_to_body'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/renderers.rb:144:in `render_to_body'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/abstract_controller/rendering.rb:25:in `render'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/rendering.rb:36:in `render'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/instrumentation.rb:43:in `block (2 levels) in render'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/me/.rbenv/versions/2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/core_ext/benchmark.rb:12:in `ms'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/instrumentation.rb:43:in `block in render'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activerecord/lib/active_record/railties/controller_runtime.rb:30:in `cleanup_view_runtime'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/instrumentation.rb:42:in `render'
  meta-tags (2.1.0) lib/meta_tags/controller_helper.rb:26:in `render_with_meta_tags'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/implicit_render.rb:19:in `default_render'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/abstract_controller/base.rb:183:in `process_action'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/rendering.rb:30:in `process_action'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/callbacks.rb:126:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/callbacks.rb:455:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/callbacks.rb:90:in `run_callbacks'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/abstract_controller/callbacks.rb:19:in `process_action'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/rescue.rb:27:in `process_action'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/notifications.rb:164:in `instrument'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activerecord/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/abstract_controller/base.rb:128:in `process'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/rendering.rb:30:in `process'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal.rb:192:in `dispatch'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_controller/metal.rb:264:in `dispatch'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/routing/route_set.rb:32:in `serve'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/journey/router.rb:42:in `block in serve'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/journey/router.rb:29:in `serve'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/routing/route_set.rb:724:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  http_accept_language (2.0.5) lib/http_accept_language/middleware.rb:14:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionview/lib/action_view/digestor.rb:14:in `call'
  warden (1.2.4) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.4) lib/warden/manager.rb:34:in `call'
  rack (2.0.0.alpha) lib/rack/etag.rb:25:in `call'
  rack (2.0.0.alpha) lib/rack/conditional_get.rb:25:in `call'
  rack (2.0.0.alpha) lib/rack/head.rb:12:in `call'
  rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:220:in `context'
  rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:214:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/middleware/cookies.rb:608:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activerecord/lib/active_record/query_cache.rb:36:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:963:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activerecord/lib/active_record/migration.rb:558:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/callbacks.rb:90:in `run_callbacks'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/middleware/reloader.rb:71:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  airbrake (4.3.5) lib/airbrake/rails/middleware.rb:13:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/railties/lib/rails/rack/logger.rb:42:in `call_app'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/railties/lib/rails/rack/logger.rb:24:in `block in call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/tagged_logging.rb:70:in `block in tagged'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/tagged_logging.rb:26:in `tagged'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/activesupport/lib/active_support/tagged_logging.rb:70:in `tagged'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/railties/lib/rails/rack/logger.rb:24:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.2.1) lib/request_store/middleware.rb:8:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.0.alpha) lib/rack/method_override.rb:22:in `call'
  rack (2.0.0.alpha) lib/rack/runtime.rb:22:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/middleware/load_interlock.rb:13:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/actionpack/lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.0.alpha) lib/rack/sendfile.rb:111:in `call'
  airbrake (4.3.5) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.3.5) lib/airbrake/user_informer.rb:12:in `call'
   () Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-13fc49509b69/railties/lib/rails/engine.rb:522:in `call'
  puma (2.15.3) lib/puma/server.rb:541:in `handle_request'
  puma (2.15.3) lib/puma/server.rb:388:in `process_client'
  puma (2.15.3) lib/puma/server.rb:270:in `block in run'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

Note: I've got this error only on not first page
`articles?page=2`
`articles?page=3`
etc.

Query for 1st page:
```
Cache digest for app/views/articles/index.html.haml: b3aff447bc72cbbbabca539f3a2eee01
   (1.1ms)  SELECT  COUNT(*) AS size, MAX("articles"."updated_at") AS timestamp FROM "articles" WHERE "articles"."status" IN ('published', 'changes_proposed') LIMIT $1 OFFSET $2  [["LIMIT", 5], ["OFFSET", 0]]
```

Query for 2nd page:
```
Cache digest for app/views/articles/index.html.haml: b3aff447bc72cbbbabca539f3a2eee01
   (1.3ms)  SELECT  COUNT(*) AS size, MAX("articles"."updated_at") AS timestamp FROM "articles" WHERE "articles"."status" IN ('published', 'changes_proposed') LIMIT $1 OFFSET $2  [["LIMIT", 5], ["OFFSET", 5]]
```

Any help please?

**Comment by kipcole9** [comment]
There's a bug on master branch that raises an exception if you have a loaded collection but there are no rows (hence why it works on your first page).  There is discussion hereabouts to change the entire strategy of collection cache_key generation but it doesn't seem to have landed yet.

In the mean time I'm using this initialiser that monkey patches collection_cache_key.  Slam this into an initialiser and see if it helps.

--Kip

````ruby
# FIXME Delete this when the PR that changes the entire strategy comes in For Rails 5
# This is patched to not raise an exception if the collection is loaded but there are no records

module ActiveRecord
  module CollectionCacheKey

    def collection_cache_key(collection = all, timestamp_column = :updated_at) # :nodoc:
      query_signature = Digest::MD5.hexdigest(collection.to_sql)
      key = "#{collection.model_name.cache_key}/query-#{query_signature}"

      if collection.loaded? && collection.any?
        size = collection.size
        timestamp = collection.max_by(&timestamp_column).public_send(timestamp_column)
      elsif !collection.loaded?
        column_type = type_for_attribute(timestamp_column.to_s)
        column = "#{connection.quote_table_name(collection.table_name)}.#{connection.quote_column_name(timestamp_column)}"

        query = collection
          .select("COUNT(*) AS size", "MAX(#{column}) AS timestamp")
          .unscope(:order)

        if result = connection.select_one(query)
          size = result["size"]
          timestamp = column_type.deserialize(result["timestamp"])
        else
          size = 0
        end
      end

      if timestamp
        "#{key}-#{size}-#{timestamp.utc.to_s(cache_timestamp_format)}"
      else
        "#{key}-#{size}"
      end
    end
  end
end
````

**Comment by kesha-antonov** [comment]
@kipcole9 Thank you for help!

I've got 60 articles - and that's why I have several pages (5 records each).
What do you mean by "empty collection"?

**Comment by prathamesh-sonpatki** [comment]
@kipcole9 @kesha-antonov https://github.com/rails/rails/pull/23080 and https://github.com/rails/rails/pull/23081 should fix the two this issue and another issue with loaded collections.
