### ISSUE TITLE
validation fails for AR if before_validation not returning true 

### ISSUE THREAD

**Issue by Sacristan** [rails/rails#23136]
rails 4.1.5
ruby 2.1.2

When using before_validation :some_method

if this some_method is not returning true -> validation fails. All fields that are validated are present and all validation conditions are 

```ruby
@record.valid? => false
@record.save => false
@record.errors.size => 0
@record.save! => throws validation error (doh!)
```

Stack:
```
      ActiveRecord::RecordInvalid:
        Validation failed:
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/activerecord-4.2.5/lib/active_record/validations.rb:79:in `raise_record_invalid'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/activerecord-4.2.5/lib/active_record/validations.rb:43:in `save!'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/activerecord-4.2.5/lib/active_record/transactions.rb:291:in `block in save!'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/activerecord-4.2.5/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/activerecord-4.2.5/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/activerecord-4.2.5/lib/active_record/transactions.rb:291:in `save!'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
      # /Users/developer/.rvm/gems/ruby-2.1.2@creativesubscriptions/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
      # ./spec/models/subscription_spec.rb:199:in `block (3 levels) in <top (required)>'
```

This is not a big problem for tested applications if last line always returns false - this is immediately found, but in cases where last line returns false in rare cases and this have not thought through - might get into some big issues like i had. 

Why it works like this ?

**Comment by yogeshjain999** [comment]
@Sacristan I think this behaviour is right. If you haven't added any error to `@record.errors`, and by any chance your validator is returning `false`, then `@record` shouldn't be saved.

**Comment by rafaelfranca** [comment]
Exactly that. This behavior is changed in Rails 5 though.

**Comment by Sacristan** [comment]
Im not adding additional validations here, but creating/updating field values - to ensure that they are present on validation.
