### ISSUE TITLE
Cannot access `owner` from an `has_many` extension method

### ISSUE THREAD

**Issue by hickscorp** [rails/rails#23173]
Consider this code:

```
class Exchange < ActiveRecord::Base
  has_many :ticks, dependent: :destroy do
    def my_assoc_method
      ap owner
    end
  end
end
```

When called like so: `Exchange.first.ticks.my_assoc_method`, an error occurs:

```
Exchange Load (0.2ms)  SELECT  `exchanges`.* FROM `exchanges`  ORDER BY `exchanges`.`id` ASC LIMIT 1
NameError:   Tick Load (0.3ms)  SELECT `ticks`.* FROM `ticks` WHERE `ticks`.`exchange_id` = ?  ORDER BY `ticks`.`created_at` DESC  [["exchange_id", 1]]
undefined local variable or method `owner' for #<Tick::ActiveRecord_Associations_CollectionProxy:0x00000005f5b158>
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/activerecord-4.2.5/lib/active_record/relation/delegation.rb:136:in `method_missing'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/activerecord-4.2.5/lib/active_record/relation/delegation.rb:99:in `method_missing'
	from /home/doodloo/bug/app/models/exchange.rb:5:in `my_assoc_method'
	from (irb):38
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/doodloo/bug/bin/rails:9:in `<top (required)>'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/spring-1.6.2/lib/spring/commands/rails.rb:6:in `call'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/spring-1.6.2/lib/spring/command_wrapper.rb:38:in `call'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/spring-1.6.2/lib/spring/application.rb:185:in `block in serve'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/spring-1.6.2/lib/spring/application.rb:156:in `fork'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/spring-1.6.2/lib/spring/application.rb:156:in `serve'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/spring-1.6.2/lib/spring/application.rb:131:in `block in run'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/spring-1.6.2/lib/spring/application.rb:125:in `loop'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/spring-1.6.2/lib/spring/application.rb:125:in `run'
	from /home/doodloo/.rvm/gems/ruby-2.3.0@Bug/gems/spring-1.6.2/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/doodloo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/doodloo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by maclover7** [comment]
Looking through [api.rubyonrails.org](http://api.rubyonrails.org), I don't think `owner` is a method provided by Active Record -- it's possible this is something internal to your app. If you can reproduce the error using one of the [bug report templates](https://github.com/rails/rails/tree/master/guides/bug_report_templates), please reopen the issue.
