### ISSUE TITLE
`rails runner` command with `<(...)`

### ISSUE THREAD

**Issue by davidpdrsn** [rails/rails#23192]
In zsh (probably also bash) you can turn the output of a command into a file in memory by using `<(...)`. Example:

```
$ ruby <(echo "puts 'hi'")
hi
```

Since this works with the `ruby` command I was expecting it to also work with the `rails runner` command but for some reason it doesn't.

```
$ rails runner <(echo "puts 'hi'")
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/runner.rb:60:in `load': cannot load such file -- /dev/fd/11 (LoadError)
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/runner.rb:60:in `<top (required)>'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:90:in `runner'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
        from /Users/davidpdrsn/source/work/tonsser/api/bin/rails:8:in `<top (required)>'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
```

**Comment by maclover7** [comment]
Not sure if we want to support this... cc @kaspth

**Comment by kaspth** [comment]
We don't take feature requests on the issue tracker, please try the Rails Core mailing list. Thanks!
