### ISSUE TITLE
Action Cable thread leak? Process freeze.

### ISSUE THREAD

**Issue by nateless** [rails/rails#23236]
Hey guys,

Was playing with AC on the beta1, it's a simple app and does nothing ( just started to work on it ) it's been good for some time then I got distracted for an hour or so and it just ping\ponged itself. However when I refreshed browser it was not able to connect to WS, I've tried to ctrl+c AC's app, but it failed. Had to kill -9 it.

I've put a code to dump all threads trapping USR2, and got interesting dump. Fresh puma instance has only 6 threads, but after few page refreshes (ws connection), and after closing the browser it has close to 130 threads. 

all has this content:
```
[48381] /Users/nate/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'
[48381] /Users/nate/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'
[48381] /Users/nate/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'
[48381] /Users/nate/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'
[48381] /Users/nate/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'
[48381] /Users/nate/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:155:in `block in run'
[48381] /Users/nate/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/timers-4.1.1/lib/timers/group.rb:66:in `wait'
[48381] /Users/nate/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'
[48381] /Users/nate/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
[48381] /Users/nate/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
[48381] /Users/nate/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
[48381] /Users/nate/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
```

Is it normal? And what options do we have to debug stuck process except playing with gdb?

**Comment by maclover7** [comment]
cc @matthewd

**Comment by pixeltrix** [comment]
@nateless we've made some significant changes to how Action Cable works like removing Celluloid and Event Machine - can you retest that with the current master branch?

**Comment by nateless** [comment]
Yeah, I will try to make few tests with new version and will reopen this ticket in case I get into the same issue.
