### ISSUE TITLE
uninitialized constant AbstractController::Rendering::ActionController with Actionmailer 4.2.5.1

### ISSUE THREAD

**Issue by reiz** [rails/rails#23259]
I'm using in one of my Gems Actionmailer as standalone dependency. This morning I updated from 4.2.5 to 4.2.5.1 and now my test cases are failing with this kind of exceptions: 

```
NameError: uninitialized constant AbstractController::Rendering::ActionController
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/actionpack-4.2.5.1/lib/abstract_controller/rendering.rb:81:in `_normalize_args'
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/actionview-4.2.5.1/lib/action_view/rendering.rb:114:in `_normalize_args'
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/actionpack-4.2.5.1/lib/abstract_controller/rendering.rb:113:in `_normalize_render'
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/actionpack-4.2.5.1/lib/abstract_controller/rendering.rb:24:in `render'
	from /Users/reiz/workspace/versioneye/versioneye-core/lib/versioneye/mailers/feedback_mailer.rb:11:in `block (2 levels) in feedback_email'
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/actionmailer-4.2.5.1/lib/action_mailer/collector.rb:26:in `custom'
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/actionpack-4.2.5.1/lib/abstract_controller/collector.rb:10:in `html'
	from /Users/reiz/workspace/versioneye/versioneye-core/lib/versioneye/mailers/feedback_mailer.rb:11:in `block in feedback_email'
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/actionmailer-4.2.5.1/lib/action_mailer/base.rb:889:in `collect_responses'
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/actionmailer-4.2.5.1/lib/action_mailer/base.rb:829:in `mail'
	from /Users/reiz/workspace/versioneye/versioneye-core/lib/versioneye/mailers/feedback_mailer.rb:10:in `feedback_email'
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/actionpack-4.2.5.1/lib/abstract_controller/base.rb:198:in `process_action'
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/actionpack-4.2.5.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
	from /Users/reiz/.rvm/gems/ruby-2.2.3@veye-core/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
```

If I downgrade back to 4.2.5 the tests are working again. Any idea what's going on here?

**Comment by prathamesh-sonpatki** [comment]
@reiz Thanks for the issue. It's already reported and being worked upon here  - https://github.com/rails/rails/pull/23242. Closing this issue in favor of #23242.

**Comment by reiz** [comment]
Thx.
