### ISSUE TITLE
wrong number of arguments (5 for 4) Rails 4.1.14.1

### ISSUE THREAD

**Issue by reidcooper** [rails/rails#23253]
I have upgraded our rails to 4.1.14.1 and its dependencies however when I try to render a file,

````
  def show
    path = Rails.root.join('spec','javascripts','fixtures', "#{params[:id]}.html")
    render file: path, layout: nil
  end
````

the render action reports a wrong number of arguments (5 for 4) error. What could be why all of the sudden, this version of rails does not want to find the file? I know that this works with our prior version of Rails, 4.1.11, and the Rails docs are saying that my render is legal.

Edit: When I try rails 4.1.14, that works. I wonder why there is a difference?

````

Started GET "/spec/javascripts/fixtures/savings_meter" for 127.0.0.1 at 2016-01-25 19:13:22 -0500
Processing by JasmineFixturesController#show as HTML
  Parameters: {"id"=>"savings_meter"}
Completed 500 Internal Server Error in 74ms (ActiveRecord: 0.3ms)

ArgumentError - wrong number of arguments (5 for 4):
  actionview (4.1.14.1) lib/action_view/template/resolver.rb:121:in `block in find_all_anywhere'
  actionview (4.1.14.1) lib/action_view/template/resolver.rb:151:in `block in cached'
  actionview (4.1.14.1) lib/action_view/template/resolver.rb:62:in `cache'
  actionview (4.1.14.1) lib/action_view/template/resolver.rb:150:in `cached'
  actionview (4.1.14.1) lib/action_view/template/resolver.rb:120:in `find_all_anywhere'
  actionview (4.1.14.1) lib/action_view/path_set.rb:68:in `block (2 levels) in _find_all'
  actionview (4.1.14.1) lib/action_view/path_set.rb:66:in `block in _find_all'
  actionview (4.1.14.1) lib/action_view/path_set.rb:65:in `_find_all'
  actionview (4.1.14.1) lib/action_view/path_set.rb:50:in `find_file'
  actionview (4.1.14.1) lib/action_view/lookup_context.rb:129:in `find_file'
  actionview (4.1.14.1) lib/action_view/renderer/abstract_renderer.rb:18:in `find_file'
  actionview (4.1.14.1) lib/action_view/renderer/template_renderer.rb:33:in `block in determine_template'
  actionview (4.1.14.1) lib/action_view/lookup_context.rb:149:in `with_fallbacks'
  actionview (4.1.14.1) lib/action_view/renderer/abstract_renderer.rb:18:in `with_fallbacks'
  actionview (4.1.14.1) lib/action_view/renderer/template_renderer.rb:33:in `determine_template'
  actionview (4.1.14.1) lib/action_view/renderer/template_renderer.rb:8:in `render'
  actionview (4.1.14.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.1.14.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.1.14.1) lib/action_view/rendering.rb:99:in `_render_template'
  actionpack (4.1.14.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.1.14.1) lib/action_view/rendering.rb:82:in `render_to_body'
  actionpack (4.1.14.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.1.14.1) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  actionpack (4.1.14.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.1.14.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.1.14.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.1.14.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/reidcooper/.rbenv/versions/2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.1.14.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.1.14.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.1.14.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.1.14.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.1.14.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  active_scaffold (3.4.17) lib/active_scaffold/extensions/action_controller_rendering.rb:14:in `render_with_active_scaffold'
  app/controllers/jasmine_fixtures_controller.rb:4:in `show'

````

````
GIT
  remote: git://github.com/assaf/vanity.git
  revision: d4bdb06b1d6054d3861e1ca93cc0c6e47db3e095
  ref: d4bdb06b1d6054d3861e1ca93cc0c6e47db3e095
  branch: master
  specs:
    vanity (2.0.0.beta8)
      i18n

GIT
  remote: git://github.com/bokmann/business_time.git
  revision: 0782aa46808a412f343e0b851d4a64a3a1aced21
  specs:
    business_time (0.7.4)
      activesupport (>= 3.1.0)
      tzinfo

GIT
  remote: git://github.com/jasonfb/spree.git
  revision: 1038311bf61b2e496547ef502fa4b0e46ac7a44e
  branch: 2-4-stable
  specs:
    spree (2.4.11.beta)
      spree_api (= 2.4.11.beta)
      spree_backend (= 2.4.11.beta)
      spree_cmd (= 2.4.11.beta)
      spree_core (= 2.4.11.beta)
      spree_frontend (= 2.4.11.beta)
      spree_sample (= 2.4.11.beta)
    spree_api (2.4.11.beta)
      rabl (~> 0.9.4.pre1)
      spree_core (= 2.4.11.beta)
      versioncake (~> 2.3.1)
    spree_backend (2.4.11.beta)
      jquery-rails (~> 3.1.2)
      jquery-ui-rails (~> 5.0.0)
      select2-rails (= 3.5.9.1)
      spree_api (= 2.4.11.beta)
      spree_core (= 2.4.11.beta)
    spree_cmd (2.4.11.beta)
      thor (~> 0.14)
    spree_core (2.4.11.beta)
      activemerchant (~> 1.44.1)
      acts_as_list (~> 0.3)
      awesome_nested_set (~> 3.0.1)
      cancancan (~> 1.9.2)
      carmen (~> 1.0.0)
      deface (~> 1.0.0)
      ffaker (~> 1.16)
      font-awesome-rails (~> 4.0)
      friendly_id (~> 5.0.4)
      highline (~> 1.6.18)
      json (~> 1.7)
      kaminari (~> 0.15, >= 0.15.1)
      monetize (~> 1.1)
      paperclip (~> 4.2.0)
      paranoia (~> 2.1.0)
      premailer-rails
      rails (~> 4.1.11)
      ransack (~> 1.4.1)
      state_machine (= 1.2.0)
      stringex (~> 1.5.1)
      truncate_html (= 0.9.2)
      twitter_cldr (~> 3.0)
    spree_frontend (2.4.11.beta)
      canonical-rails (~> 0.0.4)
      jquery-rails (~> 3.1.2)
      spree_api (= 2.4.11.beta)
      spree_core (= 2.4.11.beta)
    spree_sample (2.4.11.beta)
      spree_core (= 2.4.11.beta)

GIT
  remote: git://github.com/jasonfb/spree_avatax_certified.git
  revision: c376385f1975e52a3adc38c7088daa4205f36cca
  ref: c376385f1975e52a3adc38c7088daa4205f36cca
  branch: 2-4-stable
  specs:
    spree_avatax_certified (2.4.2)
      addressable (~> 2.3)
      json (~> 1.7)
      logging (~> 1.8)
      psych (~> 2.0.4)
      rest-client (~> 1.7)
      spree_core (~> 2.4.0)

GIT
  remote: git://github.com/mackweldon/spree_gateway.git
  revision: 73e3d75452163ef0d6ccb3d1c21951f4ea633ed4
  branch: 2-4-stable
  specs:
    spree_gateway (2.4.0)
      spree_core (~> 2.4.0)

GIT
  remote: git://github.com/mackweldon/spree_google_merchant.git
  revision: 6bc864c0d30a30c45900910c2bd3858ff0ee7fd4
  branch: 2-4-stable
  specs:
    spree_google_merchant (2.4.0)
      net-sftp (= 2.1.2)
      spree (~> 2.4)

GIT
  remote: git://github.com/mackweldon/spree_shipping_labeler.git
  revision: dc0680a5a63c4400b1265e33082c3f2d42b4fdac
  branch: 2-4-stable
  specs:
    spree_shipping_labeler (2.3.0)
      coffee-rails (~> 4.0.0)
      fedex (~> 3.6.1)
      spree_core (~> 2.4.0)

GIT
  remote: git://github.com/reidcooper/spree_auth_devise.git
  revision: de265a72c568fbeaa09d733351fcd18cb2cad018
  branch: 2-4-stable
  specs:
    spree_auth_devise (2.4.0)
      devise (~> 3.2.3)
      devise-encryptable (= 0.1.2)
      json
      multi_json
      spree_core (~> 2.4.0)

GIT
  remote: git://github.com/spree-contrib/spree_legacy_return_authorizations.git
  revision: 9968f25e12fd6f19e8fa07fa8e52ece8a1f99475
  branch: master
  specs:
    spree_legacy_return_authorizations (2.4.0)
      spree_core (~> 2.4.0)

GIT
  remote: git://github.com/spree-contrib/spree_related_products.git
  revision: d3452dbba6a748e75354fd912a893e6669b72063
  branch: 2-4-stable
  specs:
    spree_related_products (3.2)
      spree_backend (~> 2.4.0)

GIT
  remote: git://github.com/spree-contrib/spree_sitemap.git
  revision: 5ed6b1cb17b32cac9b9eefe4d9d95bad179e211f
  branch: 2-4-stable
  specs:
    spree_sitemap (2.0.0.beta)
      sitemap_generator (~> 4.3.1)
      spree_core (~> 2.4.0)

GIT
  remote: https://github.com/nofxx/symbolize.git
  revision: 58b258c7964ca200c3bdf0061f0c98306bfcbead
  ref: 58b258c7964ca200c3bdf0061f0c98306bfcbead
  specs:
    symbolize (4.5.1)
      activemodel (>= 3.2, < 5)
      activesupport (>= 3.2, < 5)

GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.0)
    actionmailer (4.1.14.1)
      actionpack (= 4.1.14.1)
      actionview (= 4.1.14.1)
      mail (~> 2.5, >= 2.5.4)
    actionpack (4.1.14.1)
      actionview (= 4.1.14.1)
      activesupport (= 4.1.14.1)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    actionview (4.1.14.1)
      activesupport (= 4.1.14.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
    active_model_serializers (0.9.3)
      activemodel (>= 3.2)
    active_record_query_trace (1.3)
    active_scaffold (3.4.17)
      rails (>= 3.2.18, < 5)
    active_utils (2.2.3)
      activesupport (>= 2.3.11)
      i18n
    activemerchant (1.44.1)
      active_utils (~> 2.2.0)
      activesupport (>= 3.2.14, < 5.0.0)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      json (~> 1.7)
      nokogiri (~> 1.4)
      offsite_payments (~> 2.0.0)
    activemodel (4.1.14.1)
      activesupport (= 4.1.14.1)
      builder (~> 3.1)
    activerecord (4.1.14.1)
      activemodel (= 4.1.14.1)
      activesupport (= 4.1.14.1)
      arel (~> 5.0.0)
    activerecord-session_store (0.1.1)
      actionpack (>= 4.0.0, < 5)
      activerecord (>= 4.0.0, < 5)
      railties (>= 4.0.0, < 5)
    activesupport (4.1.14.1)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    acts-as-taggable-on (3.5.0)
      activerecord (>= 3.2, < 5)
    acts_as_list (0.7.2)
      activerecord (>= 3.0)
    addressable (2.3.8)
    ancestry (2.1.0)
      activerecord (>= 3.0.0)
    arel (5.0.1.20140414130214)
    asset_sync (1.1.0)
      activemodel
      fog (>= 1.8.0)
      unf
    audited (4.0.0)
      rails-observers (~> 0.1.2)
    audited-activerecord (4.0.0)
      activerecord (~> 4.0)
      audited (= 4.0.0)
    autoprefixer-rails (5.1.7)
      execjs
      json
    awesome_nested_set (3.0.2)
      activerecord (>= 4.0.0, < 5)
    awesome_print (1.6.1)
    aws-sdk (1.27.0)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
      uuidtools (~> 2.1)
    bcrypt (3.1.10)
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.3)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.2.19)
    builder (3.2.2)
    bullet (4.14.5)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.9.0)
    byebug (3.5.1)
      columnize (~> 0.8)
      debugger-linecache (~> 1.2)
      slop (~> 3.6)
    callsite (0.0.11)
    camertron-eprun (1.1.0)
    cancancan (1.9.2)
    canonical-rails (0.0.11)
      rails (>= 3.1, < 5.0)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-webkit (1.7.1)
      capybara (>= 2.3.0, < 2.6.0)
      json
    carmen (1.0.2)
      activesupport (>= 3.0.0)
    childprocess (0.5.7)
      ffi (~> 1.0, >= 1.0.11)
    ckeditor (4.1.1)
      cocaine
      orm_adapter (~> 0.5.0)
    cldr-plurals-runtime-rb (1.0.1)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.8)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.0)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    colorize (0.7.7)
    columnize (0.9.0)
    commonjs (0.2.7)
    crack (0.4.2)
      safe_yaml (~> 1.0.0)
    css_parser (1.3.7)
      addressable
    dalli (2.7.2)
    database_cleaner (1.4.0)
    debug_inspector (0.0.2)
    debugger-linecache (1.2.0)
    deface (1.0.2)
      colorize (>= 0.5.8)
      nokogiri (~> 1.6.0)
      polyglot
      rails (>= 3.1)
    delayed_paperclip (2.9.1)
      paperclip (>= 3.3)
    devise (3.2.4)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-encryptable (0.1.2)
      devise (>= 2.1.0)
    diff-lcs (1.2.5)
    docile (1.1.5)
    domain_name (0.5.25)
      unf (>= 0.0.5, < 1.0.0)
    erubis (2.7.0)
    excon (0.44.1)
    execjs (2.6.0)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    fedex (3.6.1)
      httparty (~> 0.13.0)
      nokogiri (~> 1.6.0)
    ffaker (1.32.1)
    ffi (1.9.10)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    fog (1.27.0)
      fog-atmos
      fog-aws (~> 0.0)
      fog-brightbox (~> 0.4)
      fog-core (~> 1.27, >= 1.27.3)
      fog-ecloud
      fog-json
      fog-profitbricks
      fog-radosgw (>= 0.0.2)
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
      nokogiri (~> 1.5, >= 1.5.11)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.1.0)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.7.1)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-core (1.28.0)
      builder
      excon (~> 0.38)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-ecloud (0.0.2)
      fog-core
      fog-xml
    fog-json (1.0.0)
      multi_json (~> 1.0)
    fog-profitbricks (0.0.1)
      fog-core
      fog-xml
      nokogiri
    fog-radosgw (0.0.3)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-sakuracloud (1.0.0)
      fog-core
      fog-json
    fog-serverlove (0.1.1)
      fog-core
      fog-json
    fog-softlayer (0.4.0)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.0)
      fog-core
      fog-json
    fog-terremark (0.0.3)
      fog-core
      fog-xml
    fog-vmfusion (0.0.1)
      fission
      fog-core
    fog-voxel (0.0.2)
      fog-core
      fog-xml
    fog-xml (0.1.1)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    font-awesome-rails (4.5.0.0)
      railties (>= 3.2, < 5.0)
    font-awesome-sass (4.3.2.1)
      sass (~> 3.2)
    formatador (0.2.5)
    friendly_id (5.0.5)
      activerecord (>= 4.0.0)
    haml (4.0.6)
      tilt
    haml_coffee_assets (1.16.0)
      coffee-script (~> 2.0)
      sprockets (~> 2.0)
      tilt (~> 1.1)
    highline (1.6.21)
    hike (1.2.3)
    hipchat (1.5.2)
      httparty
      mimemagic
    honeybadger (2.0.6)
    htmlentities (4.3.4)
    htmlrender (0.0.0)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    httparty (0.13.7)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.6.9)
    inflecto (0.0.2)
    ipaddress (0.8.0)
    jasmine-core (2.3.4)
    jasmine-jquery-rails (2.0.3)
    jasmine-rails (0.10.8)
      jasmine-core (>= 1.3, < 3.0)
      phantomjs (>= 1.9)
      railties (>= 3.2.0)
      sprockets-rails
    jquery-fileupload-rails (0.4.4)
      actionpack (>= 3.1)
      railties (>= 3.1)
      sass (>= 3.2)
    jquery-rails (3.1.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    kgio (2.9.3)
    launchy (2.4.3)
      addressable (~> 2.3)
    less (2.6.0)
      commonjs (~> 0.2.7)
    less-rails (2.6.0)
      actionpack (>= 3.1)
      less (~> 2.6.0)
    libv8 (3.16.14.7)
    little-plugger (1.1.4)
    logging (1.8.2)
      little-plugger (>= 1.1.3)
      multi_json (>= 1.8.4)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    marionette-rails (2.4.1)
      railties (>= 3.1)
    meta_request (0.3.4)
      callsite (~> 0.0, >= 0.0.11)
      rack-contrib (~> 1.1)
      railties (>= 3.0.0, < 5.0.0)
    mime-types (2.99)
    mimemagic (0.3.0)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    modernizr-rails (2.7.1)
    monetize (1.3.1)
      money (~> 6.6)
    money (6.6.1)
      i18n (>= 0.6.4, <= 0.7.0)
    mono_logger (1.1.0)
    multi_json (1.11.2)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    mysql2 (0.3.17)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-sftp (2.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.2)
    netrc (0.11.0)
    newrelic_rpm (3.9.9.275)
    nokogiri (1.6.7)
      mini_portile2 (~> 2.0.0.rc2)
    nondestructive_migrations (1.1)
      activerecord (>= 4.0)
    offsite_payments (2.0.1)
      active_utils (~> 2.2.0)
      activesupport (>= 3.2.14, < 5.0.0)
      builder (>= 2.1.2, < 4.0.0)
      i18n (~> 0.5)
      json (~> 1.7)
      money (< 7.0.0)
      nokogiri (~> 1.4)
    orm_adapter (0.5.0)
    pagerduty (2.0.0)
      json (>= 1.7.7)
    paperclip (4.2.4)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
    paranoia (2.1.4)
      activerecord (~> 4.0)
    pdf-core (0.4.0)
    phantomjs (1.9.8.0)
    polyamorous (1.2.0)
      activerecord (>= 3.0)
    polyglot (0.3.5)
    prawn (1.3.0)
      pdf-core (~> 0.4.0)
      ttfunk (~> 1.4.0)
    premailer (1.8.6)
      css_parser (>= 1.3.6)
      htmlentities (>= 4.0.0)
    premailer-rails (1.8.2)
      actionmailer (>= 3, < 5)
      premailer (~> 1.7, >= 1.7.9)
    psych (2.0.15)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rabl (0.9.4.pre1)
      activesupport (>= 2.3.14)
    rack (1.5.5)
    rack-attack (4.3.0)
      rack
    rack-contrib (1.2.0)
      rack (>= 0.9.1)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rack-timeout (0.2.0)
    rack_session_access (0.1.1)
      builder (>= 2.0.0)
      rack (>= 1.0.0)
    rails (4.1.14.1)
      actionmailer (= 4.1.14.1)
      actionpack (= 4.1.14.1)
      actionview (= 4.1.14.1)
      activemodel (= 4.1.14.1)
      activerecord (= 4.1.14.1)
      activesupport (= 4.1.14.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.1.14.1)
      sprockets-rails (~> 2.0)
    rails-observers (0.1.2)
      activemodel (~> 4.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.4)
    rails_stdout_logging (0.0.3)
    railties (4.1.14.1)
      actionpack (= 4.1.14.1)
      activesupport (= 4.1.14.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    raindrops (0.13.0)
    rake (10.5.0)
    ransack (1.4.1)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.1)
    redis (3.2.0)
    redis-namespace (1.5.1)
      redis (~> 3.0, >= 3.0.4)
    ref (1.0.5)
    resque (1.25.2)
      mono_logger (~> 1.0)
      multi_json (~> 1.0)
      redis-namespace (~> 1.3)
      sinatra (>= 0.9.2)
      vegas (~> 0.1.2)
    resque-cleaner (0.3.0)
      resque (~> 1.0)
    resque-loner (1.3.0)
      resque (~> 1.0)
    resque-retry (1.4.0)
      resque (~> 1.25)
      resque-scheduler (~> 4.0)
    resque-scheduler (4.0.0)
      mono_logger (~> 1.0)
      redis (~> 3.0)
      resque (~> 1.25)
      rufus-scheduler (~> 3.0)
    resque_mailer (2.2.7)
      actionmailer (>= 3.0)
    resque_spec (0.15.0)
      resque (>= 1.19.0)
      rspec-core (>= 2.5.0)
      rspec-expectations (>= 2.5.0)
      rspec-mocks (>= 2.5.0)
    rest-client (1.8.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rspec (3.3.0)
      rspec-core (~> 3.3.0)
      rspec-expectations (~> 3.3.0)
      rspec-mocks (~> 3.3.0)
    rspec-core (3.3.2)
      rspec-support (~> 3.3.0)
    rspec-expectations (3.3.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-mocks (3.3.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-rails (3.3.3)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.3.0)
      rspec-expectations (~> 3.3.0)
      rspec-mocks (~> 3.3.0)
      rspec-support (~> 3.3.0)
    rspec-support (3.3.0)
    rubyzip (1.1.7)
    rufus-scheduler (3.0.9)
      tzinfo
    safe_yaml (1.0.4)
    sailthru-client (4.0.1)
      json
      multipart-post
    sass (3.4.13)
    sass-rails (5.0.1)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (~> 1.1)
    select2-rails (3.5.9.1)
      thor (~> 0.14)
    selenium-webdriver (2.48.1)
      childprocess (~> 0.5)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0)
    settingslogic (2.0.9)
    shoulda-matchers (2.8.0)
      activesupport (>= 3.0.0)
    simplecov (0.9.1)
      docile (~> 1.1.0)
      multi_json (~> 1.0)
      simplecov-html (~> 0.8.0)
    simplecov-html (0.8.0)
    sinatra (1.4.5)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (~> 1.3, >= 1.3.4)
    sitemap_generator (4.3.1)
      builder
    slim (3.0.2)
      temple (~> 0.7.3)
      tilt (>= 1.3.3, < 2.1)
    slop (3.6.0)
    sprockets (2.12.4)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    state_machine (1.2.0)
    stringex (1.5.1)
    temple (0.7.5)
    therubyracer (0.12.1)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    truncate_html (0.9.2)
    ttfunk (1.4.0)
    twitter-bootstrap-rails (3.2.0)
      actionpack (~> 4.1)
      execjs (~> 2.2)
      rails (~> 4.1)
      railties (~> 4.1)
    twitter_cldr (3.2.1)
      camertron-eprun
      cldr-plurals-runtime-rb (~> 1.0.0)
      json
      tzinfo
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.0)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    unicorn (4.8.3)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    uniform_notifier (1.9.0)
    uuidtools (2.1.5)
    vcr (2.9.3)
    vegas (0.1.11)
      rack (>= 1.0.0)
    versioncake (2.3.1)
      actionpack (>= 3.2)
      activesupport (>= 3.2)
      railties (>= 3.2)
      tzinfo
    warden (1.2.3)
      rack (>= 1.0)
    webmock (1.20.4)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
    websocket (1.2.2)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  active_model_serializers
  active_record_query_trace
  active_scaffold (= 3.4.17)
  activerecord-session_store
  acts-as-taggable-on (~> 3.4)
  acts_as_list
  ancestry
  asset_sync
  audited-activerecord (~> 4.0)
  awesome_print
  aws-sdk (= 1.27.0)
  better_errors
  binding_of_caller
  bootstrap-sass (~> 3.3.3)
  bullet
  business_time!
  byebug
  capybara (= 2.5.0)
  capybara-webkit
  ckeditor
  coffee-rails
  dalli
  database_cleaner
  delayed_paperclip
  execjs
  factory_girl_rails
  ffaker
  fog (~> 1.20)
  font-awesome-sass
  haml
  haml_coffee_assets
  hipchat
  honeybadger (= 2.0.6)
  htmlrender
  i18n (= 0.6.9)
  jasmine-jquery-rails
  jasmine-rails
  jquery-fileupload-rails
  jquery-rails (~> 3.1.3)
  launchy
  less-rails
  libv8 (~> 3.16.14.0)
  marionette-rails
  meta_request
  modernizr-rails
  mysql2 (= 0.3.17)
  newrelic_rpm
  nondestructive_migrations (= 1.1)
  pagerduty
  paperclip
  prawn
  quiet_assets
  rack-attack
  rack-timeout
  rack_session_access
  rails (= 4.1.14.1)
  rails_12factor
  redis
  resque
  resque-cleaner
  resque-loner
  resque-retry
  resque-scheduler
  resque_mailer
  resque_spec
  rspec
  rspec-mocks
  rspec-rails
  rubyzip (>= 1.0.0)
  sailthru-client
  sass-rails
  selenium-webdriver (= 2.48.1)
  settingslogic
  shoulda-matchers
  simplecov
  slim
  spree!
  spree_auth_devise!
  spree_avatax_certified!
  spree_gateway!
  spree_google_merchant!
  spree_legacy_return_authorizations!
  spree_related_products!
  spree_shipping_labeler!
  spree_sitemap!
  symbolize!
  therubyracer
  twitter-bootstrap-rails (= 3.2.0)
  uglifier (>= 1.0.3)
  unicorn
  vanity!
  vcr
  webmock

BUNDLED WITH
   1.10.6
````

**Comment by maclover7** [comment]
Yes, this is introduced as apart of the security fixes today. Rails 4.1.14.2 is scheduled to come out soon with a fix for this. To help things move along faster, you can try and open up a PR to backport the changes in [this PR](https://github.com/rails/rails/pull/23247) to the 4-1-stable branch.

**Comment by reidcooper** [comment]
Okay thank you, I thought I was going insane.

**Comment by maclover7** [comment]
@reidcooper Can you provide a sample application to reproduce the error you are seeing? Based on a vanilla Rails app, I am unable to reproduce the `ArgumentError` you are seeing. I think that one of the dependencies you have specified in your Gemfile is relying on behavior that was changed in a breaking change in `4.1.14.1`.

**Comment by reidcooper** [comment]
At the moment I am not at my computer until tomorrow but, I have Jasmine specs using some fixtures that I need to load in. I have them located in specs/javascripts/fixtures. In my routes, I have a explicit route with a parameter at the end to say which file I want to grab from the fixtures folder, specs/javascripts/fixtures/:id which routes to this controller action. This action should just display the file on screen if you type in the URL to see if the action works. In that case, the rendering doesn't work. I get this argument mismatch.

**Comment by jasonfb** [comment]
hey guys -- I think it is this: https://github.com/netzpirat/haml_coffee_assets/issues/146

@reidcooper @maclover7

**Comment by jasonfb** [comment]
FYI-- I checked the interim versions of rails, this appears to come from 4.14.12. also present in 4.14.13 and 4.14.14

**Comment by jasonfb** [comment]
@reidcooper @maclover7 -- Sadly (and oddly) it is come to my attention that the maintainer of the Gem in question passed away in April 2014. I will follow-up with GH about their repo abandonment process. In the meantime I have made our available here: https://github.com/mackweldon/haml_coffee_assets

**Comment by maclover7** [comment]
:+1: ok -- best of luck with updating your gem :)
