### ISSUE TITLE
Rails 5 ActionCable: undefined method `fetch' for nil:NilClass

### ISSUE THREAD

**Issue by kesha-antonov** [rails/rails#23337]
Hello guys!

I see this error when calling `ActionCable.server.broadcast`. Can you advise please?

```
E, [2016-01-29T22:45:37.975026 #20367] ERROR -- : Exception NoMethodError -> undefined method `fetch' for nil:NilClass
   /Users/kesha/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-703ddadafee2/actioncable/lib/action_cable/server/configuration.rb:39:in `pubsub_adapter'
   /Users/kesha/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-703ddadafee2/actioncable/lib/action_cable/server/base.rb:63:in `block in pubsub'
   /Users/kesha/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-703ddadafee2/actioncable/lib/action_cable/server/base.rb:63:in `synchronize'
   /Users/kesha/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-703ddadafee2/actioncable/lib/action_cable/server/base.rb:63:in `pubsub'
   /Users/kesha/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-703ddadafee2/actioncable/lib/action_cable/server/broadcasting.rb:42:in `broadcast'
   /Users/kesha/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-703ddadafee2/actioncable/lib/action_cable/server/broadcasting.rb:23:in `broadcast'
```

**Comment by maclover7** [comment]
Can you post a sample app to reproduce the issue here? I think this might be due to a configuration issue in your `config/cable.yml`.

**Comment by nateless** [comment]
Yeah @maclover7, had the same issue as old AC guide used redis.yml and now we use `config/cable.yml`.

**Comment by kaspth** [comment]
Have you set an adapter in `config/cable.yml`? @maclover7 recently changed this when adding Postgres pub sub support.

Adding `adapter: redis` should do it.

**Comment by kaspth** [comment]
I'll close those for now. Do reopen if my suggestion doesn't fix it.

**Comment by kesha-antonov** [comment]
Hey! Thanks!

I moved `config/redis/cable.yml` to `config/cable.yml`
Added
```
gem 'em-hiredis'
gem 'redis'
```
to Gemfile (AC was asking me for this)
and got it working.

This is `cable.yml`:
```
production: &production
  url: redis://localhost:6379
  adapter: redis
development: &development
  url: redis://localhost:6379
test: *development
```

**Comment by kaspth** [comment]
Nice!

**Comment by maclover7** [comment]
:raised_hands: awesome!

**Comment by meghasharma13492** [comment]
Perfect Thanks !!

**Comment by iarobinson** [comment]
FYI -

This error was something I struggled with as well. I was able to solve it just by adding a single blank file to the config file.

```
# Add a blank file at path 
config/cable.yml
```
