### ISSUE TITLE
Unable to start rails5.beta1.1 server, get 'cannot load such file -- action_cable/process/logging'

### ISSUE THREAD

**Issue by pisaacs** [rails/rails#23367]
Twice since working with rails5 master (beta1) I have received the below error message when starting rails. I `bundle update` to ensure the app is using the latest gems prior to starting the rails server. I even removed the rails 5 beta 1 gem and reinstalled it (`gem install rails --version 5.0.0.beta1.1 --no-ri --no-rdoc`). I can't remember what I actions I took to resolve the the issue when it first occurred (might have been when I bundle update from beta1 to beta1.1). 

```
Phillips-MBP:cleartext phillip$ rails s
=> Booting Puma
=> Rails 5.0.0.beta1.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/activesupport/lib/active_support/dependencies.rb:302:in `require': cannot load such file -- action_cable/process/logging (LoadError)
	from /Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /Users/phillip/rails/cleartext/config.ru:7:in `block in <main>'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `initialize'
	from /Users/phillip/rails/cleartext/config.ru:in `new'
	from /Users/phillip/rails/cleartext/config.ru:in `<main>'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `eval'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:40:in `parse_file'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:218:in `app'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/railties/lib/rails/commands/server.rb:58:in `app'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/railties/lib/rails/commands/server.rb:136:in `log_to_stdout'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/railties/lib/rails/commands/server.rb:76:in `start'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/railties/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/railties/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/railties/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/railties/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/railties/lib/rails/command.rb:20:in `run'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/bundler/gems/rails-a00c36feea6c/railties/lib/rails/commands.rb:19:in `<top (required)>'
	from /Users/phillip/rails/cleartext/bin/rails:9:in `require'
	from /Users/phillip/rails/cleartext/bin/rails:9:in `<top (required)>'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/spring-1.6.2/lib/spring/client/rails.rb:28:in `load'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/spring-1.6.2/lib/spring/client/rails.rb:28:in `call'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/spring-1.6.2/lib/spring/client/command.rb:7:in `call'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/spring-1.6.2/lib/spring/client.rb:28:in `run'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/spring-1.6.2/bin/spring:49:in `<top (required)>'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/spring-1.6.2/lib/spring/binstub.rb:11:in `load'
	from /Users/phillip/.rvm/gems/ruby-2.3.0/gems/spring-1.6.2/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/phillip/rails/cleartext/bin/spring:13:in `require'
	from /Users/phillip/rails/cleartext/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

I was only able to start rails after commenting out `action_cable/process/logging` from `config.ru`

```
#require 'action_cable/process/logging'
```
After commenting out, rails starts without issue, and I am able to use the app.
```
Phillips-MBP:cleartext phillip$ rails s
=> Booting Puma
=> Rails 5.0.0.beta1.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.16.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000
```

Here's my gem file:

```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
#gem 'rails', '>= 5.0.0.beta1', '< 5.1'
gem 'rails', github: 'rails/rails'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# Use Puma as the app server
gem 'puma'

.....
# other gems, dev, dev and test groups, etc...
```

**Comment by maclover7** [comment]
I believe that if you trying upgrading to Rails master from beta1.1, then your app should start up normally. cc @matthewd since you removed this via https://github.com/rails/rails/commit/503fe757c7f5f917deab95acdcd421a1dede05c7

**Comment by matthewd** [comment]
Deleting that `require` is indeed the right thing to do; that file is gone on master.

**Comment by pisaacs** [comment]
I can confirm `require 'action_cable/process/logging'` in `config.ru` as the issue. I was able to create the issue with a new project - thank you!

So if one installs the `5.0.0.beta1.1` gem (latest edge on rubygems), generates a new rails project, then updates Gemfile to point to master (`gem 'rails', github: 'rails/rails'`), then this issue will crop up...

**Comment by zavan** [comment]
I'm having this issue on Rails 5.0.0.beta.2:

`/home/zavan/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in 'require': cannot load such file -- action_cable/process/logging (LoadError)`

**Comment by pisaacs** [comment]
@zavan 
remove `require 'action_cable/process/logging'` from `config.ru`

**Comment by zavan** [comment]
@pisaacs This solves it. I understand the problem now, this is legacy code from the beta1 app generator, for EventMachine, which is not used anymore.
Thanks!

**Comment by Vaibhavi111** [comment]
SyntaxError: [stdin]:1:1: unexpected //
Extracted source (around line #9):
     
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
 
in rails 5.0.0.beta1
