### ISSUE TITLE
ActionCable not working with Thin

### ISSUE THREAD

**Issue by Nekromancer** [rails/rails#23696]
I got an exception `NoMethodError(undefined 'method possible?' for nil:NilClass)` while using Thin server. Puma is working correctly.

Full stacktrace:

```
[ERROR] There was an exception - NoMethodError(undefined method `possible?' for nil:NilClass)
[ERROR] /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/base.rb:216:in `finished_request_message'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/base.rb:166:in `handle_close'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker.rb:34:in `block in invoke'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:126:in `call'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:455:in `call'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker/active_record_connection_management.rb:15:in `block in with_database_connections'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/tagged_logger_proxy.rb:22:in `block in tag'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/tagged_logging.rb:70:in `block in tagged'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/tagged_logging.rb:70:in `tagged'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/tagged_logger_proxy.rb:22:in `tag'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker/active_record_connection_management.rb:15:in `with_database_connections'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:285:in `block in halting'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:447:in `block in around'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:455:in `call'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:750:in `_run_work_callbacks'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker.rb:33:in `invoke'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker.rb:25:in `block in async_invoke'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:333:in `run_task'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:322:in `block (3 levels) in create_worker'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:305:in `loop'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:305:in `block (2 levels) in create_worker'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:304:in `catch'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:304:in `block in create_worker'
[INFO ] GET     "/cable/"  for 127.0.0.1  at 2016-02-15 23:18:26 +0000
[INFO ] GET     "/cable"  for 127.0.0.1  at 2016-02-15 23:18:35 +0000
[ERROR] There was an exception - NoMethodError(undefined method `possible?' for nil:NilClass)
[ERROR] /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/base.rb:216:in `finished_request_message'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/base.rb:166:in `handle_close'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker.rb:34:in `block in invoke'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:126:in `call'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:455:in `call'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker/active_record_connection_management.rb:15:in `block in with_database_connections'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/tagged_logger_proxy.rb:22:in `block in tag'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/tagged_logging.rb:70:in `block in tagged'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/tagged_logging.rb:70:in `tagged'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/tagged_logger_proxy.rb:22:in `tag'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker/active_record_connection_management.rb:15:in `with_database_connections'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:285:in `block in halting'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:447:in `block in around'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:455:in `call'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:750:in `_run_work_callbacks'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker.rb:33:in `invoke'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker.rb:25:in `block in async_invoke'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:333:in `run_task'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:322:in `block (3 levels) in create_worker'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:305:in `loop'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:305:in `block (2 levels) in create_worker'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:304:in `catch'
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:304:in `block in create_worker'
```

**Comment by maclover7** [comment]
Can you please post a sample application replicate the error?

**Comment by Nekromancer** [comment]
https://github.com/Nekromancer/ThinProblem Here is basic ActionCable setup with thin server. It fails instantly after going on localhost:3000

**Comment by maclover7** [comment]
Looking into this.

**Comment by maclover7** [comment]
Took a deeper look at this, and since the error is coming from within our `concurrent-ruby` delayed worker apparatus, I'm going to pass this on to @matthewd, who's spent a bit of time with the `concurrent-ruby` setup within Action Cable. I'm thinking that we're somehow losing state (or the `receiver` that's being passed into the `Worker` isn't the latest version of the object), or some kind of awkward edge case like that, based on that `subscriptions` and `websocket` are both suspiciously nil...

Thank you for reporting this!

r? @matthewd.

**Comment by matthewd** [comment]
ActionCable requires full rack hijack support, which [Thin doesn't have](https://github.com/macournoyer/thin/issues/157), and unfortunately, I don't think we can afford to carry monkey-patches to make it work, [as faye-websocket does](https://github.com/faye/faye-websocket-ruby/blob/master/lib/faye/adapters/thin.rb).

Hopefully either thin will enable rack hijack support, or someone else will release a gem that patches things together, or something. :disappointed_relieved:

**Comment by macournoyer** [comment]
ActionCable does work w/ Thin now w/ a few extra configs:

In your `Gemfile`:
```ruby
gem 'faye-websocket'
gem 'thin'
```

Create a `config/initializers/thin_action_cable.rb`:
```ruby
Rails.application.config.action_cable.use_faye = true
Faye::WebSocket.load_adapter 'thin'
```
