### ISSUE TITLE
rake aborted , db:seed

### ISSUE THREAD

**Issue by pevargasg** [rails/rails#23725]
I'm trying to use rake db:seed and its not working I already did rake db:create , rake db:migrate but my rake db:seed doesn't work and it happens in all my ruby projects. the error that I'm getting is the following:

`rake aborted! No users in the system /home/booletmarket/Desktop/bmf/BoolaMarket/db/seeds.rb:50:in `' Tasks: TOP => db:seed`

NOTE I HAVE CRATED USERS IN MY DB EVEN SUPER USERS

```
TRACE IS THE FOLLOWING
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:abort_if_pending_migrations
rake aborted!
No users in the system
/home/booletmarket/Desktop/bmf/BoolaMarket/db/seeds.rb:50:in `<top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `block in load'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
/usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/engine.rb:543:in `load_seed'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.1.4/lib/active_record/tasks/database_tasks.rb:184:in `load_seed'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.1.4/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:seed
```
this is the seed file, and actually it only happens in this project. the other ones work fine.

```
Category.create([{ name: 'Electronics'},
                 { name: 'Furniture'},
                 { name: 'Textbooks'},
                 { name: 'Clothing'},
                 { name: 'Athletics'},
                 { name: 'Fun' },
                 { name: 'Office & Home Supplies'},
                 { name: 'Novelty'},
                 { name: 'Bikes & Related'},
                 { name: 'Housing'},
                 { name: 'Tickets'},
                 { name: 'Miscellaneous'}
                 ])
Group.create([{ name: 'All'},
              { name: 'Yale College'},
              { name: 'School of Architecture'},
              { name: 'School of Art'},
              { name: 'Divinity School'},
              { name: 'School of Drama' },
              { name: 'School of Engineering and Applied Science'},
              { name: 'School of Public Health'},
              { name: 'School of Forestry and Environmental Science'},
              { name: 'School of Nursing'},
              { name: 'School of Music'},
              { name: 'School of Management'},
              { name: 'School of Medicine'},
              { name: 'Law School'},
              { name: 'Graduate School of Arts and Sciences'}
              ])
ALL_GROUP_ID = 1
User.all.each { |u| u.add_group Group.find(ALL_GROUP_ID) }

# put in a bunch of items
NUMBER_OF_ITEMS_TO_SEED = 30
NUMBER_OF_PICTURES_PER_ITEM = 3


default_seller = User.first
all_categories = Category.all.to_a
sample_pictures = Dir['db/seedpictures/*']
raise 'No users in the system' if default_seller.nil?
raise 'No categories in the system' if all_categories.empty?

NUMBER_OF_ITEMS_TO_SEED.times do
  #fake some parameters
  item = Product.new(
    title: Faker::Commerce.product_name,
    description: Faker::Hacker.say_something_smart,
    price: Faker::Commerce.price.to_f,
    location: Faker::Address.street_address,
    sell_by: Faker::Time.forward(30, :all)
  )

  puts "faking #{item.title}"

  #handle images
  picture_group = ProductPictureGroup.new
  item.product_picture_group = picture_group
  item.product_picture_group.save
  NUMBER_OF_PICTURES_PER_ITEM.times do
    item.product_picture_group.product_pictures.create(
      picture: File.open(sample_pictures.sample))
  end
  item.product_picture_group.primary_picture = item.product_picture_group
                                                   .product_pictures.first
  item.product_picture_group.save

  #set seller, category, and finish
  item.seller = default_seller
  item.category = all_categories.sample
  item.save
end
```

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by pevargasg** [comment]
I'm new in rails, how do I do an executable test? @maclover7

**Comment by maclover7** [comment]
If you don't know how to use the test scripts that's fine -- can you create a bare-bones application that reproduces the error you are seeing, and then can you post it here?

**Comment by rafaelfranca** [comment]
This is due to your code in db/seed.rb. It is not an Rails issue. See the line 50 of that file. It raise an exception if there are no users in the database.

**Comment by devdebonair** [comment]
@rafaelfranca  Thanks for Replying rafael. but how can I add user to my database. can you be more explicit please? thanks!

**Comment by pevargasg** [comment]
Thanks for Replying rafael. but how can I add user to my database. can you be more explicit please? thanks!

**Comment by pevargasg** [comment]
@rafaelfranca Thanks for Replying rafael. but how can I add user to my database. can you be more explicit please? thanks!

**Comment by rafaelfranca** [comment]
This is something that is specific to your application, not a rails bug so
I can't help you, sorry
