### ISSUE TITLE
NameError(uninitialized constant ApplicationCable::Connection::User)

### ISSUE THREAD

**Issue by john-999** [rails/rails#23814]
The suggested authorization solution at https://github.com/rails/rails/tree/master/actioncable#a-full-stack-example yields:

```
Started GET "/cable/" [WebSocket] for ::1 at 2016-02-22 23:27:52 +0100
There was an exception - NameError(uninitialized constant ApplicationCable::Connection::User)
/home/tomtom/Websites/chat/app/channels/application_cable/connection.rb:15:in `find_verified_user'
/home/tomtom/Websites/chat/app/channels/application_cable/connection.rb:8:in `connect'
/home/tomtom/.rvm/gems/ruby-2.3.0@rails500beta/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/base.rb:155:in `handle_open'
[...]
```

**Comment by dorianmariefr** [comment]
I have the same error in a sidekiq process, using redis (not async)

**Comment by dorianmariefr** [comment]
```
require "action_cable"
```

did the trick
