### ISSUE TITLE
Breakage finding templates

### ISSUE THREAD

**Issue by bronson** [rails/rails#23881]
This looks related to @chancancode's https://github.com/rails/rails/pull/23827.

On Rails master I'm now getting:

```
  1) PdfController generate blocks when told to
     Failure/Error: get :generate, params: { dest: 'search/print.pdf', nostatus: true }
     
     NoMethodError:
       undefined method `compact' for :any:Symbol
     # /Users/bronson/rails/actionview/lib/action_view/template/resolver.rb:249:in `block in build_query'
     # /Users/bronson/rails/actionview/lib/action_view/template/resolver.rb:248:in `each'
     # /Users/bronson/rails/actionview/lib/action_view/template/resolver.rb:248:in `build_query'
     # /Users/bronson/rails/actionview/lib/action_view/template/resolver.rb:202:in `query'
     # /Users/bronson/rails/actionview/lib/action_view/template/resolver.rb:198:in `find_templates'
     # /Users/bronson/rails/actionview/lib/action_view/template/resolver.rb:125:in `block in find_all'
     # /Users/bronson/rails/actionview/lib/action_view/template/resolver.rb:165:in `block in cached'
     # /Users/bronson/rails/actionview/lib/action_view/template/resolver.rb:61:in `cache'
     # /Users/bronson/rails/actionview/lib/action_view/template/resolver.rb:164:in `cached'
     # /Users/bronson/rails/actionview/lib/action_view/template/resolver.rb:124:in `find_all'
     # /Users/bronson/rails/actionview/lib/action_view/path_set.rb:79:in `block (2 levels) in _find_all'
     # /Users/bronson/rails/actionview/lib/action_view/path_set.rb:75:in `each'
     # /Users/bronson/rails/actionview/lib/action_view/path_set.rb:75:in `block in _find_all'
     # /Users/bronson/rails/actionview/lib/action_view/path_set.rb:74:in `each'
     # /Users/bronson/rails/actionview/lib/action_view/path_set.rb:74:in `_find_all'
     # /Users/bronson/rails/actionview/lib/action_view/path_set.rb:54:in `find_all'
     # /Users/bronson/rails/actionview/lib/action_view/path_set.rb:58:in `exists?'
     # /Users/bronson/rails/actionview/lib/action_view/lookup_context.rb:140:in `any?'
     # /Users/bronson/rails/actionview/lib/action_view/view_paths.rb:13:in `any_templates?'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/implicit_render.rb:39:in `default_render'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
     # /Users/bronson/rails/actionpack/lib/abstract_controller/base.rb:183:in `process_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/rendering.rb:30:in `process_action'
     # /Users/bronson/rails/actionpack/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:126:in `call'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:126:in `call'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:455:in `call'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:455:in `call'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:90:in `run_callbacks'
     # /Users/bronson/rails/actionpack/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/rescue.rb:27:in `process_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
     # /Users/bronson/rails/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/bronson/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /Users/bronson/rails/activesupport/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
     # /Users/bronson/rails/activerecord/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /Users/bronson/rails/actionpack/lib/abstract_controller/base.rb:128:in `process'
     # /Users/bronson/rails/actionview/lib/action_view/rendering.rb:30:in `process'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal.rb:190:in `dispatch'
     # /Users/bronson/rails/actionpack/lib/action_controller/test_case.rb:531:in `process'
     # /Users/bronson/rails/actionpack/lib/action_controller/test_case.rb:624:in `process_with_kwargs'
     # /Users/bronson/rails/actionpack/lib/action_controller/test_case.rb:381:in `get'
     # ./spec/controllers/pdf_controller_spec.rb:32:in `block (3 levels) in <top (required)>'
     # /Users/bronson/rails/activesupport/lib/active_support/dependencies.rb:296:in `load'
     # /Users/bronson/rails/activesupport/lib/active_support/dependencies.rb:296:in `block in load'
     # /Users/bronson/rails/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
     # /Users/bronson/rails/activesupport/lib/active_support/dependencies.rb:296:in `load'
     # /Users/bronson/.gem/ruby/2.2.2/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # -e:1:in `<main>'
```

Here are the variables:

```
Catchpoint at /Users/bronson/rails/actionview/lib/action_view/template/resolver.rb:251: `undefined method `compact' for :any:Symbol'

[246, 255] in /Users/bronson/rails/actionview/lib/action_view/template/resolver.rb
   246:       partial = escape_entry(path.partial? ? "_#{path.name}" : path.name)
   247:       query.gsub!(/:action/, partial)
   248: 
   249:         require 'byebug'; byebug
   250:       details.each do |ext, variants|
=> 251:         query.gsub!(/:#{ext}/, "{#{variants.compact.uniq.join(',')}}")
   252:       end
   253: 
   254:       File.expand_path(query, @path)
   255:     end
(byebug) details
{:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip], :variants=>:any, :handlers=>[:raw, :erb, :html, :builder, :ruby, :haml]}
(byebug) ext
:variants
(byebug) variants
:any
```

Here's the test that causes the problem:

```ruby
    it 'blocks when told to' do
      expect_any_instance_of(Kernel).to receive(:sleep).twice.with(1)
      expect_any_instance_of(PdfGenerator).to receive(:generate).and_return(false, false, true)
      get :generate, params: { dest: 'search/print.pdf', nostatus: true }
    end
```

I tried doing the simplest, most obvious fix:

```patch
diff --git a/actionview/lib/action_view/lookup_context.rb b/actionview/lib/action_view/lookup_context.rb
index 626c4b8..60fa65f 100644
--- a/actionview/lib/action_view/lookup_context.rb
+++ b/actionview/lib/action_view/lookup_context.rb
@@ -189,7 +189,7 @@ module ActionView
 
           registered_details.each do |k|
             if k == :variants
-              details[k] = :any
+              details[k] = [:any]
             else
               details[k] = Accessors::DEFAULT_PROCS[k].call
             end
```

and now it dies with this:

```
     Failure/Error: get :generate, params: { dest: 'search/print.pdf', nostatus: true }
     
     ActionController::UnknownFormat:
       PdfController#generate does not know how to respond to this request. There are other templates available for this controller action but none of them were suitable for this request.
     
       This usually happens when the client requested an unsupported format (e.g. requesting HTML content from a JSON endpoint or vice versa), but it might also be failing due to other constraints, such as locales orvariants.
     
       Requested format(s): application/pdf
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/implicit_render.rb:56:in `default_render'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
     # /Users/bronson/rails/actionpack/lib/abstract_controller/base.rb:183:in `process_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/rendering.rb:30:in `process_action'
     # /Users/bronson/rails/actionpack/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:126:in `call'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:126:in `call'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:455:in `call'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:455:in `call'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:90:in `run_callbacks'
     # /Users/bronson/rails/actionpack/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/rescue.rb:27:in `process_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
     # /Users/bronson/rails/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/bronson/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /Users/bronson/rails/activesupport/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
     # /Users/bronson/rails/activerecord/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /Users/bronson/rails/actionpack/lib/abstract_controller/base.rb:128:in `process'
     # /Users/bronson/rails/actionview/lib/action_view/rendering.rb:30:in `process'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal.rb:190:in `dispatch'
     # /Users/bronson/rails/actionpack/lib/action_controller/test_case.rb:531:in `process'
     # /Users/bronson/rails/actionpack/lib/action_controller/test_case.rb:624:in `process_with_kwargs'
     # /Users/bronson/rails/actionpack/lib/action_controller/test_case.rb:381:in `get'
     # ./spec/controllers/pdf_controller_spec.rb:32:in `block (3 levels) in <top (required)>'
     # /Users/bronson/rails/activesupport/lib/active_support/dependencies.rb:296:in `load'
     # /Users/bronson/rails/activesupport/lib/active_support/dependencies.rb:296:in `block in load'
     # /Users/bronson/rails/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
     # /Users/bronson/rails/activesupport/lib/active_support/dependencies.rb:296:in `load'
     # /Users/bronson/.gem/ruby/2.2.2/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # -e:1:in `<main>'
```

Tell me if there's anything else I should look at.

**Comment by maclover7** [comment]
Thanks for the bug report!

r? @chancancode

**Comment by chancancode** [comment]
Oops! So the resolvers used to get `details = { formats: [...], locale: [...], variant: [...], handlers: [...] }` which searches for templates that matches those constraints (think `WHERE formats IN (...) AND locale IN (...) AND ...` in terms of SQL). We made them now handle `{ formats: [...], locale: [...], variant: :any, handlers: [...] }` as well to do an unconstrained search on variants. We [updated one of the resolver implementation](https://github.com/rails/rails/blob/master/actionview/lib/action_view/template/resolver.rb#L343-L344) to handle this but of course there are other implementations too, specifically https://github.com/rails/rails/blob/master/actionview/lib/action_view/template/resolver.rb#L343 needs updating also.

I think we basically need to do the same thing there – if `ext` is `:variant` and `variants` is `:any` (confusingly the `variants` variable here has nothing to do with `:variant`... it just means the `[...]` or `:any` we were called with – probably should rename it to avoid confusion) we need to do `"*"` instead of the gsub string.

I don't know why the tests are using a different resolver, but there must be a reason that code is there and this is probably why. Should figure that out so we know how to add a test for it.

If you or anyone else wants to take a first stab at it I believe it will be quite easy (the hard part is figuring out how to test it), otherwise I'll try to get to it soon.

**Comment by chancancode** [comment]
d150f59 should fix your application, do you mind testing master again and reopen this issue if you found anything else?

**Comment by bronson** [comment]
Thanks @chancancode.  Looks like that fixed the first issue but not the second...  On 2ef8a0e2b:

```
  1) PdfController generate blocks when told to
     Failure/Error: get :generate, params: { dest: 'search/print.pdf', nostatus: true }
     
     ActionController::UnknownFormat:
       PdfController#generate does not know how to respond to this request. There are other templates available for this controller action but none of them were suitable for this request.
     
       This usually happens when the client requested an unsupported format (e.g. requesting HTML content from a JSON endpoint or vice versa), but it might also be failing due to other constraints, such as locales or variants.
     
       Requested format(s): application/pdf
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/implicit_render.rb:56:in `default_render'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
     # /Users/bronson/rails/actionpack/lib/abstract_controller/base.rb:183:in `process_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/rendering.rb:30:in `process_action'
     # /Users/bronson/rails/actionpack/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:126:in `call'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:126:in `call'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:455:in `call'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:455:in `call'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
     # /Users/bronson/rails/activesupport/lib/active_support/callbacks.rb:90:in `run_callbacks'
     # /Users/bronson/rails/actionpack/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/rescue.rb:27:in `process_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
     # /Users/bronson/rails/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/bronson/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /Users/bronson/rails/activesupport/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
     # /Users/bronson/rails/activerecord/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /Users/bronson/rails/actionpack/lib/abstract_controller/base.rb:128:in `process'
     # /Users/bronson/rails/actionview/lib/action_view/rendering.rb:30:in `process'
     # /Users/bronson/rails/actionpack/lib/action_controller/metal.rb:190:in `dispatch'
     # /Users/bronson/rails/actionpack/lib/action_controller/test_case.rb:531:in `process'
     # /Users/bronson/rails/actionpack/lib/action_controller/test_case.rb:624:in `process_with_kwargs'
     # /Users/bronson/rails/actionpack/lib/action_controller/test_case.rb:381:in `get'
     # ./spec/controllers/pdf_controller_spec.rb:31:in `block (3 levels) in <top (required)>'
```

The get (as mentioned above) is performed with `get :generate, params: { dest: 'search/print.pdf', nostatus: true }`

Looks like I can't reopen this issue... should I open a new one?

**Comment by bronson** [comment]
I take it back.  This might be a case where I was accidentally lazy with content types but Rails let it slide... until now.

I'll comment again if there's something amiss.  For now I'm guessing the problem is in my tests.

**Comment by bronson** [comment]
Figured out the problem, it was with my test.  Your patch looks great.

Boring explanation: my action ends by sending a file:

    return send_file(generator.path, disposition: 'inline')

Which I mocked:

      expect_any_instance_of(PdfGenerator).to receive(:generate).and_return(false, false, true)
      expect(controller).to receive(:send_file).once
      get :generate, params: { dest: 'search/print.pdf', nostatus: true }

For whatever reason, Rails 5.0.0.beta1 accepts that just fine, but Rails master tries to render a template.  

I converted the mock to:

      expect(controller).to receive(:send_file).once { controller.render :nothing => true }

to make it explicit that send_file is equivalent to a render and now everything works perfectly.

Sorry for the noise, thanks for fixing this!
