### ISSUE TITLE
Why default log_level for production mode is :debug?

### ISSUE THREAD

**Issue by begin29** [rails/rails#23903]
### Steps to reproduce
Hi guys! I found interesting issue that default log level for production is `debug`.  Please look to production.rb file for new generated app.
### Expected behavior
command 
```
rails c -e production
``` 
doesn't show anything that should be related to `:debug`. 

### Actual behavior
It behaves like with log_level `:error`

### System configuration
**Rails version**:
4.2.5.1
**Ruby version**:
2.1.2

**Comment by rafaelfranca** [comment]
Yes, the default log level for production is debug. If you don't want it you can  set to a different level. See the release notes that you will find mention to that.

**Comment by begin29** [comment]
If we leave it on `debug` it steel behaves like I've used `error` log_level. Why?
It happens when I execute `rails s -e production`

**Comment by rafaelfranca** [comment]
I don't get it. How can I reproduce this behavior. Are you checking the content of `log/production.log`?

**Comment by begin29** [comment]
create new app `rails new some_foo`. 

look to environments/production.rb and find line with log_level. You will see that it is set to `:debug`. 

Start app in production `rails s -e production` and look on logs. It behaves like with settings 
log_level: `error`. 

And I have a question why it is behaves on that way?

**Comment by rafaelfranca** [comment]
Could you explain what is behaves like with setting log_level: `error`?

Also where are you looking for these logs?

**Comment by begin29** [comment]
It showed only error logs. and nothing else. It doesn't show requests, rendering, as it should be for `debug` logs.
I've looked on log/production.log

**Comment by rafaelfranca** [comment]
I just tried yours reprodution steps and I can see this in my production.log:

```
I, [2016-02-26T20:05:16.827077 #87922]  INFO -- : Started GET "/articles" for ::1 at 2016-02-26 20:05:16 -0300
I, [2016-02-26T20:05:16.827858 #87922]  INFO -- : Processing by ArticlesController#index as HTML
D, [2016-02-26T20:05:16.829111 #87922] DEBUG -- :   Article Load (0.1ms)  SELECT "articles".* FROM "articles"
I, [2016-02-26T20:05:16.829402 #87922]  INFO -- :   Rendered articles/index.html.erb within layouts/application (0.6ms)
I, [2016-02-26T20:05:16.830395 #87922]  INFO -- : Completed 200 OK in 2ms (Views: 1.8ms | ActiveRecord: 0.1ms)
I, [2016-02-26T20:05:16.980161 #87922]  INFO -- : Started GET "/stylesheets/application.css" for ::1 at 2016-02-26 20:05:16 -0300
F, [2016-02-26T20:05:16.981208 #87922] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/rafaelfranca/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/rafaelfranca/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/rafaelfranca/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


I, [2016-02-26T20:05:16.984068 #87922]  INFO -- : Started GET "/javascripts/application.js" for ::1 at 2016-02-26 20:05:16 -0300
F, [2016-02-26T20:05:16.984950 #87922] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/rafaelfranca/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/rafaelfranca/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/rafaelfranca/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

So INFO, DEBUG, and FATAL logs are being added to that file. Exactly what happens in the debug level.

Are you not getting that?

**Comment by begin29** [comment]
Oh, yeah. I rechecked it and found that file is updated, but when you run `rails s -e production` I see empty output.

**Comment by rafaelfranca** [comment]
empty output in the terminal? it is expected. Rails doesn't log to stdout by default in production.

**Comment by rafaelfranca** [comment]
empty output in the terminal? it is expected. Rails doesn't log to stdout by default in production.
