### ISSUE TITLE
`require': cannot load such file -- active_support/testing/method_call_assertions (LoadError)

### ISSUE THREAD

**Issue by yahonda** [rails/rails#24008]
### Steps to reproduce
$ cd activerecord
$ bundle ; rake test

### Expected behavior
ActiveRecord unit tests for sqlit3, mysql2 and postgresql adapters should run.

### Actual behavior
```ruby

/home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_support/testing/method_call_assertions (LoadError)
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/yahonda/git/rails/activerecord/test/cases/helper.rb:4:in `<top (required)>'
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/yahonda/git/rails/activerecord/test/cases/relations_test.rb:1:in `<top (required)>'
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
```

### System configuration
**Rails version**:
master branch
**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

Based on git bisect #23932 triggers this error.

**Comment by rafaelfranca** [comment]
Does `bundle exec rake test` work?

**Comment by yahonda** [comment]
> Does bundle exec rake test work?'

Yes. Thanks for the advice.

Also I have checked https://github.com/rails/rails/blob/master/activerecord/RUNNING_UNIT_TESTS.rdoc and found some of steps also get this error, Workarounds are same.

```ruby
$ ARCONN=postgresql ruby -Itest test/cases/base_test.rb
/home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_support/testing/method_call_assertions (LoadError)
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/yahonda/git/rails/activerecord/test/cases/helper.rb:4:in `<top (required)>'
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from test/cases/base_test.rb:1:in `<main>'
```

It works by adding `bundle exec`.

```
$ ARCONN=postgresql bundle exec ruby -Itest test/cases/base_test.rb
Using postgresql
Run options: --seed 40068

# Running:

...................................................................................................................................................

Finished in 1.822090s, 80.6766 runs/s, 201.4171 assertions/s.

147 runs, 367 assertions, 0 failures, 0 errors, 0 skips
```


```ruby
$ ruby -Itest test/cases/base_test.rb
/home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_support/testing/method_call_assertions (LoadError)
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/yahonda/git/rails/activerecord/test/cases/helper.rb:4:in `<top (required)>'
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from test/cases/base_test.rb:1:in `<main>'
```

It works by adding `bundle exec`.

```ruby
$ bundle exec ruby -Itest test/cases/base_test.rb
Using sqlite3
Run options: --seed 6419

# Running:

..............................................................................S.....................................................................

Finished in 1.323593s, 111.8169 runs/s, 274.2536 assertions/s.

148 runs, 363 assertions, 0 failures, 0 errors, 1 skips

You have skipped tests. Run with --verbose for details.
$
```

I'm going to open a pull request to modify this document to use `bundle exec`.

**Comment by rafaelfranca** [comment]
Thank you for confirming.
