### ISSUE TITLE
Fresh Rails 3.2.22.2 engine raises Exception when running rails console

### ISSUE THREAD

**Issue by dyba** [rails/rails#24073]
### Steps to reproduce

* ```rails plugin new myengine --mountable```
* ```cd myengine/test/dummy```
* ``` bundle exec rails console```

### Expected behavior

* I should get a console session

### Actual behavior

```
/Users/ddyba/Code/rails/activesupport/lib/active_support/dependencies.rb:251:in `require': Please add test-unit gem to your Gemfile: `gem 'test-unit', '~> 3.0'` (cannot load such file -- test/unit/testcase) (LoadError)
        from /Users/ddyba/Code/rails/activesupport/lib/active_support/dependencies.rb:251:in `block in require'
        from /Users/ddyba/Code/rails/activesupport/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Users/ddyba/Code/rails/activesupport/lib/active_support/dependencies.rb:251:in `require'
        from /Users/ddyba/Code/rails/activesupport/lib/active_support/test_case.rb:2:in `<top (required)>'
        from /Users/ddyba/Code/rails/activesupport/lib/active_support/dependencies.rb:251:in `require'
        from /Users/ddyba/Code/rails/activesupport/lib/active_support/dependencies.rb:251:in `block in require'
        from /Users/ddyba/Code/rails/activesupport/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Users/ddyba/Code/rails/activesupport/lib/active_support/dependencies.rb:251:in `require'
        from /Users/ddyba/Code/rails/railties/lib/rails/console/app.rb:2:in `<top (required)>'
        from /Users/ddyba/Code/rails/activesupport/lib/active_support/dependencies.rb:251:in `require'
        from /Users/ddyba/Code/rails/activesupport/lib/active_support/dependencies.rb:251:in `block in require'
        from /Users/ddyba/Code/rails/activesupport/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Users/ddyba/Code/rails/activesupport/lib/active_support/dependencies.rb:251:in `require'
        from /Users/ddyba/Code/rails/railties/lib/rails/application.rb:312:in `initialize_console'
        from /Users/ddyba/Code/rails/railties/lib/rails/application.rb:152:in `load_console'
        from /Users/ddyba/Code/rails/railties/lib/rails/commands/console.rb:27:in `start'
        from /Users/ddyba/Code/rails/railties/lib/rails/commands/console.rb:8:in `start'
        from /Users/ddyba/Code/rails/railties/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

The exception is raised [here](https://github.com/dyba/rails/blob/v3.2.22.2/activesupport/lib/active_support/test_case.rb#L4). Can you explain the rationale for expecting the user to require the ```test-unit``` gem themselves?

### System configuration
**Rails version**: 3.2.22.2

**Ruby version**: 2.3.0p0 (rev 53290)

**Comment by matthewd** [comment]
Rails 3.2 is no longer supported.
