### ISSUE TITLE
ActiveRecord-4.2.6 argument out of range in 'utc' in mysql2_adapter

### ISSUE THREAD

**Issue by Dariusch** [rails/rails#24107]
Hey guys,

I just tried to upgrade my rails-app from rails 4.2.5.2 to 4.2.6 and got a new error while running my tests. Since I could not find a reported error here is my backtrace.

```
Failure/Error: - if @inbounds.blank?

ActionView::Template::Error:
  argument out of range
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:236:in `utc'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:236:in `each'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:236:in `to_a'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:236:in `exec_query'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:144:in `block in method_missing'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:131:in `with'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:143:in `method_missing'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:401:in `limited_ids_for'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:387:in `apply_join_dependency'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:370:in `construct_relation_for_association_calculations'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:125:in `calculate'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:42:in `count'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/relation.rb:268:in `empty?'
# ./app/views/sourcing/inbounds/index.html.haml:63:in `_app_views_sourcing_inbounds_index_html_haml__3180773629415134476_76437340'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/template.rb:145:in `block in render'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/template.rb:333:in `instrument'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/template.rb:143:in `render'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:14:in `render'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/renderer/renderer.rb:46:in `render_template'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/renderer/renderer.rb:27:in `render'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/rendering.rb:100:in `_render_template'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/streaming.rb:217:in `_render_template'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/rendering.rb:83:in `render_to_body'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/abstract_controller/rendering.rb:25:in `render'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:16:in `render'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/core_ext/benchmark.rb:12:in `ms'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:43:in `render'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/remotipart-1.2.1/lib/remotipart/render_overrides.rb:14:in `render_with_remotipart'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:198:in `process_action'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in `process'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal.rb:196:in `dispatch'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_controller/metal.rb:237:in `block in action'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:43:in `serve'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `each'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb:260:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/query_cache.rb:36:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/airbrake-5.1.0/lib/airbrake/rack/middleware.rb:22:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/request_store-1.3.0/lib/request_store/middleware.rb:9:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/capybara-2.6.2/lib/capybara/rack_test/browser.rb:60:in `process'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/capybara-2.6.2/lib/capybara/rack_test/browser.rb:35:in `process_and_follow_redirects'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/capybara-2.6.2/lib/capybara/rack_test/browser.rb:21:in `visit'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/capybara-2.6.2/lib/capybara/rack_test/driver.rb:42:in `visit'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/capybara-2.6.2/lib/capybara/session.rb:232:in `visit'
# /home/dariusch/.rvm/gems/ruby-2.2.3/gems/capybara-2.6.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
# ./spec/features/sourcing/inbounds_controller_spec.rb:23:in `block (3 levels) in <top (required)>'
# ------------------
# --- Caused by: ---
# ArgumentError:
#   argument out of range
#   /home/dariusch/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:236:in `utc'
```
### System configuration

**Rails version**: 4.2.6
**Ruby version**: 2.2.3
**mysql2 gem version**: mysql2 (0.3.20)

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by al2o3cr** [comment]
@Dariusch I believe I've seen a similar error in the wild - in the case I'm thinking of, it was the result of the Mysql2 adapter attempting to deserialize an invalid date (something like `2004-00-07`). Ideally you'd fix the data at the source, but if you can't avoid running with it one workaround is to add `cast: false` to your `config/database.yml`. This may have performance implications (I haven't checked) but it beats "the application crashes when loading a record" behavior...

**Comment by bvogel** [comment]
For the record: the same error still prevails in 4.2.7 (and we still haven't found the time to create the sample app). However there is an indication that the error may be in relation with a `TIMEDIFF`-Sql-Function and [wice_grid](https://github.com/leikind/wice_grid).

**Comment by Dariusch** [comment]
As mentioned before `TIMEDIFF` with wice_grid was the Issue.
