### ISSUE TITLE
Setting `from("some_string")` fails when eagerly loading an association

### ISSUE THREAD

**Issue by zmoazeni** [rails/rails#24193]
### Steps to reproduce

Assume a codebase with the following simple data model:

```ruby
ActiveRecord::Schema.define(version: 20160314184305) do

  create_table "comments", force: :cascade do |t|
    t.text     "body"
    t.integer  "post_id"
    t.integer  "author_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "comments", ["author_id"], name: "index_comments_on_author_id"
  add_index "comments", ["post_id"], name: "index_comments_on_post_id"

  create_table "posts", force: :cascade do |t|
    t.string   "title"
    t.text     "body"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end

class Post < ActiveRecord::Base
  has_many :comments
end


class Comment < ActiveRecord::Base
  belongs_to :post
end
```

For larger applications, we sometimes need to give the database query planner hints as to what indexes to use. For example https://github.com/mirakui/activerecord-mysql-index-hint

That boils down to overriding the `from()` in the query:

```ruby
# sqlite3 example https://sqlite.org/lang_indexedby.html
Comment.from("comments INDEXED BY index_comments_on_post_id").count

# mysql example http://dev.mysql.com/doc/refman/5.7/en/index-hints.html
Comment.from("comments FORCE INDEX(index_comments_on_post_id)").count
```

That works swell for the most part until you bring in `eager_load(:model)` which fails inside rails. (Also happens with `includes(:model).where(model: { ... })` to force Rails to execute a single query instead of multiple).

### Expected behavior

It should query and return the results as expected.

### Actual behavior

```
Comment.from("comments INDEXED BY index_comments_on_post_id").eager_load(:post).count
NoMethodError: undefined method `map' for "comments INDEXED BY index_comments_on_post_id":Arel::Nodes::SqlLiteral
Did you mean?  tap
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/alias_tracker.rb:29:in `initial_count_for'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/alias_tracker.rb:19:in `block in create'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/alias_tracker.rb:60:in `aliased_table_for'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/join_dependency.rb:97:in `initialize'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:364:in `new'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:364:in `construct_join_dependency'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:375:in `construct_relation_for_association_calculations'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:125:in `calculate'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:42:in `count'
        from (irb):13
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**: 4.2.6 (but it affects 4.1.x too)

**Ruby version**: 2.3.0 (and earlier versions as well)

### Additional Notes

From what I can tell it's a problem with https://github.com/rails/rails/blob/4232f7ee427a510eb07e420f5883611bcb0abfae/activerecord/lib/active_record/relation/finder_methods.rb#L405-L407 that always assumes `from()` is an Arel::Table.

I tried exploring Arel::Table to see if I could include the SQL hint with that instead, but that fails for a different reason (quoting):

```
irb(main):001:0> temp_arel_table = Comment.arel_table.dup
=> #<Arel::Table:0x007f88632d48d8 @name="comments", @engine=Comment (call 'Comment.connection' to establish a connection), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>
irb(main):002:0> temp_arel_table.name = "comments INDEXED BY index_comments_on_post_id"
=> "comments INDEXED BY index_comments_on_post_id"
irb(main):003:0> Comment.from(temp_arel_table).eager_load(:post).count
   (0.2ms)  SELECT COUNT(DISTINCT "comments"."id") FROM "comments INDEXED BY index_comments_on_post_id" LEFT OUTER JOIN "posts" ON "posts"."id" = "comments"."post_id"
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: comments INDEXED BY index_comments_on_post_id: SELECT COUNT(DISTINCT "comments"."id") FROM "comments INDEXED BY index_comments_on_post_id" LEFT OUTER JOIN "posts" ON "posts"."id" = "comments"."post_id"
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `new'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `prepare'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/sqlite3_adapter.rb:296:in `block in exec_query'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/sqlite3_adapter.rb:293:in `exec_query'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:264:in `execute_simple_calculation'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:221:in `perform_calculation'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:127:in `calculate'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:125:in `calculate'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:42:in `count'
        from (irb):3
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by zmoazeni** [comment]
I changed the title of the description because it's not isolated to SQL hints. Setting `from()` with any string will result in the same error:

```
Comment.from("comments").eager_load(:post).count
NoMethodError: undefined method `map' for "comments":Arel::Nodes::SqlLiteral
Did you mean?  tap
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/alias_tracker.rb:29:in `initial_count_for'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/alias_tracker.rb:19:in `block in create'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/alias_tracker.rb:60:in `aliased_table_for'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/join_dependency.rb:97:in `initialize'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:364:in `new'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:364:in `construct_join_dependency'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:375:in `construct_relation_for_association_calculations'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:125:in `calculate'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:42:in `count'
        from (irb):1
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/zmoazeni/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by kamipo** [comment]
Workaround:

```ruby
irb(main):001:0> Comment.from([Arel.sql("comments")]).eager_load(:post).count
   (0.6ms)  SELECT COUNT(DISTINCT `comments`.`id`) FROM comments LEFT OUTER JOIN `posts` ON `posts`.`id` = `comments`.`post_id`
=> 98
```

**Comment by fangzhu19880123** [comment]
it will raise exception like this
`
2.1.0 :019 > Promotion::PromotionItem.from([Arel.sql('promotion_promotion_items')]).eager_load(:promotion).count
NoMethodError: undefined method `left' for "promotion_promotion_items":Arel::Nodes::SqlLiteral
        from /home/fz/.rvm/gems/ruby-2.1.0@pomelo_backend/gems/activerecord-3.2.13/lib/active_record/associations/alias_tracker.rb:64:in `block in initial_count_for'
`
