### ISSUE TITLE
Getting ActiveRecord::StatementInvalid error on TravisCI for Rails 5 project

### ISSUE THREAD

**Issue by jasnow** [rails/rails#24288]
### Steps to reproduce
 * Clone the repo and checkout "rails5" branch.
 * Set up TravisCI.
 * Change something small, such as add blank line to README.
 * Push to GitHub and watch TravisCI.

### Expected behavior
Expected not to get ActiveRecord::StatementInvalid error.
This behavior did not occur on the master (Rails 4.2.6) branch.

### Actual behavior
I have been working on upgrading our local Ruby Users Group web
site from Rails 4.2 to Rails 5 in repo's "rails5" branch and
it fails TravisCI run (works fine locally) with this error message:
```
ActiveRecord::StatementInvalid: SQLite3::SQLException: near
",": syntax error: INSERT INTO "schema_migrations" (version)
VALUES ('20120321020431'), ('20120321184254')
```
 * Code is at: https://github.com/atlrug/atlrug4/tree/rails5
 * Last TravisCI build: https://travis-ci.org/atlrug/atlrug4/builds/117959091

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**: 2.3.0
Thanks

**Comment by kaspth** [comment]
Personally, I don't think we give support to custom Travis setups when you can just submit a pull request and have our setup run. Thanks!

**Comment by jasnow** [comment]
Thanks - For History: Removed "rake" and used "rspec" and "cucumber" in .travis.yml to get to green.

**Comment by kaspth** [comment]
Doh, I'd totally misunderstood it as you trying to setup Travis for Rails the gem and not your library. Anyway, glad you got it working :smile:

**Comment by duffyjp** [comment]
I'm getting this too actually, on pretty simple, month old Rails 5 beta3 app.

Rails version: 5.0.0.beta3
Ruby version: 2.3.0

```
ruby/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize': SQLite3::SQLException: near ",": syntax error: INSERT INTO "schema_migrations" (version) VALUES ('20160308192904'), ('20160314170113') (ActiveRecord::StatementInvalid)
```

I'm using SQLite for both my development and test databases, so I'm not sure why the schema would not load...

**Comment by jasnow** [comment]
@duffyjp - Did this happen inside or outside TravisCI?

**Comment by duffyjp** [comment]
Quite a few results come up if you google ```"syntax error" INSERT INTO "schema_migrations"```

They're all Rails 5 beta3 and SQLite 1.3.11

Examples:
https://travis-ci.org/railsbridge/bridge_troll/builds/106673747#L841
https://travis-ci.org/projectblacklight/blacklight/jobs/111764929#L787
https://travis-ci.org/thiagopradi/octopus/jobs/114336625#L1125-L1126

**Comment by duffyjp** [comment]
@jasnow Only inside TravisCI.

**Comment by jasnow** [comment]
Thanks

**Comment by yahonda** [comment]
Although I do not know which SQLIte version (not sqlite3 gem version ) is using, it looks like `SQLite Release 3.7.11` or higher version necessary to insert multiple values in one statement. 
http://www.sqlite.org/releaselog/3_7_11.html

> Enhance the INSERT syntax to allow multiple rows to be inserted via the VALUES clause.

**Comment by yahonda** [comment]
https://github.com/travis-ci/apt-package-whitelist/issues/368 by updating travis.yml we may be able to use newer version of SQLite 3 database when tested in Travis CI. Let me open a pull request.

**Comment by jasnow** [comment]
Add the below code to fix above problem in my .travis.yml file:
```
        addons:
          apt:
            sources:
              - travis-ci/sqlite3
            packages:
              - sqlite3
```
It worked: https://travis-ci.org/atlrug/atlrug4/builds/121010500

**Comment by duffyjp** [comment]
@jasnow You're my hero.  That worked for me too!

Here's my full .travis.yml, if it helps anyone.

```
language: ruby
cache: bundler
before_install:
  - gem update bundler

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
```

I guess the real question is shouldn't Active Record and/or the sqlite3 gem know about the limitations of SQLite at specific versions and build SQL accordingly?

**Comment by alagos** [comment]
I'm getting the same error but in circle ci:

```
- initialize_schema_migrations_table()
   -> 0.0060s
rake aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: near ",": syntax error: INSERT INTO "schema_migrations" (version) VALUES ('20160323195409'), ('20160325195759'), ('20160325210415'), ('20160325210616'), ('20160327212439'), ('20160327213746'), ('20160328004542'), ('20160328004646'), ('20160328005334'), ('20160331213618'), ('20160405135350'), ('20160405135353'), ('20160419210118'), ('20160419214022'), ('20160419214550'), ('20160419214735'), ('20160422141558'), ('20160505193936')
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `new'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `prepare'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:134:in `execute'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/connection_adapters/sqlite3_adapter.rb:266:in `block in execute'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/connection_adapters/abstract_adapter.rb:527:in `block in log'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/connection_adapters/abstract_adapter.rb:521:in `log'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/connection_adapters/sqlite3_adapter.rb:266:in `execute'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/connection_adapters/abstract/schema_statements.rb:1006:in `assume_migrated_upto_version'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/schema.rb:52:in `define'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/schema.rb:44:in `define'
/home/ubuntu/members/db/schema.rb:14:in `<top (required)>'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:296:in `load'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:296:in `block in load'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:268:in `load_dependency'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:296:in `load'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/tasks/database_tasks.rb:220:in `load_schema'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/tasks/database_tasks.rb:250:in `block in load_schema_current'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/tasks/database_tasks.rb:290:in `block in each_current_configuration'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/tasks/database_tasks.rb:289:in `each'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/tasks/database_tasks.rb:289:in `each_current_configuration'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/tasks/database_tasks.rb:249:in `load_schema_current'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.beta3/lib/active_record/railties/databases.rake:260:in `block (3 levels) in <top (required)>'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `call'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `block in execute'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `each'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block in top_level'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:78:in `block in run'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/bin/rake:22:in `load'
/home/ubuntu/members/vendor/bundle/ruby/2.2.0/bin/rake:22:in `<main>'
```

**Comment by vipulnsward** [comment]
@alagos this has been fixed with new release https://github.com/rails/rails/pull/24685

**Comment by Premanandh-S** [comment]
Just run the following command 
rake db:schema:load
