### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::IndeterminateDatatype in Rails 5 Upgrade

### ISSUE THREAD

**Issue by sgringwe** [rails/rails#24341]
### Steps to reproduce

Query records which joins on a belongs_to polymorphic definition which joins back to the has many record

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))
### Expected behavior

Tell us what should happen

The query should work and not error.
### Actual behavior

Tell us what happens instead

The query errors with "ActiveRecord::StatementInvalid: PG::IndeterminateDatatype"
### System configuration

**Rails version**: 5.0.0.beta3

**Ruby version**: 2.3.0

Replication:

```
class Application < ActiveRecord::Base
  belongs_to :user
  belongs_to :applicable, polymorphic: true
  belongs_to :interview_schedule, -> { where(applications: { applicable_type: InterviewSchedule.name }) }, foreign_key: 'applicable_id'
end

class User < ActiveRecord::Base
  has_many :applications, dependent: :destroy
  has_many :interview_schedule_applications, -> { joins(:applications).where(applicable_type: InterviewSchedule.name) }, class_name: Application.name
end

# Fails:
User.students.first.interview_schedule_applications.where(status: %w(primary alternate)).joins(:interview_schedule)
D, [2016-03-27T17:36:32.549928 #2963] DEBUG -- :   User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."user_type" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["user_type", "Students"], ["LIMIT", 1]]
D, [2016-03-27T17:36:32.905258 #2963] DEBUG -- :   Application Load (0.7ms)  SELECT "applications".* FROM "applications" INNER JOIN "interview_schedules" ON "interview_schedules"."id" = "applications"."applicable_id" AND "applications"."applicable_type" = $1 WHERE "applications"."user_id" = $2 AND "applications"."applicable_type" = $3 AND "applications"."status" IN ('primary', 'alternate')  [["applicable_type", "InterviewSchedule"], ["applicable_type", "InterviewSchedule"], ["user_id", 30], ["applicable_type", "InterviewSchedule"]]
(pry) output error: #<ActiveRecord::StatementInvalid: PG::IndeterminateDatatype: ERROR:  could not determine data type of parameter $4
: SELECT "applications".* FROM "applications" INNER JOIN "interview_schedules" ON "interview_schedules"."id" = "applications"."applicable_id" AND "applications"."applicable_type" = $1 WHERE "applications"."user_id" = $2 AND "applications"."applicable_type" = $3 AND "applications"."status" IN ('primary', 'alternate')

# Change one line in User class (remove the joins(:applications)
has_many :interview_schedule_applications, -> {where(applicable_type: InterviewSchedule.name) }, class_name: Application.name

# Works:
[27] pry(main)> User.first.interview_schedule_applications.where(status: %w(primary alternate)).joins(:interview_schedule)
D, [2016-03-27T17:37:49.661019 #2963] DEBUG -- :   User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."user_type" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["user_type", "Students"], ["LIMIT", 1]]
D, [2016-03-27T17:37:50.035653 #2963] DEBUG -- :   Application Load (0.5ms)  SELECT "applications".* FROM "applications" INNER JOIN "interview_schedules" ON "interview_schedules"."id" = "applications"."applicable_id" AND "applications"."applicable_type" = $1 WHERE "applications"."user_id" = $2 AND "applications"."applicable_type" = $3 AND "applications"."status" IN ('primary', 'alternate')  [["applicable_type", "InterviewSchedule"], ["user_id", 30], ["applicable_type", "InterviewSchedule"]]
[]
[28] pry(main)
```

Note that without the `.joins(:interview_schedule)` on the problem query, all works fine.

**Comment by vsorlov** [comment]
I've created a script with that scenario and it doesn't seem to be failing
https://gist.github.com/vsorlov/c619d9b6c4cc06947eab4125782fd9f8

either the problem is not in rails 5.0.0.beta3 or you missed something in replication steps

**Comment by rafaelfranca** [comment]
@sgringwe could you try to chenge @vsorlov's gist to reproduce your issue?

**Comment by sgringwe** [comment]
@rafaelfranca This exhibits one of the errors I have been seeing during our rails 4.2 -> 5.0.1 transition:

```begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '5.0.1'
  gem 'pg'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'test', username: 'postgres')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :documents, force: true do |t|
    t.integer :user_id
  end

  create_table :applications_documents, id: false, force: :true do |t|
    t.integer "application_id", null: false
    t.integer "document_id",    null: false
  end

  create_table :applications, force: true do |t|
    t.integer :user_id
    t.integer :applicable_id
    t.string :applicable_type
    t.integer :interview_schedule_id
    t.string :status
    t.boolean :withdrawn
  end

  create_table :interview_schedules, force: true do |t|
    t.integer :employer_id
  end

  create_table :users, force: true do |t|
    t.string :user_type
    t.integer :institution_id
    t.string :institution_type
  end
end

class InterviewSchedule < ActiveRecord::Base
  has_many :applications, as: :applicable, dependent: :destroy
end

class Application < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :documents
  belongs_to :applicable, polymorphic: true
  # NOTE: If the 'joins(:applications)' is removed, it does work. However, this was allowed in 4.2.
  belongs_to :interview_schedule, -> { joins(:applications).where("applications.applicable_type = ?", InterviewSchedule.name) }, foreign_key: 'applicable_id'
  scope :active, -> { where(withdrawn: false) }

  scope :jobs, -> { includes(:job).where(applicable_type: Job.name) }
  scope :interview_schedules, -> { includes(:interview_schedule).where(applicable_type: InterviewSchedule.name) }
end

class Document < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :applications
end

class User < ActiveRecord::Base
  has_many :applications, dependent: :destroy
  has_many :interview_schedule_applications, -> { joins(:applications).where(applicable_type: InterviewSchedule.name)  }, class_name: Application.name

  scope :students, -> { where user_type: 'student' }
end

class BugTest < Minitest::Test
  def test_association_stuff
    user = User.create! user_type: 'student', institution_id: 1
    document = Document.create! user: user
    application = Application.create! status: 'primary', applicable_type: InterviewSchedule.name, user: user
    document.applications << application

    document.reload

    puts document.applications.active.interview_schedules.where(interview_schedules: { employer_id: user.institution_id }).exists?
  end
end
```

This code will produce this error:

```
ActiveRecord::StatementInvalid: PG::IndeterminateDatatype: ERROR:  could not determine data type of parameter $6
: SELECT  1 AS one FROM "applications" LEFT OUTER JOIN "interview_schedules" ON "interview_schedules"."id" = "applications"."applicable_id" AND (applications.applicable_type = 'InterviewSchedule') INNER JOIN "applications_documents" ON "applications"."id" = "applications_documents"."application_id" WHERE "applications_documents"."document_id" = $1 AND "applications"."withdrawn" = $2 AND "applications"."applicable_type" = $3 AND "interview_schedules"."employer_id" = $4 LIMIT $5
    /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'
    /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
    /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
    /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
    /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
    /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:587:in `execute_and_clear'
    /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:13:in `select_value'
    /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-5.0.1/lib/active_record/relation/finder_methods.rb:335:in `exists?'
    bug.rb:89:in `test_association_stuff'
```

**Comment by vovimayhem** [comment]
I'm just seeing a similar problem (same error class) when creating a record with a `belongs_to` association... working on a reproduction script...

**Comment by XanderPSON** [comment]
I'm getting the same issue here. It appears the problem is that PG is expecting there to be an extra $1 variable when there isn't one. I can't just remove the .joins() function from our scope because then other tests break and it changes behavior. Anyone have any idea? This may be a bug in R5.
