### ISSUE TITLE
bundle exec rake test_mysql2 causes Mysql2::Error: SAVEPOINT active_record_1 does not exist: ROLLBACK TO SAVEPOINT active_record_1

### ISSUE THREAD

**Issue by yahonda** [rails/rails#24391]
### Steps to reproduce
```
$ cd activerecord
$ bundle exec rake test_mysql2
```

### Minimum steps to reproduce
```
$ cd activerecord
$ ARCONN=mysql2 bundle exec ruby -W -w -I"lib:test" \
  "/home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.1/lib/rake/rake_test_loader.rb" \
  "test/cases/ar_schema_test.rb" \
  "test/cases/tasks/database_tasks_test.rb"
```

### Expected behavior
Unit tests finished without errors

### Actual behavior
Tell us what happens instead
```ruby
  1) Error:
ActiveRecord::DatabaseTasksMigrateTest#test_migrate_clears_schema_cache_afterward:
ActiveRecord::StatementInvalid: Mysql2::Error: SAVEPOINT active_record_1 does not exist: ROLLBACK TO SAVEPOINT active_record_1
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `_query'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `block in query'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `handle_interrupt'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:235:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:526:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:520:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:235:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:128:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/savepoints.rb:13:in `exec_rollback_to_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:292:in `rollback_to_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `rollback_to_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:114:in `rollback'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:183:in `rollback_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:204:in `rescue in within_new_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:201:in `within_new_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:211:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    /home/yahonda/git/rails/activerecord/lib/active_record/persistence.rb:277:in `update!'
    /home/yahonda/git/rails/activerecord/lib/active_record/internal_metadata.rb:22:in `[]='
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1198:in `record_environment'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1192:in `migrate_without_lock'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1137:in `block in migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1304:in `with_advisory_lock'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1137:in `migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1011:in `up'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:989:in `migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/tasks/database_tasks.rb:159:in `migrate'
    /home/yahonda/git/rails/activerecord/test/cases/tasks/database_tasks_test.rb:334:in `test_migrate_clears_schema_cache_afterward'

4826 runs, 13403 assertions, 0 failures, 1 errors, 5 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
```
### System configuration
**Rails version**:
master branch including https://github.com/rails/rails/commit/133befb59b8389cb483fd4194acdcddc5e288ab4

**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

debug.log shows that it is trying to rollback to the savepoint which has been already released.

```ruby
   (0.1ms)  SAVEPOINT active_record_1
   (0.3ms)  RELEASE SAVEPOINT active_record_1
   (0.2ms)  ROLLBACK TO SAVEPOINT active_record_1
```

**Comment by vipulnsward** [comment]
Looks like we are facing https://github.com/vipulnsward/rails/blob/933e11f8311e13c8d5e4355813ebcdbb50037ffc/activerecord/lib/active_record/transactions.rb#L190-L207

I can see this after running the test in isolation.

**Comment by yahonda** [comment]
Thanks for the update. I understand MySQL automatically commits transactions and release all savepoints when DDL statement executed.

but in this case I think all of savepoint statements below are explicitly executed from `ActiveRecord::ConnectionAdapters::Savepoints`.

```sql
   (0.1ms)  SAVEPOINT active_record_1
   (0.3ms)  RELEASE SAVEPOINT active_record_1
   (0.2ms)  ROLLBACK TO SAVEPOINT active_record_1
```

Then when `ROLLBACK TO SAVEPOINT` executed, it gets this error since `active_record_1` savepoint has been released by `RELEASE SAVEPOINT` statement.

```ruby
ActiveRecord::StatementInvalid: Mysql2::Error: SAVEPOINT active_record_1 does not exist: ROLLBACK TO SAVEPOINT active_record_1
```

When I execute this test alone, no `ROLLBACK TO SAVEPOINT active_record_1` statement executed, then this test works successfully.

```ruby
$ ARCONN=mysql2 bundle exec ruby -Itest test/cases/tasks/database_tasks_test.rb -n test_migrate_clears_schema_cache_afterward
```

```ruby
   (0.3ms)  RELEASE SAVEPOINT active_record_1
   (0.2ms)  ROLLBACK TO SAVEPOINT active_record_1
```

Will keep investigating.

**Comment by vipulnsward** [comment]
Yes, I tried to investigate too. Thanks for the update.

**Comment by vipulnsward** [comment]
hmm, now I am not able to reproduce this when using MariaDB.

**Comment by yahonda** [comment]
Thanks for the update. I also tried MariaDB (first time!).  Still it reproduces.

```sql
$ mysql -uroot
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 217
Server version: 5.5.47-MariaDB MariaDB Server

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> Bye
```

```ruby
$ ARCONN=mysql2 bundle exec ruby -W -w -I"lib:test" \
>   "/home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.1/lib/rake/rake_test_loader.rb" \
>   "test/cases/ar_schema_test.rb" \
>   "test/cases/tasks/database_tasks_test.rb"
Using mysql2
Run options: --seed 14486

# Running:

......................................E......................

Finished in 0.296943s, 205.4263 runs/s, 242.4704 assertions/s.

  1) Error:
ActiveRecord::DatabaseTasksMigrateTest#test_migrate_clears_schema_cache_afterward:
ActiveRecord::StatementInvalid: Mysql2::Error: SAVEPOINT active_record_1 does not exist: ROLLBACK TO SAVEPOINT active_record_1
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `_query'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `block in query'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `handle_interrupt'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:201:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:547:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:541:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:201:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:136:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/savepoints.rb:13:in `exec_rollback_to_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:293:in `rollback_to_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `rollback_to_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:114:in `rollback'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:183:in `rollback_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:204:in `rescue in within_new_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:201:in `within_new_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:234:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:211:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    /home/yahonda/git/rails/activerecord/lib/active_record/persistence.rb:277:in `update!'
    /home/yahonda/git/rails/activerecord/lib/active_record/internal_metadata.rb:22:in `[]='
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1198:in `record_environment'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1192:in `migrate_without_lock'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1137:in `block in migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1304:in `with_advisory_lock'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1137:in `migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1011:in `up'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:989:in `migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
    /home/yahonda/git/rails/activerecord/test/cases/tasks/database_tasks_test.rb:341:in `test_migrate_clears_schema_cache_afterward'

61 runs, 72 assertions, 0 failures, 1 errors, 0 skips
$
```

**Comment by yahonda** [comment]
Also reproduces with MariaDB 10.1.13. Installed to `CentOS Linux release 7.2.1511 (Core)` by following this step https://mariadb.com/kb/en/mariadb/yum/
```sql
$ mysql -uroot
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 206
Server version: 10.1.13-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> Bye
```

```ruby
$ ARCONN=mysql2 bundle exec ruby -W -w -I"lib:test" \
>   "/home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.1/lib/rake/rake_test_loader.rb" \
>   "test/cases/ar_schema_test.rb" \
>   "test/cases/tasks/database_tasks_test.rb"
Using mysql2
Run options: --seed 62494

# Running:

......................................E......................

Finished in 0.342955s, 177.8659 runs/s, 209.9401 assertions/s.

  1) Error:
ActiveRecord::DatabaseTasksMigrateTest#test_migrate_clears_schema_cache_afterward:
ActiveRecord::StatementInvalid: Mysql2::Error: SAVEPOINT active_record_1 does not exist: ROLLBACK TO SAVEPOINT active_record_1
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `_query'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `block in query'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `handle_interrupt'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:201:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:547:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:541:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:201:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:136:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/savepoints.rb:13:in `exec_rollback_to_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:293:in `rollback_to_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `rollback_to_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:114:in `rollback'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:183:in `rollback_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:204:in `rescue in within_new_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:201:in `within_new_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:234:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:211:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    /home/yahonda/git/rails/activerecord/lib/active_record/persistence.rb:277:in `update!'
    /home/yahonda/git/rails/activerecord/lib/active_record/internal_metadata.rb:22:in `[]='
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1198:in `record_environment'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1192:in `migrate_without_lock'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1137:in `block in migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1304:in `with_advisory_lock'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1137:in `migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1011:in `up'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:989:in `migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
    /home/yahonda/git/rails/activerecord/test/cases/tasks/database_tasks_test.rb:341:in `test_migrate_clears_schema_cache_afterward'

61 runs, 72 assertions, 0 failures, 1 errors, 0 skips
$
```

**Comment by vipulnsward** [comment]
Ok, we are facing this(ref: http://dev.mysql.com/doc/refman/5.7/en/savepoint.html): 

```
It might be useful to know that if you want to use savepoints, you have to start a transaction before defining your first savepoint. Setting a savepoint does not automatically start a transaction. There is no error when defining a savepoint when not in a transaction, but you get a "savepoint does not exist" when you then try to release it or do a rollback to it.
```

Sometimes when we succeed, we have a transaction open, here's an example result from:
```
> SELECT * FROM information_schema.innodb_trx
["2224202", "RUNNING", 2016-04-21 20:26:28 UTC, nil, nil, 0, 422, "SELECT * FROM information_schema.innodb_trx", nil, 0, 0, 0, 360, 0, 0, 0, "REPEATABLE READ", 1, 1, nil, 0, 10000, 0, 0]
```
In case of failures it's empty, meaning we don't have running transaction. And the thread seems to be sleeping.

```
MySQL thread id 463, OS thread handle 0x700000cc9000, query id 73536 localhost rails cleaning up
```

What astonishes me is, we do have BEGIN transactions:
```
  (0.1ms)  BEGIN
   (0.1ms)  BEGIN
   (7.2ms)  CREATE TABLE `schema_migrations` (`version` varchar(255) PRIMARY KEY) ENGINE=InnoDB
   (0.1ms)  SELECT DATABASE() as db
   (0.2ms)  SELECT GET_LOCK('2582488309082152590', 0);
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
  ActiveRecord::InternalMetadata Load (0.3ms)  SELECT  `ar_internal_metadata`.* FROM `ar_internal_metadata` ORDER BY `ar_internal_metadata`.`key` ASC LIMIT 1
   (0.3ms)  show engine innodb status
   (0.2ms)  SELECT * FROM information_schema.innodb_trx
   (0.1ms)  SAVEPOINT active_record_1
   (0.3ms)  RELEASE SAVEPOINT active_record_1
   (0.2ms)  SELECT RELEASE_LOCK('2582488309082152590')
```
So not sure, where transactions are missing.

This might be of interest to @arthurnn . 

Ofcourse easy way out to fix this is:
```ruby
     def commit
        connection.release_savepoint(savepoint_name)
      ensure
        super
      end
```
to ensure, we update state on TransactionState object.

P.S: Sorry for the long read 😁

**Comment by yahonda** [comment]
Thanks for the detailed information. I am trying to understand everything. 

So far I understand it can workaround by starting transactions explicitly or implement `ensure` in `commit` method.

I had tried 2nd one as suggested. https://github.com/yahonda/rails/commit/a3d4eacf76144d033546052bec89c38d2a012dfb

Now it gets `RELEASE SAVEPOINT active_record_1` got error, not `ROLLBACK TO SAVEPOINT active_record_1` before this commit. 

```sql
$ mysql -uroot
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1142
Server version: 5.7.12 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

```ruby
$ ARCONN=mysql2 bundle exec ruby -W -w -I"lib:test"   "/home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.1/lib/rake/rake_test_loader.rb"   "test/cases/ar_schema_test.rb"   "test/cases/tasks/database_tasks_test.rb"
Using mysql2
Run options: --seed 25450

# Running:

......................................E......................

Finished in 0.538845s, 113.2052 runs/s, 133.6192 assertions/s.

  1) Error:
ActiveRecord::DatabaseTasksMigrateTest#test_migrate_clears_schema_cache_afterward:
ActiveRecord::StatementInvalid: Mysql2::Error: SAVEPOINT active_record_1 does not exist: RELEASE SAVEPOINT active_record_1
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `_query'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `block in query'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `handle_interrupt'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:201:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:547:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:541:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:201:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:136:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/savepoints.rb:17:in `release_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:120:in `commit'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:179:in `commit_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:204:in `within_new_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:234:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:211:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    /home/yahonda/git/rails/activerecord/lib/active_record/persistence.rb:277:in `update!'
    /home/yahonda/git/rails/activerecord/lib/active_record/internal_metadata.rb:22:in `[]='
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1198:in `record_environment'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1192:in `migrate_without_lock'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1137:in `block in migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1304:in `with_advisory_lock'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1137:in `migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1011:in `up'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:989:in `migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
    /home/yahonda/git/rails/activerecord/test/cases/tasks/database_tasks_test.rb:341:in `test_migrate_clears_schema_cache_afterward'

61 runs, 72 assertions, 0 failures, 1 errors, 0 skips
$
```
