### ISSUE TITLE
uninitialized constant ActiveModel::Serializers::Xml in MongoMapper

### ISSUE THREAD

**Issue by dropsrobs** [rails/rails#24558]
After switch to rails 5.0.0.beta.3 receiving following error:

```
/home/robert/.rvm/gems/ruby-2.2.3/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/active_model.rb:9:in `<module:ActiveModel>': uninitialized constant ActiveModel::Serializers::Xml (NameError)
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/active_model.rb:4:in `<module:Plugins>'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/active_model.rb:3:in `<module:MongoMapper>'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/active_model.rb:2:in `<top (required)>'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/mongo_mapper-0.13.1/lib/mongo_mapper/document.rb:7:in `<module:Document>'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/mongo_mapper-0.13.1/lib/mongo_mapper/document.rb:3:in `<module:MongoMapper>'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/mongo_mapper-0.13.1/lib/mongo_mapper/document.rb:2:in `<top (required)>'
	from /home/robert/Documents/Softiti/anyapi/app/models/user_management/user.rb:3:in `<class:User>'
	from /home/robert/Documents/Softiti/anyapi/app/models/user_management/user.rb:2:in `<module:UserManagement>'
	from /home/robert/Documents/Softiti/anyapi/app/models/user_management/user.rb:1:in `<top (required)>'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/activesupport/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/activesupport/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/activesupport/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /home/robert/Documents/Softiti/anyapi/spec/factories/models/user_management/user/sessions.rb:2:in `block in <top (required)>'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:49:in `run'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:7:in `define'
	from /home/robert/Documents/Softiti/anyapi/spec/factories/models/user_management/user/sessions.rb:1:in `<top (required)>'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:20:in `block (2 levels) in find_definitions'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:19:in `each'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:19:in `block in find_definitions'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:15:in `each'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/factory_girl_rails-4.7.0/lib/factory_girl_rails/railtie.rb:21:in `block in <class:Railtie>'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/activesupport/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/activesupport/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/activesupport/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/activesupport/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/activesupport/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/initializable.rb:30:in `run'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/robert/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/robert/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/robert/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/robert/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/robert/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/robert/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/robert/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/robert/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/robert/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/application.rb:352:in `initialize!'
	from /home/robert/Documents/Softiti/anyapi/config/environment.rb:5:in `<top (required)>'
	from /home/robert/Documents/Softiti/anyapi/config.ru:3:in `block in <main>'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `instance_eval'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `initialize'
	from /home/robert/Documents/Softiti/anyapi/config.ru:in `new'
	from /home/robert/Documents/Softiti/anyapi/config.ru:in `<main>'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `eval'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `new_from_string'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/rack-2.0.0.alpha/lib/rack/builder.rb:40:in `parse_file'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/rack-2.0.0.alpha/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/rack-2.0.0.alpha/lib/rack/server.rb:218:in `app'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/commands/server.rb:59:in `app'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/rack-2.0.0.alpha/lib/rack/server.rb:353:in `wrapped_app'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/commands/server.rb:77:in `start'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/robert/.rvm/gems/ruby-2.2.3/bundler/gems/rails-a2de667b2eb9/railties/lib/rails/commands.rb:18:in `<top (required)>'
	from /home/robert/Documents/Softiti/anyapi/bin/rails:8:in `require'
	from /home/robert/Documents/Softiti/anyapi/bin/rails:8:in `<top (required)>'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `load'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `call'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/spring-1.7.1/lib/spring/client.rb:30:in `run'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `load'
	from /home/robert/.rvm/gems/ruby-2.2.3/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from /home/robert/Documents/Softiti/anyapi/bin/spring:13:in `require'
	from /home/robert/Documents/Softiti/anyapi/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'


```

So I found out that `activemodel-serializers-xml` were moved to external gem. But even including this gem in Gemfile does not resolve problem.

Possibly referenced gems to this error: 

```
gem 'activemodel-serializers-xml', github: 'rails/activemodel-serializers-xml'
gem 'active_model_serializers'

gem 'mongo_mapper'
gem 'bson_ext'
gem 'mongo'

```

**Rails version**: 5.0.0.beta.3

**Ruby version**: 2.2.3

**Comment by prathamesh-sonpatki** [comment]
This is because it is removed from core in Rails 5. Please include gem https://github.com/rails/activemodel-serializers-xml to make it work.

**Comment by dropsrobs** [comment]
I have written that even including this gem does not resolve problem.

**Comment by prathamesh-sonpatki** [comment]
Oops :smile:

**Comment by prathamesh-sonpatki** [comment]
https://github.com/mongomapper/mongomapper/blob/master/lib/mongo_mapper/plugins/active_model.rb#L9 is causing the issue. Should this issue be moved to mongo_mapper issue tracker?

**Comment by vipulnsward** [comment]
This is related to https://github.com/rails/activemodel-serializers-xml/pull/8.

Lets move the discussion there.

**Comment by dropsrobs** [comment]
Ok, thanks for participating :)

**Comment by smtlaissezfaire** [comment]
Hi.  Mongo mapper maintainer here.  Just ran into this one.

So the real solution would be for MongoMapper to require 'activemodel-serializers-xml', correct?

Has the json library also been extracted?  MM has the following code:

```
      include ::ActiveModel::Serialization
      include ::ActiveModel::Serializers::Xml
      include ::ActiveModel::Serializers::JSON
```
