### ISSUE TITLE
ORA-01036 since Oracle does not allow `select for update` with `fetch first n rows only`

### ISSUE THREAD

**Issue by yahonda** [rails/rails#24779]
### Steps to reproduce
* Update Gemfile to support https://github.com/rails/arel/pull/422
```ruby
gem 'arel', github: 'yahonda/arel', branch: 'v700_oracle12'
```
* Execute this ActiveRecord unit test
```ruby
$ cd activerecord
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/locking_test.rb -n test_with_lock_commits_transaction
Using oracle
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb:7: warning: method redefined; discarding old aliased_types
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb:389: warning: previous definition of aliased_types was here
Run options: -n test_with_lock_commits_transaction --seed 40683

# Running:

E

Finished in 0.253326s, 3.9475 runs/s, 0.0000 assertions/s.

  1) Error:
PessimisticLockingTest#test_with_lock_commits_transaction:
ActiveRecord::StatementInvalid: OCIError: ORA-01036: illegal variable name/number: SELECT  "PEOPLE".* FROM "PEOPLE" WHERE "PEOPLE"."ID" = :a1  FOR UPDATE
    stmt.c:195:in oci8lib_230.so
    /home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ruby-oci8-2.2.2/lib/oci8/cursor.rb:100:in `bind_param'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:161:in `bind_param'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:126:in `block in bind_params'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:122:in `each'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:122:in `bind_params'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:34:in `block in exec_query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:548:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:542:in `log'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1191:in `log'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:22:in `exec_query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    /home/yahonda/git/rails/activerecord/lib/active_record/querying.rb:39:in `find_by_sql'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:699:in `exec_queries'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:580:in `load'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:260:in `records'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:525:in `find_take'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:100:in `take'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:475:in `find_one'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:456:in `find_with_ids'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:66:in `find'
    /home/yahonda/git/rails/activerecord/lib/active_record/persistence.rb:437:in `block in reload'
    /home/yahonda/git/rails/activerecord/lib/active_record/scoping/default.rb:35:in `block in unscoped'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:351:in `scoping'
    /home/yahonda/git/rails/activerecord/lib/active_record/scoping/default.rb:35:in `unscoped'
    /home/yahonda/git/rails/activerecord/lib/active_record/persistence.rb:437:in `reload'
    /home/yahonda/git/rails/activerecord/lib/active_record/attribute_methods/dirty.rb:37:in `reload'
    /home/yahonda/git/rails/activerecord/lib/active_record/associations.rb:253:in `reload'
    /home/yahonda/git/rails/activerecord/lib/active_record/autosave_association.rb:235:in `reload'
    /home/yahonda/git/rails/activerecord/lib/active_record/aggregations.rb:13:in `reload'
    /home/yahonda/git/rails/activerecord/lib/active_record/locking/pessimistic.rb:62:in `lock!'
    /home/yahonda/git/rails/activerecord/lib/active_record/locking/pessimistic.rb:71:in `block in with_lock'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:211:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:310:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/locking/pessimistic.rb:70:in `with_lock'
    test/cases/locking_test.rb:428:in `test_with_lock_commits_transaction'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

### Expected behavior
This unit test should finish successfully. 

### Actual behavior
Got an error as shown above.  This is due to it is trying to bind two bind values ` [["id", 1], ["LIMIT", 1]]` for one bind value `:a1`. 

- Oracle
```sql
SELECT  "PEOPLE".* FROM "PEOPLE" WHERE "PEOPLE"."ID" = :a1  FOR UPDATE  [["id", 1], ["LIMIT", 1]]
```

Oracle database itself does not allow `select for update` with `fetch first n rows only`
```sql
SQL> SELECT  "PEOPLE".* FROM "PEOPLE" WHERE "PEOPLE"."ID" = 1 FETCH FIRST 1 ROWS ONLY  FOR UPDATE
  2  ;
SELECT  "PEOPLE".* FROM "PEOPLE" WHERE "PEOPLE"."ID" = 1 FETCH FIRST 1 ROWS ONLY  FOR UPDATE
*
ERROR at line 1:
ORA-02014: cannot select FOR UPDATE from view with DISTINCT, GROUP BY, etc.
```

Then `Oracle12` visitor handles this by removing o.limit `if o.limit && o.lock` like this.

https://github.com/rails/arel/blob/master/lib/arel/visitors/oracle12.rb
```ruby
      def visit_Arel_Nodes_SelectStatement o, collector
        # Oracle does not allow LIMIT clause with select for update
        if o.limit && o.lock
          o = o.dup
          o.limit = []
        end

        super
      end
```
But ActiveRecord does not know this behavior, then it binds the bind value associate with `limit`.

For other databases such as PostgreSQL it works.

- PostgreSQL
```sql
SELECT  "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
```

- Oracle 11g or lower (using Oracle visitor)

```sql
SELECT  "PEOPLE".* FROM "PEOPLE" WHERE "PEOPLE"."ID" = :a1 AND ROWNUM <= :a2  FOR UPDATE  [["id", 1], ["LIMIT", 1]]
```

### Reference

Related with https://github.com/rails/rails/issues/24775

- [Support Oracle 12c top-N query](https://github.com/rails/arel/pull/337)
(https://github.com/rails/arel/pull/337/commits/0e1427e917a4e47dce9f02ad9309600073622c73) implements `Oracle12` visitor whose `visit_Arel_Nodes_SelectStatement`
it removes limit clause for select 

### System configuration
**Rails version**:
- Rails master branch
- Arel 7.0.0 + https://github.com/rails/arel/pull/422
- Oracle enhanced adapter rails5 branch
- Oracle database 12c 12.1.0.2

**Ruby version**:
```
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

**Comment by jeremy** [comment]
I think the bug is with #24775 silently dropping the limit. For one, it's not the query the user intends or expects, and for two, it's unaware of binds.

**Comment by sgrif** [comment]
Will fix this along with #24775 once I get to Kansas.

**Comment by yahonda** [comment]
Opened https://github.com/rails/arel/pull/430 which changes Oracle12 behavior to raise an ArgumentError when limit and lock are used.

```ruby
$ ARCONN=oracle bundle exec ruby -W -w -I"lib:test" test/cases/locking_test.rb -n test_with_lock_commits_transaction
Using oracle
... snip ...
# Running:

E

Finished in 0.411625s, 2.4294 runs/s, 0.0000 assertions/s.

  1) Error:
PessimisticLockingTest#test_with_lock_commits_transaction:
ArgumentError:             'Combination of limit and lock is not supported.
            because generated SQL statements
            `SELECT FOR UPDATE and FETCH FIRST n ROWS` generates ORA-02014.`

    /home/yahonda/git/arel/lib/arel/visitors/oracle12.rb:9:in `visit_Arel_Nodes_SelectStatement'
    /home/yahonda/git/arel/lib/arel/visitors/reduce.rb:13:in `visit'
    /home/yahonda/git/arel/lib/arel/visitors/reduce.rb:7:in `accept'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/determine_if_preparable_visitor.rb:8:in `accept'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:12:in `to_sql'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    /home/yahonda/git/rails/activerecord/lib/active_record/querying.rb:39:in `find_by_sql'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:699:in `exec_queries'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:580:in `load'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:260:in `records'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:525:in `find_take'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:100:in `take'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:475:in `find_one'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:456:in `find_with_ids'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:66:in `find'
    /home/yahonda/git/rails/activerecord/lib/active_record/persistence.rb:437:in `block in reload'
    /home/yahonda/git/rails/activerecord/lib/active_record/scoping/default.rb:35:in `block in unscoped'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:351:in `scoping'
    /home/yahonda/git/rails/activerecord/lib/active_record/scoping/default.rb:35:in `unscoped'
    /home/yahonda/git/rails/activerecord/lib/active_record/persistence.rb:437:in `reload'
    /home/yahonda/git/rails/activerecord/lib/active_record/attribute_methods/dirty.rb:37:in `reload'
    /home/yahonda/git/rails/activerecord/lib/active_record/associations.rb:253:in `reload'
    /home/yahonda/git/rails/activerecord/lib/active_record/autosave_association.rb:235:in `reload'
    /home/yahonda/git/rails/activerecord/lib/active_record/aggregations.rb:13:in `reload'
    /home/yahonda/git/rails/activerecord/lib/active_record/locking/pessimistic.rb:62:in `lock!'
    /home/yahonda/git/rails/activerecord/lib/active_record/locking/pessimistic.rb:71:in `block in with_lock'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:211:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:310:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/locking/pessimistic.rb:70:in `with_lock'
    test/cases/locking_test.rb:428:in `test_with_lock_commits_transaction'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```
Once https://github.com/rails/arel/pull/422 and https://github.com/rails/arel/pull/430 are merged to Arel, the original issue reported will not happen.

**Comment by sgrif** [comment]
This has been resolved in Arel.
