### ISSUE TITLE
has_many collection proxy's build does not create the correct STI class when the type argument is a Class object in Rails 5.0.0.beta4

### ISSUE THREAD

**Issue by pwnall** [rails/rails#24808]
This is a regression for 5.0.0.beta3. The test below fails on master and 5.0.0.beta4, and passes on 5.0.0.beta3.

### Test case

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails' #, tag: 'v5.0.0.beta3'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :mailboxes, force: true do |t|
  end

  create_table :posts, force: true  do |t|
    t.integer :mailbox_id
    t.string :type
    t.text :features
  end
end

class Mailbox < ActiveRecord::Base
  has_many :posts
end

class Post < ActiveRecord::Base
  belongs_to :mailbox
end

class RefinedPost < Post
  store :features, accessors: [:read_receipt]
end

class BugTest < Minitest::Test
  def test_sti_build_type
    mailbox = Mailbox.create!
    post = mailbox.posts.create! type: RefinedPost, read_receipt: true
    assert_equal true, post.read_receipt
  end
end
```

### System configuration
I ran the test in Ruby 2.2.4 and 2.3.0.

**Comment by pwnall** [comment]
I played around with the test a bit, and discovered that the test passes if the `type` argument is a `String` instead of the `Class` object. Concretely, the test below passes on 5.0.0.beta4 and edge.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :mailboxes, force: true do |t|
  end

  create_table :posts, force: true  do |t|
    t.integer :mailbox_id
    t.string :type
    t.text :features
  end
end

class Mailbox < ActiveRecord::Base
  has_many :posts
end

class Post < ActiveRecord::Base
  belongs_to :mailbox
end

class RefinedPost < Post
  store :features, accessors: [:read_receipt]
end

class BugTest < Minitest::Test
  def test_sti_build_type
    mailbox = Mailbox.create!
    post = mailbox.posts.create! type: 'RefinedPost', read_receipt: true
    assert_equal true, post.read_receipt
  end
end
```

**Comment by vipulnsward** [comment]
Ref: https://github.com/vipulnsward/rails/commit/3ea4476942d2ba5ddc0d3b2d1f3730455661b06a

**Comment by vipulnsward** [comment]
Can you post error trace on this? I am not able to reproduce this on master.

**Comment by pwnall** [comment]
```
  1) Error:
BugTest#test_sti_build_type:
ActiveModel::UnknownAttributeError: unknown attribute 'read_receipt' for Post.
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activemodel/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activemodel/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activemodel/lib/active_model/attribute_assignment.rb:39:in `each'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activemodel/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activemodel/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/core.rb:319:in `initialize'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/inheritance.rb:65:in `new'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/inheritance.rb:65:in `new'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/reflection.rb:152:in `build_association'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/associations/association.rb:253:in `build_record'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/associations/collection_association.rb:517:in `block in _create_record'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/associations/collection_association.rb:203:in `block in transaction'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/transactions.rb:211:in `transaction'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/associations/collection_association.rb:202:in `transaction'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/associations/collection_association.rb:516:in `_create_record'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/associations/has_many_association.rb:136:in `_create_record'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/associations/collection_association.rb:176:in `create!'
    /Users/pwnall/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-6bd3e867f97c/activerecord/lib/active_record/associations/collection_proxy.rb:341:in `create!'
    bug.rb:48:in `test_sti_build_type'
```

**Comment by vipulnsward** [comment]
Thanks, let me see.

**Comment by maclover7** [comment]
Ran a `git bisect`, this behavior is introduced by https://github.com/rails/rails/commit/78ea4c598547c46cdfcf71aa484782ac903a3040
