### ISSUE TITLE
can't require active_support/dependencies in beta 4

### ISSUE THREAD

**Issue by rosenfeld** [rails/rails#24818]
### Steps to reproduce

bundle exec ruby -ractive_support/dependencies -e ''

### Expected behavior
should not fail

### Actual behavior
raises an exception

### System configuration
**Rails version**: 5.0.0.beta4
**Ruby version**: 2.3.1

**Comment by derekprior** [comment]
> raises an exception

Specifically:

```
/Users/derek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/deprecation/proxy_wrappers.rb:124:in `initialize': undefined method `instance' for ActiveSupport::Deprecation:Class (NoMethodError)
Did you mean?  instance_of?
        from /Users/derek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/deprecation/proxy_wrappers.rb:10:in `new'
        from /Users/derek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/deprecation/proxy_wrappers.rb:10:in `new'
        from /Users/derek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/core_ext/load_error.rb:30:in `<top (required)>'
        from /Users/derek/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/derek/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/derek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/dependencies.rb:12:in `<top (required)>'
        from /Users/derek/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /Users/derek/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /Users/derek/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
```

**Comment by matthewd** [comment]
You need to require `active_support` first.

**Comment by rosenfeld** [comment]
@matthewd, someone told me once that this wasn't the case for activesupport. Did this change in version 5?

**Comment by rosenfeld** [comment]
Nevermind, I'm checking the edge guides, which confirms this is now by design: http://edgeguides.rubyonrails.org/active_support_core_extensions.html

**Comment by rafaelfranca** [comment]
It always had the case, but maybe it worked by luck before. To use any Rails framework the top level file needs to be required first. We use this pattern to define common requirements and not having to duplicate all requires in the top of each files.
