### ISSUE TITLE
ActionCable complains about class being removed from module tree

### ISSUE THREAD

**Issue by jeroenvisser101** [rails/rails#25118]
### Steps to reproduce
(cannot reproduce reliably)

### Expected behavior
ActionCable would work normally

### Actual behavior
```
Could not execute command from {"command"=>"subscribe", "identifier"=>"{\"channel\":\"TemplatesChannel\",\"id\":51}"}) [ArgumentError - A copy of TemplatesChannel has been removed from the module tree but is still active!]: 
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:496:in `load_missing_constant' | 
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:203:in `const_missing' | 
/Users/jeroenvisser/Projects/*redacted*/app/channels/templates_channel.rb:6:in `subscribed' | 
/usr/local/Cellar/rbenv/1.0.0/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.rc1/lib/action_cable/channel/base.rb:236:in `block in subscribe_to_channel' | 
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:126:in `call'
```

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.1

**Comment by onemanstartup** [comment]
@jeroenvisser101 "Beware that currently the cable server will not auto-reload any changes in the framework" this is in readme for action cable

**Comment by jeroenvisser101** [comment]
@onemanstartup thanks — I knew it was disabled, but I don't think that this error should be thrown when code changes, right? Now it throws up whenever I change code.

**Comment by matthewd** [comment]
I suspect that https://github.com/rails/rails/pull/25240 fixed this

**Comment by jeroenvisser101** [comment]
Thanks @matthewd, I'll see if I can confirm!
