### ISSUE TITLE
Backtrace silencing should happen even against a pure framework trace

### ISSUE THREAD

**Issue by dhh** [rails/rails#25219]
When an exception is raised where the backtrace doesn't include user code, we default to showing the whole thing. That results in stuff like this:

```
irb(main):011:0> eit
NameError: undefined local variable or method `eit' for main:Object
Did you mean?  exit
	from (irb):11
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/console.rb:65:in `start'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/david/Code/demos/blog/bin/rails:9:in `<top (required)>'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/commands/rails.rb:6:in `call'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:191:in `block in serve'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:161:in `fork'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:161:in `serve'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

That's not a reasonable response to something so simple. I'd like to see:

```
irb(main):011:0> eit
NameError: undefined local variable or method `eit' for main:Object
Did you mean?  exit
[Backtrace silenced by Rails. Tweak config/initializers/backtrace_silencer.rb if needed]
```

**Comment by vipulnsward** [comment]
Will take care of this since I was looking to close https://github.com/rails/rails/issues/24434
r? @vipulnsward

**Comment by matthewd** [comment]
Per #3970, if there's truly zero lines of user/application code in the backtrace, the chances are very high one of those lines is at fault (so it makes sense to show them, because whoever needs to diagnose the problem is clearly going to need that information).

Perhaps the problem here is just that we don't recognize `(irb)` as being user code.

---

It might also be worth looking into what IRB does internally with backtraces: that output has a conspicuous lack of `lib/irb`-type stuff. Perhaps we can convince it to always truncate the console backtrace before `console.rb:65:in start`? We clearly know nothing *that* high up is to blame, even when the exception really is our fault.

**Comment by vipulnsward** [comment]
@matthewd if I am not mistaken you are referring to handling this better on just irb, or perhaps differently there? 
We still don't want to show this in web requests as well though.

**Comment by vipulnsward** [comment]
With new changes this would like this-

```log
ActionController::RoutingError (No route matches [GET] "/userssss"):

[Backtrace silenced by Rails. Tweak config/initializers/backtrace_silencer.rb if needed]
  Rendering /Users/sward/work/rails/actionpack/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
  Rendering /Users/sward/work/rails/actionpack/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /Users/sward/work/rails/actionpack/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (0.9ms)
  Rendered collection of /Users/sward/work/rails/actionpack/lib/action_dispatch/middleware/templates/routes/_route.html.erb [8 times] (3.3ms)
  Rendered /Users/sward/work/rails/actionpack/lib/action_dispatch/middleware/templates/routes/_table.html.erb (7.9ms)
```

**Comment by dhh** [comment]
That's an improvement, but would be great to get rid of the internal
rendering lines as well. They're not helpful here.

**Comment by vipulnsward** [comment]
cool

**Comment by matthewd** [comment]
@vipulnsward yes: I think this is two separate issues, and there are some babies in this bathwater.

**Comment by matthewd** [comment]
@vipulnsward further to the "two separate issues".. how does your PR, which changes a rack middleware, help with the behaviour described in this issue? :confused:

**Comment by vipulnsward** [comment]
> @vipulnsward further to the "two separate issues".. how does your PR, which changes a rack middleware, help with the behaviour described in this issue? 😕

@matthewd it removes the behaviour that we are ourselves adding the extra trace? By default the trace would be cleaned and silenced.
