### ISSUE TITLE
activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- sawyer (LoadError)

### ISSUE THREAD

**Issue by blshkv** [rails/rails#25336]
The original issue was reported at https://github.com/pentoo/pentoo-overlay/issues/100

I've uninstalled gentoo packages and run bundle install, but it didn't help:
```
/home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- sawyer (LoadError)
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/ruby/gems/2.1.0/gems/octokit-4.3.0/lib/octokit/connection.rb:1:in `<top (required)>'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/ruby/gems/2.1.0/gems/octokit-4.3.0/lib/octokit/client.rb:1:in `<top (required)>'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/ruby/gems/2.1.0/gems/octokit-4.3.0/lib/octokit.rb:1:in `<top (required)>'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.12/lib/msf/util/document_generator/pull_request_finder.rb:1:in `<top (required)>'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.12/lib/msf/util/document_generator.rb:7:in `<top (required)>'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.12/lib/msf/ui/console/command_dispatcher/core.rb:19:in `<top (required)>'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.12/lib/msf/ui/console/command_dispatcher.rb:86:in `<top (required)>'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.12/lib/msf/ui/console/driver.rb:6:in `<top (required)>'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.12/lib/msf/ui/console.rb:11:in `<top (required)>'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.12/lib/msf/ui.rb:11:in `<top (required)>'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/user1/.gem/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.12/lib/metasploit/framework/command/console.rb:60:in `driver'
        from /usr/lib64/metasploit4.12/lib/metasploit/framework/command/console.rb:48:in `start'
        from /usr/lib64/metasploit4.12/lib/metasploit/framework/command/base.rb:82:in `start'
        from /usr/lib/metasploit/msfconsole:48:in `<main>'
```
### System configuration
**Rails version**:
**Ruby version**:
dev-lang/ruby-2.0.0_p648
dev-lang/ruby-2.1.10

**Comment by tachyons** [comment]
Seems like issue is with [octokit](https://github.com/octokit/octokit.rb) , swayer is a dependency of octokit

**Comment by blshkv** [comment]
Thank you for the hint. I found a problem with octokit, but it is a gentoo bug, reported here:
https://bugs.gentoo.org/show_bug.cgi?id=585518
