### ISSUE TITLE
Error while trying to run a migration "wrong number of arguments (given 2, expected 0..1)"

### ISSUE THREAD

**Issue by pedrozath** [rails/rails#25440]
### Steps to reproduce
Tried to run this migration.

```
class CreatePosts < ActiveRecord::Migration[5.0]
  def change
    create_table :posts do |t|
      t.string :title
      t.text :body
      t.integer :photo_id

      t.timestamps
    end
  end
end

```
### Expected behavior
To create the table

### Actual behavior

Console outputs this:

```
macpedro:ciadascapas pedrozath$ rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
default_options has been deprecated, use options
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block (2 levels) in <top (required)> at /sites/ciadascapas/config/environments/development.rb:52)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
   (0.2ms)  SELECT pg_try_advisory_lock(4844576453229231180);
  ActiveRecord::SchemaMigration Load (0.6ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Migrating to CreatePosts (20160619124924)
   (0.1ms)  BEGIN
== 20160619124924 CreatePosts: migrating ======================================
-- create_table(:posts)
   (5.1ms)  CREATE TABLE "posts" ("id" serial primary key, "title" character varying, "body" text, "photo_id" integer, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
   -> 0.0060s
== 20160619124924 CreatePosts: migrated (0.0060s) =============================

   (1.0ms)  ROLLBACK
   (0.2ms)  SELECT pg_advisory_unlock(4844576453229231180)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 2, expected 0..1)
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/core.rb:312:in `initialize'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/inheritance.rb:65:in `new'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/inheritance.rb:65:in `new'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/validations.rb:15:in `create!'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1247:in `record_version_state_after_migrating'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1212:in `block in execute_migration_in_transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1279:in `block in ddl_transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/transactions.rb:211:in `transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1279:in `ddl_transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1210:in `execute_migration_in_transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1183:in `block in migrate_without_lock'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1182:in `each'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1182:in `migrate_without_lock'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1131:in `block in migrate'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1298:in `with_advisory_lock'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1131:in `migrate'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1005:in `up'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:983:in `migrate'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/usr/local/var/rbenv/versions/2.3.0/bin/rake:23:in `load'
/usr/local/var/rbenv/versions/2.3.0/bin/rake:23:in `<main>'
ArgumentError: wrong number of arguments (given 2, expected 0..1)
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/core.rb:312:in `initialize'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/inheritance.rb:65:in `new'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/inheritance.rb:65:in `new'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/validations.rb:15:in `create!'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1247:in `record_version_state_after_migrating'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1212:in `block in execute_migration_in_transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1279:in `block in ddl_transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/transactions.rb:211:in `transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1279:in `ddl_transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1210:in `execute_migration_in_transaction'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1183:in `block in migrate_without_lock'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1182:in `each'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1182:in `migrate_without_lock'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1131:in `block in migrate'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1298:in `with_advisory_lock'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1131:in `migrate'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:1005:in `up'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:983:in `migrate'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/usr/local/var/rbenv/versions/2.3.0/bin/rake:23:in `load'
/usr/local/var/rbenv/versions/2.3.0/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate
```

### System configuration
**Rails version**: 5.0.0rc
Running PostgreSQL

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by maclover7** [comment]
Hmm, I'm not able to reproduce this issue with [this reproduction script](https://gist.github.com/maclover7/568e2c4fb4fecd78d697bfa27ce88a01). It looks like the `protected-attributes` gem is in your backtrace -- can you try and remove that gem, and then try running the migration again?

**Comment by pedrozath** [comment]
It works perfectly now! Thanks @maclover7 :)

**Comment by maclover7** [comment]
:+1:

**Comment by elliotwesoff** [comment]
Hello, I'm having this issue on Rails 5.0.0.1 and Ruby 2.3.1. Has this issue occurred again since then or am I just unlucky?

**Comment by cemilycollins** [comment]
I had the same issue and it turned out I was missing the inheritance symbol "<" between my class name and the ActiveRecord::Migration. Not sure why it raised an argument error, but after I added the "<", the error went away.
