### ISSUE TITLE
error from rails new with version 5.0.0.rc2

### ISSUE THREAD

**Issue by kangkyu** [rails/rails#25482]
### Steps to reproduce

```
$ gem install rails -v 5.0.0.rc2
$ rails _5.0.0.rc2_ new app_name
```

### Expected behavior

should generate a new Rails app

### Actual behavior

raised error message as follows:

```
$ rails _5.0.0.rc2_ new lines
/Users/klee/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'railties' (= 5.0.0.rc2) - did find: [railties-5.0.0.rc1,railties-5.0.0.racecar1,railties-5.0.0.beta3,railties-4.2.6,railties-4.2.5.2,railties-4.2.3] (Gem::LoadError)
Checked in 'GEM_PATH=/Users/klee/.gem/ruby/2.3.0:/Users/klee/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /Users/klee/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /Users/klee/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /Users/klee/.rbenv/versions/2.3.1/bin/rails:22:in `<main>'
```

### System configuration
**Rails version**: 5.0.0.rc2

**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
As you can see by the backtrace this is a rubygems bug not a Rails bug. Everything from installation to load a gem is rubygems responsibility. I recommend you to open and issue there.

**Comment by kangkyu** [comment]
Thank you for answering! I saw this was already opened there 😃
