### ISSUE TITLE
undefined method `append' for #<Model::ActiveRecord_AssociationRelation ..>

### ISSUE THREAD

**Issue by sonalkr132** [rails/rails#25492]
### Steps to reproduce
* rails new my_app
* rails g scaffold post title:string body:text
* rails g resource comment post:references body:text
* rails db:migrate
* Add `has_many :comments` to `Post` model
* Create a post and a comment
* In rails console:
```
comment  = Comment.last
@post.comments.order(:created_at).append comment
```
### Expected behavior
get back an array appended with `comment`

### Actual behavior
Error:
```
undefined method `append' for #<Comment::ActiveRecord_AssociationRelation:0x000000049c6bf8>
  from /home/user/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc2/lib/active_record/relation/delegation.rb:123:in `method_missing'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc2/lib/active_record/relation/delegation.rb:93:in `method_missing'
  from (irb):2
  from /home/user/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.rc2/lib/rails/commands/console.rb:65:in `start'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.rc2/lib/rails/commands/console_helper.rb:9:in `start'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.rc2/lib/rails/commands/commands_tasks.rb:78:in `console'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.rc2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.rc2/lib/rails/commands.rb:18:in `<top (required)>'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc2/lib/active_support/dependencies.rb:293:in `require'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc2/lib/active_support/dependencies.rb:293:in `block in require'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc2/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc2/lib/active_support/dependencies.rb:293:in `require'
  from /home/user/my_app/bin/rails:9:in `<top (required)>'
...
```

### System configuration
**Rails version**:
rails-5.0.0.rc2
**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

This is happening because of 9d79334a1de

**Comment by rafaelfranca** [comment]
Yeah, that is expected. You should not call `append` in a `Relation`. If you need an array appended with comment call `to_a` explicitly.
