### ISSUE TITLE
Error ActiveRecord::Tasks::DatabaseAlreadyExists when running tests (Vagrant)

### ISSUE THREAD

**Issue by DannyBen** [rails/rails#25673]
### Steps to reproduce

- Use an Ubuntu 16 vagrant box, hosted on a Windows 10 host.
    - If you have Vagrant installed on Windows, simply use this [Vagrantfile] to load the box.
- Create a new rails app in the Vagrant shared folder:
    - `cd /vagrant`
    - `rails new hello`
    - `cd hello`
- Generate a controller: `rails g controller MoonLander index`
- Create the db schema file: `rails db:migrate`
- Run tests: `rails test`

### Expected behavior

The command should not generate any error.

### Actual behavior

The command generates the following error:

```
$ rails test
Running via Spring preloader in process 3742
rails aborted!
ActiveRecord::Tasks::DatabaseAlreadyExists: ActiveRecord::Tasks::DatabaseAlreadyExists
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/tasks/sqlite_database_tasks.rb:11:in `create'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/tasks/sqlite_database_tasks.rb:31:in `ensure in purge'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/tasks/sqlite_database_tasks.rb:31:in `purge'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:188:in `purge'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:369:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:375:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
/vagrant/ruby/rails5/hello/bin/rails:9:in `require'
/vagrant/ruby/rails5/hello/bin/rails:9:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
/vagrant/ruby/rails5/hello/bin/spring:13:in `require'
/vagrant/ruby/rails5/hello/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Errno::ETXTBSY: Text file busy @ unlink_internal - /vagrant/ruby/rails5/hello/db/test.sqlite3
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/tasks/sqlite_database_tasks.rb:22:in `drop'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/tasks/sqlite_database_tasks.rb:28:in `purge'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:188:in `purge'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:369:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:375:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
/vagrant/ruby/rails5/hello/bin/rails:9:in `require'
/vagrant/ruby/rails5/hello/bin/rails:9:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
/vagrant/ruby/rails5/hello/bin/spring:13:in `require'
/vagrant/ruby/rails5/hello/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:test:load => db:test:purge
(See full trace by running task with --trace)
Run options: --seed 61017

# Running:

.

Finished in 2.424344s, 0.4125 runs/s, 0.4125 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

### System configuration

**Rails version**: 5.0.0
**Ruby version**: 2.3.1
**OS**: Ubuntu 16.04 LTS (as a vagrant VM on a Windows host)

[Vagrantfile]: https://gist.github.com/DannyBen/836a952f97ab9fe2c90de8fa26471fff

**Comment by prakashmurthy** [comment]
Following the steps for reproducing the issue, I get the following error message:

````
$ rails new hello
$ cd hello/
$ rails g controller MoonLander index
$ rake test
/Users/prakash/Projects/hello/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/prakash/Projects/hello/config/application.rb to limit the frameworks that will be loaded.
````

This is a reasonable error message. Running `rails db:migrate` and then running `rake test` shows the expected output. 

This was on OS X.

**Comment by DannyBen** [comment]
@prakashmurthy - what you see seems like the correct behavior, but its not what I see. In fact, I encountered the error after trying to migrate a working rails 4.2 app (without a database, but with its schema.rb generated) - so I went on to investigate if it also happens on a fresh rails 5 app.

To be sure, I ran `db:migrate` on the same test app, and still getting the broken behavior:

```
$ rails db:migrate
$ rails test
Running via Spring preloader in process 12114
rails aborted!
ActiveRecord::Tasks::DatabaseAlreadyExists: ActiveRecord::Tasks::DatabaseAlreadyExists
...
```

**Comment by prakashmurthy** [comment]
Seems more like a Vagrant/VirtualBox issue. 

http://stackoverflow.com/questions/27359778/errnoetxtbsy-text-file-busy-unlink-internal be helpful.

**Comment by DannyBen** [comment]
1. Vagrant hasn't changed, Rails did....
2. Rails 4.x worked in the very same setup
3. Vagrant is a popular development platform

**Comment by rafaelfranca** [comment]
Thank you for the report.

The only thing that Rails does is: `File.exist?(database_file)` and this is returning true. If the file system is returning true to a file that doesn't exist it is indeed a bug in the filesystem, or in vagrant.

Even that Rails have changed and Vagrant doesn't Rails is doing the right thing that is checking if the database exists before overriding it, so we can't consider this a Rails bug.
