### ISSUE TITLE
ActiveRecord 5.0.0 - HABTM failing when association name is the same as join table name

### ISSUE THREAD

**Issue by mrbongiolo** [rails/rails#25689]
### Steps to reproduce

```bash
rails new habtm
rails g model User name
rails g model Job name
rails g migrate create_jobs_pool
```

```ruby
# db/migrate/create_jobs_pool.rb
class CreateJobsPool < ActiveRecord::Migration[5.0]
  def change
    create_table :jobs_pool, id: false do |t|
      t.references :job, null: false, index: true
      t.references :user, null: false, index: true
    end
  end
end
```

```ruby
# app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :jobs_pool,
    class_name: Job,
    join_table: 'jobs_pool'

end
```

On rails console:
```ruby
User.create(name: 1)
Job.create(name: 1)
User.first.jobs_pool = Job.all
User.first.jobs_pool.clear # it brokes here
```

### Actual behavior

It's raising:
```
Module::DelegationError: ActiveRecord::TableMetadata#association_foreign_key delegated to association.foreign_key, but association is nil: #<ActiveRecord::TableMetadata:0x00556cf17badf0 @klass=User::HABTM_JobsPool(job_id: integer, user_id: integer), @arel_table=#<Arel::Table:0x00556cf17baf80 @name="jobs_pool", @columns=nil, @aliases=[], @type_caster=#<ActiveRecord::TypeCaster::Map:0x00556cf17bb020 @types=User::HABTM_JobsPool(job_id: integer, user_id: integer)>, @table_alias=nil>, @association=nil>
from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/table_metadata.rb:3:in `rescue in association_foreign_key'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/table_metadata.rb:3:in `association_foreign_key'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/relation/predicate_builder/association_query_handler.rb:26:in `call'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/relation/predicate_builder.rb:76:in `build'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/relation/predicate_builder.rb:46:in `expand'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/relation/predicate_builder.rb:90:in `block in expand_from_hash'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/relation/predicate_builder.rb:86:in `each'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/relation/predicate_builder.rb:86:in `flat_map'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/relation/predicate_builder.rb:86:in `expand_from_hash'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/relation/predicate_builder.rb:31:in `build_from_hash'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/relation/where_clause_factory.rb:22:in `build'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/relation/query_methods.rb:632:in `where!'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/associations/has_many_through_association.rb:134:in `delete_records'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:549:in `remove_records'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:542:in `block in delete_or_destroy'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:203:in `block in transaction'
... 18 levels...
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
	from /home/mrbongiolo/projects/habtm/bin/rails:9:in `<top (required)>'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/mrbongiolo/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
	from /home/mrbongiolo/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/mrbongiolo/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

This seems to be happening because the name of the association `:jobs_pool` is the same as the table join table name. If I change it to something else then it work as intended.

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
Did this work for you in previous versions of Rails?

**Comment by mrbongiolo** [comment]
@maclover7 Yes. This started to happen as I upgraded to 5.0, I has on latest 4.2.x and the same code worked without a problem.

**Comment by maclover7** [comment]
👍 Just checking -- this helps us in figuring out where the problem here lies.

Would you be willing to do a `git bisect` between `4-2-stable` and `master` to figure out where this behavior was introduced?

**Comment by mrbongiolo** [comment]
I can do that. Will try to take a look at it today or tomorrow.

**Comment by maclover7** [comment]
👍 thanks! If you can't get to it, let me know and I can take care of it.

**Comment by prakashmurthy** [comment]
Created an executable Test Case to reproduce this behavior; confirming it works with `4.2.6` and fails with `5.0.0`. 

<details>
 <summary><b>habtm_bug.rb: </b></summary>

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  
  # Fail case
  gem 'activerecord', "5.0.0" # => Fail

  # Pass case
  # gem 'activerecord', "4.2.6" # => Pass
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string  :name
  end

  create_table :jobs, force: true do |t|
    t.string :name
  end

  create_table :jobs_pool, id: false do |t|
    t.references :job, null: false, index: true
    t.references :user, null: false, index: true
  end
end

class Job < ActiveRecord::Base
end

class User < ActiveRecord::Base
  has_and_belongs_to_many :jobs_pool,
   class_name: Job,
   join_table: 'jobs_pool'
end

class BugTest < Minitest::Test
  def test_jobs_pool_clear
    User.create(name: 1)
    Job.create(name: 1)
    User.first.jobs_pool = Job.all
    User.first.jobs_pool.clear
  end
end
```

</details>

**Comment by mrbongiolo** [comment]
@maclover7 git bisect seems to point to this commit: https://github.com/rails/rails/commit/a11a8ff7840cd5c5ebb881aac61be9771b07b3ba

**Comment by maclover7** [comment]
cc @sgrif
