### ISSUE TITLE
HABTM generates wrong join table name if models has similar prefix

### ISSUE THREAD

**Issue by danielterega** [rails/rails#25722]
### Steps to reproduce

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '5.0.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :blog_posts, force: true do |t|
  end

  create_table :blog_categories, force: true do |t|
  end

  create_table :blog_categories_blog_posts, force: true do |t|
    t.integer :blog_category_id
    t.integer :blog_post_id
  end
end
class BlogPost < ActiveRecord::Base
  has_and_belongs_to_many :blog_categories
end

class BlogCategory < ActiveRecord::Base
  has_and_belongs_to_many :blog_posts
end

class BugTest < Minitest::Test
  def test_through_joins
    BlogPost.create.blog_categories << BlogCategory.create
  end
end

```

### Expected behavior
It should not raise an error. 

### Actual behavior
It raising

```
ActiveRecord::StatementInvalid: Could not find table 'blog_categories_posts'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/sqlite3_adapter.rb:429:in `table_structure'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/sqlite3_adapter.rb:304:in `columns'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/schema_cache.rb:56:in `columns'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/schema_cache.rb:62:in `columns_hash'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/model_schema.rb:354:in `load_schema!'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/attributes.rb:233:in `load_schema!'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/attribute_decorators.rb:28:in `load_schema!'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/model_schema.rb:349:in `load_schema'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/model_schema.rb:266:in `attribute_types'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/attribute_methods.rb:179:in `has_attribute?'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/inheritance.rb:54:in `new'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/reflection.rb:152:in `build_association'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/association.rb:253:in `build_record'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:165:in `build'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/has_many_through_association.rb:67:in `build_through_record'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/has_many_through_association.rb:89:in `save_through_record'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/has_many_through_association.rb:47:in `insert_record'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:587:in `block (2 levels) in concat_records'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:430:in `replace_on_target'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:423:in `add_to_target'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:586:in `block in concat_records'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:584:in `each'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:584:in `concat_records'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/has_many_association.rb:129:in `concat_records'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/has_many_through_association.rb:27:in `concat_records'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:188:in `block in concat'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:203:in `block in transaction'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:211:in `transaction'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:202:in `transaction'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/collection_association.rb:188:in `concat'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/has_many_through_association.rb:21:in `concat'
    /Users/danielterega/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/associations/collection_proxy.rb:1007:in `<<'

```

### System configuration
**Rails version**: 5.0.0, also 4.2.6

**Ruby version**: 2.3.0

**Comment by mrgilman** [comment]
This is expected behavior: 

>  If your tables share a common prefix, it will only appear once at the beginning. For example, the tables “catalog_categories” and “catalog_products” generate a join table name of “catalog_categories_products”.

http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_and_belongs_to_many
