### ISSUE TITLE
Migrations potentially run in a different Ruby env than expected.

### ISSUE THREAD

**Issue by bionicpill** [rails/rails#25754]
### Steps to reproduce
Using a tool such a chruby (which changes your path in your local shell to point to a custom ruby install) can cause migrations to be run with a different Ruby install than the version being used by the current command line to run the test commands. This is specifically happening to me on a Mac whose system ruby is older than the required 2.2.2 to run Rails 5. Although I run the rake test command in a shell that is pointing to ruby 2.3, the system command used to run db:test:prepare runs in the system default ruby and fails since chruby does not override the global /bin/ruby

```
      def load_schema_if_pending!
        if ActiveRecord::Migrator.needs_migration? || !ActiveRecord::Migrator.any_migrations?
          # Roundtrip to Rake to allow plugins to hook into database initialization.
          FileUtils.cd Rails.root do
            current_config = Base.connection_config
            Base.clear_all_connections!
            system("bin/rails db:test:prepare")
            # Establish a new connection, the old database may be gone (db:test:prepare uses purge)
            Base.establish_connection(current_config)
          end
          check_pending!
        end
      end
```
There are workarounds involving updating the actual system Ruby to a upgraded version, but this still leaves the potential for code to run in different versions of Ruby and lead to unexpected behavior, or strange failures

1. Install chruby (or similar)
1. Use chruby to have your shell point to Ruby 2.3
1. Have some pending migrations
1. Run `bundle exec rake test` as normal

### Expected behavior
Ideally this would run db:test:prepare in the currently expected Ruby env and run the test suite.

### Actual behavior
Actually this error happens:

```
$ which ruby
/Users/jesse/.rubies/ruby-2.3.1/bin/ruby
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
$ bundle exec rake
DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use ActiveSupport::Reloader.to_prepare instead) (called from <top (required)> at /Users/jesse/work/garagiste/config/environment.rb:5)
Warning: You're using Rubygems 2.0.14.1 with Spring. Upgrade to at least Rubygems 2.1.0 and run `gem pristine --all` for better startup performance.

    Rails 5 requires Ruby 2.2.2 or newer.

    You're running
      ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

    Please upgrade to Ruby 2.2.2 or newer to continue.

rake aborted!
ActiveRecord::PendingMigrationError:

Migrations are pending. To resolve this issue, run:

	bin/rails db:migrate RAILS_ENV=test

/Users/jesse/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/migration.rb:572:in `check_pending!'
/Users/jesse/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/migration.rb:585:in `load_schema_if_pending!'
/Users/jesse/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/migration.rb:591:in `block in maintain_test_schema!'
/Users/jesse/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/migration.rb:822:in `suppress_messages'
/Users/jesse/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/migration.rb:596:in `method_missing'
/Users/jesse/.gem/ruby/2.3.1/gems/activerecord-5.0.0/lib/active_record/migration.rb:591:in `maintain_test_schema!'
/Users/jesse/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/test_help.rb:15:in `<top (required)>'
/Users/jesse/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/Users/jesse/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
/Users/jesse/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/jesse/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/Users/jesse/work/garagiste/test/test_helper.rb:3:in `<top (required)>'
/Users/jesse/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/Users/jesse/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
/Users/jesse/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/jesse/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/Users/jesse/work/garagiste/test/controllers/addresses_controller_test.rb:1:in `<top (required)>'
/Users/jesse/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/Users/jesse/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
/Users/jesse/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/jesse/.gem/ruby/2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/Users/jesse/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/test_unit/test_requirer.rb:11:in `block in require_files'
/Users/jesse/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/test_unit/test_requirer.rb:10:in `each'
/Users/jesse/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/test_unit/test_requirer.rb:10:in `require_files'
/Users/jesse/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/test_unit/minitest_plugin.rb:76:in `plugin_rails_init'
/Users/jesse/.gem/ruby/2.3.1/gems/minitest-5.9.0/lib/minitest.rb:80:in `block in init_plugins'
/Users/jesse/.gem/ruby/2.3.1/gems/minitest-5.9.0/lib/minitest.rb:78:in `each'
/Users/jesse/.gem/ruby/2.3.1/gems/minitest-5.9.0/lib/minitest.rb:78:in `init_plugins'
/Users/jesse/.gem/ruby/2.3.1/gems/minitest-5.9.0/lib/minitest.rb:129:in `run'
/Users/jesse/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/test_unit/minitest_plugin.rb:64:in `rake_run'
/Users/jesse/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/test_unit/testing.rake:15:in `block in <top (required)>'
/Users/jesse/.gem/ruby/2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/jesse/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/Users/jesse/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/jesse/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/Users/jesse/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/Users/jesse/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/jesse/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jesse/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/jesse/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/jesse/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/Users/jesse/.gem/ruby/2.3.1/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/Users/jesse/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/jesse/.gem/ruby/2.3.1/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/Users/jesse/.gem/ruby/2.3.1/bin/bundle:23:in `load'
/Users/jesse/.gem/ruby/2.3.1/bin/bundle:23:in `<main>'
```

### System configuration
**Rails version**:
Rails 5.0.0
**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by bionicpill** [comment]
Never mind, this was tracked down to a `ENV['PATH']` override in our local code base. :rage4: Please, carry on.
