### ISSUE TITLE
Unstable test suite running minitest 5.8.4

### ISSUE THREAD

**Issue by voxik** [rails/rails#25774]
### Steps to reproduce

The minitest was locket to minitest 5.3.3 more then two years ago (https://github.com/rails/rails/commit/8c48cd220648dc05c17def63d653fa98c3fab4de), but nobody cared so far to fix the instability. Since I am trying to package the latest Rails for Fedora, where is available just more recent version of minitest, the test suite is unstable from time to tim. Isn't it time to fix the instabilities and move forward to more recent versions of minitest?

These are the tests which I had to disable to make the AR test suite always pass (this is copy/paste from Fedora's .spec file, but I hope it is obvious that the sed just comments out several specific tests):

```
sed -i '/^  def test_preconfigured_includes_with_has_many_and_habtm$/,/^  end$/ s/^/#/' \
  test/cases/associations/eager_test.rb
sed -i '/^  def test_has_one_through_polymorphic_with_primary_key_option$/,/^  end$/ s/^/#/' \
  test/cases/associations/has_one_through_associations_test.rb
sed -i '/^  def test_has_many_through_polymorphic_with_primary_key_option$/,/^  end$/ s/^/#/' \
  test/cases/associations/has_many_through_associations_test.rb
sed -i '/^  def test_create_resets_cached_counters$/,/^  end$/ s/^/#/' \
  test/cases/associations/has_many_associations_test.rb
sed -i '/^  def test_do_not_call_callbacks_for_delete_all$/,/^  end$/ s/^/#/' \
  test/cases/associations/has_many_associations_test.rb
sed -i '/^  def test_find_queries_with_cache_multi_record$/,/^  end$/ s/^/#/' \
  test/cases/associations/has_many_associations_test.rb
sed -i '/^      def test_add_column_with_timestamp_type$/,/^      end$/ s/^/#/' \
  test/cases/migration/change_schema_test.rb
sed -i '/^  def test_do_not_call_callbacks_for_delete_all$/,/^  end$/ s/^/#/' \
  test/cases/query_cache_test.rb
sed -i '/^    def test_raises_an_error_when_called_with_protected_environment$/,/^    end$/ s/^/#/' \
  test/cases/tasks/database_tasks_test.rb
sed -i '/^class FoxyFixturesTest < ActiveRecord::TestCase/,/^end$/ s/^/#/' \
  test/cases/fixtures_test.rb
```

and this is how I execute the test suite later on:

```
ruby -Itest:lib <<EOF
  test_files = Dir.glob( "./test/cases/**/*_test.rb" )
  test_files.reject! { |x| x =~ %r|/adapters/| }

  # Only test sqlite3 backend
  test_files += Dir.glob("./test/cases/adapters/sqlite3/*_test.rb")

  test_files.sort.each { |f| require f }
EOF
```
### Expected behavior

The order of test cases execution does not matter and hence the test suite passes with the latest minitest.
### Actual behavior

The test cases are order dependent, so the test suite executed with the latest minitest, which executes the test suite in random order, fails from time to time.
### System configuration

**Rails version**:
5.0.0
**Ruby version**:
2.3.1
**Installed gems**:
activemodel (5.0.0)
activesupport (5.0.0)
arel (7.0.0)
bcrypt (3.1.10)
bigdecimal (1.2.8)
builder (3.2.2)
concurrent-ruby (1.0.2)
erubis (2.7.0)
i18n (0.7.0)
json (1.8.3)
metaclass (0.0.4)
minitest (5.8.4)
mocha (1.1.0)
psych (2.0.17)
rack (2.0.1)
rdoc (4.2.2)
sqlite3 (1.3.11)
thread_safe (0.3.5)
tzinfo (1.2.2)

**Comment by rafaelfranca** [comment]
Please feel free to submit pull request fixing the problems.

**Comment by zenspider** [comment]
@voxik AFAIKnew, I fixed all the order dependency issues. If there were more there was a lack of communication and laziness locking it down. If you want to help take a whack at fixing (or at least isolating) it, this is a perfect job for minitest-bisect. Lemme know if you need any advice.

**Comment by rafaelfranca** [comment]
I just created a branch to fix those problems and I'll try to fix those issues.

**Comment by voxik** [comment]
Rails::DBConsoleTest#test_sqlite3_db_without_defined_rails_root looks to be unstable

```
$ ruby -Itest -e 'Dir.glob "./test/**/*_test.rb", &method(:require)' -- -v
Run options: -v --seed 33256

# Running:

Rails::DBConsoleTest#test_config_choose_database_url_if_exists = 0.07 s = .
Rails::DBConsoleTest#test_config_with_database_url_only = 0.00 s = .
Rails::DBConsoleTest#test_config_with_db_config_only = 0.00 s = .
Rails::DBConsoleTest#test_config_with_no_db_config = 0.00 s = .
Rails::DBConsoleTest#test_env = 0.00 s = .
Rails::DBConsoleTest#test_mysql = 0.00 s = .
Rails::DBConsoleTest#test_mysql_full = 0.00 s = .
Rails::DBConsoleTest#test_mysql_include_password = 0.00 s = .
Rails::DBConsoleTest#test_oracle = 0.00 s = .
Rails::DBConsoleTest#test_oracle_include_password = 0.00 s = .
Rails::DBConsoleTest#test_postgresql = 0.00 s = .
Rails::DBConsoleTest#test_postgresql_full = 0.00 s = .
Rails::DBConsoleTest#test_postgresql_include_password = 0.00 s = .
Rails::DBConsoleTest#test_print_help_long = 0.00 s = .
Rails::DBConsoleTest#test_print_help_short = 0.00 s = .
Rails::DBConsoleTest#test_rails_env_is_dev_when_argument_is_dev_and_dev_env_is_present = 0.00 s = .
Rails::DBConsoleTest#test_rails_env_is_development_when_argument_is_dev = 0.00 s = .
Rails::DBConsoleTest#test_sqlite3 = 0.00 s = .
Rails::DBConsoleTest#test_sqlite3_db_absolute_path = 0.00 s = .
Rails::DBConsoleTest#test_sqlite3_db_without_defined_rails_root = 0.00 s = F
...
```

**Comment by voxik** [comment]
Looks like most of the generators tests are unstable, when running in one session. Are they supposed to run in one session together or not? I see that you execute each test file separately in travis, on the other hand, the Rakefile would suggest they are supposed to pass running in one sweep.

[1] https://github.com/rails/rails/blob/master/railties/Rakefile#L28

**Comment by rafaelfranca** [comment]
We always run isolated. We should remove that from the Rakefile.

**Comment by voxik** [comment]
This part of ActionPack test suite is unstable for me:

```
$ ruby -Ilib:test ./test/controller/request_forgery_protection_test.rb
Run options: --seed 62948

# Running:

..................................FFFEFFFFFFF.FF......F.........................................

Finished in 0.198903s, 482.6475 runs/s, 799.3850 assertions/s.

  1) Failure:
PerFormTokensControllerTest#test_Accepts_proper_token_for_patch_method_on_button_to_tag [./test/controller/request_forgery_protection_test.rb:731]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.


  2) Failure:
PerFormTokensControllerTest#test_rejects_token_for_incorrect_method_button_to [./test/controller/request_forgery_protection_test.rb:702]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.


  3) Failure:
PerFormTokensControllerTest#test_method_is_case_insensitive [./test/controller/request_forgery_protection_test.rb:813]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.


  4) Error:
PerFormTokensControllerTest#test_accepts_global_csrf_token:
ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/request_forgery_protection.rb:195:in `handle_unverified_request'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/request_forgery_protection.rb:223:in `handle_unverified_request'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/request_forgery_protection.rb:218:in `verify_authenticity_token'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:382:in `block in make_lambda'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:170:in `block in halting'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:454:in `block in call'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:454:in `each'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:454:in `call'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:90:in `run_callbacks'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/rescue.rb:20:in `process_action'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `block in instrument'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `instrument'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/abstract_controller/base.rb:126:in `process'
    /usr/share/gems/gems/actionview-5.0.0/lib/action_view/rendering.rb:30:in `process'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal.rb:190:in `dispatch'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/test_case.rb:532:in `process'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/test_case.rb:629:in `process_with_kwargs'
    /builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/test_case.rb:389:in `post'
    ./test/controller/request_forgery_protection_test.rb:751:in `block in test_accepts_global_csrf_token'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/test_case.rb:83:in `assert_nothing_raised'
    ./test/controller/request_forgery_protection_test.rb:750:in `test_accepts_global_csrf_token'


  5) Failure:
PerFormTokensControllerTest#test_Accepts_proper_token_for_delete_method_on_button_to_tag [./test/controller/request_forgery_protection_test.rb:731]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.


  6) Failure:
PerFormTokensControllerTest#test_Accepts_proper_token_for_implicit_post_method_on_button_to_tag [./test/controller/request_forgery_protection_test.rb:716]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.


  7) Failure:
PerFormTokensControllerTest#test_ignores_origin_during_generation [./test/controller/request_forgery_protection_test.rb:787]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.


  8) Failure:
PerFormTokensControllerTest#test_ignores_trailing_slash_during_validation [./test/controller/request_forgery_protection_test.rb:800]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.


  9) Failure:
PerFormTokensControllerTest#test_Accepts_proper_token_for_post_method_on_button_to_tag [./test/controller/request_forgery_protection_test.rb:731]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.


 10) Failure:
PerFormTokensControllerTest#test_rejects_token_for_incorrect_path [./test/controller/request_forgery_protection_test.rb:674]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.


 11) Failure:
PerFormTokensControllerTest#test_rejects_token_for_incorrect_method [./test/controller/request_forgery_protection_test.rb:688]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.


 12) Failure:
PerFormTokensControllerTest#test_accepts_token_for_correct_path_and_method [./test/controller/request_forgery_protection_test.rb:659]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.


 13) Failure:
PerFormTokensControllerTest#test_ignores_params [./test/controller/request_forgery_protection_test.rb:759]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.


 14) Failure:
PerFormTokensControllerTest#test_ignores_trailing_slash_during_generation [./test/controller/request_forgery_protection_test.rb:774]:
Expected at least 1 element matching "input[name="custom_authenticity_token"]", found 0..
Expected 0 to be >= 1.

96 runs, 159 assertions, 13 failures, 1 errors, 0 skips
```

Actually this should work independently IMO:

```
$ ruby -Ilib:test -e 'Dir.glob "./test/**/*_test.rb", &method(:require)' -- -n /PerFormTokensControllerTest/
... snip ...
15 runs, 14 assertions, 13 failures, 1 errors, 0 skips
```

**Comment by voxik** [comment]
And another from ActionPack I had to disable:

```
  1) Failure:
MimeTypeTest#test_parse_application_with_trailing_star [/builddir/build/BUILD/rubygem-actionpack-5.0.0/usr/share/gems/gems/actionpack-5.0.0/test/dispatch/mime_type_test.rb:54]:
--- expected
+++ actual
@@ -1 +1 @@
-[#<Mime::Type:0xXXXXXX @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-3848817430529246594>, #<Mime::Type:0xXXXXXX @synonyms=["application/javascript", "application/x-javascript"], @symbol=:js, @string="text/javascript", @hash=3325588938989841592>, #<Mime::Type:0xXXXXXX @synonyms=["text/xml", "application/x-xml"], @symbol=:xml, @string="application/xml", @hash=-191402270586314650>, #<Mime::Type:0xXXXXXX @synonyms=[], @symbol=:rss, @string="application/rss+xml", @hash=1120695300727392967>, #<Mime::Type:0xXXXXXX @synonyms=[], @symbol=:atom, @string="application/atom+xml", @hash=-80987169134013401>, #<Mime::Type:0xXXXXXX @synonyms=["text/yaml"], @symbol=:yaml, @string="application/x-yaml", @hash=-1597880446799649829>, #<Mime::Type:0xXXXXXX @synonyms=[], @symbol=:url_encoded_form, @string="application/x-www-form-urlencoded", @hash=3242865596997798509>, #<Mime::Type:0xXXXXXX @synonyms=["text/x-json", "application/jsonrequest"], @symbol=:json, @string="application/json", @hash=-3862578276059720616>, #<Mime::Type:0xXXXXXX @synonyms=[], @symbol=:pdf, @string="application/pdf", @hash=655040651190370667>, #<Mime::Type:0xXXXXXX @synonyms=[], @symbol=:zip, @string="application/zip", @hash=-2665118655506539456>, #<Mime::Type:0xXXXXXX @synonyms=["application/x-gzip"], @symbol=:gzip, @string="application/gzip", @hash=3008443231826502584>]
+[#<Mime::Type:0xXXXXXX @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-3848817430529246594>, #<Mime::Type:0xXXXXXX @synonyms=["application/javascript", "application/x-javascript"], @symbol=:js, @string="text/javascript", @hash=3325588938989841592>, #<Mime::Type:0xXXXXXX @synonyms=["text/xml", "application/x-xml"], @symbol=:xml, @string="application/xml", @hash=-191402270586314650>, #<Mime::Type:0xXXXXXX @synonyms=[], @symbol=:rss, @string="application/rss+xml", @hash=1120695300727392967>, #<Mime::Type:0xXXXXXX @synonyms=[], @symbol=:atom, @string="application/atom+xml", @hash=-80987169134013401>, #<Mime::Type:0xXXXXXX @synonyms=["text/yaml"], @symbol=:yaml, @string="application/x-yaml", @hash=-1597880446799649829>, #<Mime::Type:0xXXXXXX @synonyms=[], @symbol=:url_encoded_form, @string="application/x-www-form-urlencoded", @hash=3242865596997798509>, #<Mime::Type:0xXXXXXX @synonyms=[], @symbol=:pdf, @string="application/pdf", @hash=655040651190370667>, #<Mime::Type:0xXXXXXX @synonyms=[], @symbol=:zip, @string="application/zip", @hash=-2665118655506539456>, #<Mime::Type:0xXXXXXX @synonyms=["application/x-gzip"], @symbol=:gzip, @string="application/gzip", @hash=3008443231826502584>, #<Mime::Type:0xXXXXXX @synonyms=["text/x-json", "application/jsonrequest"], @symbol=:json, @string="application/json", @hash=-3862578276059720616>]
```

**Comment by rafaelfranca** [comment]
I already fixed both. Try the 5-0-stable branch.

**Comment by voxik** [comment]
ActionView has unstable test suite:

```
$ ruby -Ilib:test -e 'Dir.glob('\''./test/activerecord/**/*_test.rb'\'').each {|t| require t}'
Run options: --seed 2190

# Running:

.EE...EE................................................................................................................................................EEEEEEE.........

Finished in 3.781433s, 44.4276 runs/s, 72.9882 assertions/s.

  1) Error:
RenderPartialWithRecordIdentificationAndNestedDeeperControllersTest#test_render_with_record_collection_in_deeper_nested_controller:
NoMethodError: undefined method `info?' for nil:NilClass
    /usr/share/gems/gems/activerecord-5.0.0/lib/active_record/railties/controller_runtime.rb:22:in `cleanup_view_runtime'
    /usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:43:in `render'
    /builddir/build/BUILD/rubygem-actionview-5.0.0/usr/share/gems/gems/actionview-5.0.0/test/activerecord/render_partial_with_record_identification_test.rb:116:in `render_with_record_collection_in_deeper_nested_controller'
    /usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
    /usr/share/gems/gems/actionpack-5.0.0/lib/abstract_controller/base.rb:188:in `process_action'
    /usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
    /usr/share/gems/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:90:in `run_callbacks'
    /usr/share/gems/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
    /usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/rescue.rb:20:in `process_action'
    /usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `block in instrument'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /usr/share/gems/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `instrument'
    /usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    /usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
    /usr/share/gems/gems/activerecord-5.0.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    /usr/share/gems/gems/actionpack-5.0.0/lib/abstract_controller/base.rb:126:in `process'
    /builddir/build/BUILD/rubygem-actionview-5.0.0/usr/share/gems/gems/actionview-5.0.0/lib/action_view/rendering.rb:30:in `process'
    /usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/metal.rb:190:in `dispatch'
    /usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/test_case.rb:532:in `process'
    /usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/test_case.rb:634:in `process_with_kwargs'
    /usr/share/gems/gems/actionpack-5.0.0/lib/action_controller/test_case.rb:381:in `get'
    /builddir/build/BUILD/rubygem-actionview-5.0.0/usr/share/gems/gems/actionview-5.0.0/test/activerecord/render_partial_with_record_identification_test.rb:169:in `test_render_with_record_collection_in_deeper_nested_controller'

... snip ...
```

Is it supposed to be fixed by 9d0491937e520ac968919f7765b1209912d882a2? Because 9a1ab6674477642b72cc1760bb7dd69c9a5d6705 does not have any impact I'd say, or do the tests crashing all the times, then?

**Comment by rafaelfranca** [comment]
It should be fixed by `9d04919` is it not? `9a1ab6674477642b72cc1760bb7dd69c9a5d6705` is a different fix.

**Comment by rafaelfranca** [comment]
Are you running those tests in the 5-0-stable branch?

**Comment by pvalena** [comment]
There are new failures with Active Record 5.2.2; using Ruby 2.5, MiniTest 5.11.3:
```
ActiveRecord::BindParameterTest#test_too_many_binds:
ActiveRecord::StatementInvalid: SQLite3::SQLException: too many SQL variables: SELECT COUNT(*) FROM "topics" WHERE "topics"."id" IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, [ . . . ]
```

```
EagerAssociationTest#test_eager_habtm_with_association_inheritance:
ActiveRecord::SubclassNotFound: Invalid single-table inheritance type: Category is not a subclass of SpecialCategory
    /builddir/build/BUILD/activerecord-5.2.2/usr/share/gems/gems/activerecord-5.2.2/lib/active_record/inheritance.rb:233:in `find_sti_class'
 [ . . . ]
```

```
EagerAssociationTest#test_preloading_has_many_through_with_implicit_source:
ActiveRecord::SubclassNotFound: Invalid single-table inheritance type: Comment is not a subclass of VerySpecialComment
    /builddir/build/BUILD/activerecord-5.2.2/usr/share/gems/gems/activerecord-5.2.2/lib/active_record/inheritance.rb:233:in `find_sti_class'
 [ . . . ]
```
Full traceback:
https://paste.fedoraproject.org/paste/KOAb9HthnOoARoIpDN10hg

Full log:
https://copr-be.cloud.fedoraproject.org/results/pvalena/ruby-on-rails/fedora-rawhide-x86_64/00834661-rubygem-activerecord/build.log.gz

All dependencies / versions:
https://copr-be.cloud.fedoraproject.org/results/pvalena/ruby-on-rails/fedora-rawhide-x86_64/00834661-rubygem-activerecord/root.log.gz

Should I open a new bug or can you reopen this one?
