### ISSUE TITLE
Quoting of default values in Mysql2 adapter

### ISSUE THREAD

**Issue by PavelPenkov** [rails/rails#25810]
### Steps to reproduce

A migration with function as default value
```
class CreateFoos < ActiveRecord::Migration[5.0]
  def change
    create_table :foos do |t|
      t.timestamp :created_at, null: false, default: "now()"
    end
  end
end
```

### Expected behavior
A column with a default value should be created. 

### Actual behavior
An exception is thrown
```
== 20160713110332 CreateFoos: migrating =======================================
-- create_table(:foos)
Running via Spring preloader in process 16605
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Invalid default value for 'created_at': CREATE TABLE `foos` (`id` int AUTO_INCREMENT PRIMARY KEY, `created_at` datetime DEFAULT 'now()' NOT NULL) ENGINE=InnoDB
/home/synapse/projects/ruby/quoting_bug/db/migrate/20160713110332_create_foos.rb:3:in `change'
-e:1:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Invalid default value for 'created_at': CREATE TABLE `foos` (`id` int AUTO_INCREMENT PRIMARY KEY, `created_at` datetime DEFAULT 'now()' NOT NULL) ENGINE=InnoDB
/home/synapse/projects/ruby/quoting_bug/db/migrate/20160713110332_create_foos.rb:3:in `change'
-e:1:in `<main>'
Mysql2::Error: Invalid default value for 'created_at'
/home/synapse/projects/ruby/quoting_bug/db/migrate/20160713110332_create_foos.rb:3:in `change'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

As far as I understand MySQL server expects that function names will be unquoted, an SQL command with `now()` without quotes works fine in CLI. I can implement a fix though I'm not sure about semantics yet - how to differentiate between what should and what should not be quoted? E.g. quote strings, don't quote symbols? Or maybe I'm doing this wrong and there's a way to pass a function name?

### System configuration
**Rails version**: 5.0.0

**Ruby version**: ruby 2.3.1p112

**mysql2 version**: 0.4.4

**Comment by prakashmurthy** [comment]
This doesn't seem like a valid use case as activerecord automatically handles the default values for `created_at` and `updated_at` timestamps.

**Comment by rafaelfranca** [comment]
```
create_table :posts do |t|
  t.datetime :published_at, default: -> { 'NOW()' }
end
```

**Comment by rafaelfranca** [comment]
Does that work?

**Comment by kamipo** [comment]
Ref #20005.
