### ISSUE TITLE
ActiveSupport::SafeBuffer#gsub behaves not like expected

### ISSUE THREAD

**Issue by thutterer** [rails/rails#25824]
### Steps to reproduce

```
URI.encode(ActiveSupport::SafeBuffer.new("foo bar").to_s)
NoMethodError: undefined method `each_byte' for nil:NilClass
    from /home/tom/.rvm/rubies/ruby-2.2.3/lib64/ruby/2.2.0/uri/rfc2396_parser.rb:307:in `block in escape'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/core_ext/string/output_safety.rb:232:in `gsub'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/core_ext/string/output_safety.rb:232:in `gsub'
    from /home/tom/.rvm/rubies/ruby-2.2.3/lib64/ruby/2.2.0/uri/rfc2396_parser.rb:304:in `escape'
    from /home/tom/.rvm/rubies/ruby-2.2.3/lib64/ruby/2.2.0/uri/common.rb:99:in `escape'
    from (irb):3
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/railties-5.0.0/lib/rails/commands/console.rb:65:in `start'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /home/tom/code/rails-master/bin/rails:9:in `<top (required)>'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/spring-1.7.2/lib/spring/commands/rails.rb:6:in `call'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/spring-1.7.2/lib/spring/command_wrapper.rb:38:in `call'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/spring-1.7.2/lib/spring/application.rb:191:in `block in serve'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/spring-1.7.2/lib/spring/application.rb:161:in `fork'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/spring-1.7.2/lib/spring/application.rb:161:in `serve'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
    from /home/tom/.rvm/gems/ruby-2.2.3/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
    from /home/tom/.rvm/rubies/ruby-2.2.3/lib64/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/tom/.rvm/rubies/ruby-2.2.3/lib64/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'irb(main):004:0> _

=> nil
```
### Expected behavior

```
URI.encode(ActiveSupport::SafeBuffer.new("foo bar").to_s)
=> "foo%20bar"
```
### Actual behavior

```
ActiveSupport::SafeBuffer.new("foo bar").to_s.class
=> ActiveSupport::SafeBuffer
```

I've read an explaination for this behaviour in this [issue comment](https://github.com/rails/rails/issues/7863#issuecomment-9202215) by @jeremy.
But some difference in its gsub method I haven't further investigated yet leads to above issue.
I found this issue after I applied the [Style/UnneededInterpolation](http://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/UnneededInterpolation) rubocop to our code.
### System configuration

Tested with Rails 4.2.0 and 5.0-stable.
Both with Ruby 2.2.3

**Comment by maclover7** [comment]
As you've linked above, per @jeremy, seems like the solution is to call `to_str` on the `ActiveSupport::SafeBuffer`. 😬
