### ISSUE TITLE
Problem with dynamic layouts

### ISSUE THREAD

**Issue by owen2345** [rails/rails#25846]
Problem using this sample (Rails 5.0):
```
class ProductsController < ApplicationController
  layout Proc.new { |controller| controller.request.xhr? ? "popup" : "application" }
end
```
==> NoMethodError (undefined method `request' for [:html]:Array):

Also I tried with:
```
class ProductsController < ApplicationController
  layout :products_layout
 
  def show
    @product = Product.find(params[:id])
  end
 
  private
    def products_layout
      @current_user.special? ? "special" : "products"
    end
 
end
```
==> String, Proc, :default, true, or false, expected for `layout'; you passed :products_layout

Any ideas?

```
/www/rails/camaleon-gem/camaleon-cms-gem/app/controllers/camaleon_cms/camaleon_controller.rb:38:in `block in <class:CamaleonController>'
actionview (5.0.0) lib/action_view/renderer/template_renderer.rb:96:in `resolve_layout'
actionview (5.0.0) lib/action_view/renderer/template_renderer.rb:76:in `find_layout'
```

**Comment by owen2345** [comment]
Never mind!
