### ISSUE TITLE
Rails 5 Upgrade, error I am not able to find an issue on elsewhere

### ISSUE THREAD

**Issue by Schwad** [rails/rails#26064]
### Expected behavior

Normal page load.

### Actual behavior

Error from better_errors on page load:

```ruby
ExecJS::RuntimeError at /
SyntaxError: [stdin]:15:19: missing / (unclosed regex)
```

Breaking on `=stylesheet_link_tag`, if I comment it out it breaks on the next tag. 

`app/views/layouts/application.html.haml` =>
```ruby
    %title= content_for(:head)
    - else
      %title= _('Vessel HQ')
    %meta{content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible'}
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'pace.min'
    = include_gon
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
    = yield :js_in_head
```

Error on feature test in RSpec with Capybara:

```ruby
90) Vessel Show PSC does not raise error
    Failure/Error: visit root_path
    
    SyntaxError:
      ../../../app/views/layouts/session.html.haml:29: syntax error, unexpected '=', expecting keyword_end
      ));}\n";= javascript_include_tag :application
               ^
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/template.rb:309:in `module_eval'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/template.rb:309:in `compile'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/template.rb:258:in `block (2 levels) in compile!'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/notifications.rb:166:in `instrument'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/template.rb:350:in `instrument'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/template.rb:257:in `block in compile!'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/template.rb:245:in `synchronize'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/template.rb:245:in `compile!'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/template.rb:157:in `block in render'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/notifications.rb:166:in `instrument'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/template.rb:348:in `instrument'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/template.rb:156:in `render'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/skylight-0.10.5/lib/skylight/probes/action_view.rb:32:in `block in render_with_layout'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `block in instrument'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `instrument'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/skylight-0.10.5/lib/skylight/probes/action_view.rb:31:in `render_with_layout'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/renderer/template_renderer.rb:14:in `render'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/renderer/renderer.rb:42:in `render_template'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/renderer/renderer.rb:23:in `render'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/rendering.rb:103:in `_render_template'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/streaming.rb:217:in `_render_template'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/rendering.rb:83:in `render_to_body'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/renderers.rb:144:in `render_to_body'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/abstract_controller/rendering.rb:26:in `render'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/rendering.rb:36:in `render'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/core_ext/benchmark.rb:12:in `ms'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activerecord-5.0.0/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:43:in `render'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/wicked_pdf-1.0.6/lib/wicked_pdf/pdf_helper.rb:22:in `render_with_wicked_pdf'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/bundler/gems/remotipart-88d9a7d55bde/lib/remotipart/render_overrides.rb:16:in `render_with_remotipart'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/responders-2.2.0/lib/action_controller/responder.rb:238:in `default_render'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/responders-2.2.0/lib/action_controller/responder.rb:170:in `to_html'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/responders-2.2.0/lib/action_controller/responder.rb:163:in `respond'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/responders-2.2.0/lib/action_controller/responder.rb:156:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/responders-2.2.0/lib/action_controller/respond_with.rb:205:in `respond_with'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/devise-4.2.0/app/controllers/devise/sessions_controller.rb:12:in `new'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/abstract_controller/base.rb:188:in `process_action'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:126:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:126:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:455:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:455:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:286:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/bundler/gems/rails-observers-3fe157d6cbb5/lib/rails/observers/action_controller/caching/sweeper.rb:24:in `around'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:405:in `public_send'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:405:in `block in make_lambda'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:285:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:285:in `block in halting'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:447:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:447:in `block in around'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:455:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:455:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:90:in `run_callbacks'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/rescue.rb:20:in `process_action'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `block in instrument'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `instrument'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activerecord-5.0.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/abstract_controller/base.rb:126:in `process'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionview-5.0.0/lib/action_view/rendering.rb:30:in `process'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal.rb:190:in `dispatch'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_controller/metal.rb:262:in `dispatch'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/routing/route_set.rb:32:in `serve'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/routing/mapper.rb:46:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/routing/mapper.rb:46:in `serve'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/journey/router.rb:39:in `block in serve'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/journey/router.rb:26:in `each'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/journey/router.rb:26:in `serve'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/routing/route_set.rb:725:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-pjax-1.0.0/lib/rack/pjax.rb:12:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-attack-4.4.1/lib/rack/attack.rb:107:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/bundler/gems/remotipart-88d9a7d55bde/lib/remotipart/middleware.rb:32:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-2.0.1/lib/rack/conditional_get.rb:25:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/middleware/cookies.rb:613:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:90:in `run_callbacks'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/middleware/executor.rb:12:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/bundler/gems/airbrake-ad0837a56851/lib/airbrake/rack/middleware.rb:22:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/railties-5.0.0/lib/rails/rack/logger.rb:36:in `call_app'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `block in call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/tagged_logging.rb:70:in `block in tagged'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/tagged_logging.rb:26:in `tagged'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/tagged_logging.rb:70:in `tagged'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/sprockets-rails-3.1.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/request_store-1.3.1/lib/request_store/middleware.rb:9:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/middleware/request_id.rb:24:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/activesupport-5.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/middleware/executor.rb:12:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/actionpack-5.0.0/lib/action_dispatch/middleware/static.rb:136:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/railties-5.0.0/lib/rails/engine.rb:522:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/rack_test/browser.rb:61:in `process'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/rack_test/browser.rb:39:in `block in process_and_follow_redirects'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/rack_test/browser.rb:38:in `times'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/rack_test/browser.rb:38:in `process_and_follow_redirects'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/rack_test/browser.rb:22:in `visit'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/rack_test/driver.rb:43:in `visit'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/session.rb:233:in `visit'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
    # ./spec/support/login_macros.rb:17:in `login_admin_feature'
    # ./spec/features/error_avoidance/vessel_show_spec.rb:11:in `block (2 levels) in <top (required)>'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:98:in `block in run'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:88:in `loop'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:88:in `run'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rspec-retry-0.4.5/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
    # /Users/this_is-my_username/.rvm/gems/ruby-2.2.3/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:22:in `block (2 levels) in setup'

```

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.2.3

PM me if you'd like a gemlist. nicholas.schwaderer@gmail.com, not sure if this is related to using CoffeeScript, or implementing the configuration to use `manifest.js`. Happy to answer any questions, I would not have come here if I hadn't already exhausted all available resources for three straight days.

**Comment by pixeltrix** [comment]
@Schwad this appears to be a problem in your `session.html.haml` template and on the face of it nothing to do with Rails itself. I would double check your template first and if that appears to be okay [raise an issue with them][1].

If you still think there is a problem with Rails please reproduce the error in a simple app using ERB and an integration test (not RSpec/Capybara) so that we can effectively diagnose the problem.

[1]: https://github.com/haml/haml

**Comment by Schwad** [comment]
Thank you. 

Switched to ERB, also happening in application.html.erb file. Breaking with same error on stylesheet link tag.

**Comment by Schwad** [comment]
<img width="1280" alt="screen shot 2016-08-07 at 12 59 22 pm" src="https://cloud.githubusercontent.com/assets/7865030/17462245/dbc812ca-5c9e-11e6-80e8-7bdf3827c050.png">
When running `rake assets:precompile`

**Comment by Schwad** [comment]
my `manifest.js`

```js
// JS and CSS bundles
//
//= link_directory ../javascripts .js
//= link_directory ../stylesheets .css

// Misc for precompilation in production.

// Pull in all app/assets/images/ since app/views may link to them
// = link_directory ../images
```

**Comment by Schwad** [comment]
I think I'm getting closer. https://github.com/rails/ruby-coffee-script/blob/master/lib/coffee_script.rb#L29

**Comment by Schwad** [comment]
https://github.com/rails/ruby-coffee-script/issues/4

**Comment by Schwad** [comment]
A little more sunlight

<img width="1052" alt="screen shot 2016-08-07 at 3 12 54 pm" src="https://cloud.githubusercontent.com/assets/7865030/17462857/7e834f2c-5cb1-11e6-98eb-3aaf0cb65dcb.png">

**Comment by pixeltrix** [comment]
@Schwad have you actually managed to track down the error? I was wondering whether it was a compilation error or an actual missing `/` from a regex in your JS code.

**Comment by Schwad** [comment]
Hey @pixeltrix . I have a running hypothesis I should be able to report back on today. Will follow up back here when I know more, in case somebody runs into this same error in the future.

**Comment by Schwad** [comment]
@pixeltrix the solution for this error turned out to be downgrading sprockets from `4.0.0.beta.2` back to `~> 3.0.0`.

My coffeescript currently is not running and since non-verbose errors like the above have been associated with coffeescript, there's a 5% chance I haven't completed squashed the bug that relates to this error.

**Comment by Schwad** [comment]
Okay, final touches here, I downgraded rails-sprockets to a lower but *still* working version, broke the initial error here, and my broken JS therefore was because of the now-dead `jquery-cookie-rails` gem.

**Comment by kurtlaunchlabs** [comment]
I encounter this problem and I don't have any idea, did anybody solved this problem? Thanks

**Comment by Schwad** [comment]
Were you upgrading to Rails 5? Do you have the same gem listed above?

**Comment by kurtlaunchlabs** [comment]
Thanks for the response, I solved my issue, my problem was a syntax error
from coffescript file. From this url i got the idea
https://stackoverflow.com/questions/19130603/execjsruntime-error-somehow-related-to-javascript-coffeescript
.

**Comment by Schwad** [comment]
9 times out of 10 that's what a coffee script error is gonna look like. If only it was as easy to debug as Ruby! Glad to hear it :)

**Comment by ShomaFujii** [comment]
**### 

[1. ff****](`

> _**url**_

`)

**
