### ISSUE TITLE
Chained merge with joins generates wrong sql

### ISSUE THREAD

**Issue by Gasparila** [rails/rails#26198]
### Steps to reproduce
Basic model (silly example):
```
Site has many blogs
blogs has many comments
comments has many words
```
Following code will reproduce the issue:
```
Word.joins(:comment).merge(Comment.joins(:blog).merge(Blog.joins(:site)))
```

### Expected behavior
```
Word.joins(:comment).merge(Comment.joins(:blog).merge(Blog.joins(:site))).to_sql
```
Should generate:
```
SELECT "words".* FROM "words" INNER JOIN
"comments" ON "comments"."id" = "words"."comment_id" LEFT OUTER JOIN
"blogs" ON "blogs"."id" = "comments"."blog_id" LEFT OUTER JOIN
"sites" ON "sites"."id" = "blogs"."site_id"
```
### Actual behavior
Actual sql generated:
```
SELECT "words".* FROM "words" INNER JOIN 
"comments" ON "comments"."id" = "words"."comment_id" LEFT OUTER JOIN
"sites" ON "sites"."id" = "blogs"."site_id" LEFT OUTER JOIN 
"blogs" ON "blogs"."id" = "comments"."blog_id"
```
In this case, the `sites` join happens before the `blogs` join causing rails to crash with the following message 
```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "blogs"
```
Due to the fact that blogs hasn't been joined yet

### System configuration
**Rails version**: 4.2.5.2

**Ruby version**: 2.3.1

**Comment by prakashmurthy** [comment]
@Gasparila : I tried creating an [executable test case](https://github.com/prakashmurthy/executable_test_cases/blob/835b384629e0104c26300220782a9d77931b52c2/chained_merge_join.rb) for this issue. 

The sql generated is as you detailed in the actual behavior section above, but the query executes without any errors and returns the expected output. The script works fine with both Rails 5 and Rails 4. 

Could you provide a similar [executable test case](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) or a sample rails application to demonstrate the issue? Thanks.

**Comment by prakashmurthy** [comment]
Changing the database adapter from `sqlite3` to `postgres` in the executable test case above does make the test fail with the `ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "blogs"` error message. The script fails on rails 4.x and rails 5.x. 

https://github.com/rails/rails/issues/25806 might be the same as this issue.

<details>
  <summary>Executable test case with postgres</summary>

```ruby
##############################################################################
# Script for https://github.com/rails/rails/issues/26198
##############################################################################
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: 'rails/rails' 
  # gem "sqlite3"
  gem "pg", "~> 0.18.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
# ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "rails_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :sites, force: true do |t|
  end

  create_table :blogs, force: true do |t|
    t.integer :site_id
  end

  create_table :comments, force: true do |t|
    t.integer :blog_id
  end

  create_table :words, force: true do |t|
    t.integer :comment_id
  end
end

class Site < ActiveRecord::Base
  has_many :blogs
end

class Blog < ActiveRecord::Base
  belongs_to :site
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :blog
  has_many :words
end

class Word < ActiveRecord::Base
  belongs_to :comment
end

class BugTest < Minitest::Test
  def test_chained_merge_with_joins
    site = Site.create!

    blog1 = Blog.create!(site: site)
    blog2 = Blog.create!(site: site)

    comment1 = Comment.create!(blog: blog1)
    comment2 = Comment.create!(blog: blog1)
    comment3 = Comment.create!(blog: blog1)
    comment4 = Comment.create!(blog: blog2)

    word1 = Word.create!(comment: comment1)
    word2 = Word.create!(comment: comment2)
    word3 = Word.create!(comment: comment3)
    word4 = Word.create!(comment: comment3)
    word5 = Word.create!(comment: comment4)

    sql_query_1 = 'SELECT "words".* FROM "words" INNER JOIN "comments" ON "comments"."id" = "words"."comment_id" LEFT OUTER JOIN "blogs" ON "blogs"."id" = "comments"."blog_id" LEFT OUTER JOIN "sites" ON "sites"."id" = "blogs"."site_id"'
    sql_query_2 = 'SELECT "words".* FROM "words" INNER JOIN "comments" ON "comments"."id" = "words"."comment_id" LEFT OUTER JOIN "sites" ON "sites"."id" = "blogs"."site_id" LEFT OUTER JOIN "blogs" ON "blogs"."id" = "comments"."blog_id"'

    # assert_equal sql_query_1, Word.joins(:comment).merge(Comment.joins(:blog).merge(Blog.joins(:site))).to_sql
    assert_equal sql_query_2, Word.joins(:comment).merge(Comment.joins(:blog).merge(Blog.joins(:site))).to_sql
    assert_equal [word1, word2, word3, word4, word5], Word.joins(:comment).merge(Comment.joins(:blog).merge(Blog.joins(:site)))
  end
end

```
</details>

<details>
  <summary>Error stack trace</summary>
```ruby

  1) Error:
BugTest#test_chained_merge_with_joins:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "blogs"
LINE 1: ...ent_id" LEFT OUTER JOIN "sites" ON "sites"."id" = "blogs"."s...
                                                             ^
: SELECT "words".* FROM "words" INNER JOIN "comments" ON "comments"."id" = "words"."comment_id" LEFT OUTER JOIN "sites" ON "sites"."id" = "blogs"."site_id" LEFT OUTER JOIN "blogs" ON "blogs"."id" = "comments"."blog_id"
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:604:in `async_exec'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:604:in `block in exec_no_cache'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:586:in `block in log'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `log'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:604:in `exec_no_cache'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:591:in `execute_and_clear'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:378:in `select_prepared'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:40:in `select_all'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/querying.rb:39:in `find_by_sql'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/relation.rb:689:in `exec_queries'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/relation.rb:573:in `load'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/relation.rb:258:in `records'
    /Users/prakash/.rvm/gems/ruby-2.3.1/bundler/gems/rails-0d2f79b0ca61/activerecord/lib/active_record/relation.rb:655:in `=='

1 runs, 1 assertions, 0 failures, 1 errors, 0 skips

```
</details>

**Comment by maclover7** [comment]
Agree with @prakashmurthy, on the surface, this issue looks very similar to #25806. Going to close in favor of that issue. If it turns out they are not related, then we can open back up this ticket. :)
