### ISSUE TITLE
Error when not using active record

### ISSUE THREAD

**Issue by tomascharad** [rails/rails#26225]
### Steps to reproduce
Remove ```rails/all``` requirement from aplication.rb

require just the following
```ruby
require "active_model/railtie"
# require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "sprockets/railtie"
require "rails/test_unit/railtie"
```

### Expected behavior
I should be able to use rails without activercord.

### Actual behavior
This error:

```bash
/Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `active_record' for #<Rails::Application::Configuration:0x007f829eaa30c0> (NoMethodError)
	from /Users/tomascharad/Devapps/transituc-dispatchers-server/config/initializers/new_framework_defaults.rb:20:in `<top (required)>'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/engine.rb:648:in `block in load_config_initializer'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/engine.rb:647:in `load_config_initializer'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/engine.rb:611:in `each'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:44:in `each'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/tomascharad/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
	from /Users/tomascharad/Devapps/transituc-dispatchers-server/config/environment.rb:5:in `<top (required)>'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
	from /Users/tomascharad/Devapps/transituc-dispatchers-server/config.ru:3:in `block in <main>'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from /Users/tomascharad/Devapps/transituc-dispatchers-server/config.ru:in `new'
	from /Users/tomascharad/Devapps/transituc-dispatchers-server/config.ru:in `<main>'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/server.rb:59:in `app'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/server.rb:77:in `start'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/tomascharad/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**:
5.0.0
**Ruby version**:
2.3.1

**Comment by vipulnsward** [comment]
I believe you have 
```
Rails.application.config.active_record.belongs_to_required_by_default = false/true
```
in `new_framework_defaults.rb` file?
If you have skipped AR before, you need to get rid of this config as well.

**Comment by tomascharad** [comment]
Thanks @vipulnsward. That was indeed the problem.
