### ISSUE TITLE
Controllers will not render JSON.

### ISSUE THREAD

**Issue by louisscruz** [rails/rails#26274]
### Steps to reproduce
Perform any request that should render JSON in my controllers. (repo [here](https://github.com/louisscruz/dailydownbeat/tree/master/server)).

### Expected behavior
The controllers should render JSON.

### Actual behavior
For instance, when I make a call to create a session through my `sessions_controller`, I get the following error:

```
JWT::DecodeError (Nil JSON web token):
  
lib/json_web_token.rb:11:in `decode'
app/helpers/sessions_helper.rb:15:in `current_user'
app/controllers/api/sessions_controller.rb:13:in `create'
```

For some reason the `current_user` method of my `sessions_helper` is being called, and I have no idea why.

**sessions_helper.rb**

```
require 'json_web_token'

module SessionsHelper
  def create_session(user)
    session[:user_id] = user.id
  end

  def current_user
    puts caller
    auth_token = request.headers["Authorization"]
    if auth_token
      auth_token = auth_token.split(" ").last
      begin
        decoded_token = JsonWebToken.decode auth_token
      rescue JWT::ExpiredSignature
        return
      end
      @current_user ||= User.find_by(auth_token: auth_token)
    end
  end

  def log_out(user)
    logged_in? ? user.generate_authentication_token! : user.destroy_token!
    auth_token = user.auth_token
    user.update_attribute(:auth_token, auth_token)
  end

  def logged_in?
    current_user.present?
  end

  def authenticate_with_token!
    render json: { errors: "Not authenticated" }, status: :unauthorized unless logged_in?
  end

  def log_in(user)
    create_session(user)
    user.generate_authentication_token!
    user.update_attribute(:auth_token, user.auth_token)
  end

  def authenticate_as_self_or_admin!
    render json: { errors: "Not authorized" }, status: :unauthorized unless is_self? || is_admin?
  end

  def is_self?
    user = User.find(params[:id])
    auth_token = request.headers["Authorization"]
    auth_token = auth_token.split(" ").last if auth_token
    user.auth_token != auth_token
  end

  def is_admin?
    if logged_in? && current_user.authenticate(params[:password])
      current_user.admin
    end
  end
end

```

The output of the `p caller` is as follows:

```
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/active_model_serializers-532828b4dad4/lib/action_controller/serialization.rb:25:in `serialization_scope'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/active_model_serializers-532828b4dad4/lib/action_controller/serialization.rb:37:in `get_serializer'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/active_model_serializers-532828b4dad4/lib/action_controller/serialization.rb:60:in `block (2 levels) in <module:Serialization>'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/renderers.rb:151:in `block in _render_to_body_with_renderer'
/Users/louisstephancruz/.rbenv/versions/2.2.3/lib/ruby/2.2.0/set.rb:283:in `each_key'
/Users/louisstephancruz/.rbenv/versions/2.2.3/lib/ruby/2.2.0/set.rb:283:in `each'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/renderers.rb:147:in `_render_to_body_with_renderer'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/renderers.rb:143:in `render_to_body'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/abstract_controller/rendering.rb:26:in `render'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/rendering.rb:36:in `render'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/louisstephancruz/.rbenv/versions/2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activerecord/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/instrumentation.rb:43:in `render'
/Users/louisstephancruz/Programming/Websites/Projects/dailydownbeat/server/app/controllers/api/sessions_controller.rb:13:in `create'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/abstract_controller/base.rb:188:in `process_action'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/callbacks.rb:126:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/callbacks.rb:126:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/callbacks.rb:455:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/callbacks.rb:455:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/callbacks.rb:755:in `_run_process_action_callbacks'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/rescue.rb:20:in `process_action'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/notifications.rb:164:in `instrument'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activerecord/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/abstract_controller/base.rb:126:in `process'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal.rb:194:in `dispatch'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_controller/metal.rb:266:in `dispatch'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/journey/router.rb:39:in `block in serve'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/journey/router.rb:26:in `each'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/journey/router.rb:26:in `serve'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/routing/route_set.rb:725:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/conditional_get.rb:38:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activerecord/lib/active_record/migration.rb:553:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/callbacks.rb:755:in `_run_call_callbacks'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:57:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/railties/lib/rails/rack/logger.rb:36:in `call_app'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/railties/lib/rails/rack/logger.rb:24:in `block in call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/tagged_logging.rb:70:in `block in tagged'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/tagged_logging.rb:70:in `tagged'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/railties/lib/rails/rack/logger.rb:24:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/middleware/request_id.rb:24:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/activesupport/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/actionpack/lib/action_dispatch/middleware/static.rb:132:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/bundler/gems/rails-dd77e1bbfe36/railties/lib/rails/engine.rb:522:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `call'
/Users/louisstephancruz/.rvm/gems/ruby-2.2.4/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
Completed 500 Internal Server Error in 84ms (ActiveRecord: 3.8ms)
```

It appears that the very act of calling `render json: user` is making a call to my method `current_user`. The same error occurs with rendering JSON in the `users_controller.rb`.

### System configuration
**Rails version**: Originally on 5.0.0 (beta 2), Updated to 5.1.0 (alpha) in attempt to fix this issue

**Ruby version**: 2.2.3p173

**Comment by guilleiguaran** [comment]
The `serialization_scope` method of ActiveModelSerializers is calling to your `current_user` method, you can read more about this in [AMS guide](https://github.com/rails-api/active_model_serializers/blob/61059e900cdba72a88970fc790f73984c6bc2e99/docs/general/serializers.md#scope)

**Comment by guilleiguaran** [comment]
I'm closing this since it's a third-party issue and we keep in this repo only issues directly related to Rails.

**Comment by louisscruz** [comment]
@guilleiguaran, THANK YOU! I wouldn't have found that the serializer `scope_name` defaults to `current_user`. Plus, I've had the same serializer setup and sessions_helper for months, and this suddenly became a problem last night. I'm VERY thankful for your help in this issue.
