### ISSUE TITLE
unable to re-insert middleware that was previously deleted with middleware.delete 

### ISSUE THREAD

**Issue by naw** [rails/rails#26303]
Occasionally there may be a need to change the order of the middleware stack. In Rails 4.2 I did this by deleting a given middleware and adding it back in the new desired location.  In Rails 5, it is not possible to add a previously deleted middleware, since the delete operations run after all other operations, regardless of the actual order the operations are specified. I believe this is an unintended consequence from #18994.

### Steps to reproduce

1. Delete a middleware: `config.middleware.delete SomeMiddleware`
2. Re-insert the middleware somewhere else: `config.middleware.use SomeMiddleware`

### Expected behavior

`SomeMiddleware` should be part of the middleware stack.

### Actual behavior

`SomeMiddleware` is not part of the middleware stack.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.2.5

**Comment by maclover7** [comment]
cc @tgxworld @rafaelfranca

**Comment by rajcybage** [comment]
we got

`````
#<Rails::Configuration::MiddlewareStackProxy:0x4a90bb0 @operations=[ [:use, [ActionDispatch::Flash], nil], [:delete, [ActionDispatch::Flash], nil]]>
`````

**Comment by tgxworld** [comment]
Hmm @rafaelfranca I would suggest that we expose a `switch` method in the middleware proxy to change the position of a middleware. 

Because of how initializes can add/insert/swap middlewares, `delete` has to be run last in order for us to ensure that those insertions don't blow up because of a missing middleware that has been in an initializer somewhere else.

**Comment by naw** [comment]
@tgxworld 

Is it feasible for the user to solve those problems simply by ensuring certain initializers run after other initializers? In other words, rather than the framework itself manipulating the order in which `delete` operations occur, can't the user manipulate the order by using the normal initializer ordering mechanisms?  Or, is there a set of problems that ordering the initializers cannot solve?

If you consider how `delete` works for something simple like an array, for example, then I would propose that the current behavior of `middleware.delete` is unexpected.

```ruby
stack = ['a', 'b', 'c']
stack.delete('b')
stack.push('b')
# stack now equals ['a', 'c', 'b'], not ['a', 'c']
```

**Comment by tgxworld** [comment]
Im not sure how we will handle ordering of initializers defined in gems that manipulate the middleware stack. 

For example, if you want to do a insert_before SomeMiddleware but SomeMiddleware is deleted in an initializer in some gem. How will you handle that case?

**Comment by matthewd** [comment]
We could move the special handling of deletes into MiddlewareStack itself (from the proxy), and have it keep a hash of (deleted middleware) => (the thing that was before it)

**Comment by naw** [comment]
@tgxworld Yes, thanks for your example; that's helpful.

I see four scenarios:

1. app referencing middleware deleted from within the app
2. gem referencing middleware that you delete from within the app.
3. app referencing middleware that a gem deletes
4. gem referencing middleware deleted from within another gem

(1), (2), and (3) are all solvable if you understand the subtleties of when various chunks of configuration are actually run (i.e. application.rb, initializers, and gem initializers).  Of course, it would be nice if these problems could be solved without the user needing to know the subtleties of the initialization process.

Perhaps @matthewd 's solution would achieve that for most cases.

The most difficult of the above scenarios is (4), where you have two separate gems, each of which might make assumptions about your middleware stack.  As long as gems make assumptions, incompatibilities are possible.  While the framework can't solve _all_ of these incompatibilities, it may be able to solve some of them.

**Ideally, you want a solution that:**
  - solves most things for most users most of the time
  - doesn't violate the principle of least surprise
  - doesn't prevent users from taking more control when necessary

If you go back to the original issue #16433, there are 3 solutions/workarounds:

1. instruct the user to delete `Rack::Runtime` in an initializer instead of in application.rb 
2. modify Rails so it doesn't assume `Rack::Runtime` is present in the stack.
3. hack `delete` so that the deleted `Rack::Runtime` can be referenced elsewhere without anything blowing up.

Personally I think (1) is fine, because anyone manipulating the default Rails middleware stack is going to need to be prepared to dig a little deeper into subtleties like execution order of initialization code.  Rails builds the middleware imperatively (rather than declaratively like a rackup file), so manipulating middleware is inextricably linked to the execution order, and there is a limit to how well you can insulate or protect users from this.

(2) arguably is the best solution in principal, but pragmatically it may not have been feasible for `Rack::Runtime`

(3) is fine too (and both #18994 and @matthewd's suggestion are forms of this), but there may be trade-offs to consider if it violates the principle of least surprise for other use cases or if it is too clever for its own good.

It's ugly, but my workaround for now is not to use `middleware.delete`. Instead I swap in a pass-through middleware for any middlewares that I want to delete and add later.

Thanks to you both for taking the time to discuss this issue. :heart:

**Comment by Sirupsen** [comment]
FWIW my work-around for this issue to get Rails 4 behaviour:

```ruby
session_operations = Rails::Configuration::MiddlewareStackProxy.new([
   [:delete, %w(MiddleWareToChangeOrderingOf)],
   [:insert_after, %w(SomeOtherMiddleware MiddleWareToChangeOrderingOf)],
])

config.middleware = config.middleware + session_operations
```

**Comment by naw** [comment]
@Sirupsen 

Yeah that looks like a viable workaround.

Regarding the pass-through middleware I mentioned, it turns out you can substitute any object you want (even `nil`) as long you delete it from the stack.  In other words, it doesn't actually have to be a special pass-through middleware because you can remove it:

```ruby
config.middleware.swap(MiddlewareToChangeOrderingOf, nil)
config.middleware.delete(nil)
config.middleware.insert_after(SomeOtherMiddleware, MiddlewareToChangeOrderingOf)
```

**Comment by Sirupsen** [comment]
Clever! I'm gonna do that instead.

**Comment by benlangfeld** [comment]
@naw / @sirupsen on Rails 5.1.6, the `MiddlewareStackProxy` solution leaves me with the middleware present in both locations. The `delete(nil)` solution causes this error:

```
➭ bin/rails middleware
rails aborted!
No such middleware to insert before: MessageBus::Rack::Middleware
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/stack.rb:106:in `assert_index'
vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/stack.rb:85:in `swap'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/configuration.rb:69:in `block in merge_into'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/configuration.rb:68:in `each'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/configuration.rb:68:in `merge_into'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:507:in `block in app'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:504:in `synchronize'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:504:in `app'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/application/finisher.rb:45:in `block in <module:Finisher>'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/railtie.rb:185:in `public_send'
vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/railtie.rb:185:in `method_missing'
config/environment.rb:7:in `<main>'
```

**Comment by benlangfeld** [comment]
The only way I found to work around this is to sub-class the middleware I want to move, delete the original and insert the subclass.

**Comment by naw** [comment]
If `nil` doesn't work anymore, you can probably swap in any other arbitrary middleware you want, and then delete it later.

**Comment by camertron** [comment]
It may not cover all use cases, but I recently released a gem called [rails-middleware-extensions](https://github.com/camertron/rails-middleware-extensions) that could help with this issue. Specifically it adds `middleware.insert_unless_exists` and `middleware.move`.

**Comment by st0012** [comment]
I think this issue has been solved after https://github.com/rails/rails/pull/38169 introduced the `move_before` and `move_after` methods?
