### ISSUE TITLE
No such file or directory @ rb_sysopen when accessing cache file

### ISSUE THREAD

**Issue by nextofsearch** [rails/rails#26396]
### Error message

```
"user_id: BA0F0D7D-DEE2-4E10-A571-FD991E168DC9 | e: No such file or directory @ rb_sysopen - /home/deployer/apps/worker/releases/20160829120822/tmp/cache/743/8C1/.permissions_check.53572180.21796.747699
```

### Backtrace

```
/home/deployer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1157:in `initialize'
/home/deployer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1157:in `open'
/home/deployer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1157:in `rescue in block in touch'
/home/deployer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1153:in `block in touch'
/home/deployer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1151:in `each'
/home/deployer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1151:in `touch'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/core_ext/file/atomic.rb:58:in `probe_stat_in'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/core_ext/file/atomic.rb:32:in `atomic_write'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/cache/file_store.rb:83:in `write_entry'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/cache/strategy/local_cache.rb:115:in `write_entry'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/cache.rb:391:in `block in write'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/cache.rb:547:in `block in instrument'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:166:in `instrument'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/cache.rb:547:in `instrument'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/cache.rb:389:in `write'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/cache.rb:588:in `save_block_result_to_cache'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/cache.rb:299:in `fetch'
/home/deployer/apps/worker/releases/20160829120822/shared/workers/csv_update_sidekiq_worker.rb:163:in `create_device'
/home/deployer/apps/worker/releases/20160829120822/shared/workers/csv_update_sidekiq_worker.rb:98:in `update_profile'
/home/deployer/apps/worker/releases/20160829120822/shared/workers/csv_update_sidekiq_worker.rb:56:in `block in update_profile_with_csv_file'
/home/deployer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1748:in `each'
/home/deployer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1131:in `block in foreach'
/home/deployer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1282:in `open'
/home/deployer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1130:in `foreach'
/home/deployer/apps/worker/releases/20160829120822/shared/workers/csv_update_sidekiq_worker.rb:53:in `update_profile_with_csv_file'
/home/deployer/apps/worker/releases/20160829120822/shared/workers/csv_update_sidekiq_worker.rb:31:in `update_profile_with_csv_file'
/home/deployer/apps/worker/releases/20160829120822/shared/workers/csv_update_sidekiq_worker.rb:12:in `perform'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:152:in `execute_job'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/logging.rb:32:in `with_context'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:129:in `block in process'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:168:in `stats'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:128:in `process'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:80:in `process_one'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:68:in `run'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:17:in `watchdog'
/home/deployer/apps/worker/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

It raises an error while accessing the cache file using the following code:

```
device = Rails.cache.fetch(Device.memcache_key(os_platform_id, device_unique_id), :expires_in => Device::CACHE_EXPIRE_IN) do
```

There is a corresponding file in the folder:

```
devices%2Fos_platform_id%2F1%2Funique_id%2FBA0F0D7D-DEE2-4E10-A571-FD991E168DC9
```

This code has been run for a few years everyday processing millions of 'device' records but I haven't seen this before and we didn't update anything for a few months at least. FYI, the disk space usage is around 25%. 

### System configuration

**Rails version**: 4.2.7

**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
Hi @nextofsearch! It seems like this is an app specific issue, so I'd ask you to please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you, and hopefully your issue will be solved! We unfortunately reserve the issues tracker for issues only.

**Comment by karwank** [comment]
Hi @nextofsearch! Did you find a solution to fix this issue? I can't find any StackOverflow conversation with this subject. I have the same issue with Rails 5.

**Comment by igorpan** [comment]
Exactly the same issue here, code running for months, only difference is that it was triggered by rails cache:

```
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/fileutils.rb:1158:in `open' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/fileutils.rb:1158:in `rescue in block in touch' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/fileutils.rb:1154:in `block in touch' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/fileutils.rb:1152:in `each' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/fileutils.rb:1152:in `touch' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/file/atomic.rb:58:in `probe_stat_in' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/file/atomic.rb:32:in `atomic_write' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache/file_store.rb:83:in `write_entry' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache.rb:115:in `write_entry' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache.rb:391:in `block in write' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache.rb:547:in `block in instrument' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache.rb:547:in `instrument' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache.rb:389:in `write' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache.rb:588:in `save_block_result_to_cache' 
Apr 09 15:55:05 rounded-app app/web.2:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache.rb:299:in `fetch' 
```

**Comment by dpep** [comment]
I'm seeing this issue also.  might be a race condition involving `ActiveSupport::Cache::FileStore`, whereby the cache tries to touch a file who's directory was *just* deleted?

took a small stab at it: https://github.com/rails/rails/pull/44151
