### ISSUE TITLE
When parsing mime type: undefined method `symbol' for nil:NilClass

### ISSUE THREAD

**Issue by samphilipd** [rails/rails#26444]
### Steps to reproduce

Not sure how to give explicit steps to reproduce but I can explain with code:

```ruby
# rails/actionpack/lib/action_dispatch/http/mime_negotiation.rb
def content_mime_type
  fetch_header("action_dispatch.request.content_type") do |k|
    v = if get_header("CONTENT_TYPE") =~ /^([^,\;]*)/
      Mime::Type.lookup($1.strip.downcase)
    else
      ### Here `v` can be nil if CONTENT_TYPE isn't set
      nil 
    end
    set_header k, v
  end
end
```

But here:

```ruby
def parse_formatted_parameters(parsers)
  return yield if content_length.zero? || content_mime_type.nil?

  ### Here we assume that `content_mime_type` is never nil
  strategy = parsers.fetch(content_mime_type.symbol) { return yield }

  ...
end
```

This can happen in production. Here is the stacktrace:

```
/home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/http/parameters.rb:63:in `parse_formatted_parameters'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/http/request.rb:366:in `block in POST'
  /home/rof/cache/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/request.rb:57:in `fetch'
  /home/rof/cache/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/request.rb:57:in `fetch_header'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/http/request.rb:365:in `POST'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/http/parameters.rb:35:in `parameters'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/http/filter_parameters.rb:41:in `filtered_parameters'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb:4:in `__home_rof_cache_bundler_ruby_______gems_exception_notification_______lib_exception_notifier_views_exception_notifier__request_text_erb__3441448030875856134_70234779466920'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/template.rb:158:in `block in render'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:166:in `instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/template.rb:348:in `instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/template.rb:156:in `render'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/partial_renderer.rb:343:in `render_partial'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/partial_renderer.rb:311:in `block in render'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `block in instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/partial_renderer.rb:310:in `render'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/renderer.rb:47:in `render_partial'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/helpers/rendering_helper.rb:35:in `render'
  /home/rof/cache/bundler/ruby/2.3.0/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb:9:in `block in __home_rof_cache_bundler_ruby_______gems_exception_notification_______lib_exception_notifier_views_exception_notifier_exception_notification_text_erb__1163125053828059499_70234780148140'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb:7:in `map'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb:7:in `__home_rof_cache_bundler_ruby_______gems_exception_notification_______lib_exception_notifier_views_exception_notifier_exception_notification_text_erb__1163125053828059499_70234780148140'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/template.rb:158:in `block in render'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:166:in `instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/template.rb:348:in `instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/template.rb:156:in `render'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `block in instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  /home/rof/cache/bundler/ruby/2.3.0/gems/skylight-0.10.5/lib/skylight/probes/action_view.rb:35:in `render_with_layout'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/template_renderer.rb:14:in `render'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/renderer.rb:42:in `render_template'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/renderer/renderer.rb:23:in `render'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/rendering.rb:103:in `_render_template'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/rendering.rb:83:in `render_to_body'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/rendering.rb:26:in `render'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/base.rb:899:in `block in collect_responses'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/collector.rb:26:in `custom'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/collector.rb:9:in `text'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/email_notifier.rb:112:in `block in compose_email'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/base.rb:900:in `collect_responses'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/base.rb:816:in `mail'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/email_notifier.rb:111:in `compose_email'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/email_notifier.rb:42:in `exception_notification'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/base.rb:188:in `process_action'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:90:in `run_callbacks'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/base.rb:126:in `process'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/rescuable.rb:23:in `block in process'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/rescuable.rb:22:in `process'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionview-5.0.0/lib/action_view/rendering.rb:30:in `process'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/base.rb:595:in `block in process'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `block in instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `instrument'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/base.rb:594:in `process'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/message_delivery.rb:105:in `block in processed_mailer'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/message_delivery.rb:104:in `tap'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/message_delivery.rb:104:in `processed_mailer'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionmailer-5.0.0/lib/action_mailer/message_delivery.rb:95:in `deliver_now'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/email_notifier.rb:167:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier.rb:105:in `fire_notification'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier.rb:48:in `block in notify_exception'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier.rb:47:in `each'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier.rb:47:in `notify_exception'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notification/rack.rb:42:in `rescue in call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notification/rack.rb:32:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
  /home/rof/cache/bundler/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/conditional_get.rb:25:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
  /home/rof/cache/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/cookies.rb:613:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:90:in `run_callbacks'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:36:in `call_app'
  /home/rof/cache/bundler/ruby/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `block in call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/tagged_logging.rb:70:in `block in tagged'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/tagged_logging.rb:26:in `tagged'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/tagged_logging.rb:70:in `tagged'
  /home/rof/cache/bundler/ruby/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/silencer-0.6.0/lib/silencer/logger.rb:17:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/request_store-1.3.1/lib/request_store/middleware.rb:9:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/request_id.rb:24:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/executor.rb:12:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
  /home/rof/cache/bundler/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:522:in `call'
  /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/passenger-4.0.59/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

For what it's worth in all cases I've seen the requests came from Uptimebot and `Content-Type` was not set:

```
  * HTTP_REFERER                                   : http://uptime.com/progolfme.com
  * HTTP_USER_AGENT                                : Mozilla/5.0 (compatible; Uptimebot/1.0; http://www.uptime.com/uptimebot)
```

### System configuration
**Rails version**:
5.0.0

**Ruby version**:
2.3.1

**Comment by maclover7** [comment]
Hi @samphilipd! On a very quick look, this looks very similar to #24827. Would you be able to check and see if the associated PR (#25950) fixes this issue for you? Thanks!

**Comment by samphilipd** [comment]
@maclover7 yes! That's the same issue. Closing this one as a duplicate.
