### ISSUE TITLE
Parent does not exist error when creating parent with children in has_many belongs_to relationship 

### ISSUE THREAD

**Issue by dinsaw** [rails/rails#26618]
### Steps to reproduce

Use rails 5.0.0.1

parent.rb

```
class Parent < ApplicationRecord
  has_many :children
  accepts_nested_attributes_for :children
end
```
child.rb

```
class Child < ApplicationRecord
  belongs_to :parent
end
```

### Expected behavior

```
rb(main):008:0> parent = Parent.new
=> #<Parent id: nil, created_at: nil, updated_at: nil>
irb(main):009:0> parent.children.build
=> #<Child id: nil, parent_id: nil, created_at: nil, updated_at: nil>
irb(main):010:0> parent.save
=> true

```
### Actual behavior

```
rb(main):008:0> parent = Parent.new
=> #<Parent id: nil, created_at: nil, updated_at: nil>
irb(main):009:0> parent.children.build
=> #<Child id: nil, parent_id: nil, created_at: nil, updated_at: nil>
irb(main):010:0> parent.save
   (0.5ms)  BEGIN
   (0.4ms)  ROLLBACK
=> false
parent.save!

2.2.5 :003 > parent.save!
   (0.7ms)  BEGIN
   (0.3ms)  ROLLBACK
ActiveRecord::RecordInvalid: Validation failed: Children parent must exist
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/activerecord-5.0.0.1/lib/active_record/validations.rb:78:in `raise_validation_error'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/activerecord-5.0.0.1/lib/active_record/validations.rb:50:in `save!'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:324:in `block in save!'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:324:in `save!'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/activerecord-5.0.0.1/lib/active_record/suppressor.rb:45:in `save!'
	from (irb):3
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/user/.rvm/gems/ruby-2.2.5@got/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'


```

### System configuration
**Rails version**:

** 5.0.0.1**:

**Comment by mechanicles** [comment]
Based on your steps, this is a correct behavior. In Rails 5, if you have this kind of relationship `belongs_to :parent` then you have to pass existing parent object or create a new parent object then assign to children object.

Please check http://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html

**Comment by prathamesh-sonpatki** [comment]
This is being tracked here https://github.com/rails/rails/issues/25198

**Comment by bernardoGalindoDiscoverySpecialists** [comment]
It seems `update` method in Rails 6 is not triggering this validation.

```ruby
  class Parent < ApplicationRecord
     has_many :children
     belongs_to :granpa
   end
```

```ruby
  class Granpa < ApplicationRecord
  end
```

```ruby
    class Children < ApplicationRecord
      belongs_to :parent, autosave: true
    end
```

When you  update a given `children`  and the `parent`  contains an invalid `granpa` lets say `a deleted record`  in rails 5 
active record returns an error `Parent granpa must exist` and now in rails 6 is returning `valid?` true is it related or is it other issue?
