### ISSUE TITLE
Model validations doesn't work in rails 5.1.0.alpha

### ISSUE THREAD

**Issue by PragmaticEd** [rails/rails#26638]
Simple model validations wont work in 5.1.0.alpha

### Now to reproduce:
`$ rails _5.1.0.alpha_ new test_project`
`$ cd test_project`
`$ rails g model user`

then add any field, and add `validates :field, presence: true`

If i lock rails version in Gemfile to `5.0.0`, everything works fine.

### System configuration
**Rails version**: 5.1.0.alpha

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

Using example (https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb):
```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem 'rails', '5.1.0.alpha', github: 'rails/rails'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name, default: nil
  end
end

class User < ActiveRecord::Base
  validates :name, presence: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    User.create!(id: 1)
  end
end
```

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by PragmaticEd** [comment]
@rafaelfranca Yes, ofc. Sorry i didn't do that, to begin with.. I updated the issue

**Comment by alexcameron89** [comment]
I tried to reproduce the issue with the script, but I was not able to:
```
Resolving dependencies...
Using rake 11.2.2
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.3.3
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.2
Using bundler 1.12.5
Using method_source 0.8.2
Using thor 0.19.1
Using sqlite3 1.3.11
Using tzinfo 1.2.2
Using nokogiri 1.6.8
Using rack-test 0.6.3
Using sprockets 3.7.0
Using websocket-driver 0.6.4
Using mime-types 3.1
Using activesupport 5.1.0.alpha
Using loofah 2.0.3
Using mail 2.6.4
Using rails-dom-testing 2.0.1
Using globalid 0.3.7
Using activemodel 5.1.0.alpha
Using rails-html-sanitizer 1.0.3
Using activejob 5.1.0.alpha
Using activerecord 5.1.0.alpha
Using actionview 5.1.0.alpha
Using actionpack 5.1.0.alpha
Using actioncable 5.1.0.alpha
Using actionmailer 5.1.0.alpha
Using railties 5.1.0.alpha
Using sprockets-rails 3.2.0
Using rails 5.1.0.alpha
-- create_table(:users, {:force=>true})
D, [2016-09-27T12:26:00.037578 #24918] DEBUG -- :    (0.3ms)  CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar)
   -> 0.0431s
D, [2016-09-27T12:26:00.047410 #24918] DEBUG -- :    (3.4ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
D, [2016-09-27T12:26:00.068415 #24918] DEBUG -- :   ActiveRecord::InternalMetadata Load (9.3ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]
D, [2016-09-27T12:26:00.081136 #24918] DEBUG -- :    (0.1ms)  begin transaction
D, [2016-09-27T12:26:00.085419 #24918] DEBUG -- :   SQL (0.1ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "development"], ["created_at", "2016-09-27 17:26:00.084357"], ["updated_at", "2016-09-27 17:26:00.084357"]]
D, [2016-09-27T12:26:00.086652 #24918] DEBUG -- :    (0.2ms)  commit transaction
Run options: --seed 61741

# Running:

D, [2016-09-27T12:26:00.126749 #24918] DEBUG -- :    (0.2ms)  begin transaction
D, [2016-09-27T12:26:00.169263 #24918] DEBUG -- :    (0.2ms)  rollback transaction
E

Finished in 0.055247s, 18.1005 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_association_stuff:
ActiveRecord::RecordInvalid: Validation failed: Name can't be blank
    /home/alex/fn/rails/activerecord/lib/active_record/validations.rb:78:in `raise_validation_error'
    /home/alex/fn/rails/activerecord/lib/active_record/validations.rb:50:in `save!'
    /home/alex/fn/rails/activerecord/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
    /home/alex/fn/rails/activerecord/lib/active_record/transactions.rb:324:in `block in save!'
    /home/alex/fn/rails/activerecord/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
    /home/alex/fn/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `block in transaction'
    /home/alex/fn/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:186:in `within_new_transaction'
    /home/alex/fn/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
    /home/alex/fn/rails/activerecord/lib/active_record/transactions.rb:211:in `transaction'
    /home/alex/fn/rails/activerecord/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    /home/alex/fn/rails/activerecord/lib/active_record/transactions.rb:324:in `save!'
    /home/alex/fn/rails/activerecord/lib/active_record/suppressor.rb:46:in `save!'
    /home/alex/fn/rails/activerecord/lib/active_record/persistence.rb:51:in `create!'
    ../perusals/26638.rb:34:in `test_association_stuff'

```
