### ISSUE TITLE
PG::InvalidTextRepresentation raised when querying boolean column

### ISSUE THREAD

**Issue by fernandoluizao** [rails/rails#26669]
### Steps to reproduce

I have the following tables on a Postgres database:

    table1:
    id: integer
    active: boolean

    table2:
    id: integer
    table1_id: integer

Models

    Table1: vanilla active record
    Table2: belongs_to :table1

When I query:

    Table1.where(active: true)

It works as expected. However, when I query:

    Table2.joins(table1).where(table1: {active: true})

An exception is raised.

### Expected behavior

The query should not raise. It worked on rails 4.2.7.1.

### Actual behavior

Exception is raised
```
: SELECT "public".table2".* FROM "public"."table2" INNER JOIN "public"."table1" ON "public"."table1"."id" = "public"."table2"."table1_id" WHERE "table1"."active" = $1
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:606:in `exec_prepared'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:606:in `block in exec_cache'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:605:in `exec_cache'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:589:in `execute_and_clear'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/querying.rb:39:in `find_by_sql'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:699:in `exec_queries'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:580:in `load'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:260:in `records'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:683:in `inspect'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/fernando/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
### System configuration
**Rails version**:
5.0.0.1

**Ruby version**:
2.3.1p112

**Comment by fernandoluizao** [comment]
For the record, it's working correctly on rails master.

**Comment by maclover7** [comment]
Can you check and see if the issue is also solved on the `5-0-stable` branch?

**Comment by fernandoluizao** [comment]
Checked with 5-0-stable, it's working correctly.

**Comment by maclover7** [comment]
Cool. I'm going to close out this issue since it seems like it has already been solves on the master and 5-0-stable branches. The fix should be out in the next release of Rails, which I believe is 5.0.1. Thank you for opening up this issue! :)

**Comment by fernandoluizao** [comment]
Thanks! What is the expected date for the next release?

**Comment by maclover7** [comment]
@fernandoluizao Sorry, not sure exactly when 5.0.1 will be out, but it should be soon. :)
