### ISSUE TITLE
Rails Generate Error

### ISSUE THREAD

**Issue by QuantumLeaper** [rails/rails#26713]
Hello, I'm running into an error with rails generator (whether anything is appended after rails generate or not)
Anyhow, I cannot generate the necessary Shopify files utilizing:
`rails generate shopify_api --api_key=<KEY> --secret=<SECRET>`
After executing that I end up with:

```
/var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/response.rb:89:in `<class:Response>': undefined method `cache_control' for class `ActionDispatch::Response' (NameError)
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/response.rb:35:in `<module:ActionDispatch>'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/response.rb:6:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/live.rb:1:in `require'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/live.rb:1:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller.rb:4:in `require'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller.rb:4:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/railtie.rb:2:in `require'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/railtie.rb:2:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railtie.rb:9:in `require'
    from /var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railtie.rb:9:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/all.rb:14:in `require'
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/all.rb:14:in `block in <top (required)>'
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/all.rb:12:in `each'
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/all.rb:12:in `<top (required)>'
    from /root/Dev/backorderpro/config/application.rb:3:in `require'
    from /root/Dev/backorderpro/config/application.rb:3:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:82:in `require'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:82:in `preload'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
    from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

**Comment by utilum** [comment]
This looks like an issue for Shopify/shopify_api. Perhaps you'd benefit more from posting it there (and mentioning the versions you use: Ruby, Rails, and shopify_api).

**Comment by guilleiguaran** [comment]
Closing since this seems to be a third-party issue, if the error can be tracked back to rails please ping me and I'll re-open this again.

Thanks!!
