### ISSUE TITLE
generate guides throws exception

### ISSUE THREAD

**Issue by jihh** [rails/rails#26759]
### Steps to reproduce

``` bash
D:\Ruby>git clone  https://github.com/rails/rails
D:\Ruby>cd rails\guides
D:\Ruby\rails\guides>bundle install
D:\Ruby\rails\guides>bundle exec rake guides:generate:html
```
### Expected behavior

Generate guides.
### Actual behavior

``` bash
D:/Ruby/Ruby223-x64/bin/ruby.exe rails_guides.rb
Generating getting_started.md as getting_started.html
D:/Ruby/rails/activesupport/lib/active_support/core_ext/string/output_safety.rb:185:in `concat': incompatible character encodings: UTF-8 and GBK (ActionView::Template::Error)
        from D:/Ruby/rails/activesupport/lib/active_support/core_ext/string/output_safety.rb:185:in `concat'
        from D:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/actionview-4.2.7.1/lib/action_view/buffers.rb:12:in `<<'
        from D:/Ruby/rails/guides/source/layout.html.erb:91:in `_____uby_rails_guides_source_layout_html_erb___662758095_32236920'
        from D:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in `block in render'
        from D:/Ruby/rails/activesupport/lib/active_support/notifications.rb:166:in `instrument'
        from D:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:333:in `instrument'
        from D:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:143:in `render'
        from D:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
        from D:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
        from D:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
        from D:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:46:in `render_template'
        from D:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:27:in `render'
        from D:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/actionview-4.2.7.1/lib/action_view/helpers/rendering_helper.rb:32:in `render'
        from D:/Ruby/rails/guides/rails_guides/markdown.rb:164:in `render_page'
        from D:/Ruby/rails/guides/rails_guides/markdown.rb:25:in `render'
        from D:/Ruby/rails/guides/rails_guides/generator.rb:205:in `block in generate_guide'
        from D:/Ruby/rails/guides/rails_guides/generator.rb:195:in `open'
        from D:/Ruby/rails/guides/rails_guides/generator.rb:195:in `generate_guide'
        from D:/Ruby/rails/guides/rails_guides/generator.rb:144:in `block in generate_guides'
        from D:/Ruby/rails/guides/rails_guides/generator.rb:142:in `each'
        from D:/Ruby/rails/guides/rails_guides/generator.rb:142:in `generate_guides'
        from D:/Ruby/rails/guides/rails_guides/generator.rb:97:in `generate'
        from rails_guides.rb:63:in `<main>'
rake aborted!
Command failed with status (1): [D:/Ruby/Ruby223-x64/bin/ruby.exe rails_gui...]
D:/Ruby/rails/guides/Rakefile:11:in `block (3 levels) in <top (required)>'
Tasks: TOP => guides:generate:html
(See full trace by running task with --trace)
```
### System configuration

**Rails version**:  branch 4-2-stable 

**Ruby version**: ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]

**OS**: Windows 7 Pro sp1,  simp-chinese 

I modified `guides\rails_guides\generator.rb`, add one statement:

``` ruby
def generate_guides
  Encoding.default_external = Encoding.find('UTF-8')  # I add this
  guides_to_generate.each do |guide|
    output_file = output_file_for(guide)
    generate_guide(guide, output_file) if generate?(guide, output_file)
  end
end
```

After that, I generate the guides.

**Comment by rbcarlos** [comment]
I do not understand why is it working now. Ruby 2.0 and above uses UTF-8 as its default encoding, so my assumption then is that there was nothing changed.

**Comment by maclover7** [comment]
cc @fxn

**Comment by fxn** [comment]
The default external encoding depends on the locale (and you can override it anyway with `-E`).

@jihh I guess

    ruby -e 'puts Encoding.default_external'

prints "GBK" in your machine?

**Comment by fxn** [comment]
In principle this has been fixed by https://github.com/rails/rails/commit/37770bc8d13c5c7af024e66539c79f966718aec0, also backported to 5-0-stable, and 4-2-stable.

I have checked online that the `LANG` environment variable seems to override the locale on Windows, but have not tested this.

@jihh could you please try again and see if that patch works on Windows?

**Comment by fxn** [comment]
This is going to be optimistically closed. Please reopen if needed.
