### ISSUE TITLE
Incorrect behavior in ActiveRecord increment! method

### ISSUE THREAD

**Issue by ricardopacheco** [rails/rails#26795]
### Steps to reproduce

http://blog.locomotivellc.com/post/4120559953/counter-cache-polymorphism

### Expected behavior
```
puts user.comments_count => 3
```

### Actual behavior

```
NoMethodError: undefined method `-' for nil:NilClass
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:339:in `increment!'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/associations/belongs_to_association.rb:47:in `update_counters'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/associations/belongs_to_association.rb:39:in `increment_counters'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/counter_cache.rb:132:in `block in _create_record'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/counter_cache.rb:159:in `block in each_counter_cached_associations'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/counter_cache.rb:158:in `each'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/counter_cache.rb:158:in `each_counter_cached_associations'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/counter_cache.rb:130:in `_create_record'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/locking/optimistic.rb:75:in `_create_record'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/dirty.rb:123:in `_create_record'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/callbacks.rb:302:in `block in _create_record'
	from /usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'
	from /usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
	from /usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
	from /usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
	from /usr/local/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
... 15 levels...
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:324:in `save!'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/suppressor.rb:45:in `save!'
	from /usr/local/bundle/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:51:in `create!'
	from (irb):2
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**:
5.0.0.1
**Ruby version**:
2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

### Considerations
`change = public_send(attribute) - (attribute_was(attribute.to_s) || 0)` in `https://github.com/rails/rails/blob/master/activerecord/lib/active_record/persistence.rb#L339`

**Comment by ricardopacheco** [comment]
change counter_cache: true by counter_cache: modename_count it's works!
