### ISSUE TITLE
Testing fails if scaffolded model is named "App"

### ISSUE THREAD

**Issue by Genkilabs** [rails/rails#26835]
### Steps to reproduce
1. Roll a new rails 5 app ```rails new myapp``` and cd in ```cd myapp```
2. Generate a scaffold for a model named "App" ```rails g scaffold app```
3. Migrate to create the new model ```rake db:migrate```
4. Run tests ```rails test```

### Expected behavior
Default scaffold should pass with 7 assertions

### Actual behavior
All 7 assertions throw errors.
HOWEVER, if you change the variable '@app' to anything else, such as '@my_app', in the scaffolded test controller ```test/controllers/apps_controller_test.rb``` then it works great.

### Commentary
As it is very likely to build a Rails application to manage "apps" and App is likely a popular model name, I recommend keeping the variable used internally in tests as something which could not be generated from the model name, such as ```@_app```.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
I agree. Do you want to open a pull request?

**Comment by maclover7** [comment]
Can you submit a PR to make this change? Thanks!

**Comment by Genkilabs** [comment]
Sure. I've been using Rails for years but never contributed to core so I'd be happy to.
I'll read the how-to-contribute and take a crack at it.

**Comment by oswaldoferreira** [comment]
Hey @Genkilabs, are you working on this? Interested on taking this one.

**Comment by Genkilabs** [comment]
Sorry about that. I was derailed by... life. @oswaldoferreira if you want to take a crack at it, go for it!

The error on tests is of the nature:
```
NameError: undefined local variable or method `apps_url' for #<AppsControllerTest:0x007f9969470248>
    /Users/gingitsune/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/testing/assertions/routing.rb:172:in `method_missing'
    /Users/gingitsune/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/testing/integration.rb:546:in `method_missing'
    /Users/gingitsune/Development/deleteme/test/controllers/apps_controller_test.rb:20:in `block (2 levels) in <class:AppsControllerTest>'
    /Users/gingitsune/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/testing/assertions.rb:71:in `assert_difference'
    /Users/gingitsune/Development/deleteme/test/controllers/apps_controller_test.rb:19:in `block in <class:AppsControllerTest>'
```
If you work it from that direction, you will end up in ```/actionpack/lib/action_dispatch/testing/assertions/routing.rb``` and seeing the error on 172 (call to super) likely comes from a false on the check:
```if defined?(@controller) && @controller && defined?(@routes) && @routes && @routes.named_routes.route_defined?(selector)```
Here: https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/action_dispatch/testing/assertions/routing.rb#L169
However, I did not get into it enough to see if ```selector``` is bad or if the route is failing to be defined.

----
Alternatively, you could just dive in at the front and start with ```/actionpack/lib/action_dispatch/testing/integration.rb``` in ```module Behavior::ClassMethods``` where it includes the UrlFor helper and defines ```@@app```
https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/action_dispatch/testing/integration.rb#L757


I may tinker with this later, but as I am unfamiliar with Rails core code it took me a while just to get that much. Let me know how it goes if you do jump in.

**Comment by oswaldoferreira** [comment]
Thanks a lot for the overview @Genkilabs, I'll let you know if I get any further.

**Comment by aidistan** [comment]
The direct cause of this error is the wrong value of `integration_session.respond_to?(:apps_url)` in https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L396.

Tracing down the calling stack, we could find there is a read-only attribute `:app` [defined in Runner module](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L305) which is used [to create @integration_session](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L318) [through a super calling](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L642).

The `@app` we defined in the test has, unfortunately, overrided that attribute and [failed to include url helpers](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L331-L334).

---

I have no idea how to fix this issue since there are a large number of  ActionPack tests using the `@app` feature. Hope the info above would help anyone else.

**Comment by Genkilabs** [comment]
@aidistan That was roughly the conclusion I arrived at as well. I wondered if perhaps, the dependencies in ActionPack were mostly on ActionDispatch::IntegrationTest which holds its "app" in an ```@@app``` variable and defines its own accessor in ```Behavior::ClassMethods```...
So, perhaps the ```:app``` attribute, which seems local to ActionDispatch::Integration::Runner could be changed without it blowing up everything?

Unfortunately I don't understand the relationship between the two properly. This needs some real knowledge of the dependencies to untangle.

**Comment by kevincupp** [comment]
I've been looking into this as well. It's not only a problem with `@app`, it's with any instance variable included in `ActionDispatch::IntegrationTest`. For example, [these instance variables](http://guides.rubyonrails.org/testing.html#instance-variables-available) are documented as being available, and one could argue they may make reasonable resource names too, but you can't generate scaffolds based on those names without breaking tests that rely on those ivars (`ResponsesControllerTest#test_should_update_response` and `RequestsControllerTest#test_should_update_request` for example). And we cannot just take the ivars away without breaking existing tests either.

If there are always going to be instance variables available and relied on in the controller test scope, then there will always be the risk of accidentally overwriting one, but we may at least be able to make it so that we don't generate tests that automatically fail.

The way I see it, we can either:

* Rename colliding variables when generating the controller test file. This may have to be done by keeping a blacklist of taken instance variables in the generator and apply a prefix/suffix to variables with a colliding name when written from the scaffold generator, so that `@app = apps(:one)` becomes `@app_model = apps(:one)` for example. This doesn't seem like a good idea for maintenance reasons.
* Or, always rename these variables no matter the name. Append `_model` or something. It seems to go against convention from what I've seen, but it would greatly reduce the likelihood of a collision and we can still keep using the ivar pattern currently in use.
* Change the scaffold template not to use the ivar pattern. This isn't too great either since it goes against documented examples for writing these controllers, but there wouldn't be much practical difference. Instead of assigning the ivar in `setup` and referencing it in the tests, we could just call `apps(:one)` from the test. Or, any number of other options of refactoring the test file to achieve the same thing.

The challenge is maintaining backwards compatibility while still maintaining a recommended style.
The last two options I outlined above seem the most viable, but nothing is that great. Given this re-framing of the issue, I'm curious to hear what others think.

**Comment by Genkilabs** [comment]
@kevincupp nice write up.

Opinion -> I feel there is a difference between @app and @controller/request/response though... not just because there is documentation and support for the latter, but also because it feels like @app was put in as lazy shorthand for @application (ie. a Rails::Application instance). It is unlikely anyone would name a resource "Application", but an "App" is not a concept in the Rails universe, like Controller and Request are.

That said, this is already beyond me, so I'm just pitching in as the OP and long time user, not a real contributor to core Rails.  So a big thank you to everyone with the talent and ability to do so ^_^

**Comment by aidistan** [comment]
Agree with @Genkilabs. There is a huge difference between `@app` and other instance variables (`@request`, `@response`, etc...).

Rails developers regard `request` and `response` as common concepts  and won't create any model named as these reserved words. However, `App` is not a universal concept in Rails but a common needed model in any web application served as a platform.

Thus, I believe a better and easier solution to this issue is to roughly replace `@app` by `@application` under `ActionDispatch::IntegrationTest` and its included modules.

**Comment by kevincupp** [comment]
Thanks, guys. I'm fairly new to Rails, so I was coming at it from the mind that Rails shouldn't generate code that breaks things when you execute it. I'd still say that's the ideal, but if those are words folks generally stay away from, we can table it for now.

If `@app` is all we need fixed, it looks like this should do it:


``` diff
diff --git a/actionpack/lib/action_dispatch/testing/integration.rb b/actionpack/lib/action_dispatch/testing/integration.rb
index 021ffec862..f38ac6b6b9 100644
--- a/actionpack/lib/action_dispatch/testing/integration.rb
+++ b/actionpack/lib/action_dispatch/testing/integration.rb
@@ -302,7 +302,7 @@ module Runner
 
       APP_SESSIONS = {}
 
-      attr_reader :app
+      attr_reader :application
 
       def initialize(*args, &blk)
         super(*args, &blk)
@@ -310,7 +310,7 @@ def initialize(*args, &blk)
       end
 
       def before_setup # :nodoc:
-        @app = nil
+        @application = nil
         super
       end
 
@@ -639,7 +639,7 @@ def register_encoder(*args)
       end
 
       def app
-        super || self.class.app
+        application || self.class.app
       end
```

I'm running tests on this now, but if the above makes sense, I could open a PR. I'd guess it likely wouldn't go out until at least 5.1.0 since we're technically changing an API.

**Comment by renyijiu** [comment]
Hello，i meet the issue in my application today. I create a new rails app, the issue still can be reproduced following the steps. So i reply under the issue. Now i just change my code to avoid the issue.

Rails Version: 5.2.0
Ruby Version: 2.5.1

**Comment by Genkilabs** [comment]
Confirmed, this is still an issue in 2.5.1

The idea of "building an app" is ubiquitous, and having a Rails application which manages them is something that many new rails developers may try. I see this aliasing of @application to @app as an unnecessary hurdle rather than a helpful convention.

@kevincupp did you end up opening a PR for this? If not, and people still care, I could do it...
Anyone else feel this way still?

**Comment by kevincupp** [comment]
@Genkilabs I didn't. I think once I made the changes above, a boat load of tests needed updating, which I started doing but feel like I hit some sort of roadblock in the process and ended up putting it aside. I was very new to Rails at the time so I might have hit some uncertainty about something.

**Comment by renyijiu** [comment]
@Genkilabs I think we can reopen the issue. Let other people know this issue still exists so they can avoid the same situation before the issue is fixed.
