### ISSUE TITLE
Overwrite controller namespace in route definition

### ISSUE THREAD

**Issue by karimmortabit** [rails/rails#26893]
### Steps to reproduce

Here is a an Executable Test Case :
https://gist.github.com/karimmortabit/8f465120a41359998f349706e1c9799e
### Expected behavior / Actual behavior

See https://github.com/rails/rails/issues/12777

``` ruby
namespace :v2 do
  # This was added closing the issue
  resources :places, controller: '/api/v1/places'
  # But this still doesn't work
  resources :places, scope: 'api', module: 'v1'
end
```
### Error

```
I, [2016-10-26T01:12:08.452605 #24409]  INFO -- : Started GET "/api/v2/places" for 127.0.0.1 at 2016-10-26 01:12:08 +0200
F, [2016-10-26T01:12:08.456023 #24409] FATAL -- :
F, [2016-10-26T01:12:08.456079 #24409] FATAL -- : ActionController::RoutingError (uninitialized constant Api::V2):
F, [2016-10-26T01:12:08.456116 #24409] FATAL -- :
F, [2016-10-26T01:12:08.456162 #24409] FATAL -- : activesupport (5.0.0) lib/active_support/inflector/methods.rb:270:in `const_get'
F, [2016-10-26T01:12:08.456199 #24409] FATAL -- : activesupport (5.0.0) lib/active_support/inflector/methods.rb:270:in `block in constantize'
F, [2016-10-26T01:12:08.456236 #24409] FATAL -- : activesupport (5.0.0) lib/active_support/inflector/methods.rb:266:in `each'
F, [2016-10-26T01:12:08.456273 #24409] FATAL -- : activesupport (5.0.0) lib/active_support/inflector/methods.rb:266:in `inject'
F, [2016-10-26T01:12:08.456310 #24409] FATAL -- : activesupport (5.0.0) lib/active_support/inflector/methods.rb:266:in `constantize'
F, [2016-10-26T01:12:08.456345 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/http/request.rb:93:in `controller_class'
F, [2016-10-26T01:12:08.456382 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:44:in `controller'
F, [2016-10-26T01:12:08.456418 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:30:in `serve'
F, [2016-10-26T01:12:08.456455 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/journey/router.rb:39:in `block in serve'
F, [2016-10-26T01:12:08.456491 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/journey/router.rb:26:in `each'
F, [2016-10-26T01:12:08.456528 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/journey/router.rb:26:in `serve'
F, [2016-10-26T01:12:08.456567 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:725:in `call'
F, [2016-10-26T01:12:08.456605 #24409] FATAL -- : rack (2.0.1) lib/rack/etag.rb:25:in `call'
F, [2016-10-26T01:12:08.456640 #24409] FATAL -- : rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
F, [2016-10-26T01:12:08.456677 #24409] FATAL -- : rack (2.0.1) lib/rack/head.rb:12:in `call'
F, [2016-10-26T01:12:08.456712 #24409] FATAL -- : rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
F, [2016-10-26T01:12:08.456747 #24409] FATAL -- : rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
F, [2016-10-26T01:12:08.456783 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:613:in `call'
F, [2016-10-26T01:12:08.456819 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
F, [2016-10-26T01:12:08.456856 #24409] FATAL -- : activesupport (5.0.0) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
F, [2016-10-26T01:12:08.456893 #24409] FATAL -- : activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
F, [2016-10-26T01:12:08.456931 #24409] FATAL -- : activesupport (5.0.0) lib/active_support/callbacks.rb:90:in `run_callbacks'
F, [2016-10-26T01:12:08.456969 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
F, [2016-10-26T01:12:08.457004 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
F, [2016-10-26T01:12:08.457042 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
F, [2016-10-26T01:12:08.457080 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
F, [2016-10-26T01:12:08.457116 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
F, [2016-10-26T01:12:08.457152 #24409] FATAL -- : railties (5.0.0) lib/rails/rack/logger.rb:36:in `call_app'
F, [2016-10-26T01:12:08.457187 #24409] FATAL -- : railties (5.0.0) lib/rails/rack/logger.rb:26:in `call'
F, [2016-10-26T01:12:08.457222 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/middleware/request_id.rb:24:in `call'
F, [2016-10-26T01:12:08.457259 #24409] FATAL -- : rack (2.0.1) lib/rack/method_override.rb:22:in `call'
F, [2016-10-26T01:12:08.457295 #24409] FATAL -- : rack (2.0.1) lib/rack/runtime.rb:22:in `call'
F, [2016-10-26T01:12:08.457332 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
F, [2016-10-26T01:12:08.457368 #24409] FATAL -- : actionpack (5.0.0) lib/action_dispatch/middleware/static.rb:136:in `call'
F, [2016-10-26T01:12:08.457404 #24409] FATAL -- : rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
F, [2016-10-26T01:12:08.457439 #24409] FATAL -- : railties (5.0.0) lib/rails/engine.rb:522:in `call'
F, [2016-10-26T01:12:08.457474 #24409] FATAL -- : rack-test (0.6.3) lib/rack/mock_session.rb:30:in `request'
F, [2016-10-26T01:12:08.457509 #24409] FATAL -- : rack-test (0.6.3) lib/rack/test.rb:244:in `process_request'
F, [2016-10-26T01:12:08.457543 #24409] FATAL -- : rack-test (0.6.3) lib/rack/test.rb:58:in `get'
F, [2016-10-26T01:12:08.457578 #24409] FATAL -- : /Users/karim/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/forwardable.rb:189:in `get'
F, [2016-10-26T01:12:08.457614 #24409] FATAL -- : action_controller_gem.rb:63:in `test_returns_success'
F, [2016-10-26T01:12:08.457649 #24409] FATAL -- : minitest (5.9.1) lib/minitest/test.rb:107:in `block (3 levels) in run'
F, [2016-10-26T01:12:08.457686 #24409] FATAL -- : minitest (5.9.1) lib/minitest/test.rb:204:in `capture_exceptions'
F, [2016-10-26T01:12:08.457721 #24409] FATAL -- : minitest (5.9.1) lib/minitest/test.rb:104:in `block (2 levels) in run'
F, [2016-10-26T01:12:08.457757 #24409] FATAL -- : minitest (5.9.1) lib/minitest/test.rb:255:in `time_it'
F, [2016-10-26T01:12:08.457791 #24409] FATAL -- : minitest (5.9.1) lib/minitest/test.rb:103:in `block in run'
F, [2016-10-26T01:12:08.457827 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:348:in `on_signal'
F, [2016-10-26T01:12:08.457863 #24409] FATAL -- : minitest (5.9.1) lib/minitest/test.rb:275:in `with_info_handler'
F, [2016-10-26T01:12:08.457898 #24409] FATAL -- : minitest (5.9.1) lib/minitest/test.rb:102:in `run'
F, [2016-10-26T01:12:08.457933 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:799:in `run_one_method'
F, [2016-10-26T01:12:08.457967 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:322:in `run_one_method'
F, [2016-10-26T01:12:08.458003 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:310:in `block (2 levels) in run'
F, [2016-10-26T01:12:08.458037 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:309:in `each'
F, [2016-10-26T01:12:08.458071 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:309:in `block in run'
F, [2016-10-26T01:12:08.458106 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:348:in `on_signal'
F, [2016-10-26T01:12:08.458141 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:335:in `with_info_handler'
F, [2016-10-26T01:12:08.458175 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:308:in `run'
F, [2016-10-26T01:12:08.458212 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:158:in `block in __run'
F, [2016-10-26T01:12:08.458248 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:158:in `map'
F, [2016-10-26T01:12:08.458283 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:158:in `__run'
F, [2016-10-26T01:12:08.458317 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:135:in `run'
F, [2016-10-26T01:12:08.458352 #24409] FATAL -- : minitest (5.9.1) lib/minitest.rb:62:in `block in autorun'
F
```
### System configuration

**Rails version**:
5.0.0
**Ruby version**:
2.3.1p112

**Comment by pixeltrix** [comment]
@karimmortabit to be clear - the problem is with `:module` and not `:controller`?

**Comment by karimmortabit** [comment]
@pixeltrix Yes exactly.
