### ISSUE TITLE
All rails commands fail on clean install

### ISSUE THREAD

**Issue by pcragone** [rails/rails#26918]
### Steps to reproduce
`gem install rails`
`rails new myproject`
`rails generate scaffold person name:string`

### Expected behavior
Expected to not crash

### Actual behavior
Crashes with "incompatible library version"

### System configuration
**Rails version**:
5.0.0.1

**Ruby version**:
2.3.1

**Comment by rafaelfranca** [comment]
This is because you are not using bundle to execute the command. Use bin/rails to execute the commands inside the application

**Comment by pcragone** [comment]
Ok... actually, I was. I tried using bin/rails, I tried using bundle exec. I tried using spring rails.  None of them worked.

**Comment by rafaelfranca** [comment]
I see.  So you need to give us more information about the error because what you said seems like a problem that bundle would fix. What is the stack trace and the full error message?

**Comment by pcragone** [comment]
Here's the stack trace:
```
/Users/pragone/.rvm/gems/ruby-2.3.1/gems/sqlite3-1.3.12/lib/sqlite3.rb:6:in `require': incompatible library version - /Users/pragone/.rvm/gems/ruby-2.3.1/gems/sqlite3-1.3.12/lib/sqlite3/sqlite3_native.b
undle (fatal)
        from /Users/pragone/.rvm/gems/ruby-2.3.1/gems/sqlite3-1.3.12/lib/sqlite3.rb:6:in `rescue in <top (required)>'
        from /Users/pragone/.rvm/gems/ruby-2.3.1/gems/sqlite3-1.3.12/lib/sqlite3.rb:2:in `<top (required)>'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.0/lib/bundler/runtime.rb:91:in `require'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.0/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.0/lib/bundler/runtime.rb:86:in `each'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.0/lib/bundler/runtime.rb:86:in `block in require'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.0/lib/bundler/runtime.rb:75:in `each'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.0/lib/bundler/runtime.rb:75:in `require'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.0/lib/bundler.rb:106:in `require'
        from /Users/pragone/Dropbox/projects/testproject/config/application.rb:7:in `<top (required)>'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@everyday/gems/spring-2.0.0/lib/spring/application.rb:82:in `require'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@everyday/gems/spring-2.0.0/lib/spring/application.rb:82:in `preload'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@everyday/gems/spring-2.0.0/lib/spring/application.rb:143:in `serve'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@everyday/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@everyday/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@everyday/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
        from /Users/pragone/.rvm/gems/ruby-2.3.1@everyday/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /Users/pragone/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/pragone/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

**Comment by rafaelfranca** [comment]
It is an incompatibility between the sqlite3 gem and the library in your system. Make sure you have the correct version of sqlite3.
