### ISSUE TITLE
actionpack (5.0.0.1) lib/action_dispatch/request/session.rb:217:in `load!'

### ISSUE THREAD

**Issue by paz-choe** [rails/rails#26914]
I try to upgrade rails 4.2.4 to 5.0.0.1
after bundle rails update, just start rails server and connect localhost:3000.

```
[I 48369 2016-10-27T22:14:53.20] [current_user:Anonym] Started GET "/" for ::1 at 2016-10-27 22:14:53 +0900
[D 48369 2016-10-27T22:14:53.32] [current_user:Anonym]   ActiveRecord::SchemaMigration Load (17.1ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
[F 48369 2016-10-27T22:14:53.38] [current_user:Anonym] 
NoMethodError - undefined method `[]=' for nil:NilClass:
  actionpack (5.0.0.1) lib/action_dispatch/request/session.rb:217:in `load!'
  actionpack (5.0.0.1) lib/action_dispatch/request/session.rb:212:in `load_for_write!'
  actionpack (5.0.0.1) lib/action_dispatch/request/session.rb:197:in `merge!'
  actionpack (5.0.0.1) lib/action_dispatch/request/session.rb:17:in `create'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/session/abstract_store.rb:82:in `prepare_session'
  rack (2.0.1) lib/rack/session/abstract/id.rb:221:in `context'
  rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  activerecord (5.0.0.1) lib/active_record/migration.rb:552:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
  activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
  railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.1) lib/rack/method_override.rb:22:in `call'
  rack (2.0.1) lib/rack/runtime.rb:22:in `call'
  activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
  sentry-raven (2.1.2) lib/raven/integrations/rack.rb:50:in `call'
  railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
  rack (2.0.1) lib/rack/handler/webrick.rb:86:in `service'
  /Users/me/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/me/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/me/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

Does anyone know the solution?

### System configuration
**Rails version**:
5.0.0.1

**Ruby version**:
2.2.3p173

**Comment by maclover7** [comment]
Can you please provide a sample application, or create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by paz-choe** [comment]
@maclover7 
It's my customized middleware issue about session_store. oTL
I didn't condier different middleware-stack between rails 4 and rails 5.

**Comment by Nowaker** [comment]
@paz-raon What was the solution? I just bumped from Rails 4 to 5, and am encountering the same problem - error on `lib/action_dispatch/request/session.rb:217`. It's also reported on SO and there are no answers. https://stackoverflow.com/questions/48069131/undefined-method-for-nilnilclass-lib-action-dispatch-request-session-rb2
