### ISSUE TITLE
NotImplementedError: #views is not implemented mysql2

### ISSUE THREAD

**Issue by leonardoprg** [rails/rails#26945]
### Steps to reproduce

Hello Guys,

I'm using gem `mysql2`,
and when using it on my database, it's raising: `NotImplementedError: #views is not implemented`
when I tried to call any query (User.all) for example.

I opened a issue on `mysql2` gem and the guys told me that it's a rails issue.

https://github.com/brianmario/mysql2/issues/804#issuecomment-257406152

### Expected behavior
Works as expected

### Actual behavior
NotImplementedError: #views is not implemented

### System configuration
**Rails version**:
5.0.0.1
**Ruby version**:
2.3.1p112

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by leonardoprg** [comment]
yes, I will try to replicate It on a sample app,

the problem is, when using a older dump of the database it works, 
but when tried to use connect on production (or get production dump and import locally)
it stops working.

ps: database doesn't uses view.

**Comment by rafaelfranca** [comment]
Yeah, and also that doesn't happen if the adapter is mysql since we do implement that method, so I'm guessing it is something in your configuration.

**Comment by leonardoprg** [comment]
ok, Will try to reproduce it on an sample app, 
and investigate more about the database,

Thanks.

**Comment by cymcsg** [comment]
Is there any process on this problem? I also use  Rails 5.0.0.1 and ruby 2.3.1p112 and I get the same error.

The situation which I have been occured is I want to use rails with existing mysql database . When I run ``rake db:schema:dump``,  I also got the error ``NotImplementedError: #views is not implemented``.

**Comment by utilum** [comment]
@cymcsg can you please provide a sample application that reproduces the error?

**Comment by cymcsg** [comment]
I just use ``rails new`` to create a new sample project and edit two files below:

Gemfile:

```code 
gem 'mysql2'
gem 'activerecord-mysql2-adapter'
```

and database.yml:
```yaml
default: &default
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: test
    pool: 5
    timeout: 5000
    username: root
    password:
    socket: /tmp/mysql.sock

development:
   <<: *default
```


I run ``bundle install `` and ``rake db:schema:dump`` after that and get the error message.
The full message is : 

```code 
➜  activerecord rake db:schema:dump --trace
** Invoke db:schema:dump (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:schema:dump
rake aborted!
NotImplementedError: #views is not implemented
/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:60:in `views'
/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:34:in `data_sources'
/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/schema_dumper.rb:88:in `tables'
/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/schema_dumper.rb:37:in `dump'
/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/schema_dumper.rb:21:in `dump'
/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:253:in `block (4 levels) in <top (required)>'
/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:252:in `open'
/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:252:in `block (3 levels) in <top (required)>'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/.rvm/gems/ruby-2.3.1/bin/rake:22:in `load'
/.rvm/gems/ruby-2.3.1/bin/rake:22:in `<main>'
Tasks: TOP => db:schema:dump

```

Thank you very much. @utilum

**Comment by kamipo** [comment]
Looks like that [activerecord-mysql2-adapter](https://rubygems.org/gems/activerecord-mysql2-adapter) does not implement `#view`.
Removing `gem 'activerecord-mysql2-adapter'` line will fix this issue.

**Comment by utilum** [comment]
@cymcsg, what prompted you to add `gem 'activerecord-mysql2-adapter'` ?

```rails new issue_26495 --database=mysql
cd issue_26945/
rails db:schema:dump  # This is how Rails 5 expects you to launch the task.
rails aborted!
ActiveRecord::NoDatabaseError: Unknown database 'issue_26945_development'
/home/oz/code/issue_26945/bin/rails:9:in `require'
/home/oz/code/issue_26945/bin/rails:9:in `<top (required)>'
/home/oz/code/issue_26945/bin/spring:14:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Mysql2::Error: Unknown database 'issue_26945_development'
/home/oz/code/issue_26945/bin/rails:9:in `require'
/home/oz/code/issue_26945/bin/rails:9:in `<top (required)>'
/home/oz/code/issue_26945/bin/spring:14:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)
```

But it's still pretty much the same with rake:

```rake db:schema:dump
rake aborted!
ActiveRecord::NoDatabaseError: Unknown database 'issue_26945_development'

Mysql2::Error: Unknown database 'issue_26945_development'

Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)```

**Comment by cymcsg** [comment]
@kamipo @utilum  Great thanks! I make a mistake on this problem. I have fixed it by removing ``gem 'activerecord-mysql2-adapter'`` .

Thanks for the tips about ``rake`` and ``rails``.
