### ISSUE TITLE
`bin/rails restart` is broken out of the box

### ISSUE THREAD

**Issue by vandrijevik** [rails/rails#27127]
### Steps to reproduce

1. Run `rails new wat && cd wat && bin/setup && bin/rails migrate && bin/setup` to set up a new Rails app. (For the sake of completeness: running `bin/setup` fails the first time when preparing the database, so it is necessary to migrate to create an empty schema.rb, and then to run `bin/setup` again so it completes successfully. The steps below also work if you omit the migration and second run of `bin/setup`).
1. In one terminal window, run `bin/rails server` to start a Rails server.
1. In another terminal window, run `bin/rails restart` to restart the server.

### Expected behavior

The server is successfully restarted.

### Actual behavior

The server crashes with the following message:

```
* Restarting...
=> Booting Puma
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.6.0 (ruby 2.3.2-p217), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Inherited tcp://localhost:3000
Exiting
/Users/vladimir/code/wat/.bundle/gems/gems/puma-3.6.0/lib/puma/binder.rb:284:in `for_fd': Bad file descriptor - not a socket file descriptor (Errno::EBADF)
  from /Users/vladimir/code/wat/.bundle/gems/gems/puma-3.6.0/lib/puma/binder.rb:284:in `inherit_tcp_listener'
  from /Users/vladimir/code/wat/.bundle/gems/gems/puma-3.6.0/lib/puma/binder.rb:91:in `block in parse'
  from /Users/vladimir/code/wat/.bundle/gems/gems/puma-3.6.0/lib/puma/binder.rb:85:in `each'
  from /Users/vladimir/code/wat/.bundle/gems/gems/puma-3.6.0/lib/puma/binder.rb:85:in `parse'
  from /Users/vladimir/code/wat/.bundle/gems/gems/puma-3.6.0/lib/puma/runner.rb:133:in `load_and_bind'
  from /Users/vladimir/code/wat/.bundle/gems/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
  from /Users/vladimir/code/wat/.bundle/gems/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
  from /Users/vladimir/code/wat/.bundle/gems/gems/puma-3.6.0/lib/rack/handler/puma.rb:51:in `run'
  from /Users/vladimir/code/wat/.bundle/gems/gems/rack-2.0.1/lib/rack/server.rb:296:in `start'
  from /Users/vladimir/code/wat/.bundle/gems/gems/railties-5.0.0.1/lib/rails/commands/server.rb:79:in `start'
  from /Users/vladimir/code/wat/.bundle/gems/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
  from /Users/vladimir/code/wat/.bundle/gems/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
  from /Users/vladimir/code/wat/.bundle/gems/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
  from /Users/vladimir/code/wat/.bundle/gems/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
  from /Users/vladimir/code/wat/.bundle/gems/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
```

### System configuration

**Rails version**: 5.0.0.1
**Ruby version**: ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]

### Notes

As a result of this, the generated `bin/setup` and `bin/update` are also broken when they are run while a server is running (since they run `bin/rails restart` as their last step).

**Comment by prathamesh-sonpatki** [comment]
This issue is with Puma and is being tracked here: https://github.com/puma/puma/pull/1120

Thanks!
