### ISSUE TITLE
Saving has_many through raises exception in rails 4, but works in 3.2.22.

### ISSUE THREAD

**Issue by mrThe** [rails/rails#27156]
Hello. I'm upgrading rails on my project and has many errors like this. 
Is there some workaround or fix?

Related issue: https://github.com/rails/rails/issues/16085

### Steps to reproduce

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '4.2.7.1' # works in 3.2.22
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "recipients_lists", force: :cascade do |t|
    t.string   "name",       limit: 255, null: false
  end

  create_table "recipients_lists_recipients" do |t|
    t.references :recipients_list, null: false
    t.references :recipient,       null: false
  end

  create_table "recipients", force: :cascade do |t|
    t.string   "name",       limit: 255
  end
end

class RecipientsList < ActiveRecord::Base
  has_many :recipients, through: :recipients_lists_recipients
  has_many :recipients_lists_recipients
end

class RecipientsListsRecipient < ActiveRecord::Base
  belongs_to :recipient
  belongs_to :recipients_list
end

class Recipient < ActiveRecord::Base
  has_many   :recipients_lists,            through: :recipients_lists_recipients
  has_many   :recipients_lists_recipients
end

class BugTest < Minitest::Test
  def test_creation
    Recipient.create!(name: 'rec')

    rl = RecipientsList.new(name: 'Admins') # don't raise if i use `create` instead of `new`, but i can't because of some validations
    rl.recipients << Recipient.last

    rl.save! # raises error

    assert rl.reload.recipients.first == Recipient.last
  end
end
```

### Expected behavior
Should create object with relations

### Actual behavior
Raises error:
```
BugTest#test_creation:
ActiveRecord::StatementInvalid: SQLite3::ConstraintException: NOT NULL constraint failed: recipients_lists_recipients.recipients_list_id: INSERT INTO "recipients_lists_recipients" ("recipient_id") VALUES (?)
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.12/lib/sqlite3/statement.rb:108:in `step'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.12/lib/sqlite3/statement.rb:108:in `block in each'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.12/lib/sqlite3/statement.rb:107:in `loop'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.12/lib/sqlite3/statement.rb:107:in `each'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:302:in `to_a'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:302:in `block in exec_query'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:281:in `exec_query'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:76:in `exec_insert'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:64:in `insert'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:524:in `_create_record'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/counter_cache.rb:139:in `_create_record'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/locking/optimistic.rb:75:in `_create_record'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:133:in `_create_record'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `block in _create_record'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `_create_record'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/timestamp.rb:57:in `_create_record'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:504:in `create_or_update'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `create_or_update'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:142:in `save!'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:43:in `save!'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `block in save!'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `save!'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/associations/has_many_through_association.rb:117:in `save_through_record'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/associations/has_many_through_association.rb:66:in `insert_record'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/autosave_association.rb:373:in `block in save_collection_association'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/autosave_association.rb:364:in `each'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/autosave_association.rb:364:in `save_collection_association'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/autosave_association.rb:184:in `block in add_autosave_association_callbacks'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/autosave_association.rb:157:in `instance_eval'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/autosave_association.rb:157:in `block in define_non_cyclic_method'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:228:in `call'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `call'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `block in call'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `each'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `call'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `_create_record'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/timestamp.rb:57:in `_create_record'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:504:in `create_or_update'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `create_or_update'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:142:in `save!'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:43:in `save!'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `block in save!'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
    /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `save!'

```

### System configuration
**Rails version**: 4.2.7.1

**Ruby version**: 2.1.5

**Comment by matrix9180** [comment]
See #26834. If you move the has_many through: :foo line below the has_many :foo, things work as expected. Doesn't fix the bug (which arguably should be a friendlier error message when you hm:t before the through-association is defined.)

**Comment by mrThe** [comment]
Thanks @matrix9180 ! Now it works as expected.
