### ISSUE TITLE
`rails server` rejects options

### ISSUE THREAD

**Issue by georgeclaghorn** [rails/rails#27155]
In a new app using edge Rails, `rails server` crashes when documented options (e.g. `--binding` and `--port`) are provided:

```
~/Code$ rails new sandbox --edge
~/Code$ cd sandbox
~/Code/sandbox$ rails server -b 0.0.0.0
/Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:483:in `handle_argument_error': ERROR: "rails server" was called with arguments ["-b", "0.0.0.0"] (Thor::InvocationError)
Usage: "bin/rails server [options]"
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:34:in `rescue in run'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:21:in `run'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-49aa974ec8b1/railties/lib/rails/command/base.rb:61:in `perform'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-49aa974ec8b1/railties/lib/rails/command.rb:34:in `invoke'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-49aa974ec8b1/railties/lib/rails/commands.rb:16:in `<top (required)>'
	from /Users/gclaghorn/code/sandbox/bin/rails:9:in `require'
	from /Users/gclaghorn/code/sandbox/bin/rails:9:in `<top (required)>'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/gclaghorn/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/gclaghorn/code/sandbox/bin/spring:14:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

No crash occurs when options are not provided:

```
~/Code/sandbox$ rails s
=> Booting Puma
=> Rails 5.1.0.alpha application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.6.2 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
```

This appears to have started with https://github.com/rails/rails/commit/6813edc7d926965e5644cd8befaf229a35b9d8ca.

/cc @kaspth

**Comment by utilum** [comment]
Same here:

```
[oz@localhost rapp]$ rails s -p 3001
/home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:483:in `handle_argument_error': ERROR: "rails server" was called with arguments ["-p", "3001"] (Thor::InvocationError)
Usage: "bin/rails server [options]"
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:34:in `rescue in run'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:21:in `run'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/oz/code/rails/railties/lib/rails/command/base.rb:61:in `perform'
	from /home/oz/code/rails/railties/lib/rails/command.rb:34:in `invoke'
	from /home/oz/code/rails/railties/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
[oz@localhost rapp]$ rails server --port 3001
/home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:483:in `handle_argument_error': ERROR: "rails server" was called with arguments ["--port", "3001"] (Thor::InvocationError)
Usage: "bin/rails server [options]"
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:34:in `rescue in run'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:21:in `run'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/oz/code/rails/railties/lib/rails/command/base.rb:61:in `perform'
	from /home/oz/code/rails/railties/lib/rails/command.rb:34:in `invoke'
	from /home/oz/code/rails/railties/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
[oz@localhost rapp]$ rails server -b 0.0.0.0
/home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:483:in `handle_argument_error': ERROR: "rails server" was called with arguments ["-b", "0.0.0.0"] (Thor::InvocationError)
Usage: "bin/rails server [options]"
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:34:in `rescue in run'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:21:in `run'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/oz/code/rails/railties/lib/rails/command/base.rb:61:in `perform'
	from /home/oz/code/rails/railties/lib/rails/command.rb:34:in `invoke'
	from /home/oz/code/rails/railties/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
And it runs fine when using b724dbbb8b337d84a3ca8380c9dd75d79a44badf, the commit preceding the one mentioned.

**Comment by kaspth** [comment]
Thanks! We're aware of it and fixing it here: https://github.com/rails/rails/pull/26977
