### ISSUE TITLE
undefined 'method' helper for ActiveAdmin::Devise::SessionsController:Class

### ISSUE THREAD

**Issue by Awatatah** [rails/rails#27253]
Hello I am receiving error

``` ../.rvm/gems/ruby-2.3.0/bundler/gems/activeadmin-a932d56b156e/lib/active_admin/devise.rb:31:in `block in <module:Controller>': undefined method `helper' for ActiveAdmin::Devise::SessionsController:Class (NoMethodError)```

### Steps to reproduce

On a new rails 5 api, I added the following gems:

> gem 'devise'
> gem 'activeadmin', github: 'activeadmin'
> gem 'inherited_resources', github: 'activeadmin/inherited_resources'

I also added to `app/controllers/application_controller.rb`

>include ActionView::Layouts

### System configuration
Gem file:

``` source 'https://rubygems.org'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 3.0'

gem 'devise'
gem 'activeadmin', github: 'activeadmin'
gem 'inherited_resources', github: 'activeadmin/inherited_resources'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Rails version**:
`Rails 5.0.0.1`

**Ruby version**:
`ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]`
**Full output**
```
$ rails g active_admin:install
Running via Spring preloader in process 33185
      invoke  devise
    generate    devise:install
      create    config/initializers/devise.rb
      create    config/locales/devise.en.yml
  ===============================================================================

Some setup you must do manually if you haven't yet:

  1. Ensure you have defined default url options in your environments files. Here
     is an example of default_url_options appropriate for a development environment
     in config/environments/development.rb:

       config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

     In production, :host should be set to the actual host of your application.

  2. Ensure you have defined root_url to *something* in your config/routes.rb.
     For example:

       root to: "home#index"

  3. Ensure you have flash messages in app/views/layouts/application.html.erb.
     For example:

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  4. You can copy Devise views (for customization) to your app by running:

       rails g devise:views

===============================================================================
      invoke    active_record
      create      db/migrate/20161202173028_devise_create_admin_users.rb
      create      app/models/admin_user.rb
      invoke      test_unit
      create        test/models/admin_user_test.rb
      create        test/fixtures/admin_users.yml
      insert      app/models/admin_user.rb
       route    devise_for :admin_users
        gsub    app/models/admin_user.rb
        gsub    config/routes.rb
      append    db/seeds.rb
      create  config/initializers/active_admin.rb
      create  app/admin
      create  app/admin/dashboard.rb
      create  app/admin/admin_user.rb
      insert  config/routes.rb
    generate  active_admin:assets
/../../.rvm/gems/ruby-2.3.0/bundler/gems/activeadmin-a932d56b156e/lib/active_admin/devise.rb:31:in `block in <module:Controller>': undefined method `helper' for ActiveAdmin::Devise::SessionsController:Class (NoMethodError)
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `class_eval'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `append_features'
	from /../../.rvm/gems/ruby-2.3.0/bundler/gems/activeadmin-a932d56b156e/lib/active_admin/devise.rb:54:in `include'
	from /../../.rvm/gems/ruby-2.3.0/bundler/gems/activeadmin-a932d56b156e/lib/active_admin/devise.rb:54:in `<class:SessionsController>'
	from /../../.rvm/gems/ruby-2.3.0/bundler/gems/activeadmin-a932d56b156e/lib/active_admin/devise.rb:53:in `<module:Devise>'
	from /../../.rvm/gems/ruby-2.3.0/bundler/gems/activeadmin-a932d56b156e/lib/active_admin/devise.rb:6:in `<module:ActiveAdmin>'
	from /../../.rvm/gems/ruby-2.3.0/bundler/gems/activeadmin-a932d56b156e/lib/active_admin/devise.rb:5:in `<top (required)>'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /../../Working/Working Set/abq_cc_api/config/routes.rb:2:in `block in <top (required)>'
	from /../../.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
	from /../../.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
	from /../../.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:371:in `draw'
	from /../../Working/Working Set/abq_cc_api/config/routes.rb:1:in `<top (required)>'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `each'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/file_update_checker.rb:77:in `execute'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /../../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /../../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /../../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /../../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /../../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /../../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /../../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /../../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /../../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /../../.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
	from /../../Working/Working Set/abq_cc_api/config/environment.rb:5:in `<top (required)>'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /../../.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /../../.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:92:in `preload'
	from /../../.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:143:in `serve'
	from /../../.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
	from /../../.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
	from /../../.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
	from /../../.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /../../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /../../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
      create  db/migrate/20161202173032_create_active_admin_comments.rb```

**Comment by Awatatah** [comment]
I was able to resolve by changing 
`ApplicationController < ActionController::API` 
to
 `ApplicationController < ActionController::Base`

and by adding to `config/application.rb`
>config.middleware.use ActionDispatch::Flash
>config.middleware.use Rack::MethodOverride
>config.middleware.use ActionDispatch::Cookies
```
module MyApi
    class Application < Rails::Applcation
        config.middleware.use ActionDispatch::Flash
        config.middleware.use Rack::MethodOverride
        config.middleware.use ActionDispatch::Cookies

        config.api_only = true
    end
end 
```

**Comment by hiyashikyuri** [comment]
This helps me a lot!
Thanks!

**Comment by Awatatah** [comment]
@hiyashikyuri be sure to remove `config.api_only = true`

**Comment by maxmcd** [comment]
An additional config is needed:
```ruby
config.middleware.use ActionDispatch::Session::CookieStore
```
