### ISSUE TITLE
Railties test broken

### ISSUE THREAD

**Issue by utilum** [rails/rails#27347]
#### First error

`ruby -w -Itest test/railties/mounted_engine_test.rb`

### Expected behavior
Tests run, passing and / or failing.

### Actual behavior
```Run options: --seed 23077

# Running:

/home/oz/code/rails/activesupport/lib/active_support/testing/isolation.rb:21:in `load': undefined class/module ExecJS:: (ArgumentError)
	from /home/oz/code/rails/activesupport/lib/active_support/testing/isolation.rb:21:in `run'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/minitest-5.3.3/lib/minitest.rb:759:in `run_one_method'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/minitest-5.3.3/lib/minitest/parallel.rb:14:in `block (2 levels) in initialize'
```
#### Second error

`ruby -w -Itest test/railties/railtie_test.rb`

### Expected behavior
Tests run, passing and / or failing.

### Actual behavior
```Run options: --seed 53484

# Running:

../home/oz/code/rails/activesupport/lib/active_support/testing/isolation.rb:21:in `load': undefined class/module ExecJS:: (ArgumentError)
	from /home/oz/code/rails/activesupport/lib/active_support/testing/isolation.rb:21:in `run'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/minitest-5.3.3/lib/minitest.rb:759:in `run_one_method'
	from /home/oz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/minitest-5.3.3/lib/minitest/parallel.rb:14:in `block (2 levels) in initialize'
```

### System configuration

**Rails version**: master

**Ruby version**: 2.3.3p222

**Comment by maclover7** [comment]
Hmm, both tests seem to be passing for me on master. I'm running `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]` for my Ruby version.

**Comment by utilum** [comment]
Hmm, I get the exact same errors with `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]`.

**Comment by utilum** [comment]
Both tests pass (with multiple warnings) after I add

```
gem "therubyracer", platforms: :ruby
```

to the Gemfile and run `bundle install`.

**Comment by eileencodes** [comment]
Tests pass here. The warnings I get are

```
/Users/eileen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sass-rails-5.0.6/lib/sass/rails/helpers.rb:6: warning: method redefined; discarding old asset_data_url
/Users/eileen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sass-rails-5.0.6/lib/sass/rails/helpers.rb:6: warning: method redefined; discarding old asset_data_url
/Users/eileen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/sass_processor.rb:253: warning: previous definition of asset_data_url was here
/Users/eileen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-3.7.0/lib/sprockets/sass_processor.rb:253: warning: previous definition of asset_data_url was here
/Users/eileen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.12/lib/sqlite3/pragmas.rb:301: warning: method redefined; discarding old integrity_check
/Users/eileen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.12/lib/sqlite3/pragmas.rb:301: warning: method redefined; discarding old integrity_check
/Users/eileen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.12/lib/sqlite3/pragmas.rb:107: warning: previous definition of integrity_check was here
/Users/eileen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.12/lib/sqlite3/pragmas.rb:107: warning: previous definition of integrity_check was here
```

Sass can't be fixed because we don't own that gem and they won't accept the changes required to fix it. Sprockets can be fixed but I would double check that it's not already fixed and we just haven't updated the sprockets dependency. For the sqlite warnings that needs to be fixed in the sqlite library.

I'm going to close this because tests pass here and on CI, so this is an environment issue. For me it passes because I have node which brings along ExecJS. That's why adding rubyracer fixed it for you, installing node would fix it as well.

**Comment by utilum** [comment]
Thank you @eileencodes . Passes for me too, after installing node.
