### ISSUE TITLE
Nullify callback persists even as child class overrides association

### ISSUE THREAD

**Issue by chrisarcand** [rails/rails#27364]
### Steps to reproduce

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "5.0.0.1"
  gem "sqlite3"
  gem 'pry'
  gem 'pry-byebug'
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "houses", force: :cascade do |t|
    t.integer  "person_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "people", force: :cascade do |t|
    t.integer  "parent_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
end

class House < ActiveRecord::Base
  belongs_to :person
end

class Person < ActiveRecord::Base
  has_one :child, :foreign_key => 'parent_id', :foreign_type => 'Child'
  # Houses will continue to exist, but without their owners...
  has_many :houses, :dependent => :nullify
end

class Child < Person
  belongs_to :parent, :class_name => 'Person'
  # A child's house is their parent's house!
  has_many :houses, :through => :parent
end

class BugTest < Minitest::Test
  def setup
    @parent = Person.create(:houses => [House.create, House.create], :child => Child.create)
    @child = @parent.child

    assert_equal @parent.child, @child
    assert_equal @child.parent, @parent
    assert_equal @parent.houses.count, 2
  end

  def test_parentless_child_houses
    @parentless_child = Child.create

    assert_equal @parentless_child.houses.count, 0 # Passes
  end

  def test_child_houses_are_their_parents_houses
    assert_equal @parent.houses, @child.houses # Passes
  end

  def test_person_destroy
    assert @parent.destroy # Passes
  end

  def test_child_destroy
    assert @child.destroy # Fails!
  end
end
```

### Expected behavior

I should be able to destroy the child as the association I've specified does not attempt to nullify houses. 

### Actual behavior

```
Error: BugTest#test_child_destroy:
ActiveRecord::HasManyThroughCantAssociateThroughHasOneOrManyReflection:
Cannot modify association 'Child#houses' because the source reflection class
'House' is associated to 'Person' via :has_many.
```

### More notes

I've been digging in a bit trying to find the cause of this, but have started getting in over my head with callbacks. It appears on `child.destroy` that `_destroy_callbacks` from a `nullify` are indeed present (even though they shouldn't be), although the options within the reflection object doesn't seem to indicate that:

```
> Person.reflections['houses']
=> #<ActiveRecord::Reflection::HasManyReflection:0x007fc1703b2070
 @active_record=Person(id: integer, parent_id: integer, created_at: datetime, updated_at: datetime),
 @active_record_primary_key="id",
 @association_scope_cache={},
 @automatic_inverse_of=:person,
 @class_name="House",
 @constructable=true,
 @foreign_key="person_id",
 @foreign_type="houses_type",
 @inverse_of=
  #<ActiveRecord::Reflection::BelongsToReflection:0x007fc1703fa3e8
   @active_record=House(id: integer, person_id: integer, created_at: datetime, updated_at: datetime),
   @association_scope_cache={},
   @automatic_inverse_of=false,
   @class_name="Person",
   @constructable=true,
   @foreign_key="person_id",
   @foreign_type="person_type",
   @klass=Person(id: integer, parent_id: integer, created_at: datetime, updated_at: datetime),
   @name=:person,
   @options={},
   @plural_name="people",
   @scope=nil,
   @scope_lock=#<Thread::Mutex:0x007fc1703f9f60>,
   @type=nil>,
 @inverse_which_updates_counter_cache=nil,
 @klass=House(id: integer, person_id: integer, created_at: datetime, updated_at: datetime),
 @name=:houses,
 @options={:dependent=>:nullify},
 @plural_name="houses",
 @scope=nil,
 @scope_lock=#<Thread::Mutex:0x007fc1703b1d00>,
 @type=nil>

> Child.reflections['houses']
=> #<ActiveRecord::Reflection::ThroughReflection:0x007fc170388bd0
 @class_name="House",
 @delegate_reflection=
  #<ActiveRecord::Reflection::HasManyReflection:0x007fc170388888
   @active_record=Child(id: integer, parent_id: integer, created_at: datetime, updated_at: datetime),
   @association_scope_cache={},
   @automatic_inverse_of=false,
   @constructable=true,
   @foreign_type="houses_type",
   @klass=nil,
   @name=:houses,
   @options={:through=>:parent},
   @plural_name="houses",
   @scope=nil,
   @scope_lock=#<Thread::Mutex:0x007fc170388388>,
   @type=nil>,
 @klass=House(id: integer, person_id: integer, created_at: datetime, updated_at: datetime),
 @source_reflection_name=:houses>
```

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

cc/ @matthewd @durandom

**Comment by maclover7** [comment]
Investigating. Interesting that if you comment out the `dependent: :nullify` for the `Person`'s `has_many`, then everything passes fine. Did you experience this same behavior on 4.2.x?

**Comment by maclover7** [comment]
Hmm, I think this is due to the inheritance chain in the models. Since `_destroy_callbacks` is a class attribute (as well as `_reflections` and the like), it will be passed on to a class's children when inherited. By default, `Child` will receive all of `Person`'s callbacks, reflections, etc. by design. The trick here is that you are trying to redefine an existing callback with new options (same name, but different things on the inside), so it seems like we need a kind "undo button" to write over the existing association in favor of the new one and remove traces of the old one.

cc @sgrif

**Comment by chrisarcand** [comment]
@rafaelfranca This should probably be reopened and pinned to be investigated further; it still seems valid, at least to me. 

I just tried the same script on Rails 5.1 and it seems now there's a different concern, though I don't understand it really: I'm getting errors on all 3 tests now, with 

```
`ActiveRecord::HasManyThroughOrderError: Cannot have a has_many :through association 'Child#houses' which goes through 'Child#parent' before the through association is defined.
```

The association *is* defined before the `:through`...

**Comment by jeromedalbert** [comment]
When trying to run the repro script with the latest version of `activerecord` (`gem "activerecord"` instead of `gem "activerecord", "5.0.0.1"`), I get the following error instead:

```
Unknown key: :foreign_type. Valid keys are: :class_name, :anonymous_class, :primary_key, :foreign_key, :dependent, :validate, :inverse_of, :strict_loading, :query_constraints, :autosave, :required, :touch, :as, :through (ArgumentError)
        ...
        from repro.rb:46:in '<class:Person>'
        from repro.rb:45:in '<main>'
```

Caused by the following line in the repro script:

```ruby
  has_one :child, :foreign_key => 'parent_id', :foreign_type => 'Child'
```

It seems that for `has_one`, the `foreign_type` option is only valid if the `:as` option is provided ([source](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/associations/builder/has_one.rb#L11)).

---

@chrisarcand Can you confirm that this is still an issue? If so, can you make your repro script work again?
