### ISSUE TITLE
Current master it's not possible to use in Gemfile

### ISSUE THREAD

**Issue by deepj** [rails/rails#27382]
I'd like to play with Rails 5.1 master with our current application.

### Steps to reproduce

1. put/replace this line in Gemfile 
```
gem 'rails', github: 'rails/rails'
```

2. run `bundle`
3. run `bundle exec rails s`

### Expected behavior
Not to fail on not founding rails dependencies.

### Actual behavior
```
app/config/boot.rb:5:in `require': cannot load such file -- rails/commands/server (LoadError)
	from ../app/config/boot.rb:5:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
```

If I run `gem list`. I don't see any active/action* or rails gem on the list.

### System configuration
**Rails version**: current master

**Ruby version**: Ruby 2.3.3 / Ruby 2.4.0-rc1

**Bundler version**: 1.12.6 / 1.13.6

**Comment by utilum** [comment]
You pointed at master.
For 5.0.1 try putting this in your Gemfile: `gem 'rails', github: "rails/rails", tag: "v5.0.1.rc2"`
Then run `bundle install`.
Then launch the server.

That said, this is not a bug, more of a stackoverflow question, don't you think?

**Comment by deepj** [comment]
Yes, that works. But I want to try Rails 5.1 not Rails 5.0.1. In the past in time of Rails 5.0, it was possible to use this way.

**Comment by utilum** [comment]
What version of Rails is your current app in?

**Comment by simi** [comment]
Have you run `rails app:update`?

**Comment by deepj** [comment]
That issue doens't depend on a concrete Rails version. Just create this Gemfile in some seperated folder.

```ruby
source 'https://rubygems.org'

gem 'rails', github: 'rails/rails'

```

These are my steps how to reproduce it (please, use a clean gemset):

```
citadela:rails-5.1-test deepj$ ls -l
total 8
-rw-r--r--  1 deepj  staff  66 Dec 16 13:02 Gemfile
citadela:rails-5.1-test deepj$ ruby -v
ruby 2.4.0rc1 (2016-12-12 trunk 57064) [x86_64-darwin16]
citadela:rails-5.1-test deepj$ gem -v
2.6.8
citadela:rails-5.1-test deepj$ gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.3.0.pre.2)
did_you_mean (1.0.2)
io-console (default: 0.4.6)
json (default: 2.0.2)
minitest (5.10.1)
net-telnet (0.1.1)
openssl (default: 2.0.1)
power_assert (0.4.1)
psych (default: 2.2.1)
rake (12.0.0)
rdoc (default: 5.0.0)
test-unit (3.2.3)
xmlrpc (0.1.1)
citadela:rails-5.1-test deepj$ gem install bundler
Fetching: bundler-1.13.6.gem (100%)
Successfully installed bundler-1.13.6
1 gem installed
citadela:rails-5.1-test deepj$ bundle
The git source `git://github.com/rails/rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/rails/rails.git
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.0.0
Using minitest 5.10.1
Installing i18n 0.7.0
Installing concurrent-ruby 1.0.2
Installing thread_safe 0.3.5
Installing builder 3.2.2
Installing mini_portile2 2.1.0
Installing erubis 2.7.0
Installing rack 2.0.1
Installing nio4r 1.2.1 with native extensions
Installing websocket-extensions 0.1.2
Installing arel 7.1.4
Using bundler 1.13.6
Installing mime-types-data 3.2016.0521
Installing method_source 0.8.2
Installing thor 0.19.4
Installing tzinfo 1.2.2
Installing websocket-driver 0.6.4 with native extensions
Installing rack-test 0.6.3
Installing sprockets 3.7.0
Installing mime-types 3.1
Using activesupport 5.1.0.alpha from git://github.com/rails/rails.git (at master@b89f1aa)
Installing nokogiri 1.6.8.1 with native extensions
Installing rails-dom-testing 2.0.1
Installing loofah 2.0.3
Using activemodel 5.1.0.alpha from git://github.com/rails/rails.git (at master@b89f1aa)
Installing globalid 0.3.7
Using activerecord 5.1.0.alpha from git://github.com/rails/rails.git (at master@b89f1aa)
Using activejob 5.1.0.alpha from git://github.com/rails/rails.git (at master@b89f1aa)
Installing rails-html-sanitizer 1.0.3
Using actionview 5.1.0.alpha from git://github.com/rails/rails.git (at master@b89f1aa)
Using actionpack 5.1.0.alpha from git://github.com/rails/rails.git (at master@b89f1aa)
Using actioncable 5.1.0.alpha from git://github.com/rails/rails.git (at master@b89f1aa)
Using railties 5.1.0.alpha from git://github.com/rails/rails.git (at master@b89f1aa)
Installing mail 2.6.4
Using actionmailer 5.1.0.alpha from git://github.com/rails/rails.git (at master@b89f1aa)
Installing sprockets-rails 3.2.0
Using rails 5.1.0.alpha from git://github.com/rails/rails.git (at master@b89f1aa)
Bundle complete! 1 Gemfile dependency, 38 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
citadela:rails-5.1-test deepj$ gem list

*** LOCAL GEMS ***

arel (7.1.4)
bigdecimal (default: 1.3.0.pre.2)
builder (3.2.2)
bundler (1.13.6)
concurrent-ruby (1.0.2)
did_you_mean (1.0.2)
erubis (2.7.0)
globalid (0.3.7)
i18n (0.7.0)
io-console (default: 0.4.6)
json (default: 2.0.2)
loofah (2.0.3)
mail (2.6.4)
method_source (0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.1.0)
minitest (5.10.1)
net-telnet (0.1.1)
nio4r (1.2.1)
nokogiri (1.6.8.1)
openssl (default: 2.0.1)
power_assert (0.4.1)
psych (default: 2.2.1)
rack (2.0.1)
rack-test (0.6.3)
rails-dom-testing (2.0.1)
rails-html-sanitizer (1.0.3)
rake (12.0.0)
rdoc (default: 5.0.0)
sprockets (3.7.0)
sprockets-rails (3.2.0)
test-unit (3.2.3)
thor (0.19.4)
thread_safe (0.3.5)
tzinfo (1.2.2)
websocket-driver (0.6.4)
websocket-extensions (0.1.2)
xmlrpc (0.1.1)
citadela:rails-5.1-test deepj$ rails new testapp
/Users/deepj/.rubies/ruby-2.4.0-rc1/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem railties (>= 0.a) (Gem::GemNotFoundException)
	from /Users/deepj/.rubies/ruby-2.4.0-rc1/lib/ruby/2.4.0/rubygems.rb:298:in `activate_bin_path'
	from /Users/deepj/.gem/ruby/2.4.0/bin/rails:22:in `<main>'
```

As you can see, after `bundle install`, there are no active/action* or rails gems.

**Comment by utilum** [comment]
how about `bundle exec rails new testapp` ?

**Comment by deepj** [comment]
@utilum that doesn't help. Take a look at `gem list` after `bundle install`. No active/action* or rails aren't on the list = not installed. That's the problem.

**Comment by matthewd** [comment]
That's expected behaviour, and not new; when gems are bundled using git, they do not get installed inside rubygems.

**Comment by guilleiguaran** [comment]
Try to start it with `bin/rails s` (and update the binstub if required)

**Comment by deepj** [comment]
@guilleiguaran No, it doesn't work. I use the latest `bin\rails`

https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/bin/rails

So it fails on:

```
../config/boot.rb:5:in `require': cannot load such file -- rails/commands/server (LoadError)
	from ../config/boot.rb:5:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
```

Is there any way, how I can try Rails 5.1 master?

**Comment by deepj** [comment]
@matthewd OK, my bad. Anyway, I can't use it with `bundle exec` or `bin\rails`. Is there any way how I can try Rails 5.1 with my application without falling on:

```
../config/boot.rb:5:in `require': cannot load such file -- rails/commands/server (LoadError)
	from ../config/boot.rb:5:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
```

**Comment by deepj** [comment]
@matthewd @guilleiguaran I'd like to note. I don't have any problem with `5-0-stable`. That happens only with the current master.

**Comment by kaspth** [comment]
@deepj what does your `config/boot.rb` look like in full? Does it match https://github.com/rails/rails/blob/e592ee20a9d6889dcfbc05e485f448dfeda9b72f/railties/lib/rails/generators/rails/app/templates/config/boot.rb?
