### ISSUE TITLE
Concurrency issues with Active Record and jRuby

### ISSUE THREAD

**Issue by remofritzsche** [rails/rails#27418]
We have encountered multiple, severe and random concurrency issues with AR and jRuby, even in production mode. Please let me know if you'd like me to separate these two issues and whether I should copy over the full description from the sample app to this issue.

Many thanks for your help.

### Steps to reproduce

See [this sample application](https://github.com/remofritzsche/rails_jruby_concurrency_issues) for detailed instructions on how to reproduce these issues.

### Expected behavior

Active Record and Rails should work without any exceptions when using AR in multiple threads in production mode.

### Actual behavior

Various, random exceptions arise. Among these:

```
NoMethodError: undefined method `default_scope_override' for #<Class:0x5d75f90e>
Did you mean?  default_scope_override=
```

```
Exception: uninitialized constant ActiveRecord::QueryMethods::PredicateBuilder
Did you mean?  ActiveRecord::PredicateBuilder
```

```
Exception: uninitialized constant ActiveRecord::QueryMethods::Relation
Did you mean?  ActiveRecord::Relation
```

 See the sample application for a detailed description and full stack traces.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: jruby 9.1.6.0 (2.3.1)

**Comment by matthewd** [comment]
The second issue is rather confusing.

The line it's failing on is here: https://github.com/rails/rails/blob/v5.0.0.1/activerecord/lib/active_record/relation/query_methods.rb#L1230

That reference is lexically scoped to (yes, attempt `ActiveRecord::QueryMethods::Relation`, and then) resolve to `ActiveRecord::Relation`.

Are you sure that's not a JRuby bug?

**Comment by utilum** [comment]
@remofritzsche your README suggests calling the same script for both issues. Is that intentional?

I got the following error the 7th time I ran it:

```
[oz@localhost rails_jruby_concurrency_issues]$ RAILS_ENV=production jruby ./bin/rails runner test_schema_loading.rb
[oz@localhost rails_jruby_concurrency_issues]$ RAILS_ENV=production jruby ./bin/rails runner test_schema_loading.rb
[oz@localhost rails_jruby_concurrency_issues]$ RAILS_ENV=production jruby ./bin/rails runner test_schema_loading.rb
[oz@localhost rails_jruby_concurrency_issues]$ RAILS_ENV=production jruby ./bin/rails runner test_schema_loading.rb
[oz@localhost rails_jruby_concurrency_issues]$ RAILS_ENV=production jruby ./bin/rails runner test_schema_loading.rb
[oz@localhost rails_jruby_concurrency_issues]$ RAILS_ENV=production jruby ./bin/rails runner test_schema_loading.rb
ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: Field 'updated_at' doesn't have a default value: INSERT INTO `users` (`created_at`) VALUES ('2016-12-20 16:51:30.119000')
                                         log at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:568
                                 exec_insert at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/bundler/gems/activerecord-jdbc-adapter-ee68c1881a9b/lib/arjdbc/jdbc/adapter.rb:427
                                      insert at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:124
                                      insert at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14
                                      insert at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:65
                              _create_record at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:554
                              _create_record at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/counter_cache.rb:128
                              _create_record at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/locking/optimistic.rb:75
                              _create_record at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/dirty.rb:123
                     block in _create_record at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/callbacks.rb:302
                                        call at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126
                            block in compile at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506
                                        call at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455
                           __run_callbacks__ at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101
                       _run_create_callbacks at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750
                              _create_record at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/callbacks.rb:302
                              _create_record at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/timestamp.rb:68
                            create_or_update at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:534
                   block in create_or_update at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/callbacks.rb:298
                                        call at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126
                            block in compile at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506
                                        call at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455
                           __run_callbacks__ at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101
                         _run_save_callbacks at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750
                            create_or_update at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/callbacks.rb:298
                                        save at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:125
                                        save at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/validations.rb:44
                                        save at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/dirty.rb:22
                               block in save at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:319
  block in with_transaction_returning_status at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:395
                        block in transaction at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232
                      within_new_transaction at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189
                                 transaction at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232
                                 transaction at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211
           with_transaction_returning_status at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:392
                               block in save at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:319
               rollback_active_record_state! at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:334
                                        save at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:318
                                        save at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/suppressor.rb:41
                                      create at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:34
                             block in (root) at test_schema_loading.rb:8
```

And on the 14th run, just as you quote:

```[oz@localhost rails_jruby_concurrency_issues]$ RAILS_ENV=production jruby ./bin/rails runner test_schema_loading.rb
NoMethodError: undefined method `default_scope_override' for #<Class:0x34647f58>
Did you mean?  default_scope_override=
                          method_missing at org/jruby/RubyBasicObject.java:1655
                          method_missing at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/dynamic_matchers.rb:21
                     build_default_scope at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/scoping/default.rb:107
                          default_scoped at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/scoping/named.rb:33
                                     all at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/scoping/named.rb:28
                        scope_attributes at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/scoping.rb:24
  populate_with_current_scope_attributes at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/scoping.rb:36
           initialize_internals_callback at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/scoping.rb:43
                              initialize at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/core.rb:317
                                     new at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/inheritance.rb:65
                                  create at /home/oz/code/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:33
                         block in (root) at test_schema_loading.rb:8
```

**Comment by remofritzsche** [comment]
Thanks a lot for having a look at this.

@matthewd No, I'm not entirely sure it's not a jRuby bug.

@utilum Sorry, that was a mistake. The README should now be correct. Thanks for pointing it out.

**Comment by remofritzsche** [comment]
The second bug seems very similar to the issues I get when using concurrency in development mode and without eager loading (as Rails' autoreloading is not thread safe - which of course is totally fine). 

Maybe this might be a hint?

**Comment by matthewd** [comment]
> The second bug seems very similar to the issues I get when using concurrency in development mode and without eager loading (as Rails' autoreloading is not thread safe - which of course is totally fine).

Not really... both because the class in question should already be loaded by `User.first`, and because it uses a different autoload mechanism (the one built in to the interpreter) to do so.

But also because Rails autoreloading is very much supposed to be thread safe, so I'm interested in any claims otherwise there too.

**Comment by maclover7** [comment]
cc @headius

**Comment by remofritzsche** [comment]
@matthewd I've now added a third example to the sample application that reproduces issues we think come from autoreloading / autoloading. In the past, we've seen countless other such exceptions when using concurrency in development mode in our applications.

**Comment by matthewd** [comment]
@headius https://github.com/rails/rails/issues/27418#issuecomment-268294660 actually sounds suspiciously similar to https://bugs.ruby-lang.org/issues/12688 -- complete with "DYM [the very thing you just asked for]?". But given that's an MRI bug, ... :confused:

**Comment by matthewd** [comment]
@remofritzsche sorry, I over-simplified. It should be threadsafe when using Rails internal concurrency mechanisms (Active Job; Action Cable; multiple simultaneous web requests). If you're manually spawning your own threads, you need to have them cooperate: I need to write a guide on that, but for now, see #26847 & #26956 (the code block in https://github.com/rails/rails/issues/26847#issuecomment-255548043 is the tl;dr).

**Comment by beatgutzwiller** [comment]
Thanks, this helped me further. But we have still the same problem with 
`Rails.application.executor.wrap do`
in our application. So i tried it with the sample application provided here. Testcase 1 & 3 are still failing with 
`Rails.application.executor.wrap do`
I couldn't reproduce Testcase 2 (same Jruby and Rails version) even without any changes (+25 runs).

Our application and Testcase 1 & 3 both run fine, if I use the exlusive lock:
`ActiveSupport::Dependencies.load_interlock do`
I am not 100% understanding how this works until now, so if there are any drawbacks to using this, I would be very very grateful if somebody can explain it a little bit. 
 If it is a completly useless and wrong approach just tell me. 
But i thougth there is maybe a chance that it help you guys.

**Comment by kalsan** [comment]
I can reproduce Issue 1 (2 runs) and Issue 3 (at first run), but just like @beatgutzwiller I am unable to reproduce Issue 2.

My jruby and java version is: jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.112-b15 on 1.8.0_112-b15 +jit [linux-x86_64]

I'm running a fully up-to-date Arch Linux.

**Comment by nasa42** [comment]
Possibly related: https://github.com/rails/rails/issues/28589

**Comment by nasa42** [comment]
This does not seem specific to JRuby. https://github.com/rails/rails/issues/25838 was reported with an MRI version.

**Comment by hobodave** [comment]
@matthewd 

I have a simplified test case for the `default_scope_override` bug:

https://gist.github.com/hobodave/972c209a22d54b0d1769b0701547404c

Model does not matter.

@matthewd Should this code fail in this way?

**Comment by hobodave** [comment]
Update: the default_scope_override bug is due to `class_attribute` not being thread-safe:

https://github.com/rails/rails/issues/14021

https://github.com/rails/rails/issues/26758

**Comment by lichtamberg** [comment]
Having the same error "uninitialized constant ActiveRecord::QueryMethods::PredicateBuilder" with Rails 3.2.22.1 and normal MRI Ruby 2.3.4 - no Java.

**Comment by samarism** [comment]
We r having the exact same issue but on rails 3.2 and jruby running on jetty. Am creating a large number of threads using threadpoolexecutor service and they throw bizzarre random AR exceptions. One question, how is using self spawned threads via executor service a different use case from a jetty server handling large number of concurrent http requests ? Since common rails framework objects are used in the jetty/jruby context this prpblem shud happen ob high concurrency on the http levels also. Or is my understanding incorrect ?

**Comment by headius** [comment]
Has anyone confirmed this with a recent Rails and the newer 5.x-compatible JRuby activerecord adapters? 

It is not clear to me from reading this issue whether JRuby, activerecord-jdbc, or Rails itself are actually to blame here. A new reproduction would be very helpful.

**Comment by strika** [comment]
We got this exception on Rails 5.0.6, but it was on MRI:

```
NoMethodError: undefined method `default_scope_override' for #<Class:0x5d75f90e>
Did you mean?  default_scope_override=
```

This happened in a Sidekiq job that normally works as expected. The exception happened only 3 times, a few days ago. We were not able to reproduce it.

**Comment by drn** [comment]
Much like @strika, we ran into this as well on Rails 5.1.5 using MRI and Sidekiq.

```
NameError: undefined local variable or method `default_scope_override' for #<Class:0x005613655ceb20>
Did you mean?  default_scope_override=
  from active_record/dynamic_matchers.rb:22:in `method_missing'
  from active_record/scoping/default.rb:107:in `build_default_scope'
  from active_record/scoping/named.rb:43:in `default_scoped'
  from active_record/scoping/named.rb:28:in `all'
  from active_record/querying.rb:3:in `find'
  from active_record/core.rb:171:in `find'
  from app/workers/email/issuance_job.rb:22:in `email'
  from app/workers/email/issuance_job.rb:13:in `redis_lock'
  from app/workers/email/issuance_job.rb:6:in `perform'
  from sidekiq/processor.rb:187:in `execute_job'
  from sidekiq/processor.rb:169:in `block (2 levels) in process'
  from sidekiq/middleware/chain.rb:128:in `block in invoke'
  from raven/integrations/sidekiq.rb:7:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
```

Auto-retry succeeded and haven't seen it since.

**Comment by nasa42** [comment]
This issue is likely a duplicate of https://github.com/rails/rails/issues/25838 and already fixed in https://github.com/rails/rails/pull/29216. To be released in 5.2.

**Comment by remofritzsche** [comment]
Great. I'll be happy to lift my sample rails application to 5.2 and check it there again.

**Comment by remofritzsche** [comment]
Issues #1 and #2 as described in [this example project](https://github.com/remofritzsche/rails_jruby_concurrency_issues) indeed seem to be solved, many thanks 👍 

However, issue #3 still arises (`Exception: Circular dependency detected while autoloading constant User...`). Any idea how to tackle this?

**Comment by matthewd** [comment]
@remofritzsche see http://edgeguides.rubyonrails.org/threading_and_code_execution.html#wrapping-application-code. When using your own concurrency primitives (concurrent-ruby in this case) instead of the higher level mechanisms Rails provides (like Active Job), you need to let Rails know about the extra threads manually.

**Comment by remofritzsche** [comment]
@matthewd Thanks for your answer. We've already tried this back in 2016 and it makes these errors appear less often, but they still appear. The sample project is now updated to use Rails 5.2 and executor wrapping in the 3rd test case.

I'm still getting occasional errors like this one:

```
Exception: uninitialized constant ActiveModel::Validations::Errors
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activemodel-5.2.0.rc1/lib/active_model/validations.rb:304:in `errors'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activemodel-5.2.0.rc1/lib/active_model/validations.rb:338:in `valid?'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/validations.rb:67:in `valid?'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/validations.rb:84:in `perform_validations'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/validations.rb:46:in `save'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/transactions.rb:310:in `block in save'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/transactions.rb:386:in `block in with_transaction_returning_status'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:252:in `transaction'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/transactions.rb:212:in `transaction'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/transactions.rb:383:in `with_transaction_returning_status'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/transactions.rb:310:in `block in save'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/transactions.rb:309:in `save'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/suppressor.rb:44:in `save'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/persistence.rb:36:in `create'
test_auto_reloading.rb:3:in `block in test'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:230:in `block in within_new_transaction'
/usr/local/Cellar/jruby/9.1.6.0/libexec/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:227:in `within_new_transaction'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activerecord-5.2.0.rc1/lib/active_record/transactions.rb:212:in `transaction'
test_auto_reloading.rb:2:in `test'
test_auto_reloading.rb:16:in `block in (root)'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/activesupport-5.2.0.rc1/lib/active_support/execution_wrapper.rb:87:in `wrap'
test_auto_reloading.rb:14:in `block in (root)'
/Users/rfritzsche/Temp/rails_jruby_concurrency_issues/vendor/bundle/jruby/2.3.0/gems/concurrent-ruby-1.0.5-java/lib/concurrent/executor/java_executor_service.rb:94:in `run'
```

**Comment by remofritzsche** [comment]
Also we just got the `undefined local variable or method `default_scope_override'` error again, in *production mode*. This happens when accessing the application very early and concurrently right after restart.

**Comment by mohamedhafez** [comment]
Is there any easy way to just load the whole application and Rails parts like `ActiveRecord::QueryMethods::Relation` all at once in a single thread, instead of depending on autoloading? That would be a great feature/workaround for some of us, at least until all the fixes are in.

**Comment by shepmaster** [comment]
See also #33209 which addresses a similar issue about lazily autoloading namespaced classes concurrently.
