### ISSUE TITLE
Upgrading from Rails 5.0.0.1 to Rails 5.0.1 breaks MySQL 5.0 compatibility 

### ISSUE THREAD

**Issue by VvanGemert** [rails/rails#27422]
### Steps to reproduce
I've upgraded my rails version from 5.0.0.1 to 5.0.1 and tried to deploy it. The db:migrate command failed and stopped deployment. I've rolled back to 5.0.0.1 for now.

### Expected behavior
db:migrate should pass.

### Actual behavior
It tries to access a table that doesn't exists in mysql 5.0, named 'referential_constraints' in information_schema db. It happens when trying to dump the schema. The error it produces when running db:migrate: 
```
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown table 'referential_constraints' in information_schema: SELECT fk.referenced_table_name AS 'to_table',
       fk.referenced_column_name AS 'primary_key',
       fk.column_name AS 'column',
       fk.constraint_name AS 'name',
       rc.update_rule AS 'on_update',
       rc.delete_rule AS 'on_delete'
FROM information_schema.key_column_usage fk
JOIN information_schema.referential_constraints rc
USING (constraint_schema, constraint_name)
WHERE fk.referenced_column_name IS NOT NULL
  AND fk.table_schema = 'site'
  AND fk.table_name = 'account_event'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/mysql/database_statements.rb:36:in `exec_query'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/mysql/database_statements.rb:10:in `select_all'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:520:in `foreign_keys'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:225:in `foreign_keys'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:97:in `block in tables'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:96:in `each'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:96:in `tables'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:37:in `dump'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:21:in `dump'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:253:in `block (4 levels) in <top (required)>'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:252:in `open'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:252:in `block (3 levels) in <top (required)>'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:66:in `block (2 levels) in <top (required)>'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:59:in `block (2 levels) in <top (required)>'
/srv/piedpiper/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
```

### System configuration
**Rails version**: 5.0.1
**Ruby version**: 2.3.3
**OS**: Ubuntu 14.04
**MySQL Server**: 5.0.95

**Comment by mubashirhanif** [comment]
Just out of curiosity what was your `mysql2` `gem version` on `Rails 5.0.0.1`

**Comment by VvanGemert** [comment]
I didn't update the mysql2 gem, only Rails. The mysql2 gem version used in both Rails versions is 0.4.5.

**Comment by mubashirhanif** [comment]
A quick-search into the `commit-history`  tells that `72d18e55e7ad06a5d2d85f943757aa88bbf351ab` or `pull-request` #25307  introduced this change.

On a side note `mysql2` is only tested to work on mysql version `>= 5.5`.

**Comment by mubashirhanif** [comment]
Since `table` `referential_constraints` was introduced in mysql version `5.1`. This is breaking the your functionality I suppose.
A quick google search reveals that there is a table called `table_constraints` but it doesn't store triggers information(`DELETE_RULE`, `UPDATE_RULE`) which are used by `schema_dumper` module.
Upgrading to `5.0.1` would result in breakage of this functionality for you.

**Comment by VvanGemert** [comment]
We've updated our database to MySQL 5.6, so this issue isn't relevant for us any more. Although such a breaking change isn't supposed to happen with a minor release of course.
