### ISSUE TITLE
TypeError: Cannot visit ThreadSafe::Array

### ISSUE THREAD

**Issue by yahonda** [rails/rails#27631]
Recent unit tests getting `TypeError: Cannot visit ThreadSafe::Array` since Build #39933
https://travis-ci.org/rails/rails/jobs/190274394 . It had been fine until #39917 
https://travis-ci.org/rails/rails/jobs/190040241

It just reproduces with ruby-trunk.

### Steps to reproduce
```
* Install ruby-trunk
$ cd activerecord
$ bundle exec ruby -Itest test/cases/primary_keys_test.rb -n test_find_with_more_than_one_string_key
```
### Expected behavior
It should finish without errors.

### Actual behavior
```ruby
$ cd activerecord
$ bundle exec ruby -Itest test/cases/primary_keys_test.rb -n test_find_with_more_than_one_string_key
Using sqlite3
Run options: -n test_find_with_more_than_one_string_key --seed 41556

# Running:

E

Finished in 0.038121s, 26.2324 runs/s, 0.0000 assertions/s.

  1) Error:
PrimaryKeysTest#test_find_with_more_than_one_string_key:
TypeError: Cannot visit ThreadSafe::Array
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/reduce.rb:19:in `rescue in visit'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/reduce.rb:13:in `visit'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:600:in `visit_Arel_Nodes_In'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/determine_if_preparable_visitor.rb:13:in `visit_Arel_Nodes_In'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/reduce.rb:13:in `visit'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:799:in `block in inject_join'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:797:in `each'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:797:in `each_with_index'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:797:in `each'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:797:in `inject'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:797:in `inject_join'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:616:in `visit_Arel_Nodes_And'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/reduce.rb:13:in `visit'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:248:in `block in collect_nodes_for'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:247:in `each'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:247:in `each_with_index'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:247:in `collect_nodes_for'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:232:in `visit_Arel_Nodes_SelectCore'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:195:in `block in visit_Arel_Nodes_SelectStatement'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:194:in `each'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:194:in `inject'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/to_sql.rb:194:in `visit_Arel_Nodes_SelectStatement'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/sqlite.rb:14:in `visit_Arel_Nodes_SelectStatement'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/reduce.rb:13:in `visit'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/arel-b26638ef0419/lib/arel/visitors/reduce.rb:7:in `accept'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/determine_if_preparable_visitor.rb:8:in `accept'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:12:in `to_sql'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:33:in `select_all'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
    /home/yahonda/git/rails/activerecord/lib/active_record/querying.rb:39:in `find_by_sql'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:662:in `exec_queries'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:551:in `load'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:255:in `records'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:499:in `find_some_ordered'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:473:in `find_some'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:450:in `find_with_ids'
    /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:66:in `find'
    /home/yahonda/git/rails/activerecord/lib/active_record/querying.rb:3:in `find'
    /home/yahonda/git/rails/activerecord/lib/active_record/core.rb:170:in `find'
    test/cases/primary_keys_test.rb:93:in `test_find_with_more_than_one_string_key'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**: master branch

**Ruby version**:ruby 2.5.0dev (2017-01-10 trunk 57299) [x86_64-linux]

```ruby
$ bundle show
Gems included by the bundle:
  * actioncable (5.1.0.alpha)
  * actionmailer (5.1.0.alpha)
  * actionpack (5.1.0.alpha)
  * actionview (5.1.0.alpha)
  * activejob (5.1.0.alpha)
  * activemodel (5.1.0.alpha)
  * activerecord (5.1.0.alpha)
  * activesupport (5.1.0.alpha)
  * addressable (2.5.0)
  * amq-protocol (2.0.1)
  * arel (8.0.0 b26638e)
  * ast (2.3.0)
  * backburner (1.3.1)
  * bcrypt (3.1.11)
  * beaneater (1.0.0)
  * benchmark-ips (2.7.2)
  * blade (0.7.0)
  * blade-qunit_adapter (2.0.1)
  * blade-sauce_labs_plugin (0.6.2)
  * builder (3.2.2)
  * bundler (1.13.7)
  * bunny (2.6.2)
  * byebug (9.0.6)
  * childprocess (0.5.9)
  * coffee-rails (4.2.1)
  * coffee-script (2.4.1)
  * coffee-script-source (1.12.2)
  * concurrent-ruby (1.0.4)
  * connection_pool (2.2.1)
  * cookiejar (0.3.3)
  * curses (1.0.2)
  * daemons (1.2.4)
  * dalli (2.7.6)
  * dante (0.2.0)
  * delayed_job (4.1.2 e3772d4)
  * delayed_job_active_record (4.1.1 36f434c)
  * em-hiredis (0.3.1)
  * em-http-request (1.1.5)
  * em-socksify (0.3.1)
  * erubis (2.7.0)
  * event_emitter (0.2.5)
  * eventmachine (1.2.1)
  * execjs (2.7.0)
  * faraday (0.10.0)
  * faye (1.2.3)
  * faye-websocket (0.10.5)
  * ffi (1.9.14)
  * globalid (0.3.7)
  * hiredis (0.6.1)
  * http_parser.rb (0.6.0)
  * i18n (0.7.0)
  * jquery-rails (4.2.1)
  * json (2.0.2)
  * kindlerb (1.2.0)
  * libxml-ruby (2.9.0)
  * listen (3.1.5)
  * loofah (2.0.3)
  * mail (2.6.4)
  * metaclass (0.0.4)
  * method_source (0.8.2)
  * mime-types (3.1)
  * mime-types-data (3.2016.0521)
  * mini_portile2 (2.1.0)
  * minitest (5.3.3)
  * mocha (0.14.0)
  * mono_logger (1.1.0)
  * multi_json (1.12.1)
  * multipart-post (2.0.0)
  * mustache (1.0.3)
  * mysql2 (0.4.5)
  * nio4r (2.0.0)
  * nokogiri (1.7.0)
  * parser (2.3.3.1)
  * pg (0.19.0)
  * powerpack (0.1.1)
  * public_suffix (2.0.4)
  * puma (3.6.2)
  * qu (0.2.0)
  * qu-redis (0.2.0)
  * que (0.12.0)
  * queue_classic (3.2.0.RC1 51d56ca)
  * racc (1.4.14)
  * rack (2.0.1)
  * rack-cache (1.6.1)
  * rack-protection (1.5.3)
  * rack-test (0.6.3)
  * rails (5.1.0.alpha)
  * rails-dom-testing (2.0.2)
  * rails-html-sanitizer (1.0.3)
  * railties (5.1.0.alpha)
  * rainbow (2.1.0)
  * rake (12.0.0)
  * rb-fsevent (0.9.8)
  * rb-inotify (0.9.7 9055351)
  * rdoc (5.0.0)
  * redcarpet (3.2.3)
  * redis (3.3.2)
  * redis-namespace (1.5.2)
  * resque (1.27.0 835a4a7)
  * resque-scheduler (4.3.0)
  * rubocop (0.46.0)
  * ruby-progressbar (1.8.1)
  * ruby_dep (1.5.0)
  * rubyzip (1.2.0)
  * rufus-scheduler (3.3.1)
  * sass (3.4.23)
  * sass-rails (5.0.6)
  * sdoc (1.0.0.rc1)
  * selenium-webdriver (3.0.5)
  * sequel (4.41.0)
  * serverengine (1.5.11)
  * sidekiq (4.2.7)
  * sigdump (0.2.4)
  * simple_uuid (0.4.0)
  * sinatra (1.0)
  * sneakers (2.4.0)
  * sprockets (3.7.1)
  * sprockets-rails (3.2.0)
  * sqlite3 (1.3.13)
  * stackprof (0.2.10)
  * sucker_punch (2.0.2)
  * thin (1.7.0)
  * thor (0.19.4)
  * thread (0.1.7)
  * thread_safe (0.3.5)
  * tilt (2.0.5)
  * turbolinks (5.0.1)
  * turbolinks-source (5.0.0)
  * tzinfo (1.2.2)
  * uglifier (3.0.4)
  * unicode-display_width (1.1.2)
  * useragent (0.16.8)
  * vegas (0.1.11)
  * w3c_validators (1.3.1)
  * websocket (1.2.3)
  * websocket-client-simple (0.3.0 e161305)
  * websocket-driver (0.6.4)
  * websocket-extensions (0.1.2)
$
```

### Additional information:

This error itself returns from Arel.

https://github.com/rails/arel/blob/master/lib/arel/visitors/to_sql.rb#L600

```ruby
          visit(o.right, collector) << ")"
```
Here `o.right .class` is `ThreadSafe::Array` but `Array` is expected.

**Comment by matthewd** [comment]
The same error occurred at some point last year, and it was found to be a bug in ruby trunk: it was actually confusing the `Array` and `ThreadSafe::Array` classes internally.

I imagine that's what's happening here too.

**Comment by yahonda** [comment]
Thanks for the useful information. Looks like it is similar with https://bugs.ruby-lang.org/issues/11977 .
Also reproduced like this.

```ruby
$ git clone -b ruby250 https://github.com/yahonda/array_bug.git
$ cd array_bug
$ bundle
$ bundle exec ruby -w -e 'p [].class'
Array
$ bundle exec ruby -w -e 'require "rails"; p [].class'
ThreadSafe::Array
$ ruby -v
ruby 2.5.0dev (2017-01-10 trunk 57299) [x86_64-linux]
$ bundle -v
Bundler version 1.13.7
$
```

Cced @tenderlove since you reported [Bug with array literals caused by r53376](https://bugs.ruby-lang.org/issues/11977)

**Comment by yahonda** [comment]
Filed at bugs.ruby-lang.org https://bugs.ruby-lang.org/issues/13120

**Comment by yahonda** [comment]
Closing since  https://bugs.ruby-lang.org/issues/13120 has been addressed at [Revision 57305](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/57305). I have verified that by using ruby-trunk revision 57306.

```ruby
$ ruby -v
ruby 2.5.0dev (2017-01-11 trunk 57306) [x86_64-linux]
$ bundle exec ruby -Itest test/cases/primary_keys_test.rb -n test_find_with_more_than_one_string_key
Using sqlite3
Run options: -n test_find_with_more_than_one_string_key --seed 20407

# Running:

.

Finished in 0.044794s, 22.3243 runs/s, 22.3243 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
$
```
