### ISSUE TITLE
ActionMailer in 5.0.1 nullifying to address

### ISSUE THREAD

**Issue by biznickman** [rails/rails#27783]
### Steps to reproduce

**environment.rb**

```
ActionMailer::Base.smtp_settings = {
  user_name: ENV['USERNAME'],
  password: ENV['PASSWORD'],
  domain: ENV['DOMAIN'],
  address: "smtp.sendgrid.net",
  port: 587,
  authentication: :plain,
  enable_starttls_auto: true
}
```

**some_mailer.rb**

```
class SomeMailer < ActionMailer::Base
  default from: "myfromemail@gmail.com"
  layout 'mailer'

  def confirm
    mail(
      to: 'mygmail@gmail.com',
      subject: "Testing this out"
    )
  end
end
```

**config/development.rb**

```
# Active mailer
config.action_mailer.delivery_method = :smtp
config.action_mailer.raise_delivery_errors = true
config.action_mailer.perform_deliveries = true
```

### Expected behavior
It should send the email. If I run the following code:

```
m = SomeMailer.confirm
m.to
```

It outputs the correct email address.

However once I call:
`m.deliver`

It outputs the following error:

```
ArgumentError: An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address.
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/mail-2.6.4/lib/mail/check_delivery_params.rb:10:in `check_delivery_params'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/mail-2.6.4/lib/mail/network/delivery_methods/smtp.rb:99:in `deliver!'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/mail-2.6.4/lib/mail/message.rb:2149:in `do_delivery'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/mail-2.6.4/lib/mail/message.rb:237:in `block in deliver'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/actionmailer-5.0.1/lib/action_mailer/base.rb:543:in `block in deliver_mail'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `instrument'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/actionmailer-5.0.1/lib/action_mailer/base.rb:541:in `deliver_mail'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/mail-2.6.4/lib/mail/message.rb:237:in `deliver'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/actionmailer-5.0.1/lib/action_mailer/message_delivery.rb:96:in `block in deliver_now'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/actionmailer-5.0.1/lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/actionmailer-5.0.1/lib/action_mailer/message_delivery.rb:95:in `deliver_now'
	from (irb):7
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/railties-5.0.1/lib/rails/commands/console.rb:65:in `start'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/railties-5.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/nickoneill/Dropbox/Documents/TextACoder/clients/MatthewSmolin/AgoraTickets/app/bin/rails:9:in `<top (required)>'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/nickoneill/.rvm/gems/ruby-2.3.1@agoratickets/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/nickoneill/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/nickoneill/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

If I then run in the console:
`m.to`

It outputs `nil` as the value.

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.1

**Comment by nelyj** [comment]
I don't understand much Rails core, but in the module [ActionMailer::MessageDelivery](https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/message_delivery.rb) not appear deliver method. instead it use deliver method  maybe you can try to use deliver_now or deliver_later.

**Comment by biznickman** [comment]
@nelyj both do the same thing. `deliver_now` I believe calls `deliver`. Same outcome.

**Comment by murtyk** [comment]
@biznickman why did you close this? How is it resolved?

**Comment by xofred** [comment]
I'm having exact same problem when testing...
```ruby
  test "#notify_replied_to_customer_services 顾客回复" do
    email = ReturnRequestNotifier.notify_replied_to_customer_services(mock_return_request, mock_user)
    binding.pry
    # Send the email, then test that it got queued
    assert_emails 1 do
      email.deliver_now
    end

    # Test the body of the sent email contains what we expect it to
    assert_equal [EMAIL_FROM], email.from
    assert_equal [EMAIL_TO], email.to
    assert(email.subject.include?("Return request have new reply"))
    pp email.body.to_s     
  end
```
```
[1] pry(#<ReturnRequestNotifierTest>)> email.to
=> ["justin.c@shopperplus.com"]
[2] pry(#<ReturnRequestNotifierTest>)> email.deliver_now
ArgumentError: SMTP To address may not be blank: []
from /Users/justin/.rvm/gems/ruby-2.3.7/gems/mail-2.7.0/lib/mail/check_delivery_params.rb:21:in `check_to'
[3] pry(#<ReturnRequestNotifierTest>)> email.to
=> []
[4] pry(#<ReturnRequestNotifierTest>)> email.from
=> ["system@shopperplus.com"]
[5] pry(#<ReturnRequestNotifierTest>)> email.subject
=> "Return request have new reply 2018-12-14"
[6] pry(#<ReturnRequestNotifierTest>)> wtf
```
System configuration
Rails version: 5.1.6

Ruby version: 2.3.7
