### ISSUE TITLE
activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:124:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by segantii-alex-falkowski** [rails/rails#27808]
Ruby version: 2.4.0
Rails version: 4.2.7.1

```
/Users/alexfalkowski/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:206: warning: constant ::Fixnum is deprecated
/Users/alexfalkowski/.gem/ruby/2.4.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:155: warning: constant ::Fixnum is deprecated
/Users/alexfalkowski/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.2/lib/concurrent/atomic/mutex_atomic_fixnum.rb:80: warning: constant ::Fixnum is deprecated
/Users/alexfalkowski/.gem/ruby/2.4.0/gems/concurrent-ruby-1.0.2/lib/concurrent/atomic/mutex_atomic_fixnum.rb:80: warning: constant ::Fixnum is deprecated
/Users/alexfalkowski/.gem/ruby/2.4.0/gems/activejob-4.2.7.1/lib/active_job/arguments.rb:27: warning: constant ::Fixnum is deprecated
/Users/alexfalkowski/.gem/ruby/2.4.0/gems/activejob-4.2.7.1/lib/active_job/arguments.rb:27: warning: constant ::Bignum is deprecated
/Users/alexfalkowski/.gem/ruby/2.4.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:155: warning: constant ::Fixnum is deprecated
/Users/alexfalkowski/.gem/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/Users/alexfalkowski/.gem/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
/Users/alexfalkowski/.gem/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:124:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)
	from /Users/alexfalkowski/.gem/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/alexfalkowski/.gem/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/alexfalkowski/.gem/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/alexfalkowski/.gem/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/alexfalkowski/.gem/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/alexfalkowski/.gem/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/alexfalkowski/.gem/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/alexfalkowski/.gem/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	 ... 5526 levels...
	from /Users/alexfalkowski/.gem/ruby/2.4.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/alexfalkowski/.gem/ruby/2.4.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
``` 

Sorry if it's a duplicate.

**Comment by utilum** [comment]
@segantii-alex-falkowski what has provoked this error? That is to say: will you provide steps to reproduce?

**Comment by segantii-alex-falkowski** [comment]
It's a massive website, so I will see if I can replicate with a dummy.

**Comment by segantii-alex-falkowski** [comment]
This is just starting the website.

**Comment by y-yagi** [comment]
Rails 4.2 isn't yet compatible with Ruby 2.4. This has been fixed in #27473 but you will need to wait for a new release of 4.2.x to be cut to be able to use it with Ruby 2.4.

**Comment by segantii-alex-falkowski** [comment]
Thanks :)

**Comment by kigster** [comment]
👍  on this one.. Also happening on Rails 4.2 ruby 2.4.0. It would be awesome to release that patch!
