### ISSUE TITLE
Specifying an enum and then using with_options anywhere in the same class raises an ArgumentError

### ISSUE THREAD

**Issue by JoeWoodward** [rails/rails#27897]
### Steps to reproduce

1. Create an `enum` column and configure the values in any model. Below the `enum` definition, use `with_options`. e.g.

```ruby
class EnumWithOption < ApplicationRecord
  enum error: { one: 0, two: 1, three: 2 }

  with_options presence: true do
    validates :error, inclusion: { in: errors.keys }
  end
end
```

2. Try to instantiate the class

### Expected behavior
Should not raise an error

### Actual behavior
Raises 
ArgumentError: wrong number of arguments (given 1, expected 0)

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.3

### Trace

```
irb(main):001:0> EnumWithOption.create
ArgumentError: wrong number of arguments (given 1, expected 0)
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/enum.rb:157:in `block (2 levels) in enum'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/option_merger.rb:22:in `method_missing'
	from /Users/JoeWoodward/Desktop/enum_with_options/app/models/enum_with_option.rb:5:in `block in <class:EnumWithOption>'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/core_ext/object/with_options.rb:67:in `instance_eval'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/core_ext/object/with_options.rb:67:in `with_options'
	from /Users/JoeWoodward/Desktop/enum_with_options/app/models/enum_with_option.rb:4:in `<class:EnumWithOption>'
	from /Users/JoeWoodward/Desktop/enum_with_options/app/models/enum_with_option.rb:1:in `<top (required)>'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:477:in `load'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:477:in `block in load_file'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:662:in `new_constants_in'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:476:in `load_file'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:375:in `block in require_or_load'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
... 6 levels...
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/JoeWoodward/Desktop/enum_with_options/bin/rails:9:in `<top (required)>'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/JoeWoodward/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

### Example App

https://github.com/JoeWoodward/enum_with_options

Includes a test to show the error in `test/models/enum_with_option_test.rb`

**Comment by al2o3cr** [comment]
The issue appears to be that the call to the class-level `errors` method on line 5 of your model gets routed through the `OptionMerger` - so it gets transformed to `errors(presence: true)` and explodes.

A workaround would be to use the one-arity version of `with_options`:
```ruby
class EnumWithOption < ApplicationRecord
  enum error: { one: 0, two: 1, three: 2 }

  with_options presence: true do |om|
    om.validates :error, inclusion: { in: errors.keys }
  end
end
```

**Comment by Sen-Zhang** [comment]
As @al2o3cr said; and another solution could be:
```ruby
class EnumWithOption < ApplicationRecord
  enum error: { one: 0, two: 1, three: 2 }

  with_options presence: true do
    validates :error, inclusion: { in: EnumWithOption.errors.keys }
  end
end
```

**Comment by meinac** [comment]
Actually this issue does not effects enums only, you can't use any class methods in `with_options` block because `OptionMerger` passes method calls to the context with parameters given to `with_options`.

As @Sen-Zhang mentioned, you need to call the method as you are outside of the class.

**Comment by meinac** [comment]
@rafaelfranca I think someone can add a note into the documentation to clarify this issue. WDYT?

**Comment by rafaelfranca** [comment]
Sounds like a good idea. Do you want to give a try?
