### ISSUE TITLE
rails console doesn't seem to work with whitespace in path ( OS X, Binstubs)

### ISSUE THREAD

**Issue by therocketforever** [rails/rails#28023]
### Steps to reproduce

dependencies installed via rbenv/bundler with binstubs

1. install gems.
`bundle install --path .bundle/gems --binstubs .bundle/bin`

2. create a new rails application in a subdirectory of a directory with white space in the name.

`mkdir "Directory Name With Space"`
`cd Directory\ Name\ With\ Space/` or `cd "Directory Name With Space/"`
`rails new prototype`
`cd prototype`

3. run rails console `rails console`

### Expected behavior

Application should boot into irb console

### Actual behavior
application will fail to boot with the message:
```
/Users/therocketforever/Code/Directory Name With Space/prototype/bundle/gems/gems/spring-2.0.1/lib/spring/client/run.rb:76:in `spawn': No such file or directory - /Users/therocketforever/Code/Directory (Errno::ENOENT)
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bundle/gems/gems/spring-2.0.1/lib/spring/client/run.rb:76:in `boot_server'
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bundle/gems/gems/spring-2.0.1/lib/spring/client/run.rb:56:in `cold_run'
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bundle/gems/gems/spring-2.0.1/lib/spring/client/run.rb:33:in `rescue in call'
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bundle/gems/gems/spring-2.0.1/lib/spring/client/run.rb:30:in `call'
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bundle/gems/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bundle/gems/gems/spring-2.0.1/lib/spring/client/rails.rb:24:in `call'
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bundle/gems/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bundle/gems/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bundle/gems/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bundle/gems/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bundle/gems/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bin/spring:15:in `require'
	from /Users/therocketforever/Code/Directory Name With Space/prototype/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

### System configuration
```
macOS Sierra v10.12
Rails 5.0.1
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
rbenv 1.1.10
```

**Comment by y-yagi** [comment]
It seems to be an issue of [spring](https://github.com/rails/spring), not rails.

**Comment by maclover7** [comment]
Agree with @y-yagi; can you open up an issue [here](https://github.com/rails/spring/issues/new) with spring? Thanks!
