### ISSUE TITLE
override rails scaffold template, raise incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by oslivan** [rails/rails#28090]
I modify 'index.html.erb' as below 
```
<% attributes.reject(&:password_digest?).each do |attribute| -%>
  <th><%= I18n.t("activerecord.attributes.#{singular_table_name}.#{attribute.index_name}") %></th>
<% end -%>
```
but I execute command of scaffold, raise below exception
```
      create      app/views/words/index.html.erb
(erb):23:in `concat': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
        from (erb):23:in `template'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `result'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/file_manipulation.rb:116:in `block in template'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:53:in `render'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:62:in `open'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:62:in `block in invoke!'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:60:in `invoke!'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions.rb:95:in `action'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:25:in `create_file'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/file_manipulation.rb:115:in `template'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/generators/named_base.rb:26:in `block in template'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/generators/named_base.rb:64:in `inside_template'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/generators/named_base.rb:25:in `template'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/generators/erb/scaffold/scaffold_generator.rb:19:in `block (2 levels) in copy_view_files'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/generators/erb/scaffold/scaffold_generator.rb:17:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/generators/erb/scaffold/scaffold_generator.rb:17:in `block in copy_view_files'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/generators/erb/scaffold/scaffold_generator.rb:16:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/generators/erb/scaffold/scaffold_generator.rb:16:in `copy_view_files'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/group.rb:277:in `block in _invoke_for_class_method'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/shell.rb:68:in `with_padding'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/group.rb:266:in `_invoke_for_class_method'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/group.rb:133:in `_invoke_from_option_template_engine'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/group.rb:277:in `block in _invoke_for_class_method'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/shell.rb:68:in `with_padding'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/group.rb:266:in `_invoke_for_class_method'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/group.rb:133:in `_invoke_from_option_scaffold_controller'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/generators.rb:180:in `invoke'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:145:in `generate_or_destroy'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:60:in `generate'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```
If I use `attribute.human_name`, it will not report this, please tell me how to solve it ? thanks.

**Comment by al2o3cr** [comment]
The [relevant line](https://github.com/erikhuda/thor/blob/e6754167bd8bf184d426bac6c271af820b03bda7/lib/thor/actions/file_manipulation.rb#L116) in `thor` is reading the template with `File.binread`, which defaults to opening the file in `ASCII-8BIT`. That at least explains where that encoding is coming from.

Can you post a excerpt of the related section of your translation file? My guess is that there's at least one UTF-8-only value in there.

**Comment by oslivan** [comment]
@al2o3cr You are right, My custom template have chinese chars, I try to remove them, I found  it can execute now, thanks to your reply.

**Comment by sikachu** [comment]
Closing this as you've found the issue and it was fixed. Please let me know if that's not the case.
