### ISSUE TITLE
Action Cable config use config/cable.yml.erb is not work.

### ISSUE THREAD

**Issue by zw963** [rails/rails#28118]
I had see some others issue about the name of AC config file.

But I think maybe cable.yml.erb should be support like following:

config/cable.yml.erb

```yml
development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV.fetch('ACTION_CABLE_REDIS_URL', 'redis://127.0.0.1:6380/1') %>

production:
  adapter: redis
  url: <%= ENV.fetch('ACTION_CABLE_REDIS_URL', 'redis://127.0.0.1:6380/1') %>
```

But it not work.

```rb
NoMethodError in App::MessagesController#create

undefined method `fetch' for nil:NilClass
Extracted source (around line #24):

#22       # Also makes sure proper dependencies are required.
#23       def pubsub_adapter
*24         adapter = (cable.fetch('adapter') { 'redis' })
#25         path_to_adapter = "action_cable/subscription_adapter/#{adapter}"
#26         begin
#27           require path_to_adapter

Extracted source (around line #72):

#70       # Adapter used for all streams/broadcasting.
#71       def pubsub
*72         @pubsub || @mutex.synchronize { @pubsub ||= config.pubsub_adapter.new(self) }
#73       end
#74 
#75       # All of the identifiers applied to the connection class associated with this server.

Extracted source (around line #214):

#212     mon_enter
#213     begin
*214       yield
#215     ensure
#216       mon_exit
#217     end


Rails.root: /ershou_web

Application Trace
app/models/chatroom.rb:32:in `broadcast'
app/controllers/app/messages_controller.rb:132:in `create'

Framework Trace
actioncable (5.0.0.1) lib/action_cable/server/configuration.rb:24:in `pubsub_adapter'
actioncable (5.0.0.1) lib/action_cable/server/base.rb:72:in `block in pubsub'
/usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
actioncable (5.0.0.1) lib/action_cable/server/base.rb:72:in `pubsub'
actioncable (5.0.0.1) lib/action_cable/server/broadcasting.rb:43:in `broadcast'
actioncable (5.0.0.1) lib/action_cable/server/broadcasting.rb:23:in `broadcast'
actioncable (5.0.0.1) lib/action_cable/channel/broadcasting.rb:13:in `broadcast_to'
actionpack (5.0.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
http_accept_language (2.0.5) lib/http_accept_language/middleware.rb:14:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
puma (3.6.0) lib/puma/configuration.rb:225:in `call'
puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
puma (3.6.0) lib/puma/server.rb:415:in `process_client'
puma (3.6.0) lib/puma/server.rb:275:in `block in run'
puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'

Full Trace
actioncable (5.0.0.1) lib/action_cable/server/configuration.rb:24:in `pubsub_adapter'
actioncable (5.0.0.1) lib/action_cable/server/base.rb:72:in `block in pubsub'
/usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
actioncable (5.0.0.1) lib/action_cable/server/base.rb:72:in `pubsub'
actioncable (5.0.0.1) lib/action_cable/server/broadcasting.rb:43:in `broadcast'
actioncable (5.0.0.1) lib/action_cable/server/broadcasting.rb:23:in `broadcast'
actioncable (5.0.0.1) lib/action_cable/channel/broadcasting.rb:13:in `broadcast_to'
app/models/chatroom.rb:32:in `broadcast'
app/controllers/app/messages_controller.rb:132:in `create'
actionpack (5.0.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
http_accept_language (2.0.5) lib/http_accept_language/middleware.rb:14:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
puma (3.6.0) lib/puma/configuration.rb:225:in `call'
puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
puma (3.6.0) lib/puma/server.rb:415:in `process_client'
puma (3.6.0) lib/puma/server.rb:275:in `block in run'
puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'



Request parameters
{"chatroom_id"=>"1455890096677978112",
 "content"=>"12121",
 "random"=>"5705083249"}

Session dump
_csrf_token: "8+qBLEqY7TqOnlcIt6a3XyJ4Fb7u+P5wwMcao26T6no="
session_id: "965aca407b1b283b499896d1ded68e8d"

Env dump
GATEWAY_INTERFACE: "CGI/1.2"
HTTP_ACCEPT: "*/*"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "zh-CN,zh;q=0.8"
HTTP_ORIGIN: "http://app.sg.mymart.com"
HTTP_VERSION: "HTTP/1.0"
HTTP_X_CSRF_TOKEN: "jO9AJhPPGekoTAMovSxuo4jP6Y1BGVdlbF+DcGcDRpB/BcEKWVf006bSVCAKitn8qrf8M6/hqRWsmJnTCZCs6g=="
HTTP_X_FORWARDED_FOR: "172.18.0.1"
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "127.0.0.1"
SERVER_NAME: "app.sg.mymart.com"
SERVER_PROTOCOL: "HTTP/1.1"

Response headers
None
```

Rails version: 5.0.0.1
Ruby version: 2.3.3

**Comment by maclover7** [comment]
@zw963 the only supported configuration file for Action Cable is `config/cable.yml` 😬

**Comment by zw963** [comment]
@maclover7 , I have just try the same config content, only keep the origin `config/cable.yml` 
name not changed, like following:

config/cable.yml

```yml
development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV.fetch('ACTION_CABLE_REDIS_URL', 'redis://127.0.0.1:6380/1') %>

production:
  adapter: redis
  url: <%= ENV.fetch('ACTION_CABLE_REDIS_URL', 'redis://127.0.0.1:6380/1') %>
```

It worked!!

This confuse me a little ..., `YAML` format file is support erb even though yml not 
exist `erb` extension name. : )

Maybe this not a bug, just for a little more document. Thanks!

I will keep this issue open, Thanks

**Comment by rafaelfranca** [comment]
database.yml and secret.yml also behave like that. They are yaml files that support ERB. It is already a convention in the framework.

**Comment by zw963** [comment]
@rafaelfranca , Thanks
