### ISSUE TITLE
ActiveModel::MissingAttributeError: can't write unknown attribute

### ISSUE THREAD

**Issue by cerdiogenes** [rails/rails#28192]
I has a has_and_belongs_to_many and when I try to `model.relations << other_model` I get the error:

ActiveModel::MissingAttributeError: can't write unknown attribute `model_id`

It's on Rails 5.1.0.beta1

**Comment by clinoge** [comment]
Care to share more details as the database structure, a portion of the code or a
minimal example that produces the same bug?

It'd be easier for us to aid you if any of the above were provided :-).

**Comment by cerdiogenes** [comment]
This is my migration:

```ruby
class CreateEventsUsers < ActiveRecord::Migration[4.2]
  def change
    create_table :events_users, id: false do |t|
      t.references :event, index: true, foreign_key: true
      t.references :user, index: true, foreign_key: true
    end
  end
end
```

I found that it's a kind of incompatibility with schema_plus_foreign_keys. The DDL generated with this gem is:

```sql
CREATE TABLE public.events_users
(
  event_id integer,
  user_id integer,
  CONSTRAINT fk_events_users_event_id FOREIGN KEY (event_id)
      REFERENCES public.events (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_events_users_user_id FOREIGN KEY (user_id)
      REFERENCES public.users (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
```

I have a simple habtm in my Event model: `has_and_belongs_to_many :administrators, class_name: User`. With this DDL when I execute `Event.last.administrators.to_sql` I get:

"SELECT \"users\".* FROM \"users\" WHERE \"users\".\"event_id\" = 1"

Without the gem, my DDL is:

```sql
CREATE TABLE public.events_users
(
  event_id integer,
  user_id integer,
  CONSTRAINT fk_rails_0ea30c0a1c FOREIGN KEY (event_id)
      REFERENCES public.events (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_rails_c32bae0acf FOREIGN KEY (user_id)
      REFERENCES public.users (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
```

Not that different, but when I execute `Event.last.administrators.to_sql` I get the right SQL:

"SELECT \"users\".* FROM \"users\" INNER JOIN \"events_users\" ON \"users\".\"id\" = \"events_users\".\"user_id\" WHERE \"events_users\".\"event_id\" = 1"

I think that this is a regression that can be eliminated for 5.1.0 release. I will also test Rails 5.0 and provide a feedback soon.

**Comment by cerdiogenes** [comment]
With Rails 5.0.1 I can't add indexes to the relation table, when I try to execute `Event.last.administrators` I get a stack trace:

```
NoMethodError: undefined method `match' for #<Class:0x005606c40c1270>
Did you mean?  catch
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/dynamic_matchers.rb:21:in `method_missing'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/inheritance.rb:137:in `compute_type'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/associations/builder/has_and_belongs_to_many.rb:20:in `klass'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/associations/builder/has_and_belongs_to_many.rb:14:in `join_table'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/associations/builder/has_and_belongs_to_many.rb:57:in `table_name'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/core.rb:254:in `arel_table'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/core.rb:290:in `relation'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/scoping/named.rb:38:in `default_scoped'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/scoping/named.rb:28:in `all'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/associations/through_association.rb:17:in `block in target_scope'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/associations/through_association.rb:16:in `each'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/associations/through_association.rb:16:in `target_scope'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/associations/association.rb:86:in `scope'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/associations/collection_association.rb:448:in `scope'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/associations/collection_proxy.rb:36:in `initialize'
	from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/relation/delegation.rb:100:in `new'
... 14 levels...
	from /usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/commands/rails.rb:6:in `call'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/command_wrapper.rb:38:in `call'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:191:in `block in serve'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:161:in `fork'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:161:in `serve'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /usr/local/bundle/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

This happens with/without gem 'schema_plus_foreign_keys' and also happens with `create_join_table` method:

```ruby
class CreateJoinTableEventUser < ActiveRecord::Migration[5.0]
  def change
    create_join_table :events, :users do |t|
      t.index [:event_id, :user_id]
      # t.index [:user_id, :event_id]
    end
  end
end
```

**Comment by robin850** [comment]
Hi there !

I guess you should rather write:

~~~ruby
create_join_table :events, :users do |t|
  t.index :event_id
  t.index :user_id
end
~~~

Since the SQL discrepancy seems to be related to schema_plus_foreign_keys, we can give this a close. Feel free to comment there if I'm wrong and this should be re-opened. Thanks for reporting anyway ! :-)
