### ISSUE TITLE
Rails 4.2.8: Error related to rails-api

### ISSUE THREAD

**Issue by Petercopter** [rails/rails#28205]
Getting this error when running rspec after upgrading to Rails 4.2.8 with rails-api 4.1.2
```
/Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:196:in `method_missing': undefined method `setup_generators!' for Cluster::Application:Class (NoMethodError)
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rails-api-0.4.0/lib/rails-api/application.rb:38:in `block in <class:Application>'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:93:in `inherited'
	from /Users/petercopter/work/cluster/config/application.rb:9:in `<module:Cluster>'
	from /Users/petercopter/work/cluster/config/application.rb:8:in `<top (required)>'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/petercopter/work/cluster/config/environment.rb:2:in `<top (required)>'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/petercopter/work/cluster/spec/spec_helper.rb:8:in `<top (required)>'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `block in requires='
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `each'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `requires='
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `each'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:99:in `setup'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/petercopter/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /Users/petercopter/.rbenv/versions/2.3.3/bin/rspec:22:in `load'
	from /Users/petercopter/.rbenv/versions/2.3.3/bin/rspec:22:in `<main>'
```

related
https://github.com/rails-api/rails-api/issues/221

**Comment by rafaelfranca** [comment]
This is a rails-api bug. API mode of Rails is only officially supported starting in the version 5.0

**Comment by ilchanka** [comment]
@rafaelfranca Isn't this a change of Rails API in minor version release? Version 4.2.7.1 and lower works as expected.

**Comment by epinault** [comment]
@rafaelfranca : this is 4.2.8, a patch version.. should not introduce any breakage like this I would think since it works in 4.2.7.x

**Comment by rafaelfranca** [comment]
It was a bug fix so the behavior that it was relying was a buggy behavior. A patch version is exactly to fix bugs.

**Comment by Petercopter** [comment]
It looks like the rails-api guys are on top of it. Thanks everyone! 👍 
https://github.com/rails-api/rails-api/issues/221
