### ISSUE TITLE
ArgumentError when attempting to boot `rails console`

### ISSUE THREAD

**Issue by gabeodess** [rails/rails#28234]
### Steps to reproduce
Possibly related to Draper.  No errors when starting the server, but when I try to start the console it chokes.

### Expected behavior
Rails console should boot without issue.

### Actual behavior
Console fails to load.
```
$rails c
Running via Spring preloader in process 17800
/Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/actionpack-5.1.0.beta1/lib/action_controller/test_case.rb:39:in `create': wrong number of arguments (given 0, expected 1) (ArgumentError)
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/draper-3.0.0.pre1/lib/draper/view_context/build_strategy.rb:41:in `block in controller'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/draper-3.0.0.pre1/lib/draper/view_context/build_strategy.rb:40:in `tap'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/draper-3.0.0.pre1/lib/draper/view_context/build_strategy.rb:40:in `controller'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/draper-3.0.0.pre1/lib/draper/view_context/build_strategy.rb:30:in `call'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/draper-3.0.0.pre1/lib/draper/view_context.rb:49:in `build'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/draper-3.0.0.pre1/lib/draper/railtie.rb:55:in `block in <class:Railtie>'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/railtie.rb:228:in `block in run_console_blocks'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/railtie.rb:250:in `each'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/railtie.rb:250:in `each_registered_block'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/railtie.rb:228:in `run_console_blocks'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/application.rb:458:in `block in run_console_blocks'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/engine/railties.rb:13:in `each'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/engine/railties.rb:13:in `each'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/application.rb:458:in `run_console_blocks'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/engine.rb:442:in `load_console'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/commands/console/console_command.rb:27:in `initialize'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/commands/console/console_command.rb:17:in `new'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/commands/console/console_command.rb:17:in `start'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/commands/console/console_command.rb:85:in `perform'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/command/base.rb:63:in `perform'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/command.rb:44:in `invoke'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/railties-5.1.0.beta1/lib/rails/commands.rb:16:in `<top (required)>'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:292:in `require'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:292:in `require'
	from /Users/gabeodess/Sites/beyond/bin/rails:9:in `<top (required)>'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:286:in `load'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:286:in `block in load'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/gabeodess/.rvm/gems/ruby-2.3.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:286:in `load'
	from /Users/gabeodess/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/gabeodess/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

### System configuration
**Rails version**: 5.1.0.beta1

**Ruby version**: 2.3.0

**Comment by y-yagi** [comment]
It seems that it has already been fixed in https://github.com/drapergem/draper/pull/759

**Comment by pixeltrix** [comment]
@y-yagi thanks for the info - closing 👍
