### ISSUE TITLE
uuid primary key type confusion

### ISSUE THREAD

**Issue by mkozjak** [rails/rails#28441]
### Steps to reproduce

Setup config/application.rb:
```
config.active_record.primary_key = :uuid
```
Or
```
config.generators do |g|
    g.orm :active_record, primary_key_type: :uuid
end
```

Create a model:

With a generator:
```
rails generate model genre name:string
```

Or manually:
```
   create_table "genres", id: false, force: :cascade do |t|
     t.primary_key :id, :uuid, default: nil
     t.string   "name"
     t.datetime "created_at", null: false
     t.datetime "updated_at", null: false
   end
```

Create a new migration editing a column:
```
class AddFoo < ActiveRecord::Migration[5.0]
  def change
    rename_column :genres, :name, :label
  end
end
```

### Expected behavior

Renamed column in Genre.

### Actual behavior
Exception:
```
== 20170316023237 AddFoo: migrating ===========================================
-- rename_column(:genres, :name, :label)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: object name reserved for internal use: sqlite_autoindex_genres_1: CREATE UNIQUE INDEX "sqlite_autoindex_genres_1" ON "genres" ("id")
/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize'
/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:232:in `block in execute'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:232:in `execute'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:713:in `add_index'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:493:in `block in copy_table_indexes'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:476:in `each'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:476:in `copy_table_indexes'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:469:in `copy_table'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:445:in `move_table'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:440:in `block in alter_table'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:437:in `alter_table'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:421:in `rename_column'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/db/migrate/20170316023237_add_foo.rb:3:in `change'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1134:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'


e3::SQLException: object name reserved for internal use: sqlite_autoindex_genres_1: CREATE UNIQUE INDEX "sqlite_autoindex_genres_1" ON "genres" ("id")
/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize'
/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:232:in `block in execute'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:232:in `execute'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:713:in `add_index'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:493:in `block in copy_table_indexes'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:476:in `each'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:476:in `copy_table_indexes'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:469:in `copy_table'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:445:in `move_table'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:440:in `block in alter_table'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:437:in `alter_table'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:421:in `rename_column'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/db/migrate/20170316023237_add_foo.rb:3:in `change'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1134:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'


served for internal use: sqlite_autoindex_genres_1
/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize'
/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
/vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:232:in `block in execute'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:232:in `execute'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:713:in `add_index'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:493:in `block in copy_table_indexes'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:476:in `each'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:476:in `copy_table_indexes'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:469:in `copy_table'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:445:in `move_table'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:440:in `block in alter_table'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:437:in `alter_table'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:421:in `rename_column'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/db/migrate/20170316023237_add_foo.rb:3:in `change'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1134:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

Development environment with sqlite3.

Btw, To be honest, the documentation on this is very scarse. Am I doing something wrong? What's the right approach to have uuid as a primary key, then?

Also, this works on postgresql!

Thanks.

**Comment by strangeworks** [comment]
Not sure that it is a rails feature, according to the sqlite documentation sqlite doesn't seem to support uuid data type out of the box http://www.sqlite.org/datatype3.html comparing to postgresql where it is already here.

**Comment by rafaelfranca** [comment]
That is right uuid is not supported by sqlite
