### ISSUE TITLE
HABTM broken when primary_key_prefix_type set 

### ISSUE THREAD

**Issue by mlarraz** [rails/rails#28502]
HABTM defaults to expecting a join table without a primary key.

However, if `.primary_key_prefix_type` is set, inserts to the join table will attempt to write to its primary key.

### Steps to reproduce
```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Base.primary_key_prefix_type = :table_name_with_underscore

ActiveRecord::Schema.define do
  create_table :students
  create_table :teachers

  create_join_table(:students, :teachers)
end

class Student < ActiveRecord::Base
  has_and_belongs_to_many :teachers
end

class Teacher < ActiveRecord::Base
  has_and_belongs_to_many :students
end

class BugTest < Minitest::Test
  def test_association
    student = Student.create!
    teacher = Teacher.create!

    student.teachers << teacher
  end
end
```

### Expected behavior
The anonymous `through` model should not assume its table has a primary key, but instead check with the db before attempting to insert.

### Actual behavior
The anonymous through-model derives its primary key from the global `primary_key_prefix_type` and assumes this key exists.

Note that changing the `has_and_belongs_to_many` to a `has_many :through` and using an explicit model lets you work around this by setting `.primary_key = nil`, but this defeats the purpose of `has_and_belongs_to_many`.

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.3.1

**Comment by vipulnsward** [comment]
I am not sure, if the test you have written is meant to fail? It doesn't on master.

**Comment by mlarraz** [comment]
Sure. I've updated the example to remove the `assert_raises`, because that is not the intended behavior.

**Comment by mlarraz** [comment]
This still fails on both `master` and `5-1-stable`.

I'm dumping my local stacktrace for convenience:

```
ActiveModel::MissingAttributeError: can't write unknown attribute `habtm_teachers_id`
    /Users/mlarraz/rails/activerecord/lib/active_record/attribute.rb:205:in `with_value_from_database'
    /Users/mlarraz/rails/activerecord/lib/active_record/attribute_set.rb:54:in `write_from_user'
    /Users/mlarraz/rails/activerecord/lib/active_record/attribute_methods/write.rb:39:in `write_attribute'
    /Users/mlarraz/rails/activerecord/lib/active_record/attribute_methods/primary_key.rb:24:in `id='
    /Users/mlarraz/rails/activerecord/lib/active_record/persistence.rb:590:in `_create_record'
    /Users/mlarraz/rails/activerecord/lib/active_record/counter_cache.rb:178:in `_create_record'
    /Users/mlarraz/rails/activerecord/lib/active_record/locking/optimistic.rb:75:in `_create_record'
    /Users/mlarraz/rails/activerecord/lib/active_record/attribute_methods/dirty.rb:295:in `_create_record'
    /Users/mlarraz/rails/activerecord/lib/active_record/callbacks.rb:340:in `block in _create_record'
    /Users/mlarraz/rails/activesupport/lib/active_support/callbacks.rb:130:in `run_callbacks'
    /Users/mlarraz/rails/activesupport/lib/active_support/callbacks.rb:825:in `_run_create_callbacks'
    /Users/mlarraz/rails/activerecord/lib/active_record/callbacks.rb:340:in `_create_record'
    /Users/mlarraz/rails/activerecord/lib/active_record/timestamp.rb:94:in `_create_record'
    /Users/mlarraz/rails/activerecord/lib/active_record/persistence.rb:563:in `create_or_update'
    /Users/mlarraz/rails/activerecord/lib/active_record/callbacks.rb:336:in `block in create_or_update'
    /Users/mlarraz/rails/activesupport/lib/active_support/callbacks.rb:130:in `run_callbacks'
    /Users/mlarraz/rails/activesupport/lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
    /Users/mlarraz/rails/activerecord/lib/active_record/callbacks.rb:336:in `create_or_update'
    /Users/mlarraz/rails/activerecord/lib/active_record/persistence.rb:162:in `save!'
    /Users/mlarraz/rails/activerecord/lib/active_record/validations.rb:50:in `save!'
    /Users/mlarraz/rails/activerecord/lib/active_record/attribute_methods/dirty.rb:42:in `save!'
    /Users/mlarraz/rails/activerecord/lib/active_record/transactions.rb:313:in `block in save!'
    /Users/mlarraz/rails/activerecord/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
    /Users/mlarraz/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:224:in `transaction'
    /Users/mlarraz/rails/activerecord/lib/active_record/transactions.rb:210:in `transaction'
    /Users/mlarraz/rails/activerecord/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
    /Users/mlarraz/rails/activerecord/lib/active_record/transactions.rb:313:in `save!'
    /Users/mlarraz/rails/activerecord/lib/active_record/suppressor.rb:46:in `save!'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/has_many_through_association.rb:89:in `save_through_record'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/has_many_through_association.rb:45:in `insert_record'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/collection_association.rb:434:in `block (2 levels) in concat_records'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/collection_association.rb:448:in `replace_on_target'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/collection_association.rb:281:in `add_to_target'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/collection_association.rb:433:in `block in concat_records'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/collection_association.rb:431:in `each'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/collection_association.rb:431:in `concat_records'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/has_many_association.rb:114:in `concat_records'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/has_many_through_association.rb:27:in `concat_records'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/collection_association.rb:114:in `block in concat'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/collection_association.rb:129:in `block in transaction'
    /Users/mlarraz/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:226:in `block in transaction'
    /Users/mlarraz/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
    /Users/mlarraz/.rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
    /Users/mlarraz/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
    /Users/mlarraz/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:226:in `transaction'
    /Users/mlarraz/rails/activerecord/lib/active_record/transactions.rb:210:in `transaction'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/collection_association.rb:128:in `transaction'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/collection_association.rb:114:in `concat'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/has_many_through_association.rb:21:in `concat'
    /Users/mlarraz/rails/activerecord/lib/active_record/associations/collection_proxy.rb:1051:in `<<'
    habtm.rb:39:in `test_normal'
```
