### ISSUE TITLE
ActiveRecord::StatementInvalid in v4.2 when using except on default_scope with where clause hash conditions

### ISSUE THREAD

**Issue by rossta** [rails/rails#28505]
In ActiveRecord 4.2.xx, a relation with a `default_scope` that uses `except` will throw a `ActiveRecord::StatementInvalid` error if the default scope is a `where` condition with a hash as arguments.

The issue was possibly introduced by 11e8badb.

### Expected behavior

Assuming a typical Rails setup with the following models:

```ruby
class Blog < ActiveRecord::Base
  default_scope { where(number: 1) }
end

class Clog < ActiveRecord::Base
  default_scope { where("number = ?", 1) }
end
```

The following should both return the first instance of the model with the number 2.

```ruby
Blog.except(:where).where(number: 2).first # => #<Blog number: 2>
Clog.except(:where).where(number: 2).first # => #<Clog number: 2>
```

### Actual behavior

With ActiveRecord 4.2.xx and postgresql, the `Blog` example throws the following error:

```
# postgresql
ActiveRecord::StatementInvalid: PG::ProtocolViolation: ERROR:  bind message supplies 2 parameters, but prepared statement "a2" requires 1
: SELECT  "blogs".* FROM "blogs" WHERE "blogs"."number" = $1  ORDER BY "blogs"."id" ASC LIMIT 1
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
    /Users/ross/.gem/ruby/2.3.1/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:336:in `select'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/querying.rb:39:in `find_by_sql'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/relation.rb:638:in `exec_queries'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/relation.rb:514:in `load'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/relation.rb:243:in `to_a'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:512:in `find_nth_with_limit'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:496:in `find_nth'
    /Users/ross/.gem/ruby/2.3.1/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:139:in `first'
    default_scope_with_except/bug.rb:124:in `test_default_scope_where_conditions_hash_with_except'
```

In `sqlite3`, I observed a similar error: `ActiveRecord::StatementInvalid: SQLite3::RangeException`.

### Steps to reproduce

The behavior can be reproduced with the following script.

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

version = "4.2.0"
adapter = :sqlite3

connection_opts = case adapter
                  when :postgresql
                    {
                      adapter: "postgresql",
                      encoding: "unicode",
                      database: "default_scope_development",
                      pool: 5,
                      username: "postgres",
                      password: ""
                    }
                  else
                    {
                      :adapter  => "sqlite3",
                      :database => "memory"
                    }
                  end

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", version

  gem adapter.to_s
end

require "active_record"
require "minitest/autorun"
require "minitest/pride"
require "logger"

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(connection_opts)
logger = Logger.new(STDOUT)
ActiveRecord::Base.logger = logger

logger.info "Using adapter #{adapter}"
logger.info "Using ActiveRecord version #{version}"

ActiveRecord::Schema.define do
  create_table :blogs, :force => true do |t|
    t.integer :number
  end

  create_table :clogs, :force => true do |t|
    t.integer :number
  end

  create_table :drogs, :force => true do |t|
    t.integer :number
  end

  create_table :flogs, :force => true do |t|
    t.integer :number
  end
end

class Blog < ActiveRecord::Base
  default_scope { where(number: 1) }
end

class Clog < ActiveRecord::Base
  default_scope { where("number ?", 1) }
end

class Drog < ActiveRecord::Base
  default_scope { order(number: :asc) }
end

class Flog < ActiveRecord::Base
  default_scope { order("number ASC") }
end

class DefaultScopeWithExceptTest < Minitest::Test
  def setup
    ActiveRecord::Base.descendants.each(&:delete_all)
  end

  ###########################################################
  # This test fails with activerecord >= 4.2.0              #
  ###########################################################
  def test_default_scope_where_conditions_hash_with_except
    Blog.create(number: 1)

    expected_blog = Blog.create(number: 2)

    actual_blog = Blog.except(:where).where(number: 2).first

    assert_equal expected_blog, actual_blog
  end

  ###########################################################
  # The following tests all pass with activerecord ~> 4.1.0 #
  ###########################################################
  def test_default_scope_where_conditions_splat_with_except
    Clog.create(number: 1)

    expected_clog = Clog.create(number: 2)

    actual_clog = Clog.except(:where).where(number: 2).first

    assert_equal expected_clog, actual_clog

    actual_clog = Clog.except(:where).where("number = ?", 2).first

    assert_equal expected_clog, actual_clog
  end

  def test_default_scope_order_conditions_hash_with_except
    Drog.create(number: 1)
    Drog.create(number: 2)

    expected_drog = Drog.create(number: 3)

    actual_drog = Drog.except(:order).order(number: :desc).first

    assert_equal expected_drog, actual_drog
  end

  def test_default_scope_order_conditions_splat_with_except
    Flog.create(number: 1)
    Flog.create(number: 2)

    expected_flog = Flog.create(number: 3)

    actual_flog = Flog.except(:order).order(number: :desc).first

    assert_equal expected_flog, actual_flog
  end
end
```

Running git bisect with a variation of the script above indicated that commit 11e8badb may have introduced the issue.

### System configuration

Rails version: 4.2.8

Ruby version: 2.3.1

I hope that's all clear... Thanks!!!

**Comment by maclover7** [comment]
Hi @rossta!

Looking into what's going on `4-2-stable`. Unfortunately, `4-2-stable` is transitioning soon to be in "security fixes only mode". On the bright side, I can confirm that all of the tests above pass and work as expected on `5-0-stable` and `master` :)

**Comment by rossta** [comment]
Hi @maclover7! 

Thanks for following up. If I can find out more info about what's going on, I'll report back until it's confirmed this is a no-fix.

**Comment by kamipo** [comment]
It works as expected on 5.0, 5.1, and master.
