### ISSUE TITLE
5.1.0.rc1. Problem on heroku during `rake db:migrate`.

### ISSUE THREAD

**Issue by mrkongo** [rails/rails#28508]
### Steps to reproduce

Just updated my Gemfile with:

```
# gem 'rails', '5.1.0.beta1'
gem 'rails', '~> 5.1.0.rc1'
```
and everything works (including migrate) on my local machine.

But after `git push heroku master` I need to run `heroku run rake db:migrate` and here we go:

```
$ heroku run rake db:migrate
Running rake db:migrate on myApp... up, run.4825 (Free)
[Scout] [03/21/17 17:32:34 +0000 run.4825 (4)] WARN : Deferring agent start. Standing by for first request
I, [2017-03-21T17:32:34.961399 #4]  INFO -- : ** [Opbeat] Starting client
I, [2017-03-21T17:32:34.961654 #4]  INFO -- : ** [Opbeat] Client running
rake aborted!
ActiveSupport::MessageEncryptor::InvalidMessage: ActiveSupport::MessageEncryptor::InvalidMessage
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/message_encryptor.rb:133:in `rescue in _decrypt'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/message_encryptor.rb:112:in `_decrypt'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/message_encryptor.rb:84:in `decrypt_and_verify'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/secrets.rb:47:in `decrypt'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/secrets.rb:92:in `preprocess'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/secrets.rb:28:in `block in parse'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/secrets.rb:25:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/secrets.rb:25:in `each_with_object'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/secrets.rb:25:in `parse'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:389:in `secrets'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:172:in `key_generator'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:203:in `message_verifier'
/app/vendor/bundle/ruby/2.4.0/gems/globalid-0.3.7/lib/global_id/railtie.rb:25:in `block (2 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:43:in `execute_hook'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:30:in `instance_exec'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:30:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:59:in `block in run_initializers'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:58:in `run_initializers'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:353:in `initialize!'
/app/config/environment.rb:5:in `<top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/opbeat-3.0.10/lib/opbeat/injections.rb:74:in `require'
/app/vendor/bundle/ruby/2.4.0/gems/opbeat-3.0.10/lib/opbeat/injections.rb:74:in `require'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:329:in `require_environment!'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:443:in `block in run_tasks_blocks'
/app/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'

/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'

/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'

/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
ArgumentError: invalid base64
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/message_encryptor.rb:113:in `block in _decrypt'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/message_encryptor.rb:113:in `map'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/message_encryptor.rb:113:in `_decrypt'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/message_encryptor.rb:84:in `decrypt_and_verify'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/secrets.rb:47:in `decrypt'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/secrets.rb:92:in `preprocess'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/secrets.rb:28:in `block in parse'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/secrets.rb:25:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/secrets.rb:25:in `each_with_object'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/secrets.rb:25:in `parse'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:389:in `secrets'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:172:in `key_generator'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:203:in `message_verifier'
/app/vendor/bundle/ruby/2.4.0/gems/globalid-0.3.7/lib/global_id/railtie.rb:25:in `block (2 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:43:in `execute_hook'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:30:in `instance_exec'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:30:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:59:in `block in run_initializers'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:58:in `run_initializers'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:353:in `initialize!'
/app/config/environment.rb:5:in `<top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/opbeat-3.0.10/lib/opbeat/injections.rb:74:in `require'
/app/vendor/bundle/ruby/2.4.0/gems/opbeat-3.0.10/lib/opbeat/injections.rb:74:in `require'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:329:in `require_environment!'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.0.rc1/lib/rails/application.rb:443:in `block in run_tasks_blocks'
/app/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'

/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'

/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'

/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

Can it be **Opbeat** the problem?

**Ruby version**: 2.4.0
**Heroku stack**: heroku-16

**Comment by mrkongo** [comment]
I tryed to remove OpBeat. It's the same. It's not OpBeat.

**Comment by kaspth** [comment]
Thanks for trying out the rc! Are you using the encrypted secrets by any chance? We changed the encryption mechanism in rc1, but forgot to mention that in the release post. Try this upgrade script: https://gist.github.com/kaspth/bc37989c2f39a5642112f28b1d93f343

**Comment by mrkongo** [comment]
Maybe this is the problem. Can you explain it better?

What is this code?

**Comment by kaspth** [comment]
It's the ramifications of https://github.com/rails/rails/pull/28139.

Run the script I linked if you have a `config/secrets.yml.enc` file in your project.

**Comment by mrkongo** [comment]
I made it. The same problem. The app crash.

My operations:

- Downloaded that .rb gist in my Rails folder.

- Executed `bin/rails runner upgrade_encrypted_secrets.rb`

- Pushed everything to Heroku.

- The same error.

I need to re-encrypt my keys before pushing?

**Comment by kaspth** [comment]
Yes, you'd want to take the newly key generated in this file here: https://gist.github.com/kaspth/bc37989c2f39a5642112f28b1d93f343#file-upgrade_encrypted_secrets-rb-L17

Then replace your `RAILS_MASTER_KEY` env var on Heroku.

**Comment by mrkongo** [comment]
Now it works good! Thanks a lot!

**Comment by kaspth** [comment]
Glad to hear it! Please keep reporting issues with the RC if you come across any ❤️

**Comment by kaspth** [comment]
Oh and make sure to place the encryption 🔑 in a password manager!
