### ISSUE TITLE
Preloading associations with string foreign keys fails

### ISSUE THREAD

**Issue by matortheeternal** [rails/rails#28574]
### Steps to reproduce

See https://github.com/rails/rails/pull/14855/commits/4debc86bd329d31360272ed15459cde3b9af3a10#diff-b1215e38a98827a4b1b61271a6bf1ba8

### Expected behavior
Including an association with a string foreign key should not raise an exception.

My association is:

```rb
belongs_to :first_plugin, :foreign_key => 'first_plugin_filename', :class_name => 'Plugin', :primary_key => 'filename'
```

### Actual behavior
```
"undefined method `each' for nil:NilClass"
```

Stacktrace:
```
0: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader/association.rb:93:in `block in associated_records_by_owner'"
1: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader/association.rb:92:in `each'"
2: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader/association.rb:92:in `associated_records_by_owner'"
3: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader/singular_association.rb:9:in `preload'"
4: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader/association.rb:20:in `run'"
5: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader.rb:146:in `block (2 levels) in preloaders_for_one'"
6: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader.rb:144:in `each'"
7: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader.rb:144:in `map'"
8: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader.rb:144:in `block in preloaders_for_one'"
9: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader.rb:143:in `each'"
10: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader.rb:143:in `flat_map'"
11: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader.rb:143:in `preloaders_for_one'"
12: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader.rb:115:in `preloaders_on'"
13: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader.rb:103:in `block in preload'"
14: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader.rb:102:in `each'"
15: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader.rb:102:in `flat_map'"
16: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/associations/preloader.rb:102:in `preload'"
17: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/relation.rb:645:in `block in exec_queries'"
18: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/relation.rb:644:in `each'"
19: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/relation.rb:644:in `exec_queries'"
20: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/relation.rb:515:in `load'"
21: "E:/dev/lang/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/relation.rb:243:in `to_a'"
```

Appears to be related to #14734

### System configuration
**Rails version**: 4.2.5

**Ruby version**: 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

**Comment by matortheeternal** [comment]
I have some more information, it appears this may actually be due to a case insensitivity issue.

```rb
(byebug) owner_key
"hothtrooper44_ArmorCompilation.esp"
(byebug) owners_map.keys
["TradeRoutes.esp", "ADS.esp", "ChaosDragons.esp", "RealisticNeedsandDiseases.esp", "Helgen Reborn.esp", "Book Covers Skyrim.esp", "Hothtrooper44_Armo
rCompilation.esp", "Frostfall.esp", "Campfire.esm", "MoonAndStar_MAS.esp", "Tel_Nalta.esp", "AuroraVillage.esp", "ELFX - Exteriors.esp"]
```

This is likely my fault for setting up a foreign key relation where there are multiple records with the same key.

**Comment by matortheeternal** [comment]
Closed because I'm going to say this is a matter of user error.
