### ISSUE TITLE
Double save plus attribute_changed? deprecation warning if save called from before_save

### ISSUE THREAD

**Issue by hult** [rails/rails#28599]
### Steps to reproduce

I have the following app

```ruby
class Order < ApplicationRecord
  has_many :details
  validate :validate_name, if: lambda { |obj| obj.name_changed? }

  def validate_name
    puts "validate_name"
  end
end

class Detail < ApplicationRecord
  belongs_to :order
  before_save :update_order

  def update_order
    order.name += ' (updated)'
    order.save
  end
end
```

(As you can see, `Detail#save` can be called from the before_save callback since `Order#save` saves its children.)

Now, do

```ruby
o = Order.create! name: 'An order'
o.details.create!
```

### Expected behavior
I expect this to work without deprecation warnings.

### Actual behavior
I'm getting a deprecation warning that suggest the behavior of `attribute_changed?` changed from inside after callbacks, but this is not inside one (I could of course not use the deprecation warning's suggested fix of changing to `saved_change_to_attribute?` since it's not saved yet).

> DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead. (called from block in <class:MyModel> at /Users/magnus/Code/rails_test/api/app/models/my_model.rb:2)

### System configuration
**Rails version**: 5.1.0.rc1 and master

**Ruby version**: 2.4.1

**Comment by betesh** [comment]
@hult Can you show us a stack trace?

I suspect (though I can't be certain without a stack trace) that some after_save callback built into ActiveRecord runs validations, possibly one of the callbacks added by [this method](https://github.com/rails/rails/blob/v5.1.0.rc1/activerecord/lib/active_record/autosave_association.rb#L179)

If that's the case, it's quite possible that #28596 fixes this.

**Comment by hult** [comment]
I made my validation condition lambda a function and put `puts caller` in it just before calling `attribute_changed?`, don't know if that's enough for you?

```
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:177:in `block (2 levels) in halting_and_conditional'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:177:in `each'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:177:in `all?'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:177:in `block in halting_and_conditional'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:507:in `block in invoke_before'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:507:in `each'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:507:in `invoke_before'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:130:in `run_callbacks'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:825:in `_run_validate_callbacks'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activemodel-5.1.0.rc1/lib/active_model/validations.rb:405:in `run_validations!'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activemodel-5.1.0.rc1/lib/active_model/validations/callbacks.rb:110:in `block in run_validations!'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activemodel-5.1.0.rc1/lib/active_model/validations/callbacks.rb:110:in `run_validations!'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activemodel-5.1.0.rc1/lib/active_model/validations.rb:335:in `valid?'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/validations.rb:65:in `valid?'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/validations.rb:82:in `perform_validations'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/validations.rb:44:in `save'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/attribute_methods/dirty.rb:35:in `save'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:308:in `block (2 levels) in save'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:223:in `transaction'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:210:in `transaction'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:308:in `block in save'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:307:in `save'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/suppressor.rb:42:in `save'
/Users/magnus/Code/fisk2/app/models/detail.rb:8:in `update_order'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:600:in `catch'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:600:in `block in default_terminator'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:198:in `block in halting'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:507:in `block in invoke_before'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:507:in `each'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:507:in `invoke_before'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:130:in `run_callbacks'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/callbacks.rb:336:in `create_or_update'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/persistence.rb:154:in `save!'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/validations.rb:50:in `save!'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:313:in `block in save!'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:223:in `transaction'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:210:in `transaction'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:313:in `save!'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/suppressor.rb:46:in `save!'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/associations/has_many_association.rb:36:in `insert_record'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/associations/collection_association.rb:388:in `block (2 levels) in _create_record'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/associations/collection_association.rb:296:in `replace_on_target'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/associations/collection_association.rb:280:in `add_to_target'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/associations/collection_association.rb:386:in `block in _create_record'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/associations/collection_association.rb:128:in `block in transaction'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/connection_adapters/abstract/transaction.rb:186:in `within_new_transaction'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/transactions.rb:210:in `transaction'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/associations/collection_association.rb:127:in `transaction'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/associations/collection_association.rb:385:in `_create_record'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/associations/has_many_association.rb:126:in `_create_record'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/associations/association.rb:190:in `create!'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0.rc1/lib/active_record/associations/collection_proxy.rb:360:in `create!'
(irb):2:in `irb_binding'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/workspace.rb:87:in `eval'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/workspace.rb:87:in `evaluate'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/context.rb:381:in `evaluate'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:493:in `block (2 levels) in eval_input'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:627:in `signal_status'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:490:in `block in eval_input'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `loop'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `catch'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:489:in `eval_input'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:430:in `block in run'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:429:in `catch'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:429:in `run'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:385:in `start'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0.rc1/lib/rails/commands/console/console_command.rb:62:in `start'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0.rc1/lib/rails/commands/console/console_command.rb:17:in `start'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0.rc1/lib/rails/commands/console/console_command.rb:85:in `perform'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0.rc1/lib/rails/command/base.rb:63:in `perform'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0.rc1/lib/rails/command.rb:44:in `invoke'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0.rc1/lib/rails/commands.rb:16:in `<top (required)>'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `require'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `block in require'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `require'
/Users/magnus/Code/fisk2/bin/rails:9:in `<top (required)>'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:286:in `load'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:286:in `block in load'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:286:in `load'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/commands/rails.rb:6:in `call'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/command_wrapper.rb:38:in `call'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application.rb:191:in `block in serve'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application.rb:161:in `fork'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application.rb:161:in `serve'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
/Users/magnus/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/magnus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
```

**Comment by betesh** [comment]
From your stack trace, it looks like my guess was wrong.  It looks unrelated to #28596

**Comment by alexcameron89** [comment]
Running `git bisect`, it looks like it may have introduced in 9eee7822ac4bce983ad45a98c4d111eb36285199 which fixes #27434.

**Comment by alexcameron89** [comment]
Running git bisect, it looks like 9eee782 may have introduced the behavior, although I'm not sure why yet. It does look like it's trying to update the order twice. The deprecation for me comes between the two updates:
```
D, [2017-03-30T11:58:29.424014 #10670] DEBUG -- :    (0.0ms)  begin transaction
validate_name
D, [2017-03-30T11:58:29.424904 #10670] DEBUG -- :   SQL (0.1ms)  INSERT INTO "orders" ("name") VALUES (?)  [["name", "An order"]]
D, [2017-03-30T11:58:29.425170 #10670] DEBUG -- :    (0.0ms)  commit transaction
D, [2017-03-30T11:58:29.431287 #10670] DEBUG -- :    (0.0ms)  begin transaction
validate_name
D, [2017-03-30T11:58:29.435896 #10670] DEBUG -- :   SQL (0.2ms)  UPDATE "orders" SET "name" = ? WHERE "orders"."id" = ?  [["name", "An order (updated)"], ["id", 1]]
DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead. (called from block in <class:Order> at 28599.rb:38)
validate_name
D, [2017-03-30T11:58:29.436978 #10670] DEBUG -- :   SQL (0.1ms)  UPDATE "orders" SET "name" = ? WHERE "orders"."id" = ?  [["name", "An order (updated) (updated)"], ["id", 1]]
D, [2017-03-30T11:58:29.437509 #10670] DEBUG -- :   SQL (0.1ms)  INSERT INTO "details" ("order_id") VALUES (?)  [["order_id", 1]]
D, [2017-03-30T11:58:29.437892 #10670] DEBUG -- :    (0.0ms)  commit transaction
Run options: --seed 32067

```

**Comment by hult** [comment]
Well, the code in the example is not very good, since Detail, in its
before_save, saves the Order it belongs to, which in turn detects that it
has an unsaved Detail and saves it, which triggers another run of
before_save from within the first.

It's probably not something you ever want to do for real, but that being
said, my app did it and it worked until I tried to upgrade to 5.1.0.rc1.

I don't know how Rails should react, but pretty sure a deprecation message
about after save hooks is not it.
Le jeu. 30 mars 2017 à 19:04, Alex Kitchens <notifications@github.com> a
écrit :

**Comment by rafaelfranca** [comment]
cc @kamipo

**Comment by alexcameron89** [comment]
@hult what's strange though, is before that commit, one update runs:
```
D, [2017-03-30T15:25:19.846028 #55019] DEBUG -- :    (0.1ms)  BEGIN
validate_name
D, [2017-03-30T15:25:19.847074 #55019] DEBUG -- :   SQL (0.3ms)  INSERT INTO "orders" ("name") VALUES ($1) RETURNING "id"  [["name", "An order"]]
D, [2017-03-30T15:25:19.847584 #55019] DEBUG -- :    (0.3ms)  COMMIT
D, [2017-03-30T15:25:19.853375 #55019] DEBUG -- :    (0.1ms)  BEGIN
validate_name
D, [2017-03-30T15:25:19.857699 #55019] DEBUG -- :   SQL (0.2ms)  UPDATE "orders" SET "name" = $1 WHERE "orders"."id" = $2  [["name", "An order (updated)"], ["id", 1]]
D, [2017-03-30T15:25:19.858332 #55019] DEBUG -- :   SQL (0.3ms)  INSERT INTO "details" ("order_id") VALUES ($1) RETURNING "id"  [["order_id", 1]]
D, [2017-03-30T15:25:19.858778 #55019] DEBUG -- :    (0.3ms)  COMMIT
```

**Comment by alexcameron89** [comment]
FYI, [here's a reproducible script](https://gist.github.com/alexcameron89/ac5f084f9793aeafa0003eaa6d2ce6cc) for the issue. There is the deprecation, and also because the update is running twice, it concats the order name with `(updated)` twice: 
```
  1) Failure:
BugTest#test_association_stuff [28599.rb:62]:
Expected: "An order (updated)"
  Actual: "An order (updated) (updated)"
```

The script passes on 4.2.6, fails on master.

**Comment by hult** [comment]
@alexcameron89 That's right, I didn't see the issue until I tried to upgrade, so I guessed it was there before too. The double update doesn't happen in 5.0.1.

**Comment by alexcameron89** [comment]
#28640 looks to fix the issue for me, thanks @kamipo!
