### ISSUE TITLE
DATABASE_URL affect database config when play rails test.

### ISSUE THREAD

**Issue by zw963** [rails/rails#28633]
Following is my config/database.yml
```yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: postgres
  password: 123456
  host: <%= ENV.fetch('DATABASE_HOSTNAME', '127.0.0.1') %>
  port: 5432

development:
  <<: *default
  database: ershou_web_development

test:
  <<: *default
  database: ershou_web_test
```

Occasionally, I export this environment variable  with:

```sh
export DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/abcdefg_production
```

And, then run `rails test` in current development machine. (RAILS_ENV is not set)

```sh
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `rescue in connect': FATAL:  database "abcdefg_production" does not exist (ActiveRecord::NoDatabaseError)
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `connect'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:91:in `connection'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/migration.rb:1042:in `needs_migration?'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/migration.rb:577:in `load_schema_if_pending!'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/migration.rb:592:in `block in maintain_test_schema!'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/migration.rb:823:in `suppress_messages'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/migration.rb:597:in `method_missing'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/migration.rb:592:in `maintain_test_schema!'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/railties-5.0.2/lib/rails/test_help.rb:15:in `<top (required)>'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /home/zw963/Xthink/ershou_web/test/test_helper.rb:3:in `<top (required)>'
	from /home/zw963/Xthink/ershou_web/test/controllers/admin_panel/categories_controller_test.rb:1:in `require'
	from /home/zw963/Xthink/ershou_web/test/controllers/admin_panel/categories_controller_test.rb:1:in `<top (required)>'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/railties-5.0.2/lib/rails/test_unit/test_requirer.rb:11:in `require'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/railties-5.0.2/lib/rails/test_unit/test_requirer.rb:11:in `block in require_files'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/railties-5.0.2/lib/rails/test_unit/test_requirer.rb:10:in `each'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/railties-5.0.2/lib/rails/test_unit/test_requirer.rb:10:in `require_files'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/railties-5.0.2/lib/rails/test_unit/minitest_plugin.rb:86:in `plugin_rails_init'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/minitest-5.10.1/lib/minitest.rb:80:in `block in init_plugins'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/minitest-5.10.1/lib/minitest.rb:78:in `each'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/minitest-5.10.1/lib/minitest.rb:78:in `init_plugins'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/minitest-5.10.1/lib/minitest.rb:129:in `run'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/railties-5.0.2/lib/rails/test_unit/minitest_plugin.rb:72:in `run'
	from /home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/minitest-5.10.1/lib/minitest.rb:62:in `block in autorun'
```

But, we expect, we use the config which exists in `config/database.yml`.

Rails version: 5.0.2
Ruby version: 2.3.3

Thanks

**Comment by matthewd** [comment]
That's expected behaviour; `DATABASE_URL` overrides `database.yml`.
