### ISSUE TITLE
MySQL 8.0.1 DMR : ActiveRecord::StatementInvalid: Mysql2::Error: Unknown collation: 'utf8_0900_ai_ci'

### ISSUE THREAD

**Issue by yahonda** [rails/rails#28730]
Since MySQL 8.0.1 DMR is released https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html
two of unit tests are getting errors `ActiveRecord::StatementInvalid: Mysql2::Error: Unknown collation: 'utf8_0900_ai_ci'`

### Steps to reproduce

```ruby
$ cd activerecord
$ ARCONN=mysql2 bundle exec ruby -w -Itest test/cases/adapters/mysql2/schema_migrations_test.rb -n /for_encoding_utf8mb4/
```
### Expected behavior
They should pass. It used to pass with the previous version of MySQL DMR 8.0.0.

### Actual behavior
```ruby
$ cd activerecord
$ ARCONN=mysql2 bundle exec ruby -w -Itest test/cases/adapters/mysql2/schema_migrations_test.rb -n /for_encoding_utf8mb4/
/home/yahonda/git/rails/activesupport/lib/active_support/core_ext/enumerable.rb:20: warning: method redefined; discarding old sum
Using mysql2
Run options: -n /for_encoding_utf8mb4/ --seed 13322

# Running:

EE

Finished in 0.165948s, 12.0520 runs/s, 0.0000 assertions/s.

  1) Error:
SchemaMigrationsTest#test_initializes_internal_metadata_for_encoding_utf8mb4:
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown collation: 'utf8_0900_ai_ci': CREATE TABLE `ar_internal_metadata` (`key` varchar(255) COLLATE utf8_0900_ai_ci NOT NULL PRIMARY KEY, `value` varchar(255), `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB
    /home/yahonda/git/mysql2/lib/mysql2/client.rb:120:in `_query'
    /home/yahonda/git/mysql2/lib/mysql2/client.rb:120:in `block in query'
    /home/yahonda/git/mysql2/lib/mysql2/client.rb:119:in `handle_interrupt'
    /home/yahonda/git/mysql2/lib/mysql2/client.rb:119:in `query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:210:in `block (2 levels) in execute'
    /home/yahonda/git/rails/activesupport/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
    /home/yahonda/git/rails/activesupport/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
    /home/yahonda/git/rails/activesupport/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:209:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block (2 levels) in log'
    /home/yahonda/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:208:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:290:in `create_table'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:349:in `create_table'
    /home/yahonda/git/rails/activerecord/lib/active_record/internal_metadata.rb:34:in `create_table'
    test/cases/adapters/mysql2/schema_migrations_test.rb:30:in `block in test_initializes_internal_metadata_for_encoding_utf8mb4'
    test/cases/adapters/mysql2/schema_migrations_test.rb:47:in `with_encoding_utf8mb4'
    test/cases/adapters/mysql2/schema_migrations_test.rb:26:in `test_initializes_internal_metadata_for_encoding_utf8mb4'


  2) Error:
SchemaMigrationsTest#test_initializes_schema_migrations_for_encoding_utf8mb4:
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown collation: 'utf8_0900_ai_ci': CREATE TABLE `schema_migrations` (`version` varchar(255) COLLATE utf8_0900_ai_ci NOT NULL PRIMARY KEY) ENGINE=InnoDB
    /home/yahonda/git/mysql2/lib/mysql2/client.rb:120:in `_query'
    /home/yahonda/git/mysql2/lib/mysql2/client.rb:120:in `block in query'
    /home/yahonda/git/mysql2/lib/mysql2/client.rb:119:in `handle_interrupt'
    /home/yahonda/git/mysql2/lib/mysql2/client.rb:119:in `query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:210:in `block (2 levels) in execute'
    /home/yahonda/git/rails/activesupport/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
    /home/yahonda/git/rails/activesupport/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
    /home/yahonda/git/rails/activesupport/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:209:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block (2 levels) in log'
    /home/yahonda/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:208:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:290:in `create_table'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:349:in `create_table'
    /home/yahonda/git/rails/activerecord/lib/active_record/schema_migration.rb:27:in `create_table'
    test/cases/adapters/mysql2/schema_migrations_test.rb:19:in `block in test_initializes_schema_migrations_for_encoding_utf8mb4'
    test/cases/adapters/mysql2/schema_migrations_test.rb:47:in `with_encoding_utf8mb4'
    test/cases/adapters/mysql2/schema_migrations_test.rb:15:in `test_initializes_schema_migrations_for_encoding_utf8mb4'

2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
$
```

### System configuration
**Rails version**: * Rails master branch + Gemfile change to workaround https://github.com/brianmario/mysql2/issues/838

```ruby
   group :db do
     gem "pg", ">= 0.18.0"
     gem "mysql2", github: "yahonda/mysql2", branch: "mysql801"
   end
 end
```

**Ruby version**:
```
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```

* MySQL 8.0.1 [DMR ](urlhttps://dev.mysql.com/doc/mysql-development-cycle/en/development-milestone-releases.html)

```sql
mysql> select @@version;
+-----------+
| @@version |
+-----------+
| 8.0.1-dmr |
+-----------+
1 row in set (0.00 sec)
```

**Comment by yahonda** [comment]
I am not familiar with MySQL collation and character set. Here are character set related information I can get.

```sql
mysql> show create database activerecord_unittest;
+-----------------------+--------------------------------------------------------------------------------------------------------+
| Database              | Create Database                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------+
| activerecord_unittest | CREATE DATABASE `activerecord_unittest` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */ |
+-----------------------+--------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> show create database activerecord_unittest2;
+------------------------+---------------------------------------------------------------------------------------------------------+
| Database               | Create Database                                                                                         |
+------------------------+---------------------------------------------------------------------------------------------------------+
| activerecord_unittest2 | CREATE DATABASE `activerecord_unittest2` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */ |
+------------------------+---------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql>
```

```sql
mysql> show variables like 'character%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.01 sec)

mysql>
```

**Comment by rafaelfranca** [comment]
What is the return of `show variables collation_database`? It seems to be related with https://github.com/rails/rails/blob/acc5a55118515227537d0e7b8b129b303cfaf667/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L70-L76

**Comment by kamipo** [comment]
Since MySQL 8.0.1 (DMR2) has changed the default collation of Unicode to xxx_0900_ai_ci (Unicode 9.0.0, Accent Insensitive, Case Insensitive).
Looks like that mysql2 doesn't support new collation for now.

**Comment by kamipo** [comment]
Ah I see. MySQL 8.0.1 (DMR2) has changed the default collation of utf8mb4 to utf8mb4_0900_ai_ci and has added new collations but utf8 is not.
We can't fallback utf8mb4_0900_ai_ci to utf8_0900_ai_ci.

**Comment by yahonda** [comment]
Here is the output of `collation_database`.

```sql
mysql> show variables like 'collation_database';
+--------------------+--------------------+
| Variable_name      | Value              |
+--------------------+--------------------+
| collation_database | utf8mb4_0900_ai_ci |
+--------------------+--------------------+
1 row in set (0.00 sec)

mysql>
```

**Comment by cd-mansoor-hassan** [comment]
Hey guys, I've been facing the same issue myself. I understand why the issue persists but does anyone have any suitable solution for this? PS: Still a rookie at rails.
