### ISSUE TITLE
Attribute type class not used for column value serialization in has_one through association

### ISSUE THREAD

**Issue by jgraichen** [rails/rails#28816]
### Steps to reproduce

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :banks, id: :string, force: true do |t|
  end

  create_table :customers, id: :string, force: true do |t|
    t.string :bank_id
  end

  create_table :accounts, id: :string, force: true do |t|
    t.string :customer_id
  end
end

UuidObject = ::Struct.new(:str) do
  def to_s; str; end
end

module Types
  class UUID < ActiveRecord::Type::Value
    def serialize(value)
      value.to_s
    end

    def cast(value)
      UuidObject.new(value.to_s)
    end
  end
end

class Bank < ActiveRecord::Base
  attribute :id, ::Types::UUID.new
end

class Customer < ActiveRecord::Base
  attribute :id, ::Types::UUID.new
  attribute :bank_id, ::Types::UUID.new

  belongs_to :bank
end

class Account < ActiveRecord::Base
  attribute :id, ::Types::UUID.new
  attribute :customer_id, ::Types::UUID.new

  belongs_to :customer
  has_one :bank, through: :customer
end

BANK_UUID = 'f4032ea2-7cc5-4a4f-af97-8d8e748076dc'
CUSTOMER_UUID = '8f291dc9-3c10-41a0-bbf9-129e71655b12'
ACCOUNT_UUID = 'fade82c3-982e-450b-bff7-7c18a7ab53c9'

class BugTest < Minitest::Test
  def test_association_stuff
    bank = Bank.create! id: BANK_UUID
    customer = Customer.create! id: CUSTOMER_UUID, bank: bank
    account = Account.create! id: ACCOUNT_UUID, customer: customer

    assert_equal bank.id, account.bank.id
  end
end
```

#### Result

```
BugTest#test_association_stuff:
TypeError: can't cast UuidObject
    /active_record/connection_adapters/abstract/quoting.rb:38:in `rescue in type_cast'
    /active_record/connection_adapters/abstract/quoting.rb:25:in `type_cast'
    /active_record/connection_adapters/abstract/quoting.rb:148:in `block in type_casted_binds'
    /active_record/connection_adapters/abstract/quoting.rb:148:in `map'
    /active_record/connection_adapters/abstract/quoting.rb:148:in `type_casted_binds'
    /active_record/connection_adapters/sqlite3_adapter.rb:198:in `exec_query'
    /active_record/connection_adapters/abstract/database_statements.rb:365:in `select_prepared'
    /active_record/connection_adapters/abstract/database_statements.rb:40:in `select_all'
    /active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'
    /active_record/querying.rb:39:in `find_by_sql'
    /active_record/statement_cache.rb:107:in `execute'
    /active_record/associations/singular_association.rb:50:in `find_target'
    /active_record/associations/association.rb:147:in `load_target'
    /active_record/associations/association.rb:53:in `reload'
    /active_record/associations/singular_association.rb:7:in `reader'
    /active_record/associations/builder/association.rb:111:in `bank'
    bug.rb:81:in `test_association_stuff'
```

### Expected behavior

I expected to get the bank record reachable through the has-one-through association.

### Actual behavior

Invoking the association raised a `TypeError` as the `UuidObject` could not be casted.

Stack shows the following on Rails `5.0.2`:
```
--> #0  rescue in ActiveRecord::ConnectionAdapters::Quoting.rescue in type_cast(value#UuidObject, column#NilClass) at /activerecord-5.0.2/lib/active_record/connection_adapters/abstract/quoting.rb:41
    #1  ActiveRecord::ConnectionAdapters::Quoting.type_cast(value#UuidObject, column#NilClass) at /activerecord-5.0.2/lib/active_record/connection_adapters/abstract/quoting.rb:30
    #2  block in ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.block in exec_cache(sql#String, name#String, binds#Array) at /activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:603
    ͱ-- #3  Array.map at /activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:603
    #4  ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.exec_cache(sql#String, name#String, binds#Array) at /activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:603
    #5  ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.execute_and_clear(sql#String, name#String, binds#Array, prepare#TrueClass) at /activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:589
    #6  ActiveRecord::ConnectionAdapters::PostgreSQL::DatabaseStatements.exec_query(sql#String, name#String, binds#Array, prepare#TrueClass) at /activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:103
    #7  ActiveRecord::ConnectionAdapters::DatabaseStatements.select_prepared(sql#String, name#String, binds#Array) at /activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:377
    #8  ActiveRecord::ConnectionAdapters::DatabaseStatements.select_all(arel#String, name#String, binds#Array, preparable#TrueClass) at /activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:39
    #9  ActiveRecord::ConnectionAdapters::QueryCache.select_all(arel#String, name#String, binds#Array, preparable#TrueClass) at /activerecord-5.0.2/lib/active_record/connection_adapters/abstract/query_cache.rb:95
    #10 ActiveRecord::Querying.find_by_sql(sql#String, binds#Array, preparable#TrueClass, &block#NilClass) at /activerecord-5.0.2/lib/active_record/querying.rb:39
    #11 ActiveRecord::StatementCache.execute(params#Array, klass#Class, connection#ActiveRecord::ConnectionAdapters::PostgreSQLAdapter, &block#NilClass) at /activerecord-5.0.2/lib/active_record/statement_cache.rb:109
    #12 ActiveRecord::Associations::SingularAssociation.get_records at /activerecord-5.0.2/lib/active_record/associations/singular_association.rb:65
    #13 ActiveRecord::Associations::SingularAssociation.find_target at /activerecord-5.0.2/lib/active_record/associations/singular_association.rb:69
    #14 ActiveRecord::Associations::Association.load_target at /activerecord-5.0.2/lib/active_record/associations/association.rb:138
    #15 ActiveRecord::Associations::Association.reload at /activerecord-5.0.2/lib/active_record/associations/association.rb:53
    #16 ActiveRecord::Associations::SingularAssociation.reader(force_reload#FalseClass) at /activerecord-5.0.2/lib/active_record/associations/singular_association.rb:14
    #17 Trace::GeneratedAssociationMethods.platform(*args#Array) at /activerecord-5.0.2/lib/active_record/associations/builder/association.rb:111
```

As `column` is `nil` it will not try to use the type class to serialize the value in [ActiveRecord::ConnectionAdapters::Quoting#type_cast](https://github.com/rails/rails/blob/ef0b05e/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L24-L39):

```ruby
      def type_cast(value, column = nil)
        # ...

        if column
          value = type_cast_from_column(column, value)
        end

        # ...
      end
```

### System configuration
**Rails version**: `5.0.2`, rails/rails@ef0b05e78fb0
**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by maclover7** [comment]
After a long trip through the Active Record jungle, turns out the issue was that `Bank` did not declare any associations with `Customer`. Adding `has_one :customer` to `Bank` makes the tests pass :)

**Comment by jgraichen** [comment]
Interesting. I didn't expect that because other associations are working without the reverse direction. I can confirm with the fix it works in our application too. Thanks.
