### ISSUE TITLE
Chaining scope containing sub-select with order fails with PG::InvalidColumnReference 

### ISSUE THREAD

**Issue by gsar** [rails/rails#28890]
### Steps to reproduce

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :comments do |t|
    t.integer :likes_count, null: false, default: 0
  end
end

class Comment < ActiveRecord::Base
  scope :test_scope, ->{ where(id: select('DISTINCT(comments.id)')) }
end

[1,2].each {|n| Comment.create(likes_count: n) }

class BugTest < MiniTest::Test
  def test_scope_order
    assert_equal Comment.test_scope.order('comments.likes_count').to_a, Comment.order('comments.likes_count').test_scope.to_a
  end
end
```

### Expected behavior

Ordering while chaining `test_scope` and `order` should not matter, and the assertion in the test should pass.

### Actual behavior

Chaining `order` before `test_scope` fails with an exception.

### System configuration
**Rails version**: 5.2.0.alpha from git://github.com/rails/rails.git (at master@b6ac50b)

**Ruby version**: 2.4.1

**Comment by gsar** [comment]
Output for reference:

```
-- create_table(:comments)
D, [2017-04-26T13:03:45.019502 #107828] DEBUG -- :    (6.7ms)  CREATE TABLE "comments" ("id" bigserial primary key, "likes_count" integer DEFAULT 0 NOT NULL)
   -> 0.0308s
D, [2017-04-26T13:03:45.044723 #107828] DEBUG -- :    (16.9ms)  CREATE TABLE "ar_internal_metadata" ("key" character varying NOT NULL PRIMARY KEY, "value" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
D, [2017-04-26T13:03:45.055740 #107828] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.5ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
D, [2017-04-26T13:03:45.061330 #107828] DEBUG -- :    (0.3ms)  BEGIN
D, [2017-04-26T13:03:45.062874 #107828] DEBUG -- :   SQL (0.5ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "key"  [["key", "environment"], ["value", "development"], ["created_at", "2017-04-26 20:03:45.061711"], ["updated_at", "2017-04-26 20:03:45.061711"]]
D, [2017-04-26T13:03:45.069635 #107828] DEBUG -- :    (6.5ms)  COMMIT
D, [2017-04-26T13:03:45.078228 #107828] DEBUG -- :    (0.3ms)  BEGIN
D, [2017-04-26T13:03:45.079624 #107828] DEBUG -- :   SQL (0.6ms)  INSERT INTO "comments" ("likes_count") VALUES ($1) RETURNING "id"  [["likes_count", 1]]
D, [2017-04-26T13:03:45.080762 #107828] DEBUG -- :    (0.8ms)  COMMIT
D, [2017-04-26T13:03:45.081195 #107828] DEBUG -- :    (0.2ms)  BEGIN
D, [2017-04-26T13:03:45.082035 #107828] DEBUG -- :   SQL (0.4ms)  INSERT INTO "comments" ("likes_count") VALUES ($1) RETURNING "id"  [["likes_count", 2]]
D, [2017-04-26T13:03:45.082775 #107828] DEBUG -- :    (0.6ms)  COMMIT
Run options: --seed 57828

# Running:

D, [2017-04-26T13:03:45.090363 #107828] DEBUG -- :   Comment Load (0.8ms)  SELECT "comments".* FROM "comments" WHERE "comments"."id" IN (SELECT DISTINCT(comments.id) FROM "comments") ORDER BY comments.likes_count
D, [2017-04-26T13:03:45.091966 #107828] DEBUG -- :   Comment Load (0.4ms)  SELECT "comments".* FROM "comments" WHERE "comments"."id" IN (SELECT DISTINCT(comments.id) FROM "comments" ORDER BY comments.likes_count) ORDER BY comments.likes_count
E

Finished in 0.004323s, 231.2952 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_scope_order:
ActiveRecord::StatementInvalid: PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...CT DISTINCT(comments.id) FROM "comments" ORDER BY comments.l...
                                                             ^
: SELECT "comments".* FROM "comments" WHERE "comments"."id" IN (SELECT DISTINCT(comments.id) FROM "comments" ORDER BY comments.likes_count) ORDER BY comments.likes_count
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:613:in `async_exec'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:613:in `block (2 levels) in exec_no_cache'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activesupport/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activesupport/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activesupport/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:612:in `block in exec_no_cache'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block (2 levels) in log'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block in log'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `exec_no_cache'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `execute_and_clear'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:361:in `select'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:42:in `select_all'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/querying.rb:39:in `find_by_sql'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/relation.rb:660:in `exec_queries'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/relation.rb:547:in `load'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/relation.rb:255:in `records'
    /home/gsar/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-ce2abffc0e29/activerecord/lib/active_record/relation.rb:251:in `to_a'
    tst.rb:38:in `test_scope_order'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by gsar** [comment]
Note this bug affects all activeadmin index views that contain scopes with nested sub-selects and sortable columns.  The test case above is a much simplified version of the bug encountered with activeadmin.

**Comment by sgrif** [comment]
The order absolutely should matter. `self` in this case is whatever the current scope is, so of course the value of `select` in your scope changes based on what you've chained it on. You should explicitly call `unscoped` if that's what your desired behavior is.

**Comment by gsar** [comment]
@sgrif `unscoped` would change the semantics, so that doesn't work. How would you suggest rewriting the scope in the test to make it not produce invalid sql when it happens to be chained to a relation (assume the relation the scope is applied on is handed in from the outside) that has `order`?

**Comment by wasifhossain** [comment]
@sgrif if you don't mind, can you please re-open the issue as it is not yet solved?
