### ISSUE TITLE
`undefined method `new' for "Rack::Cors":String` on rails secrets:edit

### ISSUE THREAD

**Issue by BjornMelgaard** [rails/rails#28946]
### Steps to reproduce
On newly created project
```
$ rails secrets:setup
...output
$ rails secrets:edit
/home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/actionpack-5.1.0/lib/action_dispatch/middleware/stack.rb:35:in `build': undefined method `new' for "Rack::Cors":String (NoMethodError)
Did you mean?  next
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/actionpack-5.1.0/lib/action_dispatch/middleware/stack.rb:99:in `block in build'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/actionpack-5.1.0/lib/action_dispatch/middleware/stack.rb:99:in `each'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/actionpack-5.1.0/lib/action_dispatch/middleware/stack.rb:99:in `inject'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/actionpack-5.1.0/lib/action_dispatch/middleware/stack.rb:99:in `build'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/engine.rb:508:in `block in app'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/engine.rb:504:in `synchronize'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/engine.rb:504:in `app'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/application/finisher.rb:45:in `block in <module:Finisher>'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/initializable.rb:30:in `run'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/initializable.rb:59:in `block in run_initializers'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/initializable.rb:58:in `run_initializers'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/application.rb:353:in `initialize!'
        from /home/bjorn/projects/greenbadger-server/config/environment.rb:5:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/application.rb:329:in `require_environment!'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/command/actions.rb:16:in `require_application_and_environment!'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/commands/secrets/secrets_command.rb:34:in `edit'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/command/base.rb:63:in `perform'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/command.rb:44:in `invoke'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/railties-5.1.0/lib/rails/commands.rb:16:in `<top (required)>'
        from /home/bjorn/projects/greenbadger-server/bin/rails:9:in `require'
        from /home/bjorn/projects/greenbadger-server/bin/rails:9:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
        from /home/bjorn/.rvm/gems/ruby-2.4.0@greenbadger-server/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/bjorn/projects/greenbadger-server/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```
with and without `config.read_encrypted_secrets = true` in config/application.rb
### System configuration
**Rails version**: 5.1.0
**Ruby version**: 2.4.0
Archlinux

**Comment by BjornMelgaard** [comment]
I am sorry, its not rails problem

**Comment by simplyluke** [comment]
What was the issue @BjornMelgaard seeing the same issue on upgrading from 5 => 5.1

**Comment by kaspth** [comment]
You need to update the `"Rack::Cors"` middleware reference to use the class constant directly. 

It's not a Rails issue, but your app needing to upgrade. The commit that added the change: https://github.com/rails/rails/commit/83b767ce

Make sure your app outputs deprecation warnings, so you can spot these things. Thanks!

**Comment by adiakritos** [comment]
@kaspth  You rock for adding the solution to this thread! Thanks!

**Comment by simplyluke** [comment]
@kaspth is correct this was the issue we were hitting in older apps

**Comment by HanyMoh** [comment]
just remove the quotes.
`"Rack::Cors"` to `Rack::Cors`
look [here](https://stackoverflow.com/questions/44015266/error-when-running-rails-application)

**Comment by nsbotelho** [comment]
@HanyMoh thanks man! You're absolutely right!

**Comment by an-nasir** [comment]
> You need to update the `"Rack::Cors"` middleware reference to use the class constant directly.
> 
> It's not a Rails issue, but your app needing to upgrade. The commit that added the change: [83b767c](https://github.com/rails/rails/commit/83b767ce)
> 
> Make sure your app outputs deprecation warnings, so you can spot these things. Thanks!

AWESOME -- I was looking like a goat all over the net after fixing by finding the solution from somewhere else I just researched my problem so I can post answer BUT I got here, you have already answered --- What a moment for me
