### ISSUE TITLE
minitest 5.10.2 breaks rails test

### ISSUE THREAD

**Issue by eddroid** [rails/rails#29031]
### Steps to reproduce

```sh
rails new as_minitest
cd !$
rails g scaffold user name
rails test
```

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
```
Run options: --seed 38686

# Running:

.......

Finished in 1.440191s, 4.8605 runs/s, 6.2492 assertions/s.

7 runs, 9 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior

```
Running via Spring preloader in process 24376
Run options: --seed 57160

# Running:

.......

Finished in 2.190744s, 3.1953 runs/s, 4.1082 assertions/s.
/usr/local/lib/ruby/gems/2.4.0/gems/railties-5.1.0/lib/rails/test_unit/minitest_plugin.rb:9:in `aggregated_results': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:597:in `report'
	from /usr/local/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:687:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:687:in `report'
	from /usr/local/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:141:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/railties-5.1.0/lib/rails/test_unit/minitest_plugin.rb:77:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:63:in `block in autorun'
	from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:161:in `fork'
	from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:161:in `serve'
	from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

### System configuration
**Rails version**: confirmed on 5.1.0 and 5.0.2

**Ruby version**: 2.4.1p111

### Patch

Problem is in minitest 5.10.2. Downgrading to 5.10.1 fixes it.

```
echo "gem 'minitest', '5.10.1'" >> Gemfile
bundle update minitest
rails test
```

**Comment by ericboehs** [comment]
I decided to upgrade to Rails 5.1 yesterday and ran into this same problem. I couldn't find other reports so I thought I was going crazy.

It looks like this has already been fixed in https://github.com/rails/rails/pull/29022. It has also been backported to 5-1-stable. I'm sure this will be in the next release (e.g. 5.1.1). I think our options are:
- Use minitest 5.10.1
- Use 5-1-stable branch
- Wait for 5.1.1
- Monkey patch [this in](https://github.com/rails/rails/commit/a6dba93c4c4fa097300e94ad88fcfc18976082a4)
