### ISSUE TITLE
rails secrets:edit should have a nicer error message before it's initialized

### ISSUE THREAD

**Issue by dhh** [rails/rails#29194]
On a new app, if you do `rails secrets:edit` before you've called `rails secrets:setup`, you get this rough backtrace:

```
$ r secrets:edit
/Users/david/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/secrets.rb:49:in `binread': No such file or directory @ rb_sysopen - /Users/david/Code/examples/speeddial/config/secrets.yml.enc (Errno::ENOENT)
	from /Users/david/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/secrets.rb:49:in `read'
	from /Users/david/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/secrets.rb:59:in `read_for_editing'
	from /Users/david/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/secrets/secrets_command.rb:36:in `edit'
	from /Users/david/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/david/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/david/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/david/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
	from /Users/david/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
	from /Users/david/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
```

Would be nice to catch that and explain the need to run secrets:setup, or, even better, interactively ask if you wanted to run that now.

**Comment by nynhex** [comment]
@dhh I like this idea and I ran into the same thing because I didn't RTFM the first time when upgrading to 5.1.  I'm not even sure that the stacktrace is useful, more noise than anything.  But having it prompt and display a need to run secrets:setup and interactively ask to run would be ideal. 🤔

**Comment by kaspth** [comment]
It keeps the secrets secure by obscurity 😅

Yep, I'd like to look into this. 👍
