### ISSUE TITLE
RuntimeError (Digest::Base cannot be directly inherited in Ruby):

### ISSUE THREAD

**Issue by johnunclesam** [rails/rails#29274]
Sometimes I have this error, specially the first time I save a child entity when I boot up first time the server:

```
RuntimeError (Digest::Base cannot be directly inherited in Ruby):

rack (2.0.3) lib/rack/etag.rb:68:in `new'
rack (2.0.3) lib/rack/etag.rb:68:in `block in digest_body'
rack (2.0.3) lib/rack/deflater.rb:89:in `write'
rack (2.0.3) lib/rack/deflater.rb:84:in `close'
rack (2.0.3) lib/rack/deflater.rb:84:in `ensure in each'
rack (2.0.3) lib/rack/deflater.rb:85:in `each'
rack (2.0.3) lib/rack/etag.rb:66:in `digest_body'
rack (2.0.3) lib/rack/etag.rb:29:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
activerecord (5.1.1) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.1) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
railties (5.1.1) lib/rails/engine.rb:522:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Started GET "/api/myModel/33" for 172.18.0.1 at 2017-05-29 20:30:17 +0000
Processing by MyController#show as JSONAPI
```

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.1

What is it?

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by matthewd** [comment]
https://github.com/rack/rack/commit/c1437097dcdf92d53a692ca8135a3391791fbca3
