### ISSUE TITLE
Rails 5.1 STI - STI associations cannot be used with has_one

### ISSUE THREAD

**Issue by asurin** [rails/rails#29299]
### Steps to reproduce

Run the following test (Also verified with the `mysql2` adapter

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.1.1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :wedding do |t|
    t.string :name
    t.timestamps
  end
  create_table :url do |t|
    t.string :url
    t.string :type
    t.string :wedding_id
    t.timestamps
  end
end

class Url < ActiveRecord::Base
  self.table_name = 'url'
  belongs_to :wedding
end

class WeddingUrl < Url
end

class Wedding < ActiveRecord::Base
  self.table_name = 'wedding'
  has_one :wedding_url
end

class BugTest < Minitest::Test
  def test_sti_has_one
    w = Wedding.new(name: 'Test')
    w.save!
    url = WeddingUrl.new(url: 'http://www.test.com', wedding: w)
    url.save!
    puts w.wedding_url
  end
end
```

### Expected behavior
the wedding url object should be displayed

### Actual behavior
The following stack trace occurs:
```
Minitest::UnexpectedError: TypeError: can't cast Hash
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:45:in `rescue in type_cast'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:32:in `type_cast'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:166:in `block in type_casted_binds'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:166:in `map'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:166:in `type_casted_binds'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:206:in `exec_query'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:361:in `select'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:42:in `select_all'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/querying.rb:39:in `find_by_sql'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/statement_cache.rb:107:in `execute'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/associations/singular_association.rb:50:in `find_target'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/associations/association.rb:147:in `load_target'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/associations/association.rb:53:in `reload'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/associations/singular_association.rb:7:in `reader'
    /Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/associations/builder/association.rb:111:in `wedding_url'
    /Users/asurin/Development/repro-issue/lib/script/test_template.rb:59:in `test_sti_has_one'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:45:in `rescue in type_cast'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:32:in `type_cast'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:166:in `block in type_casted_binds'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:166:in `map'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:166:in `type_casted_binds'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:206:in `exec_query'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:361:in `select'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:42:in `select_all'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/querying.rb:39:in `find_by_sql'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/statement_cache.rb:107:in `execute'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/associations/singular_association.rb:50:in `find_target'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/associations/association.rb:147:in `load_target'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/associations/association.rb:53:in `reload'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/associations/singular_association.rb:7:in `reader'
/Users/asurin/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/associations/builder/association.rb:111:in `wedding_url'
/Users/asurin/Development/repro-issue/lib/script/test_template.rb:59:in `test_sti_has_one'
```

### System configuration
Rails: 5.1.1 (Cannot repro on Rails < 5.1)
Ruby: 2.4.1 (Can repro with 2.3.3)
Only gems installed/active are bundler, activerecord and sqlite3 (sqlite3-1.3.13)
Base system is OSX 10.12

**Comment by asurin** [comment]
Note that changing the name of the table OR the name of the field "url" appears to cause the issue to dissapear.  This appears to only affect tables where the name of the table is repeated in a column

**Comment by kamipo** [comment]
#29058 will fix the issue.

**Comment by asurin** [comment]
Awesome - thanks @kamipo

**Comment by lostapathy** [comment]
@asurin any reason not to close this at this point?

**Comment by asurin** [comment]
Nope - close away (Seems to be working with 5.1.4)

**Comment by kamipo** [comment]
Closing this since #29058 has already been backported in 7c0547e435c291503bcdaf9aed77765109065cfc.
