### ISSUE TITLE
Word "filter" in model name prevents creating it from params

### ISSUE THREAD

**Issue by kkarski82** [rails/rails#29437]
### Description

If you use the word "filter" in the model name you'll get `ActiveModel::ForbiddenAttributesError` whenever you try to set it from the params (update actions work fine, just create fails). I've tried it with `UserFilter` and `FilterSet` models so far.

### Steps to reproduce

```
[dev]$ rails g model UserFilter name:string
Running via Spring preloader in process 14950
      invoke  active_record
      create    db/migrate/20170613121732_create_user_filters.rb
      create    app/models/user_filter.rb
      invoke    test_unit
      create      test/models/user_filter_test.rb
      create      test/fixtures/user_filters.yml


[dev]$ rails db:migrate
== 20170613121732 CreateUserFilters: migrating ================================
-- create_table(:user_filters, {:id=>:uuid})
   -> 0.0066s
== 20170613121732 CreateUserFilters: migrated (0.0067s) =======================

[dev]$ rails c
Running via Spring preloader in process 15018
Loading development environment (Rails 5.0.3)
2.2.6 :001 > params = ActionController::Parameters.new({ user_filter: { name: 'new' } })
 => <ActionController::Parameters {"user_filter"=>{"name"=>"new"}} permitted: false> 
2.2.6 :002 > params.require(:user_filter).permit(:name)
 => <ActionController::Parameters {"name"=>"new"} permitted: true> 
2.2.6 :003 > model = UserFilter.new(params)
ActiveModel::ForbiddenAttributesError: ActiveModel::ForbiddenAttributesError
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activemodel-5.0.3/lib/active_model/forbidden_attributes_protection.rb:21:in `sanitize_for_mass_assignment'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activemodel-5.0.3/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activerecord-5.0.3/lib/active_record/core.rb:319:in `initialize'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activerecord-5.0.3/lib/active_record/inheritance.rb:65:in `new'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activerecord-5.0.3/lib/active_record/inheritance.rb:65:in `new'
        from (irb):3
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/railties-5.0.3/lib/rails/commands/console.rb:65:in `start'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/railties-5.0.3/lib/rails/commands/console_helper.rb:9:in `start'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/railties-5.0.3/lib/rails/commands.rb:18:in `<top (required)>'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
        from /home/kkarski/RubymineProjects/cloudtrack-api/bin/rails:9:in `<top (required)>'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:287:in `load'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:287:in `block in load'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/kkarski/.rvm/gems/ruby-2.2.6/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:287:in `load'
        from /home/kkarski/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/kkarski/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
2.2.6 :004 > quit
```

### Expected behavior

Object is created properly from valid and permitted params.

### Actual behavior

 `ActiveModel::ForbiddenAttributesError` is thrown.

### System configuration
**Rails version**: 5.0.3

**Ruby version**: 2.2.6

**Database**: PostgreSQL

**Comment by alexcameron89** [comment]
Hey @kkarski82, the issue is that calling `params.require(:user_filter).permit(:name)` does not mutate the original params, so params along will still not be permitted. Instead it returns the permitted params that you can store in another variable like `filtered_params`, or hide it behind a method like `user_filter_params`:

``` ruby
def user_filter_params
  params.require(:user_filter).permit(:name)
end
```
[Here is a script](https://gist.github.com/ff1bb871702483e60f88ade32cd1ae0f) showing the proper use.

**Comment by kkarski82** [comment]
The thing is, it doesn't want to work for me even this way. That's how I've actually come across this issue: my `create` action inside the UserFilterController was failing the tests all the time and throwing this error despite me hiding it behind a method, assigning it to a variable etc.

What puzzled me the most was that it kept doing so for scaffolds generated for models with "filter" somewhere in their name and only for create action (update action, which used the same method of obtaining params was working just fine).

**Comment by alexcameron89** [comment]
Would you mind providing us with a minimal Rails application so that I can reproduce your problem? I tried to recreate the issue in a Rails 5.0.3 app, but I am still not able to reproduce the issue.

**Comment by kkarski82** [comment]
I'll get to it later today. It might be that one of the gems in the app is messing with parameters somehow (Devise, CanCanCan etc.).

**Comment by kkarski82** [comment]
I can't seem to recreate this issue with clean application. Perhaps one day I'll find enough time to test it by adding the gems one by one and checking which one breaks it.

**Comment by kkarski82** [comment]
I can now confirm that it was caused by CanCanCan's `load_and_authorize_resource` behavior.
