### ISSUE TITLE
ActiveRecord 'after_commit on: :create' is incorrectly called on update and creates an infinite loop

### ISSUE THREAD

**Issue by dineshsprabu** [rails/rails#29465]
In Rails ActiveRecord i'm seeing a possibility for infinite loop on 'after_commit on: :create' callback when we try to **update** the same object inside **'after_commit on: :create'** callback method itself.

On the below script the User creation works fine. But on the Admin creation, the callback is called again, when I trigger an update of the object, on the callback method itself.

### Steps to reproduce

```
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'activerecord'
    gem 'mysql2'
  GEMFILE

  system 'bundle install'
end

require 'bundler'
Bundler.setup(:default)

require 'mysql2'
require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(
  adapter: 'mysql2',
  database: 'test',
  min_messages: 'warning'
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  message = "Running specs against #{ActiveRecord::Base.connection.adapter_name
  }, Active Record #{ActiveRecord::VERSION::STRING} and Arel #{Arel::VERSION}..."
  puts '=' * message.length, message, '=' * message.length

  create_table :admins, force: true do |t|
    t.boolean :instruction_email_sent
  end

  create_table :users, force: true do |t|
    t.boolean :verification_email_sent
  end
end


class User < ActiveRecord::Base
  after_commit :send_verification_email, on: :create

  # This runs successfully on create alone, as expected.
  def send_verification_email
    puts "Sending email...."
  end
end

class Admin < ActiveRecord::Base
  after_commit :send_instruction_email, on: :create

  def send_instruction_email
    puts "Sending email...."

    # On successfull send, update 'instruction_email_sent' to true.
    # Creates infinite loop, because of unwanted callback execution on update.
    self.update_attributes(instruction_email_sent: true)
  end
end

class BugTest < Minitest::Test
  def test_user_after_commit_on_create
    new_user = User.create

    # On successfull send, update 'verification_email_sent' to true.
    new_user.update_attributes(verification_email_sent: true)
  end

  def test_admin_after_commit_on_create
    Admin.create
  end
end
```

### Expected behavior
The **update** should not trigger the callback as it is marked as **on: :create**. It is expected to be same as User creation on the script.

Admin creation:

```
D, [2017-06-15T18:00:05.433264 #82085] DEBUG -- :    (0.2ms)  SET  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
===================================================================
Running specs against Mysql2, Active Record 5.1.1 and Arel 8.0.0...
===================================================================
-- create_table(:admins, {:force=>true})
D, [2017-06-15T18:00:05.436311 #82085] DEBUG -- :    (1.9ms)  DROP TABLE IF EXISTS `admins`
D, [2017-06-15T18:00:05.454887 #82085] DEBUG -- :    (18.0ms)  CREATE TABLE `admins` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `instruction_email_sent` tinyint(1)) ENGINE=InnoDB
   -> 0.0213s
-- create_table(:users, {:force=>true})
D, [2017-06-15T18:00:05.456264 #82085] DEBUG -- :    (1.0ms)  DROP TABLE IF EXISTS `users`
D, [2017-06-15T18:00:05.471734 #82085] DEBUG -- :    (15.2ms)  CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `verification_email_sent` tinyint(1)) ENGINE=InnoDB
   -> 0.0168s
D, [2017-06-15T18:00:05.505921 #82085] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.3ms)  SELECT  `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'environment' LIMIT 1
D, [2017-06-15T18:00:05.511445 #82085] DEBUG -- :    (0.2ms)  BEGIN
D, [2017-06-15T18:00:05.512520 #82085] DEBUG -- :    (0.1ms)  COMMIT
Run options: --seed 42599

# Running:

D, [2017-06-15T18:00:05.526575 #82085] DEBUG -- :    (0.1ms)  BEGIN
D, [2017-06-15T18:00:05.528031 #82085] DEBUG -- :   SQL (0.6ms)  INSERT INTO `admins` VALUES ()
D, [2017-06-15T18:00:05.528574 #82085] DEBUG -- :    (0.2ms)  COMMIT
Sending email....
D, [2017-06-15T18:00:05.528971 #82085] DEBUG -- :    (0.1ms)  BEGIN
D, [2017-06-15T18:00:05.530502 #82085] DEBUG -- :   SQL (0.3ms)  UPDATE `admins` SET `instruction_email_sent` = 1 WHERE `admins`.`id` = 1
D, [2017-06-15T18:00:05.530846 #82085] DEBUG -- :    (0.2ms)  COMMIT
Sending email....
D, [2017-06-15T18:00:05.531075 #82085] DEBUG -- :    (0.1ms)  BEGIN
D, [2017-06-15T18:00:05.531400 #82085] DEBUG -- :    (0.1ms)  COMMIT
Sending email....
D, [2017-06-15T18:00:05.531611 #82085] DEBUG -- :    (0.1ms)  BEGIN
D, [2017-06-15T18:00:05.531989 #82085] DEBUG -- :    (0.1ms)  COMMIT
Sending email....
D, [2017-06-15T18:00:05.532162 #82085] DEBUG -- :    (0.1ms)  BEGIN
D, [2017-06-15T18:00:05.532483 #82085] DEBUG -- :    (0.1ms)  COMMIT
.
.
.
D, [2017-06-15T18:00:05.909962 #82085] DEBUG -- :    (0.1ms)  BEGIN
D, [2017-06-15T18:00:05.910509 #82085] DEBUG -- :    (0.1ms)  COMMIT
Sending email....
D, [2017-06-15T18:00:05.910840 #82085] DEBUG -- :    (0.1ms)  BEGIN
D, [2017-06-15T18:00:05.911905 #82085] DEBUG -- :    (0.1ms)  ROLLBACK

ugTest#test_admin_after_commit_on_create:
SystemStackError: stack level too deep
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/attribute_set.rb:34:in `block in keys'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/attribute_set.rb:34:in `each_key'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/attribute_set.rb:34:in `each'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/attribute_set.rb:34:in `select'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/attribute_set.rb:34:in `keys'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/attribute_mutation_tracker.rb:77:in `attr_names'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/attribute_mutation_tracker.rb:20:in `changes'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/attribute_methods/dirty.rb:201:in `changes_to_save'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/attribute_methods/dirty.rb:206:in `changed_attribute_names_to_save'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/attribute_methods/dirty.rb:300:in `keys_for_partial_write'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/attribute_methods/dirty.rb:292:in `_update_record'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/callbacks.rb:344:in `block in _update_record'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:825:in `_run_update_callbacks'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/callbacks.rb:344:in `_update_record'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/timestamp.rb:107:in `_update_record'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/persistence.rb:563:in `create_or_update'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/callbacks.rb:336:in `block in create_or_update'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:97:in `run_callbacks'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/callbacks.rb:336:in `create_or_update'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/persistence.rb:129:in `save'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/validations.rb:44:in `save'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/attribute_methods/dirty.rb:35:in `save'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:307:in `block (2 levels) in save'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:383:in `block in with_transaction_returning_status'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:223:in `transaction'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:210:in `transaction'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:380:in `with_transaction_returning_status'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:307:in `block in save'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:322:in `rollback_active_record_state!'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:306:in `save'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/suppressor.rb:42:in `save'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/persistence.rb:285:in `block in update'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:383:in `block in with_transaction_returning_status'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
    /Users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:210:in `transaction'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:380:in `with_transaction_returning_status'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/persistence.rb:283:in `update'
    after_commit_save_test.rb:58:in `send_instruction_email'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:413:in `block in make_lambda'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:260:in `block in conditional'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:511:in `block in invoke_after'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:511:in `each'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:511:in `invoke_after'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:825:in `_run_commit_callbacks'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:342:in `committed!'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:86:in `commit_records'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:178:in `block in commit_transaction'
    /Users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:168:in `commit_transaction'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:207:in `block in within_new_transaction'
    /Users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:210:in `transaction'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/transactions.rb:380:in `with_transaction_returning_status'
    /Users/user/.rvm/gems/ruby-2.3.1@test_bug/gems/activerecord-5.1.1/lib/active_record/persistence.rb:283:in `update'
    after_commit_save_test.rb:58:in `send_instruction_email'
```

User creation:

```
ED, [2017-06-15T18:00:05.919126 #82085] DEBUG -- :    (0.1ms)  BEGIN
D, [2017-06-15T18:00:05.919818 #82085] DEBUG -- :   SQL (0.2ms)  INSERT INTO `users` VALUES ()
D, [2017-06-15T18:00:05.920189 #82085] DEBUG -- :    (0.2ms)  COMMIT
Sending email....
D, [2017-06-15T18:00:05.920576 #82085] DEBUG -- :    (0.1ms)  BEGIN
D, [2017-06-15T18:00:05.921535 #82085] DEBUG -- :   SQL (0.2ms)  UPDATE `users` SET `verification_email_sent` = 1 WHERE `users`.`id` = 1
D, [2017-06-15T18:00:05.922220 #82085] DEBUG -- :    (0.3ms)  COMMIT
```

### System configuration
**AR version**: activerecord (5.1.1)
**Ruby version**: ruby 2.3.1p112

I have tried this also with activerecord (4.2.8).

**Comment by eugeneius** [comment]
Previously reported as https://github.com/rails/rails/issues/14493.

I do think this is a valid issue, and that one of the two should be kept open.

**Comment by dineshsprabu** [comment]
Thanks @eugeneius. When can I expect this to be fixed? Can I start working on the fix?

**Comment by shivabhusal** [comment]
@dineshsprabu thanks for posting the issue with great reproducible details.

for now, could you please try this
```ruby
  def send_instruction_email
    puts "Sending email...."

    self.update_columns(instruction_email_sent: true)
  end

```
since `update_columns` does not trigger callbacks and in your use case it does not seem to be requiring to trigger callback.

**Comment by dineshprabu-freshdesk** [comment]
Thanks @shivabhusal. I have got that done already.

**Comment by dineshsprabu** [comment]
Thanks @shivabhusal. I got it working already. This is just an example script to prove the issue.

**Comment by shivabhusal** [comment]
is it possible to send a PR of failing test @dineshsprabu ?

**Comment by vipulnsward** [comment]
See https://github.com/rails/rails/issues/18346#issuecomment-68735666
