### ISSUE TITLE
rollbar-rails-runner doesn't work in Rails 5.1.1

### ISSUE THREAD

**Issue by dclausen** [rails/rails#29580]
### Steps to reproduce

bundle exec rollbar-rails-runner "puts 'hello'"

### Expected behavior

System should output 'hello'

### Actual behavior

bundler: failed to load command: rollbar-rails-runner (/home/deployer/app/shared/bundle/ruby/2.4.0/bin/rollbar-rails-runner)
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/deployer/app/shared/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/commands/runner.rb
  /home/deployer/app/shared/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rails/rollbar_runner.rb:39:in `read'
  /home/deployer/app/shared/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rails/rollbar_runner.rb:39:in `eval_runner'
  /home/deployer/app/shared/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rails/rollbar_runner.rb:30:in `block in run'
  /home/deployer/app/shared/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rails/rollbar_runner.rb:47:in `rollbar_managed'
  /home/deployer/app/shared/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rails/rollbar_runner.rb:30:in `run'
  /home/deployer/app/shared/bundle/ruby/2.4.0/gems/rollbar-2.14.1/bin/rollbar-rails-runner:5:in `<top (required)>'
  /home/deployer/app/shared/bundle/ruby/2.4.0/bin/rollbar-rails-runner:22:in `load'
  /home/deployer/app/shared/bundle/ruby/2.4.0/bin/rollbar-rails-runner:22:in `<top (required)>'

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.0

**Comment by dclausen** [comment]
Should've submitted this to rollbar's repo, please ignore.
