### ISSUE TITLE
Rails 3.2.22.5 Ruby 2.3.3 model saving causes serialize hash to turn to string object

### ISSUE THREAD

**Issue by Roko131** [rails/rails#29663]
## Steps to reproduce
Create new rails 3.2.22.5 app, create user model with serialize Hash field, assign value to said hash, save user in DB, retrieve hash back- retrieved as String class instead of Hash class.

###  create new rails 3.2.22.5 app
rails _3.2.22.5_ new bug123 --database=postgresql
###  add test-unit gem to your Gemfile: `gem 'test-unit', '~> 3.0'`
bundle # because added test-unit gem
###  create user model
`rails g scaffold user name comments:text logs:text logs2:text --no-test-framework`
###  migrate
`rake db:create db:migrate`
### add serialize  logs to user: 
user.rb
```
class User < ActiveRecord::Base
  attr_accessible :comments, :logs, :logs2, :name

  serialize :logs, Hash
  serialize :logs2, Hash
end
```
### open rails console- see irb(main):008:0>
```
rails c
Loading development environment (Rails 3.2.22.5)
irb(main):001:0> user = User.new
=> #<User id: nil, name: nil, comments: nil, logs: {}, logs2: {}, created_at: nil, updated_at: nil>
irb(main):002:0> user.save
=> true
irb(main):003:0> user_id = user.id
=> 2
irb(main):004:0> user.logs
=> {}
irb(main):005:0> user.logs[Time.now] = {:field_id=>6}
=> {:field_id=>6}
irb(main):006:0> user.logs
=> {2017-07-03 21:27:09 +0300=>{:field_id=>6}}
irb(main):007:0> user.save
=> true
irb(main):008:0> user.logs # why is this result now a string?
=> "---\n2017-07-03 21:27:09.030090000 +03:00:\n  :field_id: 6\n"
irb(main):009:0> User.find(user_id).logs
  User Load (2.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 2]]
=> "---\n2017-07-03 21:27:09.030090000 +03:00:\n  :field_id: 6\n"
irb(main):010:0> user.name = "my name"
=> "my name"
irb(main):011:0> user.save
=> true
irb(main):012:0> user.logs
ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be a Hash, but was a String
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.5/lib/active_record/coders/yaml_column.rb:28:in `load'
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.5/lib/active_record/attribute_methods/serialization.rb:24:in `unserialize'
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.5/lib/active_record/attribute_methods/serialization.rb:15:in `unserialized_value'
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.5/lib/active_record/attribute_methods/read.rb:72:in `__temp__'
        from (irb):12
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands/console.rb:47:in `start'
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands/console.rb:8:in `start'
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
irb(main):013:0>
```

### Expected behavior
user.logs should return a hash object

### Actual behavior
user.logs returned String object

### System configuration
**Rails version**: 3.2.22.5

**Ruby version**: 2.3.3

**OS**: windows 10 (Not that I think it matters)

Am I missing something? Thank you

# I will show Gemfile and the entire console session:

## gemfile:
```
source 'https://rubygems.org'

gem 'rails', '3.2.22.5'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
gem 'test-unit', '~> 3.0'

```
## gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (3.2.22.5)
      actionpack (= 3.2.22.5)
      mail (~> 2.5.4)
    actionpack (3.2.22.5)
      activemodel (= 3.2.22.5)
      activesupport (= 3.2.22.5)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      journey (~> 1.0.4)
      rack (~> 1.4.5)
      rack-cache (~> 1.2)
      rack-test (~> 0.6.1)
      sprockets (~> 2.2.1)
    activemodel (3.2.22.5)
      activesupport (= 3.2.22.5)
      builder (~> 3.0.0)
    activerecord (3.2.22.5)
      activemodel (= 3.2.22.5)
      activesupport (= 3.2.22.5)
      arel (~> 3.0.2)
      tzinfo (~> 0.3.29)
    activeresource (3.2.22.5)
      activemodel (= 3.2.22.5)
      activesupport (= 3.2.22.5)
    activesupport (3.2.22.5)
      i18n (~> 0.6, >= 0.6.4)
      multi_json (~> 1.0)
    arel (3.0.3)
    builder (3.0.4)
    coffee-rails (3.2.2)
      coffee-script (>= 2.2.0)
      railties (~> 3.2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    erubis (2.7.0)
    execjs (2.7.0)
    hike (1.2.3)
    i18n (0.8.4)
    journey (1.0.4)
    jquery-rails (3.1.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    json (1.8.6)
    mail (2.5.5)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    mime-types (1.25.1)
    multi_json (1.12.1)
    pg (0.21.0-x86-mingw32)
    polyglot (0.3.5)
    power_assert (1.0.2)
    rack (1.4.7)
    rack-cache (1.7.0)
      rack (>= 0.4)
    rack-ssl (1.3.4)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (3.2.22.5)
      actionmailer (= 3.2.22.5)
      actionpack (= 3.2.22.5)
      activerecord (= 3.2.22.5)
      activeresource (= 3.2.22.5)
      activesupport (= 3.2.22.5)
      bundler (~> 1.0)
      railties (= 3.2.22.5)
    railties (3.2.22.5)
      actionpack (= 3.2.22.5)
      activesupport (= 3.2.22.5)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (>= 0.14.6, < 2.0)
    rake (12.0.0)
    rdoc (3.12.2)
      json (~> 1.4)
    sass (3.4.24)
    sass-rails (3.2.6)
      railties (~> 3.2.0)
      sass (>= 3.1.10)
      tilt (~> 1.3)
    sprockets (2.2.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    test-unit (3.2.5)
      power_assert
    thor (0.19.4)
    tilt (1.4.1)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    tzinfo (0.3.53)
    uglifier (3.2.0)
      execjs (>= 0.3.0, < 3)

PLATFORMS
  x86-mingw32

DEPENDENCIES
  coffee-rails (~> 3.2.1)
  jquery-rails
  pg
  rails (= 3.2.22.5)
  sass-rails (~> 3.2.3)
  test-unit (~> 3.0)
  uglifier (>= 1.0.3)

BUNDLED WITH
   1.15.1

```

## entire rails console session:

```
C:\Users\nirra\apps\bug123>rails c
Loading development environment (Rails 3.2.22.5)
irb(main):001:0> user = User.new
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
=> #<User id: nil, name: nil, comments: nil, logs: {}, logs2: {}, created_at: nil, updated_at: nil>
irb(main):002:0> user.save
   (0.0ms)  BEGIN
  SQL (32.0ms)  INSERT INTO "users" ("comments", "created_at", "logs", "logs2", "name", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["comments", nil], ["created_at",
Mon, 03 Jul 2017 18:26:09 UTC +00:00], ["logs", "--- {}\n"], ["logs2", "--- {}\n"], ["name", nil], ["updated_at", Mon, 03 Jul 2017 18:26:09 UTC +00:00]]
   (2.0ms)  COMMIT
=> true
irb(main):003:0> user_id = user.id
=> 2
irb(main):004:0> user.logs
=> {}
irb(main):005:0> user.logs[Time.now] = {:field_id=>6}
=> {:field_id=>6}
irb(main):006:0> user.logs
=> {2017-07-03 21:27:09 +0300=>{:field_id=>6}}
irb(main):007:0> user.save
   (0.5ms)  BEGIN
   (3.0ms)  UPDATE "users" SET "updated_at" = '2017-07-03 18:27:18.478940', "logs" = '---
2017-07-03 21:27:09.030090000 +03:00:
 :field_id: 6
', "logs2" = '--- {}
' WHERE "users"."id" = 2
   (1.0ms)  COMMIT
=> true
irb(main):008:0> user.logs
=> "---\n2017-07-03 21:27:09.030090000 +03:00:\n  :field_id: 6\n"
irb(main):009:0> User.find(user_id).logs
  User Load (2.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 2]]
=> "---\n2017-07-03 21:27:09.030090000 +03:00:\n  :field_id: 6\n"
irb(main):010:0> user.name = "my name"
=> "my name"
irb(main):011:0> user.save
   (1.0ms)  BEGIN
   (2.0ms)  UPDATE "users" SET "name" = 'my name', "updated_at" = '2017-07-03 18:30:51.829465', "logs" = '--- |
 ---
 2017-07-03 21:27:09.030090000 +03:00:
 :field_id: 6
', "logs2" = '--- {}
' WHERE "users"."id" = 2
   (1.0ms)  COMMIT
=> true
irb(main):012:0> user.logs
ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be a Hash, but was a String
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.5/lib/active_record/coders/yaml_column.rb:28:in `load'
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.5/lib/active_record/attribute_methods/serialization.rb:24:in `unserialize'
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.5/lib/active_record/attribute_methods/serialization.rb:15:in `unserialized_value'
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.5/lib/active_record/attribute_methods/read.rb:72:in `__temp__'
        from (irb):12
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands/console.rb:47:in `start'
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands/console.rb:8:in `start'
        from C:/row/Ruby23/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
irb(main):013:0>

```

**Comment by matthewd** [comment]
Rails 3.2 is no longer supported.

**Comment by Roko131** [comment]
Ok. so (As I understand it) `Rails version: 3.2.22.5` is compatible with `ruby 2.2.x` but not `ruby 2.3.x`
So reverting from `ruby 2.3.3` to `ruby 2.2.6` fixed the issue for me.
