### ISSUE TITLE
Encoding::UndefinedConversionError in secrets:edit with rails 5.1.2

### ISSUE THREAD

**Issue by parthm** [rails/rails#29696]
### Steps to reproduce
Hello,

Tried upgrading to rails 5.1.2 (from 5.1.1). Changed rails version to 5.1.2 in Gemfile and did a `bundle update`.

### Expected behavior

Issued the `rails secrets:edit` command. Excpected secrets to open up in Vim as was happening in rails 5.1.1.

### Actual behavior

Issuing `rails secrets:edit` command causes the below exception. Do I need to be doing something differently or is this a bug?

```
parth@vbox-possum:~/project$ ./bin/rails secrets:edit
/home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/secrets.rb:104:in `write': "\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/secrets.rb:104:in `writing'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/secrets.rb:68:in `read_for_editing'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/commands/secrets/secrets_command.rb:33:in `edit'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
        from ./bin/rails:4:in `require'
        from ./bin/rails:4:in `<main>'
parth@vbox-possum:~/project$ rails -v
Rails 5.1.2
parth@vbox-possum:~/project$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.1

**Comment by brandonhilkert** [comment]
It looks like I can't open my secrets file on OSX or on ubuntu b/c of this.

**Comment by kulte** [comment]
Is this going to be made into a patch-level release `rails-5.1.3`?

**Comment by kaspth** [comment]
Yup, RCs incoming this wednesday.
