### ISSUE TITLE
no implicit conversion of nil into String (TypeError) with rails dbconsole

### ISSUE THREAD

**Issue by parthm** [rails/rails#29717]
### Steps to reproduce
With rails 5.1.1 issue the `./bin/rails dbconsole` command. It crashes with a `TypeError`. Seen this error with MySQL. Works fine for sqlite3.

### Expected behavior
Should start the db console.

### Actual behavior
Below is the crash report for MySQL. sqlite3 dbconsole opens up fine.

```
parth@vbox-possum:~/project$ ./bin/rails db
/home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/dbconsole/dbconsole_command.rb:126:in `exec': no implicit conversion of nil into String (TypeError)
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/dbconsole/dbconsole_command.rb:126:in `find_cmd_and_exec'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/dbconsole/dbconsole_command.rb:39:in `start'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/dbconsole/dbconsole_command.rb:6:in `start'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/dbconsole/dbconsole_command.rb:151:in `perform'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
        from ./bin/rails:4:in `require'
        from ./bin/rails:4:in `<main>'
parth@vbox-possum:~/project$

parth@vbox-possum:~/project$ mysql --version
mysql  Ver 14.14 Distrib 5.7.18, for Linux (i686) using  EditLine wrapper
parth@vbox-possum:~/project$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

```

### System configuration
**Rails version**: 5.1.1

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [i686-linux]

**mysql version**: mysql  Ver 14.14 Distrib 5.7.18, for Linux (i686) using  EditLine wrapper

**Ubuntu version**: 16.04.2 LTS

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by parthm** [comment]
[sample_app.tar.gz](https://github.com/rails/rails/files/1132884/sample_app.tar.gz)

Looks like the issue has something to do with the interaction with encrypted secrets. When the database, username and password are set in `database.yml`, `rails db` works fine i.e., prompts for password and enters mysql shell with the DB set. However, when I move these to encrypted secrets, we see the exception in the original note. Below are the steps towards creating of the sample failing app.

- Create the database and user
```
parth@vbox-possum:~$ mysql -u root -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 4
Server version: 5.7.18-0ubuntu0.16.04.1 (Ubuntu)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> create database test_dev_db;
Query OK, 1 row affected (0.00 sec)

mysql> create user 'test_dev'@'localhost' identified by 'test_dev_password';
Query OK, 0 rows affected (0.01 sec)

mysql> grant all on test_dev_db.* to 'test_dev'@'localhost';
Query OK, 0 rows affected (0.00 sec)

mysql> \q
Bye
```

- Create app and install Gems
```
parth@vbox-possum:~/experiments$ rails new sample_app_29717 -d mysql
parth@vbox-possum:~/experiments/sample_app_29717$ ./bin/bundle install
```
- Create sample controller and mode
```
parth@vbox-possum:~/experiments/sample_app_29717$ bin/rails generate controller Welcome index
parth@vbox-possum:~/experiments/sample_app_29717$ bin/rails generate model Article title:string text:text
```

- Setup DB in database.yml works OK
At this point I setup DB with username, password, database and host set in `database.yml`.
DB migration works.

```
parth@vbox-possum:~/experiments/sample_app_29717$ ./bin/rails db:migrate
== 20170708084157 CreateArticles: migrating ===================================
-- create_table(:articles)
   -> 0.0080s
== 20170708084157 CreateArticles: migrated (0.0080s) ==========================
```

- dbconsole commands works at this point
```
parth@vbox-possum:~/experiments/sample_app_29717$ ./bin/rails db
Enter password: 

...

mysql> select USER();
+--------------------+
| USER()             |
+--------------------+
| test_dev@localhost |
+--------------------+
1 row in set (0.00 sec)
```

- Setup secrets
```
parth@vbox-possum:~/experiments/sample_app_29717$ ./bin/rails secrets:setup
```
Setup `config.read_encrypted_secrets = true` for `development.rb` and update secrets as seen in the sample app. Update `database.yml` to use values from encrypted secrets. At this point `rails db` fails with `TypeError`.

```
parth@vbox-possum:~/experiments/sample_app_29717$ vim config/environments/development.rb 
parth@vbox-possum:~/experiments/sample_app_29717$ ./bin/rails secrets:edit
Waiting for secrets file to be saved. Abort with Ctrl-C.
New secrets encrypted and saved.
parth@vbox-possum:~/experiments/sample_app_29717$ vim config/database.yml 
parth@vbox-possum:~/experiments/sample_app_29717$ ./bin/rails db
/home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/dbconsole/dbconsole_command.rb:126:in `exec': no implicit conversion of nil 
into String (TypeError)
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/dbconsole/dbconsole_command.rb:126:in `find_cmd_and_exec'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/dbconsole/dbconsole_command.rb:39:in `start'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/dbconsole/dbconsole_command.rb:6:in `start'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/dbconsole/dbconsole_command.rb:151:in `perform'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
        from /home/parth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
        from /home/parth/experiments/sample_app_29717/bin/rails:9:in `require'
```

Delete tables via mysql CLI and do `db:migrate`. This works. So it seems rails is able to access encrypted secrets info just fine. However, for some reason `rails db` crashes.

```
parth@vbox-possum:~/experiments/sample_app_29717$ mysql -u test_dev -p                                                                                          [193/291]
Enter password: 

...

mysql> use test_dev_db;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+-----------------------+
| Tables_in_test_dev_db |
+-----------------------+
| ar_internal_metadata  |
| articles              |
| schema_migrations     |
+-----------------------+
3 rows in set (0.00 sec)

mysql> drop table ar_internal_metadata, articles, schema_migrations;
Query OK, 0 rows affected (0.02 sec)

mysql> show tables;
Empty set (0.00 sec)

mysql> \q
Bye
parth@vbox-possum:~/experiments/sample_app_29717$ ./bin/rails db:migrate
== 20170708084157 CreateArticles: migrating ===================================
-- create_table(:articles)
   -> 0.0073s
== 20170708084157 CreateArticles: migrated (0.0076s) =======
===================

parth@vbox-possum:~/experiments/sample_app_29717$ 

```

**Comment by parthm** [comment]
IIRC I saw the same error with PostgreSQL earlier. Unfortunately, I don't have a postgresql setup right now to try this again.

**Comment by y-yagi** [comment]
Thank you for provide sample application and detailed explanation. I could confirm it.  

Currently, `development.rb` is not loaded by the dbconsole command. Therefore, `read_encrypted_secrets` does not become true, secrets can not be read, so it seems that database can not be acquired and it is an error. I will try fix. 

Temporally Solution: 
Please set `config.read_encrypted_secrets = true` in `config/application.rb`. It probably should not cause an error.

**Comment by parthm** [comment]
Thanks @y-yagi . The temporary solution suggested by you worked perfectly.
