### ISSUE TITLE
namespaced controller inside engine cannot be called in production

### ISSUE THREAD

**Issue by nir0** [rails/rails#29863]
### Steps to reproduce

create a mountable engine `tickets`
in this engine
`rails g controller api/v1/tickets`
it should create controller that looks like
```ruby
require_dependency "tickets/application_controller"

module Tickets
  class Api::V1::TicketsController < ...
```
in main app mount that with `mount Tickets::Engine, at: "/"`
in engine routes
```ruby
Tickets::Engine.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :tickets
    end
  end
end
```
### Expected behavior
GET /api/v1/tickets calls #index action

### Actual behavior
in development it works fine, in production it returns an error 
```
uninitialized constant Tickets::Api

Rails.root: /home/deploy/gazpro5/releases/20170720051152

Application Trace | Framework Trace | Full Trace
activesupport (5.1.2) lib/active_support/inflector/methods.rb:284:in `const_get'
activesupport (5.1.2) lib/active_support/inflector/methods.rb:284:in `block in constantize'
activesupport (5.1.2) lib/active_support/inflector/methods.rb:267:in `each'
activesupport (5.1.2) lib/active_support/inflector/methods.rb:267:in `inject'
activesupport (5.1.2) lib/active_support/inflector/methods.rb:267:in `constantize'
activesupport (5.1.2) lib/active_support/dependencies.rb:582:in `get'
activesupport (5.1.2) lib/active_support/dependencies.rb:613:in `constantize'
actionpack (5.1.2) lib/action_dispatch/http/request.rb:82:in `controller_class'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:43:in `controller'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:29:in `serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
railties (5.1.2) lib/rails/engine.rb:522:in `call'
railties (5.1.2) lib/rails/railtie.rb:185:in `public_send'
railties (5.1.2) lib/rails/railtie.rb:185:in `method_missing'
actionpack (5.1.2) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.1.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.2) lib/rails/engine.rb:522:in `call'
unicorn (5.3.0) lib/unicorn/http_server.rb:606:in `process_client'
unicorn (5.3.0) lib/unicorn/http_server.rb:702:in `worker_loop'
unicorn (5.3.0) lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
unicorn (5.3.0) lib/unicorn/http_server.rb:142:in `start'
unicorn (5.3.0) bin/unicorn:126:in `<top (required)>'
/home/deploy/gazpro5/shared/bundle/ruby/2.4.0/bin/unicorn:23:in `load'
/home/deploy/gazpro5/shared/bundle/ruby/2.4.0/bin/unicorn:23:in `<main>'
Routes

Routes match in priority from top to bottom
...
Routes for Tickets::Engine
...

api_v1_tickets_path | GET | /api/v1/tickets(.:format) | tickets/api/v1/tickets#index
  | POST | /api/v1/tickets(.:format) | tickets/api/v1/tickets#create
new_api_v1_ticket_path | GET | /api/v1/tickets/new(.:format) | tickets/api/v1/tickets#new
edit_api_v1_ticket_path | GET | /api/v1/tickets/:id/edit(.:format) | tickets/api/v1/tickets#edit
api_v1_ticket_path | GET | /api/v1/tickets/:id(.:format) | tickets/api/v1/tickets#show
  | PATCH | /api/v1/tickets/:id(.:format) | tickets/api/v1/tickets#update
  | PUT | /api/v1/tickets/:id(.:format) | tickets/api/v1/tickets#update
  | DELETE | /api/v1/tickets/:id(.:format) | tickets/api/v1/tickets#destroy
```

### System configuration
**Rails version**: 5.1.2

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by nir0** [comment]
changing controller name to
```ruby
require_dependency "tickets/application_controller"

module Tickets
  class Tickets::Api::V1::TicketsController < ...
```
fixed this, but i cannot see why. maybe i'm not totally aware how module directive works, i thought it prepends `Api::V1::TicketsController` with module name (and it obviously does in development) 

feel free to close this issue if it is well-known behaviour
