### ISSUE TITLE
has_one relation to a table with a column named the same as the table raises TypeError

### ISSUE THREAD

**Issue by rnubel** [rails/rails#29878]
In the progress of upgrading my app to 5.1, I ran into a nasty bug: given a model with a column named the same as the table (for example, a `ProgramDetail` model with a `program_details` column), when associating to that table by a `has_one` relation, loading the association throws a TypeError (full stack trace below). From what I can tell, the association scope is getting confused and trying to bind the wrong parameter value (specifically, a hash instead of an ID).

The error does not occur in 5.0.4, but does occur in 5.1.0. I haven't bisected the exact commit yet.

### Steps to reproduce

These shell commands will create a minimal Rails app and reproduce the bug on Rails 5.1.0+: 
```
rails new rails-bug

cd rails-bug
bin/rails g model Program name:string
bin/rails g model ProgramDetail program_id:integer program_details:string
bin/rails db:migrate

echo 'class Program < ApplicationRecord; has_one :program_detail; end' > app/models/program.rb
echo 'class ProgramDetail < ApplicationRecord; belongs_to :program; end' > app/models/program_detail.rb

bin/rails r 'Program.create(name: %[prog]).create_program_detail(program_details: %[test])'
```

### Expected behavior
The last command should create a new Program record and an associated ProgramDetail record, without exploding.

### Actual behavior
```
/Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/quoting.rb:45:in `rescue in type_cast': can't cast Hash (TypeError)
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/quoting.rb:32:in `type_cast'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/quoting.rb:166:in `block in type_casted_binds'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/quoting.rb:166:in `map'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/quoting.rb:166:in `type_casted_binds'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:206:in `exec_query'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:365:in `select_prepared'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:40:in `select_all'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/querying.rb:39:in `find_by_sql'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/statement_cache.rb:107:in `execute'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/associations/singular_association.rb:50:in `find_target'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/associations/association.rb:157:in `load_target'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/associations/has_one_association.rb:26:in `replace'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/associations/has_one_association.rb:73:in `set_new_record'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/associations/singular_association.rb:69:in `_create_record'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/associations/association.rb:196:in `create'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/activerecord-5.1.2/lib/active_record/associations/builder/singular_association.rb:31:in `create_program_detail'
	from /Users/rnubel/.gem/ruby/2.4.1/gems/railties-5.1.2/lib/rails/commands/runner/runner_command.rb:37:in `perform'
```

### System configuration
**Rails version**: I have reproduced this on 5.1.0, 5.1.2, 5.1.3rc1, and on edge. The above code works fine in 5.0.4, however.

**Ruby version**: 2.4.1

**Comment by rnubel** [comment]
Oops, this appears to be a duplicate of https://github.com/rails/rails/issues/29045.
