### ISSUE TITLE
Namespaced model requires foreign_key option for association

### ISSUE THREAD

**Issue by brandonhilkert** [rails/rails#29886]
### Steps to reproduce
1. Create a namespaced model with generator (e.g. `bin/rails g model prefix/post`)
2. Base model `prefix.rb` is created with something like:

```ruby
module Prefix
  def self.table_name_prefix do
    'prefix_'
  end
end
```

This is awesome b/c I'm used to manually setting the prefix in the namespace models, so doing it in one place is nice savings for anything else that comes under that namespace.

3. Run script below and see that it complains about inserting a comment b/c of `post_id`

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.1.2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

module Prefix
  def self.table_name_prefix
    "prefix_"
  end
end

ActiveRecord::Schema.define do
  create_table :prefix_posts, force: true do |t|
  end

  create_table :prefix_comments, force: true do |t|
    t.integer :prefix_post_id
  end
end

class Prefix::Post < ActiveRecord::Base
  has_many :comments
end

class Prefix::Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_equal 0, Prefix::Post.count
    assert_equal 0, Prefix::Comment.count

    post = Prefix::Post.create!
    post.comments << Prefix::Comment.create!

    assert_equal 1, Prefix::Post.count
    assert_equal 1, Prefix::Comment.count
  end
end
```

It seems like manually the `foreign_key` fixes it. 

```ruby
  has_many :comments, foreign_key: "prefix_post_id"
```

Feels like this is the kind of thing that could be handled with the namespaced info, but obviously not urgent.

### Expected behavior
Association infers the foreign key based on namespaced model name

### Actual behavior
```
  1) Error:
BugTest#test_association_stuff:
ActiveModel::MissingAttributeError: can't write unknown attribute `post_id`
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/attribute.rb:205:in `with_value_from_database'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/attribute_set.rb:54:in `write_from_user'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/attribute_methods/write.rb:39:in `write_attribute'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/attribute_methods.rb:359:in `[]='
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/association.rb:225:in `block in set_owner_attributes'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/association.rb:225:in `each'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/association.rb:225:in `set_owner_attributes'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/has_many_association.rb:33:in `insert_record'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/collection_association.rb:433:in `block (2 levels) in concat_records'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/collection_association.rb:447:in `replace_on_target'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/collection_association.rb:281:in `add_to_target'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/collection_association.rb:432:in `block in concat_records'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/collection_association.rb:430:in `each'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/collection_association.rb:430:in `concat_records'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/has_many_association.rb:114:in `concat_records'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/collection_association.rb:114:in `block in concat'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/collection_association.rb:129:in `block in transaction'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/transactions.rb:210:in `transaction'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/collection_association.rb:128:in `transaction'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/collection_association.rb:114:in `concat'
    /Users/bhilkert/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/associations/collection_proxy.rb:1055:in `<<'
    /Users/bhilkert/Desktop/ar.rb:55:in `test_association_stuff'
```

### System configuration
**Rails version**: 5.1.2
**Ruby version**: 2.4.1p111

**Comment by sgrif** [comment]
This is the expected behavior [described in the documentation](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to)

>  By default this is guessed to be the name of the association with an “_id” suffix.

The table name has never had an effect, nor is it expected to.
