### ISSUE TITLE
Magento 2 Admin Error: Invalid scope type ''

### ISSUE THREAD

**Issue by alainstout** [rails/rails#29981]
When I login at Magento 2 Admin I get:

> There has been an error processing your request
> 
> Invalid scope type ''

The error log say:

```
a:4:{i:0;s:21:"Invalid scope type ''";i:1;s:6480:"#0 ROOT/vendor/magento/framework/App/Config/ScopeCodeResolver.php(48): Magento\Framework\App\ScopeResolverPool->get(NULL)
#1 ROOT/vendor/magento/framework/App/Config.php(79): Magento\Framework\App\Config\ScopeCodeResolver->resolve(NULL, NULL)
#2 ROOT/vendor/magento/module-config/Model/Config.php(480): Magento\Framework\App\Config->getValue('design/theme/th...', NULL, NULL)
#3 ROOT/app/code/Codazon/ThemeOptions/Backend/Model/Menu/Builder/Plugin.php(35): Magento\Config\Model\Config->getConfigDataValue('design/theme/th...')
#4 ROOT/app/code/Codazon/ThemeOptions/Backend/Model/Menu/Builder/Plugin.php(62): Codazon\ThemeOptions\Backend\Model\Menu\Builder\Plugin->getThemeId()
#5 ROOT/vendor/magento/framework/Interception/Interceptor.php(152): Codazon\ThemeOptions\Backend\Model\Menu\Builder\Plugin->afterGetResult(Object(Magento\Backend\Model\Menu\Builder\Interceptor), Object(Magento\Backend\Model\Menu))
#6 ROOT/var/generation/Magento/Backend/Model/Menu/Builder/Interceptor.php(26): Magento\Backend\Model\Menu\Builder\Interceptor->___callPlugins('getResult', Array, Array)
#7 ROOT/vendor/magento/module-backend/Model/Menu/Config.php(146): Magento\Backend\Model\Menu\Builder\Interceptor->getResult(Object(Magento\Backend\Model\Menu))
#8 ROOT/vendor/magento/module-backend/Model/Menu/Config.php(109): Magento\Backend\Model\Menu\Config->_initMenu()
#9 ROOT/vendor/magento/module-backend/Model/Url.php(348): Magento\Backend\Model\Menu\Config->getMenu()
#10 ROOT/vendor/magento/module-backend/Model/Url.php(308): Magento\Backend\Model\Url->_getMenu()
#11 ROOT/vendor/magento/module-backend/Controller/Adminhtml/Index/Index.php(21): Magento\Backend\Model\Url->getStartupPageUrl()
#12 ROOT/vendor/magento/framework/App/Action/Action.php(102): Magento\Backend\Controller\Adminhtml\Index\Index->execute()
#13 ROOT/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#14 ROOT/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#15 ROOT/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callParent('dispatch', Array)
#16 ROOT/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminAuthentica...')
#17 ROOT/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#18 ROOT/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 ROOT/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminMassaction...')
#20 ROOT/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 ROOT/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 ROOT/var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php(26): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#23 ROOT/vendor/magento/framework/App/FrontController.php(55): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 ROOT/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#25 ROOT/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#26 ROOT/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#27 ROOT/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 ROOT/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 ROOT/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#30 ROOT/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 ROOT/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#32 ROOT/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#33 {main}";s:3:"url";s:97:"admin/index/index/key/d6da202f324298e6492136f19b5200d311ec208d3fe62be48745910532c707dc/";s:11:"script_name";s:10:"/index.php";}
```

Nobody knows, google says nothing

Anyone know are familiar with this solution?

Many Thanks

**Comment by vipulnsward** [comment]
Not sure what led the issue to Rails. 
Magento doesn't use Rails, please check appropriate project to file the issue.

**Comment by alainstout** [comment]
What you mean with that? What do I have to do?

**Comment by kaspth** [comment]
You filed an issue on github.com/rails/rails for the web framework Ruby on Rails. What you want is to file your issue somewhere more closely related with Magento 😄

**Comment by imagina** [comment]
For reference: The error is reported here in Magento 2 repository
https://github.com/magento/magento2/issues/10365
