### ISSUE TITLE
offset and update_all cause ActiveRecord::StatementInvalid

### ISSUE THREAD

**Issue by znz** [rails/rails#30148]
### Steps to reproduce

`SomeModel.offset(n).update_all(hash)`

Related issues:
- I reported to kaminari: https://github.com/kaminari/kaminari/issues/904
- I found old (closed (not merged)) pull request: https://github.com/rails/rails/pull/14882

### Expected behavior

UPDATE SQL with offset.

### Actual behavior

Rails 4.2.9 works without offset.
Rails 5.0.5 and Rails 5.1.3 cause `ActiveRecord::StatementInvalid`.

```
% rails c -s
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from .../activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
Loading development environment in sandbox (Rails 4.2.9)
Any modifications you make will be rolled back on exit
[1] pry(main)> User.limit(2).offset(3).update_all(updated_at: Time.utc(2017))
  SQL (3.7ms)  UPDATE "users" SET "updated_at" = '2017-01-01 00:00:00.000000' WHERE "users"."id" IN (SELECT "users"."id" FROM "users" LIMIT 2)
```

```
% rails c -s
Loading development environment in sandbox (Rails 5.0.5)
Any modifications you make will be rolled back on exit
[1] pry(main)> User.limit(2).offset(3).update_all(updated_at: Time.utc(2017))
  SQL (5.5ms)  UPDATE "users" SET "updated_at" = '2017-01-01 00:00:00' WHERE "users"."id" IN (SELECT "users"."id" FROM "users" LIMIT $1)  [["LIMIT", 2], ["OFFSET", 3]]
ActiveRecord::StatementInvalid: PG::IndeterminateDatatype: ERROR:  could not determine data type of parameter $2
: UPDATE "users" SET "updated_at" = '2017-01-01 00:00:00' WHERE "users"."id" IN (SELECT "users"."id" FROM "users" LIMIT $1)
```

```
% rails c -s
Loading development environment in sandbox (Rails 5.1.3)
Any modifications you make will be rolled back on exit
[1] pry(main)> User.limit(2).offset(3).update_all(updated_at: Time.utc(2017))
  SQL (0.9ms)  UPDATE "users" SET "updated_at" = '2017-01-01 00:00:00' WHERE "users"."id" IN (SELECT "users"."id" FROM "users" LIMIT $1)  [["LIMIT", 2], ["OFFSET", 3]]
ActiveRecord::StatementInvalid: PG::IndeterminateDatatype: ERROR:  could not determine data type of parameter $2
: UPDATE "users" SET "updated_at" = '2017-01-01 00:00:00' WHERE "users"."id" IN (SELECT "users"."id" FROM "users" LIMIT $1)
```

### System configuration
**Rails version**: 4.2.9, 5.0.5, 5.1.3

**Ruby version**: 2.3.3

**Comment by intrip** [comment]
I can't reproduce the problem locally, could you please create an example app for this?

**Comment by znz** [comment]
I created example app.

How to use:

```
  git clone https://github.com/znz/rails-5-1-example
  cd rails-5-1-example
  vagrant up
  vagrant ssh
  cd /vagrant
  bundle
  bin/rails g model user
  bin/rails db:migrate
  bin/rails r 'User.offset(3).update_all(updated_at: Time.utc(2017))'
```

Error message in example app:

```
vagrant@stretch:/vagrant$ bin/rails r 'User.offset(3).update_all(updated_at: Time.utc(2017))'
/var/lib/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/postgresql_adapter.rb:614:in `async_exec': PG::IndeterminateDatatype: ERROR:  could not determine data type of parameter $1 (ActiveRecord::StatementInvalid)
: UPDATE "users" SET "updated_at" = '2017-01-01 00:00:00'
	from /var/lib/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/postgresql_adapter.rb:614:in `block (2 levels) in exec_no_cache'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
	from /var/lib/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/postgresql_adapter.rb:613:in `block in exec_no_cache'
	from /var/lib/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
	from /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /var/lib/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
	from /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	from /var/lib/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
	from /var/lib/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/postgresql_adapter.rb:612:in `exec_no_cache'
	from /var/lib/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `execute_and_clear'
	from /var/lib/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `exec_delete'
	from /var/lib/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/database_statements.rb:140:in `update'
	from /var/lib/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `update'
	from /var/lib/gems/2.3.0/gems/activerecord-5.1.3/lib/active_record/relation.rb:380:in `update_all'
	from /var/lib/gems/2.3.0/gems/railties-5.1.3/lib/rails/commands/runner/runner_command.rb:37:in `perform'
	from /var/lib/gems/2.3.0/gems/railties-5.1.3/lib/rails/commands/runner/runner_command.rb:37:in `eval'
	from /var/lib/gems/2.3.0/gems/railties-5.1.3/lib/rails/commands/runner/runner_command.rb:37:in `perform'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /var/lib/gems/2.3.0/gems/railties-5.1.3/lib/rails/command/base.rb:63:in `perform'
	from /var/lib/gems/2.3.0/gems/railties-5.1.3/lib/rails/command.rb:44:in `invoke'
	from /var/lib/gems/2.3.0/gems/railties-5.1.3/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by MaxLap** [comment]
This problem happens on 5.0 and 5.1, but not on master. I didn't check for previous versions.

On master, the offset is ignored. I'm not sure if this is just an intended change or just a side effect of another change, but I think the offset shouldn't be ignored.

Since rails support update_all with limit, I see no reason not to support offset. Thoughts? 

For reference, this is what happens for with a limit and offset on master:
```ruby
Post.offset(1).limit(2).update_all(id: 3)
#=> UPDATE "posts" SET "id" = 3 WHERE "posts"."id" IN (SELECT "posts"."id" FROM "posts" LIMIT ?)  [["LIMIT", 2]]
```

**Comment by Soliah** [comment]
This is still an issue on Rails 5.1.4.

**Comment by MaxLap** [comment]
"Working on master" means it works for the next minor release, I.E: 5.2. 

Sorry i didn't clarify initialy.

**Comment by GeorgeKaraszi** [comment]
I can verify I am seeing similar issues on 5.1.4

**Comment by ximus** [comment]
workaround i used in my situation (rails 4.2.7.1)

changed my query from:
```ruby
scope
  .order(:id)
  .offset(offset)
  .limit(batch_size)
  .update_all(use_accrued_interest: true)
```

to:
```ruby
scope.where(
  id: scope.select(:id).order(:id).offset(offset).limit(batch_size)
).update_all(use_accrued_interest: true)
```
