### ISSUE TITLE
 PG::FeatureNotSupported: ERROR: cached plan must not change result type

### ISSUE THREAD

**Issue by platbr** [rails/rails#30507]
### Steps to reproduce
1. Do some select on a table using ActiveRecord
2. Run a migration to add a column to this table without restart app. (I have two apps sharing same db)
3. Do other select using ActiveRecord.

### Expected behavior
Reset cache and retry.

### Actual behavior
Fatal error.

### System configuration
Rails: 5.0.5
Ruby: 2.2.4 
PostgreSQL: 9.5

### Log
``` 
I, [2017-09-01T23:34:17.409652 #9921]  INFO -- : Processing by Admin::TipoImpressaoController#index as JSON
D, [2017-09-01T23:34:17.416424 #9921] DEBUG -- :   TipoOpcao Load (37.5ms)  SELECT  "tipo_opcoes".* FROM "tipo_opcoes" WHERE "tipo_opcoes"."id" = $1 LIMIT $2  [["id", 15], ["LIMIT", 1]]
E, [2017-09-01T23:34:17.417274 #9921] ERROR -- : PG::FeatureNotSupported: ERROR: plano em cache não deve mudar tipo resultante
: SELECT  "tipo_opcoes".* FROM "tipo_opcoes" WHERE "tipo_opcoes"."id" = $1 LIMIT $2
E, [2017-09-01T23:34:17.417624 #9921] ERROR -- : /var/www/sistemas/ingressos/releases/58/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:606:in `exec_prepared'
/var/www/sistemas/ingressos/releases/58/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:606:in `block in exec_cache'
/var/www/sistemas/ingressos/releases/58/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
/var/www/sistemas/ingressos/releases/58/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
```

**Comment by platbr** [comment]
Analyzing postgresql_adapter.rb code i found this. 

```
CACHED_PLAN_HEURISTIC = 'cached plan must not change result type'.freeze
def is_cached_plan_failure?(e)
  pgerror = e.cause
  code = pgerror.result.result_error_field(PG::PG_DIAG_SQLSTATE)
  code == FEATURE_NOT_SUPPORTED && pgerror.message.include?(CACHED_PLAN_HEURISTIC)
rescue
  false
end
```
It expect that PostgreSQL is using english for lc_messages but once  it was pt_BR it didn't work.

Using  lc_messages='en_US.UTF-8' in postgresql.conf fixed it.

**Comment by BrunoQuaresma** [comment]
@platbr Sorry, but I don't understand how to fix that. Can you explain please?

**Comment by igbanam** [comment]
Just bumped into this myself. Hope this helps you as it's helped me https://medium.com/carwow-product-engineering/activerecord-error-cached-plan-must-not-change-result-type-aca72cdef504
