### ISSUE TITLE
rake aj:integration:delayed_job keep failing due to undefined method `yaml_as' for ActiveRecord::Base:Class (NoMethodError)

### ISSUE THREAD

**Issue by yahonda** [rails/rails#30522]
rake aj:integration:delayed_job keep failing due to undefined method `yaml_as' for ActiveRecord::Base:Class (NoMethodError) https://travis-ci.org/rails/rails/jobs/271467826

### Steps to reproduce

```ruby
$ rbenv install 2.5.0-dev
$ rbenv global 2.5.0-dev
$ git clone -b diag_yaml_as https://github.com/yahonda/rails.git
$ cd rails/activejob
$ bundle
$ bundle exec rake test:integration:delayed_job
```
The reason to use `diag_yaml_as` branch is to install `mini_racer` gem.

### Expected behavior
It should pass as using Ruby 2.4.1.

### Actual behavior
```ruby
$ bundle exec rake test:integration:delayed_job
/home/yahonda/.rbenv/versions/2.5.0-dev/bin/ruby -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/rake-12.0.0/lib" "/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/integration/queuing_test.rb"
Using delayed_job


*** rake aj:integration:delayed_job ***
== 20170904161938 CreateDelayedJobs: migrating ================================
-- create_table(:delayed_jobs, {:force=>true})
   -> 0.0026s
-- add_index(:delayed_jobs, [:priority, :run_at], {:name=>"delayed_jobs_priority"})
   -> 0.0008s
== 20170904161938 CreateDelayedJobs: migrated (0.0035s) =======================

Traceback (most recent call last):
	63: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `<main>'
	62: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `select'
	61: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	60: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:15:in `require'
	59: from /home/yahonda/git/rails/activejob/test/integration/queuing_test.rb:3:in `<top (required)>'
	58: from /home/yahonda/git/rails/activejob/test/integration/queuing_test.rb:3:in `require'
	57: from /home/yahonda/git/rails/activejob/test/helper.rb:12:in `<top (required)>'
	56: from /home/yahonda/git/rails/activejob/test/helper.rb:12:in `require'
	55: from /home/yahonda/git/rails/activejob/test/support/integration/helper.rb:18:in `<top (required)>'
	54: from /home/yahonda/git/rails/activejob/test/support/integration/helper.rb:18:in `require'
	53: from /tmp/d20170904-18376-7sadky/dummy/config/environment.rb:5:in `<top (required)>'
	52: from /home/yahonda/git/rails/railties/lib/rails/application.rb:356:in `initialize!'
	51: from /home/yahonda/git/rails/railties/lib/rails/initializable.rb:60:in `run_initializers'
	50: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	49: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	48: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	47: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:347:in `call'
	46: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:347:in `each'
	45: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	44: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	43: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:415:in `call'
	42: from /home/yahonda/git/rails/railties/lib/rails/initializable.rb:50:in `tsort_each_child'
	41: from /home/yahonda/git/rails/railties/lib/rails/initializable.rb:50:in `each'
	40: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	39: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	38: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	37: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	36: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	35: from /home/yahonda/git/rails/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
	34: from /home/yahonda/git/rails/railties/lib/rails/initializable.rb:32:in `run'
	33: from /home/yahonda/git/rails/railties/lib/rails/initializable.rb:32:in `instance_exec'
	32: from /home/yahonda/git/rails/railties/lib/rails/engine.rb:613:in `block in <class:Engine>'
	31: from /home/yahonda/git/rails/railties/lib/rails/engine.rb:613:in `each'
	30: from /home/yahonda/git/rails/railties/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	29: from /home/yahonda/git/rails/railties/lib/rails/engine.rb:656:in `load_config_initializer'
	28: from /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:170:in `instrument'
	27: from /home/yahonda/git/rails/railties/lib/rails/engine.rb:657:in `block in load_config_initializer'
	26: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:277:in `load'
	25: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
	24: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:277:in `block in load'
	23: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
	22: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
	21: from /tmp/d20170904-18376-7sadky/dummy/config/initializers/activejob.rb:2:in `<main>'
	20: from /home/yahonda/git/rails/activejob/test/support/integration/jobs_manager.rb:8:in `current_manager'
	19: from /home/yahonda/git/rails/activejob/test/support/integration/jobs_manager.rb:8:in `new'
	18: from /home/yahonda/git/rails/activejob/test/support/integration/jobs_manager.rb:13:in `initialize'
	17: from /home/yahonda/git/rails/activejob/test/support/integration/jobs_manager.rb:13:in `require_relative'
	16: from /home/yahonda/git/rails/activejob/test/support/integration/adapters/delayed_job.rb:4:in `<main>'
	15: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `require'
	14: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
	13: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
	12: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	11: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	10: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/delayed_job_active_record-4.1.2/lib/delayed_job_active_record.rb:5:in `<main>'
	 9: from /home/yahonda/git/delayed_job/lib/delayed/worker.rb:66:in `backend='
	 8: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `require'
	 7: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
	 6: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
	 5: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	 4: from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	 3: from /home/yahonda/git/delayed_job/lib/delayed/serialization/active_record.rb:2:in `<main>'
	 2: from /home/yahonda/git/delayed_job/lib/delayed/serialization/active_record.rb:3:in `<module:ActiveRecord>'
	 1: from /home/yahonda/git/delayed_job/lib/delayed/serialization/active_record.rb:4:in `<class:Base>'
/home/yahonda/git/rails/activerecord/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `yaml_as' for ActiveRecord::Base:Class (NoMethodError)
Did you mean?  yaml_tag
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/rake-12.0.0/lib" "/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/integration/queuing_test.rb" ]
/home/yahonda/.rbenv/versions/2.5.0-dev/bin/bundle:23:in `load'
/home/yahonda/.rbenv/versions/2.5.0-dev/bin/bundle:23:in `<main>'
Tasks: TOP => test:integration:delayed_job
(See full trace by running task with --trace)
$
```
### System configuration
**Rails version**:master

**Ruby version**:ruby 2.5.0dev (2017-09-04 trunk 59742) [x86_64-linux]

**Comment by y-yagi** [comment]
It seems issue of `delayed_job`.
I sent a PR. https://github.com/collectiveidea/delayed_job/pull/996

**Comment by yahonda** [comment]
Thanks for opening a pull request to delayed_job. Your pull request resolves this issue.

```ruby 
$ bundle exec rake test:integration:delayed_job
/home/yahonda/.rbenv/versions/2.5.0-dev/bin/ruby -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/rake-12.0.0/lib" "/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/integration/queuing_test.rb"
Using delayed_job


*** rake aj:integration:delayed_job ***
== 20170904232749 CreateDelayedJobs: migrating ================================
-- create_table(:delayed_jobs, {:force=>true})
   -> 0.0018s
-- add_index(:delayed_jobs, [:priority, :run_at], {:name=>"delayed_jobs_priority"})
   -> 0.0012s
== 20170904232749 CreateDelayedJobs: migrated (0.0032s) =======================

Run options: --seed 2561

# Running:

.SS..S.....

Finished in 23.328816s, 0.4715 runs/s, 0.5144 assertions/s.
11 runs, 12 assertions, 0 failures, 0 errors, 3 skips

You have skipped tests. Run with --verbose for details.
$
```

**Comment by yahonda** [comment]
Closing this and see how collectiveidea/delayed_job#996 goes.

**Comment by domainoverflow** [comment]
I am having the exact same issue but on 2.5.5 now. Would you please recommend a workaround ? thanks.

**Comment by yahonda** [comment]
Upgrade delayed_job version to 4.1.4.
https://github.com/collectiveidea/delayed_job/blob/master/CHANGELOG.md
