### ISSUE TITLE
maintain_test_schema! does not work with engines

### ISSUE THREAD

**Issue by aaronjensen** [rails/rails#30765]
### Steps to reproduce

Clone this repo:

https://github.com/aaronjensen/rails-engine-maintain_test_schema-repro

```
bundle
bin/rails db:create
bin/rails db:migrate
bin/rails test
```

### Expected behavior
The test db should get updated

### Actual behavior

```
/Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:576:in `check_pending!':  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=test

        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:589:in `load_schema_if_pending!'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:595:in `block in maintain_test_schema!'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:826:in `suppress_messages'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:600:in `method_missing'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:595:in `maintain_test_schema!'
        from /Users/aaronjensen/Source/temp/foobar/test/test_helper.rb:4:in `<top (required)>'
        from /Users/aaronjensen/Source/temp/foobar/test/foobar_test.rb:1:in `require'
        from /Users/aaronjensen/Source/temp/foobar/test/foobar_test.rb:1:in `<top (required)>'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/test_unit/runner.rb:50:in `require'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/test_unit/runner.rb:50:in `block in load_tests'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/test_unit/runner.rb:50:in `each'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/test_unit/runner.rb:50:in `load_tests'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/test_unit/runner.rb:39:in `run'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/test/test_command.rb:38:in `perform'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine/commands.rb:7:in `require'
        from /Users/aaronjensen/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine/commands.rb:7:in `<top (required)>'
        from bin/rails:14:in `require'
        from bin/rails:14:in `<main>'
```

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.1

**Comment by aaronjensen** [comment]
To make matters worse, you can't actually run the command it suggests:

```
$ bin/rails db:migrate RAILS_ENV=test
== 20170927055920 CreateFoobarTickets: migrating ==============================
-- create_table(:foobar_tickets)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "foobar_tickets" already exists
: CREATE TABLE "foobar_tickets" ("id" bigserial primary key, "assigned_to" bigint, "conversation_id" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
/Users/aaronjensen/Source/temp/foobar/db/migrate/20170927055920_create_foobar_tickets.rb:3:in `change'
bin/rails:14:in `require'
bin/rails:14:in `<main>'
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "foobar_tickets" already exists
: CREATE TABLE "foobar_tickets" ("id" bigserial primary key, "assigned_to" bigint, "conversation_id" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
/Users/aaronjensen/Source/temp/foobar/db/migrate/20170927055920_create_foobar_tickets.rb:3:in `change'
bin/rails:14:in `require'
bin/rails:14:in `<main>'
PG::DuplicateTable: ERROR:  relation "foobar_tickets" already exists
/Users/aaronjensen/Source/temp/foobar/db/migrate/20170927055920_create_foobar_tickets.rb:3:in `change'
bin/rails:14:in `require'
bin/rails:14:in `<main>'
Tasks: TOP => db:migrate => app:db:migrate
(See full trace by running task with --trace)
```
