### ISSUE TITLE
Rails can't save model with serialized Array when column has null: false

### ISSUE THREAD

**Issue by pboling** [rails/rails#30810]
### Steps to reproduce

Open `activerecord/test/cases/serialized_attribute_test.rb` and update the following test, by adding the last line (`assert_equal light.save, true`):
```
  def test_regression_serialized_default_on_text_column_with_null_false
    light = TrafficLight.new
    assert_equal [], light.state
    assert_equal [], light.long_state
    assert_equal light.save, true
  end
```

Where `TrafficLight` is defined as:
```
class TrafficLight < ActiveRecord::Base
  serialize :state, Array
  serialize :long_state, Array
end
```

### Expected behavior

The record is saved to the database successfully.

### Actual behavior
```
  1) Error:
SerializedAttributeTest#test_regression_serialized_default_on_text_column_with_null_false:
ActiveRecord::StatementInvalid: SQLite3::ConstraintException: NOT NULL constraint failed: traffic_lights.long_state: INSERT INTO "traffic_lights" ("created_at", "updated_at") VALUES (?, ?)
    /Users/pboling/.rvm/gems/ruby-2.4.2/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step'
    /Users/pboling/.rvm/gems/ruby-2.4.2/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `block in each'
    /Users/pboling/.rvm/gems/ruby-2.4.2/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
    /Users/pboling/.rvm/gems/ruby-2.4.2/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:302:in `to_a'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:302:in `block in exec_query'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
    /Users/pboling/Documents/src/forks/rails/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:281:in `exec_query'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:76:in `exec_insert'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/relation.rb:64:in `insert'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/persistence.rb:524:in `_create_record'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/counter_cache.rb:139:in `_create_record'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/locking/optimistic.rb:75:in `_create_record'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/attribute_methods/dirty.rb:133:in `_create_record'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/callbacks.rb:306:in `block in _create_record'
    /Users/pboling/Documents/src/forks/rails/activesupport/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
    /Users/pboling/Documents/src/forks/rails/activesupport/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/callbacks.rb:306:in `_create_record'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/timestamp.rb:57:in `_create_record'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/persistence.rb:504:in `create_or_update'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/callbacks.rb:302:in `block in create_or_update'
    /Users/pboling/Documents/src/forks/rails/activesupport/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
    /Users/pboling/Documents/src/forks/rails/activesupport/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/callbacks.rb:302:in `create_or_update'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/persistence.rb:120:in `save'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/validations.rb:37:in `save'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/attribute_methods/dirty.rb:21:in `save'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/transactions.rb:220:in `transaction'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/transactions.rb:286:in `block in save'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
    /Users/pboling/Documents/src/forks/rails/activerecord/lib/active_record/transactions.rb:285:in `save'
    /Users/pboling/Documents/src/forks/rails/activerecord/test/cases/serialized_attribute_test.rb:240:in `test_regression_serialized_default_on_text_column_with_null_false'

4417 runs, 12086 assertions, 0 failures, 1 errors, 2 skips
```

### System configuration
**Rails version**:
4.2.10, but this code is unchanged in all newer versions, and I expect the same bug and behavior everywhere.

**Ruby version**:
2.4.2 MRI

**Comment by pboling** [comment]
In debugging this in my own app:
```
[20, 29] in /Users/pboling/.rvm/gems/ruby-2.3.4/gems/activerecord-4.2.10/lib/active_record/type/serialized.rb
   20:         end
   21:       end
   22:
   23:       def type_cast_for_database(value)
   24:         byebug
=> 25:         return if value.nil?
   26:         unless default_value?(value)
   27:           super coder.dump(value)
   28:         end
   29:       end
(byebug) value
[]
(byebug) default_value?(value)
true
(byebug) coder.dump(value)
"--- []\n"
(byebug) exit
```

`"--- []\n"` is the value we need to go to the database, but it isn't being set because `default_value?(value) # => true`, and so `super coder.dump(value)` never gets called.

**Comment by pboling** [comment]
Unfortunately when I fix this spec to behave the way I think it should it breaks another spec, and I believe the two specs are fundamentally enforcing this bug, making it difficult to fix without breaking a spec, namely, the following:
```
  def test_nil_is_not_changed_when_serialized_with_a_class
    Topic.serialize(:content, Array)

    topic = Topic.new(content: nil)

    assert_not topic.content_changed?
  end
```

**Comment by pboling** [comment]
A new test that validates overriding the defaults with user specified values that happen to match the defaults also fails:
```
  def test_serialized_user_specified_value_matches_default_on_text_column_with_null_false
    light = TrafficLight.new(state: [], long_state: [])
    assert_equal [], light.state
    assert_equal [], light.long_state
    assert_equal(light.save, true)
  end
```
Failure same as before:
```
  1) Error:
SerializedAttributeTest#test_serialized_user_specified_value_matches_default_on_text_column_with_null_false:
ActiveRecord::StatementInvalid: SQLite3::ConstraintException: NOT NULL constraint failed: traffic_lights.long_state: INSERT INTO "traffic_lights" ("created_at", "updated_at") VALUES (?, ?)
```

**Comment by sgrif** [comment]
This is the expected behavior. `serialize :foo, Array` will treat an empty array as null. If you'd like to customize the behavior, please use the attributes API instead.

**Comment by pboling** [comment]
@sgrif Can Is there a desire for documentation around the incompatibility of `NOT NULL` and `serialize :foo, Array`?  I could work on that instead.  Judging by the issue tracker this seems to be a recurring confusion.

**Comment by sgrif** [comment]
No, `serialize` has been "soft deprecated", in that we do not currently have any plans to remove it, but it no longer is shown in our API documentation and is not recommended for use in new code.

**Comment by matthewd** [comment]
Small correction: it is still [in the API documentation](http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize), and the second paragraph of its description is:

> Empty objects as `{}`, in the case of `Hash`, or `[]`, in the case of `Array`, will always be persisted as null.

While that isn't, strictly, calling out the fact that null values can't be stored in a column with a `NOT NULL` constraint, it does get pretty close.
