### ISSUE TITLE
"invalid byte sequence" in request with proprietary format

### ISSUE THREAD

**Issue by tsujigiri** [rails/rails#31028]
In one of our controllers, we process requests from PayPal about processed transactions. This comes in a format we don't particularly care for. We just pass it into the PayPal client to verify it and we are good. The request spec for that randomly fails, though, because Instrumentation tries to parse it as UTF8 and depending on who is faster, the controller or Instrumentation, the request either fails or it doesn't. We haven't seen it in production lately, since not every request contains invalid encoding and we are also not sure whether this is something that was fixed in a later Rails version.

Is there any way to tell Instrumentation to ignore specific parameters or apply sanitation only for Instrumentation? Any other ideas?

The backtrace from the test looks like this:

```
     Failure/Error: post '/pay_pal_payments/callback', params: "foo=#{unsanitary_string}"

     ActionController::BadRequest:
       Invalid request parameters: invalid byte sequence in UTF-8
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/query_parser.rb:72:in `rescue in parse_nested_query'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/query_parser.rb:61:in `parse_nested_query'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/request.rb:468:in `parse_query'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/request.rb:343:in `POST'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/http/request.rb:355:in `block (2 levels) in POST'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/http/parameters.rb:80:in `block in parse_formatted_parameters'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/http/parameters.rb:80:in `fetch'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/http/parameters.rb:80:in `parse_formatted_parameters'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/http/request.rb:354:in `block in POST'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/request.rb:57:in `fetch'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/request.rb:57:in `fetch_header'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/http/request.rb:353:in `POST'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/http/parameters.rb:45:in `parameters'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/http/filter_parameters.rb:41:in `filtered_parameters'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_controller/metal/instrumentation.rb:21:in `process_action'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
     # /home/helge/.gem/ruby/2.4.0/gems/activerecord-5.0.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/abstract_controller/base.rb:126:in `process'
     # /home/helge/.gem/ruby/2.4.0/gems/actionview-5.0.6/lib/action_view/rendering.rb:30:in `process'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_controller/metal.rb:190:in `dispatch'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_controller/metal.rb:262:in `dispatch'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/routing/route_set.rb:32:in `serve'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/journey/router.rb:39:in `block in serve'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/journey/router.rb:26:in `each'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/journey/router.rb:26:in `serve'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/routing/route_set.rb:727:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
     # /home/helge/.gem/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
     # /home/helge/.gem/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
     # /home/helge/.gem/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/cookies.rb:613:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
     # /home/helge/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
     # /home/helge/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
     # /home/helge/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:90:in `run_callbacks'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/bugsnag-5.3.3/lib/bugsnag/rack.rb:34:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/railties-5.0.6/lib/rails/rack/logger.rb:36:in `call_app'
     # /home/helge/.gem/ruby/2.4.0/gems/railties-5.0.6/lib/rails/rack/logger.rb:24:in `block in call'
     # /home/helge/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:69:in `block in tagged'
     # /home/helge/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /home/helge/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:69:in `tagged'
     # /home/helge/.gem/ruby/2.4.0/gems/railties-5.0.6/lib/rails/rack/logger.rb:24:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/request_id.rb:24:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/static.rb:136:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:522:in `call'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /home/helge/.gem/ruby/2.4.0/gems/rack-test-0.6.3/lib/rack/test.rb:124:in `request'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/testing/integration.rb:334:in `process'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/testing/integration.rb:361:in `process_with_kwargs'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/testing/integration.rb:21:in `post'
     # /home/helge/.gem/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/testing/integration.rb:442:in `block (2 levels) in <module:Runner>'
     # /home/helge/.gem/ruby/2.4.0/gems/rails-controller-testing-1.0.2/lib/rails/controller/testing/integration.rb:12:in `block (2 levels) in <module:Integration>'
     # ./spec/requests/pay_pal_callback_encoding_spec.rb:17:in `block (2 levels) in <top (required)>'
     # /home/helge/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
     # /home/helge/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
     # /home/helge/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
     # /home/helge/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
     # /home/helge/.gem/ruby/2.4.0/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # -e:1:in `<main>'
     # ------------------
     # --- Caused by: ---
     # ArgumentError:
     #   invalid byte sequence in UTF-8
     #   /home/helge/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/query_parser.rb:81:in `normalize_params'


```

### System configuration
**Rails version**: 5.0.6
**Ruby version**: 2.4.2p198

**Comment by al2o3cr** [comment]
Can you verify that your PayPal account is set to use UTF-8 consistently? Some digging turned up very similar-sounding errors like [this StackOverflow question](https://stackoverflow.com/questions/36319174/paypal-ipn-invalid-byte-sequence-in-utf-8) or this [PayPal community post](https://www.paypal-community.com/t5/How-to-use-PayPal-Archive/IPN-always-returns-INVALID-status-with-foreign-characters-in/td-p/27723) that appear to be caused by data not always being in the right encoding. [This SO answer (and the one below it)](https://stackoverflow.com/questions/12284341/paypal-ipn-override-charset) has more info on how to change the default character set. Make sure you do this in the sandbox environment as well.

**Comment by tsujigiri** [comment]
Oh! I didn't even think about this being an option. I just assumed they don't sanitize the data users put into their system. Thanks for figuring that out for me! 😄 

In general, though, what if you want to receive data that's not UTF8/you don't know the formatting of? Aren't you out of luck then?

**Comment by eugeneius** [comment]
http://api.rubyonrails.org/v5.1.4/classes/ActionController/ParameterEncoding/ClassMethods.html#method-i-skip_parameter_encoding

**Comment by eugeneius** [comment]
Actually that setting doesn't change the encoding until after the point where your example is raising, so it wouldn't help.

Could you share the contents of `unsanitary_string` from the stacktrace you posted above?

**Comment by tsujigiri** [comment]
Turns out that's just random data, which explains why its failing randomly. 🤦‍ I should have looked at it earlier. My bad. Investigating it, it turns out that it fails if there is an `&` in it, which makes the next thing a key which may then contain gibberish and makes it fail when Rails tries to comprehend it. I assume. So, yeah. Sorry for stealing your time!

**Comment by al2o3cr** [comment]
@tsujigiri I believe that Rack will do the right thing if the data indicates what charset to use in `Content-Type`, but I can't track down specifically where that happens. I'd be curious what headers Paypal is sending with this data.
