### ISSUE TITLE
Can't use full Rails engine without database/ActiveRecord

### ISSUE THREAD

**Issue by SaladFork** [rails/rails#31030]
I'm trying to create a Rails engine for use in my application that does not interface with a database at all.

### Steps to reproduce

1. Create a new Rails engine and omit ActiveRecord (my understand is that this is what I need to do if I'm not using a database):
```bash
$ rails plugin new example_engine --full --skip-active-record
# or
$ rails plugin new example_engine --full -O
```

2. Switch to the engine's directory
```bash
$ cd example_engine
```

3. Update the gemspec so it has no FIXME/TODO or invalid homepage URL (otherwise Rails will refuse to run tests or start a server...)
```bash
$ sed -e 's/TODO: //g' -e '/homepage/d' -i -- example_engine.gemspec
```

4. Ensure that ActiveRecord is commented out and not included in `test/dummy/config/application.rb`:
```bash
$ grep active_record test/dummy/config/application.rb
# require "active_record/railtie"
```

5. Start a Rails server:
```bash
$ rails server
=> Booting WEBrick
=> Rails 5.1.4 application starting in development on http://localhost:3000
```

6. Load `localhost:3000` in a browser or otherwise make a request against the Rails server.
```bash
$ curl localhost:3000
```

7. Observe error in Rails console log and 500 server response:
```
RuntimeError (Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - ["config/database.yml"]):

railties (5.1.4) lib/rails/application/configuration.rb:139:in `database_configuration'
activerecord (5.1.4) lib/active_record/railtie.rb:121:in `block (2 levels) in <class:Railtie>'
activesupport (5.1.4) lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
...
```

### Expected behavior
The dummy application should load successfully and show the "Yay! You’re on Rails!" page.

### Actual behavior
A 500 error occurs as a result of there being no database configuration.

### System configuration
**Rails version**: 5.1.4
**Ruby version**: 2.4.0

**Comment by SaladFork** [comment]
Thanks! Glad to hear it. I searched but apparently not well enough D:
