### ISSUE TITLE
ActiveSupport::MemoryStore cannot handle ActiveRecord::Attributes defaults with proc

### ISSUE THREAD

**Issue by JanStevens** [rails/rails#31216]
### Steps to reproduce
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.1.4"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post

  attribute :config, :string, default: -> { "value" }
end

class BugTest < Minitest::Test
  def test_memory_store_fetch
    store = ActiveSupport::Cache::MemoryStore.new
    comment = Comment.create!

    store.fetch(:key) { comment }
  end
end
```
### Expected behavior
I expect that MemoryStore returns me the cached object, but it fails with following backtrace

```
TypeError: no _dump_data is defined for class Proc
    /Users/fritz/.asdf/installs/ruby/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/cache.rb:664:in `dump'
    /Users/fritz/.asdf/installs/ruby/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/cache.rb:664:in `dup_value!'
    /Users/fritz/.asdf/installs/ruby/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/cache/memory_store.rb:130:in `write_entry'
    /Users/fritz/.asdf/installs/ruby/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/cache.rb:400:in `block in write'
    /Users/fritz/.asdf/installs/ruby/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/cache.rb:555:in `block in instrument'
    /Users/fritz/.asdf/installs/ruby/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
    /Users/fritz/.asdf/installs/ruby/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/cache.rb:555:in `instrument'
    /Users/fritz/.asdf/installs/ruby/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/cache.rb:398:in `write'
    /Users/fritz/.asdf/installs/ruby/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/cache.rb:589:in `save_block_result_to_cache'
    /Users/fritz/.asdf/installs/ruby/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/cache.rb:297:in `fetch'
    /Users/fritz/Library/Preferences/RubyMine2017.2/scratches/scratch_58.rb:53:in `test_memory_store_fetch'
```

### Actual behavior
It blows up with `TypeError: no _dump_data is defined for class Proc`

### System configuration
**Rails version**: 5.1.4 (also on 5.1-stable branch)
**Ruby version**: 2.3.5 & 2.4.2

**Comment by joshmn** [comment]
Related #7375

**Comment by saveriomiroddi** [comment]
This issue ultimately boils down to serialization of Procs; see for example:

- http://yehudakatz.com/2011/11/19/how-to-marshal-procs-using-rubinius/
- http://rubyquiz.com/quiz38.html

The behavior in fact can be shown via:

```ruby
myproc = -> {}
Marshal.dump(myproc)
```

You can reduce the test case by entirely dropping the `Post` model.

Ultimately, this is a design concern - to include, or not, support for performing this operation (which can't be cleanly done with the MRI).

There is a general opinion that one shouldn't serialize complex objects. In this case, an alternative is to store the `Comment` attributes, and marshal those instead; when fetching, a new Post can be instantiated (and processed at will) using them.

**Comment by rafaelfranca** [comment]
@sgrif not priority but you may want to have a look here.

**Comment by sgrif** [comment]
This problem can be generalized to "Attributes with a proc default value cannot be marshalled".
