### ISSUE TITLE
Sprockets error when precompiling assets on new app generated with --skip-keeps

### ISSUE THREAD

**Issue by calebthompson** [rails/rails#31288]
### Steps to reproduce

```
$ rails new --no-rc --skip-keeps
# commit to git, clone elsewhere, or push to a service like Heroku
$ rake assets:precompile
```

### Expected behavior

The task should complete without errors.

### Actual behavior

What's happening here is that `app/assets/javascripts/channels` is not present in the Git repo, so the call `require_tree channels` fails because that directory does not exist.

```
$ rake assets:precompile
Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
rake aborted!
Sprockets::ArgumentError: require_tree argument must be a directory
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/app/assets/javascripts/cable.js:6
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:379:in `expand_relative_dirname'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:244:in `process_require_tree_directive'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `each'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `process_directives'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:83:in `_call'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:68:in `call'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/tmp/build_4b3daa98e7b992246e9493ff001a8b34/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
```
### System configuration
**Rails version**: 5.2.0.beta2

**Comment by Edouard-chin** [comment]
For reference this issue was already reported https://github.com/rails/rails/issues/22708  and a fix was attempted https://github.com/rails/rails/pull/22753 although I'm not sure how the proposed solution could have work

**Comment by calebthompson** [comment]
Ah, thanks. I'll close this one since it's already covered.
