### ISSUE TITLE
active_storage:install fails when gem `bullet` is there

### ISSUE THREAD

**Issue by akkee** [rails/rails#31347]
### Steps to reproduce
Run `rails active_storage:install`, while using the gem `bullet` with Rails 5.2.0 beta-2

### Expected behavior
Well, the migration should run as expected.

### Actual behavior
This is the stack-trace of what happens

```
[~/mysites/codephod2]$ rails active_storage:install
rails aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'bullet'.
Gem Load Error is: Bullet does not support active_record ActiveRecord::VERSION yet
Backtrace for gem load error is:
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bullet-5.6.1/lib/bullet/dependency.rb:28:in `active_record_version'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bullet-5.6.1/lib/bullet.rb:12:in `<module:Bullet>'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bullet-5.6.1/lib/bullet.rb:9:in `<top (required)>'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `require'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `each'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `block in require'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
/Volumes/gitdisk/mysites/codephod2/config/application.rb:7:in `<top (required)>'
/Volumes/gitdisk/mysites/codephod2/Rakefile:5:in `require'
/Volumes/gitdisk/mysites/codephod2/Rakefile:5:in `<top (required)>'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/rake-12.3.0/lib/rake/application.rb:703:in `raw_load_rakefile'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/rake-12.3.0/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/rake-12.3.0/lib/rake/application.rb:103:in `load_rakefile'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta2/lib/rails/command.rb:48:in `invoke'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `each'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `block in require'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
/Volumes/gitdisk/mysites/codephod2/config/application.rb:7:in `<top (required)>'
/Volumes/gitdisk/mysites/codephod2/Rakefile:5:in `require'
/Volumes/gitdisk/mysites/codephod2/Rakefile:5:in `<top (required)>'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta2/lib/rails/command.rb:48:in `invoke'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
Bullet does not support active_record ActiveRecord::VERSION yet
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bullet-5.6.1/lib/bullet/dependency.rb:28:in `active_record_version'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bullet-5.6.1/lib/bullet.rb:12:in `<module:Bullet>'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bullet-5.6.1/lib/bullet.rb:9:in `<top (required)>'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `require'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `each'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `block in require'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
/Volumes/gitdisk/mysites/codephod2/config/application.rb:7:in `<top (required)>'
/Volumes/gitdisk/mysites/codephod2/Rakefile:5:in `require'
/Volumes/gitdisk/mysites/codephod2/Rakefile:5:in `<top (required)>'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta2/lib/rails/command.rb:48:in `invoke'
/Users/akashsrivastava/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

### System configuration
**Rails version**:
`5.2.0.beta2`

**Ruby version**:
`2.4.0`

**Comment by guilleiguaran** [comment]
The problem is that Bullet 5.6 doesn't support ActiveRecord 5.2, you should upgrade to 5.7: https://github.com/flyerhzm/bullet/commit/52654917ca487a7e3608fc7e0571511f5d68b8b7
