### ISSUE TITLE
Generator CLI allows naming columns with forbidden characters

### ISSUE THREAD

**Issue by O-kasso** [rails/rails#31430]
### Steps to reproduce
1) `rails g scaffold foobar goodname bad-name`
2) `rails db:migrate`
3) Migration fails because of hyphen in "bad-name"
### Expected behavior
`rails g scaffold` fails with a descriptive error explaining that the hyphen character `-` is not allowed in column names

### Actual behavior
generator succeeds, creates a bunch of files, only for migrations to later fail:

```
== 20171213194949 CreateFoobars: migrating ====================================
-- create_table(:foobars)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `-' for :bad:Symbol
/Users/O-kasso/Code/o-kasso/shine/db/migrate/20171213194949_create_foobars.rb:5:in `block in change'
/Users/O-kasso/Code/o-kasso/shine/db/migrate/20171213194949_create_foobars.rb:3:in `change'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
NoMethodError: undefined method `-' for :bad:Symbol
/Users/O-kasso/Code/o-kasso/shine/db/migrate/20171213194949_create_foobars.rb:5:in `block in change'
/Users/O-kasso/Code/o-kasso/shine/db/migrate/20171213194949_create_foobars.rb:3:in `change'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
```

### System configuration
**Rails version**: 5.1.4
**Ruby version**: 2.4.2

**Comment by O-kasso** [comment]
Perhaps there's a clever way to slip in a scan for invalid chars in rails/railties/lib/rails/generators/generated_attribute.rb
