### ISSUE TITLE
selenium-webdriver in Rails 5.2 system tests: "unable to connect to chromedriver 127.0.0.1:9515"

### ISSUE THREAD

**Issue by GBH** [rails/rails#31546]
## Meta -
OS:  Ubuntu
Selenium-webdriver Version:  3.8.0
Rails Version: 5.2.beta

## Expected Behavior -
Being able to run tests

## Actual Behavior -
```
Selenium::WebDriver::Error::WebDriverError: unable to connect to chromedriver 127.0.0.1:9515
    selenium-webdriver (3.8.0) lib/selenium/webdriver/common/service.rb:142:in `connect_until_stable'
    selenium-webdriver (3.8.0) lib/selenium/webdriver/common/service.rb:72:in `block in start'
    selenium-webdriver (3.8.0) lib/selenium/webdriver/common/socket_lock.rb:39:in `locked'
    selenium-webdriver (3.8.0) lib/selenium/webdriver/common/service.rb:69:in `start'
    selenium-webdriver (3.8.0) lib/selenium/webdriver/chrome/driver.rb:41:in `initialize'
    selenium-webdriver (3.8.0) lib/selenium/webdriver/common/driver.rb:44:in `new'
    selenium-webdriver (3.8.0) lib/selenium/webdriver/common/driver.rb:44:in `for'
    selenium-webdriver (3.8.0) lib/selenium/webdriver.rb:84:in `for'
    capybara (2.16.1) lib/capybara/selenium/driver.rb:23:in `browser'
    actionpack (5.2.0.beta2) lib/action_dispatch/system_testing/driver.rb:52:in `block in register_selenium'
    actionpack (5.2.0.beta2) lib/action_dispatch/system_testing/driver.rb:51:in `tap'
    actionpack (5.2.0.beta2) lib/action_dispatch/system_testing/driver.rb:51:in `register_selenium'
    actionpack (5.2.0.beta2) lib/action_dispatch/system_testing/driver.rb:27:in `block in register'
```

## Steps to reproduce

A completely fresh vanilla Rails app with a simple generated system test.

Not sure what I need to do. Chromedriver is installed and can be ran:

```
$ which chromedriver
/home/oleg/.rbenv/shims/chromedriver

$ chromedriver -v
ChromeDriver 2.34.522913 (36222509aa6e819815938cbf2709b4849735537c)
```

Any clues what I might be missing here? Thanks.

**Comment by y-yagi** [comment]
I confirmed with a newly generated application. But not reproduced. 

Env: 

```
$ ./bin/rails -v
Rails 5.2.0.beta2
$ ruby -v
ruby 2.5.0rc1 (2017-12-14 trunk 61243) [x86_64-linux]
$ bundle exec chromedriver -v 
ChromeDriver 2.34.522913 (36222509aa6e819815938cbf2709b4849735537c)
$ google-chrome --version
Google Chrome 63.0.3239.108  
$ uname -a
Linux y-yagi 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
``` 

I assume that your environments' problem.  Please check your environment(e.g. version of chrome). Thanks!

**Comment by GBH** [comment]
Any suggestion on how to figure out what the problem might be? Chrome is the latest version.

**Comment by georgeclaghorn** [comment]
I’ve run into this before. Do you have the `chromedriver-helper` gem installed? If so, could you try uninstalling it?

**Comment by GBH** [comment]
@georgeclaghorn It's working! Removed the gem, removed chromedriver from rbenv shims, installed it directly into bin/ and it works now. Thanks.
