### ISSUE TITLE
handling of add_column with :primary_key in migrations

### ISSUE THREAD

**Issue by mmoll** [rails/rails#31553]
https://github.com/theforeman/foreman/blob/develop/db/migrate/20110712070522_create_host_class.rb
is working fine with Rails 5.1.4. When using the current master, I'm seeing the following:
```
== 20110712070522 CreateHostClass: migrating ==================================
-- rename_table(:hosts_puppetclasses, :host_classes)
   -> 0.0007s
-- add_column(:host_classes, :id, :integer, {:primary_key=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
SQLite3::SQLException: Cannot add a PRIMARY KEY column: ALTER TABLE "host_classes" ADD "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
/home/travis/.rvm/gems/ruby-2.4.3/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize'
/home/travis/.rvm/gems/ruby-2.4.3/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/home/travis/.rvm/gems/ruby-2.4.3/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
/home/travis/.rvm/gems/ruby-2.4.3/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:255:in `block (2 levels) in execute'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activesupport/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activesupport/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activesupport/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:254:in `block in execute'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `block (2 levels) in log'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:570:in `block in log'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activesupport/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:561:in `log'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:253:in `execute'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:581:in `add_column'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:301:in `add_column'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:870:in `block in method_missing'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:839:in `block in say_with_time'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:839:in `say_with_time'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:859:in `method_missing'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration/compatibility.rb:110:in `add_column'
/home/travis/build/mmoll/foreman/db/migrate/20110712070522_create_host_class.rb:4:in `up'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:816:in `exec_migration'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:797:in `block (2 levels) in migrate'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:796:in `block in migrate'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:414:in `with_connection'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:795:in `migrate'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:976:in `migrate'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:1257:in `block in execute_migration_in_transaction'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:1325:in `block in ddl_transaction'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:230:in `block in within_new_transaction'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:227:in `within_new_transaction'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/transactions.rb:212:in `transaction'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:1325:in `ddl_transaction'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:1256:in `execute_migration_in_transaction'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:1228:in `block in migrate_without_lock'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:1227:in `each'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:1227:in `migrate_without_lock'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:1177:in `migrate'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:1030:in `up'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/migration.rb:1008:in `migrate'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/home/travis/.rvm/gems/ruby-2.4.3/bundler/gems/rails-1a5bf01fe024/activerecord/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/home/travis/.rvm/gems/ruby-2.4.3/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'
```
full output, if needed, in https://travis-ci.org/mmoll/foreman/builds/320780649

**Comment by y-yagi** [comment]
`:primary_key` type handles as `:integer` type since 202d6578f44ab03ee89ed57b73a97d513fc5a008.  

But `valid_alter_table_type` method check only whether `type` is `:primary_key`.
https://github.com/rails/rails/blob/1a5bf01fe024eb1d91903094327d937f7abcb24d/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L295..L307 

For that reason, `alter_table` does not execute and error.


cc @kamipo
