### ISSUE TITLE
ActiveRecord 5.2.0.beta2: Float::INFINITY not serialized correctly with PostgreSQL Range type

### ISSUE THREAD

**Issue by juno** [rails/rails#31612]
With changes within PR #30725 , I can't store a `Range` object with `Float::INFINITY` (e.g. `1..Float::INFINITY`) into PostgreSQL Range type column.

### Steps to reproduce

1. Start PostgreSQL server
1. Create `test_ar_range` database
   - `$ createdb test_ar_range`
1. Run https://gist.github.com/juno/630dc277dc3dae1d69101d059e3ee14e
   - `$ ruby test.rb`

### Expected behavior

I can set and store a `Range` object with `Float::INFINITY` to PostgreSQL Range type column.

<details>
<summary>Test results with activerecord 5.1.4</summary>

```
$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

$ ruby test.rb
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies...
Using concurrent-ruby 1.0.5
Using i18n 0.9.1
Using minitest 5.10.3
Using thread_safe 0.3.6
Using tzinfo 1.2.4
Using activesupport 5.1.4
Using activemodel 5.1.4
Using arel 8.0.0
Using activerecord 5.1.4
Using bundler 1.16.1
Using pg 0.21.0
-- create_table(:posts, {:force=>true})
D, [2018-01-01T23:19:07.853022 #13828] DEBUG -- :    (10.5ms)  DROP TABLE IF EXISTS "posts"
D, [2018-01-01T23:19:07.863835 #13828] DEBUG -- :    (10.3ms)  CREATE TABLE "posts" ("id" bigserial primary key, "range" int4range)
   -> 0.0543s
D, [2018-01-01T23:19:07.954145 #13828] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.7ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
D, [2018-01-01T23:19:07.967169 #13828] DEBUG -- :    (0.3ms)  BEGIN
D, [2018-01-01T23:19:07.969003 #13828] DEBUG -- :    (0.3ms)  COMMIT
Run options: --seed 42739

# Running:

D, [2018-01-01T23:19:08.012591 #13828] DEBUG -- :    (0.8ms)  BEGIN
D, [2018-01-01T23:19:08.018551 #13828] DEBUG -- :   SQL (2.7ms)  INSERT INTO "posts" ("range") VALUES ($1) RETURNING "id"  [["range", "[1,]"]]
D, [2018-01-01T23:19:08.020607 #13828] DEBUG -- :    (1.2ms)  COMMIT
.

Finished in 0.031658s, 31.5876 runs/s, 31.5876 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```
</details>

### Actual behavior

When set and store a `Range` object with `Float::INFINITY` to PostgreSQL Range type column, `ArgumentError: bad value for range` will raise.

<details>
<summary>Test results with activerecord 5.2.0.beta2</summary>

```
$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

$ ruby test.rb
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies...
Using concurrent-ruby 1.0.5
Using i18n 0.9.1
Using minitest 5.10.3
Using thread_safe 0.3.6
Using tzinfo 1.2.4
Using activesupport 5.2.0.beta2
Using activemodel 5.2.0.beta2
Using arel 9.0.0
Using activerecord 5.2.0.beta2
Using bundler 1.16.1
Using pg 0.21.0
-- create_table(:posts, {:force=>true})
D, [2018-01-01T23:19:42.313546 #13902] DEBUG -- :    (6.5ms)  DROP TABLE IF EXISTS "posts"
D, [2018-01-01T23:19:42.326049 #13902] DEBUG -- :    (12.1ms)  CREATE TABLE "posts" ("id" bigserial primary key, "range" int4range)
   -> 0.0610s
D, [2018-01-01T23:19:42.408356 #13902] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.8ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
D, [2018-01-01T23:19:42.417462 #13902] DEBUG -- :    (0.2ms)  BEGIN
D, [2018-01-01T23:19:42.418690 #13902] DEBUG -- :    (0.2ms)  COMMIT
Run options: --seed 24015

# Running:

D, [2018-01-01T23:19:42.451155 #13902] DEBUG -- :    (0.2ms)  BEGIN
D, [2018-01-01T23:19:42.452297 #13902] DEBUG -- :    (0.3ms)  ROLLBACK
E

Finished in 0.019950s, 50.1253 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_association_stuff:
ArgumentError: bad value for range
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/postgresql/oid/range.rb:38:in `initialize'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/postgresql/oid/range.rb:38:in `new'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/postgresql/oid/range.rb:38:in `serialize'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activemodel-5.2.0.beta2/lib/active_model/attribute.rb:55:in `value_for_database'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/relation/query_attribute.rb:13:in `value_for_database'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/abstract/quoting.rb:144:in `block in type_casted_binds'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/abstract/quoting.rb:144:in `map'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/abstract/quoting.rb:144:in `type_casted_binds'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/postgresql_adapter.rb:590:in `exec_no_cache'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/postgresql_adapter.rb:580:in `execute_and_clear'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/abstract/database_statements.rb:117:in `exec_insert'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/postgresql/database_statements.rb:115:in `exec_insert'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/abstract/database_statements.rb:149:in `insert'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `insert'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/persistence.rb:188:in `_insert_record'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/persistence.rb:727:in `_create_record'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/counter_cache.rb:180:in `_create_record'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/locking/optimistic.rb:77:in `_create_record'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/attribute_methods/dirty.rb:137:in `_create_record'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/callbacks.rb:342:in `block in _create_record'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:132:in `run_callbacks'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/callbacks.rb:342:in `_create_record'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/timestamp.rb:95:in `_create_record'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/persistence.rb:701:in `create_or_update'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/callbacks.rb:338:in `block in create_or_update'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:98:in `run_callbacks'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0.beta2/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/callbacks.rb:338:in `create_or_update'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/persistence.rb:297:in `save!'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/validations.rb:52:in `save!'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/transactions.rb:315:in `block in save!'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/transactions.rb:386:in `block in with_transaction_returning_status'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/abstract/transaction.rb:230:in `block in within_new_transaction'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/abstract/transaction.rb:227:in `within_new_transaction'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/transactions.rb:212:in `transaction'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/transactions.rb:383:in `with_transaction_returning_status'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/transactions.rb:315:in `save!'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/suppressor.rb:48:in `save!'
    /Users/juno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0.beta2/lib/active_record/persistence.rb:53:in `create!'
    test.rb:49:in `test_association_stuff'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```
</details>

### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: 2.5.0

**PostgreSQL version**: 9.6.6

**Comment by mkamensky** [comment]
Endless ranges don't seem to be supported. It seems that adding a `nil?` option to `infinity?` would solve it
