### ISSUE TITLE
test_unit/reporter from beta2 version doesn't work nicely with minitest 5.11

### ISSUE THREAD

**Issue by skatkov** [rails/rails#31657]
### Steps to reproduce
- Have minitest 5.11.1 included in Gemfile
- Create testsuite with two tests that fail
- execute `rake test`

### Expected behavior
-- Testsuite should show two failed tests
-- Error should not be presented

### Actual behavior
- After first test fails testsuite execution stops with exception raised 

My example:
```
F

Failure:
SearchServiceTest#test_with_parent_product [/Users/sk/code/amzstore/test/services/search_service_test.rb:36]:
Expected: 8
  Actual: 1


Traceback (most recent call last):
	18: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:63:in `block in autorun'
	17: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:136:in `run'
	16: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:159:in `__run'
	15: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:159:in `map'
	14: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:159:in `block in __run'
	13: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/railties-5.2.0.beta2/lib/rails/test_unit/line_filtering.rb:10:in `run'
	12: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:319:in `run'
	11: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:347:in `with_info_handler'
	10: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:360:in `on_signal'
	 9: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:320:in `block in run'
	 8: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:320:in `each'
	 7: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:321:in `block (2 levels) in run'
	 6: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:334:in `run_one_method'
	 5: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:785:in `record'
	 4: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:785:in `each'
	 3: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/minitest-5.11.1/lib/minitest.rb:786:in `block in record'
	 2: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/railties-5.2.0.beta2/lib/rails/test_unit/reporter.rb:24:in `record'
	 1: from /Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/railties-5.2.0.beta2/lib/rails/test_unit/reporter.rb:71:in `format_rerun_snippet'
/Users/sk/.rvm/gems/ruby-2.5.0@amzstore_gems/gems/railties-5.2.0.beta2/lib/rails/test_unit/reporter.rb:71:in `method': undefined method `test_with_parent_product' for class `Minitest::Result' (NameError)
```

### Workaround
Lock older version of minitest
`gem 'minitest', '5.10.3' `

### System configuration
**Rails version**:
Rails 5.2.0.beta2

**Ruby version**:
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin15]

**Comment by skatkov** [comment]
Seems like a copy of #31624 
Sorry, closing this issue
