### ISSUE TITLE
Multiple timestamp causes db migrate error on Rails 5.1.4 and MySQL 5.7

### ISSUE THREAD

**Issue by marutosi** [rails/rails#31804]
* ruby 2.2.9p480 (2017-12-15 revision 61259) [x86_64-linux]
* mysql2 gem 0.4.10

# rails 4.2.10

* mysql server 5.7.21

```ruby
class Homu01 < ActiveRecord::Migration
  def change
    create_table :homu01 do |t|
      t.column :createdts01, :timestamp, :null => false
      t.column :createdts02, :timestamp, :null => false
    end
  end
end
```

```sql
CREATE TABLE `homu01` (`id` int(11) auto_increment PRIMARY KEY, `createdts01` datetime NOT NULL, `createdts02` datetime NOT NULL) ENGINE=InnoDB
```

```
mysql> desc homu01;
+-------------+----------+------+-----+---------+----------------+
| Field       | Type     | Null | Key | Default | Extra          |
+-------------+----------+------+-----+---------+----------------+
| id          | int(11)  | NO   | PRI | NULL    | auto_increment |
| createdts01 | datetime | NO   |     | NULL    |                |
| createdts02 | datetime | NO   |     | NULL    |                |
+-------------+----------+------+-----+---------+----------------+
3 rows in set (0.00 sec)

```

# rails 5.1.4

```ruby
class Homu01 < ActiveRecord::Migration[4.2]
  def change
    create_table :homu01 do |t|
      t.column :createdts01, :timestamp, :null => false
      t.column :createdts02, :timestamp, :null => false
    end
  end
end
```

## mysql server 5.5.59

```sql
CREATE TABLE `homu01` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `createdts01` timestamp NOT NULL, `createdts02` timestamp NOT NULL) ENGINE=InnoDB
```

```
mysql> desc homu01;
+-------------+-----------+------+-----+---------------------+-----------------------------+
| Field       | Type      | Null | Key | Default             | Extra                       |
+-------------+-----------+------+-----+---------------------+-----------------------------+
| id          | int(11)   | NO   | PRI | NULL                | auto_increment              |
| createdts01 | timestamp | NO   |     | CURRENT_TIMESTAMP   | on update CURRENT_TIMESTAMP |
| createdts02 | timestamp | NO   |     | 0000-00-00 00:00:00 |                             |
+-------------+-----------+------+-----+---------------------+-----------------------------+
3 rows in set (0.00 sec)
```

## mysql server 5.7.21

```
$ rake db:migrate RAILS_ENV=development
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

== 20180126144548 Homu01: migrating ===========================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:homu01, {:id=>:integer})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Invalid default value for 'createdts02': CREATE TABLE `homu01` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `createdts01` timestamp NOT NULL, `createdts02` timestamp NOT NULL) ENGINE=InnoDB
/home/xxxxx/.rvm/gems/ruby-2.2.7/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/home/xxxxx/.rvm/gems/ruby-2.2.7/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/home/xxxxx/.rvm/gems/ruby-2.2.7/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/home/xxxxx/.rvm/gems/ruby-2.2.7/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/home/xxxxx/.rvm/gems/ruby-2.2.7/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
/home/xxxxx/.rvm/gems/ruby-2.2.7/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/home/xxxxx/.rvm/gems/ruby-2.2.7/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
.
.
.
```

I tried this.

```diff
$ hg diff
diff --git a/db/migrate/20180126144548_homu01.rb b/db/migrate/20180126144548_homu01.rb
--- a/db/migrate/20180126144548_homu01.rb
+++ b/db/migrate/20180126144548_homu01.rb
@@ -1,4 +1,4 @@
-class Homu01 < ActiveRecord::Migration[4.2]
+class Homu01 < ActiveRecord::Migration[5.1]
   def change
     create_table :homu01 do |t|
       t.column :createdts01, :timestamp, :null => false
```

But no change.

According to [stackoverflow](https://stackoverflow.com/questions/42020422/mysql-server-5-7-17-multiple-timestamp-not-null-fields-on-table),
MySQL team said [Not a Bug](https://bugs.mysql.com/bug.php?id=80163).

I don't know why SQL type was changed from Rails 4.2 **datetime** to Rails 5.1 **timestamp**.

**Comment by rafaelfranca** [comment]
@kamipo can you take a look since you are our MySQL expert?

**Comment by kamipo** [comment]
This change is for dumping native timestamp types correctly which was introduced at #23553.

Historically, TIMESTAMP type has nonstandard behaviors for default values and NULL-value.
But the nonstandard behaviors are deprecated and will be removed in a future MySQL release.

So please enable `explicit_defaults_for_timestamp` on your server.

https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp

**Comment by nozpheratu** [comment]
So I have to get all the developers in my office to enable this obscure non-default option in their mysql server config? This is Rails, whatever happened to convention over configuration? Or is the convention to now change your configuration?

**Comment by Ex-Ark** [comment]
Had the same problem (multiple version of mysql config across developers , prod server, CI server)
I replaced all my `t.timestamp` columns to `t.datetime`. Doesn't change anything for Rails, as it converts before inserting values to the database. (only downside is datetime use 8 bytes instead of 4 for timestamp).

I now have multiple datetime column set to NOT NULL and it works on every mysql config I have.
