### ISSUE TITLE
There is no clear message if there is no master.key file

### ISSUE THREAD

**Issue by rsmything** [rails/rails#31822]
### Steps to reproduce

1. Clone any your project with existing credentials.yml.enc
2. Forget to put the master.key file
3. rails s

```
=> Booting Puma
=> Rails 5.2.0.beta2 application starting in development 
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
	62: from bin/rails:5:in `<main>'
	61: from bin/rails:5:in `load'
	60: from /Users/romansuleymanov/Downloads/Honshu/bin/spring:16:in `<top (required)>'
	59: from /Users/romansuleymanov/Downloads/Honshu/bin/spring:16:in `require'
	58: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	57: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	56: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	55: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	54: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	53: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	52: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	51: from /Users/romansuleymanov/Downloads/Honshu/bin/rails:11:in `<top (required)>'
	50: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/activesupport/lib/active_support/dependencies.rb:283:in `require'
	49: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
	48: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
	47: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	46: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	45: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/commands.rb:18:in `<main>'
	44: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/command.rb:46:in `invoke'
	43: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/command/base.rb:65:in `perform'
	42: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	41: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	40: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	39: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/commands/server/server_command.rb:142:in `perform'
	38: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/commands/server/server_command.rb:142:in `tap'
	37: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	36: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/commands/server/server_command.rb:51:in `start'
	35: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	34: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
	33: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/commands/server/server_command.rb:27:in `app'
	32: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
	31: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	30: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	29: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	28: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	27: from config.ru:in `<main>'
	26: from config.ru:in `new'
	25: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	24: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	23: from config.ru:5:in `block in <main>'
	22: from config.ru:5:in `require_relative'
	21: from /Users/romansuleymanov/Downloads/Honshu/config/environment.rb:7:in `<main>'
	20: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/application.rb:360:in `initialize!'
	19: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/initializable.rb:60:in `run_initializers'
	18: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	17: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	16: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	15: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
	14: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
	13: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	12: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	11: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	10: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	 9: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
	 8: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/initializable.rb:32:in `run'
	 7: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-7ae26885d96d/railties/lib/rails/initializable.rb:32:in `instance_exec'
	 6: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/mongoid-3ea31956b28b/lib/mongoid/railtie.rb:58:in `block in <class:Railtie>'
	 5: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/mongoid-3ea31956b28b/lib/mongoid.rb:104:in `load!'
	 4: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/mongoid-3ea31956b28b/lib/mongoid/config.rb:87:in `load!'
	 3: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/mongoid-3ea31956b28b/lib/mongoid/config/environment.rb:40:in `load_yaml'
	 2: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/erb.rb:885:in `result'
	 1: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/erb.rb:885:in `eval'
(erb):164:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
```

### Expected behavior
Clear message 

Spent some hours on the solution of the problem. The file is contained in .gitignore... :(

**Comment by y-yagi** [comment]
Thanks for your report. This issue already fixed with #31348. 
In master, an error message is showed as below. 

```
./bin/rails s -e production
=> Booting Puma
=> Rails 5.2.0.beta2 application starting in production 
=> Run `rails server -h` for more startup options
Missing encryption key to decrypt file with. Ask your team for your master key and write it to /home/y-yagi/src/tmp/master/config/master.key or put it in the ENV['RAILS_MASTER_KEY'].
Exiting 
```

**Comment by rsmything** [comment]
Updated last changes but error is reproduces

Ruby 2.5
**Gemfile.lock**
GIT
  remote: https://github.com/rails/rails.git
  revision: 889eb91d5f439eab647fbbef47886c61dc98e4e8

1. Delete config/master.key
2. Try to start rails (rails s)
3. Get error

```
=> Booting Puma
=> Rails 5.2.0.beta2 application starting in development 
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
	62: from bin/rails:5:in `<main>'
	61: from bin/rails:5:in `load'
	60: from /Users/romansuleymanov/Projects/Honshu/bin/spring:16:in `<top (required)>'
	59: from /Users/romansuleymanov/Projects/Honshu/bin/spring:16:in `require'
	58: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	57: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	56: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	55: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	54: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	53: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	52: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	51: from /Users/romansuleymanov/Projects/Honshu/bin/rails:11:in `<top (required)>'
	50: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/activesupport/lib/active_support/dependencies.rb:283:in `require'
	49: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
	48: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
	47: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	46: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	45: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/commands.rb:18:in `<main>'
	44: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/command.rb:46:in `invoke'
	43: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/command/base.rb:65:in `perform'
	42: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	41: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	40: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	39: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/commands/server/server_command.rb:142:in `perform'
	38: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/commands/server/server_command.rb:142:in `tap'
	37: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	36: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/commands/server/server_command.rb:51:in `start'
	35: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	34: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
	33: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/commands/server/server_command.rb:27:in `app'
	32: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
	31: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	30: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	29: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	28: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	27: from config.ru:in `<main>'
	26: from config.ru:in `new'
	25: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	24: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	23: from config.ru:5:in `block in <main>'
	22: from config.ru:5:in `require_relative'
	21: from /Users/romansuleymanov/Projects/Honshu/config/environment.rb:7:in `<main>'
	20: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/application.rb:360:in `initialize!'
	19: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/initializable.rb:60:in `run_initializers'
	18: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	17: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	16: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	15: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
	14: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
	13: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	12: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	11: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	10: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	 9: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
	 8: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/initializable.rb:32:in `run'
	 7: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/rails-889eb91d5f43/railties/lib/rails/initializable.rb:32:in `instance_exec'
	 6: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/mongoid-d479161ac28c/lib/mongoid/railtie.rb:58:in `block in <class:Railtie>'
	 5: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/mongoid-d479161ac28c/lib/mongoid.rb:104:in `load!'
	 4: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/mongoid-d479161ac28c/lib/mongoid/config.rb:87:in `load!'
	 3: from /Users/romansuleymanov/.rvm/gems/ruby-2.5.0@Honshu/bundler/gems/mongoid-d479161ac28c/lib/mongoid/config/environment.rb:40:in `load_yaml'
	 2: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/erb.rb:885:in `result'
	 1: from /Users/romansuleymanov/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/erb.rb:885:in `eval'
(erb):164:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the error?
