### ISSUE TITLE
5.2.0.rc1 ActiveRecord polymorphic association regression

### ISSUE THREAD

**Issue by eki** [rails/rails#31876]
### Steps to reproduce

Ignore the (perhaps poor) naming choices for the moment:

```
class Entity < ApplicationRecord
  belongs_to :entity, polymorphic: true
end
```

In Rails 5.2.0.rc1 I receive this error:

```
> rails console
Loading development environment (Rails 5.2.0.rc1)
>> Entity.create(entity: User.last)
  User Load (0.5ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
Traceback (most recent call last):
       16: from activerecord (5.2.0.rc1) lib/active_record/inheritance.rb:66:in `new'
       15: from activerecord (5.2.0.rc1) lib/active_record/core.rb:314:in `initialize'
       14: from activemodel (5.2.0.rc1) lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
       13: from activerecord (5.2.0.rc1) lib/active_record/attribute_assignment.rb:28:in `_assign_attributes'
       12: from activemodel (5.2.0.rc1) lib/active_model/attribute_assignment.rb:41:in `_assign_attributes'
       11: from activemodel (5.2.0.rc1) lib/active_model/attribute_assignment.rb:41:in `each'
       10: from activemodel (5.2.0.rc1) lib/active_model/attribute_assignment.rb:42:in `block in _assign_attributes'
        9: from activemodel (5.2.0.rc1) lib/active_model/attribute_assignment.rb:49:in `_assign_attribute'
        8: from activemodel (5.2.0.rc1) lib/active_model/attribute_assignment.rb:49:in `public_send'
        7: from activerecord (5.2.0.rc1) lib/active_record/associations/builder/association.rb:116:in `entity='
        6: from activerecord (5.2.0.rc1) lib/active_record/associations/singular_association.rb:17:in `writer'
        5: from activerecord (5.2.0.rc1) lib/active_record/associations/belongs_to_association.rb:15:in `replace'
        4: from activerecord (5.2.0.rc1) lib/active_record/associations/association.rb:101:in `set_inverse_instance'
        3: from activerecord (5.2.0.rc1) lib/active_record/associations/belongs_to_association.rb:95:in `invertible_for?'
        2: from activerecord (5.2.0.rc1) lib/active_record/associations/belongs_to_polymorphic_association.rb:24:in `inverse_reflection_for'
        1: from activerecord (5.2.0.rc1) lib/active_record/reflection.rb:528:in `polymorphic_inverse_of'
ActiveRecord::InverseOfAssociationNotFoundError (Could not find the inverse association for entity (nil in User))
```

I do not have an inverse association in `User` (nor do I want one).

Under Rails 5.1.4 this association is working as expected.

If I change the name of the association from `:entity` to anything else (and rename the database columns), the association works correctly again under 5.2.0.rc1.

It seems as if the code looking for an inverse association for the `belongs_to :entity` is finding the `belongs_to` itself and proceeding with the expectation that `User` has an inverse association. 

### System configuration
**Rails version**: 5.2.0.rc1

**Ruby version**: 2.5.0

**Comment by kamipo** [comment]
I tried but couldn't reproduce the issue, can you please try to provide an executable reproduction script by using the information given in [this](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) page?

**Comment by eki** [comment]
@kamipo This should reproduce the issue: https://gist.github.com/eki/5a894cb7f3bcb4fbceaa803b963d9443
