### ISSUE TITLE
Rails 5.2.0.rc1 lib/active_record/coders/yaml_column.rb:24:in `load': undefined method `new' for Representable::JSON:Module (NoMethodError)

### ISSUE THREAD

**Issue by thibaudgg** [rails/rails#31873]
### Steps to reproduce
Upgrading my Rails app from `5.2.0.beta2` to `5.2.0.rc1` and launching the Rails development console with `bin/rails c`.

### Expected behavior
It should work just fine, as it was with the `5.2.0.beta2` version. 😄 

### Actual behavior

```
/Users/Thibaud/.gem/ruby/2.4.3/gems/activerecord-5.2.0.rc1/lib/active_record/coders/yaml_column.rb:24:in `load': undefined method `new' for Representable::JSON:Module (NoMethodError)
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activerecord-5.2.0.rc1/lib/active_record/coders/yaml_column.rb:44:in `check_arity_of_constructor'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activerecord-5.2.0.rc1/lib/active_record/coders/yaml_column.rb:13:in `initialize'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activerecord-5.2.0.rc1/lib/active_record/store.rb:187:in `new'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activerecord-5.2.0.rc1/lib/active_record/store.rb:187:in `initialize'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activerecord-5.2.0.rc1/lib/active_record/store.rb:83:in `new'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activerecord-5.2.0.rc1/lib/active_record/store.rb:83:in `store'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activestorage-5.2.0.rc1/app/models/active_storage/blob.rb:22:in `<class:Blob>'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activestorage-5.2.0.rc1/app/models/active_storage/blob.rb:16:in `<main>'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:63:in `load'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:63:in `load'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:468:in `block in load_file'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:653:in `new_constants_in'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:467:in `load_file'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:365:in `block in require_or_load'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:348:in `require_or_load'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:502:in `load_missing_constant'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:193:in `const_missing'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activestorage-5.2.0.rc1/lib/active_storage/engine.rb:79:in `block (2 levels) in <class:Engine>'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:426:in `instance_exec'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:605:in `catch'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:199:in `block in halting'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:513:in `each'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:513:in `invoke_before'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:131:in `run_callbacks'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/reloader.rb:89:in `prepare!'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/railties-5.2.0.rc1/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/railties-5.2.0.rc1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/railties-5.2.0.rc1/lib/rails/initializable.rb:32:in `run'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/railties-5.2.0.rc1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/Thibaud/.rubies/ruby-2.4.3/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /Users/Thibaud/.rubies/ruby-2.4.3/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/Thibaud/.rubies/ruby-2.4.3/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/Thibaud/.rubies/ruby-2.4.3/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/Thibaud/.rubies/ruby-2.4.3/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /Users/Thibaud/.rubies/ruby-2.4.3/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /Users/Thibaud/.rubies/ruby-2.4.3/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/Thibaud/.rubies/ruby-2.4.3/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /Users/Thibaud/.rubies/ruby-2.4.3/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/railties-5.2.0.rc1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/railties-5.2.0.rc1/lib/rails/application.rb:360:in `initialize!'
	from /Users/Thibaud/Codes/acp-admin/config/environment.rb:5:in `<main>'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:283:in `block in require'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:283:in `require'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/railties-5.2.0.rc1/lib/rails/application.rb:336:in `require_environment!'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/railties-5.2.0.rc1/lib/rails/command/actions.rb:18:in `require_application_and_environment!'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/railties-5.2.0.rc1/lib/rails/commands/console/console_command.rb:95:in `perform'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/railties-5.2.0.rc1/lib/rails/command/base.rb:65:in `perform'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/railties-5.2.0.rc1/lib/rails/command.rb:46:in `invoke'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/railties-5.2.0.rc1/lib/rails/commands.rb:18:in `<main>'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:283:in `block in require'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/Thibaud/.gem/ruby/2.4.3/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:283:in `require'
	from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**: 5.2.0.rc1
**Ruby version**: 2.4.3

**Comment by rafaelfranca** [comment]
Thank you for the report. Fixed in https://github.com/rails/rails/pull/31855 already present in the 5-2-stable branch.

**Comment by thibaudgg** [comment]
Awesome, thanks @rafaelfranca! 💌

**Comment by benbonnet** [comment]
Hi; not a big deal but while searching for this error, landed here
Am getting the very same error while running `5.2.0.beta2` with ruby `2.5.0`, and everywhere, not just in the console

May I ask you how to grab the 5-2-stable version ?
