### ISSUE TITLE
Unable to minitest_bisect to find what causes `PersistenceTest#test_becomes` error

### ISSUE THREAD

**Issue by yahonda** [rails/rails#31893]
To isolate the cause of this error reported at https://travis-ci.org/rails/rails/jobs/337434035
I have executed `minitest_bisect` with seed 3080. Unfortunately, it will not start bisecting.

```ruby
Error:
PersistenceTest#test_becomes:
ActiveModel::MissingAttributeError: can't write unknown attribute `type`
```

### Steps to reproduce

```ruby
$ cd activerecord
$ MTB_VERBOSE=2 bundle exec minitest_bisect --seed 3080 -w -Itest "test/cases/adapter_test.rb" "test/cases/aggregations_test.rb" "test/cases/ar_schema_test.rb" "test/cases/associations/belongs_to_associations_test.rb" "test/cases/associations/bidirectional_destroy_dependencies_test.rb" "test/cases/associations/callbacks_test.rb" "test/cases/associations/cascaded_eager_loading_test.rb" "test/cases/associations/eager_load_includes_full_sti_class_test.rb" "test/cases/associations/eager_load_nested_include_test.rb" "test/cases/associations/eager_singularization_test.rb" "test/cases/associations/eager_test.rb" "test/cases/associations/extension_test.rb" "test/cases/associations/has_and_belongs_to_many_associations_test.rb" "test/cases/associations/has_many_associations_test.rb" "test/cases/associations/has_many_through_associations_test.rb" "test/cases/associations/has_one_associations_test.rb" "test/cases/associations/has_one_through_associations_test.rb" "test/cases/associations/inner_join_association_test.rb" "test/cases/associations/inverse_associations_test.rb" "test/cases/associations/join_model_test.rb" "test/cases/associations/left_outer_join_association_test.rb" "test/cases/associations/nested_through_associations_test.rb" "test/cases/associations/required_test.rb" "test/cases/associations_test.rb" "test/cases/attribute_decorators_test.rb" "test/cases/attribute_methods/read_test.rb" "test/cases/attribute_methods_test.rb" "test/cases/attributes_test.rb" "test/cases/autosave_association_test.rb" "test/cases/base_test.rb" "test/cases/batches_test.rb" "test/cases/binary_test.rb" "test/cases/bind_parameter_test.rb" "test/cases/cache_key_test.rb" "test/cases/calculations_test.rb" "test/cases/callbacks_test.rb" "test/cases/clone_test.rb" "test/cases/coders/json_test.rb" "test/cases/coders/yaml_column_test.rb" "test/cases/collection_cache_key_test.rb" "test/cases/column_alias_test.rb" "test/cases/column_definition_test.rb" "test/cases/comment_test.rb" "test/cases/connection_adapters/adapter_leasing_test.rb" "test/cases/connection_adapters/connection_handler_test.rb" "test/cases/connection_adapters/connection_specification_test.rb" "test/cases/connection_adapters/merge_and_resolve_default_url_config_test.rb" "test/cases/connection_adapters/mysql_type_lookup_test.rb" "test/cases/connection_adapters/schema_cache_test.rb" "test/cases/connection_adapters/type_lookup_test.rb" "test/cases/connection_management_test.rb" "test/cases/connection_pool_test.rb" "test/cases/connection_specification/resolver_test.rb" "test/cases/core_test.rb" "test/cases/counter_cache_test.rb" "test/cases/custom_locking_test.rb" "test/cases/database_statements_test.rb" "test/cases/date_test.rb" "test/cases/date_time_precision_test.rb" "test/cases/date_time_test.rb" "test/cases/defaults_test.rb" "test/cases/dirty_test.rb" "test/cases/disconnected_test.rb" "test/cases/dup_test.rb" "test/cases/enum_test.rb" "test/cases/errors_test.rb" "test/cases/explain_subscriber_test.rb" "test/cases/explain_test.rb" "test/cases/finder_respond_to_test.rb" "test/cases/finder_test.rb" "test/cases/fixture_set/file_test.rb" "test/cases/fixtures_test.rb" "test/cases/forbidden_attributes_protection_test.rb" "test/cases/habtm_destroy_order_test.rb" "test/cases/hot_compatibility_test.rb" "test/cases/i18n_test.rb" "test/cases/inheritance_test.rb" "test/cases/instrumentation_test.rb" "test/cases/integration_test.rb" "test/cases/invalid_connection_test.rb" "test/cases/invertible_migration_test.rb" "test/cases/json_attribute_test.rb" "test/cases/json_serialization_test.rb" "test/cases/locking_test.rb" "test/cases/log_subscriber_test.rb" "test/cases/migration/change_schema_test.rb" "test/cases/migration/change_table_test.rb" "test/cases/migration/column_attributes_test.rb" "test/cases/migration/column_positioning_test.rb" "test/cases/migration/columns_test.rb" "test/cases/migration/command_recorder_test.rb" "test/cases/migration/compatibility_test.rb" "test/cases/migration/create_join_table_test.rb" "test/cases/migration/foreign_key_test.rb" "test/cases/migration/index_test.rb" "test/cases/migration/logger_test.rb" "test/cases/migration/pending_migrations_test.rb" "test/cases/migration/references_foreign_key_test.rb" "test/cases/migration/references_index_test.rb" "test/cases/migration/references_statements_test.rb" "test/cases/migration/rename_table_test.rb" "test/cases/migration_test.rb" "test/cases/migrator_test.rb" "test/cases/mixin_test.rb" "test/cases/modules_test.rb" "test/cases/multiparameter_attributes_test.rb" "test/cases/multiple_db_test.rb" "test/cases/nested_attributes_test.rb" "test/cases/nested_attributes_with_callbacks_test.rb" "test/cases/null_relation_test.rb" "test/cases/numeric_data_test.rb" "test/cases/persistence_test.rb" "test/cases/pooled_connections_test.rb" "test/cases/primary_keys_test.rb" "test/cases/query_cache_test.rb" "test/cases/quoting_test.rb" "test/cases/readonly_test.rb" "test/cases/reaper_test.rb" "test/cases/reflection_test.rb" "test/cases/relation/delegation_test.rb" "test/cases/relation/merging_test.rb" "test/cases/relation/mutation_test.rb" "test/cases/relation/or_test.rb" "test/cases/relation/predicate_builder_test.rb" "test/cases/relation/record_fetch_warning_test.rb" "test/cases/relation/where_chain_test.rb" "test/cases/relation/where_clause_test.rb" "test/cases/relation/where_test.rb" "test/cases/relation_test.rb" "test/cases/relations_test.rb" "test/cases/reload_models_test.rb" "test/cases/reserved_word_test.rb" "test/cases/result_test.rb" "test/cases/sanitize_test.rb" "test/cases/schema_dumper_test.rb" "test/cases/schema_loading_test.rb" "test/cases/scoping/default_scoping_test.rb" "test/cases/scoping/named_scoping_test.rb" "test/cases/scoping/relation_scoping_test.rb" "test/cases/secure_token_test.rb" "test/cases/serialization_test.rb" "test/cases/serialized_attribute_test.rb" "test/cases/statement_cache_test.rb" "test/cases/store_test.rb" "test/cases/suppressor_test.rb" "test/cases/tasks/database_tasks_test.rb" "test/cases/tasks/mysql_rake_test.rb" "test/cases/tasks/postgresql_rake_test.rb" "test/cases/tasks/sqlite_rake_test.rb" "test/cases/test_fixtures_test.rb" "test/cases/time_precision_test.rb" "test/cases/timestamp_test.rb" "test/cases/touch_later_test.rb" "test/cases/transaction_callbacks_test.rb" "test/cases/transaction_isolation_test.rb" "test/cases/transactions_test.rb" "test/cases/type/adapter_specific_registry_test.rb" "test/cases/type/date_time_test.rb" "test/cases/type/integer_test.rb" "test/cases/type/string_test.rb" "test/cases/type/type_map_test.rb" "test/cases/type/unsigned_integer_test.rb" "test/cases/type_test.rb" "test/cases/types_test.rb" "test/cases/unconnected_test.rb" "test/cases/unsafe_raw_sql_test.rb" "test/cases/validations/absence_validation_test.rb" "test/cases/validations/association_validation_test.rb" "test/cases/validations/i18n_generate_message_validation_test.rb" "test/cases/validations/i18n_validation_test.rb" "test/cases/validations/length_validation_test.rb" "test/cases/validations/presence_validation_test.rb" "test/cases/validations/uniqueness_validation_test.rb" "test/cases/validations_test.rb" "test/cases/view_test.rb" "test/cases/yaml_serialization_test.rb" "test/cases/adapters/sqlite3/collation_test.rb" "test/cases/adapters/sqlite3/copy_table_test.rb" "test/cases/adapters/sqlite3/explain_test.rb" "test/cases/adapters/sqlite3/json_test.rb" "test/cases/adapters/sqlite3/quoting_test.rb" "test/cases/adapters/sqlite3/sqlite3_adapter_test.rb" "test/cases/adapters/sqlite3/sqlite3_create_folder_test.rb" "test/cases/adapters/sqlite3/statement_pool_test.rb"
```

### Expected behavior
It should start bisecting each test and would show what causes `ActiveModel::MissingAttributeError`.

### Actual behavior
```ruby
reproducing...Using sqlite3
Run options: --seed 3080 --server 10166

# Running:

Traceback (most recent call last):
	16: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:63:in `block in autorun'
	15: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:136:in `run'
	14: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:159:in `__run'
	13: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:159:in `map'
	12: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:159:in `block in __run'
	11: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:319:in `run'
	10: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:347:in `with_info_handler'
	 9: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:360:in `on_signal'
	 8: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:320:in `block in run'
	 7: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:320:in `each'
	 6: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:321:in `block (2 levels) in run'
	 5: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:334:in `run_one_method'
	 4: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:785:in `record'
	 3: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:785:in `each'
	 2: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.1/lib/minitest.rb:786:in `block in record'
	 1: from /home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-server-1.0.4/lib/minitest/server_plugin.rb:34:in `record'
/home/yahonda/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-server-1.0.4/lib/minitest/server_plugin.rb:34:in `instance_method': undefined method `test_should_automatically_validate_associations_with_:validate_=>_true' for class `Minitest::Result' (NameError)
 in 3.78 sec
Reproduction run passed? Aborting.
Try running with MTB_VERBOSE=2 to verify.
$
```

### System configuration
**Rails version**:master branch with the latest commit f9a8646d8150956524a72af9f85c832bbe84061b

**Ruby version**:ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]

**Comment by y-yagi** [comment]
This is `minitest-server`'s issue.  Latest released `minitest-server` does not support Minitest 5.11. 
It seems already fixed by https://github.com/seattlerb/minitest-server/commit/4c5827fdd2318603c69eca32bba39d91642e7bf8. 
Let's wait for the new version to be released.

**Comment by y-yagi** [comment]
For your information, it is the result of my local bisect.

```
Final reproduction:

Using sqlite3
Run options: --seed 3080 -n "/^(?:SerializedAttributeTest#(?:test_serialized_attributes_from_database_on_subclass)|PersistenceTest#(?:test_becomes))$/"

# Running:

.E

Error:
PersistenceTest#test_becomes:
ActiveModel::MissingAttributeError: can't write unknown attribute `type`
    /home/y-yagi/src/github/y-yagi/rails/activemodel/lib/active_model/attribute.rb:207:in `with_value_from_database'
    /home/y-yagi/src/github/y-yagi/rails/activemodel/lib/active_model/attribute_set.rb:57:in `write_from_user'
    /home/y-yagi/src/github/y-yagi/rails/activerecord/lib/active_record/attribute_methods/write.rb:51:in `_write_attribute'
    /home/y-yagi/src/github/y-yagi/rails/activerecord/lib/active_record/inheritance.rb:249:in `ensure_proper_type'
    /home/y-yagi/src/github/y-yagi/rails/activerecord/lib/active_record/inheritance.rb:238:in `initialize_internals_callback'
    /home/y-yagi/src/github/y-yagi/rails/activerecord/lib/active_record/scoping.rb:43:in `initialize_internals_callback'
    /home/y-yagi/src/github/y-yagi/rails/activerecord/lib/active_record/core.rb:312:in `initialize'
    /home/y-yagi/src/github/y-yagi/rails/activerecord/lib/active_record/persistence.rb:363:in `becomes'
    /home/y-yagi/src/github/y-yagi/rails/activerecord/test/cases/persistence_test.rb:250:in `test_becomes'
```

**Comment by yahonda** [comment]
Thank you for the information. Opened #31905 for the fix I wanted.

**Comment by yahonda** [comment]
@y-yagi Would you do me a favor? I'd like to use the minitest-server including https://github.com/seattlerb/minitest-server/commit/4c5827fdd2318603c69eca32bba39d91642e7bf8 but get `Could not find gem 'minitest-server' in https://github.com/seattlerb/minitest-server.git (at master@4c5827f).` error. Here are changes made and the output

https://gist.github.com/yahonda/e6d1b7294d25889c5e247f681fedba00

Thanks.

**Comment by y-yagi** [comment]
`minitest-server` doesn't provide gemspec. Therefore, can't specify GitHub  branch(If my understanding is correct). 
Therefore, I cloned the code, created a new version, and installed it. 
Another approach is to directly rewrite the installed gem's code directly. Only `lib/minitest/server_plugin.rb` needs to be modified.

**Comment by yahonda** [comment]
Thanks for the useful information. 
I did update `lib/minitest/server_plugin.rb` and now minitest_bisect is running.
