### ISSUE TITLE
change_column_null tries to drop table [ActiveRecord][SQLite][Mac]

### ISSUE THREAD

**Issue by rowend** [rails/rails#31988]
### Description [ActiveRecord][SQLite]

Hi. I try to add a not null constraint to varchar(string in active record) field to table called categories but at some point of code execution I get a *DROP TABLE* error.

### Steps to reproduce

* Create a project: `rails new blog`
* Create a model: `rails g model Category name:string`
* Create another model: `rails g model Entry name:string category:references`
* Do migrate: `rails db:migrate` 
* Add some code to seeds:
```ruby
categories = [
    { id: 1, name: 'Category 1' }
]
Category.create! categories

entries = [
    { id: 1, name: 'Entry 1', category_id: 1 }
]
Entry.create! entries

```
* Do seeds: `rails bd:seed`
* Generate a new empty migration: `rails g migration AddNotNullToCategories`
* Try to use change_column_null with name attribute in categories table:
```ruby
class AddNotNullToCategories < ActiveRecord::Migration[5.1]
  def change
    change_column_null :categories, :name, false
  end
end
```
* Do migrate to get the error: `rails db:migrate` 

### Expected behavior

The not null constraint must be added field name in the table categories.

### Actual behavior

An error for try to delete the categories table:

```
== 20180213223453 AddNotNullToCategories: migrating ===========================
-- change_column_null(:categories, :name, false)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::ConstraintException: FOREIGN KEY constraint failed: DROP TABLE "categories"
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `block in each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:152:in `map'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:152:in `block in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:95:in `prepare'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:251:in `block (2 levels) in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:250:in `block in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:249:in `execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:471:in `drop_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:435:in `move_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:427:in `block in alter_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:426:in `alter_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:370:in `change_column_null'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/Users/rowend/Projects/rails-bug-report/blog/db/migrate/20180213223453_add_not_null_to_categories.rb:3:in `change'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:792:in `exec_migration'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `ddl_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1150:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
ActiveRecord::InvalidForeignKey: SQLite3::ConstraintException: FOREIGN KEY constraint failed: DROP TABLE "categories"
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `block in each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:152:in `map'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:152:in `block in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:95:in `prepare'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:251:in `block (2 levels) in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:250:in `block in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:249:in `execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:471:in `drop_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:435:in `move_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:427:in `block in alter_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:426:in `alter_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:370:in `change_column_null'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/Users/rowend/Projects/rails-bug-report/blog/db/migrate/20180213223453_add_not_null_to_categories.rb:3:in `change'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:792:in `exec_migration'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `ddl_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1150:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
SQLite3::ConstraintException: FOREIGN KEY constraint failed
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `block in each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:152:in `map'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:152:in `block in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:95:in `prepare'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:251:in `block (2 levels) in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:250:in `block in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:249:in `execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:471:in `drop_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:435:in `move_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:427:in `block in alter_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:426:in `alter_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:370:in `change_column_null'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/Users/rowend/Projects/rails-bug-report/blog/db/migrate/20180213223453_add_not_null_to_categories.rb:3:in `change'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:792:in `exec_migration'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `ddl_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1150:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### System configuration
**OS version**: macos High Sierra 10.13.2

**Rails version**: 5.1.4

**Ruby version**: 2.4.1

**Sqlite version**: 3.19.3

Thank you for the support and all the work you do.

**Comment by rafaelfranca** [comment]
This is the expected behavior, when changing a table in sqlite3 we need to copy the content of a table to a temporary table and delete the original. See https://www.sqlite.org/lang_altertable.html.

Although we should disable foreign keys in order to that succeed.

**Comment by Yanchek99** [comment]
This also happens for `remove_column`

**Comment by hkjasf687261gh** [comment]
Also happens on rename_column

**Comment by yahonda** [comment]
Here is a testcase to reproduce it.https://gist.github.com/yahonda/7da44aca60c14625fcdb2a2a3cacd0b1

Also made a commit to fix it https://github.com/yahonda/rails/commit/de96f7efc6b732b2d92ab2b57cfa81568e8e0fb2

I'm looking for which file need update to test this change.

**Comment by Genkilabs** [comment]
Is there a manual workaround for this when doing a rename_column or rollback from add_column that people can use until the fix gets into a release version?

**Comment by dante087** [comment]
For me it worked with this initializer on rails 5.1 https://gist.github.com/dante087/3cfa71452229f8125865a3247fa03d51

**Comment by ultrawebmarketing** [comment]
Is this going to be put into 5.2? Just got bit by this today :( very thankful to @dante087 for his patch.

**Comment by bubba** [comment]
A heads up for anyone who uses this, dropping the table with foreign keys disabled also causes any foreign key linked tables with cascading deletes to cascade!
