### ISSUE TITLE
Freeze when receive multiple requests quickly

### ISSUE THREAD

**Issue by mu29** [rails/rails#32082]
### Steps to reproduce

1. Start rails app (with puma)
2. Make multiple request at same time. More specifically, when my android activity destroys, 3 fragments tries to get same resource from the server.
3. Rails app freezes. `ctrl-c`, `ctrl-d` does not work at all.

```
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.0 (ruby 2.5.0-p0), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop


Started GET "/v4/keywords/current" for 192.168.0.5 at 2018-02-22 20:41:13 +0900
Started GET "/v4/keywords/current" for 192.168.0.5 at 2018-02-22 20:41:13 +0900
Started GET "/v4/keywords/current" for 192.168.0.5 at 2018-02-22 20:41:13 +0900



^C^C^C^C^D


```
### System configuration
**Rails version**: 5.1.4
**Ruby version**: 2.5.0

**Comment by pixeltrix** [comment]
Can you reproduce this with a different version of Ruby?

**Comment by mu29** [comment]
ruby 2.4.1 gives same result:

```
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.0 (ruby 2.4.1-p111), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/v4/literatures/1" for 192.168.0.5 at 2018-02-22 23:36:04 +0900
   (0.3ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
   (1.4ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
Started GET "/v4/keywords/current" for 192.168.0.5 at 2018-02-22 23:36:04 +0900
Started GET "/v4/keywords/current" for 192.168.0.5 at 2018-02-22 23:36:04 +0900
Started GET "/v4/keywords/current" for 192.168.0.5 at 2018-02-22 23:36:04 +0900
Processing by V4::LiteraturesController#show as JSON
  Parameters: {"id"=>"1", "literature"=>{}}




^C^C^C^D


```

**Comment by pixeltrix** [comment]
And what's happening in `V4::LiteraturesController#show` - anything that might cause a deadlock?

If you could use [rbtrace][1] to track down what those three threads are doing then we can see whether there's a Rails bug or it's Puma, Ruby, etc.

[1]: https://github.com/tmm1/rbtrace

**Comment by matthewd** [comment]
You can also try [DebugLocks](http://api.rubyonrails.org/classes/ActionDispatch/DebugLocks.html).

**Comment by rschellhorn** [comment]
I also encountered this issue. There are always some threads stuck at: https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/model_schema.rb#L461

The issue appears when testing with RSpec, using `RSpec.config.use_transactional_fixtures = true` and `Rails.configuration.eager_load = false`. Flipping `eager_load` to true is a workaround.

**Comment by mu29** [comment]
I think `V4::LiteraturesController#show`'s logic is not that heavy, and my first trial does not call this action.

```
  def show
    if @parent
      @preview = true
      @literature = @parent.literature
    else
      @preview = !(free? || purchased?)
    end
  end
```

By the way, after some digging I found an interesting issue.

```
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.0 (ruby 2.5.0-p0), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/v4/keywords/current" for 192.168.0.5 at 2018-02-23 00:06:30 +0900
Started GET "/v4/keywords/current" for 192.168.0.5 at 2018-02-23 00:06:30 +0900
Started GET "/v4/keywords/current" for 192.168.0.5 at 2018-02-23 00:06:30 +0900
   (0.5ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
   (0.7ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
   (0.8ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
   (0.7ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
   (1.4ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
   (1.4ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
/Users/injung/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:457: warning: already initialized constant V4
/Users/injung/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:457: warning: previous definition of V4 was here
/Users/injung/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:457: warning: already initialized constant V4
/Users/injung/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:457: warning: previous definition of V4 was here


LoadError (Unable to autoload constant V4::KeywordsController, expected /Users/injung/Github/ssm-api/app/controllers/v4/keywords_controller.rb to define it):

LoadError (Unable to autoload constant V4::KeywordsController, expected /Users/injung/Github/ssm-api/app/controllers/v4/keywords_controller.rb to define it):
activesupport (5.1.4) lib/active_support/dependencies.rb:511:in `load_missing_constant'
activesupport (5.1.4) lib/active_support/dependencies.rb:202:in `const_missing'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:271:in `const_get'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:271:in `block in constantize'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:267:in `each'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:267:in `inject'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:267:in `constantize'
activesupport (5.1.4) lib/active_support/dependencies.rb:582:in `get'
activesupport (5.1.4) lib/active_support/dependencies.rb:613:in `constantize'
actionpack (5.1.4) lib/action_dispatch/http/request.rb:85:in `controller_class_for'
actionpack (5.1.4) lib/action_dispatch/http/parameters.rb:99:in `binary_params_for?'
actionpack (5.1.4) lib/action_dispatch/http/parameters.rb:90:in `set_binary_encoding'
actionpack (5.1.4) lib/action_dispatch/http/parameters.rb:67:in `path_parameters='
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:48:in `block in serve'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
activerecord (5.1.4) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
railties (5.1.4) lib/rails/engine.rb:522:in `call'
puma (3.11.0) lib/puma/configuration.rb:225:in `call'
puma (3.11.0) lib/puma/server.rb:624:in `handle_request'
puma (3.11.0) lib/puma/server.rb:438:in `process_client'
puma (3.11.0) lib/puma/server.rb:302:in `block in run'
puma (3.11.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

activesupport (5.1.4) lib/active_support/dependencies.rb:511:in `load_missing_constant'
activesupport (5.1.4) lib/active_support/dependencies.rb:202:in `const_missing'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:271:in `const_get'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:271:in `block in constantize'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:267:in `each'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:267:in `inject'
activesupport (5.1.4) lib/active_support/inflector/methods.rb:267:in `constantize'
activesupport (5.1.4) lib/active_support/dependencies.rb:582:in `get'
activesupport (5.1.4) lib/active_support/dependencies.rb:613:in `constantize'
actionpack (5.1.4) lib/action_dispatch/http/request.rb:85:in `controller_class_for'
actionpack (5.1.4) lib/action_dispatch/http/parameters.rb:99:in `binary_params_for?'
actionpack (5.1.4) lib/action_dispatch/http/parameters.rb:90:in `set_binary_encoding'
actionpack (5.1.4) lib/action_dispatch/http/parameters.rb:67:in `path_parameters='
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:48:in `block in serve'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
activerecord (5.1.4) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
railties (5.1.4) lib/rails/engine.rb:522:in `call'
puma (3.11.0) lib/puma/configuration.rb:225:in `call'
puma (3.11.0) lib/puma/server.rb:624:in `handle_request'
puma (3.11.0) lib/puma/server.rb:438:in `process_client'
puma (3.11.0) lib/puma/server.rb:302:in `block in run'
puma (3.11.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Processing by V4::KeywordsController#current as JSON
  Parameters: {"keyword"=>{}}
  User Load (0.6ms)  SELECT  `ssm_user`.* FROM `ssm_user` INNER JOIN ssm_token ON ssm_user.id = ssm_token.user_id WHERE (ssm_token.access_token = '201802010034595a71e223a0dee3.10890975') ORDER BY `ssm_user`.`id` ASC LIMIT 1
  FeaturedKeyword Load (0.2ms)  SELECT  `ssm_featured_keywords`.* FROM `ssm_featured_keywords` WHERE (`ssm_featured_keywords`.`actived_at` < '2018-02-22 08:06:31') ORDER BY `ssm_featured_keywords`.`id` DESC LIMIT 1
  Rendering v4/keywords/current.json.jbuilder
  Keyword Load (0.3ms)  SELECT  `ssm_keyword`.* FROM `ssm_keyword` WHERE `ssm_keyword`.`id` = 1091 LIMIT 1
  Literature Load (0.4ms)  SELECT  `literatures`.* FROM `literatures` INNER JOIN `keywords_literatures` ON `literatures`.`id` = `keywords_literatures`.`literature_id` WHERE `keywords_literatures`.`keyword_id` = 1091 LIMIT 1
   (0.7ms)  SELECT COUNT(*) FROM `pages` INNER JOIN `articles` ON `pages`.`article_id` = `articles`.`id` INNER JOIN `chapters` ON `articles`.`chapter_id` = `chapters`.`id` WHERE `chapters`.`literature_id` = 1
   (0.3ms)  SELECT COUNT(*) FROM `comments` WHERE `comments`.`commentable_id` = 1 AND `comments`.`commentable_type` = 'Literature' AND `comments`.`published` = 1 AND `comments`.`deleted` = 0
  User Load (0.2ms)  SELECT  `ssm_user`.* FROM `ssm_user` WHERE `ssm_user`.`id` = 112047 LIMIT 1
  Rendered v4/users/_user.json.jbuilder (0.3ms)
  Product Load (0.3ms)  SELECT  `products`.* FROM `products` WHERE `products`.`purchasable_id` = 1 AND `products`.`purchasable_type` = 'Literature' LIMIT 1
  Rendered v4/products/_product.json.jbuilder (0.3ms)
  Rendered v4/literatures/_literature.json.jbuilder (41.3ms)
  Rendered v4/keywords/_keyword.json.jbuilder (93.1ms)
  Rendered v4/keywords/current.json.jbuilder (96.5ms)
Completed 200 OK in 151ms (Views: 93.3ms | ActiveRecord: 11.2ms)
```

Again 3 requests, but only one succeeds, and others throw `LoadError` even `V4::KeywordsController` has defined in keywords_controller.rb

```
class V4::KeywordsController < ApplicationController
  def current
    current = FeaturedKeyword.activated_at_column.lt(7.hours.ago)
    @keyword = FeaturedKeyword.where(current).order(id: :desc).first
  end
end
```

..still struggling  with rbtrace, will see DebugLocks too.

**Comment by schugabe** [comment]
I'm currently upgrading a rails 4.2 project to 5.2rc1 and I replaced paperclip with ActiveStorage. After the replacement my rspec tests started to freeze randomly (always after tests that uploaded a file).

With ```eager_load = false``` and ```config.queue_adapter = :test``` the tests started to work again. I'm not sure if this is releated to the freeze issue reported here but it seems similar.

**Comment by mu29** [comment]
Solved by using `eager_load = false`. Thanks all! :)

**Comment by chrise86** [comment]
I'm also getting this issue in development when `config.eager_load = false`. Setting to `true` "fixes", but I don't think should be regarded as the solution. Can anyone shed some light on this? Also getting the undefined contant issues that @mu29 reported.

**Comment by snowhork** [comment]
Setting true, I also fix this issue. But, the other problem often happens...

`ArgumentError (unknown firstpos: NilClass)`

cf.
https://stackoverflow.com/questions/44465118/rails-5-1-unknown-firstpos-nilclass-issue-reloading-application?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by sumeetattree** [comment]
Experiencing the same issue. Rolling back to ruby `2.4.4` fixed it. Could not find anything with `DebugLocks`

**Comment by robmaceachern** [comment]
I'm still seeing this with:
ruby 2.5.3p105 (2018-10-18 revision 65156)
Rails 5.2.1

The `config.eager_load = true` workaround seems to be working for me in development but something is definitely broken when `config.eager_load = false`. I think this should be re-opened.

**Comment by prcongithub** [comment]
I am facing same issue with JRuby 9.2.6.0 and Rails 5.2.2 with Puma 3.11

**Comment by pmk1c** [comment]
This is probably related to: https://github.com/rails/rails/issues/33209
Which has been there for some time.

**Comment by mu29** [comment]
That makes sense. Let's continue discussion in #33209

**Comment by jose-airspace** [comment]
I fixed this by removing `wrap_parameters`
