### ISSUE TITLE
rake aj:integration:delayed_job have been getting `Segmentation fault (core dumped)` with Ruby 2.6

### ISSUE THREAD

**Issue by yahonda** [rails/rails#32339]
rake aj:integration:delayed_job have been getting `Segmentation fault (core dumped)` with Ruby 2.6

* The last successful build https://travis-ci.org/rails/rails/jobs/355590407
* The first failed build due to due to `[BUG] Segmentation fault` with bootsnap` https://travis-ci.org/rails/rails/jobs/355809016 
* The first failed build due to `Segmentation fault (core dumped)
` https://travis-ci.org/rails/rails/jobs/356278285

If I understand correctly, Rails code should not cause segmentation fault then there may be something wrong with other software, but I wanted to report it here first.

### Steps to reproduce

```ruby
$ cd activejob
$ bundle install
$ bundle exec rake test:integration:delayed_job
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ bundle exec rake test:integration:delayed_job
/home/yahonda/.rbenv/versions/2.6.0-dev/bin/ruby -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.6.0-dev/lib/ruby/gems/2.6.0/gems/rake-12.3.0/lib" "/home/yahonda/.rbenv/versions/2.6.0-dev/lib/ruby/gems/2.6.0/gems/rake-12.3.0/lib/rake/rake_test_loader.rb" "test/integration/queuing_test.rb"
Using delayed_job


*** rake aj:integration:delayed_job ***
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:253: [BUG] Segmentation fault at 0x0000556434e12a80
ruby 2.6.0dev (2018-03-24 trunk 62910) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0024 p:0038 s:0130 e:000129 RESCUE /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:253
c:0023 p:0050 s:0126 e:000125 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:245
c:0022 p:0011 s:0120 e:000119 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
Segmentation fault (core dumped)
rake aborted!
Command failed with status (139): [ruby -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.6.0-dev/lib/ruby/gems/2.6.0/gems/rake-12.3.0/lib" "/home/yahonda/.rbenv/versions/2.6.0-dev/lib/ruby/gems/2.6.0/gems/rake-12.3.0/lib/rake/rake_test_loader.rb" "test/integration/queuing_test.rb" ]
/home/yahonda/.rbenv/versions/2.6.0-dev/bin/bundle:23:in `load'
/home/yahonda/.rbenv/versions/2.6.0-dev/bin/bundle:23:in `<main>'
Tasks: TOP => test:integration:delayed_job
(See full trace by running task with --trace)
$
```

### System configuration
**Rails version**:master branch

**Ruby version**:ruby 2.6.0dev (2018-03-24 trunk 62910) [x86_64-linux]

**Comment by yahonda** [comment]
It does not reproduce by skipping bootsnap https://github.com/yahonda/rails/commit/2466ebf3aec46bca4ddfc40061ccdd4bd7ad5982

```ruby
$ ruby -v
ruby 2.6.0dev (2018-03-24 trunk 62910) [x86_64-linux]
$ bundle exec rake test:integration:delayed_job
/home/yahonda/.rbenv/versions/2.6.0-dev/bin/ruby -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.6.0-dev/lib/ruby/gems/2.6.0/gems/rake-12.3.0/lib" "/home/yahonda/.rbenv/versions/2.6.0-dev/lib/ruby/gems/2.6.0/gems/rake-12.3.0/lib/rake/rake_test_loader.rb" "test/integration/queuing_test.rb"
Using delayed_job


*** rake aj:integration:delayed_job ***
== 20180325021135 CreateDelayedJobs: migrating ================================
-- create_table(:delayed_jobs, {:force=>true})
   -> 0.0013s
-- add_index(:delayed_jobs, [:priority, :run_at], {:name=>"delayed_jobs_priority"})
   -> 0.0007s
== 20180325021135 CreateDelayedJobs: migrated (0.0022s) =======================

Run options: --seed 23474

# Running:

.SS.........S

Finished in 24.231953s, 0.5365 runs/s, 0.6603 assertions/s.
13 runs, 16 assertions, 0 failures, 0 errors, 3 skips

You have skipped tests. Run with --verbose for details.
$
```

**Comment by yahonda** [comment]
git bisect for ruby and found r62851 triggers this segmentation fault https://github.com/ruby/ruby/commit/9e26858e8c32e7f4b6ae3bccf9896ea7b61ce335

* r62844

```
$ ruby -v
ruby 2.6.0dev (2018-03-20 trunk 62844) [x86_64-linux]
$ bundle exec rake test:integration:delayed_job
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/bin/ruby -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/rake-12.3.0/lib" "/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/rake-12.3.0/lib/rake/rake_test_loader.rb" "test/integration/queuing_test.rb"
Using delayed_job


*** rake aj:integration:delayed_job ***
== 20180325071440 CreateDelayedJobs: migrating ================================
-- create_table(:delayed_jobs, {:force=>true})
   -> 0.0020s
-- add_index(:delayed_jobs, [:priority, :run_at], {:name=>"delayed_jobs_priority"})
   -> 0.0006s
== 20180325071440 CreateDelayedJobs: migrated (0.0027s) =======================

Run options: --seed 40263

# Running:

...S.....S.S.

Finished in 24.229702s, 0.5365 runs/s, 0.6603 assertions/s.
13 runs, 16 assertions, 0 failures, 0 errors, 3 skips

You have skipped tests. Run with --verbose for details.
$
```

* r62851

```ruby
$ ruby -v
ruby 2.6.0dev (2018-03-20 trunk 62851) [x86_64-linux]
$ bundle exec rake test:integration:delayed_job
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/bin/ruby -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/rake-12.3.0/lib" "/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/rake-12.3.0/lib/rake/rake_test_loader.rb" "test/integration/queuing_test.rb"
Using delayed_job


*** rake aj:integration:delayed_job ***
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/compile_cache/iseq.rb:18: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.6.0dev (2018-03-20 trunk 62851) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0062 p:---- s:0325 e:000324 CFUNC  :load_from_binary
c:0061 p:0014 s:0320 e:000319 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/compile_cache/iseq.rb:18 [FINISH]
c:0060 p:---- s:0314 e:000313 CFUNC  :fetch
c:0059 p:0069 s:0307 e:000306 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/compile_cache/iseq.rb:37 [FINISH]
c:0058 p:---- s:0301 e:000300 CFUNC  :require
c:0057 p:0028 s:0296 e:000295 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/k
c:0056 p:0009 s:0290 e:000289 BLOCK  /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0055 p:0049 s:0287 e:000286 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249
c:0054 p:0011 s:0281 e:000280 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0053 p:0111 s:0275 e:000274 TOP    /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/nodes.rb:25 [FINISH]
c:0052 p:---- s:0272 e:000271 CFUNC  :require
c:0051 p:0028 s:0267 e:000266 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/k
c:0050 p:0009 s:0261 e:000260 BLOCK  /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0049 p:0049 s:0258 e:000257 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249
c:0048 p:0011 s:0252 e:000251 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0047 p:0132 s:0246 e:000245 TOP    /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel.rb:24 [FINISH]
c:0046 p:---- s:0243 e:000242 CFUNC  :require
c:0045 p:0028 s:0238 e:000237 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/k
c:0044 p:0009 s:0232 e:000231 BLOCK  /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0043 p:0049 s:0229 e:000228 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249
c:0042 p:0011 s:0223 e:000222 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0041 p:0027 s:0217 e:000216 TOP    /home/yahonda/git/rails/activerecord/lib/active_record.rb:29 [FINISH]
c:0040 p:---- s:0214 e:000213 CFUNC  :require
c:0039 p:0028 s:0209 e:000208 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/k
c:0038 p:0009 s:0203 e:000202 BLOCK  /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0037 p:0049 s:0200 e:000199 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249
c:0036 p:0011 s:0194 e:000193 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0035 p:0006 s:0188 e:000187 TOP    /home/yahonda/git/rails/activerecord/lib/active_record/railtie.rb:3 [FINISH]
c:0034 p:---- s:0185 e:000184 CFUNC  :require
c:0033 p:0028 s:0180 e:000179 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/k
c:0032 p:0009 s:0174 e:000173 BLOCK  /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0031 p:0049 s:0171 e:000170 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249
c:0030 p:0011 s:0165 e:000164 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0029 p:0007 s:0159 e:000158 BLOCK  /home/yahonda/git/rails/railties/lib/rails/all.rb:17 [FINISH]
c:0028 p:---- s:0155 e:000154 CFUNC  :each
c:0027 p:0031 s:0151 e:000150 TOP    /home/yahonda/git/rails/railties/lib/rails/all.rb:15 [FINISH]
c:0026 p:---- s:0148 e:000147 CFUNC  :require
c:0025 p:0028 s:0143 e:000142 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/k
c:0024 p:0009 s:0137 e:000136 BLOCK  /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0023 p:0049 s:0134 e:000133 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249
c:0022 p:0011 s:0128 e:000127 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0021 p:0013 s:0122 e:000121 TOP    /tmp/d20180325-12571-1omg02r/dummy/config/application.rb:3 [FINISH]
c:0020 p:---- s:0119 e:000118 CFUNC  :require
c:0019 p:0028 s:0114 e:000113 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/k
c:0018 p:0009 s:0108 e:000107 BLOCK  /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0017 p:0049 s:0105 e:000104 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249
c:0016 p:0011 s:0099 e:000098 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0015 p:0037 s:0093 e:000092 METHOD /home/yahonda/git/rails/railties/lib/rails/command/actions.rb:17
c:0014 p:0022 s:0089 e:000088 METHOD /home/yahonda/git/rails/railties/lib/rails/commands/generate/generate_command.rb:21
c:0013 p:0064 s:0083 e:000082 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/command.rb:27
c:0012 p:0047 s:0075 e:000074 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:126
c:0011 p:0259 s:0068 e:000067 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor.rb:387
c:0010 p:0043 s:0055 e:000054 METHOD /home/yahonda/git/rails/railties/lib/rails/command/base.rb:65
c:0009 p:0134 s:0048 e:000047 METHOD /home/yahonda/git/rails/railties/lib/rails/command.rb:46
c:0008 p:0087 s:0037 e:000036 TOP    /home/yahonda/git/rails/railties/lib/rails/commands.rb:18 [FINISH]
c:0007 p:---- s:0032 e:000031 CFUNC  :require
c:0006 p:0028 s:0027 e:000026 METHOD /home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/k
c:0005 p:0009 s:0021 e:000020 BLOCK  /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0004 p:0049 s:0018 e:000017 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249
c:0003 p:0011 s:0012 e:000011 METHOD /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
c:0002 p:0033 s:0006 e:000005 EVAL   bin/rails:4 [FINISH]
c:0001 p:0000 s:0003 E:001480 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
bin/rails:4:in `<main>'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `require'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/git/rails/railties/lib/rails/commands.rb:18:in `<main>'
/home/yahonda/git/rails/railties/lib/rails/command.rb:46:in `invoke'
/home/yahonda/git/rails/railties/lib/rails/command/base.rb:65:in `perform'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/home/yahonda/git/rails/railties/lib/rails/commands/generate/generate_command.rb:21:in `perform'
/home/yahonda/git/rails/railties/lib/rails/command/actions.rb:17:in `require_application_and_environment!'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `require'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/tmp/d20180325-12571-1omg02r/dummy/config/application.rb:3:in `<main>'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `require'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/git/rails/railties/lib/rails/all.rb:15:in `<main>'
/home/yahonda/git/rails/railties/lib/rails/all.rb:15:in `each'
/home/yahonda/git/rails/railties/lib/rails/all.rb:17:in `block in <main>'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `require'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/git/rails/activerecord/lib/active_record/railtie.rb:3:in `<main>'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `require'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/git/rails/activerecord/lib/active_record.rb:29:in `<main>'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `require'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel.rb:24:in `<main>'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `require'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/nodes.rb:25:in `<main>'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `require'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283:in `block in require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/compile_cache/iseq.rb:18:in `storage_to_output'
/home/yahonda/.rbenv/versions/2.6.0-dev_yahonda/lib/ruby/gems/2.6.0/gems/bootsnap-1.1.2/lib/bootsnap/compile_cache/iseq.rb:18:in `load_from_binary'

-- Machine register context ------------------------------------------------
... snip ...
```

**Comment by yahonda** [comment]
I have opened https://github.com/Shopify/bootsnap/issues/148 to bootsnap to get some more information.

**Comment by yahonda** [comment]
Closed since it does not reproduce anymore since https://github.com/Shopify/bootsnap/issues/148 has been addressed by https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/63040/
```
$ ruby -v
ruby 2.6.0dev (2018-04-07 trunk 63108) [x86_64-linux]
```

```ruby
$ bundle exec rake test:integration:delayed_job
/home/yahonda/.rbenv/versions/2.6.0-dev/bin/ruby -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.6.0-dev/lib/ruby/gems/2.6.0/gems/rake-12.3.0/lib" "/home/yahonda/.rbenv/versions/2.6.0-dev/lib/ruby/gems/2.6.0/gems/rake-12.3.0/lib/rake/rake_test_loader.rb" "test/integration/queuing_test.rb"
Using delayed_job


*** rake aj:integration:delayed_job ***
== 20180407002819 CreateDelayedJobs: migrating ================================
-- create_table(:delayed_jobs, {:force=>true})
   -> 0.0023s
-- add_index(:delayed_jobs, [:priority, :run_at], {:name=>"delayed_jobs_priority"})
   -> 0.0005s
== 20180407002819 CreateDelayedJobs: migrated (0.0046s) =======================

Run options: --seed 540

# Running:

S...S..S.....

Finished in 24.307914s, 0.5348 runs/s, 0.6582 assertions/s.
13 runs, 16 assertions, 0 failures, 0 errors, 3 skips

You have skipped tests. Run with --verbose for details.
$
```
