### ISSUE TITLE
IpSpoofAttackError raised when config.action_dispatch.ip_spoofing_check is false

### ISSUE THREAD

**Issue by wjordan** [rails/rails#32379]
### Steps to reproduce

- default Rails app (`rails new`)
- set `config.action_dispatch.ip_spoofing_check = false` in `config/application.rb`
- Run Rails server in development environment (`bin/rails s`)
- send HTTP request with spoofed-ip request headers (`curl`)

Self-contained shell script to reproduce issue:

```
#!/bin/bash
RAILS_PATH=${RAILS_PATH:-/tmp/ip_spoof}
RAILS_VERSION=${RAILS_VERSION:-5.1.6}
RAILS_PORT=${RAILS_PORT:-8001}

rm -rf ${RAILS_PATH}
rails _${RAILS_VERSION}_ new ${RAILS_PATH} -q > /dev/null
pushd ${RAILS_PATH} > /dev/null
sed -i '/Rails::Application/a config.action_dispatch.ip_spoofing_check = false' config/application.rb
cat config/application.rb
bin/rails s -p ${RAILS_PORT} &
sleep 5
curl localhost:${RAILS_PORT} -H "X-Forwarded-For: 1.2.3.4" -H "Client-Ip: 5.6.7.8" -I
kill $!
popd > /dev/null
```

### Actual behavior

Request returns status 500 with an `IpSpoofAttackError`:

```
Started HEAD "/" for 1.2.3.4 at 2018-03-29 16:09:03 -0700

ActionDispatch::RemoteIp::IpSpoofAttackError: IP spoofing attack?! HTTP_CLIENT_IP="5.6.7.8" HTTP_X_FORWARDED_FOR="1.2.3.4"
	from [GEM]/actionpack-5.1.6/lib/action_dispatch/middleware/remote_ip.rb:134:in `calculate_ip'
	from [GEM]/actionpack-5.1.6/lib/action_dispatch/middleware/remote_ip.rb:153:in `to_s'
	from [GEM]/web-console-3.5.1/lib/web_console/request.rb:21:in `strict_remote_ip'
	from [GEM]/web-console-3.5.1/lib/web_console/request.rb:16:in `from_whitelisted_ip?'
	from [GEM]/web-console-3.5.1/lib/web_console/whiny_request.rb:8:in `from_whitelisted_ip?'
	from [GEM]/web-console-3.5.1/lib/web_console/middleware.rb:20:in `block in call'
	from [GEM]/web-console-3.5.1/lib/web_console/middleware.rb:18:in `catch'
	from [GEM]/web-console-3.5.1/lib/web_console/middleware.rb:18:in `call'
	from [GEM]/actionpack-5.1.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
	from [GEM]/railties-5.1.6/lib/rails/rack/logger.rb:36:in `call_app'
	from [GEM]/railties-5.1.6/lib/rails/rack/logger.rb:24:in `block in call'
	from [GEM]/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `block in tagged'
	from [GEM]/activesupport-5.1.6/lib/active_support/tagged_logging.rb:26:in `tagged'
	from [GEM]/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `tagged'
	from [GEM]/railties-5.1.6/lib/rails/rack/logger.rb:24:in `call'
	from [GEM]/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
	from [GEM]/actionpack-5.1.6/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
	from [GEM]/actionpack-5.1.6/lib/action_dispatch/middleware/request_id.rb:25:in `call'
	from [GEM]/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
	from [GEM]/rack-2.0.4/lib/rack/runtime.rb:22:in `call'
	from [GEM]/activesupport-5.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
	from [GEM]/actionpack-5.1.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
	from [GEM]/actionpack-5.1.6/lib/action_dispatch/middleware/static.rb:125:in `call'
	from [GEM]/rack-2.0.4/lib/rack/sendfile.rb:111:in `call'
	from [GEM]/railties-5.1.6/lib/rails/engine.rb:522:in `call'
	from [GEM]/puma-3.11.3/lib/puma/configuration.rb:225:in `call'
	from [GEM]/puma-3.11.3/lib/puma/server.rb:624:in `handle_request'
	from [GEM]/puma-3.11.3/lib/puma/server.rb:438:in `process_client'
	from [GEM]/puma-3.11.3/lib/puma/server.rb:302:in `block in run'
	from [GEM]/puma-3.11.3/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=UTF-8
X-Request-Id: 0cae9791-f3d5-4b36-8f5d-c7aa31cba837
X-Runtime: 0.000737
Content-Length: 1635
```

### Expected behavior

Request should return status 200, with a 'cannot render console' warning. Here is the output using the fix in rails/web-console#254:

```
Started HEAD "/" for 1.2.3.4 at 2018-03-29 17:34:22 -0700
Cannot render console from [Spoofed]! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Rails::WelcomeController#index as */*
  Rendering [GEM]/railties-5.1.6/lib/rails/templates/rails/welcome/index.html.erb
  Rendered [GEM]/railties-5.1.6/lib/rails/templates/rails/welcome/index.html.erb (2.3ms)
Completed 200 OK in 142ms (Views: 8.8ms)


HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
ETag: W/"c9fe6ce271930cf13b51692868f07af9"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 2c81cad6-79c4-4529-89ef-35bc15e01127
X-Runtime: 0.150273
```

### System configuration
**Rails version**:

Latest (5.1.6)

**Ruby version**:

2.5.0

### Other notes

This behavior seems to be caused by `web-console` >= `2.1.3` (rails/web-console@fc321fd8ebc49f4b1f1b0e9201e96a89a276f061), which raises `IpSpoofAttackError` on any requests it processes without regard for the `ip_spoofing_check` setting. `web-console` is included in the default `Gemfile` for Rails since version `4.2`.

**Comment by eileencodes** [comment]
Thanks for the report @wjordan and fixing it in web-console. Closing this issue 😄
