### ISSUE TITLE
How to disable credentials and use secrets in Rails 5.2 RC2

### ISSUE THREAD

**Issue by nleo** [rails/rails#32413]
`application.rb` - `config.require_master_key = false`

```yaml
# secrets.yml

development:
  secret_key_base: 092117...
production:
  secret_key_base: 0921asdf4...
```

`cap production deploy`

```
00:39 deploy:assets:precompile
      01 bundle exec rake assets:precompile
      01 ReactOnRails: Set generated_assets_dir to default: public/webpack/production
      01 rake aborted!
      01 ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:585:in `validate_secret…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:432:in `secret_key_base'
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:176:in `key_generator'
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:205:in `message_verifie…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activestorage-5.2.0.rc2/lib/active_storage/engine.rb:67:in `block (…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/lazy_load_hooks.rb:69:in…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/lazy_load_hooks.rb:62:in…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/lazy_load_hooks.rb:67:in…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/lazy_load_hooks.rb:52:in…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/lazy_load_hooks.rb:51:in…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/lazy_load_hooks.rb:51:in…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application/finisher.rb:75:in `block i…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:32:in `instance_exec'
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:32:in `run'
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:61:in `block in run_i…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:60:in `run_initialize…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:361:in `initialize!'
      01 /home/rails/wallexypro/releases/20180402075603/config/environment.rb:5:in `<main>'
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.r…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:283:in `…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:249:in `…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:283:in `…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:337:in `require_environ…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:520:in `block in run_ta…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 l…
      01 /home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
      01 Tasks: TOP => environment
      01 (See full trace by running task with --trace)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as rails@85.143.172.221: rake exit status: 1
rake stdout: ReactOnRails: Set generated_assets_dir to default: public/webpack/production
rake stderr: rake aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:585:in `validate_secret_key_base'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:432:in `secret_key_base'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:176:in `key_generator'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:205:in `message_verifier'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activestorage-5.2.0.rc2/lib/active_storage/engine.rb:67:in `block (2 levels) in <class:Engine>'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:32:in `instance_exec'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:32:in `run'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:60:in `run_initializers'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:361:in `initialize!'
/home/rails/wallexypro/releases/20180402075603/config/environment.rb:5:in `<main>'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:283:in `block in require'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:283:in `require'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:337:in `require_environment!'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/home/rails/wallexypro/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

**Comment by pixeltrix** [comment]
Looks like the `SECRET_KEY_BASE` environment variable is set to an empty string - perhaps we should add a `presence` check here:

https://github.com/rails/rails/blob/7419a4f911b2f8521db3ecfcd78148cf89ebd221/railties/lib/rails/application.rb#L428-L436

e.g.

``` ruby
ENV["SECRET_KEY_BASE"].presence || credentials.secret_key_base || secrets.secret_key_base 
```

@dhh @kaspth wdyt?

**Comment by prathamesh-sonpatki** [comment]
@pixeltrix  I think the empty string should be caught by https://github.com/rails/rails/blob/master/railties/lib/rails/application.rb#L582

We can add `presence` check though but this issue looks something different.

**Comment by pixeltrix** [comment]
@prathamesh-sonpatki yeah, you're right - didn't read the exception right when I wrote this test:

``` ruby
test "secrets.secret_key_base is used in production when require_master_key is false" do
  switch_env "SECRET_KEY_BASE", "" do
    remove_file "config/master.key"
    add_to_config "config.require_master_key = false"

    app_file "config/secrets.yml", <<-YAML
      production:
        secret_key_base: 3b7cd727ee24e8444053437c36cc66c3
    YAML

    app "production"
    assert_equal "3b7cd727ee24e8444053437c36cc66c3", app.secret_key_base
  end
end
```

Looks like the only way to get to the reported exception is if all values are nil. @nleo can you double check you don't have a typo somewhere? 

That explains why this line is checking `secret_token` and not `secret_key_base` which made me think it was the source of the error.

https://github.com/rails/rails/blob/09b2348f7fc8d4e7191e70e06608c5909067e2aa/railties/lib/rails/application.rb#L584

**Comment by kaspth** [comment]
Let's see if there was a typo in @nlea's app 👍😊

**Comment by nleo** [comment]
Sorry guys, my bad. I forgot to push my changes. Don't use capistrano often.

**Comment by ArtieReus** [comment]
Where is this fix released? I tried rails 5.2.3 and I'm still seeing this issue...

**Comment by StephenEsser** [comment]
( Cross posting from #32947 )

Has there been any decisions made for this issue? We're running into this issue while upgrading to Rails 5.2 on our CI builds. Without the secret key base builds cannot pass. We're cautious about adding a junk key into the CI stage when it's otherwise unnecessary. 

Running the following command will fail ( locally and on CI ) unless we provide a SECRET_KEY_BASE:

```
RAILS_ENV=production bundle exec rake assets:precompile
```

The error message

```
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
```

cc: @prathamesh-sonpatki @pixeltrix

**Comment by krtschmr** [comment]
this is still broken

**Comment by tcd** [comment]
+1

**Comment by carlosarias1992** [comment]
+1

**Comment by bsodmike** [comment]
+1 we've just run into this issue as well.

**Comment by jschroe212** [comment]
I ran into this same stack trace on a 5.1.7 to 5.2.2.4 upgrade while using Capistrano. If you're using Capistrano and setting the SECRET_KEY_BASE variable in a shell startup file, be aware of the following. https://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/#which_startup_files_loaded

In my case, the SECRET_KEY_BASE environment variable was not being set because the shell startup file was not loaded in the Capistrano ssh connection. The ActiveStorage addition in rails5.2 adds a code path to validate_secret_key_base that wasn't there in previous versions of Rails, so it never surfaced that ENV["SECRET_KEY_BASE"] was blank in Capistrano's ssh connections. The application server was running in an environment that had SECRET_KEY_BASE properly set. 

Our quick and dirty solution was to turn off ActiveStorage because we don't plan on migrating to it.  That said, I think migrating secrets.yml to encrypted credentials is the best solution for most cases, but if you wanna defer that, this worked.

**Comment by sobolevtimur** [comment]
It is bugged for Rails 6.0.3 as well. 
Adding lines specifed below won't resolve the isssue: 
```
config.require_master_key = false
config.read_encrypted_secrets = false
```
