### ISSUE TITLE
Casting in MySQL is different than in Postgres

### ISSUE THREAD

**Issue by jules2689** [rails/rails#32624]
### Steps to reproduce

[This commit](https://github.com/rails/rails/commit/68fe6b08ee72cc47263e0d2c9ff07f75c4b42761) was intended to fix an issue with casting.

However, it seems that, with MySQL this issue continues to occur. In the octobox app, I get

```
NotificationsControllerTest#test_archives_respects_current_filters:
ActiveRecord::StatementInvalid: Mysql2::Error: Truncated incorrect DOUBLE value: 'true': UPDATE `notifications` SET `notifications`.`archived` = TRUE WHERE `notifications`.`user_id` = 7 AND `notifications`.`archived` = FALSE AND `notifications`.`unread` = 'true'
    app/controllers/notifications_controller.rb:135:in `archive_selected'
    test/controllers/notifications_controller_test.rb:198:in `block in <class:NotificationsControllerTest>'
```

[This repo](https://github.com/jules2689/rails-issue) helps illustrate the issue in the tests.

### Expected behavior

When I use `scope.send(:unread, 'true')`. I'd expect the `'true'` to be cast to a boolean.

### Actual behavior

When I use `scope.send(:unread, 'true')`. `'true'` is not cast and ActiveRecord throws a `ActiveRecord::StatementInvalid` 

### System configuration
**Rails version**: `5.2.0`
**Ruby version**: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`

**Comment by jules2689** [comment]
cc @sgrif

**Comment by sgrif** [comment]
If you could put this in a repro script using [our standard bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) instead of a full app that'd be helpful.

**Comment by jules2689** [comment]
ugh. I was looking for that template @sgrif

**Comment by jules2689** [comment]
@sgrif https://github.com/jules2689/rails-issue has 3 different files now, one for mysql, one for postgres, and one for sqlite - all showing different responses

**Comment by sgrif** [comment]
Confirmed the issue on both master and 4.2
