### ISSUE TITLE
Obsoleted method `halt_callback_chains_on_return_false` still called in Rails 5.2

### ISSUE THREAD

**Issue by emirkin** [rails/rails#32653]
According to https://github.com/rails/rails/commit/19fbbebb1665e482d76cae30166b46e74ceafe29, this method should no longer be called. But it is.

```
undefined method `halt_callback_chains_on_return_false=' for ActiveSupport:Module (NoMethodError)
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/engine.rb:657:in `block in load_config_initializer'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/engine.rb:656:in `load_config_initializer'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/engine.rb:613:in `each'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/engine.rb:613:in `block in <class:Engine>'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `each'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/zheka/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/zheka/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
```

**Comment by rafaelfranca** [comment]
There is no call for this method inside Rails. Make sure your application is not calling it.

**Comment by emirkin** [comment]
@al2o3cr My application was a Rails 5.1. I merely updated it to 5.2.

@rafaelfranca The line `Rails.application.initialize!` in `environment.rb` ultimately results in this stacktrace. So, this is not really my app.

**Comment by al2o3cr** [comment]
@emirkin Rails 5.1 generated a file in your application at `config/initializers/new_framework_defaults.rb` which contains this code. You'll need to delete the offending line.

**Comment by rafaelfranca** [comment]
I think `grep "halt_callback_chains_on_return_false" config/**/*.rb` will show you that your application is calling it.

**Comment by vizcay** [comment]
IMHO this should be documented in the upgrade guides.. after all that code was generated by a previous rails application generator, not ourselves.

**Comment by el-rotny** [comment]
I think a better "closing of the loop" here to be to simply recommend the rails upgrade task to parse this file and recommend changes same way other files from upstream are met. Seems like if they are going to be versions like `_5_2` the previous version could be diff'd to show changes. At least, moving forward as we get to 5_3. Sometimes these things are going to be missed on guides, but this can be a more accurate programatic upgrade to the process.

**Comment by Dhrumilp17** [comment]
Thank for the suggestion, deleting the call does solves the problem
