### ISSUE TITLE
Apply `CustomCops/RefuteNot` and `CustomCops/AssertNot` for Arel test cases or not

### ISSUE THREAD

**Issue by yahonda** [rails/rails#32720]
Now Arel is part of Rails since #32097. RuboCop reports offenses `CustomCops/RefuteNot` and `CustomCops/AssertNot` offenses for newly added test files. Auto correcting these files causes test failures. I do not know how to address them then just let me open an issue.

### Steps to reproduce

```ruby
$ cd activerecord
$ bundle exec rubocop -a
$ bundle exec rake test_sqlite3
```

### Expected behavior
It should pass.

### Actual behavior

It reports these `NoMethodError`
```
NoMethodError: undefined method `assert_not_same'
NoMethodError: undefined method `assert_not'
NoMethodError: undefined method `assert_not_equal'
NoMethodError: undefined method `assert_not_same'
NoMethodError: undefined method `assert_no_match'
```

* Execute RuboCop with auto-correct option

```ruby
$ bundle exec rubocop -v
0.54.0
$ bundle exec rubocop -a
... snip ...
activerecord/test/cases/arel/select_manager_test.rb:1147:9: C: CustomCops/RefuteNot: Prefer assert_no_match over refute_match
        refute_match("LIMIT", manager.to_sql)
        ^^^^^^^^^^^^
activerecord/test/cases/arel/nodes/binary_test.rb:15:11: C: CustomCops/RefuteNot: Prefer assert_not_equal over refute_equal
          refute_equal eq.hash, eq3.hash
          ^^^^^^^^^^^^
activerecord/test/cases/arel/nodes/binary_test.rb:22:11: C: CustomCops/RefuteNot: Prefer assert_not_equal over refute_equal
          refute_equal eq.hash, neq.hash
          ^^^^^^^^^^^^
activerecord/test/cases/arel/nodes/case_test.rb:34:11: C: CustomCops/RefuteNot: Prefer assert_not_same over refute_same
          refute_same  dolly.case, node.case
          ^^^^^^^^^^^
activerecord/test/cases/arel/nodes/case_test.rb:37:11: C: CustomCops/RefuteNot: Prefer assert_not_same over refute_same
          refute_same  dolly.conditions, node.conditions
          ^^^^^^^^^^^
activerecord/test/cases/arel/nodes/case_test.rb:40:11: C: CustomCops/RefuteNot: Prefer assert_not_same over refute_same
          refute_same  dolly.default, node.default
          ^^^^^^^^^^^
activerecord/test/cases/arel/nodes/ascending_test.rb:32:9: C: CustomCops/AssertNot: Prefer assert_not over assert !
        assert !ascending.descending?
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
activerecord/test/cases/arel/nodes/descending_test.rb:27:9: C: CustomCops/AssertNot: Prefer assert_not over assert !
        assert !descending.ascending?
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
activerecord/test/cases/arel/nodes/select_core_test.rb:20:9: C: CustomCops/RefuteNot: Prefer assert_not_same over refute_same
        refute_same core.froms, dolly.froms
        ^^^^^^^^^^^
activerecord/test/cases/arel/nodes/select_core_test.rb:21:9: C: CustomCops/RefuteNot: Prefer assert_not_same over refute_same
        refute_same core.projections, dolly.projections
        ^^^^^^^^^^^
activerecord/test/cases/arel/nodes/select_core_test.rb:22:9: C: CustomCops/RefuteNot: Prefer assert_not_same over refute_same
        refute_same core.wheres, dolly.wheres
        ^^^^^^^^^^^
activerecord/test/cases/arel/attributes/attribute_test.rb:981:11: C: CustomCops/RefuteNot: Prefer assert_not over refute
          refute table.able_to_type_cast?
          ^^^^^^
```

* Execute ActiveRecord unit test using sqlite3 adapter

```ruby
$ bundle exec rake test_sqlite3
... snip ...
Using sqlite3
Run options: --seed 52604

... snip ...

Error:
Arel::Nodes::TestSelectCore#test_clone:
NoMethodError: undefined method `assert_not_same' for #<Arel::Nodes::TestSelectCore:0x00005633118927c8>
Did you mean?  assert_same
    /home/yahonda/git/rails/activerecord/test/cases/arel/nodes/select_core_test.rb:20:in `test_clone'

bin/rails test home/yahonda/git/rails/activerecord/test/cases/arel/nodes/select_core_test.rb:8

... snip ...

Error:
Arel::Nodes::TestAscending#test_descending?:
NoMethodError: undefined method `assert_not' for #<Arel::Nodes::TestAscending:0x0000563311cff4f0>
Did you mean?  assert_nil
               assert_mock
    /home/yahonda/git/rails/activerecord/test/cases/arel/nodes/ascending_test.rb:32:in `test_descending?'

bin/rails test home/yahonda/git/rails/activerecord/test/cases/arel/nodes/ascending_test.rb:30

... snip ...

Error:
Binary::#hash#test_0002_generates a hash specific to its class:
NoMethodError: undefined method `assert_not_equal' for #<#<Class:0x000056330df539f8>:0x0000563311917d60>
Did you mean?  assert_equal
    /home/yahonda/git/rails/activerecord/test/cases/arel/nodes/binary_test.rb:22:in `block (3 levels) in <module:Nodes>'

bin/rails test home/yahonda/git/rails/activerecord/test/cases/arel/nodes/binary_test.rb:18

E

Error:
Binary::#hash#test_0001_generates a hash based on its value:
NoMethodError: undefined method `assert_not_equal' for #<#<Class:0x000056330df539f8>:0x00005633118ff918>
Did you mean?  assert_equal
    /home/yahonda/git/rails/activerecord/test/cases/arel/nodes/binary_test.rb:15:in `block (3 levels) in <module:Nodes>'

bin/rails test home/yahonda/git/rails/activerecord/test/cases/arel/nodes/binary_test.rb:9

... snip ...

Error:
type casting#test_0001_does not type cast by default:
NoMethodError: undefined method `assert_not' for #<#<Class:0x000056330d6f7980>:0x0000563316d14080>
Did you mean?  assert_nil
               assert_mock
    /home/yahonda/git/rails/activerecord/test/cases/arel/attributes/attribute_test.rb:981:in `block (2 levels) in <class:AttributeTest>'

bin/rails test home/yahonda/git/rails/activerecord/test/cases/arel/attributes/attribute_test.rb:977

... snip ...

Error:
Case::#clone#test_0001_clones case, conditions and default:
NoMethodError: undefined method `assert_not_same' for #<#<Class:0x000056330df9b140>:0x000056330fe60940>
Did you mean?  assert_same
    /home/yahonda/git/rails/activerecord/test/cases/arel/nodes/case_test.rb:34:in `block (3 levels) in <module:Nodes>'

bin/rails test home/yahonda/git/rails/activerecord/test/cases/arel/nodes/case_test.rb:23

..E

Error:
take#test_0003_removes LIMIT when nil is passed:
NoMethodError: undefined method `assert_no_match' for #<#<Class:0x000056330dec6bc0>:0x000056330fd9f8a8>
Did you mean?  assert_match
    /home/yahonda/git/rails/activerecord/test/cases/arel/select_manager_test.rb:1147:in `block (2 levels) in <class:SelectManagerTest>'

bin/rails test home/yahonda/git/rails/activerecord/test/cases/arel/select_manager_test.rb:1141

... snip ...

Error:
Arel::Nodes::TestDescending#test_ascending?:
NoMethodError: undefined method `assert_not' for #<Arel::Nodes::TestDescending:0x000056330d1b2240>
Did you mean?  assert_nil
               assert_mock
    /home/yahonda/git/rails/activerecord/test/cases/arel/nodes/descending_test.rb:27:in `test_ascending?'

bin/rails test home/yahonda/git/rails/activerecord/test/cases/arel/nodes/descending_test.rb:25

... snip ...
Finished in 74.877282s, 79.9575 runs/s, 211.8400 assertions/s.
5987 runs, 15862 assertions, 0 failures, 8 errors, 8 skips
```

### System configuration
**Rails version**:master branch

**Ruby version**:ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

**Comment by yahonda** [comment]
I'd like to get some feedback from @koic and @composerinteralia

**Comment by yahonda** [comment]
https://github.com/yahonda/rails/commit/63cc2e900e6fbaedcc3ab68b1afbecf61475083e is the commit for this issue.

**Comment by y-yagi** [comment]
Arel uses Minitest directly for testing. `assert_not_xx` is an assertion method that Rails has defined independently, so it is an error because it is not defined in Minitest.
What happens when you include `ActiveSupport::Testing::Assertions` with `Arel::Test`?

**Comment by yahonda** [comment]
Thanks for the advice. I have changed as suggested first then 3 errors have been addressed. 5 remains. `test/cases/arel/nodes/binary_test.rb` causes 2 errors and other test files cause 1 error per file.

Since these file namespaces are not straightforward (for me).

* `Arel::Nodes`

```ruby
$ bundle exec ruby -Itest test/cases/arel/nodes/binary_test.rb
$ bundle exec ruby -Itest test/cases/arel/nodes/case_test.rb
```

* `Arel::Nodes::TestSelectCore < Arel::Test`
```ruby
$ bundle exec ruby -Itest test/cases/arel/nodes/select_core_test.rb
```

* `Arel::SelectManagerTest < Arel::Spec`
```ruby
$ bundle exec ruby -Itest test/cases/arel/select_manager_test.rb
```

**Comment by composerinteralia** [comment]
Yeah, that seems right. Since arel is part of rails now it would be great it if could follow similar testing patterns. That would mean inheriting from `ActiveSupport::TestCase` instead of `Minitest::Test` directly.

The only thing I am not sure how to deal with is that arel uses spec-style, inheriting from `Minitest::Spec` (https://github.com/rails/rails/blob/master/activerecord/test/cases/arel/helper.rb#L34). We don't do that anywhere else as far as I can tell.

Another option would be to mess around with the patterns in the `.rubocop.yml` to ignore these RuboCop violations, but that seems worse. These customs cops were recently merged into RuboCop, so they probably aren't going anywhere. It is better if we can fix them now.

I will have some time later today if you want help with this.

**Comment by yahonda** [comment]
I'm inclined to change Arel test cases to inherit from `ActiveSupport::TestCase`. and yes. some Arel test case use `Minitest::Spec`.

Let me have some more time to tackle this. Daniel,  If I need your help I'll ping you.

**Comment by yahonda** [comment]
`take#test_0003_removes LIMIT when nil is passed:` error has been addressed.

**Comment by yahonda** [comment]
Now all tests are green now. I've got to know what is needed. Will investigate more.

**Comment by yahonda** [comment]
Here are commits made. https://github.com/yahonda/rails/compare/c81a7fcf76663e6d189792d6eed57b1162199635...apply_cops_for_arel

**Comment by yahonda** [comment]
Opened #32771 to address these offenses.
