### ISSUE TITLE
[ActiveRecord] Migration 5.2 cause db tables recored is deleted.

### ISSUE THREAD

**Issue by zw963** [rails/rails#32812]
### Steps to reproduce

A have a old project, which use sequel, it worked, so, in my develop online database, 
exists a table, named: 'schema_info', have a version column, value is `73`, that means, 
the last we runed migrate is  `0073_change_metadata_type_to_string_for_feeds.rb`.

I create a new project, which run migrate use ActiveRecord 5.2, so i dump the database
into one file, named: `db/migrate/20180504062319_add_tables.rb`, in the files, have so
many create_table methods

```rb
class AddTables < ActiveRecord::Migration[5.2]
  def change
    create_table "activities", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin", force: :cascade do |t|
      t.string "title", default: "", null: false
      t.text "content", limit: 16777215, null: false, comment: "动态内容"
      t.bigint "creator_id", default: 0, null: false
      t.datetime "happened_at", default: -> { "CURRENT_TIMESTAMP" }, null: false, comment: "动态用户填入的记录时间"
      t.datetime "created_at", default: -> { "CURRENT_TIMESTAMP" }, null: false
      t.datetime "updated_at", default: -> { "CURRENT_TIMESTAMP" }, null: false
      t.bigint "subject_id", default: 0, null: false
      t.bigint "clazz_id", default: 0, null: false
      t.bigint "kindergarten_id", default: 0, null: false
      t.bigint "feed_id", default: 0, null: false
      t.bigint "grade_id", default: 0, null: false
      t.index ["clazz_id"], name: "activities_clazz_id_index"
      t.index ["creator_id"], name: "activities_creator_id_index"
      t.index ["feed_id"], name: "activities_feed_id_index"
      t.index ["grade_id"], name: "activities_grade_id_index"
      t.index ["kindergarten_id"], name: "activities_kindergarten_id_index"
      t.index ["subject_id"], name: "activities_subject_id_index"
    end

     ......

    create_table "audios", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|

      ......
      ......
end

### Expected behavior

throw some exception,  told me those tables is exist.

### Actual behavior
It seem like drop my db before run this migration.
### System configuration
**Rails version**:
Rails 5.2.0

**Ruby version**:
Ruby 2.5.1

**Comment by zw963** [comment]
Before run migrate,  i dump the old project tables schema with `rake db:schema:dump`, so, i got a schema file in `db/schema.rb`,

```rb
ActiveRecord::Schema.define(version: 0) do
   # ......
end
```

**Comment by zw963** [comment]
I think following two case is dangerous ....

1.  schema_migrations table is not exist
2. schema_migrations table exist, but empty.

above case, will clean all exists table data.

**Comment by y-yagi** [comment]
While creating the table first, I drop`schema_migrations` and execute `db:migrate`, but table exists error occurred as expected.

Can you create a reproduce application?

**Comment by matthewd** [comment]
`force: :cascade` instructs `create_table` to drop (cascade) anything that's currently in the way. It's a dangerous option for a migration, but it's the intended behaviour for schema load.

**Comment by zw963** [comment]
@matthewd, hi, thanks you very much.

`cascade` is caused all table is dropped,  this options is come from `rake db:schema:dump`,
which create by sequel migration.

**Comment by zw963** [comment]
It work as expect now (raise exception)

```sh
== 20180504062319 AddTables: migrating ========================================
-- create_table("activities", {:options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin"})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Index name 'activities_clazz_id_index' on table 'activities' already exists
/home/zw963/.rvm/gems/ruby-2.5.1@kid17-migrate/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:1169:in `add_index_options'
/home/zw963/.rvm/gems/ruby-2.5.1@kid17-migrate/gems/activerecord-5.2.0/lib/active_record/connection_adapters/mysql/schema_creation.rb:67:in `index_in_create'
/home/zw963/.rvm/gems/ruby-2.5.1@kid17-migrate/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:51:in `block in visit_TableDefinition'
/home/zw963/.rvm/gems/ruby-2.5.1@kid17-migrate/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:51:in `map'
/home/zw963/.rvm/gems/ruby-2.5.1@kid17-migrate/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:51:in `visit_TableDefinition'
/home/zw963/.rvm/gems/ruby-2.5.1@kid17-migrate/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:16:in `accept'
/home/zw963/.rvm/gems/ruby-2.5.1@kid17-migrate/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:311:in `create_table'
/home/zw963/.rvm/gems/ruby-2.5.1@kid17-migrate/gems/activerecord-5.2.0/lib/active_record/migration.rb:871:in `block in method_missing'
/home/zw963/.rvm/gems/ruby-2.5.1@kid17-migrate/gems/activerecord-5.2.0/lib/active_record/migration.rb:840:in `block in say_with_time'
/home/zw963/.rvm/gems/ruby-2.5.1@kid17-migrate/gems/activerecord-5.2.0/lib/active_record/migration.rb:840:in `say_with_time'
/home/zw963/.rvm/gems/ruby-2.5.1@kid17-migrate/gems/activerecord-5.2.0/lib/active_record/migration.rb:860:in `method_missing'
```

**Comment by zw963** [comment]
matthewd, i test in my local test database, when i drop my db, and rerun `Non cascade` version migration, but, generate schema.rb, with `cascade ` exist again ....

so, `schema.rb` is not suitable for as a new very first migration file ?
