### ISSUE TITLE
Undefined method `arity' for :debug:Symbol

### ISSUE THREAD

**Issue by alienxp03** [rails/rails#32928]
### Steps to reproduce

Upgrading to Rails 5.2.0 from 5.1.6 and launch the Rails console or server using `rails s` and `rails c`

### Expected behavior
- `rails s` should start the rails server
- `rails c` should start the rails console

### Actual behavior
- Both command fails to start the server and console
- Running `rspec` however doesn't produce any error and all tests passed

```ruby
=> Booting Puma
=> Rails 5.2.0 application starting in development
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
  62: from bin/rails:3:in `<main>'
  61: from bin/rails:3:in `load'
  60: from /Users/john/Workspace/Projects/project-web/bin/spring:15:in `<top (required)>'
  59: from /Users/john/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
  58: from /Users/john/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
  57: from /Users/john/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
  56: from /Users/john/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
  55: from /Users/john/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
  54: from /Users/john/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
  53: from /Users/john/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
  52: from /Users/john/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
  51: from /Users/john/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
  50: from /Users/john/Workspace/Projects/project-web/bin/rails:9:in `<top (required)>'
  49: from /Users/john/Workspace/Projects/project-web/bin/rails:9:in `require'
  48: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
  47: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
  46: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
  45: from /Users/john/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  44: from /Users/john/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  43: from /Users/john/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  42: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `perform'
  41: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `tap'
  40: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:147:in `block in perform'
  39: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:51:in `start'
  38: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
  37: from /Users/john/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
  36: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:27:in `app'
  35: from /Users/john/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
  34: from /Users/john/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
  33: from /Users/john/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
  32: from /Users/john/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
  31: from /Users/john/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
  30: from config.ru:in `<main>'
  29: from config.ru:in `new'
  28: from /Users/john/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
  27: from /Users/john/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
  26: from config.ru:3:in `block in <main>'
  25: from /Users/john/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
  24: from /Users/john/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
  23: from /Users/john/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
  22: from /Users/john/.rvm/gems/ruby-2.5.0/gems/skylight-core-2.0.1/lib/skylight/core/probes.rb:119:in `require'
  21: from /Users/john/.rvm/gems/ruby-2.5.0/gems/skylight-core-2.0.1/lib/skylight/core/probes.rb:119:in `require'
  20: from /Users/john/Workspace/Projects/project-web/config/environment.rb:5:in `<top (required)>'
  19: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
  18: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
  17: from /Users/john/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  16: from /Users/john/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  15: from /Users/john/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  14: from /Users/john/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
  13: from /Users/john/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
  12: from /Users/john/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  11: from /Users/john/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  10: from /Users/john/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
   9: from /Users/john/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
   8: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
   7: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
   6: from /Users/john/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
   5: from /Users/john/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/railtie.rb:29:in `block in <class:Railtie>'
   4: from /Users/john/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/deprecation/instance_delegator.rb:22:in `behavior='
   3: from /Users/john/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/deprecation/behaviors.rb:92:in `behavior='
   2: from /Users/john/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/deprecation/behaviors.rb:92:in `map'
   1: from /Users/john/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/deprecation/behaviors.rb:92:in `block in behavior='
/Users/john/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/deprecation/behaviors.rb:97:in `arity_coerce': undefined method `arity' for :debug:Symbol (NoMethodError)
```

### System configuration
**Rails version**:
Rails 5.2.0

**Ruby version**:
Ruby 2.5.0

**Comment by rafaelfranca** [comment]
`:debug` is not a valid deprecation behavior. We can improve the exception, but you code is incorrect and I'm not sure how that was working in previous version of rails since it should be failing any time a deprecation is raised.

**Comment by alienxp03** [comment]
Thanks @rafaelfranca! Found and fixed the issue. 

In `config/environments/development.rb`, there's a config `config.active_support.deprecation = :debug`. Removing this line seems to fix the issue. I have a few questions if that's ok

1. What would be the replacement for the code above?
2. Improving the exception message will help me a lot in terms of figuring what went wrong

Thanks again!

**Comment by rafaelfranca** [comment]
The valid values are here http://api.rubyonrails.org/classes/ActiveSupport/Deprecation/Behavior.html#method-i-behavior-3D.
