### ISSUE TITLE
Execution of `actioncable/test/connection/stream_test.rb` raises the error in a thread.

### ISSUE THREAD

**Issue by bogdanvlviv** [rails/rails#32941]
```
rails/actioncable$ bin/test test/connection/stream_test.rb
Run options: --seed 42169

# Running:

#<Thread:0x000055d2620e44c8@/work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:75 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        6: from /work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:75:in `block (2 levels) in spawn'
        5: from /work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:86:in `run'
        4: from /work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:86:in `loop'
        3: from /work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:93:in `block in run'
        2: from /work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:31:in `block in attach'
        1: from /work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:31:in `register'
/work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:31:in `initialize': no implicit conversion of StringIO into IO (TypeError)
..#<Thread:0x000055d262103418@/work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:75 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        6: from /work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:75:in `block (2 levels) in spawn'
        5: from /work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:86:in `run'
        4: from /work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:86:in `loop'
        3: from /work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:93:in `block in run'
        2: from /work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:31:in `block in attach'
        1: from /work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:31:in `register'
/work/rails/actioncable/lib/action_cable/connection/stream_event_loop.rb:31:in `initialize': no implicit conversion of StringIO into IO (TypeError)


Finished in 0.285432s, 7.0069 runs/s, 28.0277 assertions/s.
2 runs, 8 assertions, 0 failures, 0 errors, 0 skips
```
TravisCI log: https://travis-ci.org/rails/rails/jobs/381217903#L2695-L2710

Not sure that setting `Thread.report_on_exception` to `false` for these tests is propper fix of this.

**Comment by utilum** [comment]
It's another stricter 2.6 thing. Can we _explicitly_ convert `StringIO` to `IO` ?

**Comment by bogdanvlviv** [comment]
After using `IO` explicitly the test fails.
I've also tried to execute this test with https://github.com/rails/rails/blob/master/actioncable/test/connection/client_socket_test.rb#L74-L80
but got the same failure.
```
Failure:
ActionCable::Connection::StreamTest#test_closes_socket_on_Errno::ECONNRESET [/work/rails/actioncable/test/connection/stream_test.rb:49]:
Expected client_gone to be called 1 times, but was called 0 times.
Expected: 1
  Actual: 0
```

**Comment by bogdanvlviv** [comment]
@rails-bot It is reproducible on the `master` branch https://travis-ci.org/rails/rails/jobs/421594476#L2688-L2704
