### ISSUE TITLE
server is not runing

### ISSUE THREAD

**Issue by mhadiahmed** [rails/rails#32949]
**this is the error** 
```
   Exiting
/var/lib/gems/2.3.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/session/abstract_store.rb:78:in `<module:Session>': uninitialized constant Rack::Session::Abstract::Persisted (NameError)
    from /var/lib/gems/2.3.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/session/abstract_store.rb:8:in `<module:ActionDispatch>'
    from /var/lib/gems/2.3.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/session/abstract_store.rb:7:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/session/cookie_store.rb:2:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/application/configuration.rb:180:in `const_get'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/application/configuration.rb:180:in `session_store'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/application/default_middleware_stack.rb:56:in `block in build_stack'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/application/default_middleware_stack.rb:13:in `tap'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/application/default_middleware_stack.rb:13:in `build_stack'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/application.rb:501:in `default_middleware_stack'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/engine.rb:506:in `block in app'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/engine.rb:504:in `synchronize'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/engine.rb:504:in `app'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/application/finisher.rb:45:in `block in <module:Finisher>'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `instance_exec'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `run'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/initializable.rb:59:in `block in run_initializers'
    from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
    from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
    from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
    from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
    from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
    from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
    from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
    from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/initializable.rb:58:in `run_initializers'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/application.rb:353:in `initialize!'
    from /home/mhadi/Dev/ruby_on_rails/weblog/config/environment.rb:5:in `<top (required)>'
    from config.ru:3:in `require_relative'
    from config.ru:3:in `block in <main>'
    from /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `instance_eval'
    from /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `initialize'
    from config.ru:in `new'
    from config.ru:in `<main>'
    from /usr/lib/ruby/vendor_ruby/rack/builder.rb:49:in `eval'
    from /usr/lib/ruby/vendor_ruby/rack/builder.rb:49:in `new_from_string'
    from /usr/lib/ruby/vendor_ruby/rack/builder.rb:40:in `parse_file'
    from /var/lib/gems/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
    from /var/lib/gems/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:24:in `app'
    from /var/lib/gems/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:42:in `start'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:135:in `block in perform'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `tap'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `perform'
    from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
    from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
    from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
    from /var/lib/gems/2.3.0/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
    from /home/mhadi/Dev/ruby_on_rails/weblog/bin/rails:9:in `require'
    from /home/mhadi/Dev/ruby_on_rails/weblog/bin/rails:9:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
    from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
    from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
    from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
    from /var/lib/gems/2.3.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
    from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /home/mhadi/Dev/ruby_on_rails/weblog/bin/spring:15:in `<top (required)>'
    from bin/rails:3:in `load'
    from bin/rails:3:in `<main>'
```

**Comment by mroutis** [comment]
Do you mind adding some extra info for us?
- Your Rails version: (I guess is `5.1.5` based on your stack trace, but just to be sure)
- The Ruby version you are running at.

Also adding some steps to reproduce it is super helpful, here is a guide with more information about that: http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
