### ISSUE TITLE
Add a whitelist to polymorphic associations to prevent constant injection

### ISSUE THREAD

**Issue by grosser** [rails/rails#33101]
### Steps to reproduce

```ruby
belongs_to :parent, polymorhic: true

user.create!(params.require(:user).permit(:parent_type, :parent_id))
```

### Expected behavior

either would help:
 - allow defining a whitelist and reject everything except these
 - do not call `parent` in this case when validation for `parent_type` fails, for example if the developer added `validates :parent_type, inclusion: ["User", "Team"]`

### Actual behavior

... fill this out with a bad value for parent_type and we get either 
`NameError: uninitialized constant Foooo`

or `NoMethodError: undefined method `unscoped' for String:Class`

which are both kinda scary (can trigger method calls on unsupported, user-chosen objects)

### Workaround

```
  # never allow assigning an invalid type since rails will constantize and call methods on it
  def parent_type=(value)
    super(ALLOWED_PARENT_TYPES.include?(value) ? value : nil)
  end
```

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by rafaelfranca** [comment]
Is not the whitelist already allowed in the controller? How a whitelist in the model would make people actually think about the consequences of passing user input for that attribute?

**Comment by grosser** [comment]
The controller only offers field whitelisting and not value whitelisting
and lots of other values are validated in the models. stonger_parameters
deals with value whitelisting, but that's not in core rails.
So yeah not sure what the cleanest way of handling this is or if there is
no nice way, hence the issue 😊

**Comment by rafaelfranca** [comment]
I feel a simple.

```ruby
user.create!(user_params)

def user_params
  params.require(:user).permit(:parent_id).merge(parent_type: validate_parent_type(params[:user]))
end

def validate_parent_type(params)
  params[:parent_type].in?(['A', 'B'])
end
```

already protect the applications. The developers are responsible for checking the user input before passing to Active Record. Checking is not only whitelist which parameters are being passed, but also if the parameter is acceptable.

If users want to validate in the model layer, like is already being done for all other attributes they can fix with:

```ruby
validates :parent_type, inclusion: { in: ["User", "Team"], strict: true }
```

Another thing we could do is to check if the class is an `ActiveRecord::Base` subclass after constantize, and if it is not return `nil` as the parent, at least it narrow down the scope of classes users can access.

What I'm having difficult to understand is how the validation could fail and the constant be called and called unscope on it. Would not that only happen when the reader is called explicitly?

**Comment by grosser** [comment]
the issue is not that the validation fails, but that even when it fails rails constantizes the the passed in value since it tries to also check presence on `parent`

**Comment by grosser** [comment]
hmmm actually `strict` seems to be a good alternative, no regular user should get these ...
it only works when placed above the belongs_to though, but that's still pretty good workaround :)

**Comment by rafaelfranca** [comment]
Weird. Why it is only works if you place about the belongs_to? Maybe because the belongs_to is trying to validate the presence of the record (so calling the reader) before checking the inclusion?

**Comment by grosser** [comment]
Exactly

**Comment by rafaelfranca** [comment]
We could make possible to do `belongs_to :parent, polymorhic: ["User", "Team"]`

**Comment by grosser** [comment]
that looks neat!
... would it just ignore others or fail validation ?

**Comment by grosser** [comment]
... would also serve as kinda living documentation ...

**Comment by mohsen-alizadeh** [comment]
I've written following script. It works fine and no exception
Can you explain more or edit it script to produce your anticipated error?

```Ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  # source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", path: '/home/mohsen/projects/rails'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :pictures do |t|
      t.string  :name
      t.integer :imageable_id
      t.string  :imageable_type
      t.timestamps
    end

  create_table :employees do |t|
    t.string :name
  end

  create_table :products do |t|
    t.string :name
  end
end


class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
end
 
class Employee < ActiveRecord::Base
  has_many :pictures, as: :imageable
end
 
class Product < ActiveRecord::Base
  has_many :pictures, as: :imageable
end

class BugTest < Minitest::Test
  def test_association_stuff
    employee = Employee.create(name: 'Mohsen Alizadeh')
    employee.pictures.create(name: 'mosi pic')

    assert Picture.create!(imageable_type: 'Foo', imageable_id: 1)
  end
end
```

**Comment by grosser** [comment]
can confirm that this script works ... but mine still fails ... with the same rails version 🤷‍♂️ 
removed all gems that smelled like they might mess with global state ... backtrace is:

```
NameError: uninitialized constant Foo
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:283:in `const_get'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:283:in `block in constantize'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:281:in `each'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:281:in `inject'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:281:in `constantize'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
    vendor/bundle/gems/activerecord-5.2.0/lib/active_record/associations/belongs_to_polymorphic_association.rb:9:in `klass'
    vendor/bundle/gems/activerecord-5.2.0/lib/active_record/associations/belongs_to_association.rb:71:in `find_target?'
    vendor/bundle/gems/activerecord-5.2.0/lib/active_record/associations/association.rb:151:in `load_target'
    vendor/bundle/gems/activerecord-5.2.0/lib/active_record/associations/association.rb:47:in `reload'
    vendor/bundle/gems/activerecord-5.2.0/lib/active_record/associations/singular_association.rb:9:in `reader'
    vendor/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/association.rb:108:in `ignored'
    vendor/bundle/gems/activemodel-5.2.0/lib/active_model/validator.rb:150:in `block in validate'
    vendor/bundle/gems/activemodel-5.2.0/lib/active_model/validator.rb:149:in `each'
    vendor/bundle/gems/activemodel-5.2.0/lib/active_model/validator.rb:149:in `validate'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:426:in `block in make_lambda'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `catch'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `block in default_terminator'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:199:in `block in halting'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `block in invoke_before'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `each'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `invoke_before'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:131:in `run_callbacks'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:816:in `_run_validate_callbacks'
    vendor/bundle/gems/activemodel-5.2.0/lib/active_model/validations.rb:409:in `run_validations!'
    vendor/bundle/gems/activemodel-5.2.0/lib/active_model/validations/callbacks.rb:118:in `block in run_validations!'
;
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:98:in `run_callbacks'
    vendor/bundle/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
    vendor/bundle/gems/activemodel-5.2.0/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
    vendor/bundle/gems/activemodel-5.2.0/lib/active_model/validations.rb:339:in `valid?'
    vendor/bundle/gems/activerecord-5.2.0/lib/active_record/validations.rb:67:in `valid?'
    test/models/report_ignore_test.rb:17:in `block (3 levels) in <main>'
```

**Comment by grosser** [comment]
... and we found a decent workaround so maybe just close this 🤷‍♀️ 
got a test in my app that will fail if I end breaking it somehow

**Comment by rafaelfranca** [comment]
I think that script doesn't fail because belongs to is not required by default in that script, so the reader is not called.

**Comment by grosser** [comment]
oh ... the framework_defaults are not called or something like that :)

**Comment by dmitry** [comment]
Would be great to have this resolved.
