### ISSUE TITLE
Application becomes stuck if job enqueued while app is reloading

### ISSUE THREAD

**Issue by DimitriosLisenko** [rails/rails#33133]
I have previously posted this on the Sidekiq project (https://github.com/mperham/sidekiq/issues/3865), since I can reliably reproduce the bug using Sidekiq (my Puma server has a slightly different issue where the threads seem to be concurrently reloading code, which shouldn't be happening - may be related), and was suggested to post the issue here.

It looks like it has to do with the new Rails executor/reloader framework - as far as I understand, all Sidekiq jobs are wrapped in the reloader.

### Version Information
Ruby: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`
Rails: `Rails 5.2.0`
Sidekiq: `Sidekiq 5.1.3`

### Reproduction steps
- Create brand new Rails app using `rails new rails_sidekiq_reproduce_bug`
- Add Sidekiq 5.1.3 to the Gemfile
- Create a Sidekiq job that spawns threads (similar to what http://guides.rubyonrails.org/threading_and_code_execution.html recommends)
```
class ReproduceBugJob
	include Sidekiq::Worker
	sidekiq_options :queue => :default
	sidekiq_options :retry => false

	def perform(sleep_seconds, threads_to_spawn)
		threads = []
		threads_to_spawn.times do
			threads << Thread.new do
				Rails.application.executor.wrap do
					puts "begin #{sleep_seconds} second sleep"
					sleep sleep_seconds
					puts "end #{sleep_seconds} second sleep"
				end
			end
		end

		ActiveSupport::Dependencies.interlock.permit_concurrent_loads do
			threads.map(&:join)
		end
	end
end
```
- open up the rails console and quickly enqueue a few jobs via `ReproduceBugJob.perform_async(1, 1)` - all works as expected
- open and save a file and quickly enqueue a few more jobs via `ReproduceBugJob.perform_async(1, 1)` - all still works as expected
- now the secret sauce: simulate a longer app reload time by adding the following to your `config/application.rb` file:
```
config.to_prepare do
	sleep_seconds = 5
	puts "Simulating longer application reload time of #{sleep_seconds} seconds"
	sleep sleep_seconds
end
```
- open up the rails console and enqueue a few jobs via `ReproduceBugJob.perform_async(1, 1)` - all works as expected
- open and save a file and enqueue a **single** `ReproduceBugJob.perform_async(1, 1)` job - app will reload for 5 seconds, and then run the job. If you enqueue more jobs after this point, everything works as expected.
- open and save a file and then enqueue a **single** `ReproduceBugJob.perform_async(1, 1)` job, and then **while the app is reloading** enqueue another one - BOOM - the application is stuck. Jobs are continued to be enqueued, but never execute after this point.

### Expected behavior
I expect the app to finish reloading, and then run the newly enqueued jobs concurrently.

### Actual behavior
The application becomes stuck if a job gets enqueued while the app is still reloading.

### Other information
Via a fairly nasty process I hooked up the `ActionDispatch::DebugLocks` middleware to run in Sidekiq like this (there is surely a better way, but it works!):
```
Signal.trap('TTOU') do
	Thread.new do
		puts ActionDispatch::DebugLocks.new(Rails.application, nil).send(:render_details, nil)[2][0]
	end
end
```

which gives me the following output when the application is stuck:
```
Thread 0 [0x3ff72e160a0c sleep]  No lock (yielded share)
  Waiting in start_exclusive to "unload"
  may be pre-empted for: "load", "unload"
  blocked by: 2
  blocking: 1

.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `sleep'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `wait'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `wait'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:121:in `wait_while'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:221:in `wait_for'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:83:in `block (2 levels) in start_exclusive'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:82:in `block in start_exclusive'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:77:in `start_exclusive'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:25:in `start_unloading'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:101:in `require_unload_lock!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:120:in `class_unload!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/railties-5.2.0/lib/rails/application/finisher.rb:177:in `block (2 levels) in <module:Finisher>'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:426:in `instance_exec'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:426:in `block in make_lambda'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `catch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `block in default_terminator'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:199:in `block in halting'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `block in invoke_before'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `each'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `invoke_before'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:131:in `run_callbacks'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:110:in `run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:115:in `run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:72:in `block in run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:69:in `tap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:69:in `run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:64:in `run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:85:in `wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'


---


Thread 1 [0x3ff72e1cfac4 sleep]  No lock
  Waiting in start_sharing
  blocked by: 0

.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `sleep'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `wait'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `wait'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:121:in `wait_while'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:221:in `wait_for'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:125:in `block in start_sharing'
.../.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:115:in `start_sharing'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:33:in `start_running'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/railties-5.2.0/lib/rails/application/finisher.rb:94:in `run'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:27:in `before'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:426:in `block in make_lambda'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `catch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `block in default_terminator'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:199:in `block in halting'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `block in invoke_before'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `each'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `invoke_before'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:131:in `run_callbacks'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:110:in `run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:72:in `block in run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:69:in `tap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:69:in `run!'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:85:in `wrap'
.../rails_sidekiq_reproduce_bug/app/jobs/reproduce_bug_job.rb:10:in `block (2 levels) in perform'


---


Thread 2 [0x3ff72e161ab0 sleep]  No lock (yielded share)
  blocking: 0

.../rails_sidekiq_reproduce_bug/app/jobs/reproduce_bug_job.rb:19:in `join'
.../rails_sidekiq_reproduce_bug/app/jobs/reproduce_bug_job.rb:19:in `map'
.../rails_sidekiq_reproduce_bug/app/jobs/reproduce_bug_job.rb:19:in `block in perform'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
.../rails_sidekiq_reproduce_bug/app/jobs/reproduce_bug_job.rb:18:in `perform'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
.../.rvm/gems/ruby-2.5.1@rails_sidekiq_reproduce_bug/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

This is kinda weird because `thread 2` is blocking `thread 0`, but is itself holding no lock. Also there seems to be two reloaders running, though I haven't yet dug deeper to know what the expected behaviour is.

**Comment by mohsen-alizadeh** [comment]
@DimitriosLisenko Maybe you need to use **Reloader** instead of **Executor**

**Comment by DimitriosLisenko** [comment]
@mohsen-alizadeh hey, thanks for your answer.

My understanding was that you shouldn't nest `Reloader` in another `Reloader` (the Sidekiq job is already wrapped inside one) since it can cause a deadlock ([source](https://bibwild.wordpress.com/2016/12/29/concurrency-in-rails-5-0/)), and that it's only meant for framework-level processes, which this isn't.

I gave it a go anyway, and the application now becomes stuck on the first reload unconditionally.

**Comment by matthewd** [comment]
Thanks, this is a great report! (And I can confirm you're using the API correctly -- including using Executor over Reloader inside the job.)

The output isn't super clear, but `2` blocking `0` is expected: `2` had a lock, and has yielded it to allow concurrent loads... but `0` wants to *un*load, which is not permitted by the yield. (New classes are allowed to autoload in the middle of your job, but existing ones can't be removed.)

Our problem here is that the second reload (`0`) wants to happen, and because it's waiting for an exclusive lock, `1` isn't allowed to start using the shared lock. (It'd be concurrency-safe for it to do so, but we make it get in line behind the exclusive lock out of 'fairness', so that a constant stream of new shared-lock uses can't permanently starve the exclusive one.)

Off the top of my head, I think maybe we should introduce an Executor / Reloader distinction here: if a Reloader wants a new share lock, it needs to give way to any pending exclusive lock first; but if an Executor wants it, it can jump ahead of the waiting exclusive, because, as in this case, we might be waiting on it.

Does that make sense? Would you like to have a go at implementing something along those lines? (If not, I'm of course happy to put it on my list -- I just don't want to deprive you of the chance to fix it after you've done such a good job narrowing it down :smile:)

(A lower-hanging contribution fruit would be adding a class method to DebugLocks to wrap up that render hack... this is not the first time it's been useful, and it sucks that people have to rediscover it each time.)

**Comment by matthewd** [comment]
> Off the top of my head, I think maybe we should introduce an Executor / Reloader distinction here: if a Reloader wants a new share lock, it needs to give way to any pending exclusive lock first; but if an Executor wants it, it can jump ahead of the waiting exclusive, because, as in this case, we might be waiting on it.

cc @thedarkone

**Comment by thedarkone** [comment]
@matthewd that's a neat idea. Considering the intended use cases for Executor/Reloader, it certainly makes sense to allow Executors to preempt (with their share requests). Maybe we could predicate the preemption on having at least one thread that has yielded its shares (ie it must have done `permit_concurrent_loads`), as this indicates a "typical-waiting-for-other-threads" situation.

---

I'm still thinking about adding an explicit deadlock-like check (since `ShareLock` knows about all the relevant threads):

 * add an `@cv_sleeping_cnt` i-var,
 * all `@cv.broadcast` calls reset it to `@cv_sleeping_cnt = 0`,
 * track external `yield_shares` calls,
 * `ShareLock#wait_for` would have (in its `@cv.wait_while {}`) a `@cv_sleeping_cnt += 1` increment and a deadlock check: `if @cv_sleeping_cnt + external_yielded_thread_cnt == total_known_thread_cnt; deadlocked!; end`,
 * `deadlocked!` would relax `block_share` requirements for all queued up threads.

**Comment by DimitriosLisenko** [comment]
I've tested this again on Rails 6.1 with zeitwerk and was still able to replicate this issue. I'll see if I'm able to find some time to fix it.

**Comment by DimitriosLisenko** [comment]
I suppose I'll get the ball rolling!

@matthewd I have a PR [here](https://github.com/DimitriosLisenko/rails/pull/1/files) with a very rough version of what I understood you meant in https://github.com/rails/rails/issues/33133#issuecomment-397289479. Would you say that's the right approach still, and are there any parts of the codebase I should be aware of other than these?
