### ISSUE TITLE
Migrations with auto_increment fail on default postgresql database

### ISSUE THREAD

**Issue by JESii** [rails/rails#33194]
### Steps to reproduce

1. Create a basic rails site, accepting the default postgresql database
2. Create a basic database with a string field
3. Create a migration with an auto_increment field;

### Expected behavior
Should be able to add the auto_increment field; since this is postgresql and it's the default database when creating a new Rails application, I would expect Rails to recognize that "auto_increment" in mySQL is actually "identity" in postgresql.

### Actual behavior
Rejects the migration because postgresql supports only the identity attribute and not auto_imcrement.
```
rails db:migrate
== 20180622154106 AddIdKey: migrating =========================================
-- add_column(:statuses, :id, :integer, {:auto_increment=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::SyntaxError: ERROR:  syntax error at or near "AUTO_INCREMENT"
LINE 1: ALTER TABLE "statuses" ADD "id" integer AUTO_INCREMENT
                                                ^
: ALTER TABLE "statuses" ADD "id" integer AUTO_INCREMENT
/Users/jseidel/dev/status321/db/migrate/20180622154106_add_id_key.rb:3:in `change'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
bin/rails:4:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "AUTO_INCREMENT"
LINE 1: ALTER TABLE "statuses" ADD "id" integer AUTO_INCREMENT
                                                ^
: ALTER TABLE "statuses" ADD "id" integer AUTO_INCREMENT
/Users/jseidel/dev/status321/db/migrate/20180622154106_add_id_key.rb:3:in `change'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
bin/rails:4:in `<main>'

Caused by:
PG::SyntaxError: ERROR:  syntax error at or near "AUTO_INCREMENT"
LINE 1: ALTER TABLE "statuses" ADD "id" integer AUTO_INCREMENT
                                                ^
/Users/jseidel/dev/status321/db/migrate/20180622154106_add_id_key.rb:3:in `change'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/jseidel/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
Furthermore, the statement **this and all later migrations canceled** is not completely true; if you examine the postgresql database, you'll see that the id field WAS added to the database. So now a rollback is required....

### System configuration
**Rails 5.2.0**:

**ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]**:

**Comment by y-yagi** [comment]
Because the `AUTO_INCREMENT` is an attribute that MySQL supports independently, it is intentional that an error occurs in PostgreSQL. 
If you want to add primary key later, specify `primary_key` for type.
If use this, MySQL / PostgreSQL will automatically use automatic sequential numbering. 

```ruby
add_column :statuses, :id, :primary_key 
``` 

Ref: http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_column
