### ISSUE TITLE
invalid %-encoding in Rails.cache.delete_matched

### ISSUE THREAD

**Issue by bnymn** [rails/rails#33201]
### Steps to reproduce
1. Create a new rails app `rails _4.2.10_ new test-app`
2. Run the following command to regenerate the situation
```
mkdir -p tmp/cache/1FA/102/views%2Fid%2F370418%2Fslug%2Ftalat-bulut-b-planimiz-da-c-planimiz-da-var%2Ftitle%2FTalat+Bulut%3A+B+plan%C4%B1m%C4%B1z+da%2C+C+plan%C4%B1m%C4%B1z+da+var%2Fsummary%2FYasak+Elma%E2%80%99n%C4%B1n+ba%C5%9Frol+oyuncusu+Talat+Bulut%E2/%80%99un+%2862%29+kost%C3%BCm+asistan%C4%B1+%C3%96zge+%C5%9Eim%C5%9Fek%E2%80%99i+%2819%29+taciz+etti%C4%9Fi+iddia+edilmi%C5%9Fti.+Atat%C3%BCrk+Havaliman%C4%B1%E2%80%99nda+g%C3%B6r%C3%BCnt%C3%BClenen+Talat+Bulut+%2C+ya%C5%9Fad%C4/%B1klar%C4%B1n%C4%B1+troll+s...%2Fimage_normal%2Fhttp%3A%2F%2Flocalhost%3A3000%2Fsystem%2Fnews%2Fimages%2F000%2F370%2F418%2Fnormal%2F370418.jpeg%2Fimage_small%2Fhttp%3A%2F%2Flocalhost%3A3000%2Fsystem%2Fnews%2Fimages%2F000%2F370%/2F418%2Fsmall%2F370418.jpeg%2Fimage_thumb%2Fhttp%3A%2F%2Flocalhost%3A3000%2Fsystem%2Fnews%2Fimages%2F000%2F370%2F418%2Fthumb%2F370418.jpeg%2Fpublished_at%2F0%2F44%2F11%2F18%2F6%2F2018%2F1%2F169%2Ffalse%2F%2B03%2Fupdated_at%2F40%
```

```
touch tmp/cache/1FA/102/views%2Fid%2F370418%2Fslug%2Ftalat-bulut-b-planimiz-da-c-planimiz-da-var%2Ftitle%2FTalat+Bulut%3A+B+plan%C4%B1m%C4%B1z+da%2C+C+plan%C4%B1m%C4%B1z+da+var%2Fsummary%2FYasak+Elma%E2%80%99n%C4%B1n+ba%C5%9Frol+oyuncusu+Talat+Bulut%E2/%80%99un+%2862%29+kost%C3%BCm+asistan%C4%B1+%C3%96zge+%C5%9Eim%C5%9Fek%E2%80%99i+%2819%29+taciz+etti%C4%9Fi+iddia+edilmi%C5%9Fti.+Atat%C3%BCrk+Havaliman%C4%B1%E2%80%99nda+g%C3%B6r%C3%BCnt%C3%BClenen+Talat+Bulut+%2C+ya%C5%9Fad%C4/%B1klar%C4%B1n%C4%B1+troll+s...%2Fimage_normal%2Fhttp%3A%2F%2Flocalhost%3A3000%2Fsystem%2Fnews%2Fimages%2F000%2F370%2F418%2Fnormal%2F370418.jpeg%2Fimage_small%2Fhttp%3A%2F%2Flocalhost%3A3000%2Fsystem%2Fnews%2Fimages%2F000%2F370%/2F418%2Fsmall%2F370418.jpeg%2Fimage_thumb%2Fhttp%3A%2F%2Flocalhost%3A3000%2Fsystem%2Fnews%2Fimages%2F000%2F370%2F418%2Fthumb%2F370418.jpeg%2Fpublished_at%2F0%2F44%2F11%2F18%2F6%2F2018%2F1%2F169%2Ffalse%2F%2B03%2Fupdated_at%2F40%/2F44%2F12%2F18%2F6%2F2018%2F1%2F169%2Ffalse%2F%2B03%2F1%2Faa19fe7a59389a2a8e7545e8bfcaa87e
```

3. Run rails console `bin/rails c`
4. Run `Rails.cache.delete_matched('*')` in the rails console.

### Expected behavior
Matched caches should be deleted.

### Actual behavior
Exeption thrown.
```
Traceback (most recent call last):
       16: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:166:in `block in search_dir'
       15: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:162:in `search_dir'
       14: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:162:in `foreach'
       13: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:166:in `block in search_dir'
       12: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:162:in `search_dir'
       11: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:162:in `foreach'
       10: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:166:in `block in search_dir'
        9: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:162:in `search_dir'
        8: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:162:in `foreach'
        7: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:166:in `block in search_dir'
        6: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:162:in `search_dir'
        5: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:162:in `foreach'
        4: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:168:in `block in search_dir'
        3: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:61:in `block (2 levels) in delete_matched'
        2: from /home/home/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/file_store.rb:143:in `file_path_key'
        1: from /home/home/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/common.rb:393:in `decode_www_form_component'
ArgumentError (invalid %-encoding (%80%99un+%2862%29+kost%C3%BCm+asistan%C4%B1+%C3%96zge+%C5%9Eim%C5%9Fek%E2%80%99i+%2819%29+taciz+etti%C4%9Fi+iddia+edilmi%C5%9Fti.+Atat%C3%BCrk+Havaliman%C4%B1%E2%80%99nda+g%C3%B6r%C3%BCnt%C3%BClenen+Talat+Bulut+%2C+ya%C5%9Fad%C4/%B1klar%C4%B1n%C4%B1+troll+s...%2Fimage_normal%2Fhttp%3A%2F%2Flocalhost%3A3000%2Fsystem%2Fnews%2Fimages%2F000%2F370%2F418%2Fnormal%2F370418.jpeg%2Fimage_small%2Fhttp%3A%2F%2Flocalhost%3A3000%2Fsystem%2Fnews%2Fimages%2F000%2F370%/2F418%2Fsmall%2F370418.jpeg%2Fimage_thumb%2Fhttp%3A%2F%2Flocalhost%3A3000%2Fsystem%2Fnews%2Fimages%2F000%2F370%2F418%2Fthumb%2F370418.jpeg%2Fpublished_at%2F0%2F44%2F11%2F18%2F6%2F2018%2F1%2F169%2Ffalse%2F%2B03%2Fupdated_at%2F40%/2F44%2F12%2F18%2F6%2F2018%2F1%2F169%2Ffalse%2F%2B03%2F1%2Faa19fe7a59389a2a8e7545e8bfcaa87e))
```

### System configuration
**Rails version**: 4.2.10

**Ruby version**: 2.3.1

**Comment by bnymn** [comment]
I have created the following file in `config/initializers/overrides/active_support_cache_file_store.rb`.

```
module ActiveSupport
  module Cache
  	class FileStore < Store
  		private
        # Translate a file path into a key.
        def file_path_key(path)
          puts "** PATH ** "
          puts path
          puts "** PATH ** "
          
          fname = path[cache_path.to_s.size..-1]
          
          puts "** FNAME (1) ** "
          puts fname
          puts "** FNAME (1) ** "
          
          fname = fname.split(File::SEPARATOR, 4).last

          puts "** FNAME (2) ** "
          puts fname
          puts "** FNAME (2) ** "

          fname = fname.gsub(File::SEPARATOR, '')

          puts "** FNAME (3) ** "
          puts fname
          puts "** FNAME (3) ** "

          key = URI.decode_www_form_component(fname, Encoding::UTF_8)
          # key = key.encode("UTF-8", "binary", invalid: :replace, undef: :replace, replace: '')
          puts "===="
          puts key
          puts "===="
          key
        end
  	end
  end
end
```

**Comment by utilum** [comment]
4.2 is no longer supported except for severe security issues, which means that 

> ...it's your own responsibility to deal with bugs and security issues. We may provide backports of the fixes and publish them to git, however there will be no new versions released. If you are not comfortable maintaining your own versions, you should upgrade to a supported version

See [Maintenance Policy](http://edgeguides.rubyonrails.org/maintenance_policy.html)

**Comment by aiomaster** [comment]
The problem still exists with rails 5.2.1
Avoiding the problematic code by using redis store instead of file store is not fixing it, so why is this ticket closed?
