### ISSUE TITLE
Probleman with ActiveRecord find method

### ISSUE THREAD

**Issue by xdougx** [rails/rails#33251]
Hello Guys, I'm on Rails 5.2.0 and Ruby 2.5.0

And when try to find a model that doesn't exists

```
User.find('Don Exists')
```

Im receiving this error:

```
undefined method `limit' for []:Array
````

With this Backtrace:

```ruby
[
    [ 0] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/core.rb:172:in `block in find'",
    [ 1] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/statement_cache.rb:91:in `create'",
    [ 2] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/core.rb:280:in `block in cached_find_by_statement'",
    [ 3] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/collection/map/non_concurrent_map_backend.rb:31:in `compute_if_absent'",
    [ 4] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/collection/map/mri_map_backend.rb:25:in `block in compute_if_absent'",
    [ 5] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/collection/map/mri_map_backend.rb:25:in `synchronize'",
    [ 6] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/collection/map/mri_map_backend.rb:25:in `compute_if_absent'",
    [ 7] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/core.rb:280:in `cached_find_by_statement'",
    [ 8] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/core.rb:171:in `find'",
    [ 9] "(pry):2:in `__pry__'",
    [10] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:355:in `eval'",
    [11] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:355:in `evaluate_ruby'",
    [12] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:323:in `handle_line'",
    [13] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'",
    [14] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:242:in `catch'",
    [15] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:242:in `block in eval'",
    [16] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:241:in `catch'",
    [17] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:241:in `eval'",
    [18] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/repl.rb:77:in `block in repl'",
    [19] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `loop'",
    [20] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `repl'",
    [21] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `block in start'",
    [22] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/input_lock.rb:61:in `__with_ownership'",
    [23] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/input_lock.rb:79:in `with_ownership'",
    [24] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `start'",
    [25] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/repl.rb:13:in `start'",
    [26] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/pry-0.11.3/lib/pry/pry_class.rb:192:in `start'",
    [27] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:64:in `start'",
    [28] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:19:in `start'",
    [29] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:96:in `perform'",
    [30] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'",
    [31] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'",
    [32] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'",
    [33] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'",
    [34] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'",
    [35] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'",
    [36] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'",
    [37] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'",
    [38] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'",
    [39] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'",
    [40] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'",
    [41] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'",
    [42] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'",
    [43] "/Users/douglas/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'",
    [44] "bin/rails:4:in `<main>'"
]
```

**Comment by xdougx** [comment]
Im Debugging the code and i find this:

```ruby
statement = cached_find_by_statement(key) { |params|
  # where method is returning an Array not an ActiveRecord::Relation 
  where(key => params.bind).limit(1)
}
```

**Comment by xdougx** [comment]
Resolved, internal conflict!
