### ISSUE TITLE
Upgrade to Rails 5.1 results in JSON::ParserError exception for existing session cookies

### ISSUE THREAD

**Issue by jkepps** [rails/rails#33580]
### Steps to reproduce
Log in to a rails application using Rails 5.0 specifying a session key in session_store.rb:
`Rails.application.config.session_store :cookie_store, key: '_my_session'`

Restart the rails application using rails 5.1 (or 5.2). Attempt to login or load the home page.

Seems very similar to [#30364](https://github.com/rails/rails/issues/30364) (now closed with no resolution)
### Expected behavior
Previously stored session cookies are still able to be parsed.

### Actual behavior
The server responds with a 500 and the following error:
`JSON::ParserError (765: unexpected token at I"session_id:ETI"%a7a44421c9f6dcb4891fd6854dfa2d82;')`

### System configuration
**Rails version**:
5.1.0, 5.2.0
**Ruby version**:
2.3.3

**Comment by jkepps** [comment]
Here's the full stack trace:
```
I, [2018-08-10T18:35:51.207777 #11101]  INFO -- : Started POST "/api/login.json" for 127.0.0.1 at 2018-08-10 18:35:51 +0000
I, [2018-08-10T18:35:51.209775 #11101]  INFO -- : Processing by Api::Auth::SessionsController#create as JSON
I, [2018-08-10T18:35:51.209892 #11101]  INFO -- :   Parameters: {"user"=>{"login"=>"jordan.epps@revolutionprep.com", "password"=>"[FILTERED]"}, "session"=>{}}
I, [2018-08-10T18:35:51.211376 #11101]  INFO -- : Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)
F, [2018-08-10T18:35:51.218164 #11101] FATAL -- :
F, [2018-08-10T18:35:51.218360 #11101] FATAL -- : JSON::ParserError (765: unexpected token at I"session_id:ETI"%72ffdfe38dad32efa59c0ac076591188;'):
F, [2018-08-10T18:35:51.218459 #11101] FATAL -- :
F, [2018-08-10T18:35:51.218584 #11101] FATAL -- : json (2.1.0) lib/json/common.rb:156:in `parse'
json (2.1.0) lib/json/common.rb:156:in `parse'
activesupport (5.2.0) lib/active_support/json/decoding.rb:23:in `decode'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:517:in `load'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:549:in `deserialize'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:639:in `parse'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:473:in `[]'
actionpack (5.2.0) lib/action_dispatch/middleware/session/cookie_store.rb:109:in `get_cookie'
actionpack (5.2.0) lib/action_dispatch/middleware/session/cookie_store.rb:84:in `block (2 levels) in unpacked_cookie_data'
actionpack (5.2.0) lib/action_dispatch/middleware/session/abstract_store.rb:54:in `stale_session_check!'
actionpack (5.2.0) lib/action_dispatch/middleware/session/cookie_store.rb:83:in `block in unpacked_cookie_data'
rack (2.0.5) lib/rack/request.rb:57:in `fetch'
rack (2.0.5) lib/rack/request.rb:57:in `fetch_header'
actionpack (5.2.0) lib/action_dispatch/middleware/session/cookie_store.rb:82:in `unpacked_cookie_data'
actionpack (5.2.0) lib/action_dispatch/middleware/session/cookie_store.rb:77:in `block in extract_session_id'
actionpack (5.2.0) lib/action_dispatch/middleware/session/abstract_store.rb:54:in `stale_session_check!'
actionpack (5.2.0) lib/action_dispatch/middleware/session/cookie_store.rb:76:in `extract_session_id'
actionpack (5.2.0) lib/action_dispatch/request/session.rb:54:in `block in id'
actionpack (5.2.0) lib/action_dispatch/request/session.rb:53:in `fetch'
actionpack (5.2.0) lib/action_dispatch/request/session.rb:53:in `id'
actionpack (5.2.0) lib/action_dispatch/request/session.rb:72:in `id'
rack (2.0.5) lib/rack/session/abstract/id.rb:295:in `current_session_id'
rack (2.0.5) lib/rack/session/abstract/id.rb:301:in `session_exists?'
actionpack (5.2.0) lib/action_dispatch/request/session.rb:189:in `exists?'
actionpack (5.2.0) lib/action_dispatch/request/session.rb:213:in `load_for_read!'
actionpack (5.2.0) lib/action_dispatch/request/session.rb:92:in `[]'
warden (1.2.7) lib/warden/session_serializer.rb:31:in `fetch'
warden (1.2.7) lib/warden/proxy.rb:213:in `user'
airbrake (7.3.4) lib/airbrake/rack/user.rb:13:in `extract'
airbrake (7.3.4) lib/airbrake/rack/context_filter.rb:43:in `call'
airbrake-ruby (2.11.0) lib/airbrake-ruby/filter_chain.rb:44:in `block in refine'
airbrake-ruby (2.11.0) lib/airbrake-ruby/filter_chain.rb:42:in `each'
airbrake-ruby (2.11.0) lib/airbrake-ruby/filter_chain.rb:42:in `refine'
airbrake-ruby (2.11.0) lib/airbrake-ruby/notifier.rb:118:in `send_notice'
airbrake-ruby (2.11.0) lib/airbrake-ruby/notifier.rb:43:in `notify'
airbrake (7.3.4) lib/airbrake/rack/middleware.rb:76:in `notify_airbrake'
airbrake (7.3.4) lib/airbrake/rack/middleware.rb:50:in `rescue in call'
airbrake (7.3.4) lib/airbrake/rack/middleware.rb:47:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
unicorn (5.4.1) lib/unicorn/http_server.rb:606:in `process_client'
unicorn (5.4.1) lib/unicorn/http_server.rb:701:in `worker_loop'
unicorn (5.4.1) lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
unicorn (5.4.1) lib/unicorn/http_server.rb:142:in `start'
unicorn (5.4.1) bin/unicorn:126:in `<top (required)>'
/srv/www/api.rev-prep.com/shared/bundle/ruby/2.3.0/bin/unicorn:22:in `load'
/srv/www/api.rev-prep.com/shared/bundle/ruby/2.3.0/bin/unicorn:22:in `<top (required)>'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `load'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:28:in `run'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/lib/bundler/cli.rb:424:in `exec'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/lib/bundler/cli.rb:27:in `dispatch'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/lib/bundler/cli.rb:18:in `start'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/exe/bundle:30:in `block in <top (required)>'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/bin/bundle:22:in `load'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/bin/bundle:22:in `<main>'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/bin/ruby_executable_hooks:15:in `eval'
/home/deployer/.rvm/gems/ruby-2.3.3@orbit-rails5.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jkepps** [comment]
Figured out I needed to have `Rails.application.config.action_dispatch.cookies_serializer` set to `:hybrid` instead of `:json` because it was set to `:marshal` up until I migrated to 5.1

**Comment by AxelTheGerman** [comment]
FYI that was mentioned in the Rails 4.0 to 4.1 [upgrade guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#cookies-serializer) - oh fun to bring old apps back to life...
