### ISSUE TITLE
ActionDispatch::Request::Utils#normalize_encode_params error: undefined method 'with_indifferent_access'

### ISSUE THREAD

**Issue by wjordan** [rails/rails#33634]
It looks like a `require 'active_support/core_ext/hash/indifferent_access'` line is missing from `ActionDispatch::Request::Utils`, causing a `NoMethodError` to be raised from the `normalize_encode_params` helper method in certain situations.

The method was refactored to its current location in 3f299296d15bff5735a430b9d2e33476e8f24f69, but the associated `require` statement wasn't moved with it. The old `require` was soon after removed from its original location by fa216dc3b6b49660fabc6b8de41a63b1185fd8cb.

### Steps to reproduce

```ruby
gem 'actionpack', '5.2.1'
require 'action_dispatch'
puts ActionDispatch::Request::Utils.normalize_encode_params({})
```

### Expected behavior

```
{}
```

### Actual behavior

```
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from [gems]/actionpack-5.2.1/lib/action_dispatch/request/utils.rb:21:in `normalize_encode_params'
[gems]/actionpack-5.2.1/lib/action_dispatch/request/utils.rb:54:in `normalize_encode_params': undefined method `with_indifferent_access' for {}:Hash (NoMethodError)
```

### System configuration
**Rails version**: Tested in various Rails versions from 5.0.1 to 5.2.1. From the related commits, this bug should be affecting all Rails versions since `v5.0.0.beta1`.

**Ruby version**: 2.5.0

**Comment by wjordan** [comment]
I originally hit this bug while trying to run `ActionDispatch::DebugExceptions` middleware in a unit-test. Here's a minimal example of this use-case raising the same error:

```ruby
require 'action_dispatch'
debug_exceptions = ActionDispatch::DebugExceptions.new(->(_) { raise })
env = Rack::MockRequest.env_for(
  '',
  'action_dispatch.show_detailed_exceptions' => true,
  'action_dispatch.logger' => Rack::NullLogger.new(nil)
)
debug_exceptions.call(env)
```
