### ISSUE TITLE
default_scope nil error when using conditional

### ISSUE THREAD

**Issue by yagudaev** [rails/rails#33646]
### Steps to reproduce

On the way to upgrade from Rails 4.2 => 5.0.7 I found the following bug. For a little context, imagine you were creating a multi-tenant e-commerce store for book publishers. Each publisher gets their own store based on the subdomain. Shopify for book publishers if you will.

```ruby
class Book < ApplicationRecord
  default_scope { where(publisher_id: Publisher.current_id) if Publisher.current_id
end

class Publisher < ApplicationRecord
    # Class methods
  def self.current_id=(id)
    Thread.current[:studio_id] = id
  end

  def self.current_id
    Thread.current[:studio_id]
  end
end

class BooksController < ApplicationController

before_action :set_publisher

def index
  @books = Book.first # blows up
end

private

def set_publisher
   publisher = Publisher.find_by!(subdomain: request.subdomain)
   Publisher.current_id = publisher.id
end

end
```

(Guidelines for creating a bug report are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Selects the first book.

### Actual behavior
Blows up with:

```
ArgumentError: invalid argument: nil.
        from /Users/mike/projects/bookstore/vendor/ruby/2.3.0/gems/activerecord-5.0.7/lib/active_record/relation/spawn_methods.rb:36:in `merge'
        from /Users/mike/projects/bookstore/vendor/ruby/2.3.0/gems/activerecord-5.0.7/lib/active_record/scoping/default.rb:123:in `block (2 levels) in build_default_scope'
        from /Users/mike/projects/bookstore/vendor/ruby/2.3.0/gems/activerecord-5.0.7/lib/active_record/scoping/default.rb:121:in `each'
        from /Users/mike/projects/bookstore/vendor/ruby/2.3.0/gems/activerecord-5.0.7/lib/active_record/scoping/default.rb:121:in `inject'
        from /Users/mike/projects/bookstore/vendor/ruby/2.3.0/gems/activerecord-5.0.7/lib/active_record/scoping/default.rb:121:in `block in build_default_scope'
        from /Users/mike/projects/bookstore/vendor/ruby/2.3.0/gems/activerecord-5.0.7/lib/active_record/scoping/default.rb:145:in `evaluate_default_scope'
        from /Users/mike/projects/bookstore/vendor/ruby/2.3.0/gems/activerecord-5.0.7/lib/active_record/scoping/default.rb:120:in `build_default_scope'
        from /Users/mike/projects/bookstore/vendor/ruby/2.3.0/gems/activerecord-5.0.7/lib/active_record/scoping/named.rb:43:in `default_scoped'
        from /Users/mike/projects/bookstore/vendor/ruby/2.3.0/gems/activerecord-5.0.7/lib/active_record/scoping/named.rb:28:in `all'
        from /Users/mike/projects/bookstore/vendor/ruby/2.3.0/gems/activerecord-5.0.7/lib/active_record/querying.rb:3:in `first'
```
Looking at the code in those lines we see:

```ruby
          elsif default_scopes.any?
            base_rel ||= relation
            evaluate_default_scope do
              default_scopes.inject(base_rel) do |default_scope, scope|
                scope = scope.respond_to?(:to_proc) ? scope : scope.method(:call)
                default_scope.merge(base_rel.instance_exec(&scope)) # <-- issue is here 
              end
            end
          end
```

So we are not sanitizing the returned value before merging in the default scope.

To test it, I created a default scope like so as a workaround:

```
  default_scope do
    if Publisher.current_id
      where(studio: Studio.current_id)
    else
      self
    end
  end
```

It seems to fix it. But would love for us to invest in a proper fix of rails

### System configuration
**Rails version**: 5.0.7

**Ruby version**: 2.3.7

**Comment by y-yagi** [comment]
5.0 series are not supported anymore for anything besides severe security fixes. 
Please check whether the issue can be reproduced with the latest Rails. If you can reproduce, feel free to reopen the issue. Thanks!
