### ISSUE TITLE
ActionView::Template::Error: undefined method `generate_key' for nil:NilClass

### ISSUE THREAD

**Issue by johan-smits** [rails/rails#33788]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
I have a ActiveJob that renders a view. In the view there are several links. On Rails 5.2.0 it worked, but now I updated to 5.2.1 it breaks.

### Actual behavior
The render raises an template error

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1p57

```ruby
class GenerateCompanyUsageReportJob < ApplicationJob
  ApplicationController.render(partial: 'reports/report', locals: {company: report.company})
end

# In the view:
link_to(company.contact_person.name, account_url(company.contact_person))
```

BT:
```ruby
Error:
GenerateCompanyUsageReportJobTest#test_GenerateCompanyUsageReportWorker_test:
ActionView::Template::Error: undefined method `generate_key' for nil:NilClass
    app/views/reports/_report.html.erb:34:in `_app_views_reports__report_html_erb___407164473507636179_47001497228080'
    app/jobs/generate_company_usage_report_job.rb:9:in `perform'
    test/jobs/generate_company_usage_report_job_test.rb:5:in `block in <class:GenerateCompanyUsageReportJobTest>'
```

**Comment by johan-smits** [comment]
The issue was found in a other gem.
