### ISSUE TITLE
Bootsnap::LoadPathCache::Store::NestedTransactionError

### ISSUE THREAD

**Issue by KenkenIchimura** [rails/rails#33827]
Steps to reproduce
/server/config/boot.rb
```
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)

require 'bundler/setup' # Set up gems listed in the Gemfile.
require 'bootsnap/setup' # Speed up boot time by caching expensive operations.

```

ErrorMessage

-error message Terminal 
```
#<Bootsnap::LoadPathCache::Store::NestedTransactionError: 
Bootsnap::LoadPathCache::Store::NestedTransactionError>
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap- 
1.3.1/lib/bootsnap/load_path_cache/store.rb:43:in `transaction'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap- 
1.3.1/lib/bootsnap/load_path_cache/cache.rb:130:in `push_paths_locked'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap- 
1.3.1/lib/bootsnap/load_path_cache/cache.rb:113:in `block in 
reinitialize'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap- 
1.3.1/lib/bootsnap/load_path_cache/cache.rb:107:in `synchronize'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap- 
1.3.1/lib/bootsnap/load_path_cache/cache.rb:107:in `reinitialize'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap- 
1.3.1/lib/bootsnap/load_path_cache/cache.rb:46:in `find'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap- 
1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in
`require'
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/
activesupport 
#<LoadError: cannot load such file -- rails/backtrace_cleaner>
/usr/local/var/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap- 
1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 
`require'

```

Expected behavior
 Api connection should succeed.

Actual behavior
 APi doesn' t work and render above error message on terminal.

### System configuration
Versions
 - Ruby '2.5.1'
 - Rails 5.2.1 
 - bootsnap (1.3.1)

**Comment by y-yagi** [comment]
This is a Bootsnap's issue, not a Rails's issue. Let's track https://github.com/Shopify/bootsnap/issues/119 
If Rails does not work due to Bootsnap, please remove `require 'bootsnap/setup'` from `config/boot.rb` and `bootsnap` from `Gemfile`. So Rails no longer uses bootsnap.
