### ISSUE TITLE
The feature "eager-url-helpers" is not working with the helper "devise_for"

### ISSUE THREAD

**Issue by nicolasmlv** [rails/rails#34044]
This merge : https://github.com/rails/rails/commit/7f870a5ba2aa9177aa4a0e03a9d027928ba60e49 is adding an incompatibility between Devise and Rails (maybe it should be a bug in the Devise repo?) : the devise helper `devise_for` is now raising an Exception `ActionDispatch::Routing::RouteSet::UnfinalizedRouteSet => routes have not been finalized. Please call 'finalize!' or use 'draw(&block)' `

### Steps to reproduce
`rails new app`
add to the Gemfile :
```
gem 'rails', git: 'https://github.com/rails/rails.git', ref: '7f870a5ba2aa9177aa4a0e03a9d027928ba60e49'
gem 'devise'
```
add `devise_for :users` in `routes.rb`
`cd app`
`bundle`

and then when you do `bundle exec rails c`, there is this error :

```
/Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/actionpack/lib/action_dispatch/routing/route_set.rb:512:in 'url_helpers': routes have not been finalized. Please call 'finalize!' or use 'draw(&block)' (ActionDispatch::Routing::RouteSet::UnfinalizedRouteSet)
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.5.0/lib/devise/failure_app.rb:14:in '<class:FailureApp>'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.5.0/lib/devise/failure_app.rb:10:in '<module:Devise>'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.5.0/lib/devise/failure_app.rb:5:in '<main>'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in 'require'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in 'block in require_with_bootsnap_lfi'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in 'register'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in 'require_with_bootsnap_lfi'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in 'require'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/activesupport/lib/active_support/dependencies.rb:293:in 'block in require'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/activesupport/lib/active_support/dependencies.rb:259:in 'load_dependency'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/activesupport/lib/active_support/dependencies.rb:293:in 'require'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.5.0/lib/devise/mapping.rb:124:in 'default_failure_app'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.5.0/lib/devise/mapping.rb:69:in 'initialize'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.5.0/lib/devise.rb:346:in 'new'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.5.0/lib/devise.rb:346:in 'add_mapping'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.5.0/lib/devise/rails/routes.rb:243:in 'block in devise_for'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.5.0/lib/devise/rails/routes.rb:242:in 'each'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.5.0/lib/devise/rails/routes.rb:242:in 'devise_for'
	from /Users/nicolas/rails/alpha/app/config/routes.rb:3:in 'block in <main>'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/actionpack/lib/action_dispatch/routing/route_set.rb:433:in 'instance_exec'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/actionpack/lib/action_dispatch/routing/route_set.rb:433:in 'eval_block'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/actionpack/lib/action_dispatch/routing/route_set.rb:415:in 'draw'
	from /Users/nicolas/rails/alpha/app/config/routes.rb:1:in '<main>'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in 'load'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in 'load'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/activesupport/lib/active_support/dependencies.rb:287:in 'block in load'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/activesupport/lib/active_support/dependencies.rb:259:in 'load_dependency'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/activesupport/lib/active_support/dependencies.rb:287:in 'load'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/railties/lib/rails/application/routes_reloader.rb:41:in 'block in load_paths'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/railties/lib/rails/application/routes_reloader.rb:41:in 'each'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/railties/lib/rails/application/routes_reloader.rb:41:in 'load_paths'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/railties/lib/rails/application/routes_reloader.rb:20:in 'reload!'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/railties/lib/rails/application/routes_reloader.rb:30:in 'block in updater'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/activesupport/lib/active_support/file_update_checker.rb:83:in 'execute'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/railties/lib/rails/application/routes_reloader.rb:10:in 'execute'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/railties/lib/rails/application/finisher.rb:130:in 'block in <module:Finisher>'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/railties/lib/rails/initializable.rb:32:in 'instance_exec'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/railties/lib/rails/initializable.rb:32:in 'run'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/railties/lib/rails/initializable.rb:61:in 'block in run_initializers'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in 'block in tsort_each'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in 'block (2 levels) in each_strongly_connected_component'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in 'each_strongly_connected_component_from'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in 'block in each_strongly_connected_component'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in 'each'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in 'call'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in 'each_strongly_connected_component'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in 'tsort_each'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in 'tsort_each'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/railties/lib/rails/initializable.rb:60:in 'run_initializers'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/railties/lib/rails/application.rb:365:in 'initialize!'
	from /Users/nicolas/rails/alpha/app/config/environment.rb:5:in '<main>'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in 'require'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in 'block in require_with_bootsnap_lfi'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in 'register'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in 'require_with_bootsnap_lfi'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in 'require'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/activesupport/lib/active_support/dependencies.rb:293:in 'block in require'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/activesupport/lib/active_support/dependencies.rb:259:in 'load_dependency'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-7f870a5ba2aa/activesupport/lib/active_support/dependencies.rb:293:in 'require'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:102:in 'preload'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:153:in 'serve'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:141:in 'block in run'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in 'loop'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in 'run'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in '<top (required)>'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in 'require'
	from /Users/nicolas/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in 'require'
	from -e:1:in '<main>'
```

If you replace with the previous commit, it works
```
gem 'rails', git: 'https://github.com/rails/rails.git', ref: '05a66686f18000a1bbc35a92fe63e18218b829a5'
```

**Rails version**: 6.0.0.alpha (master)
**Ruby version**: ruby '2.5.1'

**Comment by nicolasmlv** [comment]
I close because it is the same issue https://github.com/rails/rails/issues/34050
