### ISSUE TITLE
rails db:drop in development throws misleading "destructive action in production" error

### ISSUE THREAD

**Issue by SampsonCrowley** [rails/rails#34041]
### Steps to reproduce

have a pending migration

run `rails db:drop`

### Expected behavior

It should drop the development db (or at least correctly show that it's a migration error)

### Actual behavior

it raises a pnding migration error internally (I'm assuming), but instead of displaying that, shows:

```
ActiveRecord::ProtectedEnvironmentError: You are attempting to run a destructive action against your 'production' database.
If you are sure you want to continue, run the same command with the environment variable:
DISABLE_DATABASE_ENVIRONMENT_CHECK=1
/home/samps/.gem/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:61:in `check_protected_environments!'
/home/samps/.gem/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:13:in `block (2 levels) in <main>'
/home/samps/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/samps/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/samps/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
/home/samps/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
/home/samps/.gem/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/samps/.gem/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/samps/.gem/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/samps/.gem/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/samps/.gem/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/samps/.gem/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/home/samps/.gem/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/samps/.gem/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
/home/samps/sites/downundersports.com/bin/rails:9:in `<top (required)>'
/home/samps/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/samps/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/samps/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/samps/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/samps/.gem/ruby/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/samps/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/samps/.gem/ruby/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/home/samps/sites/downundersports.com/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:drop => db:check_protected_environments
(See full trace by running task with --trace)
```

### System configuration
**Rails version**:             5.2.0

**Ruby version**:              2.5.1-p57 (x86_64-linux)

RubyGems version          2.7.7
Rack version              2.0.5
JavaScript Runtime        Node.js (V8)
Middleware                Rack::MiniProfiler, Rack::Sendfile, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, ActionDispatch::RequestId, ActionDispatch::RemoteIp, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, ActionDispatch::Reloader, ActionDispatch::Callbacks, ActiveRecord::Migration::CheckPending, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::MethodOverride, ActionDispatch::Flash, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, Bullet::Rack
Application root          /home/samps/sites/downundersports.com
Environment               development
Database adapter          postgresql
Database schema version   20180927185158

**Comment by y-yagi** [comment]
I executed `rails db:drop` with pending migration, but it was not reproducible.

```
$ ./bin/rails r "ActiveRecord::Migration.check_pending!(ActiveRecord::Base.connection)"

Traceback (most recent call last):
	18: from ./bin/rails:4:in `<main>'
	17: from /home/yaginuma/program/rails/master_y_yagi/rails/activesupport/lib/active_support/dependencies.rb:293:in `require'
	16: from /home/yaginuma/program/rails/master_y_yagi/rails/activesupport/lib/active_support/dependencies.rb:259:in `load_dependency'
	15: from /home/yaginuma/program/rails/master_y_yagi/rails/activesupport/lib/active_support/dependencies.rb:293:in `block in require'
	14: from /home/yaginuma/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	13: from /home/yaginuma/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	12: from /home/yaginuma/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	11: from /home/yaginuma/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	10: from /home/yaginuma/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	 9: from /home/yaginuma/program/rails/master_y_yagi/rails/railties/lib/rails/commands.rb:18:in `<main>'
	 8: from /home/yaginuma/program/rails/master_y_yagi/rails/railties/lib/rails/command.rb:46:in `invoke'
	 7: from /home/yaginuma/program/rails/master_y_yagi/rails/railties/lib/rails/command/base.rb:65:in `perform'
	 6: from /home/yaginuma/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	 5: from /home/yaginuma/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	 4: from /home/yaginuma/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 3: from /home/yaginuma/program/rails/master_y_yagi/rails/railties/lib/rails/commands/runner/runner_command.rb:41:in `perform'
	 2: from /home/yaginuma/program/rails/master_y_yagi/rails/railties/lib/rails/commands/runner/runner_command.rb:41:in `eval'
	 1: from /home/yaginuma/program/rails/master_y_yagi/rails/railties/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
/home/yaginuma/program/rails/master_y_yagi/rails/activerecord/lib/active_record/migration.rb:580:in `check_pending!':  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

        rails db:migrate RAILS_ENV=development 

$ ./bin/rails db:drop
Dropped database 'master_postgresql_development'
Dropped database 'master_postgresql_test'
```
 
Can you please provide a sample application that reproduces the issue?

**Comment by zieski** [comment]
I've encountered this error after restoring a production db locally. I believe it's from the value of the `ar_internal_metadata` table being set to production

Run: `bin/rails db:environment:set RAILS_ENV=development` to fix this

**Comment by SampsonCrowley** [comment]
I think @zieski nailed it. I was unaware that rails was also storing the environment in a metadata table. I periodically pull my production database into my local dev db to test that what I'm working on also will work on a mirror of current production data (not that there's any real reason it wouldn't, but it makes me sleep better)

**Comment by macmartine** [comment]
Just ran into this. This is terrifying.

**Comment by dotconde** [comment]
Thank you @zieski , worked !

**Comment by pradnyeshpatil** [comment]
You have taken production dump locally but forget to run `rails db:migrate`. so when you are running `rails db:drop` command you are getting this error.

**Comment by majedbojan** [comment]
`bin/rails db:environment:set RAILS_ENV=development` fixed the issue for me
