### ISSUE TITLE
data is not preserved in credentails.yml.enc file, in case of an error while saving it

### ISSUE THREAD

**Issue by abhinaykumar** [rails/rails#34107]
### Steps to reproduce

* `EDITOR=vim rails credentials:edit`
* add credentails (with 4 or more space indentaiton)
```
  google:
          client_id: 'xxxxx'
          client_secret: 'xxxxxx'
```
* save and exit with: `:wq`

### Expected behavior
* It should return an error and not discard the changes, until error is resolved.

### Actual behavior
* It throws error mentioned below:
```
Traceback (most recent call last):
	31: from bin/rails:3:in `<main>'
	30: from bin/rails:3:in `load'
	29: from /Users/abhinay/rails_projects/investr/bin/spring:15:in `<top (required)>'
	28: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	27: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	26: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	25: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	24: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	23: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	22: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	21: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	20: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	19: from /Users/abhinay/rails_projects/investr/bin/rails:9:in `<top (required)>'
	18: from /Users/abhinay/rails_projects/investr/bin/rails:9:in `require'
	17: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<top (required)>'
	16: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
	15: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
	14: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	13: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	12: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	11: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/credentials/credentials_command.rb:26:in `edit'
	10: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/command/helpers/editor.rb:26:in `catch_editing_exceptions'
	 9: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/credentials/credentials_command.rb:27:in `block in edit'
	 8: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/credentials/credentials_command.rb:50:in `change_credentials_in_system_editor'
	 7: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/encrypted_file.rb:54:in `change'
	 6: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/encrypted_file.rb:68:in `writing'
	 5: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/encrypted_configuration.rb:27:in `write'
	 4: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/encrypted_configuration.rb:46:in `deserialize'
	 3: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/2.5.0/psych.rb:263:in `load'
	 2: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/2.5.0/psych.rb:350:in `parse'
	 1: from /Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/2.5.0/psych.rb:402:in `parse_stream'
/Users/abhinay/.rbenv/versions/2.5.0/lib/ruby/2.5.0/psych.rb:402:in `parse': (/Users/abhinay/rails_projects/investr/config/credentials.yml.enc): found character that cannot start any token while scanning for the next token at line 9 column 1 (Psych::SyntaxError)
```
* All the changes are discarded.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.0

**Comment by y-yagi** [comment]
This is intentional behavior.  
I think that there is room for improvement about the behavior when an error occurs.
(I think that it is better to display the contents of the error rather than reopening the file)  

Anyway, that is a feature request. We don't take feature request on the issue tracker. Thanks.

**Comment by abhinaykumar** [comment]
@y-yagi,  
Would love to work on this feature, could you please point me to the place which requires the change. 
I found below method here: https://github.com/rails/rails/blob/3cac5fe94f0f81b4263cfa03d4822c05a55eb49c/railties/lib/rails/commands/credentials/credentials_command.rb#L68
``` ruby
def change_encrypted_file_in_system_editor(file_path, key_path)
    Rails.application.encrypted(file_path, key_path: key_path).change do |tmp_path|
        system("#{ENV["EDITOR"]} #{tmp_path}")
     end
end
```
but again I am not sure where exactly it should handle the errors and return appropriate message.
