### ISSUE TITLE
Non-specific error when getting classes descendants, with eager_load on

### ISSUE THREAD

**Issue by markvanlan** [rails/rails#34206]
### Steps to reproduce

Set eager_load In environment/development.rb:
`config.eager_load = true`

We have classes...
```
class Animal
end

class Cat < Animal
end
```
In Controller:
```
class AnimalsController < ApplicationController
  def action
    puts Animal.descendants
  end
end
```

### Expected behavior
=> ["Animal"]

### Actual behavior

```
ArgumentError (unknown firstpos: NilClass):
app_1      |   
app_1      | actionpack (5.2.0) lib/action_dispatch/journey/gtg/builder.rb:101:in `firstpos'
app_1      | actionpack (5.2.0) lib/action_dispatch/journey/gtg/builder.rb:24:in `transition_table'
app_1      | actionpack (5.2.0) lib/action_dispatch/journey/routes.rb:60:in `simulator'
app_1      | actionpack (5.2.0) lib/action_dispatch/journey/router.rb:99:in `simulator'
app_1      | actionpack (5.2.0) lib/action_dispatch/journey/router.rb:30:in `eager_load!'
app_1      | actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:390:in `eager_load!'
app_1      | railties (5.2.0) lib/rails/application/routes_reloader.rb:28:in `each'
app_1      | railties (5.2.0) lib/rails/application/routes_reloader.rb:28:in `execute'
app_1      | railties (5.2.0) lib/rails/application/finisher.rb:143:in `block (2 levels) in <module:Finisher>'
app_1      | activesupport (5.2.0) lib/active_support/callbacks.rb:426:in `instance_exec'
app_1      | activesupport (5.2.0) lib/active_support/callbacks.rb:426:in `block in make_lambda'
app_1      | activesupport (5.2.0) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
app_1      | activesupport (5.2.0) lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
app_1      | activesupport (5.2.0) lib/active_support/callbacks.rb:605:in `catch'
app_1      | activesupport (5.2.0) lib/active_support/callbacks.rb:605:in `block in default_terminator'
app_1      | activesupport (5.2.0) lib/active_support/callbacks.rb:199:in `block in halting'
app_1      | activesupport (5.2.0) lib/active_support/callbacks.rb:513:in `block in invoke_before'
app_1      | activesupport (5.2.0) lib/active_support/callbacks.rb:513:in `each'
app_1      | activesupport (5.2.0) lib/active_support/callbacks.rb:513:in `invoke_before'
app_1      | activesupport (5.2.0) lib/active_support/callbacks.rb:131:in `run_callbacks'
app_1      | activesupport (5.2.0) lib/active_support/execution_wrapper.rb:110:in `run!'
app_1      | activesupport (5.2.0) lib/active_support/reloader.rb:115:in `run!'
app_1      | activesupport (5.2.0) lib/active_support/execution_wrapper.rb:72:in `block in run!'
app_1      | activesupport (5.2.0) lib/active_support/execution_wrapper.rb:69:in `tap'
app_1      | activesupport (5.2.0) lib/active_support/execution_wrapper.rb:69:in `run!'
app_1      | activesupport (5.2.0) lib/active_support/reloader.rb:64:in `run!'
app_1      | actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
app_1      | actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
app_1      | web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
app_1      | web-console (3.6.2) lib/web_console/middleware.rb:22:in `block in call'
app_1      | web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
app_1      | web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
app_1      | actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
app_1      | railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
app_1      | railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
app_1      | activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
app_1      | activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
app_1      | activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
app_1      | railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
app_1      | sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
app_1      | actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
app_1      | actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
app_1      | rack (2.0.5) lib/rack/method_override.rb:22:in `call'
app_1      | rack (2.0.5) lib/rack/runtime.rb:22:in `call'
app_1      | actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
app_1      | actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
app_1      | rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
app_1      | rack-mini-profiler (1.0.0) lib/mini_profiler/profiler.rb:285:in `call'
app_1      | railties (5.2.0) lib/rails/engine.rb:524:in `call'
app_1      | puma (3.12.0) lib/puma/configuration.rb:225:in `call'
app_1      | puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
app_1      | puma (3.12.0) lib/puma/server.rb:472:in `process_client'
app_1      | puma (3.12.0) lib/puma/server.rb:332:in `block in run'
app_1      | puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.4.4p296

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?
