### ISSUE TITLE
`undef_method': undefined method `==' for class `ActiveSupport::ProxyObject' (NameError)

### ISSUE THREAD

**Issue by almapro** [rails/rails#34398]
### Steps to reproduce
`bin/rails server --port=4000`

### Expected behavior
Server should start.

### Actual behavior
Error:
```
71: from bin/rails:3:in `<main>'
	70: from bin/rails:3:in `load'
	69: from /almapro/work/rails/blog/bin/spring:15:in `<top (required)>'
	68: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	67: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	66: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	65: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	64: from /var/lib/gems/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	63: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	62: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	61: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	60: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	59: from /almapro/work/rails/blog/bin/rails:9:in `<top (required)>'
	58: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	57: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	56: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
	55: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	54: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	53: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	52: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	51: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	50: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
	49: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
	48: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
	47: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	46: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	45: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	44: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
	43: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
	42: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	41: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	40: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	39: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
	38: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	37: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	36: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	35: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	34: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	33: from /almapro/work/rails/blog/config/application.rb:7:in `<main>'
	32: from /var/lib/gems/2.5.0/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
	31: from /var/lib/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
	30: from /var/lib/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
	29: from /var/lib/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
	28: from /var/lib/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
	27: from /var/lib/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	26: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	25: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	24: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	23: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	22: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	21: from /var/lib/gems/2.5.0/gems/jbuilder-2.8.0/lib/jbuilder.rb:1:in `<main>'
	20: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	19: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	18: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
	17: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	16: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	15: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	14: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	13: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	12: from /var/lib/gems/2.5.0/gems/jbuilder-2.8.0/lib/jbuilder/jbuilder.rb:2:in `<main>'
	11: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	10: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	 9: from /var/lib/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
	 8: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	 7: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	 6: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	 5: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	 4: from /var/lib/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	 3: from /usr/lib/ruby/vendor_ruby/active_support/proxy_object.rb:1:in `<main>'
	 2: from /usr/lib/ruby/vendor_ruby/active_support/proxy_object.rb:4:in `<module:ActiveSupport>'
	 1: from /usr/lib/ruby/vendor_ruby/active_support/proxy_object.rb:5:in `<class:ProxyObject>'
/usr/lib/ruby/vendor_ruby/active_support/proxy_object.rb:5:in `undef_method': undefined method `==' for class `ActiveSupport::ProxyObject' (NameError)
Did you mean?  ===
```
From what I understand it's a re-require that's causing this! But I wasn't able to fix it.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by almapro** [comment]
I just created the app with `rails new blog`.

**Comment by rafaelfranca** [comment]
I also did and could not reproduce. So it can be something in your environment.

**Comment by almapro** [comment]
How can I identify what it is?

**Comment by rafaelfranca** [comment]
Unfortunately, I don't know. As I can't reproduce I can't tell where the problem is. I'd try to see if it is not a bug in your ruby installation by installing a new version of Ruby.

**Comment by almapro** [comment]
Currently, I'm running Kali Linux and that's scary to miss things up in this distro.
I'll fire up Fedora and give it a try.

**Comment by almapro** [comment]
Apparently, it was my environment! Running smooth on Fedora.
**Kali Linux** environment  is causing this.

**Comment by tomshy** [comment]
how do you solve this for kali linux?

**Comment by electrodragon** [comment]
Kali Linux Comes Pre install with ruby and all its components. only rails is not installed !. As its a pentesters distro, thats why they included ruby in it. Use RVM to get ROR ready and working !
