### ISSUE TITLE
Rails 5.2.2.rc1 - cannot use update_columns to update an attribute by it's alias

### ISSUE THREAD

**Issue by ccasabona** [rails/rails#34565]
### Steps to reproduce

```# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.2.rc1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :orders, force: true do |t|
    t.string :bill_to_first_name
    t.string :bill_to_last_name
  end
end

class Order < ActiveRecord::Base
  alias_attribute :first_name, :bill_to_first_name
  alias_attribute :last_name, :bill_to_last_name
end

class BugTest < Minitest::Test
  def test_association_stuff
    order = Order.create!

    order.first_name = 'John'
    order.last_name = 'Henry'
    order.save
    assert_equal 'John', order.bill_to_first_name
    assert_equal 'Henry', order.bill_to_last_name

    order.update_columns(first_name: nil, last_name: nil)
  end
end
```
```BugTest#test_association_stuff:
ActiveModel::MissingAttributeError: can't write unknown attribute `first_name`
    /Users/charlie/.rvm/gems/ruby-2.5.3@ruby253rails52/gems/activemodel-5.2.2.rc1/lib/active_model/attribute.rb:207:in `with_value_from_database'
    /Users/charlie/.rvm/gems/ruby-2.5.3@ruby253rails52/gems/activemodel-5.2.2.rc1/lib/active_model/attribute_set.rb:61:in `write_cast_value'
    /Users/charlie/.rvm/gems/ruby-2.5.3@ruby253rails52/gems/activerecord-5.2.2.rc1/lib/active_record/attribute_methods/write.rb:58:in `write_attribute_without_type_cast'
    /Users/charlie/.rvm/gems/ruby-2.5.3@ruby253rails52/gems/activerecord-5.2.2.rc1/lib/active_record/attribute_methods/dirty.rb:124:in `write_attribute_without_type_cast'
    /Users/charlie/.rvm/gems/ruby-2.5.3@ruby253rails52/gems/activerecord-5.2.2.rc1/lib/active_record/persistence.rb:476:in `block in update_columns'
    /Users/charlie/.rvm/gems/ruby-2.5.3@ruby253rails52/gems/activerecord-5.2.2.rc1/lib/active_record/persistence.rb:475:in `each'
    /Users/charlie/.rvm/gems/ruby-2.5.3@ruby253rails52/gems/activerecord-5.2.2.rc1/lib/active_record/persistence.rb:475:in `update_columns'
    update_columns_issue.rb:45:in `test_association_stuff'

```
The update_columns method has worked using aliased attributes in previous versions of Rails.  I have received this error in test and development environments.

When using update_columns to change an attribute using the aliased name, the attribute should be change without an exception.
### Actual behavior

An exception is generated:  ActiveModel::MissingAttributeError: can't write unknown attribute 
### System configuration
**Rails version**:
5.2.2.rc1
**Ruby version**:
ruby 2.5.3p105

**Comment by Edouard-chin** [comment]
related to rails/rails@https://github.com/rails/rails/commit/7a183bd5ca8520a2c7d86d137bd087d61c911893

**Comment by utilum** [comment]
I can reproduce this on master as well.
