### ISSUE TITLE
Possible concurrency issue in active record associations

### ISSUE THREAD

**Issue by ashu210890** [rails/rails#34615]
### Steps to reproduce
The setup goes something like this:
```
class Account < ApplicationRecord
   has_and_belongs_to_many :tags

  def add_tag(tag)
      self.tags << tag
  end
end

class Tag < ApplicationRecord
  has_and_belongs_to_many :accounts
end

acc = Account.new
acc.save!
tag = Tag.new
tag.save!
acc.add_tag(tag)

```
The above runs in multiple threads where `acc.add_tag` can be called for the same account and different tags.

### Expected behavior
The expected behaviour is that this should work properly and all the tags should be applied to the given account. 

### Actual behavior
The following stacktrace shows up intermittently:
```
NoMethodError: undefined method `<' for nil:NilClass

/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:425:in `clear_transaction_record_state', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:498:in `update_attributes_from_transaction_state', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:491:in `sync_with_transaction_state', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:232:in `new_record?', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:292:in `null_scope?', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:287:in `scope', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/association.rb:191:in `scope_for_create', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/association.rb:176:in `initialize_attributes', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/association.rb:277:in `block in build_record', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/core.rb:316:in `initialize', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/inheritance.rb:66:in `new', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/reflection.rb:154:in `build_association', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/association.rb:276:in `build_record', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:106:in `build', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/has_many_through_association.rb:60:in `build_through_record', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/has_many_through_association.rb:82:in `save_through_record', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/has_many_through_association.rb:45:in `insert_record', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:438:in `block in concat_records', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:458:in `replace_on_target', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:282:in `add_to_target', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:436:in `block in concat_records', 
org/jruby/RubyArray.java:1789:in `each', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:434:in `concat_records', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/has_many_association.rb:116:in `concat_records', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/has_many_through_association.rb:27:in `concat_records', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:119:in `block in concat', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:134:in `block in transaction', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction', 
/home/deploy/.rvm/rubies/jruby-9.2.3.0/lib/ruby/stdlib/monitor.rb:226:in `mon_synchronize', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:133:in `transaction', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:119:in `concat', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/has_many_through_association.rb:21:in `concat', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_proxy.rb:1056:in `<<',
/home/deploy/myapp/app/models/account.rb:6:in `add_tag',
...

```

We often see similar issues with activerecord on jruby where a simple `belongs_to` relationship yields `nil` response when resolved even if the  association actually exists. The above error could be of a similar flavour but much more frequent.

### System configuration
**Rails version**:
5.2.1
**Ruby version**:
2.5.1
engine: jruby
jruby-version: 9.2.3.0

**Comment by ashu210890** [comment]
Any clues or ideas to debug this? We have been seeing this quite often in production.

**Comment by anmolarora** [comment]
We're able to reproduce the issue.

### Steps to reproduce
I've used [parallel](https://github.com/grosser/parallel) gem for running code in multiple threads

```ruby
@account = Account.first
tasks = []

10000.times.each do
  tasks << Proc.new do
    j = @account.name
  end
end
10000.times.each do
  tasks << Proc.new do
    @account.update!(name: 'random')
  end
end

Parallel.each(tasks.shuffle, in_threads: 6) do |task|
  task.call
end; nil
```


### Expected Behaviour
No error

### Actual behaviour
```
NoMethodError: undefined method `<' for nil:NilClass

/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:425:in `clear_transaction_record_state', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:498:in `update_attributes_from_transaction_state', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:491:in `sync_with_transaction_state', 
/home/deploy/.rvm/gems/jruby-9.2.3.0/gems/activerecord-5.2.1/lib/active_record/attribute_methods/primary_key.rb:19:in `id'
```

**Comment by rafaelfranca** [comment]
Rails don't support sharing the same instance of ActiveRecord::Base between two threads. This can't be safe since any state inside that object would need to have need a mutex.

**Comment by rafaelfranca** [comment]
Yes. `ActiveRecord::Base` instances should not be shared between threads. See https://github.com/rails/rails/issues/22431#issuecomment-161004532
