### ISSUE TITLE
Rails 6 master - callback :verify_authenticity_token has not been defined

### ISSUE THREAD

**Issue by haberbyte** [rails/rails#34837]
Running Rails 6 master in production environment I run into the following error:

```
a426615fb178/actionmailbox/app/controllers/action_mailbox/base_controller.rb:3:in `<main>'
	 14: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/actionmailbox/app/controllers/action_mailbox/base_controller.rb:5:in `<module:ActionMailbox>'
	 13: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/actionmailbox/app/controllers/action_mailbox/base_controller.rb:6:in `<class:BaseController>'
	 12: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/actionpack/lib/action_controller/metal/request_forgery_protection.rb:150:in `skip_forgery_protection'
	 11: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/actionpack/lib/abstract_controller/callbacks.rb:214:in `block (2 levels) in <module:ClassMethods>'
	 10: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/actionpack/lib/abstract_controller/callbacks.rb:95:in `_insert_callbacks'
	  9: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/actionpack/lib/abstract_controller/callbacks.rb:95:in `each'
	  8: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/actionpack/lib/abstract_controller/callbacks.rb:96:in `block in _insert_callbacks'
	  7: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/actionpack/lib/abstract_controller/callbacks.rb:215:in `block (3 levels) in <module:ClassMethods>'
	  6: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/activesupport/lib/active_support/callbacks.rb:705:in `skip_callback'
	  5: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/activesupport/lib/active_support/callbacks.rb:626:in `__update_callbacks'
	  4: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/activesupport/lib/active_support/callbacks.rb:626:in `reverse_each'
	  3: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/activesupport/lib/active_support/callbacks.rb:628:in `block in __update_callbacks'
	  2: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/activesupport/lib/active_support/callbacks.rb:706:in `block in skip_callback'
	  1: from /Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/activesupport/lib/active_support/callbacks.rb:706:in `each'
/Users/jan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-a426615fb178/activesupport/lib/active_support/callbacks.rb:710:in `block (2 levels) in skip_callback': Before process_action callback :verify_authenticity_token has not been defined (ArgumentError)
```

The error disappears when i remove this line:

https://github.com/rails/rails/blob/d9630c4815c60f87e91361f578e53e8d987ad0ae/actionmailbox/app/controllers/action_mailbox/base_controller.rb#L6

Is this line correct? If BaseController inherits from ActionController::Base directly there should not be forgery protection anyways?

/CC @georgeclaghorn

**Comment by georgeclaghorn** [comment]
> If BaseController inherits from ActionController::Base directly there should not be forgery protection anyways?

Forgery protection is applied by default as of 5.2. Is this an old app (pre-5.2) that has been upgraded? What’s the value of `ActionController::Base.default_protect_from_forgery`?

**Comment by haberbyte** [comment]
Oh, i was missing the ``config.load_defaults`` in application.rb, so ``default_protect_from_forgery`` was set to false. It is working now...

I think this can be closed then, thank you for the quick help and sorry for the trouble.

**Comment by georgeclaghorn** [comment]
I’m going to reopen this because Action Mailbox shouldn’t break apps where that option is false.

**Comment by i2chris** [comment]
FWIW, this broke my app too

**Comment by olegantonyan** [comment]
Is there a way to disable actionmailbox? I don't need it and don't want to deal with bugs introduced by it

**Comment by ogdenstudios** [comment]
I had this issue in a Rails 5.1 app I upgraded 5.1 to 5.2 to 6 beta3. Ran fine in development, passed my test suite, built and deployed to Heroku, but crashed on the first request. 

I fixed it by setting:
`config.action_controller.default_protect_from_forgery = true` in `config/application.rb`

**Comment by sonianand11** [comment]
I have upgraded my Rails 4 to Rails 6 and I was facing this issue.
Modifying `config.load_defaults 5.0` to `config.load_defaults 6.0` in `config/application.rb` works for me

Thank you @haberbyte
