### ISSUE TITLE
Rails 6.0.0alpha - routing constraints differ in than Rails 5.2.2

### ISSUE THREAD

**Issue by btihen** [rails/rails#34854]
### Steps to reproduce

in the below text - I can start rails 6.0.0alpha  -- with two constraints within the same resource (with one it works fine).  

* if I only use ONE of my two constraints rails 6.0.0 alpha starts
* if I use BOTH of my below constraints I get the error.

This code works in Rails 5.2.2 - this is of course not so urgent - I'm just testing rails 6 with an existing app.

```
Rails.application.routes.draw do
  authenticated :user do
    root 'initiatives#index', as: :authenticated_root
  end
  resources :initiatives, except: [:destroy] do
    root 'initiatives#contacted', constraints: { query_string: /list=contacted_list/ }
    root 'initiatives#sponsored', constraints: { query_string: /list=sponsored_list/ }
    resources :contacts,  only: [:new, :create]
  end
end
```

### Expected behavior

I expect to have routing constraints in Rails 6.0.0alpha to work similar to Rails 5.2.2 

This code works in rails 5.2.2 - is there something new I need to do to use constraints (should I not use contraints in Rails 6?

### Actual behavior

=> Booting Puma
=> Rails 6.0.0.alpha application starting in development 
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	101: from bin/rails:29:in `<main>'
	100: from bin/rails:29:in `load'
	 99: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/exe/rails:10:in `<top (required)>'
	 98: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/exe/rails:10:in `require'
	 97: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/cli.rb:7:in `<top (required)>'
	 96: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/app_loader.rb:48:in `exec_app'
	 95: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/app_loader.rb:48:in `loop'
	 94: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/app_loader.rb:59:in `block in exec_app'
	 93: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/activesupport/lib/active_support/dependencies.rb:297:in `require'
	 92: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
	 91: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/activesupport/lib/active_support/dependencies.rb:297:in `block in require'
	 90: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	 89: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	 88: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	 87: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	 86: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	 85: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/commands.rb:18:in `<main>'
	 84: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/command.rb:46:in `invoke'
	 83: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/command/base.rb:65:in `perform'
	 82: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 81: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 80: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 79: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/commands/server/server_command.rb:149:in `perform'
	 78: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/commands/server/server_command.rb:149:in `tap'
	 77: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/commands/server/server_command.rb:158:in `block in perform'
	 76: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/commands/server/server_command.rb:49:in `start'
	 75: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	 74: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
	 73: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/commands/server/server_command.rb:26:in `app'
	 72: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
	 71: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	 70: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
	 69: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
	 68: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
	 67: from config.ru:in `<main>'
	 66: from config.ru:in `new'
	 65: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
	 64: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
	 63: from config.ru:3:in `block in <main>'
	 62: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
	 61: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/activesupport/lib/active_support/dependencies.rb:297:in `require'
	 60: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
	 59: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/activesupport/lib/active_support/dependencies.rb:297:in `block in require'
	 58: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	 57: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	 56: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	 55: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	 54: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	 53: from /Users/btihen/Dropbox/devel/ruby/innclass/config/environment.rb:5:in `<main>'
	 52: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/application.rb:367:in `initialize!'
	 51: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/initializable.rb:60:in `run_initializers'
	 50: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	 49: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	 48: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	 47: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `call'
	 46: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each'
	 45: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	 44: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 43: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 42: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	 41: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
	 40: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/initializable.rb:32:in `run'
	 39: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/initializable.rb:32:in `instance_exec'
	 38: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/application/finisher.rb:130:in `block in <module:Finisher>'
	 37: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/application/routes_reloader.rb:10:in `execute'
	 36: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/activesupport/lib/active_support/file_update_checker.rb:83:in `execute'
	 35: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/application/routes_reloader.rb:30:in `block in updater'
	 34: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/application/routes_reloader.rb:20:in `reload!'
	 33: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/application/routes_reloader.rb:41:in `load_paths'
	 32: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/application/routes_reloader.rb:41:in `each'
	 31: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/railties/lib/rails/application/routes_reloader.rb:41:in `block in load_paths'
	 30: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/activesupport/lib/active_support/dependencies.rb:291:in `load'
	 29: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
	 28: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/activesupport/lib/active_support/dependencies.rb:291:in `block in load'
	 27: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 26: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 25: from /Users/btihen/Dropbox/devel/ruby/innclass/config/routes.rb:14:in `<main>'
	 24: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/route_set.rb:413:in `draw'
	 23: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/route_set.rb:431:in `eval_block'
	 22: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/route_set.rb:431:in `instance_exec'
	 21: from /Users/btihen/Dropbox/devel/ruby/innclass/config/routes.rb:41:in `block in <main>'
	 20: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1457:in `resources'
	 19: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1722:in `with_scope_level'
	 18: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1459:in `block in resources'
	 17: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1730:in `resource_scope'
	 16: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:897:in `controller'
	 15: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1730:in `block in resource_scope'
	 14: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1460:in `block (2 levels) in resources'
	 13: from /Users/btihen/Dropbox/devel/ruby/innclass/config/routes.rb:49:in `block (2 levels) in <main>'
	 12: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1646:in `root'
	 11: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1722:in `with_scope_level'
	 10: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1647:in `block in root'
	  9: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1842:in `path_scope'
	  8: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1648:in `block (2 levels) in root'
	  7: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1947:in `match_root_route'
	  6: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1619:in `match'
	  5: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1871:in `map_match'
	  4: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1871:in `each'
	  3: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1877:in `block in map_match'
	  2: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1913:in `decomposed_match'
	  1: from /Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/mapper.rb:1942:in `add_route'
/Users/btihen/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-6f0cda8f8e20/actionpack/lib/action_dispatch/routing/route_set.rb:583:in `add_route': Invalid route name, already in use: 'initiatives_root'  (ArgumentError)
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
https://guides.rubyonrails.org/routing.html#restricting-the-routes-created

### System configuration
**Rails version**: Rails 6.0.0alpha - as of Jan 3 17:30 EU time -- I believe as of commit: 6f0cda8f8e208143cbd3b39e786521c2e5cddb7a

**Ruby version**: 2.6.0

Perhaps I have conflicting gem file:
```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.0'
gem 'rails', github: 'rails/rails', branch: 'master'

gem 'pg', '>= 0.18', '< 2.0'
gem 'pg_search'

gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'webpacker'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
gem 'active_model_serializers'

gem 'administrate'

# gem 'devise', '~> 4.4'
gem 'devise', git: 'https://github.com/plataformatec/devise'

gem 'countries'       #, require: 'countries/global'
gem 'country_select', '~> 3.1'
gem 'bootsnap', '>= 1.1.0', require: false

gem 'react-rails'

group :test do
  gem 'cucumber-rails', require: false
  gem 'rspec-expectations'
  gem 'database_cleaner'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'email_spec'

  gem 'simplecov'
  gem 'simplecov-console'
end

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'factory_bot_rails', '~> 4.10'
  gem 'rspec-rails', '~> 3.7'
  gem 'rails-controller-testing'
  gem 'faker', '~> 1.8'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'report_builder'
  gem 'brakeman'
  gem 'rails-erd'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by albertoalmagro** [comment]
Good afternoon @btihen , instead of using `root` you may use `get` as I show you below.

```ruby
Rails.application.routes.draw do
  resources :initiatives, except: [:destroy] do
    get 'contacted', to: 'initiatives#contacted', constraints: { query_string: /list=contacted_list/ }
    get 'sponsored', to: 'initiatives#sponsored', constraints: { query_string: /list=sponsored_list/ }
    resources :contacts,  only: [:new, :create]
  end
end
```
Using route twice within the same context is what is causing the error `Invalid route name, already in use: 'initiatives_root' (ArgumentError)`. You can find more hints about using root [here](https://guides.rubyonrails.org/routing.html#using-root).

@rafaelfranca I think they way Rails 6 works now is the way it should be, before `initiatives_root` was silently overridden. I have reproduced this behavior on Rails 5.0.7, as well as on Rails 5.2.2. I have further investigated this and was added [here](https://github.com/rails/rails/commit/dde9c488398293fb1cbdc02595b8c4e9860b03cc). Should we back port this?

Thanks

**Comment by albertoalmagro** [comment]
Well, let me partially answer myself, if it's going to be a new release for Rails 5.2, and I think it will, there is no need to backport it.

**Comment by btihen** [comment]
Thanks - I'll rewrite my code and give rails 6 another try

**Comment by btihen** [comment]
Hmmm - this solution breaks quite a few tests -- it changes my routes and breaks my tests (of course)
previously I had the routes:
```
authenticated_root GET    /                                        initiatives#index
                 initiatives GET    /initiatives(.:format)       initiatives#index
```
and then my constraints routed /initiatives with various parameters to correct methods in the controller.

Now I have the following routes:
```
authenticated_root GET    /                                     initiatives#index
        initiatives_root GET    /initiatives(.:format)    initiatives#contacted
                                  GET    /initiatives(.:format)    initiatives#sponsored
```
**what _(I think)_ I am trying to accomplish is the same as before or:
```
authenticated_root GET    /                                     initiatives#index
                initiatives GET    /initiatives(.:format)     initiatives#index
                                 GET    /initiatives(.:format)     initiatives#contacted
                                 GET    /initiatives(.:format)     initiatives#sponsored
```
And then have the constraints help me keep my controller logic simple.

Can I still use constraints or should I find another solution?
