### ISSUE TITLE
The direct method can't be used inside a routes scope block

### ISSUE THREAD

**Issue by almirpask** [rails/rails#34872]
### Overview
Im trying to update my application from Rails 5.1.3 to Rails 5.2.2 but after update the gems i got a error when i try to run the rails server.
### Steps to reproduce
My gemfile is like this:
```
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.0"

# rails
gem 'rails', '~> 5.2.2'

# api
gem 'grape', '1.1.0'
gem 'roar', git: 'https://github.com/apotonick/roar.git'
gem 'representable', git: 'https://github.com/apotonick/representable.git'
gem 'grape-roar'
gem 'grape-swagger-representable'
gem 'grape-swagger', '0.26.0'
gem 'doorkeeper'
gem 'doorkeeper-i18n'
gem 'doorkeeper-jwt'
gem 'rack-oauth2'
gem 'swagger-ui_rails', git: 'https://github.com/audionerd/swagger-ui_rails.git'
gem 'wine_bouncer'
# improve json response on json serialization
# see more on: https://github.com/GoodLife/rails-patch-json-encode/issues/4
gem 'rails-patch-json-encode'
gem 'oj'
gem 'devise_saml_authenticatable'
# smaritano worker - do not remove!
# gem 'tiny_tds', git: "https://github.com/rails-sqlserver/tiny_tds.git", ref: "63da8be67b9f3f04584931d515d202df59e2c091"

# TODO:
# this has to be this version, cuz it bring react 0.14,
# that's the one we want to keep supporting IE8
# maybe will be necessary to maintain our own fork
# given that there is a deprecation warning in tests
# saying that there is a method call that is deprecated
# and will be removed in rails 5.1
# gem 'react-rails', '1.6.2'
# gem 'sprockets-coffee-react'
gem 'react-rails', '2.4.4'
# TODO: check http://coffeescript.org/v2/#jsx

gem 'sprockets-coffee-jsx'
gem 'activejob'

#Boot large Ruby/Rails apps faster
gem 'bootsnap', require: false
#Webpacker
gem 'webpacker', '~> 3.5'
# routes
gem 'js-routes'
gem 'breadcrumbs_on_rails'
gem 'friendly_id'

# database
gem 'pg', '0.21'
gem 'baby_squeel'
gem 'active_record_union'
gem 'scenic', '1.4.1'

# authentication
gem 'devise'

#xls reports
gem 'axlsx', git: 'https://github.com/randym/axlsx.git', branch: 'master'
gem 'axlsx_rails'
gem 'spreadsheet'
gem 'rubyzip'
gem 'rubyXL'
gem 'roo'

# views
gem 'hamlit'
gem 'slim-rails'
gem 'will_paginate'
gem 'gon'
gem 'rabl-rails'
gem 'coffee-rails'
gem 'kaminari'
gem 'kaminari-bootstrap'
gem 'pjax_rails', git: 'https://github.com/rails/pjax_rails.git'
gem 'polymer-rails'
gem 'kramdown'

# uploads
gem 'carrierwave', '0.11.2'
gem 'mini_magick'
gem 'fog', '1.38.0'
gem 'remotipart'
gem 'paperclip'
gem 'aws-sdk-s3', '~> 1'

# versioning and auditing
gem 'paper_trail'

# importing
gem 'workbook', git: 'https://github.com/murb/workbook.git', ref: '301a80672cd446069bdea95240469f64b4e9d6c5'
gem 'activerecord-import', '~> 0.4'

# sidekiq
gem 'sidekiq'
gem 'sidekiq-status'
gem 'sinatra', :require => nil
gem 'sidekiq-grouping'

# URIs and HTTP
gem 'addressable', :require => 'addressable/uri'
gem 'active_link_to'

# multi-tenancy
# TODO: pay attention to use the next v0.26.0 or later version
gem 'apartment', '~> 1.1'
gem 'apartment-sidekiq', '~> 1.0'
gem 'request_store'

# policies e roles
gem 'pundit'

# skylight
gem 'skylight', '~> 3.1.2'

# redirects
gem 'rack-rewrite', :require => false
gem 'rack-ssl', :require => 'rack/ssl'

# general
gem 'unicode'
gem 'chainable_methods'
gem 'recaptcha', '3.3.0', require: 'recaptcha/rails'

group :development do
  gem "brakeman", :require => false
  gem 'i18n-tasks', '~> 0.9.18'
end

# enumerations
gem 'enumerate_it'

group :development, :test do
  gem 'awesome_print'
  gem 'bullet'
  gem 'dotenv-rails'
  gem 'parallel_tests'
  gem 'thin'
  gem 'zeus'
  gem 'spring'
  gem 'rubocop', '0.60.0'
  gem 'jasmine'
  gem 'letter_opener'
  gem 'rails-erd'
  gem 'minitest-around'
  gem 'spy'
end

group :pry do
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-suite'
  gem 'pry-byebug'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'minitest'
  gem 'poltergeist'
  gem 'selenium-webdriver'
  gem 'test_notifier'
  gem 'timecop'
  gem 'rubocop-rspec', '1.30.1'
end

group :production do
  gem 'rack-google-analytics', :require => 'rack/google-analytics'
  gem 'rack-protection'
  gem 'rack-timeout', require: "rack/timeout/base"
  gem 'foreman'
  gem 'airbrake', '~> 5.0'
  gem 'puma', '~> 3.11'
end

# assets
gem 'jquery-rails'
gem 'asset_sync','~> 2.6', :require => false
gem 'uglifier'
gem 'sass'
gem 'sass-rails'
gem 'bootstrap-sass'

# general
gem 'celluloid',    git: 'https://github.com/celluloid/celluloid.git'
gem 'coffee-script'
gem 'phantomjs'
gem 'coffee-script-source'
gem 'columnize'
gem 'connection_pool'
gem 'execjs'
gem 'formatador'
gem 'fssm'
gem 'i18n'
gem 'net-scp'
gem 'net-ssh'
gem 'nokogiri'
gem 'mini_portile'
gem 'polyglot'
gem 'rake'
gem 'rchardet'
gem 'redis-namespace'
gem 'redis'
gem 'slop'
gem 'thread_safe'
gem 'timers'
gem 'tzinfo'
gem 'uuidtools'
gem 'xml-simple'
```

### Expected behavior

The server ups without errors

### Actual behavior

I got a `The direct method can't be used inside a routes scope block` error and the server does not up.
Here the full error log:

```
Exiting
Traceback (most recent call last):
        92: from bin/rails:3:in `<main>'
        91: from bin/rails:3:in `load'
        90: from /Users/almirsantosfilho/Documents/GitHub/umanni_hr/bin/spring:15:in `<top (required)>'
        89: from /Users/almirsantosfilho/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        88: from /Users/almirsantosfilho/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        87: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in`<top (required)>'
        86: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in`load'
        85: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        84: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        83: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        82: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        81: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        80: from /Users/almirsantosfilho/Documents/GitHub/umanni_hr/bin/rails:9:in `<top (required)>'
        79: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
        78: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        77: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
        76: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        75: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        74: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        73: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        72: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        71: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<main>'
        70: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
        69: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform'
        68: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        67: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        66: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        65: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `perform'
        64: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `tap'
        63: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        62: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:51:in `start'
        61: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
        60: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
        59: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:27:in `app'
        58: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
        57: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        56: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
        55: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
        54: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
        53: from config.ru:in `<main>'
        52: from config.ru:in `new'
        51: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
        50: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
        49: from config.ru:3:in `block in <main>'
        48: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
        47: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        46: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
        45: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        44: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/skylight-core-3.1.2/lib/skylight/core/probes.rb:119:in `require'
        43: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        42: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        41: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        40: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        39: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        38: from /Users/almirsantosfilho/Documents/GitHub/umanni_hr/config/environment.rb:5:in `<main>'
        37: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
        36: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
        35: from /Users/almirsantosfilho/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        34: from /Users/almirsantosfilho/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        33: from /Users/almirsantosfilho/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        32: from /Users/almirsantosfilho/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `call'
        31: from /Users/almirsantosfilho/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each'
        30: from /Users/almirsantosfilho/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        29: from /Users/almirsantosfilho/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        28: from /Users/almirsantosfilho/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        27: from /Users/almirsantosfilho/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        26: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        25: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
        24: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
        23: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:130:in `block in <module:Finisher>'
        22: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application/routes_reloader.rb:10:in `execute'
        21: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/file_update_checker.rb:83:in `execute'
        20: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application/routes_reloader.rb:30:in `block in updater'
        19: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application/routes_reloader.rb:20:in `reload!'
        18: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application/routes_reloader.rb:41:in `load_paths'
        17: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application/routes_reloader.rb:41:in `each'
        16: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application/routes_reloader.rb:41:in `block in load_paths'
        15: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
        14: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        13: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
        12: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/zeus-0.15.14/lib/zeus/load_tracking.rb:74:in `load'
        11: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/zeus-0.15.14/lib/zeus/load_tracking.rb:82:in `load'
        10: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
         9: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
         8: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/activestorage-5.2.2/config/routes.rb:3:in `<main>'
         7: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:414:in `draw'
         6: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:430:in `eval_block'
         5: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/mapper.rb:640:in `with_default_scope'
         4: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/mapper.rb:879:in `scope'
         3: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/mapper.rb:641:in `block in with_default_scope'
         2: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/mapper.rb:641:in `instance_exec'
         1: from /Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/activestorage-5.2.2/config/routes.rb:6:in `block in <main>'
/Users/almirsantosfilho/.rvm/gems/ruby-2.6.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/mapper.rb:2099:in `direct': The direct method can't be used inside a routes scope block (RuntimeError)
```
### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.6.0

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?  
This error occurs during routes definition. Therefore, routes.rb is necessary for investigation.

**Comment by almirpask** [comment]
I figured out what was causing the problem. On my config/application.rb i just remove the `isolate_namespace`
