### ISSUE TITLE
Bug report template for action_text

### ISSUE THREAD

**Issue by hahmed** [rails/rails#35200]
### Steps to reproduce
I'm trying to create a bug report template for action text, that will help me to reproduce another issue I was looking at, however I'm getting an error with my template, a method missing error for `has_rich_text` - any idea on how I can fix this?

Thanks!

```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "actiontext"
  gem "sqlite3", '~> 1.3.6'
  gem 'pry'
end

require 'active_record'
require "action_text"
require 'minitest/autorun'
require 'logger'
require 'pry'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :pirates do |t|
    t.string :name
    t.integer :age
  end

  create_table :ships do |t|
    t.string :title
    t.integer :pirate_id
  end

  create_table :action_text_rich_texts do |t|
    t.string     :name, null: false
    t.text       :body, size: :long
    t.references :record, null: false, polymorphic: true, index: false

    t.timestamps

    t.index [ :record_type, :record_id, :name ], name: "index_action_text_rich_texts_uniqueness", unique: true
  end
end

class Pirate < ActiveRecord::Base
  has_many :ships
  has_rich_text :content
  has_rich_text :body
end

class Ship < ActiveRecord::Base
  belongs_to :pirate
  has_rich_text :content
  has_rich_text :body
end

class BugTest < Minitest::Test
  def test_assert
    black_belly = Pirate.create(name: 'Black Belly')
    blue_ear = Pirate.create(name: 'Blue Ear')

    juming_jacobin = Ship.create(title: "Jumpin' Jacobin", pirate: black_belly, content: 'hello')
    assert juming_jacobin
  end
end

```

I call the code above using:

```
rails_issues % ruby action_text_update.rb

Fetching gem metadata from https://rubygems.org/..........

Resolving dependencies...

Using builder 3.2.3

Using erubi 1.8.0

Using mini_portile2 2.4.0

Using minitest 5.11.3

Using concurrent-ruby 1.1.4

Using thread_safe 0.3.6

Using crass 1.0.4

Using bundler 2.0.1

Using coderay 1.1.2

Using sqlite3 1.3.13

Using i18n 1.5.3

Using nokogiri 1.10.1

Using rack 2.0.6

Using loofah 2.2.3

Using rack-test 1.1.0

Using rails-html-sanitizer 1.0.4

Using tzinfo 1.2.5

Using method_source 0.9.2

Using activesupport 6.0.0.beta1

Using pry 0.12.2

Using rails-dom-testing 2.0.3

Using activemodel 6.0.0.beta1

Using actionview 6.0.0.beta1

Using activerecord 6.0.0.beta1

Using actionpack 6.0.0.beta1

Using mimemagic 0.3.3

Using marcel 0.3.3

Using activestorage 6.0.0.beta1

Using actiontext 6.0.0.beta1

-- create_table(:pirates)

D, [2019-02-07T20:46:11.131871 #30126] DEBUG -- :    (8.2ms)  SELECT sqlite_version(*)

D, [2019-02-07T20:46:11.133254 #30126] DEBUG -- :    (0.7ms)  CREATE TABLE "pirates" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "age" integer)

   -> 0.0209s

-- create_table(:ships)

D, [2019-02-07T20:46:11.133650 #30126] DEBUG -- :    (0.1ms)  CREATE TABLE "ships" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar, "pirate_id" integer)

   -> 0.0003s

-- create_table(:action_text_rich_texts)

D, [2019-02-07T20:46:11.134066 #30126] DEBUG -- :    (0.1ms)  CREATE TABLE "action_text_rich_texts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "body" text, "record_type" varchar NOT NULL, "record_id" integer NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)

D, [2019-02-07T20:46:11.134518 #30126] DEBUG -- :    (0.1ms)  CREATE UNIQUE INDEX "index_action_text_rich_texts_uniqueness" ON "action_text_rich_texts" ("record_type", "record_id", "name")

   -> 0.0008s

D, [2019-02-07T20:46:11.188040 #30126] DEBUG -- :    (0.4ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)

D, [2019-02-07T20:46:11.208708 #30126] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.2ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]

D, [2019-02-07T20:46:11.212453 #30126] DEBUG -- :    (0.0ms)  begin transaction

D, [2019-02-07T20:46:11.212714 #30126] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.1ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "default_env"], ["created_at", "2019-02-07 20:46:11.212114"], ["updated_at", "2019-02-07 20:46:11.212114"]]

D, [2019-02-07T20:46:11.212883 #30126] DEBUG -- :    (0.0ms)  commit transaction

Traceback (most recent call last):

	2: from action_text_update.rb:48:in `<main>'

	1: from action_text_update.rb:50:in `<class:Pirate>'

/Users/haroon/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.beta1/lib/active_record/dynamic_matchers.rb:22:in method_missing: undefined method 'has_rich_text' for Pirate(id: integer, name: string, age: integer):Class (NoMethodError)

```

### Expected behavior
I should be able to save some content into action_text.

### Actual behavior
I'm getting the method_missing error for `has_rich_text`

### System configuration
**Ruby version**:
2.6.0

**Comment by composerinteralia** [comment]
You may need to

```rb
include ActionText::Attribute
```

into Active Record like we do in the [ActionText Engine](https://github.com/rails/rails/blob/87a5b5d023cf785d89cf0abd3e78e3084b6af02d/actiontext/lib/action_text/engine.rb#L17)

**Comment by hahmed** [comment]
Yep, I tried that after `require 'pry'` I added;

```
ActiveSupport.on_load(:active_record) do
  include ActionText::Attribute
end
```

and got the error `NameError: uninitialized constant Ship::ActionText::RichText`

**Comment by abhaynikam** [comment]
@hahmed : I tried building the script but it has too many dependencies to be satisfied for bug script to work. I was able to resolve `NameError: uninitialized constant Ship::ActionText::RichText` by adding `require "action_text/../../app/models/action_text/rich_text"`(other ways did not work while trying to require models) but it kept on needing other things to work. 

As Rails autoloads models, it is difficult to load all the necessary files in the ruby script. Tried `zeitwerk` also 😄  but I could not figure it out. 

Maybe `ActiveSupport::Dependencies.autoload_paths` this can do but not sure how to give paths to the files. 

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_support"
require "action_text"
require "active_record"
require "active_storage/reflection"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

require "active_storage/attached"
ActiveSupport.on_load(:active_record) do
  include ActiveStorage::Attached::Model
  include ActiveStorage::Reflection::ActiveRecordExtensions
  ActiveRecord::Reflection.singleton_class.prepend(ActiveStorage::Reflection::ReflectionExtension)

  require "action_text/../../app/models/action_text/rich_text"
  require "active_storage/../../app/models/active_storage/blob"
  include ActionText::Attribute
end

ActiveRecord::Schema.define do
  create_table :action_text_rich_texts do |t|
    t.string     :name, null: false
    t.text       :body, size: :long
    t.references :record, null: false, polymorphic: true, index: false

    t.timestamps

    t.index [ :record_type, :record_id, :name ], name: "index_action_text_rich_texts_uniqueness", unique: true
  end

  create_table :active_storage_blobs do |t|
    t.string   :key,        null: false
    t.string   :filename,   null: false
    t.string   :content_type
    t.text     :metadata
    t.bigint   :byte_size,  null: false
    t.string   :checksum,   null: false
    t.datetime :created_at, null: false

    t.index [ :key ], unique: true
  end

  create_table :active_storage_attachments do |t|
    t.string     :name,     null: false
    t.references :record,   null: false, polymorphic: true, index: false
    t.references :blob,     null: false

    t.datetime :created_at, null: false

    t.index [ :record_type, :record_id, :name, :blob_id ], name: "index_active_storage_attachments_uniqueness", unique: true
    t.foreign_key :active_storage_blobs, column: :blob_id
  end

  create_table :posts, force: true do |t|
    t.string :title
    t.string :content
  end
end

class Post < ActiveRecord::Base
  has_rich_text :content
end


class BugTest < Minitest::Test
  def test_stuff
    post = Post.create!(content: "Hello World")

    assert_equal "Hello World", post.content.to_plain_text
  end
end
```

Currently, above script is failing `No such file to load -- active_storage/blob/analyzable.rb (LoadError)`

**Comment by fxn** [comment]
These tests do not seem to launch Rails, don't they. If that is right, then you can eliminate the autoloading variable because the Rails components do not autoload using AS autoloading. They have some (decorated) `Module#autoload` calls.

That might point to a legit missing `require`.

**Comment by hahmed** [comment]
> These tests do not seem to launch Rails, don't they.

The intention was to load the least things possible, using the other bug templates as an example. Can we get away with not launching rails to get this to work?

> That might point to a legit missing require or autoload.

I suspected this too, will dig a little deeper and see if I can find the area where this may be missing. If you have any ideas, please let me know!

**Comment by fxn** [comment]
Let me explain what is happening in this particular bug report.

Action Text does not inject `has_rich_text` into Active Record just by loading the gem. The method is defined in [`ActionText::Attribute`](https://github.com/rails/rails/blob/15ca8ad0c1e94d11d0deb02535bc286e077d43ce/actiontext/lib/action_text/attribute.rb), which is [lazy loaded via `Module#autoload`](https://github.com/rails/rails/blob/15ca8ad0c1e94d11d0deb02535bc286e077d43ce/actiontext/lib/action_text.rb#L14) (this is a technique used by all the frameworkds and unrelated to the Rails autolaoder).

The decoration happens in an [initializer](https://github.com/rails/rails/blob/master/actiontext/lib/action_text/engine.rb) of the engine. Therefore, it needs a Rails application booting.

I believe we can close this one. But please do report the bug that originated this issue using a Rails application.
