### ISSUE TITLE
restrict_with_error raises exception when destroying CollectionProxy

### ISSUE THREAD

**Issue by shanecav84** [rails/rails#35298]
#### Executable Test Case
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.2"
  gem "sqlite3", "~> 1.3.6"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|; end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end

  create_table :sub_comments, force: true do |t|
    t.integer :comment_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  accepts_nested_attributes_for :comments, allow_destroy: true
end

class Comment < ActiveRecord::Base
  belongs_to :post
  has_many :sub_comments, dependent: :restrict_with_error
end

class SubComment < ActiveRecord::Base
  belongs_to :comment
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    comment = Comment.create!(post: post)
    SubComment.create!(comment: comment)

    invalid = assert_raises ::ActiveRecord::RecordNotDestroyed do
      post.update(comments_attributes: [{ id: comment.id, _destroy: true }])
      # `post.comments.destroy_all` also applies
    end
    assert_equal invalid.record, comment
    assert_equal invalid.record.errors.full_messages,
      ["Cannot delete record because dependent sub comments exist"]
  end
end
```

### Expected behavior
To not raise exception due to `restrict_with_error` and non-bang `update`.

### Actual behavior
Raises exception like `restrict_with_exception ` would despite `restrict_with_error`.

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.6.1

**Comment by shanecav84** [comment]
Similar issues for previous versions of Rails #20991, #24526

**Comment by shanecav84** [comment]
Here is the backtrace from the `ActiveRecord::RecordNotDestroyed` exception:

```
ActiveRecord::RecordNotDestroyed: Failed to destroy the record
    activerecord-5.2.2/lib/active_record/persistence.rb:748:in `_raise_record_not_destroyed'
    activerecord-5.2.2/lib/active_record/persistence.rb:355:in `destroy!'
    activerecord-5.2.2/lib/active_record/associations/has_many_association.rb:107:in `each'
    activerecord-5.2.2/lib/active_record/associations/has_many_association.rb:107:in `delete_records'
    activerecord-5.2.2/lib/active_record/associations/collection_association.rb:400:in `remove_records'
    activerecord-5.2.2/lib/active_record/associations/collection_association.rb:393:in `block in delete_or_destroy'
    activerecord-5.2.2/lib/active_record/associations/collection_association.rb:136:in `block in transaction'
    activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:257:in `transaction'
    activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
    activerecord-5.2.2/lib/active_record/associations/collection_association.rb:135:in `transaction'
    activerecord-5.2.2/lib/active_record/associations/collection_association.rb:393:in `delete_or_destroy'
    activerecord-5.2.2/lib/active_record/associations/collection_association.rb:199:in `destroy'
    activerecord-5.2.2/lib/active_record/autosave_association.rb:391:in `block in save_collection_association'
    activerecord-5.2.2/lib/active_record/autosave_association.rb:391:in `each'
    activerecord-5.2.2/lib/active_record/autosave_association.rb:391:in `save_collection_association'
    activerecord-5.2.2/lib/active_record/autosave_association.rb:187:in `block in add_autosave_association_callbacks'
    activerecord-5.2.2/lib/active_record/autosave_association.rb:159:in `instance_eval'
    activerecord-5.2.2/lib/active_record/autosave_association.rb:159:in `block in define_non_cyclic_method'
    activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
    activesupport-5.2.2/lib/active_support/callbacks.rb:236:in `block in halting_and_conditional'
    activesupport-5.2.2/lib/active_support/callbacks.rb:517:in `block in invoke_after'
    activesupport-5.2.2/lib/active_support/callbacks.rb:517:in `each'
    activesupport-5.2.2/lib/active_support/callbacks.rb:517:in `invoke_after'
    activesupport-5.2.2/lib/active_support/callbacks.rb:133:in `run_callbacks'
    activesupport-5.2.2/lib/active_support/callbacks.rb:816:in `_run_update_callbacks'
    activerecord-5.2.2/lib/active_record/callbacks.rb:350:in `_update_record'
    activerecord-5.2.2/lib/active_record/timestamp.rb:114:in `_update_record'
    activerecord-5.2.2/lib/active_record/persistence.rb:703:in `create_or_update'
    activerecord-5.2.2/lib/active_record/callbacks.rb:342:in `block in create_or_update'
    activesupport-5.2.2/lib/active_support/callbacks.rb:132:in `run_callbacks'
    activesupport-5.2.2/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
    activerecord-5.2.2/lib/active_record/callbacks.rb:342:in `create_or_update'
    activerecord-5.2.2/lib/active_record/persistence.rb:273:in `save'
    activerecord-5.2.2/lib/active_record/validations.rb:46:in `save'
    activerecord-5.2.2/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
    activerecord-5.2.2/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
    activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:257:in `transaction'
    activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
    activerecord-5.2.2/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
    activerecord-5.2.2/lib/active_record/transactions.rb:310:in `block in save'
    activerecord-5.2.2/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
    activerecord-5.2.2/lib/active_record/transactions.rb:309:in `save'
    activerecord-5.2.2/lib/active_record/suppressor.rb:44:in `save'
    activerecord-5.2.2/lib/active_record/persistence.rb:426:in `block in update'
    activerecord-5.2.2/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
    activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
    activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
    monitor.rb:230:in `mon_synchronize'
    activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
    activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
    activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
    activerecord-5.2.2/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
    activerecord-5.2.2/lib/active_record/persistence.rb:424:in `update'
    ar_destroy_bug.rb:55:in `test_association_stuff'
```

**Comment by shanecav84** [comment]
It looks like this is not a bug but is intended behavior. [From `collection_association.rb`](https://github.com/rails/rails/blob/d0fb775145d6780499b8910c4a0540088d3eed4b/activerecord/lib/active_record/associations/collection_association.rb#L192):

```ruby
# Deletes the +records+ and removes them from this association calling
# +before_remove+ , +after_remove+ , +before_destroy+ and +after_destroy+ callbacks.
#
# Note that this method removes records from the database ignoring the
# +:dependent+ option.
def destroy(*records)
  delete_or_destroy(records, :destroy)
end
```

Why is the `dependent` option ignored here?

**Comment by cimm** [comment]
I seem to have the same issue in Rails 6.0.2.

Using `restrict_with_error` raises an `ActiveRecord::RecordNotDestroyed` error when updating the nesting model while `restrict_with_exception` raises an `ActiveRecord::DeleteRestrictionError` error.

The second one makes sense but the first one should not raise an exception IMHO.

**Comment by mohammedgad** [comment]
same issue restrict_with_error should add an error to the child object, why it raises an exception?

**Comment by DaAwesomeP** [comment]
@cimm did you find a workaround?

**Comment by cimm** [comment]
Hi @DaAwesomeP, sorry this has been years ago, I no longer remember if or how I handled this.

**Comment by cryptogopher** [comment]
This is still an issue with Rails 7.2.2

`destroy_all` on CollectionProxy documentation says:
`Deletes the records of the collection directly from the database ignoring the :dependent option.`

Which is not true, as adding e.g. `dependent: :restrict_with_error` and calling `destroy_all` results in `ActiveRecord::RecordNotDestroyed`.

Code to reproduce:

```
Gem.paths = ENV.merge!({ "GEM_HOME" => Gem.user_dir })
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "7.2.2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end
  create_table :units, force: true do |t|
    t.references :user, foreign_key: true
    t.references :base
  end
end

class User < ActiveRecord::Base
  has_many :units
end

class Unit < ActiveRecord::Base
  belongs_to :base, optional: true, class_name: 'Unit'
  has_many :subunits, class_name: 'Unit', inverse_of: :base, dependent: :restrict_with_error
end

class BugTest < Minitest::Test
  def test_destroy_all_fails_with_dependent
    user = User.create!

    first = user.units.create!
    subunit = user.units.first.subunits.create!

    assert_raises ::ActiveRecord::RecordNotDestroyed do
      user.units.destroy_all
    end
    refute_equal -> {Unit.count}, 0
  end
end
```

(*passed* tests *mean* destroy_all works *incorrectly*)

**Comment by cryptogopher** [comment]
#53876

**Comment by cryptogopher** [comment]
> To not raise exception due to `restrict_with_error` and non-bang `update`.

I would consider replacing `destroy!` here:

https://github.com/rails/rails/blob/7a9b7254ae6bfe3fa358be60290716ae130bab09/activerecord/lib/active_record/associations/has_many_association.rb#L126-L132

with `destroy` to service `dependent:` option properly. Otherwise whatever the reason for withholding the destruction, some kind of exception will be raised.
