### ISSUE TITLE
New Rails 5.2.2 apps need sqlite3 1.3.x to work, but they install sqlite3 1.4.0 instead

### ISSUE THREAD

**Issue by DeeDeeG** [rails/rails#35387]
### Steps to reproduce

1) Initialize a new app: `rails new myapp` (wait for install to finish)
2) `cd` into the new app folder: `cd myapp`
3) Start the server: `rails s`
4) Connect to the server with a web browser; visit `localhost:3000` or `your_own_ip:3000` in a web browser.

### Expected behavior

The _"Yay! You’re on Rails!"_ demo page should appear in the browser.

### Actual behavior

An error shows:

```
Puma caught this error: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile. (LoadError)
```

<details>
  <summary>Full error <b><i>(click/tap/press Enter to expand!)</i></b></summary>

```ruby
Puma caught this error: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile. (LoadError)
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:12:in `<main>'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/connection_specification.rb:191:in `spec'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:952:in `establish_connection'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_handling.rb:60:in `establish_connection'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/railtie.rb:136:in `block (2 levels) in <class:Railtie>'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/base.rb:27:in `<main>'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/query_cache.rb:29:in `run'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:27:in `before'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:110:in `run!'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:72:in `block in run!'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:69:in `tap'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:69:in `run!'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/static.rb:127:in `call'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:524:in `call'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/home/[me]/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

</details>
.

This is saying that Puma failed to load a version of the `sqlite3` gem matching the version range `~> 1.3.6`, whereas `sqlite3` `1.4.0` is installed instead.

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.3 (x86_64-linux)

**Comment by DeeDeeG** [comment]
I think one of Rails' dependencies requires the 1.3.x branch of sqlite3, but in a way that's not reflected in the default Rails 5.2.2 Gemfile.

This issue has only popped up recently, since the 1.4.0 release of sqlite3 Gem was released on 4 February.

---

As of February 4, a version 1.4.0 of the sqlite3 gem exists: https://rubygems.org/gems/sqlite3/versions

The Gemfile created by `rails new [my-appname]` only specifies `sqlite3` without specifying or clamping the version range:

```ruby
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
```

`bundle install` pulls in `sqlite3` `1.4.0` into the `Gemfile.lock`:

```ruby
    sqlite3 (1.4.0)
```

Error message ensues.

---

A workaround for now is to edit the `Gemfile` to give a version range for `sqlite3`.

Either of these will work:

- `gem 'sqlite3', '< 1.4'`
- `gem 'sqlite3', '~> 1.3.6'`

**Comment by DeeDeeG** [comment]
I guess this is a duplicate of #35153.

**Comment by sikachu** [comment]
It's indeed similar to #35153. I'll ping the core team to see if we can release new 5.2 version, but I'm going to close this for now. Thank you for the report.

**Comment by zhenxingdev** [comment]
Encounter the same problem, ask for help! ! There is no corresponding solution in the official, there are many ways to deal with google search.

**Comment by Zeben** [comment]
I've got the same problem, so I wrote the post here in hope that I'll see some solution.

**Comment by threefivetwo420** [comment]
sudo apt-get install libsqlite3-dev

**Comment by DeeDeeG** [comment]
Hi all,

Today's release of [Rails 5.2.2.1](https://weblog.rubyonrails.org/2019/3/13/Rails-4-2-5-1-5-1-6-2-have-been-released/) inspired me to check if this issue still happens. In fact it does. (because 5.2.2.1 is just a [tiny bugfix release](https://github.com/rails/rails/compare/v5.2.2...v5.2.2.1) for a few different security issues, and doesn't include the fix for this issue #35387.)

I suppose this would need to be in a minor release, something like rails 5.2.3?

But just sort of pinging this issue again. Sorry for the noise, but I do think this will make it hard for new folks to get started with Rails, and that it is worthwhile to address. Thanks.

\- DeeDeeG

**Comment by sikachu** [comment]
Yes, as indicated by version number, 5.2.2.1 is a release that just had a security patch apply on top of 5.2.2 release to avoid unintended regression that could come with other patches.

The fix should be in the next minor version (5.2.3).

**Comment by DeeDeeG** [comment]
Thank you for your response.

P.S. Yes, I agree 5.2.3 would actually be a "patch" release, according to [semver](https://semver.org/).

**Comment by sikachu** [comment]
@DeeDeeG (sorry, I was actually correcting myself as I said a minor release in my original message to, wasn't intended to correct your message 😅)

**Comment by rubyFeedback** [comment]
Yes I just hit this problem too, on a fresh install where I followed a tutorial.

I could resolve it thanks to as to what DeeDeeG wrote - but I think in the long run, it might be better to integrate the solution right into how people install rails, out of the box. I did a simple "gem install rails", nothing aside from there, and starting rails server on a default newly created application led to this error that puma found sqlite version not working (or not being specified). I assume that the team that pushed the update of sqlite3 to rubygems.org was not aware of this issue, as otherwise that issue might not have been caught people, like noted above.

**Comment by sikachu** [comment]
Just want to drop by a note that Rails Core team has released 5.2.3.rc1: https://weblog.rubyonrails.org/2019/3/22/Rails-5-2-3-rc1-has-been-released/

5.2.3 should be out by next week if there is no regression found.

**Comment by vvichuuma** [comment]
Go to your 'RAILSAPP' -> '/* Gemfile' -> modify gem 'sqlite3'  to -> gem 'sqlite3' , '< 1.4' 
![error_sqlite3](https://user-images.githubusercontent.com/40339176/54861571-21413500-4cf9-11e9-8c24-5f60b8861bed.png)

**Comment by vvichuuma** [comment]
Go to your rails application -> /* Gemfile -> change the -> gem 'sqlite3' to -> gem 'sqlite3', '< 1.4'
![er_sqlLite3](https://user-images.githubusercontent.com/40339176/54861586-9a408c80-4cf9-11e9-92d2-8fd60dafb3f7.png)
