### ISSUE TITLE
Action View test_helper_class_that_is_being_tested_is_always_included_in_view_instance fails 

### ISSUE THREAD

**Issue by yahonda** [rails/rails#35389]
Reproduced this error at CI.
https://travis-ci.org/rails/rails/jobs/497717256#L3139-L3193

### Steps to reproduce

```ruby
$ cd actionview
$ bin/test test/template/render_test.rb test/template/test_case_test.rb -n "/^(?:CachedCollectionViewRenderTest#(?:test_render_partial_collection)|ActionView::HelperInclusionTest#(?:test_helper_class_that_is_being_tested_is_always_included_in_view_instance))$/" --seed 62617
```

### Expected behavior
It should pass.

### Actual behavior

```ruby
$ bin/test test/template/render_test.rb test/template/test_case_test.rb -n "/^(?:CachedCollectionViewRenderTest#(?:test_render_partial_collection)|ActionView::HelperInclusionTest#(?:test_helper_class_that_is_being_tested_is_always_included_in_view_instance))$/" --seed 62617
Run options: -n "/^(?:CachedCollectionViewRenderTest#(?:test_render_partial_collection)|ActionView::HelperInclusionTest#(?:test_helper_class_that_is_being_tested_is_always_included_in_view_instance))$/" --seed 62617

# Running:

.E

Error:
ActionView::HelperInclusionTest#test_helper_class_that_is_being_tested_is_always_included_in_view_instance:
ActionView::Template::Error: undefined method `_test_fixtures_test__customer_erb__1323730284087985528_47069287878420' for #<#<Class:0x0000559e586301e0>:0x0000559e58643df8>
Did you mean?  _test_fixtures_test__from_helper_erb___208306068294530904_47069288074640
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:274:in `run'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:169:in `block in render'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:182:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:381:in `instrument_render_template'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:167:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:455:in `block in collection_with_template'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:451:in `map'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:451:in `collection_with_template'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:340:in `block (2 levels) in render_collection'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb:15:in `cache_collection_render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:339:in `block in render_collection'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:328:in `render_collection'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:318:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:22:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:304:in `in_rendering_context'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:30:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/test_case.rb:206:in `render'
    /home/yahonda/git/rails/actionview/test/template/test_case_test.rb:126:in `render_from_helper'
    /home/yahonda/git/rails/actionview/test/fixtures/test/_from_helper.erb:1:in `_test_fixtures_test__from_helper_erb___208306068294530904_47069288074640'
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:274:in `run'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:169:in `block in render'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:182:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:381:in `instrument_render_template'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:167:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:361:in `block in render_partial'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:350:in `render_partial'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:320:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:22:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:304:in `in_rendering_context'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:30:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/test_case.rb:206:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/test_case.rb:122:in `render'
    /home/yahonda/git/rails/actionview/test/template/test_case_test.rb:136:in `block in <class:HelperInclusionTest>'


bin/test test/template/test_case_test.rb:132



Finished in 0.083124s, 24.0605 runs/s, 36.0907 assertions/s.
2 runs, 3 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**:master branch

**Ruby version**:ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]

**Comment by yahonda** [comment]
Have not found how to address this error yet.

**Comment by yahonda** [comment]
According to the `git bisect`, this error has been introduced since #35036 5b4df9d0eb295d402489465f3600576038f5762d

@tenderlove Would you take a look at this because you are the author of this pull request. Thank you.

**Comment by yahonda** [comment]
Closing it because it does not reproduce anymore.

According to the `git bisect` says https://github.com/rails/rails/pull/35308 07804d4759726da04020834502d37a8f4ac97a8f addresses this error.
