### ISSUE TITLE
'<class:InboundEmail>': uninitialized constant #::Incineratable (NameError)

### ISSUE THREAD

**Issue by thiyagarajan** [rails/rails#35452]
### Steps to reproduce
1. create rails app using latest 6.0.0beta2

2. run production mode

### Expected behavior
Should able to run application in production mode

### Actual behavior
/Users/vtr/.rvm/gems/ruby-2.5.3/bundler/gems/rails-f4a30d2a0706/actionmailbox/app/models/action_mailbox/inbound_email.rb:30:in `<class:InboundEmail>': uninitialized constant #<Class:0x00007fba87b11e78>::Incineratable (NameError)
Did you mean?  ActionMailbox::IncinerationJob

### System configuration
**Rails version**: 6.0.0beta2

**Ruby version**: 5.4.3

**Comment by michaeltrojanek** [comment]
Also ran into this shortly after this issue has been opened.

**Configuration:** Rails 6.0.0.beta2 on a pretty default production stack (CentOS, rbenv, nginx, Puma, MariaDB), Ruby 2.5.3p105

**Comment by kaspth** [comment]
Are any of you upgrading an app to Rails 6 or fresh on a new Rails 6 app? Could be Zeitwerk related @fxn.

**Comment by michaeltrojanek** [comment]
I am working on a update for [my book](https://efficientrailsdevops.com) to support Rails 6, therefore I am working in a totally clean environment — the app has been generated with `rails new` on a freshly provisioned CentOS 7 Vagrant box, with everything installed from scratch via Ansible.

I can definitely count out upgrade issues.

**Comment by fxn** [comment]
Hey, on a family trip without computer. Could be related, I’ll have a look back home.

**Comment by fxn** [comment]
Meanwhile, could you enable logging putting

```ruby
Rails.autoloaders.logger = method(:puts)
```

in `config/application.rb`, reproduce, and share the traces?

Also, could you please fire a console in `development` mode and reference that constant? Do we get the same error?

**Comment by michaeltrojanek** [comment]
This is the output from starting the Puma application server in production mode with logger set to `method(:puts)`:

```
[12850] Puma starting in cluster mode...
[12850] * Version 3.12.0 (ruby 2.5.3-p105), codename: Llamas in Pajamas
[12850] * Min threads: 0, max threads: 16
[12850] * Environment: production
[12850] * Process workers: 1
[12850] * Preloading application
Zeitwerk@rails.main: autoload set for ApplicationCable, to be autovivified from /var/www/myapp/application/app/channels/application_cable
Zeitwerk@rails.main: autoload set for ApplicationController, to be loaded from /var/www/myapp/application/app/controllers/application_controller.rb
Zeitwerk@rails.main: autoload set for CustomersController, to be loaded from /var/www/myapp/application/app/controllers/customers_controller.rb
Zeitwerk@rails.main: autoload set for ApplicationHelper, to be loaded from /var/www/myapp/application/app/helpers/application_helper.rb
Zeitwerk@rails.main: autoload set for CustomersHelper, to be loaded from /var/www/myapp/application/app/helpers/customers_helper.rb
Zeitwerk@rails.main: autoload set for ApplicationJob, to be loaded from /var/www/myapp/application/app/jobs/application_job.rb
Zeitwerk@rails.main: autoload set for ApplicationMailer, to be loaded from /var/www/myapp/application/app/mailers/application_mailer.rb
Zeitwerk@rails.main: autoload set for ApplicationRecord, to be loaded from /var/www/myapp/application/app/models/application_record.rb
Zeitwerk@rails.main: autoload set for Customer, to be loaded from /var/www/myapp/application/app/models/customer.rb
Zeitwerk@rails.once: autoload set for ActionText::ContentHelper, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actiontext-6.0.0.beta2/app/helpers/action_text/content_helper.rb
Zeitwerk@rails.once: autoload set for ActionText::TagHelper, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actiontext-6.0.0.beta2/app/helpers/action_text/tag_helper.rb
Zeitwerk@rails.once: autoload set for ActionText::RichText, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actiontext-6.0.0.beta2/app/models/action_text/rich_text.rb
Zeitwerk@rails.once: autoload set for ActionMailbox::BaseController, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/controllers/action_mailbox/base_controller.rb
Zeitwerk@rails.once: autoload set for ActionMailbox::Ingresses, to be autovivified from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/controllers/action_mailbox/ingresses
Zeitwerk@rails.once: autoload set for Rails::Conductor, to be autovivified from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/controllers/rails/conductor
Zeitwerk@rails.once: autoload set for ActionMailbox::IncinerationJob, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/jobs/action_mailbox/incineration_job.rb
Zeitwerk@rails.once: autoload set for ActionMailbox::RoutingJob, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/jobs/action_mailbox/routing_job.rb
Zeitwerk@rails.once: autoload set for ActionMailbox::InboundEmail, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/models/action_mailbox/inbound_email.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::BaseController, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/active_storage/base_controller.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::BlobsController, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/active_storage/blobs_controller.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::DirectUploadsController, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/active_storage/direct_uploads_controller.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::DiskController, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/active_storage/disk_controller.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::RepresentationsController, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/active_storage/representations_controller.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::SetBlob, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/concerns/active_storage/set_blob.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::SetCurrent, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/concerns/active_storage/set_current.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::AnalyzeJob, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/jobs/active_storage/analyze_job.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::BaseJob, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/jobs/active_storage/base_job.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::PurgeJob, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/jobs/active_storage/purge_job.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Attachment, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/attachment.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Blob, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/blob.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Current, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/current.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Filename, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/filename.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Preview, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/preview.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Variant, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/variant.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Variation, to be loaded from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/variation.rb
Zeitwerk@rails.once: constant ActionText::ContentHelper loaded from file /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actiontext-6.0.0.beta2/app/helpers/action_text/content_helper.rb
Zeitwerk@rails.once: constant ActionText::TagHelper loaded from file /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actiontext-6.0.0.beta2/app/helpers/action_text/tag_helper.rb
Zeitwerk@rails.main: constant ApplicationHelper loaded from file /var/www/myapp/application/app/helpers/application_helper.rb
Zeitwerk@rails.main: constant CustomersHelper loaded from file /var/www/myapp/application/app/helpers/customers_helper.rb
Zeitwerk@rails.main: constant ApplicationController loaded from file /var/www/myapp/application/app/controllers/application_controller.rb
Zeitwerk@rails.main: constant CustomersController loaded from file /var/www/myapp/application/app/controllers/customers_controller.rb
Zeitwerk@rails.main: constant ApplicationJob loaded from file /var/www/myapp/application/app/jobs/application_job.rb
Zeitwerk@rails.main: constant ApplicationMailer loaded from file /var/www/myapp/application/app/mailers/application_mailer.rb
Zeitwerk@rails.main: constant ApplicationRecord loaded from file /var/www/myapp/application/app/models/application_record.rb
Zeitwerk@rails.main: constant Customer loaded from file /var/www/myapp/application/app/models/customer.rb
Zeitwerk@rails.main: module ApplicationCable autovivified from directory /var/www/myapp/application/app/channels/application_cable
Zeitwerk@rails.main: autoload set for ApplicationCable::Channel, to be loaded from /var/www/myapp/application/app/channels/application_cable/channel.rb
Zeitwerk@rails.main: autoload set for ApplicationCable::Connection, to be loaded from /var/www/myapp/application/app/channels/application_cable/connection.rb
Zeitwerk@rails.main: constant ApplicationCable::Channel loaded from file /var/www/myapp/application/app/channels/application_cable/channel.rb
Zeitwerk@rails.main: constant ApplicationCable::Connection loaded from file /var/www/myapp/application/app/channels/application_cable/connection.rb
Zeitwerk@rails.once: constant ActionText::RichText loaded from file /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actiontext-6.0.0.beta2/app/models/action_text/rich_text.rb
Zeitwerk@rails.once: constant ActionMailbox::BaseController loaded from file /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/controllers/action_mailbox/base_controller.rb
Zeitwerk@rails.once: constant ActionMailbox::IncinerationJob loaded from file /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/jobs/action_mailbox/incineration_job.rb
Zeitwerk@rails.once: constant ActionMailbox::RoutingJob loaded from file /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/jobs/action_mailbox/routing_job.rb
[12850] ! Unable to load application: NameError: uninitialized constant #<Class:0x0000558b81b74898>::Incineratable
Did you mean?  ActionMailbox::IncinerationJob
Traceback (most recent call last):
	54: from /home/app/.rbenv/versions/2.5.3/bin/puma:23:in `<main>'
	53: from /home/app/.rbenv/versions/2.5.3/bin/puma:23:in `load'
	52: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
	51: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
	50: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
	49: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:410:in `run'
	48: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/runner.rb:145:in `load_and_bind'
	47: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'
	46: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:318:in `load_rackup'
	45: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
	44: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
	43: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
	42: from config.ru:in `<main>'
	41: from config.ru:in `new'
	40: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
	39: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
	38: from config.ru:3:in `block in <main>'
	37: from config.ru:3:in `require_relative'
	36: from /var/www/myapp/application/config/environment.rb:5:in `<top (required)>'
	35: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-6.0.0.beta2/lib/rails/application.rb:362:in `initialize!'
	34: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-6.0.0.beta2/lib/rails/initializable.rb:60:in `run_initializers'
	33: from /home/app/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	32: from /home/app/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	31: from /home/app/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	30: from /home/app/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
	29: from /home/app/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
	28: from /home/app/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	27: from /home/app/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	26: from /home/app/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	25: from /home/app/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	24: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-6.0.0.beta2/lib/rails/initializable.rb:61:in `block in run_initializers'
	23: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-6.0.0.beta2/lib/rails/initializable.rb:32:in `run'
	22: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-6.0.0.beta2/lib/rails/initializable.rb:32:in `instance_exec'
	21: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-6.0.0.beta2/lib/rails/application/finisher.rb:79:in `block in <module:Finisher>'
	20: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.3.1/lib/zeitwerk/loader.rb:315:in `eager_load_all'
	19: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.3.1/lib/zeitwerk/loader.rb:315:in `each'
	18: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.3.1/lib/zeitwerk/loader.rb:257:in `eager_load'
	17: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.3.1/lib/zeitwerk/loader.rb:257:in `synchronize'
	16: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.3.1/lib/zeitwerk/loader.rb:262:in `block in eager_load'
	15: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.3.1/lib/zeitwerk/loader.rb:479:in `each_abspath'
	14: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.3.1/lib/zeitwerk/loader.rb:479:in `foreach'
	13: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.3.1/lib/zeitwerk/loader.rb:482:in `block in each_abspath'
	12: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.3.1/lib/zeitwerk/loader.rb:264:in `block (2 levels) in eager_load'
	11: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0.beta2/lib/active_support/dependencies.rb:297:in `require'
	10: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0.beta2/lib/active_support/dependencies.rb:263:in `load_dependency'
	 9: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0.beta2/lib/active_support/dependencies.rb:297:in `block in require'
	 8: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.3.1/lib/zeitwerk/kernel.rb:16:in `require'
	 7: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	 6: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	 5: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	 4: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	 3: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	 2: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/models/action_mailbox/inbound_email.rb:5:in `<main>'
	 1: from /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/models/action_mailbox/inbound_email.rb:27:in `<module:ActionMailbox>'
/home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/models/action_mailbox/inbound_email.rb:30:in `<class:InboundEmail>': uninitialized constant #<Class:0x0000558b81b74898>::Incineratable (NameError)
Did you mean?  ActionMailbox::IncinerationJob
```

Running the Rails console in development mode *on a production machine* has been a little tricky (no db config, no bundle), but I got it working. However, I'm not sure which constant to reference.

The `ActionMailbox::IncinerationJob` module is available, of course:

```
irb(main):001:0> ActionMailbox::IncinerationJob
Zeitwerk@rails.once: constant ActionMailbox::IncinerationJob loaded from file /home/app/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/jobs/action_mailbox/incineration_job.rb
=> ActionMailbox::IncinerationJob
irb(main):002:0>
```

I have no idea what class `<Class:0x0000558b81b74898>` represents.

**Comment by fxn** [comment]
Oh! I meant to run a dev console in a dev machine. For example, if the bahaviour was different maybe that would hint to eager loading.

Typing in my phone, but I believe the constant to try in the console would be `ActionMailbox::InboundEmail::Incineratable`.

For added info, a trace of that would also be helpful no matter if it errs or not.

**Comment by michaeltrojanek** [comment]
Alright. A `rails server` in development mode on my local machine works:

```
=> Booting Puma
=> Rails 6.0.0.beta2 application starting in development
=> Run `rails server --help` for more startup options
Zeitwerk@rails.main: autoload set for ApplicationCable, to be autovivified from /private/tmp/debug/app/channels/application_cable
Zeitwerk@rails.main: autoload set for ApplicationController, to be loaded from /private/tmp/debug/app/controllers/application_controller.rb
Zeitwerk@rails.main: autoload set for CustomersController, to be loaded from /private/tmp/debug/app/controllers/customers_controller.rb
Zeitwerk@rails.main: autoload set for CustomersHelper, to be loaded from /private/tmp/debug/app/helpers/customers_helper.rb
Zeitwerk@rails.main: autoload set for ApplicationHelper, to be loaded from /private/tmp/debug/app/helpers/application_helper.rb
Zeitwerk@rails.main: autoload set for ApplicationJob, to be loaded from /private/tmp/debug/app/jobs/application_job.rb
Zeitwerk@rails.main: autoload set for ApplicationMailer, to be loaded from /private/tmp/debug/app/mailers/application_mailer.rb
Zeitwerk@rails.main: autoload set for Customer, to be loaded from /private/tmp/debug/app/models/customer.rb
Zeitwerk@rails.main: autoload set for ApplicationRecord, to be loaded from /private/tmp/debug/app/models/application_record.rb
Zeitwerk@rails.once: autoload set for ActionText::TagHelper, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actiontext-6.0.0.beta2/app/helpers/action_text/tag_helper.rb
Zeitwerk@rails.once: autoload set for ActionText::ContentHelper, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actiontext-6.0.0.beta2/app/helpers/action_text/content_helper.rb
Zeitwerk@rails.once: autoload set for ActionText::RichText, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actiontext-6.0.0.beta2/app/models/action_text/rich_text.rb
Zeitwerk@rails.once: autoload set for ActionMailbox::BaseController, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/controllers/action_mailbox/base_controller.rb
Zeitwerk@rails.once: autoload set for ActionMailbox::Ingresses, to be autovivified from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/controllers/action_mailbox/ingresses
Zeitwerk@rails.once: autoload set for Rails::Conductor, to be autovivified from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/controllers/rails/conductor
Zeitwerk@rails.once: autoload set for ActionMailbox::IncinerationJob, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/jobs/action_mailbox/incineration_job.rb
Zeitwerk@rails.once: autoload set for ActionMailbox::RoutingJob, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/jobs/action_mailbox/routing_job.rb
Zeitwerk@rails.once: autoload set for ActionMailbox::InboundEmail, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionmailbox-6.0.0.beta2/app/models/action_mailbox/inbound_email.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::DirectUploadsController, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/active_storage/direct_uploads_controller.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::BaseController, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/active_storage/base_controller.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::BlobsController, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/active_storage/blobs_controller.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::RepresentationsController, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/active_storage/representations_controller.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::DiskController, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/active_storage/disk_controller.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::SetCurrent, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/concerns/active_storage/set_current.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::SetBlob, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/controllers/concerns/active_storage/set_blob.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::BaseJob, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/jobs/active_storage/base_job.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::AnalyzeJob, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/jobs/active_storage/analyze_job.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::PurgeJob, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/jobs/active_storage/purge_job.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Variant, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/variant.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Blob, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/blob.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Filename, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/filename.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Variation, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/variation.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Attachment, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/attachment.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Current, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/current.rb
Zeitwerk@rails.once: autoload set for ActiveStorage::Preview, to be loaded from /Users/mitro/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-6.0.0.beta2/app/models/active_storage/preview.rb
Puma starting in single mode...
* Version 3.12.0 (ruby 2.5.3-p105), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

`ActionMailbox::InboundEmail::Incineratable` errors out in console:

```
Running via Spring preloader in process 13413
Loading development environment (Rails 6.0.0.beta2)
irb(main):001:0> ActionMailbox::InboundEmail::Incineratable
Traceback (most recent call last):
        1: from (irb):1
NameError (uninitialized constant #<Class:0x00007fc0f19c5ef0>::Incineratable)
Did you mean?  ActionMailbox::IncinerationJob
irb(main):002:0>
```

**Comment by eugeneius** [comment]
This is caused by a bug in Ruby 2.5 that only manifests when both Zeitwerk and Bootsnap are active. 

Zeitwerk [uses a TracePoint](https://github.com/fxn/zeitwerk/blob/v1.3.1/lib/zeitwerk/loader.rb#L122) to react to newly loaded classes. Bootsnap [defines a `load_iseq` handler](https://github.com/Shopify/bootsnap/blob/v1.4.1/lib/bootsnap/compile_cache/iseq.rb#L33), which [breaks TracePoint events on Ruby 2.5](https://bugs.ruby-lang.org/issues/14702).

The bug was fixed before Ruby 2.6.0 was released, and has been backported to the 2.5 branch, but there hasn't been a maintenance release since then.

This has only become a problem in beta2 because before https://github.com/rails/rails/pull/35332, the `const_missing` hook from `ActiveSupport::Dependencies` would load any constants that had been missed by Zeitwerk.

The most straightforward fix would be to revert https://github.com/rails/rails/pull/35332, and leave `ActiveSupport::Dependencies` in place as a fallback, at least until Ruby 2.5.4 has been out for a while.

**Comment by michaeltrojanek** [comment]
I can confirm that when running under Ruby 2.6.1 there are no issues. For me that's fine (as I want to target the latest Ruby version anyway).

Thanks for the help, guys!

**Comment by fxn** [comment]
Fantastic.

I prefer not to revert unkooking, because its purpose is precisely to prevent dependencies from autoloading. For example, `loaded?` would be inconsistent, reloading would no work... As a compromise I decided to activate Zeitwerk in the finisher, so technically dependencies is available during initialization, but you should not autoload during initialization anyway, hence the trade-off.

I’d suggest leaving the issue open to see if 2.5.4 is released before we do.

Meanwhile people can:

* Upgrade Ruby to 2.6.
* Enable classic mode.
* Disable bootsnap.

**Comment by fxn** [comment]
I have added this issue to the 6.0.0 milestone, and a [comment in Redmine](https://bugs.ruby-lang.org/issues/14702#note-11).

**Comment by fxn** [comment]
To have a clear reference of this issue in a way that doesn't need to process this tread, I have created https://github.com/rails/rails/issues/35475 and going to close here.
