### ISSUE TITLE
app:update task fails with NameError: uninitialized constant Rails::Html

### ISSUE THREAD

**Issue by cjlarose** [rails/rails#35480]
### Steps to reproduce

I'm upgrading an application from Rails 5.2.2 to Rails 6.0.0.beta2

If I invoke `bundle exec rails app:update`, I get to the part where the tool tries to invoke `active_storage:update`.

### Expected behavior

The task `active_storage:update` runs successfully

### Actual behavior

```
      create  bin/yarn
      remove  bin/yarn
       rails  active_storage:update
rails aborted!
NameError: uninitialized constant Rails::Html
/Users/chris.larose/dev/mycase/notifications/config/environment.rb:7:in `<main>'
bin/rails:4:in `<main>'

Caused by:
NameError: uninitialized constant Rails::Html
/Users/chris.larose/dev/mycase/notifications/config/environment.rb:7:in `<main>'
bin/rails:4:in `<main>'
Tasks: TOP => active_storage:update => environment
(See full trace by running task with --trace)

After this, check Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.ht
ml for more details about upgrading your app.
```

Repeating `bundle exec rails app:update` with the `--trace` option as `bundle exec rails --trace app:update` has a similar effect.

```
** Invoke app:update:active_storage (first_time)
** Execute app:update:active_storage
       rails  active_storage:update
rails aborted!
NameError: uninitialized constant Rails::Html
/Users/chris.larose/dev/mycase/notifications/config/environment.rb:7:in `<main>'
bin/rails:4:in `<main>'

Caused by:
NameError: uninitialized constant Rails::Html
/Users/chris.larose/dev/mycase/notifications/config/environment.rb:7:in `<main>'
bin/rails:4:in `<main>'
Tasks: TOP => active_storage:update => environment
(See full trace by running task with --trace)
** Invoke app:update:upgrade_guide_info (first_time)
** Execute app:update:upgrade_guide_info

After this, check Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.ht
ml for more details about upgrading your app.
** Execute app:update
```

Interestingly, it looks like the `--trace` option isn't passed to the `active_storage:update` task so I still don't get a backtrace. Also interestingly, the `app:update` task continues with the next task `app:update:upgrade_guide_info` even though the task `active_storage:update` failed. These are all separate issues.

I was able to add some `binding.pry` statements in `rake` to get the full backtrace, reproduced here:

<summary>
Full backtrace

<details>

```
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:42:in `load_missing_constant'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/actiontext-6.0.0.beta2/app/helpers/action_text/content_helper.rb:5:in `<module:ContentHelper>'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/actiontext-6.0.0.beta2/app/helpers/action_text/content_helper.rb:4:in `<module:ActionText>'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/actiontext-6.0.0.beta2/app/helpers/action_text/content_helper.rb:3:in `<main>'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/dependencies/interlock.rb:13:in `loading'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `depend_on'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.beta2/lib/abstract_controller/helpers.rb:149:in `block in modules_for_helpers'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.beta2/lib/abstract_controller/helpers.rb:144:in `map!'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.beta2/lib/abstract_controller/helpers.rb:144:in `modules_for_helpers'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.beta2/lib/action_controller/metal/helpers.rb:94:in `modules_for_helpers'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/engine.rb:491:in `helpers'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/railtie.rb:190:in `public_send'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/railtie.rb:190:in `method_missing'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/actiontext-6.0.0.beta2/lib/action_text/engine.rb:33:in `block (2 levels) in <class:Engine>'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/lazy_load_hooks.rb:72:in `class_eval'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/lazy_load_hooks.rb:72:in `block in execute_hook'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/lazy_load_hooks.rb:42:in `each'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta2/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/actiontext-6.0.0.beta2/lib/action_text/engine.rb:32:in `block in <class:Engine>'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/initializable.rb:32:in `instance_exec'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/initializable.rb:32:in `run'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `each'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `call'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/initializable.rb:60:in `run_initializers'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/application.rb:362:in `initialize!'
/Users/chris.larose/dev/mycase/notifications/config/environment.rb:7:in `<main>'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/application.rb:338:in `require_environment!'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/application.rb:513:in `block in run_tasks_blocks'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/command.rb:48:in `invoke'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta2/lib/rails/commands.rb:18:in `<main>'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/chris.larose/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
bin/rails:4:in `<main>'
```
</details>
</summary>

Edit: I found that `bundle exec rake --trace active_storage:update` will correctly print the backtrace.

The backtrace reveals that this line

https://github.com/rails/rails/blob/v6.0.0.beta2/actiontext/app/helpers/action_text/content_helper.rb#L5

References the `Rails::Html` module, which appears to be defined by the gem [`rails-html-santizer`][0]

[0]: https://github.com/rails/rails-html-sanitizer

This gem is installed as part of my application, of course, since it's a `actionpack` dependency and a `actionview` dependency, so the module exists. It just seems like it's a `require`-order problem possibly.

### System configuration
**Rails version**: 6.0.0.beta2

**Ruby version**: 2.6.1

**Comment by cjlarose** [comment]
Attempting to `bisect` on the `rails/rails` repo, I find that I get the same error in my application on the merge commit that introduced that the `active_storage:update` task 9e34df00039d63b5672315419e76f06f80ef3dc4

**Comment by bogdanvlviv** [comment]
Hey, thanks for the report. Could you please provide a minimal app to reproduce this error? I've tried to generate a simple app but couldn't reproduce that (`active_storage:update` succeed).

**Comment by cjlarose** [comment]
I generated a small app that reproduces the error here: https://github.com/cjlarose/rails-6-unitialized-constant-html-repro

The commit history is clean, but roughly the steps were

1. `rails _5.2.2_ new --skip-sprockets --skip-listen repro && cd repro`
1. Set `gem 'rails', '6.0.0.beta2'` in the Gemfile
1. Remove the `web-console` gem from the Gemfile
1. Add the `config` gem to the Gemfile
1. `bundle update rails`
1. `bundle exec rails app:update # accept changes to config/appliction.rb, then quit`
1. `bundle exec rake active_storage:update # uninitialized constant error`

From debugging my own application and trying to generate this repro app, I found that these two conditions are necessary

1. `ActionController::Base` is loaded before [this initializer in `actiontext`][0] runs.
2. The gem `rails-html-sanitizer` isn't loaded before the same initializer runs.

[0]: https://github.com/rails/rails/blob/v6.0.0.beta2/actiontext/lib/action_text/engine.rb#L31-L35

The `config` gem is just one way to make sure the first condition is satisfied since it references `ActionController::Base` explicitly in its [initializer][1]

[1]: https://github.com/railsconfig/config/blob/1.7.0/lib/config/integrations/rails/railtie.rb#L26-L32

Removing the `web-console` gem is necessary here to ensure the second condition is satisfied.

The reason why I generated the app with `--skip-sprockets` and `--skip-listen` is because that'll expand the statement to `require 'rails/all'` in the generated `config/application.rb`. If the application uses `require 'rails/all'` instead of listing out the frameworks explcitly, the error doesn't happen (something else `require`s the `rails-html-sanitizer` before the `actiontext` initializer runs.

**Comment by cjlarose** [comment]
In theory, the `config` gem could probably defer initialization until `ActionController:Base` is loaded using `ActiveSupport.on_load(:action_controller_base)`. This might solve my problem in this particular case.

However, if I'm understanding this problem correctly, `actiontext`'s initializer should probably work regardless of whether or not `ActionController::Base` has already been loaded (and the `rails-html-sanitizer` hasn't yet been `require`d).

**Comment by bogdanvlviv** [comment]
@cjlarose Thanks for the minimal app, I can reproduce this.
Adding the require `require "rails-html-sanitizer"` to https://github.com/rails/rails/blob/v6.0.0.beta2/actiontext/app/helpers/action_text/content_helper.rb#L2 fixes
```bash
   identical  bin/yarn
       rails  active_storage:update
rails aborted!
NameError: uninitialized constant Rails::Html
```

Do you want to contribute?

**Comment by cjlarose** [comment]
Will do. Thanks!
