### ISSUE TITLE
rails mongo 

### ISSUE THREAD

**Issue by luisgarcia1010** [rails/rails#35486]
### System configuration
**Rails version**:

**Ruby version**:

**Comment by luisgarcia1010** [comment]
I need to transfer a project from one server to another
but with rake db:migrate RAILS_ENV="production"
```
D, [2019-03-05T19:33:37.698159 #3953] DEBUG -- : MONGODB | EVENT: #<Mongo::Monitoring::Event::TopologyOpening topology=Unknown>
D, [2019-03-05T19:33:37.698204 #3953] DEBUG -- : MONGODB | Topology type 'unknown' initializing.
D, [2019-03-05T19:33:37.698260 #3953] DEBUG -- : MONGODB | EVENT: #<Mongo::Monitoring::Event::ServerOpening address=127.0.0.1:27017 topology=Unknown>
D, [2019-03-05T19:33:37.698277 #3953] DEBUG -- : MONGODB | Server 127.0.0.1:27017 initializing.
D, [2019-03-05T19:33:37.699501 #3953] DEBUG -- : MONGODB | EVENT: #<Mongo::Monitoring::Event::TopologyChanged prev=Unknown new=Single>
D, [2019-03-05T19:33:37.699526 #3953] DEBUG -- : MONGODB | Topology type 'unknown' changed to type 'single'.
D, [2019-03-05T19:33:37.699551 #3953] DEBUG -- : MONGODB | EVENT: #<Mongo::Monitoring::Event::ServerDescriptionChanged>
D, [2019-03-05T19:33:37.699578 #3953] DEBUG -- : MONGODB | Server description for 127.0.0.1:27017 changed from 'unknown' to 'standalone'.
D, [2019-03-05T19:33:37.699609 #3953] DEBUG -- : MONGODB | EVENT: #<Mongo::Monitoring::Event::TopologyChanged prev=Single new=Single>
D, [2019-03-05T19:33:37.699624 #3953] DEBUG -- : MONGODB | There was a change in the members of the 'single' topology.
D, [2019-03-05T19:33:37.706314 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.find | STARTED | {"find"=>"i18n", "filter"=>{}, "lsid"=>{"id"=><BSON::Binary:0x63649180 type=uuid data=0xd3a201bbaf904a3d...>}}
D, [2019-03-05T19:33:37.707804 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.find | SUCCEEDED | 0.001s
D, [2019-03-05T19:33:37.749634 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.getMore | STARTED | {"getMore"=>23243161737, "collection"=>"i18n", "lsid"=>{"id"=><BSON::Binary:0x63649180 type=uuid data=0xd3a201bbaf904a3d...>}}
...
D, [2019-03-05T19:33:38.709157 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.find | STARTED | {"find"=>"i18n", "filter"=>{}, "lsid"=>{"id"=><BSON::Binary:0x108109000 type=uuid data=0x6740a218e79f4f65...>}}
D, [2019-03-05T19:33:38.710046 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.find | SUCCEEDED | 0.000s
rake aborted!
SystemStackError: stack level too deep
/usr/local/rvm/gems/ruby-2.3.1/gems/bson-4.3.0/lib/bson/document.rb:198:in `convert_key'
/usr/local/rvm/gems/ruby-2.3.1/gems/bson-4.3.0/lib/bson/document.rb:68:in `[]='
/usr/local/rvm/gems/ruby-2.3.1/gems/bson-4.3.0/lib/bson/document.rb:136:in `block in initialize'
/usr/local/rvm/gems/ruby-2.3.1/gems/bson-4.3.0/lib/bson/document.rb:136:in `each_pair'
/usr/local/rvm/gems/ruby-2.3.1/gems/bson-4.3.0/lib/bson/document.rb:136:in `initialize'
/usr/local/rvm/gems/ruby-2.3.1/gems/bson-4.3.0/lib/bson/hash.rb:65:in `new'
/usr/local/rvm/gems/ruby-2.3.1/gems/bson-4.3.0/lib/bson/hash.rb:65:in `to_bson_normalized_value'
/usr/local/rvm/gems/ruby-2.3.1/gems/bson-4.3.0/lib/bson/document.rb:202:in `convert_value'
/usr/local/rvm/gems/ruby-2.3.1/gems/bson-4.3.0/lib/bson/document.rb:68:in `[]='
/usr/local/rvm/gems/ruby-2.3.1/gems/bson-4.3.0/lib/bson/document.rb:136:in `block in initialize'
/usr/local/rvm/gems/ruby-2.3.1/gems/bson-4.3.0/lib/bson/document.rb:136:in `each_pair'
/usr/local/rvm/gems/ruby-2.3.1/gems/bson-4.3.0/lib/bson/document.rb:136:in `initialize'
...
/usr/local/rvm/gems/ruby-2.3.1/gems/i18n_backend_mongoid-0.1.1/lib/i18n_backend_mongoid/i18n/backend/mongoid.rb:56:in `block in load_translations'
/usr/local/rvm/gems/ruby-2.3.1/gems/mongoid-6.0.3/lib/mongoid/contextual/mongo.rb:693:in `yield_document'
/usr/local/rvm/gems/ruby-2.3.1/gems/mongoid-6.0.3/lib/mongoid/contextual/mongo.rb:124:in `block in each'
/usr/local/rvm/gems/ruby-2.3.1/gems/mongo-2.6.2/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/usr/local/rvm/gems/ruby-2.3.1/gems/mongo-2.6.2/lib/mongo/cursor.rb:121:in `block in each'
/usr/local/rvm/gems/ruby-2.3.1/gems/mongo-2.6.2/lib/mongo/cursor.rb:121:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/mongo-2.6.2/lib/mongo/cursor.rb:121:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/mongo-2.6.2/lib/mongo/collection/view/iterable.rb:45:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/mongoid-6.0.3/lib/mongoid/query_cache.rb:222:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/mongoid-6.0.3/lib/mongoid/contextual/mongo.rb:123:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/mongoid-6.0.3/lib/mongoid/contextual.rb:20:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/i18n_backend_mongoid-0.1.1/lib/i18n_backend_mongoid/i18n/backend/mongoid.rb:55:in `load_translations'
/usr/local/rvm/gems/ruby-2.3.1/gems/i18n_backend_mongoid-0.1.1/lib/i18n_backend_mongoid/i18n/backend/mongoid.rb:49:in `init_translations'
/usr/local/rvm/gems/ruby-2.3.1/gems/i18n_backend_mongoid-0.1.1/lib/i18n_backend_mongoid/i18n/backend/mongoid.rb:43:in `reload!'
/usr/local/rvm/gems/ruby-2.3.1/gems/i18n-0.9.5/lib/i18n/backend/chain.rb:28:in `block in reload!'
/usr/local/rvm/gems/ruby-2.3.1/gems/i18n-0.9.5/lib/i18n/backend/chain.rb:28:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/i18n-0.9.5/lib/i18n/backend/chain.rb:28:in `reload!'
/usr/local/rvm/gems/ruby-2.3.1/gems/i18n-0.9.5/lib/i18n/config.rb:133:in `load_path='
/usr/local/rvm/gems/ruby-2.3.1/gems/i18n-0.9.5/lib/i18n.rb:43:in `load_path='
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.1/lib/active_support/i18n_railtie.rb:47:in `block in initialize_i18n'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.1/lib/active_support/i18n_railtie.rb:41:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.1/lib/active_support/i18n_railtie.rb:41:in `initialize_i18n'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.1/lib/active_support/i18n_railtie.rb:15:in `block in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.1/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.1/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.1/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.1/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.1/lib/active_support/lazy_load_hooks.rb:49:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.7.1/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.7.1/lib/rails/application/finisher.rb:65:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.7.1/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.7.1/lib/rails/application.rb:352:in `initialize!'
/home/deploy/setup/last_try/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.7.1/lib/rails/application.rb:328:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.7.1/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.7.1/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
D, [2019-03-05T19:33:38.710345 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.find | STARTED | {"find"=>"i18n", "filter"=>{}, "lsid"=>{"id"=><BSON::Binary:0x108214660 type=uuid data=0x7c33494fcaf54a26...>}}
D, [2019-03-05T19:33:38.711192 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.find | SUCCEEDED | 0.000s
D, [2019-03-05T19:33:38.734405 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.find | FAILED | stack level too deep | 0.000947437s
D, [2019-03-05T19:33:38.788564 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | admin.endSessions | STARTED | {"endSessions"=>[{"id"=><BSON::Binary:0x63649180 type=uuid data=0xd3a201bbaf904a3d...>}, {"id"=><BSON::Binary:0x54806320 type=uuid data=0x61657459f303432c...>}, {"id"=><BSON::Binary:0x54607780 type=uuid data=0x26abb6a265594b13...>}, {"id"=><BSON::Bina...
D, [2019-03-05T19:33:38.789893 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | admin.endSessions | SUCCEEDED | 0.003s
D, [2019-03-05T19:33:38.790498 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.killCursors | STARTED | {"killCursors"=>"i18n", "cursors"=>[25178977312]}
D, [2019-03-05T19:33:38.790756 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.killCursors | SUCCEEDED | 0.000s
D, [2019-03-05T19:33:38.791005 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.killCursors | STARTED | {"killCursors"=>"i18n", "cursors"=>[23080764937]}
D, [2019-03-05T19:33:38.791240 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.killCursors | SUCCEEDED | 0.000s
D, [2019-03-05T19:33:38.791465 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.killCursors | STARTED | {"killCursors"=>"i18n", "cursors"=>[21492846266]}
D, [2019-03-05T19:33:38.791660 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.killCursors | SUCCEEDED | 0.000s
D, [2019-03-05T19:33:38.791877 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.killCursors | STARTED | {"killCursors"=>"i18n", "cursors"=>[25399117075]}
D, [2019-03-05T19:33:38.792074 #3953] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.killCursors | SUCCEEDED | 0.000s
```

with a **cap production deploy**
```
D, [2019-03-05T19:44:04.651331 #11302] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.find | SUCCEEDED | 0.001s
D, [2019-03-05T19:44:04.651641 #11302] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.find | STARTED | {"find"=>"i18n", "filter"=>{}, "lsid"=>{"id"=><BSON::Binary:0x108050820 type=uuid data=0x3d891db3484e4594...>}}
D, [2019-03-05T19:44:04.652490 #11302] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.find | SUCCEEDED | 0.000s
D, [2019-03-05T19:44:04.652780 #11302] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.find | STARTED | {"find"=>"i18n", "filter"=>{}, "lsid"=>{"id"=><BSON::Binary:0x108176760 type=uuid data=0x2d996df82f434127...>}}
D, [2019-03-05T19:44:04.653617 #11302] DEBUG -- : MONGODB | 127.0.0.1:27017 | manhattan_production.find | SUCCEEDED | 0.000s
 DEBUG [22d022b2]       rake aborted!
 DEBUG [22d022b2]       SystemStackError: stack level too deep
 DEBUG [22d022b2]       /home/deploy/last_try/shared/bundle/ruby/2.3.0/gems/bson-4.3.0/lib/bson/document.rb:135:in `initialize'
/home/deploy/last_try/shared/bundle/ruby/2.3.0/gems/bson-4.3.0/lib/bson/hash.rb:65:in `new'
/home/deploy/last_try/shared/bundle/ruby/2.3.0/gems/bson-4.3.0/lib/bson/hash.rb:65:in `to_bson_normalized_value'
/home/deploy/last_try/shared/bundle/ruby/2.3.0/gems/bson-4.3.0/lib/bson/document.rb:202:in `convert_value'
/home/deploy/last_try/shared/bundle/ruby/2.3.0/gems/bson-4.3.0/lib/bson/document.rb:68:in `[]='
/home/deploy/last_try/shared/bundle/ruby/2.3.0/gems/bson-4.3.0/lib/bson/document.rb:136:in `block in initialize'
/home/deploy/last_try/shared/bundle/ruby/2.3.0/gems/bson-4.3.0/lib/bson/document.rb:136:in `each_pair'
/home/deploy/last_try/shared/bundle/ruby/2.3.0/gems/bson-4.3.0/lib/bson/document.rb:136:in `initialize'
```

centos 7
```
rvm list
=* ruby-2.3.1 [ x86_64 ]
```

What did I forget or do wrong?

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
