### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by CodingAnarchy** [rails/rails#35542]
### Expected behavior

Job should run to completion every time resque workers pull them.

### Actual behavior

Sporadically:

```
undefined method `[]' for nil:NilClass
/srv/app/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:391:in `active_connection?'
/srv/app/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:36:in `enable_query_cache!'
/srv/app/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/query_cache.rb:30:in `block in run'
/srv/app/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/query_cache.rb:30:in `each'
/srv/app/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/query_cache.rb:30:in `run'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:27:in `before'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:110:in `run!'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:72:in `block in run!'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:69:in `tap'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:69:in `run!'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:72:in `wrap'
/srv/app/shared/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `instance_exec'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:136:in `run_callbacks'
/srv/app/shared/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/execution.rb:22:in `execute'
/srv/app/shared/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/queue_adapters/resque_adapter.rb:47:in `perform'
```

Retrying the job works almost every time.

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.3

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?
