### ISSUE TITLE
Setting `inverse_of` on `belongs_to polymorphic: true` breaks `association.build`

### ISSUE THREAD

**Issue by allenwu1973** [rails/rails#35600]
### Steps to reproduce
https://gist.github.com/allenwu1973/9dadb3cba64733501f49b40de9dc112b

If I remove the inverse_of option, everything works as expected.
According to the documentation (as changed in #31446), `inverse_of` should work with polymorphic associations.

### Expected behavior
It should work just like if `inverse_of` is not set.

### Actual behavior
```
ArgumentError: Polymorphic association does not support to compute class.
    ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/reflection.rb:420:in `compute_class'
    ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/reflection.rb:379:in `klass'
    ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/reflection.rb:234:in `inverse_of'
    ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/associations/through_association.rb:110:in `build_record'
    ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/associations/has_many_through_association.rb:93:in `build_record'
    ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/associations/collection_association.rb:108:in `build'
    ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/associations/collection_proxy.rb:319:in `build'
    test.rb:56:in `test_association_stuff'
```

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.1

**Comment by allenwu1973** [comment]
This is still reproducible on 5.2 and 6.0.0.rc1
