### ISSUE TITLE
actiontext test fails ActionText::FormHelperTest

### ISSUE THREAD

**Issue by azbshiri** [rails/rails#35644]
### Steps to reproduce
Cloned project
Installed dependencies (using ruby 2.5.3)
Go to actiontext/
Run `./bin/test`

Seems that `/active_support/testing/declarative.rb` having issues with recognizing test descriptions

### Expected behavior
```
Run options: --seed 57615

# Running:

........

Finished in 0.419932s, 19.0507 runs/s, 35.7201 assertions/s.
8 runs, 15 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior
```
Traceback (most recent call last):
	14: from ./bin/test:5:in `<main>'
	13: from ./bin/test:5:in `require_relative'
	12: from /Users/alireza/github.com/rails/tools/test.rb:26:in `<top (required)>'
	11: from /Users/alireza/github.com/rails/railties/lib/rails/test_unit/runner.rb:39:in `run'
	10: from /Users/alireza/github.com/rails/railties/lib/rails/test_unit/runner.rb:50:in `load_tests'
	 9: from /Users/alireza/github.com/rails/railties/lib/rails/test_unit/runner.rb:50:in `each'
	 8: from /Users/alireza/github.com/rails/railties/lib/rails/test_unit/runner.rb:50:in `block in load_tests'
	 7: from /Users/alireza/github.com/rails/activesupport/lib/active_support/dependencies.rb:297:in `require'
	 6: from /Users/alireza/github.com/rails/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
	 5: from /Users/alireza/github.com/rails/activesupport/lib/active_support/dependencies.rb:297:in `block in require'
	 4: from /Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.3.3/lib/zeitwerk/kernel.rb:23:in `require'
	 3: from /Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.3.3/lib/zeitwerk/kernel.rb:23:in `require'
	 2: from /Users/alireza/github.com/rails/actiontext/test/dummy/node_modules/@rails/actiontext/test/template/form_helper_test.rb:5:in `<top (required)>'
	 1: from /Users/alireza/github.com/rails/actiontext/test/dummy/node_modules/@rails/actiontext/test/template/form_helper_test.rb:28:in `<class:FormHelperTest>'
/Users/alireza/github.com/rails/activesupport/lib/active_support/testing/declarative.rb:16:in `test': test_form_with_rich_text_area is already defined in ActionText::FormHelperTest (RuntimeError)
```

### System configuration
**Rails version**:
5.2.2
**Ruby version**:
2.5.3

**Comment by y-yagi** [comment]
Thanks for your report, but I cannot reproduce. 

``` 
$ ./bin/test --seed 57615 -v
Run options: --seed 57615 -v

# Running:

ActionText::FormHelperTest#test_form_with_rich_text_area_for_non-attribute = 0.02 s = .
ActionText::FormHelperTest#test_form_with_rich_text_area = 0.04 s = .
ActionText::FormHelperTest#test_form_with_rich_text_area_having_placeholder_with_locale = 0.01 s = .
ActionText::FormHelperTest#test_modelless_form_with_rich_text_area = 0.00 s = .
ActionText::FormHelperTest#test_form_with_rich_text_area_having_class = 0.00 s = .
ActionText::FormHelperTest#test_form_with_rich_text_area_having_placeholder_without_locale = 0.01 s = .
ActionText::ContentTest#test_extracts_links = 0.02 s = .
ActionText::ContentTest#test_canonicalizes_attachment_gallery_markup = 0.02 s = .
ActionText::ContentTest#test_canonicalizes_nested_attachment_gallery_markup = 0.01 s = .
ActionText::ContentTest#test_converts_Trix-formatted_attachments = 0.00 s = .
ActionText::ContentTest#test_marshal_serialization = 0.01 s = .
ActionText::ContentTest#test_equality = 0.00 s = .
ActionText::ContentTest#test_extracts_attachables = 0.08 s = .
ActionText::ContentTest#test_ignores_Trix-formatted_attachments_with_malformed_JSON = 0.00 s = .
ActionText::ContentTest#test_identifies_destroyed_attachables_as_missing = 0.03 s = .
ActionText::ContentTest#test_minifies_attachment_markup = 0.00 s = .
ActionText::ContentTest#test_extracts_remote_image_attachables = 0.00 s = .
ActionText::ContentTest#test_canonicalizes_attachment_gallery_markup_with_whitespace = 0.01 s = .
ActionText::ContentTest#test_extracts_missing_attachables = 0.00 s = .
ActionText::ContentTest#test_roundtrips_HTML_without_additional_newlines = 0.00 s = .
ActionText::PlainTextConversionTest#test_<br>_tags_are_separated_by_one_new_line = 0.00 s = .
ActionText::PlainTextConversionTest#test_<p>_tags_are_separated_by_two_new_lines = 0.00 s = .
ActionText::PlainTextConversionTest#test_preserves_non-linebreak_whitespace_after_text = 0.00 s = .
ActionText::PlainTextConversionTest#test_<h1>_tags_are_separated_by_two_new_lines = 0.00 s = .
ActionText::PlainTextConversionTest#test_preserves_trailing_linebreaks_after_text = 0.00 s = .
ActionText::PlainTextConversionTest#test_<action-text-attachment>_tags_are_converted_to_their_plain-text_representation = 0.00 s = .
ActionText::PlainTextConversionTest#test_<div>_tags_are_separated_by_one_new_line = 0.00 s = .
ActionText::PlainTextConversionTest#test_<blockquote>_tags_are_separated_by_two_new_lines = 0.00 s = .
ActionText::PlainTextConversionTest#test_<li>_tags_without_a_parent_list = 0.00 s = .
ActionText::PlainTextConversionTest#test_<ol>_tags_are_separated_by_two_new_lines = 0.00 s = .
ActionText::PlainTextConversionTest#test_<ul>_tags_are_separated_by_two_new_lines = 0.00 s = .
ActionText::PlainTextConversionTest#test_<li>_tags_are_separated_by_one_new_line = 0.00 s = .
ActionText::TrixAttachmentTest#test_#attributes_strips_unmappable_attributes = 0.00 s = .
ActionText::TrixAttachmentTest#test_filesize_is_typecast_when_integer-like = 0.00 s = .
ActionText::TrixAttachmentTest#test_previewable_is_typecast = 0.00 s = .
ActionText::TrixAttachmentTest#test_from_attributes = 0.00 s = .
ActionText::AttachmentTest#test_defaults_trix_partial_to_model_partial = 0.01 s = .
ActionText::AttachmentTest#test_converts_to_TrixAttachment_with_content = 0.02 s = .
ActionText::AttachmentTest#test_proxies_missing_methods_to_attachable = 0.01 s = .
ActionText::AttachmentTest#test_converts_to_TrixAttachment = 0.02 s = .
ActionText::AttachmentTest#test_proxies_#to_param_to_attachable = 0.01 s = .
ActionText::AttachmentTest#test_from_attachable = 0.02 s = .
ActionText::ModelTest#test_embed_extraction_only_extracts_file_attachments = 0.06 s = .
ActionText::ModelTest#test_embed_extraction = 0.04 s = .
ActionText::ModelTest#test_plain_text_conversion = 0.00 s = .
ActionText::ModelTest#test_saving_content = 0.01 s = .
ActionText::ModelTest#test_with_blank_content = 0.01 s = .
ActionText::ModelTest#test_html_conversion = 0.00 s = .
ActionText::ModelTest#test_save_body = 0.02 s = .
ActionText::ModelTest#test_without_content = 0.01 s = .

Finished in 0.558266s, 89.5630 runs/s, 161.2133 assertions/s.
50 runs, 90 assertions, 0 failures, 0 errors, 0 skips
``` 

Is it reproducible? Also, what happens if run `bundle exec rake test`

**Comment by azbshiri** [comment]
```
/Users/alireza/.rbenv/versions/2.5.3/bin/ruby -w -I"lib:test" -I"/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib" "/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/template/form_helper_test.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/unit/attachment_test.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/unit/content_test.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/unit/model_test.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/unit/plain_text_conversion_test.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/unit/trix_attachment_test.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/test/models/post_test.rb" "test/dummy/node_modules/@rails/actiontext/test/template/form_helper_test.rb" "test/dummy/node_modules/@rails/actiontext/test/unit/attachment_test.rb" "test/dummy/node_modules/@rails/actiontext/test/unit/content_test.rb" "test/dummy/node_modules/@rails/actiontext/test/unit/model_test.rb" "test/dummy/node_modules/@rails/actiontext/test/unit/plain_text_conversion_test.rb" "test/dummy/node_modules/@rails/actiontext/test/unit/trix_attachment_test.rb" "test/dummy/node_modules/actiontext/test/dummy/node_modules/actiontext/test/template/form_helper_test.rb" "test/dummy/node_modules/actiontext/test/dummy/node_modules/actiontext/test/unit/attachment_test.rb" "test/dummy/node_modules/actiontext/test/dummy/node_modules/actiontext/test/unit/content_test.rb" "test/dummy/node_modules/actiontext/test/dummy/node_modules/actiontext/test/unit/model_test.rb" "test/dummy/node_modules/actiontext/test/dummy/node_modules/actiontext/test/unit/plain_text_conversion_test.rb" "test/dummy/node_modules/actiontext/test/dummy/node_modules/actiontext/test/unit/trix_attachment_test.rb" "test/dummy/node_modules/actiontext/test/dummy/test/models/post_test.rb" "test/dummy/node_modules/actiontext/test/template/form_helper_test.rb" "test/dummy/node_modules/actiontext/test/unit/attachment_test.rb" "test/dummy/node_modules/actiontext/test/unit/content_test.rb" "test/dummy/node_modules/actiontext/test/unit/model_test.rb" "test/dummy/node_modules/actiontext/test/unit/plain_text_conversion_test.rb" "test/dummy/node_modules/actiontext/test/unit/trix_attachment_test.rb" "test/template/form_helper_test.rb" "test/unit/attachment_test.rb" "test/unit/content_test.rb" "test/unit/model_test.rb" "test/unit/plain_text_conversion_test.rb" "test/unit/trix_attachment_test.rb" 
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32454: warning: statement not reached
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32615: warning: statement not reached
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32651: warning: statement not reached
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32740: warning: statement not reached
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32756: warning: statement not reached
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32822: warning: statement not reached
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32863: warning: statement not reached
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32888: warning: statement not reached
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:31984: warning: assigned but unused variable - testEof
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/addressable-2.5.2/lib/addressable/idna/pure.rb:154: warning: assigned but unused variable - startercc
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sass-3.7.2/lib/sass/script/functions.rb:2911: warning: assigned but unused variable - value
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:370: warning: assigned but unused variable - pathlen
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:51: warning: method redefined; discarding old initialize
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_cert
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_file
/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_path
/Users/alireza/github.com/rails/actiontext/test/dummy/node_modules/@rails/actiontext/test/template/form_helper_test.rb:8: warning: method redefined; discarding old form_with
/Users/alireza/github.com/rails/actiontext/test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/template/form_helper_test.rb:8: warning: previous definition of form_with was here
/Users/alireza/github.com/rails/activesupport/lib/active_support/testing/declarative.rb:16:in `test': test_form_with_rich_text_area is already defined in ActionText::FormHelperTest (RuntimeError)
	from /Users/alireza/github.com/rails/actiontext/test/dummy/node_modules/@rails/actiontext/test/template/form_helper_test.rb:28:in `<class:FormHelperTest>'
	from /Users/alireza/github.com/rails/actiontext/test/dummy/node_modules/@rails/actiontext/test/template/form_helper_test.rb:5:in `<top (required)>'
	from /Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.4.3/lib/zeitwerk/kernel.rb:23:in `require'
	from /Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-1.4.3/lib/zeitwerk/kernel.rb:23:in `require'
	from /Users/alireza/github.com/rails/activesupport/lib/active_support/dependencies.rb:297:in `block in require'
	from /Users/alireza/github.com/rails/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
	from /Users/alireza/github.com/rails/activesupport/lib/active_support/dependencies.rb:297:in `require'
	from /Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	from /Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:5:in `select'
	from /Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:5:in `<main>'
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -I"/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib" "/Users/alireza/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/template/form_helper_test.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/unit/attachment_test.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/unit/content_test.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/unit/model_test.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/unit/plain_text_conversion_test.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/node_modules/actiontext/test/unit/trix_attachment_test.rb" "test/dummy/node_modules/@rails/actiontext/test/dummy/test/models/post_test.rb" "test/dummy/node_modules/@rails/actiontext/test/template/form_helper_test.rb" "test/dummy/node_modules/@rails/actiontext/test/unit/attachment_test.rb" "test/dummy/node_modules/@rails/actiontext/test/unit/content_test.rb" "test/dummy/node_modules/@rails/actiontext/test/unit/model_test.rb" "test/dummy/node_modules/@rails/actiontext/test/unit/plain_text_conversion_test.rb" "test/dummy/node_modules/@rails/actiontext/test/unit/trix_attachment_test.rb" "test/dummy/node_modules/actiontext/test/dummy/node_modules/actiontext/test/template/form_helper_test.rb" "test/dummy/node_modules/actiontext/test/dummy/node_modules/actiontext/test/unit/attachment_test.rb" "test/dummy/node_modules/actiontext/test/dummy/node_modules/actiontext/test/unit/content_test.rb" "test/dummy/node_modules/actiontext/test/dummy/node_modules/actiontext/test/unit/model_test.rb" "test/dummy/node_modules/actiontext/test/dummy/node_modules/actiontext/test/unit/plain_text_conversion_test.rb" "test/dummy/node_modules/actiontext/test/dummy/node_modules/actiontext/test/unit/trix_attachment_test.rb" "test/dummy/node_modules/actiontext/test/dummy/test/models/post_test.rb" "test/dummy/node_modules/actiontext/test/template/form_helper_test.rb" "test/dummy/node_modules/actiontext/test/unit/attachment_test.rb" "test/dummy/node_modules/actiontext/test/unit/content_test.rb" "test/dummy/node_modules/actiontext/test/unit/model_test.rb" "test/dummy/node_modules/actiontext/test/unit/plain_text_conversion_test.rb" "test/dummy/node_modules/actiontext/test/unit/trix_attachment_test.rb" "test/template/form_helper_test.rb" "test/unit/attachment_test.rb" "test/unit/content_test.rb" "test/unit/model_test.rb" "test/unit/plain_text_conversion_test.rb" "test/unit/trix_attachment_test.rb" ]
/Users/alireza/.rbenv/versions/2.5.3/bin/bundle:30:in `block in <main>'
/Users/alireza/.rbenv/versions/2.5.3/bin/bundle:22:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

Same result @y-yagi

**Comment by azbshiri** [comment]
It was just a node_modules directory in which there was exact same dummy app as top-level, so my bad.
