### ISSUE TITLE
Getting error on DB create. undefined method `raise_in_transactional_callbacks=' - Rails 5.2.2.1

### ISSUE THREAD

**Issue by ITDevMohsin** [rails/rails#35671]
Hi,

I have created new application. Then I installed latest Ruby and Rails versions but I got error on creating database.

The error is something like: 
```
NoMethodError: undefined method `raise_in_transactional_callbacks=' for ActiveRecord::Base:Class
```

Gem File:
```
ruby '2.5.5'
gem 'rails', '5.2.2.1'
```

```
muhammad@muhammad-mohsin:~/workspace_ror/twitter-clone$ rails -v
Rails 5.2.2.1
muhammad@muhammad-mohsin:~/workspace_ror/twitter-clone$ ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
muhammad@muhammad-mohsin:~/workspace_ror/twitter-clone$ rake db:create
rake aborted!
NoMethodError: undefined method `raise_in_transactional_callbacks=' for ActiveRecord::Base:Class
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.2.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.2.1/lib/active_record/railtie.rb:124:in `block (3 levels) in <class:Railtie>'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.2.1/lib/active_record/railtie.rb:123:in `each'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.2.1/lib/active_record/railtie.rb:123:in `block (2 levels) in <class:Railtie>'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.2.1/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.2.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.2.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.2.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.2.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.2.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.2.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.2.1/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.2.1/lib/active_record/base.rb:27:in `<top (required)>'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.2.1/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/home/muhammad/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/muhammad/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/home/muhammad/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:create => db:load_config
(See full trace by running task with --trace)
```

So, I comment that like and it appeared to work perfectly.

```
module TwitterClone
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    # config.i18n.default_locale = :de

    # Do not swallow errors in after_commit/after_rollback callbacks.
    # config.active_record.raise_in_transactional_callbacks = true
  end
end
```

Should I need to consider something else here?

**Comment by rafaelfranca** [comment]
`raise_in_transactional_callbacks` doesn't exist in Rails 5.2 anymore. It was deprecated in Rails 5.1 and removed in 5.2

**Comment by ITDevMohsin** [comment]
@rafaelfranca 
That's right but when I came up with new installation just like I have showed my steps and process then why its still showing me in application.rb file?
I know its deprecated but my concerns was to see why its popping up in my installation again?
I posted on slack channel as well but didn't get reasonable answer. I was curious so finding the reason.

**Comment by rafaelfranca** [comment]
Which version did you use to generate the Rails application? Rails 5.2 don't generate that line.

**Comment by ITDevMohsin** [comment]
I simply create the new application. Then, I update the gem version in my GEM File and did bundle install.
Is there anything wrong in it?
Can you explain the procedure if its wrong?
Is it something like install rails first and then create application or what?

**Comment by rafaelfranca** [comment]
If you create the new application in the Rails version 5.0.2 for example you can't upgrade to 5.2.2.1 and expect it to work without any code change to the application. Those versions are not backwards compatible.

**Comment by ITDevMohsin** [comment]
I see. It makes sense and that's right. :)

**Comment by saydulk** [comment]
I am using Rails 5.2.3

/usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `raise_in_transactional_callbacks=' for ActiveRecord::Base:Class (NoMethodError)


![Screenshot from 2019-09-25 19-33-30](https://user-images.githubusercontent.com/1058663/65605720-6b1e1700-dfcb-11e9-882b-3494612c227e.png)
