### ISSUE TITLE
[guides] `formats=': Invalid formats: "html"

### ISSUE THREAD

**Issue by localhostdotdev** [rails/rails#35697]
### Steps to reproduce

- `git clone https://github.com/rails/rails`
- `bundle`
- `rake guides:generate:html`

### Expected behavior

Generates HTML for the guides.

### Actual behavior

Throws an error:

```
actionview/lib/action_view/lookup_context.rb:301:in `formats=': Invalid formats: "html" (ArgumentError)
	from actionview/lib/action_view/renderer/abstract_renderer.rb:103:in `prepend_formats'
	from actionview/lib/action_view/renderer/template_renderer.rb:13:in `render'
	from actionview/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
	from actionview/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
	from actionview/lib/action_view/renderer/renderer.rb:22:in `render'
	from actionview/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
	from actionview/lib/action_view/base.rb:304:in `in_rendering_context'
	from actionview/lib/action_view/helpers/rendering_helper.rb:30:in `render'
	from guides/rails_guides/generator.rb:167:in `generate_guide'
	from guides/rails_guides/generator.rb:94:in `block in generate_guides'
	from guides/rails_guides/generator.rb:92:in `each'
	from guides/rails_guides/generator.rb:92:in `generate_guides'
	from guides/rails_guides/generator.rb:40:in `generate'
	from rails_guides.rb:30:in `<main>'
```

### System configuration

**Rails version**: 6.0.0 master, efb706daad0e2e1039c6abb4879c837ef8bf4d10
**Ruby version**: ruby-head, `ruby 2.7.0dev (2019-03-18 trunk 67296) [x86_64-darwin17]`

## Additional information

At some points the `values` of the formats is  `[:html, "html"]`, `:html` coming from the template format, and `"html"` from `@lookup_context.formats`. Then `:html` get filtered out as a valid value, but not `"html"`.

Pretty sure this has to do with the recent format vulnerability thing.

Looking into it (I just want to build the docs for rails/rails-docs-server :) ) but I'm definitely not an ActionView expert :D.

**Comment by localhostdotdev** [comment]
Obvious hotfix, but not clear what's the root cause:

```
diff --git a/actionview/lib/action_view/lookup_context.rb b/actionview/lib/action_view/lookup_context.rb
index fd3d025cbf..c301c9c663 100644
--- a/actionview/lib/action_view/lookup_context.rb
+++ b/actionview/lib/action_view/lookup_context.rb
@@ -284,7 +284,7 @@ def formats=(values)
         values.concat(default_formats) if values.delete "*/*"
         values.uniq!

-        invalid_values = (values - Template::Types.symbols)
+        invalid_values = (values.map(&:to_sym) - Template::Types.symbols)
         unless invalid_values.empty?
           raise ArgumentError, "Invalid formats: #{invalid_values.map(&:inspect).join(", ")}"
         end
```

**Comment by rafaelfranca** [comment]
This is a problem in the guides generator itself. It should be sending symbols, not strings as the `formats:` option.

**Comment by localhostdotdev** [comment]
Feels like I'm quick-fixing it, but this might be the correct way:

```
diff --git a/guides/rails_guides/generator.rb b/guides/rails_guides/generator.rb
index c3b77aa7bb..7d4a15962c 100644
--- a/guides/rails_guides/generator.rb
+++ b/guides/rails_guides/generator.rb
@@ -164,7 +164,7 @@ def generate_guide(guide, output_file)

           # Generate the special pages like the home.
           # Passing a template handler in the template name is deprecated. So pass the file name without the extension.
-          result = view.render(layout: layout, formats: [$1], file: $`)
+          result = view.render(layout: layout, formats: [$1.to_sym], file: $`)
         else
           body = File.read("#{@source_dir}/#{guide}")
           result = RailsGuides::Markdown.new(
```

**Comment by rafaelfranca** [comment]
Yeah. That one seems correct to me.
