### ISSUE TITLE
Impossible to create column decimal/numeric with default value in PG

### ISSUE THREAD

**Issue by MathieuDerelle** [rails/rails#35744]
### Steps to reproduce

```
class CreateFoos < ActiveRecord::Migration[5.2]
  def change
    create_table :foos do |t|
      t.numeric :bar, default: 0.0
      t.decimal :baz, default: 0.0
    end
  end
end
```

I could not reproduce in a fresh repo. 
I have updated rails and pg gems in my project to match those of the new project and still got the same error

Using 2 steps like this 
```
class CreateFoos < ActiveRecord::Migration[5.2]
  def change
    create_table :foos do |t|
      t.numeric :bar
      t.decimal :baz
    end
    change_column :foos, :bar, :numeric, default: 0.0
    change_column :foos, :baz, :decimal, default: 0.0
  end
end
```
does not raise  (migration pass with success)

any clue on what's wrong ?

### Expected behavior
Migration should pass with success

### Actual behavior

I get the error : NoMethodError: undefined method `oid' for #<ActiveRecord::ConnectionAdapters::ColumnDefinition:0x00007fc4344966a0>

full trace : 
```
rake db:migrate --trace                    
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:migrate
== 20190325133907 CreateFoos: migrating =======================================
-- create_table(:foos)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `oid' for #<ActiveRecord::ConnectionAdapters::ColumnDefinition:0x00007fbaef5b9508>
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql/quoting.rb:78:in `lookup_cast_type_from_column'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/quoting.rb:48:in `type_cast_from_column'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql/quoting.rb:70:in `quote_default_expression'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:19:in `quote_default_expression'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:106:in `add_column_options!'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql/schema_creation.rb:24:in `add_column_options!'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:36:in `visit_ColumnDefinition'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:16:in `accept'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:47:in `block in visit_TableDefinition'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:47:in `map'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:47:in `visit_TableDefinition'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:16:in `accept'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:311:in `create_table'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:871:in `block in method_missing'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:840:in `block in say_with_time'
/Users/mathieu/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:840:in `say_with_time'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:860:in `method_missing'
/Users/mathieu/Documents/github_purchease/receipt_processing/db/migrate/20190325133907_create_foos.rb:3:in `change'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:814:in `exec_migration'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/Users/mathieu/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:797:in `block in migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:796:in `migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:977:in `migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/mathieu/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/transactions.rb:212:in `transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1343:in `ddl_transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1262:in `each'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1210:in `migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1036:in `up'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1011:in `migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/airbrake-7.4.0/lib/airbrake/rake.rb:17:in `execute'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/mathieu/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/mathieu/.rvm/gems/ruby-2.4.3/bin/rake:23:in `load'
/Users/mathieu/.rvm/gems/ruby-2.4.3/bin/rake:23:in `<main>'
/Users/mathieu/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
/Users/mathieu/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
NoMethodError: undefined method `oid' for #<ActiveRecord::ConnectionAdapters::ColumnDefinition:0x00007fbaef5b9508>
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql/quoting.rb:78:in `lookup_cast_type_from_column'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/quoting.rb:48:in `type_cast_from_column'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql/quoting.rb:70:in `quote_default_expression'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:19:in `quote_default_expression'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:106:in `add_column_options!'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql/schema_creation.rb:24:in `add_column_options!'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:36:in `visit_ColumnDefinition'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:16:in `accept'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:47:in `block in visit_TableDefinition'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:47:in `map'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:47:in `visit_TableDefinition'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:16:in `accept'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:311:in `create_table'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:871:in `block in method_missing'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:840:in `block in say_with_time'
/Users/mathieu/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:840:in `say_with_time'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:860:in `method_missing'
/Users/mathieu/Documents/github_purchease/receipt_processing/db/migrate/20190325133907_create_foos.rb:3:in `change'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:814:in `exec_migration'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/Users/mathieu/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:797:in `block in migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:796:in `migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:977:in `migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/mathieu/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/transactions.rb:212:in `transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1343:in `ddl_transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1262:in `each'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1210:in `migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1036:in `up'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1011:in `migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/activerecord-5.2.2.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/airbrake-7.4.0/lib/airbrake/rake.rb:17:in `execute'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/mathieu/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/Users/mathieu/.rvm/gems/ruby-2.4.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/mathieu/.rvm/gems/ruby-2.4.3/bin/rake:23:in `load'
/Users/mathieu/.rvm/gems/ruby-2.4.3/bin/rake:23:in `<main>'
/Users/mathieu/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
/Users/mathieu/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
```

### System configuration
2 configs tested and failing 

1.

**Rails version**: 5.1.6.2
**Ruby version**: 2.4.3

**Gem pg**: 0.21.0
**PG DB** : 9.4.19

2.

**Rails version**: 5.2.2.1 
**Ruby version**: 2.4.3

**Gem pg**: 1.1.4
**PG DB** : 9.4.19

**Comment by alexcameron89** [comment]
Hey @MathieuDerelle, I [tried to reproduce the problem on Rails 5.2.2.1](https://gist.github.com/alexcameron89/9232a1f398ac713adcd02a4c1372b262), but I was not able to, and it sounds like you had the same experience. I'm not sure why you're hitting that issue, but I'm guessing that it has to do with something in your app's configuration.

If you are able to do some more digging and find that it is a Rails issue, I'll be glad to take a look at it.
