### ISSUE TITLE
Acronym inflector causing error in ActiveRecord associations

### ISSUE THREAD

**Issue by ziinfo** [rails/rails#35769]
### Steps to reproduce
Provided we have associated model  
```ruby
class Dashboard < ApplicationRecord
  has_many :widgets
end
```
And acronym inflector for "any"  
``` ruby
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym "any"`
end
```
Attempt to access associated records  
```ruby
Dashboard.new.widgets
```
Rises exception  
`LoadError (cannot load such file -- active_record/associations/has_m_any_association):`

[Sample app](https://github.com/ziinfo/inflect)

### Expected behavior
Inflector should not affect ActiveRecord associations

### Actual behavior
Attempt to access associated will raise exception  
`LoadError (cannot load such file -- active_record/associations/has_m_any_association):`

### System configuration
**Rails version**: `5.2.2`

**Ruby version**: `2.5.3`

**Comment by rafaelfranca** [comment]
Can you provide the full backtrace or 
could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by ziinfo** [comment]
Here you go. I also created an [app](https://github.com/ziinfo/inflect) that reproduces this error
```
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:40:in `rescue in require'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:26:in `require'
activesupport (5.2.2.1) lib/active_support/dependencies.rb:291:in `block in require'
activesupport (5.2.2.1) lib/active_support/dependencies.rb:257:in `load_dependency'
activesupport (5.2.2.1) lib/active_support/dependencies.rb:291:in `require'
activerecord (5.2.2.1) lib/active_record/reflection.rb:684:in `association_class'
activerecord (5.2.2.1) lib/active_record/associations.rb:237:in `association'
activerecord (5.2.2.1) lib/active_record/associations/builder/association.rb:108:in `widgets'
app/views/dashboards/index.html.erb:6:in `block in _app_views_dashboards_index_html_erb__1785694299262908469_70182788202180'
activerecord (5.2.2.1) lib/active_record/relation/delegation.rb:71:in `each'
activerecord (5.2.2.1) lib/active_record/relation/delegation.rb:71:in `each'
app/views/dashboards/index.html.erb:2:in `_app_views_dashboards_index_html_erb__1785694299262908469_70182788202180'
actionview (5.2.2.1) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.2.1) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.2.1) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.2.1) lib/action_view/template.rb:157:in `render'
actionview (5.2.2.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.2.2.1) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.2.1) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.2.1) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.2.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.2.2.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.2.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.2.2.1) lib/action_view/renderer/template_renderer.rb:16:in `render'
actionview (5.2.2.1) lib/action_view/renderer/renderer.rb:44:in `render_template'
actionview (5.2.2.1) lib/action_view/renderer/renderer.rb:25:in `render'
actionview (5.2.2.1) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.2.2.1) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionview (5.2.2.1) lib/action_view/rendering.rb:84:in `render_to_body'
actionpack (5.2.2.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.2.2.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.2.2.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (5.2.2.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.2.2.1) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
activesupport (5.2.2.1) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/Users/wally/.rbenv/versions/2.5.3/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
activesupport (5.2.2.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (5.2.2.1) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (5.2.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.2.2.1) lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
actionpack (5.2.2.1) lib/action_controller/metal/instrumentation.rb:45:in `render'
actionpack (5.2.2.1) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (5.2.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
actionpack (5.2.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
actionpack (5.2.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.2.1) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.2.1) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.2.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.2.1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.2.1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.2.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.2.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
actionpack (5.2.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.2.1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.2.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.2.2.1) lib/rails/engine.rb:524:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by matthewd** [comment]
`"any"` doesn't sound like much of an acronym... I wonder if we should validate that the argument starts with an uppercase letter.

@ziinfo could you describe your use case?

**Comment by ziinfo** [comment]
@matthewd you're absolutely right, it doesn't. I needed to prevent titleizing strings like "and", "of", and "any". I thought using acronym inflector would be a perfect solution

**Comment by rafaelfranca** [comment]
The inflector definitely have effect on how rails loads constants, not only its own constants but also constants on the application. If you change the inflector, you will change where a constant will be looked. This is how we make things like `GoogleAPI` be searched at `google_api` instead `google_a_p_i`. We probably could fix this issue having an special inflector only for constant lookups. @fxn do you think it is possible?

**Comment by fxn** [comment]
In `:zeitwerk` mode in Rails 6 the support is builtin. By default you get an inflector that delegates to AS's `camelize`, but you can set a custom one. @casperisfine has done it for Shopify, for example (I am sure you know that).

In `:classic` mode that is not possible today, it uses AS's `underscore`, but could be possible.

**Comment by casperisfine** [comment]
> We probably could fix this issue having an special inflector only for constant lookups. 

That inflector is already used for constants lookup all around Rails, even with the classic autoloader.  `.camelize` and `.underscore` are effectively "subtitled" as '.convert_to_a_const_name' and `.convert_to_a_path`.

It's used to infer controller name from routes, model names from tables, etc etc. Having a separate inflector just for Zeitwerk/Classic autoloader would be weird and probably inconsistent.

That being said I agree that this global nature of the inflectors can sometimes lead to problematic scenarios.

**Comment by casperisfine** [comment]
> I needed to prevent titleizing strings like "and", "of", and "any". I thought using acronym inflector would be a perfect solution

Sounds like what you are looking for is an I18n enabled version of `titleize`. I just checked and I'm very surprised `titleize` isn't internationalized like `transliterate` is.

**Comment by casperisfine** [comment]
@ziinfo here's what I think you want: https://github.com/granth/titleize/blob/185a433ed2d40dbf86396be06c1414d55f9a6019/lib/titleize.rb

It's english only though.

**Comment by fxn** [comment]
The problem with an i18n `titleize` is that not even English has one set of rules. For example, the guidelines for guides picked [_one_ possible convention](https://guides.rubyonrails.org/ruby_on_rails_guides_guidelines.html#headings), but there are others. In Spanish or Catalan titles have no special capitalization... I bet this is a rabbit hole of a complexity outside the scope of AS.

**Comment by rafaelfranca** [comment]
I was thinking something in the line of `ActiveSupport::Inflector.inflections(:internal) do {}` and every place we use inflector internally we alway call with `:internal` instead of using the `:en` one.

**Comment by casperisfine** [comment]
> . I bet this is a rabbit hole of a complexity outside the scope of AS.

Yeah definitely. It's more something for `ruby-i18n` or `rails-i18n`. I wasn't suggesting we should implement that. Just trying to step back a bit on what the need described here actually is.

**Comment by matthewd** [comment]
This isn't a supported use of the acronym inflector. Even if we changed our internals to avoid this particular misinflection, you'd still have the problem that any use of "many" in your own titles would be mangled.

The acronym inflector's primary purpose is overriding the definition of where word boundaries occur -- the fact it forces casing afterwards is secondary. It's not an appropriate tool for this job.

**Comment by ziinfo** [comment]
@casperisfine that's exactly what I was looking for. cheers
