### ISSUE TITLE
YAML column can't load ActiveSupport::TimeWithZone with year >= 10000

### ISSUE THREAD

**Issue by jcbpl** [rails/rails#35783]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "byebug"
end

require "active_support"
require "active_support/core_ext/time"
require "active_record"
require "minitest/autorun"

Time.zone = 'UTC'

class YamlTimeWithZoneTest < Minitest::Test
  def test_yaml_time_with_zone
    time_with_zone = Time.zone.parse("10000-01-01 00:00:00 Z")
    coder = ActiveRecord::Coders::YAMLColumn.new(nil)

    yaml = coder.dump(time_with_zone)
    time = coder.load(yaml) # raises NoMethodError: undefined method `year'

    assert_equal time, time_with_zone
  end
end
```

### Expected behavior
The column loads the ActiveSupport::TimeWithZone instance.

### Actual behavior

`coder.load` raises:

```
Error:
YamlTimeWithZoneTest#test_yaml_time_with_zone:
NoMethodError: undefined method `year' for "10000-01-01 00:00:00.000000000 Z":String
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/bundler/gems/rails-e3f5f1c93686/activesupport/lib/active_support/time_with_zone.rb:543:in `transfer_time_values_to_utc_constructor'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/bundler/gems/rails-e3f5f1c93686/activesupport/lib/active_support/time_with_zone.rb:53:in `initialize'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/bundler/gems/rails-e3f5f1c93686/activesupport/lib/active_support/time_with_zone.rb:176:in `init_with'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:382:in `init_with'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:374:in `revive'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/2.6.0/psych/visitors/visitor.rb:16:in `visit'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/2.6.0/psych/visitors/visitor.rb:6:in `accept'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:32:in `accept'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/2.6.0/psych/visitors/visitor.rb:16:in `visit'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/2.6.0/psych/visitors/visitor.rb:6:in `accept'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:32:in `accept'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/2.6.0/psych/nodes/node.rb:50:in `to_ruby'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/2.6.0/psych.rb:279:in `load'
    /Users/jpaul/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/bundler/gems/rails-e3f5f1c93686/activerecord/lib/active_record/coders/yaml_column.rb:26:in `load'
    test_yaml_time_with_zone.rb:26:in `test_yaml_time_with_zone'
```

### System configuration
**Rails version**: master

**Ruby version**: 2.6.1

**Comment by jcbpl** [comment]
Probably a Psych issue; will close this for now.
