### ISSUE TITLE
undefined method `webpacker' for #<Rails::Application::Configuration

### ISSUE THREAD

**Issue by matheusvetor** [rails/rails#35801]
Steps to reproduce
I have an application that I upgraded from rails 5.1 to 6.0.0.beta3 (master). Since the upgrade, the app works fine local into in local development (inside docker) and staging with heroku. But for some reason in local development I can't make sidekiq run because I get the bellow error. Even running the tests i don't get that error: 
```
undefined method `webpacker' for #<Rails::Application::Configuration:0x0000560931a0a3d0>
```

My application does not have webpacker as dependency on my Gemfile:

```
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.1'

source 'https://rubygems.org'

gem 'rails', github: 'rails/rails'

gem 'rails-i18n'

gem 'puma'

gem 'bootsnap', require: false

gem 'pg'

gem 'uglifier'

gem 'sassc-rails'

gem 'slim-rails'

gem 'stringify_date'

gem 'jquery-rails'

gem 'jbuilder'

gem 'date_validator'

gem 'inherited_resources', github: 'activeadmin/inherited_resources'

gem 'devise'
gem 'devise-i18n'

gem 'cancancan'
gem 'simple_form'

gem 'aws-sdk-elastictranscoder'
gem 'carrierwave'
gem 'cocoon'
gem 'fog-aws'
gem 'mini_magick'
gem 'will_paginate'

gem 'sendgrid'

gem 'bootstrap', '~> 4'
gem 'font-awesome-rails'
gem 'select2-rails'

gem 'sidekiq'

gem 'streamio-ffmpeg'

gem 'ransack', github: 'activerecord-hackery/ransack'

group :development, :test do
  gem 'brakeman', require: false
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'fasterer'
  gem 'rails-controller-testing'
  gem 'rspec-rails'
  gem 'rubocop-rails_config', require: false
  gem 'rubycritic', require: false
  gem 'vcr'
  gem 'webmock'
end

group :development do
  # gem 'bullet'
  gem 'guard-rspec', require: false
  gem 'listen'
  gem 'simplecov', require: false
  gem 'spring'
  gem 'spring-watcher-listen'
end

group :test do
  gem 'database_cleaner'
  gem 'rspec-sidekiq'
  gem 'shoulda-matchers', github: 'thoughtbot/shoulda-matchers'
  gem 'timecop'
end
```

My `application.rb`
```
require "rails"
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "sprockets/railtie"

Bundler.require(*Rails.groups)

module SomeAppName
  class Application < Rails::Application
    config.load_defaults 6.0
  end
end
```

My `enviroments/development.rb`:

```
Rails.application.configure do
  config.cache_classes = false
  config.eager_load = false
  config.consider_all_requests_local = true

  if Rails.root.join('tmp', 'caching-dev.txt').exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true

    config.cache_store = :memory_store
    config.public_file_server.headers = {
      'Cache-Control' => "public, max-age=#{2.days.to_i}"
    }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  config.active_storage.service = :local
  config.action_mailer.raise_delivery_errors = false
  config.action_mailer.perform_caching = false
  config.active_support.deprecation = :log
  config.active_record.migration_error = :page_load
  config.active_record.verbose_query_logs = true
  config.assets.debug = true
  config.assets.quiet = true
  config.file_watcher = ActiveSupport::EventedFileUpdateChecker
end
```

The Sidekiq config:

```
redis_url = ENV.fetch('REDIS_URL', 'redis://localhost:6379/0')

module RedisClient
  class << self
    def redis
      @redis ||= Redis.new(url: redis_url)
    end
  end
end

sidekiq_config = { url: redis_url }

Sidekiq.configure_server do |config|
  config.redis = sidekiq_config
end

Sidekiq.configure_client do |config|
  config.redis = sidekiq_config
end
```

Actual behavior
The related error is when trying to run sidekiq (inside docker):

```
sidekiq_1  | undefined method `webpacker' for #<Rails::Application::Configuration:0x0000560931a0a3d0>
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/railtie/configuration.rb:97:in `method_missing'
sidekiq_1  | /app/config/environments/development.rb:3:in `block in <main>'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/railtie.rb:216:in `instance_eval'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/railtie.rb:216:in `configure'
sidekiq_1  | /app/config/environments/development.rb:1:in `<main>'
sidekiq_1  | /bundle/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
sidekiq_1  | /bundle/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
sidekiq_1  | /bundle/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
sidekiq_1  | /bundle/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
sidekiq_1  | /bundle/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/activesupport/lib/active_support/dependencies.rb:297:in `block in require'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/activesupport/lib/active_support/dependencies.rb:297:in `require'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/engine.rb:601:in `block (2 levels) in <class:Engine>'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/engine.rb:600:in `each'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/engine.rb:600:in `block in <class:Engine>'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/initializable.rb:32:in `instance_exec'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/initializable.rb:32:in `run'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/initializable.rb:50:in `each'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/initializable.rb:50:in `tsort_each_child'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:415:in `call'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
sidekiq_1  | /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/initializable.rb:60:in `run_initializers'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/railties/lib/rails/application.rb:362:in `initialize!'
sidekiq_1  | /app/config/environment.rb:5:in `<top (required)>'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/activesupport/lib/active_support/dependencies.rb:297:in `require'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/activesupport/lib/active_support/dependencies.rb:297:in `block in require'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/activesupport/lib/active_support/dependencies.rb:263:in `load_dependency'
sidekiq_1  | /bundle/bundler/gems/rails-c11d115fa3c5/activesupport/lib/active_support/dependencies.rb:297:in `require'
sidekiq_1  | /bundle/gems/sidekiq-5.2.5/lib/sidekiq/cli.rb:288:in `boot_system'
sidekiq_1  | /bundle/gems/sidekiq-5.2.5/lib/sidekiq/cli.rb:46:in `run'
sidekiq_1  | /bundle/gems/sidekiq-5.2.5/bin/sidekiq:12:in `<top (required)>'
sidekiq_1  | /bundle/bin/sidekiq:29:in `load'
sidekiq_1  | /bundle/bin/sidekiq:29:in `<top (required)>'
sidekiq_1  | /bundle/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
sidekiq_1  | /bundle/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
sidekiq_1  | /bundle/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
sidekiq_1  | /bundle/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
sidekiq_1  | /bundle/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
sidekiq_1  | /bundle/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
sidekiq_1  | /bundle/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
sidekiq_1  | /bundle/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
sidekiq_1  | /bundle/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
sidekiq_1  | /bundle/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
sidekiq_1  | /bundle/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
sidekiq_1  | /bundle/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
sidekiq_1  | /bundle/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
sidekiq_1  | /bundle/bin/bundle:104:in `load'
sidekiq_1  | /bundle/bin/bundle:104:in `<main>'
```

System configuration
Rails version:
6.0.0.beta3(master)

Ruby version:
2.6.1

I can provide a repo with a dummy clone of my project if its needed.

**Comment by y-yagi** [comment]
Can you please provide a dummy application that reproduces the issue?

**Comment by matheusvetor** [comment]
I'm closing this because I can't reproduce the error on a dummy version of my app. I think since I'm using the master branch maybe the problem is already fixed once i make the project up to date with master branch
