### ISSUE TITLE
(Time.zone.now.midnight..Time.current).minmax logs a warning for every second covered

### ISSUE THREAD

**Issue by meismann** [rails/rails#36170]
### Steps to reproduce
On IRB, execute
```
irb(main):001:0> require 'active_support/core_ext/numeric/time'
=> true
irb(main):002:0> Time.zone = 'Europe/Berlin'
=> "Europe/Berlin"
irb(main):003:0> (Time.zone.now.midnight..Time.current).minmax
```

### Expected behavior
Immediate return of the result, i.e. sth. like:
```
[Fri, 03 May 2019 00:00:00 CEST +02:00, Fri, 03 May 2019 10:31:47 CEST +02:00]
```

### Actual behavior
The result is returned, but a warning is logged a huge amount of times (for every second, as sb. has found out here: https://makandracards.com/ff-it/23966-fixing-the-warning-time-succ-is-obsolete-use-time-+-1):
```
/Users/user/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.3/lib/active_support/time_with_zone.rb:511: warning: Time#succ is obsolete; use time + 1
/Users/user/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.3/lib/active_support/time_with_zone.rb:511: warning: Time#succ is obsolete; use time + 1
[…]
/Users/user/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.3/lib/active_support/time_with_zone.rb:511: warning: Time#succ is obsolete; use time + 1
[Fri, 03 May 2019 00:00:00 BST +01:00, Fri, 03 May 2019 10:31:47 BST +01:00]
```
If it is true that Time#succ is called for each second in the range, beside the annoying screenloads of warnings this shows that Time#minmax is very inefficient. I suggest the responsible code to be rewritten. WDYT?

### System configuration
**Rails version**: activesupport (5.2.3)

**Ruby version**: 2.4.4 and 2.4.6

**Comment by y-yagi** [comment]
> irb> (Time.zone.midnight..Time.current).minmax

This script does not work. 

```
irb(main):009:0> (Time.zone.midnight..Time.current).minmax
Traceback (most recent call last):
        2: from (irb):9
        1: from (irb):9:in `rescue in irb_binding'
NoMethodError (undefined method `midnight' for #<ActiveSupport::TimeZone:0x0000556998d44bb0>) 
```

Maybe `(Time.zone.now.midnight..Time.current).minmax`? But that does not work also. 

```
irb(main):023:0> (Time.zone.now.midnight..Time.current).minmax
Traceback (most recent call last):
        3: from (irb):23
        2: from (irb):23:in `rescue in irb_binding'
        1: from (irb):23:in `minmax'
TypeError (can't iterate from ActiveSupport::TimeWithZone) 
```

**Comment by meismann** [comment]
Sorry, just updated the issue.

**Comment by st0012** [comment]
I also got `TypeError (can't iterate from ActiveSupport::TimeWithZone)` on `5.2`

**Comment by y-yagi** [comment]
I'm not sure your purpose, but your reproducing step missing load required files. Please require `active_support/all`. Then you will probably get an error as expected. 

``` 
irb(main):001:0> require "active_support"
=> true
irb(main):002:0>  require "active_support/all"
=> true
irb(main):003:0> Time.zone = 'Europe/Berlin'
=> "Europe/Berlin"
irb(main):004:0> (Time.zone.now.midnight..Time.current).minmax
Traceback (most recent call last):
        7: from /home/yaginuma/.rbenv/versions/2.6.2/bin/irb:23:in `<main>'
        6: from /home/yaginuma/.rbenv/versions/2.6.2/bin/irb:23:in `load'
        5: from /home/yaginuma/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        4: from (irb):4
        3: from (irb):4:in `minmax'
        2: from /home/yaginuma/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/core_ext/range/each.rb:8:in `each'
        1: from /home/yaginuma/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/core_ext/range/each.rb:20:in `ensure_iteration_allowed'
TypeError (can't iterate from ActiveSupport::TimeWithZone)
irb(main):005:0> 
``` 

If this result is not what you expect, please reopen it freely. Thanks.
