### ISSUE TITLE
db:create not working (PG::ConnectionBad)

### ISSUE THREAD

**Issue by msxavi** [rails/rails#36187]
### Steps to reproduce
When I had previously executed `db:drop` to remove databases, in the following environment:
```
Rails version: 5.2.3
pg gem version: 0.21.0
apartment gem version: 1.2.0
```
`db:create` fails **PG::ConnectionBad: FATAL:  database "myapp_development" does not exist**

**Works fine on Rails 5.1.6.2**

I also tried updating pg to latest version 1.1.4 unsuccessfully.

### Expected behaviour
` rails db:create` should create databases and display
```
Created database 'myapp_development'
Created database 'myapp_test'
```
### Actual behavior
```
Caused by:
PG::ConnectionBad: FATAL:  database "myapp_development" does not exist
/usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
/usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `new'
/usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `connect'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1014:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:90:in `connection'
/usr/local/bundle/gems/apartment-1.2.0/lib/apartment/adapters/postgresql_adapter.rb:40:in `reset'
/usr/local/bundle/gems/apartment-1.2.0/lib/apartment/adapters/postgresql_adapter.rb:31:in `initialize'
/usr/local/bundle/gems/apartment-1.2.0/lib/apartment/adapters/postgresql_adapter.rb:10:in `new'
```

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.5.5

**Comment by y-yagi** [comment]
It seems apartment's issue https://github.com/influitive/apartment/pull/546.
Please try to update apartment gem. Thanks.

**Comment by msxavi** [comment]
@y-yagi thanks for that. My searches didn't return `apartment` related issues. All good!
