### ISSUE TITLE
rails db:fixtures:load doesn't play nicely with ActiveRecord::FixtureSet.context_class

### ISSUE THREAD

**Issue by Medvezo** [rails/rails#36393]
### Steps to reproduce
Most of what I will describe is written up in the [following tutorial](https://brandonhilkert.com/blog/managing-login-passwords-for-capybara-with-minitest-and-rails-fixtures/ ).

**TL;DR:** Trying to make helper methods available in fixtures in order to avoid duplication. The way to accomplish that is to use` ActiveRecord::FixtureSet.context_class.include` method [described here](https://edgeapi.rubyonrails.org/classes/ActiveRecord/FixtureSet.html#class-ActiveRecord::FixtureSet-label-Dynamic+fixtures+with+ERB).

Helper methods we are trying to call inside the fixture:
```
module AuthenticationHelper
  def default_password
    'notarealpassword'
  end

  def default_password_digest
    BCrypt::Password.create(default_password, cost: 4)
  end
end
```

Sample `users.yml` fixture:
```
test:
  email: test@example.com
  password_digest: <%= default_password_digest %>
```

Including helper methods inside `tests/test_helper.rb`:
```
class ActiveSupport::TestCase
  ...
  include Support::AuthenticationHelper
end
```

Works great until I decided to run `rails db:fixtures:load`.

### Expected behavior
`rails db:fixtures:load` shouldn't throw `NameError` and `default_password_digest` function should be called, since it worked fine in other tests.

### Actual behavior
Run the following command: `rails db:fixtures:load --trace`
```
** Invoke db:fixtures:load (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:fixtures:load
rails aborted!
NameError: undefined local variable or method `default_password_digest' for #<#<Class:0x000055bd8d099368>:0x000055bd8d099048>
test/fixtures/users.yml:3:in `get_binding'
lib/ruby/2.6.0/erb.rb:901:in `eval'
lib/ruby/2.6.0/erb.rb:901:in `result'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixture_set/file.rb:65:in `render'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixture_set/file.rb:50:in `raw_rows'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixture_set/file.rb:39:in `config_row'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixture_set/file.rb:29:in `model_class'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixtures.rb:683:in `block (2 levels) in read_fixture_files'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixture_set/file.rb:17:in `open'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixtures.rb:682:in `block in read_fixture_files'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixtures.rb:681:in `each'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixtures.rb:681:in `each_with_object'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixtures.rb:681:in `read_fixture_files'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixtures.rb:628:in `initialize'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixtures.rb:578:in `new'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixtures.rb:578:in `block in read_and_insert'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixtures.rb:576:in `map'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixtures.rb:576:in `read_and_insert'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/fixtures.rb:546:in `create_fixtures'
lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/railties/databases.rake:308:in `block (3 levels) in <main>'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/command.rb:48:in `invoke'
lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands.rb:18:in `<main>'
lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
bin/rails:9:in `<top (required)>'
lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
lib/ruby/gems/2.6.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:fixtures:load
```

### System configuration
**Rails version**: 6.0.0rc1

**Ruby version**: 2.6.3

**Comment by y-yagi** [comment]
This is because `db:fixtures:load` does not load `tests/test_helper.rb`.
If you want to use customized methods in fixtures, you need to specify `ActiveRecord::FixtureSet.context_class` in other files(e.g. `initializers`).

**Comment by lingceng** [comment]
> 

ActiveRecord::FixtureSet not found when in initializers.

I put it in the front of yaml
<%
  # ActiveRecord::FixtureSet.context_class.include not work when bin/rails db:fixtures:load
  def long_text(file_name)
    str = File.read(Rails.root.join('test/fixtures/files', file_name)).indent(4)
    "|\n" + str
  end
%>

one_user:
  conversation: one
  role: user
  status: success
