### ISSUE TITLE
Marshal.dump raises TypeError on ActiveRecord instance

### ISSUE THREAD

**Issue by sundling** [rails/rails#36401]
It is not possible to call Marshal.dump on an ActiveRecord instance that has been `inspect`ed

It seems that the commit https://github.com/rails/rails/commit/32b03b46150b0161eba2321ccac7678511e3d58e introduced the error when `DelegateClass` was added.

It worked previously in Rails 5.2.3

### Steps to reproduce
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "6.0.0.rc1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_marshal_dump
    post = Post.new(title: "My post")

    assert_equal post.inspect, Marshal.load(Marshal.dump(post)).inspect
  end
end
```

### Expected behavior
It should be possible to Marshal.dump the ActiveRecord instance

### Actual behavior
An exception is thrown
```
TypeError: can't dump anonymous class #<Class:0x00007fabde6c8e28>
    test.rb:39:in `dump'
    test.rb:39:in `test_marshal_dump'
```

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.3

**Comment by sundling** [comment]
I can still reproduce this in both the `6-0-stable` branch and on `master`
