### ISSUE TITLE
Error: undefined method `keys' for #<ActionView::Template

### ISSUE THREAD

**Issue by schneems** [rails/rails#36458]
### Steps to reproduce

```
$ git clone https://github.com/codetriage/codetriage
$ git co schneems/6-master-error
$ rails s
```

Then visit a page localhost:3000 should work.

### Expected behavior

A webpage renders fine

### Actual behavior

I get an error:

```
[58115] Puma starting in cluster mode...
[58115] * Version 3.11.4 (ruby 2.6.3-p62), codename: Love Song
[58115] * Min threads: 5, max threads: 5
[58115] * Environment: development
[58115] * Process workers: 2
[58115] * Preloading application
[58115] * Listening on tcp://0.0.0.0:3000
[58115] Use Ctrl-C to stop
[58115] - Worker 0 (pid: 58125) booted, phase: 0
[58115] - Worker 1 (pid: 58126) booted, phase: 0
Started GET "/" for 127.0.0.1 at 2019-06-10 14:29:53 -0500
   (2.7ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by PagesController#index as HTML
   (4.7ms)  SELECT COUNT(*) FROM "users"
  ↳ app/controllers/pages_controller.rb:47:in `block in description'
   (27.3ms)  SELECT COUNT(*) FROM "repos"
  ↳ app/controllers/pages_controller.rb:48:in `block in description'
Completed 500 Internal Server Error in 93ms (ActiveRecord: 54.0ms | Allocations: 13941)


undefined method `keys' for #<ActionView::Template app/views/pages/index.html.slim locals=[]> excluded from capture: DSN not set

NoMethodError (undefined method `keys' for #<ActionView::Template app/views/pages/index.html.slim locals=[]>):

skylight-core (2.0.2) lib/skylight/core/probes/action_view.rb:14:in `render_with_layout'
/Users/rschneeman/Documents/projects/rails/actionview/lib/action_view/renderer/template_renderer.rb:57:in `render_template'
/Users/rschneeman/Documents/projects/rails/actionview/lib/action_view/renderer/template_renderer.rb:13:in `render'
/Users/rschneeman/Documents/projects/rails/actionview/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
/Users/rschneeman/Documents/projects/rails/actionview/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
/Users/rschneeman/Documents/projects/rails/actionview/lib/action_view/rendering.rb:118:in `block in _render_template'
/Users/rschneeman/Documents/projects/rails/actionview/lib/action_view/base.rb:304:in `in_rendering_context'
/Users/rschneeman/Documents/projects/rails/actionview/lib/action_view/rendering.rb:117:in `_render_template'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/streaming.rb:219:in `_render_template'
/Users/rschneeman/Documents/projects/rails/actionview/lib/action_view/rendering.rb:103:in `render_to_body'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/abstract_controller/rendering.rb:25:in `render'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/rendering.rb:36:in `render'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/Users/rschneeman/Documents/projects/rails/activesupport/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/Users/rschneeman/.rubies/ruby-2.6.3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/Users/rschneeman/Documents/projects/rails/activesupport/lib/active_support/core_ext/benchmark.rb:14:in `ms'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/instrumentation.rb:85:in `cleanup_view_runtime'
/Users/rschneeman/Documents/projects/rails/activerecord/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/instrumentation.rb:43:in `render'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/abstract_controller/base.rb:196:in `process_action'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/Users/rschneeman/Documents/projects/rails/activesupport/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
raven-ruby (21669e97ee70) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
/Users/rschneeman/Documents/projects/rails/activesupport/lib/active_support/callbacks.rb:121:in `instance_exec'
/Users/rschneeman/Documents/projects/rails/activesupport/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/rschneeman/Documents/projects/rails/activesupport/lib/active_support/callbacks.rb:139:in `run_callbacks'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/Users/rschneeman/Documents/projects/rails/activesupport/lib/active_support/notifications.rb:203:in `block in instrument'
/Users/rschneeman/Documents/projects/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/rschneeman/Documents/projects/rails/activesupport/lib/active_support/notifications.rb:203:in `instrument'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/Users/rschneeman/Documents/projects/rails/activerecord/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/abstract_controller/base.rb:136:in `process'
/Users/rschneeman/Documents/projects/rails/actionview/lib/action_view/rendering.rb:39:in `process'
rack-mini-profiler (1.0.0) lib/mini_profiler/profiling_methods.rb:104:in `block in profile_method'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal.rb:191:in `dispatch'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_controller/metal.rb:252:in `dispatch'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_dispatch/journey/router.rb:32:in `each'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_dispatch/journey/router.rb:32:in `serve'
/Users/rschneeman/Documents/projects/rails/actionpack/lib/action_dispatch/routing/route_set.rb:837:in `call'
```
### System configuration

**Rails version**: master

**Ruby version**: 2.6.3

**Comment by schneems** [comment]
It was a bug in an older version of skylight
