### ISSUE TITLE
Active Storage direct upload to disk fails when faced with blank content type due to unknown file type.

### ISSUE THREAD

**Issue by cushingw** [rails/rails#36514]
### Steps to reproduce
our application is a basic rails app with direct upload to local storage in the development environment

**config/environments/development.rb**
```config.active_storage.service = :local```

**app/javascript/packs/application.js**
```require("@rails/activestorage").start();```

**app/views/jobs/new.html.erb**
```<%= f.file_field :input_files, multiple: true, direct_upload: true, class: 'form-control custom-file-input' %>```

When a file of indeterminate content type is selected in the file field, the upload process fails during the transfer of the blob prior to form submission. In our case this was triggered by a NumPy archive file (*.npz)

### Expected behavior
File should upload to local file storage correctly

### Actual behavior
Metadata creation via POST to `/rails/active_storage` succeds but upload of actual blob via PUT to `/rails/active_storage/disk` fails with Mime::Type::InvalidMimeType exception on server.

The backtrace from the blog upload request is 
```
actionpack (6.0.0.rc1) lib/action_dispatch/http/mime_type.rb:235:in `initialize'
actionpack (6.0.0.rc1) lib/action_dispatch/http/mime_type.rb:143:in `new'
actionpack (6.0.0.rc1) lib/action_dispatch/http/mime_type.rb:143:in `lookup'
actionpack (6.0.0.rc1) lib/action_dispatch/http/mime_negotiation.rb:23:in `block in content_mime_type'
rack (2.0.7) lib/rack/request.rb:59:in `fetch'
rack (2.0.7) lib/rack/request.rb:59:in `fetch_header'
actionpack (6.0.0.rc1) lib/action_dispatch/http/mime_negotiation.rb:21:in `content_mime_type'
actionpack (6.0.0.rc1) lib/action_controller/metal/params_wrapper.rb:278:in `_wrapper_enabled?'
actionpack (6.0.0.rc1) lib/action_controller/metal/params_wrapper.rb:244:in `process_action'
activerecord (6.0.0.rc1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.0.rc1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.0.rc1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.0.rc1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.0.rc1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.0.rc1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0.rc1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0.rc1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:837:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:38:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/cookies.rb:644:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
activerecord (6.0.0.rc1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
web-console (4.0.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
activesupport (6.0.0.rc1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/static.rb:126:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
webpacker (4.0.2) lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
railties (6.0.0.rc1) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.3

**Comment by cushingw** [comment]
The problem occurs because the javascript for direct upload passes along the content type received from the browser's File object even if the browser can't determine a content-type.

**activestorage/app/javascript/activestorage/blob_record.js**
```
this.attributes = {
      filename: file.name,
      content_type: file.type,
      byte_size: file.size,
      checksum: checksum
    }
```
When `file.type` is blank, that is both passed to `/rails/active_storage` as blob.content_type, but is used to set the content-type header for the actual blob upload in `blob_upload.js`.

The blank content-type causes the exception during mime type negotiation in `actionpack/lib/action_dispatch/http/mime_negotiation.rb` when a valid mime type can't be found.

If the browser File object has a blank type, it should probably be substituted for a reasonable  default Mime type like 'application/octet-stream' in `blob_record.js`

**Comment by palytoxin** [comment]
have same problem.
some xls file send, the chrome check content-type is empty string.

ruby 2.6.5
rails 6.0.2
