### ISSUE TITLE
Duplicate column overwritten despite error in Sqlite

### ISSUE THREAD

**Issue by shushugah** [rails/rails#36606]
### Steps to reproduce
```ruby
rails new sample_app
cd sample_app
rails g migration CreateKittens name # string is default type
rails g migration AddNameToKittens name:datetime
rake db:migrate
```
### Expected behavior
Because the second migration tries to add an existing column name, the expected error 
```
ActiveRecord::StatementInvalid: SQLite3::SQLException: duplicate column name: name: ALTER TABLE "kittens" ADD "name" datetime
``` 
comes up, however I expect the `name` to then be the type of the previous migration, i.e `string` not `datetime`

Running `rake db:migrate:status` works as expected showing
```bash
up     20190705210025  Create kittens
down    20190705210047  Add name to kittens
```

### Actual behavior
In Schema.rb it shows

```ruby
ActiveRecord::Schema.define(version: 2019_07_05_174914) do
  create_table "cats", force: :cascade do |t|
    t.datetime "name"
  end
end
```

### Other SQL adapters
This does not happen in Postgresql. Running 
```ruby
rails new sample_app --database=postgresql
cd sample_app
rails g migration CreateKittens name # string is default type
rails g migration AddNameToKittens name:datetime
rake db:migrate
```
will not create a `schema.rb` file at all if none existed before
On the other hand if I run 

```ruby
rails new sample_app --database=postgresql
cd sample_app
rails g migration CreateKittens name # string is default type
rake db:migrate
rails g migration AddNameToKittens name:datetime
rake db:migrate
```
The first migration file will create schema as expected
```ruby
ActiveRecord::Schema.define(version: 2019_07_05_211449) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "kittens", force: :cascade do |t|
    t.string "name"
  end
end
```
And for the second migration, it will fail with the following error as expected 💯 

```
Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "name" of relation "kittens" already exists

Caused by:
PG::DuplicateColumn: ERROR:  column "name" of relation "kittens" already exists
```
### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.5.1

**Comment by pauloancheta** [comment]
I just tried it on my machine and it worked as expected and gave me this error. Here's a gist for the test https://gist.github.com/pauloancheta/c81235ad718d46a5ca3454b0c4d65bb7
```
Running via Spring preloader in process 24723
      invoke  active_record
      create    db/migrate/20190712065254_create_kittens.rb
Running via Spring preloader in process 24737
      invoke  active_record
      create    db/migrate/20190712065255_add_name_to_kittens.rb
Running via Spring preloader in process 24751
== 20190712065254 CreateKittens: migrating ====================================
-- create_table(:kittens)
   -> 0.0009s
== 20190712065254 CreateKittens: migrated (0.0010s) ===========================

== 20190712065255 AddNameToKittens: migrating =================================
-- add_column(:kittens, :name, :datetime)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: duplicate column name: name: ALTER TABLE "kittens" ADD "name" datetime
/Users/paulo/Personal/ruby/cats/db/migrate/20190712065255_add_name_to_kittens.rb:3:in `change'
-e:1:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: SQLite3::SQLException: duplicate column name: name: ALTER TABLE "kittens" ADD "name" datetime
/Users/paulo/Personal/ruby/cats/db/migrate/20190712065255_add_name_to_kittens.rb:3:in `change'
-e:1:in `<main>'

Caused by:
SQLite3::SQLException: duplicate column name: name
/Users/paulo/Personal/ruby/cats/db/migrate/20190712065255_add_name_to_kittens.rb:3:in `change'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace```

**Comment by wjessop** [comment]
I also can't replicate this. I created a 5.2.3 app (`rails _5.2.3_ new sample_app -J`) and also a 6.0.0.rc1 one and I get the error on migration as expected in both, and `rake db:migrate:status` returns the expected result:

```
database: /Users/will/tmp/repro/sample_app/db/development.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20190714000044  Create kittens
  down    20190714000045  Add name to kittens
```

and though there is no schema.rb created, I do have the expected schema in the database:

```
sqlite> .schema
CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" varchar NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "kittens" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar);
```

Interestingly you said that the first migration creates a `schema.rb`, however one was not created for me. I had to remove the faulty migration and re-run `db:migrate` successfully to get it created. If I `rm db/schema.rb`, re-create the problem second migration and re-run `db:migrate`, once again there is no `schema.rb` created. Can you double check your reproduction instructions?

**Comment by wjessop** [comment]
Hey @shushugah, did you get a chance to take another look at this?
