### ISSUE TITLE
Named routes do not work in ActionMailer::Preview when opening the preview on browser

### ISSUE THREAD

**Issue by tuomasj** [rails/rails#36705]
## Named routes throws an error in ActionMailer::Preview when opening the preview on browser.

When previewing a mailer view that has a named route with arguments, it will throw an error. 

```
undefined method `merge' for nil:NilClass
```

`default_url_options` is `nil` in method `url_for()` (https://github.com/rails/rails/blob/v6.0.0.rc1/actionpack/lib/action_dispatch/routing/route_set.rb#L798)

### Steps to reproduce

Rails 6.0.0.rc1 skeleton
```
$ rails new bugtest
$ cd bugtest/
$ rails db:migrate
$ rails g mailer test first
$ rails s
```

Routes file defining two routes `plain` and `complex`

```
# config/routes.rb

Rails.application.routes.draw do
  get '/plain' => "home#plain", as: :plain
  get '/complex/:id' => "home#complex", as: :complex
end
```

TestMailerPreview, generated by Rails generator

```
# /test/mailers/previews/test_mailer_preview.rb

# Preview all emails at http://localhost:3000/rails/mailers/test_mailer
class TestMailerPreview < ActionMailer::Preview

  # Preview this email at http://localhost:3000/rails/mailers/test_mailer/first
  def first
    TestMailer.first
  end

end
```

Mailer view

```
# app/views/test_mailer/first.html.erb

<p>Complex URL: <%= complex_url(id: 2) %></p>
<p>Plain url: <%= plain_url %></p>
```

### Expected behavior

Mailer view should render using the named route when opening url `http://localhost:3000/rails/mailers/test_mailer/first`

### Actual behavior

When opening the url `http://localhost:3000/rails/mailers/test_mailer/first` this error message happens:

**With using 'complex' named route in the view with hash of arguments**

```
Complex URL: <%= complex_url(id: 2) %>
```
#### Error message:

```
undefined method `merge' for nil:NilClass
```

**With using 'plain' named route in the view, without arguments:**

```
Plain url: <%= plain_url %>
```

#### Error message:

```
undefined method `empty?' for nil:NilClass
```

#### Full Trace when using 'complex' named route

```
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:798:in `url_for'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:272:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:213:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:329:in `block in define_url_helper'
app/views/test_mailer/first.html.erb:1
actionview (6.0.0.rc1) lib/action_view/base.rb:274:in `_run'
actionview (6.0.0.rc1) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.0.rc1) lib/action_view/template.rb:386:in `instrument_render_template'
actionview (6.0.0.rc1) lib/action_view/template.rb:183:in `render'
actionview (6.0.0.rc1) lib/action_view/renderer/template_renderer.rb:59:in `block (2 levels) in render_template'
actionview (6.0.0.rc1) lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.0.rc1) lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
actionview (6.0.0.rc1) lib/action_view/renderer/template_renderer.rb:58:in `block in render_template'
actionview (6.0.0.rc1) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
actionview (6.0.0.rc1) lib/action_view/renderer/template_renderer.rb:57:in `render_template'
actionview (6.0.0.rc1) lib/action_view/renderer/template_renderer.rb:13:in `render'
actionview (6.0.0.rc1) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.0.0.rc1) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.0.0.rc1) lib/action_view/rendering.rb:118:in `block in _render_template'
actionview (6.0.0.rc1) lib/action_view/base.rb:304:in `in_rendering_context'
actionview (6.0.0.rc1) lib/action_view/rendering.rb:117:in `_render_template'
actionview (6.0.0.rc1) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.0.0.rc1) lib/abstract_controller/rendering.rb:25:in `render'
actionmailer (6.0.0.rc1) lib/action_mailer/base.rb:978:in `block in collect_responses_from_templates'
actionmailer (6.0.0.rc1) lib/action_mailer/base.rb:975:in `each'
actionmailer (6.0.0.rc1) lib/action_mailer/base.rb:975:in `each'
actionmailer (6.0.0.rc1) lib/action_mailer/base.rb:975:in `map'
actionmailer (6.0.0.rc1) lib/action_mailer/base.rb:975:in `collect_responses_from_templates'
actionmailer (6.0.0.rc1) lib/action_mailer/base.rb:953:in `collect_responses'
actionmailer (6.0.0.rc1) lib/action_mailer/base.rb:858:in `mail'
app/mailers/test_mailer.rb:11:in `first'
actionpack (6.0.0.rc1) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.0.rc1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0.rc1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.0.rc1) lib/abstract_controller/base.rb:136:in `process'
actionmailer (6.0.0.rc1) lib/action_mailer/rescuable.rb:25:in `block in process'
actionmailer (6.0.0.rc1) lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
actionmailer (6.0.0.rc1) lib/action_mailer/rescuable.rb:24:in `process'
actionview (6.0.0.rc1) lib/action_view/rendering.rb:39:in `process'
actionmailer (6.0.0.rc1) lib/action_mailer/base.rb:637:in `block in process'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:180:in `instrument'
actionmailer (6.0.0.rc1) lib/action_mailer/base.rb:636:in `process'
actionmailer (6.0.0.rc1) lib/action_mailer/message_delivery.rb:123:in `block in processed_mailer'
actionmailer (6.0.0.rc1) lib/action_mailer/message_delivery.rb:122:in `tap'
actionmailer (6.0.0.rc1) lib/action_mailer/message_delivery.rb:122:in `processed_mailer'
actionmailer (6.0.0.rc1) lib/action_mailer/message_delivery.rb:29:in `__getobj__'
/Users/tuomas/.rbenv/versions/2.6.2/lib/ruby/2.6.0/delegate.rb:80:in `method_missing'
actionmailer (6.0.0.rc1) lib/action_mailer/inline_preview_interceptor.rb:46:in `html_part'
actionmailer (6.0.0.rc1) lib/action_mailer/inline_preview_interceptor.rb:29:in `transform!'
actionmailer (6.0.0.rc1) lib/action_mailer/inline_preview_interceptor.rb:21:in `previewing_email'
actionmailer (6.0.0.rc1) lib/action_mailer/preview.rb:138:in `block in inform_preview_interceptors'
actionmailer (6.0.0.rc1) lib/action_mailer/preview.rb:137:in `each'
actionmailer (6.0.0.rc1) lib/action_mailer/preview.rb:137:in `inform_preview_interceptors'
actionmailer (6.0.0.rc1) lib/action_mailer/preview.rb:92:in `call'
railties (6.0.0.rc1) lib/rails/mailers_controller.rb:29:in `preview'
actionpack (6.0.0.rc1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.0.rc1) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.0.rc1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.0.rc1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
railties (6.0.0.rc1) lib/rails/mailers_controller.rb:97:in `block in set_locale'
i18n (1.6.0) lib/i18n.rb:297:in `with_locale'
railties (6.0.0.rc1) lib/rails/mailers_controller.rb:96:in `set_locale'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:139:in `run_callbacks'
actionpack (6.0.0.rc1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.0.rc1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.0.rc1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.0.rc1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.0.rc1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.0.rc1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.0.rc1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.0.rc1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.0.rc1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.0.rc1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.0.rc1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0.rc1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0.rc1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:837:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/cookies.rb:644:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
activerecord (6.0.0.rc1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
web-console (4.0.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
activesupport (6.0.0.rc1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/static.rb:126:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
webpacker (4.0.7) lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
railties (6.0.0.rc1) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread' 
```

### System configuration

```
$ rails -v
Rails 6.0.0.rc1
```

```
$ ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]
```

**Comment by chukitow** [comment]
@tuomasj did you set `default_url_options` in the proper environment file? 
 
`config/environments/development.rb`

```ruby
config.action_mailer.default_url_options = { :host => 'localhost' }
```

I think you miss it that's, why you are getting those errors.

**Comment by tuomasj** [comment]
You are right! I didn't have `default_url_options` configured in all of environments.
