### ISSUE TITLE
PG::UndefinedTable: ERROR:  relation "users" does not exist

### ISSUE THREAD

**Issue by efojs** [rails/rails#36755]
### Is it on Rails or Devise side?
Error — `LINE 8:  WHERE a.attrelid = **'"users"'**::regclass` — refers to this line (820) of code generating SQL query:

```
# postgresql_adapter.rb
WHERE a.attrelid = #{quote(quote_table_name(table_name))}::regclass
```

### Steps to reproduce
Build new app
Add Devise (?)
Add User model
Deploy to Heroku (Heroku with Postgres DB)

### Expected behavior
Should be deployed without error

### Actual behavior
```
remote: -----> Precompiling assets
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "users" does not exist
remote:        LINE 8:  WHERE a.attrelid = '"users"'::regclass
remote:                                    ^
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `async_exec'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `block (2 levels) in query'
```

### System configuration
**Rails version**:
6.1.0.alpha (b1c27c0)
**Ruby version**:
ruby-2.5.5

**Comment by efojs** [comment]
Full error trace, where in the middle Devise emerge:
```
remote: -----> Precompiling assets
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "users" does not exist
remote:        LINE 8:  WHERE a.attrelid = '"users"'::regclass
remote:                                    ^
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `async_exec'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `block (2 levels) in query'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `block in query'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:703:in `block (2 levels) in log'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:702:in `block in log'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:693:in `log'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `query'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:812:in `column_definitions'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:113:in `columns'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/schema_cache.rb:81:in `block in columns'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/schema_cache.rb:80:in `fetch'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/schema_cache.rb:80:in `columns'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/schema_cache.rb:89:in `block in columns_hash'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/schema_cache.rb:88:in `fetch'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/connection_adapters/schema_cache.rb:88:in `columns_hash'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/model_schema.rb:488:in `load_schema!'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/attributes.rb:247:in `load_schema!'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/attribute_decorators.rb:50:in `load_schema!'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/model_schema.rb:478:in `block in load_schema'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/model_schema.rb:475:in `load_schema'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/model_schema.rb:352:in `columns_hash'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/dynamic_matchers.rb:60:in `block in valid?'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/dynamic_matchers.rb:60:in `each'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/dynamic_matchers.rb:60:in `all?'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/dynamic_matchers.rb:60:in `valid?'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/dynamic_matchers.rb:11:in `respond_to_missing?'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/scoping/named.rb:208:in `respond_to?'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/scoping/named.rb:208:in `valid_scope_name?'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activerecord/lib/active_record/scoping/named.rb:186:in `scope'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/app/models/user.rb:14:in `<class:User>'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/app/models/user.rb:1:in `<top (required)>'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/kernel.rb:16:in `require'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/inflector/methods.rb:282:in `const_get'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/inflector/methods.rb:282:in `block in constantize'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/inflector/methods.rb:280:in `each'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/inflector/methods.rb:280:in `inject'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/inflector/methods.rb:280:in `constantize'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/dependencies/zeitwerk_integration.rb:19:in `constantize'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/devise-19045a483dd0/lib/devise.rb:320:in `get'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/devise-19045a483dd0/lib/devise/mapping.rb:83:in `to'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/devise-19045a483dd0/lib/devise/mapping.rb:78:in `modules'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/devise-19045a483dd0/lib/devise/mapping.rb:95:in `routes'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/devise-19045a483dd0/lib/devise/mapping.rb:162:in `default_used_route'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/devise-19045a483dd0/lib/devise/mapping.rb:72:in `initialize'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/devise-19045a483dd0/lib/devise.rb:350:in `new'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/devise-19045a483dd0/lib/devise.rb:350:in `add_mapping'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/devise-19045a483dd0/lib/devise/rails/routes.rb:243:in `block in devise_for'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/devise-19045a483dd0/lib/devise/rails/routes.rb:242:in `each'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/devise-19045a483dd0/lib/devise/rails/routes.rb:242:in `devise_for'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/config/routes.rb:7:in `block in <top (required)>'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/actionpack/lib/action_dispatch/routing/route_set.rb:426:in `instance_exec'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/actionpack/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/actionpack/lib/action_dispatch/routing/route_set.rb:408:in `draw'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/config/routes.rb:1:in `<top (required)>'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/application/routes_reloader.rb:40:in `each'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/application/routes_reloader.rb:40:in `load_paths'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/application/routes_reloader.rb:20:in `reload!'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/application/routes_reloader.rb:29:in `block in updater'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/file_update_checker.rb:83:in `execute'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/application/routes_reloader.rb:10:in `execute'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/application/finisher.rb:184:in `block in <module:Finisher>'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/initializable.rb:32:in `instance_exec'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/initializable.rb:32:in `run'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/initializable.rb:60:in `run_initializers'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/application.rb:364:in `initialize!'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/kernel.rb:23:in `require'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/dependencies.rb:321:in `block in require'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/dependencies.rb:288:in `load_dependency'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/activesupport/lib/active_support/dependencies.rb:321:in `require'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/application.rb:340:in `require_environment!'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/bundler/gems/rails-b1c27c059c88/railties/lib/rails/application.rb:515:in `block in run_tasks_blocks'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
remote:        /tmp/build_5923526ec7130ae3c0885b6b72a830b1/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
```

**Comment by chukitow** [comment]
@efojs I was able to push to create a new app, add devise and deploy it to Heroku https://ancient-mountain-89561.herokuapp.com/

Also in the future, you can create a question on http://stackoverflow.com/ instead of creating an issue. This kind off issues just add noise to the core team 😅

**Comment by efojs** [comment]
Thank you @chukitow, I thought it somehow connected with alpha version, because I had no problems with 5.2. Will dig deeper and ask at StackOverflow. IDK

**Comment by efojs** [comment]
Turned out to be a problem with scoping in User model before creating DB table: https://www.reddit.com/r/rails/comments/chtk5l/model_scopes_and_db_tables/
