### ISSUE TITLE
[6.0.0.rc2] Rails helpers are no longer recognized: Missing helper file helpers/application_helper.rb (AbstractController::Helpers::MissingHelperError)

### ISSUE THREAD

**Issue by mschnitzer** [rails/rails#36774]
First of all, I first considered not reporting this, since your guidelines propose to provide a code example or at least provide some code how to reproduce this issue. Unfortunately, I didn't succeed in debugging and I was not able to reproduce this issue in newly created Rails 6.0.0.rc2 apps. I'm still on it and I hope I can provide some more details very soon. In the meanwhile, I hope someone with the same issue comes across this issue report.

### Steps to reproduce

So I basically upgraded my Rails `6.0.0.rc1` app (which was a former `5.2.3` app) and experienced that since the change to `6.0.0.rc2` the app crashes while eager loading:

```
Traceback (most recent call last):
	87: from bin/rails:4:in `<main>'
	86: from /usr/lib64/ruby/gems/2.5.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `require'
	85: from /usr/lib64/ruby/gems/2.5.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:288:in `load_dependency'
	84: from /usr/lib64/ruby/gems/2.5.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `block in require'
	83: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	82: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	81: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	80: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	79: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	78: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/commands.rb:18:in `<top (required)>'
	77: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/command.rb:46:in `invoke'
	76: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/command/base.rb:65:in `perform'
	75: from /usr/lib64/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	74: from /usr/lib64/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	73: from /usr/lib64/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	72: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/commands/server/server_command.rb:138:in `perform'
	71: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/commands/server/server_command.rb:138:in `tap'
	70: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	69: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/commands/server/server_command.rb:37:in `start'
	68: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	67: from /usr/lib64/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
	66: from /usr/lib64/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
	65: from /usr/lib64/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	64: from /usr/lib64/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
	63: from /usr/lib64/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
	62: from /usr/lib64/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
	61: from config.ru:in `<main>'
	60: from config.ru:in `new'
	59: from /usr/lib64/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
	58: from /usr/lib64/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
	57: from config.ru:3:in `block in <main>'
	56: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
	55: from /usr/lib64/ruby/gems/2.5.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `require'
	54: from /usr/lib64/ruby/gems/2.5.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:288:in `load_dependency'
	53: from /usr/lib64/ruby/gems/2.5.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `block in require'
	52: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/kernel.rb:23:in `require'
	51: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	50: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	49: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	48: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	47: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	46: from /home/manuel/git/ho/config/environment.rb:5:in `<top (required)>'
	45: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/application.rb:363:in `initialize!'
	44: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/initializable.rb:60:in `run_initializers'
	43: from /usr/lib64/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	42: from /usr/lib64/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	41: from /usr/lib64/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	40: from /usr/lib64/ruby/2.5.0/tsort.rb:347:in `call'
	39: from /usr/lib64/ruby/2.5.0/tsort.rb:347:in `each'
	38: from /usr/lib64/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	37: from /usr/lib64/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	36: from /usr/lib64/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	35: from /usr/lib64/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	34: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/initializable.rb:61:in `block in run_initializers'
	33: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/initializable.rb:32:in `run'
	32: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/initializable.rb:32:in `instance_exec'
	31: from /usr/lib64/ruby/gems/2.5.0/gems/railties-6.0.0.rc2/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
	30: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:449:in `eager_load_all'
	29: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:449:in `each'
	28: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:338:in `eager_load'
	27: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:338:in `synchronize'
	26: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:346:in `block in eager_load'
	25: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:659:in `ls'
	24: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:659:in `foreach'
	23: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:662:in `block in ls'
	22: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:351:in `block (2 levels) in eager_load'
	21: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:351:in `const_get'
	20: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/kernel.rb:16:in `require'
	19: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	18: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	17: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	16: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	15: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	14: from /home/manuel/git/ho/app/controllers/tests_controller.rb:1:in `<top (required)>'
	13: from /usr/lib64/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/kernel.rb:16:in `require'
	12: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	11: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	10: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 9: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 8: from /usr/lib64/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 7: from /home/manuel/git/ho/app/controllers/application_controller.rb:1:in `<top (required)>'
	 6: from /usr/lib64/ruby/gems/2.5.0/gems/actionpack-6.0.0.rc2/lib/action_controller/railties/helpers.rb:19:in `inherited'
	 5: from /usr/lib64/ruby/gems/2.5.0/gems/actionpack-6.0.0.rc2/lib/abstract_controller/helpers.rb:108:in `helper'
	 4: from /usr/lib64/ruby/gems/2.5.0/gems/actionpack-6.0.0.rc2/lib/action_controller/metal/helpers.rb:94:in `modules_for_helpers'
	 3: from /usr/lib64/ruby/gems/2.5.0/gems/actionpack-6.0.0.rc2/lib/abstract_controller/helpers.rb:144:in `modules_for_helpers'
	 2: from /usr/lib64/ruby/gems/2.5.0/gems/actionpack-6.0.0.rc2/lib/abstract_controller/helpers.rb:144:in `map!'
	 1: from /usr/lib64/ruby/gems/2.5.0/gems/actionpack-6.0.0.rc2/lib/abstract_controller/helpers.rb:148:in `block in modules_for_helpers'
/usr/lib64/ruby/gems/2.5.0/gems/actionpack-6.0.0.rc2/lib/abstract_controller/helpers.rb:151:in `rescue in block in modules_for_helpers': Missing helper file helpers/application_helper.rb (AbstractController::Helpers::MissingHelperError)
```

Moving to `:classic` mode (for `config.autoloader`) has fixed this issue. So it seems to be some change in the `:zeitwerk` mode. I also checked if the `zeitwerk` version has been upgraded when I was updating the Rails `6.0.0.rc2` app, but the version of `zeitwerk` stayed the same during upgrade.

So I did find similar issues on Stackoverflow, but they seem to be pretty old and are not in relation to `6.0.0.rc2`. I verified that the helpers are still in app/helpers/[...]_helper.rb - the `application_helper.rb` file is there as well and actively used by my app.

Downgrading to `6.0.0.rc1` resolves this issue.

I'm still trying to reproduce the issue and find out which commit may have caused this.

### Expected behavior
The app eager loads properly and does not crash.

### Actual behavior
The app crashes while eager loading.

### System configuration
**Rails version**: `6.0.0.rc2`

**Ruby version**: `2.5.5p157`

**Comment by rafaelfranca** [comment]
Since you can reproduce in your app you can try to bisect the change in Rails that caused the problem to you by pointing Rails to a local fork in your gemfile and using `git bisect`.

**Comment by mschnitzer** [comment]
Thanks for pointing me into this direction. I'll debug this during the weekend and come back to you with more details (hopefully)

**Comment by rafaelfranca** [comment]
That is fine. I always can add it back again.

**Comment by mschnitzer** [comment]
@rafaelfranca I found the commit which introduced it: 668673f7793be1ce318a32bb622ed411029d00a9

I checked my app and I explicitly turned it off as suggested by the Changelog entry: https://github.com/rails/rails/commit/668673f7793be1ce318a32bb622ed411029d00a9#diff-1846d4882fa63eb5b1271541995cbfdcR5

Turning this configuration option back to `true` solves the issue for me.

Is it still a bug or am I doing something wrong?

**Comment by rafaelfranca** [comment]
Good question. @fxn any idea?

**Comment by fxn** [comment]
In `zeitwerk`  mode, can you throw

```
Rails.autoloaders.main.log!
```

after loading the defaults in `config/application.rb`, and reproduce? Let's see if there is anything interesting.

Which version of Zeitwerk is the app using?

**Comment by fxn** [comment]
The backtrace shows AS::Dependencies own `require` and `load_dependency` methods being called. That is suspicious, since in `zeitwerk` mode we should not see them. Zeitwerk takes over after the application initializers. I wonder if there is a `require` call for the helper using a relative path being triggered before.

**Comment by fxn** [comment]
I could reproduce and confirmed: [this line](https://github.com/rails/rails/blob/71e41a5b9495ba6ebe3cdf1e10afa27bcc0db208/actionpack/lib/abstract_controller/helpers.rb#L154) is effectively a `require` with a relative path.

I'll think about it.

(The observation about the unexpected `load_dependency` in the backtrace is something to have in mind, and I have a hunch about where it might come from, but probably unrelated to this error.)

**Comment by mschnitzer** [comment]
@fxn as far as I understood, you have reproduced it and don't need any further information from me, right?

**Comment by fxn** [comment]
@mschneider right!
