### ISSUE TITLE
Error when dragging and dropping image in ActionText area

### ISSUE THREAD

**Issue by SalvesTestservices** [rails/rails#36797]
### Steps to reproduce
Install ActiveStorage and ActionText, create a model with a `has_rich_text` attribute.
Create a form with an ActionText area and try to add an image.
This is on a development environment and is configured to store files locally:

````
config.active_storage.service = :local

local:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
````
### Expected behavior
Image should be uploaded with ActiveStorage and be visible when the form is submitted and saved.

### Actual behavior
Returnes an error when the image is dragged and dropped to the ActionText area:

````
Processing by ActiveStorage::DirectUploadsController#create as JSON
  Parameters: {"blob"=>{"filename"=>"schaap.jpg", "content_type"=>"image/jpeg", "byte_size"=>56679, "checksum"=>"xNr4chw64aFTDzzvpmupBg=="}, "direct_upload"=>{"blob"=>{"filename"=>"schaap.jpg", "content_type"=>"image/jpeg", "byte_size"=>56679, "checksum"=>"xNr4chw64aFTDzzvpmupBg=="}}}
   (0.3ms)  BEGIN
  ActiveStorage::Blob Create (0.6ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "byte_size", "checksum", "created_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["key", "0j708kw18u30fys1j467xkuxemju"], ["filename", "schaap.jpg"], ["content_type", "image/jpeg"], ["byte_size", 56679], ["checksum", "xNr4chw64aFTDzzvpmupBg=="], ["created_at", "2019-07-29 05:43:13.838779"]]
   (0.5ms)  COMMIT
Completed 500 Internal Server Error in 15ms (ActiveRecord: 1.3ms | Allocations: 5581)



NoMethodError (undefined method `url_for_direct_upload' for nil:NilClass):

activestorage (6.0.0.rc2) app/models/active_storage/blob.rb:150:in `service_url_for_direct_upload'
activestorage (6.0.0.rc2) app/controllers/active_storage/direct_uploads_controller.rb:19:in `direct_upload_json'
activestorage (6.0.0.rc2) app/controllers/active_storage/direct_uploads_controller.rb:9:in `create'
actionpack (6.0.0.rc2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.0.rc2) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.0.rc2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.0.rc2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.0.rc2) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.0.rc2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.0.rc2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.0.rc2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.0.rc2) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0.rc2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0.rc2) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.0.rc2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.0.rc2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.0.rc2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.0.rc2) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.0.rc2) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.0.rc2) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.0.rc2) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.0.rc2) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.0.rc2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.0.rc2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0.rc2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0.rc2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0.rc2) lib/action_dispatch/routing/route_set.rb:837:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/cookies.rb:644:in `call'
activerecord (6.0.0.rc2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0.rc2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.0.rc2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
webpacker (4.0.7) lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.0.rc2) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
````

### System configuration
**Rails version**: 6.0.0.rc2

**Ruby version**: 2.6.3

**Comment by SalvesTestservices** [comment]
It sometimes also returns this error in the exact same situation (dragging and dropping an image in the ActiveText area:

````
Started POST "/rails/active_storage/direct_uploads" for ::1 at 2019-07-29 08:12:14 +0200
Processing by ActiveStorage::DirectUploadsController#create as JSON
  Parameters: {"blob"=>{"filename"=>"schaap.jpg", "content_type"=>"image/jpeg", "byte_size"=>56679, "checksum"=>"xNr4chw64aFTDzzvpmupBg=="}, "direct_upload"=>{"blob"=>{"filename"=>"schaap.jpg", "content_type"=>"image/jpeg", "byte_size"=>56679, "checksum"=>"xNr4chw64aFTDzzvpmupBg=="}}}
Completed 500 Internal Server Error in 24ms (ActiveRecord: 0.0ms | Allocations: 4552)



NoMethodError (undefined method `[]' for nil:NilClass):

(erb):13:in `<main>'
````

**Comment by alexpooley** [comment]
It looks like the service may not have been defined correctly. Did you define the `config.active_storage.service = :local` in config/environments/development.rb ?

Do you have a sample app to reproduce?

**Comment by SalvesTestservices** [comment]
I do have `config.active_storage.service = :local` in `config/environments/development.rb`.
I have the app in Heroku, but there I don't have the setup for ActiveStorage as `service: Disk` of course, because Heroku doesn't work like that.

**Comment by jarkelen** [comment]
It is solved when I remove the commented out lines from storage.yml, which makes no sense. I guess maybe som spring cache issue? Anyway, it works again, so this one can be closed.

**Comment by SalvesTestservices** [comment]
It is solved when I remove the commented out lines from storage.yml, which makes no sense. I guess maybe som spring cache issue? Anyway, it works again, so this one can be closed.

**Comment by xchen1189** [comment]
> It is solved when I remove the commented out lines from storage.yml, which makes no sense. I guess maybe som spring cache issue? Anyway, it works again, so this one can be closed.

This tricks do works for me, thanks man.

**Comment by petebytes** [comment]
Wow, that worked for me as well. Thanks
