### ISSUE TITLE
Attaching an ActiveStorage blob in a model callback creates a SystemStackError

### ISSUE THREAD

**Issue by jarydkrish** [rails/rails#37022]
### Summary
Calling `attach` in an model callback causes a `SystemStackError: stack level too deep`.

This is specific to Rails 6, as it didn't happen previously in a Rails 5.2.3 app that I tested this in.

### Steps to reproduce
The simplest way to reproduce is to pull down an example repo, and run `rails test`: https://github.com/jarydkrish/attach-in-model-callbacks

This can be reproduced in a Rails 6 app with a model like the following:
```rb
class User < ApplicationRecord
  has_one_attached :avatar

  attr_accessor :copy_avatar_from_user_id

  # Callback that triggers an endless loop
  after_save :copy_avatar, if: :should_copy_avatar_from_user?

  def should_copy_avatar_from_user?
    copy_avatar_from_user_id.present?
  end

  # Copy a user avatar from a different user
  def copy_avatar
    user_to_copy_from = User.find_by(id: copy_avatar_from_user_id)
    avatar.attach(user_to_copy_from.avatar.blob)
  end
end
```

### Expected behavior
I would expect the above code to copy the ActiveStorage attachment to a different model, or at least not return an error.

Here is an example of the same code running in a Rails 5.2.3 application, which works as expected: https://github.com/jarydkrish/attach-in-model-callbacks-rails-5

### Actual behavior
Running `rails test` in [my example repo](https://github.com/jarydkrish/attach-in-model-callbacks) gives the following:
```bash
➜  attach-in-model-callbacks git:(master) rails test
Running via Spring preloader in process 59406
Run options: --seed 22489

# Running:

E

Error:
UserTest#test_attaching_an_image_via_callback:
SystemStackError: stack level too deep
    app/models/user.rb:16:in `copy_avatar'
    app/models/user.rb:16:in `copy_avatar'
    app/models/user.rb:16:in `copy_avatar'
    app/models/user.rb:16:in `copy_avatar'
    app/models/user.rb:16:in `copy_avatar'
    ...
    app/models/user.rb:16:in `copy_avatar'
    app/models/user.rb:16:in `copy_avatar'
    app/models/user.rb:16:in `copy_avatar'
    test/models/user_test.rb:19:in `block in <class:UserTest>'


rails test test/models/user_test.rb:4



Finished in 1.059573s, 0.9438 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.3

**Comment by jarydkrish** [comment]
I suspect that https://github.com/rails/rails/commit/28db8ba60e726d695cf35710cc43ea45966464e9 is where my `stack level too deep` is coming from? Specifically, calling `update` on the `record` (this is also on [`many.rb`](https://github.com/rails/rails/blob/58f1eca871602731b9a0ede0b39dd9ea27b3b5f8/activestorage/lib/active_storage/attached/many.rb#L30-L36):
https://github.com/rails/rails/blob/58f1eca871602731b9a0ede0b39dd9ea27b3b5f8/activestorage/lib/active_storage/attached/one.rb#L30-L36

**Comment by santib** [comment]
Looking at your application code I find it pretty reasonable to get that `SystemStackError: stack level too deep` error. I think it's just one of the dangers of using model callbacks. But it's true that it wasn't happening before so you've got a point there 😄

**Comment by diegosteiner** [comment]
The ```attach```-method calls the models ```update``` method. As a workaround just use the ```before_save``` callback and set the attachment via attribute method, like this:

```ruby
 before_save :copy_avatar, if: :should_copy_avatar_from_user?

def copy_avatar
  user_to_copy_from = User.find_by(id: copy_avatar_from_user_id)
  self.avatar = user_to_copy_from.avatar.blob
end
```

**Comment by GabrielGCardoso** [comment]
Here using `active_storage v5.2.8` and `rails 5.2.0`. We used as a workaround add to the model the `dependent: :destroy` and it worked too

```ruby
has_one_attached :file, dependent: :destroy
```
