### ISSUE TITLE
return_false_on_aborted_enqueue setting not working

### ISSUE THREAD

**Issue by paul** [rails/rails#37030]
### Steps to reproduce

I'm attempting to upgrade a 5.2 app to 6.0. I get about a million warnings during the spec suite:

> DEPRECATION WARNING: Rails 6.1 will return false when the enqueuing is aborted. Make sure your code doesn't depend on it returning the instance of the job and set `config.active_job.return_false_on_aborted_enqueue = true` to remove the deprecations. (called from handle_timeout at /home/rando/Code/textus/tesseract/app/jobs/deliver_message_job.rb:49)

Since, as far as I'm aware, we never rely on the return value of enqueuing a job, I uncommented the setting in `new_framework_defaults_6_0.rb`

```
Rails.application.config.active_job.return_false_on_aborted_enqueue = true
```

This did not make the warnings go away.

### Expected behavior

No warnings after enabling `active_job.return_false_on_aborted_enqueue = true`

### Actual behavior

Tons of warnings.

It seems the Rails config setting isn't getting passed to the ActiveJob class variable:

```
$ rails c
[tesseract|development|main]> Rails.application.config.active_job.return_false_on_aborted_enqueue
=> true
[tesseract|development|main]> ActiveJob::Base.return_false_on_aborted_enqueue
=> false
[tesseract|development|main]> ApplicationJob.return_false_on_aborted_enqueue
=> false
```

### System configuration
**Rails version**: 6.0

**Ruby version**: 2.6.3

**Comment by eugeneius** [comment]
This could be happening because your application is loading Active Job too early; the values in `Rails.application.config.active_job` are applied to `ActiveJob::Base` as soon as it loads, so if that happens before `config/initializers/new_framework_defaults_6_0.rb` runs it has no effect:

https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/activejob/lib/active_job/railtie.rb#L27-L32

You can confirm this by adding `ActiveSupport.on_load(:active_job) { puts caller }` to `config/application.rb`, adding `puts "applying new framework defaults"` to `config/initializers/new_framework_defaults_6_0.rb`, and checking whether the stacktrace is printed before the message. If it is, it should help you to find the offending code in your application.

**Comment by paul** [comment]
@eugeneius make sense, thanks. Looks like its not something I have any control over, the `Bundler.require` line in `application.rb` loads the Chewy gem, which triggers loading activesupport.

If anyone comes across this issue with the same problem, I solved it by adding this to my `config/initializers/new_framework_defaults_6_0.rb`:

```ruby
# config/initializers/new_framework_defaults_6_0.rb

# ... snip ...

# Return false instead of self when enqueuing is aborted from a callback.
Rails.application.config.active_job.return_false_on_aborted_enqueue = true

# The above setting seems to have no effect.
# https://github.com/rails/rails/issues/37030
ActiveJob::Base.return_false_on_aborted_enqueue = true

# ... snip ...
```

Backtrace from `ActiveSupport.on_load(:active_job) { puts caller }` in `application.rb`:

```
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:72:in `class_eval'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:72:in `block in execute_hook'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/rando/.gem/ruby/2.6.3/gems/activejob-6.0.0/lib/active_job/base.rb:74:in `<class:Base>'
/home/rando/.gem/ruby/2.6.3/gems/activejob-6.0.0/lib/active_job/base.rb:61:in `<module:ActiveJob>'
/home/rando/.gem/ruby/2.6.3/gems/activejob-6.0.0/lib/active_job/base.rb:15:in `<main>'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/home/rando/.gem/ruby/2.6.3/gems/chewy-5.0.0/lib/chewy/strategy/active_job.rb:13:in `<class:ActiveJob>'
/home/rando/.gem/ruby/2.6.3/gems/chewy-5.0.0/lib/chewy/strategy/active_job.rb:12:in `<class:Strategy>'
/home/rando/.gem/ruby/2.6.3/gems/chewy-5.0.0/lib/chewy/strategy/active_job.rb:2:in `<module:Chewy>'
/home/rando/.gem/ruby/2.6.3/gems/chewy-5.0.0/lib/chewy/strategy/active_job.rb:1:in `<main>'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/home/rando/.gem/ruby/2.6.3/gems/chewy-5.0.0/lib/chewy/strategy.rb:29:in `<main>'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/home/rando/.gem/ruby/2.6.3/gems/chewy-5.0.0/lib/chewy.rb:53:in `<main>'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/rando/.gem/ruby/2.6.3/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/rando/.gem/ruby/2.6.3/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
/home/rando/.gem/ruby/2.6.3/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
/home/rando/.gem/ruby/2.6.3/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
/home/rando/.gem/ruby/2.6.3/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
/home/rando/.gem/ruby/2.6.3/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
/home/rando/Code/textus/tesseract/config/application.rb:23:in `<main>'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/home/rando/.gem/ruby/2.6.3/gems/railties-6.0.0/lib/rails/command/actions.rb:22:in `require_application!'
/home/rando/.gem/ruby/2.6.3/gems/railties-6.0.0/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
/home/rando/.gem/ruby/2.6.3/gems/railties-6.0.0/lib/rails/commands/console/console_command.rb:101:in `perform'
/home/rando/.gem/ruby/2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/home/rando/.gem/ruby/2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/home/rando/.gem/ruby/2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/home/rando/.gem/ruby/2.6.3/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
/home/rando/.gem/ruby/2.6.3/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
/home/rando/.gem/ruby/2.6.3/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<main>'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/rando/.gem/ruby/2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/rando/.gem/ruby/2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
./bin/rails:6:in `<main>'
```
