### ISSUE TITLE
[Rails 6] Pry and irb completion breaks on a minimal example with a rails-originated (spurious?) deprecation

### ISSUE THREAD

**Issue by steakknife** [rails/rails#37097]
### Steps to reproduce
1.
```
git clone https://github.com/steakknife/mce-erroneous-source-annotation-extractor-deprecation && \
cd mce-erroneous-source-annotation-extractor-deprecation && \
rails db:migrate && \
rails c
```
2. `User.create!`
3. Type `User.last.` and hit <kbd>tab</kbd>

### Expected behavior

`User` methods completion

### Actual behavior
```
        $  rails c
Loading development environment (Rails 6.1.0.alpha)
irb(main):001:0> ActiveSupport::Deprecation.debug = true
=> true
irb(main):002:0> User.last.DEPRECATION WARNING: SourceAnnotationExtractor is deprecated! Use Rails::SourceAnnotationExtractor instead. (called from run at ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor/command.rb:27)
~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:174:in `include?'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:174:in `block (2 levels) in <module:InputCompletor>'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:173:in `each_object'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:173:in `block in <module:InputCompletor>'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/input-method.rb:151:in `readline'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/input-method.rb:151:in `gets'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:473:in `block (2 levels) in eval_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:647:in `signal_status'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:472:in `block in eval_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:189:in `buf_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:104:in `getc'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/slex.rb:206:in `match_io'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/slex.rb:76:in `match'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:292:in `token'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:266:in `lex'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:236:in `block (2 levels) in each_top_level_statement'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `loop'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `catch'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:489:in `eval_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:428:in `block in run'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:427:in `catch'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:427:in `run'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:383:in `start'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands/console/console_command.rb:70:in `start'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands/console/console_command.rb:19:in `start'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands/console/console_command.rb:102:in `perform'
  ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/command/base.rb:65:in `perform'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/command.rb:45:in `invoke'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands.rb:18:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'
DEPRECATION WARNING: SourceAnnotationExtractor is deprecated! Use Rails::SourceAnnotationExtractor instead. (called from run at ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor/command.rb:27)
~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:175:in `block (2 levels) in <module:InputCompletor>'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:173:in `each_object'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:173:in `block in <module:InputCompletor>'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/input-method.rb:151:in `readline'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/input-method.rb:151:in `gets'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:473:in `block (2 levels) in eval_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:647:in `signal_status'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:472:in `block in eval_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:189:in `buf_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:104:in `getc'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/slex.rb:206:in `match_io'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/slex.rb:76:in `match'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:292:in `token'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:266:in `lex'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:236:in `block (2 levels) in each_top_level_statement'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `loop'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `catch'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:489:in `eval_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:428:in `block in run'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:427:in `catch'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:427:in `run'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:383:in `start'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands/console/console_command.rb:70:in `start'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands/console/console_command.rb:19:in `start'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands/console/console_command.rb:102:in `perform'
  ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/command/base.rb:65:in `perform'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/command.rb:45:in `invoke'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands.rb:18:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'
```

### System configuration
**Rails version**: 6.0.0 or master ( 782d28030730c14658a7cd66ee81e7f16c0a12cd )

**Ruby version**: 2.6.4

**OS**: macOS 10.14.6 (18G87)

**Comment by steakknife** [comment]
Originally happened using pry, but that wasn't it; kept shrinking the example and it kept recurring. I tried it on a similar MCE with Rails 5.2.3, and it works just fine.
