### ISSUE TITLE
cannot rollback migration that removes index with long name (not high priority)

### ISSUE THREAD

**Issue by slicksammy** [rails/rails#37247]
### Steps to reproduce
1. create a migration
```
class AddDeletedAtToAuthStudies < ActiveRecord::Migration[5.2]
  def change
     remove_index :auth_studies, [:study_id, :user_id, :permission, :organization_id]
  end
end
```

Note: the index currently has a shortened name

2. run the migration
3. roll it back (it fails)

Workaround (and why not high priority): create `up` and `down` methods and specify shortened index name in `down` method.

Exception:
```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_auth_studies_on_study_id_and_user_id_and_permission_and_organization_id' on table 'auth_studies' is too long; the limit is 63 characters
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:1344:in `validate_index_length!'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:1157:in `add_index_options'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:465:in `add_index'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:871:in `block in method_missing'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:840:in `block in say_with_time'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:840:in `say_with_time'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:860:in `method_missing'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:687:in `block in revert'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:686:in `each'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:686:in `revert'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:812:in `exec_migration'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:797:in `block in migrate'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:796:in `migrate'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `migrate'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1343:in `ddl_transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1046:in `down'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1156:in `move'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1022:in `rollback'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:142:in `block (2 levels) in <top (required)>'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/sammy/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `eval'
/Users/sammy/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
ArgumentError: Index name 'index_auth_studies_on_study_id_and_user_id_and_permission_and_organization_id' on table 'auth_studies' is too long; the limit is 63 characters
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:1344:in `validate_index_length!'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:1157:in `add_index_options'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:465:in `add_index'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:871:in `block in method_missing'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:840:in `block in say_with_time'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:840:in `say_with_time'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:860:in `method_missing'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:687:in `block in revert'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:686:in `each'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:686:in `revert'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:812:in `exec_migration'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:797:in `block in migrate'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:796:in `migrate'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `migrate'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1343:in `ddl_transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1046:in `down'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1156:in `move'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/migration.rb:1022:in `rollback'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:142:in `block (2 levels) in <top (required)>'
/Users/sammy/.rvm/gems/ruby-2.6.4/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/sammy/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `eval'
/Users/sammy/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `<main>'
```

When it tries to roll it back it calculates what the index name should be. As far as I know, you cannot provide `name` option to `remove_index`

### Expected behavior
Should roll it back without exception

### Actual behavior
Exception and rollback failed

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.6.2

**Comment by louim** [comment]
The documentations says that you can pass a name option: https://api.rubyonrails.org/v5.2.3/classes/ActiveRecord/ConnectionAdapters/Table.html#method-i-remove_index

**Comment by slicksammy** [comment]
thanks.
