### ISSUE TITLE
DateTime#advance() expats `integer` params

### ISSUE THREAD

**Issue by shishirsharma** [rails/rails#37425]
### Steps to reproduce

```
irb(main):001:0> require 'rails'; DateTime.now().advance(seconds: 4.days)
Traceback (most recent call last):
        5: from /opt/rubies/2.5.6/bin/irb:11:in `<main>'
        4: from (irb):1
        3: from /Users/shishirsharma/.gem/ruby/2.5.6/gems/activesupport-6.0.0/lib/active_support/core_ext/date_time/calculations.rb:99:in `advance'
        2: from /Users/shishirsharma/.gem/ruby/2.5.6/gems/activesupport-6.0.0/lib/active_support/core_ext/date_time/calculations.rb:113:in `since'
        1: from /Users/shishirsharma/.gem/ruby/2.5.6/gems/activesupport-6.0.0/lib/active_support/core_ext/date_time/calculations.rb:113:in `Rational'
TypeError (not an integer)
irb(main):002:0> Rails.version
=> "6.0.0"
irb(main):003:0>
```

### Expected behavior

```
irb(main):001:0> require 'rails'; DateTime.now().advance(seconds: 4.days)
=> Mon, 14 Oct 2019 11:06:03 -0400
irb(main):002:0> Rails.version
=> "5.2.3"
irb(main):003:0>
```

### Actual behavior

```
irb(main):001:0> require 'rails'; DateTime.now().advance(seconds: 4.days)
Traceback (most recent call last):
        5: from /opt/rubies/2.5.6/bin/irb:11:in `<main>'
        4: from (irb):1
        3: from /Users/shishirsharma/.gem/ruby/2.5.6/gems/activesupport-6.0.0/lib/active_support/core_ext/date_time/calculations.rb:99:in `advance'
        2: from /Users/shishirsharma/.gem/ruby/2.5.6/gems/activesupport-6.0.0/lib/active_support/core_ext/date_time/calculations.rb:113:in `since'
        1: from /Users/shishirsharma/.gem/ruby/2.5.6/gems/activesupport-6.0.0/lib/active_support/core_ext/date_time/calculations.rb:113:in `Rational'
TypeError (not an integer)
irb(main):002:0> Rails.version
=> "6.0.0"
irb(main):003:0>
```

### System configuration
**Rails version**: `6.0.0`
**Ruby version**: `ruby 2.5.6p201 (2019-08-28 revision 67796) [x86_64-darwin18]`

**Comment by joshmn** [comment]
Because seconds expects an integer and `4.days` is `ActiveSupport::Duration`.

`4.days.to_i`

**Comment by shishirsharma** [comment]
I agree but It was working in rails `5.2` :)

**Comment by joshmn** [comment]
What ruby version were you running 5.2 on?

**Comment by joshmn** [comment]
What version of Ruby were you running on 5.2? 

For what it's worth, I was able to reproduce this on 2.5.1 (6.0.0). I was *not* able to reproduce this on 2.6.3 (6.0.0) or 2.4.2 (Rails 5.2.3).

**Comment by shishirsharma** [comment]
My ruby version where it works is `2.4.4`.

**Comment by kkitadate** [comment]
On rails 6.0.1, it was not reproduced in Ruby version 2.6.5, but it was reproduced in 2.5.6.

Added the following test code in #37777 :
```rb
assert_equal DateTime.civil(2005, 2, 26, 10, 10, 10), DateTime.civil(2005, 2, 22, 10, 10, 10).since(4.days)
```
So far it fails in 2.5.6, but succeeds in 2.6.5.
