### ISSUE TITLE
Ruby 2.7 not booting with Rails 6.0 due to load path changes

### ISSUE THREAD

**Issue by SamSaffron** [rails/rails#37464]
```
% bin/rails c
Traceback (most recent call last):
	30: from bin/rails:17:in `<main>'
	29: from bin/rails:17:in `require'
	28: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	27: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
	26: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
	25: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	24: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	23: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	22: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/commands/console/console_command.rb:101:in `perform'
	21: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	20: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command/actions.rb:22:in `require_application!'
	19: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command/actions.rb:22:in `require'
	18: from /home/sam/Source/discourse/config/application.rb:17:in `<top (required)>'
	17: from /home/sam/Source/discourse/config/application.rb:17:in `require'
	16: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activerecord-6.0.0/lib/active_record/railtie.rb:4:in `<top (required)>'
	15: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activerecord-6.0.0/lib/active_record/railtie.rb:4:in `require'
	14: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails.rb:18:in `<top (required)>'
	13: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
	12: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
	11: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
	10: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
	 9: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/railtie.rb:4:in `<top (required)>'
	 8: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
	 7: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
	 6: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
	 5: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
	 4: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/i18n_railtie.rb:8:in `<top (required)>'
	 3: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/i18n_railtie.rb:9:in `<module:I18n>'
	 2: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/i18n_railtie.rb:11:in `<class:Railtie>'
	 1: from /home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/ordered_options.rb:43:in `method_missing'
/home/sam/.rbenv/versions/master/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/ordered_options.rb:43:in `chomp!': can't modify frozen String: "railties_load_path=" (FrozenError)
```

Backtrace alll appears in Rails land so it seems this could be a 2.7 issue?

**Comment by SamSaffron** [comment]
Fixed on Rails 6 stable ... going to close this.

**Comment by n-rodriguez** [comment]
got the same error here :

```sh
nicolas@tchoum:~/PROJECTS/JBOX/royce/spec/dummy$ bin/rails s
[WARNING] Could not load command "rails/commands/server/server_command". Error: can't modify frozen String: "railties_load_path=".
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/ordered_options.rb:43:in `chomp!'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/ordered_options.rb:43:in `method_missing'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/i18n_railtie.rb:11:in `<class:Railtie>'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/i18n_railtie.rb:9:in `<module:I18n>'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/i18n_railtie.rb:8:in `<top (required)>'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/railtie.rb:4:in `<top (required)>'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails.rb:18:in `<top (required)>'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:5:in `require'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:5:in `<top (required)>'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command/behavior.rb:44:in `require'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command/behavior.rb:40:in `each'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command/behavior.rb:40:in `block in lookup'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command/behavior.rb:39:in `each'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command/behavior.rb:39:in `lookup'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command.rb:70:in `find_by_namespace'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/command.rb:44:in `invoke'
/home/nicolas/.rbenv/versions/2.7.0-preview2/lib/ruby/gems/2.7.0/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
rails aborted!
FrozenError: can't modify frozen String: "railties_load_path="
/home/nicolas/PROJECTS/JBOX/royce/spec/dummy/config/application.rb:7:in `<top (required)>'
/home/nicolas/PROJECTS/JBOX/royce/spec/dummy/Rakefile:6:in `require_relative'
/home/nicolas/PROJECTS/JBOX/royce/spec/dummy/Rakefile:6:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

**Comment by jasnow** [comment]
I see *FrozenError: can't modify frozen String: "railties_load_path="** message for 5.2.x and 6.0.x repos. Will this change be back-ported to these Rails versions too? Thanks.

**Comment by atstockland** [comment]
I am getting this on Heroku push too.  

ruby -v = ruby 2.7.0preview2 (2019-10-22 master 02aadf1032) [x86_64-darwin19]
rails -v = Rails 6.0.0
bundler -v = 2.1.0.pre.2
* app executes "bundle exec rake -P" successfully

.....
remote:        Cleaning up the bundler cache.
remote: -----> Detecting rake tasks
remote:
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     FrozenError: can't modify frozen String: "railties_load_path="

.....further down the stack trace

remote: /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/helpers/rake_runner.rb:106:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
remote: ensure you can run `$ bundle exec rake -P` against your app
remote: and using the production group of your Gemfile.
remote: rake aborted!
remote: FrozenError: can't modify frozen String: "railties_load_path="

**Comment by WilfredRuck** [comment]
I'm having the same issue on Heroku push.

ruby v 2.7.0
rails v 5.2.3
bundler v 2.0.2

Same stack trace as @atstockland 
I've tried working my way around it but can't come to a solution. Any new insight on this would be great.

**Comment by augnustin** [comment]
:+1: Same issue as @WilfredRuck 

Any hints on this?
