### ISSUE TITLE
6.0.0 / tests failing due to ActionPack .empty? for nil:NilClass

### ISSUE THREAD

**Issue by petermumford** [rails/rails#37552]
### Expected behavior
I've recently upgraded to rails 6.0.0 from 6.0.0.beta3 and all my integration tests are failing due to the following error: 

```
HomeControllerTest#test_should_see_home_page:
NoMethodError: undefined method `empty?' for nil:NilClass
    /Users/petermumford/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:781:in `optimize_routes_generation?'
    /Users/petermumford/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/routing/url_for.rb:220:in `optimize_routes_generation?'
    /Users/petermumford/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:228:in `optimize_routes_generation?'
    /Users/petermumford/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:198:in `call'
    /Users/petermumford/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:329:in `block in define_url_helper'
    /Users/petermumford/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/testing/integration.rb:404:in `public_send'
    /Users/petermumford/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/testing/integration.rb:404:in `method_missing'
    /Users/petermumford/code/events/test/controllers/home_controller_test.rb:6:in `block in <class:HomeControllerTest>'
```

My test example is very simple:
```
test "should see home page" do
  get root_path
  assert_response :success
end
```

to run my test I use `BACKTRACE=YES rails test test/controllers/home_controller_test.rb` Have I missed something during the upgrade or is this a known bug?

### System configuration
**Rails version**:
6.0.0
**Ruby version**:
2.6.0

**Comment by petermumford** [comment]
Whenever I use a route in my tests I get the error. When I use **byebug** in my test and simply type either `root_path` or `root_url` I get `*** NoMethodError Exception: undefined method 'empty?' for nil:NilClass`

I've tried a new rails app and the tests work as normal so its clearly something missing during the upgrade.

**Comment by petermumford** [comment]
Looking at the `test_helper` file within the `ActiveSupport.on_load(:action_dispatch_integration_test)` block I can use the `@routes` instance in my test as I get the following returned:

`#<ActionDispatch::Routing::RouteSet:0x00007fa97cf88c48>`

**Comment by petermumford** [comment]
If I change my `get` call to `get '/'` it will work but because my views have route paths via 'link_to' it will fail on these instead with the same error as above.

I'll try removing my gems and see if that does anything. Does anyone know what else I could try?

**Comment by petermumford** [comment]
Removing the gems hasn't made any difference.

**Comment by petermumford** [comment]
I've tried a new rails app and the tests work as normal so its clearly something missing during the upgrade.

**Comment by petermumford** [comment]
OK. I've finally found the issue. In my environment.rb file I am doing the following:
```
App::Application.default_url_options = App::Application.config.action_mailer.default_url_options
```
as they both use the same settings. I'm doing this as I'm using the route helpers in my models (XX_path / XX_url). I wasn't setting the `action_mailer.default_url_options` in my **environment/test.rb** file and this is why my routes were breaking. Now I check if the env is in test mode before assigning `App::Application.default_url_options` as the tests automatically use **http://www.example.com** as the url options.
