### ISSUE TITLE
API App: Non API Controllers That Inherit From ActionController::Base Cannot Call http_cache_forever

### ISSUE THREAD

**Issue by sshaw** [rails/rails#37553]
I have an API only app with one controller that deals with attachments. 

### Steps to reproduce

1. Create an API only app `config.api_only = true` in `config/application.rb`
1. Create a controller that's a subclass of `ActionController::Base`
1. include `ActionDispatch::Flash::RequestMethods`
1. In a controller action call `flash[:foo] = 'bar'` or `http_cache_forever` 

### Expected behavior

One should be able to call `http_cache_forever` or even just `flash` in an API only application that uses a controller that's a subclass of `ActionController::Base` and includes the appropriate modules.

### Actual behavior

In a `ActionController::Base`  subclass a call to `http_cache_forever` results in a call to `flash`  which results in:

```
undefined method `flash' for #<ActionDispatch::Request:0x00007fb4416b1ca8>
actionpack (5.2.1.1) lib/action_controller/metal/flash.rb:10:in `flash'
actionpack (5.2.1.1) lib/action_controller/metal/etag_with_flash.rb:15:in `block (2 levels) in <module:EtagWithFlash>'
actionpack (5.2.1.1) lib/action_controller/metal/conditional_get.rb:271:in `instance_exec'
actionpack (5.2.1.1) lib/action_controller/metal/conditional_get.rb:271:in `block in combine_etags'
actionpack (5.2.1.1) lib/action_controller/metal/conditional_get.rb:271:in `map'
actionpack (5.2.1.1) lib/action_controller/metal/conditional_get.rb:271:in `combine_etags'
actionpack (5.2.1.1) lib/action_controller/metal/conditional_get.rb:113:in `fresh_when'
actionpack (5.2.1.1) lib/action_controller/metal/conditional_get.rb:219:in `stale?'
actionpack (5.2.1.1) lib/action_controller/metal/conditional_get.rb:264:in `http_cache_forever'
actionpack (5.2.1.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.1.1) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.1.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.1.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.1.1) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.1.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.1.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.1.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.1.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.1.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.1.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.1.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.1.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.1.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.1.1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.1.1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.1.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.1.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.1.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.1.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.1.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.1.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.1.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.1.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
activerecord (5.2.1.1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.1.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.1.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.1.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.1.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.1.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.1.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.1.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.1.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.1.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.1.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.1.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.1.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.1.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.1.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
railties (5.2.1.1) lib/rails/engine.rb:524:in `call'
rack (2.0.7) lib/rack/handler/webrick.rb:86:in `service'
/Users/sshaw/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
/Users/sshaw/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
/Users/sshaw/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
Request
``` 

When the controller includes `ActionDispatch::Flash::RequestMethods` the error becomes:

```
undefined method `get_header' for #<TestController:0x00007fb32724ecf8>
```

### System configuration
**Rails version**: 5.2.3 

**Ruby version**: 2.5.1

**Comment by sshaw** [comment]
Note that in the test environment the code executes successfully.
