### ISSUE TITLE
ActiveStorage: ActionController::UrlGenerationError when `routes_prefix` set to a variable

### ISSUE THREAD

**Issue by alexeyeva** [rails/rails#37663]
### Steps to reproduce
- system using multitenancy (a schema per tenant, [apartment gem](https://github.com/influitive/apartment))
- routes prefix `(/:tenant_slug)` as an indicator of the tenant
- set up ActiveStorage
- request a file via link generated by `Rails.application.routes.url_helpers.rails_representation_url` or `Rails.application.routes.url_helpers.rails_blob_path`

In our project there is a multitenancy implemented, so for each tenant a schema (postgresql feature) is switched.
Tenant is gotten from the url. (so all routes have `(/:tenant_slug)` as a prefix)

Before, files were stored in a public schema, but then apparently some random images got shown because they matched already existing ids (from other schema). That's why we have to store files related to a tenant in the particular tenant.

So firstly, I have set `config.active_storage.routes_prefix = "(/:tenant_slug)"` for image to be taken from the necessary schema.

Our backend sends to a frontend app an url in a serializer of an object, generated via `Rails.application.routes.url_helpers.rails_representation_url` or `Rails.application.routes.url_helpers.rails_blob_path` (e.g.           `Rails.application.routes.url_helpers.rails_blob_path(object.image, only_path: true, tenant_slug: "demo")
)
Trying to get an image via sending a GET request to this url:

### Expected behavior
The image has been shown, no errors raised.

### Actual behavior
Gotten an error `ActionController::UrlGenerationError (No route matches {:action=>"show", :content_type=>"image/jpeg", :controller=>"active_storage/disk", :disposition=>"inline; filename=\"1573147535\"; filename*=UTF-8''1573147535", :filename=>#<ActiveStorage::Filename:0x00007f7f35792230 @filename="1573147535">, :tenant_slug=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhjR052YW10c2NHeHlPRzgxWm1oMWJqaHdabUYzZVhkb01YVTNaUVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUDJsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SWpFMU56TXhORGMxTXpVaU95Qm1hV3hsYm1GdFpTbzlWVlJHTFRnbkp6RTFOek14TkRjMU16VUdPd1pVT2hGamIyNTBaVzUwWDNSNWNHVkpJZzlwYldGblpTOXFjR1ZuQmpzR1ZBPT0iLCJleHAiOiIyMDE5LTExLTA4VDEyOjEwOjQwLjEzNVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--0446fc8ee242542f259b060f3b6db542f7338576"}, missing required keys: [:encoded_key])`

Here is the full trace:
```
Started GET "/demo/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fc3153060a997a083d34d7cdad8e5f29e4509446/1573147535" for ::1 at 2019-11-08 14:05:40 +0200
  Tenant Load (0.6ms)  SELECT "public"."tenants".* FROM "public"."tenants" WHERE ('localhost' = ANY(domains) OR slug = 'demo') LIMIT $1  [["LIMIT", 1]]
  ↳ app/middleware/tenant_slug_elevator.rb:23:in `find_tenant_by!'
Processing by ActiveStorage::BlobsController#show as HTML
  Parameters: {"tenant_slug"=>"demo", "signed_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fc3153060a997a083d34d7cdad8e5f29e4509446", "filename"=>"1573147535"}
  ActiveStorage::Blob Load (3.0ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 5], ["LIMIT", 1]]
  Disk Storage (0.9ms) Generated URL for file at key: pcojklplr8o5fhun8pfawywh1u7e ()
Completed 500 Internal Server Error in 6ms (ActiveRecord: 3.0ms | Allocations: 2077)

ActionController::UrlGenerationError (No route matches {:action=>"show", :content_type=>"image/jpeg", :controller=>"active_storage/disk", :disposition=>"inline; filename=\"1573147535\"; filename*=UTF-8''1573147535", :filename=>#<ActiveStorage::Filename:0x00007f7f35792230 @filename="1573147535">, :tenant_slug=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhjR052YW10c2NHeHlPRzgxWm1oMWJqaHdabUYzZVhkb01YVTNaUVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUDJsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SWpFMU56TXhORGMxTXpVaU95Qm1hV3hsYm1GdFpTbzlWVlJHTFRnbkp6RTFOek14TkRjMU16VUdPd1pVT2hGamIyNTBaVzUwWDNSNWNHVkpJZzlwYldGblpTOXFjR1ZuQmpzR1ZBPT0iLCJleHAiOiIyMDE5LTExLTA4VDEyOjEwOjQwLjEzNVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--0446fc8ee242542f259b060f3b6db542f7338576"}, missing required keys: [:encoded_key]):

actionpack (6.0.0) lib/action_dispatch/journey/formatter.rb:57:in `generate'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:741:in `generate'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:772:in `generate'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:819:in `url_for'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:272:in `call'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:329:in `block in define_url_helper'
activestorage (6.0.0) lib/active_storage/service/disk_service.rb:89:in `block in url'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `instrument'
activestorage (6.0.0) lib/active_storage/service.rb:126:in `instrument'
activestorage (6.0.0) lib/active_storage/service/disk_service.rb:75:in `url'
activestorage (6.0.0) app/models/active_storage/blob.rb:143:in `service_url'
activestorage (6.0.0) app/controllers/active_storage/blobs_controller.rb:12:in `show'
actionpack (6.0.0) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.0) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.0) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.0) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.0) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.0) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.0) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.0) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.0) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.0) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:837:in `call'
apartment (f266f73e5883) lib/apartment/elevators/generic.rb:21:in `block in call'
apartment (f266f73e5883) lib/apartment/adapters/abstract_adapter.rb:85:in `switch'
/Users/luna/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `switch'
apartment (f266f73e5883) lib/apartment/elevators/generic.rb:21:in `call'
apartment (f266f73e5883) lib/apartment/reloader.rb:18:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (6.0.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.0) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
bugsnag (6.12.1) lib/bugsnag/integrations/rack.rb:49:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
webpacker (4.0.7) lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.0) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

### System configuration
**Rails version**: Rails 6.0.0

**Ruby version**: 2.6.3

active_storage_base64 (1.0.0)

`config.active_storage.service = :local`

**Comment by theasteve** [comment]
Hi @alexeyeva, can you add your routes to this thread. I wonder if the issue is coming from what you stated:
```
So firstly, I have set config.active_storage.routes_prefix = "(/:tenant_slug)" for image to be taken from the necessary schema.
```
which could corrupt the path prefix.

**Comment by alexeyeva** [comment]
Hi @theasteve, sorry for the delay.
routes for ActiveStorage look like
```ruby
rails_service_blob GET      (/:organization_slug)/blobs/:signed_id/*filename(.:format)                                                                  active_storage/blobs#show
rails_blob_representation GET      (/:organization_slug)/representations/:signed_blob_id/:variation_key/*filename(.:format)                                    active_storage/representations#show
rails_disk_service GET      (/:organization_slug)/disk/:encoded_key/*filename(.:format)                                                                 active_storage/disk#show
update_rails_disk_service PUT      (/:organization_slug)/disk/:encoded_token(.:format)                                                                         active_storage/disk#update
rails_direct_uploads POST     (/:organization_slug)/direct_uploads(.:format)                                                                              active_storage/direct_uploads#create
```
