### ISSUE TITLE
Action Text error in form field on production [Heroku + Rails 6]

### ISSUE THREAD

**Issue by modusss** [rails/rails#37672]
This mysterious error was showing just after action text was installed on development environment and then vanished without any change on the code.

After many tests and working ok on localhost I pushed to staging env (heroku) and it is showing:

> undefined method `rich_text_area_tag'

![image](https://user-images.githubusercontent.com/20300214/68531037-d4908580-02ec-11ea-84c9-b9e350608ea4.png)

Config:

**models/mailing.rb**

```
class Mailing < ApplicationRecord

  has_rich_text :body

end
```

### System configuration
Rails 6.0.0
Ruby 2.6.5

This issue I also asked on [stackoverflow ](https://stackoverflow.com/questions/58766900/action-text-not-working-on-heroku-rails-6) with no response.

-----------------------------------------

**Edit:**

I tried to turn around this issue just copying from html on the view:

replacing from:

`<%= form.rich_text_area :body %>`

to

```
    <div class="field">
      <label>Body</label>
      <input type="hidden" name="mailing[body]" id="trix_input_mailing"><trix-toolbar id="trix-toolbar-1"><div class="button_row">
      <span class="button_group text_tools">
        <button type="button" class="icon bold" data-trix-attribute="bold" data-trix-key="b" title="Bold">Bold</button>
        <button type="button" class="icon italic" data-trix-attribute="italic" data-trix-key="i" title="Italic">Italic</button>
        <button type="button" class="icon strike" data-trix-attribute="strike" title="Strikethrough">Strikethrough</button>
        <button type="button" class="icon link" data-trix-attribute="href" data-trix-action="link" data-trix-key="k" title="Link">Link</button>
      </span>

      <span class="button_group block_tools">
        <button type="button" class="icon heading-1" data-trix-attribute="heading1" title="Heading">Heading</button>
        <button type="button" class="icon quote" data-trix-attribute="quote" title="Quote">Quote</button>
        <button type="button" class="icon code" data-trix-attribute="code" title="Code">Code</button>
        <button type="button" class="icon list bullets" data-trix-attribute="bullet" title="Bullets">Bullets</button>
        <button type="button" class="icon list numbers" data-trix-attribute="number" title="Numbers">Numbers</button>
        <button type="button" class="icon nesting-level decrease" data-trix-action="decreaseNestingLevel" title="Decrease Level" disabled="">Decrease Level</button>
        <button type="button" class="icon nesting-level increase" data-trix-action="increaseNestingLevel" title="Increase Level" disabled="">Increase Level</button>
      </span>

      <span class="button_group history_tools">
        <button type="button" class="icon undo" data-trix-action="undo" data-trix-key="z" title="Undo" disabled="">Undo</button>
        <button type="button" class="icon redo" data-trix-action="redo" data-trix-key="shift+z" title="Redo" disabled="">Redo</button>
      </span>
    </div>

    <div class="dialogs">
      <div class="dialog link_dialog" data-trix-attribute="href" data-trix-dialog="href">
        <div class="link_url_fields">
          <input type="url" required="" name="href" placeholder="Enter a URL…" disabled="disabled">
          <div class="button_group">
            <input type="button" value="Link" data-trix-method="setAttribute">
            <input type="button" value="Unlink" data-trix-method="removeAttribute">
          </div>
        </div>
      </div>
    </div></trix-toolbar>
      <trix-editor input="trix_input_mailing" class="trix-content" data-direct-upload-url="<%= request.base_url %>/rails/active_storage/direct_uploads" data-blob-url-template="<%= request.base_url %>/rails/active_storage/blobs/:signed_id/:filename" contenteditable="" trix-id="1" toolbar="trix-toolbar-1"></trix-editor>
    </div>
```

but even showing the correct content on this view Rails cannot recognize the virtual field that I called "body" and save it to be displayed on show page:

![image](https://user-images.githubusercontent.com/20300214/68533886-06194900-030d-11ea-8070-7a2a528051dc.png)

-----------------------------------------------

#How the field displays with active record in console:

**localhost:**
![image](https://user-images.githubusercontent.com/20300214/68690490-df4b5480-0550-11ea-9a37-34a86461e0a5.png)

**heroku:**
> ActionView::Template::Error (undefined method `render_action_text_content' for #<#<Class:0x00000000058bca40>:0x0000000008ab57e0>)

![image](https://user-images.githubusercontent.com/20300214/68690652-21749600-0551-11ea-9653-22c0bc826c6f.png)

**Comment by Paprikas** [comment]
Same here. On production (on Digital Ocean).
Even if I try to edit - I'll get an error:
```
undefined method `rich_text_area_tag' for #<#<Class:0x0000560e02c64308>:0x00007fef58030b98>
Did you mean?  rich_text_area
```

Ruby 2.6.5
Rails 6.0.2.1

**Comment by Paprikas** [comment]
@modusss I found what cause my problem.
I'm using ActiveAdmin with friendly_id gem, and to avoid conflict, I've added this chunk of code to active_admin initializer.
```
  ActiveAdmin::ResourceController.class_eval do
  end
```
Still looking for solution to fix conflict with AA and friendly_id without crashing ActionText

**Comment by cirdes** [comment]
I'm facing the same issue here. Everything works fine in development.
In Heroku If my rich text field(signature) is empty, I can edit through ActiveAdmin. But if I try to modify again, I get the error

Sentry Raw
```
NoMethodError: undefined method `render_action_text_content' for #<#<Class:0x00007f63a9903cd8>:0x00007f63a9902360>
  from bundle/ruby/2.6.0/gems/actiontext-6.0.2.1/app/views/action_text/content/_layout.html.erb:2:in `_vendor_bundle_ruby_______gems_actiontext_________app_views_action_text_content__layout_html_erb__660081814264943039_70033011681660'
  from action_view/base.rb:274:in `_run'
  from action_view/template.rb:185:in `block in render'
  from active_support/notifications.rb:180:in `block in instrument'
  from active_support/notifications/instrumenter.rb:24:in `instrument'
  from active_support/notifications.rb:180:in `instrument'
  from action_view/template.rb:386:in `instrument_render_template'
  from action_view/template.rb:183:in `render'
  from action_view/renderer/partial_renderer.rb:358:in `block in render_partial'
  from action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
  from active_support/notifications.rb:180:in `block in instrument'
  from active_support/notifications/instrumenter.rb:24:in `instrument'
  from active_support/notifications.rb:180:in `instrument'
  from action_view/renderer/abstract_renderer.rb:88:in `instrument'
  from action_view/renderer/partial_renderer.rb:347:in `render_partial'
  from action_view/renderer/partial_renderer.rb:317:in `render'
  from action_view/renderer/renderer.rb:65:in `render_partial_to_object'
  from action_view/renderer/renderer.rb:27:in `render_to_object'
  from action_view/rendering.rb:118:in `block in _render_template'
  from action_view/base.rb:304:in `in_rendering_context'
  from action_view/rendering.rb:117:in `_render_template'
  from action_controller/metal/streaming.rb:219:in `_render_template'
  from action_view/rendering.rb:103:in `render_to_body'
  from action_controller/metal/rendering.rb:52:in `render_to_body'
  from action_controller/metal/renderers.rb:142:in `render_to_body'
  from abstract_controller/rendering.rb:46:in `render_to_string'
  from action_controller/metal/rendering.rb:41:in `render_to_string'
  from action_controller/renderer.rb:96:in `render'
  from action_text/content.rb:91:in `to_rendered_html_with_layout'
  from action_text/content.rb:95:in `to_s'
  from action_text/content.rb:108:in `=='
  from active_model/type/value.rb:65:in `!='
  from active_model/type/value.rb:65:in `changed?'
  from delegate.rb:349:in `block in delegating_block'
  from active_model/attribute.rb:155:in `changed_from_assignment?'
  from active_model/attribute.rb:59:in `changed?'
  from active_model/attribute_mutation_tracker.rb:76:in `attribute_changed?'
  from active_model/attribute_mutation_tracker.rb:46:in `changed?'
  from active_model/attribute_mutation_tracker.rb:42:in `block in any_changes?'
  from active_model/attribute_mutation_tracker.rb:42:in `any?'
  from active_model/attribute_mutation_tracker.rb:42:in `any_changes?'
  from active_record/attribute_methods/dirty.rb:133:in `has_changes_to_save?'
  from active_record/autosave_association.rb:266:in `changed_for_autosave?'
  from active_record/autosave_association.rb:307:in `validate_single_association'
  from active_record/autosave_association.rb:220:in `block in define_autosave_validation_callbacks'
  from active_record/autosave_association.rb:159:in `instance_eval'
  from active_record/autosave_association.rb:159:in `block in define_non_cyclic_method'
  from active_support/callbacks.rb:429:in `block in make_lambda'
  from active_support/callbacks.rb:201:in `block (2 levels) in halting'
  from active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
  from active_support/callbacks.rb:606:in `catch'
  from active_support/callbacks.rb:606:in `block in default_terminator'
  from active_support/callbacks.rb:202:in `block in halting'
  from active_support/callbacks.rb:514:in `block in invoke_before'
  from active_support/callbacks.rb:514:in `each'
  from active_support/callbacks.rb:514:in `invoke_before'
  from active_support/callbacks.rb:134:in `run_callbacks'
  from active_support/callbacks.rb:827:in `_run_validate_callbacks'
  from active_model/validations.rb:407:in `run_validations!'
  from active_model/validations/callbacks.rb:118:in `block in run_validations!'
  from active_support/callbacks.rb:135:in `run_callbacks'
  from active_support/callbacks.rb:827:in `_run_validation_callbacks'
  from active_model/validations/callbacks.rb:118:in `run_validations!'
  from active_model/validations.rb:337:in `valid?'
  from active_record/validations.rb:68:in `valid?'
  from active_record/validations.rb:85:in `perform_validations'
  from active_record/validations.rb:47:in `save'
  from active_record/transactions.rb:315:in `block in save'
  from active_record/transactions.rb:375:in `block in with_transaction_returning_status'
  from active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
  from active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
  from monitor.rb:235:in `mon_synchronize'
  from active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
  from active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from active_record/transactions.rb:366:in `with_transaction_returning_status'
  from active_record/transactions.rb:315:in `save'
  from active_record/suppressor.rb:44:in `save'
  from new_relic/agent/instrumentation/active_record_prepend.rb:16:in `block in save'
  from new_relic/agent/transaction.rb:811:in `with_database_metric_name'
  from new_relic/agent.rb:644:in `with_database_metric_name'
  from new_relic/agent/instrumentation/active_record_prepend.rb:15:in `save'
  from active_admin/resource_controller/data_access.rb:155:in `block in save_resource'
  from active_support/core_ext/object/try.rb:15:in `public_send'
  from active_support/core_ext/object/try.rb:15:in `try'
  from active_admin/callbacks.rb:79:in `block (2 levels) in define_active_admin_callbacks'
  from active_admin/resource_controller/data_access.rb:154:in `save_resource'
  from active_admin/resource_controller/data_access.rb:173:in `block in update_resource'
  from active_support/core_ext/object/try.rb:15:in `public_send'
  from active_support/core_ext/object/try.rb:15:in `try'
  from active_admin/callbacks.rb:79:in `block (2 levels) in define_active_admin_callbacks'
  from active_admin/resource_controller/data_access.rb:172:in `update_resource'
  from inherited_resources/actions.rb:45:in `update'
  from action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from abstract_controller/base.rb:196:in `process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/callbacks.rb:42:in `block in process_action'
  from active_support/callbacks.rb:112:in `block in run_callbacks'
  from raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  from active_support/callbacks.rb:121:in `instance_exec'
  from active_support/callbacks.rb:121:in `block in run_callbacks'
  from active_support/callbacks.rb:139:in `run_callbacks'
  from abstract_controller/callbacks.rb:41:in `process_action'
  from action_controller/metal/rescue.rb:22:in `process_action'
  from action_controller/metal/instrumentation.rb:33:in `block in process_action'
  from active_support/notifications.rb:180:in `block in instrument'
  from active_support/notifications/instrumenter.rb:24:in `instrument'
  from active_support/notifications.rb:180:in `instrument'
  from action_controller/metal/instrumentation.rb:32:in `process_action'
  from action_controller/metal/params_wrapper.rb:245:in `process_action'
  from active_record/railties/controller_runtime.rb:27:in `process_action'
  from abstract_controller/base.rb:136:in `process'
  from action_view/rendering.rb:39:in `process'
  from action_controller/metal.rb:191:in `dispatch'
  from action_controller/metal.rb:252:in `dispatch'
  from action_dispatch/routing/route_set.rb:51:in `dispatch'
  from action_dispatch/routing/route_set.rb:33:in `serve'
  from action_dispatch/journey/router.rb:49:in `block in serve'
  from action_dispatch/journey/router.rb:32:in `each'
  from action_dispatch/journey/router.rb:32:in `serve'
  from action_dispatch/routing/route_set.rb:837:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from new_relic/rack/agent_hooks.rb:30:in `traced_call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/builder.rb:153:in `call'
  from warden/jwt_auth/middleware.rb:23:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from warden/manager.rb:36:in `block in call'
  from warden/manager.rb:34:in `catch'
  from warden/manager.rb:34:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/tempfile_reaper.rb:15:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/etag.rb:25:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/conditional_get.rb:38:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/head.rb:12:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/http/content_security_policy.rb:18:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/session/abstract/id.rb:259:in `context'
  from rack/session/abstract/id.rb:253:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/cookies.rb:648:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/callbacks.rb:27:in `block in call'
  from active_support/callbacks.rb:101:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:26:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:32:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rails/rack/logger.rb:38:in `call_app'
  from rails/rack/logger.rb:26:in `block in call'
  from active_support/tagged_logging.rb:80:in `block in tagged'
  from active_support/tagged_logging.rb:28:in `tagged'
  from active_support/tagged_logging.rb:80:in `tagged'
  from rails/rack/logger.rb:26:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/remote_ip.rb:81:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from request_store/middleware.rb:19:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/request_id.rb:27:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/method_override.rb:22:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/runtime.rb:22:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/executor.rb:14:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/static.rb:126:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/sendfile.rb:111:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/ssl.rb:74:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/host_authorization.rb:77:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rails/engine.rb:526:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from puma/configuration.rb:228:in `call'
  from puma/server.rb:681:in `handle_request'
  from puma/server.rb:472:in `process_client'
  from puma/server.rb:328:in `block in run'
  from puma/thread_pool.rb:134:in `block in spawn_thread'
```
Sentry Full
<img width="1221" alt="Screen Shot 2020-02-06 at 11 11 08 AM" src="https://user-images.githubusercontent.com/727781/73970105-6fd7cd80-48d1-11ea-8c1c-b956060f084f.png">


System configuration
Heroku
Rails 6.0.2.1
Ruby 2.6.5

models/buyer.rb
```
class Buyer < ApplicationRecord
  has_rich_text :signature
end
```

admin/buyers.rb
```
# frozen_string_literal: true

ActiveAdmin.register Buyer do
  controller { helper ActionText::Engine.helpers }

  form do |f|
    inputs 'Assinatura do Buyer' do
      f.rich_text_area :signature
    end

    actions
  end

  show do
    attributes_table do
      row :signature do |buyer|
        buyer.signature.to_plain_text
      end
    end
  end

  actions :all

  permit_params :signature
end

```

**Comment by cirdes** [comment]
@modusss, the workaround I found was copy everything inside the https://github.com/rails/rails/blob/28775ff3a231253c0052531f7d4e6b264b15497b/actiontext/app/helpers/action_text/content_helper.rb to my ApplicationHelper.rb, and now It's working!

```
module ApplicationHelper
  mattr_accessor(:sanitizer) { Rails::Html::Sanitizer.safe_list_sanitizer.new }
  mattr_accessor(:allowed_tags) do
    sanitizer.class.allowed_tags +
      [ActionText::Attachment::TAG_NAME, 'figure', 'figcaption']
  end
  mattr_accessor(:allowed_attributes) do
    sanitizer.class.allowed_attributes + ActionText::Attachment::ATTRIBUTES
  end
  mattr_accessor(:scrubber)

  def render_action_text_content(content)
    sanitize_action_text_content(render_action_text_attachments(content))
  end

  def sanitize_action_text_content(content)
    sanitizer.sanitize(
      content.to_html,
      tags: allowed_tags, attributes: allowed_attributes, scrubber: scrubber
    )
      .html_safe
  end

  def render_action_text_attachments(content)
    content.render_attachments do |attachment|
      unless attachment.in?(content.gallery_attachments)
        attachment.node.tap do |node|
          node.inner_html = render(attachment, in_gallery: false).chomp
        end
      end
    end.render_attachment_galleries do |attachment_gallery|
      render(layout: attachment_gallery, object: attachment_gallery) do
        attachment_gallery.attachments.map do |attachment|
          attachment.node.inner_html =
            render(attachment, in_gallery: true).chomp
          attachment.to_html
        end.join
          .html_safe
      end.chomp
    end
  end
end

```

**Comment by p8** [comment]
I'm seeing this error with the classic autoloader.

**Comment by p8** [comment]
A quick fix is to add an initializer with the following code:
```
ActiveSupport.on_load(:action_view) do
  include ActionText::ContentHelper
  include ActionText::TagHelper
end
```

**Comment by lordofthedanse** [comment]
This is still an issue in 6.0.3.1 when eager_load is on (no ActiveAdmin or friendly_id in my code). All runs fine in development (I pulled down production database). The issue popped up with eager_loading on. Both zeitwerk and classic eager_loading missed loading ActionText helpers locally. Including the helpers manually is a fix, verified in production on Heroku.

**Comment by pauloancheta** [comment]
Just got this error on circleci.

rails version: 6.0.3.2
ruby version: 2.5.5

**Comment by PQALAB** [comment]
I just had this happen to me and the initializers fixed worked as well

rails version: 6.0.3.4
ruby version: 2.5.0

**Comment by jeantristan** [comment]
Having the same issue.
rails version : Rails 6.1.3.2
ruby version 2.7.2

**Comment by fahadmu** [comment]
Same (works on production if cache_classes = False)
Rails 6.1.4.1
Ruby 2.7.3

**Comment by eliten00b** [comment]
No initializer solution:
```ruby
module ApplicationHelper

  include ActionText::ContentHelper
  include ActionText::TagHelper

end
```

**Comment by Fodoj** [comment]
As eager_load is be default `true`, what would be the proper fix to this issue? From description feels like ActionText does not work out of the box for prod environments, which is what my experience as well - but I assume I am doing something wrong, not Rails.
