### ISSUE TITLE
QueryCacheTest#test_query_cache_with_multiple_handlers_and_forked_processees fails with sqlite3_mem

### ISSUE THREAD

**Issue by yahonda** [rails/rails#37734]
Managed to reproduce  https://buildkite.com/rails/rails/builds/64967#b2671665-1e31-42bd-b9d3-dfcfcea32db8

### Steps to reproduce

```ruby
$ cd activerecord
$ ARCONN=sqlite3_mem bin/test test/cases/arel/attributes/math_test.rb test/cases/query_cache_test.rb -n "/^(?:Arel::Attributes::MathTest#(?:test_0031_average should be compatible with ^)|QueryCacheTest#(?:test_query_cache_with_multiple_handlers_and_forked_processes))$/" --seed 33916
```

### Expected behavior
It should pass.

### Actual behavior

```ruby
$ ARCONN=sqlite3_mem bin/test test/cases/arel/attributes/math_test.rb test/cases/query_cache_test.rb -n "/^(?:Arel::Attributes::MathTest#(?:test_0031_average should be compatible with ^)|QueryCacheTest#(?:test_query_cache_with_multiple_handlers_and_forked_processes))$/" --seed 33916
Using sqlite3_mem
Run options: -n "/^(?:Arel::Attributes::MathTest#(?:test_0031_average should be compatible with ^)|QueryCacheTest#(?:test_query_cache_with_multiple_handlers_and_forked_processes))$/" --seed 33916

# Running:

Traceback (most recent call last):
	66: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:66:in `block in autorun'
	65: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:139:in `run'
	64: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:162:in `__run'
	63: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:162:in `map'
	62: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:162:in `block in __run'
	61: from /home/yahonda/git/rails/railties/lib/rails/test_unit/line_filtering.rb:10:in `run'
	60: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:322:in `run'
	59: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:350:in `with_info_handler'
	58: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:363:in `on_signal'
	57: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:323:in `block in run'
	56: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:323:in `each'
	55: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:324:in `block (2 levels) in run'
	54: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:337:in `run_one_method'
	53: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:1014:in `run_one_method'
	52: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest/test.rb:93:in `run'
	51: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest/test.rb:211:in `with_info_handler'
	50: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:363:in `on_signal'
	49: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest/test.rb:94:in `block in run'
	48: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:268:in `time_it'
	47: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest/test.rb:95:in `block (2 levels) in run'
	46: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest/test.rb:195:in `capture_exceptions'
	45: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest/test.rb:98:in `block (3 levels) in run'
	44: from /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:93:in `test_query_cache_with_multiple_handlers_and_forked_processes'
	43: from /home/yahonda/git/rails/activesupport/lib/active_support/fork_tracker.rb:8:in `fork'
	42: from /home/yahonda/git/rails/activesupport/lib/active_support/fork_tracker.rb:8:in `fork'
	41: from /home/yahonda/git/rails/activesupport/lib/active_support/fork_tracker.rb:10:in `block in fork'
	40: from /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:120:in `block in test_query_cache_with_multiple_handlers_and_forked_processes'
	39: from /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:630:in `block in middleware'
	38: from /home/yahonda/git/rails/activesupport/lib/active_support/execution_wrapper.rb:88:in `wrap'
	37: from /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:630:in `block (2 levels) in middleware'
	36: from /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:102:in `block (2 levels) in test_query_cache_with_multiple_handlers_and_forked_processes'
	35: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_handling.rb:139:in `connected_to'
	34: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_handling.rb:176:in `with_handler'
	33: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_handling.rb:266:in `swap_connection_handler'
	32: from /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:103:in `block (3 levels) in test_query_cache_with_multiple_handlers_and_forked_processes'
	31: from /home/yahonda/git/rails/activerecord/lib/active_record/querying.rb:21:in `first'
	30: from /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:129:in `first'
	29: from /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:521:in `find_nth'
	28: from /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:536:in `find_nth_with_limit'
	27: from /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:245:in `to_ary'
	26: from /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:250:in `records'
	25: from /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:629:in `load'
	24: from /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:811:in `exec_queries'
	23: from /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:844:in `skip_query_cache_if_necessary'
	22: from /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:826:in `block in exec_queries'
	21: from /home/yahonda/git/rails/activerecord/lib/active_record/querying.rb:46:in `find_by_sql'
	20: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:105:in `select_all'
	19: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:113:in `cache_sql'
	18: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	17: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:122:in `block in cache_sql'
	16: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:105:in `block in select_all'
	15: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'
	14: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:493:in `select_prepared'
	13: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:44:in `exec_query'
	12: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:676:in `log'
	11: from /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	10: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:685:in `block in log'
	 9: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	 8: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:686:in `block (2 levels) in log'
	 7: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:45:in `block in exec_query'
	 6: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
	 5: from /home/yahonda/git/rails/activesupport/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	 4: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
	 3: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:59:in `block (2 levels) in exec_query'
	 2: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:147:in `prepare'
	 1: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:147:in `new'
/home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:147:in `initialize': no such table: posts (SQLite3::SQLException)
	66: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:66:in `block in autorun'
	65: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:139:in `run'
	64: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:162:in `__run'
	63: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:162:in `map'
	62: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:162:in `block in __run'
	61: from /home/yahonda/git/rails/railties/lib/rails/test_unit/line_filtering.rb:10:in `run'
	60: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:322:in `run'
	59: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:350:in `with_info_handler'
	58: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:363:in `on_signal'
	57: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:323:in `block in run'
	56: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:323:in `each'
	55: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:324:in `block (2 levels) in run'
	54: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:337:in `run_one_method'
	53: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:1014:in `run_one_method'
	52: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest/test.rb:93:in `run'
	51: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest/test.rb:211:in `with_info_handler'
	50: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:363:in `on_signal'
	49: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest/test.rb:94:in `block in run'
	48: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest.rb:268:in `time_it'
	47: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest/test.rb:95:in `block (2 levels) in run'
	46: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest/test.rb:195:in `capture_exceptions'
	45: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minitest-5.12.2/lib/minitest/test.rb:98:in `block (3 levels) in run'
	44: from /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:93:in `test_query_cache_with_multiple_handlers_and_forked_processes'
	43: from /home/yahonda/git/rails/activesupport/lib/active_support/fork_tracker.rb:8:in `fork'
	42: from /home/yahonda/git/rails/activesupport/lib/active_support/fork_tracker.rb:8:in `fork'
	41: from /home/yahonda/git/rails/activesupport/lib/active_support/fork_tracker.rb:10:in `block in fork'
	40: from /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:120:in `block in test_query_cache_with_multiple_handlers_and_forked_processes'
	39: from /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:630:in `block in middleware'
	38: from /home/yahonda/git/rails/activesupport/lib/active_support/execution_wrapper.rb:88:in `wrap'
	37: from /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:630:in `block (2 levels) in middleware'
	36: from /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:102:in `block (2 levels) in test_query_cache_with_multiple_handlers_and_forked_processes'
	35: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_handling.rb:139:in `connected_to'
	34: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_handling.rb:176:in `with_handler'
	33: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_handling.rb:266:in `swap_connection_handler'
	32: from /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:103:in `block (3 levels) in test_query_cache_with_multiple_handlers_and_forked_processes'
	31: from /home/yahonda/git/rails/activerecord/lib/active_record/querying.rb:21:in `first'
	30: from /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:129:in `first'
	29: from /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:521:in `find_nth'
	28: from /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:536:in `find_nth_with_limit'
	27: from /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:245:in `to_ary'
	26: from /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:250:in `records'
	25: from /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:629:in `load'
	24: from /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:811:in `exec_queries'
	23: from /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:844:in `skip_query_cache_if_necessary'
	22: from /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:826:in `block in exec_queries'
	21: from /home/yahonda/git/rails/activerecord/lib/active_record/querying.rb:46:in `find_by_sql'
	20: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:105:in `select_all'
	19: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:113:in `cache_sql'
	18: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	17: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:122:in `block in cache_sql'
	16: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:105:in `block in select_all'
	15: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'
	14: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:493:in `select_prepared'
	13: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:44:in `exec_query'
	12: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:676:in `log'
	11: from /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	10: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:685:in `block in log'
	 9: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	 8: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:686:in `block (2 levels) in log'
	 7: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:45:in `block in exec_query'
	 6: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
	 5: from /home/yahonda/git/rails/activesupport/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	 4: from /home/yahonda/git/rails/activesupport/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
	 3: from /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:59:in `block (2 levels) in exec_query'
	 2: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:147:in `prepare'
	 1: from /home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:147:in `new'
/home/yahonda/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:147:in `initialize': SQLite3::SQLException: no such table: posts (ActiveRecord::StatementInvalid)
E

Error:
QueryCacheTest#test_query_cache_with_multiple_handlers_and_forked_processes:
ArgumentError: marshal data too short
    /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:130:in `load'
    /home/yahonda/git/rails/activerecord/test/cases/query_cache_test.rb:130:in `test_query_cache_with_multiple_handlers_and_forked_processes'


bin/test test/cases/query_cache_test.rb:79



Finished in 0.044743s, 22.3497 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$ 
```

### System configuration
**Rails version**:master

**Ruby version**:ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

**Comment by yahonda** [comment]
It reproduces since https://github.com/rails/rails/commit/2d695a914ac3d14d5e1a07e40cf83e7301388e87
