### ISSUE TITLE
Calling "order" crashes when the model isn't represented by a database table

### ISSUE THREAD

**Issue by frostblooded** [rails/rails#37741]
### Steps to reproduce
Gist to reproduce: https://gist.github.com/frostblooded/6dd3c598c8de42751c2b43893bb0de63

### Expected behavior
When I was using ActiveRecord 5.1.7, the `order` method would work with the fake model and then we could call `to_sql`. This was used for testing concerns without using any exact existing model.

### Actual behavior
Now calling `order` on a model that has no database table crashes with

```
ActiveRecord::StatementInvalid: Could not find table 'test_models'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/sqlite3_adapter.rb:397:in `table_structure'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:113:in `columns'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/schema_cache.rb:69:in `columns'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/schema_cache.rb:75:in `columns_hash'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/model_schema.rb:466:in `load_schema!'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/attributes.rb:234:in `load_schema!'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/model_schema.rb:459:in `block in load_schema'
    /home/niki/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/model_schema.rb:456:in `load_schema'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/model_schema.rb:336:in `columns_hash'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/relation/query_methods.rb:1072:in `arel_column'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/relation/query_methods.rb:1175:in `block (2 levels) in preprocess_order_args'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/relation/query_methods.rb:1169:in `each'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/relation/query_methods.rb:1169:in `map'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/relation/query_methods.rb:1169:in `block in preprocess_order_args'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/relation/query_methods.rb:1161:in `map!'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/relation/query_methods.rb:1161:in `preprocess_order_args'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/relation/query_methods.rb:300:in `order!'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/relation/query_methods.rb:295:in `order'
    /home/niki/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/querying.rb:12:in `order'
    repr.rb:26:in `test_association_stuff'
```

I believe the issues appears after the commit https://github.com/rails/rails/commit/311f00116738df175c12cb36bebe79587f88e00b#diff-bf6dd6226db3aab589916f09236881c7R1170 and the changes on line 1170.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.5

**Comment by simi** [comment]
:information_source: This problem is reproducible on latest master, anyway I think this use-case (models not backed by database) is not supported. As a bandaid you can use alternative approach which doesn't need to fetch schema from DB. Passing arel attribute directly to sort will do that.

```ruby
TestModel.order(TestModel.arel_table[:published_at].desc).to_sql
```
