### ISSUE TITLE
Multiple databases and migrations using models problem 

### ISSUE THREAD

**Issue by tomgi** [rails/rails#37748]
### Description
- Given multiple databases are configured according to https://guides.rubyonrails.org/active_record_multiple_databases.html#setting-up-your-application, i.e.
    - a primary and a replica databases are defined in database.yml
    - connections to both databases are established in `ApplicationRecord` using `connects_to database: { writing: :primary, primary_replica: :primary }`

- When a migration is using a model class inheriting from `ApplicationRecord`
- Then executing such migration will raise `ActiveRecord::StatementInvalid: PG::ConnectionBad: connection is closed`

### Steps to reproduce

- clone https://github.com/tomgi/rails-multi-db-migration-problem
- run the following commands to install gems and create the database
```bash
docker-compose build
docker-compose run --rm bundle install
docker-compose run --rm app rails db:create
```
- migrate the database with
```bash
docker-compose run --rm app rails db:migrate
```

### Expected behavior

`rails db:migrate` executes all migrations and doesn't raise any errors

### Actual behavior

Executing the migration raises the following error
```
rails aborted!
ActiveRecord::StatementInvalid: PG::ConnectionBad: connection is closed
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `async_exec'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `block (2 levels) in query'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `block in query'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:718:in `block (2 levels) in log'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:717:in `block in log'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:708:in `log'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `query'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:98:in `query_value'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:383:in `release_advisory_lock'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1384:in `with_advisory_lock'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1229:in `migrate'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1061:in `up'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1036:in `migrate'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:85:in `block (3 levels) in <main>'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:83:in `each'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:83:in `block (2 levels) in <main>'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/bundle/vendor/gems/railties-6.0.1/lib/rails/command.rb:48:in `invoke'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<main>'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
/app/bin/rails:9:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/bundle/vendor/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
PG::ConnectionBad: connection is closed
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `async_exec'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `block (2 levels) in query'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `block in query'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:718:in `block (2 levels) in log'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:717:in `block in log'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:708:in `log'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `query'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:98:in `query_value'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:383:in `release_advisory_lock'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1384:in `with_advisory_lock'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1229:in `migrate'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1061:in `up'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1036:in `migrate'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:85:in `block (3 levels) in <main>'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:83:in `each'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:83:in `block (2 levels) in <main>'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/bundle/vendor/gems/railties-6.0.1/lib/rails/command.rb:48:in `invoke'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<main>'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
/app/bin/rails:9:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/bundle/vendor/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

### System configuration
**Rails version**:
6.0.1

**Ruby version**:
2.6.3

**Comment by tomgi** [comment]
I've done some investigation and I think the problem is caused by the following sequence of events:
- `ActiveRecord::Base` establishes a connection to the primary database.
- PG lock is acuired using that `ActiveRecord::Base` connection before executing migrations in https://github.com/rails/rails/blob/v6.0.1/activerecord/lib/active_record/migration.rb#L1379
- Migration code gets loaded, which loads `ApplicationRecord` and executes `connects_to database: { writing: :primary, primary_replica: :primary }`. That closes and replaces previously establishes connection for the `writing` role.
- Migration executes succesfully using the connection establishes in `ApplicationRecord`.
- PG lock is to be released in https://github.com/rails/rails/blob/v6.0.1/activerecord/lib/active_record/migration.rb#L1384, but the previously stored, already closed connection is being used for that.
- `PG::ConnectionBad: connection is closed` is being raised.

**Comment by eileencodes** [comment]
Thanks for the report @tomgi. Your connections aren't setup correctly

This:

```ruby
connects_to database: { writing: :primary, primary_replica: :primary }
```

Needs to look like:

```ruby
connects_to database: { writing: :primary, reading: :primary_replica }
```

**Comment by tomgi** [comment]
Hi @eileencodes, thanks for your fast response!

The `reading` role is not actually even used anywhere - I didn't enable automatic connection switching and I don't use it manually anywhere. 

I applied your suggestion and the problem is still there.

I think it might be happening because the already existing connection for the `writing` role is getting replaced when `connects_to database: { writing: :primary}` is executed. 

In [this](https://github.com/rails/rails/blob/v6.0.1/activerecord/lib/active_record/migration.rb#L1384) line
`connection` is closed and `Base.connection` is already a different one (and open). 

Thanks

**Comment by austinbv** [comment]
@tomgi did you find a resolution to this issue?

**Comment by eileencodes** [comment]
@austinbv I fixed it in https://github.com/rails/rails/pull/38235, it will be in the next release.

**Comment by austinbv** [comment]
@eileencodes thanks! Do you have an eta on when the next release is?

**Comment by nburns** [comment]
For anyone else with this problem, after reading the commit message, I was able to remove migrations from my app that referenced models (ex `User`, `Post`) which is the 2nd condition required to trigger the bug. @austinbv

**Comment by januszm** [comment]
BTW. Are migrations also started for a database with the `replica: true` flag or are these databases (role: reading) skipped when `rails db:migrate` runs?
