### ISSUE TITLE
ActionText: _layout.html.erb rendered multiple times when saving

### ISSUE THREAD

**Issue by vitobotta** [rails/rails#37818]
### Steps to reproduce
Have a model e.g. RichText 

```ruby
class RichText < Block
  has_rich_text :body
end
```

In the console, update the text on an instance of the model:

```ruby
irb(main):006:0> x.update body: "test"
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 2.1ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.5ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.5ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 1.2ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 1.5ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 1.1ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.5ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.9ms | Allocations: 241)
  TRANSACTION (42.0ms)  BEGIN
  ActionText::RichText Update (40.6ms)  UPDATE `action_text_rich_texts` SET `action_text_rich_texts`.`body` = 'test', `action_text_rich_texts`.`updated_at` = '2019-11-27 18:01:46.517465' WHERE `action_text_rich_texts`.`id` = 2
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.9ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 1.6ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.7ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.9ms | Allocations: 241)
  RichText Update (40.3ms)  UPDATE `blocks` SET `blocks`.`updated_at` = '2019-11-27 18:01:46.615371' WHERE `blocks`.`id` = 5
  TRANSACTION (55.6ms)  COMMIT
=> true
```

### Expected behavior
I would expect it to just do an UPDATE query.

### Actual behavior
As you can see above, when saving ActionText renders `_layout.html.erb` multiple times even if I am just saving.

### System configuration
**Rails version**:
Tried with both 6.0.1 and master

**Ruby version**:
2.6.5

**Additional info**:
ActionText::Content#to_s is what renders the HTML. I guess this is called somehow when saving but I'm not sure.

**Comment by vitobotta** [comment]
It seems that the problem doesn't occur when saving the rich text the first time. But it does on subsequent saves:

```ruby
irb(main):001:0> r = RichText.find 5
  RichText Load (40.3ms)  SELECT `blocks`.* FROM `blocks` WHERE `blocks`.`type` = 'RichText' AND `blocks`.`id` = 5 LIMIT 1
=> #<RichText id: 5, version_id: 7, position: 1, created_at: "2019-11-26 23:09:42", updated_at: "2019-11-27 18:01:46", content: "<div><figure data-trix-attachment=\"{&quot;contentT...", type: "RichText">
irb(main):002:0> r.update body: "vito"
  TRANSACTION (39.8ms)  BEGIN
  ActionText::RichText Load (40.1ms)  SELECT `action_text_rich_texts`.* FROM `action_text_rich_texts` WHERE `action_text_rich_texts`.`record_id` = 5 AND `action_text_rich_texts`.`record_type` = 'Block' AND `action_text_rich_texts`.`name` = 'body' LIMIT 1
  ActionText::RichText Create (88.0ms)  INSERT INTO `action_text_rich_texts` (`name`, `body`, `record_type`, `record_id`, `created_at`, `updated_at`) VALUES ('body', 'vito', 'Block', 5, '2019-11-27 18:39:16.696433', '2019-11-27 18:39:16.696433')
  ActiveStorage::Attachment Load (39.1ms)  SELECT `active_storage_attachments`.* FROM `active_storage_attachments` WHERE `active_storage_attachments`.`record_id` = 5 AND `active_storage_attachments`.`record_type` = 'ActionText::RichText' AND `active_storage_attachments`.`name` = 'embeds'
  RichText Update (40.6ms)  UPDATE `blocks` SET `blocks`.`updated_at` = '2019-11-27 18:39:16.785965' WHERE `blocks`.`id` = 5
  TRANSACTION (54.2ms)  COMMIT
=> true


irb(main):003:0> r.update body: "vitox"
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.9ms | Allocations: 473)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.5ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.4ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.3ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.3ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.9ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.4ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.6ms | Allocations: 241)
  TRANSACTION (40.4ms)  BEGIN
  ActionText::RichText Update (52.1ms)  UPDATE `action_text_rich_texts` SET `action_text_rich_texts`.`body` = 'vitox', `action_text_rich_texts`.`updated_at` = '2019-11-27 18:39:19.093331' WHERE `action_text_rich_texts`.`id` = 5
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.5ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.6ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.5ms | Allocations: 241)
  Rendered /usr/local/bundle/bundler/gems/rails-be2473b2ef51/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 0.4ms | Allocations: 241)
  RichText Update (65.0ms)  UPDATE `blocks` SET `blocks`.`updated_at` = '2019-11-27 18:39:19.197111' WHERE `blocks`.`id` = 5
  TRANSACTION (69.2ms)  COMMIT
=> true
```

**Comment by bentremblay** [comment]
This seems to be related to `ActionText::RichText` being a relation with `autosave: true`.

In the definition of `has_rich_text` in `rails/actiontext/lib/action_text/attribute.rb `:
```ruby
has_one :"rich_text_#{name}", -> { where(name: name) },
          class_name: "ActionText::RichText", as: :record, inverse_of: :record, autosave: true, dependent: :destroy
```

When saving the parent record, `autosave: true` triggers the `changed?` method to be called on the rich text attribute to check if it has changed and should be saved.

The layout then gets rendered in the equality check of `ActionText::Content`

```
/ruby-2.6.3@rails6/gems/actiontext-6.0.2.1/lib/action_text/content.rb:91:in `to_rendered_html_with_layout'
/ruby-2.6.3@rails6/gems/actiontext-6.0.2.1/lib/action_text/content.rb:95:in `to_s'
/ruby-2.6.3@rails6/gems/actiontext-6.0.2.1/lib/action_text/content.rb:108:in `=='
/ruby-2.6.3@rails6/gems/activemodel-6.0.2.1/lib/active_model/type/value.rb:65:in `!='
/ruby-2.6.3@rails6/gems/activemodel-6.0.2.1/lib/active_model/type/value.rb:65:in `changed?'
```

The `==` method in `ActionText::Content` checks for equality using the `to_s` function, which then renders the layout through `to_rendered_html_with_layout`:

```
def to_s
  to_rendered_html_with_layout
end

def ==(other)
  if other.is_a?(self.class)
    to_s == other.to_s
  end
end
```

Equality check shouldn't rely on a function that depends on layout rendering.

**Comment by issaysa** [comment]
I had the same problem.
Thank you very much to both of you.

I just changed the `ActionText::Content` `==` method like below, and now it works just fine.
```
def ==(other)
  if other.is_a?(self.class)
    to_html == other.to_html
  end
end
```
