### ISSUE TITLE
ActiveStorage 6.0.0 raises FrozenError on save after attach and detach

### ISSUE THREAD

**Issue by r7kamura** [rails/rails#37836]
### Steps to reproduce

Call `save` after `attach` and `detach`.

```rb
user = User.new
user.avatar.attach(
  content_type: 'text/plain',
  filename: 'avatar.txt',
  io: StringIO.new,
)
user.avatar.detach
user.save!
```

Here is an example Rails app to reproduce this error.

- https://github.com/r7kamura/active_storage_test
- https://github.com/r7kamura/active_storage_test/blob/master/test/models/user_test.rb

Clone the repo and run the following commands:

```
bundle install
bundle exec rails db:setup
bundle exec rake test
```

or run this script to do the same thing.

- https://gist.github.com/r7kamura/7ee56572693fcd07a17219cd0ee6a4ca

### Expected behavior

No error should be raised.

### Actual behavior

FrozenError is raised from `save`.

> FrozenError: can't modify frozen Hash

<details>

```
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activemodel-6.0.1/lib/active_model/attribute_set.rb:49:in `write_from_user'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/attribute_methods/write.rb:44:in `_write_attribute'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/attribute_methods/write.rb:37:in `write_attribute'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/attribute_methods.rb:337:in `[]='
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/associations/association.rb:263:in `block in set_owner_attributes'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/associations/association.rb:263:in `each'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/associations/association.rb:263:in `set_owner_attributes'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/associations/has_one_association.rb:55:in `block in replace'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/associations/has_one_association.rb:103:in `block in transaction_if'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:279:in `transaction'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/transactions.rb:212:in `transaction'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/associations/has_one_association.rb:103:in `transaction_if'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/associations/has_one_association.rb:51:in `replace'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/associations/singular_association.rb:17:in `writer'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/associations/builder/association.rb:108:in `avatar_attachment='
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activestorage-6.0.1/lib/active_storage/attached/changes/create_one.rb:32:in `public_send'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activestorage-6.0.1/lib/active_storage/attached/changes/create_one.rb:32:in `save'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activestorage-6.0.1/lib/active_storage/attached/model.rb:54:in `block in has_one_attached'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:429:in `instance_exec'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:429:in `block in make_lambda'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:239:in `block in halting_and_conditional'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:518:in `block in invoke_after'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:518:in `each'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:518:in `invoke_after'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/callbacks.rb:328:in `create_or_update'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/timestamp.rb:129:in `create_or_update'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/persistence.rb:503:in `save!'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/validations.rb:53:in `save!'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/transactions.rb:319:in `block in save!'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/transactions.rb:212:in `transaction'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/transactions.rb:319:in `save!'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-6.0.1/lib/active_record/suppressor.rb:48:in `save!'
/Users/r7kamura/src/github.com/r7kamura/active_storage_test/test/models/user_test.rb:13:in `block in <class:UserTest>'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest/test.rb:98:in `block (3 levels) in run'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest/test.rb:195:in `capture_exceptions'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest/test.rb:95:in `block (2 levels) in run'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest.rb:270:in `time_it'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest/test.rb:94:in `block in run'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest.rb:365:in `on_signal'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest/test.rb:211:in `with_info_handler'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest/test.rb:93:in `run'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest.rb:1029:in `run_one_method'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/testing/parallelization.rb:89:in `block (3 levels) in start'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest.rb:365:in `on_signal'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest.rb:352:in `with_info_handler'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/testing/parallelization.rb:88:in `block (2 levels) in start'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/testing/parallelization.rb:75:in `fork'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/testing/parallelization.rb:75:in `block in start'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/testing/parallelization.rb:74:in `times'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/testing/parallelization.rb:74:in `each'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/testing/parallelization.rb:74:in `map'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-6.0.1/lib/active_support/testing/parallelization.rb:74:in `start'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest.rb:138:in `run'
/Users/r7kamura/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minitest-5.13.0/lib/minitest.rb:68:in `block in autorun'
```

</details>

### System configuration

**Rails version**: 6.0.0 and 6.0.1

**Ruby version**: 2.5.1 and 2.6.3

Note: Rails 5.2.3 doesn't raise FrozenError.

### Note

https://github.com/rails/rails/issues/37069 is similar to this issue.

**Comment by Auralcat** [comment]
@r7kamura I ran the script you provided against Ruby 2.5.3 and Ruby 2.6.1, and confirmed the behavior described in this issue for the versions provided. This error is still present in the `6-0-stable` branch, but for the current master (c63cfc8722292ec39def505861fbc20bd9774f4c) I get this error when running the script https://gist.github.com/r7kamura/7ee56572693fcd07a17219cd0ee6a4ca :

> Error:
> MyTest#test_attach_and_detach:
> RuntimeError: Couldn't find Active Storage configuration in /private/tmp/config/storage.yml

Is there any more info I can provide to help solve this bug? :)

**Comment by r7kamura** [comment]
@Auralcat Thanks for your reply!
I encountered this problem on migration from activestorage 5.2.3 to 6.0.0 in our Rails app. This is just my guess, but I think `#attachment_changes` is not correctly cleared at `#detach`, then something wrong happens at `after_save { attachment_changes[name.to_s]&.save }`.  https://github.com/rails/rails/blob/v6.0.0/activestorage/lib/active_storage/attached/model.rb#L54.

**Comment by Auralcat** [comment]
I had some trouble to look at that in these 2 weeks, I'm going to do it in the next 7 days, sorry :S

**Comment by mattbaumann1** [comment]
This still seems to be a problem. What was the fix?
