### ISSUE TITLE
Activestorage GCP fails with cryptic messages and fails with different messages when using runner and console

### ISSUE THREAD

**Issue by timuckun** [rails/rails#37845]
### Steps to reproduce
Create a new rails app, following the instructions in the rails manual for activestorage.

Storage.yml looks like this

```yaml
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
local:
  service: Disk
  root: <% Rails.root.join("storage") %>
google:
  service: GCS
  project: <% ENV['GOOGLE_PROJECT_ID'] %>
  credentials: <% Base64.decode64(ENV['GOOGLE_APPLICATION_CREDENTIALS']).as_json %>
  bucket: <%= ENV['GOOGLE_BUCKET_NAME'] %>
google_dev:
  service: GCS
  project: tim-auction-258712
  bucket: auction_dev
  credentials: <%= Rails.root.join("config/secrets/tim-auction-gs.json") %>
```

Create a runner script as follows
```bash
#! /usr/bin/env /Users/timuckun/Dropbox/source/dropit/tim_experiments/rails_gcs_test/bin/rails runner

filename=File.join(Rails.root, "tmp", "test.pdf")
if ! File.exists? filename
  raise "#{filename} does not exist"
end

todo = Todo.first
puts todo.id
todo.picture.attach(io: File.open(filename), filename: "test.pdf")
```
I get the following error message

```bash
Running via Spring preloader in process 76515
1
Traceback (most recent call last):
	94: from -e:1:in `<main>'
	93: from /Users/timuckun/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	92: from /Users/timuckun/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	91: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	90: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	89: from /Users/timuckun/Dropbox/source/dropit/tim_experiments/rails_gcs_test/bin/rails:9:in `<main>'
	88: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/zeitwerk-2.2.1/lib/zeitwerk/kernel.rb:23:in `require'
	87: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	86: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	85: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	84: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	83: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	82: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<main>'
	81: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/railties-6.0.1/lib/rails/command.rb:46:in `invoke'
	80: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/railties-6.0.1/lib/rails/command/base.rb:65:in `perform'
	79: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	78: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	77: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	76: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/railties-6.0.1/lib/rails/commands/runner/runner_command.rb:42:in `perform'
	75: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	74: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	73: from /Users/timuckun/Dropbox/source/dropit/tim_experiments/rails_gcs_test/test_storage.sh:10:in `<main>'
	72: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.1/lib/active_storage/attached/one.rb:32:in `attach'
	71: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/persistence.rb:619:in `update'
	70: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
	69: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/transactions.rb:212:in `transaction'
	68: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
	67: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
	66: from /Users/timuckun/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
	65: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
	64: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
	63: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
	62: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/persistence.rb:621:in `block in update'
	61: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/suppressor.rb:44:in `save'
	60: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/transactions.rb:315:in `save'
	59: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
	58: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/transactions.rb:212:in `transaction'
	57: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:279:in `transaction'
	56: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
	55: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/transactions.rb:315:in `block in save'
	54: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/validations.rb:47:in `save'
	53: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/persistence.rb:470:in `save'
	52: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/timestamp.rb:129:in `create_or_update'
	51: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/callbacks.rb:328:in `create_or_update'
	50: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
	49: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
	48: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:518:in `invoke_after'
	47: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:518:in `each'
	46: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:518:in `block in invoke_after'
	45: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:239:in `block in halting_and_conditional'
	44: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:429:in `block in make_lambda'
	43: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:429:in `instance_exec'
	42: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.1/lib/active_storage/attached/model.rb:54:in `block in has_one_attached'
	41: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.1/lib/active_storage/attached/changes/create_one.rb:32:in `save'
	40: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.1/lib/active_storage/attached/changes/create_one.rb:15:in `attachment'
	39: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.1/lib/active_storage/attached/changes/create_one.rb:38:in `find_or_build_attachment'
	38: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.1/lib/active_storage/attached/changes/create_one.rb:42:in `find_attachment'
	37: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.1/lib/active_storage/attached/changes/create_one.rb:42:in `public_send'
	36: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/associations/builder/association.rb:100:in `picture_blob'
	35: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/associations/singular_association.rb:9:in `reader'
	34: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/associations/association.rb:66:in `reload'
	33: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/associations/association.rb:161:in `load_target'
	32: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/associations/association.rb:244:in `find_target?'
	31: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/associations/association.rb:137:in `klass'
	30: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/reflection.rb:769:in `klass'
	29: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/reflection.rb:422:in `compute_class'
	28: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/inheritance.rb:198:in `compute_type'
	27: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/inheritance.rb:198:in `each'
	26: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/inheritance.rb:199:in `block in compute_type'
	25: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/dependencies/zeitwerk_integration.rb:23:in `safe_constantize'
	24: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/inflector/methods.rb:325:in `safe_constantize'
	23: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/inflector/methods.rb:280:in `constantize'
	22: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/inflector/methods.rb:280:in `inject'
	21: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/inflector/methods.rb:280:in `each'
	20: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/inflector/methods.rb:284:in `block in constantize'
	19: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/inflector/methods.rb:284:in `const_get'
	18: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/zeitwerk-2.2.1/lib/zeitwerk/kernel.rb:16:in `require'
	17: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	16: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	15: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	14: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	13: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	12: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.1/app/models/active_storage/blob.rb:289:in `<main>'
	11: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	10: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
	 9: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	 8: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	 7: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	 6: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/lazy_load_hooks.rb:72:in `block in execute_hook'
	 5: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.1/lib/active_support/lazy_load_hooks.rb:72:in `class_eval'
	 4: from /Users/timuckun/.rvm/gems/ruby-2.6.3/gems/activestorage-6.0.1/lib/active_storage/engine.rb:111:in `block (2 levels) in <class:Engine>'
	 3: from /Users/timuckun/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/erb.rb:901:in `result'
	 2: from /Users/timuckun/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/erb.rb:901:in `eval'
	 1: from (erb):10:in `<main>'
/Users/timuckun/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/base64.rb:59:in `decode64': undefined method `unpack1' for nil:NilClass (NoMethodError)
```

Next I try it in the rails console

```ruby
>> >> Todo.first
Todo.first
=> #<Todo id: 1, task: "Item with picture", created_at: "2019-11-28 21:47:58", updated_at: "2019-12-01 22:03:37">
>>   Todo Load (0.1ms)  SELECT "todos".* FROM "todos" ORDER BY "todos"."id" ASC LIMIT ?  [["LIMIT", 1]]

>> Todo.first.picture.attach(io: File.open(File.join(Rails.root, 'tmp/test.pdf')), filename: "test.pdf")

Todo.first.picture.attach(io: File.open(File.join(Rails.root, 'tmp/test.pdf')), filename: "test.pdf")
  Todo Load (0.1ms)  SELECT "todos".* FROM "todos" ORDER BY "todos"."id" ASC LIMIT ?  [["LIMIT", 1]]
   (0.0ms)  begin transaction
  ActiveStorage::Blob Load (0.1ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" INNER JOIN "active_storage_attachments" ON "active_storage_blobs"."id" = "active_storage_attachments"."blob_id" WHERE "active_storage_attachments"."record_id" = ? AND "active_storage_attachments"."record_type" = ? AND "active_storage_attachments"."name" = ? LIMIT ?  [["record_id", 1], ["record_type", "Todo"], ["name", "picture"], ["LIMIT", 1]]
  ActiveStorage::Attachment Load (0.1ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = ? AND "active_storage_attachments"."record_type" = ? AND "active_storage_attachments"."name" = ? LIMIT ?  [["record_id", 1], ["record_type", "Todo"], ["name", "picture"], ["LIMIT", 1]]
  ActiveStorage::Attachment Destroy (0.3ms)  DELETE FROM "active_storage_attachments" WHERE "active_storage_attachments"."id" = ?  [["id", 3]]
  ActiveStorage::Blob Create (0.2ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "metadata", "byte_size", "checksum", "created_at") VALUES (?, ?, ?, ?, ?, ?, ?)  [["key", "41jj2xeqp9h3v0s7ag8xk67jx71n"], ["filename", "test.pdf"], ["content_type", "application/pdf"], ["metadata", "{\"identified\":true}"], ["byte_size", 78367], ["checksum", "+55ZmPhK692X16MhJ0BhYw=="], ["created_at", "2019-12-01 22:19:32.792040"]]
  ActiveStorage::Attachment Create (0.1ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES (?, ?, ?, ?, ?)  [["name", "picture"], ["record_type", "Todo"], ["record_id", 1], ["blob_id", 4], ["created_at", "2019-12-01 22:19:32.792936"]]
  Todo Update (0.1ms)  UPDATE "todos" SET "updated_at" = ? WHERE "todos"."id" = ?  [["updated_at", "2019-12-01 22:19:32.793390"], ["id", 1]]
   (0.7ms)  commit transaction
NoMethodError (undefined method `upload' for nil:NilClass)
	from (irb):6
>> 

```

I can't debug the problem with these error messages.

**Comment by dp6ai** [comment]
@timuckun Did you ever get to the bottom of the `NoMethodError (undefined method `upload' for nil:NilClass)` error?

I'm getting the same error, I've tracked it down to [here](https://github.com/rails/rails/blob/6-0-stable/activestorage/lib/active_storage/attached/one.rb#L34)

But i'm not sure how to proceed
