### ISSUE TITLE
6.0.2.rc1 regression to Engine routes expressed with symbols

### ISSUE THREAD

**Issue by jrochkind** [rails/rails#37861]
@rafaelfranca

Create an engine (eg `rails plugin new testengine --mountable`), and in it's `./config/routes.rb`, include a route such as:

```
Testengine::Engine.routes.draw do
  get "/foo", controller: :widget, action: :foo
end
```

Include this engine as a dependency of a Rails app. In the Rails app's own `./config/routes.rb` do a standard:

```
mount Testengine::Engine => '/testengine
```

Under Rails 6.0.1, all works as expected. 

Under Rails 6.0.2.rc1, when trying to boot the app (including under development mode, with a simple `rails server`), you get an exception:

    actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:353:in `add_controller_module': undefined method `start_with?' for :widget:Symbol (NoMethodError)

(Running under ruby 2.5.3, also reproducible under 2.6.5; I was reminded by this error that ruby 2.7 adds a `start_with?` for `Symbol`, but I think this is just a coincidence, I don't believe it's related to this bug, and at any event Rails 6.0.2 is obviously not intended to require ruby 2.7!)

<details><summary>Full stack trace</summary>

```
	98: from bin/rails:3:in `<main>'
	97: from bin/rails:3:in `load'
	96: from /Users/jrochkind/code/rails601app/bin/spring:15:in `<top (required)>'
	95: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	94: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	93: from /Users/jrochkind/.gem/ruby/2.5.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	92: from /Users/jrochkind/.gem/ruby/2.5.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	91: from /Users/jrochkind/.gem/ruby/2.5.3/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	90: from /Users/jrochkind/.gem/ruby/2.5.3/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	89: from /Users/jrochkind/.gem/ruby/2.5.3/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	88: from /Users/jrochkind/.gem/ruby/2.5.3/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	87: from /Users/jrochkind/.gem/ruby/2.5.3/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	86: from /Users/jrochkind/code/rails601app/bin/rails:9:in `<top (required)>'
	85: from /Users/jrochkind/.gem/ruby/2.5.3/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:325:in `require'
	84: from /Users/jrochkind/.gem/ruby/2.5.3/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:291:in `load_dependency'
	83: from /Users/jrochkind/.gem/ruby/2.5.3/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:325:in `block in require'
	82: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	81: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	80: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	79: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	78: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	77: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/commands.rb:18:in `<top (required)>'
	76: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/command.rb:46:in `invoke'
	75: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/command/base.rb:69:in `perform'
	74: from /Users/jrochkind/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	73: from /Users/jrochkind/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	72: from /Users/jrochkind/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	71: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/commands/server/server_command.rb:138:in `perform'
	70: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/commands/server/server_command.rb:138:in `tap'
	69: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	68: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/commands/server/server_command.rb:37:in `start'
	67: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	66: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
	65: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
	64: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	63: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
	62: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
	61: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
	60: from config.ru:in `<main>'
	59: from config.ru:in `new'
	58: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
	57: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
	56: from config.ru:3:in `block in <main>'
	55: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
	54: from /Users/jrochkind/.gem/ruby/2.5.3/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:325:in `require'
	53: from /Users/jrochkind/.gem/ruby/2.5.3/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:291:in `load_dependency'
	52: from /Users/jrochkind/.gem/ruby/2.5.3/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:325:in `block in require'
	51: from /Users/jrochkind/.gem/ruby/2.5.3/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
	50: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	49: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	48: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	47: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	46: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	45: from /Users/jrochkind/code/rails601app/config/environment.rb:5:in `<top (required)>'
	44: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/application.rb:363:in `initialize!'
	43: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/initializable.rb:60:in `run_initializers'
	42: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	41: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	40: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	39: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
	38: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
	37: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	36: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	35: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	34: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	33: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/initializable.rb:61:in `block in run_initializers'
	32: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/initializable.rb:32:in `run'
	31: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/initializable.rb:32:in `instance_exec'
	30: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/application/finisher.rb:184:in `block in <module:Finisher>'
	29: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:10:in `execute'
	28: from /Users/jrochkind/.gem/ruby/2.5.3/gems/activesupport-6.0.2.rc1/lib/active_support/file_update_checker.rb:83:in `execute'
	27: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:30:in `block in updater'
	26: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:20:in `reload!'
	25: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:41:in `load_paths'
	24: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:41:in `each'
	23: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:41:in `block in load_paths'
	22: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	21: from /Users/jrochkind/.gem/ruby/2.5.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	20: from /Users/jrochkind/code/rails601app/testengine/config/routes.rb:1:in `<top (required)>'
	19: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/route_set.rb:411:in `draw'
	18: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/route_set.rb:427:in `eval_block'
	17: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:648:in `with_default_scope'
	16: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:887:in `scope'
	15: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:649:in `block in with_default_scope'
	14: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:649:in `instance_exec'
	13: from /Users/jrochkind/code/rails601app/testengine/config/routes.rb:2:in `block in <top (required)>'
	12: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:712:in `get'
	11: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:751:in `map_method'
	10: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1633:in `match'
	 9: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1886:in `map_match'
	 8: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1886:in `each'
	 7: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1892:in `block in map_match'
	 6: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1928:in `decomposed_match'
	 5: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1956:in `add_route'
	 4: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:83:in `build'
	 3: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:83:in `new'
	 2: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:131:in `initialize'
	 1: from /Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:260:in `normalize_options!'
/Users/jrochkind/.gem/ruby/2.5.3/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:353:in `add_controller_module': undefined method `start_with?' for :widget:Symbol (NoMethodError)
```

</details>

**Comment by eugeneius** [comment]
Thanks for the report, but this is already tracked in https://github.com/rails/rails/issues/37857.
