### ISSUE TITLE
Malformed host header causes server errors on redirect

### ISSUE THREAD

**Issue by piloos** [rails/rails#37956]
### Steps to reproduce

* Create a minimal Rails application with one endpoint (endpoint R) redirecting to another endpoint.
* Call endpoint R with a malformed `Host` header (eg. `www.example.com:80:80`).  This will cause the server to generate an internal server error (return code 500).

The issue seems to be caused by `ActionDispatch` which tries to create the redirect URI based on the incorrect host header from the request.

Executable test case

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "action_controller/railtie"
require "minitest/autorun"
require "rack/test"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "www.example.com" << "www.example.com:80"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger = config.logger

  routes.draw do
    get '/home', to: 'test#home'
    get '/home2', to: redirect('/home')
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def home
    render plain: 'Home sweet home'
  end
end


class BugTest < ActionDispatch::IntegrationTest

  def test_home_endpoint_works
    get '/home'
    assert response.ok?
    assert "Home sweet home", response.body
  end

  def test_redirection_works
    get '/home2'
    assert response.redirect?

    get response.location
    assert response.ok?
    assert "Home sweet home", response.body
  end

  def test_redirection_does_not_error_on_malformed_host_header
    get '/home2', headers: {'Host': 'www.example.com:80:80'}
    assert_not_equal 500, response.status, "Malformed Host header caused a server error"
  end

  private

  def app
    Rails.application
  end

end
```

### Expected behavior
The rails server should not generate internal server errors on malformed requests. While these requests are not correct by themselves, a malicious user could use this to deliberately generate errors on the server.
Alternatively, there should be a way to catch these errors.

### Actual behavior
The rails server generates internal server errors on malformed requests.

### System configuration
**Rails version**: 6.1.0.alpha from https://github.com/rails/rails.git (at master@58df9a4)

**Ruby version**: 2.5.5

**Comment by st0012** [comment]
Can confirm this. And the error is 

```
URI::InvalidComponentError (bad component(expected host component): www.example.com:80):

/Users/st0012/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/generic.rb:592:in `check_host'
/Users/st0012/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/generic.rb:631:in `host='
```

I think this issue indicates 2 problems in the `actionpack`.

1. The `ActionDispatch::HostAuthorization` middleware didn't work as expected.
2. We don't have any host validation that can catch such host inside `actionpack`.

IMO, the second issue needs to be addressed first, since the `hosts` config can be optional. The simplest way is to capture `URI::InvalidComponentError` like

```
diff --git a/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb b/actionpack/lib/action_dispatch/middleware/exception_wrappe
r.rb
index e4a2a51c57..e3d2b476a7 100644
--- a/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb
+++ b/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb
@@ -20,7 +20,8 @@ class ExceptionWrapper
       "ActionController::BadRequest"                 => :bad_request,
       "ActionController::ParameterMissing"           => :bad_request,
       "Rack::QueryParser::ParameterTypeError"        => :bad_request,
-      "Rack::QueryParser::InvalidParameterError"     => :bad_request
+      "Rack::QueryParser::InvalidParameterError"     => :bad_request,
+      "URI::InvalidComponentError"                   => :bad_request
     )
```

It's simple and effective. But the downside is that it might swallow some invalid URI errors that are caused by bugs inside the actionpack.

**Comment by piloos** [comment]
Yes, this issue is still reproducible on `master` (`master@520d774`)

**Comment by piloos** [comment]
Yes, this issue is still reproducible on `master` (commit `60b43ab`)

**Comment by jcoyne** [comment]
This issue is still present in Rails 8.0.2
