### ISSUE TITLE
Constants or files randomly not loaded when using multiple puma workers in local development environment

### ISSUE THREAD

**Issue by silva96** [rails/rails#38025]
### Steps to reproduce
In my machine, having namespaced (in subfolder) files, like concerns, and setting puma workers for more than one, randomly makes the app raise `ActionController::RoutingError (uninitialized constant TripsControllerConcerns)`

Example: 

file under `app/controllers/concerns/trips_controller_concerns/trips_includes.rb`

```ruby
# frozen_string_literal: true

module TripsControllerConcerns
  module TripIncludes
    extend ActiveSupport::Concern
    def my_method
      # . . . some logic
    end
  end
end
```
`app/controllers/trips_controller.rb`
```ruby
# frozen_string_literal: true

class TripsController < ApplicationController
  include TripsControllerConcerns::TripIncludes
  # . . . some logic
end
```

After some testing I also figured out this doesn't happen only to namespaced concerns or files, it also happens to other files like this:

```
Started GET "/websocket/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzY3NjY2NzMsInN1YiI6M30.5VWMYv1nWbbaZlIjw6syYWRzNkuopZyS5pcf-AeUrRk" [WebSocket] for ::1 at 2019-12-18 12:16:49 -0300
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Could not execute command from ({"command"=>"subscribe", "identifier"=>"{\"channel\":\"GeneralInfoChannel\"}"}) [NameError - uninitialized constant ApplicationCable]: /Users/benja/.rvm/gems/ruby-2.6.5@ventanilla_system/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant' | /Users/benja/.rvm/gems/ruby-2.6.5@ventanilla_system/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry' | /Users/benja/.rvm/gems/ruby-2.6.5@ventanilla_system/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant' | /Users/benja/dev/ventas/app/channels/general_info_channel.rb:3:in `<main>' | /Users/benja/.rvm/gems/ruby-2.6.5@ventanilla_system/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
Could not execute command from ({"command"=>"subscribe", "identifier"=>"{\"channel\":\"BackgroundJobsChannel\"}"}) [NameError - uninitialized constant ApplicationCable]: /Users/benja/.rvm/gems/ruby-2.6.5@ventanilla_system/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant' | /Users/benja/.rvm/gems/ruby-2.6.5@ventanilla_system/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry' | /Users/benja/.rvm/gems/ruby-2.6.5@ventanilla_system/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant' | /Users/benja/dev/ventas/app/channels/background_jobs_channel.rb:3:in `<main>' | /Users/benja/.rvm/gems/ruby-2.6.5@ventanilla_system/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
Could not execute command from ({"command"=>"subscribe", "identifier"=>"{\"channel\":\"NotificationsChannel\"}"}) [NameError - uninitialized constant ApplicationCable]: /Users/benja/.rvm/gems/ruby-2.6.5@ventanilla_system/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant' | /Users/benja/.rvm/gems/ruby-2.6.5@ventanilla_system/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry' | /Users/benja/.rvm/gems/ruby-2.6.5@ventanilla_system/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant' | /Users/benja/dev/ventas/app/channels/notifications_channel.rb:3:in `<main>' | /Users/benja/.rvm/gems/ruby-2.6.5@ventanilla_system/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
```

### Expected behavior
Should not raise `ActionController::RoutingError (uninitialized constant TripsControllerConcerns):`

### Actual behavior
randomly raises `ActionController::RoutingError (uninitialized constant TripsControllerConcerns):`

### System configuration
**Rails version**: Rails 5.2.3

**Ruby version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

**Comment by avit** [comment]
Hi, could you please double-check your naming, I think the problem is a different file name vs. module name:

- `module TripIncludes`
- `trips_includes.rb`
