### ISSUE TITLE
StarStarMimeControllerTest#test_javascript_with_no_format_only_star_star sometime fails

### ISSUE THREAD

**Issue by yahonda** [rails/rails#38094]
StarStarMimeControllerTest#test_javascript_with_no_format_only_star_star sometime fails at Rails CI as follows.

https://buildkite.com/rails/rails/builds/65916#23a83567-6812-4dd7-b617-85c4ad712775
https://buildkite.com/rails/rails/builds/65946#2a4368fb-c7fa-4d34-a7a7-0f9378af3561
https://buildkite.com/rails/rails/builds/65943#70208757-6778-45ee-bf8a-eb3abdd9db08

I have not found how to always reproduce this error yet.

### Steps to reproduce
```
% cd actionpack
% bundle exec ruby -w -Itest test/controller/mime/accept_format_test.rb --seed 63915
```

### Expected behavior
It should pass.

### Actual behavior

It fails frequently fails like 7 of 10 attempts.

```ruby
% bundle exec ruby -w -Itest test/controller/mime/accept_format_test.rb --seed 63915
Run options: --seed 63915

# Running:

.....E

Error:
StarStarMimeControllerTest#test_javascript_with_no_format_only_star_star:
ArgumentError: Invalid formats: :iphone
    /Users/yahonda/src/github.com/yahonda/rails/actionview/lib/action_view/lookup_context.rb:287:in `formats='
    /Users/yahonda/src/github.com/yahonda/rails/actionview/lib/action_view/view_paths.rb:11:in `formats='
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/rendering.rb:29:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/callbacks.rb:98:in `run_callbacks'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/abstract_controller/callbacks.rb:41:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/rescue.rb:22:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/notifications.rb:203:in `block in instrument'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/notifications.rb:203:in `instrument'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/abstract_controller/base.rb:136:in `process'
    /Users/yahonda/src/github.com/yahonda/rails/actionview/lib/action_view/rendering.rb:39:in `process'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal.rb:190:in `dispatch'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/test_case.rb:512:in `process'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/test_case.rb:390:in `get'
    test/controller/mime/accept_format_test.rb:28:in `test_javascript_with_no_format_only_star_star'


rails test test/controller/mime/accept_format_test.rb:26



Finished in 0.228798s, 26.2240 runs/s, 39.3360 assertions/s.
6 runs, 9 assertions, 0 failures, 1 errors, 0 skips
%
```
### System configuration
**Rails version**:master branch

**Ruby version**:ruby 2.7.0dev (2019-12-25T09:47:47Z master e1e1d92277) [x86_64-darwin19]

**Comment by yahonda** [comment]
It looks like the test execution order is not fixed even if the same seed `--seed 63915` specified. I'd like to know how to fix the test order execution.

**Comment by eugeneius** [comment]
These failures looks like more fallout from https://github.com/rails/rails/pull/38026, similar to https://github.com/rails/rails/pull/38062.

Action Pack tests are run in parallel by default, which is inherently nondeterministic:

https://github.com/rails/rails/blob/3eb1f1dd105a971d3c83741b02d4da68794b1652/actionpack/test/abstract_unit.rb#L73-L75

You can disable the parallelisation by setting `N=0`:

https://github.com/rails/rails/blob/3eb1f1dd105a971d3c83741b02d4da68794b1652/actionpack/test/abstract_unit.rb#L19

**Comment by yahonda** [comment]
Thanks for the useful information as always. Setting `N=0` reproduces the failure always as follows.

* Steps to reproduce 
```ruby
% N=0 bundle exec ruby -w -Itest test/controller/mime/accept_format_test.rb  --seed 34801 -n "/^(?:MimeControllerLayoutsTest#(?:test_format_with_inherited_layouts)|StarStarMimeControllerTest#(?:test_javascript_with_no_format_only_star_star))$/" --verbose
```

* Result
```ruby
% N=0 bundle exec ruby -w -Itest test/controller/mime/accept_format_test.rb  --seed 34801 -n "/^(?:MimeControllerLayoutsTest#(?:test_format_with_inherited_layouts)|StarStarMimeControllerTest#(?:test_javascript_with_no_format_only_star_star))$/" --verbose
DEPRECATED: use MT_CPU instead of N for parallel test runs
Run options: --seed 34801 -n "/^(?:MimeControllerLayoutsTest#(?:test_format_with_inherited_layouts)|StarStarMimeControllerTest#(?:test_javascript_with_no_format_only_star_star))$/" --verbose

# Running:

MimeControllerLayoutsTest#test_format_with_inherited_layouts = 0.13 s = .
StarStarMimeControllerTest#test_javascript_with_no_format_only_star_star = 0.00 s = E


Error:
StarStarMimeControllerTest#test_javascript_with_no_format_only_star_star:
ArgumentError: Invalid formats: :iphone
    /Users/yahonda/src/github.com/yahonda/rails/actionview/lib/action_view/lookup_context.rb:287:in `formats='
    /Users/yahonda/src/github.com/yahonda/rails/actionview/lib/action_view/view_paths.rb:11:in `formats='
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/rendering.rb:29:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/callbacks.rb:98:in `run_callbacks'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/abstract_controller/callbacks.rb:41:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/rescue.rb:22:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/notifications.rb:203:in `block in instrument'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/notifications.rb:203:in `instrument'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/abstract_controller/base.rb:136:in `process'
    /Users/yahonda/src/github.com/yahonda/rails/actionview/lib/action_view/rendering.rb:39:in `process'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal.rb:192:in `dispatch'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/test_case.rb:512:in `process'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/test_case.rb:390:in `get'
    test/controller/mime/accept_format_test.rb:28:in `test_javascript_with_no_format_only_star_star'


rails test test/controller/mime/accept_format_test.rb:26


Finished in 0.134562s, 14.8630 runs/s, 14.8630 assertions/s.
2 runs, 2 assertions, 0 failures, 1 errors, 0 skips
%
```

**Comment by yahonda** [comment]
Reverting the merge commit by #38026 addresses this error.

```console
% git revert -m 1 e36d4a0
```
