### ISSUE TITLE
ThreadError in application (deadlock; recursive locking) after upgrading to Ruby version 2.7.0

### ISSUE THREAD

**Issue by laurosilvacom** [rails/rails#38125]
### Expected behavior

Successfully compile and install gems. 

### Actual behavior

I recently updated my application to use Ruby version 2.7.0. In development it runs fine, but when deploy it fails with the following error: 

I'm not sure how to go about debugging this issue. Any thoughts?

```
-----> Deploying to setih
-----> Connecting to setih (206.189.166.225 port 22) as deploy

Uploaded .hatch/action-271095.sh

Executing 'set -euxo pipefail; timeout 900 bash .hatch/action-271095.sh setih master 20191231033347 2>&1'
+ timeout 900 bash .hatch/action-271095.sh setih master 20191231033347
Fetching origin

-----> Setting Ruby version
Using Ruby from .ruby-version
Using Ruby version: 2.7.0

-----> Running deploy script

-----> Installing gems...
/home/deploy/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems/version.rb:216: warning: deprecated Object#=~ is called on Integer; it always returns nil
/home/deploy/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize': deadlock; recursive locking (ThreadError)
	from /home/deploy/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
	from /home/deploy/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:42:in `require'
	from /home/deploy/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems/resolver/set.rb:24:in `initialize'
	from /home/deploy/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems/request_set.rb:408:in `new'
	from /home/deploy/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems/request_set.rb:408:in `resolve_current'
	from /home/deploy/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems.rb:243:in `finish_resolve'
	from /home/deploy/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems.rb:306:in `block in activate_bin_path'
	from /home/deploy/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems.rb:304:in `synchronize'
	from /home/deploy/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems.rb:304:in `activate_bin_path'
	from /home/deploy/.rbenv/versions/2.7.0/bin/bundle:23:in `'

-----> Command "set -euxo pipefail; timeout 900 bash .hatch/action-271095.sh setih master 20191231033347 2>&1" returned exit code 1
```

### System configuration
**Rails version**:  6.0.2.1

**Ruby version**:  2.7.0p0

**Comment by laurosilvacom** [comment]
Closing this issue. I install the wrong Ruby version on my production server. 😅
