### ISSUE TITLE
Why can't Rails see RAILS_MASTER_KEY?

### ISSUE THREAD

**Issue by asfarley** [rails/rails#38122]
### Steps to reproduce
Full description: 
[https://devops.stackexchange.com/questions/10343/why-is-rails-with-nginx-passenger-via-ansible-unable-to-see-my-rails-master-ke](https://devops.stackexchange.com/questions/10343/why-is-rails-with-nginx-passenger-via-ansible-unable-to-see-my-rails-master-ke)
Ubuntu 18.04
Install rbenv, ruby, Passenger using Ansible Galaxy playbooks
Attempt to deploy with Capistrano

### Expected behavior
I expect that if I can echo `$RAILS_MASTER_KEY` via my 'deploy' user over SSH, and I can access the credential file using `rails credentials:edit`, then Rails should be able to see the same environment variable when the server attempts to respond to a request handled via Nginx/Passenger.

### Actual behavior
When I try to access the landing page of my server, I get a Passenger error indicating that the application failed to start: 

`"The Phusion Passenger application server tried to start the web application. But the application itself (and not Passenger) encountered an internal error."`

My first thought was that this must be related to the user running Rails, but this particular environment variable is set in `/etc/environment`, so I think I can rule that out.

### System configuration
**Rails version**: 5.2.1 in Gemfile, 5.2.2 in Gemfile.lock, 5.2.2. verified to be installed with 'bundle exec rails -v'

**Ruby version**: 2.5.3 in Gemfile, verified to be installed with 'ruby -v'

### Passenger error report

Error details:

```
exit (SystemExit)
  /var/www/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/railtie.rb:60:in `exit'
  /var/www/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/railtie.rb:60:in `rescue in block in <class:Railtie>'
  /var/www/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/railtie.rb:56:in `block in <class:Railtie>'
  /var/www/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
  /var/www/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
  /var/www/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
  /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /var/www/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
  /var/www/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
  /var/www/releases/20191230212823/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require_relative'
  config.ru:3:in `block in <main>'
  /var/www/shared/bundle/ruby/2.5.0/gems/rack-2.0.8/lib/rack/builder.rb:55:in `instance_eval'
  /var/www/shared/bundle/ruby/2.5.0/gems/rack-2.0.8/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```
The stdout/stderr output of the subprocess so far is:

```
I, [2019-12-31T03:37:11.992042 #32154]  INFO -- sentry: ** [Raven] Raven 2.9.0 ready to catch errors
Missing encryption key to decrypt file with. Ask your team for your master key and write it to /var/www/releases/20191230212823/config/master.key or put it in the ENV['RAILS_MASTER_KEY'].
Error: The application encountered the following error: exit (SystemExit)
    /var/www/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/railtie.rb:60:in `exit'
    /var/www/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/railtie.rb:60:in `rescue in block in <class:Railtie>'
    /var/www/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/railtie.rb:56:in `block in <class:Railtie>'
    /var/www/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
    /var/www/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
    /var/www/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
    /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
    /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
    /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
    /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
    /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
    /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
    /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
    /home/deploy/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
    /var/www/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
    /var/www/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
    /var/www/releases/20191230212823/config/environment.rb:5:in `<top (required)>'
    config.ru:3:in `require_relative'
    config.ru:3:in `block in <main>'
    /var/www/shared/bundle/ruby/2.5.0/gems/rack-2.0.8/lib/rack/builder.rb:55:in `instance_eval'
    /var/www/shared/bundle/ruby/2.5.0/gems/rack-2.0.8/lib/rack/builder.rb:55:in `initialize'
    config.ru:1:in `new'
    config.ru:1:in `<main>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

```

**Comment by asfarley** [comment]
Ok, it looks like the root cause is /etc/environment isn't loaded by Passenger. Using the [passenger_env_var](https://stackoverflow.com/questions/10080656/where-to-put-environment-variables-when-using-nginx-and-passenger-on-ubuntu) fixed it for me.
