### ISSUE TITLE
Cannot rollback migration that adds index using sql fragment

### ISSUE THREAD

**Issue by kuroda** [rails/rails#38176]
### Steps to reproduce

I created the `users` table on PostgreSQL 11 with these migrations:

```
class CreateUsers < ActiveRecord::Migration[6.0]
  def change
    create_table :users do |t|
      t.string :name
      t.string :phone

      t.timestamps
    end
  end
end

class AddIndexUsersOnRightPhone4 < ActiveRecord::Migration[6.0]
  def change
    add_index :users, "RIGHT(phone, 4)"
  end
end
```

### Expected behavior

The index on the `users` table should be removed.

### Actual behavior

When I tried to rollback the last migration, I got the following error:

```
== 20200107193941 AddIndexUsersOnRightPhone4: reverting =======================
-- remove_index(:users, {:column=>"RIGHT(phone, 4)"})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

No indexes found on users with the options provided.
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1293:in `index_name_for_remove'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:462:in `remove_index'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:890:in `block in method_missing'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:858:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:858:in `say_with_time'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:879:in `method_missing'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration/command_recorder.rb:116:in `block in replay'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration/command_recorder.rb:115:in `each'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration/command_recorder.rb:115:in `replay'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:702:in `revert'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:826:in `exec_migration'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:811:in `block in migrate'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `with_connection'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:810:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1001:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1311:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1362:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1362:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1310:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1282:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1281:in `each'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1281:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1229:in `block in migrate'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1229:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1071:in `down'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1181:in `move'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1047:in `rollback'
/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/railties/databases.rake:225:in `block (2 levels) in <main>'
/usr/local/bundle/gems/railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.2.1/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/apps/temp5/bin/rails:9:in `<top (required)>'
/usr/local/bundle/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/usr/local/bundle/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/usr/local/bundle/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/usr/local/bundle/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/usr/local/bundle/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/usr/local/bundle/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/usr/local/bundle/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/apps/temp5/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
```

### System configuration

* Rails 6.0.2.1
* Ruby 2.6.4

**Comment by rafaelfranca** [comment]
Yes, that is true. It is not possible to rollback automatically when you define an index like that. You need to define the `down` and `up` methods instead.

Thank you for the issue.
