### ISSUE TITLE
Jenkins fails to install ruby-runtime plugin

### ISSUE THREAD

**Issue by whr845736938** [rails/rails#38182]
When I install ruby-runtime on jenkins, the log gives the following error, who can help me.
Loading plugin ruby-runtime v0.12 (ruby-runtime) failed perhaps due to plugin dependency issues
org.jcodings.exception.InternalException: entry: /tables/CaseFold_From.bin not found
	at org.jcodings.util.ArrayReader.openStream(ArrayReader.java:33)
	at org.jcodings.util.ArrayReader.readIntArray(ArrayReader.java:54)
	at org.jcodings.unicode.UnicodeEncoding.<clinit>(UnicodeEncoding.java:480)
Caused: java.lang.ExceptionInInitializerError
	at org.jruby.RubyString.<clinit>(RubyString.java:123)
	at org.jruby.Ruby.initCore(Ruby.java:1304)
	at org.jruby.Ruby.bootstrap(Ruby.java:1213)
	at org.jruby.Ruby.init(Ruby.java:1148)
	at org.jruby.Ruby.newInstance(Ruby.java:286)
	at org.jruby.embed.internal.SingleThreadLocalContextProvider.getRuntime(SingleThreadLocalContextProvider.java:60)
	at org.jruby.embed.internal.EmbedRubyRuntimeAdapterImpl.runParser(EmbedRubyRuntimeAdapterImpl.java:156)
	at org.jruby.embed.internal.EmbedRubyRuntimeAdapterImpl.parse(EmbedRubyRuntimeAdapterImpl.java:93)
	at org.jruby.embed.ScriptingContainer.parse(ScriptingContainer.java:1196)
	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1256)
	at org.kohsuke.stapler.jelly.jruby.JRubyFacet.<init>(JRubyFacet.java:66)
	at ruby.RubyRuntimePlugin.registerJRubyFacet(RubyRuntimePlugin.java:39)
	at ruby.RubyRuntimePlugin.start(RubyRuntimePlugin.java:30)
	at hudson.ClassicPluginStrategy.startPlugin(ClassicPluginStrategy.java:401)
	at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:390)
Caused: java.io.IOException: Failed to initialize
	at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:393)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:547)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1142)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by eileencodes** [comment]
Hey @whr845736938 this sounds like a ruby-runtime or a jenkins issue, but definitely isn't a Rails bug. Hope you figure it out.

**Comment by anantjain4567** [comment]
I am also facing the same issue, if someone can provide with any help?

**Comment by eileencodes** [comment]
@anantjain4567 sorry we can't help, this isn't a Rails issue. We don't maintain Jenkins or Jenkins plugins. Please use stackoverflow or report the bug to Jenkins.
