### ISSUE TITLE
ActiveStorage: `IOError: closed stream` when multiple files are attached within a transaction

### ISSUE THREAD

**Issue by escanxr** [rails/rails#38185]
Hello,

I currently update an application from rails 5.2.3 to 6.0.1. Everything is OK except when we attach files several times within a same transaction during our tests. If the `attach` method is called at least twice within a transaction, we get an error: `IOError: closed stream`. If the code is not wrapped within  an `ActiveRecord::Base.transaction`, the error no longer occurs.

We use this storage configuration for our test environment:

```
local:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
```

We have a model Category with multiple `has_one_attached`:

```
  %i[size_chart ambiance_image logo_fr logo_de].each do |attachement|
    has_one_attached attachement
    validates attachement, attachment_type: { type: :image }
  end
```

Then we have a model where there's a method to create some records (a sale with his relations) from a json. The files we want to attach are in the tmp folder.

```
def process
  zip_file     = Dir["#{Rails.root}/tmp/product_imports/oc/#{sale.vp_code}/#{sale.oc_code}_*.zip"].first
  extract_path = "#{Rails.root}/tmp/product_imports/oc/#{File.basename(zip_file, '.*')}"

  Zip::File.open(zip_file) do |zip_files|
    zip_files.each do |entry|
      fpath = File.join(extract_path, entry.name.tr('\\', '_'))
      FileUtils.mkdir_p(File.dirname(fpath))
      entry.extract(fpath)
    end
  end

  if File.exist?("#{extract_path}/#{sale.oc_code}.json")
    ActiveRecord::Base.transaction(isolation: Rails.env.test? ? nil : :read_uncommitted) do
      json = Oj.load(File.read("#{extract_path}/#{sale.oc_code}.json"))

      json[:operation][:universes].each do |universe|
        ambiancevisual = []

        if universe.dig(:medias, :ambiance1)
          ambiancevisual = Dir.glob("#{extract_path}/#{universe[:medias][:ambiance1][:targetOcUnc]}".tr('\\\\', '/'))
        elsif universe.dig(:medias, :ambiance0)
          ambiancevisual = Dir.glob("#{extract_path}/#{universe[:medias][:ambiance0][:targetOcUnc]}".tr('\\\\', '/'))
        end

        if ambiancevisual.any? && !category.ambiance_image.attached?
          image = File.new(ambiancevisual.first, 'r')
          category.ambiance_image.attach(io: image, filename: File.basename(image))
          image.close
        end

        if universe.dig(:medias, :logo0)
          logo = Dir.glob("#{extract_path}/#{universe[:medias][:logo0][:targetOcUnc].tr('\\', '_')}")
          if logo.any?
              image    = File.new(logo.first, 'r')
              filename = File.basename(image)
              category.logo_fr.attach(io: image, filename: filename) unless category.logo_fr.attached?
              image.rewind # Temp Fix for ActiveStorage https://github.com/rails/rails/issues/32855
              category.logo_de.attach(io: image, filename: filename) unless category.logo_de.attached?
              image.close
          end
        end
      end
    end
  end

  [...]
end
```

Stack trace:
```
IOError:
  closed stream
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activestorage-6.0.1/lib/active_storage/service/disk_service.rb:20:in `copy_stream'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activestorage-6.0.1/lib/active_storage/service/disk_service.rb:20:in `block in upload'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/notifications.rb:180:in `block in instrument'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/notifications.rb:180:in `instrument'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activestorage-6.0.1/lib/active_storage/service.rb:126:in `instrument'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activestorage-6.0.1/lib/active_storage/service/disk_service.rb:19:in `upload'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activestorage-6.0.1/app/models/active_storage/blob.rb:194:in `upload_without_unfurling'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activestorage-6.0.1/lib/active_storage/attached/changes/create_one.rb:27:in `upload'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/core_ext/object/try.rb:15:in `public_send'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/core_ext/object/try.rb:15:in `try'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activestorage-6.0.1/lib/active_storage/attached/model.rb:56:in `block in has_one_attached'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:429:in `instance_exec'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:429:in `block in make_lambda'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:264:in `block in conditional'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:518:in `block in invoke_after'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:518:in `each'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:518:in `invoke_after'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rails/active_record_rescue.rb:11:in `run_callbacks'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:827:in `_run_commit_callbacks'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activerecord-6.0.1/lib/active_record/transactions.rb:340:in `committed!'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:127:in `commit_records'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:265:in `block in commit_transaction'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:255:in `commit_transaction'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:293:in `block in within_new_transaction'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
# /Users/escanxr/.rvm/gems/ruby-2.6.5@xxxx/gems/activerecord-6.0.1/lib/active_record/transactions.rb:212:in `transaction'
# ./app/models/product_oc_import.rb:36:in `process'
# ./spec/models/product_oc_import_spec.rb:77:in `block (2 levels) in <top (required)>'
```

With the 5.2.3 version, the code above works.
Please tell me if you need any other details. Have a good day.

### System configuration
**Rails version**: 6.0.1
**Ruby version**: 2.6.5

**Comment by georgeclaghorn** [comment]
The problem is that you’re closing attached IO objects before the transaction commits, like so:

```ruby
ActiveRecord::Base.transaction do
  image = File.new(...)
  category.logo_fr.attach(io: image, ...)
  image.close # ← image is closed here
end           # ← transaction commits here
```

Uploads happen after commit now, so IO objects need to be open when the transaction commits. Reorder the operations to fix:

```ruby
File.open(...) do |image|
  ActiveRecord::Base.transaction do
    category.logo_fr.attach(io: image, ...)
  end
end
```

**Comment by escanxr** [comment]
Thanks for you answer @georgeclaghorn, I didn't notice this change, it's a good thing. 👍

**Comment by kimadactyl** [comment]
I'm getting exactly the same error as the original poster with multiple images. I'm creating a migration to upload existing files from an old site into a new one. Here's the migration:

```ruby
class AddImagesToBlogs < ActiveRecord::Migration[6.0]
  def up
    json = File.read(Rails.root.join('db', 'import', 'files.json'))
    images = JSON.parse(json)

    images.each do |image|
      filename = image["filename"]
      b = Blog.find_by(imported_id: image['entity_id'])
      File.open(Rails.root.join('db', 'import', 'files', filename)) do |file|
        ActiveRecord::Base.transaction do
          b.images.attach(io: file, filename: filename)
          puts "Uploaded #{filename} to #{image['entity_id']}..."
        end
      end
    end
  end

  def down
    Blog.find_each { |b| b.images.purge }
  end
end
```

Blog model

```ruby
class Blog < ApplicationRecord
  validates :title, presence: true
  has_many_attached :images

  ...
end
```

It actually seems to finish the migration (my last file's, `pinus.JPG`'s log message shows up) but then I get this:

```
Uploaded pinus.JPG to 166...
== 20200423150600 AddImagesToBlogs: migrated (2.5945s) ========================

rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

closed stream
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/service/disk_service.rb:20:in `copy_stream'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/service/disk_service.rb:20:in `block in upload'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/notifications.rb:180:in `block in instrument'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/notifications.rb:180:in `instrument'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/service.rb:126:in `instrument'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/service/disk_service.rb:19:in `upload'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/app/models/active_storage/blob.rb:196:in `upload_without_unfurling'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/attached/changes/create_one.rb:27:in `upload'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/attached/changes/create_many.rb:20:in `each'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/attached/changes/create_many.rb:20:in `upload'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/core_ext/object/try.rb:15:in `public_send'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/core_ext/object/try.rb:15:in `try'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/attached/model.rb:129:in `block in has_many_attached'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:429:in `instance_exec'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:429:in `block in make_lambda'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:264:in `block in conditional'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:518:in `block in invoke_after'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:518:in `each'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:518:in `invoke_after'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:136:in `run_callbacks'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:827:in `_run_commit_callbacks'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:340:in `committed!'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:127:in `commit_records'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:265:in `block in commit_transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:255:in `commit_transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:293:in `block in within_new_transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:212:in `transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1362:in `ddl_transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1310:in `execute_migration_in_transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1282:in `block in migrate_without_lock'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1281:in `each'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1281:in `migrate_without_lock'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1229:in `block in migrate'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1229:in `migrate'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1061:in `up'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1036:in `migrate'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/railties/databases.rake:84:in `each'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/command.rb:48:in `invoke'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<main>'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
/Users/kim/src/katescuttings_v2/bin/rails:9:in `<top (required)>'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/kim/src/katescuttings_v2/bin/spring:15:in `require'
/Users/kim/src/katescuttings_v2/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
IOError: closed stream
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/service/disk_service.rb:20:in `copy_stream'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/service/disk_service.rb:20:in `block in upload'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/notifications.rb:180:in `block in instrument'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/notifications.rb:180:in `instrument'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/service.rb:126:in `instrument'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/service/disk_service.rb:19:in `upload'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/app/models/active_storage/blob.rb:196:in `upload_without_unfurling'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/attached/changes/create_one.rb:27:in `upload'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/attached/changes/create_many.rb:20:in `each'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/attached/changes/create_many.rb:20:in `upload'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/core_ext/object/try.rb:15:in `public_send'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/core_ext/object/try.rb:15:in `try'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activestorage-6.0.2.2/lib/active_storage/attached/model.rb:129:in `block in has_many_attached'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:429:in `instance_exec'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:429:in `block in make_lambda'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:264:in `block in conditional'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:518:in `block in invoke_after'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:518:in `each'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:518:in `invoke_after'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:136:in `run_callbacks'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:827:in `_run_commit_callbacks'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:340:in `committed!'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:127:in `commit_records'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:265:in `block in commit_transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:255:in `commit_transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:293:in `block in within_new_transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:212:in `transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1362:in `ddl_transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1310:in `execute_migration_in_transaction'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1282:in `block in migrate_without_lock'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1281:in `each'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1281:in `migrate_without_lock'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1229:in `block in migrate'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1229:in `migrate'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1061:in `up'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:1036:in `migrate'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/railties/databases.rake:84:in `each'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.2/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/command.rb:48:in `invoke'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<main>'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
/Users/kim/src/katescuttings_v2/bin/rails:9:in `<top (required)>'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/Users/kim/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/kim/src/katescuttings_v2/bin/spring:15:in `require'
/Users/kim/src/katescuttings_v2/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

This is a fairly vanilla site so really scratching my head what I can do differnetly!

**Comment by escanxr** [comment]
Migrations are wrapped in a transaction if your database supports it.
You can use the `disable_ddl_transaction!` to disable this behavior in your migration. 👍

https://apidock.com/rails/ActiveRecord/Migration/disable_ddl_transaction!/class
