### ISSUE TITLE
Unable to use ActionCable on GCP Memorystore

### ISSUE THREAD

**Issue by archonic** [rails/rails#38244]
### Steps to reproduce
GCP Memory store has the `client` redis command disabled. ActionCable attempts to use this command. If the Redis connection is configurable, this issue is avoidable.

This comment explains the workaround for Sidekiq:
https://github.com/mperham/sidekiq/issues/3518#issuecomment-390898217

Setting `id: nil` in cable.yml will stringify `nil`. I'm not sure if there's another way to configure the Redis connection for ActionCable.

### Expected behavior
ActionCable should be able to work with GCP Memorystore using the redis adapter.

### Actual behavior
Doesn't work. Here's my production log:
```
Registered connection (Z2lkOi8vY29sbGFib3Jhc2UvVXNlci8x)
#<Thread:0x000056542e52e760@/usr/local/bundle/gems/actioncable-6.0.2.1/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:124:in `call': ERR unknown command `client`, with args beginning with: `setname`, `nil`,  (Redis::CommandError)
	from /usr/local/bundle/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/redis.rb:74:in `call'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:107:in `block in connect'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:296:in `with_reconnect'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:103:in `connect'
	from /usr/local/bundle/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/redis.rb:120:in `connect'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:279:in `with_socket_timeout'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:136:in `call_loop'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/subscribe.rb:43:in `subscription'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/subscribe.rb:12:in `subscribe'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:3010:in `_subscription'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:2205:in `block in subscribe'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:50:in `block in synchronize'
	from /usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:50:in `synchronize'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:2204:in `subscribe'
	from /usr/local/bundle/gems/actioncable-6.0.2.1/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:296:in `with_reconnect'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:56:in `block in with_reconnect'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:50:in `block in synchronize'
	from /usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:50:in `synchronize'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:55:in `with_reconnect'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:62:in `without_reconnect'
	from /usr/local/bundle/gems/actioncable-6.0.2.1/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /usr/local/bundle/gems/actioncable-6.0.2.1/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:124:in `call': ERR unknown command `client`, with args beginning with: `setname`, `nil`,  (Redis::CommandError)
	from /usr/local/bundle/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/redis.rb:74:in `call'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:107:in `block in connect'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:296:in `with_reconnect'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:103:in `connect'
	from /usr/local/bundle/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/redis.rb:120:in `connect'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:279:in `with_socket_timeout'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:136:in `call_loop'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/subscribe.rb:43:in `subscription'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/subscribe.rb:12:in `subscribe'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:3010:in `_subscription'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:2205:in `block in subscribe'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:50:in `block in synchronize'
	from /usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:50:in `synchronize'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:2204:in `subscribe'
	from /usr/local/bundle/gems/actioncable-6.0.2.1/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis/client.rb:296:in `with_reconnect'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:56:in `block in with_reconnect'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:50:in `block in synchronize'
	from /usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:50:in `synchronize'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:55:in `with_reconnect'
	from /usr/local/bundle/gems/redis-4.0.3/lib/redis.rb:62:in `without_reconnect'
	from /usr/local/bundle/gems/actioncable-6.0.2.1/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /usr/local/bundle/gems/actioncable-6.0.2.1/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
[1] - Worker 0 (pid: 23001) booted, phase: 0
```

### System configuration
**Rails version**: 6.0.2.1
**Ruby version**: 2.6.3

**Comment by kaspth** [comment]
Please use the Ruby on Rails talk mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

There's also this, which could use some documentation: https://github.com/rails/rails/blob/bb5ac1623e8de08c1b7b62b1368758f0d3bb6379/actioncable/lib/action_cable/subscription_adapter/redis.rb#L17

**Comment by archonic** [comment]
For anyone else that hit this issue, you can add this to config/initializers/actioncable.rb

```
# frozen_string_literal: true

require 'action_cable/subscription_adapter/redis'

ActionCable::SubscriptionAdapter::Redis.redis_connector = ->(config) do
  config[:id] = nil
  ::Redis.new(config.except(:adapter, :channel_prefix))
end
```
It would be nice to be able to write `id: null` in the production section of cable.yml, but `||=` will end up overwriting it. It would also be nice to see it in the docs.
