### ISSUE TITLE
NoMethodError: undefined method `connection_db_config' on 6-0-stable

### ISSUE THREAD

**Issue by agrieser** [rails/rails#38315]
### Steps to reproduce
`rails db:migrate`

references a method that is not defined:
https://github.com/rails/rails/blob/6-0-stable/activerecord/lib/active_record/migration.rb#L1377

stacktrace below

```
./bin/rails db:migrate db:test:prepare --trace
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:migrate
rails aborted!
NoMethodError: undefined method `connection_db_config' for ActiveRecord::Base:Class
Did you mean?  connection_config
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/activerecord/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/activerecord/lib/active_record/migration.rb:1377:in `with_advisory_lock'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/activerecord/lib/active_record/migration.rb:1229:in `migrate'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/activerecord/lib/active_record/migration.rb:1061:in `up'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/activerecord/lib/active_record/migration.rb:1036:in `migrate'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/activerecord/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/activerecord/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/activerecord/lib/active_record/railties/databases.rake:84:in `each'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/activerecord/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/railties/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/railties/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/railties/lib/rails/command.rb:48:in `invoke'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/railties/lib/rails/commands.rb:18:in `<main>'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/activesupport/lib/active_support/dependencies.rb:324:in `block in require'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/activesupport/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/rails-1ff3ecd5ebea/activesupport/lib/active_support/dependencies.rb:324:in `require'
/Users/myuser/code/project/bin/rails:9:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
/Users/myuser/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
/Users/myuser/code/project/bin/spring:15:in `<top (required)>'
./bin/rails:3:in `load'
./bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
```

### Expected behavior
The migrations run

### Actual behavior
A nomethod error is raised

### System configuration
6-0-stable (1ff3ecd5ebea63ad8c6d8e21ecc2091c290a434b)

**Ruby version**: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]

**Comment by eileencodes** [comment]
Closed by #38316
