### ISSUE TITLE
Yarn installation requirement missing in Getting Started guide

### ISSUE THREAD

**Issue by potentialize** [rails/rails#38322]
I am new to Rails, so I followed this guide: https://guides.rubyonrails.org/getting_started.html. The first couple of times `rails server` did not work. Turns out that Rails depends on Yarn, and since Yarn was not installed on my computer, `rails new` could not set up my project properly.

### Steps to reproduce

Set up a new Rails project on a computer that does not have Yarn installed.

### Expected behavior
Follow the Getting Started guide, Rails works without an issue.

### Actual behavior
Follow the Getting Started guide, `rails server` spits a `RuntimeError` because it depends on Yarn. Since Yarn was not installed on my computer, `rails new` could not set up Rails properly for me. 

### System configuration
**Rails version**: Rails 6.0.2.1

**Ruby version**: ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux]

### Stack trace (for completion)
```
$ rails server
=> Booting Puma
=> Rails 6.0.2.1 application starting in development 
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	81: from bin/rails:3:in `<main>'
	80: from bin/rails:3:in `load'
	79: from /home/bruno/potentialize/rails_example/blog/bin/spring:15:in `<top (required)>'
	78: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	77: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	76: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	75: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	74: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	73: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	72: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	71: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	70: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	69: from /home/bruno/potentialize/rails_example/blog/bin/rails:9:in `<top (required)>'
	68: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	67: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	66: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	65: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	64: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	63: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	62: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	61: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	60: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
	59: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
	58: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
	57: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	56: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	55: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	54: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	53: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	52: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	51: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:37:in `start'
	50: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	49: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/server.rb:424:in `wrapped_app'
	48: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/server.rb:251:in `app'
	47: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/server.rb:351:in `build_app_and_options_from_config'
	46: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/builder.rb:40:in `parse_file'
	45: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/builder.rb:59:in `load_file'
	44: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/builder.rb:65:in `new_from_string'
	43: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/builder.rb:65:in `eval'
	42: from config.ru:in `<main>'
	41: from config.ru:in `new'
	40: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/builder.rb:71:in `initialize'
	39: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/builder.rb:71:in `instance_eval'
	38: from config.ru:3:in `block in <main>'
	37: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
	36: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	35: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	34: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	33: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
	32: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	31: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	30: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	29: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	28: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	27: from /home/bruno/potentialize/rails_example/blog/config/environment.rb:5:in `<main>'
	26: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
	25: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	24: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	23: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	22: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	21: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `call'
	20: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `each'
	19: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	18: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	17: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	16: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	15: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	14: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
	13: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	12: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/railtie.rb:84:in `block in <class:Engine>'
	11: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker.rb:35:in `bootstrap'
	10: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/commands.rb:25:in `bootstrap'
	 9: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/manifest.rb:18:in `refresh'
	 8: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/manifest.rb:83:in `load'
	 7: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:51:in `public_manifest_path'
	 6: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:47:in `public_output_path'
	 5: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:43:in `public_path'
	 4: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:84:in `fetch'
	 3: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:88:in `data'
	 2: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:92:in `load'
	 1: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:92:in `read'
/home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:92:in `read': No such file or directory @ rb_sysopen - /home/bruno/potentialize/rails_example/blog/config/webpacker.yml (Errno::ENOENT)
	80: from bin/rails:3:in `<main>'
	79: from bin/rails:3:in `load'
	78: from /home/bruno/potentialize/rails_example/blog/bin/spring:15:in `<top (required)>'
	77: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	76: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	75: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	74: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	73: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	72: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	71: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	70: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	69: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	68: from /home/bruno/potentialize/rails_example/blog/bin/rails:9:in `<top (required)>'
	67: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	66: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	65: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	64: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	63: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	62: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	61: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	60: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	59: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
	58: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
	57: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
	56: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	55: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	54: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	53: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	52: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	51: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	50: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:37:in `start'
	49: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	48: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/server.rb:424:in `wrapped_app'
	47: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/server.rb:251:in `app'
	46: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/server.rb:351:in `build_app_and_options_from_config'
	45: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/builder.rb:40:in `parse_file'
	44: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/builder.rb:59:in `load_file'
	43: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/builder.rb:65:in `new_from_string'
	42: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/builder.rb:65:in `eval'
	41: from config.ru:in `<main>'
	40: from config.ru:in `new'
	39: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/builder.rb:71:in `initialize'
	38: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.1.1/lib/rack/builder.rb:71:in `instance_eval'
	37: from config.ru:3:in `block in <main>'
	36: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
	35: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	34: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	33: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	32: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
	31: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	30: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	29: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	28: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	27: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	26: from /home/bruno/potentialize/rails_example/blog/config/environment.rb:5:in `<main>'
	25: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
	24: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	23: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	22: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	21: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	20: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `call'
	19: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `each'
	18: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	17: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	16: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	15: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	14: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	13: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
	12: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	11: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/railtie.rb:84:in `block in <class:Engine>'
	10: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker.rb:35:in `bootstrap'
	 9: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/commands.rb:25:in `bootstrap'
	 8: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/manifest.rb:18:in `refresh'
	 7: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/manifest.rb:83:in `load'
	 6: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:51:in `public_manifest_path'
	 5: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:47:in `public_output_path'
	 4: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:43:in `public_path'
	 3: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:84:in `fetch'
	 2: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:88:in `data'
	 1: from /home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:91:in `load'
/home/bruno/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:95:in `rescue in load': Webpacker configuration file not found /home/bruno/potentialize/rails_example/blog/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - /home/bruno/potentialize/rails_example/blog/config/webpacker.yml (RuntimeError)
```

**Comment by NeilsC** [comment]
Experiencing the same issue. 

ruby 2.6.5p114
rails 6.0.2.1

**Comment by fede-moya** [comment]
Experiencing the same issue. I think the same applies for NodeJS. Seems like the following section of the getting started guide needs an update 
[`Before you install Rails, you should check to make sure that your system has the proper prerequisites installed. These include Ruby and SQLite3.`](https://guides.rubyonrails.org/getting_started.html#installing-rails) do you guys agree ? @NeilsC @potentialize

**Comment by jakeNiemiec** [comment]
> read': **No such file** or directory @ rb_sysopen - /home/bruno/potentialize/rails_example/blog/config/**webpacker.yml** (Errno::ENOENT)

You might just need to run `bundle exec rails webpacker:install` or create `webpacker.yml` yourself.

**Comment by cur33** [comment]
> > read': **No such file** or directory @ rb_sysopen - /home/bruno/potentialize/rails_example/blog/config/**webpacker.yml** (Errno::ENOENT)
> 
> You might just need to run `bundle exec rails webpacker:install` or create `webpacker.yml` yourself.

I had the same problem, and this is the solution. However, the real problem was that running `rails webpacker:install` also failed because yarn wasn't installed. From the problem description, I believe the OP already realizes this. The true issue here, as OP mentioned, is that the guide doesn't mention installing yarn. It only says to ensure that you have ruby and sqlite3 installed, and after that, it jumps straight into creating a new Rails project.
