### ISSUE TITLE
Raising error while migrating logs it twice in console

### ISSUE THREAD

**Issue by Kejmer** [rails/rails#38335]
### Steps to reproduce
Tell me if this is intentional behavior and if it is possible to limit error prints.
Fixes on `rails server` from other issues didn't resolve the problem.

Tested both on Rails 4 and 6

Run migration
```
class MigrationError < ActiveRecord::Migration
  def change
    raise "__migration_failed__"
  end
end
```

### Expected behavior
```
== 20200122145306 MigrationError: migrating ===================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

__migration_failed__
/home/f12/projects/rubyexample/db/migrate/20200122145306_migration_error.rb:3:in `change'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:608:in `exec_migration'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:591:in `block in migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:590:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:768:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1071:in `ddl_transaction'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:984:in `block in migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `each'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:823:in `up'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:801:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/home/f12/.rvm/gems/ruby-2.4.6/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/f12/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
/home/f12/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### Actual behavior
```
== 20200122145306 MigrationError: migrating ===================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

__migration_failed__
/home/f12/projects/rubyexample/db/migrate/20200122145306_migration_error.rb:3:in `change'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:608:in `exec_migration'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:591:in `block in migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:590:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:768:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1071:in `ddl_transaction'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:984:in `block in migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `each'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:823:in `up'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:801:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/home/f12/.rvm/gems/ruby-2.4.6/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/f12/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
/home/f12/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
__migration_failed__
/home/f12/projects/rubyexample/db/migrate/20200122145306_migration_error.rb:3:in `change'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:608:in `exec_migration'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:591:in `block in migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:590:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:768:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1071:in `ddl_transaction'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:984:in `block in migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `each'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:823:in `up'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:801:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/home/f12/.rvm/gems/ruby-2.4.6/gems/activerecord-4.2.11.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/home/f12/.rvm/gems/ruby-2.4.6/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/f12/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
/home/f12/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

### System configuration
**Rails version**: 4.2.11.1 and 6.0.2.1

**Ruby version**: 2.4.6 and 2.6.5

**Comment by eileencodes** [comment]
Yes this is expected behavior which outputs the trace for the method that hit an error and the trace for the tasks themselves. Otherwise you'd just get the trace and not know what rake task caused the error.
