### ISSUE TITLE
Rails 6: errors when trying to assign many_to_many association. involves foreign keys. 

### ISSUE THREAD

**Issue by AdnanTheExcellent** [rails/rails#38361]
### Steps to reproduce
```
Class Spree::LineItem
    has_many :eligible_facility_line_items, class_name: "Mgx::EligibleFacilityLineItem", dependent: :destroy,
       foreign_key: "line_item_id", inverse_of: :eligible_facility
    has_many :eligible_facilities, through: :eligible_facility_line_items, class_name: "Spree::StockLocation"
end

Class Spree::StockLocation
  has_many :eligible_facility_line_items, foreign_key: :eligible_facility_id,
       class_name: "Mgx::EligibleFacilityLineItem", dependent: :destroy, inverse_of: :eligible_facility
  has_many :line_items, through: :eligible_facility_line_items, class_name: "Spree::LineItem"
end

line_item.create #(id is 1071460299)
eligible_facility1 = Spree::StockLocation.create(key: facility-key-1) #(id is 1)
eligible_facility2 = Spree::StockLocation.create(key: facility-key-2) #(id is 2)
line_item.eligible_facilities = [eligible_facility1, eligible_facility2]
```

### Expected behavior
I expect rails to create the join tables properly for the association between the line_item and eligible_facilities. This worked in rails 5.2.3

### Actual behavior
I get this when trying to create the association:

```
[3] pry(#<Spree::OrderContents>)> line_item.eligible_facilities = eligible_facilities
  Spree::StockLocation Load (0.5ms)  SELECT `spree_stock_locations`.* FROM `spree_stock_locations` INNER JOIN `mgx_eligible_facility_line_items` ON `spree_stock_locations`.`id` = `mgx_eligible_facility_line_items`.`eligible_facility_id` WHERE `mgx_eligible_facility_line_items`.`line_item_id` = 1071460299
  ↳ (pry):11:in `add_to_line_item'
   (0.2ms)  BEGIN
  ↳ (pry):11:in `add_to_line_item'
  Spree::LineItem Load (0.3ms)  SELECT `spree_line_items`.* FROM `spree_line_items` WHERE `spree_line_items`.`id` = 1071460299 LIMIT 1
  ↳ (pry):11:in `add_to_line_item'
  Mgx::EligibleFacilityLineItem Create (0.7ms)  INSERT INTO `mgx_eligible_facility_line_items` (`eligible_facility_id`, `line_item_id`) VALUES (1071460299, 1071460299)
  ↳ (pry):11:in `add_to_line_item'
   (5.5ms)  ROLLBACK
  ↳ (pry):11:in `add_to_line_item'
/home/adnan/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.12.2/lib/pry/exceptions.rb:28: warning: $SAFE will become a normal global variable in Ruby 3.0
ActiveRecord::InvalidForeignKey: Mysql2::Error: Cannot add or update a child row: a foreign key constraint fails (`mgx_development`.`mgx_eligible_facility_line_items`, CONSTRAINT `fk_rails_ec3042de9d` FOREIGN KEY (`eligible_facility_id`) REFERENCES `spree_stock_locations` (`id`))
from /home/adnan/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'       Caused by Mysql2::Error: Cannot add or update a child row: a foreign key constraint fails (`mgx_development`.`mgx_eligible_facility_line_items`, CONSTRAINT `fk_rails_ec3042de9d` FOREIGN KEY (`eligible_facility_id`) REFERENCES `spree_stock_locations` (`id`))
from /home/adnan/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'       
[4] pry(#<Spree::OrderContents>)> line_item.eligible_facility_line_items
  Mgx::EligibleFacilityLineItem Load (0.6ms)  SELECT `mgx_eligible_facility_line_items`.* FROM `mgx_eligible_facility_line_items` WHERE `mgx_eligible_facility_line_items`.`line_item_id` = 1071460299
  ↳ app/models/spree/order_contents_decorator.rb:18:in `add_to_line_item'
=> [#<Mgx::EligibleFacilityLineItem:0x00007ff44c46b340
  eligible_facility_id: 1071460299,
  line_item_id: 1071460299,
  id: nil>]
```

I am not sure why its trying to put the line_item_id in the eligible_facility_id column. 

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.7.0

**Comment by AdnanTheExcellent** [comment]
nevermind, i figured it out. looks like the "invernse_of in Spree::LineItem was set incorrectly. I'm not sure why this was working before in rails 5.2.3. maybe it didnt do certain checks?
