### ISSUE TITLE
Join error when using Lateral: undefined method `name' for #<Arel::Nodes::Lateral:0x00007fd87cb337b8> (NoMethodError)

### ISSUE THREAD

**Issue by adis-io** [rails/rails#38618]
Currently I'm using Rails 5.0.0.1 in my project. Due to `lateral` was introduced in Rails 6.0, I monkey-patched my arel version and issued a problem with `lateral` usage. I tried to reproduce it on Rails 6.0 and surprisingly problem still exists.

### Steps to reproduce
```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', github: 'rails/rails'
  gem 'pg'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'test_arel')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.references :post
  end

  create_table :tags, force: true do |t|
    t.references :post
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  has_many :tags
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class Tag < ActiveRecord::Base
  belongs_to :post
end

class BugTest < ActiveSupport::TestCase
  def _(table)
    Arel::Table.new(table)
  end

  def setup
    subquery = _(:comments)
      .project(_(:comments)[:post_id], "string_agg(comments.id::text, ', ') as ids")
      .group(_(:comments)[:post_id])
      .where(_(:comments)[:post_id].eq(_(:posts)[:id]))
      .lateral('comment_ids')

    comment_ids = Post.joins(
      _(:posts)
        .join(subquery, Arel::Nodes::OuterJoin)
        .on(_(:posts)[:id].eq(_(:comment_ids)[:post_id]))
        .join_sources
    )

    @query = Post.select(_(:posts)[:id])
      .merge(comment_ids)
  end

  def test_just_lateral_works
    assert_equal 0, @query.count
  end

  def test_lateral_join_with_additional_join_works
    assert_equal 0, @query.joins(:tags).count
  end
end
```

### Expected behavior
Everything must work, both test cases should pass.

### Actual behavior
`NoMethodError` exception raised on `test_lateral_join_with_additional_join_works`.

Error backtrace:
```
Traceback (most recent call last):
  23: from app.rb:80:in `<main>'
  22: from app.rb:73:in `test_lateral_join_works'
  21: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/calculations.rb:49:in `count'
  20: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/calculations.rb:142:in `calculate'
  19: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/calculations.rb:252:in `perform_calculation'
  18: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/calculations.rb:295:in `execute_simple_calculation'
  17: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/query_methods.rb:1016:in `arel'
  16: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/query_methods.rb:1044:in `build_arel'
  15: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/query_methods.rb:1164:in `build_joins'
  14: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/query_methods.rb:1179:in `build_join_query'
  13: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/join_dependency.rb:84:in `join_constraints'
  12: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/join_dependency.rb:148:in `construct_tables!'
  11: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/join_dependency/join_part.rb:37:in `each_children'
  10: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/join_dependency/join_part.rb:37:in `each'
   9: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/join_dependency/join_part.rb:38:in `block in each_children'
   8: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/join_dependency.rb:149:in `block in construct_tables!'
   7: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/join_dependency.rb:167:in `table_aliases_for'
   6: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/join_dependency.rb:167:in `map'
   5: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/join_dependency.rb:168:in `block in table_aliases_for'
   4: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/alias_tracker.rb:52:in `aliased_table_for'
   3: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/alias_tracker.rb:14:in `block in create'
   2: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/alias_tracker.rb:24:in `initial_count_for'
   1: from ./gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/associations/alias_tracker.rb:24:in `map'
./gems/activerecord-6.0.2.1/lib/active_record/associations/alias_tracker.rb:34:in `block in initial_count_for': undefined method `name' for #<Arel::Nodes::Lateral:0x00007fd87cb337b8> (NoMethodError)
```

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.5.3

**Comment by adis-io** [comment]
For now I'm monkey patched Arel and it works fine:
```ruby
# frozen_string_literal: true

module DepthFirstOuterJoinLateral
  def self.included(_)
    alias_method :visit_Arel_Nodes_OuterJoinLateral, :binary
  end
end

module DotOuterJoinLateral
  def self.included(_)
    alias_method :visit_Arel_Nodes_OuterJoinLateral, :visit_Arel_Nodes_InnerJoin
  end
end

module VisitorsPostgresqlOuterJoinLateral
  def visit_Arel_Nodes_OuterJoinLateral(o, collector)
    collector << 'LEFT OUTER JOIN LATERAL '
    collector = visit o.left, collector
    collector << ' '
    visit o.right, collector
  end
end

module Arel
  module Nodes
    class OuterJoinLateral < Arel::Nodes::OuterJoin
    end
  end
end

Arel::Visitors::DepthFirst.extend DepthFirstOuterJoinLateral
Arel::Visitors::PostgreSQL.include VisitorsPostgresqlOuterJoinLateral
```

Instead `Arel::Nodes::OuterJoin` I'm using `Arel::Nodes::OuterJoinLateral`
