### ISSUE TITLE
rails new -d sqlite3 app looking for postgres

### ISSUE THREAD

**Issue by ejstembler** [rails/rails#38645]
### Steps to reproduce

Create new rails 6 app:
```console
$ rails new myapp -d sqlite3
```
You can even omitt the `-d sqlite3` since sqlite3 is the default.

```console
$ cd myapp
$ ./bin/rails server
```

Open a browser to the address:

```console
$ open http://localhost:3000
```

The first error complains about the `pg` gem not being installed, even though I'm using `sqlite3` and not postgres:

```console
#<LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile.>
/Users/myuser/.gem/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:4:in `<main>'
/Users/myuser/Projects/myapp/vendor/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/myuser/Projects/myapp/vendor/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/myuser/Projects/myapp/vendor/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/myuser/Projects/myapp/vendor/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/myuser/Projects/myapp/vendor/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/myuser/Projects/myapp/vendor/bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/connection_specification.rb:170:in `spec'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1054:in `establish_connection'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:51:in `establish_connection'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activerecord-6.0.2.1/lib/active_record/railtie.rb:201:in `block (2 levels) in <class:Railtie>'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:72:in `class_eval'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:72:in `block in execute_hook'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activerecord-6.0.2.1/lib/active_record/base.rb:327:in `<module:ActiveRecord>'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activerecord-6.0.2.1/lib/active_record/base.rb:27:in `<main>'
/Users/myuser/Projects/myapp/vendor/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/myuser/Projects/myapp/vendor/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/myuser/Projects/myapp/vendor/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/myuser/Projects/myapp/vendor/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/myuser/Projects/myapp/vendor/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/myuser/Projects/myapp/vendor/bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activerecord-6.0.2.1/lib/active_record/query_cache.rb:31:in `run'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/execution_wrapper.rb:28:in `before'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:429:in `block in make_lambda'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:606:in `catch'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:606:in `block in default_terminator'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:202:in `block in halting'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:514:in `block in invoke_before'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:514:in `each'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:514:in `invoke_before'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:134:in `run_callbacks'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/execution_wrapper.rb:111:in `run!'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/execution_wrapper.rb:73:in `block in run!'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/execution_wrapper.rb:70:in `tap'
/Users/myuser/Projects/myapp/vendor/bundle/gems/activesupport-6.0.2.1/lib/active_support/execution_wrapper.rb:70:in `run!'
/Users/myuser/Projects/myapp/vendor/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/myuser/Projects/myapp/vendor/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:126:in `call'
/Users/myuser/Projects/myapp/vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
/Users/myuser/Projects/myapp/vendor/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
/Users/myuser/Projects/myapp/vendor/bundle/gems/webpacker-4.2.2/lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
/Users/myuser/Projects/myapp/vendor/bundle/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
/Users/myuser/Projects/myapp/vendor/bundle/gems/railties-6.0.2.1/lib/rails/engine.rb:526:in `call'
/Users/myuser/Projects/myapp/vendor/bundle/gems/puma-4.3.3/lib/puma/configuration.rb:228:in `call'
/Users/myuser/Projects/myapp/vendor/bundle/gems/puma-4.3.3/lib/puma/server.rb:682:in `handle_request'
/Users/myuser/Projects/myapp/vendor/bundle/gems/puma-4.3.3/lib/puma/server.rb:472:in `process_client'
/Users/myuser/Projects/myapp/vendor/bundle/gems/puma-4.3.3/lib/puma/server.rb:328:in `block in run'
/Users/myuser/Projects/myapp/vendor/bundle/gems/puma-4.3.3/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for ::1 at 2020-03-04 15:29:19 -0500
```

If I install the pg gem `gem install pg`, I get a different error:

```console
ActiveRecord::ConnectionNotEstablished (No connection pool with 'primary' found.):
  
activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:1117:in `retrieve_connection'
activerecord (6.0.2.1) lib/active_record/connection_handling.rb:238:in `retrieve_connection'
activerecord (6.0.2.1) lib/active_record/connection_handling.rb:206:in `connection'
activerecord (6.0.2.1) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
webpacker (4.2.2) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.2.1) lib/rails/engine.rb:526:in `call'
puma (4.3.3) lib/puma/configuration.rb:228:in `call'
puma (4.3.3) lib/puma/server.rb:682:in `handle_request'
puma (4.3.3) lib/puma/server.rb:472:in `process_client'
puma (4.3.3) lib/puma/server.rb:328:in `block in run'
puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

### Expected behavior

The expected behavior is that the app should not be looking for Postgres and it should render

### Actual behavior

The app errors out looking for Postgres.

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]

**Comment by rafaelfranca** [comment]
I just tried your reproduction steps and I got no error. Are you sure you `config/database.yml` is correct and is not using `pg` gem?

**Comment by rafaelfranca** [comment]
```
[2.7.0 myapp (master #)]$ bin/rails s
=> Booting Puma
=> Rails 6.0.2.1 application starting in development
=> Run `rails server --help` for more startup options
/Users/rafaelfranca/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/rafaelfranca/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
Puma starting in single mode...
* Version 4.3.3 (ruby 2.7.0-p0), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://127.0.0.1:3000
* Listening on tcp://[::1]:3000
* Listening on tcp://127.0.0.42:3000
Use Ctrl-C to stop
Started GET "/" for ::1 at 2020-03-04 16:19:52 -0500
   (3.3ms)  SELECT sqlite_version(*)
Processing by Rails::WelcomeController#index as HTML
/Users/rafaelfranca/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/messages/rotator.rb:28: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/rafaelfranca/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/messages/rotator.rb:6: warning: The called method `initialize' is defined here
/Users/rafaelfranca/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionview-6.0.2.1/lib/action_view/view_paths.rb:11: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/rafaelfranca/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionview-6.0.2.1/lib/action_view/lookup_context.rb:140: warning: The called method `template_exists?' is defined here
/Users/rafaelfranca/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionview-6.0.2.1/lib/action_view/unbound_template.rb:24: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/rafaelfranca/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionview-6.0.2.1/lib/action_view/template.rb:130: warning: The called method `initialize' is defined here
  Rendering /Users/rafaelfranca/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /Users/rafaelfranca/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/templates/rails/welcome/index.html.erb (Duration: 17.2ms | Allocations: 409)
Completed 200 OK in 35ms (Views: 25.5ms | ActiveRecord: 0.0ms | Allocations: 2415)
```

**Comment by ejstembler** [comment]
I'm using the unchanged database.yml:

```yaml
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
```

I'm on macOS Catalina 10.15.3 (19D76)
zsh
rbenv 1.1.2

Is there anything else I can check?  I could record an [asciinema](https://asciinema.org) video if that helps...

**Comment by rafaelfranca** [comment]
What does `echo $DATABASE_URL` returns?

**Comment by ejstembler** [comment]
Oh!  I don't have to look, I already know, I'm using that environment variable for another Crystal/Heroku project.  I didn't realize Rails looks for that.
