### ISSUE TITLE
can't run with production env

### ISSUE THREAD

**Issue by yishuiliunian** [rails/rails#38681]
### Steps to reproduce

```
step0 : rails new lark_pipeline --skip-action-mailer --skip-action-mailbox
step1: run the app with production env in RubyMine
```
### Expected behavior

run the app 
### Actual behavior

crashed and outpu:
```
/bin/zsh -c "bash -c 'env RBENV_VERSION=2.6.4 /usr/local/Cellar/rbenv/1.1.2/libexec/rbenv exec ruby /Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/ruby-debug-ide-0.8.0.beta8/bin/rdebug-ide --key-value --step-over-in-blocks --disable-int-handler --evaluation-timeout 10 --evaluation-control --time-limit 100 --memory-limit 0 --rubymine-protocol-extensions --port 49676 --host 0.0.0.0 --dispatcher-port 49677 -- /Volumes/PSSD/Bytedance/tools/pipeline/lark_pipeline/bin/rails server -b 0.0.0.0 -p 3000 -e production'"
Fast Debugger (ruby-debug-ide 0.8.0.beta8, debase 0.3.0.beta8, file filtering is supported, block breakpoints supported, smart steps supported, obtaining return values supported) listens on 0.0.0.0:49676
=> Booting Puma
=> Rails 6.0.2.1 application starting in production 
=> Run `rails server --help` for more startup options
Exiting
Uncaught exception: uninitialized constant #<Class:0x00007fa4c6a93ba8>::Analyzable
Did you mean?  ActiveStorage::Analyzer
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activestorage-6.0.2.1/app/models/active_storage/blob.rb:26:in `<class:Blob>'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activestorage-6.0.2.1/app/models/active_storage/blob.rb:19:in `<main>'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:381:in `const_get'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:381:in `block (2 levels) in eager_load'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:723:in `block in ls'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:720:in `foreach'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:720:in `ls'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:376:in `block in eager_load'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:368:in `synchronize'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:368:in `eager_load'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:483:in `each'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:483:in `eager_load_all'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `each'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `call'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
	/Volumes/PSSD/Bytedance/tools/pipeline/lark_pipeline/config/environment.rb:5:in `<main>'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:49:in `require_relative'
	config.ru:3:in `block in <main>'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:249:in `app'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:422:in `wrapped_app'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:312:in `block in start'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:379:in `handle_profiling'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:311:in `start'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:39:in `start'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	/Volumes/PSSD/Bytedance/tools/pipeline/lark_pipeline/bin/rails:9:in `<top (required)>'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/Users/dongzhao/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/Volumes/PSSD/Bytedance/tools/pipeline/lark_pipeline/bin/spring:15:in `<top (required)>'
	/Volumes/PSSD/Bytedance/tools/pipeline/lark_pipeline/bin/rails:3:in `load'
	/Volumes/PSSD/Bytedance/tools/pipeline/lark_pipeline/bin/rails:3:in `<top (required)>'

Process finished with exit code 0

```
### System configuration
**Rails version**:
6.0.2.1
**Ruby version**:
2.6.4

**Comment by dixpac** [comment]
I followed steps you've written and everything works fine on my machine:

Rails version:
6.0.2.1
Ruby version:
2.6.4
OSX 10.14

**Comment by alxx** [comment]
I have the same problem. Rails 6.0.2.2, ruby 2.6.0, OSX 10.15.

For example, in storage.yml:

```
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
```

My model:

```
class Product < ApplicationRecord
  has_one_attached :image
end
```

Then from the console:

```
Product.last.image.attach(io: File.open('/Users/xxxxxx/DSC_0267.jpg'), filename: 'tree.jpg')
```

causes:

```
NameError (uninitialized constant #<Class:0x00007faa9ec12398>::Analyzable)
```

My storage.yml is parseable:

```
YAML.load(ERB.new(File.read("#{Rails.root}/config/storage.yml")).result)
=> {"test"=>{"service"=>"Disk", "root"=>"/Users/xxxxxxx/tmp/storage"}}
```

I've temporarily set my development environment to use the test service:

```
Rails.application.config.active_storage.service
=> :test
```

Any help would be appreciated.

**Comment by mashedkeyboard** [comment]
I'm having this same issue with completely default ActiveStorage settings after upgrading from Rails 5 to Rails 6 - has anyone managed to solve it?

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by mashedkeyboard** [comment]
Thanks for the quick reply @rafaelfranca - I've created a minimum reproducible example repo, which I've put here: https://github.com/mashedkeyboard/activestorage-done-brokey

**Comment by dixpac** [comment]
If it helps I wasn't able to reproduce the issue using your repo @mashedkeyboard. Works for me.

**Comment by mashedkeyboard** [comment]
Hrm, that's strange - thanks @dixpac, that is useful. What OS are you using? Maybe this is a system-specific issue - I'm using Manjaro Linux.

**Comment by dixpac** [comment]
macOS 10.14.6. Also, I tried to reproduce this on different ruby versions `2.5.3, 2.6.0 and 2.6.2`.

**Comment by ReekenX** [comment]
Running into the same issue:

```
NameError: uninitialized constant #<Class:0x000056323caee7b8>::Analyzable
from /gems-cache/ruby/2.7.0/gems/activestorage-6.0.3/app/models/active_storage/blob.rb:26:in `<class:Blob>'
```

Same with Rails `6.0.2` and `6.0.3`. Also on Macos.

My app is just default `rails new --api` without configs changed yet.

Strange, but given repo works for me just fine: https://github.com/mashedkeyboard/activestorage-done-brokey. The only bigger difference I see is ours Gemfile only (can't find anything special about it).

**Comment by mashedkeyboard** [comment]
That's even stranger @ReekenX. Could you upload your `rails new --api` somewhere? I know it should be the same, but I'm now wondering given that my repo works for you, whether your repo would work for me.

**Comment by mashedkeyboard** [comment]
Hi, please can someone reopen this issue? The original author may not have provided the requested information, but I have, and it's clear that there is some sort of issue here, as it's been reported by multiple individuals across different platforms.

**Comment by hugoh59** [comment]
Same issue here

**Comment by gkpacker** [comment]
Same issue here. 

```rb
ActiveStorage::Blob::Analyzable
ActiveStorage::Blob::Identifiable
ActiveStorage::Blob::Representable
```
Are not loaded even with `Rails.autoloaders.zeitwerk_enabled? == true`

removing `unless Rails.autoloaders.zeitwerk_enabled?` condition from `/Users/gkpacker/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activestorage-6.0.3.2/app/models/active_storage/blob.rb`, made it work:
```rb
  unless Rails.autoloaders.zeitwerk_enabled?
    require_dependency "active_storage/blob/analyzable"
    require_dependency "active_storage/blob/identifiable"
    require_dependency "active_storage/blob/representable"
  end
```
Maybe a [zeitwerk](https://github.com/fxn/zeitwerk) bug?

@yishuiliunian @rafaelfranca any thoughts?

**Comment by gkpacker** [comment]
@hugoh59 @mashedkeyboard 
I'm not having this issue anymore, but idk exactly what did the trick, so here is what I've done so far:

`brew upgrade imagemagick` - had a problem with openssl, followed [this](https://stackoverflow.com/questions/59006602/dyld-library-not-loaded-usr-local-opt-openssl-lib-libssl-1-0-0-dylib) stackoverflow answer

Updated rails to the latest version: `gem 'rails', '~> 6.0.3'` in my gemfile

My ruby version: 2.6.5

Now I'm getting another error:
```
undefined method `identify' for #<ActiveStorage::Blob:0x00007f863e940428>
```
I'll investigate later

**Comment by misteral** [comment]
Same issue:
Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin18]

```
[2] pry> model = create(:store_import)
=> #<StoreImport:0x00007ff17be3dba8 id: 2, desc: "MyString", kind: nil, created_at: Fri, 19 Jun 2020 02:00:52 UTC +00:00, updated_at: Fri, 19 Jun 2020 02:00:52 UTC +00:00>
[3] pry> model.import_file.attach(io: File.open(file_name),
[3] pry> *   filename: 'users.xlsx',
[3] pry>* content_type: 'application/xlsx')
NameError: uninitialized constant #<Class:0x00007ff17bce6778>::Analyzable
from /Users/aleksandrbobrov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activestorage-6.0.3.2/app/models/active_storage/blob.rb:26:in `<class:Blob>'
```

**Comment by gkpacker** [comment]
Sorry, I still have the issue. 🤦 

I'm getting
```
undefined method 'identify' for #<ActiveStorage::Blob:0x00007f863e940428>
```
because `ActiveStorage::Blob::Identifiable` isn't included

**Comment by gkpacker** [comment]
If it helps, it works when running all specs:
<img width="1271" alt="Screen Shot 2020-06-21 at 15 34 40" src="https://user-images.githubusercontent.com/35704671/85232383-df5bde80-b3d4-11ea-8e82-8e84c87dd5cf.png">

But it fails when running specific examples:
<img width="1267" alt="Screen Shot 2020-06-21 at 15 35 15" src="https://user-images.githubusercontent.com/35704671/85232385-e1be3880-b3d4-11ea-8a36-a61d8c031478.png">

**Comment by light94** [comment]
I am also facing the same issue on **Rails: 6.0.3.2** **Ruby 2.6.6**
I do see a related commit in master https://github.com/rails/rails/commit/c7c3abe03b8e2848990bdb83831e4e30cbd97d02#diff-123aa7e5579a68c3dc535779855c51e1 related to workaround suggested by @gkpacker . However, the exact diff does not work for me, I need to do both `require_dependency` as well as `include ActiveStorage::Blob::Analyzable` . I tried reverting back to the `classic` autoloading mode, but got the same error.

**Comment by ivantoniev** [comment]
Experiencing the same error. I got it when attaching an image to a model that I was setting up for a spec. Running on `rails 6.0.3.2` and `ruby 2.7.1p83`. My system is on an OSX 10.15.5

in `storage.yml`
```
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
```

model:
```ruby
class Listing < ApplicationRecord
  has_one_attached :primary_image
  has_many_attached :secondary_images
end
```

in the spec I am doing:
```ruby
listing.primary_image.attach(
  io: File.open(Rails.root.join("spec/assets/images/truck.jpeg")),
  filename: "truck.jpeg",
  content_type: "image/jpeg"
)
```

**Comment by Andrew-Max** [comment]
Hey @rafaelfranca  as @mashedkeyboard mentioned is there anyway this could be reopened? This is just totally broken for me with a pretty generic setup.

**Comment by Andrew-Max** [comment]
for now I'm going to just use the deprecated paperclip  gem to get around this but definitely feels weird that this major component of core just won't work for an up to date version.

**Comment by marcelmongs** [comment]
Try to Include

_config/application.rb_
`config.autoloader = :classic`

**Comment by tomily1** [comment]
Is there any reason why Active Storage is still using ActiveRecord::Migration for rails version 5.2?

`class CreateActiveStorageTables < ActiveRecord::Migration[5.2]`

https://github.com/mashedkeyboard/activestorage-done-brokey/blob/8a0d58f15f17b7be3914862a5df0bb7f8ee383ff/db/migrate/20200501183915_create_active_storage_tables.active_storage.rb#L2

**Comment by azdrenymeri** [comment]
I had the same issue in development mode. 
I solved it by opting out from Zeitwek Mode and using the classic mode instead.
[Autoloading and Reloading Constants (Zeitwerk Mode)](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html)
```bash
Rails version             6.0.3.3
Ruby version              ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
RubyGems version          3.1.4
Rack version              2.2.3

```
`/config/environments/development.rb`
```ruby
config.autoloader = :classic
```

**Comment by mildavw** [comment]
FWIW I was seeing this in the test environment only. Upgrading zeitwerk from 2.3.0 to 2.4.1 (by upgrading Rails from 6.0.2.1 to 6.0.3.4) fixed it.

**Comment by eveevans** [comment]
Same problem using Active Storage on Rails 6.1.
`config.autoloader = :classic` solves the problem

**Comment by mbronek7** [comment]
Same problem on Rails 6.1.1, Ruby 3, also 
```ruby
config.autoloader = :classic
```
solved problem

**Comment by thermistor** [comment]
I encountered a similar error intermittently when using `binding.pry` in a spec while using `guard`. 

Error I get:
`NameError: uninitialized constant #<Class:0x00000001225bd010>::Analyzable
from /Users/weston/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activestorage-6.1.4.1/app/models/active_storage/blob.rb:33:in '<class:Blob>'`

I work around it with this in an initializer:
```
Rails.application.reloader.to_prepare do
  ActiveStorage::Blob
end
```

**Comment by fuse** [comment]
I had the same problem in test mode, using spring. I had to turn on eager loading to make it works.

`config.eager_load = true`
