### ISSUE TITLE
"rails new app" failed

### ISSUE THREAD

**Issue by tokenarky** [rails/rails#38835]
Hi, I installed Ruby and Rails through the rbenv, but execute  `rails new demoApp` failed.

### Steps to reproduce
`rails new demoApp`

### Expected behavior
success

### Actual behavior

```
Traceback (most recent call last):
        29: from /root/.rbenv/versions/2.8.0-dev/bin/rails:23:in `<main>'
        28: from /root/.rbenv/versions/2.8.0-dev/bin/rails:23:in `load'
        27: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/railties-6.0.2.2/exe/rails:10:in `<top (required)>'
        26: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/2.8.0/rubygems/core_ext/kernel_require.rb:74:in `require'
        25: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/2.8.0/rubygems/core_ext/kernel_require.rb:74:in `require'
        24: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/railties-6.0.2.2/lib/rails/cli.rb:18:in `<top (required)>'
        23: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/railties-6.0.2.2/lib/rails/command.rb:46:in `invoke'
        22: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/railties-6.0.2.2/lib/rails/command/base.rb:69:in `perform'
        21: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        20: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        19: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        18: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/railties-6.0.2.2/lib/rails/commands/application/application_command.rb:26:in `perform'
        17: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        16: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
        15: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
        14: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
        13: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
        12: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
        11: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        10: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
         9: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/railties-6.0.2.2/lib/rails/generators/rails/app/app_generator.rb:332:in `create_credentials'
         8: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/railties-6.0.2.2/lib/rails/generators/app_base.rb:156:in `build'
         7: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/railties-6.0.2.2/lib/rails/generators/rails/app/app_generator.rb:177:in `credentials'
         6: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/railties-6.0.2.2/lib/rails/generators/rails/credentials/credentials_generator.rb:31:in `add_credentials_file_silently'
         5: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/activesupport-6.0.2.2/lib/active_support/encrypted_configuration.rb:29:in `write'
         4: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/activesupport-6.0.2.2/lib/active_support/encrypted_file.rb:50:in `write'
         3: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/activesupport-6.0.2.2/lib/active_support/encrypted_file.rb:76:in `encrypt'
         2: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/activesupport-6.0.2.2/lib/active_support/message_encryptor.rb:151:in `encrypt_and_sign'
         1: from /root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/activesupport-6.0.2.2/lib/active_support/message_encryptor.rb:175:in `_encrypt'
/root/.rbenv/versions/2.8.0-dev/lib/ruby/gems/2.8.0/gems/activesupport-6.0.2.2/lib/active_support/messages/metadata.rb:17:in `wrap': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

### System configuration
**Rails version**: Rails 6.0.2.2

**Ruby version**: ruby 2.8.0dev (2020-03-27T10:04:03Z master 3486a460ea) [x86_64-linux]

**OS**: CentOS 7

**Comment by eugeneius** [comment]
This was fixed in https://github.com/rails/rails/commit/87b428c8e0b9cb38ba87dd71e4e14fc755de6345 which hasn't made it into a release yet. Rails doesn't aim to stay compatible with Ruby's master branch, so I'm going to close this.

I'd recommend using Ruby 2.6.5 if you just want your app to work, but if you really want to use an in-development version of Ruby, you can try doing the same for Rails:

```bash
# Clone the repo and run:
railties/exec/rails new --edge demoApp
```
