### ISSUE TITLE
Upgrade 5.2 to 6.0.2.2 failed with `credentials_available_for_current_en

### ISSUE THREAD

**Issue by thebravoman** [rails/rails#39017]
### Steps to reproduce
Upgrading an app from rails 5.2 to rails 6. Sorry, not open source and can not share the code.

### Expected behavior
1. Follow the upgrade guide at https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html, 
2. rails s

### Actual behavior
1. Followed the guide
2. rails s
```
$ rails s
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.6-compliant syntax, but you are running 2.6.5.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Traceback (most recent call last):
  33: from bin/rails:3:in `<main>'
  32: from bin/rails:3:in `load'
  31: from /home/userproject/bin/spring:15:in `<top (required)>'
  30: from /home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  29: from /home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  28: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
  27: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
  26: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
  25: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
  24: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
  23: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
  22: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
  21: from /home/userproject/bin/rails:9:in `<top (required)>'
  20: from /home/userproject/bin/rails:9:in `require'
  19: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<top (required)>'
  18: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/command.rb:46:in `invoke'
  17: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/command/base.rb:69:in `perform'
  16: from /home/user/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  15: from /home/user/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  14: from /home/user/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  13: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:138:in `perform'
  12: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:138:in `tap'
  11: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:141:in `block in perform'
  10: from /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
   9: from /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
   8: from /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
   7: from /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
   6: from /home/userproject/config/application.rb:18:in `<top (required)>'
   5: from /home/userproject/config/application.rb:19:in `<module:Module>'
   4: from /home/userproject/config/application.rb:28:in `<class:Application>'
   3: from /home/userproject/config/application.rb:28:in `new'
   2: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/application/configuration.rb:67:in `initialize'
   1: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/application/configuration.rb:351:in `default_credentials_content_path'
/home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/application/configuration.rb:367:in `credentials_available_for_current_env?': undefined method `join' for nil:NilClass (NoMethodError)

```
### System configuration
**Rails version**:
6.0.2.2

**Ruby version**:
2.6.5

**Comment by thebravoman** [comment]
```
$ rails credentials:edit --environment development
```
is not fixing it.

**Comment by eileencodes** [comment]
Are you using a special gem for your configuration? I've never seen `config.is = Rails::Application::Configuration.new` before and it's not common to set in your Rails application.

**Comment by thebravoman** [comment]
No. Nothing special.
