### ISSUE TITLE
validates_uniqueness_of is broken with Rails 5, JRuby 9.2 and postgresql

### ISSUE THREAD

**Issue by haohaolee** [rails/rails#39058]
### Context
Recently we tried to upgrade our rails app from 4.2 to 5.0, but failed with this issue. We are using jruby 9.2, which is compatible with MRI 2.5.
I created a simple test file to reproduce this issue.

https://gist.github.com/haohaolee/b0ebc426502dcbf0b6b35f53537581d8 

### Steps to reproduce

```
$ ruby -v
jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 25.242-b08 on 1.8.0_242-b08 +jit [darwin-x86_64]
$# make sure there is a postgresql db running

$ ruby active_record_gem.rb                                                                                      <<<
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies.........
Using concurrent-ruby 1.1.6
Using i18n 1.8.2
Using minitest 5.14.0
Using thread_safe 0.3.6 (java)
Using tzinfo 1.2.7
Using activesupport 5.0.7.2
Using activemodel 5.0.7.2
Using arel 7.1.4
Using activerecord 5.0.7.2
Using activerecord-jdbc-adapter 50.6 (java)
Using jdbc-postgres 42.2.6
Using activerecord-jdbcpostgresql-adapter 50.6 (java)
Using bundler 2.1.4
-- create_table(:posts, {:force=>true})
D, [2020-04-27T01:56:16.718157 #73531] DEBUG -- :    (5.2ms)  DROP TABLE "posts"
D, [2020-04-27T01:56:16.727887 #73531] DEBUG -- :    (7.2ms)  CREATE TABLE "posts" ("id" serial primary key, "post_date" date)
   -> 0.2751s
   -> 0 rows
D, [2020-04-27T01:56:16.818644 #73531] DEBUG -- :   ActiveRecord::InternalMetadata Load (20.3ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", :environment], ["LIMIT", 1]]
D, [2020-04-27T01:56:16.848489 #73531] DEBUG -- :    (0.9ms)  BEGIN TRANSACTION
D, [2020-04-27T01:56:16.855852 #73531] DEBUG -- :    (0.2ms)  COMMIT TRANSACTION
Run options: --seed 1544

# Running:

D, [2020-04-27T01:56:16.928453 #73531] DEBUG -- :    (0.1ms)  BEGIN TRANSACTION
D, [2020-04-27T01:56:16.965431 #73531] DEBUG -- :   Post Exists (15.0ms)  SELECT  1 AS one FROM "posts" WHERE "posts"."post_date" = ? LIMIT ?  [["post_date", "2001-01-01"], ["LIMIT", 1]]
D, [2020-04-27T01:56:16.972472 #73531] DEBUG -- :    (3.9ms)  ROLLBACK TRANSACTION
E

Finished in 0.086486s, 11.5626 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_association_stuff:
ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: operator does not exist: date = character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 57: SELECT  1 AS one FROM "posts" WHERE "posts"."post_date" = ? LIMIT ?
    arjdbc/jdbc/RubyJdbcConnection.java:1209:in `execute_prepared_query'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-50.6-java/lib/arjdbc/abstract/database_statements.rb:35:in `block in exec_query'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-5.0.7.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-50.6-java/lib/arjdbc/abstract/core.rb:70:in `log'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-jdbc-adapter-50.6-java/lib/arjdbc/abstract/database_statements.rb:32:in `exec_query'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:69:in `select_rows'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:54:in `select_value'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/relation/finder_methods.rb:335:in `exists?'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/validations/uniqueness.rb:29:in `validate_each'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activemodel-5.0.7.2/lib/active_model/validator.rb:151:in `block in validate'
    org/jruby/RubyArray.java:1809:in `each'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activemodel-5.0.7.2/lib/active_model/validator.rb:148:in `validate'
    org/jruby/RubyKernel.java:1960:in `public_send'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:405:in `block in make_lambda'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:169:in `block in halting'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:547:in `block in default_terminator'
    org/jruby/RubyKernel.java:1189:in `catch'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:546:in `block in default_terminator'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:170:in `block in halting'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:454:in `block in call'
    org/jruby/RubyArray.java:1809:in `each'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupenesport-5.0.7.2/lib/active_support/callbacks.rb:454:in `call'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:750:in `_run_validate_callbacks'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activemodel-5.0.7.2/lib/active_model/validations.rb:408:in `run_validations!'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activemodel-5.0.7.2/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:750:in `_run_validation_callbacks'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activemodel-5.0.7.2/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activemodel-5.0.7.2/lib/active_model/validations.rb:338:in `valid?'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/validations.rb:65:in `valid?'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/validations.rb:82:in `perform_validations'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/validations.rb:50:in `save!'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:324:in `block in save!'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:211:in `transaction'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:324:in `save!'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/suppressor.rb:45:in `save!'
    /Users/xxx/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-5.0.7.2/lib/active_record/persistence.rb:51:in `create!'
    active_record_gem.rb:42:in `test_association_stuff'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

### Expected behavior
This test should run

### Actual behavior
There is an exception about postgresql and JDBC

### System configuration
**Rails version**:
5.0.7.2
**Ruby version**:
jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 25.242-b08 on 1.8.0_242-b08 +jit [darwin-x86_64]

**Comment by haohaolee** [comment]
This issue does not exist in Rails 5.1 btw

**Comment by eugeneius** [comment]
Thanks for the report. Rails 5.0 is no longer supported, so if this works in 5.1 there's nothing else we can do about it.

**Comment by headius** [comment]
@haohaolee If you believe this is a bug specific to JRuby, you may be able to get a response at https://github.com/jruby/activerecord-jdbc-adapter. We continue to maintain support for the 5.0 on a limited basis.

I would of course recommend upgrading, though.

**Comment by haohaolee** [comment]
> @haohaolee If you believe this is a bug specific to JRuby, you may be able to get a response at https://github.com/jruby/activerecord-jdbc-adapter. We continue to maintain support for the 5.0 version of the adapter on a limited basis.
> 
> I would of course recommend upgrading, though.

This issue is a combination of Rails 5.0 and JRuby&activerecord-jdbc-adapter, because it doesn't show up in Rails 5.1 nor Rails 5.0 with Sqlite. So it must has something to do with activerecord-jdbc-adapter especially jdbcpostgresql-adapter. But I am not really sure that which part should be in charge of this. :D

We do want to upgrade to a newer Rails, but you know upgrading rails is an Odyssey. Our strategy is to upgrade one major version a time, with all tests fixed, then the next major version. This issue seems prevent us from doing this.

Thanks anyway
