### ISSUE TITLE
DATABASE_URL is not being take into account for test database creation

### ISSUE THREAD

**Issue by lfv89** [rails/rails#39222]
### Steps to reproduce

0) Ensure that you does not have any database running on your host

1) Configure `DATABASE_URL` to point to a up and running database instance running on another host, which in development is almost always on the same machine (containers!)

2) Run `bin/rake db:reset` on your machine, ensuring that `RAILS_ENV` is `development`

### Expected behavior
The databases for the `development` and `test` are created 

### Actual behavior

The `development` database is created, but the `test` is not

```
Dropped database 'myapp_development'
Database 'myapp_test' does not exist
Created database 'myapp_development'
could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Couldn't create 'myapp_test' database. Please check your configuration.
rake aborted!
ActiveRecord::NoDatabaseError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_handling.rb:189:in `connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/postgresql_database_tasks.rb:13:in `connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/postgresql_database_tasks.rb:22:in `create'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:122:in `create'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:179:in `block in create_current'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:472:in `block (2 levels) in each_current_configuration'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:469:in `each'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:469:in `block in each_current_configuration'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:468:in `each'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:468:in `each_current_configuration'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:178:in `create_current'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'

Caused by:
PG::ConnectionBad: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/home/me/Projects/apps/app1/.gems/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/home/me/Projects/apps/app1/.gems/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/home/me/Projects/apps/app1/.gems/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/connection_handling.rb:189:in `connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/postgresql_database_tasks.rb:13:in `connection'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/postgresql_database_tasks.rb:22:in `create'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:122:in `create'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:179:in `block in create_current'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:472:in `block (2 levels) in each_current_configuration'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:469:in `each'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:469:in `block in each_current_configuration'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:468:in `each'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:468:in `each_current_configuration'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/tasks/database_tasks.rb:178:in `create_current'
/home/me/Projects/apps/app1/.gems/gems/activerecord-6.0.3/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
Tasks: TOP => db:reset => db:setup => db:schema:load_if_ruby => db:create
(See full trace by running task with --trace)
```

### System configuration
**Rails version**: 6.0.3

**Ruby version**: 2.6.0p0

**Comment by eugeneius** [comment]
See https://github.com/rails/rails/pull/39223#issuecomment-626405581.
