### ISSUE TITLE
Rails application gets unresponsive when S3 server malfunctions and timeouts (ActiveStorage)

### ISSUE THREAD

**Issue by vizcay** [rails/rails#39327]
### Steps to reproduce
1. Create a standard Rails app that uses ActiveStorage connected to a S3 provider.
2. The S3 server stops responding (in this case Linode has an emergency network maintenance) but not refusing the connection, basically connections start to timeout on read.
3. All my puma workers and threads get filled and are all waiting for the S3 server to respond.
4. The reverse proxy HTTP queque gets full and 502 Bad Gateway starts to happen; application is totally unresponsive.

### Expected behavior
The availability of the S3 server should't affect the main Rails application by design, only the attachments. Sensible defaults for timeouts should be provided.

### Actual behavior
The malfunction of the S3 server (were only images were stored) made my Rails application completely unavailable.

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

Rails needed 242768ms to timeout, here is the complete request log example:

```
I, [2020-05-18T02:22:54.763454 #1733]  INFO -- : [e06b1557-ba28-47d8-93af-3665437ab01c] Started GET "/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fbcc609f29856787b92793a874e0809d70bf11a9/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9VY21WemFYcGxYM1J2WDJ4cGJXbDBXd2RwWldsbCIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--d87e4e37ba061908f6914b120615a0f5a564637c/salmon.jpg" for 201.179.2.226 at 2020-05-18 02:22:54 -0300
I, [2020-05-18T02:22:54.764526 #1733]  INFO -- : [e06b1557-ba28-47d8-93af-3665437ab01c] Processing by ActiveStorage::RepresentationsController#show as JPEG
I, [2020-05-18T02:22:54.764628 #1733]  INFO -- : [e06b1557-ba28-47d8-93af-3665437ab01c]   Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fbcc609f29856787b92793a874e0809d70bf11a9", "variation_key"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9VY21WemFYcGxYM1J2WDJ4cGJXbDBXd2RwWldsbCIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--d87e4e37ba061908f6914b120615a0f5a564637c", "filename"=>"salmon"}
D, [2020-05-18T02:22:54.766083 #1733] DEBUG -- : [e06b1557-ba28-47d8-93af-3665437ab01c]   [1m[36mActiveStorage::Blob Load (0.2ms)[0m  [1m[34mSELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2[0m  [["id", 18], ["LIMIT", 1]]
D, [2020-05-18T02:26:57.531981 #1733] DEBUG -- : [e06b1557-ba28-47d8-93af-3665437ab01c] [36m  S3 Storage (242765.2ms) [0m[34mChecked if file exists at key: variants/2e2encf85h8jr31himaehq2soy90/966eb7d4bb99976f8a044d5684493947bc5278b0d26fc7c1e796c78263152c8f (no)[0m
I, [2020-05-18T02:26:57.532295 #1733]  INFO -- : [e06b1557-ba28-47d8-93af-3665437ab01c] Completed 500 Internal Server Error in 242768ms (ActiveRecord: 0.2ms | Allocations: 42144)
F, [2020-05-18T02:26:57.709081 #1733] FATAL -- : [e06b1557-ba28-47d8-93af-3665437ab01c]   
[e06b1557-ba28-47d8-93af-3665437ab01c] Seahorse::Client::NetworkingError (Net::ReadTimeout with #<TCPSocket:(closed)>):
[e06b1557-ba28-47d8-93af-3665437ab01c]   
[e06b1557-ba28-47d8-93af-3665437ab01c] /home/deploy/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill'
[e06b1557-ba28-47d8-93af-3665437ab01c] /home/deploy/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
[e06b1557-ba28-47d8-93af-3665437ab01c] /home/deploy/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
[e06b1557-ba28-47d8-93af-3665437ab01c] /home/deploy/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
[e06b1557-ba28-47d8-93af-3665437ab01c] /home/deploy/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
[e06b1557-ba28-47d8-93af-3665437ab01c] /home/deploy/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
[e06b1557-ba28-47d8-93af-3665437ab01c] /home/deploy/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
[e06b1557-ba28-47d8-93af-3665437ab01c] /home/deploy/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
[e06b1557-ba28-47d8-93af-3665437ab01c] /home/deploy/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:1479:in `request'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/seahorse/client/net_http/connection_pool.rb:340:in `request'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/seahorse/client/net_http/handler.rb:74:in `block in transmit'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/seahorse/client/net_http/handler.rb:126:in `block in session'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/seahorse/client/net_http/connection_pool.rb:101:in `session_for'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/seahorse/client/net_http/handler.rb:121:in `session'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/seahorse/client/net_http/handler.rb:73:in `transmit'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/seahorse/client/net_http/handler.rb:47:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/seahorse/client/plugins/content_length.rb:15:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/s3_signer.rb:103:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/s3_signer.rb:57:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/s3_host_id.rb:15:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/transfer_encoding.rb:24:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/s3_signer.rb:83:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/redirects.rb:18:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/retry_errors.rb:350:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/retry_errors.rb:384:in `retry_request'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/retry_errors.rb:372:in `retry_if_possible'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/retry_errors.rb:361:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/retry_errors.rb:384:in `retry_request'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/retry_errors.rb:372:in `retry_if_possible'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/retry_errors.rb:361:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/retry_errors.rb:384:in `retry_request'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/retry_errors.rb:372:in `retry_if_possible'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/retry_errors.rb:361:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/dualstack.rb:34:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/accelerate.rb:50:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/md5s.rb:32:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/bucket_name_restrictions.rb:24:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/bucket_dns.rb:33:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/bucket_arn.rb:47:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/rest/handler.rb:8:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/user_agent.rb:11:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/seahorse/client/plugins/endpoint.rb:45:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/seahorse/client/plugins/response_target.rb:23:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/seahorse/client/request.rb:70:in `send_request'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/waiters/poller.rb:63:in `send_request'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/waiters/poller.rb:49:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/waiters/waiter.rb:105:in `block in poll'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/waiters/waiter.rb:102:in `loop'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/waiters/waiter.rb:102:in `poll'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/waiters/waiter.rb:92:in `block (2 levels) in wait'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/waiters/waiter.rb:91:in `catch'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/waiters/waiter.rb:91:in `block in wait'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/waiters/waiter.rb:90:in `catch'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-core (3.92.0) lib/aws-sdk-core/waiters/waiter.rb:90:in `wait'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/waiters.rb:198:in `wait'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/object.rb:377:in `wait_until_exists'
[e06b1557-ba28-47d8-93af-3665437ab01c] aws-sdk-s3 (1.61.2) lib/aws-sdk-s3/object.rb:358:in `exists?'
[e06b1557-ba28-47d8-93af-3665437ab01c] activestorage (6.0.2.2) lib/active_storage/service/s3_service.rb:63:in `block in exist?'
[e06b1557-ba28-47d8-93af-3665437ab01c] activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `block in instrument'
[e06b1557-ba28-47d8-93af-3665437ab01c] activesupport (6.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[e06b1557-ba28-47d8-93af-3665437ab01c] activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `instrument'
[e06b1557-ba28-47d8-93af-3665437ab01c] activestorage (6.0.2.2) lib/active_storage/service.rb:126:in `instrument'
[e06b1557-ba28-47d8-93af-3665437ab01c] activestorage (6.0.2.2) lib/active_storage/service/s3_service.rb:62:in `exist?'
[e06b1557-ba28-47d8-93af-3665437ab01c] activestorage (6.0.2.2) app/models/active_storage/variant.rb:95:in `processed?'
[e06b1557-ba28-47d8-93af-3665437ab01c] activestorage (6.0.2.2) app/models/active_storage/variant.rb:67:in `processed'
[e06b1557-ba28-47d8-93af-3665437ab01c] activestorage (6.0.2.2) app/controllers/active_storage/representations_controller.rb:12:in `show'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/abstract_controller/base.rb:196:in `process_action'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[e06b1557-ba28-47d8-93af-3665437ab01c] activesupport (6.0.2.2) lib/active_support/callbacks.rb:135:in `run_callbacks'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
[e06b1557-ba28-47d8-93af-3665437ab01c] activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `block in instrument'
[e06b1557-ba28-47d8-93af-3665437ab01c] activesupport (6.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[e06b1557-ba28-47d8-93af-3665437ab01c] activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `instrument'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
[e06b1557-ba28-47d8-93af-3665437ab01c] activerecord (6.0.2.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/abstract_controller/base.rb:136:in `process'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionview (6.0.2.2) lib/action_view/rendering.rb:39:in `process'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_controller/metal.rb:191:in `dispatch'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_controller/metal.rb:252:in `dispatch'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `each'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `serve'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:837:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] exception_notification (4.4.0) lib/exception_notification/rack.rb:36:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] rack (2.2.2) lib/rack/etag.rb:27:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] rack (2.2.2) lib/rack/head.rb:12:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
[e06b1557-ba28-47d8-93af-3665437ab01c] rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[e06b1557-ba28-47d8-93af-3665437ab01c] activesupport (6.0.2.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] railties (6.0.2.2) lib/rails/rack/logger.rb:38:in `call_app'
[e06b1557-ba28-47d8-93af-3665437ab01c] railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `block in call'
[e06b1557-ba28-47d8-93af-3665437ab01c] activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
[e06b1557-ba28-47d8-93af-3665437ab01c] activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
[e06b1557-ba28-47d8-93af-3665437ab01c] activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `tagged'
[e06b1557-ba28-47d8-93af-3665437ab01c] railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] rack (2.2.2) lib/rack/method_override.rb:24:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] rack (2.2.2) lib/rack/runtime.rb:22:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] activesupport (6.0.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] actionpack (6.0.2.2) lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] railties (6.0.2.2) lib/rails/engine.rb:526:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] puma (4.3.3) lib/puma/configuration.rb:228:in `call'
[e06b1557-ba28-47d8-93af-3665437ab01c] puma (4.3.3) lib/puma/server.rb:682:in `handle_request'
[e06b1557-ba28-47d8-93af-3665437ab01c] puma (4.3.3) lib/puma/server.rb:472:in `process_client'
[e06b1557-ba28-47d8-93af-3665437ab01c] puma (4.3.3) lib/puma/server.rb:328:in `block in run'
[e06b1557-ba28-47d8-93af-3665437ab01c] puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by brenogazzola** [comment]
I'll confirm this one. Got an alert this morning and found autoscale had scaled up the amount of servers I had because queue time had increased a lot and they were throwing out of memory errors. When I checked ActiveStorage's ProxyController endpoint had response times of 26 seconds.

**Comment by stephenchen13** [comment]
I took a look into these errors and and the long response times (`242768ms`) seem indicative of the behavior of the [AWS http client](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/S3/Client.html), specifically the `http_read_timeout` and `retry_limit` default configuration settings. `http_read_timeout (60s) * (1 + retry_limit (3)) = 240s`.

You can pass through those settings in `config/storage.yml` with values that make more sense for your applications:

```
amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: us-east-1
  http_read_timeout: 5
  retry_limit: 2
```

I've submitted a PR to update the documentation in case others run across this issue as well.

**Comment by jonathanhefner** [comment]
@stephenchen13 Great detective work!

I wonder if we should include more sensible defaults directly in the default `config/storage.yml`?

**Comment by vizcay** [comment]
> I took a look into these errors and and the long response times (`242768ms`) seem indicative of the behavior of the [AWS http client](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/S3/Client.html), specifically the `http_read_timeout` and `retry_limit` default configuration settings. `http_read_timeout (60s) * (1 + retry_limit (3)) = 240s`.
> 
> You can pass through those settings in `config/storage.yml` with values that make more sense for your applications:
> 
> ```
> amazon:
>   service: S3
>   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
>   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
>   region: us-east-1
>   http_read_timeout: 5
>   retry_limit: 2
> ```
> 
> I've submitted a PR to update the documentation in case others run across this issue as well.

Great, I think `http_open_timeout` should be set to a sane default too (default: 15).

**Comment by maxencehenneron** [comment]
I just had the same issue, our s3 provider went down and the whole app became unresponsive. I think it's a good idea to change the default timeout to something rational. 

( 5 seconds, a retry set to 2 ).

**Comment by vizcay** [comment]
I have a new incident related to this issue. Even whith a very short timeout (2 seconds in my case) your application is directly at the mercy of your S3 service provider. Last friday exactly that happened, when there was a major outage (https://status.linode.com/incidents/kx5s7qddxhtg).

My application is basically a catalog of products with images, mostly variants. I will estimate that 95% of my traffic is handling `ActiveStorage::RepresentationsController#show`. When the downtime started all that requests begun to timeout as it took them ~2 secs to respond, basically here:

```
class ActiveStorage::Variant
  private
    def processed?
      service.exist?(key)
    end
end
```

As the rate on which requests came in was grater than the ability to respond, the nginx backlog queue finally got full and is started to respond with `502 Bad gateway` even for requests it will be able to handle. No ammount of auto-scaling will solve this (and you could en with a big bill if not careful).

This is why https://github.com/rails/rails/pull/37901 is so important IMHO and it will be great if a temporary solution exists until 6.1. With that merge, ActiveStorage will be able to track if a variant was processed already and it won't need to hit S3. Of course the image won't be displayed anyway but it won't take your whole app down!
