### ISSUE TITLE
ActiveStorage Google Cloud bucket public access does not work

### ISSUE THREAD

**Issue by romanvbabenko** [rails/rails#39421]
### Steps to reproduce

Follow instructions described there https://edgeguides.rubyonrails.org/active_storage_overview.html#public-access
and setup public access to GCS bucket

### Expected behavior

Rails generates not signed urls, at least does not raise errors

### Actual behavior

```
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] ArgumentError (unknown keyword: :public):
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5]
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] google-cloud-storage (1.26.1) lib/google/cloud/storage.rb:78:in `new'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activestorage (6.0.3) lib/active_storage/service/gcs_service.rb:138:in `client'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activestorage (6.0.3) lib/active_storage/service/gcs_service.rb:134:in `bucket'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activestorage (6.0.3) lib/active_storage/service/gcs_service.rb:115:in `file_for'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activestorage (6.0.3) lib/active_storage/service/gcs_service.rb:78:in `block in exist?'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activesupport (6.0.3) lib/active_support/notifications.rb:180:in `block in instrument'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activesupport (6.0.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activesupport (6.0.3) lib/active_support/notifications.rb:180:in `instrument'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activestorage (6.0.3) lib/active_storage/service.rb:126:in `instrument'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activestorage (6.0.3) lib/active_storage/service/gcs_service.rb:77:in `exist?'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activestorage (6.0.3) app/models/active_storage/variant.rb:95:in `processed?'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activestorage (6.0.3) app/models/active_storage/variant.rb:67:in `processed'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activestorage (6.0.3) app/controllers/active_storage/representations_controller.rb:12:in `show'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/abstract_controller/base.rb:195:in `process_action'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activesupport (6.0.3) lib/active_support/callbacks.rb:135:in `run_callbacks'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/abstract_controller/callbacks.rb:41:in `process_action'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activesupport (6.0.3) lib/active_support/notifications.rb:180:in `block in instrument'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activesupport (6.0.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activesupport (6.0.3) lib/active_support/notifications.rb:180:in `instrument'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activerecord (6.0.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/abstract_controller/base.rb:136:in `process'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionview (6.0.3) lib/action_view/rendering.rb:39:in `process'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_controller/metal.rb:190:in `dispatch'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_controller/metal.rb:254:in `dispatch'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/routing/route_set.rb:33:in `serve'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/journey/router.rb:49:in `block in serve'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/journey/router.rb:32:in `each'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/journey/router.rb:32:in `serve'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/routing/route_set.rb:834:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] warden (1.2.8) lib/warden/manager.rb:34:in `catch'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] warden (1.2.8) lib/warden/manager.rb:34:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] rack (2.2.2) lib/rack/etag.rb:27:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] rack (2.2.2) lib/rack/head.rb:12:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/middleware/cookies.rb:648:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activerecord (6.0.3) lib/active_record/migration.rb:567:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activesupport (6.0.3) lib/active_support/callbacks.rb:101:in `run_callbacks'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] railties (6.0.3) lib/rails/rack/logger.rb:37:in `call_app'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] railties (6.0.3) lib/rails/rack/logger.rb:26:in `block in call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activesupport (6.0.3) lib/active_support/tagged_logging.rb:80:in `block in tagged'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activesupport (6.0.3) lib/active_support/tagged_logging.rb:28:in `tagged'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activesupport (6.0.3) lib/active_support/tagged_logging.rb:80:in `tagged'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] railties (6.0.3) lib/rails/rack/logger.rb:26:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] rack (2.2.2) lib/rack/method_override.rb:24:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] rack (2.2.2) lib/rack/runtime.rb:22:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] activesupport (6.0.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/middleware/static.rb:126:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] actionpack (6.0.3) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] webpacker (5.1.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] railties (6.0.3) lib/rails/engine.rb:527:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] puma (4.3.3) lib/puma/configuration.rb:228:in `call'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] puma (4.3.3) lib/puma/server.rb:682:in `handle_request'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] puma (4.3.3) lib/puma/server.rb:472:in `process_client'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] puma (4.3.3) lib/puma/server.rb:328:in `block in run'
[6eb0c146-5a77-45e1-94a8-7561fd96a4a5] puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

### System configuration
**Rails version**: 6.0.3

**Ruby version**: 2.7.1

**Comment by eugeneius** [comment]
The public access feature hasn't been released yet, it'll be part of Rails 6.1.

https://edgeguides.rubyonrails.org/ is the documentation for the master branch; https://guides.rubyonrails.org/ covers the latest stable version.
