### ISSUE TITLE
ActiveStorage crashes when loading AzureStorage with azure-storage-blob gem

### ISSUE THREAD

**Issue by mattwebbio** [rails/rails#39628]
### Steps to reproduce
1. Create a new Rails project
2. Configure ActiveStorage to use Azure Storage per the guide: https://edgeguides.rubyonrails.org/active_storage_overview.html#microsoft-azure-storage-service
3. Change `config.active_storage.service = :local` to `config.active_storage.service = : azure` in `config/environments/production.rb`
3. Start rails server (`RAILS_ENV=production bundle exec rails s`)

### Expected behavior
Puma launches successfully

### Actual behavior
Puma crashes because `azure_storage_service.rb` requires `azure/storage`, resulting in:

`cannot load such file -- azure/storage` and `Missing service adapter for "AzureStorage"`

Full trace:
```
/app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/lib/active_storage/service/configurator.rb:31:in `rescue in resolve': Cannot load `Rails.config.active_storage.service`: (RuntimeError)
Missing service adapter for "AzureStorage"
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/lib/active_storage/service/configurator.rb:27:in `resolve'
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/lib/active_storage/service/configurator.rb:17:in `build'
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/lib/active_storage/service/configurator.rb:8:in `build'
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/lib/active_storage/service.rb:49:in `configure'
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/lib/active_storage/engine.rb:120:in `block (2 levels) in <class:Engine>'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/app/models/active_storage/blob.rb:291:in `<main>'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:388:in `const_get'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:388:in `block (2 levels) in eager_load'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:723:in `block in ls'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:720:in `foreach'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:720:in `ls'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:376:in `block in eager_load'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:368:in `synchronize'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:368:in `eager_load'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:483:in `each'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:483:in `eager_load_all'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:32:in `instance_exec'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:32:in `run'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:60:in `run_initializers'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/application.rb:363:in `initialize!'
       from /app/config/environment.rb:5:in `<main>'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `block in require'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:291:in `load_dependency'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:49:in `require_relative'
       from config.ru:3:in `block in <main>'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/server.rb:349:in `build_app_and_options_from_config'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/server.rb:249:in `app'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/server.rb:422:in `wrapped_app'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/server.rb:312:in `block in start'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/server.rb:379:in `handle_profiling'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/server.rb:311:in `start'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/commands/server/server_command.rb:39:in `start'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/commands/server/server_command.rb:138:in `tap'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/commands/server/server_command.rb:138:in `perform'
       from /app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
       from /app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
       from /app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/command/base.rb:69:in `perform'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/command.rb:46:in `invoke'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/commands.rb:18:in `<main>'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `block in require'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:291:in `load_dependency'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `require'
       from bin/rails:4:in `<main>'
/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require': cannot load such file -- azure/storage (LoadError)
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/lib/active_storage/service/azure_storage_service.rb:4:in `<main>'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/lib/active_storage/service/configurator.rb:28:in `resolve'
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/lib/active_storage/service/configurator.rb:17:in `build'
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/lib/active_storage/service/configurator.rb:8:in `build'
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/lib/active_storage/service.rb:49:in `configure'
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/lib/active_storage/engine.rb:120:in `block (2 levels) in <class:Engine>'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
       from /app/vendor/bundle/ruby/2.7.0/gems/activestorage-6.0.3.1/app/models/active_storage/blob.rb:291:in `<main>'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:388:in `const_get'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:388:in `block (2 levels) in eager_load'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:723:in `block in ls'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:720:in `foreach'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:720:in `ls'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:376:in `block in eager_load'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:368:in `synchronize'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:368:in `eager_load'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:483:in `each'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:483:in `eager_load_all'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:32:in `instance_exec'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:32:in `run'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
       from /usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:60:in `run_initializers'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/application.rb:363:in `initialize!'
       from /app/config/environment.rb:5:in `<main>'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `block in require'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:291:in `load_dependency'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:49:in `require_relative'
       from config.ru:3:in `block in <main>'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/server.rb:349:in `build_app_and_options_from_config'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/server.rb:249:in `app'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/server.rb:422:in `wrapped_app'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/server.rb:312:in `block in start'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/server.rb:379:in `handle_profiling'
       from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/server.rb:311:in `start'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/commands/server/server_command.rb:39:in `start'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/commands/server/server_command.rb:138:in `tap'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/commands/server/server_command.rb:138:in `perform'
       from /app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
       from /app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
       from /app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/command/base.rb:69:in `perform'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/command.rb:46:in `invoke'
       from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/commands.rb:18:in `<main>'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `block in require'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:291:in `load_dependency'
       from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `require'
       from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**:
6.0.3.1
**Ruby version**:
2.7.1

### Example
I've uploaded an example here: https://github.com/mattwebbio/Broken-ActiveStorage-with-AzureStorageBlob

Running `docker-compose build` and `docker-compose up` should reproduce the same error.

**Comment by mattwebbio** [comment]
I apologize, I linked to the edge guides and am not on an edge version of Rails.
