### ISSUE TITLE
Upgrade Rails from 6.0.3 to 6.1 causes cannot load such file /config/boot_with_spring (LoadError)

### ISSUE THREAD

**Issue by jamesw** [rails/rails#39622]
When updating a Rails 6.0.3 app to 6.1 using `rails app:update` I was asked if I wanted to overwrite bin/rails
I requested a diff and was presented with the following
```
- require_relative '../config/boot'
+ require_relative "../config/boot_with_spring"
```
I chose to overwrite the file however upon starting rails server I am presented with the error 
cannot load such file /config/boot_with_spring (LoadError)

Obviously the file is missing however I do still have the config/boot.rb file.

The upgrade process should either install the boot_with_spring file (which I am unable to find anywhere or it should not make this change to the bin/rails file.

For anyone else facing this, to work around this I have renamed boot.rb to boot_with_spring.rb and all seems good but obviously there was a change for a reason so I am unsure if this is an appropriate work around for the time being.

I have omitted the full application paths as they are irrelevant.

**Comment by jonathanhefner** [comment]
@dhh You mentioned wanting to revert this addition in https://github.com/rails/rails/pull/39225#issuecomment-632840544.  Is that still the plan?

**Comment by dhh** [comment]
What I'd actually like to do is to upgrade boot such that it has the spring machinery in there. Rather than having a separate file, and rather than having spring modify binstubs. If you want to take a stab at that 🙏

**Comment by jamesw** [comment]
I believe that there may be a knock on effect from this in production. Because the boot.rb file now loads spring
```
begin
  load File.expand_path("../bin/spring", __dir__)
rescue LoadError => e
  raise unless e.path.end_with?("/bin/spring")
end
```
 and a newly generated application pops the spring gem in the development group of the Gemfile all is good in development, however, when deploying to and running in production on a production server I am now faced with the following error

`
Gem::Exception: can't find executable spring for gem spring. spring is not currently included in the bundle, perhaps you meant to add it to your Gemfile?\r`
 
I assume spring is not meant for production environments? Is this an error? Should I create a new issue? Should this issue be re-opened?

If my assumption is wrong then obviously I just need to include spring in all groups in the projects Gemfile

Please advise

**Comment by jonathanhefner** [comment]
@jamesw  A `RAILS_ENV` guard still needs to be added (see https://github.com/rails/rails/pull/39632#discussion_r440488572 and https://github.com/rails/rails/pull/39225#issuecomment-632855297).  Because the Spring binstub loads Spring based on Gemfile.lock, which is ignorant of installed gems and gem groups, perhaps the guard should be added to the binstub itself. :thinking:

But I'm confused as to why you're getting a `Gem::Exception` instead of a `Gem::LoadError`.  Could you please include the rest of the stack trace for that error message?  What command were you running?

**Comment by jamesw** [comment]
@jonathanhefner Sure, I'll post a stack trace asap, I am facing other issues right now that I need to resolve before I can deploy to production again but as soon as I have those resolved I'll pop the trace up here. 
I assumed I was getting a `Gem::Exception` as the gem did not exist in the production environment

**Comment by jamesw** [comment]
@jonathanhefner Here is my stack trace, this is the result of a capistrano deploy script
I have included from the start of the error to the last output from the deployment script.
Hopefully it will help

```
 INFO [89cba54e] Running /home/comtechrcc/rawdoncc/rvm1scripts/rvm-auto.sh . bundle exec rake db:migrate on 46.101.0.71
 DEBUG [89cba54e] Command: cd /home/comtechrcc/rawdoncc/releases/20200627023913 && ( export RAILS_ENV="production" ; /home/comtechrcc/rawdoncc/rvm1scripts/rvm-auto.sh . bundle exec rake db:migrate )
 DEBUG [89cba54e] 	rake aborted!
 DEBUG [89cba54e] 	
 DEBUG [89cba54e] 	Gem::Exception: can't find executable spring for gem spring. spring is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
 DEBUG [89cba54e] 	
 DEBUG [89cba54e] 	/home/comtechrcc/rawdoncc/releases/20200627023913/bin/spring:29:in `<top (required)>'
 DEBUG [89cba54e] 	
 DEBUG [89cba54e] 	/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `load'
 DEBUG [89cba54e] 	
 DEBUG [89cba54e] 	/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `<top (required)>'
 DEBUG [89cba54e] 	
 DEBUG [89cba54e] 	/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `require_relative'
 DEBUG [89cba54e] 	
 DEBUG [89cba54e] 	/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `<top (required)>'
 DEBUG [89cba54e] 	
 DEBUG [89cba54e] 	/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `require_relative'
 DEBUG [89cba54e] 	
 DEBUG [89cba54e] 	/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `<top (required)>'
 DEBUG [89cba54e] 	
 DEBUG [89cba54e] 	/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
 DEBUG [89cba54e] 	
 DEBUG [89cba54e] 	/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'
 DEBUG [89cba54e] 	
 DEBUG [89cba54e] 	/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'
 DEBUG [89cba54e] 	
 DEBUG [89cba54e] 	(See full trace by running task with --trace)
 DEBUG [89cba54e] 	
#<Thread:0x00007f5e041afa90 /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	13: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	12: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `run'
	11: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	10: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/capistrano-rails-1.5.0/lib/capistrano/tasks/migrations.rake:23:in `block (3 levels) in <top (required)>'
	 9: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:92:in `within'
	 8: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/capistrano-rails-1.5.0/lib/capistrano/tasks/migrations.rake:24:in `block (4 levels) in <top (required)>'
	 7: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:100:in `with'
	 6: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/capistrano-rails-1.5.0/lib/capistrano/tasks/migrations.rake:25:in `block (5 levels) in <top (required)>'
	 5: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:80:in `execute'
	 4: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	 3: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `tap'
	 2: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	 1: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/netssh.rb:170:in `execute_command'
/home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/command.rb:97:in `exit_status=': rake exit status: 1 (SSHKit::Command::Failed)
rake stdout: rake aborted!\r
Gem::Exception: can't find executable spring for gem spring. spring is not currently included in the bundle, perhaps you meant to add it to your Gemfile?\r
/home/comtechrcc/rawdoncc/releases/20200627023913/bin/spring:29:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `load'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `require_relative'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `require_relative'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'\r
(See full trace by running task with --trace)
rake stderr: Nothing written
	1: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing on host 46.101.0.71: rake exit status: 1 (SSHKit::Runner::ExecuteError)
rake stdout: rake aborted!\r
Gem::Exception: can't find executable spring for gem spring. spring is not currently included in the bundle, perhaps you meant to add it to your Gemfile?\r
/home/comtechrcc/rawdoncc/releases/20200627023913/bin/spring:29:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `load'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `require_relative'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `require_relative'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'\r
(See full trace by running task with --trace)
rake stderr: Nothing written
#<Thread:0x00007f5e041c0c50 /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	13: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	12: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `run'
	11: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	10: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/capistrano-rails-1.5.0/lib/capistrano/tasks/migrations.rake:23:in `block (3 levels) in <top (required)>'
	 9: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:92:in `within'
	 8: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/capistrano-rails-1.5.0/lib/capistrano/tasks/migrations.rake:24:in `block (4 levels) in <top (required)>'
	 7: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:100:in `with'
	 6: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/capistrano-rails-1.5.0/lib/capistrano/tasks/migrations.rake:25:in `block (5 levels) in <top (required)>'
	 5: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:80:in `execute'
	 4: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	 3: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `tap'
	 2: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	 1: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/backends/netssh.rb:170:in `execute_command'
/home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/command.rb:97:in `exit_status=': rake exit status: 1 (SSHKit::Command::Failed)
rake stdout: rake aborted!\r
Gem::Exception: can't find executable spring for gem spring. spring is not currently included in the bundle, perhaps you meant to add it to your Gemfile?\r
/home/comtechrcc/rawdoncc/releases/20200627023913/bin/spring:29:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `load'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `require_relative'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `require_relative'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'\r
(See full trace by running task with --trace)
rake stderr: Nothing written
	1: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing on host 46.101.0.71: rake exit status: 1 (SSHKit::Runner::ExecuteError)
rake stdout: rake aborted!\r
Gem::Exception: can't find executable spring for gem spring. spring is not currently included in the bundle, perhaps you meant to add it to your Gemfile?\r
/home/comtechrcc/rawdoncc/releases/20200627023913/bin/spring:29:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `load'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `require_relative'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `require_relative'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'\r
(See full trace by running task with --trace)
rake stderr: Nothing written
	1: from /home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/home/jamie/.rvm/gems/ruby-2.7.0@rawdon/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing on host 46.101.0.71: Exception while executing on host 46.101.0.71: rake exit status: 1 (SSHKit::Runner::ExecuteError)
rake stdout: rake aborted!\r
Gem::Exception: can't find executable spring for gem spring. spring is not currently included in the bundle, perhaps you meant to add it to your Gemfile?\r
/home/comtechrcc/rawdoncc/releases/20200627023913/bin/spring:29:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `load'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `require_relative'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `require_relative'\r
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'\r
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'\r
(See full trace by running task with --trace)
rake stderr: Nothing written
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 46.101.0.71: Exception while executing on host 46.101.0.71: rake exit status: 1
rake stdout: rake aborted!
Gem::Exception: can't find executable spring for gem spring. spring is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
/home/comtechrcc/rawdoncc/releases/20200627023913/bin/spring:29:in `<top (required)>'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `load'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `<top (required)>'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `require_relative'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `<top (required)>'
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `require_relative'
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `<top (required)>'
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
rake stderr: Nothing written


Caused by:
SSHKit::Runner::ExecuteError: Exception while executing on host 46.101.0.71: rake exit status: 1
rake stdout: rake aborted!
Gem::Exception: can't find executable spring for gem spring. spring is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
/home/comtechrcc/rawdoncc/releases/20200627023913/bin/spring:29:in `<top (required)>'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `load'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `<top (required)>'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `require_relative'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `<top (required)>'
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `require_relative'
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `<top (required)>'
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
rake stderr: Nothing written


Caused by:
SSHKit::Command::Failed: rake exit status: 1
rake stdout: rake aborted!
Gem::Exception: can't find executable spring for gem spring. spring is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
/home/comtechrcc/rawdoncc/releases/20200627023913/bin/spring:29:in `<top (required)>'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `load'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `<top (required)>'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `require_relative'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `<top (required)>'
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `require_relative'
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `<top (required)>'
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
rake stderr: Nothing written

Tasks: TOP => deploy:migrate
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing on host 46.101.0.71: Exception while executing on host 46.101.0.71: rake exit status: 1
rake stdout: rake aborted!
Gem::Exception: can't find executable spring for gem spring. spring is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
/home/comtechrcc/rawdoncc/releases/20200627023913/bin/spring:29:in `<top (required)>'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `load'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/boot.rb:2:in `<top (required)>'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `require_relative'
/home/comtechrcc/rawdoncc/releases/20200627023913/config/application.rb:1:in `<top (required)>'
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `require_relative'
/home/comtechrcc/rawdoncc/releases/20200627023913/Rakefile:4:in `<top (required)>'
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'
/home/comtechrcc/rawdoncc/shared/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
rake stderr: Nothing written
```

**Comment by jonathanhefner** [comment]
> /home/comtechrcc/rawdoncc/releases/20200627023913/bin/spring:29:in `<top (required)>'

@jamesw  Could you share the contents of your `bin/spring`?  The `bin/spring` that Spring currently generates looks like [this](https://github.com/rails/spring/blob/v2.1.0/lib/spring/client/binstub.rb#L27-L43), which is shorter than 29 lines.  (Going through the git history, it does not seem to have been longer in the past either.)  Is your `bin/spring` customized in some way?

> I assumed I was getting a `Gem::Exception` as the gem did not exist in the production environment

If Spring isn't installed, then [`gem 'spring'`](https://github.com/rails/spring/blob/v2.1.0/lib/spring/client/binstub.rb#L40) should raise a `Gem::MissingSpecError` which is a `Gem::LoadError` which is a `LoadError` which would be [rescued](https://github.com/rails/spring/blob/v2.1.0/lib/spring/client/binstub.rb#L17-L19) in a Springified `bin/rails` stub.  I did change the rescue in #39632 to only [apply to `bin/spring` itself](https://github.com/rails/rails/pull/39632/files#diff-b1ff4525fe1ec818c464a3d0a2bb82e6R5), but I can revert that, or, possibly better, we can add a `RAILS_ENV` guard to `bin/spring`.  However, neither of these would seem to help your case if you're experiencing a `Gem::Exception` (not a `LoadError`) from a customized `bin/spring`.

**Comment by jamesw** [comment]
@jonathanhefner I have a spring.rb in my config folder
```
Spring.watch(
  ".ruby-version",
  ".rbenv-vars",
  "tmp/restart.txt",
  "tmp/caching-dev.txt"
)
```
and in my bin folder I have the following spring.rb file
```

#!/usr/bin/env ruby
# frozen_string_literal: true

#
# This file was generated by Bundler.
#
# The application 'spring' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require "pathname"
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile",
  Pathname.new(__FILE__).realpath)

bundle_binstub = File.expand_path("../bundle", __FILE__)

if File.file?(bundle_binstub)
  if File.read(bundle_binstub, 300) =~ /This file was generated by Bundler/
    load(bundle_binstub)
  else
    abort("Your `bin/bundle` was not generated by Bundler, so this binstub cannot run.
Replace `bin/bundle` by running `bundle binstubs bundler --force`, then run this command again.")
  end
end

require "rubygems"
require "bundler/setup"

load Gem.bin_path("spring", "spring")

```

**Comment by jonathanhefner** [comment]
@jamesw  Thank you!  I understand what's happening now.  Your deploy script has a line in it like the following, yes?

```ruby
set :bundle_binstubs, -> { shared_path.join('bin') }
```

So the deploy script replaces `bin/spring` with the file you posted.  And, in particular, `Gem.bin_path("spring", "spring")` raises a `Gem::Exception` when Spring is not installed, rather than any form of `LoadError`.

I've submitted #39746 to address this and the other issues I've mentioned.

**Comment by jamesw** [comment]
@jonathanhefner indeed it does. I have
`set :rvm_map_bins, [ 'rake', 'gem', 'bundle', 'ruby', 'puma', 'pumactl', 'webpack' ]`

I am actually unhappy with the whole deployment process that I have and the need for this. I am currently re-writing the scripts as I am having so many problems especially around compiling assets and webpacker with command webpack not found errors and imported stylesheets from node_modules to sprockets application.scss not being found. If it is of any help I will let you know how I get on but I am starting a new rails 6.1 app from scratch as the upgrade process has just been too painful

Thank you for your attention to this
