### ISSUE TITLE
Model.upsert_all cause error with  schema using ActiveRecord::Enum

### ISSUE THREAD

**Issue by gituytfjhfgdv** [rails/rails#39788]
Hello. I encountered this error. I report this.  🙇 

#### db/schema.rb

```rb
create_table "cats", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", force: :cascade do |t|
  t.string "name", null: false
  t.integer "food_type", default: 1, null: false
  t.integer "height"
  t.integer "weight" 
end
```

#### Model
```rb
class Cat < ApplicationRecord
  enum food_type: { vegetable: 1, fish: 2 }

  class << self
    def daily_update
      cats = []
      Cat.all.find_each do |cat|
        cat.weight = cat.weight + 1 if cat.weight.present?
        cat.height = cat.height + 3 if cat.height.present?
        cats << cat.as_json
      end
      Cat.upsert_all cats
    end
  end
end
```

#### spec
using rspec with factoryBot.

`spec/factories/cats.rb`
```rb
FactoryBot.define do
  factory :cat do
    name { 'mike' }
    food_type { :vegetable }
  end
end
```

`spec/models/cat_spec.rb`
```ruby
RSpec.describe Cat, type: :model do
   describe '.daily_update' do
      let(:cat_1) { create(:cat, weight: 5, height: 10) }
      context 'when cat have weight and height,' do
        it 'updates weight and height.' do
          expect {
            Cat.daily_update
          }.to change { cat_1.weight }.from(5).to(6)
           .and change { cat_1.height }.from(10).to(13)
        end
     end
   end
end
```

### Expected behavior
update cats.

### Actual behavior
```
     Failure/Error: Cat.upsert_all cats

     ActiveRecord::NotNullViolation:
       Mysql2::Error: Column 'food_type' cannot be null
```

I test in rails console also.

```
> Cat.daily_update

Cat Upsert (1.1ms)  INSERT INTO `cats`(`id`,`weight`,`height`,`food_type`,`created_at`,`updated_at`) VALUES (1, 10, 3, NULL, '2020-04-13 04:13:22', '2020-04-14 08:00:53.929000') ON DUPLICATE KEY UPDATE `weight`=VALUES(`weight`),`height`=VALUES(`height`),`food_type`=VALUES(`food_type`),`created_at`=VALUES(`created_at`),`updated_at`=VALUES(`updated_at`)
/usr/local/bundle/gems/pry-0.12.2/lib/pry/exceptions.rb:28: warning: $SAFE will become a normal global variable in Ruby 3.0
ActiveRecord::NotNullViolation: Mysql2::Error: Column 'food_type' cannot be null
from /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
Caused by Mysql2::Error: Column 'food_type' cannot be null
from /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
```

### System configuration
**Rails version**:  6.0.2.2

**Ruby version**: 2.7.1

**Comment by eugeneius** [comment]
I'm pretty sure this was fixed by https://github.com/rails/rails/pull/38763, which was released in Rails 6.0.3. Can you try upgrading to the latest 6.0 release?

**Comment by gituytfjhfgdv** [comment]
@eugeneius 
Thank you so much.
Sorry. I missed #38763 .
I'll upgrade and try then. 🏃‍♂️

**Comment by gituytfjhfgdv** [comment]
I checked my problem is fixed by upgrade Rails. Thank you!
