### ISSUE TITLE
Callbacks should print query logs

### ISSUE THREAD

**Issue by aried3r** [rails/rails#39868]
### Steps to reproduce

```Ruby
# callback_query_logs.rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "6.0.3"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.verbose_query_logs = true

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.timestamps
    t.datetime :last_action_at
  end
end

class Post < ActiveRecord::Base
  after_create { self.last_action_at = created_at }
end

class BugTest < Minitest::Test
  def test_db_query_log_in_callback
    post = Post.create!

    assert_equal post.created_at, post.last_action_at
  end
end
```

```console
$ ruby callback_query_logs.rb
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using concurrent-ruby 1.1.6
Using i18n 1.8.3
Using minitest 5.14.1
Using thread_safe 0.3.6
Using tzinfo 1.2.7
Using zeitwerk 2.4.0
Using activesupport 6.0.3
Using activemodel 6.0.3
Using activerecord 6.0.3
Using bundler 2.1.4
Using sqlite3 1.4.2
-- create_table(:posts, {:force=>true})
D, [2020-07-17T22:58:12.947126 #59432] DEBUG -- :    (0.7ms)  SELECT sqlite_version(*)
D, [2020-07-17T22:58:12.947403 #59432] DEBUG -- :   ↳ active_record_master.rb:24:in `block in <main>'
D, [2020-07-17T22:58:12.947888 #59432] DEBUG -- :    (0.1ms)  DROP TABLE IF EXISTS "posts"
D, [2020-07-17T22:58:12.948036 #59432] DEBUG -- :   ↳ active_record_master.rb:24:in `block in <main>'
D, [2020-07-17T22:58:12.948509 #59432] DEBUG -- :    (0.3ms)  CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL, "last_action_at" datetime)
D, [2020-07-17T22:58:12.948648 #59432] DEBUG -- :   ↳ active_record_master.rb:24:in `block in <main>'
   -> 0.0053s
D, [2020-07-17T22:58:12.972968 #59432] DEBUG -- :    (0.2ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
D, [2020-07-17T22:58:12.973131 #59432] DEBUG -- :   ↳ active_record_master.rb:23:in `<main>'
D, [2020-07-17T22:58:12.983202 #59432] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.2ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]
D, [2020-07-17T22:58:12.983531 #59432] DEBUG -- :   ↳ active_record_master.rb:23:in `<main>'
D, [2020-07-17T22:58:12.988039 #59432] DEBUG -- :    (0.1ms)  begin transaction
D, [2020-07-17T22:58:12.988551 #59432] DEBUG -- :   ↳ active_record_master.rb:23:in `<main>'
D, [2020-07-17T22:58:12.988895 #59432] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.1ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "default_env"], ["created_at", "2020-07-17 20:58:12.987589"], ["updated_at", "2020-07-17 20:58:12.987589"]]
D, [2020-07-17T22:58:12.989254 #59432] DEBUG -- :   ↳ active_record_master.rb:23:in `<main>'
D, [2020-07-17T22:58:12.989420 #59432] DEBUG -- :    (0.0ms)  commit transaction
D, [2020-07-17T22:58:12.989600 #59432] DEBUG -- :   ↳ active_record_master.rb:23:in `<main>'
Run options: --seed 8385

# Running:

D, [2020-07-17T22:58:12.999432 #59432] DEBUG -- :    (0.1ms)  begin transaction
D, [2020-07-17T22:58:12.999809 #59432] DEBUG -- :   ↳ active_record_master.rb:36:in `test_db_query_log_in_callback'
D, [2020-07-17T22:58:13.000034 #59432] DEBUG -- :   Post Create (0.1ms)  INSERT INTO "posts" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2020-07-17 20:58:12.999026"], ["updated_at", "2020-07-17 20:58:12.999026"]]
D, [2020-07-17T22:58:13.000296 #59432] DEBUG -- :   ↳ active_record_master.rb:36:in `test_db_query_log_in_callback'
D, [2020-07-17T22:58:13.000486 #59432] DEBUG -- :    (0.0ms)  commit transaction
D, [2020-07-17T22:58:13.006689 #59432] DEBUG -- :   ↳ active_record_master.rb:36:in `test_db_query_log_in_callback'
.

Finished in 0.012916s, 77.4234 runs/s, 77.4234 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

### Expected behavior

The log should show the `last_action_at` column being set.

### Actual behavior

Instead it seems that no log output is generated from within the callback. I didn't find any information in [the Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) document or in the [Debugging Rails Applications](https://guides.rubyonrails.org/debugging_rails_applications.html) one.

According to [one gem](https://github.com/jaredbeck/rails-callback_log) that enables _some_ logging, logging callbacks causes significant overhead, however right now I did not find a possibility to see everything our Rails application is doing.

Maybe I missed a configuration option, but I searched the docs and code but was unable to find one or even discussion about this in the issues, although maybe I didn't know what to search for. If I indeed missed that, I apologize.

### System configuration
**Rails version**:
6.0.3
**Ruby version**:
2.7.1

**Comment by aried3r** [comment]
My bad, the example code is wrong, it only sets the attribute but doesn't save it.
