### ISSUE TITLE
ActiveRecord sql structure file dump fails

### ISSUE THREAD

**Issue by mattbaumann** [rails/rails#39894]
### Steps to reproduce

1. Postgres 12.3 client and db server in docker and `DATABASE_URL=postgresql://postgres:postgres@postgres:5432`
2. `schema_format` set  to `:sql`
3. invoke ` $ ./bin/rails db:migrate --trace RAILS_ENV=test`

The db:structure:dump works fine with `schema_format` set  to `:ruby`.

It it my gut feeling, that `pg_dump` does not behave correctly on my system, but I'd wish to have a better error msg to determine that.

*Dockerfile of Runtime Container*

```
FROM ruby:2.7-alpine3.12

RUN apk --update add postgresql-client postgresql-dev ca-certificates imagemagick chromium firefox-esr build-base python2 tzdata libc6-compat && gem install bundler

# Install NodeJS fast

ENV NODE_VERSION 14.5.0

# Install NodeJS like the NodeJS Container's Dockerfile

```

*Gemfile*

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# Documentation
gem 'sdoc', '~> 1.1.0'

gem 'active_storage_validations', '~> 0.8.9'
gem 'font-awesome-sass', '~> 5.13.0'
gem 'mini_magick', '>= 4.9.5'
gem 'parslet', '~> 2.0.0'
gem 'pg_search', '~> 2.2.0'
gem 'ruby-units', '~> 2.3.1'
gem 'will_paginate', '~> 3.3.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'postgresql', '~> 1.0.0'
gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
# Use Puma as the app server
gem 'puma', '~> 4.1'
gem 'rack-contrib', '~> 2.2.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Style Sheets
gem 'bulma-rails', '~> 0.8.0'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails', '~> 4.0.1'
  gem 'rubocop', '~> 0.88.0', require: false
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '>= 3.3.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'apparition'
  gem 'factory_bot_rails', '~> 6.0.0'
  gem 'launchy', '~> 2.5.0'
  gem 'rails-controller-testing', '~> 1.0.4'
  gem 'rspec_junit_formatter', '~> 0.4.1'
  gem 'shoulda-matchers', '~> 4.3.0'
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

```

### Expected behavior

Dump structure.sql file to /db and exit with 0.

### Actual behavior

```
== 20200628145801 ChangeUnitValueName: migrated (0.0039s) =====================
 ** Invoke db:_dump (first_time)
 ** Execute db:_dump
 ** Invoke db:structure:dump (first_time)
 ** Invoke db:load_config 
 ** Execute db:structure:dump
 rails aborted!
 TypeError: no implicit conversion of nil into String
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/postgresql_database_tasks.rb:113:in `system'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/postgresql_database_tasks.rb:113:in `run_cmd'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/postgresql_database_tasks.rb:78:in `structure_dump'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:310:in `structure_dump'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:380:in `dump_schema'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:435:in `block (4 levels) in <main>'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:433:in `each'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:433:in `block (3 levels) in <main>'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:98:in `block (2 levels) in <main>'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:88:in `block (2 levels) in <main>'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/command.rb:48:in `invoke'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
 /builds/infra/cook-book/bin/rails:9:in `<top (required)>'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
 /builds/infra/cook-book/vendor/ruby/ruby/2.7.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
 /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
 /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
 /builds/infra/cook-book/bin/spring:15:in `<top (required)>'
 ./bin/rails:3:in `load'
 ./bin/rails:3:in `<main>'
 Tasks: TOP => db:structure:dump
```

### System configuration
**Rails version**:
6.0.3
**Ruby version**:
2.7.1

**Comment by duderamos** [comment]
Hey @mattbaumann, do you mind sharing your `config/database.yml` as well?

**Comment by mattbaumann** [comment]
Absolutly.
Tried it already with both:
1. using DATABASE_URL=postgresql://postgres:postgres@postgres:5432
2. Using database.yml

```yaml
default: &default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  gssencmode: disable

development:
  <<: *default

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default

production:
  <<: *default
```

Concurrently I debugged the library version 6.0.3.2, which is the version installed by bundler; turns out `/usr/src/app/vendor/ruby/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/postgresql_database_tasks.rb` on line 77:

```ruby
args << configuration["database"]
```

This piece of code will append `nil` to the call of `run_cmd("pg_dump", args, "dumping")`. Which is the reason of the error. 

Please be aware, that this error seems to be fixed in the current version, see https://github.com/rails/rails/blob/master/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L75 

Because I only use URLs the `configuration["database"]` is always `nil`. Since, the error is already there and will be fixed soon, I suggest to add an explanation of the fact in [Database Guide](https://guides.rubyonrails.org/configuring.html#configuring-a-database)

**Comment by tgxworld** [comment]
@mattbaumann It looks like this bug will be fixed in the next release of Rails, can this be closed?
