### ISSUE TITLE
ArgumentError (SMTP-AUTH requested but missing user name)

### ISSUE THREAD

**Issue by Souravgoswami** [rails/rails#40262]
### Steps to reproduce
Add this code to config/environments/development.rb

```
config.action_mailer.default_url_options = { host: 'localhost:8080' }
config.action_mailer.delivery_method = :smtp

config.action_mailer.smtp_settings = {
  address: 'smtp.gmail.com',
  port: 587,
  domain: 'example.net',
  authentication: 'plain',
  enable_starttls_auto: true,
  user_name: 'gmail_email',
  password: '...'
}

config.action_mailer.raise_delivery_errors = true
config.action_mailer.perform_deliveries = true
```

### Expected behavior
Action mailer should send email from the sender to the receiver.
This ruby code works just fine:

```
#!/usr/bin/ruby -w
require 'net/smtp'

message = <<~EOF
    From: mygmail@gmail.com
    To: someone@protonmail.com
    Subject: Hello!

    Hello!
        #{"HELLO ".*(50).delete_suffix(?\s)}
EOF

Net::SMTP.new('smtp.gmail.com', 587).tap(&:enable_starttls_auto).start('gmail.com', 'mygmail@gmail.com', 'mygmailpass', :plain) do |smtp|
    smtp.send_message message, 'mygmail@gmail.com', 'someone@protonmail.com'
end
```

### Actual behavior
Getting:

```ruby
ArgumentError (SMTP-AUTH requested but missing user name)
```

![image](https://user-images.githubusercontent.com/37468605/93739598-4f614700-fc06-11ea-963f-f27847842be5.png)

![image](https://user-images.githubusercontent.com/37468605/93739580-44a6b200-fc06-11ea-8fac-58969dee784b.png)

Full Error:

```ruby
.
.
.
started POST "/users" for 127.0.0.1 at 2020-09-21 12:28:46 +0530
Processing by Devise::RegistrationsController#create as HTML
  Parameters: {"authenticity_token"=>"QB+WY0nXJpQKMv4yUpakxCvvMverNLWNS7Gd5RH7+k1r3CHiUFkrI9TcHMWBvAwVUtPsWUAuz9adAJbEvUlq4w==", "user"=>{"email"=>"Abcdefghijklmnopqrstuvwxy@fn.netfdasfdssdf", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>""}
   (0.1ms)  begin transaction
  User Exists? (0.5ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "abcdefghijklmnopqrstuvwxy@fn.netfdasfdssdf"], ["LIMIT", 1]]
  CACHE User Exists? (0.0ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "abcdefghijklmnopqrstuvwxy@fn.netfdasfdssdf"], ["LIMIT", 1]]
  User Create (1.2ms)  INSERT INTO "users" ("email", "encrypted_password", "confirmation_token", "confirmation_sent_at", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?)  [["email", "abcdefghijklmnopqrstuvwxy@fn.netfdasfdssdf"], ["encrypted_password", "$2a$12$o7Jat3swSQ0UvtOHaJWWcucI5UD/iOpgyc5ctpx0trwOid9/OTvra"], ["confirmation_token", "r9ofHgi8SFpoiu_8ChF4"], ["confirmation_sent_at", "2020-09-21 06:58:47.021256"], ["created_at", "2020-09-21 06:58:47.021006"], ["updated_at", "2020-09-21 06:58:47.021006"]]
   (9.8ms)  commit transaction
  Rendering devise/mailer/confirmation_instructions.html.erb
  Rendered devise/mailer/confirmation_instructions.html.erb (Duration: 1.9ms | Allocations: 230)
Devise::Mailer#confirmation_instructions: processed outbound mail in 10.5ms
Delivered mail 5f684f2712d09_47fa5c80790ce@archlinux.mail (24.9ms)
Date: Mon, 21 Sep 2020 12:28:47 +0530
From: please-change-me-at-config-initializers-devise@example.com
Reply-To: please-change-me-at-config-initializers-devise@example.com
To: abcdefghijklmnopqrstuvwxy@fn.netfdasfdssdf
Message-ID: <5f684f2712d09_47fa5c80790ce@archlinux.mail>
Subject: Confirmation instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Welcome abcdefghijklmnopqrstuvwxy@fn.netfdasfdssdf!</p>

<p>You can confirm your account email through the link below:</p>

<p><a href="http://localhost:8080/users/confirmation?confirmation_token=r9ofHgi8SFpoiu_8ChF4">Confirm my account</a></p>

Completed 500 Internal Server Error in 488ms (ActiveRecord: 11.6ms | Allocations: 18407)


  
ArgumentError (SMTP-AUTH requested but missing user name):
  
/usr/local/lib/ruby/2.7.0/net/smtp.rb:777:in `check_auth_args'
/usr/local/lib/ruby/2.7.0/net/smtp.rb:546:in `do_start'
/usr/local/lib/ruby/2.7.0/net/smtp.rb:518:in `start'
mail (2.7.1) lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
mail (2.7.1) lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
mail (2.7.1) lib/mail/message.rb:2159:in `do_delivery'
mail (2.7.1) lib/mail/message.rb:260:in `block in deliver'
actionmailer (6.0.3.3) lib/action_mailer/base.rb:589:in `block in deliver_mail'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `instrument'
actionmailer (6.0.3.3) lib/action_mailer/base.rb:587:in `deliver_mail'
mail (2.7.1) lib/mail/message.rb:260:in `deliver'
actionmailer (6.0.3.3) lib/action_mailer/message_delivery.rb:115:in `block in deliver_now'
actionmailer (6.0.3.3) lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
actionmailer (6.0.3.3) lib/action_mailer/message_delivery.rb:114:in `deliver_now'
devise (4.7.2) lib/devise/models/authenticatable.rb:200:in `send_devise_notification'
devise (4.7.2) lib/devise/models/confirmable.rb:121:in `send_confirmation_instructions'
devise (4.7.2) lib/devise/models/confirmable.rb:183:in `send_on_create_confirmation_instructions'
activesupport (6.0.3.3) lib/active_support/callbacks.rb:428:in `block in make_lambda'
activesupport (6.0.3.3) lib/active_support/callbacks.rb:263:in `block in conditional'
activesupport (6.0.3.3) lib/active_support/callbacks.rb:517:in `block in invoke_after'
activesupport (6.0.3.3) lib/active_support/callbacks.rb:517:in `each'
activesupport (6.0.3.3) lib/active_support/callbacks.rb:517:in `invoke_after'
activesupport (6.0.3.3) lib/active_support/callbacks.rb:136:in `run_callbacks'
activesupport (6.0.3.3) lib/active_support/callbacks.rb:825:in `_run_commit_callbacks'
activerecord (6.0.3.3) lib/active_record/transactions.rb:339:in `committed!'
activerecord (6.0.3.3) lib/active_record/connection_adapters/abstract/transaction.rb:127:in `commit_records'
activerecord (6.0.3.3) lib/active_record/connection_adapters/abstract/transaction.rb:265:in `block in commit_transaction'
activesupport (6.0.3.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
activesupport (6.0.3.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
activesupport (6.0.3.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
activesupport (6.0.3.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
activesupport (6.0.3.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
activerecord (6.0.3.3) lib/active_record/connection_adapters/abstract/transaction.rb:255:in `commit_transaction'
activerecord (6.0.3.3) lib/active_record/connection_adapters/abstract/transaction.rb:293:in `block in within_new_transaction'
activesupport (6.0.3.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
activesupport (6.0.3.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
activesupport (6.0.3.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
activesupport (6.0.3.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
activesupport (6.0.3.3) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
activerecord (6.0.3.3) lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
activerecord (6.0.3.3) lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
activerecord (6.0.3.3) lib/active_record/transactions.rb:212:in `transaction'
activerecord (6.0.3.3) lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
activerecord (6.0.3.3) lib/active_record/transactions.rb:314:in `save'
activerecord (6.0.3.3) lib/active_record/suppressor.rb:44:in `save'
devise (4.7.2) app/controllers/devise/registrations_controller.rb:19:in `create'
actionpack (6.0.3.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.3.3) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.3.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.3.3) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.3.3) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.3.3) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.3.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.3.3) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.3.3) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.3.3) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.3.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.3.3) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.3.3) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.3.3) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.3.3) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.3.3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.3.3) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.3.3) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (6.0.3.3) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.3.3) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.3.3) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3.3) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3.3) lib/action_dispatch/routing/route_set.rb:834:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.3.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.3.3) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.3) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.4) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.4) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.3) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.3) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.3) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.3) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.3) lib/rails/engine.rb:527:in `call'
puma (4.3.6) lib/puma/configuration.rb:228:in `call'
puma (4.3.6) lib/puma/server.rb:713:in `handle_request'
puma (4.3.6) lib/puma/server.rb:472:in `process_client'
puma (4.3.6) lib/puma/server.rb:328:in `block in run'
puma (4.3.6) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

### System configuration
**Rails version**:
Rails 6.0.3.3

**Ruby version**:
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**Comment by Souravgoswami** [comment]
I think this is devise issue and not action mailer problem? 🤔🤔

**Comment by Souravgoswami** [comment]
This was a stupid error caused by sendgrid. It's not a fault of ActionMailer.

**Comment by anujmiddha** [comment]
I copied your code into a fresh project, and was able to send an email using ActionMailer without any problem. Can you share how you are triggering the email?

```
irb(main):002:0> SampleMailer.welcome_email.deliver_now
=> #<Mail::Message:70283843294600, Multipart: true, Headers: <Date: Tue, 22 Sep 2020 18:04:27 +0530>, <From: ...@gmail.com>, <To: ...@gmail.com>, <Message-ID: <5f69ef53ed3e6_3e953fec38036e5c673d8@Nayans-MBP.mail>>, <Subject: Welcome to My Awesome Site>, <Mime-Version: 1.0>, <Content-Type: multipart/alternative; boundary="--==_mimepart_5f69ef53ec3e8_3e953fec38036e5c672cf"; charset=UTF-8>, <Content-Transfer-Encoding: 7bit>>
```

**Comment by Souravgoswami** [comment]
Sorry it was a failure due to the use of sendgrid. Sendgrid was probably not set up properly, and as I was following the instructor, he said to pollute the application.rb instead of development.rb or production.rb. Later the application.rb got ignored, and the error raised. It was fixed by removing sendgrid overall!
