### ISSUE TITLE
Raise `SQLite3::SQLException` when migrating table with self association

### ISSUE THREAD

**Issue by jasl** [rails/rails#40325]
### Steps to reproduce

```ruby
require "active_record"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
    create_table :tags do |t|
      t.references :preferred_id, null: true, foreign_key: false
    end

    add_foreign_key :tags, :tags, column: :preferred_id
end
```

### Expected behavior

The migration should pass

### Actual behavior

```
-- create_table(:tags)
D, [2020-10-03T23:07:45.591389 #71803] DEBUG -- :    (1.7ms)  SELECT sqlite_version(*)
D, [2020-10-03T23:07:45.592191 #71803] DEBUG -- :    (0.3ms)  CREATE TABLE "tags" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "preferred_id_id" integer)
D, [2020-10-03T23:07:45.592649 #71803] DEBUG -- :    (0.1ms)  CREATE  INDEX "index_tags_on_preferred_id_id" ON "tags" ("preferred_id_id")
   -> 0.0069s
-- add_foreign_key(:tags, :tags, {:column=>:preferred_id})
D, [2020-10-03T23:07:45.592928 #71803] DEBUG -- :    (0.0ms)  begin transaction
D, [2020-10-03T23:07:45.593031 #71803] DEBUG -- :    (0.0ms)  PRAGMA foreign_keys
D, [2020-10-03T23:07:45.593159 #71803] DEBUG -- :    (0.0ms)  PRAGMA defer_foreign_keys
D, [2020-10-03T23:07:45.593246 #71803] DEBUG -- :    (0.0ms)  PRAGMA defer_foreign_keys = ON
D, [2020-10-03T23:07:45.593329 #71803] DEBUG -- :    (0.0ms)  PRAGMA foreign_keys = OFF
D, [2020-10-03T23:07:45.595332 #71803] DEBUG -- :    (0.1ms)  CREATE TEMPORARY TABLE "atags" ("id" integer NOT NULL PRIMARY KEY, "preferred_id_id" integer DEFAULT NULL)
D, [2020-10-03T23:07:45.596097 #71803] DEBUG -- :    (0.1ms)  CREATE  INDEX "tindex_atags_on_preferred_id_id" ON "atags" ("preferred_id_id")
D, [2020-10-03T23:07:45.596432 #71803] DEBUG -- :    (0.1ms)  INSERT INTO "atags" ("id","preferred_id_id")
                     SELECT "id","preferred_id_id" FROM "tags"
D, [2020-10-03T23:07:45.596587 #71803] DEBUG -- :    (0.1ms)  DROP TABLE "tags"
D, [2020-10-03T23:07:45.597341 #71803] DEBUG -- :    (0.2ms)  CREATE TABLE "tags" ("id" integer NOT NULL PRIMARY KEY, "preferred_id_id" integer DEFAULT NULL, CONSTRAINT "fk_rails_4782b458a6"
FOREIGN KEY ("preferred_id")
  REFERENCES "tags" ("id")
)
D, [2020-10-03T23:07:45.597447 #71803] DEBUG -- :    (0.0ms)  PRAGMA defer_foreign_keys = 0
D, [2020-10-03T23:07:45.597537 #71803] DEBUG -- :    (0.0ms)  PRAGMA foreign_keys = 1
D, [2020-10-03T23:07:45.597640 #71803] DEBUG -- :    (0.0ms)  rollback transaction
Traceback (most recent call last):
       16: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
       15: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
       14: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
       13: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
       12: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
       11: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
       10: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
        9: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:24:in `block in execute'
        8: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
        7: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
        6: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
        5: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:25:in `block (2 levels) in execute'
        4: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:193:in `execute'
        3: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `prepare'
        2: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `new'
        1: from /Users/jasl/.rvm/gems/ruby-2.7.1/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `initialize'
ActiveRecord::StatementInvalid (SQLite3::SQLException: unknown column "preferred_id" in foreign key definition)
```

### System configuration

**Rails version**: 6.0.3.3

**Ruby version**: 2.7.1

### Note

It will pass if change `references` to `bigint`

```ruby
require "active_record"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
    create_table :tags do |t|
      t.bigint :preferred_id, null: true
    end

    add_foreign_key :tags, :tags, column: :preferred_id
end
```

```
-- create_table(:tags)
D, [2020-10-03T23:04:58.854637 #71766] DEBUG -- :    (2.3ms)  SELECT sqlite_version(*)
D, [2020-10-03T23:04:58.855345 #71766] DEBUG -- :    (0.3ms)  CREATE TABLE "tags" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "preferred_id" bigint)
   -> 0.0076s
-- add_foreign_key(:tags, :tags, {:column=>:preferred_id})
D, [2020-10-03T23:04:58.855639 #71766] DEBUG -- :    (0.0ms)  begin transaction
D, [2020-10-03T23:04:58.855741 #71766] DEBUG -- :    (0.0ms)  PRAGMA foreign_keys
D, [2020-10-03T23:04:58.855838 #71766] DEBUG -- :    (0.0ms)  PRAGMA defer_foreign_keys
D, [2020-10-03T23:04:58.855922 #71766] DEBUG -- :    (0.0ms)  PRAGMA defer_foreign_keys = ON
D, [2020-10-03T23:04:58.856010 #71766] DEBUG -- :    (0.0ms)  PRAGMA foreign_keys = OFF
D, [2020-10-03T23:04:58.857977 #71766] DEBUG -- :    (0.1ms)  CREATE TEMPORARY TABLE "atags" ("id" integer NOT NULL PRIMARY KEY, "preferred_id" integer DEFAULT NULL)
D, [2020-10-03T23:04:58.858379 #71766] DEBUG -- :    (0.1ms)  INSERT INTO "atags" ("id","preferred_id")
                     SELECT "id","preferred_id" FROM "tags"
D, [2020-10-03T23:04:58.858525 #71766] DEBUG -- :    (0.1ms)  DROP TABLE "tags"
D, [2020-10-03T23:04:58.859247 #71766] DEBUG -- :    (0.1ms)  CREATE TABLE "tags" ("id" integer NOT NULL PRIMARY KEY, "preferred_id" integer DEFAULT NULL, CONSTRAINT "fk_rails_4782b458a6"
FOREIGN KEY ("preferred_id")
  REFERENCES "tags" ("id")
)
D, [2020-10-03T23:04:58.859664 #71766] DEBUG -- :    (0.1ms)  INSERT INTO "tags" ("id","preferred_id")
                     SELECT "id","preferred_id" FROM "atags"
D, [2020-10-03T23:04:58.859797 #71766] DEBUG -- :    (0.1ms)  DROP TABLE "atags"
D, [2020-10-03T23:04:58.859886 #71766] DEBUG -- :    (0.0ms)  PRAGMA defer_foreign_keys = 0
D, [2020-10-03T23:04:58.859966 #71766] DEBUG -- :    (0.0ms)  PRAGMA foreign_keys = 1
D, [2020-10-03T23:04:58.860095 #71766] DEBUG -- :    (0.1ms)  commit transaction
   -> 0.0047s
D, [2020-10-03T23:04:58.889973 #71766] DEBUG -- :    (0.1ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
D, [2020-10-03T23:04:58.901555 #71766] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.8ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]
D, [2020-10-03T23:04:58.905225 #71766] DEBUG -- :    (0.0ms)  begin transaction
D, [2020-10-03T23:04:58.905466 #71766] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.1ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "default_env"], ["created_at", "2020-10-03 15:04:58.904877"], ["updated_at", "2020-10-03 15:04:58.904877"]]
D, [2020-10-03T23:04:58.905603 #71766] DEBUG -- :    (0.0ms)  commit transaction
 => "default_env"
```

**Comment by abhaynikam** [comment]
@jasl I think that is an expected Rails behavior. In order to add self-association with `reference` you need to specify the table referring to with `references: :tags`(in this case).

```
t.references :preferred, null: true, foreign_key: false, references: :tags
```

Following should work: 
```
require "active_record"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :tags do |t|
    t.references :preferred, null: true, foreign_key: false, references: :tags
  end

  add_foreign_key :tags, :tags, column: :preferred_id
end
```

**Comment by jasl** [comment]
> @jasl I think that is an expected Rails behavior. In order to add self-association with `reference` you need to specify the table referring to with `references: :tags`(in this case).
> 
> ```
> t.references :preferred, null: true, foreign_key: false, references: :tags
> ```
> 
> Following should work:
> 
> ```
> require "active_record"
> require "logger"
> 
> ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
> ActiveRecord::Base.logger = Logger.new(STDOUT)
> 
> ActiveRecord::Schema.define do
>   create_table :tags do |t|
>     t.references :preferred, null: true, foreign_key: false, references: :tags
>   end
> 
>   add_foreign_key :tags, :tags, column: :preferred_id
> end
> ```

Thank you!

I don't know there's `references: :tags` before, I was thought if I set `foreign_key: false`, it will only generate a `bigint` column
