### ISSUE TITLE
Error on initialization when RAILS_ENV is set to an unconfigured value

### ISSUE THREAD

**Issue by moeffju** [rails/rails#40342]
### Steps to reproduce

- Create a new rails app
- Create a simple controller responding with just success and create a route for `GET /health` pointing to it
- Set RAILS_ENV to a value that no environment is defined for, such as “dev” instead of “development”
- Start the rails server
- Make a GET request to /health on the server

### Expected behavior

Rails should tell me that the requested environment is not defined and abort.

### Actual behavior

Rails server starts and runs the config/initialization code multiple times, resulting in errors like this:

```
2020-10-06 04:53:57 +0000: Rack app error handling request { GET /health }
#<NoMethodError: undefined method `delete' for nil:NilClass>
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/railtie.rb:179:in `block (2 levels) in <class:Railtie>'
```

The error is confusing and misleading, and searching for it on the web doesn’t lead to clear cause descriptions either.

### System configuration
**Rails version**: 6.0.3.3

**Ruby version**: 2.7.2

**Comment by moeffju** [comment]
To add some background, this happened when deploying a Rails app in an environment otherwise set up for Java Spring boot services, which used “dev” and “prod” as environment names. Debugging let me down a rabbit hole for a bit.

**Comment by yoones** [comment]
With the following setup:
- ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
- rails 6.0.3.3

```
rails new toto
cd toto
rails g controller home index
# routes.rb: root to: 'home#index'
```

```
$ RAILS_ENV=toto rails s
=> Booting Puma
=> Rails 6.0.3.3 application starting in toto 
=> Run `rails server --help` for more startup options
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

RAILS_ENV=toto environment is not defined in config/webpacker.yml, falling back to production environment
Puma starting in single mode...
* Version 4.3.6 (ruby 2.7.1-p83), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: toto
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

When requesting the root page, here is the full output I get:

```
2020-10-07 10:38:05 +0200: Rack app error handling request { GET / }
#<ActiveRecord::AdapterNotSpecified: The `toto` database is not configured for the `toto` environment.

Available databases configurations are:

default
development
test
production
>
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/connection_specification.rb:250:in `resolve_symbol_connection'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/connection_specification.rb:218:in `resolve_connection'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/connection_handling.rb:170:in `resolve_config_for_connection'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/connection_handling.rb:50:in `establish_connection'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/railtie.rb:201:in `block (2 levels) in <class:Railtie>'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/base.rb:327:in `<module:ActiveRecord>'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/base.rb:27:in `<main>'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/query_cache.rb:31:in `run'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/execution_wrapper.rb:28:in `before'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:604:in `catch'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:604:in `block in default_terminator'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:201:in `block in halting'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:513:in `each'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:513:in `invoke_before'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:134:in `run_callbacks'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/execution_wrapper.rb:111:in `run!'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/execution_wrapper.rb:73:in `block in run!'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/execution_wrapper.rb:70:in `tap'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/execution_wrapper.rb:70:in `run!'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/static.rb:126:in `call'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.3/lib/rails/engine.rb:527:in `call'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.6/lib/puma/configuration.rb:228:in `call'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.6/lib/puma/server.rb:713:in `handle_request'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.6/lib/puma/server.rb:472:in `process_client'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.6/lib/puma/server.rb:328:in `block in run'
/home/yoones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.6/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

When I update `config/database.yml` to add the missing configuration (notice I did not add a new file under `config/environments/`), I get a `200 OK` with the following warning in the logs: `RAILS_ENV=toto environment is not defined in config/webpacker.yml, falling back to production environment`.

Conclusion: an application can work without `config/environments/*.rb` (not a recommandation, just an observation).

I find it a bit confusing because `railties/lib/rails/command/environment_argument.rb#available_environments` seems to suggest only environments present in  `config/environments/*.rb` should be available.

It seems to me that this issue has more to do with whether or not to enforce the presence of a `config/environments/*.rb` file than it has to do with the adequacy of the output in case of this file being missing.

**Comment by moeffju** [comment]
Sorry, I accidentally removed the mention of `--api` in my report :( 

```
$ rails new teal --api
$ cd teal
$ RAILS_ENV=foobar rails s -p 3001   # in another window, make a GET request to the server
=> Booting Puma
=> Rails 6.0.3.3 application starting in foobar
=> Run `rails server --help` for more startup options
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

Puma starting in single mode...
* Version 4.3.6 (ruby 2.7.1-p83), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: foobar
* Listening on tcp://0.0.0.0:3001
Use Ctrl-C to stop
2020-10-07 11:51:34 +0200: Rack app error handling request { GET / }
#<ActiveRecord::AdapterNotSpecified: The `foobar` database is not configured for the `foobar` environment.
```

So, to conclude: In an API only project, the webpacker message isn’t shown, so you only get the server error for the unconfigured database. I believe this case could be handled better by pointing devs to the root cause - that the environment is likely missing/unconfigured.

In my case, the environment the app was deployed it used `dev` and `prod` as environment names, instead of the `development` and `production` Rails expected, but it was hard to get visibility into this because the value was injected from the CI pipeline through Helm into k8s. An error message that clearly stated “there is no environment configured with this RAILS_ENV `dev'” would have saved me time debugging.

**Comment by tahsin352** [comment]
I assume "The `foobar` database is not configured for the `foobar` environment." message clearly states that the environment is `foobar`. As a developer we should check the env settings. This is a developer debug log, so, he should understand where the error could be from this message. Tts not for client's frontend display messages.

**Comment by sajjadmurtaza** [comment]
I also tried with `gem 'rails', '~> 6-1-stable'`
and getting same error.

My `database.yml` file is

```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  primary:
    database: xyz_development
  primary_replica:
    database: xyz_development
    replica: true
```

and 

```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :primary, reading: :primary_replica }
end
```

> `resolve_symbol_connection': The `primary_replica` database is not configured for the `development` environment.

maybe @eileencodes if you can help here.

**Comment by eileencodes** [comment]
As far as I can tell this issue is about the Rails ENV being wrong, whereas @sajjadmurtaza you have a totally different issue. 

This is not written correctly, default should be included in `primary` and `primary_replica`. Look at the output of your configurations and you'll see they are not correct.

```
development:
  <<: *default
  primary:
    database: xyz_development
  primary_replica:
    database: xyz_development
    replica: true
```

This is correct:

```
development:
  primary:
    <<: *default
    database: xyz_development
  primary_replica:
     <<: *default
    database: xyz_development
    replica: true
```

**Comment by moeffju** [comment]
Correct, my issue is about misleading messages when an unconfigured environment is selected. It's more of a UX issue.On Jan 11, 2021 14:19, "Eileen M. Uchitelle" <notifications@github.com> wrote:
As far as I can tell this issue is about the Rails ENV being wrong, whereas @sajjadmurtaza you have a totally different issue.
This is not written correctly, default should be included in primary and primary_replica. Look at the output of your configurations and you'll see they are not correct.
development:
  <<: *default
  primary:
    database: xyz_development
  primary_replica:
    database: xyz_development
    replica: true

This is correct:
development:
  primary:
    <<: *default
    database: xyz_development
  primary_replica:
     <<: *default
    database: xyz_development
    replica: true
