### ISSUE TITLE
Zeitwerk::NameError on Heroku

### ISSUE THREAD

**Issue by fxn** [rails/rails#40367]
Moved from https://github.com/fxn/zeitwerk/issues/139.

Ruby 2.6.3
Rails 6.0.1

I've just added email to my app (I essentially followed the guide at https://guides.rubyonrails.org/action_mailer_basics.html). Works locally, and previews display at `http://localhost:3000/rails/mailers` as expected, but deploying to production on Heroku crashes the app with the error `Unable to load application: Zeitwerk::NameError: expected file /app/app/mailers/previews/user_mailer_preview.rb to define constant Previews::UserMailerPreview, but didn't`.

Presumably it's the `/app/app/` part of the file path that is the problem, but I'm not sure why it's not just loading `app/mailers/...`.

In `application.rb` is `config.action_mailer.preview_path = "#{Rails.root}/app/mailers/previews"`.

Looking at other threads, a temporary fix will be `config.autoloader = :classic`, but I'd like to avoid this if possible.

Any ideas what's going wrong?

The full error is:
```
2020-10-11T14:21:49.074313+00:00 heroku[web.1]: Starting process with command `bundle exec puma -C config/puma.rb`
2020-10-11T14:21:51.338806+00:00 heroku[run.8266]: Awaiting client
2020-10-11T14:21:51.434921+00:00 heroku[run.8266]: State changed from starting to up
2020-10-11T14:21:51.639097+00:00 heroku[run.8266]: Starting process with command `rails c`
2020-10-11T14:21:52.394808+00:00 app[web.1]: Puma starting in single mode...
2020-10-11T14:21:52.394849+00:00 app[web.1]: * Version 4.3.5 (ruby 2.6.3-p62), codename: Mysterious Traveller
2020-10-11T14:21:52.394850+00:00 app[web.1]: * Min threads: 5, max threads: 5
2020-10-11T14:21:52.394850+00:00 app[web.1]: * Environment: production
2020-10-11T14:21:56.974707+00:00 app[web.1]: ! Unable to load application: Zeitwerk::NameError: expected file /app/app/mailers/previews/user_mailer_preview.rb to define constant Previews::UserMailerPreview, but didn't
2020-10-11T14:21:56.974741+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.6.0/bin/puma)
2020-10-11T14:21:56.974820+00:00 app[web.1]: Zeitwerk::NameError: expected file /app/app/mailers/previews/user_mailer_preview.rb to define constant Previews::UserMailerPreview, but didn't
2020-10-11T14:21:56.974820+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader/callbacks.rb:17:in `on_file_autoloaded'
2020-10-11T14:21:56.974821+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:17:in `block in require'
2020-10-11T14:21:56.974826+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `tap'
2020-10-11T14:21:56.974826+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
2020-10-11T14:21:56.974826+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:381:in `const_get'
2020-10-11T14:21:56.974827+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:381:in `block (2 levels) in eager_load'
2020-10-11T14:21:56.974827+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:723:in `block in ls'
2020-10-11T14:21:56.974828+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:720:in `foreach'
2020-10-11T14:21:56.974828+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:720:in `ls'
2020-10-11T14:21:56.974828+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:376:in `block in eager_load'
2020-10-11T14:21:56.974828+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:368:in `synchronize'
2020-10-11T14:21:56.974828+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:368:in `eager_load'
2020-10-11T14:21:56.974828+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:483:in `each'
2020-10-11T14:21:56.974829+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:483:in `eager_load_all'
2020-10-11T14:21:56.974829+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.1/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
2020-10-11T14:21:56.974829+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:32:in `instance_exec'
2020-10-11T14:21:56.974829+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:32:in `run'
2020-10-11T14:21:56.974830+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:61:in `block in run_initializers'
2020-10-11T14:21:56.974830+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
2020-10-11T14:21:56.974830+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2020-10-11T14:21:56.974830+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
2020-10-11T14:21:56.974831+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
2020-10-11T14:21:56.974831+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each'
2020-10-11T14:21:56.974832+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `call'
2020-10-11T14:21:56.974832+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
2020-10-11T14:21:56.974832+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
2020-10-11T14:21:56.974832+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
2020-10-11T14:21:56.974832+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:60:in `run_initializers'
2020-10-11T14:21:56.974833+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.1/lib/rails/application.rb:363:in `initialize!'
2020-10-11T14:21:56.974833+00:00 app[web.1]: /app/config/environment.rb:5:in `<top (required)>'
2020-10-11T14:21:56.974834+00:00 app[web.1]: config.ru:3:in `require_relative'
2020-10-11T14:21:56.974834+00:00 app[web.1]: config.ru:3:in `block in <main>'
2020-10-11T14:21:56.974834+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
2020-10-11T14:21:56.974834+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
2020-10-11T14:21:56.974834+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
2020-10-11T14:21:56.974835+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
2020-10-11T14:21:56.974835+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/configuration.rb:321:in `load_rackup'
2020-10-11T14:21:56.974835+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/configuration.rb:246:in `app'
2020-10-11T14:21:56.974835+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/runner.rb:155:in `load_and_bind'
2020-10-11T14:21:56.974835+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/single.rb:98:in `run'
2020-10-11T14:21:56.974835+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:172:in `run'
2020-10-11T14:21:56.974836+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/cli.rb:80:in `run'
2020-10-11T14:21:56.974836+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/bin/puma:10:in `<top (required)>'
2020-10-11T14:21:56.974836+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
2020-10-11T14:21:56.974836+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
2020-10-11T14:21:57.064221+00:00 heroku[web.1]: Process exited with status 1
2020-10-11T14:21:57.101354+00:00 heroku[web.1]: State changed from starting to crashed
2020-10-11T14:21:59.859851+00:00 heroku[run.8266]: Process exited with status 1
```

**Comment by fxn** [comment]
Let me first explain what is happening.

The problem here is that Action Mailer puts the preview path in the autoload paths only if previews are configured to be shown ([source code](https://github.com/rails/rails/blob/5699122abf7613465c62f2e50e3af017e95cb609/actionmailer/lib/action_mailer/railtie.rb#L57-L63)):

```ruby
initializer "action_mailer.set_autoload_paths" do |app|
  options = app.config.action_mailer


  if options.show_previews && options.preview_path
    ActiveSupport::Dependencies.autoload_paths << options.preview_path
  end
end
```

Since the application has the previews path under `app/mailers`, the preview code is going to be eager loaded. Since `app/mailers/previews` is NOT in the autoload paths, it's supposed to define a namespace `Previews` in `zeitwerk` mode.

This works in `classic` mode because `classic` is ambiguous about what should happen in nested autoload paths (which leads to inconsistent situations).

Why do you configure mailer previews to be in that place specifically?

**Comment by fxn** [comment]
Let me clarify a bit my question.

By putting those previews in that particular path, production mode eager loads them because `app/mailers` is in the eager load paths. Normally, you do not want to configure things that way.

So the question is, why does the application change the default path for mailer previews?
