### ISSUE TITLE
Newly created engine throws Sprockets::Rails::Helper::AssetNotPrecompiled

### ISSUE THREAD

**Issue by la-ruby** [rails/rails#40508]
### Steps to reproduce

To see this Sprockets::Rails::Helper::AssetNotPrecompiled error,
try creating an engine using commands mentioned at https://guides.rubyonrails.org/v6.0/engines.html

```
$ cd ~/parent-app
$ rails --version
Rails 6.0.3.4
$ rails plugin new blorgh --mountable
$ cd blorgh
$ perl -i -pe 's/TODO//g' blorgh.gemspec
$ bundle      
$ rails generate scaffold article title:string text:text
      invoke  active_record
      create    db/migrate/20201102080421_create_blorgh_articles.rb
      create    app/models/blorgh/article.rb
      invoke    test_unit
      create      test/models/blorgh/article_test.rb
      create      test/fixtures/blorgh/articles.yml
      invoke  resource_route
       route    resources :articles
      invoke  scaffold_controller
      create    app/controllers/blorgh/articles_controller.rb
      invoke    erb
      create      app/views/blorgh/articles
      create      app/views/blorgh/articles/index.html.erb
      create      app/views/blorgh/articles/edit.html.erb
      create      app/views/blorgh/articles/show.html.erb
      create      app/views/blorgh/articles/new.html.erb
      create      app/views/blorgh/articles/_form.html.erb
      invoke    test_unit
      create      test/controllers/blorgh/articles_controller_test.rb
      create      test/system/blorgh/articles_test.rb
      invoke    helper
      create      app/helpers/blorgh/articles_helper.rb
      invoke      test_unit
      invoke  assets
      invoke    css
      create      app/assets/stylesheets/blorgh/articles.css
      invoke  css
      create    app/assets/stylesheets/scaffold.css
$ cd ~/parent-app
$ gsed -i '2 amount Blorgh::Engine, at: "/blog"' config/routes.rb 
$ bundle exec rails server -d
$ open 'http://localhost:3000/blog/articles'
```

### Expected behavior
200 OK

### Actual behavior
![image](https://user-images.githubusercontent.com/55279023/97845851-fa532f00-1ca1-11eb-8cb2-e5910d9ce53b.png)

Stacktrace:
```
Started GET "/blog/articles" for ::1 at 2020-11-02 00:23:02 -0800
Processing by Blorgh::ArticlesController#index as HTML
  Rendering blorgh/app/views/blorgh/articles/index.html.erb within layouts/blorgh/application
  Blorgh::Article Load (0.5ms)  SELECT "blorgh_articles".* FROM "blorgh_articles"
  Rendered blorgh/app/views/blorgh/articles/index.html.erb within layouts/blorgh/application (Duration: 10.0ms | Allocations: 2954)
Completed 500 Internal Server Error in 75ms (ActiveRecord: 2.8ms | Allocations: 21647)



ActionView::Template::Error (blorgh/application.css):
     5:   <%= csrf_meta_tags %>
     6:   <%= csp_meta_tag %>
     7:
     8:   <%= stylesheet_link_tag    "blorgh/application", media: "all" %>
     9: </head>
    10: <body>
    11:

sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:372:in `raise_unless_precompiled_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:349:in `find_debug_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:230:in `block in lookup_debug_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:243:in `block in resolve_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:242:in `each'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:242:in `detect'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:242:in `resolve_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:229:in `lookup_debug_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:171:in `block in stylesheet_link_tag'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:170:in `map'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:170:in `stylesheet_link_tag'
blorgh/app/views/layouts/blorgh/application.html.erb:8
actionview (6.0.3.4) lib/action_view/base.rb:274:in `_run'
actionview (6.0.3.4) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.3.4) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.3.4) lib/action_view/template.rb:385:in `instrument_render_template'
actionview (6.0.3.4) lib/action_view/template.rb:183:in `render'
actionview (6.0.3.4) lib/action_view/renderer/template_renderer.rb:69:in `render_with_layout'
actionview (6.0.3.4) lib/action_view/renderer/template_renderer.rb:56:in `render_template'
actionview (6.0.3.4) lib/action_view/renderer/template_renderer.rb:13:in `render'
actionview (6.0.3.4) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.0.3.4) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.0.3.4) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (6.0.3.4) lib/action_view/base.rb:304:in `in_rendering_context'
actionview (6.0.3.4) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (6.0.3.4) lib/action_controller/metal/streaming.rb:218:in `_render_template'
actionview (6.0.3.4) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.0.3.4) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (6.0.3.4) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.0.3.4) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.0.3.4) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (6.0.3.4) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/Users/administrator/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
activesupport (6.0.3.4) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (6.0.3.4) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (6.0.3.4) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (6.0.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
actionpack (6.0.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
actionpack (6.0.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.3.4) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.3.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.3.4) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.3.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.3.4) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.3.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.3.4) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.3.4) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.3.4) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.3.4) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
railties (6.0.3.4) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.3.4) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.3.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.3.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.3.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.3.4) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (eeaf8473d970) lib/web_console/middleware.rb:132:in `call_app'
web-console (eeaf8473d970) lib/web_console/middleware.rb:28:in `block in call'
web-console (eeaf8473d970) lib/web_console/middleware.rb:17:in `catch'
web-console (eeaf8473d970) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (257df41cb170) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
puma (4.3.6) lib/puma/configuration.rb:228:in `call'
puma (4.3.6) lib/puma/server.rb:713:in `handle_request'
puma (4.3.6) lib/puma/server.rb:472:in `process_client'
puma (4.3.6) lib/puma/server.rb:328:in `block in run'
puma (4.3.6) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

### System configuration
Rails 6-0-stable / Rails 6.0.3.4/ gem 'rails', ref: '7474a83736'
ruby-2.7.2

There's a section in the guide called **6.5 Separate Assets & Precompiling** but
thats not applicable to me because thats for
 '.. situations where your engine's assets are not required by the host application..'

**Comment by abhaynikam** [comment]
@la-ruby You need to add `//= link blorgh/application.css` in the `app/assets/config/manifest.js`and **restart** the server.

**Comment by la-ruby** [comment]
> you need to add...

thanks, that should fix it (for now).
should the docs mention it though? I checked a bunch of rails versions, and the error comes up
in rails gem versions labeled bad:

6.0.3.4 bad
6.0.1 bad
6.0.1.rc1 bad
6.0.0 good

**Comment by pagejess009** [comment]
Ok, will do that.



On Nov. 2, 2020 at 21:21, la-ruby <notifications@github.com> wrote:

you need to add...

thanks, that should fix it (for now).
should the docs mention it though? I checked a bunch of rails versions, and
the error comes up
in rails gem versions labeled bad:

6.0.3.4 bad
6.0.1 bad
6.0.1.rc1 bad
6.0.0 good

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rails/rails/issues/40508#issuecomment-720869951>, or
unsubscribe

**Comment by rmcbarreto** [comment]
Hi, I am opening this issue because I followed the docs and had exactly the same problem.

> @la-ruby You need to add `//= link blorgh/application.css` in the `app/assets/config/manifest.js`and **restart** the server.

This trick solved the issue but is this normal behavior? If it is, shouldn't it be in the docs as @la-ruby mentioned? 

I am using ruby 3.0.0 and rails 6.1.3.2.

**Comment by zzak** [comment]
@rmcbarreto @la-ruby Is this still an issue with the current docs? Then we should consider fixing them 🙏

**Comment by rmcbarreto** [comment]
@zzak Yes, I followed the latest docs and this fix is not in there.

**Comment by zzak** [comment]
@rmcbarreto Could you elaborate? It sounds like the issue was fixed but just to be sure.

Would you mind creating a step-by-step to reproduce the issue? 🙇

**Comment by rmcbarreto** [comment]
I followed the rails engine [guide](https://guides.rubyonrails.org/engines.html):
1- Created a new engine `rails plugin new blorgh --mountable` and generated the model as the guide describes.
2- Created a new rails app like in the guide `rails new unicorn` and added the engine to the gem file and mounted it in the routes.
3- Generated the migrations and started the server. The rails default page shows up but when I access the engine path (/blog) the server throws `Sprockets::Rails::Helper::AssetNotPrecompiled`.
4- I added the line `//= link blorgh_manifest.js` to the rails unicorn manifest.js file (app/assets/config/manifest.js) and the error disappears (or add `//= link blorgh/application.css` but I prefer to add the engine manifest and inside the engine manifest add all other css and js files).

If I follow the same process but instead of creating an engine with namespace as I have done, create an engine without namespace `rails plugin new blorgh --full` the `AssetNotPrecompiled` error is not thrown.

The problem is that in the docs they suggest creating an engine with namespace and do not mention the necessity to add `//= link blorgh_manifest.js` to the rails app manifest.js file. For a beginner in rails engine (like me) is difficult when following the tutorial step-by-step an error is thrown and you have done nothing wrong.

**Comment by zzak** [comment]
@rmcbarreto What is the difference between `--mountable` and `--full`? That might help lead us to some answers.

**Comment by rmcbarreto** [comment]
@zzak, as de documentation explains the `--mountable` creates a namespace for the engine, as the `--full` does not create a namespace, so the files are shared between the engine and the rails app and should not have the same name files in both engine and rails app (example: the engine has `application_controller.rb` the rails should not have the `application_controller.rb`or it will have conflict).
