### ISSUE TITLE
undefined method `email_verification' for UserMailer:Class

### ISSUE THREAD

**Issue by dmurawsky** [rails/rails#40607]
### Steps to reproduce
Not sure how to reproduce. We just started getting this error two days ago.

### Expected behavior
Expected no error or a better error message

### Actual behavior
Started getting this error without changes to how we're using ActionMailer

### System configuration
**Rails version**:
`~> 5.2.0`
**Ruby version**:
`~> 2.6.2`

**Comment by tahsin352** [comment]
Please provide code sample using bundler/inliner.

**Comment by eileencodes** [comment]
This sounds like an application level error and not a framework level error since Rails doesn't define the `email_verification` method, likely your application does. At the moment there isn't enough information here to determine what's wrong beyond that.

If you still think this is a framework level bug please provide a reproduction - either in the form of a new Rails application or a demo script. If that's not possible at stacktrace and the code of your UserMailer (with any IP removed) would be helpful as well.

For help with your application please use StackOverflow, we reserve the issues tracker for framework level bugs.

**Comment by dmurawsky** [comment]
Yeah, I hated posting so little info but that's really all I have. There is no instance of `email_verification` in our codebase so it must be coming from a gem but I can't find any gem being used besides ActionMailer

**Comment by eileencodes** [comment]
The stacktrace should tell you where it's coming from. Can you paste it here?

**Comment by dmurawsky** [comment]
```
NoMethodError: undefined method `email_verification' for UserMailer:Class
  from action_mailer/base.rb:582:in `method_missing'
  from action_mailer/delivery_job.rb:16:in `public_send'
  from action_mailer/delivery_job.rb:16:in `perform'
  from active_job/execution.rb:39:in `block in perform_now'
  from active_support/callbacks.rb:109:in `block in run_callbacks'
  from raven/integrations/rails/active_job.rb:18:in `capture_and_reraise_with_sentry'
  from raven/integrations/rails/active_job.rb:12:in `block (2 levels) in included'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from new_relic/agent/instrumentation/active_job.rb:53:in `perform'
  from new_relic/agent/instrumentation/active_job.rb:23:in `block (4 levels) in <main>'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from i18n.rb:313:in `with_locale'
  from active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
  from active_support/notifications.rb:168:in `block in instrument'
  from active_support/notifications/instrumenter.rb:23:in `instrument'
  from active_support/notifications.rb:168:in `instrument'
  from active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
  from active_job/logging.rb:46:in `block in tag_logger'
  from active_support/tagged_logging.rb:71:in `block in tagged'
  from active_support/tagged_logging.rb:28:in `tagged'
  from active_support/tagged_logging.rb:71:in `tagged'
  from active_job/logging.rb:46:in `tag_logger'
  from active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_support/callbacks.rb:136:in `run_callbacks'
  from active_job/execution.rb:38:in `perform_now'
  from active_job/execution.rb:24:in `block in execute'
  from active_support/callbacks.rb:109:in `block in run_callbacks'
  from active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
  from active_support/execution_wrapper.rb:87:in `wrap'
  from active_support/reloader.rb:73:in `block in wrap'
  from active_support/execution_wrapper.rb:83:in `wrap'
  from active_support/reloader.rb:72:in `wrap'
  from active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_support/callbacks.rb:136:in `run_callbacks'
  from active_job/execution.rb:22:in `execute'
  from active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
  from sidekiq/processor.rb:192:in `execute_job'
  from sidekiq/processor.rb:165:in `block (2 levels) in process'
  from sidekiq/middleware/chain.rb:128:in `block in invoke'
  from new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
  from new_relic/agent/instrumentation/controller_instrumentation.rb:376:in `perform_action_with_newrelic_trace'
  from new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from raven/integrations/sidekiq.rb:9:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/chain.rb:133:in `invoke'
  from sidekiq/processor.rb:164:in `block in process'
  from sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
  from sidekiq/job_retry.rb:109:in `local'
  from sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
  from sidekiq/rails.rb:43:in `block in call'
  from active_support/execution_wrapper.rb:87:in `wrap'
  from active_support/reloader.rb:73:in `block in wrap'
  from active_support/execution_wrapper.rb:87:in `wrap'
  from active_support/reloader.rb:72:in `wrap'
  from sidekiq/rails.rb:42:in `call'
  from sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
  from sidekiq/processor.rb:250:in `stats'
  from sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
  from sidekiq/job_logger.rb:8:in `call'
  from sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
  from sidekiq/job_retry.rb:74:in `global'
  from sidekiq/processor.rb:125:in `block in dispatch'
  from sidekiq/logging.rb:48:in `with_context'
  from sidekiq/logging.rb:42:in `with_job_hash_context'
  from sidekiq/processor.rb:124:in `dispatch'
  from sidekiq/processor.rb:163:in `process'
  from sidekiq/processor.rb:83:in `process_one'
  from sidekiq/processor.rb:71:in `run'
  from sidekiq/util.rb:16:in `watchdog'
  from sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by dmurawsky** [comment]
Any other feedback on anything is very welcome. I feel like this stack trace shouldn't be so deep.

**Comment by eileencodes** [comment]
It's hitting method_missing so it definitely seems like there's somewhere your app is calling `email_verification`. I think your problem lies in the i18n.rb file.

The trace confirms this is an application level issue and since we reserve the issues tracker for framework bugs I think it's best to move this to StackOverflow where someone else might be able to devote more time to helping. Good luck!
