### ISSUE TITLE
Rails 6.1.0.rc1 Error: undefined method `deprecate' for Rails::DBConsole:Class

### ISSUE THREAD

**Issue by ChrisCPO** [rails/rails#40634]
### Steps to reproduce
tested on two different apps just update to Rails 6.1.0.rc1 
console command `rails db` results in error.

### Expected behavior
open console to local database, in both setups psql console 

### Actual behavior
Results in error: 
```
 % rails db
[WARNING] Could not load command "rails/commands/dbconsole/dbconsole_command". Error: undefined method `deprecate' for Rails::DBConsole:Class.
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0.rc1/lib/rails/commands/dbconsole/dbconsole_command.rb:95:in `<class:DBConsole>'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0.rc1/lib/rails/commands/dbconsole/dbconsole_command.rb:7:in `<module:Rails>'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0.rc1/lib/rails/commands/dbconsole/dbconsole_command.rb:6:in `<main>'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0.rc1/lib/active_support/dependencies.rb:332:in `block in require'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0.rc1/lib/active_support/dependencies.rb:299:in `load_dependency'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0.rc1/lib/active_support/dependencies.rb:332:in `require'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0.rc1/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0.rc1/lib/rails/command/behavior.rb:40:in `each'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0.rc1/lib/rails/command/behavior.rb:40:in `block in lookup'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0.rc1/lib/rails/command/behavior.rb:39:in `each'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0.rc1/lib/rails/command/behavior.rb:39:in `lookup'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0.rc1/lib/rails/command.rb:76:in `find_by_namespace'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0.rc1/lib/rails/command.rb:48:in `invoke'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.0.rc1/lib/rails/commands.rb:18:in `<main>'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0.rc1/lib/active_support/dependencies.rb:332:in `block in require'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0.rc1/lib/active_support/dependencies.rb:299:in `load_dependency'
.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.0.rc1/lib/active_support/dependencies.rb:332:in `require'
bin/rails:4:in `<main>'
rails aborted!
Don't know how to build task 'dbconsole' (See the list of available tasks with `rails --tasks`)
```

### System configuration
**Rails version**: 6.1.0.rc1

**Ruby version**: 2.6.6

**Comment by eugeneius** [comment]
Thanks for the report! This was already flagged in https://github.com/rails/rails/issues/40575, it'll be fixed in the next release.

**Comment by ChrisCPO** [comment]
cool
