### ISSUE TITLE
ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by Paulpatou** [rails/rails#40649]
### Actual behavior
I make an AJAX request in javascript of type POST, in which I send all the fields of my form to the controller.

Here is my javascript code
```
$.ajax({
url: "/VEILLE/saisie/sauvegarde_author",
type: 'POST',
data: { ch: form.serialize() },
dataType: "html",
success: function (ht) {
... // whatever I need to do after the controller has processed my form
}
});
```
Here's how i declared my form
`<%= form_for :prod_page_2 do |p| %> <% end %>`

### The error 
```
ActionController::InvalidAuthenticityToken in SaisieProduitController#sauvAuthor

ActionController::InvalidAuthenticityToken
Extracted source (around line #215):

#213 
#214         def handle_unverified_request
*215           raise ActionController::InvalidAuthenticityToken
#216         end
#217       end
#218     end

Extracted source (around line #247):

#245 
#246       def handle_unverified_request # :doc:
*247         forgery_protection_strategy.new(self).handle_unverified_request
#248       end
#249 
#250       #:nodoc:

Extracted source (around line #242):

#240             end
#241           end
*242           handle_unverified_request
#243         end
#244       end
#245 


Rails.root: /home/user/Documents/Sites/ihm_web

Framework Trace
actionpack (6.0.3.1) lib/action_controller/metal/request_forgery_protection.rb:215:in `handle_unverified_request'
actionpack (6.0.3.1) lib/action_controller/metal/request_forgery_protection.rb:247:in `handle_unverified_request'
actionpack (6.0.3.1) lib/action_controller/metal/request_forgery_protection.rb:242:in `verify_authenticity_token'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:428:in `block in make_lambda'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
actionpack (6.0.3.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:201:in `block in halting'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:513:in `each'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:110:in `block in run_callbacks'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:139:in `run_callbacks'
actionpack (6.0.3.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.3.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
mongoid (7.1.5) lib/mongoid/railties/controller_runtime.rb:22:in `process_action'
actionpack (6.0.3.1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.3.1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.3.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.3.1) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.3.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.3.1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.1) lib/rails/rack/logger.rb:28:in `call'
silencer (1.0.1) lib/silencer/rails/logger.rb:41:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.1) lib/rails/engine.rb:527:in `call'
thin (1.7.2) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.7.2) lib/thin/connection.rb:84:in `catch'
thin (1.7.2) lib/thin/connection.rb:84:in `pre_process'
thin (1.7.2) lib/thin/connection.rb:53:in `process'
thin (1.7.2) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.2.7) lib/eventmachine.rb:195:in `run_machine'
eventmachine (1.2.7) lib/eventmachine.rb:195:in `run'
thin (1.7.2) lib/thin/backends/base.rb:73:in `start'
thin (1.7.2) lib/thin/server.rb:162:in `start'
rack (2.2.3) lib/rack/handler/thin.rb:22:in `run'
rack (2.2.3) lib/rack/server.rb:327:in `start'
railties (6.0.3.1) lib/rails/commands/server/server_command.rb:39:in `start'
railties (6.0.3.1) lib/rails/commands/server/server_command.rb:147:in `block in perform'
railties (6.0.3.1) lib/rails/commands/server/server_command.rb:138:in `tap'
railties (6.0.3.1) lib/rails/commands/server/server_command.rb:138:in `perform'
thor (1.0.1) lib/thor/command.rb:27:in `run'
thor (1.0.1) lib/thor/invocation.rb:127:in `invoke_command'
thor (1.0.1) lib/thor.rb:392:in `dispatch'
railties (6.0.3.1) lib/rails/command/base.rb:69:in `perform'
railties (6.0.3.1) lib/rails/command.rb:46:in `invoke'
railties (6.0.3.1) lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Full Trace
actionpack (6.0.3.1) lib/action_controller/metal/request_forgery_protection.rb:215:in `handle_unverified_request'
actionpack (6.0.3.1) lib/action_controller/metal/request_forgery_protection.rb:247:in `handle_unverified_request'
actionpack (6.0.3.1) lib/action_controller/metal/request_forgery_protection.rb:242:in `verify_authenticity_token'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:428:in `block in make_lambda'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
actionpack (6.0.3.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:201:in `block in halting'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:513:in `each'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:110:in `block in run_callbacks'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:139:in `run_callbacks'
actionpack (6.0.3.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.3.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.3.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
mongoid (7.1.5) lib/mongoid/railties/controller_runtime.rb:22:in `process_action'
actionpack (6.0.3.1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.3.1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.3.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.3.1) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.3.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.3.1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.1) lib/rails/rack/logger.rb:28:in `call'
silencer (1.0.1) lib/silencer/rails/logger.rb:41:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.1) lib/rails/engine.rb:527:in `call'
thin (1.7.2) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.7.2) lib/thin/connection.rb:84:in `catch'
thin (1.7.2) lib/thin/connection.rb:84:in `pre_process'
thin (1.7.2) lib/thin/connection.rb:53:in `process'
thin (1.7.2) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.2.7) lib/eventmachine.rb:195:in `run_machine'
eventmachine (1.2.7) lib/eventmachine.rb:195:in `run'
thin (1.7.2) lib/thin/backends/base.rb:73:in `start'
thin (1.7.2) lib/thin/server.rb:162:in `start'
rack (2.2.3) lib/rack/handler/thin.rb:22:in `run'
rack (2.2.3) lib/rack/server.rb:327:in `start'
railties (6.0.3.1) lib/rails/commands/server/server_command.rb:39:in `start'
railties (6.0.3.1) lib/rails/commands/server/server_command.rb:147:in `block in perform'
railties (6.0.3.1) lib/rails/commands/server/server_command.rb:138:in `tap'
railties (6.0.3.1) lib/rails/commands/server/server_command.rb:138:in `perform'
thor (1.0.1) lib/thor/command.rb:27:in `run'
thor (1.0.1) lib/thor/invocation.rb:127:in `invoke_command'
thor (1.0.1) lib/thor.rb:392:in `dispatch'
railties (6.0.3.1) lib/rails/command/base.rb:69:in `perform'
railties (6.0.3.1) lib/rails/command.rb:46:in `invoke'
railties (6.0.3.1) lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'



Request parameters
{"ch"=>"utf8=%E2%9C%93&authenticity_token=%2BFg%2Fg6WfwOzsIUCJxpJOXmvJCVkxbmRlCpXG7lPQViDZ4ApxVkbK0wSDYj4eum4KeKQA8ePOpxJ6YTxwvnGVtg%3D%3D&prod_page_2%5Bid%5D=byc620201119094908&prod_page_2%5Bpltf%5D=60&prod_page_2%5BtypGp%5D=5&prod_page_2%5BtypAct%5D=2&prod_page_2%5BidAuth%5D=138538&prod_page_2%5Blogin%5D=QhOTNFTUda&prod_page_2%5Bnom%5D=https%3A%2F%2Fwww.4shared.com%2Foffice%2FQhOTNFTUda%2Fnbaa138.html&prod_page_2%5BcptePos%5D=1&prod_page_2%5BcpteUrl%5D=https%3A%2F%2Fwww.4shared.com%2Foffice%2FQhOTNFTUda%2Fnbaa138.html&prod_page_2%5BtypAct%5D=&prod_page_2%5BtypAct%5D=2&prod_page_2%5Bdate%5D=2020-11-05&prod_page_2%5Bheure%5D=02%3A05&prod_page_2%5BprodUrl%5D=jhljlk"}

Session dump
_csrf_token: "KBWHbDXFdMMlrkbaPVcCVD4NDsOC7gxUoh3JqW4rxSw="
session_id: "01a3daa146335e99948ef94f1880a8f8"

Env dump
GATEWAY_INTERFACE: "CGI/1.2"
HTTP_ACCEPT: "text/html, */*; q=0.01"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3"
HTTP_ORIGIN: "http://127.0.0.1:3000"
HTTP_VERSION: "HTTP/1.1"
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "127.0.0.1"
SERVER_NAME: "127.0.0.1"
SERVER_PROTOCOL: "HTTP/1.1"

Response headers
None
```

### Expected behavior
I expect the routed action in my controller to start processing my form and render an html partial at the end.

### System configuration
**Rails version**: Ruby 2.7.0p0

**Ruby version**: Rails 6.0.3.1

**Comment by p8** [comment]
You are missing the CSRF-token:
https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/actionview/app/assets/javascripts/rails-ujs/utils/csrf.coffee#L18
See:
https://edgeguides.rubyonrails.org/working_with_javascript_in_rails.html#cross-site-request-forgery-csrf-token-in-ajax

**Comment by Paulpatou** [comment]
Thanks a lot for the help, it works
