### ISSUE TITLE
PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block

### ISSUE THREAD

**Issue by thebravoman** [rails/rails#40699]
### Steps to reproduce
This started occurring recently. Can not understand why
I am trying to track it down but I can't for now and similar problems on the internet are not very informative.
Even if this ia a problem with another gem and not active record itself It should be great if ActiveRecord could provide more information about the error. Like what is the invalid sql for example.

### Expected behavior
I am doing user.destroy. This sends and email for destroying the user.

### Actual behavior
```
     ActiveRecord::StatementInvalid:
       PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `async_exec'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `block (2 levels) in query'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `block in query'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `query'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/postgresql_adapter.rb:820:in `column_definitions'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:114:in `columns'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/schema_cache.rb:76:in `columns'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/schema_cache.rb:82:in `columns_hash'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/model_schema.rb:488:in `load_schema!'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/attributes.rb:247:in `load_schema!'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/attribute_decorators.rb:50:in `load_schema!'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/model_schema.rb:478:in `block in load_schema'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/model_schema.rb:475:in `load_schema'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/model_schema.rb:362:in `attribute_types'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/attribute_methods.rb:171:in `has_attribute?'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/inheritance.rb:55:in `new'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/ahoy_email-1.1.0/lib/ahoy_email.rb:42:in `block in <module:AhoyEmail>'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/ahoy_email-1.1.0/lib/ahoy_email/tracker.rb:14:in `block in perform'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/safely_block-0.3.0/lib/safely/core.rb:50:in `safely'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/ahoy_email-1.1.0/lib/ahoy_email/tracker.rb:10:in `perform'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/ahoy_email-1.1.0/lib/ahoy_email/observer.rb:4:in `delivered_email'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/mail-2.7.1/lib/mail/mail.rb:229:in `block in inform_observers'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/mail-2.7.1/lib/mail/mail.rb:228:in `each'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/mail-2.7.1/lib/mail/mail.rb:228:in `inform_observers'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/mail-2.7.1/lib/mail/message.rb:244:in `inform_observers'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/mail-2.7.1/lib/mail/message.rb:264:in `deliver'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/actionmailer-6.0.3.3/lib/action_mailer/message_delivery.rb:115:in `block in deliver_now'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/actionmailer-6.0.3.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/actionmailer-6.0.3.3/lib/action_mailer/message_delivery.rb:114:in `deliver_now'
     # ./app/models/user.rb:449:in `send_account_deletion_email'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:428:in `block in make_lambda'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:181:in `block (2 levels) in halting_and_conditional'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:604:in `catch'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:604:in `block in default_terminator'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:182:in `block in halting_and_conditional'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:513:in `each'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:513:in `invoke_before'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:134:in `run_callbacks'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/acts_as_paranoid-0.6.3/lib/acts_as_paranoid/core.rb:137:in `block in destroy!'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/transactions.rb:212:in `transaction'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/acts_as_paranoid-0.6.3/lib/acts_as_paranoid/core.rb:136:in `destroy!'
     # ./spec/models/author_spec.rb:78:in `block (2 levels) in <top (required)>'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:318:in `load'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:318:in `block in load'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:318:in `load'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # -e:1:in `<main>'
     # ------------------
     # --- Caused by: ---
     # PG::InFailedSqlTransaction:
     #   ERROR:  current transaction is aborted, commands ignored until end of transaction block
     #   /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `async_exec'

```
Here is the last sql executed in

```
# database_statements
# Queries the database and returns the results in an Array-like object
        def query(sql, name = nil) #:nodoc:
          materialize_transactions

          log(sql, name) do
            ActiveSupport::Dependencies.interlock.permit_concurrent_loads do
              puts ""
              puts sql
              result_as_array @connection.async_exec(sql)
            end
          end
        end
```

```

SELECT a.attname, format_type(a.atttypid, a.atttypmod),
       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
       c.collname, col_description(a.attrelid, a.attnum) AS comment
  FROM pg_attribute a
  LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
  LEFT JOIN pg_type t ON a.atttypid = t.oid
  LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
 WHERE a.attrelid = '"ahoy_messages"'::regclass
   AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum

```

Although I understand the the problem is not with the last but with one of the previous, but which one.

### System configuration
**Rails version**: 6.0.3.3 (I have also tried with 6.0.3.4)

**Ruby version**: 2.6.5

Update 2:
I've reduced and removed acts_as_paranoid as dependency. It still occurs.

Update 3:
I've removed ahoy and now It works. I quest it is a problem with ahoy. 
Still not sure until resolved a probably active_record could help by telling which is the query with a problem. 

Update 4: 
```
config.use_transactional_fixtures = false 
```
this is set to false.
Setting it to true/false or removing it does not have effect

Update 5:
One more exception, with a different stacktrace, same exception involving ahoy
```
    ActiveRecord::StatementInvalid:
       PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `exec_params'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `block (2 levels) in exec_no_cache'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:674:in `block in exec_no_cache'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:673:in `exec_no_cache'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:656:in `execute_and_clear'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `exec_query'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:135:in `exec_insert'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:132:in `exec_insert'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:166:in `insert'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:375:in `_insert_record'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:932:in `_create_record'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/counter_cache.rb:166:in `_create_record'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/locking/optimistic.rb:70:in `_create_record'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/attribute_methods/dirty.rb:211:in `_create_record'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/callbacks.rb:331:in `block in _create_record'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:101:in `run_callbacks'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:825:in `_run_create_callbacks'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/callbacks.rb:331:in `_create_record'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/timestamp.rb:110:in `_create_record'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:905:in `create_or_update'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/callbacks.rb:327:in `block in create_or_update'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:135:in `run_callbacks'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/callbacks.rb:327:in `create_or_update'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/timestamp.rb:128:in `create_or_update'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:503:in `save!'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:53:in `save!'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:318:in `block in save!'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:212:in `transaction'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:318:in `save!'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/suppressor.rb:48:in `save!'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/ahoy_email-1.1.0/lib/ahoy_email.rb:59:in `block in <module:AhoyEmail>'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/ahoy_email-1.1.0/lib/ahoy_email/tracker.rb:14:in `block in perform'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/safely_block-0.3.0/lib/safely/core.rb:50:in `safely'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/ahoy_email-1.1.0/lib/ahoy_email/tracker.rb:10:in `perform'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/ahoy_email-1.1.0/lib/ahoy_email/observer.rb:4:in `delivered_email'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/mail-2.7.1/lib/mail/mail.rb:229:in `block in inform_observers'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/mail-2.7.1/lib/mail/mail.rb:228:in `each'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/mail-2.7.1/lib/mail/mail.rb:228:in `inform_observers'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/mail-2.7.1/lib/mail/message.rb:244:in `inform_observers'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/mail-2.7.1/lib/mail/message.rb:264:in `deliver'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/actionmailer-6.0.3.4/lib/action_mailer/message_delivery.rb:115:in `block in deliver_now'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/actionmailer-6.0.3.4/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/actionmailer-6.0.3.4/lib/action_mailer/message_delivery.rb:114:in `deliver_now'
     # ./app/models/user.rb:453:in `send_account_deletion_email'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:428:in `block in make_lambda'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:181:in `block (2 levels) in halting_and_conditional'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:604:in `catch'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:604:in `block in default_terminator'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:182:in `block in halting_and_conditional'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:513:in `each'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:513:in `invoke_before'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:134:in `run_callbacks'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:825:in `_run_destroy_callbacks'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/callbacks.rb:309:in `destroy'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:310:in `block in destroy'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:212:in `transaction'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:310:in `destroy'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:551:in `destroy!'
     # ./spec/models/user_spec.rb:154:in `block (3 levels) in <top (required)>'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
     # /home/user/.rvm/gems/ruby-2.6.5/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'

```

**Comment by wilg** [comment]
I am getting a similar error, except I think it involves Scout APM

**Comment by wilg** [comment]
Perhaps it involves rescuing a DB exception: https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html#module-ActiveRecord::Transactions::ClassMethods-label-Exception+handling+and+rolling+back
https://stackoverflow.com/questions/21138207/activerecordstatementinvalid-pg-infailedsqltransaction

**Comment by espen** [comment]
This can be a bit tricky to debug but check if you are doing AR transactions with rescuing DB exceptions as mentioned. This is not a Rails bug so this issue should be closed. Perhaps try to create an issue on the mentioned gem if you think the issue is there, alternatively try asking on StackOverflow.

**Comment by thebravoman** [comment]
This is not a Rails bug. This is clear. What I am think of is how could Rails help and " if ActiveRecord could provide more information about the error. ". This would make it easier to debug what the error is, in which gem it occurs, and could facilitate the debug process.

Because now from this error I am not sure which gem is causing the error and even what the error is.

**Comment by espen** [comment]
@thebravoman if you look in the trace you will see which gem is causing the error (ahoy_email). Rails is just relaying the database error.
