### ISSUE TITLE
Rails 5.2.4.4 and Ruby 3.0.0.preview1: Error loading ActionDispatch::Static middleware

### ISSUE THREAD

**Issue by johnmaxwell** [rails/rails#40741]
### Steps to reproduce

```
rbenv shell 2.7.2
rails _5.2.4.4_ new RailsFiveInstall
cd RailsFiveInstall
rbenv local 3.0.0-preview1
rbenv shell 3.0.0-preview1
(edit Gemfile to use "ruby '3.0.0'")
bundle update ruby_dep listen
bundle exec rails c
```

### Expected behavior
After a new app is successfully created under Ruby 2.7.2 and migrated to 3.0.0.preview1, the Rails console should be started under Ruby 3. 

### Actual behavior
The following error and stack trace are generated. Looking into it, it appears to be related how ActionDispatch ::MiddlewareStack::Middleware builds the middleware chain, specifically when initializing the ActionDispatch::Static middleware. 

Could this be related to passing args using `*args` to a method with keyword params under Ruby 3? In my case, args is: `["/Users/john/work/RailsFiveInstall/public", {:index=>"index", :headers=>{}}]` and block is `nil`

https://github.com/rails/rails/blob/2a3f8a29e5d7d17a0448fa47fd756c8d11b175b1/actionpack/lib/action_dispatch/middleware/stack.rb#L37
https://github.com/rails/rails/blob/2a3f8a29e5d7d17a0448fa47fd756c8d11b175b1/actionpack/lib/action_dispatch/middleware/static.rb#L111

```
/Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/static.rb:111:in `initialize': wrong number of arguments (given 3, expected 2) (ArgumentError)
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/stack.rb:37:in `new'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/stack.rb:37:in `build'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/stack.rb:101:in `block in build'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/stack.rb:101:in `each'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/stack.rb:101:in `inject'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/stack.rb:101:in `build'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/engine.rb:510:in `block in app'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/engine.rb:506:in `synchronize'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/engine.rb:506:in `app'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'
	from /Users/john/work/RailsFiveInstall/config/environment.rb:5:in `<main>'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:106:in `preload'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /Users/john/.rbenv/versions/3.0.0-preview1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from -e:1:in `<main>'
```

### System configuration
**Rails version**: 5.2.4.4

**Ruby version**: 3.0.0.preview1

**Comment by rafaelfranca** [comment]
Thank you for the issue but Rails 5.2 is not supported for bug fixes anymore. It means that it will not support Ruby 3. You must upgrade Rails if you want to use Ruby 3.
