### ISSUE TITLE
NoMethodError - undefined method `[]' for nil:NilClass:

### ISSUE THREAD

**Issue by jollyoldsaintnixon** [rails/rails#40763]
### Steps to reproduce

Model.rb:
`has_one_attached :photo`

Controller#method:
```
model.photo.attach(params[:photo]) if params[:photo]
model.save
```

params[:photo] within byebug REPL:
`#<ActionDispatch::Http::UploadedFile:0x000056167566b5c0 @tempfile=#<Tempfile:/tmp/RackMultipart20201207-5397-zruzs9.jpeg>, @original_filename="striped_skunk_spotted_skunk_comparison.jpeg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"photo\"; filename=\"striped_skunk_spotted_skunk_comparison.jpeg\"\r\nContent-Type: image/jpeg\r\n">`

storage.yml:
```
amazon_dev:
  service: S3
  access_key_id: <%= Rails.application.credentials.aws[:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials.aws[:secret_access_key] %>
  region: <%= Rails.application.credentials.aws[:region] %>
  bucket: <%= Rails.application.credentials.aws[:dev][:bucket] %>
```

development.rb:
`config.active_storage.service = :amazon_dev`

schema.rb:
```
  create_table "active_storage_attachments", force: :cascade do |t|
    t.string "name", null: false
    t.string "record_type", null: false
    t.bigint "record_id", null: false
    t.bigint "blob_id", null: false
    t.datetime "created_at", null: false
    t.index ["blob_id"], name: "index_active_storage_attachments_on_blob_id"
    t.index ["record_type", "record_id", "name", "blob_id"], name: "index_active_storage_attachments_uniqueness", unique: true
  end

  create_table "active_storage_blobs", force: :cascade do |t|
    t.string "key", null: false
    t.string "filename", null: false
    t.string "content_type"
    t.text "metadata"
    t.bigint "byte_size", null: false
    t.string "checksum", null: false
    t.datetime "created_at", null: false
    t.index ["key"], name: "index_active_storage_blobs_on_key", unique: true
  end

  add_foreign_key "active_storage_attachments", "active_storage_blobs", column: "blob_id"
```

credentials.yml:
```
aws:
  access_key_id: "<s3_user_id>"
  secret_access_key: "<s3_user_key>"
  region: "<bucket's_region>"
  dev:
    bucket: "<my_bucket>"

secret_key_base: <secret_key_base>
```

Puma output: 
```
  ↳ app/controllers/api/model/modelss_controller.rb:78:in `upload_picture'
   (0.7ms)  ROLLBACK
  ↳ app/controllers/api/model/models_controller.rb:78:in `upload_picture'
Completed 500 Internal Server Error in 415079ms (ActiveRecord: 16.5ms | Allocations: 135344)



NoMethodError - undefined method `[]' for nil:NilClass:
  (erb):32:in `<main>'
  app/controllers/api/model/models_controller.rb:78:in `upload_picture'
```

Stack trace after uncommenting `Rails.backtrace_cleaner.remove_silencers!` in initializers/backtrace_silencers:
```
NoMethodError - undefined method `[]' for nil:NilClass:
  (erb):6:in `<main>'
  /home/josn/.rbenv/versions/2.7.0/lib/ruby/2.7.0/erb.rb:905:in `result'
  activestorage (6.0.3.4) lib/active_storage/engine.rb:111:in `block (2 levels) in <class:Engine>'
  activesupport (6.0.3.4) lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
  activesupport (6.0.3.4) lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
  activesupport (6.0.3.4) lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
  activesupport (6.0.3.4) lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
  activesupport (6.0.3.4) lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
  activestorage (6.0.3.4) app/models/active_storage/blob.rb:291:in `<main>'
  bootsnap (1.5.1) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  bootsnap (1.5.1) lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  bootsnap (1.5.1) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  bootsnap (1.5.1) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  zeitwerk (2.4.2) lib/zeitwerk/kernel.rb:26:in `require'
  activesupport (6.0.3.4) lib/active_support/inflector/methods.rb:284:in `block in constantize'
  activesupport (6.0.3.4) lib/active_support/inflector/methods.rb:280:in `constantize'
  activesupport (6.0.3.4) lib/active_support/inflector/methods.rb:325:in `safe_constantize'
  activesupport (6.0.3.4) lib/active_support/dependencies/zeitwerk_integration.rb:23:in `safe_constantize'
  activerecord (6.0.3.4) lib/active_record/inheritance.rb:198:in `block in compute_type'
  activerecord (6.0.3.4) lib/active_record/inheritance.rb:197:in `compute_type'
  activerecord (6.0.3.4) lib/active_record/reflection.rb:424:in `compute_class'
  activerecord (6.0.3.4) lib/active_record/reflection.rb:769:in `klass'
  activerecord (6.0.3.4) lib/active_record/associations/association.rb:140:in `klass'
  activerecord (6.0.3.4) lib/active_record/associations/association.rb:240:in `find_target?'
  activerecord (6.0.3.4) lib/active_record/associations/association.rb:164:in `load_target'
  activerecord (6.0.3.4) lib/active_record/associations/association.rb:65:in `reload'
  activerecord (6.0.3.4) lib/active_record/associations/singular_association.rb:9:in `reader'
  activerecord (6.0.3.4) lib/active_record/associations/builder/association.rb:100:in `profile_picture_blob'
  activestorage (6.0.3.4) lib/active_storage/attached/changes/create_one.rb:42:in `find_attachment'
  activestorage (6.0.3.4) lib/active_storage/attached/changes/create_one.rb:38:in `find_or_build_attachment'
  activestorage (6.0.3.4) lib/active_storage/attached/changes/create_one.rb:15:in `attachment'
  activestorage (6.0.3.4) lib/active_storage/attached/changes/create_one.rb:32:in `save'
  activestorage (6.0.3.4) lib/active_storage/attached/model.rb:54:in `block in has_one_attached'
  activesupport (6.0.3.4) lib/active_support/callbacks.rb:428:in `block in make_lambda'
  activesupport (6.0.3.4) lib/active_support/callbacks.rb:238:in `block in halting_and_conditional'
  activesupport (6.0.3.4) lib/active_support/callbacks.rb:517:in `block in invoke_after'
  activesupport (6.0.3.4) lib/active_support/callbacks.rb:517:in `invoke_after'
  activesupport (6.0.3.4) lib/active_support/callbacks.rb:136:in `run_callbacks'
  activesupport (6.0.3.4) lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
  activerecord (6.0.3.4) lib/active_record/callbacks.rb:327:in `create_or_update'
  activerecord (6.0.3.4) lib/active_record/timestamp.rb:128:in `create_or_update'
  activerecord (6.0.3.4) lib/active_record/persistence.rb:470:in `save'
  activerecord (6.0.3.4) lib/active_record/validations.rb:47:in `save'
  activerecord (6.0.3.4) lib/active_record/transactions.rb:314:in `block in save'
  activerecord (6.0.3.4) lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
  activerecord (6.0.3.4) lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
  activerecord (6.0.3.4) lib/active_record/transactions.rb:212:in `transaction'
  activerecord (6.0.3.4) lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
  activerecord (6.0.3.4) lib/active_record/transactions.rb:314:in `save'
  activerecord (6.0.3.4) lib/active_record/suppressor.rb:44:in `save'
  activerecord (6.0.3.4) lib/active_record/persistence.rb:621:in `block in update'
  activerecord (6.0.3.4) lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
  activerecord (6.0.3.4) lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
  activerecord (6.0.3.4) lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
  activesupport (6.0.3.4) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
  activesupport (6.0.3.4) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
  activesupport (6.0.3.4) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
  activerecord (6.0.3.4) lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
  activerecord (6.0.3.4) lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
  activerecord (6.0.3.4) lib/active_record/transactions.rb:212:in `transaction'
  activerecord (6.0.3.4) lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
  activerecord (6.0.3.4) lib/active_record/persistence.rb:619:in `update'
  activestorage (6.0.3.4) lib/active_storage/attached/one.rb:32:in `attach'
  app/controllers/api/tenants/tenants_controller.rb:78:in `upload_picture'
  actionpack (6.0.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  actionpack (6.0.3.4) lib/abstract_controller/base.rb:195:in `process_action'
  actionpack (6.0.3.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  activesupport (6.0.3.4) lib/active_support/callbacks.rb:135:in `run_callbacks'
  actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
  actionpack (6.0.3.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
  actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
  activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `block in instrument'
  activesupport (6.0.3.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `instrument'
  actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  actionpack (6.0.3.4) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  activerecord (6.0.3.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  actionpack (6.0.3.4) lib/abstract_controller/base.rb:136:in `process'
  actionview (6.0.3.4) lib/action_view/rendering.rb:39:in `process'
  actionpack (6.0.3.4) lib/action_controller/metal.rb:190:in `dispatch'
  actionpack (6.0.3.4) lib/action_controller/metal.rb:254:in `dispatch'
  actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
  actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
  actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
  actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
  rack (2.2.3) lib/rack/etag.rb:27:in `call'
  rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
  rack (2.2.3) lib/rack/head.rb:12:in `call'
  activerecord (6.0.3.4) lib/active_record/migration.rb:567:in `call'
  actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
  activesupport (6.0.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
  actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
  actionpack (6.0.3.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
  better_errors (2.9.1) lib/better_errors/middleware.rb:87:in `protected_app_call'
  better_errors (2.9.1) lib/better_errors/middleware.rb:82:in `better_errors_call'
  better_errors (2.9.1) lib/better_errors/middleware.rb:60:in `call'
  actionpack (6.0.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
  web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
  web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
  actionpack (6.0.3.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  railties (6.0.3.4) lib/rails/rack/logger.rb:37:in `call_app'
  railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `block in call'
  activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `block in tagged'
  activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:28:in `tagged'
  activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `tagged'
  railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `call'
  actionpack (6.0.3.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  actionpack (6.0.3.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
  rack (2.2.3) lib/rack/runtime.rb:22:in `call'
  activesupport (6.0.3.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
  actionpack (6.0.3.4) lib/action_dispatch/middleware/static.rb:126:in `call'
  rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
  actionpack (6.0.3.4) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
  rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
  webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
  rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
  railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
  puma (4.3.7) lib/puma/configuration.rb:228:in `call'
  puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
  puma (4.3.7) lib/puma/server.rb:472:in `process_client'
  puma (4.3.7) lib/puma/server.rb:328:in `block in run'
  puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

### Expected behavior
I expected the photo to attach, or at least to receive a useful error message or even a stack trace.

### Actual behavior
I receive the NoMethodError.  Same thing happens in the console.  Also happens with `model.photo.attach(file: <image_file>, filename: '<filename>')`. 

However, `model.photo.attached?` properly returns as false.  When I run  `model.photo = image_file` in the console, no error is returned.  However when I then run `model.photo.attached?` I get the same error.

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.7.0p0

**Comment by jollyoldsaintnixon** [comment]
I imagine this is due to some missing environment credential.  However, each of the four lines that query my credential.yml file from storage.yml return with the correct value in the console.  The error is certainly on my part (and any help/suggestions would be greatly appreciated), but the bug is that the error message is unhelpful.

**Comment by rafaelfranca** [comment]
You could try to run your code with the environment variable `BACKTRACE=true` set to see where exactly that exception is coming from.

**Comment by jollyoldsaintnixon** [comment]
Thanks @rafaelfranca.  I wasn't quite sure where to put the` BACKTRACE=true`, but I did uncomment the `Rails.backtrace_cleaner.remove_silencers!` in initializers/backtrace_silencers.rb.  I'll go ahead and add the resulting stack trace to the original issue.  Please let me know if this was not what you were looking for.

**Comment by rafaelfranca** [comment]
That is a different exception than you reported. It is not `NoMethodError`. It seems the problem is on the decryption of the configuration file. Are you sure the master key is the correct one?

**Comment by jollyoldsaintnixon** [comment]
Woops, I forgot I had reverted to a previous commit earlier.  Just reset and reverified the credentials.yml.  I'll post the correct stack trace now.  Sorry about that.

**Comment by rafaelfranca** [comment]
It seems the problem is the content of your `config/storage.yml`. Some code inside it is retuning `nil` and calling `[]` on that `nil`.

**Comment by rafaelfranca** [comment]
Ah, it is `Rails.application.credentials.aws` that is `nil`. Are you sure that `Rails.application.credentials.aws` in the Rails console return anything?

**Comment by jollyoldsaintnixon** [comment]
It does :(

```
[2] pry(main)> Rails.application.credentials.aws
=> {:access_key_id=>"<maybe_secret?>",
 :secret_access_key=>"<secret>",
 :region=>"us-east-1",
 :dev=>{:bucket=>"leasebuddy-dev-photos"}}
```

**Comment by rafaelfranca** [comment]
So maybe the storage.yml file is being read before the `Rails.application.credentials` is loaded. This can happen if you, or a gem, monkey patch `ActiveStorage::Blob` during the initiialization of the app

**Comment by jollyoldsaintnixon** [comment]
Hmm... I wonder if that is it.  Any ideas how I may be able to see if that is indeed what is happening, or where I should start looking?  I really do hope I can figure this one out.  Thanks for all your replies, I appreciate it.

**Comment by jollyoldsaintnixon** [comment]
Or perhaps, do you know how I can uninstall Active Storage so that I can install it again (and hopefully cure this error)?

**Comment by rafaelfranca** [comment]
Looking the backtrace I don't think that is the case. The code that fails only get executed when the controller's action executes, that is definitely after the credentials are loaded. Maybe it is the call of `Rails.application.credentials.aws[:dev][:bucket]`, `Rails.application.credentials.aws[:dev]` is returning `nil`. Try to set the values inside `storage.yml` without using ERB and put back the ERB calls one-by-one to see which line is the cause of the problem

**Comment by jollyoldsaintnixon** [comment]
Still nothing :/  

I do get an appropriate response for `Rails.application.credentials.aws[:dev]` in the console:
```
[5] pry(main)> Rails.application.credentials.aws[:dev]
=> {:bucket=>"leasebuddy-dev-photos"}
```

**Comment by rafaelfranca** [comment]
Did you try making the storage.yml use static values and add back the ERB values one by one?

**Comment by jollyoldsaintnixon** [comment]
I did, and I got the same error when they were all static values.  I'm working on stepping through the stack via byebug.  Let me know if you have any suggestions as to what parts of the stack trace I should pay particular attention too.  And thanks again for being so responsive.

**Comment by rafaelfranca** [comment]
That is strange. I didn't expect the static values to raise the same error. Looking your stracktrace, the error is on the line 6 of the erb (`  (erb):6:in `<main>'`), that is really `bucket: <%= Rails.application.credentials.aws[:dev][:bucket] %>`. `bucket: 'test'` should not raise that exception anymore given there is no ERB to be evaluated there anymore

**Comment by rubywarlock** [comment]
Are you using master.key file?
