### ISSUE TITLE
Differing enum keys in Rails 6.1 throw an error that they are duplicates

### ISSUE THREAD

**Issue by russellrichardson** [rails/rails#40804]
### Steps to reproduce

```
class Event < ApplicationRecord
  enum timezone: {
    'Etc/GMT+1' => 1,
    'Etc/GMT-1' => 2
  }
end
```

### Expected behavior
I should be able to run the app and use these enums.

### Actual behavior
ArgumentError (You tried to define an enum named "timezone" on the model "Event", but this will generate a instance method "Etc_GMT_1?", which is already defined by another enum.)

### System configuration
Rails 6.1
Ruby 2.6.5p114

**Comment by fatkodima** [comment]
This is expected. Have you considered changing enum keys and using only alpha-numeric or underscore characters?

**Comment by russellrichardson** [comment]
I preferred to keep the keys matching the names of the IANA time zones. Makes for simpler code between a mobile app and a Rails API. I could change them to alpha-numeric or underscores but then I have to write code as a workaround to translate the IANA time zones in to the keys. Has anyone considered adding a `_methods: false` option for enums so these methods are not generated? That would solve my problem since I do not use them for this use case. Another option would be adding another option that allows you to customize the character replacement. e.g. 

```
  enum timezone: {
    'Etc/GMT+1' => 1,
    'Etc/GMT-1' => 2
   }, name_for_this: {
     "/" => "_",
     "+" => "plus",
     "-" => "minus"
   }
```

**Comment by fatkodima** [comment]
Seems like you are not using scopes too and probably really do not need an `enum`.

How about something like:
```ruby
class Event < ApplicationRecord
  TIMEZONES = {
      'Etc/GMT+1' => 1,
      'Etc/GMT-1' => 2
  }

  def timezone=(value)
    self[:timezone] = TIMEZONES.fetch(value)
  end

  def timezone
    TIMEZONES.key(self[:timezone])
  end
end
```

You can expand on this, like maybe adding validations, etc.

**Comment by russellrichardson** [comment]
I could do that, but to me that code is just reimplementing enum, especially if I start to add validations. I'd probably end up doing something like this : 
```ruby
  enum timezone: {
    'Etc_GMT_plus_1' => 1,
    'Etc_GMT_minus_1' => 2
  }

  INVALID_TZ_FIX = {
    "Etc/GMT+1" => "Etc_GMT_plus_1",
    "Etc/GMT-1" => "Etc_GMT_minus_1"
  }

  def timezone=(value)
    if INVALID_TZ_FIX.has_key?(value)
      super(INVALID_TZ_FIX[value])
    else
      super(value)
    end
  end

  def timezone
    val = super
    if INVALID_TZ_FIX.key(val)
      INVALID_TZ_FIX.key(val)
    else
      val
    end
  end
```

**Comment by 8398a7** [comment]
There is a similar problem when the value contains Japanese characters.
I would like to consider using only alphanumeric characters, but if you can fix it, I would be happy.

It seems to be an effect of this line.
https://github.com/rails/rails/blob/v6.1.0/activerecord/lib/active_record/enum.rb#L205

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :status
  end
end

class Post < ActiveRecord::Base
  enum status: %i[成功 失敗]
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(status: 1)
    puts post.status
  end
end
```

```
Traceback (most recent call last):
        12: from active_record_gem.rb:29:in `<main>'
        11: from active_record_gem.rb:30:in `<class:Post>'
        10: from /.../ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/enum.rb:170:in `enum'
         9: from /.../ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/enum.rb:170:in `each'
         8: from /.../ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/enum.rb:190:in `block in enum'
         7: from /.../ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/enum.rb:190:in `module_eval'
         6: from /.../ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/enum.rb:193:in `block (2 levels) in enum'
         5: from /.../ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/enum.rb:193:in `each'
         4: from /.../ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/enum.rb:193:in `each_with_index'
         3: from /.../ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/enum.rb:193:in `each'
         2: from /.../ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/enum.rb:212:in `block (3 levels) in enum'
         1: from /.../ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/enum.rb:271:in `detect_enum_conflict!'
/.../ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/enum.rb:276:in `raise_conflict_error': You tried to define an enum named "status" on the model "Post", but this will generate a instance method "_?", which is already defined by another enum. (ArgumentError)
```
