### ISSUE TITLE
After updating to rails 6.1.0 any operation with rails produces TypeError 

### ISSUE THREAD

**Issue by vtamara** [rails/rails#40831]
### Steps to reproduce

* Download  branch rails6.1 of a motor and test application from <https://github.com/pasosdeJesus/sip>
* Follow setup instructions available at: <https://semaphoreci.com/vtamara/sip/branches/rails6-1/builds/1>
* During setup by executing `bundle exec rake db:test:prepare RAILS_ENV=test`  (or trying any operation like `bin/rails console`) will produce an error, like: `TypeError: module attributes should be defined directly on class, not singleton
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.0/lib/active_support/core_ext/module/attribute_accessors.rb:52:in 'mattr_reader'`

### Expected behavior
It should prepare the test database, and present in screen:
```
 set_config 
------------
 
(1 row)
```

This was the behaviour when the rails version used was  6.0.3.4 as can be seen at <https://semaphoreci.com/vtamara/sip/branches/master/builds/781>

Other operations like `bin/rails console` should behave as usual.

### Actual behavior

The full trace taken from <https://semaphoreci.com/vtamara/sip/branches/rails6-1/builds/1> is:

```
rake aborted!
TypeError: module attributes should be defined directly on class, not singleton
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.0/lib/active_support/core_ext/module/attribute_accessors.rb:52:in `mattr_reader'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.0/lib/active_support/core_ext/module/attribute_accessors.rb:202:in `mattr_accessor'
/home/runner/sip/lib/sip/engine.rb:38:in `singleton class'
/home/runner/sip/lib/sip/engine.rb:37:in `<module:Sip>'
/home/runner/sip/lib/sip/engine.rb:3:in `<main>'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
/home/runner/sip/lib/sip.rb:3:in `<main>'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
/home/runner/sip/test/dummy/config/application.rb:11:in `<top (required)>'
/home/runner/sip/test/dummy/Rakefile:4:in `require'
/home/runner/sip/test/dummy/Rakefile:4:in `<top (required)>'
/home/runner/sip/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/runner/.rbenv/versions/2.6.1/bin/bundle:23:in `load'
/home/runner/.rbenv/versions/2.6.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```
### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.6.1 is configured in semaphoreci.com but it also happens with 2.7.1p83 and 2.7.2p137

**Comment by eileencodes** [comment]
The error message is telling you that you need to move your [`mattr_` definitions](https://github.com/pasosdeJesus/sip/blob/master/lib/sip/engine.rb#L38-L91) to a class and away from a singleton. This change was implemented in https://github.com/rails/rails/pull/38144.

**Comment by vtamara** [comment]
Thank you @eileencodes
