### ISSUE TITLE
rails 6.1 : Rails.cache.write/read => undefined method dup_value!

### ISSUE THREAD

**Issue by seb-sykio** [rails/rails#40869]
I just upgrade to rails 6.1 and now when I call
Rails.cache.write or Rails.cache.read
I have this error : 
undefined method dup_value!

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by seb-sykio** [comment]
hi,
sorry, I dont really where to find more detail
If I start a rails console and run this

```
Loading development environment (Rails 6.1.0)
2.7.2 :001 > Rails.cache.write('wff', 'hello')
Cache write: wff
Dalli::Server#connect 127.0.0.1:11211
```


it work fine

if I start a rails server and put "byebug" in controllers, when I run this I have this error

```
(byebug) Rails.cache.write('wff', 'hello')
Cache write: wff
*** NoMethodError Exception: undefined method `dup_value!' for "hello":String

.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/cache/strategy/local_cache.rb:68:in `write_entry'
.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/cache/strategy/local_cache.rb:162:in `write_entry'
.rvm/gems/ruby-2.7.2/gems/dalli-2.7.11/lib/active_support/cache/dalli_store.rb:154:in `block (2 levels) in write'
.rvm/gems/ruby-2.7.2/gems/dalli-2.7.11/lib/dalli/client.rb:267:in `with'
.rvm/gems/ruby-2.7.2/gems/dalli-2.7.11/lib/active_support/cache/dalli_store.rb:92:in `with'
.rvm/gems/ruby-2.7.2/gems/dalli-2.7.11/lib/active_support/cache/dalli_store.rb:152:in `block in write'
.rvm/gems/ruby-2.7.2/gems/dalli-2.7.11/lib/active_support/cache/dalli_store.rb:395:in `block in instrument_with_log'
.rvm/gems/ruby-2.7.2/gems/dalli-2.7.11/lib/active_support/cache/dalli_store.rb:404:in `block in instrument'
.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.0/lib/active_support/notifications.rb:205:in `instrument'
.rvm/gems/ruby-2.7.2/gems/dalli-2.7.11/lib/active_support/cache/dalli_store.rb:403:in `instrument'
.rvm/gems/ruby-2.7.2/gems/dalli-2.7.11/lib/active_support/cache/dalli_store.rb:395:in `instrument_with_log'
.rvm/gems/ruby-2.7.2/gems/dalli-2.7.11/lib/active_support/cache/dalli_store.rb:151:in `write'
```

rails 6.1
ruby 2.7.2

**Comment by rafaelfranca** [comment]
Are you using the dalli_store from the dalli gem to store the cache? If that is the case that is a bug in that store.
