### ISSUE TITLE
undefined method `xmlschema' for class `Time' (NameError)

### ISSUE THREAD

**Issue by benhutton** [rails/rails#40861]
### Steps to reproduce

This is kind of tricky. The [provided template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/generic_gem.rb) actually solves the problem through the `gemfile` method it calls, so I cannot use that template to reproduce the error!

Using ActiveSupport 6.1, WITHOUT `time` required (meaning, if you run `require 'time'` at this point, it returns `true`), run the following:

```
# frozen_string_literal: true

require "active_support"
require "active_support/core_ext/date_time"
```

HOWEVER, the way we ran upon this problem is that we were calling the following as part of our app:

```
require "active_support/core_ext"
```

and it would fail intermittently. I narrowed it down to a random ordering problem caused by the `Dir.glob` here: https://github.com/rails/rails/blob/v6.1.0/activesupport/lib/active_support/core_ext.rb#L3

Different heroku dynos would order the files differently. Anytime `require "active_support/core_ext/date_time"` happened before `require "active_support/core_ext/time"`, we would get the error below.

I am planning to fix the problem in my app by requiring `time` before AS.

### Expected behavior
It should require the file.

### Actual behavior
```
Traceback (most recent call last):
	2: from report.rb:20:in `<main>'
	1: from /home/ben/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/home/ben/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- active_support/core_ext/date_time (LoadError)
	12: from report.rb:20:in `<main>'
	11: from /home/ben/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	10: from /home/ben/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
	 9: from /home/ben/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
	 8: from /home/ben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/core_ext/date_time.rb:7:in `<top (required)>'
	 7: from /home/ben/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 6: from /home/ben/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 5: from /home/ben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/core_ext/date_time/conversions.rb:5:in `<top (required)>'
	 4: from /home/ben/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 3: from /home/ben/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 2: from /home/ben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/core_ext/time/conversions.rb:6:in `<top (required)>'
	 1: from /home/ben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/core_ext/time/conversions.rb:72:in `<class:Time>'
/home/ben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/core_ext/time/conversions.rb:72:in `alias_method': undefined method `xmlschema' for class `Time' (NameError)
```

### System configuration
**Rails version**: We are running ActiveSupport 6.1 in a non-Rails system.

**Ruby version**: 2.7.2

**Comment by rafaelfranca** [comment]
Fixed by #40859
