### ISSUE TITLE
Controller throws 'ActionDispatch::UnknownFormat' when 'Accept' header is set to 'application/json, */*'

### ISSUE THREAD

**Issue by gowda** [rails/rails#40908]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end


require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    respond_to do |format|
      format.json { render json: { message: 'hello world' } }
    end
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success_with_json_only
    header 'Accept', 'application/json'
    get '/'
    assert last_response.ok?
  end

  def test_returns_success_with_json_and_html
    header 'Accept', 'application/json, text/html'
    get '/'
    assert last_response.ok?
  end

  def test_returns_success_with_json_and_wildcard
    header 'Accept', 'application/json, */*'
    get '/'
    assert last_response.ok?
  end

  private

  def app
    Rails.application
  end
end
```

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "6.1.0"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    respond_to do |format|
      format.json { render json: { message: 'hello world' } }
    end
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success_with_json_only
    header 'Accept', 'application/json'
    get '/'
    assert last_response.ok?
  end

  def test_returns_success_with_json_and_html
    header 'Accept', 'application/json, text/html'
    get '/'
    assert last_response.ok?
  end

  def test_returns_success_with_json_and_wildcard
    header 'Accept', 'application/json, */*'
    get '/'
    assert last_response.ok?
  end

  private

  def app
    Rails.application
  end
end
```

### Expected behavior

Tests should pass

### Actual behavior

Tests are failing with:
```
ActionController::UnknownFormat (ActionController::UnknownFormat):

actionpack (6.1.0) lib/action_controller/metal/mime_responds.rb:216:in `respond_to'
action_controller_gem.rb:35:in `index'
```
### System configuration
**Rails version**: 6.1.0, [master](https://github.com/rails/rails/commit/71bc41477da96bb05edc33c1b6a42203e6999667)

**Ruby version**: 2.6.3

**Comment by gowda** [comment]
Expected behaviour as explained in the comment:

> We use normal content negotiation unless you include */* in your list,
> in which case we assume you're a browser and send HTML.

From [actionpack/lib/action_dispatch/http/mime_negotiation.rb](https://github.com/rails/rails/blob/903656f43fe5bff666f0699f6cf056924b4080d7/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L161)
