### ISSUE TITLE
Marshal.dump/load breaks on extreme dates when serializing  ActiveSupport::TimeWithZone

### ISSUE THREAD

**Issue by taf2** [rails/rails#41075]
### Steps to reproduce
Load a time into mysql e.g.

```sql
CREATE TABLE `test_dates` (
  `closed_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

```
class TestDate < ApplicationRecord
end
```

insert some test data with extreme dates e.g. very long ago or very far into the future.
```
insert into test_dates (closed_at) VALUES('0001-07-21 00:00:00');
```

Now in a rails console
```
TestDate.last.closed_at
=> Sat, 21 Jul 0001 00:00:00 UTC +00:00
TestDate.last.closed_at.class
=> ActiveSupport::TimeWithZone
Marshal.dump(TestDate.last.closed_at)
Traceback (most recent call last):
       10: from script/rails:6:in `<main>'
        9: from script/rails:6:in `require'
        8: from /var/www/apps/phonetrac/shared/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
        7: from /var/www/apps/phonetrac/shared/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        6: from /var/www/apps/phonetrac/shared/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:78:in `console'
        5: from /var/www/apps/phonetrac/shared/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/console_helper.rb:9:in `start'
        4: from /var/www/apps/phonetrac/shared/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/console.rb:65:in `start'
        3: from (irb):3
        2: from (irb):3:in `dump'
        1: from (irb):3:in `_dump'
```
Constrast to converting to a DateTime

```
Marshal.dump(TestDate.last.closed_at.to_datetime)
=> "\x04\bU:\rDateTime[\vi\x00i\x03\x19E\x1Ai\x00i\x00i\x00f\f2299161"
```

### Expected behavior
I would expect an ActiveSupport::TimeWithZone to be as crash safe as a DateTime with respect to Marshal behavior.  Where this really can be an issue is when using Rails.cache

### Actual behavior
When Marshal.dump a ActiveSupport::TimeWithZone you get 
```
ArgumentError (year too small to marshal: 1 UTC)
```
### System configuration
**Rails version**:  5.0.x and 5.2.x  (tested) but would appear to be the same behavior in later version of rails

**Ruby version**: 2.6.6 (tested) but would appear to be the same behavior in later versions of ruby

**Comment by alipman88** [comment]
This is an interesting bug. I'm able to reproduce in Ruby 2.6.6 / Rails 6.1.2.1.

However, updating to Ruby 2.7.2 eliminates the bug.

We can see where the error message is triggered from, within Ruby's codebase: https://github.com/ruby/ruby/blob/aea40f44aa2918f5b64d2eab1720b3d63a8b2c98/time.c#L5087

Here's my executable test script:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 6.1.2.1"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection({
  adapter: "mysql2",
  # connection config redacted
})

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :test_dates, force: true do |t|
    t.datetime :closed_at
  end
end

class TestDate < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    ActiveRecord::Base.connection.execute("insert into test_dates (closed_at) VALUES('0001-07-21 00:00:00');")
    t = TestDate.last.closed_at.in_time_zone('UTC')
    Marshal.dump t
  end
end

```

**Comment by alipman88** [comment]
On further examination, this bug seems related to Ruby, not Rails - I can reproduce a similar error in vanilla Ruby:

```ruby
# using Ruby 2.6.6
Marshal.dump(Time.new('1900-01-01'))
=> "\x04\bIu:\tTime\r%\x00\x00\x80\x00\x00\x00\x00\a:\voffseti\xFE\xB0\xB9:\tzoneI\"\bEST\x06:\x06EF"

Marshal.dump(Time.new('1899-12-31'))
ArgumentError (year too small to marshal: 1899 UTC)
```

I think this issue can be closed, as it relates to Ruby rather than Rails. Seems like older versions of Ruby tried to shave some bytes off of marshaled Time objects by only storing the number of years since 1900, if I'm reading the C code and comments correctly.

**Comment by taf2** [comment]
Thanks!  About to finish our ruby 2.7.2 update here - seems to make sense thank you
