### ISSUE TITLE
Spec using stop_stream_from fails with undefined 'pubsub'

### ISSUE THREAD

**Issue by jasonatball** [rails/rails#41077]
### Steps to reproduce
Create ActionCable Channel spec which calls stop_stream_from

### Expected behavior
Spec should pass

### Actual behavior
NoMethodError:  undefined method `pubsub' for #<ActionCable::Channel::ConnectionStub:0x0000000007507998>

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.2

Channel Code:
```
class StreamingChannel < ApplicationCable::Channel
  def subscribed
    stream_from uuid
  end

  def unsubscribed
    stop_stream_from uuid
  end

  def add(data)
    reject_subscription
  end
end
```

Spec:
```
require "rails_helper"
RSpec.describe StreamingChannel, :type => :channel do
  before do
    stub_connection uuid: '12345'
  end

  it "adds" do
    subscribe()
    subscription.add({data: 'hello'})
  end
end
```

Fix (put this at the top of the spec file):
```
module ActionCable
  module Channel
    class ConnectionStub
      def pubsub
        ActionCable.server.pubsub
      end
    end
  end
end
```

**Comment by jasonatball** [comment]
Reproduceable on rails 6.1.3.1. Reproduction steps:

Install rails, rails new blog. Update Gemfile to add rspec-rails to test group:
```
group :test do
  gem 'rspec-rails', "~> 4.0.0"
```

Install rspec: ```rails generate rspec:install```

Add following method to app/channels/application_cable/channel.rb:
```
module ApplicationCable
  class Channel < ActionCable::Channel::Base
    def subscribed
      stream_from uuid
      stop_stream_from uuid # This causes the error
    end
  end
end
```
Create following spec/channels/channel_spec.rb
```
require "rails_helper"
RSpec.describe ApplicationCable::Channel, :type => :channel do
  it "subscribes" do
    stub_connection uuid: '12345'
    subscribe()
  end
end
```
Run spec: ```rspec spec\channels\channel_spec.rb```

Observe error:
```
Failures:

  1) ApplicationCable::Channel subscribes
     Failure/Error: stop_stream_from uuid

     NoMethodError:
       undefined method `pubsub' for #<ActionCable::Channel::ConnectionStub:0x000000000bd0d8a0>
     # ./app/channels/application_cable/channel.rb:5:in `subscribed'
     # ./spec/channels/channel_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 0.04651 seconds (files took 10.52 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/channels/channel_spec.rb:4 # ApplicationCable::Channel subscribes
```
Fix issue by adding code to channel_spec.rb:
```
module ActionCable
  module Channel
    class ConnectionStub
      def pubsub
        ActionCable.server.pubsub
      end
    end
  end
end
```

**Comment by Lewiscowles1986** [comment]
This still happens, and the solution still works for Rails 7.
