### ISSUE TITLE
Error after updating to Ruby 3.0.0

### ISSUE THREAD

**Issue by Shalashtein** [rails/rails#41113]
I had a running rails app, after upgrading the ruby version to 3.0.0 I had some gems that depended on the the previous version of Ruby, I removed all these gems but when I run the rails server and head to the route I get the `We're sorry, but something went wrong.` screen in development enviroment, instead of the usual web console.

Here are the logs displayed in the console:

```
Started GET "/" for ::1 at 2021-01-13 21:04:58 +0200
Processing by PagesController#store as HTML
Completed 500 Internal Server Error in 94ms (ActiveRecord: 2.1ms | Allocations: 16182)


  
ArgumentError (wrong number of arguments (given 4, expected 3)):
  
actionview (6.0.3.4) lib/action_view/template.rb:130:in `initialize'
deface (1.5.3) lib/deface/action_view_extensions.rb:21:in `initialize'
actionview (6.0.3.4) lib/action_view/unbound_template.rb:23:in `new'
actionview (6.0.3.4) lib/action_view/unbound_template.rb:23:in `build_template'
actionview (6.0.3.4) lib/action_view/unbound_template.rb:17:in `bind_locals'
actionview (6.0.3.4) lib/action_view/template/resolver.rb:203:in `block in query'
actionview (6.0.3.4) lib/action_view/template/resolver.rb:193:in `map'
actionview (6.0.3.4) lib/action_view/template/resolver.rb:193:in `query'
actionview (6.0.3.4) lib/action_view/template/resolver.rb:186:in `_find_all'
actionview (6.0.3.4) lib/action_view/template/resolver.rb:120:in `block in find_all'
actionview (6.0.3.4) lib/action_view/template/resolver.rb:154:in `block in cached'
actionview (6.0.3.4) lib/action_view/template/resolver.rb:66:in `cache'
actionview (6.0.3.4) lib/action_view/template/resolver.rb:153:in `cached'
actionview (6.0.3.4) lib/action_view/template/resolver.rb:119:in `find_all'
actionview (6.0.3.4) lib/action_view/path_set.rb:76:in `block (2 levels) in _find_all'
actionview (6.0.3.4) lib/action_view/path_set.rb:75:in `each'
actionview (6.0.3.4) lib/action_view/path_set.rb:75:in `block in _find_all'
actionview (6.0.3.4) lib/action_view/path_set.rb:74:in `each'
actionview (6.0.3.4) lib/action_view/path_set.rb:74:in `_find_all'
actionview (6.0.3.4) lib/action_view/path_set.rb:55:in `find_all'
actionview (6.0.3.4) lib/action_view/path_set.rb:59:in `exists?'
actionview (6.0.3.4) lib/action_view/lookup_context.rb:143:in `exists?'
actionview (6.0.3.4) lib/action_view/view_paths.rb:11:in `template_exists?'
actionpack (6.0.3.4) lib/action_controller/metal/implicit_render.rb:34:in `default_render'
actionpack (6.0.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
<internal:kernel>:90:in `tap'
actionpack (6.0.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.3.4) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.3.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.3.4) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.3.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.3.4) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.3.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.3.4) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.3.4) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.3.4) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.3.4) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
skylight-core (4.3.2) lib/skylight/core/probes/action_dispatch/routing/route_set.rb:14:in `block in call'
skylight-core (4.3.2) lib/skylight/core/fanout.rb:25:in `instrument'
skylight-core (4.3.2) lib/skylight/core/probes/action_dispatch/routing/route_set.rb:13:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.3.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.3.4) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
skylight-core (4.3.2) lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/debug_locks.rb:41:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
puma (4.3.7) lib/puma/configuration.rb:228:in `call'
puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
puma (4.3.7) lib/puma/server.rb:472:in `process_client'
puma (4.3.7) lib/puma/server.rb:328:in `block in run'
puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'

```

**Comment by gmcgibbon** [comment]
Please provide us with a [test script](https://github.com/rails/rails/tree/master/guides/bug_report_templates) or rails app demonstrating this issue. We are unable to help otherwise. Thanks!

**Comment by composerinteralia** [comment]
Based on the stack trace this looks like it is coming from the deface gem, not rails. https://github.com/spree/deface/pull/213 should fix it. This has to do with the[ keyword arguments changes in Ruby 3](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

**Comment by Shalashtein** [comment]
> Based on the stack trace this looks like it is coming from the deface gem, not rails. [spree/deface#213](https://github.com/spree/deface/pull/213) should fix it. This has to do with the[ keyword arguments changes in Ruby 3](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

Thanks a lot man, I didn't notice the second line, upgraded deface from the repo and it worked
