### ISSUE TITLE
Unable to set default JSON value on a text column with MariaDB 

### ISSUE THREAD

**Issue by janko** [rails/rails#41240]
### Steps to reproduce

```rb
require "active_record"

ActiveRecord::Base.establish_connection(
  adapter: "mysql2",
  database: "...",
  username: "...",
  password: "...",
)

class MyRecord < ActiveRecord::Base
  serialize :col, JSON
end

ActiveRecord::Schema.define do
  create_table :my_records, force: true do |t|
    t.text :col, default: "[]"
  end
end

record = MyRecord.create
```

### Expected behavior

I expect that `my_records.col` column default value will be set to `'[]'` (empty string in SQL).

### Actual behavior

The `my_records.col` column default value gets set to the SQL equivalent of `'\'[]\''` (`"'[]'"` in Ruby), which fails to get JSON-parsed when the record is saved. The error with reversed stack trace (sorry):

```
        39: from tmp/ar.rb:20:in `<main>'
        38: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb:38:in `create'
        37: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/suppressor.rb:44:in `save'
        36: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:315:in `save'
        35: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
        34: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:212:in `transaction'
        33: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
        32: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
        31: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
        30: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
        29: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
        28: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
        27: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:315:in `block in save'
        26: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/validations.rb:47:in `save'
        25: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb:470:in `save'
        24: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/timestamp.rb:129:in `create_or_update'
        23: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/callbacks.rb:328:in `create_or_update'
        22: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
        21: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
        20: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/callbacks.rb:328:in `block in create_or_update'
        19: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb:906:in `create_or_update'
        18: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/timestamp.rb:111:in `_create_record'
        17: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/callbacks.rb:332:in `_create_record'
        16: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
        15: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
        14: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/callbacks.rb:332:in `block in _create_record'
        13: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/attribute_methods/dirty.rb:212:in `_create_record'
        12: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/dirty.rb:146:in `changes_applied'
        11: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/dirty.rb:249:in `forget_attribute_assignments'
        10: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/attribute_set.rb:88:in `map'
         9: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/attribute_set.rb:88:in `transform_values'
         8: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/attribute.rb:67:in `forgetting_assignment'
         7: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/attribute.rb:55:in `value_for_database'
         6: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/attribute.rb:42:in `value'
         5: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/attribute.rb:164:in `type_cast'
         4: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/type/serialized.rb:22:in `deserialize'
         3: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/coders/json.rb:11:in `load'
         2: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/json/decoding.rb:23:in `decode'
         1: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at ''[]'' (JSON::ParserError)
```

I've tried all the combinations:

```rb
t.text :col, default: [] # ~> TypeError: can't quote Array
t.json :col, default: [] # ~> JSON::ParserError: 767: unexpected token at ''[]''
t.json :col, default: -> { "'[]'" } # ~> JSON::ParserError: 767: unexpected token at ''[]''
t.json :col, default: -> { "[]" } # ~> Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '[])' at line 1
``` 

It appears that Active Record is doing some conversion work here that I don't want it to do, even in the block version of `:default` value, where I thought it's supposed to interpret my string as raw SQL.

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.6.5

**Comment by fatkodima** [comment]
This will be fixed by #40822
