### ISSUE TITLE
Whitespace at start/end of query string triggers ActiveRecord::UnknownAttributeReference

### ISSUE THREAD

**Issue by Adrian-Hirt** [rails/rails#41307]
I hope this hasn't been discussed yet, didn't find anything in the issues.

### Steps to reproduce

* Create a DB table with some columns
* Use `pluck` to pluck the values of some columns, supplying the names of the columns in a string containing newlines as demonstrated in the tests in the ` FAILING TESTS` section:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'activerecord', '6.1.1'
  gem 'sqlite3'
  gem 'minitest-hooks'
end

require 'active_record'
require 'minitest/autorun'
require 'minitest/hooks/test'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :email
    t.string :first_name
    t.string :last_name
  end

end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class User < ApplicationRecord; end


class BugTest < Minitest::Test
  include Minitest::Hooks

  EXPECTED_DATA = [['example@example.com', 'Joe', 'Doe']].freeze

  def before_all
    User.create!(
      email: 'example@example.com',
      first_name: 'Joe',
      last_name: 'Doe'
    )
  end

  ################################################################
  # PASSING TESTS
  ################################################################

  def test_valid_with_symbol
    data = User.pluck(:email, :first_name, :last_name)

    assert_equal data, EXPECTED_DATA
  end

  def test_valid_with_string
    data = User.pluck('email, first_name, last_name')

    assert_equal data, EXPECTED_DATA
  end

  def test_valid_with_strings
    data = User.pluck('email', 'first_name', 'last_name')

    assert_equal data, EXPECTED_DATA
  end

  def test_valid_with_percentage_notation
    data = User.pluck(%Q[email, first_name, last_name])

    assert_equal data, EXPECTED_DATA
  end

  def test_valid_with_arel_multiline_string
    data = User.pluck(Arel.sql(
      '
        email,
        first_name,
        last_name
      '
    ))

    assert_equal data, EXPECTED_DATA
  end

  def test_valid_with_multiline_string_without_starting_and_final_newline
    data = User.pluck('email,
        first_name,
        last_name'
      )

    assert_equal data, EXPECTED_DATA
  end

  ################################################################
  # FAILING TESTS
  ################################################################

  # This test fails as the string has a newline at the start and the end of
  # the string passed to #pluck
  def test_invalid_with_multiline_string_with_newlines
    data = User.pluck('
        email,
        first_name,
        last_name
      '
    )

    assert_equal data, EXPECTED_DATA
  end

  # This test fails as the string has a newline at the start of
  # the string passed to #pluck
  def test_invalid_with_multiline_string_with_starting_newline
    data = User.pluck('
        email,
        first_name,
        last_name'
    )

    assert_equal data, EXPECTED_DATA
  end

  # This test fails as the string has a newline at the end of
  # the string passed to #pluck
  def test_invalid_with_multiline_string_with_final_newline
    data = User.pluck('email,
        first_name,
        last_name
      ')

    assert_equal data, EXPECTED_DATA
  end

  ################################################################
  # FAILING TESTS FIXED
  ################################################################

  def test_invalid_with_multiline_string_with_newlines_fixed
    data = User.pluck('
        email,
        first_name,
        last_name
      '.strip
    )

    assert_equal data, EXPECTED_DATA
  end

  def test_invalid_with_multiline_string_with_starting_newline_fixed
    data = User.pluck('
        email,
        first_name,
        last_name'.strip
    )

    assert_equal data, EXPECTED_DATA
  end

  def test_invalid_with_multiline_string_with_final_newline_fixed
    data = User.pluck('email,
        first_name,
        last_name
      '.strip)

    assert_equal data, EXPECTED_DATA
  end
end
```

### Expected behavior

All tests passing

### Actual behavior

The 3 tests in the `FAILING TESTS` section fail:

```
  1) Error:
BugTest#test_invalid_with_multiline_string_with_starting_newline:
ActiveRecord::UnknownAttributeReference: Query method called with non-attribute argument(s): "\n        email,\n        first_name,\n        last_name"
    /home/<username>/work/SitroxCore/sitrox_core/vendor/bundle/gems/activerecord-6.1.1/lib/active_record/sanitization.rb:145:in `disallow_raw_sql!'
    /home/<username>/work/SitroxCore/sitrox_core/vendor/bundle/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:192:in `pluck'
    /home/<username>/work/SitroxCore/sitrox_core/vendor/bundle/gems/activerecord-6.1.1/lib/active_record/querying.rb:22:in `pluck'
    test.rb:122:in `test_invalid_with_multiline_string_with_starting_newline'

  2) Error:
BugTest#test_invalid_with_multiline_string_with_newlines:
ActiveRecord::UnknownAttributeReference: Query method called with non-attribute argument(s): "\n        email,\n        first_name,\n        last_name\n      "
    /home/<username>/work/SitroxCore/sitrox_core/vendor/bundle/gems/activerecord-6.1.1/lib/active_record/sanitization.rb:145:in `disallow_raw_sql!'
    /home/<username>/work/SitroxCore/sitrox_core/vendor/bundle/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:192:in `pluck'
    /home/<username>/work/SitroxCore/sitrox_core/vendor/bundle/gems/activerecord-6.1.1/lib/active_record/querying.rb:22:in `pluck'
    test.rb:111:in `test_invalid_with_multiline_string_with_newlines'

  3) Error:
BugTest#test_invalid_with_multiline_string_with_final_newline:
ActiveRecord::UnknownAttributeReference: Query method called with non-attribute argument(s): "email,\n        first_name,\n        last_name\n      "
    /home/<username>/work/SitroxCore/sitrox_core/vendor/bundle/gems/activerecord-6.1.1/lib/active_record/sanitization.rb:145:in `disallow_raw_sql!'
    /home/<username>/work/SitroxCore/sitrox_core/vendor/bundle/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:192:in `pluck'
    /home/<username>/work/SitroxCore/sitrox_core/vendor/bundle/gems/activerecord-6.1.1/lib/active_record/querying.rb:22:in `pluck'
    test.rb:132:in `test_invalid_with_multiline_string_with_final_newline'

```

### System configuration

**Rails version**: 6.1.1

**Ruby version**: 2.7.1

### Comment

Now, I see that the [disallow_raw_sql!](https://github.com/rails/rails/blob/a1d35aecc6e24aa6878d1a0b0a1329bc46719bd7/activerecord/lib/active_record/sanitization.rb#L140) method checks if the supplied argument is either a Symbol, an Arel node or if it's a string that matches the column name matcher of the connection adapter, which makes perfect sense to protect against malicious SQL input.

However, the fact that whitespace at the start and/or end of the string make a query invalid can be quite confusing, as it might not be intuitive at first why

```ruby
User.pluck("first_name,
email")
```

works, and the version

```ruby
User.pluck("first_name,
email
")
```

raises an `ActiveRecord::UnknownAttributeReference`.

Changing 

```ruby
next if arg.is_a?(Symbol) || Arel.arel_node?(arg) || permit.match?(arg.to_s)
```

to

```ruby
next if arg.is_a?(Symbol) || Arel.arel_node?(arg) || permit.match?(arg.to_s.strip)
```

(i.e. adding `.strip` to the last condition in the `if`clause) in the before mentioned [disallow_raw_sql!](https://github.com/rails/rails/blob/a1d35aecc6e24aa6878d1a0b0a1329bc46719bd7/activerecord/lib/active_record/sanitization.rb#L140) method fixes this issue locally for me. Are there any issues regarding security or otherwise with trimming whitespace at the start and end of the supplied string, such that adding whitespace at the start and / or end of the string won't make the query fail?
If not, I'd be happy to open a pull-request, but I'm happy to hear from the you if this would be an issue.

With regards

**Comment by gmcgibbon** [comment]
`next if arg.is_a?(Symbol) || Arel.arel_node?(arg) || permit.match?(arg.to_s.strip)` works, but I think that's just to get around the exception. The SQL we log shouldn't have newlines and extra spaces in it:

```
User Pluck (0.1ms)  SELECT
        email,
        first_name,
                last_name
       FROM "users"
```

We should fix that too. Either in the sanitize method, or beforehand.

**Comment by Adrian-Hirt** [comment]
@gmcgibbon Agreed, sounds good as well, or even deprecating multi-column strings as you suggested in #41326, my main concern was that the behaviour is not intuitive. Thanks for the quick reply :+1: Let me know if I can be of any help, either here or in #41326 :smiley:
