### ISSUE TITLE
number_with_precision :en locale issue

### ISSUE THREAD

**Issue by dilumn** [rails/rails#41459]
Today while I was trying to update to Rails 6.1 I encounter this issue

### Steps to reproduce

```
include ActionView::Helpers::NumberHelper
number_with_precision(111.234, locale: :en)

TypeError:
       no implicit conversion of String into Integer
     # /rails/activesupport/lib/active_support/number_helper/rounding_helper.rb:16:in `round'
     # /rails/activesupport/lib/active_support/number_helper/rounding_helper.rb:16:in `round'
     # /rails/activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb:13:in `convert'
     # /rails/activesupport/lib/active_support/number_helper/number_converter.rb:134:in `execute'
     # /rails/activesupport/lib/active_support/number_helper/number_converter.rb:120:in `convert'
     # /rails/activesupport/lib/active_support/number_helper.rb:239:in `number_to_rounded'
     # /rails/actionview/lib/action_view/helpers/number_helper.rb:413:in `public_send'
     # /rails/actionview/lib/action_view/helpers/number_helper.rb:413:in `block in delegate_number_helper_method'
     # /rails/actionview/lib/action_view/helpers/number_helper.rb:437:in `wrap_with_output_safety_handling'
     # /rails/actionview/lib/action_view/helpers/number_helper.rb:412:in `delegate_number_helper_method'
     # /rails/actionview/lib/action_view/helpers/number_helper.rb:252:in `number_with_precision'
```

The issue coming from https://github.com/rails/rails/pull/38148 this change https://github.com/rails/rails/pull/38148/files#diff-5431f6f3a381ee7842251c7fc01698f7b9c025c18b75eeb2d4897d1a972c57b6R48

When I checked even further, found that `!ruby/sym default` is not loading the value as a symbol in rails (But with Ruby this syntax working fine), instead `round_mode` load as a string & causing this issue.

### Expected behavior

In Rails 6.0
```
:001 > include ActionView::Helpers::NumberHelper
 => Object 
 :002 > number_with_precision(111.234, locale: :en)
 => "111.234" 
```

### Actual behavior

In Rails 6.1

```
 :001 > include ActionView::Helpers::NumberHelper
 => Object 
 :002 > number_with_precision(111.234, locale: :en)
Traceback (most recent call last):
        1: from (irb):2
TypeError (no implicit conversion of String into Integer)
```

### System configuration
**Rails version**:
6.1.2.1

**Ruby version**:
2.7.1

We can do

```
rounded_number = convert_to_decimal(number).round(precision, options.fetch(:round_mode, :default).to_sym)
```
as a fix, I can create the pull request if you think that is a proper fix. Or else please help check what is the root cause for `!ruby/sym` in yml files not working with rails

**Comment by dilumn** [comment]
@tom-lord do you think this is a good fix for the issue?

```
rounded_number = convert_to_decimal(number).round(precision, options.fetch(:round_mode, :default).to_sym)
```

Or else we can remove `round_mode: !ruby/sym default` from `lib/active_support/locale/en.yml` as a fix also

**Comment by tom-lord** [comment]
> `!ruby/sym default` is not loading the value as a symbol in rails (But with Ruby this syntax working fine), instead round_mode load as a string & causing this issue.

Oh, that's super weird... I feel like maybe _that's_ the bug we could be addressing instead?

I just tried to reproduce your report:

```
gem install rails -v 6.1.2.1
rails new i18n_test
cd i18n_test
rails c
> include ActionView::Helpers::NumberHelper
> number_with_precision(111.234, locale: :en)
  => "111.234"
```

...But it worked without error. So I would presume that the problem lies in some 3rd party gem?

**Comment by dilumn** [comment]
ohh looks like it is something to do with another gem. I will narrow it down. Thanks for your input Tom

Closing the issue

**Comment by anamba** [comment]
I am having the same issue and have not yet been able to figure out what is causing it.

Example:

```
$ rails r 'puts ActiveSupport::NumberHelper::number_to_currency(123)'
Traceback (most recent call last):
        23: from bin/rails:6:in `<main>'
        22: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        21: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        20: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        19: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        18: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        17: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/commands.rb:18:in `<main>'
        16: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/command.rb:50:in `invoke'
        15: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/command/base.rb:69:in `perform'
        14: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        13: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        12: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        11: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/commands/runner/runner_command.rb:45:in `perform'
        10: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/commands/runner/runner_command.rb:45:in `eval'
         9: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
         8: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/number_helper.rb:117:in `number_to_currency'
         7: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/number_helper/number_converter.rb:120:in `convert'
         6: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/number_helper/number_converter.rb:134:in `execute'
         5: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/number_helper/number_to_currency_converter.rb:19:in `convert'
         4: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/number_helper/number_converter.rb:120:in `convert'
         3: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/number_helper/number_converter.rb:134:in `execute'
         2: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/number_helper/number_to_rounded_converter.rb:13:in `convert'
         1: from /Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/number_helper/rounding_helper.rb:16:in `round'
/Users/anamba/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/number_helper/rounding_helper.rb:16:in `round': no implicit conversion of String into Integer (TypeError)
```

Then I created a new rails app, and it works as expected:
```
$ rails r 'puts ActiveSupport::NumberHelper::number_to_currency(123)'
$123.00
```

To try to isolate the cause, I then added my gems (still worked), then added my initializers (worked), then added all the rest of my code (worked), then added everything else I could think of (worked). Finally, I copied in the .git from my broken app and slowly `git checkout`-ed things until they were exactly identical.

So... seemingly no matter what I add to it, the newly generated app works fine, and my existing app gives `TypeError (no implicit conversion of String into Integer)`. ?????

**Comment by dilumn** [comment]
It looks like `safe_yaml` gem restriction causing the issue. But didn't have time to 100% confirm this yet

**Comment by anamba** [comment]
I mean, in the end, I did solve my problem, just in a very strange way that I can't explain.

I have seen this issue on other projects as well, so it would be nice find a better fix than creating a new rails app and transforming it into the existing one via git.

**Comment by anamba** [comment]
For anyone who happens to find this later via the google, the reason I was unable to isolate the cause of this issue was that I was not clearing the bootsnap cache between experiments. After figuring that out, I confirmed that I am indeed experiencing the same issue, and disabling safe_yaml makes the number helpers work again.
