### ISSUE TITLE
rails test fails with cannot load such file rexml/document

### ISSUE THREAD

**Issue by shireenrao** [rails/rails#41502]
### Steps to reproduce

$ rails new myapp
$ cd myapp
$ rake db:create
$ rails g scaffold Entry meal_type:string calories:integer
$ rails db:migrate
$ rails test
### Expected behavior

```
Running via Spring preloader in process 26783
Run options: --seed 40222

# Running:

.......

Finished in 2.915169s, 2.4012 runs/s, 3.0873 assertions/s.
7 runs, 9 assertions, 0 failures, 0 errors, 0 skips
```
### Actual behavior

```
/home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require': cannot load such file -- rexml/document (LoadError)
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `block in require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox.rb:22:in `<main>'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `block in require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/webdrivers-4.5.0/lib/webdrivers/geckodriver.rb:72:in `<main>'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `block in require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/webdrivers-4.5.0/lib/webdrivers.rb:4:in `<main>'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:66:in `block (2 levels) in require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:61:in `each'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:61:in `block in require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:50:in `each'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:50:in `require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler.rb:174:in `require'
        from /home/srao/projects/rails/v3/myapp/config/application.rb:7:in `<top (required)>'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
        from /home/srao/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from <internal:/home/srao/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/srao/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from -e:1:in `<main>'
```
### System configuration
**Rails version**:
Rails 6.1.3
**Ruby version**:
ruby 3.0.0p0

Adding 'rexml' in the test group in the Gemfile fixes the issue. 

```ruby
group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
  gem 'rexml'
end
```

**Comment by rafaelfranca** [comment]
This is an issue with selenium-webdriver. https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/firefox.rb#L22. Could you please report there?

**Comment by rafaelfranca** [comment]
In fact it was already fixed and should be released in the new version of selenium-webdriver https://github.com/SeleniumHQ/selenium/commit/526fd9d0de60a53746ffa982feab985fed09a278

**Comment by shireenrao** [comment]
Thank you @rafaelfranca!

**Comment by joel** [comment]
Actually it seems this gem is missing in Ruby 3

I had to add it to my Gemfile 

```
ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
gem install rails -v '6.1.3' 
rails new weblog  
rails generate scaffold Post title:string body:text
rails db:migrate     
rails test
```

```
rails test
```

```
~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require': cannot load such file -- rexml/document (LoadError)
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `block in require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:299:in `load_dependency'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox.rb:22:in `<main>'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `block in require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:299:in `load_dependency'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/webdrivers-4.5.0/lib/webdrivers/geckodriver.rb:72:in `<main>'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `block in require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:299:in `load_dependency'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/webdrivers-4.5.0/lib/webdrivers.rb:4:in `<main>'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:66:in `block (2 levels) in require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:61:in `each'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:61:in `block in require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:50:in `each'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:50:in `require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/site_ruby/3.0.0/bundler.rb:173:in `require'
        from ~/WorkSpace/Ruby/Examples/weblog/config/application.rb:7:in `<top (required)>'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
        from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from <internal:~/.asdf/installs/ruby/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:~/.asdf/installs/ruby/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from -e:1:in `<main>'
```

**Comment by eclectic-coding** [comment]
> This is an issue with selenium-webdriver. https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/firefox.rb#L22. Could you please report there?

I know I am late here, but the issue is that there will not be a fix released for [selenium-webdriver 3.x](https://github.com/SeleniumHQ/selenium/pull/9002#issuecomment-759830745), which at this point is the version used for a default `rails new` build. 

For a better user experience, especially for new users, would it be prudent to consider either adding `rexml` to the Gemfile OR bumping `selenium-webdriver` to v.4.0.0.beta1, which has been fixed?

**Comment by zhandosalmaty** [comment]
Sometimes it was bootsnap, example write rights tmp is not writable.
You in console write this:

cd rails_project_folder
rm -rf tmp

tmp folder is deleted, and then when you restarted rails his is be writable.

**Comment by jchilders** [comment]
I know this issue is closed, but I'm not entirely sure the reasoning behind doing so is acceptable. Currently, out of the box Rails does not work. Adding rexml to the test group in the Gemfile fixes it. This is a one line change. Can this issue be reexamined?

**Comment by jacobgreenleaf** [comment]
Once `selenium-webdriver` releases its 4.0 gem, it will work, because the version specifier has no major version constraint. 

https://github.com/rails/rails/blob/0b3a63fe07507fca5b2cab6409e85789a46ed624/railties/lib/rails/generators/rails/app/templates/Gemfile.tt#L71

Until then, you can change the `selenium-webdriver` gem to be pinned to any version after `4.0.0.beta1` where the [fix](https://github.com/SeleniumHQ/selenium/commit/d7f2ef23b6ba464f64b4b6765ac08dbddecfcf75) was pre-released. 

```
gem 'selenium-webdriver', '~> 4.0.0.beta4'
```

Unfortunately, `selenium-webdriver` has been in the process of cutting their 4.0 release for [about 18 months](https://rubygems.org/gems/selenium-webdriver/versions) since this writing. I would advise poking them to backport this to 3.x, or pinning to `~> 4.0.0.beta1` in Rails.

**Comment by haseebeqx** [comment]
For now, it can be fixed by adding 
```rb
gem 'rexml', '~> 3.2.5'
```
