### ISSUE TITLE
params.require shows to users controller methods in PROD mode

### ISSUE THREAD

**Issue by VitaliiLazebnyi** [rails/rails#41515]
### Steps to reproduce
1. add params.require(:some_param) to controller action
2. do a request

### Expected behavior
I see an error: ":some_param" is missed
I see no internal system details.

### Actual behavior
I see my controller details on the test and production environment. (thankfully to "Did you mean?" section)
(even though **consider_all_requests_local** is _false_  everywhere )

since exception.to_s produces  `"param is missing or the value is empty: some_param\nDid you mean?  user_id\n               valid?\n               controller\n               action"`

The response is:

```
{
    "status": 400,
    "message": "Bad Request",
    "error": [
        {
            "message": "param is missing or the value is empty: some_param\nDid you mean?  user_id\n               valid?\n               controller\n               action"
        }
    ]
}
```

### Impact
A user sees details he doesn't understand.
An attacker can gain some knowledge about my system.

### Reason
https://github.com/rails/rails/pull/39347

### System configuration
**Rails version**:
6.1.2.1
**Ruby version**:
2.7

**Comment by p8** [comment]
Hi @VitaliiLazebnyi. Thanks for reporting this issue.
Are you rescuing the ParameterMissing exception?
When I try to reproduce it just raises the error:
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"
require "active_model/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    post "/" => "test#index"
  end
end

class Person
  include ActiveModel::Model
  attr_accessor :name, :age
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    person = Person.new(params.require(:person).permit(:name, :age))
    render json: person.to_json
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    #error = assert_raises ActionController::ParameterMissing do
      post "/", person2: { name: "baz" }
    #end
    assert last_response.ok?
    assert_equal '', last_response.body
  end

  private
    def app
      Rails.application
    end
end
```

**Comment by VitaliiLazebnyi** [comment]
@p8 

your test gives me the following output:
```
sing rails 7.0.0.alpha from https://github.com/rails/rails.git (at main@14f35cd)
Run options: --seed 29964

# Running:

I, [2021-03-03T15:48:51.789663 #253]  INFO -- : Started POST "/" for 127.0.0.1 at 2021-03-03 15:48:51 +0000
F, [2021-03-03T15:48:51.866443 #253] FATAL -- :   
ActionController::ParameterMissing (param is missing or the value is empty: person
Did you mean?  person2
               action
               controller):
  
test.rb:38:in `index'
test.rb:51:in `test_returns_success'
F

Failure:
BugTest#test_returns_success [test.rb:53]:
Expected false to be truthy.

rails test test.rb:49

Finished in 0.093317s, 10.7161 runs/s, 10.7161 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
root@550c85952684:/app# 

```

and this part is my problem on test and production environments:
```
ActionController::ParameterMissing (param is missing or the value is empty: person
Did you mean?  person2
               action
               controller):
```

So yes. I have to do the following to negotiate the problem:
```
     rescue_from ActionController::ParameterMissing, with: :argument_error

       def argument_error(exception)
      error_message =
        if detailed_exceptions?
          exception.to_s
        else
          exception.original_message
        end

      error_details = [{ message: error_message }]
      respond(400, BAD_REQUEST, error_details)
    end

    def detailed_exceptions?
      Rails.application.config.consider_all_requests_local
    end
```

The worst is that I see no benefits of seeing my methods in a controller because they are always different from passed params.

**Comment by VitaliiLazebnyi** [comment]
When I disable the module with my custom error handling output even worse:
```
Puma caught this error: param is missing or the value is empty: enabled
Did you mean?  tenant_id
               readonly
               controller
               action (ActionController::ParameterMissing)
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_controller/metal/strong_parameters.rb:507:in `require'
/app/app/controllers/readonly_controller.rb:35:in `configuration_params'
/app/app/controllers/readonly_controller.rb:40:in `validate_post_params'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/callbacks.rb:512:in `each'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/callbacks.rb:512:in `invoke_before'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/callbacks.rb:105:in `run_callbacks'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/notifications.rb:205:in `instrument'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
/usr/local/bundle/gems/activerecord-6.1.2.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/abstract_controller/base.rb:165:in `process'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_controller/metal.rb:190:in `dispatch'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_controller/metal.rb:254:in `dispatch'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/journey/router.rb:32:in `each'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/journey/router.rb:32:in `serve'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/routing/route_set.rb:842:in `call'
/usr/local/bundle/gems/bullet-6.1.3/lib/bullet/rack.rb:12:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/streetcar-logging-2.0.0/lib/streetcar/logging/correlation_middleware.rb:25:in `call'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/local/bundle/gems/streetcar-logging-2.0.0/lib/streetcar/logging/middleware.rb:28:in `block in call'
/usr/local/bundle/gems/streetcar-logging-2.0.0/lib/streetcar/logging/middleware.rb:39:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/notifications.rb:203:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/notifications.rb:203:in `instrument'
/usr/local/bundle/gems/streetcar-logging-2.0.0/lib/streetcar/logging/middleware.rb:39:in `instrument'
/usr/local/bundle/gems/streetcar-logging-2.0.0/lib/streetcar/logging/middleware.rb:25:in `call'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/local/bundle/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/usr/local/bundle/gems/activesupport-6.1.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/middleware/static.rb:24:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/usr/local/bundle/gems/actionpack-6.1.2.1/lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
/usr/local/bundle/gems/railties-6.1.2.1/lib/rails/engine.rb:539:in `call'
/usr/local/bundle/gems/puma-4.3.7/lib/puma/configuration.rb:228:in `call'
/usr/local/bundle/gems/puma-4.3.7/lib/puma/server.rb:713:in `handle_request'
/usr/local/bundle/gems/puma-4.3.7/lib/puma/server.rb:472:in `process_client'
/usr/local/bundle/gems/puma-4.3.7/lib/puma/server.rb:328:in `block in run'
/usr/local/bundle/gems/puma-4.3.7/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by smt116** [comment]
Workaround:

```ruby
# config/initializers/strong_parameters.rb

# Do not include "did you mean" information in the response.
#
# Introduced in: https://github.com/rails/rails/pull/39347.
# Issue: https://github.com/rails/rails/issues/41515.
module ActionController
  class ParameterMissing
    class Correction
      def corrections
        []
      end
    end
  end
end
```

**Comment by rafaelfranca** [comment]
Let me see if I understood correctly. You are getting the exception that was raised and returning its content to your users in the response?

If that is the case don't do that. We don't guarantee the exception message is good for sending as response. Exceptions are internals to the systems, not to be exposed in http response unless you want to leak information.

**Comment by smt116** [comment]
> If that is the case don't do that. We don't guarantee the exception message is good for sending as response. Exceptions are internals to the systems, not to be exposed in http response unless you want to leak information.

@rafaelfranca it make sense, but then why do rails rescue [such exceptions with a proper HTTP code](https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L8-L24)? If the exceptions are internal to the system, it should always return HTTP 500 Internal Server Error forcing developers to handle them on theirs own.

**Comment by rafaelfranca** [comment]
I didn't said the exception is internal. I said the exception message are internal. What Rails doesn't don't expose the exception, neither the exception message.
