### ISSUE TITLE
Broken routes after installing webpacker

### ISSUE THREAD

**Issue by coliveiraluca** [rails/rails#41605]
Recently I've upgraded an application from rails 5.2 to 6.1.3, following the steps suggested in the rails guides: https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html
The Process went fine the rails project was successfully upgraded.

To proceed with the upgrade on the project we chose to add Webpacker to the project, following the same steps described on the guide and also in the Github from Webpacker.
* Adding the gem in the Gemfile
`gem 'webpacker'`
* Running the following in the console
`bundle install`
`bundle exec rails webpacker:install`

### Expected behavior
Webpacker should be installed with minor impact to the project since the assets are still being loaded properly.
### Actual behavior
Most of the routes were broken, mainly rails don't find the controller either action for a specific endpoint and they are set to `nil` when running `rails routes`.
The only routes shown in the `rails routes` output are the ones with the `to:` param in the `routes.rb`.

### Rails routes output - Webpacker NOT Installed
```                                  Prefix Verb   URI Pattern                                                                                       Controller#Action
                                    ...
                      authenticated_root GET    /                                                                                                 transactions#index
                  transaction_invalidate POST   /transactions/:transaction_id/invalidate(.:format)                                                transactions#invalidate {:transaction_id=>/\d+/}
               transaction_download_slip GET    /transactions/:transaction_id/download_slip(.:format)                                             transactions#download_slip {:transaction_id=>/\d+/}
                     export_transactions GET    /transactions/export(.:format)                                                                    transactions#export
                            transactions GET    /transactions(.:format)                                                                           transactions#index
                                         POST   /transactions(.:format)                                                                           transactions#create
                         new_transaction GET    /transactions/new(.:format)                                                                       transactions#new
                           slip_download GET    /slips/:slip_id/download(.:format)                                                                slips#download
                                   slips GET    /slips(.:format)                                                                                  slips#index
                                    slip GET    /slips/:id(.:format)                                                                              slips#show
                                    ...


```

### Rails routes output - Webpacker Installed
```                                  Prefix Verb   URI Pattern                                                                                       Controller#Action
                                    ...
                      authenticated_root GET    /                                                                                                 transactions#index
                confirmable_transactions GET    /confirmable_transactions(.:format)                                                               nil
                  transaction_invalidate POST   /transactions/:transaction_id/invalidate(.:format)                                                nil {:transaction_id=>/\d+/}
               transaction_download_slip GET    /transactions/:transaction_id/download_slip(.:format)                                             nil {:transaction_id=>/\d+/}
                     export_transactions GET    /transactions/export(.:format)                                                                    nil
                            transactions GET    /transactions(.:format)                                                                           nil
                                         POST   /transactions(.:format)                                                                           nil
                         new_transaction GET    /transactions/new(.:format)                                                                       nil
                           slip_download GET    /slips/:slip_id/download(.:format)                                                                nil
                                   slips GET    /slips(.:format)                                                                                  nil
                                    slip GET    /slips/:id(.:format)                                                                              nil
                                    ...
```

### routes.rb
```
# frozen_string_literal: true

Rails.application.routes.draw do
  ...
  devise_scope :user do
    authenticated :user do
      root 'transactions#index', as: :authenticated_root
    end

  resources :transactions, only: [:index, :new, :create] do
    post :invalidate,    constraints: { transaction_id: /\d+/ }
    get  :download_slip, constraints: { transaction_id: /\d+/ }

    collection do
      get :export
    end
  end
  ...
end
```

### Rspec

Due to that, a series of tests were broken since some routes to controller and action seemed to be not found. Following is the error that shows up in numerous cases

```
     Failure/Error: get :index

     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"anonymous"}
     # /usr/local/rvm/gems/ruby-2.6.3/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/template_assertions.rb:62:in `process'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:35:in `block in process'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:102:in `catch'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:102:in `_catch_warden'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:35:in `process'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/integration.rb:16:in `block (2 levels) in <module:Integration>'
     # ./spec/controllers/application_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

```

### System configuration
**Rails version**: `6.1.3`
**Webpacker version**: `5.2.1`

**Ruby version**: `2.6.3`

**Comment by p8** [comment]
This same ticket was also reported in https://github.com/rails/webpacker/issues/2944
Possibly related ticket in Rspec-rails: https://github.com/rspec/rspec-rails/issues/636

**Comment by p8** [comment]
I think you are missing an end in your routes:
```ruby
  devise_scope :user do
    authenticated :user do
      root 'transactions#index', as: :authenticated_root
    end
 end # This seems to be missing
```

**Comment by p8** [comment]
This is difficult to fix without a reproduction script. @coliveiraluca did you manage to fix this?
