### ISSUE TITLE
precompile problem in rails project

### ISSUE THREAD

**Issue by aliaz-programmer** [rails/rails#41667]
Hi
I started a new rails project on windows 10 and everything works fine but when I want to precompile the assets using 
**rails assets:precompile --trace** I get error like this:

`rails aborted!
Errno::ENOEXEC: Exec format error - "E:/MyProject/bin/yarn" --version
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.3/lib/rails/tasks/yarn.rake:13:in ``'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.3/lib/rails/tasks/yarn.rake:13:in `block (2 levels) in <main>'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.3/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.3/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.3/lib/rails/command.rb:52:in `invoke'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.3/lib/rails/commands.rb:18:in `<main>'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => assets:precompile => yarn:install`

I also have node.js and yarn installed

anyone know the problem?

I'm using Rails version 6.1.3

Ruby version 3.1

**Comment by aliaz-programmer** [comment]
I've found the solution after 6 hours!!

in the "**C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.3/lib/rails/tasks/yarn.rake**" file and in line 13 it use backtics around the path string by default but that cause error. you have to use **‘single’** quotes instead !!!!
its a bug in rake gem that should be fixed in later versions for windows
