### ISSUE TITLE
activesupport-6.0.3.5 dependencies cannot load such file -- polyamorous

### ISSUE THREAD

**Issue by Kacia-Sychyk-ITechArt** [rails/rails#41739]
### Steps to reproduce
I updated the gem 'rails' from '5.2.4.3' to '6.0.3.5'.
The Gemfile now looks like [Gemfile.txt](https://github.com/rails/rails/files/6188613/Gemfile.txt)
The Gemfile.lock looks like [Gemfile-lock.txt](https://github.com/rails/rails/files/6188619/Gemfile-lock.txt)

### Expected behavior
No errors

### Actual behavior
Getting an error when running rspec
```
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

LoadError:
  cannot load such file -- polyamorous
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/bundler/gems/ransack-mongoid-dee6acbbd84d/lib/ransack/adapters/mongoid/context.rb:2:in `<top (required)>'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/bundler/gems/ransack-mongoid-dee6acbbd84d/lib/ransack/adapters/mongoid.rb:12:in `<top (required)>'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/ransack-2.4.2/lib/ransack/adapters.rb:48:in `require_adapter'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/ransack-2.4.2/lib/ransack.rb:26:in `<top (required)>'
# ./config/application.rb:17:in `<top (required)>'
# ./config/environment.rb:2:in `require_relative'
# ./config/environment.rb:2:in `<top (required)>'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
# ./spec/rails_helper.rb:3:in `<top (required)>'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
# /Users/katsiaryna/.rvm/gems/ruby-2.6.6@coverwallet/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
No examples found.
No examples found.
```

### System configuration
**Rails version**:
6.0.3.5
**Ruby version**:
ruby-2.6.6

Appreciate your help! Please, notify me if any other information is needed.

**Comment by intrip** [comment]
from the stacktrace looks like the issue is related to the `coverwallet` gem: what happens if you temporary remove this gem?

**Comment by Kacia-Sychyk-ITechArt** [comment]
coverwallet is a name of rvm gemset. I fixed this issue by explicitly adding the `gem 'polyamorous'` line to my Gemfile. But this does not sound like a good solution. I decided, that the problem is with the active support, because the stacktrace refers to `gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb`. Do you have any idea what may cause a problem?

**Comment by intrip** [comment]
Sorry I ment `polyamorous` :). 
Looks like the problem is that this gem is required from the codebase but not explicitly set as dependency, I think adding the gem to the gemfile is the correct solution, this is not an `activesupport` issue

**Comment by Kacia-Sychyk-ITechArt** [comment]
Thank you for your time!
