### ISSUE TITLE
Autoloading issues in ActiveStorage after upgrade from 5.2.4.5 -> 5.2.5

### ISSUE THREAD

**Issue by PeterLanglois** [rails/rails#41804]
### Steps to reproduce
After upgrading Rails from 5.2.4.5 -> 5.2.5 we are running into this autoloading issue while attempting to either start a server or console.

Error:
```
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:511:in `load_missing_constant': Unable to autoload constant ActiveStorage::Blob::Analyzable, expected /usr/local/bundle/gems/activestorage-5.2.5/app/models/active_storage/blob/analyzable.rb to define it (LoadError)
        from /usr/local/bundle/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:195:in `const_missing'
        from /usr/local/bundle/gems/activestorage-5.2.5/app/models/active_storage/blob.rb:21:in `<class:Blob>'
        from /usr/local/bundle/gems/activestorage-5.2.5/app/models/active_storage/blob.rb:16:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
        from /usr/local/bundle/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:476:in `block in load_file'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:661:in `new_constants_in'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:475:in `load_file'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:373:in `block in require_or_load'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:37:in `block in load_interlock'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies/interlock.rb:13:in `loading'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:37:in `load_interlock'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:356:in `require_or_load'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:334:in `depend_on'
        from /usr/local/bundle/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in depend_on'
        from /usr/local/bundle/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
        from /usr/local/bundle/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `rescue in depend_on'
        from /usr/local/bundle/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `depend_on'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:246:in `require_dependency'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:477:in `each'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:477:in `block in eager_load!'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:475:in `each'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:475:in `eager_load!'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:356:in `eager_load!'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/application/finisher.rb:69:in `each'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `instance_exec'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `run'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
        from /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
        from /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        from /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:60:in `run_initializers'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/application.rb:361:in `initialize!'
        from /app/config/environment.rb:5:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /usr/local/bundle/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /usr/local/bundle/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
        from /usr/local/bundle/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
        from /usr/local/bundle/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
        from /usr/local/bundle/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
        from /usr/local/bundle/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
        from /usr/local/bundle/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
        from /usr/local/bundle/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
```

This _**only**_ happens in environments where rails is configured to eager load classes
```ruby
Rails.application.configure do
  config.eager_load = true
end
```

### Expected behavior

With eager loading classes enabled, start a rails server or open a rails console
```
rails s
```
or 
```
rails c
```

### Actual behavior
With eager loading enabled, rails will crash while autoloading `ActiveStorage::Blob::Analyzable`

### System configuration
**Rails version**: 5.2.5

**Ruby version**: 2.5.7

**Comment by rafaelfranca** [comment]
There where no changes in the code that could explain this new behavior https://github.com/rails/rails/compare/v5.2.4.5...v5.2.5#diff-eec2338fdef55a927e74bdde44f4cd18b6717916113089c3279dee8e790c632f.

The diff if very small and there were not changes to class names or even how constants are loaded.

Are you sure it is related to the Rails upgrade?

Can you reproduce in a new application using Rails 5.2.5?

**Comment by PeterLanglois** [comment]
@rafaelfranca 
Downgrading back to 5.2.4.5 resolves the issues.
I'll try re-creating in a different app, in the meantime, here's the Gemfile.lock diff

```
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -5,25 +5,25 @@ GEM
     Ascii85 (1.0.3)
     aasm (5.0.8)
       concurrent-ruby (~> 1.0)
-    actioncable (5.2.5)
-      actionpack (= 5.2.5)
+    actioncable (5.2.4.5)
+      actionpack (= 5.2.4.5)
       nio4r (~> 2.0)
       websocket-driver (>= 0.6.1)
-    actionmailer (5.2.5)
-      actionpack (= 5.2.5)
-      actionview (= 5.2.5)
-      activejob (= 5.2.5)
+    actionmailer (5.2.4.5)
+      actionpack (= 5.2.4.5)
+      actionview (= 5.2.4.5)
+      activejob (= 5.2.4.5)
       mail (~> 2.5, >= 2.5.4)
       rails-dom-testing (~> 2.0)
-    actionpack (5.2.5)
-      actionview (= 5.2.5)
-      activesupport (= 5.2.5)
+    actionpack (5.2.4.5)
+      actionview (= 5.2.4.5)
+      activesupport (= 5.2.4.5)
       rack (~> 2.0, >= 2.0.8)
       rack-test (>= 0.6.3)
       rails-dom-testing (~> 2.0)
       rails-html-sanitizer (~> 1.0, >= 1.0.2)
-    actionview (5.2.5)
-      activesupport (= 5.2.5)
+    actionview (5.2.4.5)
+      activesupport (= 5.2.4.5)
       builder (~> 3.1)
       erubi (~> 1.4)
       rails-dom-testing (~> 2.0)
@@ -35,24 +35,24 @@ GEM
       jsonapi-renderer (>= 0.1.1.beta1, < 0.3)
     active_record_union (1.3.0)
       activerecord (>= 4.0)
-    activejob (5.2.5)
-      activesupport (= 5.2.5)
+    activejob (5.2.4.5)
+      activesupport (= 5.2.4.5)
       globalid (>= 0.3.6)
     activejob_arguments (0.1.0)
       activejob
-    activemodel (5.2.5)
-      activesupport (= 5.2.5)
-    activerecord (5.2.5)
-      activemodel (= 5.2.5)
-      activesupport (= 5.2.5)
+    activemodel (5.2.4.5)
+      activesupport (= 5.2.4.5)
+    activerecord (5.2.4.5)
+      activemodel (= 5.2.4.5)
+      activesupport (= 5.2.4.5)
       arel (>= 9.0)
     activerecord-import (0.15.0)
       activerecord (>= 3.2)
-    activestorage (5.2.5)
-      actionpack (= 5.2.5)
-      activerecord (= 5.2.5)
-      marcel (~> 1.0.0)
-    activesupport (5.2.5)
+    activestorage (5.2.4.5)
+      actionpack (= 5.2.4.5)
+      activerecord (= 5.2.4.5)
+      marcel (~> 0.3.1)
+    activesupport (5.2.4.5)
       concurrent-ruby (~> 1.0, >= 1.0.2)
       i18n (>= 0.7, < 2)
       minitest (~> 5.1)
@@ -277,7 +277,8 @@ GEM
       nokogiri (>= 1.5.9)
     mail (2.7.1)
       mini_mime (>= 0.1.1)
-    marcel (1.0.0)
+    marcel (0.3.3)
+      mimemagic (~> 0.3.2)
     message_format (0.0.5)
       twitter_cldr (~> 4.0)
     method_source (0.9.2)
@@ -285,6 +286,9 @@ GEM
     mime-types (3.2.2)
       mime-types-data (~> 3.2015)
     mime-types-data (3.2018.0812)
+    mimemagic (0.3.10)
+      nokogiri (~> 1)
+      rake
     mini_mime (1.0.3)
     mini_portile2 (2.5.0)
     minitest (5.14.4)
@@ -341,27 +345,27 @@ GEM
     rack-test (1.1.0)
       rack (>= 1.0, < 3)
     rack-timeout (0.6.0)
-    rails (5.2.5)
-      actioncable (= 5.2.5)
-      actionmailer (= 5.2.5)
-      actionpack (= 5.2.5)
-      actionview (= 5.2.5)
-      activejob (= 5.2.5)
-      activemodel (= 5.2.5)
-      activerecord (= 5.2.5)
-      activestorage (= 5.2.5)
-      activesupport (= 5.2.5)
+    rails (5.2.4.5)
+      actioncable (= 5.2.4.5)
+      actionmailer (= 5.2.4.5)
+      actionpack (= 5.2.4.5)
+      actionview (= 5.2.4.5)
+      activejob (= 5.2.4.5)
+      activemodel (= 5.2.4.5)
+      activerecord (= 5.2.4.5)
+      activestorage (= 5.2.4.5)
+      activesupport (= 5.2.4.5)
       bundler (>= 1.3.0)
-      railties (= 5.2.5)
+      railties (= 5.2.4.5)
       sprockets-rails (>= 2.0.0)
     rails-dom-testing (2.0.3)
       activesupport (>= 4.2.0)
       nokogiri (>= 1.6)
     rails-html-sanitizer (1.3.0)
       loofah (~> 2.3)
-    railties (5.2.5)
-      actionpack (= 5.2.5)
-      activesupport (= 5.2.5)
+    railties (5.2.4.5)
+      actionpack (= 5.2.4.5)
+      activesupport (= 5.2.4.5)
       method_source
       rake (>= 0.8.7)
       thor (>= 0.19.0, < 2.0)
@@ -614,7 +618,7 @@ DEPENDENCIES
   rack-cors
   rack-test
   rack-timeout
-  rails (~> 5.2.0)
+  rails (~> 5.2.4.5)
   redis
   request_store
   retries

```

**Comment by PeterLanglois** [comment]
It's unclear as to why, but it seems to be related to our `storage.yml` config.
Switching the storage service from S3 to Disk allows Rails to successfully boot.

from: 
```yaml
stage:
  service: S3
  region: <%= ENV["S3_REGION"] %>
  bucket: <%= ENV["S3_BUCKET"] %>
```
to
```yaml
stage:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
```

Obviously this isn't a usable solution, but just narrowing down a cause.
Not seeing anything in the diff that would have changed S3 connection requirements though..

**Comment by PeterLanglois** [comment]
I'm seeing [this line](https://github.com/rails/rails/blob/cb0a558f42fc6957fac4d2daa16771b72ff7da6e/activestorage/lib/active_storage/service/s3_service.rb#L3)
added in [this diff](https://github.com/rails/rails/compare/v5.2.4.5...v5.2.5)

If I comment that out, it seems to resolve the issue.
I don't see any changelog about this, are there supposed to be steps to upgrade with this change?

**Comment by rafaelfranca** [comment]
That line is just making sure your app is using "aws-sdk-s3" "~> 1.48", it should not require any change in the app if you are using that version. Is that the case?

**Comment by PeterLanglois** [comment]
Right, sorry my comment was misleading. Upgrading to that version worked.
This seems to be a new dependency requirement that wasn't documented. 
So I just want to make sure there aren't any other upgrade steps required for v5.2.5.

**Comment by rafaelfranca** [comment]
Not that I'm aware. I'm surprised you had to upgrade the aws gem to `1.48` since that version is from 2019.

**Comment by crberube** [comment]
I have seen this same issue on Rails `6.1.3` and Ruby `3.0.0`. Setting the autoloader to `classic` mode as described [here](https://github.com/rails/rails/issues/38681#issuecomment-780228293) solved the issue, though that is obviously not a long-term solution.

**Comment by amiratak88** [comment]
This is still an issue.
