### ISSUE TITLE
InsertAll does not work with tables with overridden primary_key

### ISSUE THREAD

**Issue by grk** [rails/rails#41848]
### Steps to reproduce

In our case, we have a partitioned table in postgres 12, which requires us to set `self.primary_key = "id"` in the model. Because of that, while `Model.primary_key` returns `"id"`, `ApplicationRecord.connection.schema_cache.primary_keys(Model.table_name)` returns `nil`.

### Expected behavior

`insert_all` should keep working for this table after upgrading from 6.0.x to 6.1.3.1.

### Actual behavior

`insert_all` fails with error
```
     ArgumentError:
       No unique index found for id
     # /Users/grk/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/insert_all.rb:82:in `find_unique_index_for'
     # /Users/grk/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/insert_all.rb:25:in `initialize'
```

It seems that this is happening since https://github.com/rails/rails/commit/1af44e4aeeb04a6360b5104d8ee7b4a042ef93d8#diff-3f89af7ff219385718b7c0e4635cc4190476349db18f8bf80fb84fa1e7f5e289R35, where the array of primary keys is taken from the schema cache instead of the model. Because of that, https://github.com/rails/rails/commit/1af44e4aeeb04a6360b5104d8ee7b4a042ef93d8#diff-3f89af7ff219385718b7c0e4635cc4190476349db18f8bf80fb84fa1e7f5e289R64 does not pick up the case for inserting with uniqueness by primary key, as it compares `["id"] == []`.

I'd like to open a PR but I'm not sure what the correct solution would be. One approach would be to revert to the previous implementation of `primary_keys`. Another would be to change it to something like `Array(connection.schema_cache.primary_keys(model.table_name)).presence || Array(model.primary_key)`.

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: 2.7.2

**Comment by ghiculescu** [comment]
@grk  did you find a workaround here?
@lsylvester do you have any ideas on a fix?

**Comment by lsylvester** [comment]
Are you using `on_duplicate` at all? I think that we should only need to find the unique index if we are using the `on_duplicate` option. The original implementation only looked for it if we had a `unique_by` - which you wouldn't have had so the look up would have been skipped. I think that if we only look up the unique index if a `on_duplicate` option is set - then if should work for your case while still allowing for on_duplicates of the primary key.
