### ISSUE TITLE
`prepare called on a closed database` when accessing ActiveRecord objects whilst using multiple databases

### ISSUE THREAD

**Issue by mtcmorris** [rails/rails#41876]
### Steps to reproduce

1. Have a rails codebase with multiple databases according to [this](https://guides.rubyonrails.org/active_record_multiple_databases.html#setting-up-your-application) - replicated on a [new rails codebase](https://github.com/mtcmorris/multi-db-migration-issue/commit/7900c2b2fa70113d0d512249bef8c53a3e10255f)

2. Write a migration than accesses an ActiveRecord object

```ruby
class TestMigrationIssue < ActiveRecord::Migration[6.1]
  def change
    add_column :boats, :name, :string

    # Any ActiveRecord query on any model will cause this issue
    Boat.update(name: "Something")

    change_column_null :boats, :name, false
  end
end
```

3. Run `bundle exec rails db:migrate:primary`

### Expected behavior

Migration should complete

### Actual behavior

```
== 20210408060158 TestMigrationIssue: migrating ===============================
-- add_column(:boats, :name, :string)
   -> 0.0018s
-- change_column_null(:boats, :name, false)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

prepare called on a closed database
vendor/bundle/ruby/2.7.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `initialize'
vendor/bundle/ruby/2.7.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `new'
vendor/bundle/ruby/2.7.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `prepare'
vendor/bundle/ruby/2.7.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:193:in `execute'
vendor/bundle/ruby/2.7.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:659:in `rollback'
```

The database is closed (`change_column_null`) fails.

pg adapter has the same issue

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: 2.7.2

**Comment by mtcmorris** [comment]
Looks like this is a dupe of https://github.com/rails/rails/issues/41855 - closing.
