### ISSUE TITLE
Error printing out migration file with -p option

### ISSUE THREAD

**Issue by verdywid** [rails/rails#41900]
### Steps to reproduce
1. Generate a new rails project
2. `bundle exec rails g migration CreateCompanies -p`

### Expected behavior
It prints out a filename to be created, eg. `db/migrate/20210410170741_create_companies.rb`

### Actual behavior
It produced an error
```
~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/actions.rb:116:in `relative_to_original_destination_root': undefined method `start_with?' for false:FalseClass (NoMethodError)
        from ~/.gem/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/generators/actions/create_migration.rb:36:in `relative_existing_migration'
	from ~/.gem/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/generators/actions/create_migration.rb:24:in `invoke!'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/actions.rb:93:in `action'
	from ~/.gem/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/generators/migration.rb:36:in `create_migration'
	from ~/.gem/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/generators/migration.rb:65:in `migration_template'
	from ~/.gem/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/rails/generators/active_record/migration/migration_generator.rb:17:in `create_migration_file'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_all'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `each'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `map'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `invoke_all'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:232:in `dispatch'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:277:in `block in _invoke_for_class_method'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/shell.rb:68:in `with_padding'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:266:in `_invoke_for_class_method'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:134:in `_invoke_from_option_orm'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_all'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `each'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `map'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `invoke_all'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:232:in `dispatch'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from ~/.gem/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/generators.rb:275:in `invoke'
	from ~/.gem/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from ~/.gem/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/command/base.rb:69:in `perform'
	from ~/.gem/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/command.rb:50:in `invoke'
	from ~/.gem/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/commands.rb:18:in `<main>'
	from ~/.gem/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from ~/.gem/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from ~/.gem/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from ~/.gem/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from ~/.gem/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from ~/.gem/ruby/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from ~/dev/rails-test/bin/rails:5:in `<main>'
	from ~/.gem/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from ~/.gem/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from ~/.gem/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:10:in `block in fork'
	from ~/.gem/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:10:in `block in fork'
	from ~/.gem/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:8:in `fork'
	from ~/.gem/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:8:in `fork'
	from ~/.gem/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:26:in `fork'
	from ~/.gem/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:8:in `fork'
	from ~/.gem/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:26:in `fork'
	from -e:1:in `require'
	from -e:1:in `<main>'
```

But it worked fine without the `-p` options.

### System configuration
**Rails version**:
6.1.3.1
**Ruby version**:
3.0.0

**Comment by eugeneius** [comment]
This has already been fixed in https://github.com/rails/rails/pull/41255, and will work again in the next release.
