### ISSUE TITLE
Session options are nil. Unable to add sessions and automatic connection switching to an api_only app.

### ISSUE THREAD

**Issue by maxrosecollins** [rails/rails#41932]
I recently updated sidekiq and I need to use sessions in my api_only rails app as per [6.2.1](https://github.com/mperham/sidekiq/blob/master/Changes.md#621). I've tried to add them back in per the [docs](https://edgeguides.rubyonrails.org/api_app.html#using-session-middlewares), but it doesn't work. If I set `config.api_only = true` to `config.api_only = false` then it all works as expected. I opened an issue in the [sidekiq repo](https://github.com/mperham/sidekiq/issues/4872) and I was directed here.

### Steps to reproduce
`config/application.rb`
```
    config.api_only = true

    # This also configures session_options for use below
    config.session_store :cookie_store, key: '_interslice_session'

    # Required for all session management (regardless of session_store)
    config.middleware.use ActionDispatch::Cookies
    config.middleware.use ActionDispatch::Session::CookieStore, key: '_interslice_session'
    config.middleware.insert_after(ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, key: '_interslice_session')

    config.middleware.use config.session_store, config.session_options

```

### Expected behavior
It should load the session cookie config?

### Actual behavior
It looks like the sessions aren't working and the web part of my app won't boot.

```
F, [2021-04-12T09:20:34.579998 #33] FATAL -- : [389c9875-8447-43d7-9e18-bde804be0f4a]
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] NoMethodError (undefined method `[]=' for nil:NilClass):
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a]
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/request/session.rb:235:in `load!'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/request/session.rb:230:in `load_for_write!'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/request/session.rb:216:in `merge!'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/request/session.rb:19:in `create'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/middleware/session/abstract_store.rb:71:in `prepare_session'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] rack (2.2.3) lib/rack/session/abstract/id.rb:265:in `context'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] rack (2.2.3) lib/rack/static.rb:161:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] rack (2.2.3) lib/rack/builder.rb:244:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] sidekiq (6.2.1) lib/sidekiq/web.rb:108:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] sidekiq (6.2.1) lib/sidekiq/web.rb:113:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/middleware/database_selector.rb:53:in `block in call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/middleware/database_selector/resolver.rb:63:in `block (2 levels) in read_from_replica'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/middleware/database_selector/resolver.rb:62:in `block in read_from_replica'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/connection_handling.rb:383:in `block (2 levels) in with_role_and_shard'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:1025:in `while_preventing_writes'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/connection_handling.rb:381:in `block in with_role_and_shard'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/connection_handling.rb:398:in `swap_connection_handler'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/connection_handling.rb:373:in `with_handler'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/connection_handling.rb:380:in `with_role_and_shard'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/connection_handling.rb:175:in `connected_to'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/middleware/database_selector/resolver.rb:61:in `read_from_replica'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/middleware/database_selector/resolver.rb:39:in `read'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/middleware/database_selector.rb:63:in `select_database'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activerecord (6.1.3.1) lib/active_record/middleware/database_selector.rb:52:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] rack (2.2.3) lib/rack/etag.rb:27:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] rack (2.2.3) lib/rack/head.rb:12:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] appsignal (3.0.2) lib/appsignal/rack/rails_instrumentation.rb:32:in `call_with_appsignal_monitoring'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] appsignal (3.0.2) lib/appsignal/rack/rails_instrumentation.rb:17:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] railties (6.1.3.1) lib/rails/rack/logger.rb:37:in `call_app'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `block in call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:37:in `tagged'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `tagged'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] activesupport (6.1.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] actionpack (6.1.3.1) lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] puma (5.2.2) lib/puma/configuration.rb:248:in `call'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] puma (5.2.2) lib/puma/request.rb:76:in `block in handle_request'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] puma (5.2.2) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] puma (5.2.2) lib/puma/request.rb:75:in `handle_request'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] puma (5.2.2) lib/puma/server.rb:431:in `process_client'
web-74b87b954b-tqv78 — [389c9875-8447-43d7-9e18-bde804be0f4a] puma (5.2.2) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] rack (2.2.3) lib/rack/head.rb:12:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] activesupport (6.1.3.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] actionpack (6.1.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] appsignal (3.0.2) lib/appsignal/rack/rails_instrumentation.rb:32:in `call_with_appsignal_monitoring'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] appsignal (3.0.2) lib/appsignal/rack/rails_instrumentation.rb:17:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] actionpack (6.1.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] actionpack (6.1.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] railties (6.1.3.1) lib/rails/rack/logger.rb:37:in `call_app'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `block in call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:37:in `tagged'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `tagged'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] actionpack (6.1.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] actionpack (6.1.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] activesupport (6.1.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] actionpack (6.1.3.1) lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] puma (5.2.2) lib/puma/configuration.rb:248:in `call'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] puma (5.2.2) lib/puma/request.rb:76:in `block in handle_request'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] puma (5.2.2) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] puma (5.2.2) lib/puma/request.rb:75:in `handle_request'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] puma (5.2.2) lib/puma/server.rb:431:in `process_client'
web-74b87b954b-j8pbj — [564a856e-9bfb-45e9-ba16-a2fa8d4ed391] puma (5.2.2) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

### System configuration
Ruby version: 2.7.2
Rails version: 6.1.3.1
Sidekiq version: 6.2.1
Sidekiq Pro version: 5.2.2

**Comment by Elgonzo422** [comment]
Have you tried it on the sidekiq version you were running before the update?

**Comment by maxrosecollins** [comment]
@Elgonzo422 before I updated sidekiq it didn't require sessions.

This line `config.middleware.use config.session_store, config.session_options` prevents any of my web requests from succeeding. I only mention sidekiq because I need to use sessions to get the sidekiq web ui to work.

**Comment by rafaelfranca** [comment]
Can you check what is the value of `config.session_options`?

**Comment by maxrosecollins** [comment]
If I put byebug here;

```

# This also configures session_options for use below
config.session_store :cookie_store, key: '_interslice_session'

# Required for all session management (regardless of session_store)
config.middleware.use ActionDispatch::Cookies

byebug

config.middleware.use config.session_store, config.session_options
```

I can see `{:key=>"_interslice_session"}`

If I run the app in development and use the interactive debugger I can see this error.
`#<NameError: undefined local variable or method `config' for #<ActionDispatch::Request::Session:0x9ab0 not yet loaded>>` 
![Screenshot 2021-04-13 at 11 20 55](https://user-images.githubusercontent.com/784189/114529525-52775f80-9c4a-11eb-9bbc-5cdd48fd6c3b.png)

**Comment by maxrosecollins** [comment]
@rafaelfranca I found the issue.

I created a new rails api app `rails new my_api --api --database=postgresql`

These are the only changes I made.

I added sessions and the read/write database config.

```
# This also configures session_options for use below
    config.session_store :cookie_store, key: '_interslice_session'

    # Required for all session management (regardless of session_store)
    config.middleware.use ActionDispatch::Cookies

    config.middleware.use config.session_store, config.session_options

    config.active_record.database_selector = { delay: 2.seconds }
    config.active_record.database_resolver = ActiveRecord::Middleware::DatabaseSelector::Resolver
    config.active_record.database_resolver_context = ActiveRecord::Middleware::DatabaseSelector::Resolver::Session
```

**Comment by maxrosecollins** [comment]
@eileencodes Do you have any ideas about this?

**Comment by gmcgibbon** [comment]
https://github.com/rails/rails/blob/adc0146a07ccc72405aec78ccb65aac3502a4300/actionpack/lib/action_dispatch/request/session.rb#L17-L19

On API only apps, there appears to be data in the `"rack.session"` header of the request that is an empty hash. This doesn't seem to happen on normal apps.

**Comment by gmcgibbon** [comment]
The database selector calls

https://github.com/rails/rails/blob/e2781c2d93808031fbc4dbecaa7aac59aa90b4b8/activerecord/lib/active_record/middleware/database_selector/resolver/session.rb#L14

which calls `request.session` and then this sets the session to a hash:

https://github.com/rails/rails/blob/e2781c2d93808031fbc4dbecaa7aac59aa90b4b8/actionpack/lib/action_dispatch/http/request.rb#L365-L369

That explains the difference in behaviour, but the error itself suggests session options might need to be set before merging, options is `nil` until set for new sessions:

https://github.com/rails/rails/blob/adc0146a07ccc72405aec78ccb65aac3502a4300/actionpack/lib/action_dispatch/request/session.rb#L19-L22

**Comment by maxrosecollins** [comment]
@gmcgibbon Thank you for figuring it out!

Is there a temp fix I can apply my side by any chance?

**Comment by gmcgibbon** [comment]
@maxrosecollins I believe this should work, but keep an eye on the PR if the implementation changes:

```rb
ActiveSupport.on_load(:action_dispatch_request) do
  def reset_session
    if session && session.respond_to?(:destroy)
      session.destroy
    else
      default_session
    end
  end

  def session
    fetch_header(RACK_SESSION) do |k|
      set_header RACK_SESSION, default_session
    end
  end
end
```

**Comment by casperisfine** [comment]
Quick heads up about https://github.com/rails/rails/pull/42231, writing into a session without having it properly configured will now explicitly raise.

Also I haven't read too carefully into the reported issue here, but I don't think `ActiveRecord::Middleware::DatabaseSelector::Resolver::Session` is suitable if you are implementing an API. You probably want to implement your own selector that doesn't use a session (or to have some kind of custom session store that does session on a per API client basis).

**Comment by 308820773** [comment]
When I  remove **
**

**Comment by adobnikar** [comment]
I had the same issue using rails 6.0.6

For me, this issue was resolved by rearranging the middleware sequence.
You can print your middleware sequence by running the `rake middleware` command.
With the help of the command, you can check how the middleware is arranged with the `config.api_only = false` and how it is arranged with `config.api_only = false`.
Then try to match the sequence with `config.api_only = false` as closely as possible.

This error appeared because the Cookies middleware was called too late in the stack.
The solution was to move it a few places up the stack.

This code snippet worked for me (put it in the `config/application.rb` file):

```ruby
config.api_only = true
if config.api_only
  config.session_store :cookie_store, key: '_interslice_session'
  config.middleware.insert_after ActiveRecord::Migration::CheckPending, ActionDispatch::Cookies
  config.middleware.insert_after ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, config.session_options
end
```

**Comment by shawndeprey** [comment]
I've run into this issue multiple times in one of my projects and hit it again when upgrading to rails 7.1.1. I previously used @gmcgibbon solution above, which worked great, but due to changes in rails 7.1, this solution broke. I tested @adobnikar solution above, and it does work, however, it does have the side-effect of an additional required cooked in requests, which may not be optimal in your use case, as it isn't for mine.

An additional solution to this problem is a modification of @gmcgibbon solution. I've been testing this in both local and production scale environments for a couple of days and it works great at resolving this problem in rails 7.1.1. If anyone spots inconsistencies or improvements to this solution, please note them here and I will update this solution with those improvements.

```ruby
ActiveSupport.on_load(:action_dispatch_request) do
  def reset_session
    if session && session.respond_to?(:destroy)
      session.destroy
    else
      default_session
    end
  end

  def session
    fetch_header(Rack::RACK_SESSION) do |k|
      set_header Rack::RACK_SESSION, default_session
    end
  end

  private
    def default_session
      self.session_options = {}
      self.session = SessionFallback.new
    end

    class SessionFallback < Hash
      def initialize
        @data = {}
      end
    
      def id
        nil
      end
    
      # Retrieve a value by its key
      def [](key)
        @data[key]
      end
    
      # Set a value by its key
      def []=(key, value)
        @data[key] = value
      end
    end
end
```

**Comment by skipkayhil** [comment]
@shawndeprey  Why is any patch needed? I believe Gannon's solution was a stop gap until the PR was merged, but now that its merged the patch should no longer be necessary.

If you are still having an issue on Rails 7.1 can you open a new issue and include a reproduction app to demonstrate the issue?

**Comment by shawndeprey** [comment]
Hey @skipkayhil, thanks for jumping in. Upon updating to rails 7.1.1 and trying to make write requests to my Rails app, I started getting the following error when I have the patch disabled. Modifying the patch ended up resolving the issue for me. Am I missing something in new and necessary configuration for Rails which makes this patch no longer necessary?

```
ActionDispatch::Request::Session::DisabledSessionError (Your application has sessions disabled. To write to the session you must first configure a session store):
actionpack (7.1.1) lib/action_dispatch/request/session.rb:260:in `load_for_write!'
actionpack (7.1.1) lib/action_dispatch/request/session.rb:153:in `[]='
activerecord (7.1.1) lib/active_record/middleware/database_selector/resolver/session.rb:39:in `update_last_write_timestamp'
activerecord (7.1.1) lib/active_record/middleware/database_selector/resolver.rb:73:in `block (2 levels) in write_to_primary'
activesupport (7.1.1) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activerecord (7.1.1) lib/active_record/middleware/database_selector/resolver.rb:70:in `block in write_to_primary'
activerecord (7.1.1) lib/active_record/connection_handling.rb:361:in `with_role_and_shard'
activerecord (7.1.1) lib/active_record/connection_handling.rb:147:in `connected_to'
activerecord (7.1.1) lib/active_record/middleware/database_selector/resolver.rb:69:in `write_to_primary'
activerecord (7.1.1) lib/active_record/middleware/database_selector/resolver.rb:44:in `write'
activerecord (7.1.1) lib/active_record/middleware/database_selector.rb:79:in `select_database'
activerecord (7.1.1) lib/active_record/middleware/database_selector.rb:66:in `call'
rack (2.2.8) lib/rack/etag.rb:27:in `call'
rack (2.2.8) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.8) lib/rack/head.rb:12:in `call'
activerecord (7.1.1) lib/active_record/migration.rb:653:in `call'
actionpack (7.1.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (7.1.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (7.1.1) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
actionpack (7.1.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.1) lib/action_dispatch/middleware/actionable_exceptions.rb:16:in `call'
actionpack (7.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (7.1.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (7.1.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (7.1.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (7.1.1) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
actionpack (7.1.1) lib/action_dispatch/middleware/request_id.rb:28:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (7.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.1.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.1) lib/action_dispatch/middleware/static.rb:25:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
rack (2.2.8) lib/rack/deflater.rb:44:in `call'
actionpack (7.1.1) lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
rack-cors (2.0.1) lib/rack/cors.rb:102:in `call'
railties (7.1.1) lib/rails/engine.rb:529:in `call'
puma (6.3.0) lib/puma/configuration.rb:270:in `call'
puma (6.3.0) lib/puma/request.rb:100:in `block in handle_request'
puma (6.3.0) lib/puma/thread_pool.rb:344:in `with_force_shutdown'
puma (6.3.0) lib/puma/request.rb:99:in `handle_request'
puma (6.3.0) lib/puma/server.rb:443:in `process_client'
puma (6.3.0) lib/puma/server.rb:245:in `block in run'
puma (6.3.0) lib/puma/thread_pool.rb:151:in `block in spawn_thread'
```

**Comment by skipkayhil** [comment]
The error you're getting is probably correct. The Database Resolver middleware by default uses the Session to determine how long ago the last write was, so if you don't have any Session configured it can't work properly. If you don't want to use a cookie to hold the session, then you should use one of the alternative session stores (or use a custom Database Resolver that doesn't require a session).

The patch above was specifically for the ```NoMethodError (undefined method `[]=' for nil:NilClass):``` even when a session had been configured.
