### ISSUE TITLE
Upgraded from Rails 4 to 6: uninitialized constant ActiveRecord::ConnectionAdapters::SchemaCache

### ISSUE THREAD

**Issue by chiragd** [rails/rails#42021]
I upgraded a rather old app from rails 4.2 to 6.1.3.1. The app runs fine locally, but when I try to deploy it to my server using capistrano I get the error below. It states that

```
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::SchemaCache 
     ** Did you mean?  ActiveRecord::Schema
```
This occurs when running bundle exec rake assets:precompile either via capistrano or manually on the server. I've tried setting some flags in application.rb like:
`
config.assets.initialize_on_precompile = false`
However this did not fix the issue. I feel like I've exhausted my knowledge and search skills. Could someone help point me in the right direction please?

```
  * executing "cd -- /home/user/app_rails6/releases/20210419123208 && RAILS_ENV=staging RAILS_GROUPS=assets bundle exec rake assets:precompile"
  * executing command
 ** rake aborted! 
 ** NameError: uninitialized constant ActiveRecord::ConnectionAdapters::SchemaCache 
 ** Did you mean?  ActiveRecord::Schema
 **  
 ** /home/user/app_rails6/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.3.1/lib/active_record/railtie.rb:139:in `block (3 levels) in <class:Railtie>'
 **  
 ** /home/user/app_rails6/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
 **  
 ** /home/user/app_rails6/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
 ** /home/user/app_rails6/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
------trace truncated by author------
```

When I use an environment which uses sqlite as the database, the command runs fine. When I use an environment which uses postgres as the database I get the error.

Is this a rails error?

**Comment by benoittgt** [comment]
Hello @chiragd

I am wondering if your issue isn't linked to something that is loaded in an initializer. Also maybe an issue with what is loaded into your `RAILS_GROUPS`?

Do you think you can post a bigger stack trace?

**Comment by chiragd** [comment]
I added

autoload :SchemaCache to /usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters.rb and it seemed to solve the issue.

I now have a new issue:

```
RAILS_ENV=staging RAILS_GROUPS=assets bundle exec rake assets:precompile
rake aborted!
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::Column::Deduplicable
```

I've removed this change so I can give you the full trace:


```
RAILS_ENV=staging RAILS_GROUPS=assets bundle exec rake assets:precompile
rake aborted!
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::SchemaCache
Did you mean?  ActiveRecord::Schema
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activerecord-6.1.3.1/lib/active_record/railtie.rb:139:in `block (3 levels) in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:42:in `each'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activerecord-6.1.3.1/lib/active_record/railtie.rb:131:in `block (2 levels) in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/railties-6.1.3.1/lib/rails/application/finisher.rb:140:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `run'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/railties-6.1.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/railties-6.1.3.1/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/railties-6.1.3.1/lib/rails/application.rb:384:in `initialize!'
/home/user/dev/rails/app_rails6/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/railties-6.1.3.1/lib/rails/application.rb:360:in `require_environment!'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/railties-6.1.3.1/lib/rails/application.rb:526:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

**Comment by chiragd** [comment]
@benoittgt I downgraded to rails 6.0.3 and it worked fine. Something is broken on 6.1.3 and 6.1.3.1. How do we fix?

**Comment by benoittgt** [comment]
Do you think you `git bisect` Rails to identify the commit?

**Comment by chiragd** [comment]
I am afraid I am a bit out of my depth here.

**Comment by rafaelfranca** [comment]
It was introduced by https://github.com/rails/rails/commit/b71c1cddddea736ae5af70474fe9bd765596e727. The issue was fixed in 6175549eaf3ab866632e9684455b5096cfbd0f2f and aa67785d7f

**Comment by chiragd** [comment]
Thanks @rafaelfranca when is this likely to be available to use?

**Comment by rafaelfranca** [comment]
Beginning of may or so, but you can use right now right you point your Gemfile to 6-1-stable branch.

**Comment by chiragd** [comment]
Hi @rafaelfranca , I updated my Gemfile to use the 6-1-stable branch. I have a new error now:

```
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::Column::Deduplicable
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/connection_adapters/column.rb:8:in `<class:Column>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/connection_adapters/column.rb:7:in `<module:ConnectionAdapters>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/connection_adapters/column.rb:5:in `<module:ActiveRecord>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/connection_adapters/column.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/connection_adapters/schema_cache.rb:12:in `block in load_from'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/connection_adapters/schema_cache.rb:22:in `read'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/connection_adapters/schema_cache.rb:11:in `load_from'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/railtie.rb:139:in `block (3 levels) in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:42:in `each'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/railtie.rb:131:in `block (2 levels) in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/application/finisher.rb:140:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/initializable.rb:32:in `run'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/application.rb:391:in `initialize!'
/home/user/dev/rails/app-rails6/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/dependencies.rb:332:in `require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/application.rb:367:in `require_environment!'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
ArgumentError: undefined class/module Struct::ActiveRecord::
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/connection_adapters/schema_cache.rb:12:in `block in load_from'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/connection_adapters/schema_cache.rb:22:in `read'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/connection_adapters/schema_cache.rb:11:in `load_from'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/railtie.rb:139:in `block (3 levels) in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:42:in `each'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activerecord/lib/active_record/railtie.rb:131:in `block (2 levels) in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/application/finisher.rb:140:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/initializable.rb:32:in `run'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/application.rb:391:in `initialize!'
/home/user/dev/rails/app-rails6/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/activesupport/lib/active_support/dependencies.rb:332:in `require'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/application.rb:367:in `require_environment!'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bundler/gems/rails-aa67785d7f86/railties/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
/usr/local/rvm/gems/ruby-2.6.3@apr21/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.3@apr21/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

**Comment by chiragd** [comment]
@rafaelfranca friendly reminder on this one. Should I file a new bug?

**Comment by rafaelfranca** [comment]
It seems this is related to your schema cache being in an old format. How did you generate this schema cache file? With which version of Rails?

**Comment by rafaelfranca** [comment]
Actually, this is another autoload bug. I now wish I could duplication this in a new app. Are you able to replicate this same failure in a new app?

**Comment by rafaelfranca** [comment]
8e7c3f407a should fix this new bug. Let me know if you still see errors and if you are able to replicate in a new app.
