### ISSUE TITLE
undefined method `find_script_name' for nil:NilClass

### ISSUE THREAD

**Issue by psunix** [rails/rails#42218]
### Steps to reproduce
1. update from rails 6.0.x to 6.1.3.2
2. access running application from webbrowser or execute integration specs

after a restart of the rails server, it sometimes works. then it is raises the exception again after a few requests.

### Expected behavior
path helper should not raise any exceptions :)

### Actual behavior
exception is raised: 

`undefined method `find_script_name' for nil:NilClass`

```
     ActionView::Template::Error:
       undefined method `find_script_name' for nil:NilClass
     # ./app/views/session/local/new.html.haml:9:in `_app_views_session_local_new_html_haml__3352878839210418481_44280'
     # /opt/bundle/ruby/2.7.0/gems/sentry-raven-3.1.2/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
     # /opt/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
     # /opt/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
     # /opt/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
     # /opt/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
     # /opt/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
     # /opt/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
     # /opt/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:37:in `call_app'
     # /opt/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:26:in `block in call'
     # /opt/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:26:in `call'
     # /opt/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
     # /opt/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
     # /opt/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
     # /opt/bundle/ruby/2.7.0/gems/sentry-raven-3.1.2/lib/raven/integrations/rack.rb:51:in `call'
     # /opt/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/engine.rb:539:in `call'
     # /opt/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /opt/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /opt/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # ./spec/integration/root_login_spec.rb:32:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `find_script_name' for nil:NilClass
     #   ./app/views/session/local/new.html.haml:9:in `_app_views_session_local_new_html_haml__3352878839210418481_44280'
```
### System configuration
**Rails version**:
6.1.3.2

**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

Project: https://github.com/puzzle/cryptopus/tree/feature/374-rails-update

**Comment by hernanat** [comment]
hi there! I'm looking into this, but if you change `session_local_path` to `Rails.application.routes.url_helpers.session_local_path` in your view, it works for now if you want to continue on with your upgrade. I noticed that you have some other unrelated test failures.

While debugging I noticed that [this](https://github.com/rails/rails/commit/5b4df9d0eb295d402489465f3600576038f5762d#diff-4eb6ab15abbdcf7f87bfebb27baf8982326e86fff05fead4b0da795496fcd1eeR38) codepath was getting hit, which @tenderlove added some time ago. Will try to look into it more later unless anyone has an answer as to what's going on.

**Comment by hernanat** [comment]
full backtrace for anyone else who wants to look into this:
<details>
<summary>Backtrace</summary>

```
Run options: include {:locations=>{"./spec/integration/root_login_spec.rb"=>[29]}}
F

Failures:

  1) Root login does not let root login with wrong password
     Failure/Error: = form_tag(session_local_path, class: 'login') do

     ActionView::Template::Error:
       undefined method `find_script_name' for nil:NilClass
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route_set.rb:203:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route_set.rb:326:in `block in define_url_helper'
     # ./app/views/session/local/new.html.haml:9:in `_app_views_session_local_new_html_haml__2291102583304789329_43920'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/base.rb:247:in `public_send'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/base.rb:247:in `_run'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/template.rb:154:in `block in render'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/template.rb:345:in `instrument_render_template'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/template.rb:152:in `render'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/renderer/template_renderer.rb:11:in `render'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/rendering.rb:117:in `block in _render_template'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/base.rb:273:in `in_rendering_context'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/rendering.rb:116:in `_render_template'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/streaming.rb:218:in `_render_template'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/rendering.rb:103:in `render_to_body'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/abstract_controller/rendering.rb:25:in `render'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/rendering.rb:36:in `render'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
     # /$RUBIES/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/core_ext/benchmark.rb:14:in `ms'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
     # /$GEM_HOME/ruby/2.7.2/gems/activerecord-6.1.3.2/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/instrumentation.rb:45:in `render'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/abstract_controller/base.rb:228:in `process_action'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
     # /$GEM_HOME/ruby/2.7.2/gems/sentry-raven-3.1.2/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:137:in `run_callbacks'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
     # /$GEM_HOME/ruby/2.7.2/gems/activerecord-6.1.3.2/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/abstract_controller/base.rb:165:in `process'
     # /$GEM_HOME/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/rendering.rb:39:in `process'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal.rb:190:in `dispatch'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_controller/metal.rb:254:in `dispatch'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route_set.rb:33:in `serve'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/journey/router.rb:50:in `block in serve'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/journey/router.rb:32:in `each'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/journey/router.rb:32:in `serve'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route_set.rb:842:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
     # /$GEM_HOME/ruby/2.7.2/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/cookies.rb:689:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:37:in `call_app'
     # /$GEM_HOME/ruby/2.7.2/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:26:in `block in call'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `block in tagged'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:37:in `tagged'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `tagged'
     # /$GEM_HOME/ruby/2.7.2/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:26:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/request_id.rb:26:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/activesupport-6.1.3.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/static.rb:24:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/sentry-raven-3.1.2/lib/raven/integrations/rack.rb:51:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/railties-6.1.3.2/lib/rails/engine.rb:539:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /$GEM_HOME/ruby/2.7.2/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /$GEM_HOME/ruby/2.7.2/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/testing/integration.rb:279:in `process'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/testing/integration.rb:16:in `get'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/testing/integration.rb:71:in `public_send'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/testing/integration.rb:71:in `follow_redirect!'
     # /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/testing/integration.rb:372:in `follow_redirect!'
     # ./spec/integration/root_login_spec.rb:32:in `block (2 levels) in <top (required)>'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-rails-5.0.1/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /$GEM_HOME/ruby/2.7.2/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
     # /$GEM_HOME/ruby/2.7.2/bin/rspec:23:in `load'
     # /$GEM_HOME/ruby/2.7.2/bin/rspec:23:in `<top (required)>'
     # /$RUBIES/ruby-2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
     # /$RUBIES/ruby-2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
     # /$RUBIES/ruby-2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
     # /$RUBIES/ruby-2.7.2/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
     # /$RUBIES/ruby-2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /$RUBIES/ruby-2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     # /$RUBIES/ruby-2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
     # /$RUBIES/ruby-2.7.2/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
     # /$RUBIES/ruby-2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
     # /$RUBIES/ruby-2.7.2/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
     # /$RUBIES/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
     # /$RUBIES/ruby-2.7.2/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
     # /$RUBIES/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
     # /$RUBIES/ruby-2.7.2/bin/bundle:23:in `load'
     # /$RUBIES/ruby-2.7.2/bin/bundle:23:in `<main>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `find_script_name' for nil:NilClass
     #   /$GEM_HOME/ruby/2.7.2/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route_set.rb:203:in `call'

Finished in 0.99125 seconds (files took 3.98 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/integration/root_login_spec.rb:29 # Root login does not let root login with wrong password
```
</details>

**Comment by HParker** [comment]
Are you able to reproduce this issue with the reproduction script?

https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller_main.rb

This helps us verify where the problem is.

Thanks!

**Comment by AlexanderCohen** [comment]
I understand that this has been closed, however, has there been a resolution to this issue? I'm experiencing it in Rails 7.

**Comment by obromios** [comment]
I have a similar problem with a [gem](https://github.com/obromios/rails_fancies) that I am supporting.  Using rails 6.0.5.1 then all tests pass. However when I upgrade to rails 6.1.5.1 all tests fail, with the following type of error

```
Failure/Error: routes.url_helpers.respond_to?(m) ? routes.url_helpers.send(m, *args) : super
      
      NoMethodError:
        undefined method `url_helpers' for nil:NilClass
```
The master branch of the gem uses `rails 6.0.5.1` and the `rails_6_1` branch uses `rails 6.1.5.1`.

**Comment by ajkovar** [comment]
+1

**Comment by obromios** [comment]
I am not sure, but it appears that upgrading to rails `6.1.6.1` solved the problem.

**Comment by swtiit** [comment]
@23tux @obromios 
I'm also experiencing a similar issue to yours, where I sometimes encounter errors when running a web application on the server. However, this error is not common and I am not sure what specific error it is, so I do not know how to solve it.

My solution is simply restarting the web server, which usually resolves the issue. If either of you has any solutions, please share them with me. Thank you.

For context, I am using Ruby 2.7.2 and Rails 6.1.6.1.

**Comment by pixiitech** [comment]
I am dealing with this issue as well. It appears that in `lib/action_dispatch/routing/route_set.rb` line 203, `_routes` is nil causing the errors. I tried what users above have done with prefixing the route helpers with `Rails.application.routes.url_helpers.` (I used a LinkHelper class) and this worked until I had to render a Rails form. This caused another similar issue where I would get an error "undefined method `polymorphic_mappings`", also due to `_routes` being nil in `lib/action_dispatch_routing/polymorphic_routes.rb` line 170. 

My only way of continuing was to downgrade to Rails 6.0.6. I hope this is fixed in Rails 7.

**Comment by pixiitech** [comment]
Can this issue be reopened? It's preventing an upgrade to Rails 7 for me now.

**Comment by skipkayhil** [comment]
> Can this issue be reopened? It's preventing an upgrade to Rails 7 for me now.

If you include a reproduction script that fails on Rails 7, feel free to open a new issue

**Comment by jdaviderb** [comment]
@pixiitech I'm having this same error in Rails 7

I was able to resolve the problem with a temporary fix. It may not be the most elegant solution, but it's a temporal fix until the core team can address the issue.

```ruby
module ApplicationHelper
# app/helpers/application_helper.rb

  Rails.application.routes.url_helpers.instance_methods.each do |method|
    if method.to_s.include?("_path")
      define_method(method) do |*args, **kwargs|
        Rails.application.routes.url_helpers.send(method, *args, **kwargs)
      end
    end
  end

end
```

**Comment by anquinn** [comment]
I'm also running into the error `undefined method 'polymorphic_mappings' for nil:NilClass`. This issue is the only place I can find a reference to it. Unfortunately, @jdaviderb's solution doesn't seem to work for me. 

What's odd is that restarting the server in development fixes the issue temporarily, but it comes back after loading a form for a second time.

**Comment by rafaelfranca** [comment]
> What's odd is that restarting the server in development fixes the issue temporarily, but it comes back after loading a form for a second time.

This is a signal that something in your app is strange. Can you try to reproduce in a new Rails application? Maybe the problem is in a library, or in some patch to Rails that you are doing.

**Comment by pixiitech** [comment]
> I'm also running into the error `undefined method 'polymorphic_mappings' for nil:NilClass`. This issue is the only place I can find a reference to it. Unfortunately, @jdaviderb's solution doesn't seem to work for me. I get the error when trying to use a basic form: `<%= form_with(model: @feedback) do |form| %>` on rails 7.0.8.
> 
> What's odd is that restarting the server in development fixes the issue temporarily, but it comes back after loading a form for a second time.

I was able to work around this error by specifying `url` to the form explicitly (with @jdaviderb's solution)

**Comment by anquinn** [comment]
For future individuals who come across this issue - I had included url_helpers in a mailer that weren't necessary. Removing the include statement solved the problem. 

The proposed solution above didn't entirely solve the issue when I tried it. Thank you @rafaelfranca for the assistance.

**Comment by benjamin-hg** [comment]
I had the same symptoms as @anquinn descdribed in https://github.com/rails/rails/issues/42218#issuecomment-1737861134 

The patch suggested by @jdaviderb worked, but on forms I kept getting the `undefined method 'polymorphic_mappings' for nil:NilClass` ... but only on my AWS EB instance and not when running locally. 

I've managed to reproduce the issue locally by setting `RACK_ENV=production` which helped a lot with my experiments.

Thanks to @anquinn's last post I found this:

```page_blueprint.rb
# frozen_string_literal: true

include Rails.application.routes.url_helpers  # <-- removing this line solves the issue 🎉 

module Api
  module V1
    class PageBlueprint < Blueprinter::Base
      view :my_view do
        #  ....
      end
    end
  end
end
```
