### ISSUE TITLE
Incompatibility between api_only, session middleware and automatic database connection switching

### ISSUE THREAD

**Issue by jgrau** [rails/rails#42306]
### Steps to reproduce

1. Create a new rails api only application `rails new --api`
2. Configure application for multiple databases as described in https://guides.rubyonrails.org/active_record_multiple_databases.html#setting-up-your-application
3. Add session middleware back into the api only application as described in https://guides.rubyonrails.org/api_app.html#using-session-middlewares
4. Activate automatic connection switching as described in https://guides.rubyonrails.org/active_record_multiple_databases.html#activating-automatic-connection-switching
5. Visiting the welcome page will not fail.

[This repo](https://github.com/jgrau/api-only-with-replica) contains an application with a failing integration test. [The commit history](https://github.com/jgrau/api-only-with-replica/commits/master) might be useful - it follows the same steps as above.

### Expected behavior

Automatic database switching should work

### Actual behavior

This error is raised:

```
❯ BACKTRACE=1 rake
Run options: --seed 34305

# Running:

E

Error:
FooTest#test_can_see_the_welcome_page:
NoMethodError: undefined method `[]=' for nil:NilClass
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/request/session.rb:235:in `load!'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/request/session.rb:230:in `load_for_write!'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/request/session.rb:216:in `merge!'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/request/session.rb:19:in `create'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/session/abstract_store.rb:71:in `prepare_session'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:265:in `context'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/cookies.rb:689:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/middleware/database_selector.rb:53:in `block in call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/middleware/database_selector/resolver.rb:63:in `block (2 levels) in read_from_replica'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/middleware/database_selector/resolver.rb:62:in `block in read_from_replica'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_handling.rb:388:in `with_role_and_shard'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_handling.rb:175:in `connected_to'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/middleware/database_selector/resolver.rb:61:in `read_from_replica'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/middleware/database_selector/resolver.rb:39:in `read'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/middleware/database_selector.rb:63:in `select_database'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/middleware/database_selector.rb:52:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:37:in `call_app'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:26:in `block in call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `block in tagged'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:37:in `tagged'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `tagged'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:26:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/request_id.rb:26:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/static.rb:24:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.1.3.2/lib/rails/engine.rb:539:in `call'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/testing/integration.rb:279:in `process'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/testing/integration.rb:16:in `get'
    /Users/jgrau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/testing/integration.rb:372:in `get'
    /Users/jgrau/src/api-only-with-replica/test/integration/foo_test.rb:5:in `block in <class:FooTest>'
```
### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin20]

**Comment by lfalcao** [comment]
Related https://github.com/rails/rails/issues/41932

**Comment by jgrau** [comment]
> Related #41932

Thank you for referencing that issue - I hadn't seen that. This issue seems like a duplicate so I'll close it.

**Comment by zzak** [comment]
@jgrau Would you mind giving #42216 a shot and see if that solves your need?

**Comment by jgrau** [comment]
> @jgrau Would you mind giving #42216 a shot and see if that solves your need?

@zzak that PR makes my test green 👍

**Comment by zzak** [comment]
@jgrau Thanks for confirming!
