### ISSUE TITLE
Can't finish `rails new` with edge Ruby.

### ISSUE THREAD

**Issue by yamat47** [rails/rails#42329]
### Steps to reproduce
1. Install edge version Ruby via rbenv.
2. Exec `rbenv local 3.1.0-dev`.

```
$ cat .ruby-version
3.1.0-dev

$ ruby --version
ruby 3.1.0dev (2021-05-31T12:26:24Z master 3954799071) [x86_64-darwin20]
```

3. Exec `gem install rails`.

```
$ gem install rails
Successfully installed rails-6.1.3.2
1 gem installed

$ rails --version
Rails 6.1.3.2
```

4. Exec `rails new .`.

```
$ rails new .
       exist
      create  README.md
      create  Rakefile
   identical  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Reinitialized existing Git repository in /Users/takuya_yamaguchi/src/github.com/yamat47/rails-sample-app-20210531/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/spring
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_6_1.rb
      create  config/initializers/permissions_policy.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_6_1.rb
         run  bundle install
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies....
Fetching gem metadata from https://rubygems.org/.
Using rake 13.0.3
Using concurrent-ruby 1.1.8
Using minitest 5.14.4
Using crass 1.0.6
Using builder 3.2.4
Using zeitwerk 2.4.2
Using rack 2.2.3
Using nio4r 2.5.7
Using mini_mime 1.0.3
Using public_suffix 4.0.6
Using racc 1.5.2
Using erubi 1.10.0
Using bundler 2.3.0.dev
Using marcel 1.0.1
Using regexp_parser 2.1.1
Using timeout 0.1.1
Using ffi 1.15.1
Using msgpack 1.4.2
Using rb-fsevent 0.11.0
Using method_source 1.0.0
Using thor 1.1.0
Using rubyzip 2.3.0
Using semantic_range 3.0.0
Using spring 2.1.1
Using sqlite3 1.4.2
Using turbolinks-source 5.2.0
Using i18n 1.8.10
Using tzinfo 2.0.4
Using rack-test 1.1.0
Using rack-mini-profiler 2.3.2
Using rack-proxy 0.7.0
Using sprockets 4.0.2
Using mail 2.7.1
Using puma 5.3.2
Using addressable 2.7.0
Using bootsnap 1.7.5
Using activesupport 6.1.3.2
Using rb-inotify 0.10.1
Using sassc 2.4.0
Using turbolinks 5.2.1
Using globalid 0.4.2
Using activemodel 6.1.3.2
Using jbuilder 2.11.2
Using listen 3.5.1
Using activejob 6.1.3.2
Using activerecord 6.1.3.2
Using date 3.1.1
Using tilt 2.0.10
Using time 0.1.0
Using websocket-extensions 0.1.5
Using io-wait 0.1.1
Using websocket-driver 0.7.4
Using net-protocol 0.1.1
Using childprocess 3.0.0
Using net-ftp 0.1.2
Using selenium-webdriver 3.142.7
Using mini_portile2 2.5.2
Using bindex 0.8.1
Using nokogiri 1.11.6
Using byebug 11.1.3
Using rails-dom-testing 2.0.3
Using loofah 2.9.1
Using xpath 3.2.0
Using rails-html-sanitizer 1.3.0
Using capybara 3.35.3
Using actionview 6.1.3.2
Using webdrivers 4.6.0
Using actionpack 6.1.3.2
Using actioncable 6.1.3.2
Using activestorage 6.1.3.2
Using actionmailer 6.1.3.2
Using actionmailbox 6.1.3.2
Using sprockets-rails 3.2.2
Using actiontext 6.1.3.2
Using railties 6.1.3.2
Using rails 6.1.3.2
Using sassc-rails 2.1.2
Using web-console 4.1.0
Using sass-rails 6.0.0
Using webpacker 5.4.0
Bundle complete! 17 Gemfile dependencies, 80 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  webpacker:install
Warning: the running version of Bundler (2.2.18) is older than the version that created the lockfile (2.3.0.dev). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.0.dev --pre`.
Rails couldn't infer whether you are using multiple databases from your database.yml and can't generate the tasks for the non-primary databases. If you'd like to use this feature, please simplify your ERB.
Warning: you are using an unstable release of Node.js (v15.6.0). If you encounter issues with Node.js, consider switching to an Active LTS release. More info: https://docs.npmjs.com/try-the-latest-stable-version-of-node
Rails couldn't infer whether you are using multiple databases from your database.yml and can't generate the tasks for the non-primary databases. If you'd like to use this feature, please simplify your ERB.
rails aborted!
Psych::BadAlias: Cannot load database configuration:
Unknown alias: default
/Users/takuya_yamaguchi/src/github.com/yamat47/rails-sample-app-20210531/config/environment.rb:5:in `<main>'
/Users/takuya_yamaguchi/src/github.com/yamat47/rails-sample-app-20210531/bin/rails:5:in `<top (required)>'
/Users/takuya_yamaguchi/src/github.com/yamat47/rails-sample-app-20210531/bin/spring:10:in `require'
/Users/takuya_yamaguchi/src/github.com/yamat47/rails-sample-app-20210531/bin/spring:10:in `block in <top (required)>'
/Users/takuya_yamaguchi/src/github.com/yamat47/rails-sample-app-20210531/bin/spring:7:in `<top (required)>'

Caused by:
Psych::BadAlias: Unknown alias: default
/Users/takuya_yamaguchi/src/github.com/yamat47/rails-sample-app-20210531/config/environment.rb:5:in `<main>'
/Users/takuya_yamaguchi/src/github.com/yamat47/rails-sample-app-20210531/bin/rails:5:in `<top (required)>'
/Users/takuya_yamaguchi/src/github.com/yamat47/rails-sample-app-20210531/bin/spring:10:in `require'
/Users/takuya_yamaguchi/src/github.com/yamat47/rails-sample-app-20210531/bin/spring:10:in `block in <top (required)>'
/Users/takuya_yamaguchi/src/github.com/yamat47/rails-sample-app-20210531/bin/spring:7:in `<top (required)>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
```

### Expected behavior
`rails new .` is finished without any errors.

### Actual behavior
`Psych::BadAlias` is raised and `rails new .` is not finished.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: ruby 3.1.0dev (2021-05-31T12:26:24Z master 3954799071) [x86_64-darwin20]

**Comment by yamat47** [comment]
I realized this issue for [yamat47/activerecord_accessible_json's CI failure.](https://github.com/yamat47/activerecord_accessible_json/runs/2706483289) CI checks if this gem is compatible with edge Ruby and edge Rails everyday, but failed with edge Ruby from May 17.

On May 18, some commits are added to [ruby/psych](https://github.com/ruby/psych):

* https://github.com/ruby/psych/commit/ffa2791c5b5f689611f0464eff509af50fc09da9
* https://github.com/ruby/psych/commit/c27c4a02210ddb494930e6361b311c5dfe621838
* https://github.com/ruby/psych/commit/3fabcb953f04b4c4927b419d6d91026f65e984af
* https://github.com/ruby/psych/commit/f8a5e512a1856231bf10c80e8a08714b06fb95c4

Especially https://github.com/ruby/psych/commit/f8a5e512a1856231bf10c80e8a08714b06fb95c4 changed `YAML.load_file`'s behavior and this may cause this issue.

**Comment by zzak** [comment]
Hello Yamaguchi-san,

Thanks for your report!

I've also seen this when trying to use rails edge but haven't gotten around to figuring out why.

**Comment by zzak** [comment]
Using the latest commit of ruby to generate `rails new --main`:

```
Bundle complete! 17 Gemfile dependencies, 74 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  webpacker:install
Warning: the running version of Bundler (2.2.18) is older than the version that created the lockfile (2.3.0.dev). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.0.dev --pre`.
Rails couldn't infer whether you are using multiple databases from your database.yml and can't generate the tasks for the non-primary databases. If you'd like to use this feature, please simplify your ERB.
Rails couldn't infer whether you are using multiple databases from your database.yml and can't generate the tasks for the non-primary databases. If you'd like to use this feature, please simplify your ERB.
rails aborted!
Psych::BadAlias: Cannot load database configuration:
Unknown alias: default
/private/var/folders/v9/r0l99jh94k3cqr9wk3jvzmvr0000gn/T/tmp.Fam9UEA4/--main/config/environment.rb:5:in `<main>'
/private/var/folders/v9/r0l99jh94k3cqr9wk3jvzmvr0000gn/T/tmp.Fam9UEA4/--main/bin/rails:5:in `<top (required)>'
/private/var/folders/v9/r0l99jh94k3cqr9wk3jvzmvr0000gn/T/tmp.Fam9UEA4/--main/bin/spring:10:in `require'
/private/var/folders/v9/r0l99jh94k3cqr9wk3jvzmvr0000gn/T/tmp.Fam9UEA4/--main/bin/spring:10:in `block in <top (required)>'
/private/var/folders/v9/r0l99jh94k3cqr9wk3jvzmvr0000gn/T/tmp.Fam9UEA4/--main/bin/spring:7:in `<top (required)>'

Caused by:
Psych::BadAlias: Unknown alias: default
/private/var/folders/v9/r0l99jh94k3cqr9wk3jvzmvr0000gn/T/tmp.Fam9UEA4/--main/config/environment.rb:5:in `<main>'
/private/var/folders/v9/r0l99jh94k3cqr9wk3jvzmvr0000gn/T/tmp.Fam9UEA4/--main/bin/rails:5:in `<top (required)>'
/private/var/folders/v9/r0l99jh94k3cqr9wk3jvzmvr0000gn/T/tmp.Fam9UEA4/--main/bin/spring:10:in `require'
/private/var/folders/v9/r0l99jh94k3cqr9wk3jvzmvr0000gn/T/tmp.Fam9UEA4/--main/bin/spring:10:in `block in <top (required)>'
/private/var/folders/v9/r0l99jh94k3cqr9wk3jvzmvr0000gn/T/tmp.Fam9UEA4/--main/bin/spring:7:in `<top (required)>'

$ ruby -v
ruby 3.1.0dev (2021-06-01T05:56:22Z master 0d32a18f5b) [x86_64-darwin19]
```

**Comment by zzak** [comment]
cc #42257

**Comment by yamat47** [comment]
@zzak Thank you for your comments! 

I tried `rails new` again with the latest Ruby and **the latest Rails (at ee8134d6f98660fb4de66e2bafc2e8d8df2ca593)** and this succeeded!
Probably #42257 fixed this problem.

Will #42257 be backported into 6.1 or 6.0? 
@casperisfine [says he will backport this into 6.1](https://github.com/rails/rails/pull/42257#issuecomment-844051751), but have not finished yet? 😊

**Comment by casperisfine** [comment]
I did backport it to 6-1-stable https://github.com/rails/rails/commit/255b5ff9af57f9b54dee7ec884b12a1ad16f0321

**Comment by yamat47** [comment]
@casperisfine 

> I did backport it to 6-1-stable 255b5ff

Thanks! 

I also tried with `6-1-stable` Rails and succeeded! I'm looking forward to new 6.1 release🥺

**Comment by zzak** [comment]
Ok, I was able to confirm that if you "rails new" from a version of Rails that includes the `yaml.load` patch then this works. Closing this issue 🙏
