### ISSUE TITLE
ActionCable: RemoteConnection.disconnect - Wrong Number of Arguments

### ISSUE THREAD

**Issue by KuroBayashi** [rails/rails#42377]
### Steps to reproduce
Hello,

I was trying to find a way to "unsubscribe" an User for a specific Channel from the server side, something like:
```ruby
ChatRoomChannel.unsubscribe(@user, @room)    # ? 
```
so I could use it when banning an User from a Room, but couldn't find anything that specific, only found this command (from the api doc):

```ruby
ActionCable.server.remote_connections.where(current_user: @user).disconnect
```

And here is my code:
```yaml
# app/config/cable.yml
development:
  adapter: postgresql
```
```ruby
# app/channels/application_cable/connection.rb
module ApplicationCable
class Connection < ActionCable::Connection::Base

	identified_by :current_user

	# --------------------------------------------------------------------------
	# Public methods
	# --------------------------------------------------------------------------
	def connect
		self.current_user = find_verified_user
	end

	# --------------------------------------------------------------------------
	# Private methods
	# --------------------------------------------------------------------------
	private

	def find_verified_user
		if verified_user = env['warden'].user
			verified_user
		else
			reject_unauthorized_connection
		end
	end

end
end
```
```ruby
# app/channels/chat_room_channel.rb
class ChatRoomChannel < ApplicationCable::Channel

	# --------------------------------------------------------------------------
	# Callbacks
	# --------------------------------------------------------------------------
	before_subscribe :set_room

	before_subscribe :check_allowed_to_access

	# --------------------------------------------------------------------------
	# Public methods
	# --------------------------------------------------------------------------
	def subscribed
		stream_for @room
	end

	def unsubscribed
		# Any cleanup needed when channel is unsubscribed
	end

	# --------------------------------------------------------------------------
	# Private methods
	# --------------------------------------------------------------------------
	private

	def set_room
		@room = Chat::Room.find_by(id: params[:id])
	end

	# Cancancan
	def check_allowed_to_access
		reject unless current_user.can?(:access, @room)
	end

end
```

### Expected behavior
Like said in the documentation, I was expecting to disconnect all connections from `@user`.

### Actual behavior
But I'm getting the following error:
```
ArgumentError in Api::Chat::RolesController#create

wrong number of arguments (given 1, expected 2)

Extracted source (around line #24):

#22    module Broadcasting
#23        # Broadcast a hash directly to a named <tt>broadcasting</tt>. This will later be JSON encoded.
*24        def broadcast(broadcasting, message, coder: ActiveSupport::JSON)
#25            broadcaster_for(broadcasting, coder: coder).broadcast(message)
#26        end
#27 

Extracted source (around line #48):

#46    # Uses the internal channel to disconnect the connection.
#47    def disconnect
*48        server.broadcast internal_channel, type: "disconnect"
#49    end
#50 
#51    # Returns all the identifiers that were applied to this connection.

Extracted source (around line #36):
#34
#35
*36        ActionCable.server.remote_connections.where(current_user: @user).disconnect
#37 
#38    end
#39

Rails.root: /var/learning_ror

Application Trace
app/controllers/api/chat/roles_controller.rb:36:in `create'

Framework Trace
actioncable (6.1.3.1) lib/action_cable/server/broadcasting.rb:24:in `broadcast'
actioncable (6.1.3.1) lib/action_cable/remote_connections.rb:48:in `disconnect'
actionpack (6.1.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.1.3.1) lib/abstract_controller/base.rb:228:in `process_action'
actionpack (6.1.3.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
```

### System configuration
**Rails version**:
Rails 6.1.3.1

**Ruby version**:
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux-musl]

**Comment by KuroBayashi** [comment]
Already reported, didn't see it before, my bad. #41890
