### ISSUE TITLE
ActiveRecord merge method error in Rails 6.0.4

### ISSUE THREAD

**Issue by patorash** [rails/rails#42531]
After updating to Rails 6.0.4, I got an error in the merge method of ActiveRecord.

### Steps to reproduce

```ruby
# example
foos = Foo.joins(:bar).where(bars: { id: 1..10 })
bars = Bar.eager_load(:foos).merge(foos).records # error!
```

Rails 6.0.3.7

```sql
FROM
  "bars"
  LEFT OUTER JOIN
    "foos"
  ON  "foos"."bar_id" = "bars"."id"
  INNER JOIN
    "bars" "bars_foos"
  ON  "bars_foos"."id" = "foos"."bar_id"
```

Rails 6.0.4

```sql
FROM
  "bars"
  INNER JOIN
    "bars" "bars_foos"
  ON  "bars_foos"."id" = "foos"."bar_id" -- foos table not found.
  LEFT OUTER JOIN
    "foos"
  ON  "foos"."bar_id" = "bars"."id"
```

### System configuration
**Rails version**: 6.0.4

**Ruby version**: 2.7.3

**Database**: PostgreSQL 11

**Comment by lfalcao** [comment]
@patorash can you make a reproduction script? https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb

**Comment by patorash** [comment]
@lfalcao lfalcao When I tried it with sqlite3, to my surprise, the test passed.
However, when I checked it with PostgreSQL, the test failed.

### sqlite3

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.text :content
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.text :content
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(title: "Title", content: "Content")
    post.comments << Comment.create!(content: "Comment")

    posts = Post.joins(:comments).where(comments: { content: "Comment" })
    comments = Comment.eager_load(:post).merge(posts)

    assert_equal "Title", comments.first.post.title
  end
end
```

#### sqlite3 result

```
-- create_table(:posts, {:force=>true})
D, [2021-06-20T07:25:12.174098 #96182] DEBUG -- :    (1.6ms)  SELECT sqlite_version(*)
D, [2021-06-20T07:25:12.174528 #96182] DEBUG -- :    (0.1ms)  DROP TABLE IF EXISTS "posts"
D, [2021-06-20T07:25:12.174992 #96182] DEBUG -- :    (0.3ms)  CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar, "content" text)
   -> 0.0108s
-- create_table(:comments, {:force=>true})
D, [2021-06-20T07:25:12.175295 #96182] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "comments"
D, [2021-06-20T07:25:12.175519 #96182] DEBUG -- :    (0.1ms)  CREATE TABLE "comments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "post_id" integer, "content" text)
   -> 0.0005s
D, [2021-06-20T07:25:12.206486 #96182] DEBUG -- :    (0.1ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
D, [2021-06-20T07:25:12.223529 #96182] DEBUG -- :   ActiveRecord::InternalMetadata Load (5.3ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]
D, [2021-06-20T07:25:12.227703 #96182] DEBUG -- :   TRANSACTION (0.1ms)  begin transaction
D, [2021-06-20T07:25:12.228047 #96182] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.1ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "development"], ["created_at", "2021-06-19 22:25:12.227311"], ["updated_at", "2021-06-19 22:25:12.227311"]]
D, [2021-06-20T07:25:12.228359 #96182] DEBUG -- :   TRANSACTION (0.1ms)  commit transaction
Run options: --seed 27839

# Running:

D, [2021-06-20T07:25:12.271242 #96182] DEBUG -- :   TRANSACTION (0.1ms)  begin transaction
D, [2021-06-20T07:25:12.271590 #96182] DEBUG -- :   Post Create (0.1ms)  INSERT INTO "posts" ("title", "content") VALUES (?, ?)  [["title", "Title"], ["content", "Content"]]
D, [2021-06-20T07:25:12.271965 #96182] DEBUG -- :   TRANSACTION (0.1ms)  commit transaction
D, [2021-06-20T07:25:12.281692 #96182] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-06-20T07:25:12.281871 #96182] DEBUG -- :   Comment Create (0.1ms)  INSERT INTO "comments" ("content") VALUES (?)  [["content", "Comment"]]
D, [2021-06-20T07:25:12.282062 #96182] DEBUG -- :   TRANSACTION (0.1ms)  commit transaction
D, [2021-06-20T07:25:12.287559 #96182] DEBUG -- :   TRANSACTION (0.1ms)  begin transaction
D, [2021-06-20T07:25:12.287759 #96182] DEBUG -- :   Comment Update (0.1ms)  UPDATE "comments" SET "post_id" = ? WHERE "comments"."id" = ?  [["post_id", 1], ["id", 1]]
D, [2021-06-20T07:25:12.287942 #96182] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-06-20T07:25:12.295612 #96182] DEBUG -- :   SQL (0.2ms)  SELECT "comments"."id" AS t0_r0, "comments"."post_id" AS t0_r1, "comments"."content" AS t0_r2, "posts"."id" AS t1_r0, "posts"."title" AS t1_r1, "posts"."content" AS t1_r2 FROM "comments" INNER JOIN "comments" "comments_posts" ON "comments_posts"."post_id" = "posts"."id" LEFT OUTER JOIN "posts" ON "posts"."id" = "comments"."post_id" WHERE "comments"."content" = ? ORDER BY "comments"."id" ASC LIMIT ?  [["content", "Comment"], ["LIMIT", 1]]
.

Finished in 0.028729s, 34.8080 runs/s, 34.8080 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

### PostgreSQL

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "pg", "~> 1.2.3"
  # gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

system('dropdb --host=localhost --port=5432 --username=postgres --if-exists active_record_main')
system('createdb --owner=postgres --host=localhost --port=5432 --username=postgres active_record_main')

# This connection will do for database-independent bug reports.
# ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
# ActiveRecord::Base.logger = Logger.new(STDOUT)

# for postgresql setting
ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  database: "active_record_main",
  user: "postgres",
  host: "localhost",
  port: 5432,
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.text :content
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.text :content
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(title: "Title", content: "Content")
    post.comments << Comment.create!(content: "Comment")

    posts = Post.joins(:comments).where(comments: { content: "Comment" })
    comments = Comment.eager_load(:post).merge(posts)

    assert_equal "Title", comments.first.post.title
  end
end
```

#### PostgreSQL result

```
-- create_table(:posts, {:force=>true})
D, [2021-06-20T07:10:09.967859 #94747] DEBUG -- :    (5.5ms)  DROP TABLE IF EXISTS "posts"
D, [2021-06-20T07:10:10.002100 #94747] DEBUG -- :    (34.0ms)  CREATE TABLE "posts" ("id" bigserial primary key, "title" character varying, "content" text)
   -> 0.1070s
-- create_table(:comments, {:force=>true})
D, [2021-06-20T07:10:10.004498 #94747] DEBUG -- :    (2.0ms)  DROP TABLE IF EXISTS "comments"
D, [2021-06-20T07:10:10.017778 #94747] DEBUG -- :    (12.9ms)  CREATE TABLE "comments" ("id" bigserial primary key, "post_id" integer, "content" text)
   -> 0.0156s
D, [2021-06-20T07:10:10.063438 #94747] DEBUG -- :    (9.7ms)  CREATE TABLE "ar_internal_metadata" ("key" character varying NOT NULL PRIMARY KEY, "value" character varying, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)
D, [2021-06-20T07:10:10.086186 #94747] DEBUG -- :   ActiveRecord::InternalMetadata Load (1.7ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
D, [2021-06-20T07:10:10.096708 #94747] DEBUG -- :   TRANSACTION (1.5ms)  BEGIN
D, [2021-06-20T07:10:10.100287 #94747] DEBUG -- :   ActiveRecord::InternalMetadata Create (3.4ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "key"  [["key", "environment"], ["value", "development"], ["created_at", "2021-06-19 22:10:10.094828"], ["updated_at", "2021-06-19 22:10:10.094828"]]
D, [2021-06-20T07:10:10.102573 #94747] DEBUG -- :   TRANSACTION (2.0ms)  COMMIT
Run options: --seed 43152

# Running:

D, [2021-06-20T07:10:10.140199 #94747] DEBUG -- :   TRANSACTION (1.6ms)  BEGIN
D, [2021-06-20T07:10:10.142548 #94747] DEBUG -- :   Post Create (2.2ms)  INSERT INTO "posts" ("title", "content") VALUES ($1, $2) RETURNING "id"  [["title", "Title"], ["content", "Content"]]
D, [2021-06-20T07:10:10.145548 #94747] DEBUG -- :   TRANSACTION (2.7ms)  COMMIT
D, [2021-06-20T07:10:10.164977 #94747] DEBUG -- :   TRANSACTION (1.7ms)  BEGIN
D, [2021-06-20T07:10:10.167292 #94747] DEBUG -- :   Comment Create (2.1ms)  INSERT INTO "comments" ("content") VALUES ($1) RETURNING "id"  [["content", "Comment"]]
D, [2021-06-20T07:10:10.169625 #94747] DEBUG -- :   TRANSACTION (2.1ms)  COMMIT
D, [2021-06-20T07:10:10.179634 #94747] DEBUG -- :   TRANSACTION (1.6ms)  BEGIN
D, [2021-06-20T07:10:10.183432 #94747] DEBUG -- :   Comment Update (3.6ms)  UPDATE "comments" SET "post_id" = $1 WHERE "comments"."id" = $2  [["post_id", 1], ["id", 1]]
D, [2021-06-20T07:10:10.185673 #94747] DEBUG -- :   TRANSACTION (2.0ms)  COMMIT
D, [2021-06-20T07:10:10.198576 #94747] DEBUG -- :   SQL (2.8ms)  SELECT "comments"."id" AS t0_r0, "comments"."post_id" AS t0_r1, "comments"."content" AS t0_r2, "posts"."id" AS t1_r0, "posts"."title" AS t1_r1, "posts"."content" AS t1_r2 FROM "comments" INNER JOIN "comments" "comments_posts" ON "comments_posts"."post_id" = "posts"."id" LEFT OUTER JOIN "posts" ON "posts"."id" = "comments"."post_id" WHERE "comments"."content" = $1 ORDER BY "comments"."id" ASC LIMIT $2  [["content", "Comment"], ["LIMIT", 1]]
E

Error:
BugTest#test_association_stuff:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "posts"
LINE 1: ... "comments_posts" ON "comments_posts"."post_id" = "posts"."i...
                                                             ^

    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:706:in `exec_params'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:706:in `block (2 levels) in exec_no_cache'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activesupport/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activesupport/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activesupport/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:705:in `block in exec_no_cache'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activesupport/lib/active_support/notifications/instrumenter.rb:44:in `instrument'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:704:in `exec_no_cache'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:683:in `execute_and_clear'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:51:in `exec_query'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:547:in `select'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation.rb:918:in `block (2 levels) in exec_main_query'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation/finder_methods.rb:445:in `apply_join_dependency'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation.rb:912:in `block in exec_main_query'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation.rb:944:in `skip_query_cache_if_necessary'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation.rb:908:in `exec_main_query'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation.rb:894:in `block in exec_queries'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation.rb:944:in `skip_query_cache_if_necessary'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation.rb:888:in `exec_queries'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation.rb:675:in `load'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation.rb:256:in `records'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation.rb:251:in `to_ary'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation/finder_methods.rb:562:in `find_nth_with_limit'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation/finder_methods.rb:547:in `find_nth'
    /Users/toko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-cde84b85eb76/activerecord/lib/active_record/relation/finder_methods.rb:148:in `first'
    active_record_main.rb:65:in `test_association_stuff'


rails test active_record_main.rb:58



Finished in 0.073168s, 13.6672 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by zzak** [comment]
@kamipo Do you have any ideas? 🙏

**Comment by yahonda** [comment]
FYI. based on the git bisect result, this behavior change has been introduced since https://github.com/rails/rails/commit/f9ba52477ca288e7effa5f6794ae3df3f4e982bc

```
% git bisect good                                                       (git)-[v6.0.4~145|bisect]-
f9ba52477ca288e7effa5f6794ae3df3f4e982bc is the first bad commit
commit f9ba52477ca288e7effa5f6794ae3df3f4e982bc
Author: Ryuta Kamizono <kamipo@gmail.com>
Date:   Thu May 14 06:22:50 2020 +0900

    Merge pull request #39268 from kamipo/fix_merging_multiple_left_joins

    Fix left joins order when merging multiple left joins from different associations

 activerecord/lib/active_record/relation/merger.rb  |  9 +++++++--
 .../lib/active_record/relation/query_methods.rb    | 22 ++++++++++++++--------
 .../left_outer_join_association_test.rb            | 11 ++++++++++-
 3 files changed, 31 insertions(+), 11 deletions(-)
%
```

**Comment by kamipo** [comment]
Thank you for the report. I'll take a look tomorrow.

**Comment by etsenake** [comment]
Any updates on this? Hitting this error as well, is it fixed in newer rails versions? is there a workaround I can use? will re-writing the query on our end without merge at least give us a temporary fix?

**Comment by andriusch** [comment]
Until this is fixed as a workaround you might be able to do:
```ruby
foos = Foo.joins(:bar).where(bars: { id: 1..10 })
bars = Bar.joins(:foos).merge(foos).records # error!
```
