### ISSUE TITLE
SOS - RAILS CAN NOT WORKING

### ISSUE THREAD

**Issue by ciscolive** [rails/rails#42556]
### Steps to reproduce

```
D:\Workflow\codes\mojo>**rake netdisco:to_oxidized** --trace
rake aborted!
NameError: undefined method `extend_object' for class `Singleton'
Did you mean?  extended
C:/Ruby27-x64/lib/ruby/2.7.0/singleton.rb:150:in `undef_method'
C:/Ruby27-x64/lib/ruby/2.7.0/singleton.rb:150:in `singleton class'
C:/Ruby27-x64/lib/ruby/2.7.0/singleton.rb:138:in `<module:Singleton>'
C:/Ruby27-x64/lib/ruby/2.7.0/singleton.rb:94:in `<main>'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_w
ith_bootsnap_lfi'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_boots
nap_lfi'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/deprecation.rb:3:in `<main>'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_w
ith_bootsnap_lfi'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_boots
nap_lfi'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/rails.rb:26:in `<main>'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_w
ith_bootsnap_lfi'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_boots
nap_lfi'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch.rb:27:in `<main>'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_w
ith_bootsnap_lfi'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_boots
nap_lfi'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/railtie.rb:3:in `<main>'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_w
ith_bootsnap_lfi'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_boots
nap_lfi'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.3.2/lib/rails.rb:18:in `<main>'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_w
ith_bootsnap_lfi'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_boots
nap_lfi'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
D:/Workflow/codes/mojo/config/application.rb:5:in `<top (required)>'
D:/Workflow/codes/mojo/Rakefile:6:in `require_relative'
D:/Workflow/codes/mojo/Rakefile:6:in `<top (required)>'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load_rakefile'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:703:in `raw_load_rakefile'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:104:in `block in load_rakefile'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:103:in `load_rakefile'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:82:in `block in run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
C:/Ruby27-x64/bin/rake:23:in `load'
C:/Ruby27-x64/bin/rake:23:in `<main>'
```

```ruby
namespace :xxxx do
  desc "auto sync device info from xxxx"
  task to_oxidized: :environment do
    require "sequel"

    DB = Sequel.connect("postgresql://11111/xxxx", user: "xxxxxx", password: "xxxxx")

    DB[:device].each do |h|
      # 丢弃 安全组 IPS 设备地址
      next if h[:model].match /fpr21/i

      # 预处理设备厂商系统型号
      vendor = h[:os].to_s.downcase.gsub!(/-/, "") || h[:os].to_s.downcase
      vendor = if (h[:model].match /Fpr4120K9/i)
                 "firelinuxos"
               elsif (h[:model].match /air/i)
                 "aireos"
               elsif (vendor =~ /cisco/i)
                 "ios"
               elsif (vendor =~ /alteon/)
                 "alteonos"
               elsif (vendor =~ /h3c/i)
                 "comware"
               elsif (vendor =~ /juniper/i)
                 "junos"
               else
                 vendor
               end
      # 预处理设备名称，删除不必要的 #
      hostname = h[:name].gsub(/\..*\z/, "") || h[:name]
      hostname.gsub!(/#/, "") if hostname

      # 预处理龙华工厂设备标识符
      location = h[:location]
      # 预处理设备登录账号密码
      #  预处理设备类型
      layer = if (vendor =~ /panos|firelinuxos/i)
                "防火墙"
              else
                (vendor =~ /alteon/i) ? "负载均衡" : "交换机"
              end

      # 检查主机名称是否为空
      hostname = h[:ip] if hostname.empty?

      # 本地数据比对，增量更新
      if Device.find_by(ip: h[:ip]).nil?
        p "已通过 Netdisco 自动新建备份对象 #{h[:ip]}"
        Device.create(hostname: hostname, ip: h[:ip], vendor: vendor, model: h[:model], username: username, password: password, location: h[:location], contact: h[:contact], layers: layer, serial: h[:serial], os: h[:os], os_ver: h[:os_ver])
      else
        p "已通过 Netdisco 自动同步备份对象 #{h[:ip]}"
        Device.where(ip: h[:ip]).update_all(hostname: hostname, ip: h[:ip], vendor: vendor, model: h[:model], username: username, password: password, location: h[:location], contact: h[:contact], layers: layer, serial: h[:serial], os: h[:os], os_ver: h[:os_ver])
      end
    end
  end
end
```

### Expected behavior

runing the tasks
### Actual behavior

raise error 
### System configuration
**Rails version**:
Rails 6.1.3.2

**Ruby version**:
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x64-mingw32]

**Comment by ciscolive** [comment]
D:\Workflow\codes\mojo>rake netdisco:to_oxidized
rake aborted!
NameError: undefined method `extend_object' for class `Singleton'
Did you mean?  extended
D:/Workflow/codes/mojo/config/application.rb:5:in `<top (required)>'
D:/Workflow/codes/mojo/Rakefile:6:in `require_relative'
D:/Workflow/codes/mojo/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by connordoner** [comment]
It would help to explain in more detail what behaviour you expect and to translate the comments in your code to English, as this will make the issue easier to identify.

**Comment by rafaelfranca** [comment]
This issue doesn't seems to be related to Rails. It is Ruby that is failing to execute this line https://github.com/ruby/ruby/blob/v2_7_3/lib/singleton.rb#L150 becase this method doesn't exist in the `Singleton` class. This method is defined in all modules though https://github.com/ruby/ruby/blob/d92f09a5eea009fa28cd046e9d0eb698e3d94c5c/eval.c#L2107, so I think some gem or something in your application is undefining it.

If you can reproduce this issue with a new Rails application let us know and we can reopen it.
