### ISSUE TITLE
NoMethodError: undefined method `action_dispatch' 

### ISSUE THREAD

**Issue by ethaning** [rails/rails#42567]
Hi,

We are currently experiencing this bug when running our rails app in a docker container. All web requests and all ```rails``` commands result in this error.

We are not experiencing this issue across all devices running the app. It could potentially be an issue with docker / docker-compose.

Is anyone else experiencing this bug? If so, any advice on how to solve this issue?

Thanks

@rosariogueli

```root@dc92777a2cac:/home/app/web# rails -T --trace
rails aborted!
NoMethodError: undefined method `action_dispatch' for #<Rails::Railtie::Configuration:0x00005568d7923430>
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/railties-6.0.3.7/lib/rails/railtie/configuration.rb:96:in `method_missing'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activerecord-6.0.3.7/lib/active_record/railtie.rb:21:in `<class:Railtie>'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activerecord-6.0.3.7/lib/active_record/railtie.rb:15:in `<module:ActiveRecord>'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activerecord-6.0.3.7/lib/active_record/railtie.rb:13:in `<main>'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
/home/app/web/config/application.rb:7:in `<main>'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
/home/app/web/rakefile:4:in `<main>'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:318:in `block in load'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:318:in `load'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/rake-12.3.3/lib/rake/application.rb:703:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/rake-12.3.3/lib/rake/application.rb:104:in `block in load_rakefile'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/rake-12.3.3/lib/rake/application.rb:103:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/railties-6.0.3.7/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/railties-6.0.3.7/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/railties-6.0.3.7/lib/rails/command.rb:48:in `invoke'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/railties-6.0.3.7/lib/rails/commands.rb:18:in `<main>'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.3@paperless/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
/home/app/web/bin/rails:4:in `<main>'
```

### Expected behavior

The rails app loads and works normally.

### Actual behavior

The app is unable to complete initialization and crashes.

### System configuration
**Rails version**:
6.0.3.7

**Ruby version**:
2.6.3

**Comment by ghiculescu** [comment]
We have not seen the same issue on our 6.0.3.7 app. Can you check if it happens without docker?

**Comment by ethaning** [comment]
Hi, I have just set up a new rails app with the same rails version and ruby version outside of docker. It all works fine. 

The same setup also works fine on my computer within docker. @rosariogueli is having issues on his macbook though. 

@rosariogueli - are you able to create the app outside of docker?

**Comment by rosariogueli** [comment]
@ethaning I've finally de-dockerised the project and it works well (other than some CORS issues which can be resolved, it's all good). It seems that when ran in docker, sidekik is exiting with the above error.

**Comment by p8** [comment]
Closing as this seems to be a Docker issue.
