### ISSUE TITLE
ActiveRecord `update` forcing type cast of untouched attributes

### ISSUE THREAD

**Issue by bboe** [rails/rails#42738]
Perhaps the following is the expected behavior, however, it seems a little inconsistent because the type cast is not forced when obtaining an instance.

### Steps to reproduce

```ruby
require "active_record"

ActiveRecord::Base.establish_connection(
  adapter: "mysql2",
  database: "test",
)

ActiveRecord::Schema.define do
  create_table :examples, force: true do |t|
    t.string :value
    t.timestamp :unused
  end
end

ActiveRecord::Base.connection.execute("insert into examples values (1, 'value', NOW())")

class CustomDateTimeType < ActiveModel::Type::DateTime
  def cast(value)
    raise Exception, "Should this be called?"
  end
end

ActiveRecord::Type.register(:custom_datetime, CustomDateTimeType)

class Example < ActiveRecord::Base
  attribute :unused, :custom_datetime
end

example = Example.first

# This works fine
puts example.value

# This works fine
example.update_columns(value: "working value")

# The following fails because it forces a cast of `unused`
# Should that be the case even though I haven't explictly asked for that attribute?
example.update(value: "new value")
```

### Expected behavior
I would think that `forgetting_assignment` would need only touch the attributes that are dirty, not all attributes thus not forcing a type cast of the `unused` attribute.

### Actual behavior
`forgetting_assignment` appears to reset all attributes, thus triggering `cast` to be called on an attribute resulting in the following exception (note that the rollback fails for a similar reason):

```
Traceback (most recent call last):
	43: from tmp.rb:40:in `<main>'
	42: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/persistence.rb:626:in `update'
	41: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
	40: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
	39: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:308:in `within_new_transaction'
	38: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	37: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	36: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	35: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	34: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	33: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:310:in `block in within_new_transaction'
	32: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
	31: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
	30: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/persistence.rb:628:in `block in update'
	29: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/suppressor.rb:44:in `save'
	28: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/transactions.rb:298:in `save'
	27: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
	26: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:318:in `transaction'
	25: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
	24: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/transactions.rb:298:in `block in save'
	23: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/validations.rb:47:in `save'
	22: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/persistence.rb:474:in `save'
	21: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/timestamp.rb:126:in `create_or_update'
	20: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/callbacks.rb:457:in `create_or_update'
	19: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:824:in `_run_save_callbacks'
	18: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
	17: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/callbacks.rb:457:in `block in create_or_update'
	16: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/persistence.rb:900:in `create_or_update'
	15: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/timestamp.rb:121:in `_update_record'
	14: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/callbacks.rb:465:in `_update_record'
	13: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:824:in `_run_update_callbacks'
	12: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
	11: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/callbacks.rb:465:in `block in _update_record'
	10: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/attribute_methods/dirty.rb:196:in `_update_record'
	 9: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/dirty.rb:149:in `changes_applied'
	 8: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/dirty.rb:257:in `forget_attribute_assignments'
	 7: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/attribute_set.rb:90:in `map'
	 6: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/attribute_set.rb:90:in `transform_values'
	 5: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/attribute.rb:68:in `forgetting_assignment'
	 4: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/attribute.rb:56:in `value_for_database'
	 3: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/attribute.rb:43:in `value'
	 2: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/attribute.rb:164:in `type_cast'
	 1: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/type/value.rb:32:in `deserialize'
tmp.rb:21:in `cast': Should this be called? (Exception)
	29: from tmp.rb:40:in `<main>'
	28: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/persistence.rb:626:in `update'
	27: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
	26: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
	25: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:308:in `within_new_transaction'
	24: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	23: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	22: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	21: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	20: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	19: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:313:in `block in within_new_transaction'
	18: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:315:in `rescue in block in within_new_transaction'
	17: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:300:in `rollback_transaction'
	16: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	15: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	14: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	13: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	12: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	11: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:303:in `block in rollback_transaction'
	10: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:125:in `rollback_records'
	 9: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/transactions.rb:334:in `rolledback!'
	 8: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/transactions.rb:407:in `restore_transaction_record_state'
	 7: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/attribute_set.rb:90:in `map'
	 6: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/attribute_set.rb:90:in `transform_values'
	 5: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3.2/lib/active_record/transactions.rb:408:in `block in restore_transaction_record_state'
	 4: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/attribute_set/builder.rb:43:in `fetch_value'
	 3: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/attribute.rb:43:in `value'
	 2: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/attribute.rb:164:in `type_cast'
	 1: from /Users/bboe/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-6.1.3.2/lib/active_model/type/value.rb:32:in `deserialize'
tmp.rb:21:in `cast': Should this be called? (Exception)
```

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.6.3

---

Thanks!

**Comment by intrip** [comment]
@bboe 
I think the current behaviour makes sense: imagine the DB runs triggers or some other logic which indirectly updates columns not explicitly given in input when calling `update`, in such situation the model would be outdated.

**Comment by bboe** [comment]
@intrip as far as I can tell, the values are not actually refetched from the db though. They just go through the cast process using whatever value exists in memory. So I don't think that explanation justifies why this is the existing behavior.

**Comment by intrip** [comment]
@bboe you're right I've overlooked at it. 
I don't know the reasons behind the existing behaviour but your proposal looks reasonable to me. Are you willing to make a PR?

**Comment by bboe** [comment]
> Are you willing to make a PR?

I should be able to take a stab at it in a few days. My thought process was to allow the attributes to "forget" to optionally be passed into `forgetting_assignment`, or perhaps look at what's dirty when running `forgetting_assignment`.

**Comment by intrip** [comment]
@bboe thanks!
I'd prefer the latter approach, what about passing a flag to `forgetting_assigment` which allows to select only the `changed?` attributes?

**Comment by bboe** [comment]
Sounds like a good approach to try. Thanks for the suggestion.
