### ISSUE TITLE
ActiveRecord 6.1 raises `AM::MissingAttributeError` when used with `eager_load` and `select`

### ISSUE THREAD

**Issue by sinsoku** [rails/rails#42753]
I noticed a difference in behavior between ActiveRecord 6.0 and 6.1, is this the intended change?

This has changed with 46393182158e5159be64349684be1716944ecc4e.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  if ENV["RAILS_VERSION"]
    gem "activerecord", ENV["RAILS_VERSION"]
  else
    gem "rails", path: "."
  end
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table(:posts, force: true)

  create_table :comments, force: true do |t|
    t.integer :x_post_id
  end
end

class Post < ActiveRecord::Base
end

class Comment < ActiveRecord::Base
  belongs_to :post, foreign_key: :x_post_id
end

class BugTest < Minitest::Test
  def test_ar
    post = Post.create!
    Comment.create!(x_post_id: post.id)

    comments = Comment.eager_load(:post).select(:id)
    assert_equal post.id, comments.first.x_post_id
    # 6.1.4
    #=> ActiveModel::MissingAttributeError: missing attribute: x_post_id
  end
end
```

#### v6.0.4

```
$ RAILS_VERSION=6.0.4 ruby steps_to_reproduce.rb
# Running:

D, [2021-07-11T23:13:04.603297 #34274] DEBUG -- :    (0.0ms)  begin transaction
D, [2021-07-11T23:13:04.603447 #34274] DEBUG -- :   Post Create (0.1ms)  INSERT INTO "posts" DEFAULT VALUES
D, [2021-07-11T23:13:04.603689 #34274] DEBUG -- :    (0.0ms)  commit transaction
D, [2021-07-11T23:13:04.605885 #34274] DEBUG -- :    (0.0ms)  begin transaction
D, [2021-07-11T23:13:04.606072 #34274] DEBUG -- :   Comment Create (0.1ms)  INSERT INTO "comments" ("x_post_id") VALUES (?)  [["x_post_id", 1]]
D, [2021-07-11T23:13:04.606195 #34274] DEBUG -- :    (0.0ms)  commit transaction
D, [2021-07-11T23:13:04.612667 #34274] DEBUG -- :   SQL (0.1ms)  SELECT "comments"."id", "comments"."id" AS t0_r0, "comments"."x_post_id" AS t0_r1, "posts"."id" AS t1_r0 FROM "comments" LEFT OUTER JOIN "posts" ON "posts"."id" = "comments"."x_post_id" ORDER BY "comments"."id" ASC LIMIT ?  [["LIMIT", 1]]
.

Finished in 0.014134s, 70.7514 runs/s, 70.7514 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

#### v6.1.4

```
$ RAILS_VERSION=6.1.4 ruby steps_to_reproduce.rb
# Running:

D, [2021-07-11T23:21:39.887912 #34367] DEBUG -- :   TRANSACTION (0.1ms)  begin transaction
D, [2021-07-11T23:21:39.888111 #34367] DEBUG -- :   Post Create (0.1ms)  INSERT INTO "posts" DEFAULT VALUES
D, [2021-07-11T23:21:39.888412 #34367] DEBUG -- :   TRANSACTION (0.1ms)  commit transaction
D, [2021-07-11T23:21:39.891234 #34367] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-07-11T23:21:39.891462 #34367] DEBUG -- :   Comment Create (0.1ms)  INSERT INTO "comments" ("x_post_id") VALUES (?)  [["x_post_id", 1]]
D, [2021-07-11T23:21:39.891675 #34367] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-07-11T23:21:39.898994 #34367] DEBUG -- :   SQL (0.2ms)  SELECT "comments"."id", "comments"."id" AS t0_r0, "posts"."id" AS t1_r0 FROM "comments" LEFT OUTER JOIN "posts" ON "posts"."id" = "comments"."x_post_id" ORDER BY "comments"."id" ASC LIMIT ?  [["LIMIT", 1]]
E

Finished in 0.017107s, 58.4556 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_ar:
ActiveModel::MissingAttributeError: missing attribute: x_post_id
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activemodel-6.1.4/lib/active_model/attribute.rb:222:in `value'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activemodel-6.1.4/lib/active_model/attribute_set/builder.rb:55:in `block in fetch_value'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activemodel-6.1.4/lib/active_model/attribute_set/builder.rb:46:in `fetch'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activemodel-6.1.4/lib/active_model/attribute_set/builder.rb:46:in `fetch_value'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/attribute_methods/read.rb:36:in `_read_attribute'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/associations/belongs_to_association.rb:132:in `stale_state'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/associations/association.rb:79:in `loaded!'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/associations/association.rb:96:in `target='
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/associations/join_dependency.rb:284:in `construct_model'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/associations/join_dependency.rb:264:in `block in construct'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/associations/join_dependency.rb:241:in `each'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/associations/join_dependency.rb:241:in `construct'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/associations/join_dependency.rb:142:in `block (2 levels) in instantiate'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/result.rb:62:in `block in each'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/result.rb:62:in `each'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/result.rb:62:in `each'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/associations/join_dependency.rb:139:in `block in instantiate'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/associations/join_dependency.rb:138:in `instantiate'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/relation.rb:839:in `block (2 levels) in exec_queries'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/relation/finder_methods.rb:421:in `apply_join_dependency'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/relation.rb:833:in `block in exec_queries'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/relation.rb:861:in `skip_query_cache_if_necessary'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/relation.rb:828:in `exec_queries'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/relation.rb:631:in `load'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/relation.rb:249:in `records'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/relation.rb:244:in `to_ary'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/relation/finder_methods.rb:553:in `find_nth_with_limit'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/relation/finder_methods.rb:538:in `find_nth'
    /Users/sinsoku/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4/lib/active_record/relation/finder_methods.rb:122:in `first'
    steps_to_reproduce.rb:48:in `test_pr'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration
**Rails version**: v6.0.4, v6.1.4

**Ruby version**: v3.0.1

**Comment by csrutil** [comment]
Hey @sinsoku, the difference between ActiveRecord 6.0 and 6.1 are

```sql
-- 6.0
SELECT "comments"."id",
       "comments"."id" AS t0_r0,
       "comments"."x_post_id" AS t0_r1,
       "posts"."id" AS t1_r0
FROM "comments"
LEFT OUTER JOIN "posts" ON "posts"."id" = "comments"."x_post_id"
```

```sql
-- 6.1.4
SELECT "comments"."id",
       "comments"."id" AS t0_r0,
       "posts"."id" AS t1_r0
FROM "comments"
LEFT OUTER JOIN "posts" ON "posts"."id" = "comments"."x_post_id"
```

Those two SQLs are generated by 

```ruby
comments = Comment.eager_load(:post).select(:id)
```

The issue is that 6.1.4 did not fetch the `x_post_id` foreign key, I'll investigate further

**Comment by kamipo** [comment]
Same issue with #40874.

The reason that MissingAttributeError is not raised on `eager_load` before Rails 6.0 unlike `includes`/`preload` is that `eager_load` had ignored `select` values.

Do you expect `eager_load` to ignore the `select` values even though it was specified?

**Comment by sinsoku** [comment]
I expected a foreign key to be added to `select` values in addition to the value I specified to use the association to work.
