### ISSUE TITLE
No way to specify a password for a socket Postgres DATABASE_URL

### ISSUE THREAD

**Issue by mike-burns** [rails/rails#42797]
### Background

[Postgres's connection info URI](https://www.postgresql.org/docs/current/libpq-connect.html#id-1.7.3.8.3.6) is not a valid [RFC 2396](https://datatracker.ietf.org/doc/html/rfc2396) implementation.

Postgres:

> `postgresql://[userspec@][hostspec][/dbname][?paramspec]`
>
> and hostspec is:
>
> `[host][:port][,...]`

RFC 2396:

```
server        = [ [ userinfo "@" ] hostport ]
hostport      = host [ ":" port ]
```

PG has an optional host; if the host is not specified, it uses the socket. That means this is a valid PG connection URI:

```
postgres://user:passwd@/theapp_production
```

### Steps to reproduce

However, `URI::Parser` uses the RFC 2396 parser on it:

```ruby
ActiveRecord::DatabaseConfigurations::UrlConfig.new(:production, :production, 'postgres://user:passwd@/theapp_production', {})
```

```
/home/mike/.rubies/ruby-3.0.2/lib/ruby/3.0.0/uri/generic.rb:207:in `initialize': the scheme postgres does not accept registry part: user:passwd@ (or bad hostname?) (URI::InvalidURIError)
```

However, PG also allows for query params. This allows us to create a valid RFC 2396 URI:

```
postgres:///?user=user&password=passwd&dbname=theapp_production
```

This gives a different issue: the `password` is overridden with `uri.password`, which is nil:

```ruby
ActiveRecord::DatabaseConfigurations::UrlConfig.new(:production, :production, 'postgres:///?user=user&password=passwd&dbname=theapp_production', {}).configuration_hash
```

```
=> {:user=>"user", :dbname=>"theapp_production", :adapter=>"postgresql"}
```

### Expected behavior

```
> ActiveRecord::DatabaseConfigurations::UrlConfig.new(:production, :production, 'postgres://user:passwd@/theapp_production', {}).configuration_hash
=> {:user=>"user", :dbname=>"theapp_production", :adapter=>"postgresql", :password=>"passwd"}
> ActiveRecord::DatabaseConfigurations::UrlConfig.new(:production, :production, 'postgres:///?user=user&password=passwd&dbname=theapp_production', {}).configuration_hash
=> {:user=>"user", :dbname=>"theapp_production", :adapter=>"postgresql", :password=>"passwd"}
```

### Actual behavior

```
> ActiveRecord::DatabaseConfigurations::UrlConfig.new(:production, :production, 'postgres://user:passwd@/theapp_production', {}).configuration_hash
=> /home/mike/.rubies/ruby-3.0.2/lib/ruby/3.0.0/uri/generic.rb:207:in `initialize': the scheme postgres does not accept registry part: user:passwd@ (or bad hostname?) (URI::InvalidURIError)
> ActiveRecord::DatabaseConfigurations::UrlConfig.new(:production, :production, 'postgres:///?user=user&password=passwd&dbname=theapp_production', {}).configuration_hash
=> {:user=>"user", :dbname=>"theapp_production", :adapter=>"postgresql"}
```

### Extraneous

This [came up as a StackOverflow question](https://stackoverflow.com/questions/27037990/connecting-to-postgres-via-database-url-and-unix-socket-in-rails) six years ago.

The query params would be a fine workaround; what do you think of reversing the merge in ConnectionUrlResolver:

https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/activerecord/lib/active_record/database_configurations/connection_url_resolver.rb#L70-L77

(Note that `port` has the same issue.)

### System configuration
**Rails version**: 6.1.4

**Ruby version**: 3.0.2

**Comment by krlsdu** [comment]
Need attention in credentials to not show in output when debug application.

**Comment by Debulknor** [comment]
##``

**Comment by mortbauer** [comment]
@mike-burns thanks for this research and the write up, I'm having the same issue.

**Comment by dfmoreto** [comment]
I was looking for a Good First Issue. I'll try it.

**Comment by kamipo** [comment]
Fixed by #42840.
