### ISSUE TITLE
Problem with rails webpacker:install,Error-Message: NameError: uninitialized constant ActionDispatch::DebugExceptions

### ISSUE THREAD

**Issue by songjiz** [rails/rails#42801]
### Steps to reproduce

```bash
rails new demo --master --skip-sprockets
```

### Actual behavior

```
     create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in demo/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/spring
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_6_1.rb
      create  config/initializers/permissions_policy.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/assets.rb
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_6_1.rb
         run  bundle install
Fetching https://github.com/rails/rails.git
Fetching https://github.com/rails/web-console.git
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Using rake 13.0.6
Using concurrent-ruby 1.1.9
Using erubi 1.10.0
Using racc 1.5.2
Using builder 3.2.4
Using zeitwerk 2.4.2
Using nio4r 2.5.7
Using websocket-extensions 0.1.5
Using marcel 1.0.1
Using mini_mime 1.1.0
Using crass 1.0.6
Using public_suffix 4.0.6
Using minitest 5.14.4
Using msgpack 1.4.2
Using rack 2.2.3
Using bundler 2.2.22
Using childprocess 3.0.0
Using ffi 1.15.3
Using regexp_parser 2.1.1
Using byebug 11.1.3
Using thor 1.1.0
Using rubyzip 2.3.2
Using semantic_range 3.0.0
Using spring 2.1.1
Using sqlite3 1.4.2
Using turbolinks-source 5.2.0
Using i18n 1.8.10
Using tzinfo 2.0.4
Using nokogiri 1.11.7 (x86_64-darwin)
Using puma 5.3.2
Using method_source 1.0.0
Using mail 2.7.1
Using addressable 2.8.0
Using rack-test 1.1.0
Using bootsnap 1.7.5
Using rb-fsevent 0.11.0
Using bindex 0.8.1
Using rack-proxy 0.7.0
Using rack-mini-profiler 2.3.2
Using sprockets 4.0.2
Using selenium-webdriver 3.142.7
Using activesupport 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using websocket-driver 0.7.5
Using turbolinks 5.2.1
Using xpath 3.2.0
Using loofah 2.10.0
Using rb-inotify 0.10.1
Using webdrivers 4.6.0
Using listen 3.5.1
Using rails-html-sanitizer 1.3.0
Using capybara 3.35.3
Using rails-dom-testing 2.0.3
Using globalid 0.4.2
Using actionview 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using activemodel 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using actionpack 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using activejob 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using jbuilder 2.11.2
Using actioncable 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using activerecord 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using railties 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using sprockets-rails 3.2.2
Using activestorage 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using actionmailer 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using actionmailbox 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using actiontext 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using rails 7.0.0.alpha from https://github.com/rails/rails.git (at main@359efef)
Using webpacker 5.4.0
Using web-console 4.1.0 from https://github.com/rails/web-console.git (at master@91eed5a)
Bundle complete! 16 Gemfile dependencies, 69 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  webpacker:install
rails aborted!
NameError: uninitialized constant ActionDispatch::DebugExceptions
demo/config/environment.rb:5:in `<main>
demo/bin/rails:5:in `<top (required)>
demo/bin/spring:10:in `require'
demo/bin/spring:10:in `block in <top (required)
demo/bin/spring:7:in `<top (required)>
Tasks: TOP =>app:template =>environment
(See full trace by running task with --trace)
```

Run webpacker:install manually:

```
rails webpacker:install --trace
```

Got:

```
** Invoke webpacker:install (first_time)
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
** Invoke webpacker:check_yarn (first_time)
** Execute webpacker:check_yarn
** Execute webpacker:install
rails aborted!
NameError: uninitialized constant ActionDispatch::DebugExceptions
demo/config/environment.rb:5:in `<main>'
demo/bin/rails:5:in `<top (required)>'
demo/bin/spring:10:in `require'
demo/bin/spring:10:in `block in <top (required)>'
demo/bin/spring:7:in `<top (required)>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
```

Retry with:

```
rake webpacker:install --trace
```

Got:

```
.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/actionpack/lib/action_dispatch/railtie.rb:51:in `block (2 levels) in <class:Railtie>': uninitialized constant ActionDispatch::DebugExceptions (NameError)
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/activesupport/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/activesupport/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/activesupport/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/activesupport/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/activesupport/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/activesupport/lib/active_support/lazy_load_hooks.rb:51:in `each'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/activesupport/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/actionpack/lib/action_dispatch/http/request.rb:444:in `<main>'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:3:in `<main>'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/web-console-91eed5a56ca2/lib/web_console/railtie.rb:13:in `block in <class:Railtie>'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/railties/lib/rails/initializable.rb:32:in `instance_exec'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/railties/lib/rails/initializable.rb:32:in `run'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
  from .asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
  from .asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  from .asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
  from .asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
  from .asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each'
  from .asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `call'
  from .asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
  from .asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
  from .asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/railties/lib/rails/initializable.rb:60:in `run_initializers'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-359efef64b30/railties/lib/rails/application.rb:391:in `initialize!'
  from Desktop/demo/config/environment.rb:5:in `<main>'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:106:in `preload'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
  from .asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
  from <internal:.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  from <internal:.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  from -e:1:in `<main>'
```

### System configuration
**Rails version**: 7.0.0.alpha
**Ruby version**: 3.0.2

**Comment by p8** [comment]
I've made a PR to web-console: https://github.com/rails/web-console/pull/310
Changing the web-console version in the Gemfile to:
```
  gem 'web-console', github: 'p8/web-console', branch: 'fix-debug-exceptions-loading'
```
Fixes running `rake webpacker:install --trace` for me.

**Comment by p8** [comment]
This bug doesn't occur when including `sprockets-rails` because I think the following code prematurely loads all of `ActionDispatch`, inlcuding `ActionDispatch::DebugExceptions`. We probably need an `on_load` hook for `ActionDispatch::Routing`.
https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L223-L233

**Comment by mbayucot** [comment]
Hi @p8. Are you working on this? If not, can i pick up this issue?

**Comment by p8** [comment]
Hi @mbayucot, I think my PR to web-console fixes this issue.

**Comment by mbayucot** [comment]
Hi @p8. Sorry, i didn't mean to ignore you're PR. I was referring to this issue
```

We probably need an on_load hook for ActionDispatch::Routing.
https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L223-L233

```

**Comment by p8** [comment]
@mbayucot Sure pick it up if you want 🙂

**Comment by mbayucot** [comment]
@p8 thank you 🙇

**Comment by songjiz** [comment]
@p8 Thank you 👍

**Comment by eugeneius** [comment]
This problem was introduced in https://github.com/rails/rails/pull/42592, by referencing `ActionDispatch::DebugExceptions` inside an `action_dispatch_request` load hook, when DebugExceptions itself has a dependency on `ActionDispatch::Request`:

https://github.com/rails/rails/blob/4a906cbbbc68f41ab23d2510954336db63451acc/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L3

 I think the right way to solve the problem is to break that circular dependency.
