### ISSUE TITLE
rails production 500 error

### ISSUE THREAD

**Issue by shiratsu** [rails/rails#43022]
### Steps to reproduce

it works fine on development.
but it doesn't work on prodiction environment

# Your reproduction script goes here

i run this command
```
[ec2-user@ip-xxxxxxxxxxx concier_tech]$ bundle exec rails s -e production
=> Booting Puma
=> Rails 6.1.3.2 application starting in production
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.4.0 (ruby 2.7.2-p137) ("Super Flight")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 4913
* Listening on http://0.0.0.0:3000
* Listening on unix:///var/www/concier_tech/tmp/sockets/puma.sock
Use Ctrl-C to stop
^C[ec2-user@ip-xxxxxxxxxxx concier_tech]$ bundle exec rails s -e production
=> Booting Puma
=> Rails 6.1.3.2 application starting in production
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.4.0 (ruby 2.7.2-p137) ("Super Flight")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 7720
* Listening on http://0.0.0.0:3000
* Listening on unix:///var/www/concier_tech/tmp/sockets/puma.sock
Use Ctrl-C to stop
```

### Expected behavior

show top page properly

### Actual behavior
it produced the following error
```
I, [2021-08-16T03:56:42.640604 #7720]  INFO -- : Processing by RootController#show as HTML
D, [2021-08-16T03:56:42.800604 #7720] DEBUG -- :   Rendering layout layouts/biz_lp_application.html.erb
D, [2021-08-16T03:56:42.800757 #7720] DEBUG -- :   Rendering root/show.html.erb within layouts/biz_lp_application
I, [2021-08-16T03:56:42.809632 #7720]  INFO -- :   Rendered root/show.html.erb within layouts/biz_lp_application (Duration: 8.8ms | Allocations: 2300)
I, [2021-08-16T03:56:42.810582 #7720]  INFO -- :   Rendered layout layouts/biz_lp_application.html.erb (Duration: 9.8ms | Allocations: 2348)
I, [2021-08-16T03:56:42.811366 #7720]  INFO -- : Rendering 500 with exception: wrong number of arguments (given 4, expec
I, [2021-08-16T03:56:42.811767 #7720]  INFO -- : /var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/url_for.rb:170:in `url_for'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route_set.rb:270:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route_set.rb:213:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route_set.rb:326:in `block in define_url_helper'
/var/www/concier_tech/app/views/root/show.html.erb:49:in `_app_views_root_show_html_erb___710287118399561835_160620'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/base.rb:247:in `public_send'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/base.rb:247:in `_run'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/template.rb:154:in `block in render'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:205:in `instrument'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/template.rb:345:in `instrument_render_template'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/template.rb:152:in `render'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/template_renderer.rb:11:in `render'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/rendering.rb:117:in `block in _render_template'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/base.rb:273:in `in_rendering_context'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/rendering.rb:116:in `_render_template'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/streaming.rb:218:in `_render_template'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/rendering.rb:103:in `render_to_body'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/abstract_controller/rendering.rb:25:in `render'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/rendering.rb:36:in `render'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/core_ext/benchmark.rb:14:in `ms'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/mongoid-7.3.2/lib/mongoid/railties/controller_runtime.rb:28:in `cleanup_view_runtime'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/instrumentation.rb:45:in `render'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/remotipart-1.4.4/lib/remotipart/render_overrides.rb:23:in `render'
/var/www/concier_tech/app/controllers/root_controller.rb:23:in `biz_lp'
/var/www/concier_tech/app/controllers/root_controller.rb:12:in `show'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/abstract_controller/base.rb:228:in `process_action'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actiontext-6.1.3.2/lib/action_text/rendering.rb:20:in `with_renderer'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actiontext-6.1.3.2/lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/active_decorator-1.4.0/lib/active_decorator/view_context.rb:37:in `block (3 levels) in <module:Filter>'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/active_decorator-1.4.0/lib/active_decorator/view_context.rb:25:in `run_with'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/active_decorator-1.4.0/lib/active_decorator/view_context.rb:36:in `block (2 levels) in <module:Filter>'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:137:in `run_callbacks'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/mongoid-7.3.2/lib/mongoid/railties/controller_runtime.rb:22:in `process_action'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/abstract_controller/base.rb:165:in `process'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionview-6.1.3.2/lib/action_view/rendering.rb:39:in `process'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal.rb:190:in `dispatch'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_controller/metal.rb:254:in `dispatch'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/journey/router.rb:32:in `each'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/journey/router.rb:32:in `serve'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/route_set.rb:842:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/turnout-2.5.0/lib/rack/turnout.rb:25:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/remotipart-1.4.4/lib/remotipart/middleware.rb:32:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/exception_notification-4.4.3/lib/exception_notification/rack.rb:49:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/cookies.rb:689:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:37:in `call_app'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:28:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/static.rb:24:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/engine.rb:539:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/puma-5.4.0/lib/puma/configuration.rb:249:in `call'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/puma-5.4.0/lib/puma/request.rb:77:in `block in handle_request'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/puma-5.4.0/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/puma-5.4.0/lib/puma/request.rb:76:in `handle_request'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/puma-5.4.0/lib/puma/server.rb:440:in `process_client'
/var/www/concier_tech/vendor/bundle/ruby/2.7.0/gems/puma-5.4.0/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
D, [2021-08-16T03:56:43.176134 #7720] DEBUG -- :   Rendering errors/error_500.html.erb
D, [2021-08-16T03:56:43.178426 #7720] DEBUG -- :   Rendered shared/_common_analytics.html.erb (Duration: 0.3ms | Allocations: 173)
D, [2021-08-16T03:56:43.178550 #7720] DEBUG -- :   Rendered shared/_personal_analytics.html.erb (Duration: 1.1ms | Allocations: 571)
I, [2021-08-16T03:56:43.178628 #7720]  INFO -- :   Rendered errors/error_500.html.erb (Duration: 2.3ms | Allocations: 1079)
I, [2021-08-16T03:56:43.178944 #7720]  INFO -- : Completed 500 Internal Server Error in 538ms (Views: 3.3ms | ActiveRecord: 10.1ms | MongoDB: 0.0ms | Allocations: 16123)
```

### System configuration
**6.1.3.2**:

**2.7.2**:

**Comment by shiratsu** [comment]
by the way it works fine on development mode

**Comment by shiratsu** [comment]
i could resolve by my self by copy dev setting to prod.
