### ISSUE TITLE
`ActionController::Base#to_json` fails with `SystemStackOverflow`.

### ISSUE THREAD

**Issue by ioquatix** [rails/rails#43040]
```
samuel@Fukurou ~> irb
irb(main):001:0> require 'active_support'
=> true
irb(main):002:0> require 'action_controller'
=> true
irb(main):003:0> ActionController::Base
=> ActionController::Base
irb(main):004:0> ActionController::Base.to_json
/Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:175:in `initialize_dup': stack level too deep (SystemStackError)
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:175:in `dup'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:174:in `each'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:174:in `as_json'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:58:in `as_json'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:174:in `each'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:174:in `as_json'
	 ... 9880 levels...
	from /Users/samuel/.rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from /Users/samuel/.rubies/ruby-3.0.2/bin/irb:23:in `load'
	from /Users/samuel/.rubies/ruby-3.0.2/bin/irb:23:in `<main>'
```

I believe this is a bug. By the way, this does work:

```
irb(main):005:0> JSON::generate(ActionController::Base)
=> "\"ActionController::Base\""
```

Perhaps a more trivial reproduction is this:

```
irb(main):006:0> x = {}; x[:self] = x
=> {:self=>{...}}
irb(main):007:0> x.to_json
/Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:175:in `initialize_dup': stack level too deep (SystemStackError)
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:175:in `dup'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:174:in `each'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:174:in `as_json'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:174:in `each'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:174:in `as_json'
	from /Users/samuel/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
	 ... 9579 levels...
	from /Users/samuel/.rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from /Users/samuel/.rubies/ruby-3.0.2/bin/irb:23:in `load'
	from /Users/samuel/.rubies/ruby-3.0.2/bin/irb:23:in `<main>'
```

Not sure what is fundamentally different about the two operations, but `JSON::generate` does have a limit parameter which defaults to 100 to prevent recursion and prevents the latter issue.

**Comment by ghiculescu** [comment]
> but `JSON::generate` does have a limit parameter which defaults to 100 to prevent recursion and prevents the latter issue.

The param is `max_nesting` https://github.com/flori/json/blob/127f0e286c284812c9cbfe0fe5849d949735f5ef/lib/json/pure/parser.rb#L59

Maybe https://github.com/rails/rails/blob/main/activesupport/lib/active_support/core_ext/object/json.rb should support the same param 🤔

**Comment by ioquatix** [comment]
I think that `JSON.generate` correctly handles recursion but `ActionController::Base` might have a circular reference to itself which causes `#to_json` to blow up, but it's just a guess.

**Comment by ryoheiudagawa1995** [comment]
Im wiling to give this a try. Can I be assigned?

**Comment by marcelolx** [comment]
@ryoheiudagawa1995 No need to be assigned, feel free to work on this and open a PR 👍

**Comment by ioquatix** [comment]
```
> gem install rails
Successfully installed rails-6.1.4.1
Parsing documentation for rails-6.1.4.1
Installing ri documentation for rails-6.1.4.1
Done installing documentation for rails after 0 seconds
1 gem installed

> irb
irb(main):001:0> require 'active_support'
=> true
irb(main):002:0> require 'action_controller'
=> true
irb(main):003:0> ActionController::Base.to_json
Traceback (most recent call last):
	9892: from /home/samuel/.gem/ruby/2.7.4/bin/irb:23:in `<main>'
	9891: from /home/samuel/.gem/ruby/2.7.4/bin/irb:23:in `load'
	9890: from /home/samuel/.gem/ruby/2.7.4/gems/irb-1.3.7/exe/irb:11:in `<top (required)>'
	 ... 9880 levels...
	   4: from /home/samuel/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/json.rb:174:in `as_json'
	   3: from /home/samuel/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/json.rb:174:in `each'
	   2: from /home/samuel/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
	   1: from /home/samuel/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/json.rb:175:in `dup'
/home/samuel/.gem/ruby/2.7.4/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/json.rb:175:in `initialize_dup': stack level too deep (SystemStackError)
```

**Comment by rafaelfranca** [comment]
This is fined in the main branch by https://github.com/rails/rails/pull/42532. I didn't backported yet because I didn't want to possibly change behavior between bug release versions. I could backport though.

**Comment by ioquatix** [comment]
Thanks!
