### ISSUE TITLE
Inefficient fresh_when Queries on Collection

### ISSUE THREAD

**Issue by tleish** [rails/rails#43125]
When using eTag methods `#fresh_when` or `#stale?` on an ActiveRecord collection, you get 2 slightly different queries every time . 

```sql
SELECT MAX("posts"."updated_at") FROM "posts"
SELECT COUNT(*) AS "size", MAX("posts"."updated_at") AS timestamp FROM "posts"
```
It seems you could get the updated_at form the 2nd query and do away with the first.

### Steps to reproduce

Use `#fresh_when` or `#stale?` on an ActiveRecord collection

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "action_controller/railtie"
require "active_record/railtie"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.timestamps
  end
end


class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end


class Post < ActiveRecord::Base
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
  
  def index
    post = Post.all
    return unless stale? post
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def setup
    Post.create!
    @log_subscriber = Class.new(ActiveSupport::LogSubscriber) do
      def self.queries
        @@queries ||= []
      end

      def sql(event)
        self.class.queries << event.payload[:sql]
      end
    end
    @log_subscriber.attach_to :active_record
  end

  def test_fresh_when_with_cache_versioning_queries_table_once
    get "/"
    assert_equal 1, @log_subscriber.queries.grep(/SELECT .* "posts"/).uniq.length
  end

  private
  def app
    Rails.application
  end
end

```

### Expected behavior
When using `#stale?` or `#fresh_when` with an ActiveRecord collection I expect a single query to calculate the eTag for the collection.

```sql
SELECT COUNT(*) AS "size", MAX("posts"."updated_at") AS timestamp FROM "posts"
```
or at least use the same query so Rails caches it
```sql
SELECT COUNT(*) AS "size", MAX("posts"."updated_at") AS timestamp FROM "posts"
[CACHED] SELECT COUNT(*) AS "size", MAX("posts"."updated_at") AS timestamp FROM "posts"
```

### Actual behavior
 `#fresh_when` creates 2 somewhat similar queries.

```sql
SELECT MAX("posts"."updated_at") FROM "posts"
SELECT COUNT(*) AS "size", MAX("posts"."updated_at") AS timestamp FROM "posts"
```

The first query comes from the `#fresh_when` method when it tries to determine the last_modified date:

```ruby
# action_controller/metal/conditional_get.rb
def fresh_when(object = nil, ..., last_modified: nil, ...)
  #...
  last_modified ||= object.try(:updated_at) || object.try(:maximum, :updated_at)
```

The second query comes from `ActiveRecord::Relation#compute_cache_version` through `#fresh_when` when generating `#strong_etag` or `#weak_etag` when the collection is not yet `loaded?`.

```
# stacktrace
active_record/relation.rb:369:in `compute_cache_version'
active_record/relation.rb:340:in `cache_version'
active_record/relation.rb:389:in `cache_key_with_version'
active_support/cache.rb:97:in `retrieve_cache_key'
active_support/cache.rb:99:in `block in retrieve_cache_key'
active_support/cache.rb:99:in `map'
active_support/cache.rb:99:in `retrieve_cache_key'
active_support/cache.rb:90:in `expand_cache_key'
action_dispatch/http/cache.rb:135:in `generate_strong_etag'
action_dispatch/http/cache.rb:131:in `generate_weak_etag'
action_dispatch/http/cache.rb:106:in `weak_etag='
action_controller/metal/conditional_get.rb:114:in `fresh_when'
```

```ruby
# active_record/relation.rb
def compute_cache_version(timestamp_column) # :nodoc:
  timestamp_column = timestamp_column.to_s

  if loaded? || distinct_value
    size = records.size
    if size > 0
      timestamp = records.map { |record| record.read_attribute(timestamp_column) }.max
    end
  else
    collection = eager_loading? ? apply_join_dependency : self

    column = connection.visitor.compile(table[timestamp_column])
    select_values = "COUNT(*) AS #{connection.quote_column_name("size")}, MAX(%s) AS timestamp"

    if collection.has_limit_or_offset?
      query = collection.select("#{column} AS collection_cache_key_timestamp")
      subquery_alias = "subquery_for_cache_key"
      subquery_column = "#{subquery_alias}.collection_cache_key_timestamp"
      arel = query.build_subquery(subquery_alias, select_values % subquery_column)
    else
      query = collection.unscope(:order)
      query.select_values = [select_values % column]
      arel = query.arel
    end

    size, timestamp = connection.select_rows(arel, nil).first

    if size
      column_type = klass.type_for_attribute(timestamp_column)
      timestamp = column_type.deserialize(timestamp)
    else
      size = 0
    end
  end

  if timestamp
    "#{size}-#{timestamp.utc.to_s(cache_timestamp_format)}"
  else
    "#{size}"
  end
end
```

#### OPTION 1

Extract query in `#compute_cache_version`.  This executes 2 identitical queries (2nd one cached).  Something like:

   ```diff
   # action_controller/metal/conditional_get.rb:108:in `fresh_when'
   - last_modified ||= object.try(:updated_at) || object.try(:maximum, :updated_at)
   + last_modified ||= object.try(:updated_at)
   + _size, last_modified ||= object.try(:size_and_timestamp, :updated_at)
   
   # active_record/relation.rb:369:in `compute_cache_version'
   - size, timestamp = connection.select_rows(arel, nil).first
   + size, timestamp = connection.size_and_timestamp(timestamp_column)
   ```

results:

```sql
SELECT COUNT(*) AS "size", MAX("posts"."updated_at") AS timestamp FROM "posts"
[CACHED] SELECT COUNT(*) AS "size", MAX("posts"."updated_at") AS timestamp FROM "posts"
```

#### OPTION 2

Extract last_modified from `#cache_key`.  This executes 1 query  via `cache_key` . (note: tested the following monkeypatch)

```ruby
module FreshWhenLastModifiedFromCacheKey
  def fresh_when(object = nil, **kwargs)
    kwargs[:last_modified] ||= object.try(:updated_at) || last_modified_from_cache_key(object)
    super
  end

  # extract last_modified from cache_key in order to avoid 2 similar queries
  # e.g.
  # SELECT MAX("posts"."updated_at") FROM "posts"
  # SELECT COUNT(*) AS "size", MAX("posts"."updated_at") AS timestamp FROM "posts"
  def last_modified_from_cache_key(object)
    cache_version_timestamp = ActiveSupport::Cache.expand_cache_key(object).to_s.split('-').last
    return unless cache_version_timestamp.present? && object.try(:cache_timestamp_format)

    cache_timestamp_format = Time::DATE_FORMATS[object.cache_timestamp_format].tr('0-9', '') # strip %6N => %N
    time_class = ActiveRecord.default_timezone == :utc ? ActiveSupport::TimeZone['UTC'] : Time
    begin
      time_class.strptime(cache_version_timestamp, cache_timestamp_format)
    rescue ArgumentError
    end
  end
end
      
class ApplicationController < ActionController::Base
  include FreshWhenLastModifiedFromCacheKey
end
```

results:

```sql
SELECT COUNT(*) AS "size", MAX("posts"."updated_at") AS timestamp FROM "posts"
```

### System configuration

**Rails version**: 6.x and main branch (as of 2021-08-28)

**Ruby version**: Any

**Comment by ghiculescu** [comment]
Option 2 feels a bit fragile, for example I don't think it would work if [you don't use `collection_cache_versioning`](https://github.com/rails/rails/blob/ce546c7d3a867dce11e7b99624160a7388bee1f5/activerecord/lib/active_record/relation.rb#L354).

I guess option 1 has a similar issue, in that you could change the query in `fresh_when` but then it'd result in two different queries for people with other cache key generation configurations.

I don't have a solution for this just yet, just thinking out loud 🤔
