### ISSUE TITLE
RAILS_ENV=test rails db:create fails on new 7.0.0.alpha2 project without rexml gem

### ISSUE THREAD

**Issue by ccasabona** [rails/rails#43248]
### Steps to reproduce

Create a new rails 7.0.0.alpha app with

`rails new project_name`

Create something that requires a database migration, i.e:

`rails g scaffold User name email password_digest`

The development migration works:

```
 % rails db:migrate
== 20210918111857 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0017s
== 20210918111857 CreateUsers: migrated (0.0017s) =============================

```

The test migration does not:

```
% RAILS_ENV=test rails db:migrate
rails aborted!
LoadError: cannot load such file -- rexml/document
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/zeitwerk-2.5.0.beta3/lib/zeitwerk/kernel.rb:35:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox.rb:22:in `<main>'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/zeitwerk-2.5.0.beta3/lib/zeitwerk/kernel.rb:35:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/webdrivers-4.6.1/lib/webdrivers/geckodriver.rb:72:in `<main>'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/zeitwerk-2.5.0.beta3/lib/zeitwerk/kernel.rb:35:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/webdrivers-4.6.1/lib/webdrivers.rb:4:in `<main>'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/zeitwerk-2.5.0.beta3/lib/zeitwerk/kernel.rb:35:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.27/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.27/lib/bundler/runtime.rb:55:in `each'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.27/lib/bundler/runtime.rb:55:in `block in require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.27/lib/bundler/runtime.rb:44:in `each'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.27/lib/bundler/runtime.rb:44:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bundler-2.2.27/lib/bundler.rb:174:in `require'
/Users/charlie/sites/aaaaa/config/application.rb:7:in `<main>'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'
/Users/charlie/sites/aaaaa/Rakefile:4:in `<main>'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/railties-7.0.0.alpha2/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/railties-7.0.0.alpha2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/railties-7.0.0.alpha2/lib/rails/command.rb:51:in `invoke'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/railties-7.0.0.alpha2/lib/rails/commands.rb:18:in `<main>'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/charlie/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

### Expected behavior
The migration should execute.

### Actual behavior
The migration fails because the default gemfile does not contain by default the rexml gem.

### System configuration
rails 7.0.0.alpha2

**Ruby version**:
3.0.2

**Comment by byroot** [comment]
Unfortunately that's a bug in `selenium-webdriver`, it was fixed 8 months ago https://github.com/SeleniumHQ/selenium/commit/d7f2ef23b6ba464f64b4b6765ac08dbddecfcf75 but still not released outside of an RC.

**Comment by byroot** [comment]
Ref: https://github.com/SeleniumHQ/selenium/issues/9001

**Comment by byroot** [comment]
To work around this you can add `rexml` to your gemfile, and `require 'rexml'` in `Rakefile`.

**Comment by ceritium** [comment]
@byroot, It would make sense to fix it on the Rails side until selenium-webdriver releases it?

I see two options:
- Require a working release candidate of selenium-webdriver
- Implement your workaround; require rexml.

**Comment by byroot** [comment]
For Rails 7 we can probably add the last RC as dependency, and hopefully it will be fully released by the time Rails 7.0 is ready.

For Rails 6.1 however it's a bit more tricky: https://github.com/rails/rails/issues/43248

**Comment by ccasabona** [comment]
Thank you for your answers and concern.  

At (great) risk of stating the obvious, a just-created new Rails project should work out of the box without having to debug anything.   This is not always possible given the number of 3rd party gems that are incorporated into a basic project.  Either solution proposed here would meet that goal.

**Comment by rafaelfranca** [comment]
I guess for new apps using 4.0.0 will not be a problem for Rails 6.1. I just backported that change
