### ISSUE TITLE
Unable to allow dots in params without slashes

### ISSUE THREAD

**Issue by maths22** [rails/rails#43466]
### Steps to reproduce

See this gist
https://gist.github.com/maths22/d4b0b689fdb18eb4d51d35d852b6e466

### Expected behavior
Given that you have a route that allows dots in a param but not slashes
And given that this route passes its params to a route helper with the same rule
And given that the the route is requested with an escaped slashes in the param
Requesting the route should not fail

### Actual behavior
Given the above, you get the following error:
```
ActionController::UrlGenerationError (No route matches {:action=>"with_dots", :controller=>"test", :param=>"foo/bar"}, possible unmatched constraints: [:param]
Did you mean?  with_dots_url):
  
rails (3b5db8e8c951) actionpack/lib/action_dispatch/journey/formatter.rb:44:in `path'
rails (3b5db8e8c951) actionpack/lib/action_dispatch/routing/route_set.rb:822:in `url_for'
rails (3b5db8e8c951) actionpack/lib/action_dispatch/routing/route_set.rb:269:in `call'
rails (3b5db8e8c951) actionpack/lib/action_dispatch/routing/route_set.rb:325:in `block in define_url_helper'
./action-pack-surprise-demo:38:in `with_dots'
```

This appears to be because the default param regex (`/[^\.\/\?]+/`) isn't enforced when constructing a url (which works since params get escaped when the url is actually built), but if you add an explicit constraint it is enforced at construction time.  Simply removing slashes from the list of prohibited characters doesn't work because then intermediate parameters in urls aren't parsed correctly.

### System configuration
**Rails version**: 6.0.4.1 through main

**Ruby version**: 2.7

**Comment by joiggama** [comment]
👋  @gmcgibbon, I had a look at reproduction steps and noticed the the failing test fails due to the `param` being unescaped when it reaches the controller, e.g.

```
[24] pry(#<TestController>)> with_dots_path(params[:param])
ActionController::UrlGenerationError: No route matches {:action=>"with_dots", :controller=>"test", :param=>"foo/bar"}, possible unmatched constraints: [:param]
from /Users/Ignacio/.gem/ruby/3.2.0/bundler/gems/rails-1bb9f0e616fb/actionpack/lib/action_dispatch/journey/formatter.rb:44:in `path'
```

Escaping `param` in the controller would allow the `url_helper` to correctly match and build the path:

```
[25] pry(#<TestController>)> with_dots_path(CGI.escape(params[:param]))
=> "/with_dots/foo%252Fbar"
[26] pry(#<TestController>)>
```

My understanding is that both requests in tests are being correctly routed to their corresponding controller actions, then the latter fails due to an error building the response as `with_dots` url helper can't match a route with the given param as it's already unescaped.

Am I missing something?

**Comment by evanbattaglia** [comment]
@joiggama 
Sorry we missed the question in February. This has been brought to my attention again after renewed reports of problems from some users.

> Escaping param in the controller would allow the url_helper to correctly match and build the path:
> ```
> [25] pry(#<TestController>)> with_dots_path(CGI.escape(params[:param]))
> => "/with_dots/foo%252Fbar"
> ```
This does not correctly build the path. The `%` is escaped here, so `"with_dots/foo%252Fbar"` would correspond to a param with a literal `%` followed by "2F", rather than a slash. The correct path is `"with_dots/foo%25bar"`.

**Comment by skipkayhil** [comment]
> This does not correctly build the path. The `%` is escaped here, so `"with_dots/foo%252Fbar"` would correspond to a param with a literal `%` followed by "2F", rather than a slash. The correct path is `"with_dots/foo%2Fbar"`

Do you see different behavior in an app compared to the gist posted in the issue? The tests in the gist pass with the `CGI.escape` change mentioned above.

**Comment by evanbattaglia** [comment]
The only assertion in the test is `assert last_response.ok?`; it does not test that `with_dots_path()` returns the correct URL with the parameter properly encoded (`/with_dots/foo%2Fbar`). I can write an updated test if it's helpful.

**Comment by evanbattaglia** [comment]
@skipkayhil
Updated test case at https://gist.github.com/evanbattaglia/a7b84de02245d919b615fcef7afe1d41
Thank you for reopening!

**Comment by evanbattaglia** [comment]
I did a bit more digging to try to understand the difference between supplying a constraint vs. using the default regexp.

It seems that when we give constraints, the constraint is added to the `requirements` in the `Journey::Path::Pattern` object. This happens at around `actionpack-7.0.5.1/lib/action_dispatch/routing/mapper.rb:164` in `Mapping#initialize`:
```
requirements, conditions = split_constraints ast.path_params, constraints
...
ast.requirements = @requirements
@path = Journey::Path::Pattern.new(ast, @requirements, JOINED_SEPARATORS, @anchor)
```
The requirements are checked when constructing a path in `Journey::Path::Pattern#requirements_for_missing_keys_check` (called from `ActionDispatch::Journey::Formatter#missing_keys`):
```
def requirements_for_missing_keys_check
  @requirements_for_missing_keys_check ||= requirements.transform_values do |regex|
    /\A#{regex}\Z/
  end
end
```
It's this requirements check which makes the path construction fail when it sees the slash in the param.

The same requirements are also used (in that `ast.requirements = @requirements` line above) to set the `regexp` value on the `Symbol` node in `Ast#requirements=`:
```
def requirements=(requirements)
  ...
  (symbols + stars).each do |node|
    re = requirements[node.to_sym]
    node.regexp = re if re
  end
```

On the other hand, when we don't give constraints, the `Journey::Path::Pattern` object has no requirements. The `Symbol` node still has a regexp however, which is set by default (journey/nodes/node.rb):
```
class Symbol < Terminal
  ...
  DEFAULT_EXP = /[^.\/?]+/
  GREEDY_EXP = /(.+)/
  def initialize(left, regexp = DEFAULT_EXP)
    super(left)
    @regexp = regexp
    @name = -left.tr("*:", "")
  end
```
Presumably (?) this `regexp` facilitates parsing of slash-separated path segments (so we can do `/foo/:param/bar` and `:param` won't capture the rest of the line) -- as @maths22 mentioned, we can't simply allow slashes in our `constraints` regex.
It seems that what we want in our case is to not have a constraint, but just adjust this regexp to allow unescaped dots. From grepping the code, though, it doesn't seem possible for that `regexp` parameter to `initialize` to get a custom value -- the only time it's passed in is when `GREEDY_EXP` is used instead:
```
def _reduce_10(val, _values)
 Star.new(Symbol.new(val.last, Symbol::GREEDY_EXP))
end
```

An alternative approach to all of this could be to try to change the `escaper` user by the route with a constraint. We'd need to have it not escape at all (to prevent double escaping as seen in the `%252F`), and then always `CGI.escape()` ourselves before calling the path constructor. But it seems like escaping should be one of the details a path constructor abstracts away, lest we forget to call `CGI.escape()` somewhere.

**Comment by evanbattaglia** [comment]
I've managed to hack around this with something like:

```
module ConstraintsBugHackRequirements
  def requirements
    @_constraints_bug_hack_requirements ||= super.reject { |_k, v| v == /[^\/\?]+/ }
  end
end

ActionDispatch::Journey::Path::Pattern.prepend ConstraintsBugHackRequirements
```

But a monkey-patch like this is far from ideal.
