### ISSUE TITLE
ActionController::RequestForgeryProtection::DisabledSessionError in Rails::WelcomeController#index

### ISSUE THREAD

**Issue by TalaatMagdy** [rails/rails#43579]
### Steps to reproduce
when create new project API mode and use Rails 7.0.0.alpha2 then start project `rails s` . 
when visit `http://127.0.0.1:3000/` occur issue 
> ActionController::RequestForgeryProtection::DisabledSessionError in Rails::WelcomeController#index
> Request forgery protection requires a working session store but your application has sessions disabled. You need to either disable request forgery protection, or configure a working session store.

### Expected behavior
appear normal page loading (rails page) without any error 

### Actual behavior
```
Started GET "/" for 127.0.0.1 at 2021-11-02 02:14:51 +0200
   (1.0ms)  SELECT sqlite_version(*)
Processing by Rails::WelcomeController#index as HTML
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms | Allocations: 868)


  
ActionController::RequestForgeryProtection::DisabledSessionError (Request forgery protection requires a working session store but your application has sessions disabled. You need to either disable request forgery protection, or configure a working session store.):
  
actionpack (7.0.0.alpha2) lib/action_controller/metal/request_forgery_protection.rb:483:in `ensure_session_is_enabled!'
actionpack (7.0.0.alpha2) lib/action_controller/metal/request_forgery_protection.rb:472:in `protect_against_forgery?'
actionpack (7.0.0.alpha2) lib/action_controller/metal/request_forgery_protection.rb:321:in `verified_request?'
actionpack (7.0.0.alpha2) lib/action_controller/metal/request_forgery_protection.rb:252:in `verify_authenticity_token'
activesupport (7.0.0.alpha2) lib/active_support/callbacks.rb:415:in `block in make_lambda'
activesupport (7.0.0.alpha2) lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
actionpack (7.0.0.alpha2) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (7.0.0.alpha2) lib/active_support/callbacks.rb:200:in `block in halting'
activesupport (7.0.0.alpha2) lib/active_support/callbacks.rb:500:in `block in invoke_before'
activesupport (7.0.0.alpha2) lib/active_support/callbacks.rb:500:in `each'
activesupport (7.0.0.alpha2) lib/active_support/callbacks.rb:500:in `invoke_before'
activesupport (7.0.0.alpha2) lib/active_support/callbacks.rb:116:in `block in run_callbacks'
activesupport (7.0.0.alpha2) lib/active_support/callbacks.rb:138:in `run_callbacks'
actionpack (7.0.0.alpha2) lib/abstract_controller/callbacks.rb:220:in `process_action'
actionpack (7.0.0.alpha2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (7.0.0.alpha2) lib/action_controller/metal/instrumentation.rb:65:in `block in process_action'
activesupport (7.0.0.alpha2) lib/active_support/notifications.rb:207:in `block in instrument'
activesupport (7.0.0.alpha2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.0.alpha2) lib/active_support/notifications.rb:207:in `instrument'
actionpack (7.0.0.alpha2) lib/action_controller/metal/instrumentation.rb:64:in `process_action'
actionpack (7.0.0.alpha2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (7.0.0.alpha2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (7.0.0.alpha2) lib/abstract_controller/base.rb:151:in `process'
actionview (7.0.0.alpha2) lib/action_view/rendering.rb:39:in `process'
actionpack (7.0.0.alpha2) lib/action_controller/metal.rb:188:in `dispatch'
actionpack (7.0.0.alpha2) lib/action_controller/metal.rb:251:in `dispatch'
actionpack (7.0.0.alpha2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.0.0.alpha2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.0.0.alpha2) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.0.alpha2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.0.alpha2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.0.alpha2) lib/action_dispatch/routing/route_set.rb:845:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
activerecord (7.0.0.alpha2) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.0.alpha2) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.0.alpha2) lib/rails/rack/logger.rb:36:in `call_app'
railties (7.0.0.alpha2) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.0.alpha2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.0.alpha2) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.0.alpha2) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.0.alpha2) lib/rails/rack/logger.rb:25:in `call'
actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.0.alpha2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.0.alpha2) lib/action_dispatch/middleware/host_authorization.rb:96:in `call'
railties (7.0.0.alpha2) lib/rails/engine.rb:530:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

```

### System configuration
**Rails version**:  7.0.0.alpha2

**Ruby version**: 3.0.2

**Comment by ghiculescu** [comment]
Thank you for the report. It looks like this will be fixed in the next alpha release, so if you target the `main` branch it should work fine. See https://github.com/rails/rails/pull/43427

I'm going to close this for now, but if it's still an issue on `main` or an issue elsewhere in your API project please re-open.
