### ISSUE TITLE
File not found error (even though the file is actually there) when using rails

### ISSUE THREAD

**Issue by joulev** [rails/rails#43783]
I'm not even sure if this is an issue of Rails, but since I encountered it when I tried to use Rails and I don't know a more suitable place, I decided to report it here.

### Steps to reproduce
* Install Ruby, Rails and everything as mentioned in [Getting Started](https://guides.rubyonrails.org/getting_started.html)
* Run `rails new blog` (literally following the Getting Started guide)

### Expected behavior
* The command should be executed successfully, of course...

### Actual behavior
* An error was reported: `LoadError: libffi.so.7: cannot open shared object file: No such file or directory - /home/joulev/.local/share/gem/ruby/3.0.0/extensions/x86_64-linux/3.0.0/ffi-1.15.4/ffi_c.so`. Weirdly enough, that file is actually present.

    ```
    $ rails new blog 
    ......
             run  bundle binstubs bundler
           rails  webpacker:install
    rails aborted!
    LoadError: libffi.so.7: cannot open shared object file: No such file or directory - /home/joulev/.local/share/gem/ruby/3.0.0/extensions/x86_64-linux/3.0.0/ffi-1.15.4/ffi_c.so
    ......
    
    $ ls -Alh /home/joulev/.local/share/gem/ruby/3.0.0/extensions/x86_64-linux/3.0.0/ffi-1.15.4  
    total 212K
    -rwxr-xr-x 1 joulev joulev 193K Oct 25 20:22 ffi_c.so
    -rw-r--r-- 1 joulev joulev    0 Oct 25 20:22 gem.build_complete
    -rw-r--r-- 1 joulev joulev 1.4K Oct 25 20:22 gem_make.out
    -rw-r--r-- 1 joulev joulev 9.3K Oct 25 20:22 mkmf.log
    ```

<details>
<summary>Full command output</summary>

```
$ rails new blog 
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /home/joulev/dev/misc/cvwo2122-as/blog/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/spring
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_6_1.rb
      create  config/initializers/permissions_policy.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_6_1.rb
         run  bundle install
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies....
Using rake 13.0.6
Following files may not be writable, so sudo is needed:
  /usr/bin
  /usr/lib/ruby/gems/3.0.0
  /usr/lib/ruby/gems/3.0.0/build_info
  /usr/lib/ruby/gems/3.0.0/cache
  /usr/lib/ruby/gems/3.0.0/doc
  /usr/lib/ruby/gems/3.0.0/extensions
  /usr/lib/ruby/gems/3.0.0/gems
  /usr/lib/ruby/gems/3.0.0/plugins
  /usr/lib/ruby/gems/3.0.0/specifications
Using concurrent-ruby 1.1.9
Using minitest 5.14.4
Using zeitwerk 2.5.1
Using builder 3.2.4
Using erubi 1.10.0
Using racc 1.6.0
Using crass 1.0.6
Using rack 2.2.3
Using mini_mime 1.1.2
Using public_suffix 4.0.6
Using bindex 0.8.1
Using msgpack 1.4.2
Using bundler 2.2.29
Using byebug 11.1.3
Using matrix 0.4.2
Using regexp_parser 2.2.0
Using websocket-extensions 0.1.5
Using ffi 1.15.4
Using nio4r 2.5.8
Using method_source 1.0.0
Using thor 1.1.0
Using marcel 1.0.2
Using rexml 3.2.5
Using rubyzip 2.3.2
Using tilt 2.0.10
Using semantic_range 3.0.0
Using spring 3.1.1
Using sqlite3 1.4.2
Using turbolinks-source 5.2.0
Using tzinfo 2.0.4
Using nokogiri 1.12.5 (x86_64-linux)
Using rack-test 1.1.0
Using mail 2.7.1
Using rack-mini-profiler 2.3.3
Using rack-proxy 0.7.0
Using sprockets 4.0.2
Using addressable 2.8.0
Using i18n 1.8.11
Using websocket-driver 0.7.5
Using rb-fsevent 0.11.0
Using childprocess 4.1.0
Using puma 5.5.2
Using turbolinks 5.2.1
Using sassc 2.4.0
Using xpath 3.2.0
Using activesupport 6.1.4.1
Using bootsnap 1.9.3
Using selenium-webdriver 4.1.0
Using globalid 1.0.0
Using activemodel 6.1.4.1
Using rails-dom-testing 2.0.3
Using jbuilder 2.11.3
Using webdrivers 5.0.0
Using activejob 6.1.4.1
Using activerecord 6.1.4.1
Using rb-inotify 0.10.1
Using capybara 3.36.0
Using loofah 2.12.0
Using rails-html-sanitizer 1.4.2
Using listen 3.7.0
Using actionview 6.1.4.1
Using actionpack 6.1.4.1
Using actioncable 6.1.4.1
Using activestorage 6.1.4.1
Using actionmailer 6.1.4.1
Using railties 6.1.4.1
Using sprockets-rails 3.4.1
Using actionmailbox 6.1.4.1
Using webpacker 5.4.3
Using sassc-rails 2.1.2
Using web-console 4.2.0
Using actiontext 6.1.4.1
Using sass-rails 6.0.0
Using rails 6.1.4.1
Bundle complete! 17 Gemfile dependencies, 75 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  webpacker:install
rails aborted!
LoadError: libffi.so.7: cannot open shared object file: No such file or directory - /home/joulev/.local/share/gem/ruby/3.0.0/extensions/x86_64-linux/3.0.0/ffi-1.15.4/ffi_c.so
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/ffi-1.15.4/lib/ffi.rb:5:in `rescue in <main>'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/ffi-1.15.4/lib/ffi.rb:2:in `<main>'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<main>'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<main>'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:55:in `each'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:55:in `block in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:44:in `each'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:44:in `require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.29/lib/bundler.rb:174:in `require'
/home/joulev/dev/misc/cvwo2122-as/blog/config/application.rb:7:in `<main>'
/home/joulev/dev/misc/cvwo2122-as/blog/Rakefile:4:in `<main>'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/command.rb:50:in `invoke'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<main>'
/home/joulev/dev/misc/cvwo2122-as/blog/bin/rails:5:in `<top (required)>'
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/joulev/dev/misc/cvwo2122-as/blog/bin/spring:10:in `block in <top (required)>'
<internal:kernel>:90:in `tap'
/home/joulev/dev/misc/cvwo2122-as/blog/bin/spring:7:in `<top (required)>'
bin/rails:2:in `load'
bin/rails:2:in `<main>'

Caused by:
LoadError: cannot load such file -- 3.0/ffi_c
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/ffi-1.15.4/lib/ffi.rb:3:in `<main>'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<main>'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<main>'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:55:in `each'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:55:in `block in require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:44:in `each'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.29/lib/bundler/runtime.rb:44:in `require'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/bundler-2.2.29/lib/bundler.rb:174:in `require'
/home/joulev/dev/misc/cvwo2122-as/blog/config/application.rb:7:in `<main>'
/home/joulev/dev/misc/cvwo2122-as/blog/Rakefile:4:in `<main>'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/command.rb:50:in `invoke'
/home/joulev/.local/share/gem/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<main>'
/home/joulev/dev/misc/cvwo2122-as/blog/bin/rails:5:in `<top (required)>'
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/joulev/dev/misc/cvwo2122-as/blog/bin/spring:10:in `block in <top (required)>'
<internal:kernel>:90:in `tap'
/home/joulev/dev/misc/cvwo2122-as/blog/bin/spring:7:in `<top (required)>'
bin/rails:2:in `load'
bin/rails:2:in `<main>'
(See full trace by running task with --trace)

$ ls -Alh /home/joulev/.local/share/gem/ruby/3.0.0/extensions/x86_64-linux/3.0.0/ffi-1.15.4  
total 212K
-rwxr-xr-x 1 joulev joulev 193K Oct 25 20:22 ffi_c.so
-rw-r--r-- 1 joulev joulev    0 Oct 25 20:22 gem.build_complete
-rw-r--r-- 1 joulev joulev 1.4K Oct 25 20:22 gem_make.out
-rw-r--r-- 1 joulev joulev 9.3K Oct 25 20:22 mkmf.log
```
</details>

### System configuration

OS: Manjaro Linux

```
$ ruby --version
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

$ rails --version
Rails 6.1.4.1

$ bundle --version        
Bundler version 2.2.32
```

**Comment by flavorjones** [comment]
:wave: It looks like this is an issue with the `ffi` gem. You should try uninstalling *all* versions of the `ffi` gem and then re-bundler. If that doesn't work, we can dig in a bit more or redirect you.

**Comment by joulev** [comment]
Thank you for your quick response!

Indeed it looks like I already messed up my gem installations pretty badly before this. Just reinstalling `ffi` didn't work, but after I literally purged away everything ruby-related and reinstalled again, it works fine now. Probably an overkill, but it works. Thanks for the help!
