### ISSUE TITLE
uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState

### ISSUE THREAD

**Issue by dorianmariefr** [rails/rails#43851]
### Steps to reproduce

It seems like there is a bug in cocoapods but seems related to the 7.0.0rc1 version of rails, so posting here and there in case

```
gem install cocoapods
pod install
```

```ruby
require File.join(
          File.dirname(`node --print "require.resolve('expo/package.json')"`),
          "scripts/autolinking"
        )
require File.join(
          File.dirname(
            `node --print "require.resolve('react-native/package.json')"`
          ),
          "scripts/react_native_pods"
        )
require File.join(
          File.dirname(
            `node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`
          ),
          "native_modules"
        )

platform :ios, "12.0"

require "json"
podfile_properties =
  begin
    JSON.parse(File.read("./Podfile.properties.json"))
  rescue StandardError
    {}
  end

target "socializus" do
  use_expo_modules!

  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: podfile_properties["expo.jsEngine"] == "hermes"
  )

  use_flipper!({ "Flipper" => "0.119.0" })

  post_install do |installer|
    flipper_post_install(installer)
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      if (target.name&.eql?("FBReactNativeSpec"))
        target.build_phases.each do |build_phase|
          if (
               build_phase.respond_to?(:name) &&
                 build_phase.name.eql?("[CP-User] Generate Specs")
             )
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end
end

target "OneSignalNotificationServiceExtension" do
  pod "OneSignal"
end
```

### Expected behavior

Upgrades pods, works fine

### Actual behavior

An error

```
/Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0.rc1/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
	from /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0.rc1/lib/active_support/xml_mini.rb:103:in `backend='
	from /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0.rc1/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
	from /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0.rc1/lib/active_support/xml_mini.rb:11:in `<top (required)>'
	from <internal:/Users/dorianmariefr/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/dorianmariefr/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0.rc1/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	from <internal:/Users/dorianmariefr/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/dorianmariefr/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/cocoapods-1.11.2/lib/cocoapods.rb:9:in `<top (required)>'
	from <internal:/Users/dorianmariefr/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/dorianmariefr/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/cocoapods-1.11.2/bin/pod:36:in `<top (required)>'
	from /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/bin/pod:25:in `load'
	from /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/bin/pod:25:in `<main>'
	from /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/bin/ruby_executable_hooks:22:in `eval'
	from /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/bin/ruby_executable_hooks:22:in `<main>'
```

### System configuration
**Rails version**:

**Ruby version**:

**Comment by dorianmariefr** [comment]
The fix would be either for rails to add `require "active_support/isolated_execution_state"` in activesupport's lib/active_support/xml_mini.rb or for cocoapods to add it

**Comment by adamniedzielski** [comment]
I stumbled across this error when trying to do:

```ruby
require "active_record/base"

class StagedJob < ActiveRecord::Base
end
```

This is a gem and not a Rails app, so I have to require `active_record` manually. It felt like a good idea to require `active_record/base` specifically as this is the class that I'm referencing in my code.

Unfortunately this doesn't work and throws `ActiveSupport::XmlMini::IsolatedExecutionState`. I'm not sure if `require "active_record/base"` worked before Rails 7 or not 🤔 

Anyway, I changed it to:

```ruby
require "active_record"

class StagedJob < ActiveRecord::Base
end
```

and now it works properly 🎉 That's because `active_record.rb` requires `active_support` properly.

Leaving this comment here, in case somebody finds it useful.

**Comment by dorianmariefr** [comment]
I just stumbled against this error again while upgrading my app to rails 7

```ruby
Failure/Error: require "active_support/testing/time_helpers"

NameError:
  uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState
# /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:184:in `current_thread_backend'
# /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:103:in `backend='
# /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
# /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:11:in `<top (required)>'
# /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0/lib/active_support/core_ext/array/conversions.rb:3:in `require'
# /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
# /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0/lib/active_support/duration.rb:3:in `require'
# /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0/lib/active_support/duration.rb:3:in `<top (required)>'
# /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0/lib/active_support/core_ext/time/calculations.rb:3:in `require'
# /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
# /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0/lib/active_support/testing/time_helpers.rb:4:in `require'
# /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/activesupport-7.0.0/lib/active_support/testing/time_helpers.rb:4:in `<top (required)>'
# ./spec/spec_helper.rb:6:in `require'
# ./spec/spec_helper.rb:6:in `<top (required)>'
```

The fix was to do:

```ruby
require "active_support"
require "active_support/testing/time_helpers"
```

**Comment by ddoherty03** [comment]
Same with `require active_support/date`.  Staying with 6.* for now.

**Comment by jaswinderahuja** [comment]
> ```ruby
> require "active_support"
> require "active_support/testing/time_helpers"
> ```

require in which file please ?

**Comment by dorianmariefr** [comment]
@jaswinderahuja  wherever you are requiring active support time helpers, you need to require active support first
