### ISSUE TITLE
Rails fails to render specific views

### ISSUE THREAD

**Issue by JoaoPedroAssis** [rails/rails#43858]
### Steps to reproduce
I have a docker-compose deploy, that consists of a psql, rails and traefik services. The domain is routed via Cloudflare. Most of the app is working fine, but some specific views are failing to render, and rails gives little information about what has gone wrong.

Basically, when I check the container logs it gives me the following:

```
eduq_1  | Error during failsafe response: errors.css
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:372:in `raise_unless_precompiled_asset'
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:338:in `digest_path'
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:326:in `asset_path'
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:103:in `block in resolve_asset_path'
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:243:in `block in resolve_asset'
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:242:in `each'
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:242:in `detect'
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:242:in `resolve_asset'
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:102:in `resolve_asset_path'
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:80:in `compute_asset_path'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/helpers/asset_url_helper.rb:203:in `asset_path'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/helpers/asset_url_helper.rb:348:in `stylesheet_path'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/helpers/asset_tag_helper.rb:161:in `block in stylesheet_link_tag'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/helpers/asset_tag_helper.rb:160:in `map'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/helpers/asset_tag_helper.rb:160:in `stylesheet_link_tag'
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:186:in `block in stylesheet_link_tag'
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:184:in `map'
eduq_1  |   /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:184:in `stylesheet_link_tag'
eduq_1  |   /app/app/views/errors/internal_server_error.html.erb:2:in `_app_views_errors_internal_server_error_html_erb___4086362273943664643_127160'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/base.rb:247:in `public_send'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/base.rb:247:in `_run'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/template.rb:154:in `block in render'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `block in instrument'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `instrument'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/template.rb:345:in `instrument_render_template'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/template.rb:152:in `render'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `block in instrument'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `instrument'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `block in instrument'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `instrument'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/renderer/template_renderer.rb:11:in `render'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/rendering.rb:117:in `block in _render_template'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/base.rb:273:in `in_rendering_context'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/rendering.rb:116:in `_render_template'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/streaming.rb:218:in `_render_template'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/rendering.rb:103:in `render_to_body'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/abstract_controller/rendering.rb:25:in `render'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/rendering.rb:36:in `render'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
eduq_1  |   /usr/local/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
eduq_1  |   /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/instrumentation.rb:45:in `render'
eduq_1  |   /usr/local/bundle/gems/meta-tags-2.16.0/lib/meta_tags/controller_helper.rb:22:in `render'
eduq_1  |   /app/app/controllers/errors_controller.rb:18:in `internal_server_error'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/abstract_controller/base.rb:228:in `process_action'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:106:in `run_callbacks'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `block in instrument'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `instrument'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
eduq_1  |   /usr/local/bundle/gems/activerecord-6.1.4.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/abstract_controller/base.rb:165:in `process'
eduq_1  |   /usr/local/bundle/gems/actionview-6.1.4.1/lib/action_view/rendering.rb:39:in `process'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal.rb:190:in `dispatch'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_controller/metal.rb:254:in `dispatch'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/journey/router.rb:32:in `each'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/journey/router.rb:32:in `serve'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/routing/route_set.rb:842:in `call'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/show_exceptions.rb:52:in `render_exception'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
eduq_1  |   /usr/local/bundle/gems/railties-6.1.4.1/lib/rails/rack/logger.rb:37:in `call_app'
eduq_1  |   /usr/local/bundle/gems/railties-6.1.4.1/lib/rails/rack/logger.rb:26:in `block in call'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/tagged_logging.rb:37:in `tagged'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/tagged_logging.rb:99:in `tagged'
eduq_1  |   /usr/local/bundle/gems/railties-6.1.4.1/lib/rails/rack/logger.rb:26:in `call'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
eduq_1  |   /usr/local/bundle/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
eduq_1  |   /usr/local/bundle/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
eduq_1  |   /usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/static.rb:24:in `call'
eduq_1  |   /usr/local/bundle/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
eduq_1  |   /usr/local/bundle/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
eduq_1  |   /usr/local/bundle/gems/railties-6.1.4.1/lib/rails/engine.rb:539:in `call'
eduq_1  |   /usr/local/bundle/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
eduq_1  |   /usr/local/bundle/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
eduq_1  |   /usr/local/bundle/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
eduq_1  |   /usr/local/bundle/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
eduq_1  |   /usr/local/bundle/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```
where eduq_1 is the container/service name.

When I go inside the container and check the `production.log` file, it gives me this output:

```
... usual rails active record queries...

D, [2021-12-13T17:51:32.901953 #7] DEBUG -- : [123f80f4-514a-431e-813a-3b99e0089186]   Rendering layout layouts/logged_user_layout.html.erb
D, [2021-12-13T17:51:32.902148 #7] DEBUG -- : [123f80f4-514a-431e-813a-3b99e0089186]   Rendering dashboard/dashboard.html.erb within layouts/logged_user_layout
I, [2021-12-13T17:51:32.903424 #7]  INFO -- : [123f80f4-514a-431e-813a-3b99e0089186]   Rendered dashboard/dashboard.html.erb within layouts/logged_user_layout (Duration: 1.2ms | Allocations: 687)
I, [2021-12-13T17:51:32.903575 #7]  INFO -- : [123f80f4-514a-431e-813a-3b99e0089186]   Rendered layout layouts/logged_user_layout.html.erb (Duration: 1.5ms | Allocations: 744)
I, [2021-12-13T17:51:32.903831 #7]  INFO -- : [123f80f4-514a-431e-813a-3b99e0089186] Completed 500 Internal Server Error in 204ms (ActiveRecord: 96.0ms | Allocations: 46834)
F, [2021-12-13T17:51:32.905149 #7] FATAL -- : [123f80f4-514a-431e-813a-3b99e0089186]
[123f80f4-514a-431e-813a-3b99e0089186] ActionView::Template::Error (dashboard.css):
[123f80f4-514a-431e-813a-3b99e0089186]     1: <%= stylesheet_link_tag "dashboard" %>
[123f80f4-514a-431e-813a-3b99e0089186]     2: <h3 class=""><%= welcome_message.html_safe %>, <%= current_user.first_name %>!</h3>
[123f80f4-514a-431e-813a-3b99e0089186]     3: <h6 class="text-muted">Dashboard</h6>
[123f80f4-514a-431e-813a-3b99e0089186]     4:
[123f80f4-514a-431e-813a-3b99e0089186]
[123f80f4-514a-431e-813a-3b99e0089186] app/views/dashboard/dashboard.html.erb:1
I, [2021-12-13T17:51:32.914308 #7]  INFO -- : [123f80f4-514a-431e-813a-3b99e0089186] Processing by ErrorsController#internal_server_error as HTML
D, [2021-12-13T17:51:32.915159 #7] DEBUG -- : [123f80f4-514a-431e-813a-3b99e0089186]   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 5 LIMIT 1
D, [2021-12-13T17:51:32.916028 #7] DEBUG -- : [123f80f4-514a-431e-813a-3b99e0089186]   Rendering layout layouts/error-layout.html.erb
D, [2021-12-13T17:51:32.916126 #7] DEBUG -- : [123f80f4-514a-431e-813a-3b99e0089186]   Rendering errors/internal_server_error.html.erb within layouts/error-layout
I, [2021-12-13T17:51:32.917528 #7]  INFO -- : [123f80f4-514a-431e-813a-3b99e0089186]   Rendered errors/internal_server_error.html.erb within layouts/error-layout (Duration: 1.3ms | Allocations: 676)
I, [2021-12-13T17:51:32.917668 #7]  INFO -- : [123f80f4-514a-431e-813a-3b99e0089186]   Rendered layout layouts/error-layout.html.erb (Duration: 1.6ms | Allocations: 733)
I, [2021-12-13T17:51:32.917971 #7]  INFO -- : [123f80f4-514a-431e-813a-3b99e0089186] Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms | Allocations: 1056)
```
The strange thing is that this error only happens in some views, the other ones are working just fine. All the assets are being properly precompiled, and the migrations have been run. I'm stuck with this for quite some time now, and have no clue on what is causing the error

### Expected behavior
The views should render properly.

### Actual behavior
The apps custom error page is not shown, instead the following plaintext is displayed:

`500 Internal Server Error If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.`

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.2

**Comment by ghiculescu** [comment]
> All the assets are being properly precompiled, and the migrations have been run. I'm stuck with this for quite some time now, and have no clue on what is causing the error

Are you sure? This error suggests that the relevant assets have not been precompiled. It's crashing here: https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/rails/helper.rb#L372

**Comment by JoaoPedroAssis** [comment]
> > All the assets are being properly precompiled, and the migrations have been run. I'm stuck with this for quite some time now, and have no clue on what is causing the error
> 
> Are you sure? This error suggests that the relevant assets have not been precompiled. It's crashing here: https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/rails/helper.rb#L372

Yeah, i'm pretty sure. I have the precompile command on the dockerfile and the build process shows that it has been successful. Besides that, i've run the command inside the container, so the fact that these assets were not precompiled is what's bothering me

**Comment by ghiculescu** [comment]
Is this issue in production or development (or both)?

In production, sprockets should have generated a file called `manifest-HASH.json`. In my case it lives in `public/assets` but that may differ for you. The manifest contains a record of all the files sprockets thinks it has precompiled, as well as a path to them. The path is then used by `asset_path` to construct a full URL (ie. to add a link to a CDN or whatever your asset host is)

So as a starting point, check if the files in question exist in your manifest file.

**Comment by JoaoPedroAssis** [comment]
@ghiculescu It's in production, development works just fine. I think I found the correct file, but it was named `.sprockets-manifest-46fbaa303af652485010bba3fad11c78.json` (not intuitive, took me a while haha). Anyway, I inspected the file on the dashboard stylesheet part, since it was on the crash log posted above and found the following:

```json
"dashboard-d291209d1ba16383930ecbc635a9db8729bc77eb4e8d339a924c5a2504064323.scss": {
      "logical_path": "dashboard.scss",
      "mtime": "2021-12-13T19:34:22-03:00",
      "size": 1034,
      "digest": "ecb770173b75c5aa5d76719862b2ab81bd23c059bea4916651ec834c2db6a141",
      "integrity": "sha256-7LdwFzt1xapddnGYYrKrgb0jwFm+pJFmUeyDTC22oUE="
 },
"assets": {
  "dashboard.scss": "dashboard-d291209d1ba16383930ecbc635a9db8729bc77eb4e8d339a924c5a2504064323.scss"
}
``` 

This tells me that the file is in fact precompiled and its path is correct. Am I missing something?

**Comment by ghiculescu** [comment]
```
[123f80f4-514a-431e-813a-3b99e0089186] ActionView::Template::Error (dashboard.css):
[123f80f4-514a-431e-813a-3b99e0089186]     1: <%= stylesheet_link_tag "dashboard" %>
```

Here it seems like sprockets is looking for `dashboard.css`.

But in the manifest you have `dashboard.scss`.

**Comment by JoaoPedroAssis** [comment]
> ```
> [123f80f4-514a-431e-813a-3b99e0089186] ActionView::Template::Error (dashboard.css):
> [123f80f4-514a-431e-813a-3b99e0089186]     1: <%= stylesheet_link_tag "dashboard" %>
> ```
> 
> Here it seems like sprockets is looking for `dashboard.css`.
> 
> But in the manifest you have `dashboard.scss`.

All other assets are in .scss format so it is a bit odd thar rails is looking for a .css one. Nevertheless, I found that other assets are being referenced as .css

Is there a reason why rails would do that kind of change? And how could I make it reference the files correctly?

**Comment by ghiculescu** [comment]
I think .css is correct for a production asset... you want to be serving .css files not .scss files.

I don't have any good ideas as to what's causing it to behave differently for this specific asset though. Is there a file at `app/assets/stylesheets/dashboard.css`? (not scss)

**Comment by JoaoPedroAssis** [comment]
> I think .css is correct for a production asset... you want to be serving .css files not .scss files.
> 
> I don't have any good ideas as to what's causing it to behave differently for this specific asset though. Is there a file at `app/assets/stylesheets/dashboard.css`? (not scss)

Sorry, I meant to say that. All my assets are written in scss (so there is not a dashboard.css in `assets/stylesheets/`), but served in css. So I think that the problem is that the precompiled assets has not turned into css during `assets:precompile`. This is driving me crazy, because there is no logical reason to this behavior, since most files were processed correctly

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by JoaoPedroAssis** [comment]
Hey @ghiculescu, I'm happy to inform that i have fixed the issue. My `assets.rb` file contained files ending in .scss and not .css. I didn't realize you should put in the name you want the asset to have after it's precompiled. The only issue here is how tf this hasn't broken the system before 🤣 , it has been running for a couple of years now. Thanks for the support!
