### ISSUE TITLE
FixturesWithForeignKeyViolationsTest#test_does_not_raise_if_no_fk_violations#test_does_not_raise_if_no_fk_violations error

### ISSUE THREAD

**Issue by yahonda** [rails/rails#43872]
Managed to reproduce CI failure at https://buildkite.com/rails/rails/builds/83346#2ac29d83-54bf-4123-8a94-c483218ebaf6 . 

Unlike the similar ones like #43101 and #42829 . I do not find a way to address it because `PreloaderTest` file already load both `:authors` and `:author_addresses`
https://github.com/rails/rails/blob/139183cbce9b8251a2071d255b264ac0d99687d7/activerecord/test/cases/associations_test.rb#L38

### Steps to reproduce

```ruby
cd activerecord
ARCONN=postgresql bin/test test/cases/associations_test.rb test/cases/fixtures_test.rb -n "/^(?:PreloaderTest#(?:test_preload_grouped_queries_of_middle_records)|FixturesWithForeignKeyViolationsTest#(?:test_does_not_raise_if_no_fk_violations))$/" --seed 62142
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ ARCONN=postgresql bin/test test/cases/associations_test.rb test/cases/fixtures_test.rb -n "/^(?:PreloaderTest#(?:test_preload_grouped_queries_of_middle_records)|FixturesWithForeignKeyViolationsTest#(?:test_does_not_raise_if_no_fk_violations))$/" --seed 62142
Using postgresql
Run options: -n "/^(?:PreloaderTest#(?:test_preload_grouped_queries_of_middle_records)|FixturesWithForeignKeyViolationsTest#(?:test_does_not_raise_if_no_fk_violations))$/" --seed 62142

# Running:

.E

Error:
FixturesWithForeignKeyViolationsTest#test_does_not_raise_if_no_fk_violations:
RuntimeError: Foreign key violations found in your fixture data. Ensure you aren't referring to labels that don't exist on associations.
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:633:in `block in insert'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:621:in `each'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:621:in `insert'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:607:in `read_and_insert'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:567:in `create_fixtures'
    /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/fixtures_test.rb:846:in `block (2 levels) in test_does_not_raise_if_no_fk_violations'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/assertions.rb:34:in `assert_nothing_raised'
    /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/fixtures_test.rb:845:in `block in test_does_not_raise_if_no_fk_violations'
    /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/fixtures_test.rb:859:in `with_verify_foreign_keys_for_fixtures'
    /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/fixtures_test.rb:844:in `test_does_not_raise_if_no_fk_violations'


bin/test test/cases/fixtures_test.rb:837



Finished in 0.237820s, 8.4097 runs/s, 4.2049 assertions/s.
2 runs, 1 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**:ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]

**Comment by yahonda** [comment]
Just after this test gets error, I have executed sql statementto validate foreign key defined at https://github.com/rails/rails/blob/139183cbce9b8251a2071d255b264ac0d99687d7/activerecord/lib/active_record/connection_adapters/postgresql/referential_integrity.rb#L42-L60
It shows the foreign key violation is parental record does not exist in "author_addresses".

```sql
$ psql -d activerecord_unittest
psql (14.0 (Ubuntu 14.0-1.pgdg21.04+1))
Type "help" for help.

activerecord_unittest=#             do $$
              declare r record;
            BEGIN
            FOR r IN (
              SELECT FORMAT(
                'UPDATE pg_constraint SET convalidated=false WHERE conname = ''%I''; ALTER TABLE %I VALIDATE CONSTRAINT %I;',
                constraint_name,
                table_name,
                constraint_name
              ) AS constraint_check
              FROM information_schema.table_constraints WHERE constraint_type = 'FOREIGN KEY'
            )
              LOOP
                EXECUTE (r.constraint_check);
              END LOOP;
            END;
            $$;
ERROR:  insert or update on table "authors" violates foreign key constraint "fk_rails_94423a17a3"
DETAIL:  Key (author_address_id)=(1) is not present in table "author_addresses".
CONTEXT:  SQL statement "UPDATE pg_constraint SET convalidated=false WHERE conname = 'fk_rails_94423a17a3'; ALTER TABLE authors VALIDATE CONSTRAINT fk_rails_94423a17a3;"
PL/pgSQL function inline_code_block line 14 at EXECUTE
activerecord_unittest=#
```

**Comment by yahonda** [comment]
My bad. I was watching fixtures of the different test case.

`PreloaderTest` fixture only loads `: authors`. `:author_addresses` is missing. 
https://github.com/rails/rails/blob/139183cbce9b8251a2071d255b264ac0d99687d7/activerecord/test/cases/associations_test.rb#L398

**Comment by yahonda** [comment]
Will open a pull request to address it.
