### ISSUE TITLE
Rails 7.0.0: requiring active_support/core_ext/string raises 

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [rails/rails#43889]
Similar to https://github.com/rails/rails/issues/43851 that was closed by the author but with a simple repro:

### Steps to reproduce
```sh
ruby -e 'require "active_support"; puts ActiveSupport.version'
# => 7.0.0

ruby -e 'require "active_support/core_ext/string"'
/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
	from /Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:103:in `backend='
	from /Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
	from /Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:11:in `<top (required)>'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from /Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from /Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/duration.rb:3:in `<top (required)>'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from /Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from /Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/core_ext/string/conversions.rb:4:in `<top (required)>'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from /Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/core_ext/string.rb:3:in `<top (required)>'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from -e:1:in `<main>'
<internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- active_support/core_ext/string (LoadError)
	from <internal:/Users/jfeltesse/.asdf/installs/ruby/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'
```

### Expected behavior
Doesn't blow up.

### Actual behavior
Blows up.

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.3

**Comment by matthewd** [comment]
Requiring individual files from Active Support without first requiring the top-level `active_support` is not supported.

Does this work for you?

```
ruby -e 'require "active_support"; require "active_support/core_ext/string"'
```

**Comment by jfeltesse-mdsol** [comment]
That works indeed, I didn't know you _always_ had to require active_support, it worked just fine up until now.

Wouldn't that require the entire collection of active support utilities though?
We have a bunch of libraries that only use select active support utilities and requiring the entire collection would needlessly make startup slower and increase memory consumption.

**Comment by rafaelfranca** [comment]
> Wouldn't that require the entire collection of active support utilities though?

No, it would not. It would just setup and require the common parts of Active Support.

**Comment by jfeltesse-mdsol** [comment]
Thanks for the precisions!
