### ISSUE TITLE
undefined method 'response' for ActionMailer

### ISSUE THREAD

**Issue by alecslupu** [rails/rails#43884]
### Steps to reproduce
When importing a stylesheet in a mailer, the following error is encountered: 
```
undefined method `response' for #<Decidim::DecidimDeviseMailer:0x00000000038ea0>
```

Which is caused by 
https://github.com/rails/rails/blob/67a8028f094f682a50a2fbbbdaaaed9faf6fdaaf/actionview/lib/action_view/helpers/asset_tag_helper.rb#L545

As you can see few lines below the following snippet is present:

https://github.com/rails/rails/blob/67a8028f094f682a50a2fbbbdaaaed9faf6fdaaf/actionview/lib/action_view/helpers/asset_tag_helper.rb#L551

### Expected behavior
Would be to have a link tag in the mailer template.

### Actual behavior
```
 ActionView::Template::Error:
       undefined method `response' for #<Decidim::DecidimDeviseMailer:0x00000000038ea0>
       Did you mean?  response_body
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/helpers/controller_helper.rb:16:in `response'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/helpers/asset_tag_helper.rb:545:in `send_preload_links_header'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/helpers/asset_tag_helper.rb:202:in `stylesheet_link_tag'
     # /bundle_cache/ruby/2.7.0/gems/webpacker-6.0.0.rc.5/lib/webpacker/helper.rb:146:in `stylesheet_pack_tag'
     # /code/decidim/decidim-core/app/views/layouts/decidim/mailer.html.erb:6:in `__code_decidim_decidim_core_app_views_layouts_decidim_mailer_html_erb___328851960538032058_116540'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/base.rb:244:in `public_send'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/base.rb:244:in `_run'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/template.rb:157:in `block in render'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/notifications.rb:208:in `instrument'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/template.rb:361:in `instrument_render_template'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/template.rb:155:in `render'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/renderer/template_renderer.rb:76:in `block in render_with_layout'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/notifications.rb:206:in `block in instrument'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/notifications.rb:206:in `instrument'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/renderer/template_renderer.rb:74:in `render_with_layout'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/renderer/template_renderer.rb:59:in `render_template'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/renderer/template_renderer.rb:11:in `render'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/rendering.rb:117:in `block in _render_template'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/base.rb:270:in `in_rendering_context'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/rendering.rb:116:in `_render_template'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/rendering.rb:103:in `render_to_body'
     # /bundle_cache/ruby/2.7.0/gems/actionpack-7.0.0.rc1/lib/abstract_controller/rendering.rb:25:in `render'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/base.rb:967:in `block in collect_responses_from_templates'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/base.rb:964:in `each'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/base.rb:964:in `each'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/base.rb:964:in `map'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/base.rb:964:in `collect_responses_from_templates'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/base.rb:942:in `collect_responses'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/base.rb:850:in `mail'
     # /bundle_cache/ruby/2.7.0/bundler/gems/devise-9f5b83750eef/lib/devise/mailers/helpers.rb:19:in `devise_mail'
     # /code/decidim/decidim-core/app/mailers/decidim/decidim_devise_mailer.rb:34:in `block in devise_mail'
     # /code/decidim/decidim-core/app/mailers/concerns/decidim/localised_mailer.rb:19:in `block in with_user'
     # /bundle_cache/ruby/2.7.0/gems/i18n-1.8.11/lib/i18n.rb:314:in `with_locale'
     # /code/decidim/decidim-core/app/mailers/concerns/decidim/localised_mailer.rb:18:in `with_user'
     # /code/decidim/decidim-core/app/mailers/decidim/decidim_devise_mailer.rb:32:in `devise_mail'
     # /code/decidim/decidim-core/app/mailers/decidim/decidim_devise_mailer.rb:25:in `invitation_instructions'
     # /bundle_cache/ruby/2.7.0/gems/actionpack-7.0.0.rc1/lib/abstract_controller/base.rb:214:in `process_action'
     # /bundle_cache/ruby/2.7.0/gems/actionpack-7.0.0.rc1/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/callbacks.rb:107:in `run_callbacks'
     # /bundle_cache/ruby/2.7.0/gems/actionpack-7.0.0.rc1/lib/abstract_controller/callbacks.rb:233:in `process_action'
     # /bundle_cache/ruby/2.7.0/gems/actionpack-7.0.0.rc1/lib/abstract_controller/base.rb:151:in `process'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/rescuable.rb:25:in `block in process'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/rescuable.rb:24:in `process'
     # /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/rendering.rb:39:in `process'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/base.rb:622:in `block in process'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/notifications.rb:206:in `block in instrument'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/notifications.rb:206:in `instrument'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/base.rb:621:in `process'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/message_delivery.rb:128:in `block in processed_mailer'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/message_delivery.rb:127:in `tap'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/message_delivery.rb:127:in `processed_mailer'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
     # /bundle_cache/ruby/2.7.0/gems/actionmailer-7.0.0.rc1/lib/action_mailer/mail_delivery_job.rb:23:in `perform'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/execution.rb:59:in `block in _perform_job'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
     # /bundle_cache/ruby/2.7.0/gems/i18n-1.8.11/lib/i18n.rb:314:in `with_locale'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/callbacks.rb:127:in `instance_exec'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/callbacks.rb:127:in `instance_exec'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/callbacks.rb:138:in `run_callbacks'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/execution.rb:58:in `_perform_job'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/instrumentation.rb:20:in `_perform_job'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/execution.rb:46:in `perform_now'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/instrumentation.rb:14:in `block in perform_now'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/instrumentation.rb:25:in `block in instrument'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/notifications.rb:206:in `block in instrument'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/notifications.rb:206:in `instrument'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/instrumentation.rb:35:in `instrument'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/instrumentation.rb:14:in `perform_now'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/logging.rb:18:in `block in perform_now'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/tagged_logging.rb:37:in `tagged'
     # /bundle_cache/ruby/2.7.0/gems/activesupport-7.0.0.rc1/lib/active_support/tagged_logging.rb:99:in `tagged'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/logging.rb:25:in `tag_logger'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/logging.rb:18:in `perform_now'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/test_helper.rb:691:in `block in flush_enqueued_jobs'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/test_helper.rb:667:in `block in jobs_with'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/test_helper.rb:650:in `select'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/test_helper.rb:650:in `jobs_with'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/test_helper.rb:680:in `enqueued_jobs_with'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/test_helper.rb:688:in `flush_enqueued_jobs'
     # /bundle_cache/ruby/2.7.0/gems/activejob-7.0.0.rc1/lib/active_job/test_helper.rb:599:in `perform_enqueued_jobs'
     # ./spec/commands/decidim/system/register_organization_spec.rb:114:in `block (6 levels) in <module:System>'
     # ./spec/commands/decidim/system/register_organization_spec.rb:112:in `block (5 levels) in <module:System>'
     # /bundle_cache/ruby/2.7.0/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `response' for #<Decidim::DecidimDeviseMailer:0x00000000038ea0>
     #   Did you mean?  response_body
     #   /bundle_cache/ruby/2.7.0/gems/actionview-7.0.0.rc1/lib/action_view/helpers/controller_helper.rb:16:in `response'
```

### System configuration
**Rails version**: 7.0.0.rc1
**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**Comment by rafaelfranca** [comment]
Thank you for the issue. Can you submit a pull request please?

**Comment by alecslupu** [comment]
@rafaelfranca I have created #43885 . 
I am not really sure what kind of test to add for this issue.

**Comment by rafaelfranca** [comment]
Thanks!
