### ISSUE TITLE
Can't load active_support/time anymore after update to 7.0.0

### ISSUE THREAD

**Issue by dhs-rec** [rails/rails#43908]
### Steps to reproduce

```ruby
% irb
3.0.2 :001 > require 'active_support/time'
/usr/local/rvm/gems/ruby-3.0.2@RubyTest/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
        from /usr/local/rvm/gems/ruby-3.0.2@RubyTest/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:103:in `backend='
        from /usr/local/rvm/gems/ruby-3.0.2@RubyTest/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
        from /usr/local/rvm/gems/ruby-3.0.2@RubyTest/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:11:in `<top (required)>'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/rvm/gems/ruby-3.0.2@RubyTest/gems/activesupport-7.0.0/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/rvm/gems/ruby-3.0.2@RubyTest/gems/activesupport-7.0.0/lib/active_support/duration.rb:3:in `<top (required)>'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/rvm/gems/ruby-3.0.2@RubyTest/gems/activesupport-7.0.0/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/rvm/gems/ruby-3.0.2@RubyTest/gems/activesupport-7.0.0/lib/active_support/core_ext/time.rb:4:in `<top (required)>'
        from <internal:/usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        ... 9 levels...
<internal:/usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- active_support/time (LoadError)
        from <internal:/usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from (irb):1:in `<main>'
        from /usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-3.0.2/bin/irb:23:in `load'
        from /usr/local/rvm/rubies/ruby-3.0.2/bin/irb:23:in `<main>'
```

### Expected behavior
Module should be loaded, as is the case with 6.1.4.4

### Actual behavior
See above

### System configuration
**ActiveSupport version**: 7.0.0

**Ruby version**: 3.0.2

**Comment by casperisfine** [comment]
See https://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support, `active_support` must be required before any sub component.

Note that it won't load all of active support, only the minimum required parts.

**Comment by dhs-rec** [comment]
Yeah, that works. Thanks a lot.

**Comment by casperisfine** [comment]
Welcome.
