### ISSUE TITLE
Method current_page? does not work on rails 6.0 and Ruby 3

### ISSUE THREAD

**Issue by BackendDev-Auction** [rails/rails#43952]
### Steps to reproduce

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', '~> 6.0.0'
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
  include ActionView::Helpers::UrlHelper

  def index
    current_page?(action: 'index')
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end

```
### Expected behavior
Test should pass

### Actual behavior
ArgumentError is thrown.
```
I, [2021-12-21T17:41:08.073278 #43384]  INFO -- : Started GET "/" for 127.0.0.1 at 2021-12-21 17:41:08 +0530
F, [2021-12-21T17:41:08.076700 #43384] FATAL -- :
ArgumentError (wrong number of arguments (given 0, expected 1)):

actionview (6.0.4.4) lib/action_view/helpers/url_helper.rb:543:in `current_page?'
rub.rb:33:in `index'
actionpack (6.0.4.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.4.4) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.4.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.4.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.4.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.4.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
```

### System configuration
**Rails version**: 6.0.4.4

**Ruby version**: 3.0.2

A fix was made but I think it works only on 6.1 https://github.com/rails/rails/pull/41206

**Comment by ghiculescu** [comment]
Thanks for the report, however Rails 6 is not supported anymore. See https://guides.rubyonrails.org/maintenance_policy.html

You could try a monkey patch fix in an initializer (I haven't tested this, but just a suggestion that you could explore if you like):

```ruby
module ActionView::Helpers::UrlHelper
      def current_page?(options = nil, check_parameters: false, **options_as_kwargs)
        unless request
          raise "You cannot use helpers that need to determine the current " \
                "page unless your view context provides a Request object " \
                "in a #request method"
        end

        return false unless request.get? || request.head?

        options ||= options_as_kwargs
        check_parameters ||= options.is_a?(Hash) && options.delete(:check_parameters)
        url_string = URI::DEFAULT_PARSER.unescape(url_for(options)).force_encoding(Encoding::BINARY)

        # We ignore any extra parameters in the request_uri if the
        # submitted URL doesn't have any either. This lets the function
        # work with things like ?order=asc
        # the behaviour can be disabled with check_parameters: true
        request_uri = url_string.index("?") || check_parameters ? request.fullpath : request.path
        request_uri = URI::DEFAULT_PARSER.unescape(request_uri).force_encoding(Encoding::BINARY)
        if url_string.start_with?("/") && url_string != "/"
          url_string.chomp!("/")
          request_uri.chomp!("/")
        end
        if %r{^\w+://}.match?(url_string)
          url_string == "#{request.protocol}#{request.host_with_port}#{request_uri}"
        else
          url_string == request_uri
        end
      end
end
```
