### ISSUE TITLE
Active Text / Active Storage: vips.so.42: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by overdrivemachines** [rails/rails#43976]
### Steps to reproduce
I encountered this error while following DHH's youtube video "Rails 7: The Demo" at 9:10. I have a fresh install of Ubuntu 20.04 and RoR. I got the same error on another computer with a freshly installed Ubuntu and RoR.  Here are the steps:
1) Install action_text and add a rich_text_area to a form.
2) Run rails server
3) add some text and image to the rich text and hit submit

### Expected behavior
contents of form get saved normally along with image getting uploaded.

### Actual behavior
Rails server quits and I see the following error:

```
...
...
#<Thread:0x00007fd7113596f8 /home/dynamic/.rvm/gems/ruby-3.0.2/gems/actionpack-7.0.0/lib/action_controller/metal/live.rb:340 run> terminated with exception (report_on_exception is true):
/home/dynamic/.rvm/gems/ruby-3.0.2/gems/ffi-1.15.4/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory
	from /home/dynamic/.rvm/gems/ruby-3.0.2/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `map'
	from /home/dynamic/.rvm/gems/ruby-3.0.2/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `ffi_lib'
	from /home/dynamic/.rvm/gems/ruby-3.0.2/gems/ruby-vips-2.1.4/lib/vips.rb:573:in `<module:Vips>'
	from /home/dynamic/.rvm/gems/ruby-3.0.2/gems/ruby-vips-2.1.4/lib/vips.rb:570:in `<main>'
...
...
```

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.3

### What fixed the issue:
I installed ImageMagick and libvips: `sudo apt install imagemagick libvips` and the error went away and everything works normally. It took me a long time to figure that out. I hope there is a more appropriate error message when ImageMagick and libvips are not installed on the computer. The error message should clearly ask the user to install ImageMagick to proceed. This will save a lot of frustration and time.

**Comment by diabolo** [comment]
Similar issue here.

I think that the reason for the error is that turbo is not installed. In the YouTube video hotwire is installed by default. Following along with rails 7 it isn't. You need to run

```
rails importmap:install
rails turbo:install:importmap
```

Doing the turbo install adds a number of gems.

```
Installing mini_magick 4.11.0
Installing ruby-vips 2.1.4
Fetching image_processing 1.12.1
Installing image_processing 1.12.1
```

which may fix the issue without having to install imagemagick and libvips.

**Comment by ghiculescu** [comment]
@overdrivemachines could you share a sample app that reproduces the issue? It'd be good to confirm what gems are present.

**Comment by jcowhigjr** [comment]
To reproduce I was also following DHH guide using the latest Dockerfile with the default rails new Gemfile.

``` # Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
-# gem "image_processing", "~> 1.2"
+gem "image_processing", "~> 1.2"
```
Gemfile.lock
```    image_processing (1.12.1)
      mini_magick (>= 4.9.5, < 5)
      ruby-vips (>= 2.0.17, < 3)
````
the Gemfile comment could be changed to: 
Please see these dependencies -> https://guides.rubyonrails.org/active_storage_overview.html#requirements

However, it was a fairly simple fix based on https://www.libvips.org/install.html since I've used ubuntu a lot to search for a vips package (imagemagick not required)

for example for the tutorial, I added one new package and rebuilt the container for this: 

libvips-dev

FROM ruby:3.1.0-rc-slim

 RUN apt-get update -qq \
  && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
    build-essential \
    gnupg2 \
    curl \
    less \
    git \
    shared-mime-info \
    libsqlite3-dev \
    libvips-dev \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

add libvips-dev

The requirement is discussed here.  https://github.com/rails/rails/issues/43182

**Comment by ghiculescu** [comment]
https://guides.rubyonrails.org/active_storage_overview.html#requirements documents this.

> Various features of Active Storage depend on third-party software which Rails will not install, and must be installed separately.

A PR to make the error message better would be awesome, if anyone wants to make one.

**Comment by brenogazzola** [comment]
If anyone decides to pick that, you can use `Analyzer::ImageAnalyzer::Vips` as an example. It catches the `LoadError` and prints a message saying `ruby-vips` is not installed.

**Comment by Zicrou** [comment]
> 

hi can you please tell me where to put that `

> Analyzer::ImageAnalyzer::Vips``

`

**Comment by Zicrou** [comment]
> If anyone decides to pick that, you can use `Analyzer::ImageAnalyzer::Vips` as an example. It catches the `LoadError` and prints a message saying `ruby-vips` is not installed.
hi can you please tell me where to put that `

    Analyzer::ImageAnalyzer::Vips``

`

**Comment by charlietag** [comment]
## Root cause

* **Rails 7** default is using `libvips v8.6+` to deal with image (resize with gem `image_processing`)
  * https://edgeguides.rubyonrails.org/configuring.html#configuring-active-storage
    ![image](https://user-images.githubusercontent.com/6238917/151618507-ebb70a3d-e0e0-400c-b503-8b292e4a8c4a.png)

## Solution 1 (change back to use `ImageMagick` like what `<= Rails 6` did)

* **config/application.rb**

  ```diff
  config.load_defaults 7.0
  + config.active_storage.variant_processor = :mini_magic
  ```

## Solution 2 (Install `libvips v8.6+` packages via OS package manager)

* Ubuntu
  
  ```bash
  apt install -y libvips
  ```

* CentOS

  ```bash
  dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
  dnf install -y vips vips-tools
  ```

## Notes

* **vips** is much more faster than **ImageMagick**

**Comment by charlesdeb** [comment]
Yeah, I had the same issue just now with ActiveStorage. I worked around it by doing `apt install -y libvips`

**Comment by egemen-github** [comment]
I had a very similar problem when I wanted to view a uploaded picture (using trix) and constantly got this message:

**LoadError in ActiveStorage::Representations::RedirectController#show**
---
**Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory. Could not open library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory**

`sudo apt install imagemagick libvips` fixed the problem.

Thank you for sharing the solution, much appreciated.

**Comment by Roald87** [comment]
After `sudo apt install imagemagick libvips`. I got 

```
Liquid Exception: No such file or directory - vips in /home/../
/var/lib/gems/3.0.0/gems/jekyll_picture_tag-2.0.4/lib/jekyll_picture_tag/parsers/image_backend.rb:17:in ``': No such file or directory - vips (Errno::ENOENT)
```

Then I did `sudo apt install libvips-tools` and now it finally works.
