### ISSUE TITLE
Pysch 4 support with secrets is not available in the latest 6.1.4 release

### ISSUE THREAD

**Issue by CamilleDrapier** [rails/rails#44090]
### Steps to reproduce

- create a new app with rails 6.1.4.4 (`rails create blog`)
- copy `config/database.yml` to `config/secrets.yml`
- insert `puts secrets.adapter` at line 14 of  `config/application.rb`
- run `rails serve` 

### Expected behavior

The server should start

### Actual behavior

The server does not start with the following error:

```
sych::BadAlias: Unknown alias: default
/home/camille/.rvm/gems/ruby-3.1.0/gems/railties-6.1.4.4/lib/rails/secrets.rb:28:in `block in parse'
/home/camille/.rvm/gems/ruby-3.1.0/gems/railties-6.1.4.4/lib/rails/secrets.rb:25:in `each'
/home/camille/.rvm/gems/ruby-3.1.0/gems/railties-6.1.4.4/lib/rails/secrets.rb:25:in `each_with_object'
/home/camille/.rvm/gems/ruby-3.1.0/gems/railties-6.1.4.4/lib/rails/secrets.rb:25:in `parse'
/home/camille/.rvm/gems/ruby-3.1.0/gems/railties-6.1.4.4/lib/rails/application.rb:413:in `secrets'
/home/camille/.rvm/gems/ruby-3.1.0/gems/railties-6.1.4.4/lib/rails/railtie.rb:207:in `public_send'
/home/camille/.rvm/gems/ruby-3.1.0/gems/railties-6.1.4.4/lib/rails/railtie.rb:207:in `method_missing'
/home/camille/xdev/blog2/config/application.rb:14:in `<class:Application>'
/home/camille/xdev/blog2/config/application.rb:11:in `<module:Blog2>'
/home/camille/xdev/blog2/config/application.rb:9:in `<main>'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'
/home/camille/xdev/blog2/Rakefile:4:in `<main>'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/home/camille/.rvm/gems/ruby-3.1.0/gems/railties-6.1.4.4/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/camille/.rvm/gems/ruby-3.1.0/gems/railties-6.1.4.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/camille/.rvm/gems/ruby-3.1.0/gems/railties-6.1.4.4/lib/rails/command.rb:50:in `invoke'
/home/camille/.rvm/gems/ruby-3.1.0/gems/railties-6.1.4.4/lib/rails/commands.rb:18:in `<main>'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/camille/.rvm/gems/ruby-3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/camille/xdev/blog2/bin/rails:5:in `<top (required)>'
/home/camille/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client/rails.rb:30:in `load'
/home/camille/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client/rails.rb:30:in `call'
/home/camille/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client/command.rb:7:in `call'
/home/camille/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client.rb:30:in `run'
/home/camille/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/bin/spring:49:in `<top (required)>'
/home/camille/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `load'
/home/camille/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `<top (required)>'
/home/camille/xdev/blog2/bin/spring:10:in `require'
/home/camille/xdev/blog2/bin/spring:10:in `block in <top (required)>'
<internal:kernel>:90:in `tap'
/home/camille/xdev/blog2/bin/spring:7:in `<top (required)>'
bin/rails:2:in `load'
bin/rails:2:in `<main>'

```

### System configuration
**Rails version**: 6.1.4.4

**Ruby version**: 3.1.0

I see that the fix is in the 6.1-stable (and 7.0-stable) branch: https://github.com/rails/rails/blob/6-1-stable/railties/lib/rails/secrets.rb
The changelog says/implies that this should be available since 6.1.4.0 (https://github.com/rails/rails/blob/6-1-stable/railties/CHANGELOG.md),
The fix is not in the 6.1.4.4 release/code: https://github.com/rails/rails/blob/v6.1.4.4/railties/lib/rails/secrets.rb

So would it be possible to make another release of the 6.1 branches with the fix included, please? I would like to upgrade ruby before upgrading to the next rails :pray: Sorry if this issue is about something that is already fixed and waiting for release :bow: 

Might be related to: https://github.com/rails/rails/issues/43890

**Comment by rafaelfranca** [comment]
I can't promise a new release of 6.1 since it is not supported for bug fixes anymore, but I'll try to do.

**Comment by rafaelfranca** [comment]
I wish that was the only issue with Ruby 3.1, and I'm afraid getting it support 3.1 will be a lot of work that I'm not willing to do, but I'll try to see.

**Comment by rafaelfranca** [comment]
That changelog entry you are seeing is about config_for, not secrets. So indeed that change is not released yet.

**Comment by CamilleDrapier** [comment]
Thank you very much for looking into this. If the way forward (for me) is to first upgrade rails and then upgrade ruby, then I'm perfectly fine with that.

With this issue, I just wanted to point out that the situation with secrets and aliases is currently a bit confusing with rails 6.1 and ruby 3.1, so that if other people are facing the problem they can refer to this. Since there are no other code changes required here (as far as I understand), maybe it is safe/OK to close this?

**Comment by rafaelfranca** [comment]
I'll keep it open since I will maybe work in a release for 6.1, but it is not my priority.

**Comment by byroot** [comment]
The fix is 0ebb7084f494291db64ae458fcec804d72afac91

The recommended workaround is to put `gem "psych", "< 4"` in your `Gemfile`.

**Comment by yahonda** [comment]
Rails 6.1.5 includes this fix https://github.com/rails/rails/commit/aac3edbaff051198defd0bb062e5fff512dd1134 so I think we can close this issue.
