### ISSUE TITLE
Running 'rails console' causes an rdoc LoadError

### ISSUE THREAD

**Issue by lukehayes** [rails/rails#44143]
### Steps to reproduce

cd into project and run `rails console`

### Expected behavior
The rails console should run.

### Actual behavior

Calling rails c in the terminal causes this output:

```
/home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- rdoc (LoadError)
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:88:in `register'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/irb-1.4.1/lib/irb/input-method.rb:17:in `<main>'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/irb-1.4.1/lib/irb/context.rb:14:in `<main>'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/irb-1.4.1/lib/irb.rb:16:in `<main>'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/railties-7.0.1/lib/rails/commands/console/console_command.rb:3:in `<main>'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/railties-7.0.1/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/railties-7.0.1/lib/rails/command/behavior.rb:40:in `each'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/railties-7.0.1/lib/rails/command/behavior.rb:40:in `block in lookup'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/railties-7.0.1/lib/rails/command/behavior.rb:39:in `each'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/railties-7.0.1/lib/rails/command/behavior.rb:39:in `lookup'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/railties-7.0.1/lib/rails/command.rb:73:in `find_by_namespace'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/railties-7.0.1/lib/rails/command.rb:46:in `invoke'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/railties-7.0.1/lib/rails/commands.rb:18:in `<main>'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**:
Rails 7.0.1

**Ruby version**:
Ruby 3.0.3

### Things I've tried
I need to rails console so that I can follow along with the  rails guides website as I want to learn rails. I'm new to ruby/rails so my bug hunting skills won't be that great yet. However, I have tried:

``` gem install rdoc ```
``` gem install bootsnap ```
```reinstalling RubyGems```
```reinstalling Rails```
```reinstalling Ruby```

and I still get this error.

I have installed ruby etc using pacman. I doubt that would mean much but I wanted to add it as I have seen Manjaro users have specific issues.

I will root around and see what I can find.

**Comment by Rik-de-Kort** [comment]
Same here, on ArchLinux (I'm surmising from your using pacman you are on something like Arch or Manjaro).

I noticed that `irb` also wasn't working, so I tried installing `ruby-irb`, which, curiously, does not work on its own. Installing `ruby-rdoc` on top of that makes it work. However, that does not fix the problem for the rails console, either the generic one (`rails console`) or the specific one (`bin/rails console`).
Kernel build is linux 5.15.10.arch1-1 if anyone was wondering. Will have a go at updating, but doubt it'll help.

Additionally I had some issue with the PATH not being updated to include the local gems directory. Probably an Arch package issue, but might want to add it to the guide if you are so inclined.

**Comment by byroot** [comment]
Seems like it's a big in IRB.

They require `rdoc` here: https://github.com/ruby/irb/blob/1c03bd33737e9c69ffa34a86618d69a543795e75/lib/irb/input-method.rb#L17, but it's not declared as a dependency: https://github.com/ruby/irb/blob/1c03bd33737e9c69ffa34a86618d69a543795e75/irb.gemspec#L39

**Comment by byroot** [comment]
Actually, `rdoc` is a default gem, so somehow your ruby install must be a bit broken: https://github.com/ruby/ruby/blob/728304093c4d5ec8be7dd5f1467da4aa362f2d5c/tool/sync_default_gems.rb#L9

However I found a Rdoc issue on a previous similar problem, and they did add some code to handle rdoc not being there: https://github.com/ruby/irb/pull/215, so maybe they'd accept a similar PR for that other call site.

**Comment by erikhu** [comment]
try adding into Gemfile gem "rdoc"

**Comment by rafaelfranca** [comment]
Closing since this issue is not on rails, but on irb, or the ruby installation.

**Comment by CHINOBv** [comment]
> try adding into Gemfile gem "rdoc"

This work's me :)

**Comment by st0012** [comment]
The IRB team is thinking about adding `rdoc` as a dependency to prevent similar issues in the future: https://github.com/ruby/irb/pull/648. Since `IRB` is now a Railties dependency, it means `rdoc` would be Rails' indirect dependency too (currently it's not). Do you think that'll cause any negative impact for Rails apps in production? @rafaelfranca @byroot

**Comment by byroot** [comment]
Just adding the dependency isn't not a huge deal, assuming it's not loaded if you don't use it. It just waste a bit of disk space.
