### ISSUE TITLE
Rails 6, Uncaught Error: Module build failed 

### ISSUE THREAD

**Issue by lanceliumeng** [rails/rails#44172]
### Steps to reproduce
I am very beginner to use ruby on rails to build my first app, here are my steps:
```ruby
rails new blog_app
```
then cd blog_app

```ruby
rails db:create
rails g scaffold Post title:string body:text
rails db:migrate
rails s
```

### Expected behaviour
when I went to the localhost, the destroy should help me to delete the test post if I click it

### Actual behavior
but when I click the destroy button, it doesn't work and I got the browser console error below:

 Uncaught Error: Module build failed (from ./.yarn/__virtual__/babel-loader-virtual-5e1e3f47a6/0/cache/babel-loader-npm-8.2.3-855681b984-78e1e1a919.zip/node_modules/babel-loader/lib/index.js):
Error: Your application tried to access @babel/plugin-syntax-dynamic-import, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: @babel/plugin-syntax-dynamic-import
Required by: /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/

Require stack:
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/files/index.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/index.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/__virtual__/babel-loader-virtual-5e1e3f47a6/0/cache/babel-loader-npm-8.2.3-855681b984-78e1e1a919.zip/node_modules/babel-loader/lib/index.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/loader-runner-npm-2.4.0-c414104c2f-e27eebbca5.zip/node_modules/loader-runner/lib/loadLoader.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/loader-runner-npm-2.4.0-c414104c2f-e27eebbca5.zip/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/__virtual__/webpack-virtual-32ab02fe86/0/cache/webpack-npm-4.46.0-a8158cfa7f-013fa24c00.zip/node_modules/webpack/lib/NormalModule.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/__virtual__/webpack-virtual-32ab02fe86/0/cache/webpack-npm-4.46.0-a8158cfa7f-013fa24c00.zip/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/__virtual__/webpack-virtual-32ab02fe86/0/cache/webpack-npm-4.46.0-a8158cfa7f-013fa24c00.zip/node_modules/webpack/lib/Compiler.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/__virtual__/webpack-virtual-32ab02fe86/0/cache/webpack-npm-4.46.0-a8158cfa7f-013fa24c00.zip/node_modules/webpack/lib/webpack.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/__virtual__/webpack-cli-virtual-1e6a860761/0/cache/webpack-cli-npm-3.3.12-3f0b130bc7-3097084e7b.zip/node_modules/webpack-cli/bin/utils/validate-options.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/__virtual__/webpack-cli-virtual-1e6a860761/0/cache/webpack-cli-npm-3.3.12-3f0b130bc7-3097084e7b.zip/node_modules/webpack-cli/bin/utils/convert-argv.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/__virtual__/webpack-cli-virtual-1e6a860761/0/cache/webpack-cli-npm-3.3.12-3f0b130bc7-3097084e7b.zip/node_modules/webpack-cli/bin/cli.js
- /Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/__virtual__/webpack-virtual-32ab02fe86/0/cache/webpack-npm-4.46.0-a8158cfa7f-013fa24c00.zip/node_modules/webpack/bin/webpack.js
    at Function.external_module_.Module._resolveFilename (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.pnp.cjs:21479:55)
    at resolve (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/v8-compile-cache-npm-2.3.0-961375f150-adb0a271ea.zip/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
    at resolveStandardizedName (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/files/plugins.js:111:7)
    at resolvePlugin (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/files/plugins.js:55:10)
    at loadPlugin (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/files/plugins.js:63:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/config-descriptors.js:187:16)
    at createDescriptor.next (<anonymous>)
    at step (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip/node_modules/gensync/index.js:261:32)
    at evaluateAsync (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip/node_modules/gensync/index.js:291:5)
    at :3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip/node_modules/gensync/index.js:43:15)
    at Function.all (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/config-descriptors.js:142:41)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/config-descriptors.js:138:17)
    at createPluginDescriptors.next (<anonymous>)
    at plugins (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/config-descriptors.js:65:26)
    at plugins.next (<anonymous>)
    at mergeChainOpts (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/config-chain.js:419:34)
    at mergeChainOpts.next (<anonymous>)
    at :3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/config-chain.js:378:14
    at Generator.next (<anonymous>)
    at loadFileChain (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/config-chain.js:232:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/config-chain.js:95:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (:3000/Users/lanceliu/Desktop/Web_Development_Bootcamp/Term_2_overall/week_01_ClassNotes/rails_test/first_test_app/.yarn/cache/@babel-core-npm-7.16.7-268c2eb3fa-3206e077e7.zip/node_modules/@babel/core/lib/config/partial.js:103:62)
    at Object../app/javascript/packs/application.js (bootstrap:83:1)
    at __webpack_require__ (bootstrap:19:1)
    at bootstrap:83:1
    at bootstrap:83:1
./app/javascript/packs/application.js @ bootstrap:83
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83

### Please help me
Sorry for the silly question. My coding skill is minimal at this stage, I tried to google it and there is no similar issue here, I tried to fix the problem for two days 😂😂, really painful... Thank you so much! 

### System configuration
**Computer**:
M1 MacBook pro

**Rails version**:
Rails 6.1.4.4

**Ruby version**:
ruby 3.0.2

**Yarn version**
yarn 3.1.1

**NVM version**
v16.13.2

**Node version**
v16.13.2

**Package.json**
{
  "name": "first-test-app",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "5.4.3",
    "babel-plugin-macros": "^3.1.0",
    "turbolinks": "^5.2.0",
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-dev-server": "^3"
  }
}

**Comment by lanceliumeng** [comment]
problem resolved~, the nightmare error because I migrated my yarn version from 1 to 3 in somehow, so I can use command yarn set version 1.xxxx, then back to stable version, and everything is ok. I will close this issue then.
