### ISSUE TITLE
ActiveStorage proxy with rails api only requiring Flash middleware

### ISSUE THREAD

**Issue by uxxman** [rails/rails#44181]
### Steps to reproduce
When using activestorage proxy model with a rails api only project, the generated proxy urls crashes because they internally rely on Flash middleware which is not needed in an api only project.

Demo Source Code: https://github.com/uxxman/rails_api_activestorage_proxy

Reproduction steps can be easily followed by following commits: https://github.com/uxxman/rails_api_activestorage_proxy/commits/main

```shell
git clone git@github.com:uxxman/rails_api_activestorage_proxy.git
cd rails_api_activestorage_proxy
bundle
rails db:create
rails db:migrate
rails db:seed

rails c
Rails.application.routes.url_helpers.rails_storage_proxy_url(Post.first.image)  # => "http://localhost:3000/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2bbf8adb6c6562438e67001421f572551360c8c6/image.png"
```

Now, with rails server running, if we open the above proxied url, we get

```json
{"status":500,"error":"Internal Server Error","exception":"#\u003cNoMethodError: undefined method `flash' for #\u003cActionDispatch::Request GET \"http://localhost:3000/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2bbf8adb6c6562438e67001421f572551360c8c6/image.png\" for ::1\u003e\u003e","traces":{"Application Trace":[],"Framework Trace":[{"exception_object_id":17580,"id":0,"trace":"actionpack (7.0.1) lib/action_controller/metal/flash.rb:10:in `flash'"},{"exception_object_id":17580,"id":1,"trace":"actionpack (7.0.1) lib/action_controller/metal/etag_with_flash.rb:15:in `block (2 levels) in \u003cmodule:EtagWithFlash\u003e'"},{"exception_object_id":17580,"id":2,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:322:in `instance_exec'"},{"exception_object_id":17580,"id":3,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:322:in `block in combine_etags'"},{"exception_object_id":17580,"id":4,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:322:in `map'"},{"exception_object_id":17580,"id":5,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:322:in `combine_etags'"},{"exception_object_id":17580,"id":6,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:126:in `fresh_when'"},{"exception_object_id":17580,"id":7,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:250:in `stale?'"},{"exception_object_id":17580,"id":8,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:309:in `http_cache_forever'"},{"exception_object_id":17580,"id":9,"trace":"activestorage (7.0.1) app/controllers/active_storage/blobs/proxy_controller.rb:16:in `show'"},{"exception_object_id":17580,"id":10,"trace":"actionpack (7.0.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"},{"exception_object_id":17580,"id":11,"trace":"actionpack (7.0.1) lib/abstract_controller/base.rb:214:in `process_action'"},{"exception_object_id":17580,"id":12,"trace":"actionpack (7.0.1) lib/action_controller/metal/rendering.rb:53:in `process_action'"},{"exception_object_id":17580,"id":13,"trace":"actionpack (7.0.1) lib/abstract_controller/callbacks.rb:234:in `block in process_action'"},{"exception_object_id":17580,"id":14,"trace":"activesupport (7.0.1) lib/active_support/callbacks.rb:118:in `block in run_callbacks'"},{"exception_object_id":17580,"id":15,"trace":"actiontext (7.0.1) lib/action_text/rendering.rb:20:in `with_renderer'"},{"exception_object_id":17580,"id":16,"trace":"actiontext (7.0.1) lib/action_text/engine.rb:69:in `block (4 levels) in \u003cclass:Engine\u003e'"},{"exception_object_id":17580,"id":17,"trace":"activesupport (7.0.1) lib/active_support/callbacks.rb:127:in `instance_exec'"},{"exception_object_id":17580,"id":18,"trace":"activesupport (7.0.1) lib/active_support/callbacks.rb:127:in `block in run_callbacks'"},{"exception_object_id":17580,"id":19,"trace":"activesupport (7.0.1) lib/active_support/callbacks.rb:138:in `run_callbacks'"},{"exception_object_id":17580,"id":20,"trace":"actionpack (7.0.1) lib/abstract_controller/callbacks.rb:233:in `process_action'"},{"exception_object_id":17580,"id":21,"trace":"actionpack (7.0.1) lib/action_controller/metal/rescue.rb:22:in `process_action'"},{"exception_object_id":17580,"id":22,"trace":"actionpack (7.0.1) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'"},{"exception_object_id":17580,"id":23,"trace":"activesupport (7.0.1) lib/active_support/notifications.rb:206:in `block in instrument'"},{"exception_object_id":17580,"id":24,"trace":"activesupport (7.0.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'"},{"exception_object_id":17580,"id":25,"trace":"activesupport (7.0.1) lib/active_support/notifications.rb:206:in `instrument'"},{"exception_object_id":17580,"id":26,"trace":"actionpack (7.0.1) lib/action_controller/metal/instrumentation.rb:66:in `process_action'"},{"exception_object_id":17580,"id":27,"trace":"actionpack (7.0.1) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'"},{"exception_object_id":17580,"id":28,"trace":"activerecord (7.0.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'"},{"exception_object_id":17580,"id":29,"trace":"actionpack (7.0.1) lib/abstract_controller/base.rb:151:in `process'"},{"exception_object_id":17580,"id":30,"trace":"actionview (7.0.1) lib/action_view/rendering.rb:39:in `process'"},{"exception_object_id":17580,"id":31,"trace":"actionpack (7.0.1) lib/action_controller/metal/live.rb:266:in `block (2 levels) in process'"},{"exception_object_id":17580,"id":32,"trace":"activesupport (7.0.1) lib/active_support/concurrency/share_lock.rb:162:in `sharing'"},{"exception_object_id":17580,"id":33,"trace":"activesupport (7.0.1) lib/active_support/dependencies/interlock.rb:37:in `running'"},{"exception_object_id":17580,"id":34,"trace":"actionpack (7.0.1) lib/action_controller/metal/live.rb:258:in `block in process'"},{"exception_object_id":17580,"id":35,"trace":"actionpack (7.0.1) lib/action_controller/metal/live.rb:343:in `block in new_controller_thread'"}],"Full Trace":[{"exception_object_id":17580,"id":0,"trace":"actionpack (7.0.1) lib/action_controller/metal/flash.rb:10:in `flash'"},{"exception_object_id":17580,"id":1,"trace":"actionpack (7.0.1) lib/action_controller/metal/etag_with_flash.rb:15:in `block (2 levels) in \u003cmodule:EtagWithFlash\u003e'"},{"exception_object_id":17580,"id":2,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:322:in `instance_exec'"},{"exception_object_id":17580,"id":3,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:322:in `block in combine_etags'"},{"exception_object_id":17580,"id":4,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:322:in `map'"},{"exception_object_id":17580,"id":5,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:322:in `combine_etags'"},{"exception_object_id":17580,"id":6,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:126:in `fresh_when'"},{"exception_object_id":17580,"id":7,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:250:in `stale?'"},{"exception_object_id":17580,"id":8,"trace":"actionpack (7.0.1) lib/action_controller/metal/conditional_get.rb:309:in `http_cache_forever'"},{"exception_object_id":17580,"id":9,"trace":"activestorage (7.0.1) app/controllers/active_storage/blobs/proxy_controller.rb:16:in `show'"},{"exception_object_id":17580,"id":10,"trace":"actionpack (7.0.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"},{"exception_object_id":17580,"id":11,"trace":"actionpack (7.0.1) lib/abstract_controller/base.rb:214:in `process_action'"},{"exception_object_id":17580,"id":12,"trace":"actionpack (7.0.1) lib/action_controller/metal/rendering.rb:53:in `process_action'"},{"exception_object_id":17580,"id":13,"trace":"actionpack (7.0.1) lib/abstract_controller/callbacks.rb:234:in `block in process_action'"},{"exception_object_id":17580,"id":14,"trace":"activesupport (7.0.1) lib/active_support/callbacks.rb:118:in `block in run_callbacks'"},{"exception_object_id":17580,"id":15,"trace":"actiontext (7.0.1) lib/action_text/rendering.rb:20:in `with_renderer'"},{"exception_object_id":17580,"id":16,"trace":"actiontext (7.0.1) lib/action_text/engine.rb:69:in `block (4 levels) in \u003cclass:Engine\u003e'"},{"exception_object_id":17580,"id":17,"trace":"activesupport (7.0.1) lib/active_support/callbacks.rb:127:in `instance_exec'"},{"exception_object_id":17580,"id":18,"trace":"activesupport (7.0.1) lib/active_support/callbacks.rb:127:in `block in run_callbacks'"},{"exception_object_id":17580,"id":19,"trace":"activesupport (7.0.1) lib/active_support/callbacks.rb:138:in `run_callbacks'"},{"exception_object_id":17580,"id":20,"trace":"actionpack (7.0.1) lib/abstract_controller/callbacks.rb:233:in `process_action'"},{"exception_object_id":17580,"id":21,"trace":"actionpack (7.0.1) lib/action_controller/metal/rescue.rb:22:in `process_action'"},{"exception_object_id":17580,"id":22,"trace":"actionpack (7.0.1) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'"},{"exception_object_id":17580,"id":23,"trace":"activesupport (7.0.1) lib/active_support/notifications.rb:206:in `block in instrument'"},{"exception_object_id":17580,"id":24,"trace":"activesupport (7.0.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'"},{"exception_object_id":17580,"id":25,"trace":"activesupport (7.0.1) lib/active_support/notifications.rb:206:in `instrument'"},{"exception_object_id":17580,"id":26,"trace":"actionpack (7.0.1) lib/action_controller/metal/instrumentation.rb:66:in `process_action'"},{"exception_object_id":17580,"id":27,"trace":"actionpack (7.0.1) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'"},{"exception_object_id":17580,"id":28,"trace":"activerecord (7.0.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'"},{"exception_object_id":17580,"id":29,"trace":"actionpack (7.0.1) lib/abstract_controller/base.rb:151:in `process'"},{"exception_object_id":17580,"id":30,"trace":"actionview (7.0.1) lib/action_view/rendering.rb:39:in `process'"},{"exception_object_id":17580,"id":31,"trace":"actionpack (7.0.1) lib/action_controller/metal/live.rb:266:in `block (2 levels) in process'"},{"exception_object_id":17580,"id":32,"trace":"activesupport (7.0.1) lib/active_support/concurrency/share_lock.rb:162:in `sharing'"},{"exception_object_id":17580,"id":33,"trace":"activesupport (7.0.1) lib/active_support/dependencies/interlock.rb:37:in `running'"},{"exception_object_id":17580,"id":34,"trace":"actionpack (7.0.1) lib/action_controller/metal/live.rb:258:in `block in process'"},{"exception_object_id":17580,"id":35,"trace":"actionpack (7.0.1) lib/action_controller/metal/live.rb:343:in `block in new_controller_thread'"}]}}
```

### Expected behavior
It should not rely on Flash middleware

### Actual behavior
It relies in Flash middleware

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 3.1.0

**Comment by mihaic195** [comment]
I cannot reproduce the issue. Seems to work fine on my end.
Seems to be the case that Flash middleware is skipped in api_only mode: https://github.com/rails/rails/blob/main/railties/lib/rails/application/default_middleware_stack.rb#L73-L74

**Comment by mihaic195** [comment]
Indeed, the issue is there. But I don't think it's a valid bug.
https://guides.rubyonrails.org/api_app.html#other-middleware 

> ### 4.5 Other Middleware
> Rails ships with a number of other middleware that you might want to use in an API application, especially if one of your API clients is the browser:
> 
>  - `Rack::MethodOverride`
> - `ActionDispatch::Cookies`
> - `ActionDispatch::Flash`
> 
> Any of these middleware can be added via:
> 
> `config.middleware.use Rack::MethodOverride`
> 
> ### 4.6 Removing Middleware
> If you don't want to use a middleware that is included by default in the API-only middleware set, you can remove it with:
> 
> `config.middleware.delete ::Rack::Sendfile`
> 
> Keep in mind that removing these middlewares will remove support for certain features in Action Controller.

So in your case, to avoid the Flash middleware, you would add `config.middleware.delete ActionDispatch::Flash` in your `application.rb` and then everything works fine.

**Comment by uxxman** [comment]
> So in your case, to avoid the Flash middleware, you would add `config.middleware.delete ActionDispatch::Flash` in your `application.rb` and then everything works fine.

@mihaic195 actually its the opposite, API_ONLY apps don't have Flash middleware, so doing `config.middleware.use ActionDispatch::Flash` fixes things. I am trying to understand here is why Flash is being used to create a url with long live cache?

**Comment by mihaic195** [comment]
You are right! Flash is being used due to the Etag when accessing the link in the browser and not when the link is created. I believe you need to add Flash in the middlewares in order to avoid this problem.
I've also added a PR, but I don't think it's the right solution, given that some tests regarding ETag freshness are failing.

**Comment by uxxman** [comment]
@mihaic195 thank you for looking into this :) 

I am looking at you PR #44195

```ruby
included do
  if defined?(flash)
    etag { flash unless flash.empty? }
  end
end
```

I think **flash** only exists inside the etag Proc scope and not before that. That's why tests are failing because the if condition is always false, even when flash middleware is there.

Also, there is the following is defined in **ActionController::Flash** module
```ruby
delegate :flash, to: :request
```

So, the patch should be,

```ruby
included do
  etag { flash if request.respond_to?(:flash) && !flash.empty? }
end
```
