### ISSUE TITLE
[rails 7.0.1] rails or rake tasks are failing with error on debian staging server

### ISSUE THREAD

**Issue by salex** [rails/rails#44234]
### Steps to reproduce

I'm in the process of upgrading 3 Rails apps from 6.1.3 to 7.0.1.

The first one I followed the rails app:update process. That took about a week
* created a rails7 branch
* rails app:update then followed guide
* Removed webpacker and added importmap, tailwind gem, turbo etc
* Moved css (converted scss), stimulus controller etc to the right places  (probably took the most time!)
* replace few Rails.ujs stuff with TurboFrame or fetch

Once I was satisfied, I tried to deploy the branch to my staging server and couldn't find a way to get it to work with Capistrano. I bit the bullet and merged the rails7 branch and  deployed  master. 

The second app I took a different approach. I created a new rails 7 app, then basically copied the app directory to the new app, taking into account assets differences. Added my Capistrano stuff and other changes in the config folder. CSS was still a long task

I then tried to deploy to my staging server and had all kinds of problems, assets failed, migrations failed, just about everything. I don't have all the errors but they all point to the same error that I can reproduce by going into a staging Capistrano release file on the debian staging server and trying:

```sh
developer@staging:~/apps/ptgolf7$ cd current
developer@staging:~/apps/ptgolf7/current$ bin/rails -T
/home/developer/.rbenv/versions/3.0.1/lib/ruby/3.0.0/x86_64-linux/continuation.so: warning: callcc is obsolete; use Fiber instead
Debug.rb
Emacs support available.

/home/developer/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/runtime.rb:53:        next unless (dep.groups & groups).any? && dep.should_include?
(rdb:1) exit
/home/developer/.rbenv/versions/3.0.1/lib/ruby/3.0.0/debug.rb:240:in `synchronize': deadlock; recursive locking (ThreadError)
	from /home/developer/.rbenv/versions/3.0.1/lib/ruby/3.0.0/debug.rb:240:in `check_suspend'
	from /home/developer/.rbenv/versions/3.0.1/lib/ruby/3.0.0/debug.rb:838:in `trace_func'
	from /home/developer/.rbenv/versions/3.0.1/lib/ruby/3.0.0/debug.rb:1104:in `block in <class:DEBUGGER__>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
developer@staging:~/apps/ptgolf7/current$ 
```
It would then go into this rdb irb like app, The exit produce this error. This is the same error I'd see in my capistrano log,

### Expected behavior

In the above test, it should of listed the rails or rake tasks

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 3.0.1

**Staging server**

```sh
developer@staging:/etc$ cat os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by pjfitzgibbons** [comment]
Did your OG release branches (rails 6.1.3) use Ruby 3.0 as well?
Wondering if this is an issue w/ Ruby Debug?

**Comment by salex** [comment]
> Did your OG release branches (rails 6.1.3) use Ruby 3.0 as well?
> Wondering if this is an issue w/ Ruby Debug?

No, I was running 2.7.2 or 3.  Thought about dropping back,

I also get a error on my OS X m1 lap top (sometimes!), but it doesn't go into debug.

```
developer@staging:~/apps/myvfw/current$ bin/rails -T
/home/developer/.rbenv/versions/2.7.3/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/developer/apps/myvfw/shared/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/developer/.rbenv/versions/2.7.3/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/developer/apps/myvfw/shared/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/developer/.rbenv/versions/2.7.3/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/developer/apps/myvfw/shared/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
rails about                              # List versions of all Rails frameworks and the environment
```

Now that I look at it, it's referecing another app that I have not touch in weeks

**Comment by salex** [comment]
Sorry, I have never been sure how to reply to an issue email
--

No, I was running 2.7.2 or 3. Thought about dropping back,

I also get a error on my OS X m1 lap top (sometimes!), but it doesn't go into debug.

I posted more details on the issue,

**Comment by salex** [comment]
Just a little update. I'm still stuggling with this problem.

I moved one app to ruby 3.1.0 on one of the apps, but gem prawn has not been updated to that versions deploy failed

Move back to ruby 2.7.3 on tried again. Still get bin/rails -T going into debugger.  Can deploy as long as here is no rake task, although precompile worked.

The first app I deployed was rail 7.0.0 and the bin/rails T works!  Have a feeling if I move to 7.0.1 it will break

Something is broke but not sure what approach to take.

**Comment by rafaelfranca** [comment]
debug should not be present on the production/staging environments. Did you do `--without development` when running `bundle install`?

**Comment by rafaelfranca** [comment]
BTW, the deadlock itself seems to be an issue in the debug gem, so the issue should be reported there. Thank you.

**Comment by salex** [comment]
> debug should not be present on the production/staging environments. Did you do `--without development` when running `bundle install`?

I figured 

```ruby
group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem 
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end
```

Would take care of it.  
Since Capistrano does the bundle call on deployment, I just took out the debug gem. It didn't fail on the test `bin/rails -T`

I will post issue on the debug gem. 

Thank for you taking a look at it.

**Comment by rafaelfranca** [comment]
Yeah, that should do it, but maybe capistrano is not passing the options to bundler?
