### ISSUE TITLE
deadlock in activesupport 7.0.1 (ruby 3.1.0)

### ISSUE THREAD

**Issue by mildred** [rails/rails#44263]
After upgrading to rails 7 I occasionally get deadlocks. I enabled puma control server and could get the thread stack traces, and it seems that the theads are all waiting on a lock to be available

The following is the backtraces of the rails process obtained using puma control status server: [thread-backtraces.txt](https://github.com/rails/rails/files/7943135/thread-backtraces.txt)

The blocking thread seems to be **Thread: TID-2omw puma server threadpool 009**:

```
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:108:in `sleep'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:108:in `wait'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:108:in `wait_for_cond'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:108:in `wait'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:116:in `wait_while'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/share_lock.rb:220:in `wait_for'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/share_lock.rb:190:in `block in yield_shares'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:202:in `mon_synchronize'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/share_lock.rb:189:in `yield_shares'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:18:in `block in query'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:17:in `query'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:99:in `query_values'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:35:in `data_sources'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/schema_cache.rb:199:in `tables_to_cache'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/schema_cache.rb:236:in `prepare_data_sources'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/schema_cache.rb:90:in `data_source_exists?'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/model_schema.rb:395:in `table_exists?'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/core.rb:406:in `inspect'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/rack-2.2.3/lib/rack/lint.rb:81:in `inspect'",
```

There is also **Thread: TID-2oo0 puma server threadpool 008** which holds a shared lock:

```
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:17:in `enter'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:17:in `block in mon_enter'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:17:in `mon_enter'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:22:in `block in synchronize'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkin'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:304:in `block (3 levels) in clear_reloadable_connections'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:301:in `each'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:301:in `block (2 levels) in clear_reloadable_connections'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:202:in `mon_synchronize'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:300:in `block in clear_reloadable_connections'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `block in with_exclusively_acquired_all_connections'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:598:in `with_new_connections_blocked'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `with_exclusively_acquired_all_connections'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:299:in `clear_reloadable_connections'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:323:in `clear_reloadable_connections!'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/connection_handler.rb:176:in `each'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/connection_handler.rb:176:in `clear_reloadable_connections!'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_handling.rb:337:in `clear_reloadable_connections!'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/railtie.rb:295:in `block (3 levels) in <class:Railtie>'",
```

and **Thread: TID-2nb4 puma server threadpool 003** with the same shared lock:

```
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:108:in `sleep'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:108:in `wait'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:108:in `wait_for_cond'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:108:in `wait'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:116:in `wait_while'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/share_lock.rb:220:in `wait_for'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/share_lock.rb:190:in `block in yield_shares'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'",
      "/usr/local/rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/monitor.rb:202:in `mon_synchronize'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/share_lock.rb:189:in `yield_shares'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:18:in `block in query'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activesupport-7.0.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:17:in `query'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:99:in `query_values'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:35:in `data_sources'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/schema_cache.rb:199:in `tables_to_cache'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/schema_cache.rb:236:in `prepare_data_sources'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/connection_adapters/schema_cache.rb:90:in `data_source_exists?'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/model_schema.rb:395:in `table_exists?'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/activerecord-7.0.1/lib/active_record/core.rb:406:in `inspect'",
      "/usr/local/rvm/gems/ruby-3.1.0@lcas/gems/rack-2.2.3/lib/rack/lint.rb:81:in `inspect'",
```

I also experience occasional synchronizing issues with zeitwerk reported in https://github.com/fxn/zeitwerk/issues/207

**Comment by mildred** [comment]
Might be relared to #34310 but I'm not sure that's the same issue. I couldn't debug it that far.

**Comment by mildred** [comment]
Attempts to use `ActionDispatch::DebugLocks` fails because the request to `/rails/locks` is blocked by the lock involved in the deadlock even though the server pool still has available slots.

**Comment by mildred** [comment]
The deadlock happens after the block in `permit_concurrent_loads` has beed executed, in the ensure block in share_lock.rb (yield_shares method). it waits indefinitely for `@exclusive_thread`.

**Comment by matthewd** [comment]
> Attempts to use `ActionDispatch::DebugLocks` fails because the request to `/rails/locks` is blocked by the lock involved in the deadlock even though the server pool still has available slots.

Just to start here: this sounds like a configuration issue. This is the situation that DebugLocks is intended to help you debug, and it's thus expected to work even when the loading locks are blocked. Do you have an unusual middleware stack configuration, such that inserting it at the documented position would still leave it subject to locking?

**Comment by mildred** [comment]
I don't have such an unusual configuration. i have a few gems that can hok in there such as better_errors, pry or rack-mini-profiler. I use devise for authentication. However, it might be related with a rails endpoint which uses redis a lot, and has blocking connections to it.

If you think this comes from my configuration, let's close this issue and I'll investigate on my side. However, Iḿ having difficulties to test this because of another bug with zeitwerk: #44264 (`RuntimeError: can't add a new key into hash during iteration` triggered within zeitwerk)

**Comment by matthewd** [comment]
I'm mostly just confused because, as long as you insert the debug middleware in the correct documented location in your middleware stack, it appears before anything that could attempt to hold a lock -- unless you've completely exhausted your available puma threads, it should give you a response. (And in turn, should be in the best position to help understand the actual locking issue -- those backtraces contain some information, but e.g. don't describe which threads are waiting for which others.)

Perhaps try inserting it even higher in the list? By design it has basically zero dependencies.
