### ISSUE TITLE
Non-nullable field with default value raises ActiveRecord::Encryption::Errors::Decryption when absent

### ISSUE THREAD

**Issue by airled** [rails/rails#44314]
### Steps to reproduce
Migration:
```ruby
class CreateAccounts < ActiveRecord::Migration[7.0]
  def change
    create_table :accounts do |t|
      t.text :email, null: false, default: ''
      t.timestamps
    end
  end
end
``` 
Model:
```ruby
class Account < ApplicationRecord
  encrypts :email, deterministic: true, downcase: true
end
```
### Expected behavior
I expect that `Account.create!()` creates a new account and email field has either encrypted empty string or just empty string.

### Actual behavior
```
irb(main):002:0> Account.create!()
/home/air/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activerecord-7.0.1/lib/active_record/encryption/encryptor.rb:58:in `rescue in decrypt': ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption)
/home/air/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activerecord-7.0.1/lib/active_record/encryption/message_serializer.rb:26:in `rescue in load': ActiveRecord::Encryption::Errors::Encoding (ActiveRecord::Encryption::Errors::Encoding)
/home/air/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/json/common.rb:216:in `parse': 859: unexpected token at '' (JSON::ParserError)
/home/air/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activerecord-7.0.1/lib/active_record/encryption/encryptor.rb:58:in `rescue in decrypt': ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption)
/home/air/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activerecord-7.0.1/lib/active_record/encryption/message_serializer.rb:26:in `rescue in load': ActiveRecord::Encryption::Errors::Encoding (ActiveRecord::Encryption::Errors::Encoding)
/home/air/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/json/common.rb:216:in `parse': 859: unexpected token at '' (JSON::ParserError)
irb(main):003:0>
```
If I remove `null: false, default: ''` in the migration file it works ok.

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 3.1.0

**Comment by airled** [comment]
Seems related to #43664

**Comment by sajjadmurtaza** [comment]
I can confirm, the same thing is happening with my setup.
