### ISSUE TITLE
$rails new name - native gem Makefile failures 

### ISSUE THREAD

**Issue by bjpcjp** [rails/rails#44327]
### Steps to reproduce

$rails new demo

### Expected behavior

normal rails app creation

### Actual behavior

```
Installing io-wait 0.2.1 with native extensions
Installing digest 3.1.0 with native extensions
Installing msgpack 1.4.4 with native extensions
Installing puma 5.6.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/digest-3.1.0/ext/digest/bubblebabble
/home/bjpcjp/.rbenv/versions/3.0.2/bin/ruby -I
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0 -r
./siteconf20220203-11695-wkgcb5.rb extconf.rb
creating Makefile

current directory:
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/digest-3.1.0/ext/digest/bubblebabble
make DESTDIR\= clean

current directory:
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/digest-3.1.0/ext/digest/bubblebabble
make DESTDIR\=
compiling bubblebabble.c
make: /home/bjpcjp/miniconda3/envs/working/bin/x86_64-conda-linux-gnu-cc: No
such file or directory
make: *** [Makefile:245: bubblebabble.o] Error 127

make failed, exit code 2

Gem files will remain installed in
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/digest-3.1.0 for
inspection.
Results logged to
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/digest-3.1.0/gem_make.out

An error occurred while installing digest (3.1.0), and Bundler cannot
continue.
Make sure that `gem install digest -v '3.1.0' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  rails was resolved to 7.0.1, which depends on
    actionmailbox was resolved to 7.0.1, which depends on
      net-imap was resolved to 0.2.3, which depends on
        digest


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/io-wait-0.2.1/ext/io/wait
/home/bjpcjp/.rbenv/versions/3.0.2/bin/ruby -I
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0 -r
./siteconf20220203-11695-2teed3.rb extconf.rb
checking for rb_io_wait()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/bjpcjp/.rbenv/versions/3.0.2/bin/$(RUBY_BASE_NAME)
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:471:in `try_do': The
compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:564:in
`try_link0'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:582:in
`try_link'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:794:in
`try_func'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:1083:in `block
in have_func'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:971:in `block in
checking_for'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:361:in `block (2
levels) in postpone'
	from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:331:in `open'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:361:in `block in
postpone'
	from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:331:in `open'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:357:in
`postpone'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:970:in
`checking_for'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:1082:in
`have_func'
	from extconf.rb:5:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/io-wait-0.2.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/io-wait-0.2.1 for
inspection.
Results logged to
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/io-wait-0.2.1/gem_make.out

An error occurred while installing io-wait (0.2.1), and Bundler cannot
continue.
Make sure that `gem install io-wait -v '0.2.1' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  rails was resolved to 7.0.1, which depends on
    actionmailbox was resolved to 7.0.1, which depends on
      net-imap was resolved to 0.2.3, which depends on
        net-protocol was resolved to 0.1.2, which depends on
          io-wait


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/strscan-3.0.1/ext/strscan
/home/bjpcjp/.rbenv/versions/3.0.2/bin/ruby -I
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0 -r
./siteconf20220203-11695-ke9gly.rb extconf.rb
checking for onig_region_memsize() in ruby.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/bjpcjp/.rbenv/versions/3.0.2/bin/$(RUBY_BASE_NAME)
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:471:in `try_do': The
compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:564:in `try_link0'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:582:in `try_link'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:794:in `try_func'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:1083:in `block in have_func'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:971:in `block in checking_for'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:361:in `block (2 levels) in postpone' 	from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:331:in `open'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:361:in `block in postpone'
	from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:331:in `open'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:357:in `postpone'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:970:in `checking_for'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:1082:in `have_func' 	from extconf.rb:4:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/strscan-3.0.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/strscan-3.0.1 for inspection.
Results logged to /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/strscan-3.0.1/gem_make.out

An error occurred while installing strscan (3.0.1), and Bundler cannot continue.
Make sure that `gem install strscan -v '3.0.1' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  rails was resolved to 7.0.1, which depends on
    actionmailbox was resolved to 7.0.1, which depends on
      net-imap was resolved to 0.2.3, which depends on
        strscan


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/io-console-0.5.11/ext/io/console
/home/bjpcjp/.rbenv/versions/3.0.2/bin/ruby -I
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0 -r
./siteconf20220203-11695-z70lvt.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/bjpcjp/.rbenv/versions/3.0.2/bin/$(RUBY_BASE_NAME)
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:471:in `try_do': The
compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:597:in `block in try_compile'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:546:in `with_werror'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:597:in `try_compile'
from /home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/mkmf.rb:864:in `macro_defined?'
	from extconf.rb:7:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/io-console-0.5.11/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/io-console-0.5.11
for inspection.
Results logged to
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/io-console-0.5.11/gem_make.out

An error occurred while installing io-console (0.5.11), and Bundler cannot continue.
Make sure that `gem install io-console -v '0.5.11' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  debug was resolved to 1.4.0, which depends on
    irb was resolved to 1.4.1, which depends on
      reline was resolved to 0.3.1, which depends on
        io-console
         run  bundle binstubs bundler
Resolving dependencies...
       rails  importmap:install
/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/3.0.0/x86_64-linux/continuation.so: warning: callcc is obsolete; use Fiber instead
Debug.rb
Emacs support available.

/home/bjpcjp/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:103:        hash = long.hash
(rdb:1) 
````
### System configuration

$rbenv local 3.0.2
$rails -v ==> 7.0.1

**Comment by nickpellant** [comment]
Hi @bjpcjp. 👋 

The issue you're reporting isn't a Rails bug. Instead, the problem you're seeing is because the `rails new` command runs `bundle install` as part of its workflow. Unfortunately for you, when it does this, it fails to install some gems due to native extensions failing to compile.

I recommend opening an issue on StackOverflow; the folks there may be able to provide you with further support if you need it.

**Comment by byroot** [comment]
Given that several totally unrelated native extensions fail to compile, you are likely missing some important development tools. If you are on Debian or Ubuntu make sure to install `build-essential`, or it's equivalent on whatever distro you use.

If it's still doesn't work, you'll have to look at the `mkmf.log` files that are pointed in the output, and try to figure which command is missing.

**Comment by bjpcjp** [comment]
I confirmed build-essential is up to date, and didn't see any smoking guns in mkmf.log.

Will submit a ticket to Bundler next. Thanks.

**Comment by byroot** [comment]
It's really unlikely to be bundler, and you're likely to get the same response there.

```
 The
compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
```

Clearly show there's something missing on our system, and given that the output show several different extensions couldn't compile it's likely something important.

What does your mkmf.log look like?

**Comment by bjpcjp** [comment]
Oh, THAT's interesting. (I overlooked the (now-nonexistent) miniconda3
paths appearing in mkmf.log):

I've had problems before with miniconda. Deleted the directory, removed all
references to it in my .bashrc, then rebooted. Same error. Here's the
mkmf.log prior to rebooting.

"/home/bjpcjp/miniconda3/envs/working/bin/x86_64-conda-linux-gnu-cc -o
conftest
-I/home/bjpcjp/.rbenv/versions/3.0.2/include/ruby-3.0.0/x86_64-linux
-I/home/bjpcjp/.rbenv/versions/3.0.2/include/ruby-3.0.0/ruby/backward
-I/home/bjpcjp/.rbenv/versions/3.0.2/include/ruby-3.0.0 -I.
-I/home/bjpcjp/.rbenv/versions/3.0.2/include -DNDEBUG -D_FORTIFY_SOURCE=2
-O2 -isystem /home/bjpcjp/miniconda3/envs/working/include   -march=nocona
-mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2
-ffunction-sections -pipe -isystem
/home/bjpcjp/miniconda3/envs/working/include  -fPIC conftest.c  -L.
-L/home/bjpcjp/.rbenv/versions/3.0.2/lib
-Wl,-rpath,/home/bjpcjp/.rbenv/versions/3.0.2/lib -L.
-L/home/bjpcjp/.rbenv/versions/3.0.2/lib -Wl,-O2 -Wl,--sort-common
-Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags
-Wl,--gc-sections -Wl,-rpath,/home/bjpcjp/miniconda3/envs/working/lib
-Wl,-rpath-link,/home/bjpcjp/miniconda3/envs/working/lib
-L/home/bjpcjp/miniconda3/envs/working/lib -fstack-protector-strong
-rdynamic -Wl,-export-dynamic
-Wl,-rpath,/home/bjpcjp/.rbenv/versions/3.0.2/lib
-L/home/bjpcjp/.rbenv/versions/3.0.2/lib -lruby  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
