### ISSUE TITLE
Unable to require `active_record/base` separately from `active_record`

### ISSUE THREAD

**Issue by postmodern** [rails/rails#44336]
It should be possible to require `active_record/base`, and any files it may need, separately from requiring all of `active_record`.

### Steps to reproduce

1. Create the `Gemfile`

    ```ruby
    source 'https://rubygems.org/'
    gem 'activerecord', '7.0.1'
    ```
2. `bundle install`
3. `ruby -r bundler/setup -r active_record/base -e 'p ActiveRecord::Base'`

### Test Case

```ruby
assert_nothing_raised do
  require 'active_record/base'
end
```

### Expected behavior

Requires `active_record/base` and any other files `ActiveRecord::Base` may need.

### Actual behavior

```
/home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)

        IsolatedExecutionState[:xml_mini_backend]
        ^^^^^^^^^^^^^^^^^^^^^^
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:103:in `backend='
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:11:in `<top (required)>'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `require'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/duration.rb:3:in `require'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/duration.rb:3:in `<top (required)>'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/time/calculations.rb:3:in `require'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/time.rb:4:in `require'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/time.rb:4:in `<top (required)>'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/time.rb:12:in `require'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.1/lib/active_support/time.rb:12:in `<top (required)>'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.1/lib/active_record/base.rb:6:in `require'
	from /home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.1/lib/active_record/base.rb:6:in `<top (required)>'
	from -e:in `require'
```

### System configuration

* activerecord 7.0.1
* ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]

This error is reproducible on all ruby versions, ruby 3.1.0 just had the nicer error message.

**Comment by matthewd** [comment]
To avoid maintaining a deeply complex web of boilerplate requirements, and/or circular dependency issues, project convention is that the top-level requires are presumed, and thus must be loaded first.

So, before requiring an arbitrary `active_support/foo/bar`, one must first require `active_support` -- and so on for the other gems.

(In the case of `active_record` [it's mostly just a list of autoloads](https://github.com/rails/rails/blob/91f80a899f448b44e79937ae6972bd0f46b280d9/activerecord/lib/active_record.rb).)

**Comment by postmodern** [comment]
Note, this bug is also effecting [yard-activerecord](https://github.com/theodorton/yard-activerecord#readme).

When running `rake yard` with `--plugin yard-activerecord` added to `.yardopts`, I get the same error coming from `activerecord`:

```
[error]: Invalid configuration file, using default options.
[error]: NameError: uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState
[error]: Stack trace:
	/data/home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:184:in `current_thread_backend'
	/data/home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:103:in `backend='
	/data/home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
	/data/home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:11:in `<top (required)>'
	/data/home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `require'
	/data/home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
```
