### ISSUE TITLE
`require "bigdecimal"` is missing

### ISSUE THREAD

**Issue by pvalena** [rails/rails#44399]
### Steps to reproduce

When running ActiveJob tests with Ruby 3.1 while building it for Fedora I've hit (100% of the time) - require 'bigdecimal' needed.

### Actual behavior

```
+ ruby -Ilib:test -e 'Dir.glob "./test/cases/**/*_test.rb", &method(:require)'
Using async
/builddir/build/BUILD/activejob-7.0.2/usr/share/gems/gems/activejob-7.0.2/lib/active_job/arguments.rb:49:in `<module:Arguments>': uninitialized constant ActiveJob::Arguments::BigDecimal (NameError)
      PERMITTED_TYPES = [ NilClass, String, Integer, Float, BigDecimal, TrueClass, FalseClass ]
                                                            ^^^^^^^^^^
	from /builddir/build/BUILD/activejob-7.0.2/usr/share/gems/gems/activejob-7.0.2/lib/active_job/arguments.rb:27:in `<module:ActiveJob>'
	from /builddir/build/BUILD/activejob-7.0.2/usr/share/gems/gems/activejob-7.0.2/lib/active_job/arguments.rb:5:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /builddir/build/BUILD/activejob-7.0.2/usr/share/gems/gems/activejob-7.0.2/lib/active_job/enqueuing.rb:3:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /builddir/build/BUILD/activejob-7.0.2/usr/share/gems/gems/activejob-7.0.2/lib/active_job/base.rb:7:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /builddir/build/BUILD/activejob-7.0.2/usr/share/gems/gems/activejob-7.0.2/test/helper.rb:14:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /builddir/build/BUILD/activejob-7.0.2/usr/share/gems/gems/activejob-7.0.2/test/cases/adapter_test.rb:3:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:dir>:220:in `glob'
	from -e:1:in `<main>'
```

I'm not sure what causes this issue - it occurs in the production build system only, which has almost the same dependencies as the development one, which works fine.

### System configuration
**Rails version**:
7.0.2

**Ruby version**:
3.1

**Comment by SkipKayhil** [comment]
How are you installing ruby? If you are getting it through Fedora package manager, they could be missing BigDecimal. There have been similar issues raised before for other package managers: #44143, #42373

**Comment by pvalena** [comment]
Same with actionmailer:
```
+ ruby -Ilib:test -e 'Dir.glob "./test/**/*_test.rb", &method(:require)'
/usr/share/gems/gems/activejob-7.0.2/lib/active_job/arguments.rb:49:in `<module:Arguments>': uninitialized constant ActiveJob::Arguments::BigDecimal (NameError)
      PERMITTED_TYPES = [ NilClass, String, Integer, Float, BigDecimal, TrueClass, FalseClass ]
                                                            ^^^^^^^^^^
	from /usr/share/gems/gems/activejob-7.0.2/lib/active_job/arguments.rb:27:in `<module:ActiveJob>'
	from /usr/share/gems/gems/activejob-7.0.2/lib/active_job/arguments.rb:5:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/share/gems/gems/activejob-7.0.2/lib/active_job/enqueuing.rb:3:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/share/gems/gems/activejob-7.0.2/lib/active_job/base.rb:7:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/share/gems/gems/activejob-7.0.2/lib/active_job/test_helper.rb:37:in `<module:TestHelper>'
	from /usr/share/gems/gems/activejob-7.0.2/lib/active_job/test_helper.rb:8:in `<module:ActiveJob>'
	from /usr/share/gems/gems/activejob-7.0.2/lib/active_job/test_helper.rb:6:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /builddir/build/BUILD/actionmailer-7.0.2/usr/share/gems/gems/actionmailer-7.0.2/lib/action_mailer/test_helper.rb:9:in `<module:TestHelper>'
	from /builddir/build/BUILD/actionmailer-7.0.2/usr/share/gems/gems/actionmailer-7.0.2/lib/action_mailer/test_helper.rb:8:in `<module:ActionMailer>'
	from /builddir/build/BUILD/actionmailer-7.0.2/usr/share/gems/gems/actionmailer-7.0.2/lib/action_mailer/test_helper.rb:5:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /builddir/build/BUILD/actionmailer-7.0.2/usr/share/gems/gems/actionmailer-7.0.2/lib/action_mailer/test_case.rb:36:in `<module:Behavior>'
	from /builddir/build/BUILD/actionmailer-7.0.2/usr/share/gems/gems/actionmailer-7.0.2/lib/action_mailer/test_case.rb:32:in `<class:TestCase>'
	from /builddir/build/BUILD/actionmailer-7.0.2/usr/share/gems/gems/actionmailer-7.0.2/lib/action_mailer/test_case.rb:15:in `<module:ActionMailer>'
	from /builddir/build/BUILD/actionmailer-7.0.2/usr/share/gems/gems/actionmailer-7.0.2/lib/action_mailer/test_case.rb:6:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /builddir/build/BUILD/actionmailer-7.0.2/usr/share/gems/gems/actionmailer-7.0.2/test/abstract_unit.rb:21:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /builddir/build/BUILD/actionmailer-7.0.2/usr/share/gems/gems/actionmailer-7.0.2/test/assert_select_email_test.rb:3:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:dir>:220:in `glob'
	from -e:1:in `<main>'
```

**Comment by pvalena** [comment]
> How are you installing ruby? If you are getting it through Fedora package manager, they could be missing BigDecimal. There have been similar issues raised before for other package managers: #44143, #42373

Please note that simply adding `require 'bigdecimal'` or `ruby -rbigdecimal ...` solves this issue. Another issue might be that we're actually not using Bundler for running the test suite (...all dependencies are resolved + installed by the OS, you see). AFAIK, this did not happen with 7.0.1 (Ruby might've changed in the meantime as well, though).
Yes, we're packaging Ruby as well - this actually happens when running tests, while building the Rails RubyGem packages for Fedora (the point is to integrate+test this together on the OS). So it might be integration/installation issue. I'm unfamiliar with lastest changes, though. @voxik, has something changed with latest Ruby which could cause this?

**Comment by pvalena** [comment]
Thanks for taking the time to respond!

**Comment by SkipKayhil** [comment]
> Please note that simply adding `require 'bigdecimal'` or `ruby -rbigdecimal ...` solves this issue. 

Hmm, yeah this makes me think it's unlikely to be packaging related. I'll look into changes between 7.0.1 and 7.0.2 and see if anything jumps out at me

**Comment by voxik** [comment]
Just grepping through ActiveJob:

~~~
$ grep -R BigDecimal
test/cases/argument_serialization_test.rb:    "a", true, false, BigDecimal(5),
lib/active_job/arguments.rb:  # BigDecimal, Symbol, Date, Time, DateTime, ActiveSupport::TimeWithZone,
lib/active_job/arguments.rb:      PERMITTED_TYPES = [ NilClass, String, Integer, Float, BigDecimal, TrueClass, FalseClass ]
lib/active_job/enqueuing.rb:      # Integer, Float, NilClass, TrueClass, FalseClass, BigDecimal, Symbol, Date,

$ grep -R bigdecimal
~~~

The BigDecimal is not required neither defined. Relying on anything else to provide the constant is a bit fishy to me. But I am quite sure that using Bundler to execute the test suit or not would make difference.

**Comment by voxik** [comment]
Also, I'd say that something like:

~~~
class BigDecimal; end
~~~

could be enough for the purpose.

**Comment by byroot** [comment]
Thank you, I fixed it on `main` and backported to `7-0-stable`.
