### ISSUE TITLE
Tests related do #40226 fail.

### ISSUE THREAD

**Issue by pvalena** [rails/rails#44395]
### Steps to reproduce
Hello,

when creating an update for Fedora, the following 4 tests fail. 

Probably related to #40226.

### Actual behavior

```
Error:
ActiveStorage::VariantTest#test_optimized_variation_of_GIF_blob:
Vips::Error: VipsForeignSave: "/tmp/image_processing20220210-1778-cjj2xp.gif" is not a known file format
VipsForeignSave: "/tmp/image_processing20220210-1778-cjj2xp.gif" is not a known file format

    /usr/share/gems/gems/ruby-vips-2.1.4/lib/vips/image.rb:590:in `write_to_file'
    /usr/share/gems/gems/image_processing-1.12.1/lib/image_processing/vips.rb:63:in `save_image'
    /usr/share/gems/gems/image_processing-1.12.1/lib/image_processing/processor.rb:23:in `call'
    /usr/share/gems/gems/image_processing-1.12.1/lib/image_processing/pipeline.rb:50:in `call_processor'
    /usr/share/gems/gems/image_processing-1.12.1/lib/image_processing/pipeline.rb:28:in `block in call'
    /usr/share/gems/gems/image_processing-1.12.1/lib/image_processing/pipeline.rb:64:in `create_tempfile'
    /usr/share/gems/gems/image_processing-1.12.1/lib/image_processing/pipeline.rb:27:in `call'
    /usr/share/gems/gems/image_processing-1.12.1/lib/image_processing/builder.rb:14:in `block in call!'
    /usr/share/gems/gems/image_processing-1.12.1/lib/image_processing/builder.rb:21:in `instrument'
    /usr/share/gems/gems/image_processing-1.12.1/lib/image_processing/builder.rb:13:in `call!'
    /usr/share/gems/gems/image_processing-1.12.1/lib/image_processing/chainable.rb:58:in `call'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/lib/active_storage/transformers/image_processing_transformer.rb:22:in `process'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/lib/active_storage/transformers/transformer.rb:22:in `transform'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/app/models/active_storage/variation.rb:56:in `block in transform'
    /usr/share/gems/gems/activesupport-7.0.2/lib/active_support/notifications.rb:208:in `instrument'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/app/models/active_storage/variation.rb:55:in `transform'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/app/models/active_storage/variant.rb:110:in `block in process'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/lib/active_storage/downloader.rb:15:in `block in open'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/lib/active_storage/downloader.rb:24:in `open_tempfile'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/lib/active_storage/downloader.rb:12:in `open'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/lib/active_storage/service.rb:90:in `open'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/app/models/active_storage/blob.rb:301:in `open'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/app/models/active_storage/variant.rb:109:in `process'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/app/models/active_storage/variant.rb:64:in `processed'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/test/models/variant_test.rb:122:in `block (3 levels) in <class:VariantTest>'
    /usr/share/gems/gems/activesupport-7.0.2/lib/active_support/testing/assertions.rb:34:in assert_nothing_raised'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/test/models/variant_test.rb:121:in `block (2 levels) in <class:VariantTest>'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/test/models/variant_test.rb:218:in `process_variants_with'
    /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/test/models/variant_test.rb:120:in `block in <class:VariantTest>'

rails test /builddir/build/BUILD/activestorage-7.0.2/usr/share/gems/gems/activestorage-7.0.2/test/models/variant_test.rb:117
```
Same failures also for BMP, ICO and PSD.

I've also filed https://github.com/janko/image_processing/issues/98, but I'm not sure it's related in any way.

### System configuration
**Rails version**:
7.0.2

**Ruby version**:
3.1

**Comment by gmcgibbon** [comment]
Please clarify how you are encountering this error and what you are expecting to happen here. I assume you are expecting the test to pass? The test passes for me locally, and on our CI.

Active Storage uses `image_processing` and `ruby-vips` respectively for variant processing. Based on the stacktrace and error class, it looks like the issue is coming from one of those gems.

**Comment by pvalena** [comment]
> Please clarify how you are encountering this error and what you are expecting to happen here. I assume you are expecting the test to pass? The test passes for me locally, and on our CI.

Correct, we prefer if the tests succeed. :)
Yes, this might be dependent on the test environment (we don't use Bundler as we test the dependencies packaged for the OS).

> 
> Active Storage uses `image_processing` and `ruby-vips` respectively for variant processing. Based on the stacktrace and error class, it looks like the issue is coming from one of those gems.

Agreed. We also might use incompatible versions. Thanks for checking!

**Comment by voxik** [comment]
If somebody ever wondered, this needs `vips-magick` on Fedora
