### ISSUE TITLE
AttrEncrypted::Adapters::ActiveRecord not working

### ISSUE THREAD

**Issue by celsoMartins** [rails/rails#44425]
### Steps to reproduce
- Update rails to rails 7
- run ```rails app:update```
- run ```bin/rails db:environment:set RAILS_ENV=test --trace```

```ruby
# Your reproduction script goes here
```

### Expected behavior
Environment set in the schema.rb

### Actual behavior
```** Invoke db:environment:set (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:environment:set
rails aborted!
NoMethodError: undefined method `key?' for false:FalseClass

              send method, new_attributes.reject { |k, _|  self.class.encrypted_attributes?.key?(k.to_sym) }, *args
                                                                                           ^^^^^
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:28:in `block in perform_attribute_assignment'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:28:in `reject'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:28:in `perform_attribute_assignment'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:36:in `assign_attributes'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/activerecord-7.0.2.2/lib/active_record/core.rb:468:in `initialize'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/activerecord-7.0.2.2/lib/active_record/inheritance.rb:75:in `new'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/activerecord-7.0.2.2/lib/active_record/inheritance.rb:75:in `new'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/activerecord-7.0.2.2/lib/active_record/relation.rb:861:in `_new'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/activerecord-7.0.2.2/lib/active_record/relation.rb:71:in `block in new'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/activerecord-7.0.2.2/lib/active_record/relation.rb:880:in `_scoping'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/activerecord-7.0.2.2/lib/active_record/relation.rb:428:in `scoping'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/activerecord-7.0.2.2/lib/active_record/relation.rb:71:in `new'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/activerecord-7.0.2.2/lib/active_record/relation.rb:227:in `find_or_initialize_by'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/activerecord-7.0.2.2/lib/active_record/querying.rb:22:in `find_or_initialize_by'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/activerecord-7.0.2.2/lib/active_record/internal_metadata.rb:31:in `[]='
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/activerecord-7.0.2.2/lib/active_record/railties/databases.rake:14:in `block (2 levels) in <top (required)>'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/railties-7.0.2.2/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/railties-7.0.2.2/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/celsomartins/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/railties-7.0.2.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/railties-7.0.2.2/lib/rails/command.rb:51:in `invoke'
/Users/celsomartins/.rvm/gems/ruby-3.1.0@flow_climate/gems/railties-7.0.2.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:environment:set
```

### System configuration
**Rails version**: rails (7.0.2.2)

**Ruby version**: ruby-3.1.0

Comments on issue:

When I added a null check to the line, the task worked:

```send method, new_attributes.reject { |k, _|  self.class.encrypted_attributes&.key?(k.to_sym) }, *args```

When I inspected the ```self.class``` the result was ```ActiveRecord::InternalMetadata```

I already removed all encryptations in my code and the issue remains.

Thanks in advance.

**Comment by celsoMartins** [comment]
I removed the gem ```attr_encrypted``` and it worked.

It may be important for future references.

Thanks.
