### ISSUE TITLE
`rails new rails_app` command fails in Rails v5.2.6.2

### ISSUE THREAD

**Issue by AndyObtiva** [rails/rails#44443]
### Steps to reproduce

Run the following in a clean Ruby v3.0.2 environment (e.g. a new [RVM gemset](https://rvm.io/gemsets/basics)):
```
gem install rails -v5.2.6.2
rails new rails_app
```

### Expected behavior

It should just work as expected by generating a new Rails 5 application.

### Actual behavior

The `rails new rails_app` command fails with an error:

```
rails new rails_app         
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /Users/andymaleh/code/rails_app/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/javascripts/application.js
      create  app/assets/javascripts/cable.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/assets/javascripts/channels
      create  app/assets/javascripts/channels/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/update
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_5_2.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
/Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/activesupport-5.2.6.2/lib/active_support/messages/metadata.rb:17:in `wrap': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/activesupport-5.2.6.2/lib/active_support/message_encryptor.rb:175:in `_encrypt'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/activesupport-5.2.6.2/lib/active_support/message_encryptor.rb:151:in `encrypt_and_sign'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/activesupport-5.2.6.2/lib/active_support/encrypted_file.rb:75:in `encrypt'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/activesupport-5.2.6.2/lib/active_support/encrypted_file.rb:49:in `write'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/activesupport-5.2.6.2/lib/active_support/encrypted_configuration.rb:29:in `write'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/railties-5.2.6.2/lib/rails/generators/rails/credentials/credentials_generator.rb:31:in `add_credentials_file_silently'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/railties-5.2.6.2/lib/rails/generators/rails/app/app_generator.rb:185:in `credentials'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/railties-5.2.6.2/lib/rails/generators/app_base.rb:159:in `build'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/railties-5.2.6.2/lib/rails/generators/rails/app/app_generator.rb:328:in `create_credentials'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `each'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `map'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `invoke_all'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/thor-1.2.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/railties-5.2.6.2/lib/rails/commands/application/application_command.rb:26:in `perform'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/railties-5.2.6.2/lib/rails/command/base.rb:69:in `perform'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/railties-5.2.6.2/lib/rails/command.rb:46:in `invoke'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/railties-5.2.6.2/lib/rails/cli.rb:18:in `<top (required)>'
	from <internal:/Users/andymaleh/.rvm/rubies/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/andymaleh/.rvm/rubies/ruby-3.0.2/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/railties-5.2.6.2/exe/rails:10:in `<top (required)>'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/bin/rails:25:in `load'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/bin/rails:25:in `<main>'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/bin/ruby_executable_hooks:22:in `eval'
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/bin/ruby_executable_hooks:22:in `<main>'
```

### System configuration
**Rails version**: 5.2.6.2

**Ruby version**: 3.0.2

**Comment by mrtorks** [comment]
@AndyObtiva An observation I wanted to point out here. Your first line is installing a specific version of rails since you have a more recent version installed right?

**Comment by yahonda** [comment]
```
/Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/activesupport-5.2.6.2/lib/active_support/messages/metadata.rb:17:in `wrap': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /Users/andymaleh/.rvm/gems/ruby-3.0.2@code/gems/activesupport-5.2.6.2/lib/active_support/message_encryptor.rb:175:in `_encrypt'
```

Rails 5.2.Z is not supported against Ruby 3.0 which implements the keyword argument separation. What I can suggest is to use Rails 6.0 or higher. or use Ruby 2.7 if you need to run Rails 5.2.Z.

Refer to https://github.com/rails/rails/commit/87b428c8e0b9cb38ba87dd71e4e14fc755de6345 which modifies the `_encrypt` method if you are interested.

**Comment by AndyObtiva** [comment]
Thank you @yahonda ! Downgrading to Ruby 2.7.2 resolved the issue.
