### ISSUE TITLE
[activerecord] It should not be possible to define an `enum` without a Hash

### ISSUE THREAD

**Issue by postmodern** [rails/rails#44457]
#### Gemfile

```ruby
source 'https://rubygems.org/'

gem 'activerecord', '~> 7.0'
gem 'sqlite3'
```

#### test.rb

```ruby
require 'bundler/setup'
require 'active_record'

class CreateTestModelTable < ActiveRecord::Migration[7.0]

  def change
    create_table :test_models do |t|
      t.string :my_enum
    end
  end

end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

CreateTestModelTable.migrate(:up)

class TestModel < ActiveRecord::Base

  enum :my_enum # BUG: should not be possible to call enum with only a name, but no Hash of values
  validates :my_enum, inclusion: {in: [1,2,3]}

end
TestModel.connection

p TestModel

record = TestModel.new(my_enum: 1)
```

### Expected behavior

An `ArgumentError` should be raised indicating that `enum` was called with only 1 argument, instead of 2 or more.

### Actual behavior

```
==  CreateTestModelTable: migrating ===========================================
-- create_table(:test_models)
   -> 0.0005s
==  CreateTestModelTable: migrated (0.0007s) ==================================

TestModel(id: integer, my_enum: string)
/home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/enum.rb:157:in `assert_valid_value': '1' is not a valid my_enum (ArgumentError)
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/attribute.rb:76:in `with_value_from_user'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/attribute_set.rb:55:in `write_from_user'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/attribute_methods/write.rb:42:in `_write_attribute'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/attribute_methods.rb:277:in `my_enum='
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/attribute_assignment.rb:49:in `public_send'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/attribute_assignment.rb:49:in `_assign_attribute'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/attribute_assignment.rb:21:in `block in _assign_attributes'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/attribute_assignment.rb:13:in `each'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/attribute_assignment.rb:13:in `_assign_attributes'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/core.rb:468:in `initialize'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/inheritance.rb:75:in `new'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/inheritance.rb:75:in `new'
	from test.rb:28:in `<main>'
```

### System configuration

* activerecord-7.0.2.2
* ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

**Comment by fatkodima** [comment]
I hope this error is rare 😄, but still a good improvement to the enum. 
Do you want to submit a PR?

**Comment by postmodern** [comment]
Maybe. It appears the problem is that the `enum` method tries to do way too much. Should the method check for `if name && value` otherwise fallback to trying to parse `**options`? Or should it check `if name` then check `if value` otherwise raise an `ArgumentError`?

**Comment by fatkodima** [comment]
`enum` is too trustful to the user's sanity. I think that should be added too.

**Comment by postmodern** [comment]
Also should we improve the error messages? Raising `must be either a hash, an array of symbols, or an array of strings.` doesn't really indicate that the given values is empty. Also since `enum` tries to extract the values and defaults it to `{}`, we can't really tell in `assert_valid_enum_definition_values` that no values were given.

**Comment by fatkodima** [comment]
I think, that `{}` already means that no values were given. Maybe something like `must be either a non-empty hash, an array of symbols, or an array of strings`?

**Comment by postmodern** [comment]
Hmm it looks like we need to have separate `value.all?` tests for when `values` is a `Hash` or an `Array`. How should `values` be validated when it's a `Hash`?

**Comment by fatkodima** [comment]
Hash:
* non-empty

Array:
* non-empty
* either all strings
* or all symbols

Mmm?

**Comment by postmodern** [comment]
Sounds good to me. I wasn't sure if the Hash had to have all values that matched the underlying column type, or all Symbol keys, or what.

**Comment by postmodern** [comment]
Force pushed to my fork-branch. I added a `case/when` for `Hash` vs. `Array` checks. Also added descriptive error messages for each edge-case telling you what's wrong, instead of a generic error message, and added more test cases.

**Comment by byroot** [comment]
https://github.com/rails/rails/pull/44471 merged. Thank you!
