### ISSUE TITLE
[activerecord] `numericality: {in: ...}` should accept an Array or Set of explicit values

### ISSUE THREAD

**Issue by postmodern** [rails/rails#44465]
In order to be consistent with `inclusion: {in: ...}`, it should be possible to pass an Array or Set of literal Integer values to `numericality: {in: ...}`, instead of only a Range.

#### Gemfile

```ruby
source 'https://rubygems.org/'

gem 'activerecord', '~> 7.0'
gem 'sqlite3'
```

#### test.rb

```ruby
require 'bundler/setup'
require 'active_record'

class CreateTestModelTable < ActiveRecord::Migration[7.0]

  def change
    create_table :test_models do |t|
      t.integer :ip_version
    end
  end

end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

CreateTestModelTable.migrate(:up)

class TestModel < ActiveRecord::Base

  attribute :ip_version, :integer
  validates :ip_version, numericality: {in: [4,6]}

end
TestModel.connection

record = TestModel.new(ip_version: 4)
p record.valid?
p record.errors
```

### Expected behavior

`numericality: {in: ...}` accepts an Array of literal Integer values and validates against them.

### Actual behavior

```
==  CreateTestModelTable: migrating ===========================================
-- create_table(:test_models)
   -> 0.0007s
==  CreateTestModelTable: migrated (0.0008s) ==================================

/home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/validations/numericality.rb:29:in `block in check_validity!': :in must be a range (ArgumentError)
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/validations/numericality.rb:27:in `each'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/validations/numericality.rb:27:in `check_validity!'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/validator.rb:142:in `initialize'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/validations/with.rb:86:in `new'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/validations/with.rb:86:in `block in validates_with'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/validations/with.rb:85:in `each'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/validations/with.rb:85:in `validates_with'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/validations/validates.rb:126:in `block in validates'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/validations/validates.rb:115:in `each'
	from /home/postmodern/test/ruby/active_record/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.2/lib/active_model/validations/validates.rb:115:in `validates'
	from test.rb:21:in `<class:TestModel>'
	from test.rb:18:in `<main>'
```

### System configuration

* activerecord 7.0.2.2
* ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

**Comment by fatkodima** [comment]
Agreed, seems like there is no reason to restrict it only to ranges. 
Do you want to open a PR?

**Comment by SkipKayhil** [comment]
Hey, I kind of jumped on this one earlier, hopefully I didn't step on any toes :/ I would appreciate any feedback if y'all have ideas

**Comment by rafaelfranca** [comment]
Why not use `inclusion` instead of `numericality` for this case?
