### ISSUE TITLE
STI foreign key auto detection regression

### ISSUE THREAD

**Issue by yskkin** [rails/rails#44594]
### Steps to reproduce

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "sqlite3", "~> 1.3.0"
  # Activate the gem you are reporting the issue against.
  gem "rails", "5.1.6"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
end

class ChildPost < Post
  has_one :foo, class_name: 'Comment', inverse_of: :bar, foreign_key: :post_id
end

class Comment < ActiveRecord::Base
  belongs_to :bar, class_name: 'ChildPost', inverse_of: :foo
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = ChildPost.create!

    post.build_foo
  end
end

```

### Expected behavior

exit without error in Rails 5.1.6, 5.2.0 and 6.1.0

### Actual behavior

exit without error in Rails 5.1.6
exit with following error in Rails 5.2.0 and 6.1.0
```
Error:
BugTest#test_association_stuff:
ActiveModel::MissingAttributeError: can't write unknown attribute `bar_id`
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activemodel-5.2.0/lib/active_model/attribute.rb:207:in `with_value_from_database'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activemodel-5.2.0/lib/active_model/attribute_set.rb:57:in `write_from_user'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/attribute_methods/write.rb:51:in `_write_attribute'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/attribute_methods/write.rb:45:in `write_attribute'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/attribute_methods.rb:410:in `[]='
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/associations/belongs_to_association.rb:92:in `replace_keys'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/associations/belongs_to_association.rb:33:in `target='
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/associations/association.rb:103:in `set_inverse_instance'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/associations/association.rb:178:in `initialize_attributes'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/associations/association.rb:271:in `block in build_record'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/core.rb:316:in `initialize'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/inheritance.rb:66:in `new'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/inheritance.rb:66:in `new'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/reflection.rb:154:in `build_association'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/associations/association.rb:270:in `build_record'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/associations/singular_association.rb:21:in `build'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-5.2.0/lib/active_record/associations/builder/singular_association.rb:29:in `build_foo'
    active_record_gem.rb:50:in `test_association_stuff'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:98:in `block (3 levels) in run'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:195:in `capture_exceptions'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:95:in `block (2 levels) in run'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:281:in `time_it'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:94:in `block in run'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:376:in `on_signal'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:221:in `with_info_handler'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:93:in `run'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:1042:in `run_one_method'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:350:in `run_one_method'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:337:in `block (2 levels) in run'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:336:in `each'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:336:in `block in run'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:376:in `on_signal'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:363:in `with_info_handler'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:335:in `run'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:169:in `block in __run'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:169:in `map'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:169:in `__run'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:146:in `run'
    /Users/xxxx/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:73:in `block in autorun'
```

### System configuration
**Rails version**:

**Ruby version**: 2.7.3

**Comment by fatkodima** [comment]
Regression was introduced in https://github.com/rails/rails/pull/31575

**Comment by yskkin** [comment]
STI was irrelevant. The following script also reproduces original issue.

<details>

```rb
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "sqlite3", "~> 1.3.0"
  # Activate the gem you are reporting the issue against.
  gem "rails", "5.1.6"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_one :foo, class_name: 'Comment', inverse_of: :bar, foreign_key: :post_id
end

class Comment < ActiveRecord::Base
  belongs_to :bar, class_name: 'Post', inverse_of: :foo
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!

    post.build_foo
  end
end
```

</details>

**Comment by caseyprovost** [comment]
I am able to reproduce as well but in my case it is by defining `Model.model_name` to return the name of the base class on all subclasses. I wonder if that is a smell though

**Comment by lazaronixon** [comment]
This should be the correct representation, no ?

```
class Post < ActiveRecord::Base
  has_one :foo, class_name: 'Comment', inverse_of: :bar
end

class Comment < ActiveRecord::Base
  belongs_to :bar, class_name: 'Post', inverse_of: :foo, foreign_key: :post_id
end
```

**Comment by jeromedalbert** [comment]
I cannot repro the issue using @lazaronixon's suggestion.

<details>
<summary>Reproduction file</summary>

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "sqlite3"
  gem "rails"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_one :foo, class_name: 'Comment', inverse_of: :bar
end

class Comment < ActiveRecord::Base
  belongs_to :bar, class_name: 'Post', inverse_of: :foo, foreign_key: :post_id
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!

    post.build_foo
  end
end
```
</details>
