### ISSUE TITLE
Upgrading Rails from 6.0 --> 6.1 breaks this query

### ISSUE THREAD

**Issue by markhilkert** [rails/rails#44619]
### Background

I'm updating an app from 6.0 --> 6.1. An existing query broke after upgrading, and I can't figure out why. The query fails on any version 6.1.0+. Any ideas? I've reproduced the error below.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "7-0-stable"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  'adapter'  => 'mysql2',
  'database' => 'test_database',
  'username' => 'root'
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "drone_identifier_sources", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci", force: :cascade do |t|
    t.string "name"
    t.string "priority"
  end

  create_table "drone_identifier_types", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci", force: :cascade do |t|
    t.string "name"
  end

  create_table "drone_identifiers", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci", force: :cascade do |t|
    t.string "identifier"
    t.bigint "drone_id"
    t.bigint "drone_identifier_type_id"
    t.bigint "drone_identifier_source_id"
    t.index ["drone_id"], name: "index_drone_identifiers_on_drone_id"
    t.index ["drone_identifier_source_id"], name: "index_drone_identifiers_on_drone_identifier_source_id"
    t.index ["drone_identifier_type_id"], name: "index_drone_identifiers_on_drone_identifier_type_id"
  end

  create_table "drones", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci", force: :cascade do |t|
    t.string "name"
  end
end

class Drone < ActiveRecord::Base
  has_many(:drone_identifiers,
    ->() { joins(:drone_identifier_source).order('drone_identifier_sources.priority') },
    dependent: :destroy
  )

  def self.find_by_identifier(identifier, drone_identifier_type_id)
    joins(drone_identifiers: :drone_identifier_source)
      .where(
        drone_identifiers: {
          identifier: identifier,
          drone_identifier_type_id: drone_identifier_type_id
        }
      )
      .order('drone_identifier_sources.priority')
      .first!
    rescue ActiveRecord::RecordNotFound
      nil
  end
end

class DroneIdentifier < ActiveRecord::Base
  belongs_to :drone_identifier_type
  belongs_to :drone_identifier_source
  belongs_to :drone
end

class DroneIdentifierSource < ActiveRecord::Base
  has_many :drone_identifiers
end

class DroneIdentifierType < ActiveRecord::Base
  has_many :drone_identifiers
end

class BugTest < Minitest::Test
  def test_association_stuff
    drone = Drone.find_by_identifier('abc', 1)

    assert_nil drone
  end
end

```

### Expected behavior

In Rails 6.0, the following query is executed successfully:

```sql
SELECT `drones`.* 
  FROM `drones` 
  INNER JOIN `drone_identifiers` 
  ON `drone_identifiers`.`drone_id` = `drones`.`id` 
  INNER JOIN `drone_identifier_sources` 
  ON `drone_identifier_sources`.`id` = `drone_identifiers`.`drone_identifier_source_id` 
  WHERE `drone_identifiers`.`identifier` = 'abc' 
  AND `drone_identifiers`.`drone_identifier_type_id` = 1 
  ORDER BY drone_identifier_sources.priority 
  LIMIT 1
```

### Actual behavior

Once I upgrade Rails to 6.1 or higher, this SQL query is executed:

```sql
SELECT `drones`.* 
  FROM `drones` 
  INNER JOIN `drone_identifiers` 
  ON `drone_identifiers`.`drone_id` = `drones`.`id` 
  INNER JOIN `drone_identifier_sources` `drone_identifier_sources_drone_identifiers` 
  ON `drone_identifier_sources_drone_identifiers`.`id` = `drone_identifiers`.`drone_identifier_source_id` 
  WHERE `drone_identifiers`.`identifier` = 'abc' 
  AND `drone_identifiers`.`drone_identifier_type_id` = 1 
  ORDER BY drone_identifier_sources.priority 
  LIMIT 1
```

Which results in the following error:

```
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'drone_identifier_sources.priority' in 'order clause'
```

Stacktrace:

```
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'drone_identifier_sources.priority' in 'order clause'
    2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
    2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
    2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
    2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:632:in `block (2 levels) in raw_execute'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activesupport/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activesupport/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:631:in `block in raw_execute'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:630:in `raw_execute'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb:96:in `raw_execute'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb:47:in `execute'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:207:in `execute_and_free'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb:52:in `exec_query'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb:12:in `select_all'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/querying.rb:54:in `_query_by_sql'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation.rb:941:in `block in exec_main_query'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation.rb:961:in `skip_query_cache_if_necessary'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation.rb:927:in `exec_main_query'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation.rb:913:in `block in exec_queries'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation.rb:961:in `skip_query_cache_if_necessary'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation.rb:907:in `exec_queries'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation.rb:695:in `load'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation.rb:250:in `records'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation.rb:245:in `to_ary'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation/finder_methods.rb:549:in `find_nth_with_limit'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation/finder_methods.rb:534:in `find_nth'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation/finder_methods.rb:146:in `first'
    2.7.0/bundler/gems/rails-4656c1a8f2e8/activerecord/lib/active_record/relation/finder_methods.rb:153:in `first!'
    demo.rb:66:in `find_by_identifier'
    demo.rb:88:in `test_association_stuff'
```

### System configuration
**Rails version**: 7.0.2.2 (but the error occurs on any version after 6.1.0)

**Ruby version**: 2.7.2p137

**MySQL version**: 8.0.28 for macos12.2 on x86_64

**Comment by janniswidderich** [comment]
I think whats happening here is that in 6.1 the joined table gets renamed in this line: `INNER JOIN \`drone_identifier_sources\` \`drone_identifier_sources_drone_identifiers\``

**Comment by janniswidderich** [comment]
I think whats happening here is that in 6.1 the joined table gets renamed in this line: 
````
INNER JOIN `drone_identifier_sources` `drone_identifier_sources_drone_identifiers`
````
(turns out you can leave out the keyword `AS` - I never knew!)

Your order calls (`.order('drone_identifier_sources.priority')`) still reference the table by its original name. But since it has been renamed, MySQL says a table with that name doesn't exist.

I would say that the best fix would be to change the order call to `.order(DroneIdentifierSource.arel_table[:priority])`. If that doesn't work, changing it to `.order('drone_identifier_sources_drone_identifiers.priority')` should also work.

**Comment by markhilkert** [comment]
Thanks for your response! I also didn't know you could omit `AS`, and had never heard of the `arel_table` method, so looking into them was helpful.

For reasons I don't understand (probably because I don't understand what `arel_table` really does yet), `.order(DroneIdentifierSource.arel_table[:priority])` does not fix my issue. But `.order('drone_identifier_sources_drone_identifiers.priority')` does! I really appreciate the help.

Here's what the method looks like after incorporating your update:

```ruby
  def self.find_by_identifier(identifier, drone_identifier_type_id)
    joins(drone_identifiers: :drone_identifier_source)
      .where(
        drone_identifiers: {
          identifier: identifier,
          drone_identifier_type_id: drone_identifier_type_id
        }
      )
      .order('drone_identifier_sources_drone_identifiers.priority')
      .first!
    rescue ActiveRecord::RecordNotFound
      nil
  end
```

And here's a second test I added to make sure it works when the method does find a drone:

```ruby
  def test_find_drone_by_identifier
    drone_identifier_type = DroneIdentifierType.create(name: "drone type")
    drone_identifier_source = DroneIdentifierSource.create(name: "drone source")
    drone = Drone.create(name: "steve")

    drone_identifier = DroneIdentifier.create(
      identifier: 'abcdef',
      drone_id: drone.id,
      drone_identifier_type_id: drone_identifier_type.id,
      drone_identifier_source_id: drone_identifier_source.id
    )

    subject = Drone.find_by_identifier('abcdef', drone_identifier_type.id)
    refute subject.new_record?
    assert_equal drone, subject
  end
```

And now both tests pass. I'll close this issue.
