### ISSUE TITLE
System tests screenshots - include path in test_result message, backtrace or separate metadata

### ISSUE THREAD

**Issue by davidwessman** [rails/rails#44624]
While parsing test results from system tests, it would be very useful to include the paths to taken screenshots in the metadata.

In the [`ScreenshotHelper`](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb#L37) the path will be output with `puts`, but then it can only be accessed in logs and not in for example a [`Minitest::Reporter`](https://github.com/seattlerb/minitest/blob/master/lib/minitest.rb#L602).

While looking through [`ActiveSupport::TestCase`](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/test_case.rb)  and [`Minitest::Test`](https://github.com/seattlerb/minitest/blob/master/lib/minitest/test.rb#L10) I could not find a good place to add more metadata.

It would be useful if the failure screenshot path (or paths to all screenshots in the test case):

- are added to the `ActiveSupport::TestCase` failure message.
- are added to some custom metadata of the test case, that could be accessed in e.g. a reporter.

## Rspec

In Rspec it adds screenshot output as [`extra_failure_lines`](https://github.com/rspec/rspec-rails/blob/3e7d8d0391cbd6355eca7d6259fd5547e07d8277/spec/rspec/rails/example/system_example_group_spec.rb#L91) which is included in the spec result message of a failure.

------------

I would love to make a try at a PR, but I would need some guidance if it is possible or not.

**Comment by eileencodes** [comment]
Hey @davidwessman - thanks for the request. We generally don't take feature requests on the issues tracker but I think this one should be pretty straightforward.

First, can you show me an example of what you're looking for? I don't quite follow and I don't use Rspec so the code you linked to doesn't clarify it for me what this feature would look like. Once I understand better I can point you to the correct area to update. The Screenshot code is located here https://github.com/rails/rails/blob/ce72a8a5a75d3de925cb06ffde886932e6bdfd2e/actionpack/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb#L7 in Action Pack rather than in Active Support if that helps you find what you're looking for.

**Comment by davidwessman** [comment]
Thank you for responding, sorry for using this as a feature request - I was not sure if it was possible to do or not already.

When running a system test and it takes a screenshot due to failure, it would be great if the output from the ScreenshotHelper was stored and not just written to a log.

I want to be able to write a `Minitest::Reporter` that can check for screenshots for each failure, but the information that a screenshot was taken and written to file is not available in any context other than the log.

<details>
  <summary>This is the output from a junit-report for Rspec where a screenshot was taken and the [Screenshot:] path is added to the failure body.</summary>
  
  ```xml
    <testcase classname="spec.system.sign_in_spec" name="Sign in error" file="./spec/system/sign_in_spec.rb" time="0.701368">
    <failure message="undefined local variable or method `invalid_code&apos; for #&lt;RSpec::ExampleGroups::SignIn:0x00007fdd90d6bf08&gt;" type="NameError">Failure/Error: invalid_code

NameError:
  undefined local variable or method `invalid_code&apos; for #&lt;RSpec::ExampleGroups::SignIn:0x00007fdd90d6bf08&gt;

[Screenshot]: ./test/tmp/screenshots/failures_r_spec_example_groups_sign_in_error_848.png


./spec/system/sign_in_spec.rb:27:in `block (2 levels) in &lt;main&gt;&apos;</failure>
  </testcase>
  ```
  
</details>



This is the test result object in a Minitest::Reporter of a system tests where a screenshot was taken
  
  ```ruby
{
 "NAME"=>"test_visit_landing_page",                                                                                                      
 "failures"=>["Unexpected exception"],                                                                                                   
 "assertions"=>0,                                                                                                                        
 "klass"=>"LandingTest",                                                                                                                 
 "time"=>4.022064000018872,                                                                                                              
 "source_location"=>["test/system/landing_test.rb", 5],                                     
 "failure_message"=>"Capybara::ElementNotFound: Unable to find visible css \"a\" with text \"No such link\"\n    test/system/landing_test.rb:8:in `block in <class:LandingTest>'",
 "failure_backtrace"=>["test/system/landing_test.rb:8:in `block in <class:LandingTest>'"]
 } 
  ```
  
  I would like the screenshot path to be added somewhere in the metadata of the Minitest, maybe added to the `failure.message` like they solved it in Rspec:
  
  ```ruby
{
 "NAME"=>"test_visit_landing_page",                                                                                                      
 "failures"=>["Unexpected exception"],                                                                                                   
 "assertions"=>0,                                                                                                                        
 "klass"=>"LandingTest",                                                                                                                 
 "time"=>4.022064000018872,                                                                                                              
 "source_location"=>["test/system/landing_test.rb", 5],                                     
 "failure_message"=>"Capybara::ElementNotFound: Unable to find visible css \"a\" with text \"No such link\"\n\n[Screenshot]: ./test/tmp/screenshots/failures_r_spec_example_groups_sign_in_error_848.png\ntest/system/landing_test.rb:8:in `block in <class:LandingTest>'",
 "failure_backtrace"=>["test/system/landing_test.rb:8:in `block in <class:LandingTest>'"]
 } 
  ```
  
  https://github.com/davidwessman/blinka_reporter/blob/main/lib/minitest/blinka_plugin.rb#L44 this is the way my Gem looks today and where I would like to access the Screenshot-metadata of a test, but it would work for any other reporter as well.

**Comment by matteeyah** [comment]
This wasn't possible until recently because `Minitest` didn't support embedding additional data to the test results - https://github.com/minitest/minitest/issues/956.
