### ISSUE TITLE
"cannot load such file -- bootsnap/setup (LoadError)" when running "rails new"

### ISSUE THREAD

**Issue by getaaron** [rails/rails#44649]
### Steps to reproduce

Create this `Gemfile`:

```ruby
source "https://rubygems.org"

gem "rails"
```

Run `bundle` which installs `rails (7.0.2.3)` and related dependencies

Run `bundle exec rails new app/`

### Expected behavior
I expect the app to be created without errors

### Actual behavior

```
[…]
Using rails 7.0.2.3
Bundle complete! 15 Gemfile dependencies, 74 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  importmap:install
Traceback (most recent call last):
	3: from bin/rails:3:in `<main>'
	2: from bin/rails:3:in `require_relative'
	1: from /Users/aaron/rlto/app/config/boot.rb:4:in `<top (required)>'
/Users/aaron/rlto/app/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
       rails  turbo:install stimulus:install
Traceback (most recent call last):
	3: from bin/rails:3:in `<main>'
	2: from bin/rails:3:in `require_relative'
	1: from /Users/aaron/rlto/app/config/boot.rb:4:in `<top (required)>'
/Users/aaron/rlto/app/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
```

### System configuration
**Rails version**:

```
$ bundle exec rails -v
Rails 7.0.2.3
```

**Ruby version**:

```
$ bundle exec ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [arm64-darwin21]
```

**Comment by matthewd** [comment]
> Create this Gemfile

This is not a supported use; as you've seen, generating a new application from inside a bundle will have issues distinguishing which bundle to use, etc.

Please follow [the instructions](https://guides.rubyonrails.org/getting_started.html#creating-a-new-rails-project-installing-rails) in the Getting Started guide.
