### ISSUE TITLE
Rails 7 occasionally produces <TypeError: nil can't be coerced into Float> on concurrent multiple requests

### ISSUE THREAD

**Issue by n00bvn** [rails/rails#44700]
I'm using latest Rails 7.0.2.3 API mode and the app is currently developing on development environment only.

### Steps to reproduce
Well because this happen occasionally, so I'm not sure about this... 
Anyway basically, my frontend app sends multiple requests at the same time to Rails backend.
If I delay those requests a bit to make them call to the backend in series, then everything is ok.

### Expected behavior
All requests should go through. 

### Actual behavior
But occasionally, I got error `<TypeError: nil can't be coerced into Float>`

### My investigations:
- Firstly, I edit `puma.rb` config to get more details of the exception:
```
lowlevel_error_handler do |e|
  puts "EXCEPTION = #{e.inspect}".red
  puts "TRACES = #{e.backtrace.inspect}".red
end
```

- Then I got these messages:
```
EXCEPTION = #<TypeError: nil can't be coerced into Float>
TRACES = ["/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:133:in `-'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:133:in `duration'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/activesupport-7.0.2.3/lib/active_support/core_ext/enumerable.rb:61:in `map'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/activesupport-7.0.2.3/lib/active_support/core_ext/enumerable.rb:61:in `sum'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/activesupport-7.0.2.3/lib/active_support/core_ext/enumerable.rb:298:in `sum'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/server_timing.rb:26:in `block in call'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/server_timing.rb:25:in `each'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/server_timing.rb:25:in `map'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/server_timing.rb:25:in `call'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/static.rb:23:in `call'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/host_authorization.rb:137:in `call'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/railties-7.0.2.3/lib/rails/engine.rb:530:in `call'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/puma-5.6.2/lib/puma/configuration.rb:252:in `call'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/puma-5.6.2/lib/puma/request.rb:77:in `block in handle_request'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/puma-5.6.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/puma-5.6.2/lib/puma/request.rb:76:in `handle_request'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/puma-5.6.2/lib/puma/server.rb:441:in `process_client'",
"/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/puma-5.6.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'"]
```

- Then I open the file `/Users/thaw/.rvm/gems/ruby-3.0.0@epitome/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb` and added this to line 134, (`duration` method)
`puts "=============#{self.end} --- #{time}================".red`

And I got this message before above exception message `=============1647410890381.45 --- ================`

### System configuration
**Rails version**:
7.0.2.3
**Ruby version**:
3.0.0
**Puma version**:
5.6.2

I didn't have this error before upgrading to Rails 7.
Thanks a lot for all of your helps!

**Comment by SkipKayhil** [comment]
I believe this is https://github.com/rails/rails/issues/44167, which was fixed in https://github.com/rails/rails/pull/44454 and backported to 7-0-stable, but just hasn't been released yet. In the meantime you can disable the ServerTiming middleware and the issue should go away.

**Comment by n00bvn** [comment]
Oh thank you. That's exactly what I faced.
Close the issue!
