### ISSUE TITLE
Rails quits after creating a rich text entry with an image in the database.

### ISSUE THREAD

**Issue by Shetty-Tejas** [rails/rails#44729]
### Steps to reproduce

```ruby
1. Installing ActionText.
2. Installing libvips, ruby-vips, ruby-ffi
3. Adding config.active_storage.variant_processor = :vips to config/application.rb
4. Adding has_rich_text :body to my Post.rb
5. Adding the trix editor on the new post form.
6. Adding a post with an image through the form.
```

### Expected behavior
Should save the post and redirect to the newly created post page while rails continues to work.

### Actual behavior
Rails saves the post and after redirection, the rails server crashes without any error.

### System configuration
**Rails version**:
Rails 7.0.2.2

**Ruby version**:
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x64-mingw-ucrt]

### Log before crash
```
Started GET "/posts/new" for 127.0.0.1 at 2022-03-20 15:32:43 +0530
Processing by PostsController#new as HTML
  Rendering layout layouts/application.html.erb
  Rendering posts/new.html.erb within layouts/application
  Rendered posts/new.html.erb within layouts/application (Duration: 90.2ms | Allocations: 12092)
  Rendered components/_navbar.html.erb (Duration: 0.1ms | Allocations: 53)
  Rendered layout layouts/application.html.erb (Duration: 110.0ms | Allocations: 17229)
Completed 200 OK in 116ms (Views: 111.6ms | ActiveRecord: 0.0ms | Allocations: 17669)


Started POST "/rails/active_storage/direct_uploads" for 127.0.0.1 at 2022-03-20 15:32:49 +0530
Processing by ActiveStorage::DirectUploadsController#create as JSON
  Parameters: {"blob"=>{"filename"=>"Untitled.png", "content_type"=>"image/png", "byte_size"=>67712, "checksum"=>"JSkbfD1/qYR3jiMSQ4StXw=="}, "direct_upload"=>{"blob"=>{"filename"=>"Untitled.png", "content_type"=>"image/png", "byte_size"=>67712, "checksum"=>"JSkbfD1/qYR3jiMSQ4StXw=="}}}
  TRANSACTION (0.1ms)  begin transaction
  ActiveStorage::Blob Create (1.8ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "metadata", "service_name", "byte_size", "checksum", "created_at") VALUES (?, ?, 
?, ?, ?, ?, ?, ?)  [["key", "yg3tcj8az8wejmz1hc0baej8cb6l"], ["filename", "Untitled.png"], ["content_type", "image/png"], ["metadata", nil], ["service_name", "local"], ["byte_size", 67712], 
["checksum", "JSkbfD1/qYR3jiMSQ4StXw=="], ["created_at", "2022-03-20 10:02:49.678370"]]        
  TRANSACTION (4.8ms)  commit transaction
  Disk Storage (0.9ms) Generated URL for file at key: yg3tcj8az8wejmz1hc0baej8cb6l (http://localhost:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDam9JYTJWNVNTSWhlV2N6ZEdOcU9HRjZPSGRsYW0xNk1XaGpNR0poWldvNFkySTJiQVk2QmtWVU9oRmpiMjUwWlc1MFgzUjVjR1ZKSWc1cGJXRm5aUzl3Ym1jR093WlVPaE5qYjI1MFpXNTBYMnhsYm1kMGFHa0RnQWdCT2cxamFHVmphM04xYlVraUhVcFRhMkptUkRFdmNWbFNNMnBwVFZOUk5GTjBXSGM5UFFZN0JsUTZFWE5sY25acFkyVmZibUZ0WlRvS2JHOWpZV3c9IiwiZXhwIjoiMjAyMi0wMy0yMFQxMDowNzo0OS42OTRaIiwicHVyIjoiYmxvYl90b2tlbiJ9fQ==--dc343ddf348a3fa46f8d8b59c26e68893ed5ae00)       
Completed 200 OK in 27ms (Views: 0.6ms | ActiveRecord: 6.7ms | Allocations: 4744)


Started PUT "/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDam9JYTJWNVNTSWhlV2N6ZEdOcU9HRjZPSGRsYW0xNk1XaGpNR0poWldvNFkySTJiQVk2QmtWVU9oRmpiMjUwWlc1MFgzUjVjR1ZKSWc1cGJXRm5aUzl3Ym1jR093WlVPaE5qYjI1MFpXNTBYMnhsYm1kMGFHa0RnQWdCT2cxamFHVmphM04xYlVraUhVcFRhMkptUkRFdmNWbFNNMnBwVFZOUk5GTjBXSGM5UFFZN0JsUTZFWE5sY25acFkyVmZibUZ0WlRvS2JHOWpZV3c9IiwiZXhwIjoiMjAyMi0wMy0yMFQxMDowNzo0OS42OTRaIiwicHVyIjoiYmxvYl90b2tlbiJ9fQ==--dc343ddf348a3fa46f8d8b59c26e68893ed5ae00" for 127.0.0.1 at 2022-03-20 15:32:49 +0530
Processing by ActiveStorage::DiskController#update as */*
  Parameters: {"encoded_token"=>"[FILTERED]"}
  Disk Storage (5.0ms) Uploaded file to key: yg3tcj8az8wejmz1hc0baej8cb6l (checksum: JSkbfD1/qYR3jiMSQ4StXw==)
Completed 204 No Content in 13ms (ActiveRecord: 0.0ms | Allocations: 497)


Started GET "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50e4c4426007be24eaa37994d19f26672b7c16aa/Untitled.png" for 127.0.0.1 at 2022-03-20 15:32:49 +0530
Processing by ActiveStorage::Blobs::RedirectController#show as PNG
  Parameters: {"signed_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50e4c4426007be24eaa37994d19f26672b7c16aa", "filename"=>"Untitled"}
   (0.1ms)  SELECT sqlite_version(*)
  ActiveStorage::Blob Load (0.3ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 26], ["LIMIT", 1]]
  Disk Storage (1.1ms) Generated URL for file at key: yg3tcj8az8wejmz1hc0baej8cb6l (http://localhost:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhlV2N6ZEdOcU9HRjZPSGRsYW0xNk1XaGpNR0poWldvNFkySTJiQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUTJsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SWxWdWRHbDBiR1ZrTG5CdVp5STdJR1pwYkdWdVlXMWxLajFWVkVZdE9DY25WVzUwYVhSc1pXUXVjRzVuQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJT2FXMWhaMlV2Y0c1bkJqc0dWRG9SYzJWeWRtbGpaVjl1WVcxbE9ncHNiMk5oYkE9PSIsImV4cCI6IjIwMjItMDMtMjBUMTA6MDc6NDkuOTg1WiIsInB1ciI6ImJsb2Jfa2V5In19--3335eeeb5946484b14537c654c35e2c04294fddf/Untitled.png)
Redirected to http://localhost:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhlV2N6ZEdOcU9HRjZPSGRsYW0xNk1XaGpNR0poWldvNFkySTJiQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUTJsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SWxWdWRHbDBiR1ZrTG5CdVp5STdJR1pwYkdWdVlXMWxLajFWVkVZdE9DY25WVzUwYVhSc1pXUXVjRzVuQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJT2FXMWhaMlV2Y0c1bkJqc0dWRG9SYzJWeWRtbGpaVjl1WVcxbE9ncHNiMk5oYkE9PSIsImV4cCI6IjIwMjItMDMtMjBUMTA6MDc6NDkuOTg1WiIsInB1ciI6ImJsb2Jfa2V5In19--3335eeeb5946484b14537c654c35e2c04294fddf/Untitled.png
Completed 302 Found in 15ms (ActiveRecord: 0.9ms | Allocations: 1939)


Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhlV2N6ZEdOcU9HRjZPSGRsYW0xNk1XaGpNR0poWldvNFkySTJiQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUTJsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SWxWdWRHbDBiR1ZrTG5CdVp5STdJR1pwYkdWdVlXMWxLajFWVkVZdE9DY25WVzUwYVhSc1pXUXVjRzVuQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJT2FXMWhaMlV2Y0c1bkJqc0dWRG9SYzJWeWRtbGpaVjl1WVcxbE9ncHNiMk5oYkE9PSIsImV4cCI6IjIwMjItMDMtMjBUMTA6MDc6NDkuOTg1WiIsInB1ciI6ImJsb2Jfa2V5In19--3335eeeb5946484b14537c654c35e2c04294fddf/Untitled.png" for 127.0.0.1 at 2022-03-20 15:32:50 +0530
Processing by ActiveStorage::DiskController#show as PNG
  Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"Untitled"}
Completed 200 OK in 4ms (ActiveRecord: 0.0ms | Allocations: 198)


Started POST "/posts" for 127.0.0.1 at 2022-03-20 15:33:05 +0530
Processing by PostsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "post"=>{"title"=>"asdfaljdsf", "body"=>"<div>asdfasdfasdf<figure data-trix-attachment=\"{&quot;contentType&quot;:&quot;image/png&quot;,&quot;filename&quot;:&quot;Untitled.png&quot;,&quot;filesize&quot;:67712,&quot;height&quot;:391,&quot;sgid&quot;:&quot;BAh7CEkiCGdpZAY6BkVUSSI6Z2lkOi8vZ3V5cy13aG8tY29kZS9BY3RpdmVTdG9yYWdlOjpCbG9iLzI2P2V4cGlyZXNfaW4GOwBUSSIMcHVycG9zZQY7AFRJIg9hdHRhY2hhYmxlBjsAVEkiD2V4cGlyZXNfYXQGOwBUMA==--3f7a9f38b00731822e370a0629ee34084018e38b&quot;,&quot;url&quot;:&quot;http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50e4c4426007be24eaa37994d19f26672b7c16aa/Untitled.png&quot;,&quot;width&quot;:375}\" data-trix-content-type=\"image/png\" data-trix-attributes=\"{&quot;presentation&quot;:&quot;gallery&quot;}\" class=\"attachment attachment--preview attachment--png\"><img src=\"http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50e4c4426007be24eaa37994d19f26672b7c16aa/Untitled.png\" width=\"375\" height=\"391\"><figcaption class=\"attachment__caption\"><span class=\"attachment__name\">Untitled.png</span> <span class=\"attachment__size\">66.13 KB</span></figcaption></figure></div>"}, "commit"=>"Create Post"}
   (0.1ms)  SELECT sqlite_version(*)
  ↳ app/controllers/posts_controller.rb:15:in `create'
  TRANSACTION (0.0ms)  begin transaction
  ↳ app/controllers/posts_controller.rb:16:in `create'
  ActiveStorage::Blob Load (0.3ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 26], ["LIMIT", 1]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  CACHE ActiveStorage::Blob Load (0.0ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 26], ["LIMIT", 1]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  CACHE ActiveStorage::Blob Load (0.0ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 26], ["LIMIT", 1]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  CACHE ActiveStorage::Blob Load (0.0ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 26], ["LIMIT", 1]]
  ↳ app/models/post.rb:8:in `body_length'
  Post Create (1.7ms)  INSERT INTO "posts" ("title", "created_at", "updated_at") VALUES (?, ?, 
?)  [["title", "asdfaljdsf"], ["created_at", "2022-03-20 10:03:05.969215"], ["updated_at", "2022-03-20 10:03:05.969215"]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  ActiveStorage::Blob Load (0.1ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 26], ["LIMIT", 1]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  ActionText::RichText Create (0.5ms)  INSERT INTO "action_text_rich_texts" ("name", "body", "record_type", "record_id", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?)  [["name", "body"], ["body", "<div>asdfasdfasdf<action-text-attachment sgid=\"BAh7CEkiCGdpZAY6BkVUSSI6Z2lkOi8vZ3V5cy13aG8tY29kZS9BY3RpdmVTdG9yYWdlOjpCbG9iLzI2P2V4cGlyZXNfaW4GOwBUSSIMcHVycG9zZQY7AFRJIg9hdHRhY2hhYmxlBjsAVEkiD2V4cGlyZXNfYXQGOwBUMA==--3f7a9f38b00731822e370a0629ee34084018e38b\" content-type=\"image/png\" url=\"http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50e4c4426007be24eaa37994d19f26672b7c16aa/Untitled.png\" filename=\"Untitled.png\" filesize=\"67712\" width=\"375\" height=\"391\" presentation=\"gallery\"></action-text-attachment></div>"], ["record_type", "Post"], ["record_id", 20], ["created_at", "2022-03-20 10:03:06.009179"], ["updated_at", "2022-03-20 10:03:06.009179"]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  ActiveStorage::Blob Load (0.1ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 26], ["LIMIT", 1]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  ActiveStorage::Blob Update (0.3ms)  UPDATE "active_storage_blobs" SET "metadata" = ? WHERE "active_storage_blobs"."id" = ?  [["metadata", "{\"identified\":true}"], ["id", 26]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  ActiveStorage::Attachment Create (0.5ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES (?, ?, ?, ?, ?)  [["name", "embeds"], ["record_type", "ActionText::RichText"], ["record_id", 20], ["blob_id", 26], ["created_at", "2022-03-20 10:03:06.032143"]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  Post Update (0.1ms)  UPDATE "posts" SET "updated_at" = ? WHERE "posts"."id" = ?  [["updated_at", "2022-03-20 10:03:06.037194"], ["id", 20]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  ActionText::RichText Update (0.1ms)  UPDATE "action_text_rich_texts" SET "updated_at" = ? WHERE "action_text_rich_texts"."id" = ?  [["updated_at", "2022-03-20 10:03:06.036584"], ["id", 20]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  TRANSACTION (5.8ms)  commit transaction
  ↳ app/controllers/posts_controller.rb:16:in `create'
[ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: 20f7d9f4-4915-4db6-ad45-9214c5df56f0) to Async(default) with arguments: #<GlobalID:0x0000019f6a5745f8 @uri=#<URI::GID gid://guys-who-code/ActiveStorage::Blob/26>>
Redirected to http://localhost:3000/posts/20
Completed 302 Found in 140ms (ActiveRecord: 10.4ms | Allocations: 39718)


Started GET "/posts/20" for 127.0.0.1 at 2022-03-20 15:33:06 +0530
[ActiveJob] [ActiveStorage::AnalyzeJob] [20f7d9f4-4915-4db6-ad45-9214c5df56f0]   ActiveStorage::Blob Load (0.2ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 26], ["LIMIT", 1]]
[ActiveJob] [ActiveStorage::AnalyzeJob] [20f7d9f4-4915-4db6-ad45-9214c5df56f0] Performing ActiveStorage::AnalyzeJob (Job ID: 20f7d9f4-4915-4db6-ad45-9214c5df56f0) from Async(default) enqueued at 2022-03-20T10:03:06Z with arguments: #<GlobalID:0x0000019f6a5b8c08 @uri=#<URI::GID gid://guys-who-code/ActiveStorage::Blob/26>>
[ActiveJob] [ActiveStorage::AnalyzeJob] [20f7d9f4-4915-4db6-ad45-9214c5df56f0]   Disk Storage (4.1ms) Downloaded file from key: yg3tcj8az8wejmz1hc0baej8cb6l
Processing by PostsController#show as TURBO_STREAM
  Parameters: {"id"=>"20"}
  Post Load (0.5ms)  SELECT "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", 20], ["LIMIT", 1]]
  ↳ app/controllers/posts_controller.rb:3:in `show'
  Rendering layout layouts/application.html.erb
  Rendering posts/show.html.erb within layouts/application
  ActionText::RichText Load (0.5ms)  SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."record_id" = ? AND "action_text_rich_texts"."record_type" = ? AND "action_text_rich_texts"."name" = ? LIMIT ?  [["record_id", 20], ["record_type", "Post"], ["name", "body"], ["LIMIT", 1]]
  ↳ app/views/posts/show.html.erb:12
  ActiveStorage::Blob Load (0.3ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 26], ["LIMIT", 1]]
  ↳ app/views/posts/show.html.erb:12
  Rendered active_storage/blobs/_blob.html.erb (Duration: 0.9ms | Allocations: 496)
  Rendered C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/actiontext-7.0.2.2/app/views/action_text/contents/_content.html.erb within layouts/action_text/contents/_content (Duration: 8.1ms | Allocations: 3912)
  Rendered posts/show.html.erb within layouts/application (Duration: 17.1ms | Allocations: 6114)
  Rendered layout layouts/application.html.erb (Duration: 53.0ms | Allocations: 15288)


[ActiveJob] [ActiveStorage::AnalyzeJob] [20f7d9f4-4915-4db6-ad45-9214c5df56f0]   TRANSACTION (0.1ms)  begin transaction
[ActiveJob] [ActiveStorage::AnalyzeJob] [20f7d9f4-4915-4db6-ad45-9214c5df56f0]   ActiveStorage::Blob Update (2.1ms)  UPDATE "active_storage_blobs" SET "metadata" = ? WHERE "active_storage_blobs"."id" = ?  [["metadata", "{\"identified\":true,\"width\":375,\"height\":391,\"analyzed\":true}"], ["id", 26]]
[ActiveJob] [ActiveStorage::AnalyzeJob] [20f7d9f4-4915-4db6-ad45-9214c5df56f0]   TRANSACTION (4.6ms)  commit transaction
[ActiveJob] [ActiveStorage::AnalyzeJob] [20f7d9f4-4915-4db6-ad45-9214c5df56f0] Performed ActiveStorage::AnalyzeJob (Job ID: 20f7d9f4-4915-4db6-ad45-9214c5df56f0) from Async(default) in 578.03ms
```

**Comment by Shetty-Tejas** [comment]
A follow up:
When I use mini_magick as the variant processor, there is no side effect with rails and everything works nicely. It's just the vips that's causing the problem.

**Comment by HParker** [comment]
when you open an issue with `ruby-vips` feel free to link this issue. Also, if you are able to make a small test app and post it here it would save some time setting up your example.

**Comment by Shetty-Tejas** [comment]
Hello @HParker.
I am new to creating issue so I didn't understand about 'linking the issue'. Would you please elaborate?
And yes, I am working on a personal project where I have integrated ActionText. I can happily link that [here](https://github.com/Shetty-Tejas/guys-who-code/) for you to check it out.

**Comment by HParker** [comment]
It sounds like you might have an issue with your image processing gem, so I was suggesting you might open an issue there and see if they know what is causing this issue. When you do, you can add a copy paste the link to this issue and it will connect them. You are welcome, but not required to do that.

Also, if you still believe this is a rails issue, it would be helpful to reproduce your issue using one of the templates listed here, https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html

Hope that helps!
