### ISSUE TITLE
Rails 6.1.5 id type regression on migration

### ISSUE THREAD

**Issue by marocchino** [rails/rails#44767]
### Steps to reproduce

```rb
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', ENV.fetch('RAILS_VERSION', '6.1.5')
  gem 'mysql2'
end

require 'active_record'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'mysql2', database: 'migration_issue_development', username: 'root',
                                        host: '127.0.0.1', password: 'root', port: 4306)
ActiveRecord::Base.logger = Logger.new(STDOUT)

class CreateActiveStorageTables < ActiveRecord::Migration[5.2]
  def change
    create_table :active_storage_blobs do |t|
      t.string   :key,        null: false
      t.string   :filename,   null: false
      t.string   :content_type
      t.text     :metadata
      t.bigint   :byte_size,  null: false
      t.string   :checksum,   null: false
      t.datetime :created_at, null: false

      t.index [:key], unique: true
    end

    create_table :active_storage_attachments do |t|
      t.string     :name,     null: false
      t.references :record,   null: false, polymorphic: true, index: false
      t.references :blob,     null: false

      t.datetime :created_at, null: false

      t.index %i[record_type record_id name blob_id], name: 'index_active_storage_attachments_uniqueness',
                                                      unique: true
      t.foreign_key :active_storage_blobs, column: :blob_id
    end
  end
end

class CreateActiveStorageVariantRecords < ActiveRecord::Migration[6.0]
  def change
    create_table :active_storage_variant_records do |t|
      t.belongs_to :blob, null: false, index: false
      t.string :variation_digest, null: false

      t.index %i[blob_id variation_digest], name: 'index_active_storage_variant_records_uniqueness', unique: true
      t.foreign_key :active_storage_blobs, column: :blob_id
    end
  end
end

CreateActiveStorageTables.migrate(:up)
CreateActiveStorageVariantRecords.migrate(:up)

```

### Expected behavior

Complete migration without errors. 6.1.4.7 version was fine.
```
$ RAILS_VERSION=6.1.4.7 ruby migration_bug.rb
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using rake 13.0.6
Using concurrent-ruby 1.1.10
Using minitest 5.15.0
Using zeitwerk 2.5.4
Using builder 3.2.4
Using erubi 1.10.0
Using racc 1.6.0
Using method_source 1.0.0
Using i18n 1.10.0
Using tzinfo 2.0.4
Using crass 1.0.6
Using activesupport 6.1.4.7
Using marcel 1.0.2
Using globalid 1.0.0
Using activemodel 6.1.4.7
Using bundler 2.3.9
Using activerecord 6.1.4.7
Using activejob 6.1.4.7
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using mini_mime 1.1.2
Using nokogiri 1.13.3 (arm64-darwin)
Using mysql2 0.5.3
Using thor 1.2.1
Using rails-dom-testing 2.0.3
Using loofah 2.15.0
Using mail 2.7.1
Using rails-html-sanitizer 1.4.2
Using rack 2.2.3
Using websocket-driver 0.7.5
Using actionview 6.1.4.7
Using sprockets 4.0.3
Using rack-test 1.1.0
Using actionpack 6.1.4.7
Using actioncable 6.1.4.7
Using activestorage 6.1.4.7
Using actionmailer 6.1.4.7
Using railties 6.1.4.7
Using actiontext 6.1.4.7
Using sprockets-rails 3.4.2
Using actionmailbox 6.1.4.7
Using rails 6.1.4.7
==  CreateActiveStorageTables: migrating ======================================
-- create_table(:active_storage_blobs)
D, [2022-03-25T07:47:34.880170 #91008] DEBUG -- :    (6.4ms)  CREATE TABLE `active_storage_blobs` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `key` varchar(255) NOT NULL, `filename` varchar(255) NOT NULL, `content_type` varchar(255), `metadata` text, `byte_size` bigint NOT NULL, `checksum` varchar(255) NOT NULL, `created_at` datetime NOT NULL, UNIQUE INDEX `index_active_storage_blobs_on_key` (`key`))
   -> 0.0069s
-- create_table(:active_storage_attachments)
D, [2022-03-25T07:47:34.888578 #91008] DEBUG -- :    (8.1ms)  CREATE TABLE `active_storage_attachments` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255) NOT NULL, `record_type` varchar(255) NOT NULL, `record_id` bigint NOT NULL, `blob_id` bigint NOT NULL, `created_at` datetime NOT NULL, INDEX `index_active_storage_attachments_on_blob_id` (`blob_id`), UNIQUE INDEX `index_active_storage_attachments_uniqueness` (`record_type`, `record_id`, `name`, `blob_id`), CONSTRAINT `fk_rails_c3b3935057`
FOREIGN KEY (`blob_id`)
  REFERENCES `active_storage_blobs` (`id`)
)
   -> 0.0084s
==  CreateActiveStorageTables: migrated (0.0153s) =============================

==  CreateActiveStorageVariantRecords: migrating ==============================
-- create_table(:active_storage_variant_records)
D, [2022-03-25T07:47:34.899508 #91008] DEBUG -- :    (9.5ms)  CREATE TABLE `active_storage_variant_records` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `blob_id` bigint NOT NULL, `variation_digest` varchar(255) NOT NULL, UNIQUE INDEX `index_active_storage_variant_records_uniqueness` (`blob_id`, `variation_digest`), CONSTRAINT `fk_rails_993965df05`
FOREIGN KEY (`blob_id`)
  REFERENCES `active_storage_blobs` (`id`)
)
   -> 0.0099s
==  CreateActiveStorageVariantRecords: migrated (0.0100s) =====================
```

### Actual behavior

end with this error: Column `blob_id` on table `active_storage_variant_records` does not match column `id` on `active_storage_blobs`, which has type `bigint(20)`.

```
$ ruby migration_bug.rb
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using rake 13.0.6
Using concurrent-ruby 1.1.10
Using zeitwerk 2.5.4
Using builder 3.2.4
Using erubi 1.10.0
Using nio4r 2.5.8
Using method_source 1.0.0
Using rack 2.2.3
Using thor 1.2.1
Using tzinfo 2.0.4
Using rack-test 1.1.0
Using sprockets 4.0.3
Using marcel 1.0.2
Using bundler 2.3.9
Using crass 1.0.6
Using mysql2 0.5.3
Using websocket-extensions 0.1.5
Using minitest 5.15.0
Using websocket-driver 0.7.5
Using racc 1.6.0
Using i18n 1.10.0
Using mini_mime 1.1.2
Using activesupport 6.1.5
Using nokogiri 1.13.3 (arm64-darwin)
Using activemodel 6.1.5
Using globalid 1.0.0
Using mail 2.7.1
Using activerecord 6.1.5
Using rails-dom-testing 2.0.3
Using activejob 6.1.5
Using loofah 2.15.0
Using rails-html-sanitizer 1.4.2
Using actionview 6.1.5
Using actionpack 6.1.5
Using actioncable 6.1.5
Using activestorage 6.1.5
Using actionmailer 6.1.5
Using railties 6.1.5
Using sprockets-rails 3.4.2
Using actionmailbox 6.1.5
Using actiontext 6.1.5
Using rails 6.1.5
==  CreateActiveStorageTables: migrating ======================================
-- create_table(:active_storage_blobs)
D, [2022-03-25T07:43:53.437458 #85774] DEBUG -- :    (8.0ms)  CREATE TABLE `active_storage_blobs` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `key` varchar(255) NOT NULL, `filename` varchar(255) NOT NULL, `content_type` varchar(255), `metadata` text, `byte_size` bigint NOT NULL, `checksum` varchar(255) NOT NULL, `created_at` datetime NOT NULL, UNIQUE INDEX `index_active_storage_blobs_on_key` (`key`))
   -> 0.0084s
-- create_table(:active_storage_attachments)
D, [2022-03-25T07:43:53.449683 #85774] DEBUG -- :    (11.8ms)  CREATE TABLE `active_storage_attachments` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255) NOT NULL, `record_type` varchar(255) NOT NULL, `record_id` bigint NOT NULL, `blob_id` bigint NOT NULL, `created_at` datetime NOT NULL, INDEX `index_active_storage_attachments_on_blob_id` (`blob_id`), UNIQUE INDEX `index_active_storage_attachments_uniqueness` (`record_type`, `record_id`, `name`, `blob_id`), CONSTRAINT `fk_rails_c3b3935057`
FOREIGN KEY (`blob_id`)
  REFERENCES `active_storage_blobs` (`id`)
)
   -> 0.0122s
==  CreateActiveStorageTables: migrated (0.0207s) =============================

==  CreateActiveStorageVariantRecords: migrating ==============================
-- create_table(:active_storage_variant_records)
D, [2022-03-25T07:43:53.462655 #85774] DEBUG -- :    (11.5ms)  CREATE TABLE `active_storage_variant_records` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `blob_id` int NOT NULL, `variation_digest` varchar(255) NOT NULL, UNIQUE INDEX `index_active_storage_variant_records_uniqueness` (`blob_id`, `variation_digest`), CONSTRAINT `fk_rails_993965df05`
FOREIGN KEY (`blob_id`)
  REFERENCES `active_storage_blobs` (`id`)
)
/Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query': Column `blob_id` on table `active_storage_variant_records` does not match column `id` on `active_storage_blobs`, which has type `bigint(20)`. To resolve this issue, change the type of the `blob_id` column on `active_storage_variant_records` to be :bigint. (For example `t.bigint :blob_id`). (ActiveRecord::MismatchedForeignKey)
Original message: Mysql2::Error: Cannot add foreign key constraint
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:206:in `block (2 levels) in execute'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:205:in `block in execute'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:204:in `execute'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/mysql/database_statements.rb:52:in `execute'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:322:in `create_table'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/mysql/schema_statements.rb:81:in `create_table'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:929:in `block in method_missing'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:897:in `block in say_with_time'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/benchmark.rb:296:in `measure'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:897:in `say_with_time'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:918:in `method_missing'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration/compatibility.rb:52:in `create_table'
	from migration_bug.rb:51:in `change'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:867:in `exec_migration'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/benchmark.rb:296:in `measure'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:850:in `block in migrate'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:849:in `migrate'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:663:in `migrate'
	from migration_bug.rb:62:in `<main>'
/Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query': Cannot add foreign key constraint (Mysql2::Error)
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:206:in `block (2 levels) in execute'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:205:in `block in execute'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:204:in `execute'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/mysql/database_statements.rb:52:in `execute'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:322:in `create_table'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/mysql/schema_statements.rb:81:in `create_table'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:929:in `block in method_missing'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:897:in `block in say_with_time'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/benchmark.rb:296:in `measure'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:897:in `say_with_time'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:918:in `method_missing'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration/compatibility.rb:52:in `create_table'
	from migration_bug.rb:51:in `change'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:867:in `exec_migration'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/benchmark.rb:296:in `measure'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:850:in `block in migrate'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:849:in `migrate'
	from /Users/marocchino/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activerecord-6.1.5/lib/active_record/migration.rb:663:in `migrate'
	from migration_bug.rb:62:in `<main>'
```

### System configuration
**Rails version**: 6.1.5

**Ruby version**: 3.1.1

**MySql version**:  5.7.31

**Comment by yahonda** [comment]
This issue should have been fixed at `6-1-stable` branch which includes https://github.com/rails/rails/pull/44691

```ruby
gem 'rails', github: "rails/rails", branch: "6-1-stable"
```

**Comment by marocchino** [comment]
I have confirmed that it works without any problems in that branch. Thank you!

**Comment by viroulep** [comment]
FYI for anyone passing by: we managed to workaround this issue by setting the migration version to 6.1 instead of 6.0 in the automatically generated migration, without having to make the gemfile point to `6-1-stable`.
