### ISSUE TITLE
Rails 6.1.5 ignores net-smtp LoadError

### ISSUE THREAD

**Issue by JunichiIto** [rails/rails#44799]
### Steps to reproduce

```
git clone git@github.com:JunichiIto/rails-6-1-mailer-sandbox.git
cd rails-6-1-mailer-sandbox
bin/setup
bin/rails test:system
```

### Expected behavior

Fails to start server because of net-smtp LoadError

### Actual behavior

Server can start up, then test fails with the error below:

```
2022-03-30 08:36:43 +0900 Rack app ("GET /" - (127.0.0.1)): #<NameError: uninitialized constant Mail::TestMailer

      delegate :deliveries, :deliveries=, to: Mail::TestMailer
                                                  ^^^^^^^^^^^^>
E
```

### System configuration
**Rails version**:

- 6.1.5

**Ruby version**:

- 3.1.1

### My investigation

The changes below were introduced since Rails 6.1.5:

- https://github.com/rails/rails/commit/13cdd7a6aef86b23c3410adff1d4f6eeefc72c67
- https://github.com/rails/rails/commit/13cdd7a6aef86b23c3410adff1d4f6eeefc72c67

However, the regexp should be `/net\/stmp/` because `error.message` is "cannot load such file -- net/smtp":

<img width="661" alt="Screen Shot 2022-03-30 at 8 04 32" src="https://user-images.githubusercontent.com/1148320/160723650-15782a6c-6ac1-43a3-8546-70e2b578d3e3.png">

Since net-smtp LoadError is ignored and mail gem is not loaded, the error "NameError: uninitialized constant Mail::TestMailer" is raised.

When I changed the regexp in my local box, the test fails like this:

```
You don't have net-smtp installed in your application. Please add it to your Gemfile and run bundle install
2022-03-30 08:47:59 +0900 Rack app ("GET /" - (127.0.0.1)): #<LoadError: cannot load such file -- net/smtp>
E

Error:
HomesTest#test_visiting_the_index:
LoadError: cannot load such file -- net/smtp
    app/mailers/application_mailer.rb:1:in `<main>'
    app/mailers/user_mailer.rb:1:in `<main>'
    app/controllers/home_controller.rb:3:in `index'


rails test test/system/homes_test.rb:4



Finished in 2.118014s, 0.4721 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

I guess this is the expected behavior.

**Comment by JunichiIto** [comment]
I confirmed this issue is already fixed, so I close.
https://github.com/rails/rails/commit/8687a4faacb0ec58f250ca072f7479a37e30fe71
