### ISSUE TITLE
EnumerableTests#test_doesnt_bust_constant_cache error since https://github.com/ruby/ruby/pull/5716

### ISSUE THREAD

**Issue by yahonda** [rails/rails#44835]
### Steps to reproduce

- Install Ruby 3.2.0dev

```ruby
cd activesupport
bin/test test/core_ext/enumerable_test.rb -n test_doesnt_bust_constant_cache
```

### Expected behavior
It should pass.

### Actual behavior
It gets `ArgumentError: unknown key: global_constant_state` error.

```ruby
$ bin/test test/core_ext/enumerable_test.rb -n test_doesnt_bust_constant_cache
Running 27 tests in a single process (parallelization threshold is 50)
Run options: -n test_doesnt_bust_constant_cache --seed 22647

# Running:

E

Error:
EnumerableTests#test_doesnt_bust_constant_cache:
ArgumentError: unknown key: global_constant_state
    /home/yahonda/src/github.com/rails/rails/activesupport/test/core_ext/enumerable_test.rb:365:in `stat'
    /home/yahonda/src/github.com/rails/rails/activesupport/test/core_ext/enumerable_test.rb:365:in `test_doesnt_bust_constant_cache'


bin/test test/core_ext/enumerable_test.rb:364



Finished in 0.000558s, 1792.8216 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**:$ ruby -v
ruby 3.2.0dev (2022-04-01T18:48:22Z master 6068da8937) [x86_64-linux]

**Comment by yahonda** [comment]
According to `git bisect`, this error has been introduced since https://github.com/ruby/ruby/commit/6068da8937d7e4358943f95e7450dae7179a7763

cc @byroot as you are the author of https://github.com/rails/rails/pull/44611

**Comment by yahonda** [comment]
Here are `RubyVM.stat` differences between Ruby 3.1.1 and Ruby 3.2.0.dev

- Ruby 3.1.1
```ruby
$ ruby -v
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux]
$ irb
irb(main):001:0> RubyVM.stat
=> {:global_constant_state=>1672, :class_serial=>1305, :global_cvar_state=>99}
irb(main):002:0>
```

- Current Ruby 3.2.0.dev
```ruby
$ ruby -v
ruby 3.2.0dev (2022-04-01T18:48:22Z master 6068da8937) [x86_64-linux]
$ irb
irb(main):001:0> RubyVM.stat
=>
{:class_serial=>1307,
 :global_cvar_state=>99,
 :constant_cache=>
  {:StdioInputMethod=>1,
   :Terminfo=>1,
   :ANCHORED_VERSION_PATTERN=>1,
   :Fiddle=>4,
   :Thread=>2,
   :Importer=>1,
   :Gem=>148,
   :SingleLine=>1,
   :IO=>4,
   :PrettyPrint=>4,
   :StandardError=>12,
   :Handle=>1,
   :ArgumentError=>1,
   :DLError=>1,
   :Function=>4,
   :TOPLEVEL_BINDING=>2,
   :SyntaxError=>1,
   :LoadError=>5,
   :InstructionSequence=>3,
   :PPMethods=>2,
   :ObjectMixin=>1,
   :Inspector=>7,
   :INSPECTORS=>4,
   :Errno=>1,
   :Correctable=>2,
   :Color=>2,
   :FRESH=>2,
   :RingBuffer=>1,
   :STDIN_FILE_NAME=>1,
   :InputMethod=>4,
   :HistorySavingAbility=>3,
   :TYPES=>1,
   :Mutex=>1,
   :MagicFile=>1,
   :DEBUG_RESOLVER=>1,
   :InputCompletor=>3,
   :ComposedSet=>1,
   :STDIN=>5,
   :STDOUT=>4,
   :CompletionProc=>1,
   :PerfectMatchedProc=>1,
   :BASIC_WORD_BREAK_CHARACTERS=>1,
   :SHOW_DOC_DIALOG=>1,
   :NON_PRINTING_START_INDEX=>2,
   :Stats=>1,
   :WIDTH_SCANNER=>2,
   :OSC_REGEXP_INDEX=>2,
   :NON_PRINTING_END_INDEX=>2,
   :PP=>6,
   :RUBYGEMS_ACTIVATION_MONITOR=>6,
   :MBCharWidthRE=>1,
   :CSI_REGEXP_INDEX=>3,
   :IRB=>65,
   :File=>88,
   :DependencyRequest=>4,
   :Molinillo=>6,
   :GRAPHEME_CLUSTER_INDEX=>4,
   :DEFAULT=>3,
   :Irb=>1,
   :Numeric=>3,
   :DependencyGraph=>3,
   :EscapedPairs=>1,
   :ENCODING_SPEC_RE=>1,
   :Lexer=>2,
   :State=>3,
   :Context=>3,
   :ExtendCommandBundle=>1,
   :Elem=>1,
   :CompletionRequireProc=>1,
   :RubyLex=>2,
   :SINGLE_POSSIBILITY_CONSTRAINT_PENALTY=>1,
   :Float=>1,
   :Delegator=>3,
   :CParser=>1,
   :INFINITY=>1,
   :ALT_SEPARATOR=>1,
   :NOT_FOUND=>1,
   :ERROR_TOKENS=>1,
   :CURRENT=>1,
   :Resolution=>1,
   :NULL=>1,
   :Edge=>1,
   :Set=>1,
   :Log=>1,
   :VERSION=>2,
   :UNTAINT=>12,
   :WIN_PATTERNS=>1,
   :CompletionState=>2,
   :NORMAL=>2,
   :LOADED_SPECS_MUTEX=>3,
   :StubSpecification=>2,
   :Reline=>106,
   :Unicode=>9,
   :PROMPT_LIST_CACHE_TIMEOUT=>1,
   :Specification=>11,
   :NullChecker=>1,
   :AddVertex=>1,
   :Tag=>1,
   :AddEdgeNoCircular=>1,
   :Ripper=>10,
   :SetPayload=>1,
   :RequestSet=>1,
   :Key=>2,
   :WorkSpace=>1,
   :Dependency=>8,
   :CursorPos=>3,
   :DialogRenderInfo=>1,
   :Requirement=>8,
   :Object=>1,
   :Core=>2,
   :Class=>2,
   :ATTR_READER_NAMES=>1,
   :Module=>5,
   :Kernel=>1,
   :Vertex=>1,
   :BasicObject=>1,
   :IOGate=>43,
   :ENOENT=>1,
   :Dir=>3,
   :String=>23,
   :Array=>6,
   :Hash=>6,
   :PathSupport=>1,
   :NilClass=>1,
   :Deprecate=>1,
   :PossibilitySet=>2,
   :RUBY_VERSION=>11,
   :RUBY_PLATFORM=>3,
   :RUBY_PATCHLEVEL=>1,
   :OPT_TABLE=>2,
   :RUBY_ENGINE=>7,
   :KillRing=>1,
   :DialogProc=>1,
   :RbConfig=>14,
   :CONFIG=>14,
   :ANSI=>5,
   :GeneralIO=>1,
   :AbstractSyntaxTree=>1,
   :EXCB=>3,
   :OVERRIDE_PRIVATE_ONLY=>1,
   :OVERRIDE_ALL=>1,
   :NO_OVERRIDE=>1,
   :Util=>2,
   :Time=>5,
   :DEFAULT_DIALOG_PROC_AUTOCOMPLETE=>1,
   :ARGV=>2,
   :RUBY_DESCRIPTION=>1,
   :UTF_8=>6,
   :US_ASCII=>1,
   :TrueClass=>2,
   :FalseClass=>2,
   :ResolutionState=>4,
   :Encoding=>11,
   :DEFAULT_DIALOG_CONTEXT=>2,
   :HISTORY=>1,
   :Platform=>21,
   :RUBY=>8,
   :DialogProcScope=>1,
   :TSort=>4,
   :DateTimeFormat=>1,
   :Dialog=>1,
   :Signal=>6,
   :Version=>15,
   :Forwardable=>3,
   :SingleForwardable=>1,
   :ActivationRequest=>2,
   :ENV=>19,
   :Config=>1,
   :Struct=>5,
   :DependencyState=>1,
   :LineEditor=>1,
   :KeyStroke=>1,
   :Regexp=>5,
   :Binding=>1,
   :Installed=>1,
   :BestSet=>1,
   :History=>1,
   :PREFIX=>3,
   :ReadlineInputMethod=>1,
   :CSI_REGEXP=>1,
   :CurrentSet=>1,
   :PossibilityState=>1,
   :LOCALE_NAME_RE=>1,
   :LOCALE_DIR=>2,
   :Locale=>1,
   :CLEAR=>1,
   :Resolver=>15,
   :Source=>1,
   :EXPR_BEG=>2,
   :TOKEN_KEYWORDS=>1,
   :IRBRC_EXT=>2,
   :EXPR_ENDFN=>2,
   :TOKEN_SEQ_EXPRS=>1,
   :EXPR_FNAME=>1,
   :SymbolState=>1,
   :OPEN_MODE=>1,
   :StubLine=>2,
   :NO_EXTENSIONS=>1,
   :REQUIRE_PATHS=>1,
   :REQUIRE_PATH_LIST=>1,
   :KeyActor=>3,
   :Emacs=>1,
   :ViInsert=>1,
   :ViCommand=>1,
   :Marshal=>3,
   :OPS=>2,
   :PATTERN_RAW=>1,
   :VERSION_PATTERN=>1,
   :PATTERN=>1,
   :DefaultRequirement=>3,
   :MAJOR_VERSION=>1,
   :MINOR_VERSION=>1,
   :Ractor=>1,
   :DefaultPrereleaseRequirement=>1,
   :Symbol=>10,
   :FileInputMethod=>1,
   :ReidlineInputMethod=>4,
   :RubyVM=>8}}
irb(main):002:0>
```

**Comment by casperisfine** [comment]
Thanks @yahonda, it's a result of https://bugs.ruby-lang.org/issues/18589, I'll take care of updating the test.

**Comment by casperisfine** [comment]
Fixed by https://github.com/ruby/ruby/commit/42000664be43f8c70322557703003b9141cfb28f
