### ISSUE TITLE
Rolback remove_column with defined type in migration change method causes ArgumentError: wrong number of arguments (given 2, expected 3)

### ISSUE THREAD

**Issue by deepj** [rails/rails#44901]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :payments, force: true do |t|
    t.bigint :region_id
  end
end

class Payment < ActiveRecord::Base
end

class RollbackBug < ActiveRecord::Migration[7.0]
  def change
    remove_column :payments, :region_id, type: :bigint
  end
end

class BugTest < Minitest::Test
  def test_migration_down
    RollbackBug.migrate(:down)
    Payment.reset_column_information
  end
end
```

### Expected behavior

I can use rollback in this type of migration. According Rails docs this would be a legit call of `remove_column` method https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_column

### Actual behavior

```
==  RollbackBug: reverting ====================================================
-- add_column(:payments, :region_id, {:type=>:bigint})
E

Finished in 0.001362s, 734.2144 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_migration_down:
ArgumentError: wrong number of arguments (given 2, expected 3)
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/sqlite3_adapter.rb:244:in `add_column'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:931:in `block in method_missing'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:899:in `block in say_with_time'
    ~/.rubies/ruby-3.1.2/lib/ruby/3.1.0/benchmark.rb:296:in `measure'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:899:in `say_with_time'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:920:in `method_missing'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration/command_recorder.rb:126:in `block in replay'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration/command_recorder.rb:125:in `each'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration/command_recorder.rb:125:in `replay'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:743:in `revert'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:867:in `exec_migration'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:853:in `block (2 levels) in migrate'
    ~/.rubies/ruby-3.1.2/lib/ruby/3.1.0/benchmark.rb:296:in `measure'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:852:in `block in migrate'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:851:in `migrate'
    ~/.gem/ruby/3.1.2/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:665:in `migrate'
    ar_bug.rb:40:in `test_migration_down'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
~

```

### System configuration
**Rails version**: 7.0.2.3

**Ruby version**: Ruby 3.1.2

**Comment by fatkodima** [comment]
It needs to be rewritten as: `remove_column :payments, :region_id, :bigint`, see https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_column

**Comment by deepj** [comment]
@fatkodima ah, I mixed it up with `remove_columns` where is `type` as a keyword. My bad. Thank you for correction me. Closing
