### ISSUE TITLE
ActiveRecord::Base abstract class with method none invalid for comparison

### ISSUE THREAD

**Issue by Viktor-Ivliev** [rails/rails#44905]
Rails: 7.0.2.3
ruby: 3.1.2
gem: pg (1.3.5) and pg (1.3.4)

```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class User < ApplicationRecord
end

```

examples:

```
ApplicationRecord.none => []
ApplicationRecord.none.to_sql
TypeError: no implicit conversion of nil into String 
from /home/karl/.rbenv/versions/3.1.2/gemsets/mobile_coach/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/postgresql/utils.rb:26:in `quote_ident'
```

```
User.none == User.none => true
```

```
ApplicationRecord.none == User.none 
TypeError: no implicit conversion of nil into String 
from /home/karl/.rbenv/versions/3.1.2/gemsets/mobile_coach/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/postgresql/utils.rb:26:in `quote_ident'
```

quote_ident - can't work with [nil, nil].

-----

In rails 6.1.5 it works correctly:
pg (1.3.4)

```
ApplicationRecord.none.to_sql => ""
ApplicationRecord.none == User.none => true
```

**Comment by gardnerapp** [comment]
Could you post the whole stack trace?

**Comment by Viktor-Ivliev** [comment]
> Could you post the whole stack trace?

Unfortunately, this is the entire stack. This is also evident on new applications.

```rb
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.3"
gem "sprockets-rails"
gem 'pg'
gem "puma", "~> 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
group :development do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "web-console"
end

```
rails c

![Выделение_628](https://user-images.githubusercontent.com/6106270/163778428-be03c8ee-dc87-4255-bc08-0c4427f12623.png)

**Comment by fatkodima** [comment]
What is the use case for `ApplicationRecord.none`? Since `ApplicationRecord` is abstract and does not have a table, I personally do not expect any meaningful result from `to_sql`.

This change was introduced by https://github.com/rails/rails/pull/42232.
cc @byroot

**Comment by Viktor-Ivliev** [comment]
> What is the use case for `ApplicationRecord.none`? Since `ApplicationRecord` is abstract and does not have a table, I personally do not expect any meaningful result from `to_sql`.
> 
> This change was introduced by #42232. cc @byroot

Thanks for the explanation.

It was an old code in which, depending on the condition, certain groups of users had to be returned, or in another case `ApplicationRecord.none`.

Here is a brief example:

```
def recipients_per_group(group)
      case group.to_sym
      when :example_grop_user1 then Profiles::UserGrop1
      when :example_grop_user2 then other_scope.user_grop2
      .......
      else ApplicationRecord.none
      end
end

scope = subject.recipients_per_group(:non_existing_group)
scope.inludes(:relationships).where(created_at: ...1.year.ago)
```

**Comment by byroot** [comment]
Thanks for the ping. I'm on the fence between trying to get the old behavior back, or to have `#none` raise when called on an abstract class.

I'l probably restore the old behavior though, as even though it wasn't documented it used to work.

**Comment by Viktor-Ivliev** [comment]
> Thanks for the ping. I'm on the fence between trying to get the old behavior back, or to have `#none` raise when called on an abstract class.
> 
> I'l probably restore the old behavior though, as even though it wasn't documented it used to work.

Thanks

**Comment by Viktor-Ivliev** [comment]
I close the task because there is a solution here https://github.com/rails/rails/pull/44959
