### ISSUE TITLE
JavaScript directory missing in my rails 7.0.2.3 app directory

### ISSUE THREAD

**Issue by omokehinde** [rails/rails#44952]
### Steps to reproduce
I am using 7.0.2.3 and ruby ruby 3.1.0p0 on windows 11 to build a rails application. when I run

```ruby
# rails new app_name
```

### System configuration
**Rails 7.0.2.3**:

**Ruby 3.1.0p0**:

**Comment by psantos10** [comment]
I could not reproduce the issue. Can you please run the command again and share the output of the `rails new` command? (the output after installing gems)

**Comment by omokehinde** [comment]
@psantos10 
create
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in C:/Users/OMOKEHINDE/Documents/RailsProjects/app_name/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/new_framework_defaults_7_0.rb
      create  config/initializers/permissions_policy.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_7_0.rb
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies........
Using rake 13.0.6
Using concurrent-ruby 1.1.10
Using racc 1.6.0
Using minitest 5.15.0
Using builder 3.2.4
Using erubi 1.10.0
Using crass 1.0.6
Using rack 2.2.3
Using nio4r 2.5.8
Using digest 3.1.0
Using timeout 0.2.0
Using strscan 3.0.1
Using websocket-extensions 0.1.5
Using marcel 1.0.2
Using mini_mime 1.1.2
Using bundler 2.3.3
Using public_suffix 4.0.7
Using bindex 0.8.1
Using msgpack 1.5.1
Using matrix 0.4.2
Using regexp_parser 2.3.1
Using childprocess 4.1.0
Using rexml 3.2.5
Using method_source 1.0.0
Using thor 1.2.1
Using zeitwerk 2.5.4
Using rubyzip 2.3.2
Using sqlite3 1.4.2
Using i18n 1.10.0
Using tzinfo 2.0.4
Using nokogiri 1.13.4 (x64-mingw-ucrt)
Using rack-test 1.1.0
Using websocket-driver 0.7.5
Using mail 2.7.1
Using net-protocol 0.1.3
Using addressable 2.8.0
Using puma 5.6.4
Using sprockets 4.0.3
Using bootsnap 1.11.1
Using selenium-webdriver 4.1.0
Using activesupport 7.0.2.3
Using loofah 2.16.0
Using net-imap 0.2.3
Using net-pop 0.1.1
Using net-smtp 0.3.1
Using xpath 3.2.0
Using rails-dom-testing 2.0.3
Using rails-html-sanitizer 1.4.2
Using globalid 1.0.0
Using activemodel 7.0.2.3
Using webdrivers 5.0.0
Using capybara 3.36.0
Using actionview 7.0.2.3
Using activejob 7.0.2.3
Using activerecord 7.0.2.3
Using actionpack 7.0.2.3
Using jbuilder 2.11.5
Using actioncable 7.0.2.3
Using activestorage 7.0.2.3
Using actionmailer 7.0.2.3
Using railties 7.0.2.3
Using sprockets-rails 3.4.2
Using actionmailbox 7.0.2.3
Using actiontext 7.0.2.3
Using importmap-rails 1.0.3
Using stimulus-rails 1.0.4
Using turbo-rails 1.0.1
Using web-console 4.2.0
Using rails 7.0.2.3
Bundle complete! 15 Gemfile dependencies, 69 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  importmap:install
rails aborted!
TZInfo::DataSourceNotFound: tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install
C:/Users/OMOKEHINDE/Documents/RailsProjects/app_name/config/environment.rb:5:in `<main>'

Caused by:
TZInfo::DataSources::ZoneinfoDirectoryNotFound: None of the paths included in TZInfo::DataSources::ZoneinfoDataSource.search_path are valid zoneinfo directories.
C:/Users/OMOKEHINDE/Documents/RailsProjects/app_name/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
       rails  turbo:install stimulus:install
You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem.
You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem.

**Comment by omokehinde** [comment]
After following your steps I got: 
`rails aborted!
TZInfo::DataSourceNotFound: tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install
C:/Users/OMOKEHINDE/Documents/RailsProjects/app_name/config/environment.rb:5:in `<main>'

Caused by:
TZInfo::DataSources::ZoneinfoDirectoryNotFound: None of the paths included in TZInfo::DataSources::ZoneinfoDataSource.search_path are valid zoneinfo directories.
C:/Users/OMOKEHINDE/Documents/RailsProjects/app_name/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)`

**Comment by flavorjones** [comment]
@omokehinde Can you share with us the output from `gem env`? It would help determing whether and how we should update the default `tzinfo-data` line in the generated `Gemfile` to support systems like yours.

**Comment by omokehinde** [comment]
> 

After following this step by replacing `gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]` with `gem "tzinfo-data"` It was fixed. Is it possible to have just `gem "tzinfo-data"` in the boiler plate code generated when the app is being created with the platforms: %i[ mingw mswin x64_mingw jruby ] part commented out with instruction to comment it out in case it is needed for windows users that need it so that don't need it won't run into issues? Thanks for helping out. I am grateful!

**Comment by omokehinde** [comment]
> @omokehinde Can you share with us the output from `gem env`? It would help determing whether and how we should update the default `tzinfo-data` line in the generated `Gemfile` to support systems like yours.

Here it is:
`RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.3
  - RUBY VERSION: 3.1.0 (2021-12-25 patchlevel 0) [x64-mingw-ucrt]
  - INSTALLATION DIRECTORY: C:/Ruby31-x64/lib/ruby/gems/3.1.0
  - USER INSTALLATION DIRECTORY: C:/Users/OMOKEHINDE/.local/share/gem/ruby/3.1.0
  - RUBY EXECUTABLE: C:/Ruby31-x64/bin/ruby.exe
  - GIT EXECUTABLE: C:\Program Files\Git\cmd/git.EXE
  - EXECUTABLE DIRECTORY: C:/Ruby31-x64/bin
  - SPEC CACHE DIRECTORY: C:/Users/OMOKEHINDE/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
     - ruby
     - x64-mingw-ucrt
  - GEM PATHS:
     - C:/Ruby31-x64/lib/ruby/gems/3.1.0
     - C:/Users/OMOKEHINDE/.local/share/gem/ruby/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Program Files (x86)\Common Files\Oracle\Java\javapath,C:\Program Files\Java\jdk1.8.0_291\bin
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
     - C:\WINDOWS\System32\OpenSSH\
     - C:\Program Files\nodejs\
     - C:\Program Files\dotnet\
     - C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
     - C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
     - C:\ProgramData\chocolatey\bin
     - C:\flutter\bin
     - C:\Program Files\Git\cmd
     - C:\Users\OMOKEHINDE\AppData\Local\Android\Sdk\platform-tools
     - C:\Program Files\MongoDB\Server\4.4\bin
     - C:\Program Files\PostgreSQL\13\bin
     - C:\UnxUtils\usr\local\wbin
     - C:\Ruby31-x64\bin
     - C:\Program Files\MySQL\MySQL Shell 8.0\bin\
     - C:\Users\OMOKEHINDE\anaconda3
     - C:\Users\OMOKEHINDE\anaconda3\Library\mingw-w64\bin
     - C:\Users\OMOKEHINDE\anaconda3\Library\usr\bin
     - C:\Users\OMOKEHINDE\anaconda3\Library\bin
     - C:\Users\OMOKEHINDE\anaconda3\Scripts
     - C:\Users\OMOKEHINDE\AppData\Local\Microsoft\WindowsApps
     - C:\Users\OMOKEHINDE\AppData\Local\Programs\Microsoft VS Code\bin
     - C:\Users\OMOKEHINDE\AppData\Roaming\npm
     - C:\Users\OMOKEHINDE\.dotnet\tools
     - C:\Program Files\Java\jdk1.8.0_291\bin
     - C:\tools\dart-sdk\bin
     - C:\Users\OMOKEHINDE\AppData\Roaming\Pub\Cache\bin
     - C:\Users\OMOKEHINDE\AppData\Local\Programs\Python\Python36\Scripts
     - C:\Program Files\MySQL\MySQL Server 8.0\bin
     - C:\vips-dev-w64-web-8.12.1\vips-dev-8.12\bin`

**Comment by psantos10** [comment]
I think, your issue is related to this: https://github.com/ruby/setup-ruby/issues/193

**Comment by omokehinde** [comment]
> importmap:install

Yeah, I see it has nothing to do with rails but with ruby. So installing ruby 3.1 could fix this? How do I install multiple version on ruby on my windows machine? so I can confirm this.

**Comment by psantos10** [comment]
My recommendation would be: Don't use Windows for programming with Ruby. 

If you are on windows, you can use WSL2 .

**Comment by omokehinde** [comment]
> My recommendation would be: Don't use Windows for programming with Ruby.
> 
> If you are on windows, you can use WSL2 .

Yeah, thanks. I know coding ruby on windows is really complicated but doable(because of some gem, reddis, and a few bottlenecks like this). I just tried this on my WSL and it worked fine with redis setup when as creating the project with rails new command. But the version of ruby on my WSL is ruby 3.1. Do you know of uru? It allows you install and run multiple versions of ruby on windows.

**Comment by omokehinde** [comment]
> > > My recommendation would be: Don't use Windows for programming with Ruby.
> > > If you are on windows, you can use WSL2 .
> > 
> > 
> > Yeah, thanks. I know coding ruby on windows is really complicated but doable(because of some gem, reddis, and a few bottlenecks like this). I just tried this on my WSL and it worked fine with redis setup when as creating the project with rails new command. But the version of ruby on my WSL is ruby 3.1. Do you know of uru? It allows you install and run multiple versions of ruby on windows.
> 
> You can use a version manager. You have few options: asdf (https://asdf-vm.com/), rbenv (https://github.com/rbenv/rbenv) and rvm (https://rvm.io/)
> 
> I personally prefer and use `asdf` since it is not only for ruby. I can add plugins for any language.
> 
> ![image](https://user-images.githubusercontent.com/374424/165517244-00b2d978-3a76-4762-8cd6-37de4cd8482a.png)
> 
> The output of my `asdf list` . By the way, this is on Windows (Ubuntu WSL2)

Thanks, I currently use rvm but seldomly use WSL maybe I will start using it more and try out one of these version manager probably asdf. Thanks a bunch for helping out, I have learnt a lot,

**Comment by SkipKayhil** [comment]
I wanted to follow up on the loose end about what platform should be specified in the Gemfile:

I found rubygems/rubygems#5269 which seems to indicate that `x64-mingw-ucrt` should _probably_ be included in `x64_mingw` so no changes would be necessary in Rails. Whether or not that changes, I think we will have to wait for that issue to be resolved.

**Comment by omokehinde** [comment]
@psantos10 After following your steps and running `rails importmap:install` I found out that the javascript directory has just application.js file and the other folders and files that supposed to be there are missing. I have another rails project I created from the WSL terminal containing these missing files and directory, can I copy these into my existing project and expect it to work? Or is there any command I am supposed to run to generate these?

**Comment by unfazedEgnimadevspace** [comment]
Hi, I am currently having the same problems too, how do I go about the missing files in the JavaScript directory

**Comment by omokehinde** [comment]
> Hi, I am currently having the same problems too, how do I go about the missing files in the JavaScript directory

Are you on windows? If so you can use WSL to recreate the project, if you cannot start the project from scratch you create a new project from WSL and copy the missing directory from to your existing project. It should work, that is what I am currently doing. But as @psantos10 has said avoid doing rails development on windows
