### ISSUE TITLE
AzureStorage crush after Ruby & Rails upgrade 

### ISSUE THREAD

**Issue by equivalent** [rails/rails#44960]
### Steps to reproduce

I've upgraded my Ruby form 2.7.4 to 3.1.1 & Rails from 6.1 to 7.0.2.3 

in my Gemfile I have:

```
gem "rails", "~> 7.0.0"
# ...
gem "azure-storage-blob", require: false
# ...
```

If I run server with   `bundle exec puma -p 80` In production (development is fine)

it will crush  with

```
v3webserver_1  | running puma
v3webserver_1  | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
v3webserver_1  | /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/configurator.rb:33:in `rescue in resolve': Missing service adapter for "AzureStorage" (RuntimeError)
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/configurator.rb:29:in `resolve'
# ...
 ! Unable to load application: RuntimeError: Missing service adapter for "AzureStorage"
```

(full log in bottom of the ticket description)

### Reason 

in https://github.com/rails/rails/blob/main/activestorage/lib/active_storage/service/azure_storage_service.rb:3

there is a line:

```
gem "azure-storage-blob", ">= 2.0"
```

I'm suspecting that in Ruby 3.1.1 or in bundler  2.3.12. there is something that is causing not to load this. Or this may be due to some eager load option as this happens only in production environment (development puma is fine )

### System configuration
**Rails version**: 7.0.2.3

**Ruby version**: 3.1.1

**bundler version**:  2.3.12

--------------------------------------------------

### full log

```
Attaching to current_v3webserver_1
v3webserver_1  | running puma
v3webserver_1  | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
v3webserver_1  | /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/configurator.rb:33:in `rescue in resolve': Missing service adapter for "AzureStorage" (RuntimeError)
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/configurator.rb:29:in `resolve'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/configurator.rb:17:in `build'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/mirror_service.rb:23:in `block in build'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/mirror_service.rb:23:in `collect'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/mirror_service.rb:23:in `build'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/configurator.rb:17:in `build'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/registry.rb:13:in `block in fetch'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/registry.rb:11:in `fetch'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/registry.rb:11:in `fetch'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/engine.rb:157:in `block (2 levels) in <class:Engine>'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/app/models/active_storage/blob.rb:410:in `<main>'
v3webserver_1  | 	from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
v3webserver_1  | 	from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:244:in `block (2 levels) in eager_load'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
v3webserver_1  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application/finisher.rb:78:in `block in <module:Finisher>'
v3webserver_1  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instance_exec'
v3webserver_1  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
v3webserver_1  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
v3webserver_1  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
v3webserver_1  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
v3webserver_1  | 	from /app/config/environment.rb:5:in `<top (required)>'
v3webserver_1  | 	from config.ru:3:in `require_relative'
v3webserver_1  | 	from config.ru:3:in `block in <main>'
v3webserver_1  | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
v3webserver_1  | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
v3webserver_1  | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
v3webserver_1  | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/lib/puma/configuration.rb:348:in `load_rackup'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/lib/puma/configuration.rb:270:in `app'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/lib/puma/runner.rb:150:in `load_and_bind'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/lib/puma/cluster.rb:357:in `run'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/lib/puma/launcher.rb:182:in `run'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/lib/puma/cli.rb:81:in `run'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/bin/puma:10:in `<top (required)>'
v3webserver_1  | 	from /usr/local/bundle/bin/puma:25:in `load'
v3webserver_1  | 	from /usr/local/bundle/bin/puma:25:in `<top (required)>'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `load'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:23:in `run'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:483:in `exec'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
v3webserver_1  | 	from /usr/local/bundle/bin/bundle:25:in `load'
v3webserver_1  | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
v3webserver_1  | /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/rubygems_integration.rb:291:in `block (2 levels) in replace_gem': can't activate azure-storage-blob (>= 2.0), already activated azure-storage-blob-1.1.0. Make sure all dependencies are added to Gemfile. (Gem::LoadError)
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/azure_storage_service.rb:3:in `<main>'
v3webserver_1  | 	from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
v3webserver_1  | 	from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/configurator.rb:30:in `resolve'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/configurator.rb:17:in `build'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/mirror_service.rb:23:in `block in build'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/mirror_service.rb:23:in `collect'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/mirror_service.rb:23:in `build'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/configurator.rb:17:in `build'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/registry.rb:13:in `block in fetch'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/registry.rb:11:in `fetch'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/service/registry.rb:11:in `fetch'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/lib/active_storage/engine.rb:157:in `block (2 levels) in <class:Engine>'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
v3webserver_1  | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
v3webserver_1  | 	from /usr/local/bundle/gems/activestorage-7.0.2.3/app/models/active_storage/blob.rb:410:in `<main>'
v3webserver_1  | 	from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
v3webserver_1  | 	from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:244:in `block (2 levels) in eager_load'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
v3webserver_1  | 	from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
v3webserver_1  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application/finisher.rb:78:in `block in <module:Finisher>'
v3webserver_1  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instance_exec'
v3webserver_1  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
v3webserver_1  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
v3webserver_1  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
v3webserver_1  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
v3webserver_1  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
v3webserver_1  | 	from /app/config/environment.rb:5:in `<top (required)>'
v3webserver_1  | 	from config.ru:3:in `require_relative'
v3webserver_1  | 	from config.ru:3:in `block in <main>'
v3webserver_1  | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
v3webserver_1  | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
v3webserver_1  | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
v3webserver_1  | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/lib/puma/configuration.rb:348:in `load_rackup'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/lib/puma/configuration.rb:270:in `app'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/lib/puma/runner.rb:150:in `load_and_bind'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/lib/puma/cluster.rb:357:in `run'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/lib/puma/launcher.rb:182:in `run'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/lib/puma/cli.rb:81:in `run'
v3webserver_1  | 	from /usr/local/bundle/gems/puma-5.6.4/bin/puma:10:in `<top (required)>'
v3webserver_1  | 	from /usr/local/bundle/bin/puma:25:in `load'
v3webserver_1  | 	from /usr/local/bundle/bin/puma:25:in `<top (required)>'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `load'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:23:in `run'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:483:in `exec'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
v3webserver_1  | 	from /usr/local/bundle/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
v3webserver_1  | 	from /usr/local/bundle/bin/bundle:25:in `load'
v3webserver_1  | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
v3webserver_1  | [18] Puma starting in cluster mode...
v3webserver_1  | [18] * Puma version: 5.6.4 (ruby 3.1.1-p18) ("Birdie's Version")
v3webserver_1  | [18] *  Min threads: 5
v3webserver_1  | [18] *  Max threads: 5
v3webserver_1  | [18] *  Environment: staging
v3webserver_1  | [18] *   Master PID: 18
v3webserver_1  | [18] *      Workers: 3
v3webserver_1  | [18] *     Restarts: (✔) hot (✖) phased
v3webserver_1  | [18] * Preloading application
v3webserver_1  | [18] ! Unable to load application: RuntimeError: Missing service adapter for "AzureStorage"
```

**Comment by SkipKayhil** [comment]
This looks like expected behavior to me. The requirement in `active_storage_service` was updated in 0920b02 because version 1.1.0 of the gem doesn't support Ruby > 2.5

To fix this you should upgrade your `azure-storage-blob` in Gemfile to be `>= 2.0` as well

**Comment by equivalent** [comment]
@SkipKayhil  you deserve a cookie !!

yes you right as soon as I've updated my  Gemfile to 

```
gem 'azure-storage-blob', "~> 2.0", require: false
```

...it started to work. 

Now I see it's obvious `gem "azure-storage-blob", ">= 2.0"` I'm stupid not to realize  this when reading https://github.com/rails/rails/blob/main/activestorage/lib/active_storage/service/azure_storage_service.rb:3


Maybe it's worth mentioning this in official ActiveStorage guide https://edgeguides.rubyonrails.org/active_storage_overview.html So I've created PR https://github.com/rails/rails/pull/44965

<img width="672" alt="Screenshot 2022-04-26 at 21 01 24" src="https://user-images.githubusercontent.com/721990/165374689-3bbacf89-5acf-4bc7-849d-c919e5d7c479.png">
