### ISSUE TITLE
XMLMini does not requre IsolatedExecutionState

### ISSUE THREAD

**Issue by singpolyma** [rails/rails#45050]
### Steps to reproduce

```ruby
require "active_support/xml_mini"

ActiveSupport::XmlMini.parse("<stuff />")
```

### Expected behavior

It should parse.

### Actual behavior

It raises:

```
3: from /home/singpolyma/src/sgx-jmp/.gems/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/xml_mini.rb:11:in `<top (required)>'
	2: from .../gems/activesupport-7.0.3/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
	1: from .../gems/activesupport-7.0.3/lib/active_support/xml_mini.rb:103:in `backend='
.../.gems/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
```

### System configuration
**Rails version**: 7

**Ruby version**: 2.7.4

**Comment by SkipKayhil** [comment]
Hey @singpolyma, thanks for the report. To use any components of Active Support you must `require 'active_support'` first. See https://github.com/rails/rails/issues/43889#issuecomment-995364395
