### ISSUE TITLE
Configuration for multiple databases unable to establish connection.

### ISSUE THREAD

**Issue by dvodvo** [rails/rails#45107]
Context: Building a distributed database system with multiple mixed single vs main/replica databases.

[not directly related to the issue, but relevant to this observer] I would like to mention that [the relative rails guide](https://guides.rubyonrails.org/active_record_multiple_databases.html) is lacking on a couple of fundamental points.
1) postgresql has mechanisms for ensuring replication for users with that role attributed.  I have to assume that these users needed to be created with that attibuted role given the guide is totally mute on the subject of user creation.  
2) postresql has its own instruction set for setting up replicating data. This leads to a second assumption : Rails handles this aspect as it knows about both data stores in database.yml.  If this assumption is wrong then the guide is utterly lacking.

With two assumptions we are entering a geometric sphere of possibilities.  Additionally these two are, on the face of it contradictory: first case => intervene on postgresql, second case => not.
[end of mention]

### Steps to reproduce
```
production:
  primary:
    adapter: postgresql
    encoding: unicode
    host: central.domain.ws
    username: deploy_root
    password: pwd_root
    database: users
    pool: 50
  primary_replica:
    adapter: postgresql
    encoding: unicode
    host: replica.domain.ws
    username: deploy_readonly
    password: pwd_readonly
    database: users
    pool: 50
    replica: true
  forum:
    adapter: postgresql
    encoding: unicode
    database: fora
    username: deploy_root
    password: pwd_root
    host: central.domain.ws
    migrations_paths: db/forum_migrate
  forum_replica:
    adapter: postgresql
    encoding: unicode
    database: fora
    username: deploy_readonly
    password: pwd_readonly
    host: replica.domain.ws
    replica: true
  franchise:
    adapter: postgresql
    encoding: unicode
    database: franchise
    username: deploy_root
    password: pwd_root
    host: central.domain.ws
    migrations_paths: db/franchise_migrate
```
### Expected behavior
Migration proceeds as by design

### Actual behavior
Two error behaviours are observed and they are not consistent with each other.

The second came about as a means of testing the migration command.  Note: `bin/rails db:migrate` would not run.
Logging into the server and launching from the releases directory
```
bundle exec rake db:migrate
rake aborted!
ActiveRecord::DatabaseConnectionError: There is an issue connecting to your database with your username/password, username: deploy_root.

Please check your database configuration to ensure the username/password are valid.
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `public_send'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `new_connection'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:700:in `checkout_new_connection'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:679:in `try_to_checkout_new_connection'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:640:in `acquire_connection'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:341:in `checkout'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `connection'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_handler.rb:211:in `retrieve_connection'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_handling.rb:313:in `retrieve_connection'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_handling.rb:280:in `connection'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:282:in `block in db_configs_with_versions'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:280:in `each'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:280:in `db_configs_with_versions'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/railties/databases.rake:95:in `block (2 levels) in <main>'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/deploy_root/.rbenv/versions/3.1.0/bin/bundle:25:in `load'
/home/deploy_root/.rbenv/versions/3.1.0/bin/bundle:25:in `<main>'

Caused by:
PG::ConnectionBad: connection to server at "::1", port 5432 failed: FATAL:  password authentication failed for user "deploy_root"
connection to server at "::1", port 5432 failed: FATAL:  password authentication failed for user "deploy_root"
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/pg-1.3.5/lib/pg/connection.rb:637:in `async_connect_or_reset'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/pg-1.3.5/lib/pg/connection.rb:707:in `new'
/home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/pg-1.3.5/lib/pg.rb:69:in `connect'
```
The authentication error is curious - have tried encapsulating the strings in quotes, but there is no change in behaviour.  This is also different messaging form the first set of errors

The initial error was observed upon a migration task. In production mode, upon deployment (domains sanitised):

```
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
      01 rake aborted!
      01 ActiveRecord::ConnectionNotEstablished: could not translate host name "central.domain.ws" to address: Name or service not known
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:87:in `rescue in new_client'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connectio…
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `public_send'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `new_connectio…
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:700:in `checkout_new_…
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:679:in `try_to_checko…
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:640:in `acquire_conne…
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:341:in `checkout'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `connection'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_handler.rb:211:in `retrieve_c…
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_handling.rb:313:in `retrieve_connection'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_handling.rb:280:in `connection'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:282:in `block in db_configs_with_versions'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:280:in `each'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:280:in `db_configs_with_versions'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/railties/databases.rake:95:in `block (2 levels) in <main>'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
      01 /home/deploy_root/.rbenv/versions/3.1.0/bin/bundle:25:in `load'
      01 /home/deploy_root/.rbenv/versions/3.1.0/bin/bundle:25:in `<main>'
      01
      01 Caused by:
      01 PG::ConnectionBad: could not translate host name "central.domain.ws" to address: Name or service not known
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/pg-1.3.5/lib/pg/connection.rb:702:in `connect_start'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/pg-1.3.5/lib/pg/connection.rb:702:in `new'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/pg-1.3.5/lib/pg.rb:69:in `connect'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:78:in `new_client'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connectio…
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `public_send'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `new_connectio…
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:700:in `checkout_new_…
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:679:in `try_to_checko…
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:640:in `acquire_conne…
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:341:in `checkout'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `connection'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/connection_handler.rb:211:in `retrieve_c…
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_handling.rb:313:in `retrieve_connection'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_handling.rb:280:in `connection'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:282:in `block in db_configs_with_versions'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:280:in `each'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:280:in `db_configs_with_versions'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/railties/databases.rake:95:in `block (2 levels) in <main>'
      01 /home/deploy_root/franchise/shared/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
      01 /home/deploy_root/.rbenv/versions/3.1.0/bin/bundle:25:in `load'
      01 /home/deploy_root/.rbenv/versions/3.1.0/bin/bundle:25:in `<main>'
      01 Tasks: TOP => db:migrate
      01 (See full trace by running task with --trace)
```

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.1.0

**Comment by matthewd** [comment]
> If this assumption is wrong then the guide is utterly lacking.

Hmmm, the only thing I can see the guide potentially lacking is a paragraph that essentially says "how to set up database replication: don't -- if you're asking us, you almost certainly don't need it".

This functionality is important for applications of a certain scale, but it's very much structured as a "here's how to configure Rails to work with the existing replication arrangement established by your DBA team", not a guide to configuring database replication from scratch -- as you've found. I'm curious what path brought you there apparently expecting the latter? 

To address those opening assumptions: 1) as a project we have no opinion on how to configure replication on any particular database platform (but despite not having personally set up PG replication outside toy setups, I'm pretty sure that no, that user type is absolutely not for the purpose you're implying, and that would never work for any application). 2) if you wish to use replication, you'll need to set it up yourself, outside of Rails. We do handle creation of regular databases through `db:create` for development convenience, but the complexity and wildly unique requirements of a production multi-part database cluster are well outside our domain -- generally a DBA will rightfully limit any administrative access that Rails would have, well before an application reaches that scale, anyway.

---

As for your quoted errors: those are coming straight from the PG gem, reporting that your supplied credentials -- and in one case entire hostname -- are incorrect. If you were expecting us to deploy those resources: that's again outside our domain; especially in a production environment, everything your `database.yml` is pointing at should already exist. If you believe they do exist, I can't really speculate on why your database server and DNS server disagree.

**Comment by dvodvo** [comment]
Thank you matthewd.  This above a practice set-up, as there are a number of motives pointing in this direction.  

This bit removed all the assumptions: "here's how to configure Rails to work with the existing replication arrangement established by your DBA team".  Thus the guide does require an amendment
1) users, roles and replication functions are to be administered from within the database application sphere.
2) these should be set-up before configuring rails databases.

Yes?  

the DNS indication resolved in practice the issue (at some minor typo is just not seen in the sea of bigger things!)

**Comment by matthewd** [comment]
:+1:

Yeah, a PR to add that clarity would be welcome.
