### ISSUE TITLE
test_db:prepare_runs_seeds_once fails as ERROR:  relation "dogs" already exists

### ISSUE THREAD

**Issue by yahonda** [rails/rails#45114]
Managed to reproduce https://buildkite.com/rails/rails/builds/86357#61382cfd-f8b2-43b6-978d-6bc5fab4f780

### Steps to reproduce
```ruby
$ cd railties
$ bin/test test/application/rake/multi_dbs_test.rb --seed 32117 -n "/^(?:ApplicationTests::RakeTests::RakeMultiDbsTest#(?:test_db:abort_if_pending_migrations_works_on_all_databases|test_db:prepare_runs_seeds_once|test_db:prepare_setups_missing_database_without_clearing_existing_one))$/"
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ bin/test test/application/rake/multi_dbs_test.rb --seed 32117 -n "/^(?:ApplicationTests::RakeTests::RakeMultiDbsTest#(?:test_db:abort_if_pending_migrations_works_on_all_databases|test_db:prepare_runs_seeds_once|test_db:prepare_setups_missing_database_without_clearing_existing_one))$/"
Run options: --seed 32117 -n "/^(?:ApplicationTests::RakeTests::RakeMultiDbsTest#(?:test_db:abort_if_pending_migrations_works_on_all_databases|test_db:prepare_runs_seeds_once|test_db:prepare_setups_missing_database_without_clearing_existing_one))$/"

# Running:

.E

Error:
ApplicationTests::RakeTests::RakeMultiDbsTest#test_db:prepare_runs_seeds_once:
RuntimeError: rails command failed (1): bin/rails db:prepare 2>&1
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:687: warning: conflicting chdir during another chdir block
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:708: warning: conflicting chdir during another chdir block
Created database 'railties_test'
== 20220516233707 CreateBooks: migrating ======================================
-- create_table(:books)
   -> 0.0035s
== 20220516233707 CreateBooks: migrated (0.0036s) =============================

== 20220516233708 CreateRecipes: migrating ====================================
-- create_table(:recipes)
   -> 0.0031s
== 20220516233708 CreateRecipes: migrated (0.0031s) ===========================

== 20220516233708 CreateDogs: migrating =======================================
-- create_table(:dogs)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "dogs" already exists
/home/yahonda/src/github.com/rails/rails/tmp/d20220517-166172-cg0j15/app/db/animals_migrate/20220516233708_create_dogs.rb:3:in `change'
/home/yahonda/src/github.com/rails/rails/tmp/d20220517-166172-cg0j15/app/bin/rails:4:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "dogs" already exists
/home/yahonda/src/github.com/rails/rails/tmp/d20220517-166172-cg0j15/app/db/animals_migrate/20220516233708_create_dogs.rb:3:in `change'
/home/yahonda/src/github.com/rails/rails/tmp/d20220517-166172-cg0j15/app/bin/rails:4:in `<top (required)>'

Caused by:
PG::DuplicateTable: ERROR:  relation "dogs" already exists
/home/yahonda/src/github.com/rails/rails/tmp/d20220517-166172-cg0j15/app/db/animals_migrate/20220516233708_create_dogs.rb:3:in `change'
/home/yahonda/src/github.com/rails/rails/tmp/d20220517-166172-cg0j15/app/bin/rails:4:in `<top (required)>'
Tasks: TOP => db:prepare
(See full trace by running task with --trace)

    /home/yahonda/src/github.com/rails/rails/railties/test/isolation/abstract_unit.rb:390:in `rails'
    /home/yahonda/src/github.com/rails/rails/railties/test/application/rake/multi_dbs_test.rb:868:in `block (2 levels) in <class:RakeMultiDbsTest>'
    /home/yahonda/src/github.com/rails/rails/railties/test/application/rake/multi_dbs_test.rb:857:in `chdir'
    /home/yahonda/src/github.com/rails/rails/railties/test/application/rake/multi_dbs_test.rb:857:in `block in <class:RakeMultiDbsTest>'


bin/test test/application/rake/multi_dbs_test.rb:855

E

Error:
ApplicationTests::RakeTests::RakeMultiDbsTest#test_db:prepare_setups_missing_database_without_clearing_existing_one:
RuntimeError: rails command failed (1): bin/rails db:prepare 2>&1
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:687: warning: conflicting chdir during another chdir block
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:708: warning: conflicting chdir during another chdir block
== 20220516233706 CreateBooks: migrating ======================================
-- create_table(:books)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "books" already exists
/home/yahonda/src/github.com/rails/rails/tmp/d20220517-166171-cg0j15/app/db/migrate/20220516233706_create_books.rb:3:in `change'
/home/yahonda/src/github.com/rails/rails/tmp/d20220517-166171-cg0j15/app/bin/rails:4:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "books" already exists
/home/yahonda/src/github.com/rails/rails/tmp/d20220517-166171-cg0j15/app/db/migrate/20220516233706_create_books.rb:3:in `change'
/home/yahonda/src/github.com/rails/rails/tmp/d20220517-166171-cg0j15/app/bin/rails:4:in `<top (required)>'

Caused by:
PG::DuplicateTable: ERROR:  relation "books" already exists
/home/yahonda/src/github.com/rails/rails/tmp/d20220517-166171-cg0j15/app/db/migrate/20220516233706_create_books.rb:3:in `change'
/home/yahonda/src/github.com/rails/rails/tmp/d20220517-166171-cg0j15/app/bin/rails:4:in `<top (required)>'
Tasks: TOP => db:prepare
(See full trace by running task with --trace)

    /home/yahonda/src/github.com/rails/rails/railties/test/isolation/abstract_unit.rb:390:in `rails'
    /home/yahonda/src/github.com/rails/rails/railties/test/application/rake/multi_dbs_test.rb:845:in `block (2 levels) in <class:RakeMultiDbsTest>'
    /home/yahonda/src/github.com/rails/rails/railties/test/application/rake/multi_dbs_test.rb:837:in `chdir'
    /home/yahonda/src/github.com/rails/rails/railties/test/application/rake/multi_dbs_test.rb:837:in `block in <class:RakeMultiDbsTest>'


bin/test test/application/rake/multi_dbs_test.rb:835



Finished in 2.963446s, 1.0123 runs/s, 0.6749 assertions/s.
3 runs, 2 assertions, 0 failures, 2 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**:ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by yahonda** [comment]
I am not familiar with multi_dbs_test.rb. However, I assume some test attempts to use the same database that already has `books` table.

**Comment by fatkodima** [comment]
I investigated a bit and, so, seems like the reason is that 2 tests use `use_postgresql(multi_db: true)` and since they run in parallel, they try to run `rails("db:prepare")` at the same time with different (not satisfied) assumptions. If I add a `sleep 10` for example, they both pass.

I think there are several ways to solve this flaky test:
1. add sleeping
2. combine both tests into one
3. update and merge https://github.com/rails/rails/pull/36620 to avoid using `use_postgresql(multi_db: true)`

**Comment by eileencodes** [comment]
I opened this PR https://github.com/rails/rails/pull/45178. I spent way too much time trying to fix this and ultimately adding an optional db name seemed to be the easiest.
