### ISSUE TITLE
test_db:prepare_creates_test_database_if_it_does_not_exist fails

### ISSUE THREAD

**Issue by yahonda** [rails/rails#45158]
Managed to reproduce https://buildkite.com/rails/rails/builds/86697#914ae9c5-1469-4269-b24b-202e6b5e07f0 via https://github.com/rails/rails/pull/45157

### Steps to reproduce
```ruby
$ cd railties
$ bin/test test/application/rake/dbs_test.rb --seed 8301 -n "/^(?:ApplicationTests::RakeTests::RakeDbsTest#(?:test_db:drop_failure_because_database_does_not_exist|test_db:create_works_when_schema_cache_exists_and_database_does_not_exist|test_db:prepare_creates_test_database_if_it_does_not_exist))$/"
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ bin/test test/application/rake/dbs_test.rb --seed 8301 -n "/^(?:ApplicationTests::RakeTests::RakeDbsTest#(?:test_db:drop_failure_because_database_does_not_exist|test_db:create_works_when_schema_cache_exists_and_database_does_not_exist|test_db:prepare_creates_test_database_if_it_does_not_exist))$/"
Run options: --seed 8301 -n "/^(?:ApplicationTests::RakeTests::RakeDbsTest#(?:test_db:drop_failure_because_database_does_not_exist|test_db:create_works_when_schema_cache_exists_and_database_does_not_exist|test_db:prepare_creates_test_database_if_it_does_not_exist))$/"

# Running:

.E

Error:
ApplicationTests::RakeTests::RakeDbsTest#test_db:prepare_creates_test_database_if_it_does_not_exist:
RuntimeError: rails command failed (1): bin/rails db:drop db:create 2>&1
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:687: warning: conflicting chdir during another chdir block
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:708: warning: conflicting chdir during another chdir block
Dropped database 'railties_development'
Dropped database 'railties_test'
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "pg_database_datname_index"
DETAIL:  Key (datname)=(railties_development) already exists.
Couldn't create 'railties_development' database. Please check your configuration.
rails aborted!
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "pg_database_datname_index"
DETAIL:  Key (datname)=(railties_development) already exists.
/home/yahonda/src/github.com/rails/rails/tmp/d20220524-106385-tf2m4v/app/bin/rails:4:in `<top (required)>'

Caused by:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "pg_database_datname_index"
DETAIL:  Key (datname)=(railties_development) already exists.
/home/yahonda/src/github.com/rails/rails/tmp/d20220524-106385-tf2m4v/app/bin/rails:4:in `<top (required)>'
Tasks: TOP => db:create
(See full trace by running task with --trace)

    /home/yahonda/src/github.com/rails/rails/railties/test/isolation/abstract_unit.rb:390:in `rails'
    /home/yahonda/src/github.com/rails/rails/railties/test/application/rake/dbs_test.rb:739:in `block (2 levels) in <class:RakeDbsTest>'
    /home/yahonda/src/github.com/rails/rails/railties/test/application/rake/dbs_test.rb:737:in `chdir'
    /home/yahonda/src/github.com/rails/rails/railties/test/application/rake/dbs_test.rb:737:in `block in <class:RakeDbsTest>'


bin/test test/application/rake/dbs_test.rb:736

.

Finished in 3.422332s, 0.8766 runs/s, 0.8766 assertions/s.
3 runs, 3 assertions, 0 failures, 1 errors, 0 skips
$
```
### System configuration
**Rails version**: main branch

**Ruby version**:ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by fatkodima** [comment]
Looks like this is the same problem as in https://github.com/rails/rails/issues/45114.

**Comment by eileencodes** [comment]
I opened this PR https://github.com/rails/rails/pull/45178. I spent way too much time trying to fix this and ultimately adding an optional db name seemed to be the easiest.
