### ISSUE TITLE
API only apps do not have an `enabled?` method on the session.

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#45228]
I have a rails 7.0 application that is set for `api_mode = true`. 

When I run an integration tests I get an error like this:

```
NoMethodError: undefined method `enabled?' for {}:Hash
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/flash.rb:63:in `commit_flash'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_controller/metal.rb:189:in `dispatch'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_controller/metal.rb:251:in `dispatch'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:32:in `serve'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/journey/router.rb:32:in `each'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/journey/router.rb:32:in `serve'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:852:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3.1/lib/rack/etag.rb:27:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3.1/lib/rack/conditional_get.rb:40:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3.1/lib/rack/head.rb:12:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:99:in `run_callbacks'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-7.0.3/lib/rails/rack/logger.rb:40:in `call_app'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-7.0.3/lib/rails/rack/logger.rb:25:in `block in call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3/lib/active_support/tagged_logging.rb:114:in `block in tagged'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3/lib/active_support/tagged_logging.rb:38:in `tagged'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3/lib/active_support/tagged_logging.rb:114:in `tagged'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-7.0.3/lib/rails/rack/logger.rb:25:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3.1/lib/rack/runtime.rb:22:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/static.rb:23:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3.1/lib/rack/sendfile.rb:110:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/honeybadger-4.12.1/lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/honeybadger-4.12.1/lib/honeybadger/agent.rb:426:in `with_rack_env'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/honeybadger-4.12.1/lib/honeybadger/rack/error_notifier.rb:30:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/honeybadger-4.12.1/lib/honeybadger/rack/user_feedback.rb:31:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/honeybadger-4.12.1/lib/honeybadger/rack/user_informer.rb:21:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-7.0.3/lib/rails/engine.rb:530:in `call'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/testing/integration.rb:279:in `process'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/testing/integration.rb:34:in `put'
    /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/testing/integration.rb:370:in `put'
    /Users/jcoyne85/workspace/sul-dlss/workflow-server-rails/test/integration/update_step_test.rb:11:in `block in <class:UpdateStepTest>'
 ```

I believe this regression was introduced in https://github.com/rails/rails/commit/ca7c820c6962788d510c99a68e725de83cbe9cad where the code was refactored to depend this method: https://github.com/rails/rails/commit/ca7c820c6962788d510c99a68e725de83cbe9cad#diff-5f81b06a0e3051b576daee16c960b21e715a6cc26d97d020c546d2fa697c9bc6R203-R205

However that module is not used by API only applications
https://github.com/rails/rails/blob/ca7c820c6962788d510c99a68e725de83cbe9cad/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L48-L49

So when `commit_flash` is called there is no `enabled?` method defined on the `session` variable.

**Comment by jcoyne** [comment]
This was caused by the Honeybadger gem setting a value for `request.session` when calling `Honeybadger.notify` in the controller context.
