### ISSUE TITLE
RuntimeError: can't add a new key into hash during iteration on lib/active_record/connection_adapters/abstract/query_cache.rb

### ISSUE THREAD

**Issue by sobrinho** [rails/rails#45287]
### Steps to reproduce

No idea how to reproduce.

### Expected behavior
No concurrency errors in query cache.

### Actual behavior
A concurrency error in query cache.

It is happening inside a Sidekiq worker, FWIW.

And it has been happening for at least a year now:

<img width="839" alt="Screen Shot 2022-06-07 at 12 46 42" src="https://user-images.githubusercontent.com/26460/172424269-6e8cc3b9-b5ca-41a4-a438-5f3c03976d80.png">

Here's the backtrace:

```
      "/app/vendor/cache/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/query_cache.rb:118:in `block in cache_sql'",
      "/app/vendor/cache/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'",
      "/app/vendor/cache/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'",
      "/app/vendor/cache/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'",
      "/app/vendor/cache/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'",
      "/app/vendor/cache/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'",
      "/app/vendor/cache/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/query_cache.rb:109:in `cache_sql'",
      "/app/vendor/cache/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'",
      "/app/vendor/cache/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/querying.rb:47:in `find_by_sql'",
      "/app/vendor/cache/ruby/2.7.0/gems/scout_apm-2.6.6/lib/scout_apm/instruments/active_record.rb:333:in `find_by_sql_with_scout_instruments'",
      "/app/vendor/cache/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/statement_cache.rb:150:in `execute'",
      "/app/vendor/cache/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/associations/association.rb:227:in `find_target'",
      "/app/vendor/cache/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/associations/singular_association.rb:39:in `find_target'",
      "/app/vendor/cache/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/associations/association.rb:174:in `load_target'",
      "/app/vendor/cache/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/associations/association.rb:67:in `reload'",
      "/app/vendor/cache/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/associations/singular_association.rb:9:in `reader'",
      "/app/vendor/cache/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/associations/builder/association.rb:103:in `location'",
      "/app/app/services/my_service.rb:9:in `initialize'",
```

Pseudo code from the original source code:

```ruby
class MyWorker
  include Sidekiq::Worker

  def perform
    MyModel.where('x < ?', 1.month.ago).where(a_column: A_VALUE).find_each do |my_model|
      MyService.new(lead_source).something
    end
  end
end

class MyService
  def initialize(my_model)
    @my_model = my_model
    @something = my_model.a_standard_belongs_to_relation # error is triggered here!
  end

  def something
    # ...
  end
end
```

This has been reported before [here](https://github.com/rails/rails/issues/40608) but without a specific solution.

`sentry-raven`, `sentry-ruby` and `activerecord-import` were mentioned but we aren't using it but we do have `prometheus_exporter`.

What I don't get is how this error could happen considering there is a monitor around the query cache.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.7.2

**Comment by luanzeba** [comment]
Hi @sobrinho , thanks for opening this issue!
There have been a lot of changes since Rails 6.1. Are you able to verify this issue happens on Rails 7 as well?

**Comment by sobrinho** [comment]
Checking the source code there is almost no changes between 6.1.3.2 and master in that regard.

Upgrading from 6.1 to 7.0 is also not easy due to the size/nature of the application, it will take a while.

**Comment by luanzeba** [comment]
Fair enough. I'm planning to take a look at this in the next few weeks and will report back if I find anything interesting.

That being said, the Rails maintenance policy is to only apply bug fixes to the latest release series https://guides.rubyonrails.org/maintenance_policy.html#bug-fixes, so if anyone reading this bug is able to reproduce this in Rails 7, that would be helpful!

**Comment by eileencodes** [comment]
The reason that the other issue didn't have a solution is because we're pretty sure that this isn't a bug in Rails and no one has provided a way to reproduce or prove that it is Rails.

The code already has lock synchronization so it is likely an external gem that is incorrectly iterating over the query cache. Since we can't see your application, we can't guess what that gem might be. I'd start with scout-apm as it's in your stack trace and is on a version that is 3 years old.

**Comment by sobrinho** [comment]
@eileencodes I can provide further details in the case of need.

So far I can tell that there is no references to `query_cache` in any of the gems used or our my app:

```
$ ag query_cache

$ ag query_cache $(bundle show --paths | grep -v /Users/sobrinho/.gem/ruby/2.7.2/gems/activerecord-6.1.3.2)
[DEPRECATED] use `bundle list` instead of `bundle show --paths`
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
/Users/sobrinho/.gem/ruby/2.7.2/gems/actionview-6.1.3.2/lib/action_view/template/resolver.rb
92:        @query_cache = SmallCache.new
96:        "#{to_s[0..-2]} keys=#{@data.size} queries=#{@query_cache.size}>"
105:        @query_cache[query] ||= canonical_no_templates(yield)
110:        @query_cache.clear
127:        size + @query_cache.size
```

**Comment by eileencodes** [comment]
It might not be a direct reference to the query cache, but a lack of a lock synch in code overriding Active Record.

**Comment by sobrinho** [comment]
@eileencodes alright, let me try to update the gem and see what happens

**Comment by jordan-brough** [comment]
This just started happening to us also, and I get the same search result as @sobrinho:
```sh
$ ag '\bquery_cache\b' $(bundle list --paths)
```
<details><summary>Click to show results</summary>

```
/Users/jordan/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionview-6.1.6/lib/action_view/template/resolver.rb
92:        @query_cache = SmallCache.new
96:        "#{to_s[0..-2]} keys=#{@data.size} queries=#{@query_cache.size}>"
105:        @query_cache[query] ||= canonical_no_templates(yield)
110:        @query_cache.clear
127:        size + @query_cache.size

/Users/jordan/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/query_cache.rb
50:      attr_reader :query_cache, :query_cache_enabled
54:        @query_cache         = Hash.new { |h, sql| h[sql] = {} }
92:          @query_cache.clear
111:              if @query_cache[sql].key?(binds)
116:                @query_cache[sql][binds]
118:                @query_cache[sql][binds] = yield
```
</details>

> It might not be a direct reference to the query cache, but a lack of a lock synch in code overriding Active Record.

If the only [manipulation @query_cache](https://github.com/rails/rails/blob/v6.1.6/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb#L54-L118) happens in `QueryCache`, then I think these are the only operations performed on `@query_cache`:
```ruby
@query_cache = Hash.new { |h, sql| h[sql] = {} }
@query_cache.clear
@query_cache[sql]
```
Right?

Does anyone know how to trigger a `RuntimeError: can't add a new key into hash during iteration` using just those primitives? (assuming that the locking has been messed up)

**Comment by sobrinho** [comment]
@jordan-brough please keep me updated if you find anything new, we are going to release the gem upgrade as suggested by Eileen but since there is no manipulation in the query cache at all, I'm guessing it won't take any effect.

I will keep here updated as well.

**Comment by sobrinho** [comment]
I'm still seeing this in a few different places, even during HTTP requests.

```
* 		[GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/query_cache.rb:118 :in `block in cache_sql`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26 :in `block (2 levels) in synchronize`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25 :in `handle_interrupt`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25 :in `block in synchronize`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21 :in `handle_interrupt`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21 :in `synchronize`
* 		 [GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/query_cache.rb:109 :in `cache_sql`
* 		 [GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/query_cache.rb:101 :in `select_all`
* 		 [GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/querying.rb:47 :in `find_by_sql`
* 		 [GEM_ROOT]/gems/scout_apm-4.1.1/lib/scout_apm/instruments/active_record.rb:321 :in `find_by_sql_with_scout_instruments`
* 		 [GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/statement_cache.rb:150 :in `execute`
* 		 [GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/associations/association.rb:227 :in `find_target`
* 		 [GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/associations/collection_association.rb:274 :in `load_target`
* 		 [GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/associations/collection_proxy.rb:43 :in `load_target`
* 		 [GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/associations/collection_proxy.rb:1002 :in `records`
* 		 [GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/relation/delegation.rb:88 :in `each`
* 		 [PROJECT_ROOT]/app/controllers/locations_controller.rb:12 :in `block in index`
* 		 [GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/relation/delegation.rb:88 :in `each`
* 		 [GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/relation/delegation.rb:88 :in `each`
* 		 [PROJECT_ROOT]/app/controllers/locations_controller.rb:11 :in `index`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_controller/metal/basic_implicit_render.rb:6 :in `send_action`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/abstract_controller/base.rb:228 :in `process_action`
* 		 [GEM_ROOT]/gems/scout_apm-4.1.1/lib/scout_apm/instruments/action_controller_rails_3_rails4.rb:103 :in `process_action`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_controller/metal/rendering.rb:30 :in `process_action`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/abstract_controller/callbacks.rb:42 :in `block in process_action`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:117 :in `block in run_callbacks`
* 		 [GEM_ROOT]/gems/actiontext-6.1.3.1/lib/action_text/rendering.rb:20 :in `with_renderer`
* 		 [GEM_ROOT]/gems/actiontext-6.1.3.1/lib/action_text/engine.rb:55 :in `block (4 levels) in <class:Engine>`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126 :in `instance_exec`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126 :in `block in run_callbacks`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:137 :in `run_callbacks`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/abstract_controller/callbacks.rb:41 :in `process_action`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_controller/metal/rescue.rb:22 :in `process_action`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_controller/metal/instrumentation.rb:34 :in `block in process_action`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203 :in `block in instrument`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:24 :in `instrument`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203 :in `instrument`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_controller/metal/instrumentation.rb:33 :in `process_action`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_controller/metal/params_wrapper.rb:249 :in `process_action`
* 		 [GEM_ROOT]/gems/activerecord-6.1.3.1/lib/active_record/railties/controller_runtime.rb:27 :in `process_action`
* 		 [GEM_ROOT]/gems/scout_apm-4.1.1/lib/scout_apm/instruments/action_controller_rails_3_rails4.rb:120 :in `process_action`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/abstract_controller/base.rb:165 :in `process`
* 		 [GEM_ROOT]/gems/actionview-6.1.3.1/lib/action_view/rendering.rb:39 :in `process`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_controller/metal.rb:190 :in `dispatch`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_controller/metal.rb:254 :in `dispatch`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/routing/route_set.rb:50 :in `dispatch`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/routing/route_set.rb:33 :in `serve`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/journey/router.rb:50 :in `block in serve`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/journey/router.rb:32 :in `each`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/journey/router.rb:32 :in `serve`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/routing/route_set.rb:842 :in `call`
* 		 [GEM_ROOT]/gems/scout_apm-4.1.1/lib/scout_apm/instruments/rails_router.rb:29 :in `call_with_scout_instruments`
* 		 [GEM_ROOT]/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192 :in `call!`
* 		 [GEM_ROOT]/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169 :in `call`
* 		 [GEM_ROOT]/gems/scout_apm-4.1.1/lib/scout_apm/middleware.rb:17 :in `call`
* 		 [GEM_ROOT]/gems/warden-1.2.9/lib/warden/manager.rb:36 :in `block in call`
* 		 [GEM_ROOT]/gems/warden-1.2.9/lib/warden/manager.rb:34 :in `catch`
* 		 [GEM_ROOT]/gems/warden-1.2.9/lib/warden/manager.rb:34 :in `call`
* 		 [GEM_ROOT]/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15 :in `call`
* 		 [GEM_ROOT]/gems/rack-2.2.3/lib/rack/etag.rb:27 :in `call`
* 		 [GEM_ROOT]/gems/rack-2.2.3/lib/rack/conditional_get.rb:27 :in `call`
* 		 [GEM_ROOT]/gems/rack-2.2.3/lib/rack/head.rb:12 :in `call`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/http/permissions_policy.rb:22 :in `call`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/http/content_security_policy.rb:18 :in `call`
* 		 [GEM_ROOT]/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266 :in `context`
* 		 [GEM_ROOT]/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260 :in `call`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/cookies.rb:689 :in `call`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/callbacks.rb:27 :in `block in call`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:98 :in `run_callbacks`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/callbacks.rb:26 :in `call`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18 :in `call`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:29 :in `call`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/show_exceptions.rb:33 :in `call`
* 		 [GEM_ROOT]/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15 :in `call_app`
* 		 [GEM_ROOT]/gems/railties-6.1.3.1/lib/rails/rack/logger.rb:26 :in `block in call`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/tagged_logging.rb:99 :in `block in tagged`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/tagged_logging.rb:37 :in `tagged`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/tagged_logging.rb:99 :in `tagged`
* 		 [GEM_ROOT]/gems/railties-6.1.3.1/lib/rails/rack/logger.rb:26 :in `call`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/remote_ip.rb:81 :in `call`
* 		 [GEM_ROOT]/gems/request_store-1.5.0/lib/request_store/middleware.rb:19 :in `call`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/request_id.rb:26 :in `call`
* 		 [GEM_ROOT]/gems/rack-2.2.3/lib/rack/method_override.rb:24 :in `call`
* 		 [GEM_ROOT]/gems/rack-2.2.3/lib/rack/runtime.rb:22 :in `call`
* 		 [GEM_ROOT]/gems/activesupport-6.1.3.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29 :in `call`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/executor.rb:14 :in `call`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/static.rb:24 :in `call`
* 		 [GEM_ROOT]/gems/rack-2.2.3/lib/rack/sendfile.rb:110 :in `call`
* 		 [GEM_ROOT]/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/host_authorization.rb:92 :in `call`
* 		 [GEM_ROOT]/gems/rack-cors-1.1.1/lib/rack/cors.rb:100 :in `call`
* 		 [GEM_ROOT]/gems/scout_apm-4.1.1/lib/scout_apm/instruments/middleware_summary.rb:58 :in `call`
* 		 [GEM_ROOT]/gems/railties-6.1.3.1/lib/rails/engine.rb:539 :in `call`
* 		 [GEM_ROOT]/gems/puma-3.12.6/lib/puma/configuration.rb:227 :in `call`
* 		 [GEM_ROOT]/gems/puma-3.12.6/lib/puma/server.rb:706 :in `handle_request`
* 		 [GEM_ROOT]/gems/puma-3.12.6/lib/puma/server.rb:476 :in `process_client`
* 		 [GEM_ROOT]/gems/puma-3.12.6/lib/puma/server.rb:334 :in `block in run`
* 		 [GEM_ROOT]/gems/puma-3.12.6/lib/puma/thread_pool.rb:135 :in `block in spawn_thread`
```

**Comment by kamil-kudra** [comment]
> Fair enough. I'm planning to take a look at this in the next few weeks and will report back if I find anything interesting.
> 
> That being said, the Rails maintenance policy is to only apply bug fixes to the latest release series https://guides.rubyonrails.org/maintenance_policy.html#bug-fixes, so if anyone reading this bug is able to reproduce this in Rails 7, that would be helpful!

Reproduced almost the same issue at 7.0.8.1 - also mostly in Sidekiq workers.

**Comment by kamil-kudra** [comment]
All I found looks related to concurrent-ruby and working on shared hash between threads. Could it be related?
https://github.com/ruby-concurrency/concurrent-ruby/issues/1040
https://github.com/ruby-concurrency/concurrent-ruby/issues/970

concurrent-ruby: 1.2.3
rails: 7.0.8.1
sidekiq: 7.1.4 and 7.2.2

**Comment by d0minikk** [comment]
Had the same issue. `RuntimeError: can't add a new key into hash during iteration` exception from Sidekiq jobs.

Ruby 3.2.2, Rails 7.1.3.4.
`prometheus_exporter` gem was really outdated. After bumping to the newest version there is no issue anymore :)
