### ISSUE TITLE
app:update (selecting All) results in NoMethodError on config/initializers/assets.rb:4

### ISSUE THREAD

**Issue by josh-m-sharpe** [rails/rails#45295]
### Steps to reproduce
1) rails 6.1 app
2) bundle update to rails 7.0.3
3) rake app:update
4) select 'a' for all

So, app:update replaces `config/initializers/assets.rb`, and then it looks like `rails  active_storage:update` fails on line 4 of that file: 
`NoMethodError: undefined method `assets'`

```
√ (9:14:15 PM) ~/fin {3.0.4p208} (master) 😜 be rake app:update
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
    conflict  config/boot.rb
Overwrite /Users/jsharpe/fin/config/boot.rb? (enter "h" for help) [Ynaqdhm] a
       force  config/boot.rb
       exist  config
    conflict  config/application.rb
       force  config/application.rb
   identical  config/environment.rb
       exist  config/environments
    conflict  config/environments/development.rb
       force  config/environments/development.rb
    conflict  config/environments/production.rb
       force  config/environments/production.rb
    conflict  config/environments/test.rb
       force  config/environments/test.rb
       exist  config/initializers
    conflict  config/initializers/assets.rb
       force  config/initializers/assets.rb
    conflict  config/initializers/content_security_policy.rb
       force  config/initializers/content_security_policy.rb
      create  config/initializers/cors.rb
    conflict  config/initializers/filter_parameter_logging.rb
       force  config/initializers/filter_parameter_logging.rb
    conflict  config/initializers/inflections.rb
       force  config/initializers/inflections.rb
      create  config/initializers/new_framework_defaults_7_0.rb
   identical  config/initializers/permissions_policy.rb
      remove  app/assets/stylesheets/application.css
      remove  config/initializers/cors.rb
       exist  bin
    conflict  bin/rails
       force  bin/rails
   identical  bin/rake
    conflict  bin/setup
       force  bin/setup
        gsub  db/schema.rb
       rails  active_storage:update
rails aborted!
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x000000010f3869a8 @root=#<Pathname:/Users/jsharpe/fin>, @generators=#<Rails::Configuration::Generators:0x000000010922b7d0 @aliases={}, @options={:rails=>{:orm=>:active_record, :test_framework=>:test_unit, :integration_tool=>:test_unit, :system_tests=>:test_unit}, :active_record=>{:migration=>true, :timestamps=>true}, :test_unit=>{:fixture=>false, :fixture_replacement=>:factory_bot}}, @fallbacks={}, @templates=[], @colorize_logging=true, @api_only=false, @hidden_namespaces=[], @after_generate_callbacks=[]>, @middleware=#<Rails::Configuration::MiddlewareStackProxy:0x000000010f386700 @operations=[#<Proc:0x000000010f801a78 /Users/jsharpe/.rvm/gems/ruby-3.0.4@fin/gems/railties-7.0.3/lib/rails/configuration.rb:53 (lambda)>, #<Proc:0x0000000110657078 /Users/jsh
arpe/.rvm/gems/ruby-3.0.4@fin/gems/railties-7.0.3/lib/rails/configuration.rb:59 (lambda)>], @delete_operations=[]>, @javascript_path="javascript", @encoding=#<Encoding:UTF-8>, @allow_concurrency=nil, @consider_all_requests_local=true, @filter_parameters=[], @filter_redirect=[], @helpers_paths=["/Users/jsharpe/fin/app/helpers"], @hosts=[".localhost", #<IPAddr: IPv4:0.0.0.0/0.0.0.0>, #<IPAddr: IPv6:0000:0000:0000:0000:0000:0000:0000:0000/0000:0000:0000:0000:0000:0000:0000:0000>], @host_authorization={}, @public_file_server=#<ActiveSupport::OrderedOptions {:enabled=>true, :index_name=>"index"}>, @force_ssl=false, @ssl_options={:hsts=>{:subdomains=>true}}, @session_store=nil, @time_zone="UTC", @beginning_of_week=:monday, @log_level=:debug, @cache_store=:null_store, @railties_order=[:all], @relative_url_root=nil, @reload_classes_only_on_ch
ange=true, @file_watcher=ActiveSupport::FileUpdateChecker, @exceptions_app=nil, @autoflush_log=true, @log_formatter=#<ActiveSupport::Logger::SimpleFormatter:0x000000010f39c848 @datetime_format=nil>, @eager_load=false, @secret_key_base=nil, @api_only=false, @debug_exception_response_format=nil, @x=#<Rails::Application::Configuration::Custom:0x000000010f39c7a8 @configurations={}>, @enable_dependency_loading=false, @read_encrypted_secrets=false, @content_security_policy=nil, @content_security_policy_report_only=false, @content_security_policy_nonce_generator=nil, @content_security_policy_nonce_directives=nil, @require_master_key=false, @loaded_config_version=6.0, @credentials=#<ActiveSupport::OrderedOptions {:content_path=>#<Pathname:/Users/jsharpe/fin/config/credentials.yml.enc>, :key_path=>#<Pathname:/Users/jsharpe/fin/config/mast
er.key>}>, @disable_sandbox=false, @add_autoload_paths_to_load_path=true, @permissions_policy=nil, @rake_eager_load=false, @server_timing=true, @paths=#<Rails::Paths::Root:0x000000010f4d5098 @path=#<Pathname:/Users/jsharpe/fin>, @root={"app"=>#<Rails::Paths::Path:0x000000010f4d4eb8 @paths=["app"], @current="app", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob="{*,*/concerns}", @exclude=["assets", "javascript"], @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/assets"=>#<Rails::Paths::Path:0x000000010f4d4d50 @paths=["app/assets"], @current="app/assets", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/controllers"=>#<Rails::Paths::Path:0x000000010f4d4c88 @paths=["app/controllers"], @curren
t="app/controllers", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/channels"=>#<Rails::Paths::Path:0x000000010f4d4be8 @paths=["app/channels"], @current="app/channels", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/helpers"=>#<Rails::Paths::Path:0x000000010f4d4b48 @paths=["app/helpers"], @current="app/helpers", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/models"=>#<Rails::Paths::Path:0x000000010f4d4aa8 @paths=["app/models"], @current="app/models", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclud
e=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/mailers"=>#<Rails::Paths::Path:0x000000010f4d4a08 @paths=["app/mailers"], @current="app/mailers", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/views"=>#<Rails::Paths::Path:0x000000010f4d4968 @paths=["app/views"], @current="app/views", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib"=>#<Rails::Paths::Path:0x000000010f4d48c8 @paths=["lib"], @current="lib", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "lib/assets"=>#<Rails::Paths::Path:0x
000000010f4d4800 @paths=["lib/assets"], @current="lib/assets", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/tasks"=>#<Rails::Paths::Path:0x000000010f4d4760 @paths=["lib/tasks"], @current="lib/tasks", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob="**/*.rake", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config"=>#<Rails::Paths::Path:0x000000010f4d46e8 @paths=["config"], @current="config", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environments"=>#<Rails::Paths::Path:0x000000010f4d45a8 @paths=["config/environments"], @current="config/environments", @root=#<Rails:
:Paths::Root:0x000000010f4d5098 ...>, @glob="development.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/initializers"=>#<Rails::Paths::Path:0x000000010f4d4508 @paths=["config/initializers"], @current="config/initializers", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/locales"=>#<Rails::Paths::Path:0x000000010f4d4468 @paths=["config/locales"], @current="config/locales", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob="**/*.{rb,yml}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes.rb"=>#<Rails::Paths::Path:0x000000010f4d43f0 @paths=["config/routes.rb"], @current="config/routes.rb", @root=#<Rails::Paths::R
oot:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes"=>#<Rails::Paths::Path:0x000000010f4d4350 @paths=["config/routes"], @current="config/routes", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db"=>#<Rails::Paths::Path:0x000000010f4d42d8 @paths=["db"], @current="db", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/migrate"=>#<Rails::Paths::Path:0x000000010f4d4260 @paths=["db/migrate"], @current="db/migrate", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=f
alse, @load_path=false>, "db/seeds.rb"=>#<Rails::Paths::Path:0x000000010f4d41e8 @paths=["db/seeds.rb"], @current="db/seeds.rb", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "vendor"=>#<Rails::Paths::Path:0x000000010f4d4148 @paths=["vendor"], @current="vendor", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "vendor/assets"=>#<Rails::Paths::Path:0x000000010f4d40a8 @paths=["vendor/assets"], @current="vendor/assets", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/database"=>#<Rails::Paths::Path:0x000000010f4d4008 @paths=["confi
g/database.yml"], @current="config/database", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/secrets"=>#<Rails::Paths::Path:0x000000010f4ebf50 @paths=["config"], @current="config/secrets", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob="secrets.yml{,.enc}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environment"=>#<Rails::Paths::Path:0x000000010f4ebeb0 @paths=["config/environment.rb"], @current="config/environment", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/templates"=>#<Rails::Paths::Path:0x000000010f4ebe38 @paths=["lib/templates"], @current="lib/templa
tes", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "log"=>#<Rails::Paths::Path:0x000000010f4ebd48 @paths=["log/development.log"], @current="log", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public"=>#<Rails::Paths::Path:0x000000010f4ebcd0 @paths=["public"], @current="public", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/javascripts"=>#<Rails::Paths::Path:0x000000010f4ebc58 @paths=["public/javascripts"], @current="public/javascripts", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autolo
ad_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/stylesheets"=>#<Rails::Paths::Path:0x000000010f4ebbe0 @paths=["public/stylesheets"], @current="public/stylesheets", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "tmp"=>#<Rails::Paths::Path:0x000000010f4ebb68 @paths=["tmp"], @current="tmp", @root=#<Rails::Paths::Root:0x000000010f4d5098 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>}>, @cache_classes=false, @autoload_paths=[], @eager_load_paths=["/Users/jsharpe/fin/app/channels", "/Users/jsharpe/fin/app/classes", "/Users/jsharpe/fin/app/controllers", "/Users/jsharpe/fin/app/controllers/concerns", "/Users/jsharpe/fin/app/helpers", "/Users/jsharpe/fin/app/jobs", "/Users/jsharpe/fin/app/mailers", "/Users/jsharpe/fin/app/models", "/Users/jsharpe/fin/app/models/concerns", "/Users/jsharpe/fin/app/sidekiq"], @autoload_once_paths=[]>
Did you mean?  asset_host
/Users/jsharpe/fin/config/initializers/assets.rb:4:in `<top (required)>'
/Users/jsharpe/fin/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => active_storage:update => environment
(See full trace by running task with --trace)
```

### System configuration
**Rails version**:
```
be rails --version
Rails 7.0.3
```

**Ruby version**:
```
ruby --version
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21]
```

**Comment by josh-m-sharpe** [comment]
Hmm, I guess this is related: https://github.com/rails/rails/issues/43793
...but very unexpected.

**Comment by skipkayhil** [comment]
Is there somewhere you think making it more clear would have helped? Its currently mentioned in the upgrading docs here: https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#sprockets-is-now-an-optional-dependency

**Comment by josh-m-sharpe** [comment]
Maybe detect that sprockets-rails has been removed due to lack of explicit inclusion? Or alternatively, maybe capture `NoMethodError: undefined method 'assets'` in the load path somewhere and point to https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#sprockets-is-now-an-optional-dependency

I'm not sure, I think this is unique to this version of rails, and is the exception not the rule..  I don't think rails has dropped such an (previously) important dependency before.  Typical configuration changes are well-handled by the default config system and the new initializer that gets loaded.  This missing gem comes before all of that in the load order and is therefore unhandled.

**Comment by skipkayhil** [comment]
> Or alternatively, maybe capture `NoMethodError: undefined method 'assets'` in the load path somewhere

This seems like an interesting idea, would you be interested in exploring this/creating a PR?

**Comment by skipkayhil** [comment]
@josh-m-sharpe I created a PR that should fix the error you were seeing, if you are able to test it out and provide feedback I would really appreciate it!
