### ISSUE TITLE
undefined local variable or method `before_add_for' for Class

### ISSUE THREAD

**Issue by naftis** [rails/rails#45316]
I'm updating from `7.0.0.alpha2` to `7.0.3`. I just ran the update scripts and I'm now getting 
```rb
NameError (undefined local variable or method `before_add_for_contributors' for Question:Class):
app/models/question.rb:71:in `<class:Question>'
app/models/question.rb:3:in `<top (required)>'
```

Question-model configuration with contributors:
```rb
has_many :contributors, through: :questions_users, source: :user
before_add_for_contributors << ->(_method, owner, change) { owner.send(:mail_new_contributor, change) }
```

The odd thing is though that if I add `before_add` to the `has_many`, the latter `before_add_for_contributors` also seems to starts working like it should:
```rb
has_many :contributors, through: :questions_users, source: :user, before_add: ->(owner, change) {}
```

Wonder what could cause this behaviour?

### System configuration
**Rails version**: Rails 7.0.3

**Ruby version**:  ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin20]

**Comment by eileencodes** [comment]
Hi @naftis thanks for the report. Please provide a [script](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb) that reproduces this bug. Without that it's impossible for us to determine whether this is a bug in the framework or in your application (potentially a gem you are using).

**Comment by CodeMeister** [comment]
I have the same issue. I use these methods to hook in an AuditLog module that records both attribute and association changes.

These methods are defined in `CollectionAssociation`, found [here](https://github.com/rails/rails/blob/014347620db4b063e63caf3914f1737cd87bf5d5/activerecord/lib/active_record/associations/builder/collection_association.rb)

In Rails 6, `<callback_name>_for_<association_name>` methods for all four callback options [:before_add, :after_add, :before_remove, :after_remove] were created, even if they were not specified when the association was created. This let us add them dynamically AFTER the association was in place.

Rails 7 has removed this, and only creates the method if an option is specified when creating the association. 

See the example from [project.rb](https://github.com/rails/rails/blob/014347620db4b063e63caf3914f1737cd87bf5d5/activerecord/test/models/project.rb)

```ruby
has_and_belongs_to_many :developers_with_callbacks, class_name: "Developer", before_add: Proc.new { |o, r| o.developers_log << "before_adding#{r.id || '<new>'}" },
                            after_add: Proc.new { |o, r| o.developers_log << "after_adding#{r.id || '<new>'}" },
                            before_remove: Proc.new { |o, r| o.developers_log << "before_removing#{r.id}" },
                            after_remove: Proc.new { |o, r| o.developers_log << "after_removing#{r.id}" }
```

It was changed in commit [bfcac1359e6a1848c07ced1b301a339b54fb260d](https://github.com/rails/rails/commit/bfcac1359e6a1848c07ced1b301a339b54fb260d#diff-0e0ba9f548037ce5d4f147573d47ac5fe619c12f7ebb2d2f24090306a2bf7133)

Any chance of this functionality being re-introduced?

@eileencodes - there are no notes around why it was removed, but it would be simple to re-introduce this functionality. I'm happy to do a pull request if the team is OK for it to be re-added.

**Comment by skipkayhil** [comment]
Is there a reason you can't define the callbacks when the association is defined?

**Comment by eileencodes** [comment]
> Any chance of this functionality being re-introduced?

They were removed for two reasons. One they were never intended to be public and two because class attributes are expensive.

I don't want to reintroduce this functionality as applications shouldn't have been consuming it in the first place. Applications should use the publicly documented way - defining the callbacks when associations are defined. 

@jhawthorn let me know if you disagree or feel strongly about adding this functionality back and I'll reopen.
