### ISSUE TITLE
Attachments in a single transaction are uploaded multiple times

### ISSUE THREAD

**Issue by georgeclaghorn** [rails/rails#45339]
Rails: latest main (https://github.com/rails/rails/commit/34934071c61bcc89edb805ccc50430df93b96f73 currently).
Ruby: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]`.

Reproduction script:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", ref: "main"
  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }

  config.active_storage.replace_on_assign_to_many = true
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_many_attached :files
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_upload_and_download
    user = User.create! do |user|
      user.files.attach \
        io: StringIO.new("hello"),
        content_type: "text/plain",
        filename: "1.txt"

      user.files.attach \
        io: StringIO.new("world"),
        content_type: "text/plain",
        filename: "2.txt"
    end

    assert_equal 2, user.files.count
  end
end
```

Expected: pass.

Actual:

```
Error:
BugTest#test_upload_and_download:
ActiveStorage::IntegrityError: ActiveStorage::IntegrityError
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/service/disk_service.rb:164:in `ensure_integrity_of'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/service/disk_service.rb:22:in `block in upload'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/notifications.rb:206:in `instrument'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/service.rb:163:in `instrument'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/service/disk_service.rb:20:in `upload'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/app/models/active_storage/blob.rb:268:in `upload_without_unfurling'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/attached/changes/create_one.rb:28:in `upload'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/attached/changes/create_many.rb:23:in `each'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/attached/changes/create_many.rb:23:in `upload'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/core_ext/object/try.rb:15:in `public_send'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/core_ext/object/try.rb:15:in `try'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/attached/model.rb:200:in `block in has_many_attached'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:445:in `instance_exec'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:445:in `block in make_lambda'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:261:in `block in conditional'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:599:in `block in invoke_after'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:599:in `each'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:599:in `invoke_after'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:108:in `run_callbacks'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:929:in `_run_commit_callbacks'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/transactions.rb:321:in `committed!'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:177:in `commit_records'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:412:in `block in commit_transaction'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:396:in `commit_transaction'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:473:in `block in within_new_transaction'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:425:in `within_new_transaction'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/transactions.rb:302:in `save!'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/suppressor.rb:54:in `save!'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/persistence.rb:55:in `create!'
    bug.rb:59:in `test_upload_and_download'
```

With a debugger stopped at `ActiveStorage::Attached::Changes::CreateMany#upload`, `pending_uploads` contains two `ActiveStorage::Attached::Changes::CreateOneOfMany` objects for the first attachable:

```
[18, 27] in /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/attached/changes/create_many.rb
   18:     def blobs
   19:       @blobs ||= subchanges.collect(&:blob)
   20:     end
   21: 
   22:     def upload
=> 23:       pending_uploads.each(&:upload)
   24:     end
   25: 
   26:     def save
   27:       assign_associated_attachments
(byebug) pending_uploads
[#<ActiveStorage::Attached::Changes::CreateOneOfMany:0x000000010b1a2e38 @attachable={:io=>#<StringIO:0x000000010b728920>, :content_type=>"text/plain", :filename=>"1.txt"}, @record=#<User id: 1>, @name="files", @blob=#<ActiveStorage::Blob id: nil, key: nil, filename: "1.txt", content_type: "text/plain", metadata: {"identified"=>true}, service_name: "local", byte_size: 5, checksum: "XUFAKrxLKna5cZ2REBfFkg==", created_at: nil>, @attachment=#<ActiveStorage::Attachment id: nil, name: "files", record_type: "User", record_id: nil, blob_id: nil, created_at: nil>>, #<ActiveStorage::Attached::Changes::CreateOneOfMany:0x000000010ad0ff10 @attachable={:io=>#<StringIO:0x000000010b728920>, :content_type=>"text/plain", :filename=>"1.txt"}, @record=#<User id: 1>, @name="files", @blob=#<ActiveStorage::Blob id: 1, key: "w7lb7ia2gwqwwrcacww3w2q47elk", filename: "1.txt", content_type: "text/plain", metadata: {"identified"=>true}, service_name: "local", byte_size: 5, checksum: "XUFAKrxLKna5cZ2REBfFkg==", created_at: "2022-06-13 12:21:19.589382000 +0000">, @attachment=#<ActiveStorage::Attachment id: 1, name: "files", record_type: "User", record_id: 1, blob_id: 1, created_at: "2022-06-13 12:21:19.592854000 +0000">>, #<ActiveStorage::Attached::Changes::CreateOneOfMany:0x000000010b910b70 @attachable={:io=>#<StringIO:0x000000010ad1f460>, :content_type=>"text/plain", :filename=>"2.txt"}, @record=#<User id: 1>, @name="files", @blob=#<ActiveStorage::Blob id: 2, key: "c2gp0zf92yt9h746mdq0ygcv7hcj", filename: "2.txt", content_type: "text/plain", metadata: {"identified"=>true}, service_name: "local", byte_size: 5, checksum: "fXkwN6B2AYZXSwKC8vQ15w==", created_at: "2022-06-13 12:21:19.597202000 +0000">, @attachment=#<ActiveStorage::Attachment id: 2, name: "files", record_type: "User", record_id: 1, blob_id: 2, created_at: "2022-06-13 12:21:19.599980000 +0000">>]
```

The `ActiveStorage::IntegrityError` occurs because the second attempt to upload `1.txt` reads from the end of the IO.

Bisects to #42300. /cc @santib @Jeremy

**Comment by santib** [comment]
thanks for the detailed report George, I'll take a look at it
