### ISSUE TITLE
Rails7.X: Cache of attribtute method definistions will be applied to methods with different target.

### ISSUE THREAD

**Issue by sachisuzuki** [rails/rails#45416]
### Steps to reproduce
```
$ docker run --rm -ti ruby:3.1.2 /bin/bash
$ ruby test_case.rb
```
-test_case.rb
```ruby:test_case.rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org/"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "activemodel", "~> 7.0.3"
end

require "active_model"

class C1
  include ActiveModel::AttributeMethods
  attribute_method_suffix "_changed?", parameters: false
  define_attribute_methods :x
  attr_accessor :x

  def attributes
    {"x" => @x}
  end

  def attribute_changed?(name, **options)
    [name, self.class, __method__]
  end
end

p C1.new.x_changed? #=> ["x", C1, :attribute_changed?]

# The definition of `x_changed?` is cached on ActiveSupprt::CodeGenerator,
# and It is applied to methods with the same name, even if they should call
# different target method.
class C2
  include ActiveModel::AttributeMethods
  attribute_method_suffix "?", parameters: false
  define_attribute_methods :x_changed
  attr_accessor :x_changed

  def attributes
    {"x_changed" => @x_changed}
  end

  # It is expected to be called through `C2#x_changed?`,
  # although `C2#attribute_changed?` will be called.
  def attribute?(name, **options)
    [name, self.class, __method__]
  end
end

p C2.new.x_changed? #=> undefined method `attribute_changed?' for #<C2:0x00007fdbbd0688a8> (NoMethodError)

```

### Expected behavior
C2#attribute? is expected to be called.

### Actual behavior
Cached `C2#attribute_changed?` is called and a NoMethodError is raised.
undefined method `attribute_changed?' for #<C2:.....> (NoMethodError)

### System configuration
**Rails version**: 7.0.3
**Ruby version**: 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by byroot** [comment]
Thanks for the bug report. I backported the fix to `7-0-stable`.

**Comment by Eric-Guo** [comment]
After pick up this commit, it will cause my testing suite failed, can confirm it cause by this PR at `7-0-stable`

```log
$ bin/rails db:setup RAILS_ENV=test
Created database 'cybros_test'
rails aborted!
NameError: undefined local variable or method `proxy_target' for ActiveRecord::InternalMetadata:Class
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activemodel/lib/active_model/attribute_methods.rb:397:in `define_proxy_call'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activemodel/lib/active_model/attribute_methods.rb:322:in `block (2 levels) in define_attribute_method'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activemodel/lib/active_model/attribute_methods.rb:313:in `each'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activemodel/lib/active_model/attribute_methods.rb:313:in `block in define_attribute_method'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activesupport/lib/active_support/code_generator.rb:38:in `batch'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activemodel/lib/active_model/attribute_methods.rb:312:in `define_attribute_method'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activemodel/lib/active_model/attribute_methods.rb:278:in `block (2 levels) in define_attribute_methods'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activemodel/lib/active_model/attribute_methods.rb:278:in `each'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activemodel/lib/active_model/attribute_methods.rb:278:in `block in define_attribute_methods'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activesupport/lib/active_support/code_generator.rb:41:in `batch'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activemodel/lib/active_model/attribute_methods.rb:277:in `define_attribute_methods'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/attribute_methods.rb:65:in `block in define_attribute_methods'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/attribute_methods.rb:62:in `define_attribute_methods'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/core.rb:765:in `init_internals'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/associations.rb:323:in `init_internals'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/core.rb:465:in `initialize'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/inheritance.rb:75:in `new'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/inheritance.rb:75:in `new'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/relation.rb:861:in `_new'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/relation.rb:71:in `block in new'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/relation.rb:880:in `_scoping'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/relation.rb:428:in `scoping'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/relation.rb:71:in `new'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/relation.rb:227:in `find_or_initialize_by'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/querying.rb:22:in `find_or_initialize_by'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/internal_metadata.rb:31:in `[]='
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/schema.rb:63:in `define'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/schema.rb:50:in `define'
/builds/cybros/portal/db/schema.rb:13:in `<main>'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/tasks/database_tasks.rb:377:in `load_schema'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/tasks/database_tasks.rb:482:in `block in load_schema_current'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/tasks/database_tasks.rb:557:in `block (2 levels) in each_current_configuration'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/tasks/database_tasks.rb:554:in `each'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/tasks/database_tasks.rb:554:in `block in each_current_configuration'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/tasks/database_tasks.rb:553:in `each'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/tasks/database_tasks.rb:553:in `each_current_configuration'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/tasks/database_tasks.rb:481:in `load_schema_current'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/activerecord/lib/active_record/railties/databases.rake:470:in `block (3 levels) in <main>'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/railties/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/railties/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/railties/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/railties/lib/rails/command.rb:51:in `invoke'
/builds/cybros/portal/vendor/ruby/3.0.0/bundler/gems/rails-8e7b3b735e87/railties/lib/rails/commands.rb:18:in `<main>'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/builds/cybros/portal/vendor/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
Tasks: TOP => db:setup => db:schema:load
(See full trace by running task with --trace)

Cleaning up project directory and file based variables
00:01

ERROR: Job failed: exit code 1
```

**Comment by byroot** [comment]
Yes my bad, I borked the backport. I'll fix it in a minute.

**Comment by byroot** [comment]
I pushed https://github.com/rails/rails/commit/0a23b963ca3d15c1ffcdcbcaefe8d3be917a11fa which should fix it.

**Comment by sachisuzuki** [comment]
Thank you for your prompt reply. @byroot
