### ISSUE TITLE
Action Pack CI fails since rack-test v2.0.0 

### ISSUE THREAD

**Issue by yahonda** [rails/rails#45467]
Managed to reproduce https://buildkite.com/rails/rails/builds/87630#0181a100-e98e-41d3-9114-9f767b8e9e3d

According to git bisect, this behavior change has been introduced via https://github.com/rack/rack-test/commit/a68ea95e75bdceaf4644efb9178cb3657b9eb3e0 I am not familiar with rack-test let me open this issue.

### Steps to reproduce

```ruby
git clone https://github.com/rails/rails
cd rails/actionpack
bundle update rack-test --conservative
bin/test
```

### Expected behavior
It should pass.

### Actual behavior

```ruby
Run options: --seed 48625

# Running:

.......................................................................................................................................................................................................................................................................................................................E

Error:
MemCacheStoreTest#test_getting_session_value_after_session_reset:
NoMethodError: undefined method `hash_for' for #<Rack::Test::CookieJar:0x00007f95ec01cb90 @default_host="www.example.com", @cookies=[#<Rack::Test::Cookie:0x00007f95ebfcf458 @default_host="www.example.com", @raw="_session_id=7e3e28b363f1159dac05374704fbdb5f", @name="_session_id", @value="7e3e28b363f1159dac05374704fbdb5f", @options={"path"=>"/", "HttpOnly"=>nil, "domain"=>"www.example.com"}, @exact_domain_match=true>]>
    /home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/mem_cache_store_test.rb:74:in `block in test_getting_session_value_after_session_reset'
    /home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/mem_cache_store_test.rb:205:in `block in with_test_route_set'
    /home/yahonda/src/github.com/rails/rails/actionpack/test/abstract_unit.rb:154:in `with_routing'
    /home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/mem_cache_store_test.rb:191:in `with_test_route_set'
    /home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/mem_cache_store_test.rb:70:in `test_getting_session_value_after_session_reset'


rails test home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/mem_cache_store_test.rb:69

...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F

Failure:
RenderStreaming::StreamingTest#test_rendering_with_template_exception [/home/yahonda/src/github.com/rails/rails/actionpack/test/controller/new_base/render_streaming_test.rb:84]:
--- expected
+++ actual
@@ -1,5 +1,2 @@
-"37\r
-\"><script>window.location = \"/500.html\"</script></html>\r
-0\r
-\r
+"500 error fixture
 "



rails test home/yahonda/src/github.com/rails/rails/actionpack/test/controller/new_base/render_streaming_test.rb:82

F

Failure:
RenderStreaming::StreamingTest#test_rendering_with_layout_exception [/home/yahonda/src/github.com/rails/rails/actionpack/test/controller/new_base/render_streaming_test.rb:78]:
--- expected
+++ actual
@@ -1,7 +1,2 @@
-"d\r
-<body class=\"\r
-37\r
-\"><script>window.location = \"/500.html\"</script></html>\r
-0\r
-\r
+"500 error fixture
 "



rails test home/yahonda/src/github.com/rails/rails/actionpack/test/controller/new_base/render_streaming_test.rb:76

F

Failure:
RenderStreaming::StreamingTest#test_rendering_with_streaming_do_not_override_explicit_cache_control_given_to_render [/home/yahonda/src/github.com/rails/rails/actionpack/test/controller/new_base/render_streaming_test.rb:61]:
--- expected
+++ actual
@@ -1,7 +1 @@
-"b\r
-Hello world\r
-b\r
-, I'm here!\r
-0\r
-\r
-"
+"Hello world, I'm here!"



rails test home/yahonda/src/github.com/rails/rails/actionpack/test/controller/new_base/render_streaming_test.rb:59

.F

Failure:
RenderStreaming::StreamingTest#test_rendering_with_streaming_given_to_render [/home/yahonda/src/github.com/rails/rails/actionpack/test/controller/new_base/render_streaming_test.rb:55]:
--- expected
+++ actual
@@ -1,7 +1 @@
-"b\r
-Hello world\r
-b\r
-, I'm here!\r
-0\r
-\r
-"
+"Hello world, I'm here!"



rails test home/yahonda/src/github.com/rails/rails/actionpack/test/controller/new_base/render_streaming_test.rb:53

F

Failure:
RenderStreaming::StreamingTest#test_rendering_with_streaming_no_layout [/home/yahonda/src/github.com/rails/rails/actionpack/test/controller/new_base/render_streaming_test.rb:67]:
--- expected
+++ actual
@@ -1,5 +1 @@
-"b\r
-Hello world\r
-0\r
-\r
-"
+"Hello world"



rails test home/yahonda/src/github.com/rails/rails/actionpack/test/controller/new_base/render_streaming_test.rb:65

...F

Failure:
RenderStreaming::StreamingTest#test_rendering_with_streaming_enabled_at_the_class_level [/home/yahonda/src/github.com/rails/rails/actionpack/test/controller/new_base/render_streaming_test.rb:49]:
--- expected
+++ actual
@@ -1,7 +1 @@
-"b\r
-Hello world\r
-b\r
-, I'm here!\r
-0\r
-\r
-"
+"Hello world, I'm here!"



rails test home/yahonda/src/github.com/rails/rails/actionpack/test/controller/new_base/render_streaming_test.rb:47

...................................................................................................................................................E

Error:
CacheStoreTest#test_getting_session_value_after_session_reset:
NoMethodError: undefined method `hash_for' for #<Rack::Test::CookieJar:0x00007f95eb7a8068 @default_host="www.example.com", @cookies=[#<Rack::Test::Cookie:0x00007f95eb7b7108 @default_host="www.example.com", @raw="_session_id=dfcb9f82e4826d004315e8245269a293", @name="_session_id", @value="dfcb9f82e4826d004315e8245269a293", @options={"path"=>"/", "HttpOnly"=>nil, "domain"=>"www.example.com"}, @exact_domain_match=true>]>
    /home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/cache_store_test.rb:62:in `block in test_getting_session_value_after_session_reset'
    /home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/cache_store_test.rb:221:in `block in with_test_route_set'
    /home/yahonda/src/github.com/rails/rails/actionpack/test/abstract_unit.rb:154:in `with_routing'
    /home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/cache_store_test.rb:208:in `with_test_route_set'
    /home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/cache_store_test.rb:58:in `test_getting_session_value_after_session_reset'


rails test home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/cache_store_test.rb:57

.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 8.480767s, 437.4604 runs/s, 2075.5197 assertions/s.
3710 runs, 17602 assertions, 6 failures, 2 errors, 0 skips
rake aborted!
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by skipkayhil** [comment]
Related #45177

**Comment by yahonda** [comment]
Tested #45177 and many of them have been addressed. The one remaining error is below.

```ruby
Error:
MemCacheStoreTest#test_getting_session_value_after_session_reset:
NoMethodError: undefined method `hash_for' for #<Rack::Test::CookieJar:0x00007f203c86dab8 @default_host="www.example.com", @cookies=[#<Rack::Test::Cookie:0x00007f203c878670 @default_host="www.example.com", @raw="_session_id=facaea4123670d24ca0c89b9178cf64c", @name="_session_id", @value="facaea4123670d24ca0c89b9178cf64c", @options={"path"=>"/", "HttpOnly"=>nil, "domain"=>"www.example.com"}, @exact_domain_match=true>]>
    /home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/mem_cache_store_test.rb:74:in `block in test_getting_session_value_after_session_reset'
    /home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/mem_cache_store_test.rb:205:in `block in with_test_route_set'
    /home/yahonda/src/github.com/rails/rails/actionpack/test/abstract_unit.rb:154:in `with_routing'
    /home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/mem_cache_store_test.rb:191:in `with_test_route_set'
    /home/yahonda/src/github.com/rails/rails/actionpack/test/dispatch/session/mem_cache_store_test.rb:70:in `test_getting_session_value_after_session_reset'
```
