### ISSUE TITLE
ActiveRecord: Bad handling of already loaded middle association in Associations::Preloaders::ThroughAssociation

### ISSUE THREAD

**Issue by such** [rails/rails#45542]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "7.0.2.4"
  gem "sqlite3"
end

require "active_record"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :cards, force: true do |t|
    t.references :card_data
  end

  create_table :card_data, force: true do |t|
    t.references :player
  end

  create_table :players, force: true do |t|
    t.references :active_club
  end

  create_table :teams, force: true do |t|
    t.string :type
  end
end

class Card < ActiveRecord::Base
  belongs_to :card_data
  has_one :player, through: :card_data
  has_one :active_club, through: :player
end

class CardData < ActiveRecord::Base
  belongs_to :player
end

class Player < ActiveRecord::Base
  belongs_to :active_club, class_name: 'Club' # NB: if class_name: 'Team' this works
end

class Team < ActiveRecord::Base
end

class Club < Team
end

player = Player.create!
card_data = CardData.create!(player:)
card = Card.create!(card_data:)

card.reload.player # NB: if removed this works
::ActiveRecord::Associations::Preloader.new(records: [card], associations: :active_club).call.then(&:first)
```

### Expected behavior
The association should be loaded properly

### Actual behavior
```
/Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:31:in `block (2 levels) in records_by_owner': undefined method `[]' for nil:NilClass (NoMethodError)

              source_records_by_owner[record]
                                     ^^^^^^^^
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:30:in `each'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:30:in `flat_map'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:30:in `block in records_by_owner'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:14:in `each'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:14:in `each_with_object'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:14:in `records_by_owner'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/association.rb:122:in `run'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/batch.rb:28:in `each'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/batch.rb:28:in `call'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader.rb:118:in `call'
	from test_source_records_by_owner.rb:62:in `<main>'
```

### System configuration
**Rails version**: 7.0.2.4

**Ruby version**: 3.1.1

**Comment by yopzer** [comment]
This is still an issue on Rails 7.0.4, tested with Ruby 3.1.2 and getting exactly the same failure as reported.

**Comment by such** [comment]
This is still an issue with `main`

**Comment by joshuay03** [comment]
> This is still an issue on `main`

@such I've got [this PR](https://github.com/rails/rails/pull/46579) up which resolves [this issue](https://github.com/rails/rails/issues/45822). Are you able to check if it resolves this one too?

**Comment by zzak** [comment]
@joshuay03 I was unable to reproduce the issue @such created in the test code above, so I think your PR works!

```
  #gem "activerecord", "7.0.2.4" # reproduces
  #gem "activerecord", github: "rails/rails" # reproduces
  gem "activerecord", github: "joshuay03/rails", branch: "fix-through-association-incorrect-preloading"
```

**Comment by nilbus** [comment]
I can also reproduce this problem with 7.0.2.4 but not with @joshuay03's PR https://github.com/rails/rails/pull/46579 via the same method in @zzak's comment. Looks like a fix to me! 🎉

**Comment by joshuay03** [comment]
PR was merged btw 💃🏽 @such @zzak @nilbus
