### ISSUE TITLE
Config `use_yaml_unsafe_load` breaks `assets:precompile` when without `config/database.yml`

### ISSUE THREAD

**Issue by cmitz** [rails/rails#45587]
## Context

We have a Rails app that we dockerized using a multi-stage Dockerfile. `database.yml` is not available when precompiling the assets, as assets are static and we don't want a NodeJS exec runtime when running the Rails container, and database connection info is supplied at runtime via ENV variables.

### Steps to reproduce
Demo available at: https://github.com/cmitz/rails_demo_unsafe_yaml_db

Execute `bundle exec rails assets:precompile` on:
* Initial commit: https://github.com/cmitz/rails_demo_unsafe_yaml_db/commit/b68a71bb082a08a54806be20175a3ce25f314a67
* Second commit: https://github.com/cmitz/rails_demo_unsafe_yaml_db/commit/c514108db6fa71804130de65b7c1e30d4142c350

```bash
bundle exec rails assets:precompile
```

### Expected behavior

**Build successfull!**

Console output:

<details>

```
yarn install v1.21.1
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.34s.
I, [2022-07-13T16:43:52.583023 #67874]  INFO -- : Writing /Users/my_username/src/rails_demo_unsafe_yaml_db/public/assets/manifest-b4bf6e57a53c2bdb55b8998cc94cd00883793c1c37c5e5aea3ef6749b4f6d92b.js
I, [2022-07-13T16:43:52.583268 #67874]  INFO -- : Writing /Users/my_username/src/rails_demo_unsafe_yaml_db/public/assets/manifest-b4bf6e57a53c2bdb55b8998cc94cd00883793c1c37c5e5aea3ef6749b4f6d92b.js.gz
I, [2022-07-13T16:43:52.583411 #67874]  INFO -- : Writing /Users/my_username/src/rails_demo_unsafe_yaml_db/public/assets/application-b324c44f04a0d0da658824105489a2676d49df561c3d06723770321fd441977c.css
I, [2022-07-13T16:43:52.583558 #67874]  INFO -- : Writing /Users/my_username/src/rails_demo_unsafe_yaml_db/public/assets/application-b324c44f04a0d0da658824105489a2676d49df561c3d06723770321fd441977c.css.gz
Compiling...
Compiled all packs in /Users/my_username/src/rails_demo_unsafe_yaml_db/public/packs
Hash: 83f44b586f0dbe4874e0
Version: webpack 4.46.0
Time: 1058ms
Built at: 07/13/2022 4:43:56 PM
                                        Asset       Size  Chunks                         Chunk Names
       js/application-ea49f96df08ec2f415e6.js   68.2 KiB       0  [emitted] [immutable]  application
    js/application-ea49f96df08ec2f415e6.js.br   15.2 KiB          [emitted]
    js/application-ea49f96df08ec2f415e6.js.gz   17.5 KiB          [emitted]
   js/application-ea49f96df08ec2f415e6.js.map    201 KiB       0  [emitted] [dev]        application
js/application-ea49f96df08ec2f415e6.js.map.br     43 KiB          [emitted]
js/application-ea49f96df08ec2f415e6.js.map.gz   49.6 KiB          [emitted]
                                manifest.json  364 bytes          [emitted]
                             manifest.json.br  129 bytes          [emitted]
                             manifest.json.gz  142 bytes          [emitted]
Entrypoint application = js/application-ea49f96df08ec2f415e6.js js/application-ea49f96df08ec2f415e6.js.map
[3] ./app/javascript/packs/application.js 480 bytes {0} [built]
[4] ./app/javascript/channels/index.js 205 bytes {0} [built]
[5] ./app/javascript/channels sync _channel\.js$ 160 bytes {0} [built]
    + 3 hidden modules

Execution time: 0h:00m:09s sec
```

</details>

### Actual behavior

```
my_username ~/src/rails_demo_unsafe_yaml_db main $ be rails assets:precompile
rails aborted!
Cannot load database configuration:
Could not load database configuration. No such file - ["config/database.yml"]
/Users/my_username/src/rails_demo_unsafe_yaml_db/config/environment.rb:5:in `<main>'
/Users/my_username/src/rails_demo_unsafe_yaml_db/bin/rails:5:in `<top (required)>'
/Users/my_username/src/rails_demo_unsafe_yaml_db/bin/spring:10:in `require'
/Users/my_username/src/rails_demo_unsafe_yaml_db/bin/spring:10:in `block in <top (required)>'
/Users/my_username/src/rails_demo_unsafe_yaml_db/bin/spring:7:in `tap'
/Users/my_username/src/rails_demo_unsafe_yaml_db/bin/spring:7:in `<top (required)>'

Caused by:
Could not load database configuration. No such file - ["config/database.yml"]
/Users/my_username/src/rails_demo_unsafe_yaml_db/config/environment.rb:5:in `<main>'
/Users/my_username/src/rails_demo_unsafe_yaml_db/bin/rails:5:in `<top (required)>'
/Users/my_username/src/rails_demo_unsafe_yaml_db/bin/spring:10:in `require'
/Users/my_username/src/rails_demo_unsafe_yaml_db/bin/spring:10:in `block in <top (required)>'
/Users/my_username/src/rails_demo_unsafe_yaml_db/bin/spring:7:in `tap'
/Users/my_username/src/rails_demo_unsafe_yaml_db/bin/spring:7:in `<top (required)>'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

> This step succeeds when I add an correct database.yml file

### System configuration
**Rails version**: `6.0.5.1`, `6.1.6.1`

**Ruby version**: `2.6`, `2.7`

**Comment by skipkayhil** [comment]
Hey @cmitz 👋 thanks for the repo, it made reproducing this super quick. The issue is the new patch loads `ActiveRecord::Base` in an initializer, which it should not be doing. 

The fix is #45584 @byroot the initializer commit should be backported to `6-1-stable`, `6-0-stable` and `5-2-stable`

**Comment by byroot** [comment]
Thanks for the heads up.

**Comment by byroot** [comment]
Done.

**Comment by skipkayhil** [comment]
Thanks! @cmitz you can point your app at `6-1-stable` to fix this if its urgent. I don't know if/when another 6.1.x release will be

**Comment by cmitz** [comment]
Awesome work people! Thanks for fixing it super quickly
