### ISSUE TITLE
ActiveRecord does not correctly format a parameterized array of bytes when querying a binary column

### ISSUE THREAD

**Issue by postmodern** [rails/rails#45760]
I ran into this bug where I was trying to query a binary column using a parameterized value. I assumed it must require an Array of bytes instead of a binary String. However, this resulted in the Array of bytes being formatted as `a,b,c`, which caused a SQL error.

### Steps to reproduce

Gemfile:

```ruby
source 'https://rubygems.org'

gem 'activerecord', '~> 7.0'
gem 'sqlite3',      '~> 1.0'
```

test.rb:

```ruby
#!/usr/bin/env ruby

require 'bundler/setup'
require 'active_record'

ActiveRecord::Base.establish_connection(
  adapter: 'sqlite3',
  database: 'test.sqlite3'
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

class CreateUsersTable < ActiveRecord::Migration[7.0]

  def change
    drop_table :users, if_exists: true
    create_table :users do |t|
      t.string :name, null: false
      t.string :email, null: false
      t.binary :bin_data, null: false
      t.index :email, unique: true
    end
  end

end

CreateUsersTable.migrate(:up)

class User < ActiveRecord::Base

  attribute :name, :string
  validates :name, presence: true

  attribute :email, :string
  validates :name, presence:   true,
                   uniqueness: true

end

bin_data = String.new("\x00\x01\x02", encoding: Encoding::ASCII_8BIT)
user = User.create(name: 'Test', email: 'test@example.com', bin_data: bin_data)

p User.where('bin_data = ?', [0x00, 0x01, 0x02])
```

### Expected behavior

Queries the `bin_data` column using the special SQLite3 literal binary string syntax of `bin_data = x'000102'`.

### Actual behavior

```
==  CreateUsersTable: migrating ===============================================
D, [2022-08-04T00:27:56.376569 #34771] DEBUG -- :    (0.8ms)  SELECT sqlite_version(*)
-- drop_table(:users, {:if_exists=>true})
D, [2022-08-04T00:27:56.631286 #34771] DEBUG -- :    (254.2ms)  DROP TABLE IF EXISTS "users"
   -> 0.2547s
-- create_table(:users)
D, [2022-08-04T00:27:56.739408 #34771] DEBUG -- :    (106.4ms)  CREATE TABLE "users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "email" varchar NOT NULL, "bin_data" blob NOT NULL)
D, [2022-08-04T00:27:56.872967 #34771] DEBUG -- :    (132.7ms)  CREATE UNIQUE INDEX "index_users_on_email" ON "users" ("email")
   -> 0.2413s
==  CreateUsersTable: migrated (0.4965s) ======================================

D, [2022-08-04T00:27:56.932140 #34771] DEBUG -- :   TRANSACTION (0.1ms)  begin transaction
D, [2022-08-04T00:27:56.933114 #34771] DEBUG -- :   User Exists? (0.7ms)  SELECT 1 AS one FROM "users" WHERE "users"."name" = ? LIMIT ?  [["name", "Test"], ["LIMIT", 1]]
D, [2022-08-04T00:27:56.934068 #34771] DEBUG -- :   User Create (0.3ms)  INSERT INTO "users" ("name", "email", "bin_data") VALUES (?, ?, ?)  [["name", "Test"], ["email", "test@example.com"], ["bin_data", "<3 bytes of binary data>"]]
D, [2022-08-04T00:27:57.051168 #34771] DEBUG -- :   TRANSACTION (116.8ms)  commit transaction
D, [2022-08-04T00:27:57.053506 #34771] DEBUG -- :   User Load (0.5ms)  SELECT "users".* FROM "users" WHERE (bin_data = 0,1,2) /* loading for inspect */ LIMIT ?  [["LIMIT", 11]]
/home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/database.rb:152:in `initialize': SQLite3::SQLException: row value misused (ActiveRecord::StatementInvalid)
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/database.rb:152:in `new'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/sqlite3-1.4.4/lib/sqlite3/database.rb:152:in `prepare'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:50:in `block (2 levels) in exec_query'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:47:in `block in exec_query'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:46:in `exec_query'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/querying.rb:54:in `_query_by_sql'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/relation.rb:941:in `block in exec_main_query'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/relation.rb:961:in `skip_query_cache_if_necessary'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/relation.rb:927:in `exec_main_query'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/relation.rb:913:in `block in exec_queries'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/relation.rb:961:in `skip_query_cache_if_necessary'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/relation.rb:907:in `exec_queries'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/relation.rb:695:in `load'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/relation.rb:250:in `records'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/relation.rb:245:in `to_ary'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/relation/finder_methods.rb:528:in `find_take_with_limit'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/relation/finder_methods.rb:98:in `take'
	from /home/postmodern/test/ruby/activerecord/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/relation.rb:795:in `inspect'
	from ./test.rb:42:in `p'
	from ./test.rb:42:in `<main>'
```

### System configuration

* libsqlite 3.36.0
* ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
* Gems included by the bundle:
  * activemodel (7.0.3.1)
  * activerecord (7.0.3.1)
  * activesupport (7.0.3.1)
  * bundler (2.3.17)
  * concurrent-ruby (1.1.10)
  * i18n (1.12.0)
  * minitest (5.16.2)
  * sqlite3 (1.4.4)
  * tzinfo (2.0.5)

**Comment by matthewd** [comment]
This one is expected behaviour: we have no context on the intended use of the `?` placeholder in the middle of a string, so we can only apply one interpretation. The meaning we historically settled on, when given an array, was to render it as a comma-separated list of individually escaped values (being intended for use as e.g. `"some_col IN (?)"`), which does indeed yield invalid SQL in a context that does not expect a list.
