### ISSUE TITLE
ArgumentError due to nil `pool_config` when calling `connects_to` 

### ISSUE THREAD

**Issue by lsylvester** [rails/rails#45767]
### Steps to reproduce

Create configuration for a second database.

Ensure that `legacy_connection_handling` is not in use.

Ensure that there are no fixture file for the secondary database. - if there are any fixture files then the Abstract class that configures the database referenced before the fixtures are loaded and it is able to be configured successfully.

Configure the databases in the abstract class using `reading` before `writing` in the `connects_to database:` hash - the error only occurs if the `pool_config` for the `reading` role is set before the `writing` roles.

Run tests.

Reproduced in application at https://github.com/lsylvester/connection-pool-error

### Expected behavior

Application should connect to second database.

### Actual behavior

```
Error:
DogTest#test_dog:
ArgumentError: The `pool_config` for the :reading role and :default shard was `nil`. Please check your configuration. If you want your writing role to be something other than `:writing` set `config.active_record.writing_role` in your application configuration. The same setting should be applied for the `reading_role` if applicable.
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/connection_adapters/pool_manager.rb:42:in `set_pool_config'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/test_fixtures.rb:234:in `block (3 levels) in setup_shared_connection_pool'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/test_fixtures.rb:229:in `each'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/test_fixtures.rb:229:in `block (2 levels) in setup_shared_connection_pool'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/test_fixtures.rb:226:in `each'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/test_fixtures.rb:226:in `block in setup_shared_connection_pool'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/test_fixtures.rb:224:in `each'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/test_fixtures.rb:224:in `setup_shared_connection_pool'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/test_fixtures.rb:140:in `block in setup_fixtures'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activesupport/lib/active_support/notifications/fanout.rb:236:in `finish'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activesupport/lib/active_support/notifications/fanout.rb:76:in `block in finish'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activesupport/lib/active_support/notifications/fanout.rb:91:in `block in iterate_guarding_exceptions'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activesupport/lib/active_support/notifications/fanout.rb:90:in `each'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activesupport/lib/active_support/notifications/fanout.rb:90:in `iterate_guarding_exceptions'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activesupport/lib/active_support/notifications/fanout.rb:76:in `finish'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activesupport/lib/active_support/notifications/instrumenter.rb:49:in `finish_with_state'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activesupport/lib/active_support/notifications/instrumenter.rb:30:in `instrument'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:154:in `establish_connection'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/connection_handling.rb:95:in `block in connects_to'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/connection_handling.rb:90:in `each'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/rails-d60d0587c3c1/activerecord/lib/active_record/connection_handling.rb:90:in `connects_to'
    /Users/lachlansylvester/Blake/connection-pool/app/models/animals_record.rb:4:in `<class:AnimalsRecord>'
    /Users/lachlansylvester/Blake/connection-pool/app/models/animals_record.rb:1:in `<main>'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
    /Users/lachlansylvester/Blake/connection-pool/app/models/dog.rb:1:in `<main>'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
    /Users/lachlansylvester/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
    /Users/lachlansylvester/Blake/connection-pool/test/models/dog_test.rb:6:in `block in <class:DogTest>'
```

### System configuration
**Rails version**: Rails 6.1 / Edge

**Ruby version**: 3.0.1

**Comment by eileencodes** [comment]
Thanks for the report. I've confirmed that I can reproduce this on main and will work on a fix today.
