### ISSUE TITLE
Google::Apis::ClientError raised when using ActiveStorage to generate signed URLs to access a file in a GCS bucket with GKE Workload Identity

### ISSUE THREAD

**Issue by danielyazbek** [rails/rails#45791]
### Steps to reproduce
Configure ActiveStorage with GKE Workload identity (as documented [here](https://edgeguides.rubyonrails.org/active_storage_overview.html#google-cloud-storage-service)):

```ruby
google:
  service: GCS
  iam: true
  project: <%= ENV['ACTIVE_STORAGE_PROJECT'] %>
  bucket: <%= ENV['ACTIVE_STORAGE_BUCKET'] %>
```

Define a class:
```ruby
class Transaction < ApplicationRecord
  has_one_attached :csv_report
end
```

Write something to ActiveStorage:
```ruby
t = Transaction.create
t.csv_report.attach(io: StringIO.new("A,B,C"), filename: 'test.csv')
```

Generate a Signed URL
```ruby
Rails.application.routes.url_helpers.rails_blob_url(Transaction.last.csv_report, disposition: 'attachment')
```

Paste the generated URL into a browser

### Expected behavior
ActiveRecord provides the attachment

### Actual behavior
Error is raised:

```
Google::Apis::ClientError (Invalid request):
gems/google-apis-core-0.7.0/lib/google/apis/core/http_command.rb:236:in `check_status': Invalid request (Google::Apis::ClientError)
    from gems/google-apis-core-0.7.0/lib/google/apis/core/api_command.rb:134:in `check_status'
    from gems/google-apis-core-0.7.0/lib/google/apis/core/http_command.rb:199:in `process_response'
    from gems/google-apis-core-0.7.0/lib/google/apis/core/http_command.rb:318:in `execute_once'
    from gems/google-apis-core-0.7.0/lib/google/apis/core/http_command.rb:118:in `block (2 levels) in execute'
    from gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
    from gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
    from gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
    from gems/google-apis-core-0.7.0/lib/google/apis/core/http_command.rb:115:in `block in execute'
    from gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
    from gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
    from gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
    from gems/google-apis-core-0.7.0/lib/google/apis/core/http_command.rb:105:in `execute'
    from gems/google-apis-core-0.7.0/lib/google/apis/core/base_service.rb:397:in `execute_or_queue_command'
    from gems/google-apis-iamcredentials_v1-0.13.0/lib/google/apis/iamcredentials_v1/service.rb:158:in `sign_service_account_blob'
    from gems/activestorage-7.0.3.1/lib/active_storage/service/gcs_service.rb:232:in `block in signer'
    from gems/google-cloud-storage-1.38.0/lib/google/cloud/storage/file/signer_v2.rb:135:in `generate_signature'
    from gems/google-cloud-storage-1.38.0/lib/google/cloud/storage/file/signer_v2.rb:128:in `signed_url'
    from gems/google-cloud-storage-1.38.0/lib/google/cloud/storage/file.rb:1801:in `signed_url'
    from gems/activestorage-7.0.3.1/lib/active_storage/service/gcs_service.rb:160:in `private_url'
    from gems/activestorage-7.0.3.1/lib/active_storage/service.rb:123:in `block in url'
    from gems/activesupport-7.0.3.1/lib/active_support/notifications.rb:206:in `block in instrument'
    from gems/activesupport-7.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from gems/activesupport-7.0.3.1/lib/active_support/notifications.rb:206:in `instrument'
    from gems/activestorage-7.0.3.1/lib/active_storage/service.rb:163:in `instrument'
    from gems/activestorage-7.0.3.1/lib/active_storage/service.rb:118:in `url'
    from gems/activestorage-7.0.3.1models/active_storage/blob.rb:217:in `url'
    from gems/activestorage-7.0.3.1controllers/active_storage/blobs/redirect_controller.rb:14:in `show'
```

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**google-cloud-storage gem version:** 1.38.0

**Comment by Tho85** [comment]
I had the same issue today and was able to fix it. The service account was missing the `iam.serviceAccounts.signBlob` permission which is required to sign URLs. Fixed it by assigning the service account to the role `roles/iam.serviceAccountTokenCreator`.

Maybe this should be added to the docs?

**Comment by skipkayhil** [comment]
> Maybe this should be added to the docs?

Feel free to open a PR 😃

**Comment by shpml** [comment]
It's probably not a great idea to have `roles/iam.serviceAccountTokenCreator` at a project level. It gives access to all service accounts in the project, including service accounts created in the future and default accounts created by GCP.

It might be best to figure out what service account it needs create a token for, at a guess it is the default storage account for the storage service or something. Another alternative would be create a custom role with `iam.serviceAccounts.signBlob` as the only permission and assign that custom role to the service account.

- https://docs.bridgecrew.io/docs/bc_gcp_iam_3
- https://www.trendmicro.com/cloudoneconformity/knowledge-base/gcp/CloudIAM/check-for-iam-users-with-service-roles.html#
