### ISSUE TITLE
Change Column with Raw Character Set Failure

### ISSUE THREAD

**Issue by ahoglund** [rails/rails#45823]
With [this recent change to how collation is handled for column changes](https://github.com/rails/rails/pull/45744/files), there is now a potential for older migrations written in a specific manner to break if the `collation:` argument is not specific.

### Steps to reproduce

```ruby
# frozen_string_literal: true

# you need to install mysql locally for this to work.
# on Mac:
# brew install mysql
# brew services start mysql

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "mysql2"

end

require "active_record"
require "minitest/autorun"
require "logger"

client = Mysql2::Client.new(host: 'localhost', username: "root")
client.query("DROP DATABASE test")
client.query("CREATE DATABASE test")

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "mysql2", database: "test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :payments, force: true do |t|
    t.string :description, "varchar(64)", null: false
  end
end

class Payment < ActiveRecord::Base
end

class ChangeAmountToAddScale < ActiveRecord::Migration[7.1]
  # This sets the default character set for the payments
  # table to utf32 with a default COLLATION of utf32_general_ci.
  # This can be verified by running the following query:
  #
  # SHOW CHARACTER SET;
  #
  connection.execute(<<~SQL)
    ALTER TABLE payments CONVERT TO CHARACTER SET utf32
  SQL

  def change
    reversible do |dir|
      dir.up do
        change_table(:payments, bulk: true) do |t|
          # The default collation of utf32_general_ci
          # will not be compatible with this ascii character set. 
          #
          # when we build the column change now we automatically
          # try to assign the previous collation to the column if no `collation:` is specified.
          # 
          # https://github.com/rails/rails/pull/45744
          #
          # The workaround is to add `collation: 'ascii_bin'` or `collation: 'ascii_general_ci'` to the change.
          #
          # This isn't a huge deal and it has a workaround but it _will_ break
          # anyone who has migrations that are written like this and upgrade to this version
          # of Rails.
          t.change :description, "varchar(64) CHARACTER SET ascii", null: false
        end
      end

      dir.down do
        change_table(:payments, bulk: true) do |t|
          t.change :description, "varchar(64)", null: false
        end
      end
    end
  end
end

class BugTest < Minitest::Test
  def test_migration_up
    ChangeAmountToAddScale.migrate(:up)
    Payment.reset_column_information

    assert_equal "varchar", Payment.columns.last.sql_type
  end

  def test_migration_down
    ChangeAmountToAddScale.migrate(:down)
    Payment.reset_column_information

    assert_equal "varchar", Payment.columns.last.sql_type
  end
end
```

### Expected behavior

I would expect this to detect that the character set is being changed, and either 

1. change the collation to be compatible.
2. At least give a clearer error that requires the `collation:` arg to be passed when the character set is being modified.

### Actual behavior

This error:

```
Error:
BugTest#test_migration_up:
ActiveRecord::StatementInvalid: Mysql2::Error: COLLATION 'utf32_general_ci' is not valid for CHARACTER SET 'ascii'
    test.rb:51:in `block (2 levels) in change'
    test.rb:50:in `block in change'
    test.rb:49:in `change'
    test.rb:67:in `test_migration_up'
```

### System configuration
**Rails version**: main
**Ruby version**: ruby 3.1.1p18

**Comment by byroot** [comment]
I've just been made aware of this issue, sorry for not noticing it sooner, but also don't hesitate to comment on the original PR when you identify it.

I think the new behavior is still desirable, however we shouldn't break old migrations. I think we just need to only enable that new behavior if the migration was written for Rails 7.1.

cc @fatkodima let me know if you wish to handle this, otherwise I'll try to tackle it early next week (cc @casperisfine)
