### ISSUE TITLE
7-0-stable still breaks with ActiveRecord.serialize with yaml coder

### ISSUE THREAD

**Issue by renatolond** [rails/rails#45846]
### Steps to reproduce

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "7-0-stable"
  gem "sqlite3"
end

require "action_controller/railtie"
require "active_record"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    post "/" => "test#index"
  end
end

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text :data
  end
end

class Post < ActiveRecord::Base
  serialize :data
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    Post.create!(params.permit(data: [:title]))
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    post "/", data: { title: "who needs a schema?" }
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior

It should serialize simple values into the data column & back out, like it used to in Rails 7.0.3

### Actual behavior

An PsychDisallowedClass is raised:
```
Psych::DisallowedClass: Tried to load unspecified class: ActiveSupport::HashWithIndifferentAccess
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/psych/class_loader.rb:97:in `find'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/psych/class_loader.rb:28:in `load'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:411:in `resolve_class'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:283:in `visit_Psych_Nodes_Mapping'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:313:in `visit_Psych_Nodes_Document'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/psych.rb:360:in `safe_load'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/coders/yaml_column.rb:61:in `yaml_load'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/coders/yaml_column.rb:26:in `load'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/type/serialized.rb:22:in `deserialize'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activemodel/lib/active_model/type/helpers/mutable.rb:8:in `cast'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activemodel/lib/active_model/attribute.rb:179:in `type_cast'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activemodel/lib/active_model/attribute.rb:43:in `value'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activemodel/lib/active_model/attribute_set.rb:46:in `fetch_value'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/transactions.rb:403:in `block in restore_transaction_record_state'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activemodel/lib/active_model/attribute_set.rb:93:in `transform_values'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activemodel/lib/active_model/attribute_set.rb:93:in `map'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/transactions.rb:402:in `restore_transaction_record_state'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/transactions.rb:334:in `rolledback!'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:134:in `rollback_records'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:312:in `block in rollback_transaction'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:309:in `rollback_transaction'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:325:in `rescue in block in within_new_transaction'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:322:in `block in within_new_transaction'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/transactions.rb:302:in `save!'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/suppressor.rb:54:in `save!'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activerecord/lib/active_record/persistence.rb:55:in `create!'
test.rb:47:in `index'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/abstract_controller/base.rb:215:in `process_action'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_controller/metal/rendering.rb:53:in `process_action'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/callbacks.rb:99:in `run_callbacks'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/abstract_controller/callbacks.rb:233:in `process_action'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/notifications.rb:206:in `block in instrument'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/notifications.rb:206:in `instrument'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/abstract_controller/base.rb:151:in `process'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionview/lib/action_view/rendering.rb:39:in `process'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_controller/metal.rb:188:in `dispatch'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_controller/metal.rb:251:in `dispatch'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/journey/router.rb:32:in `each'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/journey/router.rb:32:in `serve'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/routing/route_set.rb:852:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/rack-2.2.4/lib/rack/etag.rb:27:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/rack-2.2.4/lib/rack/conditional_get.rb:40:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/middleware/cookies.rb:696:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/activesupport/lib/active_support/callbacks.rb:99:in `run_callbacks'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/railties/lib/rails/rack/logger.rb:40:in `call_app'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/railties/lib/rails/rack/logger.rb:27:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/middleware/static.rb:23:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/actionpack/lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/bundler/gems/rails-cd673773bc65/railties/lib/rails/engine.rb:530:in `call'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/rack-test-2.0.2/lib/rack/test.rb:358:in `process_request'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/rack-test-2.0.2/lib/rack/test.rb:165:in `custom_request'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/rack-test-2.0.2/lib/rack/test.rb:114:in `post'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/2.7.0/forwardable.rb:235:in `post'
test.rb:62:in `test_returns_success'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest/test.rb:98:in `block (3 levels) in run'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest/test.rb:195:in `capture_exceptions'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest/test.rb:95:in `block (2 levels) in run'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:296:in `time_it'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest/test.rb:94:in `block in run'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:391:in `on_signal'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest/test.rb:243:in `with_info_handler'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest/test.rb:93:in `run'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:1059:in `run_one_method'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:365:in `run_one_method'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:352:in `block (2 levels) in run'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:351:in `each'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:351:in `block in run'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:391:in `on_signal'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:378:in `with_info_handler'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:350:in `run'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:182:in `block in __run'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:182:in `map'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:182:in `__run'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:159:in `run'
/home/renatolond/.rvm/rubies/ruby-2.7.6-jemalloc/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:83:in `block in autorun'
```

### System configuration
**Rails version**: From 7-0-stable, which has the fix for #45585

**Ruby version**: 2.7.6

**Comment by eileencodes** [comment]
The issue you linked was calling hash with indifferent access internally which was unnecessary, but your reproduction is calling `with_indifferent_access` so you need to add `ActiveSupport::HashWithIndifferentAccess` to your `ActiveRecord.yaml_column_permitted_classes`.

**Comment by renatolond** [comment]
Sorry, my example was not too clear. I rewrote with a controller so that the issue we're facing is a bit more clear, because we're not explictly using `HashWithIndifferentAccess`, the controller is doing it

**Comment by byroot** [comment]
Sure, but it's your code that pass the value as a `HashWithIndifferentAccess`, not Rails.

You can either allow that type, or cast the value as a regular hash.
