### ISSUE TITLE
No implicit conversion of String into Integer (TypeError) - when commiting record to the database

### ISSUE THREAD

**Issue by bcoelh0** [rails/rails#45879]
### Steps to reproduce
```
rails new testApp
cd testApp
rails g model Test hash:string
rake db:migrate
rails console
> t = Test.create!(hash: "sdas")
(1.2ms)  SELECT sqlite_version(*)
 TRANSACTION (0.1ms)  begin transaction
  Test Create (2.9ms)  INSERT INTO "tests" ("hash", "created_at", "updated_at") VALUES (?, ?, ?)  [["hash", "sdas"], ["created_at", "2022-08-24 12:37:30.474479"], ["updated_at", "2022-08-24 12:37:30.474479"]]
  TRANSACTION (1.1ms)  commit transaction

/Users/<user>/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:156:in `commit_records': no implicit conversion of String into Integer (TypeError)
```

### Expected behavior
Expected object to be created in the database with no errors AND object to be returned

### Actual behavior
The record is actually saved to the database, but this error is returned 
The variable `t` is set to `nil` instead of the object just saved.
This only happens if the record has one of the fields named `hash`. Any class without this field saves to the database without any issues.

### Fix
I was able to fix this locally simply by changing the affected lines to use the method `to_s` on `record`

```
should_run_callbacks = !already_run_callbacks[record.to_s] && trigger_callbacks
already_run_callbacks[record.to_s] ||= trigger_callbacks
```
This works for me as a quick fix, but not sure if this is the best fix.

### System configuration
**Rails version**: Rails 7.0.3.1
**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

**Comment by byroot** [comment]
Thanks for the report, could you produce a repro script using this template? https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb

That would make it much easier for us to look into this.

**Comment by fatkodima** [comment]
Repro script:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :tests, force: true do |t|
    t.string :hash
  end
end

class Test < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_create_with_hash_attribute
    t = Test.create!(hash: "something")
    assert_equal "something", t.hash
  end
end
```

```
Error:
BugTest#test_create_with_hash_attribute:
TypeError: no implicit conversion of String into Integer
    /Users/fatkodima/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-aa85e8973123/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:221:in `block in prepare_instances_to_run_callbacks_on'
    /Users/fatkodima/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-aa85e8973123/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:200:in `each'
    /Users/fatkodima/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-aa85e8973123/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:200:in `each_with_object'
    /Users/fatkodima/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-aa85e8973123/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:200:in `prepare_instances_to_run_callbacks_on'
    /Users/fatkodima/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-aa85e8973123/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:177:in `commit_records'
... snip ...
```

The problem is that Active Record defines an attribute method for `hash` column, but `hash` method is used by `Hash` class for keys.

1. So first of all, it is better to avoid having columns named like `hash`, `object_id` etc, that will cause problems in other places. 

2. There is already a check for "dangerous" attribute names - https://github.com/rails/rails/blob/aa85e897312396b5c6993d8092b9aff7faa93011/activerecord/lib/active_record/attribute_methods.rb#L31-L38

Probably we can extend it with some other methods like `hash`?

3. I was able to kinda fix this problem (all tests passed) with the following hacky solution:
```diff
diff --git a/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb
index 44adf0d950..851ec1b70a 100644
--- a/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb
+++ b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb
@@ -155,7 +155,7 @@ def rollback_records
         instances_to_run_callbacks_on = prepare_instances_to_run_callbacks_on(ite)

         while record = ite.shift
-          should_run_callbacks = record.__id__ == instances_to_run_callbacks_on[record].__id__
+          should_run_callbacks = record.__id__ == instances_to_run_callbacks_on[record.__hash__].__id__
           record.rolledback!(force_restore_state: full_rollback?, should_run_callbacks: should_run_callbacks)
diff --git a/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb b/activerecord/lib/active_record/connection_adapters/abstract/transact
ion.rb
index 44adf0d950..851ec1b70a 100644
--- a/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb
+++ b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb
@@ -155,7 +155,7 @@ def rollback_records
         instances_to_run_callbacks_on = prepare_instances_to_run_callbacks_on(ite)

         while record = ite.shift
-          should_run_callbacks = record.__id__ == instances_to_run_callbacks_on[record].__id__
+          should_run_callbacks = record.__id__ == instances_to_run_callbacks_on[record.__hash__].__id__
           record.rolledback!(force_restore_state: full_rollback?, should_run_callbacks: should_run_callbacks)
         end
       ensure
@@ -177,7 +177,7 @@ def commit_records
           instances_to_run_callbacks_on = prepare_instances_to_run_callbacks_on(ite)

           while record = ite.shift
-            should_run_callbacks = record.__id__ == instances_to_run_callbacks_on[record].__id__
+            should_run_callbacks = record.__id__ == instances_to_run_callbacks_on[record.__hash__].__id__
             record.committed!(should_run_callbacks: should_run_callbacks)
           end
         else
@@ -200,7 +200,7 @@ def prepare_instances_to_run_callbacks_on(records)
           records.each_with_object({}) do |record, candidates|
             next unless record.trigger_transactional_callbacks?

-            earlier_saved_candidate = candidates[record]
+            earlier_saved_candidate = candidates[record.__hash__]

             next if earlier_saved_candidate && record.class.run_commit_callbacks_on_first_saved_instances_in_transaction

@@ -218,7 +218,7 @@ def prepare_instances_to_run_callbacks_on(records)

             # The last instance to save itself is likeliest to have internal
             # state that matches what's committed to the database
-            candidates[record] = record
+            candidates[record.__hash__] = record
           end
         end
     end
diff --git a/activerecord/lib/active_record/core.rb b/activerecord/lib/active_record/core.rb
index 0aa59fe885..b285993909 100644
--- a/activerecord/lib/active_record/core.rb
+++ b/activerecord/lib/active_record/core.rb
@@ -580,6 +580,7 @@ def hash
         super
       end
     end
+    alias :__hash__ :hash

     # Clone and freeze the attributes hash such that associations are still
     # accessible, even on destroyed records, but cloned models will not be
```

**Comment by byroot** [comment]
Ah good catch @fatkodima.

I don't think we should work around this. Adding `hash` to the list of dangerous methods should be enough.

**Comment by fatkodima** [comment]
Agreed, will open a PR. Do you think other methods should be also added?

**Comment by byroot** [comment]
Possibly yes, looking (very quickly) at https://ruby-doc.org/core-3.1.1/Object.html and https://ruby-doc.org/core-3.1.1/BasicObject.html

- `__id__`
- `__send__`
- `method_missing`
- `dup`
- `hash`
- `freeze` ?
- `inspect`
- `public_send`
- `send`

Which is quite a long list and somewhat arbitrary.

Another option would be not to exclude the methods that were inherited, but then have a small exclusion list for `Object` methods that are unlikely to be a problem and are common names (e.g. `Object#display`).
