### ISSUE TITLE
Active Job integration tests for `resque` and `sidekiq` fail with `redis` 5.0.1 and `redis-client` 0.7.1

### ISSUE THREAD

**Issue by yahonda** [rails/rails#45913]
Managed to reproduce https://buildkite.com/rails/rails/builds/89114#0182ef6a-4316-4671-981b-3dafdeee29a2

### Steps to reproduce
```ruby
git clone https://github.com/rails/rails
cd rails/activejob
bundle update redis --conservative
git diff
bundle exec rake test:integration:resque
AJ_INTEGRATION_TESTS=1 AJ_ADAPTER=sidekiq bin/test test/integration/queuing_test.rb
```

### Expected behavior
Both of Active Job integration tests for `resque` and `sidekiq` should pass.

### Actual behavior
```ruby
$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 28cfa23d9c..c39161f625 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -400,7 +400,10 @@ GEM
     rbtree (0.4.5)
     rdoc (6.3.3)
     redcarpet (3.2.3)
-    redis (4.7.1)
+    redis (5.0.1)
+      redis-client (~> 0.7)
+    redis-client (0.7.1)
+      connection_pool
     redis-namespace (1.8.1)
       redis (>= 3.0.4)
     regexp_parser (2.2.1)
$
```

* for resque `redis-client-0.7.1/lib/redis_client/config.rb:20:in `initialize': unknown keyword: :thread_safe (ArgumentError)`

```ruby
$ bundle exec rake test:integration:resque
/home/yahonda/.rbenv/versions/3.1.2/bin/ruby -w -I"lib:test" /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb "test/integration/queuing_test.rb"
Using resque
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:24: warning: method redefined; discarding old require
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27: warning: previous definition of require was here
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32454: warning: statement not reached
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32615: warning: statement not reached
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32651: warning: statement not reached
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32740: warning: statement not reached
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32756: warning: statement not reached
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32822: warning: statement not reached
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32863: warning: statement not reached
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:32888: warning: statement not reached
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:31984: warning: assigned but unused variable - testEof
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:370: warning: assigned but unused variable - pathlen
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:51: warning: method redefined; discarding old initialize
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_cert
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_file
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_path
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cookiejar-0.3.3/lib/cookiejar/cookie.rb:183: warning: mismatched indentations at 'end' with 'else' at 181
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cookiejar-0.3.3/lib/cookiejar/jar.rb:225: warning: mismatched indentations at 'end' with 'else' at 223
/home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.7.1/lib/redis_client/config.rb:20:in `initialize': unknown keyword: :thread_safe (ArgumentError)
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.7.1/lib/redis_client/config.rb:155:in `initialize'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.7.1/lib/redis_client.rb:122:in `new'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.7.1/lib/redis_client.rb:122:in `config'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.1/lib/redis/client.rb:22:in `config'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.1/lib/redis.rb:157:in `initialize_client'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.1/lib/redis.rb:73:in `initialize'
	from /home/yahonda/src/github.com/rails/rails/activejob/test/support/integration/adapters/resque.rb:6:in `new'
	from /home/yahonda/src/github.com/rails/rails/activejob/test/support/integration/adapters/resque.rb:6:in `setup'
	from /tmp/d20220831-278031-adlbts/dummy/config/initializers/activejob.rb:2:in `<main>'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/engine.rb:673:in `block in load_config_initializer'
	from /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/notifications.rb:208:in `instrument'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/engine.rb:672:in `load_config_initializer'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/engine.rb:626:in `block (2 levels) in <class:Engine>'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/engine.rb:625:in `each'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/engine.rb:625:in `block in <class:Engine>'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/initializable.rb:32:in `run'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/initializable.rb:50:in `each'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:415:in `call'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/application.rb:372:in `initialize!'
	from /tmp/d20220831-278031-adlbts/dummy/config/environment.rb:5:in `<top (required)>'
	from /home/yahonda/src/github.com/rails/rails/activejob/test/support/integration/helper.rb:16:in `require'
	from /home/yahonda/src/github.com/rails/rails/activejob/test/support/integration/helper.rb:16:in `<top (required)>'
	from /home/yahonda/src/github.com/rails/rails/activejob/test/helper.rb:12:in `require'
	from /home/yahonda/src/github.com/rails/rails/activejob/test/helper.rb:12:in `<top (required)>'
	from /home/yahonda/src/github.com/rails/rails/activejob/test/integration/queuing_test.rb:3:in `require'
	from /home/yahonda/src/github.com/rails/rails/activejob/test/integration/queuing_test.rb:3:in `<top (required)>'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `require'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
	from /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" /home/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb "test/integration/queuing_test.rb" ]
/home/yahonda/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/home/yahonda/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => test:integration:resque
(See full trace by running task with --trace)
$
```

* for sidekiq

```ruby
$ AJ_INTEGRATION_TESTS=1 AJ_ADAPTER=sidekiq bin/test test/integration/queuing_test.rb
Using sidekiq
Run options: --seed 44047

# Running:

.F

Failure:
QueuingTest#test_should_run_jobs_enqueued_on_a_listening_queue [/home/yahonda/src/github.com/rails/rails/activejob/test/integration/queuing_test.rb:13]:
Job AJ-129bbbb5-e8ba-480b-b4b6-5f386868c6e4 was not executed


bin/test test/integration/queuing_test.rb:10

F

Failure:
QueuingTest#test_current_timezone_is_kept_while_running_perform_later [/home/yahonda/src/github.com/rails/rails/activejob/test/integration/queuing_test.rb:118]:
Job AJ-a1d7d95b-4a1e-45b9-ab5f-7d50a809fe41 was not executed


bin/test test/integration/queuing_test.rb:109

.SF

Failure:
QueuingTest#test_current_locale_is_kept_while_running_perform_later [/home/yahonda/src/github.com/rails/rails/activejob/test/integration/queuing_test.rb:101]:
Job AJ-eaf07152-0f27-4d5d-8b81-4023971c352e was not executed


bin/test test/integration/queuing_test.rb:92

SSS.F

Failure:
QueuingTest#test_should_run_job_enqueued_in_the_future_at_the_specified_time [/home/yahonda/src/github.com/rails/rails/activejob/test/integration/queuing_test.rb:75]:
Job AJ-3152b499-0fbe-4e13-ae37-ccc708eb7784 was not executed


bin/test test/integration/queuing_test.rb:70

...

Finished in 34.074661s, 0.4109 runs/s, 0.3522 assertions/s.
14 runs, 12 assertions, 4 failures, 0 errors, 4 skips

You have skipped tests. Run with --verbose for details.
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by yahonda** [comment]
`for resque redis-client-0.7.1/lib/redis_client/config.rb:20:in initialize': unknown keyword: :thread_safe (ArgumentError)` looks like fixed via https://github.com/resque/resque/pull/1822

**Comment by yahonda** [comment]
Other compatibility issues are explained at https://github.com/redis/redis-rb/issues/1142

**Comment by byroot** [comment]
I'm currently fixing the remaining issues in https://github.com/resque/resque/pull/1828

After than we should be good to unlock the redis dependency.

**Comment by byroot** [comment]
So we're good on the resque front, however I missed that sidekiq is failing too, I'll have to investigate that because AFAIK Sidekiq doesn't really have a problem with latest redis-rb
