### ISSUE TITLE
Cannot load such file -- redis/connection/hiredis (LoadError)

### ISSUE THREAD

**Issue by qquokka** [rails/rails#45996]
Hi. I'm trying to upgrade the ruby version from 2.6.6 to 2.7.5 and the rails version from 6.0.3.3 to 6.1.7 of my existing project, which works well now. The problem is that Rails cannot load a certain file related with the redis gem although I've changed nothing but the ruby and the rails version. Is the redis version not corresponding to the rails's?

### Steps to reproduce
The below codes are written in [the hiredis gem README](https://github.com/redis/hiredis-rb#redis-rb)

```ruby
# Gemfile

gem "hiredis", '0.6.3'
gem 'redis', '5.0.4', :require => ["redis", "redis/connection/hiredis"]
gem 'redis-namespace', '1.9.0'
```

```bash
$ bundle install

$ rails s
```

### Expected behavior
Successfully run the server.

### Actual behavior
```bash
$ rails s

Traceback (most recent call last):
	25: from bin/rails:6:in `<main>'
	24: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:33:in `require'
	23: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:33:in `require'
	22: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.1.7/lib/rails/commands.rb:18:in `<main>'
	21: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.1.7/lib/rails/command.rb:48:in `invoke'
	20: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.1.7/lib/rails/command/base.rb:69:in `perform'
	19: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	18: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	17: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	16: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.1.7/lib/rails/commands/server/server_command.rb:135:in `perform'
	15: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.1.7/lib/rails/commands/server/server_command.rb:135:in `tap'
	14: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.1.7/lib/rails/commands/server/server_command.rb:138:in `block in perform'
	13: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
	12: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
	11: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
	10: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:33:in `require'
	 9: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:33:in `require'
	 8: from /Users/yanghyejin/workspace/deali/bird/config/application.rb:23:in `<main>'
	 7: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler.rb:174:in `require'
	 6: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
	 5: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
	 4: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
	 3: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
	 2: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
	 1: from /Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18:in `require'
/Users/yanghyejin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18:in `require': cannot load such file -- redis/connection/hiredis (LoadError)
```

### System configuration
**Rails version**: 6.1.7

**Ruby version**: 2.7.5

Chipset: M1(mac)

**Comment by khoerodin** [comment]
Hi @qquokka, I have the same problem, how to solve it?
