### ISSUE TITLE
Upgrading to Ruby v3, wrong number of arguments (given 4, expected 1..3) in query_cache.rb

### ISSUE THREAD

**Issue by stephenarifin** [rails/rails#46028]
### Steps to reproduce

Not sure how to reproduce. Only happens when I run my test suite. This started happening when I upgraded from Ruby 2.7.3 to Ruby 3.0.4

```ruby
# Your reproduction script goes here
```

### Expected behavior

Should be able to call SQL queries without crashing

### Actual behavior

```
ArgumentError:
       wrong number of arguments (given 4, expected 1..3)
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/query_cache.rb:96:in `select_all'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/connection_pool-2.2.2/lib/connection_pool.rb:157:in `block in method_missing'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/connection_pool-2.2.2/lib/connection_pool.rb:136:in `with'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/connection_pool-2.2.2/lib/connection_pool.rb:156:in `method_missing'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/querying.rb:47:in `find_by_sql'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation.rb:843:in `block in exec_queries'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation.rb:861:in `skip_query_cache_if_necessary'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation.rb:828:in `exec_queries'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation.rb:631:in `load'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation.rb:249:in `records'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation.rb:244:in `to_ary'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation/finder_methods.rb:553:in `find_nth_with_limit'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation/finder_methods.rb:538:in `find_nth'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation/finder_methods.rb:122:in `first'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation/finder_methods.rb:153:in `last'
     # ./app/models/concerns/sortable_by_date_created.rb:12:in `block (2 levels) in <module:SortableByDateCreated>'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `instance_exec'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `block in _exec_scope'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation.rb:804:in `_scoping'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `_exec_scope'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.7/lib/active_record/scoping/named.rb:176:in `block in scope'
     # ./spec/services/properties/create_property_spec.rb:22:in `block (2 levels) in <module:Properties>'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/ruby-debug-ide-2.3.1/lib/ruby-debug-ide.rb:100:in `debug_load'
     # /Users/stephenarifin/.rvm/gems/ruby-3.0.4/gems/ruby-debug-ide-2.3.1/lib/ruby-debug-ide.rb:100:in `debug_program'


```
### System configuration
**Rails version**:

v6.1.7

**Ruby version**:

v3.0.4

I'm not sure what's going on and I've been stuck on this for hours. For some reason, when ActiveRecord calls 

`result_set = connection.select_all(sanitize_sql(sql), "#{name} Load", binds, preparable: preparable)`

an exception is thrown about incorrect arguments. I know the argument syntax is correct because I've reproduced a dummy function with the same parameters and can call the function as is.

For reference, here's `query_cache.rb`

```
      def select_all(arel, name = nil, binds = [], preparable: nil)
        if @query_cache_enabled && !locked?(arel)
          arel = arel_from_relation(arel)
          sql, binds, preparable = to_sql_and_binds(arel, binds, preparable)

          cache_sql(sql, name, binds) { super(sql, name, binds, preparable: preparable) }
        else
          super
        end
      end
```

And here's all of `find_by_sql`

```
    def find_by_sql(sql, binds = [], preparable: nil, &block)
      result_set = connection.select_all(sanitize_sql(sql), "#{name} Load", binds, preparable: preparable)
      column_types = result_set.column_types

      ActiveRecord::ConnectionAdapters::PostgreSQLAdapter

      unless column_types.empty?
        column_types = column_types.reject { |k, _| attribute_types.key?(k) }
      end

      message_bus = ActiveSupport::Notifications.instrumenter

      payload = {
        record_count: result_set.length,
        class_name: name
      }

      message_bus.instrument("instantiation.active_record", payload) do
        if result_set.includes_column?(inheritance_column)
          result_set.map { |record| instantiate(record, column_types, &block) }
        else
          # Instantiate a homogeneous set
          result_set.map { |record| instantiate_instance_of(self, record, column_types, &block) }
        end
      end
    end
```

It's really strange because it only happens in the test suite. Any help or pointers would be appreciated!

**Comment by stephenarifin** [comment]
Just figured it out, of course after I post!

I followed this guide: http://blog.plataformatec.com.br/2011/12/three-tips-to-improve-the-performance-of-your-test-suite/

Step #3 overrode the connection method in ActiveRecord, which I guess fucked everything up. Remove the code fixed everything!
