### ISSUE TITLE
Upgrade causing error: ArgumentError: wrong number of arguments (given 3, expected 2)

### ISSUE THREAD

**Issue by dmc2015** [rails/rails#46176]
### Steps to reproduce

Upgraded from ruby 2.4 to ruby 3.0
Rails version Rails 5.2.8.1

```ruby
rails c
```
I cannot get in to the console to do any of these tests.

### Expected behavior

Enter the console

### Actual behavior

Error:
```
/Users/user/.rvm/gems/ruby-3.0.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/static.rb:111:in `initialize': wrong number of arguments (given 3, expected 2) (ArgumentError)
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/stack.rb:37:in `new'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/stack.rb:37:in `build'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/stack.rb:101:in `block in build'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/stack.rb:101:in `each'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/stack.rb:101:in `inject'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/stack.rb:101:in `build'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/engine.rb:510:in `block in app'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/engine.rb:506:in `synchronize'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/engine.rb:506:in `app'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `instance_exec'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `run'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /Users/don/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /Users/don/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /Users/don/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /Users/don/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /Users/don/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /Users/don/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /Users/don/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /Users/don/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /Users/don/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:60:in `run_initializers'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/application.rb:361:in `initialize!'
        from /Users/don/dev/prj/config/environment.rb:5:in `<top (required)>'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/application.rb:337:in `require_environment!'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/command/actions.rb:28:in `require_environment!'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/commands/console/console_command.rb:95:in `perform'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/command/base.rb:69:in `perform'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/command.rb:46:in `invoke'
        from /Users/don/.rvm/gems/ruby-3.0.0/gems/railties-5.2.8.1/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```
### System configuration
**Rails version**:
 5.2.8.1

**Ruby version**:
ruby 3.0

Seems to be the same as these issues:

https://stackoverflow.com/questions/66750055/wrong-number-of-arguments-errors-when-upgrading-rails-5-2-to-6-0

I think I've narrowed the location down to here, but I am not sure what to do with it:

`/Users/user/.rvm/gems/ruby-3.0.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/stack.rb:102:in`

```
100: def build(app = nil, &block)
101:   binding.pry
=> 102:   middlewares.freeze.reverse.inject(app || block) { |a, e| e.build(a) }
    103: end

[1] pry(#<ActionDispatch::MiddlewareStack>)> middlewares.freeze.reverse.inject(app || block) { |a, e| e.build(a) }
ArgumentError: wrong number of arguments (given 3, expected 2)
from /Users/user/.rvm/gems/ruby-3.0.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/static.rb:111:in `initialize'
[2] pry(#<ActionDispatch::MiddlewareStack>)> 
```

**Comment by skipkayhil** [comment]
Hey @dmc2015, thanks for opening an issue! I don't think Rails 5.2 will work on Ruby 3, and based on #38426 I'm not sure it will work on Ruby 2.7 either. I would recommend going to Rails 6 first, then Rails 6.1, and then trying to upgrade Ruby.
