### ISSUE TITLE
Updating a column using `serialize` to its database default value of `{}` instead tries to save it as NULL

### ISSUE THREAD

**Issue by dfritsch** [rails/rails#46351]
### Steps to reproduce

I originally was noticing issues trying to disable `partial_inserts` as part of upgrading to Rails 7. The oddness was that some models were failing to be created because Rails was now setting a null value for a column that had a database default and didn't allow nulls.

I then debugged that to what I think is consistent behavior in `serialize` that if you try to set the value of a column using `serialize` to its database default, Rails will instead try to set the value to NULL instead of the default value (which ultimately means you don't get the default).

Below is a test case I was able to write against ActiveRecord that I believe isolates the core issue here. At the very least I likely need to use a different model/fixture for adding the new column with null false and a default, but thought I would get some feedback on whether this is a real issue before digging deeper to try to isolate where the nil comes from.

```ruby
# new test added here:
# activerecord/test/cases/serialized_attribute_test.rb
  def test_serialized_attribute_with_default_can_update_to_default
    klass = Class.new(ActiveRecord::Base) do
      self.table_name = Topic.table_name
      serialize(:content, Hash)
    end

    t = klass.create!(content: { "other_key" => "new_value" })
    assert_equal({ "other_key" => "new_value" }, t.content)

    t.update!(content: {})
    assert_equal({}, t.content)
  end
```

```ruby
# Adjusted the Topic schema in activerecord/test/schema/schema.rb to:
t.text     :content, null: false, default: "{}"
```

Running
```
bundle exec ruby -Itest test/cases/serialized_attribute_test.rb -n test_serialized_attribute_with_default_can_update_to_default
```

Then gives the failure that you are violating the not null constraint:

```
Error:
SerializedAttributeTestWithYamlSafeLoad#test_serialized_attribute_with_default_can_update_to_default:
ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: topics.content
    /Users/dfritsch/.gem/ruby/3.1.2/gems/sqlite3-1.4.4/lib/sqlite3/statement.rb:108:in `step'
    /Users/dfritsch/.gem/ruby/3.1.2/gems/sqlite3-1.4.4/lib/sqlite3/statement.rb:108:in `block in each'
    /Users/dfritsch/.gem/ruby/3.1.2/gems/sqlite3-1.4.4/lib/sqlite3/statement.rb:107:in `loop'
    /Users/dfritsch/.gem/ruby/3.1.2/gems/sqlite3-1.4.4/lib/sqlite3/statement.rb:107:in `each'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:54:in `to_a'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:54:in `block (2 levels) in exec_query'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:970:in `block in with_raw_connection'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:942:in `with_raw_connection'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:45:in `block in exec_query'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1075:in `log'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:44:in `exec_query'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:72:in `exec_delete'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:180:in `update'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `update'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/persistence.rb:513:in `_update_record'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/persistence.rb:1081:in `_update_row'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/locking/optimistic.rb:88:in `_update_row'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/persistence.rb:1103:in `_update_record'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/attribute_methods/dirty.rb:216:in `_update_record'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/callbacks.rb:465:in `block in _update_record'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/callbacks.rb:99:in `run_callbacks'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/callbacks.rb:947:in `_run_update_callbacks'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/callbacks.rb:465:in `_update_record'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/timestamp.rb:121:in `_update_record'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/persistence.rb:1090:in `create_or_update'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/callbacks.rb:457:in `block in create_or_update'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/callbacks.rb:99:in `run_callbacks'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/callbacks.rb:947:in `_run_save_callbacks'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/callbacks.rb:457:in `create_or_update'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/timestamp.rb:126:in `create_or_update'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/persistence.rb:648:in `save!'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/validations.rb:55:in `save!'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/transactions.rb:304:in `block in save!'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/transactions.rb:356:in `block in with_transaction_returning_status'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/transactions.rb:352:in `with_transaction_returning_status'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/transactions.rb:304:in `save!'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/suppressor.rb:54:in `save!'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/persistence.rb:801:in `block in update!'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/transactions.rb:356:in `block in with_transaction_returning_status'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:455:in `block in within_new_transaction'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    /Users/dfritsch/workspace/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:453:in `within_new_transaction'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:322:in `transaction'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/transactions.rb:352:in `with_transaction_returning_status'
    /Users/dfritsch/workspace/rails/activerecord/lib/active_record/persistence.rb:799:in `update!'
    test/cases/serialized_attribute_test.rb:592:in `test_serialized_attribute_with_default_can_update_to_default'
```

### Expected behavior

I'd expect the column to be updated to the serialized format of the column default.

### Actual behavior

Nil/null is passed as the new column default, violating the not null constraint.

### System configuration
**Rails version**: 7.0.4 and main

**Ruby version**: 3.1.2

**Comment by fatkodima** [comment]
The problem is here: https://github.com/rails/rails/blob/9da0d1a24f73bf15e881ba5b70b78c1a7043063d/activerecord/lib/active_record/type/serialized.rb#L28-L30

The database default `"{}"` is converted to `{}`, but it is considered the default for `Hash` coder, so set to `nil`.

I came up with a solution (similar to https://github.com/rails/rails/pull/45962), but it fails the test at https://github.com/rails/rails/blob/9da0d1a24f73bf15e881ba5b70b78c1a7043063d/activerecord/test/cases/yaml_serialization_test.rb#L26-L29 because procs are not deserializable from yaml.

So, suggestions how to overcome this are welcomed.

```diff
diff --git a/activerecord/lib/active_record/attribute_methods/serialization.rb b/activerecord/lib/active_record/attribute_methods/serialization.rb
index 8361f3ac3f..34c22d2098 100644
--- a/activerecord/lib/active_record/attribute_methods/serialization.rb
+++ b/activerecord/lib/active_record/attribute_methods/serialization.rb
@@ -118,7 +118,7 @@ def serialize(attr_name, class_name_or_coder = Object, **options)
             end

             cast_type = cast_type.subtype if Type::Serialized === cast_type
-            Type::Serialized.new(cast_type, coder)
+            Type::Serialized.new(cast_type, coder, default: -> { columns_hash[attr_name.to_s]&.default })
           end
         end

diff --git a/activerecord/lib/active_record/type/serialized.rb b/activerecord/lib/active_record/type/serialized.rb
index f2d463e0e5..bd86d6f990 100644
--- a/activerecord/lib/active_record/type/serialized.rb
+++ b/activerecord/lib/active_record/type/serialized.rb
@@ -9,9 +9,10 @@ class Serialized < DelegateClass(ActiveModel::Type::Value) # :nodoc:

       attr_reader :subtype, :coder

-      def initialize(subtype, coder)
+      def initialize(subtype, coder, default: nil)
         @subtype = subtype
         @coder = coder
+        @default = default
         super(subtype)
       end

@@ -25,7 +26,7 @@ def deserialize(value)

       def serialize(value)
         return if value.nil?
-        unless default_value?(value)
+        unless default_value?(value) && @default&.call.nil?
           super coder.dump(value)
         end
diff --git a/activerecord/lib/active_record/attribute_methods/serialization.rb b/activerecord/lib/active_record/attribute_methods/serialization.rb
index 8361f3ac3f..34c22d2098 100644
--- a/activerecord/lib/active_record/attribute_methods/serialization.rb
+++ b/activerecord/lib/active_record/attribute_methods/serialization.rb
@@ -118,7 +118,7 @@ def serialize(attr_name, class_name_or_coder = Object, **options)
             end

             cast_type = cast_type.subtype if Type::Serialized === cast_type
-            Type::Serialized.new(cast_type, coder)
+            Type::Serialized.new(cast_type, coder, default: -> { columns_hash[attr_name.to_s]&.default })
           end
         end

diff --git a/activerecord/lib/active_record/type/serialized.rb b/activerecord/lib/active_record/type/serialized.rb
index f2d463e0e5..bd86d6f990 100644
--- a/activerecord/lib/active_record/type/serialized.rb
+++ b/activerecord/lib/active_record/type/serialized.rb
@@ -9,9 +9,10 @@ class Serialized < DelegateClass(ActiveModel::Type::Value) # :nodoc:

       attr_reader :subtype, :coder

-      def initialize(subtype, coder)
+      def initialize(subtype, coder, default: nil)
         @subtype = subtype
         @coder = coder
+        @default = default
         super(subtype)
       end

@@ -25,7 +26,7 @@ def deserialize(value)

       def serialize(value)
         return if value.nil?
-        unless default_value?(value)
+        unless default_value?(value) && @default&.call.nil?
           super coder.dump(value)
         end
       end
diff --git a/activerecord/test/cases/serialized_attribute_test.rb b/activerecord/test/cases/serialized_attribute_test.rb
index 3356412308..4e271a5961 100644
--- a/activerecord/test/cases/serialized_attribute_test.rb
+++ b/activerecord/test/cases/serialized_attribute_test.rb
@@ -23,6 +23,10 @@ class ImportantTopic < Topic
     serialize :important, Hash
   end

+  class Book < ActiveRecord::Base
+    serialize :content
+  end
+
   teardown do
     Topic.serialize("content")
   end
@@ -570,6 +574,12 @@ def test_nil_is_always_persisted_as_null
     assert_equal [topic], Topic.where(content: nil)
   end

+  def test_serialized_attribute_with_database_default
+    book = Book.create!(content: { "foo" => "bar" })
+    book.update_attribute :content, {}
+    assert_equal [book], Book.where(content: {})
+  end
+
   def test_serialized_attribute_with_default
     klass = Class.new(ActiveRecord::Base) do
       self.table_name = Topic.table_name
diff --git a/activerecord/test/schema/schema.rb b/activerecord/test/schema/schema.rb
index 3f402e9003..3e33fd372f 100644
--- a/activerecord/test/schema/schema.rb
+++ b/activerecord/test/schema/schema.rb
@@ -124,6 +124,7 @@
     t.references :author
     t.string :format
     t.column :name, :string
+    t.column :content, :string, null: false, default: "{}"
     t.column :status, :integer, **default_zero
     t.column :last_read, :integer, **default_zero
     t.column :nullable_status, :integer
```

**Comment by fatkodima** [comment]
Reproducible test script:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", path: "~/Desktop/oss/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text     :content, null: false, default: "{}"
  end
end

class Post < ActiveRecord::Base
  serialize(:content, Hash)
end

class BugTest < Minitest::Test
  def test_serialized_attribute_with_default_can_update_to_default
    t = Post.create!(content: { "other_key" => "new_value" })
    assert_equal({ "other_key" => "new_value" }, t.content)

    t.update!(content: {})
    assert_equal({}, t.content)
  end
end
```

**Comment by byroot** [comment]
Yeah, serialize always assume the column is nullable. It's always been the case, but never explicitly documented.

I suppose we theoretically could check in the column metadata whether it's nullable? (just a quick thought, I haven't dug in the code to refresh my memory)

**Comment by byroot** [comment]
Fixed in https://github.com/rails/rails/pull/47191

**Comment by byroot** [comment]
Reopening as we had to revert https://github.com/rails/rails/pull/47191 in https://github.com/rails/rails/pull/47482

**Comment by viktorianer** [comment]
It is the same for `json` and `jsonb` columns in PostgreSQL, if I understand the problem correctly :(. Here is a reproducible test script:

```
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', '~> 7.1.3'
  gem 'pg'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

system("createdb -U postgres -h localhost -p 5432 serialize_test") unless system("psql -U postgres -h localhost -p 5432 -lqt | cut -d \\| -f 1 | grep -w serialize_test")

ActiveRecord::Base.establish_connection(
  adapter: 'postgresql',
  host: 'localhost',
  port: 5432,
  schema_search_path: 'public',
  database: 'serialize_test',
  username: 'postgres',
  password: 'postgres'
)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.json :json_content, null: false, default: '{}'
    t.jsonb :jsonb_content, null: false, default: '{}'
  end
end

class Post < ActiveRecord::Base
  serialize(:json_content, Hash)
  serialize(:jsonb_content, Hash)
end

class BugTest < Minitest::Test
  def test_serialized_json_attribute_with_default_can_update_to_default
    t = Post.create!(json_content: { 'other_key' => 'new_value' })
    assert_equal({ 'other_key' => 'new_value' }, t.json_content)

    t.update!(json_content: {})
    assert_equal({}, t.json_content)
  end
  def test_serialized_jsonb_attribute_with_default_can_update_to_default
    t = Post.create!(jsonb_content: { 'other_key' => 'new_value' })
    assert_equal({ 'other_key' => 'new_value' }, t.jsonb_content)

    t.update!(jsonb_content: {})
    assert_equal({}, t.jsonb_content)
  end
end
```

Notice the slightly different error report:

```
# jsonb
Error:
BugTest#test_serialized_jsonb_attribute_with_default_can_update_to_default:
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "jsonb_content" of relation "posts" violates not-null constraint
DETAIL:  Failing row contains (1, "{}", null).

# json
Error:
BugTest#test_serialized_json_attribute_with_default_can_update_to_default:
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "json_content" of relation "posts" violates not-null constraint
DETAIL:  Failing row contains (2, null, "{}").
```

**Comment by swistak** [comment]
> Yeah, serialize always assume the column is nullable. It's always been the case, but never explicitly documented.
> 
> I suppose we theoretically could check in the column metadata whether it's nullable? (just a quick thought, I haven't dug in the code to refresh my memory)

@byroot This definitely didn't used to be the case since it cane up during the upgrade of one of our old applications. So it is a regression.
