### ISSUE TITLE
Rails 6.1 app fails on production boot due to missing gems on Ruby 3.1.2

### ISSUE THREAD

**Issue by schneems** [rails/rails#46437]
In Ruby 3.1 some gems were removed from stdlib such as `net-smtp`. If you generate a new Rails 6.1 app with Ruby 3.1 you cannot boot it with `RAILS_ENV=production`

### Steps to reproduce

```ruby
chruby 3.1.2
rails _6.1.7_ new myapp -d=postgresql
cd myapp
SECRET_KEY_BASE=foo RAILS_ENV=production rails s
```

Fails with:

```
$ SECRET_KEY_BASE=foo RAILS_ENV=production rails s

You don't have net-smtp installed in your application. Please add it to your Gemfile and run bundle install
=> Booting Puma
=> Rails 6.1.7 application starting in production
=> Run `bin/rails server --help` for more startup options
You don't have net-smtp installed in your application. Please add it to your Gemfile and run bundle install
Exiting
/Users/rschneeman/.gem/ruby/3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require': cannot load such file -- net/smtp (LoadError)
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/mail-2.7.1/lib/mail.rb:9:in `<module:Mail>'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/mail-2.7.1/lib/mail.rb:3:in `<main>'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/actionmailer-6.1.7/lib/action_mailer/mail_with_error_handling.rb:4:in `<main>'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/actionmailer-6.1.7/lib/action_mailer/base.rb:3:in `<main>'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/kernel.rb:38:in `require'
	from /private/tmp/myapp2/app/mailers/application_mailer.rb:1:in `<main>'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/kernel.rb:30:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader/helpers.rb:135:in `cget'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader/helpers.rb:25:in `each'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader/helpers.rb:25:in `ls'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader/eager_load.rb:16:in `each'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader.rb:296:in `block in eager_load_all'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader.rb:294:in `each'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/zeitwerk-2.6.5/lib/zeitwerk/loader.rb:294:in `eager_load_all'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/railties-6.1.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/rschneeman/.rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /Users/rschneeman/.rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/rschneeman/.rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/rschneeman/.rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/rschneeman/.rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /Users/rschneeman/.rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /Users/rschneeman/.rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/rschneeman/.rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /Users/rschneeman/.rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
	from /private/tmp/myapp2/config/environment.rb:5:in `<main>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/rack-2.2.4/lib/rack/server.rb:312:in `block in start'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/rack-2.2.4/lib/rack/server.rb:379:in `handle_profiling'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/rack-2.2.4/lib/rack/server.rb:311:in `start'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/railties-6.1.7/lib/rails/commands/server/server_command.rb:39:in `start'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/railties-6.1.7/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/railties-6.1.7/lib/rails/commands/server/server_command.rb:135:in `perform'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/railties-6.1.7/lib/rails/command/base.rb:69:in `perform'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/railties-6.1.7/lib/rails/command.rb:48:in `invoke'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/railties-6.1.7/lib/rails/commands.rb:18:in `<main>'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rschneeman/.gem/ruby/3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:5:in `<main>'
```

### Expected behavior

The server boots with the latest Rails version and latest Ruby version from a fresh `rails new` command.

### Actual behavior

It fails due to a missing gem.

### System configuration

- **Rails version**: 6.1.7
- **Ruby version**: 3.1.2

## Suggested fix

I suggest adding the following gems to the default Gemfile:

```
gem 'net-smtp'
gem 'net-imap'
gem 'net-pop'
```

**Comment by yahonda** [comment]
Hi,

It has been merged to main branch https://github.com/rails/rails/pull/44083 and backported to 7-0-stable branch via https://github.com/rails/rails/commit/cb44df700d04f144917b5083910c3dfde6179dbf .
This change has not been backported to 6-1-stable . So what I can suggest is to add these gems manually or use the newer versions of Rails.

Thanks.

**Comment by eileencodes** [comment]
We can't backport the gem requires into 6.1 because we need to support older Rubies. That's why we added the error message you're hitting.

```
You don't have net-smtp installed in your application. Please add it to your Gemfile and run bundle install
```

See Rafael's commit here https://github.com/skipkayhil/rails/commit/06ac69f4291201e89df497372a8cf52cd61b534e. I'm going to close because there's nothing else we can do here.

**Comment by schneems** [comment]
Makes sense. I think if someone wants to make a patch to show ALL the gems on the first error it would be good to have. Currently it only complains about one at a time.

Alternatively adding a conditional to check the version of ruby is >= 2.6 in the Gemfile.
