### ISSUE TITLE
Every form view fails with: private method `field_name' called for #<ActionView::Base> since upgrade to 7.0.4 (from 6.1)

### ISSUE THREAD

**Issue by svgr-slth** [rails/rails#46443]
### Steps to reproduce
I will hardly manage to create steps to reproduce as it may be project related. But i can show some examples of forms that used to work in 6.1 and that generates this error when updated to 7.0.4.

Any form generated with, `form_for`, or `form_with`, now provokes this error.

```haml
= form_with(model: @user, url: user_path(@user, form_step: @form_step), multipart: true) do |f|
  .row
    .input-group.mb-3.col-12
      .input-group-prepend
        %span.input-group-text
          = t('activerecord.attributes.user.name')
      = f.text_field :name, class: 'form-control'
    .input-group.mb-3.col-12
      .input-group-prepend
        %span.input-group-text
          = t('activerecord.attributes.user.email')
      = f.text_field :email, class: 'form-control'
     = f.submit t('views.users.save'), class: 'btn btn-primary text-white w-25 mt-4'
```

Here `@user` is either an existing user in the context of edition, or a `User.new` when creating a new one (through the same form) 
I simplified the form on purpose. But basically this happens on every form, for every field, or any Model.

### Expected behavior
The form generates properly

### Actual behavior
This error is being raised:
![image](https://user-images.githubusercontent.com/92316565/200622889-3210a80b-7e7c-4c26-bbe7-9200b2840e2c.png)
Full stack trace:
```
actionview (7.0.4) lib/action_view/helpers/tags/base.rb:108:in `tag_name'
actionview (7.0.4) lib/action_view/helpers/tags/base.rb:97:in `block in add_default_name_and_id'
actionview (7.0.4) lib/action_view/helpers/tags/base.rb:97:in `fetch'
actionview (7.0.4) lib/action_view/helpers/tags/base.rb:97:in `add_default_name_and_id'
actionview (7.0.4) lib/action_view/helpers/tags/text_field.rb:16:in `render'
actionview (7.0.4) lib/action_view/helpers/form_helper.rb:1167:in `text_field'
actionview (7.0.4) lib/action_view/helpers/form_helper.rb:2007:in `public_send'
actionview (7.0.4) lib/action_view/helpers/form_helper.rb:2007:in `text_field'
app/views/users/user_form_steps/_general_user_info.html.haml:6
actionview (7.0.4) lib/action_view/base.rb:244:in `public_send'
actionview (7.0.4) lib/action_view/base.rb:244:in `_run'
actionview (7.0.4) lib/action_view/template.rb:157:in `block in render'
activesupport (7.0.4) lib/active_support/notifications.rb:208:in `instrument'
actionview (7.0.4) lib/action_view/template.rb:361:in `instrument_render_template'
actionview (7.0.4) lib/action_view/template.rb:155:in `render'
actionview (7.0.4) lib/action_view/renderer/partial_renderer.rb:251:in `block in render_partial_template'
activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.4) lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
actionview (7.0.4) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionview (7.0.4) lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
actionview (7.0.4) lib/action_view/renderer/renderer.rb:53:in `render_partial'
actionview (7.0.4) lib/action_view/helpers/rendering_helper.rb:44:in `render'
haml (5.2.2) lib/haml/helpers/action_view_mods.rb:13:in `block in render'
haml (5.2.2) lib/haml/helpers.rb:93:in `non_haml'
haml (5.2.2) lib/haml/helpers/action_view_mods.rb:13:in `render'
app/views/users/edit.html.haml:26
haml (5.2.2) lib/haml/helpers.rb:379:in `block in capture_haml'
haml (5.2.2) lib/haml/helpers.rb:670:in `with_haml_buffer'
haml (5.2.2) lib/haml/helpers.rb:375:in `capture_haml'
haml (5.2.2) lib/haml/helpers/xss_mods.rb:66:in `capture_haml_with_haml_xss'
haml (5.2.2) lib/haml/helpers/action_view_mods.rb:46:in `capture_with_haml'
actionview (7.0.4) lib/action_view/helpers/form_helper.rb:768:in `form_with'
app/views/users/edit.html.haml:23
actionview (7.0.4) lib/action_view/base.rb:244:in `public_send'
actionview (7.0.4) lib/action_view/base.rb:244:in `_run'
actionview (7.0.4) lib/action_view/template.rb:157:in `block in render'
activesupport (7.0.4) lib/active_support/notifications.rb:208:in `instrument'
actionview (7.0.4) lib/action_view/template.rb:361:in `instrument_render_template'
actionview (7.0.4) lib/action_view/template.rb:155:in `render'
actionview (7.0.4) lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.4) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
actionview (7.0.4) lib/action_view/renderer/template_renderer.rb:75:in `block in render_with_layout'
activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.4) lib/action_view/renderer/template_renderer.rb:74:in `render_with_layout'
actionview (7.0.4) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
actionview (7.0.4) lib/action_view/renderer/template_renderer.rb:11:in `render'
actionview (7.0.4) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (7.0.4) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (7.0.4) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (7.0.4) lib/action_view/base.rb:270:in `in_rendering_context'
actionview (7.0.4) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (7.0.4) lib/action_controller/metal/streaming.rb:216:in `_render_template'
actionview (7.0.4) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (7.0.4) lib/action_controller/metal/rendering.rb:46:in `render_to_body'
actionpack (7.0.4) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (7.0.4) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (7.0.4) lib/action_controller/metal/rendering.rb:30:in `render'
actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:22:in `block (2 levels) in render'
/usr/local/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
activesupport (7.0.4) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:22:in `block in render'
actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:91:in `cleanup_view_runtime'
activerecord (7.0.4) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:21:in `render'
actionpack (7.0.4) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (7.0.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
actionpack (7.0.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
actionpack (7.0.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (7.0.4) lib/abstract_controller/base.rb:215:in `process_action'
actionpack (7.0.4) lib/action_controller/metal/rendering.rb:53:in `process_action'
actionpack (7.0.4) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
activesupport (7.0.4) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
actiontext (7.0.4) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (7.0.4) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `instance_exec'
activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
activesupport (7.0.4) lib/active_support/callbacks.rb:138:in `run_callbacks'
actionpack (7.0.4) lib/abstract_controller/callbacks.rb:233:in `process_action'
actionpack (7.0.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
actionpack (7.0.4) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
activerecord (7.0.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (7.0.4) lib/abstract_controller/base.rb:151:in `process'
actionview (7.0.4) lib/action_view/rendering.rb:39:in `process'
actionpack (7.0.4) lib/action_controller/metal.rb:188:in `dispatch'
actionpack (7.0.4) lib/action_controller/metal.rb:251:in `dispatch'
actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
bullet (7.0.3) lib/bullet/rack.rb:15:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.4) lib/rack/etag.rb:27:in `call'
rack (2.2.4) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.4) lib/rack/head.rb:12:in `call'
actionpack (7.0.4) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/cookies.rb:696:in `call'
activerecord (7.0.4) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.4) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
better_errors (2.9.1) lib/better_errors/middleware.rb:62:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:19:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.4) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.4) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.4) lib/rails/rack/logger.rb:25:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.4) lib/rack/method_override.rb:24:in `call'
rack (2.2.4) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
railties (7.0.4) lib/rails/engine.rb:530:in `call'
client_ruby (c2b4ecf3bb5b) lib/prometheus/middleware/exporter.rb:33:in `call'
yabeda-prometheus (0.8.0) lib/yabeda/prometheus/exporter.rb:57:in `call'
client_ruby (c2b4ecf3bb5b) lib/prometheus/middleware/exporter.rb:33:in `call'
client_ruby (c2b4ecf3bb5b) lib/prometheus/middleware/collector.rb:32:in `block in call'
client_ruby (c2b4ecf3bb5b) lib/prometheus/middleware/collector.rb:61:in `block in trace'
/usr/local/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
client_ruby (c2b4ecf3bb5b) lib/prometheus/middleware/collector.rb:61:in `trace'
client_ruby (c2b4ecf3bb5b) lib/prometheus/middleware/collector.rb:32:in `call'
rack (2.2.4) lib/rack/deflater.rb:44:in `call'
rack (2.2.4) lib/rack/handler/webrick.rb:95:in `service'
webrick (1.7.0) lib/webrick/httpserver.rb:140:in `service'
webrick (1.7.0) lib/webrick/httpserver.rb:96:in `run'
webrick (1.7.0) lib/webrick/server.rb:310:in `block in start_thread' 
```

Also important to that these cases also raise the exact same error:
```haml
    = f.text_field :name, name: field_name(:user, :name), class: 'form-control'
```

```haml
    = f.text_field :name, name: f.field_name(:name), class: 'form-control'
```

The only way i managed to workaround this issue is to manually set the name attribute like so
```haml
    = f.text_field :name, name: 'user[name]', class: 'form-control'
```

But i doubt i'm supposed to manually set every field name on every field of every form manually. 

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 2.7.0

**Comment by eileencodes** [comment]
I can't reproduce this, forms (with and without field name) work fine in 7.0 and main. If you can't reproduce in a new application it is likely not Rails related. I'd recommend upgrading HAML and seeing if that fixes it. I saw your stackoverflow post as well and I don't think the change you mentioned is related at all (see https://github.com/rails/rails/commit/e62d8f2e12c2d632bb885f9a32d3c33f0bf015cf), it simply changed `empty?` to `blank?` but didn't change the callers.

If upgrading HAML doesn't change anything I'd recommend setting up Rails locally and doing a git bisect to find the change that introduced this. Another option is to make sure only Rails gems get upgraded and see if the bug exists. Unfortunately without a reproduction we can't help further. Hope that helps and you find the problem soon.

**Comment by svgr-slth** [comment]
Yep, i do understand it's near impossible to help me here as it's most likely project dependent. I thought maybe that could ring a bell to anybody working on these pieces of code which could have an idea to help me identify who / what can cause such error.
 
Anyways thanks for the advice! I will definitely try that out and see if I can get this to work
