### ISSUE TITLE
Setting cookies domain doesn't work with Ruby 3.1.3 and integration tests

### ISSUE THREAD

**Issue by mrhead** [rails/rails#46578]
### Steps to reproduce

Run the following script with Ruby 3.1.3:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "7.0.4"
  # gem "rails", github: "rails/rails", branch: "main"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    cookies[:foo] = { value: :bar, domain: :all }
    render plain: "Home"
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior

The test should pass as it passes on Ruby 3.1.2.

### Actual behavior

The test fails with the following error:

```
E

Error:
BugTest#test_returns_success:
ArgumentError: invalid domain: ".example.org"
    /Users/head/.rbenv/versions/3.1.3/lib/ruby/3.1.0/cgi/cookie.rb:128:in `domain='
    /Users/head/.rbenv/versions/3.1.3/lib/ruby/3.1.0/cgi/cookie.rb:95:in `initialize'
    /Users/head/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/mock.rb:239:in `new'
    /Users/head/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/mock.rb:239:in `block in parse_cookies_from_header'
    /Users/head/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/mock.rb:236:in `each'
    /Users/head/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/mock.rb:236:in `parse_cookies_from_header'
    /Users/head/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/mock.rb:187:in `initialize'
    /Users/head/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-test-2.0.2/lib/rack/test.rb:360:in `new'
    /Users/head/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-test-2.0.2/lib/rack/test.rb:360:in `process_request'
    /Users/head/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-test-2.0.2/lib/rack/test.rb:165:in `custom_request'
    /Users/head/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-test-2.0.2/lib/rack/test.rb:114:in `get'
    /Users/head/.rbenv/versions/3.1.3/lib/ruby/3.1.0/forwardable.rb:238:in `get'
    bug_test.rb:44:in `test_returns_success'


rails test bug_test.rb:43
```

### System configuration

**Rails version**: 7.0.4, main

**Ruby version**: 3.1.3

### Additional information

This happens only when running integration tests. When I run the development server, then everything works as expected.

I'm unsure if the issue is caused by Rails, the `rack` gem, or Ruby's built-in `cgi` gem.

Anyway, the test is failing because of this change in Ruby: https://github.com/ruby/ruby/pull/6784/files

[`Rack::MockResponse#parse_cookies_from_header`](https://github.com/rack/rack/blob/2.2.4/lib/rack/mock.rb#L243) sets the cookie domain to `.example.com`, which is not accepted by the built-in `cgi` gem because it doesn't match [this regular expression](https://github.com/ruby/ruby/blob/master/lib/cgi/cookie.rb#L45).

Please let me know if you need any further information.

**Comment by flavorjones** [comment]
This issue is being discussed upstream: https://github.com/ruby/cgi/pull/29

**Comment by casperisfine** [comment]
There is a broken test in Rails test suite because of this change, and it's being handled upstream right now: https://github.com/ruby/cgi/pull/29

Not much we can do.

**Comment by mrhead** [comment]
Thanks for the link to the ruby/cgi issue, I'll look better next time.

Should I close this issue?

**Comment by yahonda** [comment]
I think this issue can be closed because there is almost nothing we can do in the Rails code.
