### ISSUE TITLE
insert_all with UNIQUE NULLS NOT DISTINCT index in Postgres

### ISSUE THREAD

**Issue by 23tux** [rails/rails#46654]
### Steps to reproduce

I'm on Postgres 15 and would like to use the `UNIQUE NULLS NOT DISTINCT` feature.

Given the following table with STI:

```
CREATE TABLE public.time_entries (
    id bigint NOT NULL,
    contract_id bigint,
    title character varying,
    "from" timestamp(6) without time zone,
    "to" timestamp(6) without time zone,
    key character varying NOT NULL,
    type character varying NOT NULL,
    date date NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT date_and_from_same_day CHECK ((("from")::date = date)),
    CONSTRAINT from_present_if_to_present CHECK (((("to" IS NULL) AND ("from" IS NULL)) OR (("to" IS NOT NULL) AND ("from" IS NOT NULL)) OR (("to" IS NULL) AND ("from" IS NOT NULL)))),
    CONSTRAINT to_after_from CHECK (("to" >= "from"))
);
```
When I try to batch insert records, I get the following error

```
(ruby@rspec#608) TimeEntry.insert_all([{ type: "TimeEntry::Toggl", from: Time.zone.now, to: Time.zone.now, key: "1" }])                                        │                WHERE a.attrelid = #{oid}
eval error: undefined method `scan' for nil:NilClass                                                                                                           │                AND a.attnum IN (#{indkey.join(",")})
                                                                                                                                                               │              SQL
              expressions.scan(/(?<column>\w+)"?\s?(?<opclass>\w+_ops)?\s?(?<desc>DESC)?\s?(?<nulls>NULLS (?:FIRST|LAST))?/).each do |column, opclass, desc, nu│
lls|                                                                                                                                                           │              # add info on sort order (only desc order is explicitly specified, asc is the default)
                         ^^^^^                                                                                                                                 │              # and non-default opclasses
  /usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql/schema_statements.rb:128:in `block in indexes'                    │              expressions.scan(/(?<column>\w+)"?\s?(?<opclass>\w+_ops)?\s?(?<desc>DESC)?\s?(?<nulls>NULLS (?:FIRST|LAST))?/).each do |column, opclass, desc, n
  /usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql/schema_statements.rb:103:in `map'                                 │ulls|
  /usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql/schema_statements.rb:103:in `indexes'                             │                opclasses[column] = opclass.to_sym if opclass
  /usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/connection_adapters/schema_cache.rb:137:in `block in indexes'                                    │                if nulls
  /usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/connection_adapters/schema_cache.rb:135:in `fetch'                                               │                  orders[column] = [desc, nulls].compact.join(" ")
  /usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/connection_adapters/schema_cache.rb:135:in `indexes'                                             │                else
  /usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/insert_all.rb:129:in `unique_indexes'                                                            │                  orders[column] = :desc if desc
  /usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/insert_all.rb:119:in `find_unique_index_for'                                                     │                end
  /usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/insert_all.rb:31:in `initialize'                                                                 │              end
  /usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/persistence.rb:146:in `new'                                                                      │            end
  /usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/persistence.rb:146:in `insert_all'                                                               │
  (rdbg)//usr/src/app/app/models/time_entry.rb:1:in `block (2 levels) in sync_all!'
```

Is this a bug, or am I doing something wrong?

### System configuration
**Rails version**:
7.0.4
**Ruby version**:
3.1.2

**Comment by ghiculescu** [comment]
Could you provide an executable test case? That would make it easier to confirm the issue. https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case
