### ISSUE TITLE
Use `File.absolute_path?` instead of `Pathname`

### ISSUE THREAD

**Issue by voxik** [rails/rails#46741]
Not exactly sure what is the reason, but recently, AR test suite started to fail on Fedora. The error looks like:

~~~
... snip ...

...................S...................................................................................................................................................................................................................................................................................................................................................[12965, #<Thread:0xf7e21da8 run>, #<MockExpectationError: mocked method :call called with unexpected arguments ["/usr/lib/gems/ruby/racc-1.6.1", "gem.build_complete"]>, ["/usr/share/gems/gems/minitest-5.16.3/lib/minitest/mock.rb:201:in `method_missing'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest/mock.rb:300:in `block in stub'", "/usr/share/rubygems/rubygems/basic_specification.rb:50:in `gem_build_complete_path'", "/usr/share/rubygems/rubygems/specification.rb:2174:in `missing_extensions?'", "/usr/share/rubygems/rubygems/basic_specification.rb:75:in `contains_requirable_file?'", "/usr/share/rubygems/rubygems/specification.rb:1058:in `block in find_in_unresolved'", "/usr/share/rubygems/rubygems/specification.rb:1058:in `each'", "/usr/share/rubygems/rubygems/specification.rb:1058:in `find_all'", "/usr/share/rubygems/rubygems/specification.rb:1058:in `find_in_unresolved'", "<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:101:in `require'", "/usr/share/gems/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'", "/builddir/build/BUILD/activerecord-7.0.4/usr/share/gems/gems/activerecord-7.0.4/lib/active_record/tasks/sqlite_database_tasks.rb:25:in `drop'", "/builddir/build/BUILD/activerecord-7.0.4/usr/share/gems/gems/activerecord-7.0.4/lib/active_record/tasks/database_tasks.rb:224:in `drop'", "/builddir/build/BUILD/activerecord-7.0.4/usr/share/gems/gems/activerecord-7.0.4/test/cases/tasks/sqlite_rake_test.rb:113:in `block (3 levels) in test_generates_absolute_path_with_given_root'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest/mock.rb:317:in `stub'", "/usr/share/gems/gems/activesupport-7.0.4/lib/active_support/testing/method_call_assertions.rb:24:in `assert_called_with'", "/builddir/build/BUILD/activerecord-7.0.4/usr/share/gems/gems/activerecord-7.0.4/test/cases/tasks/sqlite_rake_test.rb:110:in `block (2 levels) in test_generates_absolute_path_with_given_root'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest/mock.rb:317:in `stub'", "/builddir/build/BUILD/activerecord-7.0.4/usr/share/gems/gems/activerecord-7.0.4/test/cases/tasks/sqlite_rake_test.rb:109:in `block in test_generates_absolute_path_with_given_root'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest/mock.rb:317:in `stub'", "/builddir/build/BUILD/activerecord-7.0.4/usr/share/gems/gems/activerecord-7.0.4/test/cases/tasks/sqlite_rake_test.rb:108:in `test_generates_absolute_path_with_given_root'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest/test.rb:98:in `block (3 levels) in run'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest/test.rb:195:in `capture_exceptions'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest/test.rb:95:in `block (2 levels) in run'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:296:in `time_it'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest/test.rb:94:in `block in run'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:391:in `on_signal'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest/test.rb:243:in `with_info_handler'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest/test.rb:93:in `run'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:1059:in `run_one_method'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:365:in `run_one_method'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:352:in `block (2 levels) in run'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:351:in `each'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:351:in `block in run'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:391:in `on_signal'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:378:in `with_info_handler'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:350:in `run'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:182:in `block in __run'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:182:in `map'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:182:in `__run'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:159:in `run'", "/usr/share/gems/gems/minitest-5.16.3/lib/minitest.rb:83:in `block in autorun'"]]
E.............................................................................................................................................................................S..........................................................................................................................................................................
Finished in 164.554320s, 46.3920 runs/s, 151.5974 assertions/s.
  1) Error:
ActiveRecord::SqliteDBDropTest#test_generates_absolute_path_with_given_root:
RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true
    <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require'
    <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:167:in `require'
    /usr/share/gems/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
    /builddir/build/BUILD/activerecord-7.0.4/usr/share/gems/gems/activerecord-7.0.4/lib/active_record/tasks/sqlite_database_tasks.rb:25:in `drop'
    /builddir/build/BUILD/activerecord-7.0.4/usr/share/gems/gems/activerecord-7.0.4/lib/active_record/tasks/database_tasks.rb:224:in `drop'
    /builddir/build/BUILD/activerecord-7.0.4/usr/share/gems/gems/activerecord-7.0.4/test/cases/tasks/sqlite_rake_test.rb:113:in `block (3 levels) in test_generates_absolute_path_with_given_root'
7634 runs, 24946 assertions, 0 failures, 1 errors, 19 skips
~~~

The problem is, that for whatever reason, the `pathname` library is required here and the `require` fails (although the `pathname` is already loaded, this is surprising):

https://github.com/rails/rails/blob/532294b39f4436b4e427e5213738071b49f5e030/activerecord/lib/active_record/tasks/sqlite_database_tasks.rb#L22-L30

In any case, I don't think it is wise to call `require` at the same time when the `Pathname.new` is stubbed here:

https://github.com/rails/rails/blob/2da863e0c380ef6bb9ddbd223a301554feb6a40e/activerecord/test/cases/tasks/sqlite_rake_test.rb#L107-L117

Moreover, the usage and loading of `Pathname` seems to be complete overkill, when the code could look like:

~~~patch
diff --git a/activerecord/lib/active_record/tasks/sqlite_database_tasks.rb b/activerecord/lib/active_record/tasks/sqlite_database_tasks.rb
index 84d429b16d..3cdaf54ce7 100644
--- a/activerecord/lib/active_record/tasks/sqlite_database_tasks.rb
+++ b/activerecord/lib/active_record/tasks/sqlite_database_tasks.rb
@@ -22,9 +22,7 @@ def create
       end
 
       def drop
-        require "pathname"
-        path = Pathname.new(db_config.database)
-        file = path.absolute? ? path.to_s : File.join(root, path)
+        file = File.absolute_path? db_config.database ? db_config.database : File.join(root, db_config.database)
 
         FileUtils.rm(file)
       rescue Errno::ENOENT => error
~~~

So is there chance to make the code and the associated test case simpler?

**Comment by voxik** [comment]
Of course, the code probably used to be more robust in days, where `require` was plain Ruby require instead of Zeitwerk / Bundler / Rubygems custom version

**Comment by ghiculescu** [comment]
This seems reasonable. Do you want to make a PR?

**Comment by voxik** [comment]
BTW @fxn, any idea why it is not identified earlier, that the `pathname` has been loaded already?

**Comment by vishaldeepak** [comment]
Hey, can this be assigned to me, I'd like to try this, thank you
