### ISSUE TITLE
`synchronize': can't be called from trap context (ThreadError)

### ISSUE THREAD

**Issue by aaronjensen** [rails/rails#46785]
### Steps to reproduce
I reported this to https://github.com/guard/listen/issues/565 as well, in case the fix needs to be there.

Use:

```rb
  config.file_watcher = ActiveSupport::EventedFileUpdateChecker
```

And puma as your web server. The warning happens randomly, but when it does you will see:

```
my-app/gems/ruby/3.1.0/gems/actionview-7.0.4/lib/action_view/helpers/tag_helper.rb:189: warning: Exception in finalizer #<Proc:0x000000010852fb80 my-app/gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/evented_file_update_checker.rb:91>
my-app/gems/ruby/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:80:in `synchronize': can't be called from trap context (ThreadError)
        from my-app/gems/ruby/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:80:in `transition!'
        from my-app/gems/ruby/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:104:in `transition_with_callbacks!'
        from my-app/gems/ruby/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:72:in `transition'
        from my-app/gems/ruby/3.1.0/gems/listen-3.7.1/lib/listen/listener.rb:103:in `stop'
        from my-app/gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/evented_file_update_checker.rb:111:in `stop'
        from my-app/gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/evented_file_update_checker.rb:92:in `block in finalizer'
       ... additional unrelated application stacktrace ...
```

It appears to be `action_view/cache_expiry` that is being finalized (the below is the `caller` of `initialize` that I store to print again in the finalizer.

```
my-app/gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/evented_file_update_checker.rb:45:in `new'
my-app/gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/evented_file_update_checker.rb:45:in `initialize'
my-app/gems/ruby/3.1.0/gems/actionview-7.0.4/lib/action_view/cache_expiry.rb:48:in `new'
my-app/gems/ruby/3.1.0/gems/actionview-7.0.4/lib/action_view/cache_expiry.rb:48:in `block in execute_if_updated'
my-app/gems/ruby/3.1.0/gems/actionview-7.0.4/lib/action_view/cache_expiry.rb:42:in `synchronize'
my-app/gems/ruby/3.1.0/gems/actionview-7.0.4/lib/action_view/cache_expiry.rb:42:in `execute_if_updated'
my-app/gems/ruby/3.1.0/gems/actionview-7.0.4/lib/action_view/cache_expiry.rb:15:in `block in run'
my-app/gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
my-app/gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
my-app/gems/ruby/3.1.0/gems/actionview-7.0.4/lib/action_view/cache_expiry.rb:14:in `run'
my-app/gems/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:29:in `before'
```

### Expected behavior
No warning, it seems like stopping listen in a finalizer is error prone because those may run in traps.

### Actual behavior
The warning

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**Comment by ksweetie** [comment]
I'm seeing the same error using Rails/Puma/ViewComponent/Listen:

```
/Users/kevinsweet/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/ordered_options.rb:44: warning: Exception in finalizer #<Proc:0x0000000135bee3e0 /Users/kevinsweet/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/evented_file_update_checker.rb:91>
/Users/kevinsweet/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.8.0/lib/listen/fsm.rb:80:in `synchronize': can't be called from trap context (ThreadError)
	from /Users/kevinsweet/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.8.0/lib/listen/fsm.rb:80:in `transition!'
	from /Users/kevinsweet/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.8.0/lib/listen/fsm.rb:104:in `transition_with_callbacks!'
	from /Users/kevinsweet/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.8.0/lib/listen/fsm.rb:72:in `transition'
	from /Users/kevinsweet/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.8.0/lib/listen/listener.rb:103:in `stop'
	from /Users/kevinsweet/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/evented_file_update_checker.rb:111:in `stop'
	from /Users/kevinsweet/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/evented_file_update_checker.rb:92:in `block in finalizer'
	from /Users/kevinsweet/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/ordered_options.rb:44:in `to_s'
	from /Users/kevinsweet/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/ordered_options.rb:44:in `method_missing'
```

@aaronjensen Did you happen to find a fix/workaround?

**Comment by aaronjensen** [comment]
@ksweetie I tested w/ `main` and didn't see it. Could you try that and see if it fixes it for you?
