### ISSUE TITLE
ActionCable subscription problem (possibly Redis related)

### ISSUE THREAD

**Issue by gmhz** [rails/rails#46882]
### Steps to reproduce
Running the app in production:
Ubuntu 20.04
via systemd services, commands are:
- RAILS_ENV=production bundle exec puma -w 2 -t 5:5
- RAILS_ENV=production bundle exec anycable --log-level=fatal
- RAILS_ENV=production bundle exec sidekiq -c 7

```ruby
action cable is used for driver location updates (every 10-20 milliseconds), which are inserted into Redis.
```

### Expected behavior
no error in the console, and action cable subscription gets confirmations

### Actual behavior
This error happens once or twice
```
#<Thread:0x000055bf26978840 /usr/share/rvm/gems/ruby-2.7.2/gems/actioncable-7.0.4/lib/action_cable/subscription_adapter/redis.rb:150 run> terminated with exception (report_on_exception is true):
/usr/share/rvm/gems/ruby-2.7.2/gems/redis-5.0.5/lib/redis/subscribe.rb:52:in `subscription': ERR Protocol error: too big inline request (Redis::CommandError)
	from /usr/share/rvm/gems/ruby-2.7.2/gems/redis-5.0.5/lib/redis/subscribe.rb:17:in `subscribe'
	from /usr/share/rvm/gems/ruby-2.7.2/gems/redis-5.0.5/lib/redis.rb:188:in `_subscription'
	from /usr/share/rvm/gems/ruby-2.7.2/gems/redis-5.0.5/lib/redis/commands/pubsub.rb:17:in `subscribe'
	from /usr/share/rvm/gems/ruby-2.7.2/gems/actioncable-7.0.4/lib/action_cable/subscription_adapter/redis.rb:83:in `block in listen'
	from /usr/share/rvm/gems/ruby-2.7.2/gems/redis-client-0.11.2/lib/redis_client.rb:641:in `ensure_connected'
	from /usr/share/rvm/gems/ruby-2.7.2/gems/redis-5.0.5/lib/redis/client.rb:104:in `disable_reconnection'
	from /usr/share/rvm/gems/ruby-2.7.2/gems/redis-5.0.5/lib/redis.rb:79:in `without_reconnect'
	from /usr/share/rvm/gems/ruby-2.7.2/gems/actioncable-7.0.4/lib/action_cable/subscription_adapter/redis.rb:80:in `listen'
	from /usr/share/rvm/gems/ruby-2.7.2/gems/actioncable-7.0.4/lib/action_cable/subscription_adapter/redis.rb:154:in `block in ensure_listener_running'
```
and plenty of these errors in the console
```
#<Thread:0x00007fb470573358 /usr/share/rvm/gems/ruby-2.7.2/gems/actioncable-7.0.4/lib/action_cable/connection/stream_event_loop.rb:75 run> terminated with exception (report_on_exception is true):
/usr/share/rvm/gems/ruby-2.7.2/gems/actioncable-7.0.4/lib/action_cable/connection/stream_event_loop.rb:31:in `block in attach': can't add a new key into hash during iteration (RuntimeError)
	from /usr/share/rvm/gems/ruby-2.7.2/gems/actioncable-7.0.4/lib/action_cable/connection/stream_event_loop.rb:93:in `block in run'
	from /usr/share/rvm/gems/ruby-2.7.2/gems/actioncable-7.0.4/lib/action_cable/connection/stream_event_loop.rb:86:in `loop'
	from /usr/share/rvm/gems/ruby-2.7.2/gems/actioncable-7.0.4/lib/action_cable/connection/stream_event_loop.rb:86:in `run'
	from /usr/share/rvm/gems/ruby-2.7.2/gems/actioncable-7.0.4/lib/action_cable/connection/stream_event_loop.rb:75:in `block (2 levels) in spawn'
```

Browser behavior:  there's only one _confirm_subscription_, expected 3 of them, and without confirmation, there's no streaming data.
```
{"command":"subscribe","identifier":"{\"channel\":\"Channel1\"}"}	70
10:15:15.222
{"command":"subscribe","identifier":"{\"channel\":\"Channel2\"}"}	73
10:15:15.222
{"command":"subscribe","identifier":"{\"channel\":\"Channel3\"}"}	79
10:15:15.222
{"identifier":"{\"channel\":\"Channel3\"}","type":"confirm_subscription"}	84
10:15:15.320
{"command":"subscribe","identifier":"{\"channel\":\"Channel2\"}"}	76
10:15:15.724
{"command":"subscribe","identifier":"{\"channel\":\"Channel1\"}"}	70
10:15:15.724
{"command":"subscribe","identifier":"{\"channel\":\"Channel2\"}"}	73
10:15:15.724
{"command":"subscribe","identifier":"{\"channel\":\"Channel3\"}"}	79
10:15:15.724
{"type":"ping","message":1672816515}	36
10:15:15.873
{"command":"subscribe","identifier":"{\"channel\":\"Channel2\"}"}	76
10:15:16.231
{"command":"subscribe","identifier":"{\"channel\":\"Channel1\"}"}	70
10:15:16.232
{"command":"subscribe","identifier":"{\"channel\":\"Channel2\"}"}	73
10:15:16.232
{"command":"subscribe","identifier":"{\"channel\":\"Channel3\"}"}	79
10:15:16.232
{"command":"subscribe","identifier":"{\"channel\":\"Channel2\"}"}	76
10:15:16.744
{"command":"subscribe","identifier":"{\"channel\":\"Channel1\"}"}	70
10:15:16.745
{"command":"subscribe","identifier":"{\"channel\":\"Channel2\"}"}	73
10:15:16.745
{"command":"subscribe","identifier":"{\"channel\":\"Channel3\"}"}	79
10:15:16.745
{"command":"subscribe","identifier":"{\"channel\":\"Channel2\"}"}	76
10:15:17.255
{"command":"subscribe","identifier":"{\"channel\":\"Channel1\"}"}	70
10:15:17.255
{"command":"subscribe","identifier":"{\"channel\":\"Channel2\"}"}	73
10:15:17.255
{"command":"subscribe","identifier":"{\"channel\":\"Channel3\"}"}	79
10:15:17.255
{"command":"subscribe","identifier":"{\"channel\":\"Channel2\"}"}	76
10:15:17.766
{"command":"subscribe","identifier":"{\"channel\":\"Channel1\"}"}	70
10:15:17.766
{"command":"subscribe","identifier":"{\"channel\":\"Channel2\"}"}	73
10:15:17.767
{"command":"subscribe","identifier":"{\"channel\":\"Channel3\"}"}
```

redis-cli info gives:
```
# Server
redis_version:7.0.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:6fb48e98d145b7a2
redis_mode:standalone
os:Linux 5.4.0-135-generic x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:9.4.0
process_id:697
process_supervised:systemd
run_id:dd359779a33f78f5a70912534df6d739fda8af7c
tcp_port:6379
server_time_usec:1672818063080079
uptime_in_seconds:64211
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:11873679
executable:/usr/bin/redis-server
config_file:/etc/redis/redis.conf
io_threads_active:0

# Clients
connected_clients:30
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:57344
client_recent_max_output_buffer:0
blocked_clients:7
tracking_clients:0
clients_in_timeout_table:7

# Memory
used_memory:2759648
used_memory_human:2.63M
used_memory_rss:8806400
used_memory_rss_human:8.40M
used_memory_peak:2885528
used_memory_peak_human:2.75M
used_memory_peak_perc:95.64%
used_memory_overhead:1342902
used_memory_startup:862192
used_memory_dataset:1416746
used_memory_dataset_perc:74.67%
allocator_allocated:2756344
allocator_active:3309568
allocator_resident:5902336
total_system_memory:4122689536
total_system_memory_human:3.84G
used_memory_lua:35840
used_memory_vm_eval:35840
used_memory_lua_human:35.00K
used_memory_scripts_eval:312
number_of_cached_scripts:1
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:32768
used_memory_vm_total:68608
used_memory_vm_total_human:67.00K
used_memory_functions:184
used_memory_scripts:496
used_memory_scripts_human:496B
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.20
allocator_frag_bytes:553224
allocator_rss_ratio:1.78
allocator_rss_bytes:2592768
rss_overhead_ratio:1.49
rss_overhead_bytes:2904064
mem_fragmentation_ratio:3.24
mem_fragmentation_bytes:6086624
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_total_replication_buffers:0
mem_clients_slaves:0
mem_clients_normal:419454
mem_cluster_links:0
mem_aof_buffer:0
mem_allocator:jemalloc-5.2.1
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
async_loading:0
current_cow_peak:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:2144
rdb_bgsave_in_progress:0
rdb_last_save_time:1672817965
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
rdb_saves:213
rdb_last_cow_size:782336
rdb_last_load_keys_expired:0
rdb_last_load_keys_loaded:965
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_rewrites:0
aof_rewrites_consecutive_failures:0
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:240
total_commands_processed:4037159
instantaneous_ops_per_sec:74
total_net_input_bytes:822317248
total_net_output_bytes:688241177
total_net_repl_input_bytes:0
total_net_repl_output_bytes:0
instantaneous_input_kbps:14.89
instantaneous_output_kbps:12.46
instantaneous_input_repl_kbps:0.00
instantaneous_output_repl_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:883
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:4347
evicted_keys:0
evicted_clients:0
total_eviction_exceeded_time:0
current_eviction_exceeded_time:0
keyspace_hits:931055
keyspace_misses:52906
pubsub_channels:47
pubsub_patterns:0
pubsubshard_channels:0
latest_fork_usec:597
total_forks:213
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
total_active_defrag_time:0
current_active_defrag_time:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:10
dump_payload_sanitizations:0
total_reads_processed:3953374
total_writes_processed:4855195
io_threaded_reads_processed:0
io_threaded_writes_processed:0
reply_buffer_shrinks:2119
reply_buffer_expands:2035

# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:dee07bfacc1019120627692fbfd302be9fa916b6
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:484.049083
used_cpu_user:273.063061
used_cpu_sys_children:0.614614
used_cpu_user_children:0.668754
used_cpu_sys_main_thread:483.820213
used_cpu_user_main_thread:272.991556

# Modules

# Errorstats
errorstat_ERR:count=10

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=879,expires=384,avg_ttl=3322471832
```

### System configuration
**Rails version**:
Rails 7.0.4,
actioncable-7.0.4

**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Comment by byroot** [comment]
I had to check the redis-server source code to understand that error, because I never seen it before.

It seems to happen if the server has to do a "read line / gets" and the line happens to be over 64k long.

I don't see how Action Cable could cause this, it's more likely to be an issue in `redis-client`, but I really don't see what it could be, so without more information I doubt I'll be able to debug it.
