### ISSUE TITLE
AppGeneratorTest fails against Bundler 2.4.4 / RubyGems 3.4.4

### ISSUE THREAD

**Issue by yahonda** [rails/rails#47045]
Managed to reproduce CI failure at https://buildkite.com/rails/rails/builds/92702#0185c033-9a4d-4526-adad-168f50a4a977/1060-1068

This error has been triggered since using newer vesions of Bundler 2.4.4.

### Steps to reproduce

```ruby
git clone https://github.com/rails/rails
cd rails/railties
ruby -v
rm ../Gemfile.lock
bundle install
gem -v
bundler -v
bin/test test/generators/app_generator_test.rb -n test_app_update_preserves_skip_action_mailbox
# `1 runs, 2 assertions, 0 failures, 0 errors, 0 skips`

# Updating RubyGems and Bundler version by `gem update --system` it starts failing.

gem update --system
gem -v
bundler -v
rm ../Gemfile.lock
bundle install
bin/test test/generators/app_generator_test.rb -n test_app_update_preserves_skip_action_mailbox
# RuntimeError: Command failed with exit 1: yes | bin/rails app:update
```

### Expected behavior
It should pass.

### Actual behavior

```ruby
$ gem -v
3.4.4
$ bundler -v
Bundler version 2.4.4
$ bin/test test/generators/app_generator_test.rb -n test_app_update_preserves_skip_action_mailbox
... snip warnings ...
Run options: -n test_app_update_preserves_skip_action_mailbox --seed 64492

# Running:

E

Error:
AppGeneratorTest#test_app_update_preserves_skip_action_mailbox:
RuntimeError: Command failed with exit 1: yes | bin/rails app:update
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1140:in `system'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1140:in `block (2 levels) in run_app_update'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/stream.rb:11:in `silence_stream'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/stream.rb:19:in `block in quietly'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/stream.rb:11:in `silence_stream'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/stream.rb:18:in `quietly'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1140:in `block in run_app_update'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1135:in `chdir'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1135:in `run_app_update'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:259:in `block (2 levels) in test_app_update_preserves_skip_action_mailbox'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/assertions.rb:48:in `assert_nothing_raised'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/assertions.rb:265:in `_assert_nothing_raised_or_warn'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/assertions.rb:241:in `assert_no_changes'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:258:in `block in test_app_update_preserves_skip_action_mailbox'
    /home/yahonda/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:244:in `chdir'
    /home/yahonda/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:244:in `cd'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:256:in `test_app_update_preserves_skip_action_mailbox'


bin/test test/generators/app_generator_test.rb:253



Finished in 0.221952s, 4.5055 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**: main branh
**Ruby version**: ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]

**Comment by yahonda** [comment]
It works successfully with these versions.

```ruby
$ ruby -v
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]
$ gem -v
3.4.1
$ bundler -v
Bundler version 2.4.1
```

**Comment by yahonda** [comment]
`tzinfo-data` should be installed to Windows and JRuby, should not installed at CI environment where it runs CRuby on Linux environment.

https://github.com/rails/rails/blob/120e6bd2cda7f1ef30c309f97bde13e053e9784f/Gemfile#L169

Compared the `Gemfile.lock` between Bundler 2.4.1 and 2.4.4, Gemfile.lock file generated by Bundler 2.4.4 contains `tzinfo-data (1.2022.7)` entry.

```ruby
    tzinfo-data (1.2022.7)
      tzinfo (>= 1.0.0)
```

```diff
$ diff -u ../Gemfile.lock.241 ../Gemfile.lock.244
--- ../Gemfile.lock.241	2023-01-18 11:51:10.807817606 +0900
+++ ../Gemfile.lock.244	2023-01-18 11:55:19.353428441 +0900
@@ -101,6 +101,17 @@
 GEM
   remote: https://rubygems.org/
   specs:
+    activerecord-jdbc-adapter (1.3.25)
+      activerecord (>= 2.2, < 5.0)
+    activerecord-jdbcmysql-adapter (1.3.25)
+      activerecord-jdbc-adapter (~> 1.3.25)
+      jdbc-mysql (>= 5.1.22)
+    activerecord-jdbcpostgresql-adapter (1.3.25)
+      activerecord-jdbc-adapter (~> 1.3.25)
+      jdbc-postgres (~> 9.1, <= 9.4.1206)
+    activerecord-jdbcsqlite3-adapter (1.3.25)
+      activerecord-jdbc-adapter (~> 1.3.25)
+      jdbc-sqlite3 (>= 3.7.2, < 3.9)
     addressable (2.8.1)
       public_suffix (>= 2.0.2, < 6.0)
     amq-protocol (2.3.2)
@@ -264,6 +275,9 @@
     jbuilder (2.11.5)
       actionview (>= 5.0.0)
       activesupport (>= 5.0.0)
+    jdbc-mysql (8.0.27)
+    jdbc-postgres (9.4.1206)
+    jdbc-sqlite3 (3.8.11.2)
     jmespath (1.6.2)
     jsbundling-rails (1.1.1)
       railties (>= 6.0.0)
@@ -477,12 +491,15 @@
       railties (>= 6.0.0)
     tzinfo (2.0.5)
       concurrent-ruby (~> 1.0)
+    tzinfo-data (1.2022.7)
+      tzinfo (>= 1.0.0)
     uber (0.1.0)
     unicode-display_width (2.4.2)
     w3c_validators (1.3.7)
       json (>= 1.8)
       nokogiri (~> 1.6)
       rexml (~> 3.2)
+    wdm (0.1.1)
     web-console (4.2.0)
       actionview (>= 6.0.0)
       activemodel (>= 6.0.0)
@@ -586,4 +603,4 @@
   websocket-client-simple!

 BUNDLED WITH
-   2.4.1
+   2.4.4
$
```

**Comment by rafaelfranca** [comment]
Seems related to https://github.com/rubygems/rubygems/pull/6266. Is this by design @deivid-rodriguez?

**Comment by deivid-rodriguez** [comment]
I don't think so, it seems like a regression, and it might indeed be caused by that linked PR. That linked PR intended to fix unintentional removal of existing platform specific gems to the lockfile, but what this issue is reporting seems unexpected. Let me have a closer look, sorry for the trouble!

**Comment by yahonda** [comment]
It looks like https://github.com/rubygems/rubygems/pull/6285 is going to address this issue.

**Comment by deivid-rodriguez** [comment]
Yeah, I got a PR in place and will be releasing it ASAP.

**Comment by ioquatix** [comment]
Can you please add "(railties failures in CI)" to the title of this issue? I searched but nothing came up. This issue is exactly what I was looking for.

**Comment by ioquatix** [comment]
Yeah, makes total sense once you know, but I didn't know the conventions, and just searched for "railties failures".

Can we pin the bundler version until this is fixed?

**Comment by yahonda** [comment]
Opened https://github.com/rails/buildkite-config/pull/30

**Comment by yahonda** [comment]
Confirmed Bundler 2.4.5 addresses this issue.

```ruby
$ gem -v
3.4.5
$ bundler -v
Bundler version 2.4.5
$ bundle
$ bin/test test/generators/app_generator_test.rb -n test_app_update_preserves_skip_action_mailbox
... snip warnings ...
Run options: -n test_app_update_preserves_skip_action_mailbox --seed 48593

# Running:

.

Finished in 1.598815s, 0.6255 runs/s, 1.2509 assertions/s.
1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
$
```
