### ISSUE TITLE
Unable to run migrations on Ruby 3.2 with Rails 7.0.4.2 

### ISSUE THREAD

**Issue by ted-hanson** [rails/rails#47233]
### Steps to reproduce

Trying to run `rake db:schema:load` or `rake db:migrate` results in an error.  We get a stack trace that leads us to believe that  ruby-3.2 kwargs aren't being passed correctly in `ActiveRecord::Migration#method_missing` 

wrong number of arguments (given 2, expected 1)
/Users/ted/workspace/callerzen/db/migrate/20140307084445_create_users.rb:5:in `change'

Stack trace:
```
== 20140307084445 CreateUsers: migrating ======================================
-- create_table(:users, {:id=>:integer})
/Users/ted/.rvm/gems/ruby-3.2.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:299:in `create_table'
/Users/ted/.rvm/gems/ruby-3.2.0/gems/activerecord-7.0.4.2/lib/active_record/migration.rb:932:in `block in method_missing'
/Users/ted/.rvm/gems/ruby-3.2.0/gems/activerecord-7.0.4.2/lib/active_record/migration.rb:900:in `block in say_with_time'
/Users/ted/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/benchmark.rb:296:in `measure'
/Users/ted/.rvm/gems/ruby-3.2.0/gems/activerecord-7.0.4.2/lib/active_record/migration.rb:900:in `say_with_time'
/Users/ted/.rvm/gems/ruby-3.2.0/gems/activerecord-7.0.4.2/lib/active_record/migration.rb:921:in `method_missing'
/Users/ted/.rvm/gems/ruby-3.2.0/gems/zero_downtime_migrations-0.0.7/lib/zero_downtime_migrations/migration.rb:83:in `method_missing'
/Users/ted/.rvm/gems/ruby-3.2.0/gems/activerecord-7.0.4.2/lib/active_record/migration/compatibility.rb:61:in `create_table'
/Users/ted/.rvm/gems/ruby-3.2.0/gems/activerecord-7.0.4.2/lib/active_record/migration/compatibility.rb:110:in `create_table'
/Users/ted/.rvm/gems/ruby-3.2.0/gems/activerecord-7.0.4.2/lib/active_record/migration/compatibility.rb:180:in `create_table'
/Users/ted/.rvm/gems/ruby-3.2.0/gems/activerecord-7.0.4.2/lib/active_record/migration/compatibility.rb:240:in `create_table'
/Users/ted/.rvm/gems/ruby-3.2.0/gems/activerecord-7.0.4.2/lib/active_record/migration/compatibility.rb:278:in `create_table'
/Users/ted/workspace/callerzen/db/migrate/20140307084445_create_users.rb:5:in `change'
```

The migration in question:
```ruby
class CreateUsers < ActiveRecord::Migration[5.0]
  def change
    create_table :users do |t|
      t.string :name
      t.string :email

      t.timestamps
    end
  rescue => e
    puts e.backtrace
    raise
  end
end
```

### Expected behavior
Ideally we should still be able to run the old migrations, but at the very least we should be able to call `rake db:schema:load`

### Actual behavior
We cannot run the old migrations anymore as the ruby-3.2 kwargs aren't being passed correctly in `ActiveRecord::Migration#method_missing`

### System configuration
**Rails version**: 7.0.4.2

**Ruby version**: 3.2.0

**psych version**: 3.3.4

**Comment by ted-hanson** [comment]
After downgrading to Ruby 2.7.7 you can see the warning:

```
/Users/ted/.rvm/gems/ruby-2.7.7/gems/anyway_config-2.3.0/lib/anyway/type_casting.rb:111: warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
/Users/ted/.rvm/gems/ruby-2.7.7/gems/anyway_config-2.3.0/lib/anyway/rbs.rb:40: warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
/Users/ted/.rvm/gems/ruby-2.7.7/gems/activerecord-7.0.4.2/lib/active_record/migration.rb:932: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/ted/.rvm/gems/ruby-2.7.7/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:299: warning: The called method `create_table' is defined here
```

**Comment by eileencodes** [comment]
Can you reproduce in a new Rails application?

I suspect this is potentially coming from `zero_downtime_migrations` instead of Rails. I found this issue https://github.com/LendingHome/zero_downtime_migrations/pull/43. The gem doesn't appear maintained anymore (and hasn't been updated since 2018).

**Comment by ted-hanson** [comment]
you are correct closing

**Comment by fatkodima** [comment]
If the `zero_downtime_migrations` is not maintained, you can consider a newer alternative - https://github.com/fatkodima/online_migrations.
