### ISSUE TITLE
Not allowed to use the `/assets` route

### ISSUE THREAD

**Issue by StephenVNelson** [rails/rails#47297]
### Steps to reproduce
I think this may be an issue with all rails apps out of the box. (Or maybe it's intentional and we're just supposed to avoid any routes called `/assets`.) to verify I created a new rails app. 
```
rails new rails-bug
rails db:setup
rails db:migrate
```
Then I added an `Asset` resource. 
```
rails g scaffold Asset name:string
```
This is what my routes file looks like
```ruby
Rails.application.routes.draw do
  resources :assets
end
```

### Expected behavior

I tried to navigate to `http://localhost:3000/assets` to view the page but I received the error instead. If there was a routing error, I would expect the error to at least show the correct route. 

### Actual behavior

I get the following error. 
`No route matches [GET] "/"`

Here is the callstack
```
actionpack (7.0.4.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.4.2) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.4.2) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.4.2) lib/rails/rack/logger.rb:25:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:11:in `block in call'
activesupport (7.0.4.2) lib/active_support/logger_silence.rb:18:in `block in silence'
activesupport (7.0.4.2) lib/active_support/logger_thread_safe_level.rb:43:in `log_at'
activesupport (7.0.4.2) lib/active_support/logger_silence.rb:18:in `silence'
activesupport (7.0.4.2) lib/active_support/logger.rb:64:in `block (3 levels) in broadcast'
activesupport (7.0.4.2) lib/active_support/logger_silence.rb:18:in `block in silence'
activesupport (7.0.4.2) lib/active_support/logger_thread_safe_level.rb:43:in `log_at'
activesupport (7.0.4.2) lib/active_support/logger_silence.rb:18:in `silence'
activesupport (7.0.4.2) lib/active_support/logger.rb:62:in `block (2 levels) in broadcast'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:11:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.6.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.6.2) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.4.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
actionpack (7.0.4.2) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.6.2) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.4.2) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
railties (7.0.4.2) lib/rails/engine.rb:530:in `call'
puma (5.6.5) lib/puma/configuration.rb:252:in `call'
puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
puma (5.6.5) lib/puma/server.rb:443:in `process_client'
puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread' 
```

### System configuration
**Rails version**: 7.0.4.2

**Ruby version**: 3.1.0

**Comment by rafaelfranca** [comment]
`assets` is mounted by Rails to render the css, javascript and image files. You can make your route work, but you need to change [this](https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L98) configuration first.

**Comment by joshuay03** [comment]
Hey @rafaelfranca, do you think it's worth raising an error in this case?

I was helping out a Junior dev today who ran into this issue with a fresh Rails app. I knew someone else must've run into this too which led me here. It's quite a confusing situation especially when you're following the documentation and simply adding a resource you'd expect to work.

**Comment by esasse** [comment]
I was bitten by this in the past. +1 for raising a better error.
