### ISSUE TITLE
[ Rails 6.1.4/7.0.4 & Ruby 3.1.2] Migration is failing to check index_exists?

### ISSUE THREAD

**Issue by Ramesh7** [rails/rails#47291]
### Steps to reproduce
Rails migration failing at index_exists?  due to the old ruby with Rails 6.1 & 7.0 syntax.https://github.com/rails/rails/blob/v7.0.4.2/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L664-L666
Below is an example of migration :
```ruby
class TestMigrationWithIndex < ActiveRecord::Migration[6.0]

  def up
    change_table :test_table do |t|
      t.index [:name, :category_type], name: :index_account_categories_ref unless t.index_exists? :index_account_categories_ref
    end

end
```

### Expected behavior
Migration should run successfully.

### Actual behavior
```
rake aborted!
ArgumentError: wrong number of arguments (given 3, expected 2)
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/schema_statements.rb:99:in `index_exists?'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration/command_recorder.rb:284:in `public_send'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration/command_recorder.rb:284:in `method_missing'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/schema_definitions.rb:636:in `index_exists?'
/Users/ramesh.senchacoupa.com/CoupaCodeBase/DEV/coupa_development/db/migrate/20230203123731_test_migration_with_index.rb:6:in `block in up'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration/compatibility.rb:105:in `block in change_table'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration/compatibility.rb:44:in `block in change_table'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/schema_statements.rb:487:in `change_table'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:929:in `block in method_missing'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:897:in `block in say_with_time'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:897:in `say_with_time'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:918:in `method_missing'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration/compatibility.rb:44:in `change_table'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration/compatibility.rb:105:in `change_table'
/Users/ramesh.senchacoupa.com/CoupaCodeBase/DEV/coupa_development/db/migrate/20230203123731_test_migration_with_index.rb:5:in `up'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:870:in `public_send'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:870:in `exec_migration'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:850:in `block in migrate'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/Users/ramesh.senchacoupa.com/.rvm/gems/ruby-3.1.2@enterprise/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:849:in `migrate'
```

### System configuration
**Rails version**:
- 7.0.4.1
- 6.1.4.7

**Ruby version**:
3.1.2

**Comment by Ramesh7** [comment]
Looks like the change is in main branch but not yet propagated to 7.0 https://github.com/rails/rails/pull/43576/files
