### ISSUE TITLE
Can't create a new app with rails `7.0.4.2`

### ISSUE THREAD

**Issue by remy727** [rails/rails#47440]
### Steps to reproduce

```ruby
rails new my_demo --api -T -d postgresql --css tailwind
```

### Expected behavior

The app is created with rails `7.0.4.2`

### Actual behavior

<details>
<summary>View error</summary>

```bash
...
Fetching tailwindcss-rails 2.0.23 (x86_64-darwin)
Installing tailwindcss-rails 2.0.23 (x86_64-darwin)
Bundle complete! 7 Gemfile dependencies, 51 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  tailwindcss:install
rails aborted!
Don't know how to build task 'assets:precompile' (See the list of available tasks with `rails --tasks`)
/Users/admin/.rvm/gems/ruby-3.2.0/gems/tailwindcss-rails-2.0.23-x86_64-darwin/lib/tasks/build.rake:20:in `<main>'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/engine.rb:661:in `load'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/engine.rb:661:in `block in run_tasks_blocks'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/engine.rb:661:in `each'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/engine.rb:661:in `run_tasks_blocks'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/application.rb:505:in `block in run_tasks_blocks'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/engine/railties.rb:15:in `each'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/engine/railties.rb:15:in `each'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/application.rb:505:in `run_tasks_blocks'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/engine.rb:464:in `load_tasks'
/Users/admin/work/personal/my_demo/Rakefile:6:in `<main>'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/command.rb:51:in `invoke'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/commands.rb:18:in `<main>'
<internal:/Users/admin/.rvm/rubies/ruby-3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/admin/.rvm/rubies/ruby-3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Users/admin/.rvm/gems/ruby-3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```
</details>

### System configuration
**Rails version**: 7.0.4.2

**Ruby version**: 3.2.1

**Comment by remy727** [comment]
It's my mistake. I included both `--api` and `--css` flags
