### ISSUE TITLE
Active Job Resque adapter test failures on Ruby 3.3

### ISSUE THREAD

**Issue by zzak** [rails/rails#47469]
Active Job integration tests for Resque is current failing on Ruby trunk builds:
https://buildkite.com/rails/rails/builds/94058#018678a6-db53-44f8-af53-04853ed8814b

Steps to reproduce:

```
# Use Ruby 3.3
ruby -v
ruby 3.3.0dev (2023-02-20T01:50:49Z master b326a5f3dd) [arm64-darwin22]

AJ_ADAPTER=resque AJ_INTEGRATION_TESTS=1 bin/test test/integration/queuing_test.rb
```

Output:

```
#<Thread:0x00007f09ff100260 /rails/activejob/test/support/integration/adapters/resque.rb:27 run> terminated with exception (report_on_exception is true):
--
  | /usr/local/lib/ruby/3.3.0+0/logger.rb:385:in `level': undefined method `[]' for nil (NoMethodError)
  |  
  | @level_override[Fiber.current] \|\| @level
  | ^^^^^^^^^^^^^^^
  | from /usr/local/lib/ruby/3.3.0+0/logger.rb:654:in `add'
  | from /usr/local/lib/ruby/3.3.0+0/logger.rb:698:in `info'
  | from /usr/local/lib/ruby/gems/3.3.0+0/gems/resque-scheduler-4.8.0/lib/resque/scheduler.rb:396:in `log!'
  | from /usr/local/lib/ruby/gems/3.3.0+0/gems/resque-scheduler-4.8.0/lib/resque/scheduler.rb:408:in `procline'
  | from /usr/local/lib/ruby/gems/3.3.0+0/gems/resque-scheduler-4.8.0/lib/resque/scheduler.rb:40:in `run'
  | from /rails/activejob/test/support/integration/adapters/resque.rb:35:in `block in start_workers'
  | Run options: --seed 44201
  |  
  | # Running:
  |  
  | S..SS..F
  |  
  | Failure:
  | QueuingTest#test_should_run_job_bulk_enqueued_in_the_future_at_the_specified_time [/rails/activejob/test/integration/queuing_test.rb:85]:
  | Job AJ-ce17619a-38da-4e61-834c-f8018edf2b9a was not executed
  |  
  |  
  | bin/rails test /rails/activejob/test/integration/queuing_test.rb:80
  |  
  | S.SF
  |  
  | Failure:
  | QueuingTest#test_should_run_job_enqueued_in_the_future_at_the_specified_time [/rails/activejob/test/integration/queuing_test.rb:75]:
  | Job AJ-7cf1fa0b-d2ed-4f0c-98a5-1481a3726b9c was not executed
  |  
  |  
  | bin/rails test /rails/activejob/test/integration/queuing_test.rb:70
```

**Comment by zzak** [comment]
This could entirely be a bug with [resque-scheduler](https://github.com/resque/resque-scheduler), have not fully investigated the issue but wanted to report in case other folks have ideas.

**Comment by yahonda** [comment]
I have opened https://github.com/resque/resque/issues/1856 then https://github.com/steveklabnik/mono_logger/pull/12 has been opened to address this issue at `mono_logger`.

**Comment by zzak** [comment]
@yahonda Oh glad you've already looked into this, thank you! Should we keep this open to track the issue?

**Comment by yahonda** [comment]
Let's close it. As long as we are aware there is an issue that should be fine.
