### ISSUE TITLE
AppGeneratorTest get errors `Your Ruby version is 3.3.0.dev, but your Gemfile specified 3.3.0`

### ISSUE THREAD

**Issue by yahonda** [rails/rails#47542]
Since https://github.com/rails/rails/pull/47524 has been merged to revert #45979 AppGeneratorTest using Ruby 3.3.0dev get errors. https://buildkite.com/rails/rails/builds/94260#0186953b-c968-466c-8124-2e976b9dbbe4

Although, It is kind of expected because #47524 reverts #45979 "Support prerelease rubies in Gemfile template". Let me open a issue here.

### Steps to reproduce

```ruby
Use Ruby 3.3.0dev like `rbenv install 3.3.0-dev ; rbenv global 3.3.0-dev` or whatever
git clone https://github.com/rails/rails
cd rails
rm Gemfile.lock
bundle install
cd railties
bin/test test/generators/app_generator_test.rb -n test_application_name_is_detected_if_it_exists_and_app_folder_renamed # any test that calls `run_app_update` should gets error
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ bin/test test/generators/app_generator_test.rb -n test_application_name_is_detected_if_it_exists_and_app_folder_renamed
Run options: -n test_application_name_is_detected_if_it_exists_and_app_folder_renamed --seed 23396

# Running:

E

Error:
AppGeneratorTest#test_application_name_is_detected_if_it_exists_and_app_folder_renamed:
RuntimeError: Command failed with exit 1: yes | bin/rails app:update
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1142:in `system'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1142:in `block (2 levels) in run_app_update'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/stream.rb:11:in `silence_stream'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/stream.rb:19:in `block in quietly'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/stream.rb:11:in `silence_stream'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/stream.rb:18:in `quietly'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1142:in `block in run_app_update'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1137:in `chdir'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1137:in `run_app_update'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:160:in `test_application_name_is_detected_if_it_exists_and_app_folder_renamed'


bin/test test/generators/app_generator_test.rb:154



Finished in 0.128656s, 7.7726 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.3.0dev (2023-02-28T18:05:30Z master c43fbe4ebd) [x86_64-linux]

**Comment by yahonda** [comment]
Any test that calls `run_app_update` should gets error by removing the `quietly` block as follows.


```diff
$ git diff test/generators/app_generator_test.rb
diff --git a/railties/test/generators/app_generator_test.rb b/railties/test/generators/app_generator_test.rb
index 3118afaf18..171b7421b0 100644
--- a/railties/test/generators/app_generator_test.rb
+++ b/railties/test/generators/app_generator_test.rb
@@ -1139,7 +1139,7 @@ def run_app_update(app_root = destination_root)
         gemfile_contents.sub!(/^(gem "rails").*/, "\\1, path: #{File.expand_path("../../..", __dir__).inspect}")
         File.write("Gemfile", gemfile_contents)

-        quietly { system({ "BUNDLE_GEMFILE" => "Gemfile" }, "yes | bin/rails app:update", exception: true) }
+        system({ "BUNDLE_GEMFILE" => "Gemfile" }, "yes | bin/rails app:update", exception: true)
       end
     end

$
```


- The actual error message is `Your Ruby version is 3.3.0.dev, but your Gemfile specified 3.3.0`
```ruby
$ bin/test test/generators/app_generator_test.rb -n test_app_update_create_new_framework_defaults
Run options: -n test_app_update_create_new_framework_defaults --seed 59350

# Running:

Your Ruby version is 3.3.0.dev, but your Gemfile specified 3.3.0
E

Error:
AppGeneratorTest#test_app_update_create_new_framework_defaults:
RuntimeError: Command failed with exit 18: yes | bin/rails app:update
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1142:in `system'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1142:in `block in run_app_update'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1137:in `chdir'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:1137:in `run_app_update'
    /home/yahonda/src/github.com/rails/rails/railties/test/generators/app_generator_test.rb:187:in `test_app_update_create_new_framework_defaults'


bin/test test/generators/app_generator_test.rb:181



Finished in 0.132107s, 7.5696 runs/s, 7.5696 assertions/s.
1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
$
```
