### ISSUE TITLE
actioncable test suite errors: NoMethodError: undefined method `strings' for Puma::Events:Class

### ISSUE THREAD

**Issue by Apteryks** [rails/rails#47617]
### Steps to reproduce

Ran the test suite with `rake test`.

### Expected behavior
The test suite should pass.

### Actual behavior
I got the following errors:
```
Finished in 15.334834s, 13.3683 runs/s, 35.6704 assertions/s.

  1) Error:
ClientTest#test_single_client:
NoMethodError: undefined method `strings' for Puma::Events:Class
    /tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb:68:in `with_puma_server'
    /tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb:208:in `test_single_client'

  2) Error:
ClientTest#test_disappearing_client:
NoMethodError: undefined method `strings' for Puma::Events:Class
    /tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb:68:in `with_puma_server'
    /tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb:259:in `test_disappearing_client'

  3) Error:
ClientTest#test_unsubscribe_client:
NoMethodError: undefined method `strings' for Puma::Events:Class
    /tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb:68:in `with_puma_server'
    /tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb:278:in `test_unsubscribe_client'

  4) Error:
ClientTest#test_server_restart:
NoMethodError: undefined method `strings' for Puma::Events:Class
    /tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb:68:in `with_puma_server'
    /tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb:303:in `test_server_restart'

  5) Error:
ClientTest#test_interacting_clients:
NoMethodError: undefined method `strings' for Puma::Events:Class
    /tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb:68:in `with_puma_server'
    /tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb:220:in `test_interacting_clients'

  6) Error:
ClientTest#test_many_clients:
NoMethodError: undefined method `strings' for Puma::Events:Class
    /tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb:68:in `with_puma_server'
    /tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb:243:in `test_many_clients'

205 runs, 547 assertions, 0 failures, 6 errors, 12 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -I"/gnu/store/j4z07lyi1ykk8bc68h1p4bpj1il9dn3f-ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib" "/gnu/store/j4z07lyi1ykk8bc68h1p4bpj1il9dn3f-ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/channel/base_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/channel/broadcasting_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/channel/naming_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/channel/periodic_timers_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/channel/rejection_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/channel/stream_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/channel/test_case_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/client_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/connection/authorization_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/connection/base_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/connection/client_socket_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/connection/cross_site_forgery_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/connection/identifier_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/connection/multiple_identifiers_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/connection/stream_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/connection/string_identifier_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/connection/subscriptions_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/connection/test_case_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/javascript_package_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/server/base_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/server/broadcasting_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/subscription_adapter/async_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/subscription_adapter/base_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/subscription_adapter/inline_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/subscription_adapter/postgresql_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/subscription_adapter/redis_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/subscription_adapter/subscriber_map_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/subscription_adapter/test_adapter_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/test_helper_test.rb" "/tmp/guix-build-ruby-actioncable-7.0.4.2.drv-0/source/actioncable/test/worker_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "rake" arguments: ("test") exit-status: 1 term-signal: #f stop-signal: #f> 
phase `check' failed after 15.8 seconds
command "rake" "test" failed with status 1
```

### System configuration
**Rails version**: 7.0.4.2

**Ruby version**: 2.7.4

Dependencies used:
```
redis@7.0.9 ruby-actionpack@7.0.4.2 ruby-activerecord@7.0.4.2 ruby-activesupport@7.0.4.2
+ ruby-nio4r@2.5.2 ruby-pg@1.3.5 ruby-puma@6.1.1 ruby-redis@4.2.5 ruby-websocket-client-simple@0.6.0
+ ruby-websocket-driver@0.7.1
```

**Comment by skipkayhil** [comment]
Puma 6 compatibility in tests was fixed in #46106, and the change was backported to `7-0-stable` in 42b066b6935441a5eb53bf032c4f64e3f95ff7b5.

Since this has already been resolved in `7-0-stable`, I'm going to close this, but feel free to reply if you have any questions!
