### ISSUE TITLE
[railties] test/generators_test.rb incompatiblities with MiniTest 5.17

### ISSUE THREAD

**Issue by Apteryks** [rails/rails#47657]
### Steps to reproduce
Modify Gemfile to use minitest 5.17,  and run the railties test suite.

```
cd railties
rake test
```

### Actual behavior

A single railties test appears to be incompatible with MiniTest 5.17 (latest version), `test/generators_test.rb`:`

```
# Running:

../tmp/guix-build-ruby-railties-7.0.4.2.drv-0/source/railties/lib/rails/generators.rb:263: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/gnu/store/i5x8ph2ldgd9ldw43f8s4dn6y3yqk3wq-ruby-minitest-5.17.0/lib/ruby/vendor_ruby/gems/minitest-5.17.0/lib/minitest/mock.rb:301: warning: The called method is defined here
E

Error:
GeneratorsTest#test_invoke_with_config_values:
ArgumentError: mocked method :call expects 2 arguments, got [["Account"]]
    test/generators_test.rb:74:in `block in test_invoke_with_config_values'
    test/generators_test.rb:73:in `test_invoke_with_config_values'

rails test test/generators_test.rb:72

..E

Error:
GeneratorsTest#test_simple_invoke:
ArgumentError: mocked method :call expects 2 arguments, got [["Account"]]
    test/generators_test.rb:22:in `block in test_simple_invoke'
    test/generators_test.rb:21:in `test_simple_invoke'

rails test test/generators_test.rb:19

..............E

Error:
GeneratorsTest#test_should_give_higher_preference_to_rails_generators:
ArgumentError: mocked method :call expects 2 arguments, got [["Account"]]
    test/generators_test.rb:61:in `block (2 levels) in test_should_give_higher_preference_to_rails_generators'
    test/generators_test.rb:61:in `block in test_should_give_higher_preference_to_rails_generators'
    test/generators_test.rb:60:in `test_should_give_higher_preference_to_rails_generators'

rails test test/generators_test.rb:58

..E

Error:
GeneratorsTest#test_nested_fallbacks_for_generators:
ArgumentError: mocked method :call expects 2 arguments, got [["Account"]]
    test/generators_test.rb:201:in `block in test_nested_fallbacks_for_generators'
    test/generators_test.rb:200:in `test_nested_fallbacks_for_generators'

rails test test/generators_test.rb:197

.E

Error:
GeneratorsTest#test_fallbacks_for_generators_on_invoke:
ArgumentError: mocked method :call expects 2 arguments, got [["Account"]]
    test/generators_test.rb:191:in `block in test_fallbacks_for_generators_on_invoke'
    test/generators_test.rb:190:in `test_fallbacks_for_generators_on_invoke'

rails test test/generators_test.rb:188

.E

Error:
GeneratorsTest#test_invoke_with_default_values:
ArgumentError: mocked method :call expects 2 arguments, got [["Account"]]
    test/generators_test.rb:68:in `block in test_invoke_with_default_values'
    test/generators_test.rb:67:in `test_invoke_with_default_values'

rails test test/generators_test.rb:66

.../tmp/guix-build-ruby-railties-7.0.4.2.drv-0/source/railties/lib/rails/generators.rb:263: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/gnu/store/i5x8ph2ldgd9ldw43f8s4dn6y3yqk3wq-ruby-minitest-5.17.0/lib/ruby/vendor_ruby/gems/minitest-5.17.0/lib/minitest/mock.rb:150: warning: The called method `method_missing' is defined here
E

Error:
GeneratorsTest#test_invoke_with_nested_namespaces:
ArgumentError: mocked method :start expects 2 arguments, got [["Account"]]
    test/generators_test.rb:122:in `block in test_invoke_with_nested_namespaces'
    test/generators_test.rb:121:in `test_invoke_with_nested_namespaces'

rails test test/generators_test.rb:118



Finished in 0.499966s, 64.0043 runs/s, 134.0091 assertions/s.
32 runs, 67 assertions, 0 failures, 7 errors, 0 skips
^^^ +++

````

### System configuration
**Rails version**: 7.0.4.2

**Ruby version**: 7.4.2

**Comment by eileencodes** [comment]
Hi @Apteryks - we have minitest locked to not test against 5.17 or higher because it's too hard to support the changes in 5.16. Please test railties with 5.16 or lower.

**Comment by zzak** [comment]
FWIW this seems to only affect 7-0-stable branch, as I can see we've lifted the restriction on main. This commit has a bit more context too for anyone interested: https://github.com/rails/rails/commit/7d4b29ad20fb2a7d04dfcf3f805bfcb54fc82827
