### ISSUE TITLE
update_all on ordered collection raises error for table without id

### ISSUE THREAD

**Issue by IngoAlbers** [rails/rails#47750]
### Steps to reproduce
When a table doesn't have an id or primary key column calling `update_all` on an ordered collection will raise an error.
For example something directly from the `update_all`examples. 
```ruby
# Update all books that match conditions, but limit it to 5 ordered by date
Book.where('title LIKE ?', '%Rails%').order(:created_at).limit(5).update_all(author: 'David')
```
I am aware this can be resolved by having an id or primary key column, but I still wouldn't expect an error and wrongly generated SQL.

Simple testcase:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, id: false do |t|
    t.string "title"
    t.timestamps
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_ordered_update_all
    post = Post.create!
    Post.order(:created_at).update_all(title: "Title")

    assert_equal "Title", post.reload.title
  end
end

```

### Expected behavior
`update_all` updates the attribute of all records.

### Actual behavior
Exception is raised:
```
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: posts.
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/sqlite3-1.6.1-arm64-darwin/lib/sqlite3/database.rb:152:in `initialize'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/sqlite3-1.6.1-arm64-darwin/lib/sqlite3/database.rb:152:in `new'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/sqlite3-1.6.1-arm64-darwin/lib/sqlite3/database.rb:152:in `prepare'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:50:in `block (2 levels) in exec_query'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:47:in `block in exec_query'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:46:in `exec_query'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:74:in `exec_delete'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:175:in `update'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `update'
    /opt/homebrew/Cellar/asdf/0.11.1/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/relation.rb:485:in `update_all'
    test.rb:32:in `test_ordered_update_all'
```
Generated SQL:
```sql
Post Update All (0.1ms)  UPDATE "posts" SET "title" = ? WHERE "posts"."" IN (SELECT "posts"."" FROM "posts" ORDER BY "posts"."created_at" ASC)  [["title", "Title"]]
```

### System configuration
**Rails version**: >=6.1.7.3

**Ruby version**: 3.2.1

**Comment by nvasilevski** [comment]
I think the fix for this would be to completely ignore the `order()` clause for `update_all` operation since the order shouldn't make any difference. Am I missing something here?
So a primitive change perhaps would be to reset the order here:

https://github.com/rails/rails/blob/995768e791221084ae3383c5fb9667545619bf6e/activerecord/lib/active_record/relation.rb#L493

by doing smth like `stmt.order` which should set the order to nothing

**Comment by sampatbadhe** [comment]
> I think the fix for this would be to completely ignore the order() clause for update_all operation since the order shouldn't make any difference. Am I missing something here?
  
 If `limit` is applied with `order` and if we remove `order`, it will update the records in random order. 
  
    #   # Update all books that match conditions, but limit it to 5 ordered by date
    #   Book.where('title LIKE ?', '%Rails%').order(:created_at).limit(5).update_all(author: 'David')

Currently it generates `IN` query to filter the records and updates the values.
```sql
UPDATE "books" SET "author" = $1 WHERE "books"."" IN (SELECT "books"."" FROM "books" WHERE (title LIKE '%Rails%') ORDER BY "books"."created_at" ASC LIMIT $2)  [["author", "David"], ["LIMIT", 5]] 
```

How about replacing `IN` query with `FROM` query to build subquery?

```sql
UPDATE "books" SET "author" = $1 FROM (SELECT * FROM "books" WHERE (name LIKE '%Rails%') ORDER BY "books"."created_at" ASC LIMIT $2) AS subquery  [["author", "David"], ["LIMIT", 5]] 
```
