### ISSUE TITLE
Update Ruby to 3.2.2 throws ArgumentError for redis_cache_store 

### ISSUE THREAD

**Issue by pdany1116** [rails/rails#47860]
### Steps to reproduce

Hi, I wanted to update a project from ruby version 2.7.2 to 3.2.2. The rails version is 5.2.6.3. After updating the necessary gems, I wanted to run the test suite, but running `rails test` gives the following error:
```
Coverage report generated for Minitest to /app/coverage. 72 / 88 LOC (81.82%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
/bundle/vendor/ruby/3.2.0/gems/activesupport-5.2.6.3/lib/active_support/cache/redis_cache_store.rb:166:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /bundle/vendor/ruby/3.2.0/gems/activesupport-5.2.6.3/lib/active_support/cache.rb:60:in `new'
	from /bundle/vendor/ruby/3.2.0/gems/activesupport-5.2.6.3/lib/active_support/cache.rb:60:in `lookup_store'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/application/bootstrap.rb:67:in `block in <module:Bootstrap>'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/initializable.rb:32:in `run'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/application.rb:361:in `initialize!'
	from /app/config/environment.rb:5:in `<top (required)>'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /app/test/test_helper.rb:9:in `<main>'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /app/test/builders/all_organizations_mirror_builder_test.rb:3:in `<main>'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/test_unit/runner.rb:50:in `block in load_tests'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/test_unit/runner.rb:50:in `each'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/test_unit/runner.rb:50:in `load_tests'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/test_unit/runner.rb:39:in `run'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/commands/test/test_command.rb:33:in `perform'
	from /bundle/vendor/ruby/3.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /bundle/vendor/ruby/3.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /bundle/vendor/ruby/3.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/command/base.rb:69:in `perform'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/command.rb:46:in `invoke'
	from /bundle/vendor/ruby/3.2.0/gems/railties-5.2.6.3/lib/rails/commands.rb:18:in `<main>'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /bundle/vendor/ruby/3.2.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from bin/rails:4:in `<main>'
```

My Gemfile is:
```
# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

gem 'rails', '~> 5.2.6.3'

gem 'activejob-locking'
gem 'active_model_serializers', '~> 0.10.13'
gem 'acts_as_commentable', '~> 4.0.2'
gem 'acts_as_tree'
gem 'addressable', '~> 2.7'
gem 'appsignal', '~> 3.0'
gem 'awesome_print', require: 'ap'
gem 'aws-sdk-s3'
gem 'bootsnap', '~> 1.7.5', require: false
gem 'bourbon', '~> 4.2.1'
gem 'ckeditor', '~> 4.3.0'
gem 'coffee-rails'
gem 'cookiejar', git: 'https://github.com/MissionCapital/cookiejar.git'
gem 'custom_error_message', git: 'https://github.com/jeremydurham/custom-err-msg.git', branch: 'master'
gem 'data_migrate', '~> 8.4.2'
gem 'devise'
gem 'doorkeeper', '~> 5.6.0'
gem 'dynamic_form', '~> 1.1.4'
gem 'email_check', '~> 1.0.2'
gem 'eventmachine'
gem 'facets', '~> 3.1.0', require: false
gem 'faraday'
gem 'faraday-cookie_jar'
gem 'flying-sphinx', '~> 2.2.0'
gem 'fog-aws'
gem 'font-awesome-sass', '~> 4.7.0'
gem 'foreman'
gem 'graphlient', '~> 0.5'
gem 'gzipped_tar'
gem 'haml'
gem 'hpricot', '0.8.6'
gem 'htmlentities', '~> 4.3', '>= 4.3.4'
gem 'iso-639', '~> 0.3.5'
gem 'jquery-rails'
gem 'jquery-slick-rails', '~> 1.9'
gem 'jquery-ui-rails'
gem 'jwt', '~> 2.7'
gem 'karafka', '~> 1.4.9'
gem 'karafka-sidekiq-backend', '~> 1.4'
gem 'kt-paperclip', '~> 7.0.0'
gem 'matrix'
gem 'money-rails'
gem 'mosaico', '~> 1.1'
gem 'mysql2', '= 0.5.3' # Required for Thinking Sphinx!!!
gem 'net-smtp', require: false
gem 'nokogiri', '~> 1.14'
gem 'non-stupid-digest-assets'
gem 'pg', '< 2'
gem 'rack-cors', '~> 1.1.1'
gem 'rack-tracker', '~> 1.13.0'
gem 'rails_event_store', '~> 0.14.5'
gem 'rails-observers'
gem 'ranked-model'
gem 'recaptcha', '~> 5.12.3'
gem 'redis', '~> 5.0.6'
gem 'redlock'
gem 'restforce'
gem 'roo', '~> 2.9.0'
gem 'saml_idp', '~> 0.7.2'
gem 'sass-rails', '~> 5.0.7'
gem 'sidekiq', '< 7'
gem 'spreadsheet', '~> 1.2.9'
gem 'state_machine', git: 'https://github.com/seuros/state_machine.git', branch: 'master'
gem 'stripe', '~> 5.32.1'
gem 'thinking-sphinx', '~> 5.4.0'
gem 'uglifier'
gem 'virtus'
gem 'webrick', '~> 1.8'
gem 'will_paginate'
gem 'with_advisory_lock'

group :development do
  gem 'annotate'
  gem 'brakeman'
  gem 'bullet'
  gem 'bundler-audit'
  gem 'guard'
  gem 'guard-minitest'
  gem 'guard-reek', '~> 1.2.0'
  gem 'guard-rubocop', '~> 1.5.0'
  gem 'rails_live_reload', '~> 0.3.2'
  gem 'web-console'
end

group :test do
  gem 'capybara', '~> 3.35.3'
  gem 'database_cleaner', '~> 2.0.1'
  gem 'fake_stripe', '~> 0.3.0', require: false
  gem 'minitest', '~> 5.14.2'
  gem 'minitest-hooks', '~> 1.5.0'
  gem 'minitest-rails'
  gem 'minitest-rails-capybara'
  gem 'minitest-reporters', '~> 1.4.3'
  gem 'minitest-spec-rails'
  gem 'mocha'
  gem 'poltergeist'
  gem 'rails-controller-testing'
  gem 'ruby-saml'
  gem 'shoulda' # , '~> 3.5'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'simplecov', require: false
  gem 'spy'
  gem 'webmock'
end

group :development, :test do
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'pry', '~> 0.14.2'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'puma'
  gem 'reek', '~> 6.1.2'
  gem 'rubocop', '~> 1.39.0'
  gem 'rubocop-faker', '~> 1.1.0'
  gem 'rubocop-minitest', '~> 0.21.0'
  gem 'rubocop-performance', '~> 1.14.3'
  gem 'rubocop-rails', '~> 2.15.2'
  gem 'rubocop-rake', '~> 0.6.0'
  gem 'selenium-webdriver'
  gem 'spring'
end

group :development, :test, :preview do
  gem 'factory_bot_rails'
  gem 'faker'
end

group :production, :staging do
  gem 'rack-attack', '~> 6.6.1'
end

group :production do
  gem 'passenger',        '6.0.14'
  gem 'rack-timeout', '~> 0.6.0'
end

```

```ruby
# Your reproduction script goes here
```

### Expected behavior

I want to be able to run the test suite without errors after updating ruby version from 2.7.2 to 3.2.2 with rails version 5.2.6.3.

### Actual behavior

When running `rails test`, the following error is thrown `/bundle/vendor/ruby/3.2.0/gems/activesupport-5.2.6.3/lib/active_support/cache/redis_cache_store.rb:166:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)`

### System configuration
**Rails version**: 5.2.6.3

**Ruby version**: 3.2.2

**Comment by skipkayhil** [comment]
Hey @pdany1116, thanks for opening an issue.

Rails 5.2 has been [End of Life since Jun 1 2022](https://github.com/rails/rails/commit/61685c987e21c002aa19d814fd67c0c40c47c147), and so isn't receiving Ruby 3+ compatibility fixes. I recommend upgrading to Rails 6.1 (or even 7.0) before upgrading to Ruby 3+.

I'm going to close because Rails 5.2 is unsupported and we reserve the issue tracker for bugs. However, feel free to reply if you have any questions!
