### ISSUE TITLE
Enum with `required: true` generates broken error

### ISSUE THREAD

**Issue by pehrlich2** [rails/rails#48016]
### Steps to reproduce

```ruby
class MyModel < ApplicationRecord
  enum reason: %i[asdfasdf], required: true
end
```

### Expected behavior

An error which says `required` is not a valid argument

### Actual behavior

```
ArgumentError: You tried to define an enum named "asdfasdf" on the model "MyModel", but this will generate a instance method "asdfasdf?", which is already defined by another enum.
```

### System configuration
**Rails version**: 7.0.4.2

**Ruby version**: 3.2.2

**Comment by skipkayhil** [comment]
Hey @pehrlich2, thanks for opening an issue! I tried reproducing your issue but I'm seeing a different result:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :reason
  end
end

class Post < ActiveRecord::Base
  enum reason: %i[asdfasdf], required: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
  end
end
```

```
/home/hartley/.cache/asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-5beb0621fc42/activerecord/lib/active_record/enum.rb:310:in `assert_valid_enum_definition_values': Enum values true must be either a non-empty hash or an array. (ArgumentError)

          raise ArgumentError, "Enum values #{values} must be either a non-empty hash or an array."
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /home/hartley/.cache/asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-5beb0621fc42/activerecord/lib/active_record/enum.rb:197:in `_enum'
        from /home/hartley/.cache/asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-5beb0621fc42/activerecord/lib/active_record/enum.rb:187:in `block in enum'
        from /home/hartley/.cache/asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-5beb0621fc42/activerecord/lib/active_record/enum.rb:187:in `each'
        from /home/hartley/.cache/asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-5beb0621fc42/activerecord/lib/active_record/enum.rb:187:in `enum'
        from test.rb:29:in `<class:Post>'
        from test.rb:28:in `<main>'
```

Can you modify this script to show how you got the error?

**Comment by pehrlich2** [comment]
Hm, I looked a little more closely.   It looks like due to a relationship:

post - a model
postfollow - with the status 

related by `has_many :post_follows`

In my test I simply can call `post.post_follows` to get the error

In a different test I can call `PostFollow.insert` and get a different, also unexpected error: `Message: <"undefined method `all?' for true:TrueClass">`

Thanks!

**Comment by ghiculescu** [comment]
@pehrlich2 could you make a replication script so we can replicate the issue? Here's how: https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case

**Comment by pehrlich2** [comment]
Hi! I'm going to be out for a week - may be able to take a look when I'm back
