### ISSUE TITLE
[solved] Missing :controller key on routes definition, please check your routes. (ArgumentError)

### ISSUE THREAD

**Issue by zzz6519003** [rails/rails#48079]
I'm doing https://guides.rubyonrails.org/getting_started.html

when i run

`bin/rails generate controller Articles index --skip-routes`

I get

/opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:302:in `check_part': Missing :controller key on routes definition, please check your routes. (ArgumentError)

                raise ArgumentError, message
                      ^^^^^^^^^^^^^^^^^^^^^^
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:282:in `check_controller_and_action'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:223:in `normalize_options!'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:132:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:85:in `new'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:85:in `build'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:1961:in `add_route'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:1933:in `decomposed_match'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:1897:in `block in map_match'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:1891:in `each'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:1891:in `map_match'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:1639:in `match'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:735:in `map_method'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:688:in `get'
	from /Users/mac/Develop/ruby/blog/config/routes.rb:2:in `block in <main>'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:428:in `instance_exec'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:428:in `eval_block'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:410:in `draw'
	from /Users/mac/Develop/ruby/blog/config/routes.rb:1:in `<main>'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `load'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `block in load_paths'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `each'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `load_paths'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:24:in `reload!'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:38:in `block in updater'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/file_update_checker.rb:83:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:13:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/finisher.rb:158:in `block in <module:Finisher>'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `run'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:372:in `initialize!'
	from /Users/mac/Develop/ruby/blog/config/environment.rb:5:in `<main>'
	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:348:in `require_environment!'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/actions.rb:28:in `require_environment!'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/base.rb:87:in `perform'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command.rb:48:in `invoke'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'
	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'

**Comment by zzz6519003** [comment]
solved, i'm missing a slash `  get "/articles", to: "articles#index"`

but this makes me unhappy
