### ISSUE TITLE
Rails new succeeds (exit status zero) even when it does not bundle install Redis

### ISSUE THREAD

**Issue by schneems** [rails/rails#48278]
### Steps to reproduce

```term
$ gem install rails --no-document
Successfully installed rails-7.0.4.3
1 gem installed
```

Uninstall all redis gems:

```
$ gem uninstall redis --all
```

Create a Rails app:

```term
$ rails new myapp --database=postgresql
...
$ echo $?
0
$ cd myapp
```

Fails to boot:

```
$ rails c
Could not find redis-4.8.1 in locally installed gems
```

### Expected behavior

After `rails new` returns a zero status code I expect that everything is installed correctly and that I can use it.

### Actual behavior

Rails fails to install the redis gem, but continues anyway

```
$ rails new myapp --database=postgresql
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /Users/rschneeman/Documents/projects/rundoc/test/fixtures/rails_7/tmp/myapp/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/new_framework_defaults_7_0.rb
      create  config/initializers/permissions_policy.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_7_0.rb
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using rake 13.0.6
Using concurrent-ruby 1.2.2
Using minitest 5.18.0
Using builder 3.2.4
Using racc 1.6.2
Using rack 2.2.7
Using websocket-extensions 0.1.5
Using marcel 1.0.2
Using mini_mime 1.1.2
Using public_suffix 5.0.1
Using bindex 0.8.1
Using bundler 2.4.13
Using erubi 1.12.0
Using crass 1.0.6
Using nio4r 2.5.9
Using date 3.3.3
Using timeout 0.3.2
Using msgpack 1.7.1
Using matrix 0.4.2
Using regexp_parser 2.8.0
Using io-console 0.6.0
Using method_source 1.0.0
Using thor 1.2.2
Using zeitwerk 2.6.8
Using pg 1.5.3
Using rexml 3.2.5
Using rubyzip 2.3.2
Using websocket 1.2.9
Using tzinfo 2.0.6
Using i18n 1.13.0
Using nokogiri 1.15.1 (x86_64-darwin)
Using rack-test 2.1.0
Using websocket-driver 0.7.5
Using sprockets 4.2.0
Using addressable 2.8.4
Using bootsnap 1.16.0
Using activesupport 7.0.4.3
Using puma 5.6.5
Using reline 0.3.4
Using globalid 1.1.0
Using activemodel 7.0.4.3
Using irb 1.6.4
Using activerecord 7.0.4.3
Using debug 1.8.0
Using net-protocol 0.2.1
Using activejob 7.0.4.3
Using selenium-webdriver 4.9.1
Using rails-dom-testing 2.0.3
Using loofah 2.21.3
Using xpath 3.2.0
Using webdrivers 5.2.0
Using rails-html-sanitizer 1.5.0
Using capybara 3.39.1
Using actionview 7.0.4.3
Using net-smtp 0.3.3
Using net-imap 0.3.4
Using net-pop 0.1.2
Using jbuilder 2.11.5
Using actionpack 7.0.4.3
Using mail 2.8.1
Using actioncable 7.0.4.3
Using activestorage 7.0.4.3
Using railties 7.0.4.3
Using sprockets-rails 3.4.2
Using actionmailer 7.0.4.3
Using actionmailbox 7.0.4.3
Using actiontext 7.0.4.3
Using importmap-rails 1.1.6
Using stimulus-rails 1.2.1
Using turbo-rails 1.4.0
Using web-console 4.2.0
Using rails 7.0.4.3
Bundle complete! 15 Gemfile dependencies, 72 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  importmap:install
Add Importmap include tags in application layout
      insert  app/views/layouts/application.html.erb
Create application.js module as entrypoint
      create  app/javascript/application.js
Use vendor/javascript for downloaded pins
      create  vendor/javascript
      create  vendor/javascript/.keep
Ensure JavaScript files are in the Sprocket manifest
      append  app/assets/config/manifest.js
Configure importmap paths in config/importmap.rb
      create  config/importmap.rb
Copying binstub
      create  bin/importmap
       rails  turbo:install stimulus:install
Import Turbo
      append  app/javascript/application.js
Pin Turbo
      append  config/importmap.rb
Enable redis in bundle
        gsub  Gemfile
         run  bundle install
/Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:290:in `raise_not_found!': Could not find gem 'redis (~> 4.0)' in locally installed gems. (Bundler::GemNotFound)

The source contains the following gems matching 'redis':
  * redis-5.0.5
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:343:in `block in prepare_dependencies'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:328:in `each'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:328:in `map'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:328:in `prepare_dependencies'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:53:in `setup_solver'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:28:in `start'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/definition.rb:554:in `start_resolution'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/definition.rb:289:in `resolve'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/definition.rb:507:in `materialize'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/definition.rb:197:in `specs'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/definition.rb:254:in `specs_for'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/runtime.rb:18:in `setup'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler.rb:162:in `setup'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/setup.rb:23:in `block in <top (required)>'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/ui/shell.rb:159:in `with_level'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/ui/shell.rb:111:in `silence'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/setup.rb:23:in `<top (required)>'
	from <internal:/Users/rschneeman/.rubies/ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/rschneeman/.rubies/ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
Switch development cable to use redis
        gsub  config/cable.yml
/Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:290:in `raise_not_found!': Could not find gem 'redis (~> 4.0)' in locally installed gems. (Bundler::GemNotFound)

The source contains the following gems matching 'redis':
  * redis-5.0.5
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:343:in `block in prepare_dependencies'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:328:in `each'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:328:in `map'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:328:in `prepare_dependencies'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:53:in `setup_solver'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/resolver.rb:28:in `start'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/definition.rb:554:in `start_resolution'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/definition.rb:289:in `resolve'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/definition.rb:507:in `materialize'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/definition.rb:197:in `specs'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/definition.rb:254:in `specs_for'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/runtime.rb:18:in `setup'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler.rb:162:in `setup'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/setup.rb:23:in `block in <top (required)>'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/ui/shell.rb:159:in `with_level'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/ui/shell.rb:111:in `silence'
	from /Users/rschneeman/.gem/ruby/3.1.4/gems/bundler-2.4.13/lib/bundler/setup.rb:23:in `<top (required)>'
	from <internal:/Users/rschneeman/.rubies/ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/rschneeman/.rubies/ruby-3.1.4/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
$ echo $?
0
```

Slightly different (not sure why):

```
$ rails new myapp --database=postgresql
      create
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /private/tmp/myapp/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/new_framework_defaults_7_0.rb
      create  config/initializers/permissions_policy.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_7_0.rb
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using rake 13.0.6
Using minitest 5.18.0
Using builder 3.2.4
Using racc 1.6.2
Using crass 1.0.6
Using rack 2.2.7
Using nio4r 2.5.9
Using marcel 1.0.2
Using zeitwerk 2.6.8
Using mini_mime 1.1.2
Using bundler 2.4.13
Using rexml 3.2.5
Using concurrent-ruby 1.2.2
Using websocket 1.2.9
Using websocket-extensions 0.1.5
Using date 3.3.3
Using public_suffix 5.0.1
Using msgpack 1.7.1
Using regexp_parser 2.8.0
Using sprockets 4.2.0
Using method_source 1.0.0
Using thor 1.2.2
Using timeout 0.3.2
Using bindex 0.8.1
Using pg 1.5.3
Using matrix 0.4.2
Using rubyzip 2.3.2
Using erubi 1.12.0
Using selenium-webdriver 4.9.1
Using rack-test 2.1.0
Using puma 5.6.5
Using i18n 1.13.0
Using tzinfo 2.0.6
Using io-console 0.6.0
Using websocket-driver 0.7.5
Using addressable 2.8.4
Using bootsnap 1.16.0
Using net-protocol 0.2.1
Using nokogiri 1.15.1 (x86_64-darwin)
Using activesupport 7.0.4.3
Using reline 0.3.4
Using net-smtp 0.3.3
Using net-imap 0.3.4
Using irb 1.6.4
Using loofah 2.21.3
Using xpath 3.2.0
Using webdrivers 5.2.0
Using activemodel 7.0.4.3
Using rails-dom-testing 2.0.3
Using globalid 1.1.0
Using activerecord 7.0.4.3
Using debug 1.8.0
Using activejob 7.0.4.3
Using capybara 3.39.1
Using net-pop 0.1.2
Using rails-html-sanitizer 1.5.0
Using mail 2.8.1
Using actionview 7.0.4.3
Using actionpack 7.0.4.3
Using jbuilder 2.11.5
Using actioncable 7.0.4.3
Using activestorage 7.0.4.3
Using actionmailer 7.0.4.3
Using railties 7.0.4.3
Using actiontext 7.0.4.3
Using web-console 4.2.0
Using sprockets-rails 3.4.2
Using actionmailbox 7.0.4.3
Using importmap-rails 1.1.6
Using stimulus-rails 1.2.1
Using rails 7.0.4.3
Using turbo-rails 1.4.0
Bundle complete! 15 Gemfile dependencies, 72 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  importmap:install
Add Importmap include tags in application layout
      insert  app/views/layouts/application.html.erb
Create application.js module as entrypoint
      create  app/javascript/application.js
Use vendor/javascript for downloaded pins
      create  vendor/javascript
      create  vendor/javascript/.keep
Ensure JavaScript files are in the Sprocket manifest
      append  app/assets/config/manifest.js
Configure importmap paths in config/importmap.rb
      create  config/importmap.rb
Copying binstub
      create  bin/importmap
       rails  turbo:install stimulus:install
Import Turbo
      append  app/javascript/application.js
Pin Turbo
      append  config/importmap.rb
Enable redis in bundle
        gsub  Gemfile
         run  bundle install
Could not find gem 'redis (~> 4.0)' in locally installed gems.
Run `bundle install` to install missing gems.
Switch development cable to use redis
        gsub  config/cable.yml
Could not find gem 'redis (~> 4.0)' in locally installed gems.
Run `bundle install` to install missing gems.
$ echo $?
0
```

### System configuration
**Rails version**: 

```
$ rails -v
Rails 7.0.4.3
```

**Ruby version**:

```
$ ruby -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-darwin22]
```

**Comment by skipkayhil** [comment]
Hey @schneems!

Does your `bundle config` potentially have `frozen`/`deployment` etc. set that could be preventing `bundle install` from fetching the gem? When I follow the steps you list my `bundler` downloads `redis`

---

Tracking down where this `bundle install` is happening: it appears to be in `turbo-rails`: https://github.com/hotwired/turbo-rails/blob/ea00f3732e21af9c2156cf74dabe95524b17c361/lib/install/turbo_needs_redis.rb#LL14C8-L14C8

which calls ends up back in Rails: https://github.com/rails/rails/blob/b4369aa629e49d120f2bc0cba88a6411777f3171/railties/lib/rails/generators/app_base.rb#L618

Maybe we should be adding `exception: true` to this call? I'll gather some more context 🤔

**Comment by schneems** [comment]
The first `bundle install` works fine. Also, re-running `bundle install` resolves the problem. 

The issue, though, is twofold:

- Why doesn't redis get installed with the first `bundle install` 🤷  (this might be hard to solve or even reproduce)
- Even if we can't figure that out, `rails new` shouldn't exit 0 if its associated subcommand failed.

I do not have deployment mode enabled:

```
$ bundle config
Settings are listed in order of priority. The top value will be used.
gem.changelog
Set for the current user (/Users/rschneeman/.bundle/config): true

gem.ci
Set for the current user (/Users/rschneeman/.bundle/config): "circle"

gem.coc
Set for the current user (/Users/rschneeman/.bundle/config): true

gem.linter
Set for the current user (/Users/rschneeman/.bundle/config): "standard"

gem.mit
Set for the current user (/Users/rschneeman/.bundle/config): true

gem.test
Set for the current user (/Users/rschneeman/.bundle/config): "rspec"

jobs
Set for the current user (/Users/rschneeman/.bundle/config): 16
```

**Comment by schneems** [comment]
Worth mentioning I'm using `Bundler version 2.4.13`. The redis not getting installed may be a bundler bug (though, honestly 🤷 )

**Comment by Edouard-chin** [comment]
Had the same problem with redis not getting installed each time I created a new Rails app. It's a bundler bug that now got fixed https://github.com/rubygems/rubygems/issues/7365
