### ISSUE TITLE
Activesupport Dependency Inclusion Results in NameError

### ISSUE THREAD

**Issue by dm8302** [rails/rails#48401]
### Steps to reproduce
1. Create simple Sinatra application, leveraging Puma, and neo4j (Gemfile, app.rb, config.ru).
3. Including 'neo4j' gem as dependency (brings in activesupport )
4. bundle install
5. Run application (bundle exec puma)

```ruby
# app.rb
require 'sinatra'
require 'neo4j'

class Test < Sinatra::Base
  get '/' do
    'It works'
  end
end

# config.ru
require './app'
run Test

# Gemfile
gem 'puma'
gem 'sinatra'
gem 'neo4j'
```

### Expected behavior
Webserver runs.

### Actual behavior
Receive NameError originating within 'neo4j-core-9.0.0/lib/neo4j/transaction.rb'.  However, the file is referencing 'activesupport-7.0.5/lib/active_support/per_thread_registry.rb', and triggering deprecation warning.  It _appears_ as though this file may be missing an include (i.e., 

```ruby
#require "active_support/deprecation"
```

Actual run of code:
```ruby
% bundle exec puma                                                                                
Puma starting in single mode...
* Puma version: 6.3.0 (ruby 3.1.0-p0) ("Mugi No Toki Itaru")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 73563
! Unable to load application: NameError: uninitialized constant ActiveSupport::Deprecation

      ActiveSupport::Deprecation.warn(<<~MSG)
                   ^^^^^^^^^^^^^
bundler: failed to load command: puma (/Users/dan/.gem/ruby/3.1.0/bin/puma)
/Users/dan/.gem/ruby/3.1.0/gems/activesupport-7.0.5/lib/active_support/per_thread_registry.rb:44:in `extended': uninitialized constant ActiveSupport::Deprecation (NameError)

      ActiveSupport::Deprecation.warn(<<~MSG)
                   ^^^^^^^^^^^^^
	from /Users/dan/.gem/ruby/3.1.0/gems/neo4j-core-9.0.0/lib/neo4j/transaction.rb:10:in `extend'
	from /Users/dan/.gem/ruby/3.1.0/gems/neo4j-core-9.0.0/lib/neo4j/transaction.rb:10:in `<class:TransactionsRegistry>'
	from /Users/dan/.gem/ruby/3.1.0/gems/neo4j-core-9.0.0/lib/neo4j/transaction.rb:9:in `<module:Transaction>'
	from /Users/dan/.gem/ruby/3.1.0/gems/neo4j-core-9.0.0/lib/neo4j/transaction.rb:5:in `<module:Neo4j>'
	from /Users/dan/.gem/ruby/3.1.0/gems/neo4j-core-9.0.0/lib/neo4j/transaction.rb:4:in `<top (required)>'
	from /Users/dan/.gem/ruby/3.1.0/gems/neo4j-core-9.0.0/lib/neo4j/core.rb:3:in `require'
	from /Users/dan/.gem/ruby/3.1.0/gems/neo4j-core-9.0.0/lib/neo4j/core.rb:3:in `<top (required)>'
	from /Users/dan/.gem/ruby/3.1.0/gems/neo4j-core-9.0.0/lib/neo4j-core.rb:3:in `require'
	from /Users/dan/.gem/ruby/3.1.0/gems/neo4j-core-9.0.0/lib/neo4j-core.rb:3:in `<top (required)>'
	from /Users/dan/.gem/ruby/3.1.0/gems/neo4j-9.6.2/lib/neo4j.rb:4:in `require'
	from /Users/dan/.gem/ruby/3.1.0/gems/neo4j-9.6.2/lib/neo4j.rb:4:in `<top (required)>'
	from /Users/dan/Documents/test_activesupport_issue/app.rb:2:in `require'
	from /Users/dan/Documents/test_activesupport_issue/app.rb:2:in `<top (required)>'
	from config.ru:1:in `require'
	from config.ru:1:in `block in <main>'
	from /Users/dan/.gem/ruby/3.1.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `eval'
	from /Users/dan/.gem/ruby/3.1.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `new_from_string'
	from /Users/dan/.gem/ruby/3.1.0/gems/rack-2.2.7/lib/rack/builder.rb:105:in `load_file'
	from /Users/dan/.gem/ruby/3.1.0/gems/rack-2.2.7/lib/rack/builder.rb:66:in `parse_file'
	from /Users/dan/.gem/ruby/3.1.0/gems/puma-6.3.0/lib/puma/configuration.rb:366:in `load_rackup'
	from /Users/dan/.gem/ruby/3.1.0/gems/puma-6.3.0/lib/puma/configuration.rb:288:in `app'
	from /Users/dan/.gem/ruby/3.1.0/gems/puma-6.3.0/lib/puma/runner.rb:158:in `load_and_bind'
	from /Users/dan/.gem/ruby/3.1.0/gems/puma-6.3.0/lib/puma/single.rb:44:in `run'
	from /Users/dan/.gem/ruby/3.1.0/gems/puma-6.3.0/lib/puma/launcher.rb:194:in `run'
	from /Users/dan/.gem/ruby/3.1.0/gems/puma-6.3.0/lib/puma/cli.rb:75:in `run'
	from /Users/dan/.gem/ruby/3.1.0/gems/puma-6.3.0/bin/puma:10:in `<top (required)>'
	from /Users/dan/.gem/ruby/3.1.0/bin/puma:25:in `load'
	from /Users/dan/.gem/ruby/3.1.0/bin/puma:25:in `<top (required)>'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/3.1.0/bundler/cli.rb:484:in `exec'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.3/libexec/bundle:48:in `block in <top (required)>'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/dan/.rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.3/libexec/bundle:36:in `<top (required)>'
	from /Users/dan/.gem/ruby/3.1.0/bin/bundle:25:in `load'
	from /Users/dan/.gem/ruby/3.1.0/bin/bundle:25:in `<main>'
```
### System configuration
**Rails version**: n/a
**Ruby version**: ruby-3.1.0

**Comment by rafaelfranca** [comment]
This is a bug in neo4j-core. [They are using active support without requiring the top level `active_support` file](https://github.com/neo4jrb/neo4j-core/blob/4b649fca33a1b1dba8705e6f999764ad9fb4d76e/lib/neo4j/transaction.rb#LL1C5-L2) as documented [here](https://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support).

Cloud you please open an issue there?
