### ISSUE TITLE
I would like `Nokogiri` to be installed only for those who need it through bundle install.

### ISSUE THREAD

**Issue by keisukeYamagishi** [rails/rails#48439]
### Steps to reproduce

I have obtained the following LOG

```
bash-5.1# rails s -p 3000 -b '0.0.0.0'
=> Booting Puma
=> Rails 5.2.8.1 application starting in development 
=> Run `rails server -h` for more startup options
Exiting
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/nokogiri-1.15.2-aarch64-linux/lib/nokogiri/extension.rb:31:in `rescue in <top (required)>'
	from /usr/local/bundle/gems/nokogiri-1.15.2-aarch64-linux/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /usr/local/bundle/gems/nokogiri-1.15.2-aarch64-linux/lib/nokogiri.rb:8:in `require_relative'
	from /usr/local/bundle/gems/nokogiri-1.15.2-aarch64-linux/lib/nokogiri.rb:8:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/loofah-2.21.3/lib/loofah.rb:3:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/rails-html-sanitizer-1.6.0/lib/rails-html-sanitizer.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/sanitize_helper.rb:4:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/text_helper.rb:34:in `<module:TextHelper>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/text_helper.rb:31:in `<module:Helpers>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/text_helper.rb:8:in `<module:ActionView>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/text_helper.rb:6:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/form_tag_helper.rb:20:in `<module:FormTagHelper>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/form_tag_helper.rb:16:in `<module:Helpers>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/form_tag_helper.rb:10:in `<module:ActionView>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/form_tag_helper.rb:8:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/form_helper.rb:6:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers.rb:54:in `<module:Helpers>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers.rb:6:in `<module:ActionView>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/base.rb:7:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/debug_exceptions.rb:7:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application/default_middleware_stack.rb:49:in `block in build_stack'
	from /usr/local/bundle/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/stack.rb:47:in `initialize'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application/default_middleware_stack.rb:15:in `new'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application/default_middleware_stack.rb:15:in `build_stack'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application.rb:576:in `default_middleware_stack'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:508:in `block in app'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:506:in `synchronize'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:506:in `app'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application.rb:361:in `initialize!'
	from /app/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:116:in `eval'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:116:in `new_from_string'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:105:in `load_file'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:66:in `parse_file'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:249:in `app'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:27:in `app'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:422:in `wrapped_app'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:51:in `start'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/command/base.rb:69:in `perform'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/command.rb:46:in `invoke'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
/usr/local/bundle/gems/nokogiri-1.15.2-aarch64-linux/lib/nokogiri/extension.rb:7:in `require_relative': Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/local/bundle/gems/nokogiri-1.15.2-aarch64-linux/lib/nokogiri/3.1/nokogiri.so) - /usr/local/bundle/gems/nokogiri-1.15.2-aarch64-linux/lib/nokogiri/3.1/nokogiri.so (LoadError)
	from /usr/local/bundle/gems/nokogiri-1.15.2-aarch64-linux/lib/nokogiri/extension.rb:7:in `<top (required)>'
	from /usr/local/bundle/gems/nokogiri-1.15.2-aarch64-linux/lib/nokogiri.rb:8:in `require_relative'
	from /usr/local/bundle/gems/nokogiri-1.15.2-aarch64-linux/lib/nokogiri.rb:8:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/loofah-2.21.3/lib/loofah.rb:3:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/rails-html-sanitizer-1.6.0/lib/rails-html-sanitizer.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/sanitize_helper.rb:4:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/text_helper.rb:34:in `<module:TextHelper>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/text_helper.rb:31:in `<module:Helpers>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/text_helper.rb:8:in `<module:ActionView>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/text_helper.rb:6:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/form_tag_helper.rb:20:in `<module:FormTagHelper>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/form_tag_helper.rb:16:in `<module:Helpers>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/form_tag_helper.rb:10:in `<module:ActionView>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/form_tag_helper.rb:8:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers/form_helper.rb:6:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers.rb:54:in `<module:Helpers>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers.rb:6:in `<module:ActionView>'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/helpers.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionview-5.2.8.1/lib/action_view/base.rb:7:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/debug_exceptions.rb:7:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application/default_middleware_stack.rb:49:in `block in build_stack'
	from /usr/local/bundle/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/stack.rb:47:in `initialize'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application/default_middleware_stack.rb:15:in `new'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application/default_middleware_stack.rb:15:in `build_stack'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application.rb:576:in `default_middleware_stack'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:508:in `block in app'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:506:in `synchronize'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/engine.rb:506:in `app'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/application.rb:361:in `initialize!'
	from /app/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:116:in `eval'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:116:in `new_from_string'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:105:in `load_file'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:66:in `parse_file'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:249:in `app'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:27:in `app'
	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:422:in `wrapped_app'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:51:in `start'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/command/base.rb:69:in `perform'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/command.rb:46:in `invoke'
	from /usr/local/bundle/gems/railties-5.2.8.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'

```

### Expected behavior
execute `rails s -p 3000 -b '0.0.0.0'`

### Actual behavior
 can not execute it OMG

### System configuration
**Rails version**:
5.*
**Ruby version**:
3.1.0

Why do you need Nokogiri?
I don't need it. I don't require it.
Please delete it or tell me an alternative method.

**Comment by keisukeYamagishi** [comment]
I don't actually need `nokogiri` at all, so why is it necessary? Is it possible to modify it so that it's not required even if I don't use it?

**Comment by keisukeYamagishi** [comment]
Rethink my environment and executed the following steps:

```bash
bash-5.1# apk search ld-linux-aarch64.so.1
```

The following output is displayed:

```bash
gcompat-1.0.0-r4
```

```bash
bash-5.1# apk add gcompat
(1/2) Installing musl-obstack (1.2.3-r0)
(2/2) Installing gcompat (1.0.0-r4)
OK: 349 MiB in 94 packages
```

Add the following to your Dockerfile:
```bash
apk --no-cache add
gcompat \
```

The version of Ruby is as follows:
```yml
FROM ruby:3.1.0-alpine
```
Install nokogiri as follows:
```
Installing nokogiri 1.15.2 (aarch64-linux)
```
After that, you can run the following command:
```bash
bash-5.1# rails s -p 3000 -b '0.0.0.0'
=> Booting Puma
=> Rails 7.0.5 application starting in development
=> Run `bin/rails server --help` for more startup options
[587] Puma starting in cluster mode...
[587] * Puma version: 6.3.0 (ruby 3.1.0-p0) ("Mugi No Toki Itaru")
[587] *  Min threads: 5
[587] *  Max threads: 5
[587] *  Environment: development
[587] *   Master PID: 587
[587] *      Workers: 2
[587] *     Restarts: (✔) hot (✖) phased
[587] * Preloading application
[587] * Listening on http://0.0.0.0:3000
[587] Use Ctrl-C to stop
DEPRECATION WARNING: Using legacy connection handling is deprecated. Please set
`legacy_connection_handling` to `false` in your application.

The new connection handling does not support the `connection_handlers` getter and setter.
```
Success🎉

but I think you should rethink that.

**Comment by JoeDupuis** [comment]
Nokogiri is a dependency of Rails. It is used internally by various components (Action Pack, Action View, Action Text). 
It cannot be removed. 

That being said, something is weird with you setup. You would have an easier time using the regular base image instead of the alpine one. 

Switch `FROM ruby:3.1.0-alpine` to `FROM ruby:3.1.0`

**Comment by yahonda** [comment]
Hi, There is no plan to remove Nokogiri from Rails as also explained https://github.com/rails/rails/issues/41016

We do not accept feature requests in the issue tracker, please join the discussion below if you are interested in this topic https://discuss.rubyonrails.org/t/nokogiri-as-a-default-dependency/74369
