### ISSUE TITLE
Active Support unit tests fails against Ruby 3.1 and 3.2

### ISSUE THREAD

**Issue by yahonda** [rails/rails#48483]
### Steps to reproduce
https://buildkite.com/rails/rails/builds/97157#0188bbe5-7031-470f-a9ef-8c72d49e5116/1052-1061

https://buildkite.com/rails/rails/builds/97157#0188bbe5-70b9-47d2-b3b4-f8fbdd4cf611/1167-1176

### Expected behavior
Active Support unit tests should run against all Ruby versions 3.0, 3.1, 3.2 and 3.3.0dev

### Actual behavior
Active Support unit tests fail against Ruby 3.1 and 3.2, Ruby 3.0 and 3.3.0dev are fine.

### System configuration
**Rails version**: main branch

**Ruby version**:
Ruby          3.1.4p223 (2023-03-30 revision 957bb7cb81995f26c671afce0ee50a5c660e540e) [x86_64-linux]

Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x86_64-linux]

**Comment by yahonda** [comment]
Here are minimum steps:

```
$ bin/test test/message_encryptors_test.rb -n "/^(?:MessageEncryptorsTest#(?:test_#transitional_swaps_the_first_two_rotations_when_enabled|test_#transitional_treats_a_nil_first_rotation_as_a_new_rotation))$/"
Running 24 tests in a single process (parallelization threshold is 50)
Run options: -n "/^(?:MessageEncryptorsTest#(?:test_#transitional_swaps_the_first_two_rotations_when_enabled|test_#transitional_treats_a_nil_first_rotation_as_a_new_rotation))$/" --seed 34990

# Running:

E

Error:
MessageEncryptorsTest#test_#transitional_swaps_the_first_two_rotations_when_enabled:
OpenSSL::HMACError: EVP_DigestSignInit: unsupported
    /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/3.2.0/openssl/hmac.rb:55:in `initialize'
    /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/3.2.0/openssl/hmac.rb:55:in `new'
    /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/3.2.0/openssl/hmac.rb:55:in `hexdigest'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_verifier.rb:328:in `generate_digest'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_verifier.rb:306:in `sign_encoded'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_verifier.rb:297:in `create_message'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_encryptor.rb:266:in `sign'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_encryptor.rb:257:in `create_message'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_encryptor.rb:221:in `encrypt_and_sign'
    /home/yahonda/src/github.com/rails/rails/activesupport/test/message_encryptors_test.rb:50:in `roundtrip'
    /home/yahonda/src/github.com/rails/rails/activesupport/test/rotation_coordinator_tests.rb:113:in `block (2 levels) in <module:RotationCoordinatorTests>'


bin/test test/rotation_coordinator_tests.rb:97

E

Error:
MessageEncryptorsTest#test_#transitional_treats_a_nil_first_rotation_as_a_new_rotation:
OpenSSL::Digest::DigestError: Digest initialization failed: initialization error
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_verifier.rb:336:in `initialize'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_verifier.rb:336:in `new'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_verifier.rb:336:in `digest_length_in_hex'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_verifier.rb:344:in `separator_index_for'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_verifier.rb:315:in `extract_encoded'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_verifier.rb:301:in `read_message'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/rotator.rb:25:in `read_message'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_encryptor.rb:270:in `verify'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_encryptor.rb:261:in `read_message'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/rotator.rb:25:in `read_message'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/rotator.rb:33:in `block (2 levels) in read_message'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/rotator.rb:51:in `block (2 levels) in catch_rotation_error'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/rotator.rb:50:in `catch'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/rotator.rb:50:in `block in catch_rotation_error'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/rotator.rb:49:in `catch'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/rotator.rb:49:in `catch_rotation_error'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/rotator.rb:32:in `block in read_message'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/rotator.rb:31:in `each'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/rotator.rb:31:in `read_message'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_encryptor.rb:245:in `block (3 levels) in decrypt_and_verify'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/codec.rb:47:in `block in catch_and_ignore'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/codec.rb:46:in `catch'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/codec.rb:46:in `catch_and_ignore'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_encryptor.rb:244:in `block (2 levels) in decrypt_and_verify'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/codec.rb:54:in `block in catch_and_raise'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/codec.rb:53:in `catch'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/codec.rb:53:in `catch_and_raise'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_encryptor.rb:243:in `block in decrypt_and_verify'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/codec.rb:54:in `block in catch_and_raise'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/codec.rb:53:in `catch'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/messages/codec.rb:53:in `catch_and_raise'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/message_encryptor.rb:242:in `decrypt_and_verify'
    /home/yahonda/src/github.com/rails/rails/activesupport/test/message_encryptors_test.rb:50:in `roundtrip'
    /home/yahonda/src/github.com/rails/rails/activesupport/test/rotation_coordinator_tests.rb:146:in `block (2 levels) in <module:RotationCoordinatorTests>'


bin/test test/rotation_coordinator_tests.rb:128



Finished in 0.078272s, 25.5520 runs/s, 89.4320 assertions/s.
2 runs, 7 assertions, 0 failures, 2 errors, 0 skips
$
```

**Comment by yahonda** [comment]
Reported to https://github.com/ruby/openssl/issues/642
