### ISSUE TITLE
Action View `actionview: rake test:ujs` gets `ERROR: 127`

### ISSUE THREAD

**Issue by yahonda** [rails/rails#48525]
Managed to reproduce CI error since https://buildkite.com/rails/rails/builds/97157#0188bbe5-70da-4702-8617-4de08ad34ece/1090-1091

### Steps to reproduce

```ruby
$ git clone https://github.com/rails/rails.git
$ cd rails
$ git clone https://github.com/rails/buildkite-config .buildkite/
$ RUBY_IMAGE=ruby:3.2 docker-compose -f .buildkite/docker-compose.yml build base \
&& CI=1 docker-compose -f .buildkite/docker-compose.yml run -e PRE_STEPS -e RACK --rm actionview runner actionview 'rake test:ujs'
```

### Expected behavior
It should finish successfully

### Actual behavior
It gets `ERROR: 127` . Here is the entire output.
https://gist.github.com/yahonda/8384471b51c204ffab363fa471eea25f

### System configuration
**Rails version**: main branch

**Ruby version**: 3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x86_64-linux]

**Comment by yahonda** [comment]
exit status 127 is raised when the command for system method is not available.
https://github.com/rails/rails/blob/162c4b47d3d5e230b4b64f2c977d814c96e3bbbd/actionview/Rakefile#L35-L36

- Example
```
$ irb
irb(main):003:0> system('nonexistent_program')
=> nil
irb(main):004:0> $?.exitstatus
=> 127
irb(main):005:0>
```

- When `npm` command is not installed, it exits with 127 exit code
```
$ which npm
$ bundle exec rake test:ujs
$ echo $?
127
```

- When `npm` command is installed, it attempts to `karma start` and get another error.
Actually, I am not familiar with ujs, so it may be my environment specific.

```
$ sudo apt install npm
$ which npm
/usr/bin/npm
$ bundle exec rake test:ujs

> @rails/ujs@7.1.0-alpha lint
> eslint app/javascript && eslint test/ujs/public/test


> @rails/ujs@7.1.0-alpha pretest
> rollup --config rollup.config.test.js


test/ujs/src/test.js → test/ujs/compiled/test.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
jquery (imported by test/ujs/public/test/call-remote-callbacks.js, test/ujs/public/test/csrf-refresh.js, test/ujs/public/test/data-disable.js, test/ujs/public/test/call-remote.js, test/ujs/public/test/settings.js, test/ujs/public/test/data-disable-with.js, test/ujs/public/test/csrf-token.js, test/ujs/public/test/override.js, test/ujs/public/test/data-method.js, test/ujs/public/test/data-remote.js, test/ujs/public/test/data-confirm.js, test/ujs/public/test/call-ajax.js)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
jquery (guessing '$$1')
created test/ujs/compiled/test.js in 311ms

> @rails/ujs@7.1.0-alpha test
> karma start

20 06 2023 12:37:55.024:INFO [karma-server]: Karma v3.1.3 server started at http://0.0.0.0:9876/
20 06 2023 12:37:55.026:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
20 06 2023 12:37:55.030:INFO [launcher]: Starting browser ChromeHeadless
20 06 2023 12:37:55.584:INFO [HeadlessChrome 114.0.5735 (Linux 0.0.0)]: Connected on socket 8BN1Aai2DgIKDA_-AAAA with id 74785195
HeadlessChrome 114.0.5735 (Linux 0.0.0) ERROR
  {
    "message": "Uncaught ReferenceError: $$1 is not defined\nat test/ujs/compiled/test.js:3541:3\n\nReferenceError: $$1 is not defined\n    at test/ujs/compiled/test.js:3541:3",
    "str": "Uncaught ReferenceError: $$1 is not defined\nat test/ujs/compiled/test.js:3541:3\n\nReferenceError: $$1 is not defined\n    at test/ujs/compiled/test.js:3541:3"
  }


npm ERR! Lifecycle script `test` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @rails/ujs@7.1.0-alpha
npm ERR!   at location: /home/yahonda/src/github.com/rails/rails/actionview
```

**Comment by yahonda** [comment]
After installing `npm` package at https://github.com/rails/buildkite-config ,
'rake test:ujs' finishes successfully.

```
$ git diff
diff --git a/Dockerfile b/Dockerfile
index 80184a5..3997075 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -70,6 +70,7 @@ RUN echo "--- :ruby: Updating RubyGems and Bundler" \
         libxslt-dev \
         libyaml-dev \
         make \
+        npm \
         patch \
         unzip \
         xz-utils \
$
```

```
$ RUBY_IMAGE=ruby:3.2 docker-compose -f .buildkite/docker-compose.yml build base && CI=1 docker-compose -f .buildkite/docker-compose.yml run -e PRE_STEPS -e RACK --rm actionview runner actionview 'rake test:ujs'
... snip ...
+++ actionview: rake test:ujs

> @rails/ujs@7.1.0-alpha lint
> eslint app/javascript && eslint test/ujs/public/test


> @rails/ujs@7.1.0-alpha pretest
> rollup --config rollup.config.test.js


test/ujs/src/test.js → test/ujs/compiled/test.js...
created test/ujs/compiled/test.js in 698ms

> @rails/ujs@7.1.0-alpha test
> karma start

20 06 2023 03:45:33.745:INFO [karma-server]: Karma v3.1.4 server started at http://0.0.0.0:9876/
20 06 2023 03:45:33.748:INFO [launcher]: Launching browsers sl_chrome with concurrency unlimited
20 06 2023 03:45:33.753:INFO [launcher]: Starting browser chrome latest (Windows 10) on SauceLabs
20 06 2023 03:46:00.738:INFO [launcher.sauce]: chrome latest (Windows 10) session at https://saucelabs.com/tests/1a1f3e09f5f94d8dbcdc2a2eb572049d
20 06 2023 03:46:02.590:INFO [Chrome 114.0.0 (Windows 10.0.0)]: Connected on socket 01LDLgSQsZE1pohTAAAA with id 61941211
................................................................................
..................................................
Chrome 114.0.0 (Windows 10.0.0): Executed 130 of 130 SUCCESS (17.381 secs / 17.118 secs)
20 06 2023 03:46:21.439:INFO [launcher.sauce]: Shutting down Sauce Connect
$ echo $?
0
$
```

Here is the entire log file.
https://gist.github.com/yahonda/19c8fbb0aa95f768efafaaf4841ff65b

**Comment by yahonda** [comment]
Opened https://github.com/rails/buildkite-config/pull/50 to address this issue.

**Comment by yahonda** [comment]
Closed https://github.com/rails/buildkite-config/pull/50 and opened another one
https://github.com/rails/buildkite-config/pull/51
