### ISSUE TITLE
Cannot load `Rails.application.database_configuration

### ISSUE THREAD

**Issue by JayPanchani1054** [rails/rails#48621]
After installing refinerycms gem and creating a new app with $ refinerycms rickrockstar
when I tried to run rails server it shows:

```
=> Booting Puma
=> Rails 5.1.7 application starting in development
=> Run `rails server -h` for more startup options
Exiting
C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:431:in `visit_Psych_Nodes_Alias': Cannot load `Rails.application.database_configuration`: (ArgumentError)
wrong number of arguments (given 1, expected 0)
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:347:in `block in revive_hash'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each_slice'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `revive_hash'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:169:in `visit_Psych_Nodes_Mapping'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:347:in `block in revive_hash'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each_slice'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `revive_hash'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:169:in `visit_Psych_Nodes_Mapping'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:320:in `visit_Psych_Nodes_Document'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych.rb:334:in `safe_load'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych.rb:369:in `load'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/application/configuration.rb:133:in `database_configuration'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activerecord-5.1.7/lib/active_record/railtie.rb:121:in `block (2 levels) in <class:Railtie>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:41:in `block in on_load'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:40:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:40:in `on_load'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activerecord-5.1.7/lib/active_record/railtie.rb:120:in `block in <class:Railtie>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `instance_exec'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `run'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/initializable.rb:59:in `block in run_initializers'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:347:in `each'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:347:in `call'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/initializable.rb:58:in `run_initializers'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/application.rb:353:in `initialize!'
        from W:/Computer ENG/Dev/Reel Canteen/reelc/config/environment.rb:5:in `<top (required)>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `eval'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `new_from_string'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:105:in `load_file'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:66:in `parse_file'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:249:in `app'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:24:in `app'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:422:in `wrapped_app'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:42:in `start'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:135:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:130:in `perform'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/command/base.rb:63:in `perform'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/command.rb:44:in `invoke'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from bin/rails:4:in `<main>'
C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:431:in `visit_Psych_Nodes_Alias': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:347:in `block in revive_hash'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each_slice'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `revive_hash'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:169:in `visit_Psych_Nodes_Mapping'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:347:in `block in revive_hash'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each_slice'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `revive_hash'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:169:in `visit_Psych_Nodes_Mapping'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:320:in `visit_Psych_Nodes_Document'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych.rb:334:in `safe_load'
        from C:/Ruby32-x64/lib/ruby/3.2.0/psych.rb:369:in `load'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/application/configuration.rb:133:in `database_configuration'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activerecord-5.1.7/lib/active_record/railtie.rb:121:in `block (2 levels) in <class:Railtie>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:41:in `block in on_load'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:40:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:40:in `on_load'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activerecord-5.1.7/lib/active_record/railtie.rb:120:in `block in <class:Railtie>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `instance_exec'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `run'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/initializable.rb:59:in `block in run_initializers'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:347:in `each'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:347:in `call'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
        from C:/Ruby32-x64/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/initializable.rb:58:in `run_initializers'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/application.rb:353:in `initialize!'
        from W:/Computer ENG/Dev/Reel Canteen/reelc/config/environment.rb:5:in `<top (required)>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `eval'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `new_from_string'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:105:in `load_file'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:66:in `parse_file'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:249:in `app'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:24:in `app'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:422:in `wrapped_app'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:42:in `start'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:135:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:130:in `perform'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/command/base.rb:63:in `perform'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/command.rb:44:in `invoke'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by JayPanchani1054** [comment]
I just got solution from chatgpt it's because of the ruby version that I'm using. In order to use refinerycms I downgraded my rails version to 5.1.7 & ruby version to 2.7.8

**Comment by JayPanchani1054** [comment]
I just got solution from chatgpt it's because of the ruby version that I'm using. In order to use refinerycms I downgraded my rails version to 5.1.7 & ruby version to 2.7.8
