### ISSUE TITLE
Rails 7.0.6 - undefined method `wait_for_state' 

### ISSUE THREAD

**Issue by OskarEichler** [rails/rails#48620]
### Steps to reproduce
After upgrading to Rails 7.0.6 we are getting an `undefined method `wait_for_state' ` error, please see below for error log.

### Expected behavior
Rails App should initialize

### Actual behavior
Getting error: undefined method `wait_for_state' 

### System configuration
**Rails version**:
7.0.6

**Ruby version**:
3.2.1

**Error Log**:

```
/Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/evented_file_update_checker.rb:120:in `start': undefined method `wait_for_state' for #<Listen::Listener:0x000000010b2838e8 @config=#<Listen::Listener::Config:0x000000010b283898 @options={:debug=>false, :wait_for_delay=>nil, :relative=>false, :force_polling=>false, :polling_fallback_message=>nil}, @relative=false, @min_delay_between_events=nil, @silencer_rules={:debug=>false, :wait_for_delay=>nil, :relative=>false, :force_polling=>false, :polling_fallback_message=>nil}>, @silencer_controller=#<Listen::Silencer::Controller:0x000000010b2a1e10 @silencer=#<Listen::Silencer:0x000000010b2a2040 @only_patterns=nil, @ignore_patterns=[/^(?: (NoMethodError)
      \.git
      | \.svn
      | \.hg
      | \.rbx
      | \.bundle
      | bundle
      | vendor\/bundle
      | log
      | tmp
      |vendor\/ruby
    )(\/|$)/x, /(?:
      # Kate's tmp\/swp files
      \..*\d+\.new
      | \.kate-swp

      # Gedit tmp files
      | \.goutputstream-.{6}

      # Intellij files
      | ___jb_bak___
      | ___jb_old___

      # Vim swap files and write test
      | \.sw[px]
      | \.swpx
      | ^4913

      # Sed temporary files - but without actual words, like 'sedatives'
      | (?:^
         sed

         (?:
          [a-zA-Z0-9]{0}[A-Z]{1}[a-zA-Z0-9]{5} |
          [a-zA-Z0-9]{1}[A-Z]{1}[a-zA-Z0-9]{4} |
          [a-zA-Z0-9]{2}[A-Z]{1}[a-zA-Z0-9]{3} |
          [a-zA-Z0-9]{3}[A-Z]{1}[a-zA-Z0-9]{2} |
          [a-zA-Z0-9]{4}[A-Z]{1}[a-zA-Z0-9]{1} |
          [a-zA-Z0-9]{5}[A-Z]{1}[a-zA-Z0-9]{0}
         )
        )

      # other files
      | \.DS_Store
      | \.tmp
      | ~
    )$/x]>, @prev_silencer_options={}>, @backend=#<Listen::Backend:0x000000010b2a1af0 @min_delay_between_events=0.05, @adapter=#<Listen::Adapter::Polling:0x000000010b282cb8 @started=true, @config=#<Listen::Adapter::Config:0x000000010b282df8 @directories=[#<Pathname:/Users/Oskar/1001tl/config/locales>], @silencer=#<Listen::Silencer:0x000000010b2a2040 @only_patterns=nil, @ignore_patterns=[/^(?:
      \.git
      | \.svn
      | \.hg
      | \.rbx
      | \.bundle
      | bundle
      | vendor\/bundle
      | log
      | tmp
      |vendor\/ruby
    )(\/|$)/x, /(?:
      # Kate's tmp\/swp files
      \..*\d+\.new
      | \.kate-swp

      # Gedit tmp files
      | \.goutputstream-.{6}

      # Intellij files
      | ___jb_bak___
      | ___jb_old___

      # Vim swap files and write test
      | \.sw[px]
      | \.swpx
      | ^4913

      # Sed temporary files - but without actual words, like 'sedatives'
      | (?:^
         sed

         (?:
          [a-zA-Z0-9]{0}[A-Z]{1}[a-zA-Z0-9]{5} |
          [a-zA-Z0-9]{1}[A-Z]{1}[a-zA-Z0-9]{4} |
          [a-zA-Z0-9]{2}[A-Z]{1}[a-zA-Z0-9]{3} |
          [a-zA-Z0-9]{3}[A-Z]{1}[a-zA-Z0-9]{2} |
          [a-zA-Z0-9]{4}[A-Z]{1}[a-zA-Z0-9]{1} |
          [a-zA-Z0-9]{5}[A-Z]{1}[a-zA-Z0-9]{0}
         )
        )

      # other files
      | \.DS_Store
      | \.tmp
      | ~
    )$/x]>, @queue=#<Listen::Event::Queue:0x000000010b2a21f8 @event_queue=#<Thread::Queue:0x000000010b2a2158>, @block=#<Proc:0x000000010b2a20b8 /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.0.8/lib/listen/listener.rb:40>, @config=#<Listen::Event::Queue::Config:0x000000010b2a2298 @relative=false>>, @adapter_options={:wait_for_delay=>nil}>, @configured=true, @options=#<Listen::Options:0x000000010b2ee148 @options={:latency=>1.0, :wait_for_delay=>0.05}>, @callbacks={#<Pathname:/Users/Oskar/1001tl/config/locales>=>#<Proc:0x000000010b2ed7c0 /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.0.8/lib/listen/adapter/base.rb:41 (lambda)>}, @polling_callbacks=[#<Proc:0x000000010b2ed7c0 /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.0.8/lib/listen/adapter/base.rb:41 (lambda)>], @snapshots={#<Pathname:/Users/Oskar/1001tl/config/locales>=>#<Listen::Change:0x000000010b2ed450 @config=#<Listen::Change::Config:0x000000010b2ed680 @queue=#<Listen::Event::Queue:0x000000010b2a21f8 @event_queue=#<Thread::Queue:0x000000010b2a2158>, @block=#<Proc:0x000000010b2a20b8 /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.0.8/lib/listen/listener.rb:40>, @config=#<Listen::Event::Queue::Config:0x000000010b2a2298 @relative=false>>, @silencer=#<Listen::Silencer:0x000000010b2a2040 @only_patterns=nil, @ignore_patterns=[/^(?:
      \.git
      | \.svn
      | \.hg
      | \.rbx
      | \.bundle
      | bundle
      | vendor\/bundle
      | log
      | tmp
      |vendor\/ruby
    )(\/|$)/x, /(?:
      # Kate's tmp\/swp files
      \..*\d+\.new
      | \.kate-swp

      # Gedit tmp files
      | \.goutputstream-.{6}

      # Intellij files
      | ___jb_bak___
      | ___jb_old___

      # Vim swap files and write test
      | \.sw[px]
      | \.swpx
      | ^4913

      # Sed temporary files - but without actual words, like 'sedatives'
      | (?:^
         sed

         (?:
          [a-zA-Z0-9]{0}[A-Z]{1}[a-zA-Z0-9]{5} |
          [a-zA-Z0-9]{1}[A-Z]{1}[a-zA-Z0-9]{4} |
          [a-zA-Z0-9]{2}[A-Z]{1}[a-zA-Z0-9]{3} |
          [a-zA-Z0-9]{3}[A-Z]{1}[a-zA-Z0-9]{2} |
          [a-zA-Z0-9]{4}[A-Z]{1}[a-zA-Z0-9]{1} |
          [a-zA-Z0-9]{5}[A-Z]{1}[a-zA-Z0-9]{0}
         )
        )

      # other files
      | \.DS_Store
      | \.tmp
      | ~
    )$/x]>>, @record=#<Listen::Record:0x000000010b2ed5e0 @tree={"devise.en.yml"=>{:mtime=>1686929602.3669014, :mode=>33188}}, @root="/Users/Oskar/1001tl/config/locales">>}>>, @processor=#<Listen::Event::Loop:0x000000010b282c18 @config=#<Listen::Event::Config:0x000000010b282c68 @listener=#<Listen::Listener:0x000000010b2838e8 ...>, @event_queue=#<Listen::Event::Queue:0x000000010b2a21f8 @event_queue=#<Thread::Queue:0x000000010b2a2158>, @block=#<Proc:0x000000010b2a20b8 /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.0.8/lib/listen/listener.rb:40>, @config=#<Listen::Event::Queue::Config:0x000000010b2a2298 @relative=false>>, @queue_optimizer=#<Listen::QueueOptimizer:0x000000010b2edf68 @config=#<Listen::QueueOptimizer::Config:0x000000010b2ee030 @adapter_class=#<Listen::Backend:0x000000010b2a1af0 @min_delay_between_events=0.05, @adapter=#<Listen::Adapter::Polling:0x000000010b282cb8 @started=true, @config=#<Listen::Adapter::Config:0x000000010b282df8 @directories=[#<Pathname:/Users/Oskar/1001tl/config/locales>], @silencer=#<Listen::Silencer:0x000000010b2a2040 @only_patterns=nil, @ignore_patterns=[/^(?:
      \.git
      | \.svn
      | \.hg
      | \.rbx
      | \.bundle
      | bundle
      | vendor\/bundle
      | log
      | tmp
      |vendor\/ruby
    )(\/|$)/x, /(?:
      # Kate's tmp\/swp files
      \..*\d+\.new
      | \.kate-swp

      # Gedit tmp files
      | \.goutputstream-.{6}

      # Intellij files
      | ___jb_bak___
      | ___jb_old___

      # Vim swap files and write test
      | \.sw[px]
      | \.swpx
      | ^4913

      # Sed temporary files - but without actual words, like 'sedatives'
      | (?:^
         sed

         (?:
          [a-zA-Z0-9]{0}[A-Z]{1}[a-zA-Z0-9]{5} |
          [a-zA-Z0-9]{1}[A-Z]{1}[a-zA-Z0-9]{4} |
          [a-zA-Z0-9]{2}[A-Z]{1}[a-zA-Z0-9]{3} |
          [a-zA-Z0-9]{3}[A-Z]{1}[a-zA-Z0-9]{2} |
          [a-zA-Z0-9]{4}[A-Z]{1}[a-zA-Z0-9]{1} |
          [a-zA-Z0-9]{5}[A-Z]{1}[a-zA-Z0-9]{0}
         )
        )

      # other files
      | \.DS_Store
      | \.tmp
      | ~
    )$/x]>, @queue=#<Listen::Event::Queue:0x000000010b2a21f8 @event_queue=#<Thread::Queue:0x000000010b2a2158>, @block=#<Proc:0x000000010b2a20b8 /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.0.8/lib/listen/listener.rb:40>, @config=#<Listen::Event::Queue::Config:0x000000010b2a2298 @relative=false>>, @adapter_options={:wait_for_delay=>nil}>, @configured=true, @options=#<Listen::Options:0x000000010b2ee148 @options={:latency=>1.0, :wait_for_delay=>0.05}>, @callbacks={#<Pathname:/Users/Oskar/1001tl/config/locales>=>#<Proc:0x000000010b2ed7c0 /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.0.8/lib/listen/adapter/base.rb:41 (lambda)>}, @polling_callbacks=[#<Proc:0x000000010b2ed7c0 /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.0.8/lib/listen/adapter/base.rb:41 (lambda)>], @snapshots={#<Pathname:/Users/Oskar/1001tl/config/locales>=>#<Listen::Change:0x000000010b2ed450 @config=#<Listen::Change::Config:0x000000010b2ed680 @queue=#<Listen::Event::Queue:0x000000010b2a21f8 @event_queue=#<Thread::Queue:0x000000010b2a2158>, @block=#<Proc:0x000000010b2a20b8 /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.0.8/lib/listen/listener.rb:40>, @config=#<Listen::Event::Queue::Config:0x000000010b2a2298 @relative=false>>, @silencer=#<Listen::Silencer:0x000000010b2a2040 @only_patterns=nil, @ignore_patterns=[/^(?:
      \.git
      | \.svn
      | \.hg
      | \.rbx
      | \.bundle
      | bundle
      | vendor\/bundle
      | log
      | tmp
      |vendor\/ruby
    )(\/|$)/x, /(?:
      # Kate's tmp\/swp files
      \..*\d+\.new
      | \.kate-swp

      # Gedit tmp files
      | \.goutputstream-.{6}

      # Intellij files
      | ___jb_bak___
      | ___jb_old___

      # Vim swap files and write test
      | \.sw[px]
      | \.swpx
      | ^4913

      # Sed temporary files - but without actual words, like 'sedatives'
      | (?:^
         sed

         (?:
          [a-zA-Z0-9]{0}[A-Z]{1}[a-zA-Z0-9]{5} |
          [a-zA-Z0-9]{1}[A-Z]{1}[a-zA-Z0-9]{4} |
          [a-zA-Z0-9]{2}[A-Z]{1}[a-zA-Z0-9]{3} |
          [a-zA-Z0-9]{3}[A-Z]{1}[a-zA-Z0-9]{2} |
          [a-zA-Z0-9]{4}[A-Z]{1}[a-zA-Z0-9]{1} |
          [a-zA-Z0-9]{5}[A-Z]{1}[a-zA-Z0-9]{0}
         )
        )

      # other files
      | \.DS_Store
      | \.tmp
      | ~
    )$/x]>>, @record=#<Listen::Record:0x000000010b2ed5e0 @tree={"devise.en.yml"=>{:mtime=>1686929602.3669014, :mode=>33188}}, @root="/Users/Oskar/1001tl/config/locales">>}>>, @silencer=#<Listen::Silencer:0x000000010b2a2040 @only_patterns=nil, @ignore_patterns=[/^(?:
      \.git
      | \.svn
      | \.hg
      | \.rbx
      | \.bundle
      | bundle
      | vendor\/bundle
      | log
      | tmp
      |vendor\/ruby
    )(\/|$)/x, /(?:
      # Kate's tmp\/swp files
      \..*\d+\.new
      | \.kate-swp

      # Gedit tmp files
      | \.goutputstream-.{6}

      # Intellij files
      | ___jb_bak___
      | ___jb_old___

      # Vim swap files and write test
      | \.sw[px]
      | \.swpx
      | ^4913

      # Sed temporary files - but without actual words, like 'sedatives'
      | (?:^
         sed

         (?:
          [a-zA-Z0-9]{0}[A-Z]{1}[a-zA-Z0-9]{5} |
          [a-zA-Z0-9]{1}[A-Z]{1}[a-zA-Z0-9]{4} |
          [a-zA-Z0-9]{2}[A-Z]{1}[a-zA-Z0-9]{3} |
          [a-zA-Z0-9]{3}[A-Z]{1}[a-zA-Z0-9]{2} |
          [a-zA-Z0-9]{4}[A-Z]{1}[a-zA-Z0-9]{1} |
          [a-zA-Z0-9]{5}[A-Z]{1}[a-zA-Z0-9]{0}
         )
        )

      # other files
      | \.DS_Store
      | \.tmp
      | ~
    )$/x]>>>, @min_delay_between_events=0.05, @block=#<Proc:0x000000010b2a25e0 (lambda)>>, @wait_thread=#<Thread:0x000000010b2ecfa0 /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6 sleep>, @state=:processing, @reasons=#<Thread::Queue:0x000000010b2ede00>>, @state=:processing_events>

        @listener&.wait_for_state(:processing_events)
                 ^^^^^^^^^^^^^^^^
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/evented_file_update_checker.rb:90:in `initialize'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/evented_file_update_checker.rb:42:in `new'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/evented_file_update_checker.rb:42:in `initialize'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/i18n_railtie.rb:64:in `new'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/i18n_railtie.rb:64:in `initialize_i18n'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/i18n_railtie.rb:20:in `block in <class:Railtie>'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/lazy_load_hooks.rb:92:in `block in execute_hook'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/lazy_load_hooks.rb:76:in `block in run_load_hooks'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/lazy_load_hooks.rb:75:in `each'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/lazy_load_hooks.rb:75:in `run_load_hooks'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/application/finisher.rb:87:in `block in <module:Finisher>'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:32:in `run'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/application.rb:372:in `initialize!'
	from /Users/Oskar/1001tl/config/environment.rb:5:in `<main>'
	from config.ru:5:in `require_relative'
	from config.ru:5:in `block in <main>'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `eval'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `new_from_string'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:105:in `load_file'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:66:in `parse_file'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:249:in `app'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:422:in `wrapped_app'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands/server/server_command.rb:36:in `start'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/command/base.rb:87:in `perform'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/command.rb:48:in `invoke'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands.rb:18:in `<main>'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/Oskar/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by guilleiguaran** [comment]
You need to upgrade the "listen" gem to a more recent version.

**Comment by OskarEichler** [comment]
That worked!! Thank you @guilleiguaran 🙌🏼
