### ISSUE TITLE
Repeated calls to `read_multi` on `NullStore` cache causes a NoMethodError

### ISSUE THREAD

**Issue by JBKahn** [rails/rails#48867]
### Steps to reproduce

Using a local cache block with the NullStore causes an exception. I dug a little deeper to discover that somehow the local cache has an explicitly stored `nil` for the missing value *after* the first call. And then when the second call is made, that is what causes it to break.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activesupport", "~> 7.0.6"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_two_calls_to_read_multi
    cache = ActiveSupport::Cache::NullStore.new
    cache.with_local_cache do 
      cache.write("1", "one")
      cache.write("2", "two")
      keys = ["1", "2", "3"]

      assert(cache.read_multi(*keys) == { "1" => "one", "2" => "two" })
      assert(cache.read_multi(*keys) == { "1" => "one", "2" => "two" })
    end
  end
end

```

### Expected behavior
The cache retrieves the values the second time

### Actual behavior

```
BugTest#test_two_calls_to_read_multi:
NoMethodError: undefined method `value' for nil:NilClass
    .gem/ruby/3.2.2/gems/activesupport-7.0.6/lib/active_support/cache/strategy/local_cache.rb:127:in `block in read_multi_entries'
    .gem/ruby/3.2.2/gems/activesupport-7.0.6/lib/active_support/cache/strategy/local_cache.rb:126:in `transform_values!'
    .gem/ruby/3.2.2/gems/activesupport-7.0.6/lib/active_support/cache/strategy/local_cache.rb:126:in `read_multi_entries'
    .gem/ruby/3.2.2/gems/activesupport-7.0.6/lib/active_support/cache.rb:400:in `block in read_multi'
    .gem/ruby/3.2.2/gems/activesupport-7.0.6/lib/active_support/cache.rb:783:in `block in instrument'
    .gem/ruby/3.2.2/gems/activesupport-7.0.6/lib/active_support/notifications.rb:208:in `instrument'
    .gem/ruby/3.2.2/gems/activesupport-7.0.6/lib/active_support/cache.rb:783:in `instrument'
    .gem/ruby/3.2.2/gems/activesupport-7.0.6/lib/active_support/cache.rb:399:in `read_multi'
    bug_test.rb:27:in `block in test_two_calls_to_read_multi'
    .gem/ruby/3.2.2/gems/activesupport-7.0.6/lib/active_support/cache/strategy/local_cache.rb:178:in `use_temporary_local_cache'
    .gem/ruby/3.2.2/gems/activesupport-7.0.6/lib/active_support/cache/strategy/local_cache.rb:64:in `with_local_cache'
    bug_test.rb:21:in `test_two_calls_to_read_multi'
```

### System configuration
**Rails version**: 7.0.6

**Ruby version**: 3.2.2

**Comment by rafaelfranca** [comment]
Fixed by #48868
