### ISSUE TITLE
`warning: instance variable @has_query_constraints not initialized`

### ISSUE THREAD

**Issue by yahonda** [rails/rails#48985]
### Steps to reproduce

Managed to reproduce CI failure https://buildkite.com/rails/rails/builds/98819#018a0ab6-fa5c-4db8-89e3-b6d140173e92

1. Install Ruby 2.7

```ruby
git clone https://github.com/rails/rails
cd rails/activerecord
bundle install
RAILS_STRICT_WARNINGS=1 bin/test test/cases/base_test.rb -n test_connection_in_local_time
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ ruby -v
ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-linux]
$ RAILS_STRICT_WARNINGS=1 bin/test test/cases/base_test.rb -n test_connection_in_local_time
Using sqlite3
Run options: -n test_connection_in_local_time --seed 9334

# Running:

/home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/persistence.rb:496: warning: instance variable @has_query_constraints not initialized
E

Error:
BasicsTest#test_connection_in_local_time:
RuntimeError: /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/persistence.rb:496: warning: instance variable @has_query_constraints not initialized

    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/strict_warnings.rb:32:in `warn'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/persistence.rb:496:in `has_query_constraints?'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/reflection.rb:810:in `association_primary_key'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/reflection.rb:820:in `join_primary_key'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixture_set/table_row.rb:162:in `block in resolve_sti_reflections'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixture_set/table_row.rb:150:in `each_value'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixture_set/table_row.rb:150:in `resolve_sti_reflections'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixture_set/table_row.rb:92:in `fill_row_model_attributes'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixture_set/table_row.rb:70:in `initialize'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixture_set/table_rows.rb:36:in `new'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixture_set/table_rows.rb:36:in `block in build_table_rows_from'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixture_set/table_rows.rb:35:in `each'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixture_set/table_rows.rb:35:in `map'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixture_set/table_rows.rb:35:in `build_table_rows_from'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixture_set/table_rows.rb:18:in `initialize'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:691:in `new'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:691:in `table_rows'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:625:in `block (2 levels) in insert'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:624:in `each'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:624:in `block in insert'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:621:in `each'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:621:in `insert'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:607:in `read_and_insert'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:552:in `create_fixtures'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/test_fixtures.rb:255:in `load_fixtures'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/test_fixtures.rb:142:in `setup_fixtures'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/test_fixtures.rb:10:in `before_setup'


bin/test test/cases/base_test.rb:1184



Finished in 0.019610s, 50.9954 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-linux]

**Comment by yahonda** [comment]
Rails CI fails when any warnings raised since https://github.com/rails/rails/commit/d917896f45a .
Since Ruby 3.0, uninitialized instance variables are not warned https://bugs.ruby-lang.org/issues/17055 .

**Comment by nvasilevski** [comment]
This was supposed to be fixed by https://github.com/rails/rails/commit/3b5a4a56fb1dc471fa6dd9450d8ed50d72d45732
and got substituted by https://github.com/rails/rails/commit/ce36426c988fa7d8df530aa557b2c21c6a679fed

It looks like the second fix didn't work for all scenarios so when we come up with a correct fix let's make sure we reference  previous attempts

**Comment by yahonda** [comment]
Confirmed https://github.com/rails/rails/commit/77080d5e17ae74a0e4fe169acf3a6405ddaf1610 addresses this issue. Thanks.
