### ISSUE TITLE
`DEPRECATION WARNING: AbstractStiPost model aliases`

### ISSUE THREAD

**Issue by yahonda** [rails/rails#48994]
### Steps to reproduce

```ruby
git clone https://github.com/rails/rails
cd rails/activerecord
bundle install
bin/test test/cases/associations/join_model_test.rb
```

### Expected behavior
It should pass without deprecation warnings.

### Actual behavior
It raises `DEPRECATION WARNING: AbstractStiPost model aliases`.

```ruby
$ bin/test test/cases/associations/join_model_test.rb
Using sqlite3
Run options: --seed 52182

# Running:

...........................DEPRECATION WARNING: AbstractStiPost model aliases `id` and has a method called `id_came_from_user?` defined. Starting in Rails 7.2 `id_value_came_from_user?` will not be calling `id_came_from_user?` anymore. You may want to additionally define `id_value_came_from_user?` to preserve the current behavior. (called from block (3 levels) in run at /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/test.rb:94)
/home/yahonda/src/github.com/rails/rails/activemodel/lib/active_model/attribute_methods.rb:218:in `block in generate_alias_attribute_methods'
  /home/yahonda/src/github.com/rails/rails/activemodel/lib/active_model/attribute_methods.rb:217:in `each'
  /home/yahonda/src/github.com/rails/rails/activemodel/lib/active_model/attribute_methods.rb:217:in `generate_alias_attribute_methods'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/attribute_methods.rb:58:in `block in alias_attribute'
  /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/code_generator.rb:41:in `batch'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/attribute_methods.rb:57:in `alias_attribute'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/model_schema.rb:621:in `block in load_schema!'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/model_schema.rb:612:in `each'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/model_schema.rb:612:in `load_schema!'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/attributes.rb:264:in `load_schema!'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/encryption/encryptable_record.rb:123:in `load_schema!'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/model_schema.rb:595:in `block in load_schema'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/model_schema.rb:592:in `synchronize'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/model_schema.rb:592:in `load_schema'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/model_schema.rb:416:in `columns_hash'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/inheritance.rb:88:in `descends_from_active_record?'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/inheritance.rb:86:in `descends_from_active_record?'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/inheritance.rb:94:in `finder_needs_type_condition?'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/inheritance.rb:349:in `ensure_proper_type'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/inheritance.rb:339:in `initialize_internals_callback'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/scoping.rb:55:in `initialize_internals_callback'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/core.rb:434:in `initialize'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/inheritance.rb:76:in `new'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/inheritance.rb:76:in `new'
  /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/persistence.rb:37:in `create'
  /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/associations/join_model_test.rb:102:in `test_polymorphic_has_many_create_model_with_inheritance_and_custom_base_class'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/test.rb:94:in `block (3 levels) in run'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/test.rb:191:in `capture_exceptions'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/test.rb:89:in `block (2 levels) in run'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:296:in `time_it'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/test.rb:88:in `block in run'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:405:in `on_signal'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/test.rb:239:in `with_info_handler'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/test.rb:87:in `run'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:1091:in `run_one_method'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:371:in `run_one_method'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:358:in `block (2 levels) in run'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:357:in `each'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:357:in `block in run'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:405:in `on_signal'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:392:in `with_info_handler'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:356:in `run'
  /home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/line_filtering.rb:10:in `run'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:182:in `block in __run'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:182:in `map'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:182:in `__run'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:159:in `run'
  /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest.rb:83:in `block in autorun'
... snip ...
Finished in 0.569273s, 177.4192 runs/s, 739.5396 assertions/s.
101 runs, 421 assertions, 0 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]

**Comment by yahonda** [comment]
This deprecation warning has been added via https://github.com/rails/rails/pull/48533

**Comment by nvasilevski** [comment]
A few observations:
- `AbstractStiPost` doesn't really alias `id` so the message is misleading
- None of the `AbstractStiPost` ancestors alias `id` as well
- Which makes me think that the alias is the global one we added in https://github.com/rails/rails/pull/48930
I can't see the warning on CI, could be a sign that it is only reproducible when models are lazy loaded

**Comment by ipc103** [comment]
👋 I took a quick peek and agree with @nvasilevski, it seems to be generated from the changes in #48930. Looks like the warning is being issues in CI as well, but it's not causing any tests to fair (see this [build](https://buildkite.com/rails/rails/builds/98917#018a19f1-8c03-4c1f-b281-0f1d9aa1413e) chosen somewhat at random for an example)

I believe the deprecation warning is being issued due to the check [here](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/attribute_methods.rb#L90) - it seems like the generated attribute method exists in a different module than the generated methods for the abstract class. To reproduce, I added `binding.irb if target_name == "id_came_from_user?" && self.name == "AbstractStiPost"` directly above line 90 in the file linked above and ran `bin/test test/cases/associations/join_model_test.rb`

```
3.1.2 :001 > manually_defined
 => true 
3.1.2 :002 > self.instance_method(target_name).owner
 => Post::GeneratedAttributeMethods 
3.1.2 :003 > generated_attribute_methods
 => AbstractStiPost::GeneratedAttributeMethods 
3.1.2 :004 > self
 => AbstractStiPost(abstract) 
 ```

**Comment by nvasilevski** [comment]
Here is the fix - https://github.com/rails/rails/pull/48996

I end up fixing the deprecation logic. But I still think that we shouldn't be defining global `id_value` on abstract classes and I'm also suspicious to why we even go into `load_schema!` for an abstract class. 
I'll look into that later, separately from the deprecation issue
