### ISSUE TITLE
Error "SystemCallError:Unknown error (SystemCallError)" at write in ActiveSupport::Cache::FileStore

### ISSUE THREAD

**Issue by rammpeter** [rails/rails#49295]
### Steps to reproduce

Executing leads to exception "SystemCallError:Unknown error (SystemCallError)" if executed on Windows 11 (Arm64) .
The same program / function works well without errors on Windows (x86_64).

```ruby
ActiveSupport::Cache::FileStore.new.write('key', { x: :y}, expires_in: 3.months ) 
```

Stacktrace for the call
```
org/jruby/RubyFile.java:676:in `chown'
C:/Users/pramm/AppData/Local/Temp/6acf7f8b-5770-4e0e-b127-dccc0b339b4f/gems/jruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext/file/atomic.rb:41:in `block in atomic_write'
org/jruby/ext/tempfile/Tempfile.java:246:in `open'
C:/Users/pramm/AppData/Local/Temp/6acf7f8b-5770-4e0e-b127-dccc0b339b4f/gems/jruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext/file/atomic.rb:24:in `atomic_write'
C:/Users/pramm/AppData/Local/Temp/6acf7f8b-5770-4e0e-b127-dccc0b339b4f/gems/jruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/cache/file_store.rb:88:in `write_entry'
C:/Users/pramm/AppData/Local/Temp/6acf7f8b-5770-4e0e-b127-dccc0b339b4f/gems/jruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/cache/strategy/local_cache.rb:165:in `write_entry'
C:/Users/pramm/AppData/Local/Temp/6acf7f8b-5770-4e0e-b127-dccc0b339b4f/gems/jruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/cache.rb:476:in `block in write'
C:/Users/pramm/AppData/Local/Temp/6acf7f8b-5770-4e0e-b127-dccc0b339b4f/gems/jruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/cache.rb:726:in `block in instrument'
C:/Users/pramm/AppData/Local/Temp/6acf7f8b-5770-4e0e-b127-dccc0b339b4f/gems/jruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/notifications.rb:205:in `instrument'
C:/Users/pramm/AppData/Local/Temp/6acf7f8b-5770-4e0e-b127-dccc0b339b4f/gems/jruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/cache.rb:726:in `instrument'
C:/Users/pramm/AppData/Local/Temp/6acf7f8b-5770-4e0e-b127-dccc0b339b4f/gems/jruby/3.1.0/gems/activesupport-6.1.7.6/lib/active_support/cache.rb:474:in `write'
C
```
### Expected behavior
No exception because the target file/dir is fully writable

### Actual behavior
Exception is raised in atomic_write at `chown(old_stat.uid, old_stat.gid, temp_file.path)` (line 41)

If all exceptions are catched at line 44 in the same way like `rescue Errno::EPERM, Errno::EACCES` then the functions does the expected.

### System configuration
Windows 11 preview for Arm64
Java 17.0.8.1

**Rails version**:
6.1.7.6

**Ruby version**:
jRuby 9.4.3.0

**Comment by skipkayhil** [comment]
Hey @rammpeter, thank you for opening an issue. This sounds like a bug in jRuby and not Rails, so I would open an issue there. (I'm happy to reopen if we discover that I'm wrong)
