### ISSUE TITLE
Custom master key path is not respected in credentials:show and credentials:edit

### ISSUE THREAD

**Issue by Verseth** [rails/rails#49328]
### Steps to reproduce

```sh
$ rails new example
$ cd example
$ mv config/master.key config/custom_master.key
$ echo "Rails.application.config.credentials.key_path = Rails.root.join('config', 'custom_master.key')" >> config/application.rb
$ echo "Rails.application.config.require_master_key = true" >> config/application.rb
```

The app is set up. It is configured with a custom master key path, and to shutdown when the master key could not be found.

### Expected behavior

The server should work just fine

```sh
$ bin/rails s
=> Booting Puma
=> Rails 7.0.8 application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.6.7 (ruby 3.2.2-p53) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 43547
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
```

The `credentials:show` and `credentials:edit` commands should look for the key in the file path configured in `config/application.rb`. They should load the key from `config/custom_master.key`, just like the app does when the server is started with `bin/rails server`

```sh
$ bin/rails credentials:show
# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 6dd34e9349447df81fac521bb56e790e7851148c8d6b308d9467ee4750f0432f5d2b9c64d49caa67094783504ee578932b7de5ffbe2478ea10b673de1ac85027
```

The same thing should happen for the `credentials:edit` command.

```sh
$ EDITOR="code --wait" bin/rails credentials:edit
```

### Actual behaviour
The server works just fine

```sh
$ bin/rails s
=> Booting Puma
=> Rails 7.0.8 application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.6.7 (ruby 3.2.2-p53) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 43547
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
```

But the `credentials:show` and `credentials:edit` commands are broken.

`bin/rails credentials:show` still looks for the master key in the default path `config/master.key` even though I configured `Rails.application.config.credentials.key_path` to `config/custom_master.key`.

```sh
$ bin/rails credentials:show
/Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/encrypted_file.rb:121:in `handle_missing_key': Missing encryption key to decrypt file with. Ask your team for your master key and write it to /Users/mateuszdrewniak/tmp/example/config/master.key or put it in the ENV['RAILS_MASTER_KEY']. (ActiveSupport::EncryptedFile::MissingKeyError)
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/encrypted_file.rb:53:in `key'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/encrypted_file.rb:65:in `read'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/encrypted_configuration.rb:43:in `read'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/commands/credentials/credentials_command.rb:51:in `show'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/command/base.rb:87:in `perform'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/command.rb:48:in `invoke'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<main>'
        from <internal:/Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
```

The same thing happens for the `credentials:edit` command.

```sh
$ EDITOR="code --wait" bin/rails credentials:edit
/Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/encrypted_file.rb:121:in `handle_missing_key': Missing encryption key to decrypt file with. Ask your team for your master key and write it to /Users/mateuszdrewniak/tmp/example/config/master.key or put it in the ENV['RAILS_MASTER_KEY']. (ActiveSupport::EncryptedFile::MissingKeyError)
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/encrypted_file.rb:53:in `key'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/commands/credentials/credentials_command.rb:34:in `edit'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/command/base.rb:87:in `perform'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/command.rb:48:in `invoke'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<main>'
        from <internal:/Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /Users/mateuszdrewniak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**:
Rails 7.0.8

**Ruby version**:
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

**Comment by fatkodima** [comment]
This was fixed in https://github.com/rails/rails/pull/47107. 
@jonathanhefner Can you backport this to `7-0-stable`?

**Comment by rafaelfranca** [comment]
This patch is too big to backport to a stable version. Upgrading to 7.1 is the way to go. Thanks for the issue.
