### ISSUE TITLE
ArgumentError when using create_with().find_or_create_by() with an array of enum.

### ISSUE THREAD

**Issue by jean-francois-labbe** [rails/rails#49353]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :devices, force: true do |t|
  end

  create_table :alerts, force: true do |t|
    t.integer :device_id
    t.string :status
  end
end

class Device < ActiveRecord::Base
  has_many :alerts
end

class Alert < ActiveRecord::Base
  belongs_to :device
  enum status: { active: 'active', closed: 'closed', pending: 'pending' }
end

class BugTest < Minitest::Test
  def test_find_or_create_by_with_array_of_enum
    device = Device.create!

    Alert.find_by(device: device, status: [:pending, :active]) # Working fine

    Alert.create_with(status: :pending).find_or_create_by(device: device, status: [:pending, :active])
  end

  def test_find_or_create_by_doesnt_take_create_with_into_account
    assert_equal Alert.create_with(status: :pending).find_or_create_by(device: Device.create!, status: :active), 'pending'
  end
end
```

Crashes with
```
Failure:
BugTest#test_find_or_create_by_doesnt_take_create_with_into_account [find_or_create_by_rails_issue.rb:51]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Alert id: 1, device_id: 1, status: "active">
+"pending"

Error:
BugTest#test_find_or_create_by_with_array_of_enum:
ArgumentError: '[:pending, :active]' is not a valid status
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/enum.rb:215:in `assert_valid_value'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activemodel/lib/active_model/attribute.rb:79:in `with_value_from_user'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activemodel/lib/active_model/attribute_set.rb:60:in `write_from_user'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/attribute_methods/write.rb:42:in `_write_attribute'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activemodel/lib/active_model/attribute_methods.rb:286:in `status='
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activemodel/lib/active_model/attribute_assignment.rb:49:in `public_send'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activemodel/lib/active_model/attribute_assignment.rb:49:in `_assign_attribute'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/attribute_assignment.rb:19:in `block in _assign_attributes'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/attribute_assignment.rb:11:in `each'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/attribute_assignment.rb:11:in `_assign_attributes'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activemodel/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/core.rb:431:in `initialize'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/inheritance.rb:76:in `new'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/inheritance.rb:76:in `new'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/persistence.rb:37:in `create'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation.rb:899:in `_create'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation.rb:103:in `block in create'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation.rb:914:in `_scoping'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation.rb:452:in `scoping'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation.rb:103:in `create'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation.rb:216:in `block in create_or_find_by'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:531:in `block in within_new_transaction'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:528:in `within_new_transaction'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/transactions.rb:212:in `transaction'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation/delegation.rb:122:in `public_send'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation/delegation.rb:122:in `block in method_missing'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation.rb:914:in `_scoping'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation.rb:452:in `scoping'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation/delegation.rb:122:in `method_missing'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation.rb:216:in `create_or_find_by'
    .gem/ruby/3.0.6/bundler/gems/rails-e6f09150a88c/activerecord/lib/active_record/relation.rb:176:in `find_or_create_by'
    find_or_create_by_rails_issue.rb:45:in `test_association_stuff'
```

### Expected behavior
When using `create_with(status: :pending)` followed by `find_or_create_by(device: device, status: [:pending, :active])` with an array of enum values I would expect the find to use the array of enum values and in case it needs to create a record it would use the value provided in `create_with`.

### Actual behavior
it crashes with `ArgumentError: '[:pending, :active]' is not a valid status`

What's surprising is that    ` Alert.find_by(device: device, status: [:pending, :active]) ` is Working fine

### System configuration
**Rails version**:  main@e6f0915

**Ruby version**: 3.0.6

**EDIT:**
Added `test_find_or_create_by_doesnt_take_create_with_into_account`

**Comment by alpaca-tc** [comment]
If find_or_create_by is used, the value of the argument passed is used to create the record.

```
Alert.create_with(status: :active).find_or_create_by(status: :pending).status #=> "pending"
```

If you use first_or_create, the value of create_with will be used, which is the behavior you expect.

```
Alert.create_with(status: :active).where(status: [:pending, :active]).first_or_create.status #=> "active"
```

**Comment by fatkodima** [comment]
> ### Expected behavior
> When using `create_with(status: :pending)` followed by `find_or_create_by(device: device, status: [:pending, :active])` with an array of enum values I would expect the find to use the array of enum values and in case it needs to create a record it would use the value provided in `create_with`.

For a chain of `create_with(attributes1)` followed by `find_or_create_by(attributes2)`, I would expect that when the record was not found, the new record is created with `attributes1.merge(attributes2)` attributes. So the behavior raised in this issue is correct for me.

**Comment by ghiculescu** [comment]
I'd expect `find_or_create_by` to take precedence `create_with`, since it gets called later. And that's what happening here. I'm going to close this as it's behaving as documented.
