### ISSUE TITLE
`PersistenceTest#test_persisted_returns_boolean` fails at 7-1-stable branch

### ISSUE THREAD

**Issue by yahonda** [rails/rails#49439]
Managed to reproduce this 7-1-stable branch CI failure.

https://buildkite.com/rails/rails/builds/100265#018ae40b-9424-4772-a311-3263c2230ec4/1192-1203

This issue only reports the first error while there is 11 failures and 25 errors https://buildkite.com/rails/rails/builds/100265#018ae40b-9424-4772-a311-3263c2230ec4/1192-2016 because the first error may be causing all following errors/failures.

### Steps to reproduce

```ruby
git clone https://github.com/rails/rails
cd rails
git checkout 7-1-stable
bundle update sdoc --conservative # or `rm Gemfile.lock ; bundle install`
cd activerecord
ARCONN=postgresql bundle exec ruby -Itest:lib -e 'require "./test/cases/active_record_test.rb" ; require "./test/cases/relation/merging_test.rb" ; require "./test/cases/persistence_test.rb"' -- --seed 63051  -n "/^(?:ActiveRecordTest#(?:test_.disconnect_all\!_closes_all_connections)|RelationMergingTest#(?:test_merging_reorders_bind_params)|PersistenceTest#(?:test_persisted_returns_boolean))$/"
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ ARCONN=postgresql bundle exec ruby -Itest:lib -e 'require "./test/cases/active_record_test.rb" ; require "./test/cases/relation/merging_test.rb" ; require "./test/cases/persistence_test.rb"' -- --seed 63051  -n "/^(?:ActiveRecordTest#(?:test_.disconnect_all\!_closes_all_connections)|RelationMergingTest#(?:test_merging_reorders_bind_params)|PersistenceTest#(?:test_persisted_returns_boolean))$/"
Using postgresql
Run options: --seed 63051 -n "/^(?:ActiveRecordTest#(?:test_.disconnect_all\\!_closes_all_connections)|RelationMergingTest#(?:test_merging_reorders_bind_params)|PersistenceTest#(?:test_persisted_returns_boolean))$/"

# Running:

..E

Error:
PersistenceTest#test_persisted_returns_boolean:
ActiveRecord::RecordInvalid: Validation failed: Salary is not included in the list
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/validations.rb:84:in `raise_validation_error'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/validations.rb:55:in `save!'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:313:in `block in save!'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:531:in `block in within_new_transaction'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `handle_interrupt'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `block in synchronize'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:528:in `within_new_transaction'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:313:in `save!'
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/suppressor.rb:56:in `save!'
    /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/persistence_test.rb:1301:in `test_persisted_returns_boolean'


bin/rails test /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/persistence_test.rb:1298



Finished in 0.151615s, 19.7869 runs/s, 32.9782 assertions/s.
3 runs, 5 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**: `7-1-stable`, it does not reproduce at `main`

**Ruby version**: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]

**Comment by yahonda** [comment]
Confirmed that backporting  https://github.com/rails/rails/pull/49378 to the `7-1-stable` branch by `git cherry-pick -m 1 0d0e6bd` addresses all of errros/failures at https://buildkite.com/rails/rails/builds/100265#018ae40b-9424-4772-a311-3263c2230ec4

**Comment by andyatkinson** [comment]
Hello. I started the process of reproducing the failure using your steps. I ran into an issue with bundling the `mysql` gem because I don't have MySQL installed at all. I'm not sure whether it's required for rails/rails or not. I did `brew install mysql` on macOS and now I get past that step. This is more of an FYI as it seems unrelated to your PR. Maybe this is part of some general steps or ones I can submit to some general steps for reproducing issues.

I'll carry on with the rest now!

**Comment by andyatkinson** [comment]
I also manually created the databases needed for the test:

```sh
psql # connected as superuser
create database activerecord_unittest;
create database activerecord_unittest2;
```

With those created, running the last step in your list reproduces the same error on my machine:

```rb
# Running:

..E

Error:
PersistenceTest#test_persisted_returns_boolean:
ActiveRecord::RecordInvalid: Validation failed: Salary is not included in the list
    /Users/andy/Projects/rails/activerecord/lib/active_record/validations.rb:84:in `raise_validation_error'
```

**Comment by skipkayhil** [comment]
@andyatkinson there's a guide for these things here: https://edgeguides.rubyonrails.org/development_dependencies_install.html

Is there someone where we could link this that would have helped you find it?

**Comment by andyatkinson** [comment]
Thanks. The guide covers it well including macOS and MySQL dependencies.

**Comment by rafaelfranca** [comment]
Pro tip: If you use vscode, use the devcontainer in the repository to develop Rails. I'll document this later.

**Comment by rafaelfranca** [comment]
@byroot can you take a look?

**Comment by casperisfine** [comment]
Ok, so the validation error is an inclusion:

```
#<ActiveModel::Errors [#<ActiveModel::Error attribute=salary, type=inclusion, options={:value=>"70000"}>]>
```

`Developer` has `validates_inclusion_of :salary, in: 50000..200000`.

Looking into `InclusionValidator#validate_each`, the value isn't casted yet. It's `"70000" (String)`, not `70000 (Integer)`.

So I suspect the adapter type map isn't properly registered, which likely explains why backporting https://github.com/rails/rails/pull/49378 fixes it.

I'm not sure we should backport such a change this late though, so I'll see if I can figure a more localized fix.

**Comment by casperisfine** [comment]
Interestingly, the following diff fixes it:

```diff
diff --git a/activerecord/test/cases/active_record_test.rb b/activerecord/test/cases/active_record_test.rb
index 5d569f56d0..aaf4570757 100644
--- a/activerecord/test/cases/active_record_test.rb
+++ b/activerecord/test/cases/active_record_test.rb
@@ -4,6 +4,8 @@
 require "rack"
 
 class ActiveRecordTest < ActiveRecord::TestCase
+  fixtures :developers
+
   unless in_memory_db?
     test ".disconnect_all! closes all connections" do
       ActiveRecord::Base.connection.active?
```

It's not quite clear to me yet which parts of the fixtures setup/teardown steps is important, but it's an interesting insight.

**Comment by casperisfine** [comment]
Using the following debug:

```diff
diff --git a/activerecord/test/cases/persistence_test.rb b/activerecord/test/cases/persistence_test.rb
index 3512480409..f0202948e9 100644
--- a/activerecord/test/cases/persistence_test.rb
+++ b/activerecord/test/cases/persistence_test.rb
@@ -1296,6 +1296,8 @@ def test_destroyed_returns_boolean
   end
 
   def test_persisted_returns_boolean
+    pp Developer._default_attributes["salary"]
+
     developer = Developer.new(name: "Jose")
     assert_equal false, developer.persisted?
     developer.save!
```

standalone:

```
#<ActiveModel::Attribute::FromDatabase:0x00000001107dad78 @name="salary", @original_attribute=nil, @type=#<ActiveModel::Type::Integer:0x00000001060f84d8 @limit=4, @precision=nil, @range=-2147483648...2147483648, @scale=nil>, @value_before_type_cast="70000">
```

repro:

```
#<ActiveModel::Attribute::FromDatabase:0x000000010a1c9520 @name="salary", @original_attribute=nil, @type=#<ActiveModel::Type::Value:0x0000000109859968 @limit=nil, @precision=nil, @scale=nil>, @value_before_type_cast="70000">
```

So the root cause seem to be that the schema isn't loaded or something like that. I'll keep going deeper.

**Comment by casperisfine** [comment]
I have a fix here: https://github.com/rails/rails/pull/49451
