### ISSUE TITLE
Using config gem and with_options crashed on 7.1.0.rc1

### ISSUE THREAD

**Issue by euglena1215** [rails/rails#49457]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", tag: "v7.1.0.rc1"
  # gem "rails", github: "rails/rails", tag: "v7.1.0.beta1" # It works
  gem "sqlite3"
  gem "config"
end

require "active_record"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  with_options if: -> { true } do
    validates :foo, presence: true
    validate :something_validation
  end
end

```

### Expected behavior

Complete loading without crashing.

<details><summary>Execution result in v7.1.0.beta1</summary>

```shell
% ruby reproduce.rb
Fetching https://github.com/rails/rails.git
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
-- create_table(:posts, {:force=>true})
D, [2023-10-02T22:45:26.402083 #92115] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "posts"
D, [2023-10-02T22:45:26.402355 #92115] DEBUG -- :    (0.2ms)  CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)
   -> 0.0089s
D, [2023-10-02T22:45:26.402963 #92115] DEBUG -- :    (0.0ms)  CREATE TABLE "schema_migrations" ("version" varchar NOT NULL PRIMARY KEY)
D, [2023-10-02T22:45:26.403759 #92115] DEBUG -- :    (0.0ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
D, [2023-10-02T22:45:26.415922 #92115] DEBUG -- :   ActiveRecord::InternalMetadata Load (1.7ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
D, [2023-10-02T22:45:26.416117 #92115] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.0ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES ('environment', 'development', '2023-10-02 13:45:26.415971', '2023-10-02 13:45:26.415973')
```

</details> 

### Actual behavior

raises ArgumentError

```
% ruby reproduce.rb
Fetching https://github.com/rails/rails.git
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
-- create_table(:posts, {:force=>true})
D, [2023-10-02T22:42:04.623135 #91869] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "posts"
D, [2023-10-02T22:42:04.623333 #91869] DEBUG -- :    (0.1ms)  CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)
   -> 0.0070s
D, [2023-10-02T22:42:04.624177 #91869] DEBUG -- :    (0.1ms)  CREATE TABLE "schema_migrations" ("version" varchar NOT NULL PRIMARY KEY)
D, [2023-10-02T22:42:04.625161 #91869] DEBUG -- :    (0.0ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
D, [2023-10-02T22:42:04.636874 #91869] DEBUG -- :   ActiveRecord::InternalMetadata Load (1.1ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
D, [2023-10-02T22:42:04.637118 #91869] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.0ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES ('environment', 'development', '2023-10-02 13:42:04.636924', '2023-10-02 13:42:04.636926') RETURNING "key"
/Users/me/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-bf460ba277b7/activemodel/lib/active_model/validations.rb:177:in `block in validate': Unknown key: :presence. Valid keys are: :on, :if, :unless, :prepend. Perhaps you meant to call `validates` instead of `validate`? (ArgumentError)

              raise ArgumentError.new("Unknown key: #{k.inspect}. Valid keys are: #{VALID_OPTIONS_FOR_VALIDATE.map(&:inspect).join(', ')}. Perhaps you meant to call `validates` instead of `validate`?")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /Users/me/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-bf460ba277b7/activemodel/lib/active_model/validations.rb:175:in `each_key'
	from /Users/me/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-bf460ba277b7/activemodel/lib/active_model/validations.rb:175:in `validate'
	from /Users/me/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-bf460ba277b7/activesupport/lib/active_support/option_merger.rb:28:in `method_missing'
	from reproduce.rb:31:in `block in <class:Post>'
	from /Users/me/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-bf460ba277b7/activesupport/lib/active_support/core_ext/object/with_options.rb:96:in `instance_eval'
	from /Users/me/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-bf460ba277b7/activesupport/lib/active_support/core_ext/object/with_options.rb:96:in `with_options'
	from reproduce.rb:29:in `<class:Post>'
	from reproduce.rb:28:in `<main>'
```

### System configuration
**Rails version**: `v7.1.0.rc1`

**Ruby version**: `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin21]`

**Comment by euglena1215** [comment]
I am not sure if this bug is caused by Rails or the config gem.

**Comment by euglena1215** [comment]
@fatkodima 
Thank you!
I'll open this issue in the `config` gem after I check it too.

**Comment by jonathanhefner** [comment]
I opened https://github.com/rubyconfig/config/pull/342 to address this.  Since it is a third-party issue, I will go ahead and close.  Thank you for the bug report, @euglena1215!  And thank you for investigating, @fatkodima! :raised_hands:
