### ISSUE TITLE
Rails 7.1.0rc2 NoMethodError: undefined method `-' in active_record/validations/uniqueness.rb:90

### ISSUE THREAD

**Issue by hatai** [rails/rails#49481]
### Steps to reproduce

An NoMethodError occurred when trying to save data in the following table.
This error seems to be a problem in [active_record/validations/uniqueness.rb:90](https://github.com/rails/rails/blame/536d1680a1e79ca9e6cb95de7d914f762cac5b7e/activerecord/lib/active_record/validations/uniqueness.rb#L90)

- schema.rb 

```ruby:schema.rb
 create_table "branches", id: :serial, force: :cascade do |t|
    t.integer "account_id", null: false
    t.string "name", null: false
    t.string "display_name", null: false
    t.uuid "uuid", default: -> { "uuid_generate_v4()" }, null: false
	...
    t.datetime "deleted_at", precision: nil
    t.index "account_id, display_name, COALESCE(deleted_at, 'infinity'::timestamp without time zone)", name: "index_branch_display_name_unique", unique: true
  end
```

- Error log

```sh
NoMethodError:
       undefined method `-' for "account_id, display_name, COALESCE(deleted_at, 'infinity'::timestamp without time zone)":String
       Did you mean?  -@

# ./app/controllers/admin/branches_controller.rb:194:in `block in create'
# ./app/controllers/admin/branches_controller.rb:179:in `create'
```

- Backtrace

```sh
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/validations/uniqueness.rb:90:in `block (2 levels) in covered_by_unique_index?'
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/validations/uniqueness.rb:87:in `any?'
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/validations/uniqueness.rb:87:in `block in covered_by_unique_index?'
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/validations/uniqueness.rb:83:in `select'
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/validations/uniqueness.rb:83:in `covered_by_unique_index?'
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/validations/uniqueness.rb:79:in `validation_needed?'
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/validations/uniqueness.rb:23:in `validate_each'
/vendor/bundle/ruby/3.0.0/gems/globalize-6.2.1/lib/patches/active_record/rails6_1/uniqueness_validator.rb:38:in `validate_each'
/vendor/bundle/ruby/3.0.0/gems/enumerize-2.5.0/lib/enumerize/hooks/uniqueness.rb:16:in `validate_each'
/vendor/bundle/ruby/3.0.0/gems/activemodel-7.1.0.rc2/lib/active_model/validator.rb:155:in `block in validate'
/vendor/bundle/ruby/3.0.0/gems/activemodel-7.1.0.rc2/lib/active_model/validator.rb:151:in `each'
/vendor/bundle/ruby/3.0.0/gems/activemodel-7.1.0.rc2/lib/active_model/validator.rb:151:in `validate'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:706:in `catch'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:706:in `block in default_terminator'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:203:in `block in halting'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:598:in `block in invoke_before'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:598:in `each'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:598:in `invoke_before'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:109:in `run_callbacks'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:952:in `_run_validate_callbacks'
/vendor/bundle/ruby/3.0.0/gems/activemodel-7.1.0.rc2/lib/active_model/validations.rb:441:in `run_validations!'
/vendor/bundle/ruby/3.0.0/gems/activemodel-7.1.0.rc2/lib/active_model/validations/callbacks.rb:115:in `block in run_validations!'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:110:in `run_callbacks'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:952:in `_run_validation_callbacks'
/vendor/bundle/ruby/3.0.0/gems/activemodel-7.1.0.rc2/lib/active_model/validations/callbacks.rb:115:in `run_validations!'
/vendor/bundle/ruby/3.0.0/gems/activemodel-7.1.0.rc2/lib/active_model/validations.rb:366:in `valid?'
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/validations.rb:72:in `valid?'
/app/controllers/admin/branches_controller.rb:194:in `block in create'
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/connection_adapters/abstract/transaction.rb:531:in `block in within_new_transaction'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `handle_interrupt'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `block in synchronize'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/connection_adapters/abstract/transaction.rb:528:in `within_new_transaction'
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/transactions.rb:212:in `transaction'
/app/controllers/admin/branches_controller.rb:179:in `create'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/abstract_controller/base.rb:224:in `process_action'
/vendor/bundle/ruby/3.0.0/gems/ddtrace-0.53.0/lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb:127:in `process_action'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/action_controller/metal/rendering.rb:165:in `process_action'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/abstract_controller/callbacks.rb:259:in `block in process_action'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/vendor/bundle/ruby/3.0.0/gems/active_decorator-1.4.1/lib/active_decorator/view_context.rb:37:in `block (3 levels) in <module:Filter>'
/vendor/bundle/ruby/3.0.0/gems/active_decorator-1.4.1/lib/active_decorator/view_context.rb:25:in `run_with'
/vendor/bundle/ruby/3.0.0/gems/active_decorator-1.4.1/lib/active_decorator/view_context.rb:36:in `block (2 levels) in <module:Filter>'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:130:in `instance_exec'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/vendor/bundle/ruby/3.0.0/gems/sentry-rails-5.11.0/lib/sentry/rails/controller_transaction.rb:28:in `block in sentry_around_action'
/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-5.11.0/lib/sentry/hub.rb:102:in `with_child_span'
/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-5.11.0/lib/sentry-ruby.rb:456:in `with_child_span'
/vendor/bundle/ruby/3.0.0/gems/sentry-rails-5.11.0/lib/sentry/rails/controller_transaction.rb:14:in `sentry_around_action'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/callbacks.rb:141:in `run_callbacks'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/abstract_controller/callbacks.rb:258:in `process_action'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/action_controller/metal/rescue.rb:25:in `process_action'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/notifications.rb:206:in `block in instrument'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/notifications.rb:206:in `instrument'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/action_controller/metal/instrumentation.rb:73:in `process_action'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
/vendor/bundle/ruby/3.0.0/gems/activerecord-7.1.0.rc2/lib/active_record/railties/controller_runtime.rb:32:in `process_action'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/abstract_controller/base.rb:160:in `process'
/vendor/bundle/ruby/3.0.0/gems/actionview-7.1.0.rc2/lib/action_view/rendering.rb:40:in `process'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/action_controller/metal.rb:227:in `dispatch'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/action_controller/test_case.rb:611:in `block in process_controller_response'
/vendor/bundle/ruby/3.0.0/gems/activesupport-7.1.0.rc2/lib/active_support/execution_wrapper.rb:92:in `wrap'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/action_controller/test_case.rb:601:in `wrap_execution'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/action_controller/test_case.rb:611:in `process_controller_response'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/action_controller/test_case.rb:521:in `process'
/vendor/bundle/ruby/3.0.0/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/template_assertions.rb:62:in `process'
/vendor/bundle/ruby/3.0.0/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:35:in `block in process'
/vendor/bundle/ruby/3.0.0/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:104:in `catch'
/vendor/bundle/ruby/3.0.0/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:104:in `_catch_warden'
/vendor/bundle/ruby/3.0.0/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:35:in `process'
/vendor/bundle/ruby/3.0.0/gems/actionpack-7.1.0.rc2/lib/action_controller/test_case.rb:422:in `post'
/vendor/bundle/ruby/3.0.0/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/integration.rb:16:in `block (2 levels) in <module:Integration>'
/spec/controllers/admin/branches_controller_spec.rb:43:in `block (3 levels) in <top (required)>'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:263:in `instance_exec'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:263:in `block in run'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `block in run'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
/vendor/bundle/ruby/3.0.0/gems/rspec-rails-6.0.3/lib/rspec/rails/example/controller_example_group.rb:192:in `block (2 levels) in <module:ControllerExampleGroup>'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
/vendor/bundle/ruby/3.0.0/gems/rspec-rails-6.0.3/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
/spec/rails_helper.rb:249:in `block (2 levels) in <top (required)>'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
/vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.12.3/lib/rspec/expectations/failure_aggregator.rb:25:in `block in aggregate'
/vendor/bundle/ruby/3.0.0/gems/rspec-support-3.12.1/lib/rspec/support.rb:124:in `with_failure_notifier'
/vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.12.3/lib/rspec/expectations/failure_aggregator.rb:23:in `aggregate'
/vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.12.3/lib/rspec/matchers.rb:306:in `aggregate_failures'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2253:in `block in define_built_in_hooks'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `run'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:259:in `run'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:646:in `block in run_examples'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `map'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `run_examples'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:607:in `run'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `block in run'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `map'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `run'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `map'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in `report'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:115:in `run_specs'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in `run'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/exe/rspec:4:in `<top (required)>'
/vendor/bundle/ruby/3.0.0/bin/rspec:25:in `load'
/vendor/bundle/ruby/3.0.0/bin/rspec:25:in `<main>'
```

### System configuration
**Rails version**: 7.1.0.rc2

**Ruby version**: 3.0.5

**Comment by skipkayhil** [comment]
looks like c2bdc6b0c2d160254f0db7d705a697336aca388a cc @fatkodima

**Comment by fatkodima** [comment]
Thanks, taking look at it.
