### ISSUE TITLE
ArgumentError: wrong number of arguments (given 3, expected 2) when execute down migration of `rename_table`

### ISSUE THREAD

**Issue by sue445** [rails/rails#49523]
Down migration  (e.g. `./bin/rails db:rollback`) of `rename_table` fails when version less than 7.1 is specified in migration file

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "7.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :things, force: true do |t|
    t.text "content"
  end
end

class RenameThings < ActiveRecord::Migration[7.0]
  def change
    rename_table "things", "awesome_things"
  end
end

class BugTest < Minitest::Test
  def test_migration_down
    RenameThings.migrate(:up)
    RenameThings.migrate(:down)
  end
end
```

### Expected behavior
no error ( down migration is successful)

### Actual behavior
```
==  RenameThings: reverting ===================================================
E

Finished in 0.002283s, 438.0201 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_migration_down:
ArgumentError: wrong number of arguments (given 3, expected 2)
    /Users/sue445/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/migration/compatibility.rb:105:in `rename_table'
    /Users/sue445/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/migration/command_recorder.rb:146:in `block in replay'
    /Users/sue445/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/migration/command_recorder.rb:145:in `each'
    /Users/sue445/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/migration/command_recorder.rb:145:in `replay'
    /Users/sue445/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/migration.rb:855:in `revert'
    /Users/sue445/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/migration.rb:980:in `exec_migration'
    /Users/sue445/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/migration.rb:966:in `block (2 levels) in migrate'
    /Users/sue445/.rbenv/versions/3.2.2/lib/ruby/3.2.0/benchmark.rb:296:in `measure'
    /Users/sue445/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/migration.rb:965:in `block in migrate'
    /Users/sue445/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:229:in `with_connection'
    /Users/sue445/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/migration.rb:964:in `migrate'
    /Users/sue445/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/migration.rb:738:in `migrate'
    scripts/active_record_migrations_gem.rb:38:in `test_migration_down'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration
**Rails version**: 7.1.0

**Ruby version**: 3.1.2

### Workarround
We can avoid this by one of the following

#### 1. Use `ActiveRecord::Migration[7.1]`
e.g.

```ruby
class RenameThings < ActiveRecord::Migration[7.1]
  def change
    rename_table "things", "awesome_things"
  end
end
```

####  2.  Use `def self.change`
e.g.

```ruby
class RenameThings < ActiveRecord::Migration[7.0]
  def self.change
    rename_table "things", "awesome_things"
  end
end
```

**Comment by ghiculescu** [comment]
Looks like it’s related to https://github.com/rails/rails/pull/45136 cc @fatkodima

**Comment by skipkayhil** [comment]
Is this something that used to work but is now failing or something that never worked? I tried bisecting but I haven't found a commit where the test passes yet

**Comment by fatkodima** [comment]
Thanks for mentioning, looking into this.
