### ISSUE TITLE
Rails 7.1.1 breaks Postgres < 10

### ISSUE THREAD

**Issue by ccutrer** [rails/rails#49591]
pg_attribute.attidentity was introduced in 10. See https://www.postgresql.org/docs/9.6/catalog-pg-attribute.html vs. https://www.postgresql.org/docs/10/catalog-pg-attribute.html. According to Rails docs at https://guides.rubyonrails.org/active_record_postgresql.html, back to 9.3 is supported.

End result when running against Postgres 9.6:

```
PG::UndefinedColumn: ERROR:  column a.attidentity does not exist
LINE 4:        a.attidentity AS identity,
               ^
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `block (2 levels) in query'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:1024:in `block in with_raw_connection'
/usr/local/bundle/gems/activesupport-7.1.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:996:in `with_raw_connection'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:18:in `block in query'
/usr/local/bundle/gems/activesupport-7.1.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/app/lib/switchman/sharded_instrumenter.rb:26:in `instrument'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:1134:in `log'
/app/lib/switchman/active_record/abstract_adapter.rb:39:in `log'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:17:in `query'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:1075:in `column_definitions'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:109:in `columns'
/app/lib/switchman/active_record/postgresql_adapter.rb:132:in `block in columns'
/app/lib/switchman/active_record/postgresql_adapter.rb:98:in `with_local_table_name'
/app/lib/switchman/active_record/postgresql_adapter.rb:132:in `columns'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:346:in `block in columns'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:345:in `fetch'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:345:in `columns'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:354:in `block in columns_hash'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:353:in `fetch'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:353:in `columns_hash'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:58:in `columns_hash'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:188:in `columns_hash'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/model_schema.rb:616:in `load_schema!'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/attributes.rb:264:in `load_schema!'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/encryption/encryptable_record.rb:127:in `load_schema!'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/model_schema.rb:561:in `block in load_schema'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/model_schema.rb:558:in `synchronize'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/model_schema.rb:558:in `load_schema'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/model_schema.rb:439:in `attribute_types'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/attribute_methods.rb:256:in `_has_attribute?'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/inheritance.rb:61:in `new'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/persistence.rb:54:in `create!'
```

**Comment by fatkodima** [comment]
Thanks for reporting! Sorry, that was caused by the change I introduced recently. I will look at it tomorrow if no one else already does.

**Comment by ghiculescu** [comment]
ref https://github.com/rails/rails/pull/49504

**Comment by zzak** [comment]
It was backported to 7-1-stable here it looks like:
1ebb12c5d3ae898202a3c21461b1aa84f3c84e61
