### ISSUE TITLE
Rails 7.1: incorrect path when submitting form for a singular resource

### ISSUE THREAD

**Issue by jp524** [rails/rails#49604]
### Steps to reproduce
When submitting a form with an error, Rails 7.1 redirects to incorrect path when the resource is singular.
This may be an issue with Turbo (see expected and actual behaviors below).

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 7.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :authors, force: true do |t|
    t.string :name
  end
end

class Author < ActiveRecord::Base
  validates :name,
            format: { with: /\A[a-zA-Z0-9-]{0,39}\z/, message: 'can only contain alphanumeric characters and dashes' },
            length: { maximum: 39 }
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    resource :author, only: %i[edit update]
  end
end

class AuthorsController < ActionController::Base
  include Rails.application.routes.url_helpers

  before_action :set_author, only: %i[edit update]

  def edit; end

  def update
    if @author.update(author_params)
      redirect_to edit_author_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_author
    @author = Author.find(1) # Actual application would use session to find author logged in
  end

  def author_params
    params.require(:author).permit(:name)
  end
end

class BugTest < Minitest::Test
  include Rack::Test::Methods

  Author.create!(name: 'name')

  def test_author_updated_success
    patch '/author', { author: { name: 'validName' } }
    assert_equal 'http://example.org/author/edit', last_response.headers['location']
  end

  def test_author_updated_failure
    patch '/author', { author: { name: 'invalid!!!name?' } }
    assert_equal 'http://example.org/author/edit', last_response.headers['location']
  end

  private

  def app
    Rails.application
  end
end
```

### Expected behavior
The request path should be `author/edit`.
The console in Rails 7.0.8 showed
```ruby
Started PATCH "/author" for 127.0.0.1 at 2023-10-12 09:22:13 -0400
Processing by AuthorsController#update as TURBO_STREAM
```

### Actual behavior
The request path is `author/#{author.id}”`.
The console in Rails 7.1.0 shows
```ruby
Started PATCH "/author.1" for 127.0.0.1 at 2023-10-12 09:21:10 -0400
Processing by AuthorsController#update as */*
```

### System configuration
**Rails version**: 7.1.0

**Ruby version**: 3.2.2

**Comment by jp524** [comment]
This issue only happens when specifying a singular resource in `config/routes.rb`, such as `resource :author`. This results in the following routes and actions:
```ruby
                                  Prefix Verb   URI Pattern                                                                                       Controller#Action
                              new_author GET    /author/new(.:format)                                                                             authors#new
                             edit_author GET    /author/edit(.:format)                                                                            authors#edit
                                  author GET    /author(.:format)                                                                                 authors#show
                                         PATCH  /author(.:format)                                                                                 authors#update
                                         PUT    /author(.:format)                                                                                 authors#update
                                         DELETE /author(.:format)                                                                                 authors#destroy
```
So the `edit_author_path` has a corresponding URI of `/author/edit(.:format)`. The params `:id` is not required.

**Comment by paulreece** [comment]
Thanks for clarifying!  

We still need your repro script updated to reproduce the error if possible.  

I changed my local app to the setup as singular resource and I get a  `PATCH` request to `/author.id` for each one, valid or invalid.

```Ruby
Started GET "/author/edit" for ::1 at 2023-10-12 15:02:25 -0400
Processing by AuthorsController#edit as HTML
  Author Load (0.2ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/authors_controller.rb:62:in `set_author'
  Rendering layout layouts/application.html.erb
  Rendering authors/edit.html.erb within layouts/application
  Rendered authors/_form.html.erb (Duration: 1.1ms | Allocations: 344)
  Rendered authors/edit.html.erb within layouts/application (Duration: 1.4ms | Allocations: 471)
  Rendered layout layouts/application.html.erb (Duration: 2.1ms | Allocations: 859)
Completed 200 OK in 4ms (Views: 2.6ms | ActiveRecord: 0.2ms | Allocations: 1823)

Started PATCH "/author.1" for ::1 at 2023-10-12 15:03:31 -0400
Processing by AuthorsController#update as */*
  Parameters: {"authenticity_token"=>"[FILTERED]", "author"=>{"name"=>"validName"}, "commit"=>"Update Author"}
  Author Load (0.7ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/authors_controller.rb:62:in `set_author'
  TRANSACTION (0.1ms)  BEGIN
  ↳ app/controllers/authors_controller.rb:23:in `update'
  Author Update (0.7ms)  UPDATE "authors" SET "name" = $1, "updated_at" = $2 WHERE "authors"."id" = $3  [["name", "validName"], ["updated_at", "2023-10-12 19:03:31.152743"], ["id", 1]]
  ↳ app/controllers/authors_controller.rb:23:in `update'
  TRANSACTION (0.9ms)  COMMIT
  ↳ app/controllers/authors_controller.rb:23:in `update'
Redirected to http://[::1]:3000/author/edit
Completed 302 Found in 6ms (ActiveRecord: 2.3ms | Allocations: 1864)


Started GET "/author/edit" for ::1 at 2023-10-12 15:03:31 -0400
Processing by AuthorsController#edit as HTML
  Author Load (0.5ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/authors_controller.rb:62:in `set_author'
  Rendering layout layouts/application.html.erb
  Rendering authors/edit.html.erb within layouts/application
  Rendered authors/_form.html.erb (Duration: 0.8ms | Allocations: 344)
  Rendered authors/edit.html.erb within layouts/application (Duration: 1.0ms | Allocations: 471)
  Rendered layout layouts/application.html.erb (Duration: 1.4ms | Allocations: 859)
Completed 200 OK in 4ms (Views: 1.7ms | ActiveRecord: 0.4ms | Allocations: 1823)


Started PATCH "/author.1" for ::1 at 2023-10-12 15:03:35 -0400
Processing by AuthorsController#update as */*
  Parameters: {"authenticity_token"=>"[FILTERED]", "author"=>{"name"=>"invalid!!!name?"}, "commit"=>"Update Author"}
  Author Load (0.5ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/authors_controller.rb:62:in `set_author'
  Rendering layout layouts/application.html.erb
  Rendering authors/edit.html.erb within layouts/application
  Rendered authors/_form.html.erb (Duration: 1.0ms | Allocations: 848)
  Rendered authors/edit.html.erb within layouts/application (Duration: 1.2ms | Allocations: 975)
  Rendered layout layouts/application.html.erb (Duration: 1.6ms | Allocations: 1359)
Completed 422 Unprocessable Entity in 6ms (Views: 1.9ms | ActiveRecord: 0.5ms | Allocations: 3355)
```

When I try the image name I'm temporarily on `/author.1` with a validation error.  As soon as I submit a valid name I'm back to `/author/edit`.  It doesn't seem like buggy behavior to me but rather intentional since underneath the hood Rails is sending a `PATCH` request to `/author.1`.

**Comment by jp524** [comment]
Thanks for taking the time to look at this!

I found a way around the issue by specifying a `url` in my form such as:
```ruby
<%= form_with(model: @author, url: '/author') do |form| %>
```
This ensures that the request is sent to the correct path.

I am not sure if the change was intentional or not under the hood, but up until Rails 7.0.8 the `PATCH` requests were sent to `/author`, as seen below:
```ruby
Started GET "/author/edit" for 127.0.0.1 at 2023-10-12 15:18:20 -0400
  ActiveRecord::SchemaMigration Pluck (0.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by AuthorsController#edit as HTML
  Author Load (0.2ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/authors_controller.rb:22:in `set_author'
  Rendering layout layouts/application.html.erb
  Rendering authors/edit.html.erb within layouts/application
  Rendered authors/edit.html.erb within layouts/application (Duration: 2.5ms | Allocations: 2525)
  Rendered layout layouts/application.html.erb (Duration: 19.2ms | Allocations: 37620)
Completed 200 OK in 29ms (Views: 20.5ms | ActiveRecord: 0.4ms | Allocations: 48913)


Started PATCH "/author" for 127.0.0.1 at 2023-10-12 15:18:41 -0400
Processing by AuthorsController#update as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "author"=>{"name"=>"validName"}, "commit"=>"Update Author"}
  Author Load (0.1ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/authors_controller.rb:22:in `set_author'
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/authors_controller.rb:10:in `update'
  Author Update (0.7ms)  UPDATE "authors" SET "name" = ?, "updated_at" = ? WHERE "authors"."id" = ?  [["name", "validName"], ["updated_at", "2023-10-12 19:18:41.572352"], ["id", 1]]
  ↳ app/controllers/authors_controller.rb:10:in `update'
  TRANSACTION (0.7ms)  commit transaction
  ↳ app/controllers/authors_controller.rb:10:in `update'
Redirected to http://localhost:3000/author/edit
Completed 302 Found in 8ms (ActiveRecord: 1.5ms | Allocations: 4357)


Started GET "/author/edit" for 127.0.0.1 at 2023-10-12 15:18:41 -0400
Processing by AuthorsController#edit as TURBO_STREAM
  Author Load (0.1ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/authors_controller.rb:22:in `set_author'
  Rendering layout layouts/application.html.erb
  Rendering authors/edit.html.erb within layouts/application
  Rendered authors/edit.html.erb within layouts/application (Duration: 0.8ms | Allocations: 917)
  Rendered layout layouts/application.html.erb (Duration: 2.7ms | Allocations: 3218)
Completed 200 OK in 4ms (Views: 3.0ms | ActiveRecord: 0.1ms | Allocations: 4034)


Started PATCH "/author" for 127.0.0.1 at 2023-10-12 15:19:02 -0400
Processing by AuthorsController#update as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "author"=>{"name"=>"invalid!!!name?"}, "commit"=>"Update Author"}
  Author Load (0.2ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/authors_controller.rb:22:in `set_author'
  Rendering layout layouts/application.html.erb
  Rendering authors/edit.html.erb within layouts/application
  Rendered authors/edit.html.erb within layouts/application (Duration: 2.1ms | Allocations: 1135)
  Rendered layout layouts/application.html.erb (Duration: 6.5ms | Allocations: 3320)
Completed 422 Unprocessable Entity in 12ms (Views: 7.3ms | ActiveRecord: 0.2ms | Allocations: 5303)
```

**Comment by paulreece** [comment]
So this is definitely intentional after researching it more.

They changed the SQL statements here which suggests to me this is intentional:
https://github.com/rails/rails/commit/6444ec0d307b4c0e599bb7b26dc29aa300097191

I'll see if I can find the PR that introduced the change a bit later unless someone else jumps in who already knows when this behavior changed.

**Comment by jvillarejo** [comment]
I think I found the problem. 

I tested and here is the behaviour with single resource on the `form_with` in `lib/action_view/helpers/form_helper.rb`

**On 7.1:**
https://github.com/rails/rails/blob/7-1-stable/actionview/lib/action_view/helpers/form_helper.rb#L761

Here the`form_with` uses the `polymporphic_path(model, {})`
```ruby
(ruby) polymorphic_path(model, {})
"/author.1"
```

If I use here on `7.1` the method `polymorphic_path(model, format: format)` the correct path for single resource gets resolved `/author`

```ruby
(ruby) polymorphic_path(model, format: format)
"/author"
```

**On 7.0:**
https://github.com/rails/rails/blob/7-0-stable/actionview/lib/action_view/helpers/form_helper.rb#L760

Here the `form_with` uses the `polymorphic_path(model, format: format)` 
```ruby
(ruby) polymorphic_path(model, format: format)
"/author"
```

If I use here on `7.0` the method `polymorphic_path(model, {})`, the wrong path for sigle resource gets resolved `/author.1` 

```ruby
(ruby) polymorphic_path(model, {})
"/author.1"
```

---

I don't know much why this was changed on https://github.com/rails/rails/pull/43766/
If someone (maybe @jhawthorn or @cryptoque ) can guide me to the right solution I can implement a PR to fix it.

**Comment by paulreece** [comment]
@jvillarejo Nice detective work here!!

After reading #43766 they did this so that it Rails would still render forms even with a `nil` value for format.  

A maintainer will need to chime in on whether adding the `.id` to the end of the url is actually an intentional change.

However the current fix to the problem would be to pass in a `format: :hmtl` option to the `form_with` method in the `_form` partial of your views:
```Ruby
<%= form_with(model: author, format: :html) do |form| %>
```

**Comment by matthewd** [comment]
> They changed the SQL statements here which suggests to me this is intentional: 6444ec0d307b4c0e599bb7b26dc29aa300097191

@paulreece I don't see how that change is related, let alone implying intention?

> A maintainer will need to chime in on whether adding the .id to the end of the url is actually an intentional change.

No, it's clearly a bug for an id value to end up in the format part of a URL. That said, tbh I'm slightly more surprised that the format-explicit cases _are_ working. I guess they might still have a dangling id value, and it's just running out of places to go?

**Comment by paulreece** [comment]
@matthewd thanks for clarifying about the intentionality of this bug.

>@paulreece I don't see how that change is related, let alone implying intention?

This was in reference to the methods using different SQL queries which  I initially thought was related to the routes bug here.  I apologize for the confusion.

**Comment by jvillarejo** [comment]
> A maintainer will need to chime in on whether adding the .id to the end of the url is actually an intentional change.

There wasn't any intention to change how the paths were resoved.
 
As @matthewd said. This is clearly a bug. The `/author.1` is the wrong path for a single resource configuration.
I will try to research `polymorphic_url` today. 

I was going to upgrade my application to `7.1`, but I have some single resources configured. So I want to fix it.

**Comment by paulreece** [comment]
>As @matthewd said. This is clearly a bug. The /author.1 is the wrong path for a single resource configuration.
I will try to research polymorphic_url today.

Yes, I thought I clarified that in my comment above after he chimed in?

>I was going to upgrade my application to 7.1, but I have some single resources configured. So I want to fix it.

Great! Thanks for taking the time to look into this.

**Comment by jhawthorn** [comment]
This behaviour is really unfortunate. It seems like this is a pre-existing bug based on `polymorphic_path(@author)` having the undesirable behaviour on 7.0 (at least, likely further back), so I don't think we should patch over it by reverting `form_for`/`form_with` changes, but we should find some way to fix it properly.

For those encountering this problem, would using [`resolve` in routes.rb](https://guides.rubyonrails.org/routing.html#using-resolve) help? For example in the reproduction given, we can get the desired behaviour by specifying:

```
resolve("Author") { [:author] }
```

Knowing whether this workaround works would help inform possible paths forward.

Ultimately this is a bit awkward because we're specifying a model for polymorphic_path to use. polymorphic_path has no knowledge of how its route helper is defined (ie. that it is a singular resource) and assumes it should always be passed the id for that object (which singular resource routes do not expect). Passing `format: nil` (which we previously did implicitly) hid this bug by overriding the passed argument (which probably should be a warning or something).


IMO the correct way to get this route should be `polymorphic_path(:author)` not `polymorphic_path(@author)` (so in this example specifying `url: author_path` or `url: :author`), but the behaviour is really surprising and ideally we could make polymorphic_path smarter and have both generate the same path.

**Comment by jvillarejo** [comment]
Hey @jhawthorn ! Thanks for your guidelines. 

Yes, yesterday I was researching a little bit more, and thought that the best way to fix this was to fix the method `polymorphic_path`. The `form_for` / `form_with` just manifest the bug and should not be responsible for it. 

I will try to check the `resolve` as you suggested today and come up with results.  Thanks!

**Comment by jp524** [comment]
Thank you @jhawthorn! Using `resolve` works on my end.

**Comment by jvillarejo** [comment]
Hey @jhawthorn `resolve` works perfectly fine. 
Also the documentation states that it is necessary for `form_with` to work with the `model`

https://guides.rubyonrails.org/routing.html#singular-resources

> The call to resolve is necessary for converting instances of the Geocoder to routes through [record identification](https://guides.rubyonrails.org/form_helpers.html#relying-on-record-identification). 

So technically this is not a bug, it's not expected to work without the `resolve`

I wonder if there is an improvement that can be made here. 
I've looked into the code and I couldn't find any way to check if the resource mapping is `singleton?`
Would be a problem that `resource` method in `mapper.rb` internally calls the `resolve` ? So it is set by default ?

Something like:
```ruby
def resource(*resources, &block)
  # ...
  cloned_resources = resources.clone
  named_resource = cloned_resources.last.to_s.titleize
  resolve(named_resource) { cloned_resources }

  with_scope_level(:resource) do
    # ...
  end
```
 
I tested and if in the routes the resolve for the same name is called again it gets overrided. 
I can write a PR for this change.

**Comment by eizengan** [comment]
Adding a problem to the mix: nested singular resources are currently broken and cannot benefit from a fix via `resolve`. To illustrate, consider

```ruby
# config/routes.rb
resources :users do
  resource :contact_info
end

# somewhere_else.rb
form_for([@user, @contact_info])
```

`form_for` now renders a form which sends a PATCH to e.g. `users/1/contact_info.1` instead of `users/1/contact_info`, but `resolve` is not applicable ([ref](https://api.rubyonrails.org/v7.1.1/classes/ActionDispatch/Routing/Mapper/CustomUrls.html#method-i-resolve))

> NOTE: This custom behavior only applies to simple polymorphic URLs where a single model instance is passed and not more complicated forms
> ...
> NOTE: The resolve method can’t be used inside of a scope block such as namespace or scope and will raise an error if it detects that it is.

**Comment by paulreece** [comment]
Thanks for your input.  My PR doesn't use resources.  I tested your use case and it works fine in my suggested fix linked in the above PR.

```Ruby
Started PATCH "/posts/1/author" for 127.0.0.1 at 2023-10-26 15:29:05 -0400
Processing by AuthorsController#update as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "author"=>{"name"=>"validName"}, "commit"=>"Update Author", "post_id"=>"1"}
  Author Load (1.6ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/authors_controller.rb:67:in `set_author'
Redirected to http://127.0.0.1:3000/posts/1/author/edit
Completed 302 Found in 15ms (ActiveRecord: 1.6ms | Allocations: 1049)


Started GET "/posts/1/author/edit" for 127.0.0.1 at 2023-10-26 15:29:05 -0400
Processing by AuthorsController#edit as TURBO_STREAM
  Parameters: {"post_id"=>"1"}
  Author Load (0.3ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/authors_controller.rb:67:in `set_author'
  Rendering layout layouts/application.html.erb
  Rendering authors/edit.html.erb within layouts/application
  Post Load (0.2ms)  SELECT "posts".* FROM "posts" WHERE "posts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/views/authors/edit.html.erb:3
  Rendered authors/_form.html.erb (Duration: 1.3ms | Allocations: 355)
  Rendered authors/edit.html.erb within layouts/application (Duration: 2.8ms | Allocations: 916)
  Rendered layout layouts/application.html.erb (Duration: 3.5ms | Allocations: 1303)
Completed 200 OK in 6ms (Views: 3.9ms | ActiveRecord: 0.6ms | Allocations: 2278)
```

**Comment by paulreece** [comment]
So I was informed by Rafael that my implementation was not a viable solution.  So anyone can feel free to open other PRs to fix this!  I'll try again as well, time permitting.

**Comment by eizengan** [comment]
> Thanks for your input. My PR doesn't use resources. I tested your use case and it works fine in my suggested fix linked in the above PR.

Understood, but there appear to be two competing philosophies here:

- treat as a regression in `polymorphic_path`
- treat as a side effect of failing to use `resolve` when necessary/appropriate, now exposed by enhancements to underlying infrastructure

My comment regarding there being no working path for nested singular resources is aimed at fixes adhering to the latter, not the former

**Comment by jvillarejo** [comment]
> treat as a side effect of failing to use resolve when necessary/appropriate, now exposed by enhancements to underlying infrastructure

I think it's better to treat it as a side-effect for not using `resolve`. 

That's why I asked if it would be correct to change the current convention and that `resource ...` internally sets the `resolve` . 
If that approach would be correct I can try to do a PR for it.

**Comment by eizengan** [comment]
> That's why I asked if it would be correct to change the current convention and that resource ... internally sets the `resolve`

I don't have the context to say whether that's the best approach, but In that case to restore parity with pre-7.1 behavior we would also need to make `resolve` to work with nested singular resources. Given that this is specifically called out in the docs (the notes on my [earlier comment](https://github.com/rails/rails/issues/49604#issuecomment-1781581023)) I suspect that could be a nontrivial enhancement

**Comment by paulreece** [comment]
I don't currently have a fix but another current workaround is to specify the `format` in your form:
```Ruby
<%= form_with(model: author, format: html) do |form| %>
```

**Comment by eizengan** [comment]
> I don't currently have a fix but another current workaround is to specify the `format` in your form:
> 
> ```ruby
> <%= form_with(model: author, format: html) do |form| %>
> ```

Setting the url keyword argument also suffices

**Comment by paulreece** [comment]
Thanks. That was noted earlier in the issue as well.

**Comment by paulreece** [comment]
So according to #41727 you're supposed to use `resolve` with singular resources:

https://guides.rubyonrails.org/routing.html#singular-resources

This means this isn't a bug and the convention now is for the user to provide the information to the framework using `resolve` in order for this to generate URLs properly. 
```markdown
        # If you want instances of a model to work with this resource via
        # record identification (eg. in +form_with+ or +redirect_to+), you
        # will need to call resolve[rdoc-ref:CustomUrls#resolve]:
        #
        #   resource :profile
        #   resolve('Profile') { [:profile] }
        #
        #   # Enables this to work with singular routes:
        #   form_with(model: @profile) {}
```

**Comment by eizengan** [comment]
Once again: resolve is _not a working solution for nested singular resources_. If it is intended to be our blessed-path solution, then this inadequacy should be addressed.

**Comment by paulreece** [comment]
Thank you @eizengan.

I've decided to open this back up for the time being given that the nested resources will not work with resolve.

As I noted above we do have it documented for how to use `resource` non-nested.  However having nested resources is a popular use case and I think adding support for this will be beneficial to the framework. 

I tested this locally.

`routes.rb`
both
```Ruby
  resources :posts do
    resource :author, resolve: { Author: [:author, :post] }
  end
```
and 
```Ruby
  resources :posts do
    resource :author
  end
  resolve("Author") { [:post, :author] }
```

Result in:
```Ruby
Started PATCH "/posts/1/author.1"
```

My PR #49889 addresses both use cases.

**Comment by eizengan** [comment]
> I've decided to open this back up for the time being given that the nested resources will not work with resolve.

I could open an issue specific to this particular edge case, alternatively. If that's preferable, just let me know!

**Comment by pixeltrix** [comment]
@eizengan it's a bit ugly but you can work around the top level limitation like this:

Your example:
```
# config/routes.rb
resources :users do
  resource :contact_info
end

# somewhere_else.rb
form_for([@user, @contact_info])
```

Workaround:
```
# config/routes.rb
resources :users
resource :contact_info, path: "/users/:user_id/contact_info"
resolve("ContactInfo") { |ci| [:contact_info, { user_id: ci.user_id }] }

# somewhere_else.rb
form_for([@contact_info])
```

This will generate the desired url but pretty it is not 😄

**Comment by arjun810** [comment]
We're getting this issue without using a singular resource. We have:

patch :model, to: "model#create"

and form_for [model] generates a form url with the model at at the end. Worked on 7.0 as well.

**Comment by igillis-clara** [comment]
This would be a huge win for us -- is there still a plan to get [the PR](https://github.com/rails/rails/pull/49889) over the line?
