### ISSUE TITLE
Document for rails >= 7.1 how to run an application in a mounting point different to "/".   This will avoid duplication of the relative root path in routes helpers.

### ISSUE THREAD

**Issue by vtamara** [rails/rails#49688]
## Simple case

(1) An engine that has a route (let's say `articles_path` pointing to `/articles`) and
(2) an application mounted on a relative route (let's say `/a/`) that mounts the engine on that same route by a) using `config.relative_url_root="/a"` in `config/application.rb` as well as defining a `scope "/a"`  in `config/routes.rb` and mounting the engine on the same route.

In the application `articles_path` will be `/a/a/articles` instead of `/a/articles` as it is with rails 7.0

### Steps to reproduce

1. With rails 7 generate part of the engine described at <https://edgeguides.rubyonrails.org/engines.html>:
    ```
    rails plugin new engine49688 --mountable
    cd engine49688
    bundle
    bin/rails generate scaffold article title:string text:text
    bin/rails db:migrate
    ```
   If you prefer you can clone this engine from this repository https://gitlab.com/vtamara/engine49688 or 
   check more details of how we generated it in the    [README.md](https://gitlab.com/vtamara/engine49688/-/blob/main/README.md)
3. With rails 7 generate part of the application described at <https://edgeguides.rubyonrails.org/engines.html>:
    ```sh
    cd ..
    rails new app49688 --minimal --skip-keeps
    cd app49688
    bundle add engine49688 --path=../engine49688
    bundle
    bin/rails engine49688:install:migrations
    bin/rails g scaffold user username:string name:string
    bin/rails db:migrate
    ```
   In this application make sure that the relative root is `/a` by 
   * Adding `config.relative_url_root = "/a/"` to `config/application.rb`
   * Using that route as main scope in `config/routes.rb` and to mount on it the engine, i.e the contents of the file is:
      ```ruby
      Rails.application.routes.draw do            
        scope "/a" do
          resources :users
        end
        mount Engine49688::Engine => "/a", as: :engine49688
      end
      ```
    And create the test `test/controllers/routes_test.rb` with:
    ```ruby
     require "test_helper"
     class RoutesTest < ActionDispatch::IntegrationTest

       test "articles_path" do
         assert_equal '/a/articles', engine49688.articles_path
       end
     end
     ```
     If you prefer you can also clone this application from https://gitlab.com/vtamara/app49688 or check details on how 
     we generated it and use it in the [README.md](https://gitlab.com/vtamara/app49688/-/blob/main/README.md).
4.  Run the test with rails 7 and it wil pass
5.  Update the application to rails 7.1 by changing in the `Gemfile` the line `gem "rails", "~> 7.0.8"` with
     `gem "rails", "~> 7.1"` and running `bundle`
6.  Run the same test and it will fail

### Expected behavior
With rails 7.1 the test should pass, i.e `engine49688.articles_path` should be `/a/articles` as it is with Rails 7.0:
```
% bin/rails test test/controllers/routes_test.rb
Running 1 tests in a single process (parallelization threshold is 50)
Run options: --seed 22764

# Running:

.

Finished in 0.345284s, 2.8962 runs/s, 2.8962 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior

```
 % bin/rails test test/controllers/routes_test.rb
...
Running 1 tests in a single process (parallelization threshold is 50)
Run options: --seed 2957

# Running:

F

Failure:
RoutesTest#test_articles_path [/home/vtamara/comp/rails/tmp/app49688/test/controllers/routes_test.rb:6]:
Expected: "/a/articles"
  Actual: "/a/a/articles"


bin/rails test test/controllers/routes_test.rb:5



Finished in 0.206910s, 4.8330 runs/s, 4.8330 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips 
```

In the test `articles_path` duplicates the relative  root.

### System configuration
**Rails version**: 7.1

**Ruby version**: 3.2.2

**Comment by vtamara** [comment]
## Second case

### Steps to reproduce

This application <https://gitlab.com/pasosdeJesus/heb412/-/tree/rails7.0> uses rails 7.0,  two mounted engines (`msip` and `heb412_gen` as can be seen in the [Gemfile](https://gitlab.com/pasosdeJesus/heb412/-/blob/rails7.0/Gemfile)) and it uses a `relative_url_root`  (`heb412`  as can be seen in variable `RUTA_RELATIVA` of the template [.env.plantilla](https://gitlab.com/pasosdeJesus/heb412/-/blob/rails7.0/.env.plantilla) and the files [config/initializers/punto_montaje.rb](https://gitlab.com/pasosdeJesus/heb412/-/blob/rails7.0/config/initializers/punto_montaje.rb) and [config/routes.rb](https://gitlab.com/pasosdeJesus/heb412/-/blob/rails7.0/config/routes.rb)).

It has a simple test ([tests/controllers/rutas0_test.rb](https://gitlab.com/pasosdeJesus/heb412/-/blob/rails7.0/test/controllers/rutas0_test.rb)) that checks the path of a route coming from one of the engines:

    assert_equal '/heb412/personas', personas_path

In rails 7.0 it works but as soon as I change in the `Gemfile`

   gem 'rails', '>= 7.0', '< 7.1'

for

  gem 'rails', '>= 7.1'

and run `bundle` and run the test, it fails:
```
% bin/rails test test/controllers/rutas0_test.rb
...
Failure:                                
Rutas0Test#test_personas_path_usable [/home/vtamara/comp/rails/tmp/heb412/test/controllers/rutas0_test.rb:8]:
Expected: "/heb412/personas"                                                    
  Actual: "/heb412/heb412/personas" 
```

### Expected behavior
The test should pass, i.e `personas_path` should be `/heb412/personas` as it is with Rails 7.0

### Actual behavior
In the test `personas_path` duplicates the relative  becomes `/heb412/heb412/personas`

### System configuration
**Rails version**: 7.1

**Ruby version**: 3.2.2

### Remarks

I tried to replicate the problem with a minimal engine and a minimal application but the problem didn't happen.

**Comment by vtamara** [comment]
Using git bisect I found that it begins to fail with the following commit:

```
commit 066ce1e34fed319a224c45c3f8f28fcdebf32663 (HEAD)
Author: Ben Sheldon [he/him] <bensheldon@gmail.com>
Date:   Sun Jul 31 15:42:21 2022 -0700

    Allow Engine url_helpers to respect config.relative_url_root
```

**Comment by bensheldon** [comment]
Thanks for the ping! Here's the PR that introduced that change: #45719

I'm not quite sure what the root cause is here, but to try to reduce the changes here that you're sharing:


```rb
# config/initializers/punto_montaje.rb
heb412::Application.config.relative_url_root = ENV.fetch('RUTA_RELATIVA', '/heb412')

# config/routes.rb
rutarel = ENV.fetch('RUTA_RELATIVA', 'heb412/')
scope rutarel do
  mount TheEngine, at: rutarel
end
```

First, that routes file looks a little strange. I imagine that it could be trying to work around the longstanding bug fixed by that commit you referenced, because I would believe the _correct_ route would be `heb412/heb412/the_path` because it's a `mount at:` nested in a `scope`

Second, I will hypothesize that the culprit here is setting the `relative_url_root` in an initializer. **I wonder if you would get the correct behavior if you configured `relative_url_root` instead in `config/application.rb`.** It's possible that some parts of the routing stack are being initialized _before_ that initializer is invoked and that's causing the inconsistency (a not [uncommon problem](https://github.com/rails/rails/issues/16209#issuecomment-49363962))

**Comment by vtamara** [comment]
Thanks a lot for reviewing this @bensheldon.

First, I checked again and the file `config/routes.rb` is not like:
```
rutarel = ENV.fetch('RUTA_RELATIVA', 'heb412/')
scope rutarel do
  mount TheEngine, at: rutarel
end
```

But
```
Rails.application.routes.draw do
  rutarel = ENV.fetch('RUTA_RELATIVA', 'heb412/')
  scope rutarel do
  end

  mount TheEngine, at: rutarel
end
```
It doesn´t have the `mount` nested inside the `scope`.

Second `relative_url_root` is also set in `config/application.rb` where it says:
```
  config.relative_url_root = ENV.fetch('RUTA_RELATIVA', '/heb412')
```

As far as I remember I ended up duplicating this configuration in config/application.rb and in an initializers to fix something.  However just to try I removed the configuration from the initializer and did the test again but still the test fails by duplicating the `relative_url_root`.

**Comment by vtamara** [comment]
@bensheldon I was able to simplify the context where the problem happens not using my engines and applications, but just generating part of the standard example <https://edgeguides.rubyonrails.org/engines.html>.   I changed the description and the first test case of this issue --hoping it is fine.

**Comment by bensheldon** [comment]
@vtamara sorry, I think I'm confused now about the problem. The `relative_url_root` should prefix all paths with that value. This is the correct values I would expect that were fixed by #45719 (the behavior in 7.0 was a bug):

```ruby
test "users_path" do
  assert_equal '/a/a/users', users_path
end
test "articles_path" do
  assert_equal '/a/a/articles', engine49688.articles_path
end
```

I think what you're seIf you want to use `relative_url_root` but do not want the double path, you should mount your engine at the root of your application (`mount Engine49688::Engine => "/", as: :engine49688`.

**Comment by vtamara** [comment]
@bensheldon thanks for the answer.   

Now I understand what you wanted to fix with #45719, but even with that  fix still there are inconcistencies with engines mounted on applications with relative roots different to "/".

Extending a little the two tests you proposed, IMHO it would be consistent if the following two tests would pass:

```
test "users_path" do
  assert_equal '/a/a/users', users_path
  get main_app.users_path
  assert_response :success  
end

test "articles_path" do
  assert_equal '/a/a/articles', engine49688.articles_path
  get engine49688.articles_path
  assert_response :success
end
```

In fact I just changed the application  <https://gitlab.com/vtamara/app49688>  ensuring that it can be run with `bin/rails s`,  adding those two tests, leaving `config.relative_url_root = "/a/"` in `config/application.rb` and changing `config/routes.rb` as you suggested to:
```
Rails.application.routes.draw do 
  scope "/a" do
    resources :users 
    mount Engine49688::Engine => "/", as: :engine49688
  end                                                                                                                                                           
end   
```


With rails 7.0 the application fails with:
```
Failure:                                                                        
RoutesTest#test_articles_path [/home/vtamara/comp/rails/app49688/test/controllers/routes_test.rb:10]:
Expected: "/a/a/articles"
  Actual: "/a/articles"


rails test test/controllers/routes_test.rb:9

Error:
RoutesTest#test_users_path:
ActionController::RoutingError: No route matches [GET] "/a/a/users"
    test/controllers/routes_test.rb:5:in `block in <class:RoutesTest>'


rails test test/controllers/routes_test.rb:3
```

Updating to rails 7.1 the tests fails with:

```
Error:
RoutesTest#test_users_path:
ActionController::RoutingError: No route matches [GET] "/a/a/users"
    test/controllers/routes_test.rb:5:in `block in <class:RoutesTest>'
                                                                                
                                        
bin/rails test test/controllers/routes_test.rb:3

Error:
RoutesTest#test_articles_path:
ActionController::RoutingError: No route matches [GET] "/a/a/articles"
    test/controllers/routes_test.rb:11:in `block in <class:RoutesTest>'


bin/rails test test/controllers/routes_test.rb:9
```

**Comment by nbennke** [comment]
Any news at this point?
We're also faced by this problem, setting `RAILS_RELATIVE_URL_ROOT` and using it via `scope` in `config/routes.rb` that the url helpers `Rails.application.routes.url_helpers.xxx_path` returning ab doubled path prefix.

**Comment by bensheldon** [comment]
@nbennke The brief summary at this point, imo, is: you're using a workaround to a problem that no longer exists (albeit it existed for a very long time), and any explicit usage of `relative_url_root` in your application's `config/routes.rb` should be removed.

I think your Rack configuration is the only place in an application where `relative_url_root` should be read ([issue](https://github.com/rails/rails/issues/42248)):

```ruby
# config.ru
map RelativeRoot::Application.config.relative_url_root || '/' do
  run Rails.application
end
```

 
I've been trying to summarize this for months, so I'll try again here:

Rails has two types of url helpers:

- URL helpers that exist in controllers and views, that have full access to the request object. When a request comes in, Rack does the work of calculating the `SCRIPT_NAME` (which is the "relative url root") and will prepend that to the `_path`/`_url` strings it generates.
- URL helpers that are accessed directly from `Rails.application.routes.url_helpers`. These are not part of a request and therefore don't have the path context of `SCRIPT_NAME`. Therefore `config.relative_url_root` is the mechanism for prepending to the `_path`/`_url` strings.

(I think the Asset Pipeline has its own helpers too that use `config.relative_url_root`, but I don't think are part of this confusion). 

For example, if the application is Rack `map` mounted at `/foo/bar` then the `routes.rb` should only concern itself with the path that comes after that. Conceptually, the Rack `map` mount should be able to be changed without changing any other part of the application (other than the `config.relative_url_root` configuration value)

```
https://example.com/foo/bar/posts/1
                   |-------| <-- SCRIPT_NAME and config.relative_url_root
```.                       | ----> The application root in config/routes.rb

**Comment by nbennke** [comment]
@bensheldon Thank you for the fast response with clarification!
Actually our problem occurs by using the url helpers from ERB code during the asset pipeline...
We will give your advice to the `config.ru` another try to "flatten" the routes without the scope. Hoping without it getting non doubled script name values during the precompilation of our assets.

**Comment by vtamara** [comment]
> Any news at this point? We're also faced by this problem, setting `RAILS_RELATIVE_URL_ROOT` and using it via `scope` in `config/routes.rb` that the url helpers `Rails.application.routes.url_helpers.xxx_path` returning ab doubled path prefix.

I just renamed the bug, because with help of @bensheldon I was able to change my applications as described below.

----

rails 7.0 and 7.1 has changed the operation of path helpers when an application is mounted in a mount point different to "/" .     If your appliction is not mounted at "/" but for example at `/mymount/point/`  and if you are using `scope` in `config/routes.rb`:

1. Remove the `scope`  from `config/routes.rb` because the mount point will not be managed by rails but  by rack.

2. Modify the rack configuration file  `config.ru`, it should look like this:
```
 require_relative "config/environment"
                                                                                                                                                        
 map Rails.application.config.relative_url_root || '/' do
    run Rails.application
    Rails.application.load_server
 end
```

3. In `config/application.rb` keep the line
```
config.relative_url_root = "mymount/point/"
```

4. If you are using sprockets and you configured it to compile the resources at `public/mymoun/point/assets` you need to configure right downloads in development and in production modes:
     
    a. In development mode it should be enough `cd public; ln -sf public/mipunto/demontaje/assets`
    b. In production mode with nginx and unicorn 6.1.0.  We suggest to keep using rack 2 (until unicorn release a new version)  by adding to the  `Gemfile`:  `gem "rack ", "~> 2"`.   If the files of your application are at `/var/www/htdocs/myapp` and you configured unicorn to run in port 2051, the configuration file for nginx should include:

        ...
        http {
          ...
          upstream unicorn_myapp {
            server 127.0.0.1:2051 fail_timeout=0;
          }
          ...
          server {
            ...
            location /mymount/point {
              try_files $uri @unicorn_myapp;
            }
            location @unicorn_myapp {
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header Host $http_host;
              proxy_redirect off;
              proxy_pass http://unicorn_myapp;
              proxy_pass http://unicorn_myapp;
              error_page 500 502 503 504 /500.html;
              keepalive_timeout 10;
            }
            location ~ ^/mymount/point/(assets|images)/ {
               gzip_static on;
               expires max;
               add_header Cache-Control public;
               root /var/www/htdocs/myapp/public/;
            }
       ...

**Comment by bensheldon** [comment]
@vtamara Thanks for sharing all of that! That's really interesting about the assets:

> If you are using sprockets and you configured it to compile the resources at `public/mymount/point/assets`

I would also suggest that that _should_ be moved back to `public/` so that the Rails application in its entirety is relative to its (relative) root, and any prepended path exists solely in Rack or Nginx (and the `config.relative_url_root` value).

...though if that doesn't work with how Rails serves assets, I think that should be fixed too.

**Comment by vtamara** [comment]
> @vtamara Thanks for sharing all of that! That's really interesting about the assets:
> 
> > If you are using sprockets and you configured it to compile the resources at `public/mymount/point/assets`
> 
> I would also suggest that that _should_ be moved back to `public/` so that the Rails application in its entirety is relative to its (relative) root, and any prepended path exists solely in Rack or Nginx (and the `config.relative_url_root` value).
> 
> ...though if that doesn't work with how Rails serves assets, I think that should be fixed too.

Thanks. However the problem of that is that is supposes that in testing an development it is fine to use `config.relative_url_root=/` while in production everything will work in the desired with `config.relative_url_root=/mount/point`.

However I do prefer to test and develop in an environment as close as  possible to production, including the same `config.relative_url_root`

**Comment by nbennke** [comment]
> > Any news at this point? We're also faced by this problem, setting `RAILS_RELATIVE_URL_ROOT` and using it via `scope` in `config/routes.rb` that the url helpers `Rails.application.routes.url_helpers.xxx_path` returning ab doubled path prefix.
> 
> I just renamed the bug, because with help of @bensheldon I was able to change my applications as described below.
> 
> ----
> 
> rails 7.0 and 7.1 has changed the operation of path helpers when an application is mounted in a mount point different to "/" .     If your appliction is not mounted at "/" but for example at `/mymount/point/`  and if you are using `scope` in `config/routes.rb`:
> 
> 1. Remove the `scope`  from `config/routes.rb` because the mount point will not be managed by rails but  by rack.
> 
> 2. Modify the rack configuration file  `config.ru`, it should look like this:
> 
>      ```rb
>        require_relative "config/environment"
>        map Rails.application.config.relative_url_root || '/' do
>           run Rails.application
>           Rails.application.load_server
>        end
>      ```
> 
> 3. In `config/application.rb` keep the line
>      ```rb
>         config.relative_url_root = "mymount/point/"
>      ```
> 4. If you are using sprockets and you configured it to compile the resources at `public/mymoun/point/assets` you need to configure right downloads in development and in production modes:
>      
>     a. In development mode it should be enough `cd public; ln -sf public/mipunto/demontaje/assets`
>     b. In production mode with nginx and unicorn 6.1.0.  We suggest to keep using rack 2 (until unicorn release a new version)  by adding to the  `Gemfile`:  `gem "rack ", "~> 2"`.   If the files of your application are at `/var/www/htdocs/myapp` and you configured unicorn to run in port 2051, the configuration file for nginx should include:
> 
>      ```nginx
>         ...
>         http {
>           ...
>           upstream unicorn_myapp {
>             server 127.0.0.1:2051 fail_timeout=0;
>           }
>           ...
>           server {
>             ...
>             location /mymount/point {
>               try_files $uri @unicorn_myapp;
>             }
>             location @unicorn_myapp {
>               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>               proxy_set_header X-Forwarded-Proto $scheme;
>               proxy_set_header Host $http_host;
>               proxy_redirect off;
>               proxy_pass http://unicorn_myapp;
>               proxy_pass http://unicorn_myapp;
>               error_page 500 502 503 504 /500.html;
>               keepalive_timeout 10;
>             }
>             location ~ ^/mymount/point/(assets|images)/ {
>                gzip_static on;
>                expires max;
>                add_header Cache-Control public;
>                root /var/www/htdocs/myapp/public/;
>             }
>        ...
>      ```
> 5. Regarding controllers tests, at this point it is not possible to make pass a simple test like `get path_helper_path` when the `config.relative_url_root` is different to "/" see https://github.com/rails/rails/issues/50461 .  To help running existing tests, it is possible to add `config.relative_url_root="/"`  to `config/environments/test.rb` 

@vtamara thank you for sharing these steps and configuration examples. Using this strategy we solved the problem in our application. Routing and links generated during precompilation process now works as expected. Great work 👌

**Comment by Paul-Bob** [comment]
> I've been trying to summarize this for months, so I'll try again here:
> 
> Rails has two types of url helpers:
> 
>   *  URL helpers that exist in controllers and views, that have full access to the request object. When a request comes in, Rack does the work of calculating the `SCRIPT_NAME` (which is the "relative url root") and will prepend that to the `_path`/`_url` strings it generates.
>   * URL helpers that are accessed directly from `Rails.application.routes.url_helpers`. These are not part of a request and therefore don't have the path context of `SCRIPT_NAME`. Therefore `config.relative_url_root` is the mechanism for prepending to the `_path`/`_url` strings.


@bensheldon Is there any exhaustive documentation about these two types of url helpers?

**Comment by bensheldon** [comment]
@Paul-Bob not that I'm aware of.

**Comment by zzak** [comment]
I think this is related to #51910

**Comment by vtamara** [comment]
@zzak  It seems the problem was solved.

Now in tests I can use routes helpers and they will start with what is configured in `Rails.configuration.relative_url_root`

**Comment by vtamara** [comment]
I closed this one by mistake.  I wanted to close: https://github.com/rails/rails/issues/50461

From my comment  <https://github.com/rails/rails/issues/49688#issuecomment-1915014971> now I would remove points 5 and 6 since the controller test now use correctly `config.relative_url_root`

**Comment by vtamara** [comment]
IMHO a good place to improve the documentation based on this issues is <https://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root>

**Comment by zzak** [comment]
@vtamara Would you be willing to work on a PR to improve the docs?

**Comment by oravapw** [comment]
Documenting this would be *very* nice, I just spent most of the day banging my head against the wall trying to get a subpath-mounted app to work properly. The documentation only talks about `config.relative_url_root`, but as noted here that is not enough -- the url helpers will produce wrong results.

The `config.ru` modification shown above by @vtamara was the missing sauce, I added that and now suddenly everything works as expected. Huge thank you for that! I was losing hope of getting it to work at all.

I wonder why that is not included as a standard `config.ru`, actually? With that included as default, `config.relative_url_root` would work as advertised.
