### ISSUE TITLE
`Rails.logger.tagged` will execute block as many times as the number of tagged loggers in the broadcast

### ISSUE THREAD

**Issue by davidstosik** [rails/rails#49745]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "debug"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

module ActiveSupport
  class BugTest < Minitest::Test
    def test_tagged_broadcast
      logger1_io = StringIO.new
      logger2_io = StringIO.new

      logger = BroadcastLogger.new(TaggedLogging.new(Logger.new(logger1_io)))
      logger.broadcast_to(TaggedLogging.new(Logger.new(logger2_io)))

      run_counter = 0

      logger.tagged("TEST") do
        logger.info("Doing something")
        run_counter += 1
      end

      # require "debug";binding.b
      assert_equal 1, run_counter                                  # Actual: 2
      assert_equal "[TEST] Doing something\n", logger1_io.string   # Actual: "[TEST] Doing something\nDoing something\n"
      assert_equal "[TEST] Doing something\n", logger2_io.string   # Actual: "Doing something\n[TEST] Doing something\n"
    end
  end
end
```

### Expected behavior

When I do `Rails.logger.tagged("MY TAG") { do_something }`, I expect `do_something` to be called once, regardless of how many loggers Rails is broadcasting to.

I also expect my log to be tagged and displayed in each logger. (I should see "[TEST] Doing something" once in the first log sink, and once in the second log sink.)

I don't know how common this is, but I've seen many applications (starting with Shopify), passing rather long blocks to `#tagged`, expecting all logs produced by the code in that block to be tagged. This becomes a problem if we for example do database operations in that block.

### Actual behavior

The block passed to `tagged` is run as many times as there are loggers broadcasted to.
The log messages get multiplied too (obviously), and only one for each logger is tagged.

### System configuration

**Rails version**: `HEAD`
**Ruby version**: 3.2.1

---

Still working on a graceful but quick solution to handle this. Suggestions welcome!

**Comment by davidstosik** [comment]
Here's an idea: implement a "recursive" `tagged` method in `BroadcastLogger`:

```rb
module ActiveSupport
  class BroadcastLogger
    # ...

    def tagged(*tags, &block)
      recursive_tagged(@broadcasts, *tags, &block)
    end

    private

      def recursive_tagged(loggers, *tags, &block)
        return block.call if loggers.empty?
  
        if loggers.first.respond_to?(:tagged)
          loggers.first.tagged(*tags) do
            recursive_tagged(loggers[1..-1], *tags, &block)
          end
        else # skip logger if it doesn't support tagging
          recursive_tagged(loggers[1..-1], *tags, &block)
        end
      end
  end
end
```

**Comment by davidstosik** [comment]
For the record, I tried a brand new Rails 7.1.1 application:
```sh
rails new testlog --minimal
cd testlog
vim config/environments/development.rb
```
Add this:
```rb
  loggers = [
    STDOUT,
    "log/development.log",
  ].map do |output|
    ActiveSupport::Logger.new(output)
      .tap  { |logger| logger.formatter = ::Logger::Formatter.new }
      .then { |logger| ActiveSupport::TaggedLogging.new(logger) }
  end
  config.logger = ActiveSupport::BroadcastLogger.new(*loggers)
```

Start Rails server, browse to the root, and receive this error:
```
Puma caught this error: no implicit conversion of String into Integer (TypeError)
/Users/sto/.gem/ruby/3.2.1/gems/actionpack-7.1.1/lib/action_dispatch/middleware/request_id.rb:28:in `[]='
/Users/sto/.gem/ruby/3.2.1/gems/actionpack-7.1.1/lib/action_dispatch/middleware/request_id.rb:28:in `block in call'
<internal:kernel>:90:in `tap'
/Users/sto/.gem/ruby/3.2.1/gems/actionpack-7.1.1/lib/action_dispatch/middleware/request_id.rb:28:in `call'
/Users/sto/.gem/ruby/3.2.1/gems/rack-3.0.8/lib/rack/method_override.rb:28:in `call'
/Users/sto/.gem/ruby/3.2.1/gems/rack-3.0.8/lib/rack/runtime.rb:24:in `call'
/Users/sto/.gem/ruby/3.2.1/gems/activesupport-7.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/sto/.gem/ruby/3.2.1/gems/actionpack-7.1.1/lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'
/Users/sto/.gem/ruby/3.2.1/gems/actionpack-7.1.1/lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'
/Users/sto/.gem/ruby/3.2.1/gems/actionpack-7.1.1/lib/action_dispatch/middleware/server_timing.rb:58:in `call'
/Users/sto/.gem/ruby/3.2.1/gems/actionpack-7.1.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/sto/.gem/ruby/3.2.1/gems/actionpack-7.1.1/lib/action_dispatch/middleware/static.rb:25:in `call'
/Users/sto/.gem/ruby/3.2.1/gems/rack-3.0.8/lib/rack/sendfile.rb:114:in `call'
/Users/sto/.gem/ruby/3.2.1/gems/actionpack-7.1.1/lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
/Users/sto/.gem/ruby/3.2.1/gems/railties-7.1.1/lib/rails/engine.rb:529:in `call'
/Users/sto/.gem/ruby/3.2.1/gems/puma-6.4.0/lib/puma/configuration.rb:272:in `call'
/Users/sto/.gem/ruby/3.2.1/gems/puma-6.4.0/lib/puma/request.rb:100:in `block in handle_request'
/Users/sto/.gem/ruby/3.2.1/gems/puma-6.4.0/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/Users/sto/.gem/ruby/3.2.1/gems/puma-6.4.0/lib/puma/request.rb:99:in `handle_request'
/Users/sto/.gem/ruby/3.2.1/gems/puma-6.4.0/lib/puma/server.rb:443:in `process_client'
/Users/sto/.gem/ruby/3.2.1/gems/puma-6.4.0/lib/puma/server.rb:241:in `block in run'
/Users/sto/.gem/ruby/3.2.1/gems/puma-6.4.0/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by davidstosik** [comment]
<details><summary>Here's an executable test case reproducing the error I described manually in my previous comment.</summary>

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"
  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

Rails.application.initializers
  .find { _1.name == :initialize_logger }
  .run(Rails.application)

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?

    Rails.logger.broadcast_to(
      ActiveSupport::TaggedLogging.new(ActiveSupport::Logger.new($stdout))
    )

    get "/"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

</details> 


<details><summary>And the output.</summary>

```
# Running:

Started GET "/" for 127.0.0.1 at 2023-10-24 09:58:29 +0900
Started GET "/" for 127.0.0.1 at 2023-10-24 09:58:29 +0900
E

Error:
BugTest#test_returns_success:
TypeError: no implicit conversion of String into Integer
    /Users/sto/.gem/ruby/3.2.1/bundler/gems/rails-1f8f2fb9f5c4/actionpack/lib/action_dispatch/middleware/request_id.rb:28:in `[]='
    /Users/sto/.gem/ruby/3.2.1/bundler/gems/rails-1f8f2fb9f5c4/actionpack/lib/action_dispatch/middleware/request_id.rb:28:in `block in call'
    <internal:kernel>:90:in `tap'
    /Users/sto/.gem/ruby/3.2.1/bundler/gems/rails-1f8f2fb9f5c4/actionpack/lib/action_dispatch/middleware/request_id.rb:28:in `call'
    /Users/sto/.gem/ruby/3.2.1/gems/rack-3.0.8/lib/rack/method_override.rb:28:in `call'
    /Users/sto/.gem/ruby/3.2.1/gems/rack-3.0.8/lib/rack/runtime.rb:24:in `call'
    /Users/sto/.gem/ruby/3.2.1/bundler/gems/rails-1f8f2fb9f5c4/actionpack/lib/action_dispatch/middleware/executor.rb:14:in `call'
    /Users/sto/.gem/ruby/3.2.1/bundler/gems/rails-1f8f2fb9f5c4/actionpack/lib/action_dispatch/middleware/static.rb:25:in `call'
    /Users/sto/.gem/ruby/3.2.1/gems/rack-3.0.8/lib/rack/sendfile.rb:114:in `call'
    /Users/sto/.gem/ruby/3.2.1/bundler/gems/rails-1f8f2fb9f5c4/actionpack/lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
    /Users/sto/.gem/ruby/3.2.1/bundler/gems/rails-1f8f2fb9f5c4/railties/lib/rails/engine.rb:529:in `call'
    /Users/sto/.gem/ruby/3.2.1/gems/rack-test-2.1.0/lib/rack/test.rb:360:in `process_request'
    /Users/sto/.gem/ruby/3.2.1/gems/rack-test-2.1.0/lib/rack/test.rb:163:in `custom_request'
    /Users/sto/.gem/ruby/3.2.1/gems/rack-test-2.1.0/lib/rack/test.rb:112:in `get'
    /opt/rubies/3.2.1/lib/ruby/3.2.0/forwardable.rb:240:in `get'
    reproduce2.rb:51:in `test_returns_success'
```

</details>

**Comment by eileencodes** [comment]
hey @Edouard-chin I saw that you mentioned you saw this one on the other issue so I assigned this to you and will assign the other one. Let us know if you need more information.

**Comment by Edouard-chin** [comment]
Perfect, thanks @eileencodes  👍

**Comment by davidstosik** [comment]
@Edouard-chin Hi there! 👋🏻 

Just a quick comment to mention that I noticed around the end of my day earlier, that `#silence` will have the same issues as `#tagged`.

Might want to consider what `#flush` does as well.

**Comment by reidmorrison** [comment]
The solution is to replace the logger itself and not to use Broadcast logger at all. 
Rails Semantic Logger does this for several standard Rails components, and even replaces rails built-in log subscribers that are not structured logging aware. 
For this scenario track down the offending logger initialization and then we can patch the Rails code as needed to only use the supplied Semantic Logger instance.
https://github.com/reidmorrison/rails_semantic_logger/blob/master/lib/rails_semantic_logger/engine.rb#L137

**Comment by alexevanczuk** [comment]
Hi @davidstosik !

I was wondering if there are any plans to get this merged. I ran into this today when trying to set up some tagged logging to be sent to two locations.

Is there another workaround you recommend in the meantime?

**Comment by Lindemann66** [comment]
@rafaelfranca @JuanVqz @unflxw
Unfortunately, rails `8.1.3.1` also has this bug.

**Comment by JuanVqz** [comment]
@Lindemann66 confirmed, and #53105 (open since Sep 2024) fixes it. I verified that PR's `activesupport/lib` change against current `main` with an executable bug report, which I posted on the PR.

Until it lands, the workaround is to wrap the broadcast rather than the loggers, so only one object does the tagging:

```ruby
# instead of broadcasting between two tagged loggers
config.logger = ActiveSupport::TaggedLogging.new(
  ActiveSupport::BroadcastLogger.new(
    ActiveSupport::Logger.new(STDOUT),
    ActiveSupport::Logger.new("log/development.log"),
  )
)
```
