### ISSUE TITLE
ActiveRecord fails to recover in some cases after database restart

### ISSUE THREAD

**Issue by jacobat** [rails/rails#49781]
ActiveRecord does not handle the database going away properly in all cases. In the following example we execute `Event.first.name`, then we stop the database and execute it again to see it fail. Even after starting the database back up repeated executions continue to fail.

Only once we execute `Event.all.map(&:name)` the connection is reestablished and `Event.first.name` starts executing correctly again.

### Steps to reproduce

```
Loading development environment (Rails 7.1.1)

irb(main):001> Event.first.name
  Event Load (0.6ms)  SELECT "events".* FROM "events" ORDER BY "events"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> "First event"

irb(main):002> `brew services stop postgresql@16`
=> "Stopping `postgresql@16`... (might take a while)\n==> Successfully stopped `postgresql@16` (label: homebrew.mxcl.postgresql@16)\n"

irb(main):003> Event.first.name
  Event Load (0.6ms)  SELECT "events".* FROM "events" ORDER BY "events"."id" ASC LIMIT $1  [["LIMIT", 1]]
.../gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:912:in `exec_prepared': PQconsumeInput() FATAL:  terminating connection due to unexpected postmaster exit (ActiveRecord::ConnectionFailed)
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

.../gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:912:in `exec_prepared': PQconsumeInput() FATAL:  terminating connection due to unexpected postmaster exit (PG::ConnectionBad)
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

irb(main):004> Event.first.name
  Event Load (0.2ms)  SELECT "events".* FROM "events" ORDER BY "events"."id" ASC LIMIT $1  [["LIMIT", 1]]
.../gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:912:in `exec_prepared': PQsocket() can't get socket descriptor (ActiveRecord::ConnectionNotEstablished)
.../gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:912:in `exec_prepared': PQsocket() can't get socket descriptor (PG::ConnectionBad)

irb(main):005> `brew services start postgresql@16`
=> "==> Successfully started `postgresql@16` (label: homebrew.mxcl.postgresql@16)\n"

irb(main):006> Event.first.name
  Event Load (0.3ms)  SELECT "events".* FROM "events" ORDER BY "events"."id" ASC LIMIT $1  [["LIMIT", 1]]
.../gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:912:in `exec_prepared': PQsocket() can't get socket descriptor (ActiveRecord::ConnectionNotEstablished)
.../gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:912:in `exec_prepared': PQsocket() can't get socket descriptor (PG::ConnectionBad)

irb(main):007> Event.first.name
  Event Load (0.2ms)  SELECT "events".* FROM "events" ORDER BY "events"."id" ASC LIMIT $1  [["LIMIT", 1]]
.../gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:912:in `exec_prepared': PQsocket() can't get socket descriptor (ActiveRecord::ConnectionNotEstablished)
.../gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:912:in `exec_prepared': PQsocket() can't get socket descriptor (PG::ConnectionBad)

irb(main):008> Event.all
  Event Load (0.6ms)  SELECT "events".* FROM "events" /* loading for pp */ LIMIT $1  [["LIMIT", 11]]
=>
[#<Event:0x0000000105abd5c8
  id: 1,
  name: "First event",
  created_at: Wed, 25 Oct 2023 12:37:39.770913000 UTC +00:00,
  updated_at: Wed, 25 Oct 2023 12:37:39.770913000 UTC +00:00>]

irb(main):009> Event.first.name
  Event Load (0.4ms)  SELECT "events".* FROM "events" ORDER BY "events"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> "First event"
```

### Expected behavior

`Event.first.name` should succeed once the database is back online.

### Actual behavior

`Event.first.name` continues to fail indefinitely until `Event.all.each(&:name)` is called.

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

**Comment by nvasilevski** [comment]
Was able to reproduce it on `PostgreSQL` but out of curiosity tried mysql and wasn't able to reproduce using both `mysql2` and `trilogy` adapters. So must be something wrong in the postgresql adapter specifically

**Comment by nvasilevski** [comment]
Interestingly it looks like on Rails `7.0.8` even `Event.all.to_a` doesn't reconnect so in a way in Rails 7.1 it become better but not completely

**Comment by composerinteralia** [comment]
I can see the problem, and I think it's fixable. I just need to think about how to write a test for it. It has to do with the way the postgres adapter uses `with_raw_connection` when preparing statements.
