### ISSUE TITLE
Creating new project with rails 7.1.1 fails with An error occurred while installing puma (6.4.0), and Bundler cannot continue.

### ISSUE THREAD

**Issue by thebravoman** [rails/rails#49905]
I will probably manage to fix it on my own, but it is one of those things that will stop people starting with rails.

### Steps to reproduce

rvm use ruby-3.0.4
gem install rails -v 7.1.1
rails --version
rails new viber-bot

### Expected behavior

A new project is created 

### Actual behavior

```
% gem list rails

*** LOCAL GEMS ***

autoprefixer-rails (8.2.0, 6.5.4)
bootstrap-modal-rails (2.2.0)
capistrano-rails (1.6.2)
caxlsx_rails (0.6.3)
coffee-rails (5.0.0, 4.2.2, 4.2.1, 4.1.1)
cssbundling-rails (1.1.2)
elasticsearch-rails (5.0.1)
factory_bot_rails (6.2.0, 4.11.1)
factory_girl_rails (4.9.0)
font-awesome-rails (4.7.0.8, 4.7.0.0)
foundation-rails (6.6.2.0)
foundation_rails_helper (4.0.1)
graphiql-rails (1.8.0)
hamlit-rails (0.2.3)
importmap-rails (1.2.1, 1.1.6, 1.1.5)
initialjs-rails (0.2.0.9)
jquery-fileupload-rails (1.0.0)
jquery-rails (4.5.1, 4.5.0, 3.1.1)
jquery-ui-rails (6.0.1, 5.0.3)
jsbundling-rails (1.1.1)
lodash-rails (4.17.10)
omniauth-rails_csrf_protection (1.0.1)
pry-rails (0.3.9)
rails (7.0.8, 7.0.6, 7.0.4.3, 7.0.4.2, 7.0.4, 6.1.7.4, 6.0.5.1, 5.1.7, 5.0.7.2, 4.2.11.32, 4.2.11.21, 4.2.11)
rails-assets-leaflet (1.5.1)
rails-assets-markdown-it (9.0.1)
rails-controller-testing (1.0.5)
rails-deprecated_sanitizer (1.0.4)
rails-dom-testing (2.2.0, 2.1.1, 2.0.3, 1.0.9)
rails-html-sanitizer (1.6.0, 1.5.0, 1.4.4, 1.4.3)
rails-i18n (6.0.0)
rails-observers (0.1.2)
railslts-version (4.2.11.32, 4.2.11.21)
retreaverjs-rails (0.2.18, 0.2.16)
rspec-rails (6.0.1, 5.1.2, 4.1.2, 3.2.3)
rubocop-rails (2.15.2)
sass-rails (6.0.0, 5.0.7, 5.0.6)
sassc-rails (2.1.2)
select2-rails (3.5.2)
sprockets-rails (3.4.2, 3.2.2, 2.3.3)
stimulus-rails (1.2.2, 1.2.1, 1.1.0)
sunspot_rails (2.4.0)
tailwindcss-rails (2.0.14 arm64-darwin)
turbo-rails (1.4.0, 1.3.2, 1.3.0)
vite_rails (3.0.14, 3.0.13, 3.0.12)
vite_rails_legacy (3.0.4)
x-editable-rails (1.5.2)
kireto@ip-192-168-0-38 code % gem install rails -v 7.1 
^CERROR:  Interrupted
kireto@ip-192-168-0-38 code % gem install rails -v 7.1.1
^CERROR:  Interrupted
kireto@ip-192-168-0-38 code % rvm list
   ruby-2.7.4 [ arm64 ]
=* ruby-2.7.6 [ arm64 ]
   ruby-2.7.7 [ arm64 ]
   ruby-2.7.8 [ arm64 ]
   ruby-3.0.4 [ arm64 ]
   ruby-3.0.5 [ arm64 ]
   ruby-3.1.2 [ arm64 ]
   ruby-3.2.2 [ arm64 ]

# => - current
# =* - current && default
#  * - default

kireto@ip-192-168-0-38 code % rvm use ruby-3.0.4
Using /Users/kireto/.rvm/gems/ruby-3.0.4
kireto@ip-192-168-0-38 code % gem install rails -v 7.1.1
Fetching minitest-5.20.0.gem
Fetching concurrent-ruby-1.2.2.gem
Fetching thor-1.3.0.gem
Fetching rack-3.0.8.gem
Fetching rackup-2.1.0.gem
Fetching connection_pool-2.4.1.gem
Fetching activesupport-7.1.1.gem
Fetching loofah-2.21.4.gem
Fetching rails-html-sanitizer-1.6.0.gem
Fetching rails-dom-testing-2.2.0.gem
Fetching rack-session-2.0.0.gem
Fetching actionview-7.1.1.gem
Fetching actionpack-7.1.1.gem
Fetching railties-7.1.1.gem
Fetching timeout-0.4.0.gem
Fetching activemodel-7.1.1.gem
Fetching rails-7.1.1.gem
Fetching activerecord-7.1.1.gem
Fetching activejob-7.1.1.gem
Fetching activestorage-7.1.1.gem
Fetching actiontext-7.1.1.gem
Fetching actionmailer-7.1.1.gem
Fetching actionmailbox-7.1.1.gem
Fetching actioncable-7.1.1.gem
Successfully installed thor-1.3.0
Successfully installed rack-3.0.8
rackup's executable "rackup" conflicts with rack
Overwrite the executable? [yN]  y
Successfully installed rackup-2.1.0
Successfully installed concurrent-ruby-1.2.2
Successfully installed minitest-5.20.0
Successfully installed connection_pool-2.4.1
Successfully installed activesupport-7.1.1
Successfully installed loofah-2.21.4
Successfully installed rails-html-sanitizer-1.6.0
Successfully installed rails-dom-testing-2.2.0
Successfully installed rack-session-2.0.0
Successfully installed actionview-7.1.1
Successfully installed actionpack-7.1.1
Successfully installed railties-7.1.1
Successfully installed timeout-0.4.0
Successfully installed activemodel-7.1.1
Successfully installed activerecord-7.1.1
Successfully installed activejob-7.1.1
Successfully installed activestorage-7.1.1
Successfully installed actiontext-7.1.1
Successfully installed actionmailer-7.1.1
Successfully installed actionmailbox-7.1.1
Successfully installed actioncable-7.1.1
Successfully installed rails-7.1.1
Parsing documentation for thor-1.3.0
Installing ri documentation for thor-1.3.0
Parsing documentation for rack-3.0.8
Installing ri documentation for rack-3.0.8
Parsing documentation for rackup-2.1.0
Installing ri documentation for rackup-2.1.0
Parsing documentation for concurrent-ruby-1.2.2
Installing ri documentation for concurrent-ruby-1.2.2
Parsing documentation for minitest-5.20.0
Installing ri documentation for minitest-5.20.0
Parsing documentation for connection_pool-2.4.1
Installing ri documentation for connection_pool-2.4.1
Parsing documentation for activesupport-7.1.1
Couldn't find file to include 'activesupport/README.rdoc' from lib/active_support.rb
Installing ri documentation for activesupport-7.1.1
Parsing documentation for loofah-2.21.4
Installing ri documentation for loofah-2.21.4
Parsing documentation for rails-html-sanitizer-1.6.0
Installing ri documentation for rails-html-sanitizer-1.6.0
Parsing documentation for rails-dom-testing-2.2.0
Installing ri documentation for rails-dom-testing-2.2.0
Parsing documentation for rack-session-2.0.0
Installing ri documentation for rack-session-2.0.0
Parsing documentation for actionview-7.1.1
Couldn't find file to include 'actionview/README.rdoc' from lib/action_view.rb
Installing ri documentation for actionview-7.1.1
Parsing documentation for actionpack-7.1.1
Installing ri documentation for actionpack-7.1.1
Parsing documentation for railties-7.1.1
Installing ri documentation for railties-7.1.1
Parsing documentation for timeout-0.4.0
Installing ri documentation for timeout-0.4.0
Parsing documentation for activemodel-7.1.1
Couldn't find file to include 'activemodel/README.rdoc' from lib/active_model.rb
Installing ri documentation for activemodel-7.1.1
Parsing documentation for activerecord-7.1.1
Couldn't find file to include 'activerecord/README.rdoc' from lib/active_record.rb
Installing ri documentation for activerecord-7.1.1
Parsing documentation for activejob-7.1.1
Couldn't find file to include 'activejob/README.md' from lib/active_job.rb
Installing ri documentation for activejob-7.1.1
Parsing documentation for activestorage-7.1.1
Couldn't find file to include 'activestorage/README.md' from lib/active_storage.rb
Installing ri documentation for activestorage-7.1.1
Parsing documentation for actiontext-7.1.1
Couldn't find file to include 'actiontext/README.md' from lib/action_text.rb
Installing ri documentation for actiontext-7.1.1
Parsing documentation for actionmailer-7.1.1
Couldn't find file to include 'actionmailer/README.rdoc' from lib/action_mailer.rb
Installing ri documentation for actionmailer-7.1.1
Parsing documentation for actionmailbox-7.1.1
Couldn't find file to include 'actionmailbox/README.md' from lib/action_mailbox.rb
Installing ri documentation for actionmailbox-7.1.1
Parsing documentation for actioncable-7.1.1
Couldn't find file to include 'actioncable/README.md' from lib/action_cable.rb
Installing ri documentation for actioncable-7.1.1
Parsing documentation for rails-7.1.1
Installing ri documentation for rails-7.1.1
Done installing documentation for thor, rack, rackup, concurrent-ruby, minitest, connection_pool, activesupport, loofah, rails-html-sanitizer, rails-dom-testing, rack-session, actionview, actionpack, railties, timeout, activemodel, activerecord, activejob, activestorage, actiontext, actionmailer, actionmailbox, actioncable, rails after 13 seconds
24 gems installed
kireto@ip-192-168-0-38 code % git stauts
git: 'stauts' is not a git command. See 'git --help'.

The most similar command is
	status
kireto@ip-192-168-0-38 code % git status
fatal: not a git repository (or any of the parent directories): .git
kireto@ip-192-168-0-38 code % rails --version
Rails 7.1.1
kireto@ip-192-168-0-38 code % rails new viber-bot
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /Users/kireto/axles/code/viber-bot/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  Dockerfile
      create  .dockerignore
      create  bin/docker-entrypoint
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/new_framework_defaults_7_1.rb
      create  config/initializers/permissions_policy.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_7_1.rb
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Fetching rake 13.1.0
Installing rake 13.1.0
Fetching base64 0.1.1
Using concurrent-ruby 1.2.2
Fetching mutex_m 0.1.2
Using ruby2_keywords 0.0.5
Using minitest 5.20.0
Using builder 3.2.4
Fetching nio4r 2.5.9
Fetching bigdecimal 3.1.4
Fetching racc 1.7.2
Using connection_pool 2.4.1
Using crass 1.0.6
Fetching zeitwerk 2.6.12
Using erubi 1.12.0
Using marcel 1.0.2
Using rack 3.0.8
Using timeout 0.4.0
Fetching public_suffix 5.0.3
Using websocket-extensions 0.1.5
Fetching bindex 0.8.1
Fetching mini_mime 1.1.5
Using date 3.3.3
Fetching msgpack 1.7.2
Installing bindex 0.8.1 with native extensions
Installing base64 0.1.1
Installing mutex_m 0.1.2
Installing mini_mime 1.1.5
Using bundler 2.2.33
Using matrix 0.4.2
Fetching regexp_parser 2.8.2
Installing msgpack 1.7.2 with native extensions
Installing bigdecimal 3.1.4 with native extensions
Installing racc 1.7.2 with native extensions
Installing public_suffix 5.0.3
Fetching stringio 3.0.8
Fetching io-console 0.6.0
Installing nio4r 2.5.9 with native extensions
Installing zeitwerk 2.6.12
Using webrick 1.8.1
Using thor 1.3.0
Fetching rexml 3.2.6
Installing stringio 3.0.8 with native extensions
Installing regexp_parser 2.8.2
Using rubyzip 2.3.2
Fetching websocket 1.2.10
Installing io-console 0.6.0 with native extensions
Fetching sqlite3 1.6.8 (arm64-darwin)
Installing rexml 3.2.6
Installing websocket 1.2.10
Fetching i18n 1.14.1
Using tzinfo 2.0.6
Fetching drb 2.1.1
Installing drb 2.1.1
Using rack-session 2.0.0
Fetching rack-test 2.1.0
Installing i18n 1.14.1
Fetching sprockets 4.2.1
Installing rack-test 2.1.0
Installing sqlite3 1.6.8 (arm64-darwin)
Fetching websocket-driver 0.7.6
Installing websocket-driver 0.7.6 with native extensions
Installing sprockets 4.2.1
Using net-protocol 0.2.1
Fetching addressable 2.8.5
Using rackup 2.1.0
Fetching selenium-webdriver 4.15.0
Installing addressable 2.8.5
Fetching net-imap 0.4.3
Installing net-imap 0.4.3
Using net-pop 0.1.2
Fetching net-smtp 0.4.0
Installing net-smtp 0.4.0
Using mail 2.8.1
Installing selenium-webdriver 4.15.0
Fetching nokogiri 1.15.4 (arm64-darwin)
Fetching psych 5.1.1.1
Installing psych 5.1.1.1 with native extensions
Installing nokogiri 1.15.4 (arm64-darwin)
Fetching reline 0.3.9
Installing reline 0.3.9
Using loofah 2.21.4
Using xpath 3.2.0
Using rails-html-sanitizer 1.6.0
Fetching capybara 3.39.2
Fetching rdoc 6.5.0
Installing capybara 3.39.2
Fetching puma 6.4.0
Installing puma 6.4.0 with native extensions
Installing rdoc 6.5.0
Fetching irb 1.8.3
Installing irb 1.8.3
Fetching debug 1.8.0
Installing debug 1.8.0 with native extensions
Fetching bootsnap 1.17.0
Installing bootsnap 1.17.0 with native extensions
Using activesupport 7.1.1
Using rails-dom-testing 2.2.0
Using activemodel 7.1.1
Using actionview 7.1.1
Fetching globalid 1.2.1
Fetching jbuilder 2.11.5
Using activerecord 7.1.1
Using actionpack 7.1.1
Using actioncable 7.1.1
Using sprockets-rails 3.4.2
Using railties 7.1.1
Fetching importmap-rails 1.2.3
Fetching stimulus-rails 1.3.0
Fetching web-console 4.2.1
Installing globalid 1.2.1
Using activejob 7.1.1
Using activestorage 7.1.1
Fetching turbo-rails 1.5.0
Using actionmailer 7.1.1
Using actiontext 7.1.1
Using actionmailbox 7.1.1
Using rails 7.1.1
Installing jbuilder 2.11.5
Installing web-console 4.2.1
Installing importmap-rails 1.2.3
Installing stimulus-rails 1.3.0
Installing turbo-rails 1.5.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/kireto/.rvm/gems/ruby-3.0.4/gems/puma-6.4.0/ext/puma_http11
/Users/kireto/.rvm/rubies/ruby-3.0.4/bin/ruby -I /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0 -r ./siteconf20231103-73944-myvy76.rb extconf.rb
using OpenSSL pkgconfig (openssl.pc)
checking for openssl/bio.h... yes
checking for DTLS_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_session_cache_mode(NULL, 0) in openssl/ssl.h... yes
checking for TLS_server_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_min_proto_version(NULL, 0) in openssl/ssl.h... yes
checking for X509_STORE_up_ref()... yes
checking for SSL_CTX_set_ecdh_auto(NULL, 0) in openssl/ssl.h... yes
checking for SSL_CTX_set_dh_auto(NULL, 0) in openssl/ssl.h... yes
checking for SSL_get1_peer_certificate() in openssl/ssl.h... no
checking for Random.bytes... yes
creating Makefile

current directory: /Users/kireto/.rvm/gems/ruby-3.0.4/gems/puma-6.4.0/ext/puma_http11
make DESTDIR\= clean

current directory: /Users/kireto/.rvm/gems/ruby-3.0.4/gems/puma-6.4.0/ext/puma_http11
make DESTDIR\=
compiling http11_parser.c
compiling mini_ssl.c
compiling puma_http11.c
linking shared-object puma/puma_http11.bundle
Undefined symbols for architecture arm64:
  "_SSL_get1_peer_certificate", referenced from:
      _engine_peercert in mini_ssl.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [puma_http11.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/kireto/.rvm/gems/ruby-3.0.4/gems/puma-6.4.0 for inspection.
Results logged to /Users/kireto/.rvm/gems/ruby-3.0.4/extensions/arm64-darwin-21/3.0.0/puma-6.4.0/gem_make.out

  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:93:in `run'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:44:in `block in make'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:36:in `each'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:36:in `make'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:159:in `build_extension'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in `block in build_extensions'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `each'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `build_extensions'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/installer.rb:837:in `build_extensions'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/source/rubygems.rb:204:in `install'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /Users/kireto/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing puma (6.4.0), and Bundler cannot continue.

In Gemfile:
  puma
         run  bundle lock --add-platform=x86_64-linux
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies........
Writing lockfile to /Users/kireto/axles/code/viber-bot/Gemfile.lock
         run  bundle lock --add-platform=aarch64-linux
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Writing lockfile to /Users/kireto/axles/code/viber-bot/Gemfile.lock
         run  bundle binstubs bundler
Could not find puma-6.4.0 in any of the sources
       rails  importmap:install
Could not find puma-6.4.0 in any of the sources
Run `bundle install` to install missing gems.
       rails  turbo:install stimulus:install
Could not find puma-6.4.0 in any of the sources
Run `bundle install` to install missing gems.
kireto@ip-192-168-0-38 code % 
```

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.0.4

**Comment by fatkodima** [comment]
This is definitely not a rails issue. That is related to ssl + puma. Seems like https://github.com/puma/puma/issues/3266, which is already fixed.

**Comment by thebravoman** [comment]
@fatkodima you are absolutely right. This is not an issue with rails itself, at the same time these are huge issues for rails.

As far as I remember on the latest rails world in October 2023 one of the directions for submitting talks was around "introducing new commers to rails". Such issues, while they are not with rails, are exactly with rails as they stop people from starting up.

Rails is meant to have a set of preselected tools that make it just work, and to reduce the amount of stuff we have to do to get it going. I don't think this is happening. Although I don't have hard data to support it, my personal experience of teaching hundreds of people to use rails, shows that rails often just stops at issues like that and is relatively hard to get going with, compared to other frameworks and tools. I sometimes wonder - like do we really need latest version of puma compile with native extensions to rails new, and then rails s. 

Let me know your thoughts

**Comment by fatkodima** [comment]
Reopening for other people thoughts.

**Comment by repoles** [comment]
I agree. This is not a Rails issue. The [Ruby on Rails forum](https://discuss.rubyonrails.org) seems to be a better place to ask for help, like @thebravoman already [did](https://discuss.rubyonrails.org/t/could-not-rails-new-project-issue-was-closed-with-this-is-not-a-rails-problem-rails-7-1/84180).

**Comment by zzak** [comment]
Thanks for your report! Other developers who run into this problem might find the answer here, and hopefully there will be a release of puma with the fix soon enough.
