### ISSUE TITLE
Unable to combine in_order_of with distinct while using postgresql

### ISSUE THREAD

**Issue by mkasztelnik** [rails/rails#49953]
### Steps to reproduce

We have a list of records with the preferred status order and joins leading to no-unique results. As a result, we want to combine `in_order_of` with `distinct`. This works fine with `mysql` and `sqlite` but fails on `postgresql`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  # gem "sqlite3"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
# ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.establish_connection(
  adapter: 'postgresql',
  encoding: 'unicode',
  # host: ENV.fetch("POSTGRES_HOST", "127.0.0.1"),
  # port: ENV.fetch("POSTGRES_PORT", 5432),
  database: 'rails_dev'
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :state
  end
end

class User < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_distint_with_in_order_of
    User.create! state: "a"
    User.create! state: "b"
    User.create! state: "c"

    result = User.in_order_of(:state, ["c", "a", "b"]).distinct
    assert_equal ["c", "a", "b"], result.map(&:state)
  end
end

```

### Expected behavior

Unique records returned in defined order

### Actual behavior

```
Error:
BugTest#test_distint_with_in_order_of:
ActiveRecord::StatementInvalid: PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...WHERE "users"."state" IN ('c', 'a', 'b') ORDER BY CASE WHEN ...
                                                             ^

    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:896:in `exec_params'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:896:in `block (2 levels) in exec_no_cache'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1031:in `block in with_raw_connection'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1003:in `with_raw_connection'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:895:in `block in exec_no_cache'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1141:in `log'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_no_cache'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:874:in `execute_and_clear'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `internal_exec_query'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:628:in `select'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:71:in `select_all'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:114:in `select_all'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/querying.rb:62:in `_query_by_sql'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/relation.rb:983:in `block in exec_main_query'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/relation.rb:1003:in `skip_query_cache_if_necessary'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/relation.rb:969:in `exec_main_query'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/relation.rb:947:in `block in exec_queries'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/relation.rb:1003:in `skip_query_cache_if_necessary'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/relation.rb:941:in `exec_queries'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/relation.rb:727:in `load'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/relation.rb:264:in `records'
    /home/marek/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d53ef2c18073/activerecord/lib/active_record/relation/delegation.rb:99:in `each'
    distinct-in_order_of-postgresql-bug.rb:53:in `map'
    distinct-in_order_of-postgresql-bug.rb:53:in `test_distint_with_in_order_of'
```
The ugly solution right now is to add dedicated select section:

```ruby
User
  .select("users.*, CASE WHEN users.state = 'c' THEN 1 WHEN users.state = 'a' THEN 2 WHEN users.state = 'b' THEN 3 END")
  .in_order_of(:state, ["c", "a", "b"]).distinct
```
But it is fragile and can change even when updating between bug fix rails release (e.g. https://github.com/rails/rails/pull/45670 introduced in rails 7.0.7)

### System configuration
**Rails version**:
Tested from `7.0.5` till `main`

**Ruby version**:
Tested with ruby `3.2.1`

**Comment by paulreece** [comment]
cc @fatkodima

**Comment by fatkodima** [comment]
Thanks for mentioning, I will take a look.

**Comment by fatkodima** [comment]
Investigated a bit. Not sure we can solve this in rails better than just updating this method docs with the example.

There are 2 problems:
1. `in_order_of` should always be used after `distinct` in the query (meaning `.distinct.in_order_of`, but not `.in_order_of.distinct`), because we won't detect when to extend the `SELECT` clause. Yes, we can just always extend it, but the query will become much uglier in all the cases, not only when `distinct` is used.
2. We need to extend the `SELECT` clause with this `CASE`. We can add something like `select(*, case ...)` in the implementation of the `in_order_of` method, but it would not work correctly if `in_order_of` will be followed by some custom `select`, because all the columns are already selected. So, `in_order_of.select(:column)` will do `SELECT *, CASE ..., column`, which is wrong.

You can also rewrite you query with a little simple code as `User.distinct.to_a.in_order_of(:state, ["c", "a", "b"])`.

**Comment by mkasztelnik** [comment]
Thx for looking at this issue. 

> 1. `in_order_of` should always be used after `distinct` in the query (meaning `.distinct.in_order_of`, but not `.in_order_of.distinct`), because we won't detect when to extend the `SELECT` clause. Yes, we can just always extend it, but the query will become much uglier in all the cases, not only when `distinct` is used.
> 2. We need to extend the `SELECT` clause with this `CASE`. We can add something like `select(*, case ...)` in the implementation of the `in_order_of` method, but it would not work correctly if `in_order_of` will be followed by some custom `select`, because all the columns are already selected. So, `in_order_of.select(:column)` will do `SELECT *, CASE ..., column`, which is wrong.

As far as I understand you are proposing tackling this issue on the active record level (which will be method order dependent). Is Arel level (DB dependent part) also an option to investigate? 

> You can also rewrite you query with a little simple code as `User.distinct.to_a.in_order_of(:state, ["c", "a", "b"])`.

The problem with `to_a` is that the query stops being chainable and paginable. I found a walkaround for now by using `User.from(User.distinct, "users").in_order_of(:state, ["c", "a", "b"])`. The good part is that it is still chainable and paginable, bad is that I need to do all the filtering in the subquery.

**Comment by fatkodima** [comment]
> As far as I understand you are proposing tackling this issue on the active record level (which will be method order dependent). 
Yes, but this is ugly and a hack. It should really not depend on the ordering. I would like to avoid such an implementation. 

> Is Arel level (DB dependent part) also an option to investigate?

I do not think this is an appropriate place. This will be complicated and unnecessary just for this method.

**Comment by tonxyx** [comment]
I can confirm same issue here, but with a bit different implementation.

We have Users model, with a `default_scope { order("users.name ASC") }`
In the other model (Course) where we implement `has_many :users,  -> { distinct }, :through`, we get the same error as mentioned before..

 This worked in Rails 7.0.4., Ruby 3.1.2
 Now upgrading to Rails 7.1.1, Ruby 3.2.2
