### ISSUE TITLE
Parallel tests does not work when using `active_record.schema_format = :sql`

### ISSUE THREAD

**Issue by b3coded** [rails/rails#49968]
### Steps to reproduce
My parallel tests are crashing after changing the `active_record.schema_format` to `:sql` on `config/application.rb`.
Without this option, parallelization worked for me.

Steps:
1. add the configuration
2. run `RAILS_ENV=test rails db:setup` to configure the test database and generate the `structure.sql` file
3. run tests

### Expected behavior
No crashes

### Actual behavior
The tests are crashing with this output
```
Error:
ArticleTest#test_should_not_save_article_without_title:
ArgumentError: comparison of Integer with String failed
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/mysql/database_statements.rb:137:in `>'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/mysql/database_statements.rb:137:in `max_allowed_packet_reached?'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/mysql/database_statements.rb:127:in `block in combine_multi_statements'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/mysql/database_statements.rb:125:in `each'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/mysql/database_statements.rb:125:in `each_with_object'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/mysql/database_statements.rb:125:in `combine_multi_statements'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/mysql/database_statements.rb:86:in `execute_batch'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block (2 levels) in truncate_tables'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:182:in `disable_referential_integrity'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `block in truncate_tables'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/mysql/database_statements.rb:117:in `with_multi_statements'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:198:in `truncate_tables'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `truncate_tables'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/tasks/database_tasks.rb:221:in `truncate_tables'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/tasks/database_tasks.rb:368:in `reconstruct_from_schema'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/test_databases.rb:17:in `block in create_and_load_schema'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/test_databases.rb:14:in `each'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/test_databases.rb:14:in `create_and_load_schema'
  /bundle/ruby/3.0.0/gems/activerecord-6.1.0/lib/active_record/test_databases.rb:8:in `block in <module:TestDatabases>'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/testing/parallelization/worker.rb:79:in `block in after_fork'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/testing/parallelization/worker.rb:78:in `each'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/testing/parallelization/worker.rb:78:in `after_fork'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/testing/parallelization/worker.rb:24:in `block in start'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:10:in `block in fork'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:10:in `block in fork'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:8:in `fork'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:8:in `fork'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:26:in `fork'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:8:in `fork'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:26:in `fork'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/testing/parallelization/worker.rb:15:in `start'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/testing/parallelization.rb:37:in `block in start'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/testing/parallelization.rb:36:in `times'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/testing/parallelization.rb:36:in `each'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/testing/parallelization.rb:36:in `map'
  /bundle/ruby/3.0.0/gems/activesupport-6.1.0/lib/active_support/testing/parallelization.rb:36:in `start'
```

### System configuration
**Rails version**:
6.1.0
**Ruby version**:
3.0.3

**Comment by fatkodima** [comment]
Can you verify this behavior with rails 7.1+? Rails 6.1 is not supported for bug fixes (https://guides.rubyonrails.org/maintenance_policy.html).

**Comment by b3coded** [comment]
Upgraded my test app to rails 7.1 and the parallelization worked

**Comment by fatkodima** [comment]
Thanks! That was fixed somewhere in between the versions.

**Comment by b3coded** [comment]
@fatkodima 
I noticed that in the test using the version 7.1 worked because the number of tests did not reach the parallelization threshold so the tests ran in single process.

When I reduced the threshold to enable the parallelization it stopped working returning the same error

```
DRb::DRbRemoteError: ArgumentError: comparison of Integer with String failed (ActiveRecord::StatementInvalid)
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/mysql/database_statements.rb:71:in `>'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/mysql/database_statements.rb:71:in `max_allowed_packet_reached?'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/mysql/database_statements.rb:61:in `block in combine_multi_statements'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/mysql/database_statements.rb:59:in `each'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/mysql/database_statements.rb:59:in `each_with_object'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/mysql/database_statements.rb:59:in `combine_multi_statements'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/mysql2/database_statements.rb:60:in `execute_batch'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:224:in `block (2 levels) in truncate_tables'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:215:in `disable_referential_integrity'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:222:in `block in truncate_tables'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/mysql2/database_statements.rb:90:in `block in with_multi_statements'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract_adapter.rb:1028:in `block in with_raw_connection'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract_adapter.rb:1000:in `with_raw_connection'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/mysql2/database_statements.rb:87:in `with_multi_statements'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:221:in `truncate_tables'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/query_cache.rb:25:in `truncate_tables'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/tasks/database_tasks.rb:226:in `block in truncate_tables'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/tasks/database_tasks.rb:501:in `block in with_temporary_connection'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/tasks/database_tasks.rb:518:in `with_temporary_pool'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/tasks/database_tasks.rb:500:in `with_temporary_connection'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/tasks/database_tasks.rb:225:in `truncate_tables'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/tasks/database_tasks.rb:392:in `block in reconstruct_from_schema'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/tasks/database_tasks.rb:518:in `with_temporary_pool'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/tasks/database_tasks.rb:390:in `reconstruct_from_schema'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/test_databases.rb:17:in `block in create_and_load_schema'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/test_databases.rb:14:in `each'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/test_databases.rb:14:in `create_and_load_schema'
    /bundle/ruby/3.0.0/gems/activerecord-7.1.2/lib/active_record/test_databases.rb:8:in `block in <module:TestDatabases>'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/testing/parallelization/worker.rb:82:in `block in after_fork'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/testing/parallelization/worker.rb:81:in `each'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/testing/parallelization/worker.rb:81:in `after_fork'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/testing/parallelization/worker.rb:24:in `block in start'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/fork_tracker.rb:20:in `block in fork'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/fork_tracker.rb:18:in `fork'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/fork_tracker.rb:18:in `fork'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/testing/parallelization/worker.rb:15:in `start'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/testing/parallelization.rb:37:in `block in start'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/testing/parallelization.rb:36:in `times'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/testing/parallelization.rb:36:in `each'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/testing/parallelization.rb:36:in `map'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/testing/parallelization.rb:36:in `start'
    /bundle/ruby/3.0.0/gems/activesupport-7.1.2/lib/active_support/testing/parallelize_executor.rb:19:in `start'
```

**Comment by fatkodima** [comment]
Can you provide a reproduction test script?
