### ISSUE TITLE
Psych::DisallowedClass when loading fixtures

### ISSUE THREAD

**Issue by dylan-hoefsloot** [rails/rails#49977]
### Steps to reproduce
I upgraded ruby from `2.7.6` to `3.1.4`

Run any rspec tests which load fixtures that have a field that is a time

### Expected behavior
Fixtures are loaded and tests run

### Actual behavior
I get the following error when trying to run any specs
```
   Failure/Error: raise DisallowedClass.new('load', klassname)

       Psych::DisallowedClass:
         Tried to load unspecified class: Time
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixture_set/file.rb:50:in `raw_rows'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixture_set/file.rb:39:in `config_row'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixture_set/file.rb:29:in `model_class'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixtures.rb:685:in `block (2 levels) in read_fixture_files'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixture_set/file.rb:17:in `open'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixtures.rb:684:in `block in read_fixture_files'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixtures.rb:683:in `each'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixtures.rb:683:in `each_with_object'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixtures.rb:683:in `read_fixture_files'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixtures.rb:631:in `initialize'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixtures.rb:576:in `new'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixtures.rb:576:in `block in read_and_insert'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixtures.rb:574:in `map'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixtures.rb:574:in `read_and_insert'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/fixtures.rb:545:in `create_fixtures'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/test_fixtures.rb:223:in `load_fixtures'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/test_fixtures.rb:120:in `setup_fixtures'
       # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/test_fixtures.rb:8:in `before_setup'
       # /usr/local/bundle/gems/activejob-6.0.6.1/lib/active_job/test_helper.rb:45:in `before_setup'
```

### System configuration
**Rails version**: 6.0.6.1
**Ruby version**: 3.1.4

### Solutions I have tried
Adding the following to `config/application.rb` (which is suggested in every other issue pertaining to this error I can find)
```
config.active_record.use_yaml_unsafe_load = true
config.active_record.yaml_column_permitted_classes = [Symbol, Hash, Array, ActiveSupport::TimeWithZone, ActiveSupport::TimeZone, ActiveSupport::HashWithIndifferentAccess, ActiveModel::Attribute.const_get(:FromDatabase), Time]
```

Confirming it is the fixtures throwing the error by commenting out
```
config.global_fixtures = :all
```

Confirming it is the time in the fixtures by commenting out usages such as
```
published_at: 2010-05-16 14:00
```

Downgrading back to `2.7.6` works but this is not ideal as I am trying to upgrade ruby to a newer version

**Comment by dylan-hoefsloot** [comment]
Looks like the line to blame is [here](https://github.com/rails/rails/blob/e29f5e0feb68ee6a9bd44f24991d7494a71884f0/activerecord/lib/active_record/fixture_set/file.rb#L50)

I fixed this by changing it from 
```ruby
data = YAML.load(render(IO.read(@file)))
```
to
```ruby
YAML.safe_load(render(IO.read(@file)), permitted_classes: ActiveRecord::Base.yaml_column_permitted_classes)
```
however this isn't a long term solution as it required me updating the code in the gems files locally.

It looks like rails `6.1` and later load fixtures differently a perhaps this solves this issue, I will try upgrading rails see if this solves the issue.

**Comment by fatkodima** [comment]
Rails < 7.1 is not supported for bugfixes (see https://guides.rubyonrails.org/maintenance_policy.html). Can you verify this behavior with newer rails?

**Comment by dylan-hoefsloot** [comment]
Can confirm that upgrading to rails `6.1` fixed this issue
