### ISSUE TITLE
Incorrect serialization of `ActiveSupport::StringInquirer` instances 

### ISSUE THREAD

**Issue by viralpraxis** [rails/rails#50076]
### Steps to reproduce

Consider the following MRE:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activejob", "~> 7.1.0"
  gem "sidekiq", "~> 7.2.0"
end

require "minitest/autorun"
require "active_job"
require "active_support/core_ext/string/inquiry"

class BuggyJob < ActiveJob::Base
  self.queue_adapter = :sidekiq

  def perform(argument)
    p argument
  end
end

class BuggyJobTest < ActiveJob::TestCase
  def test_stuff
    BuggyJob.perform_later("paid".inquiry)
    perform_enqueued_jobs
  end

  def queue_adapter_for_test
    ActiveJob::QueueAdapters::SidekiqAdapter.new
  end
end
```

Basically we pass an instance of `ActiveSupport::StringInquirer` to `.perform_later` (note that queue adapter is set to `sidekiq`), and I expect it to be serialized correctly. In fact, an exception occurs (I believe that's because of [this](https://github.com/sidekiq/sidekiq/issues/5246) sidekiq change.)

It happenes because here

https://github.com/rails/rails/blob/6b93fff8af32ef5e91f4ec3cfffb081d0553faf0/activejob/lib/active_job/arguments.rb#L74-L76

first comparsion (with `PERMITTED_TYPES`) passes because that's equivalent with

```ruby
[String].any? { "foo".inquiry.is_a? _1 }
true
```

Unfortunately, it cannot be bypassed "in place" (without monkeypatching) with custom AJ serializer (via `Rails.application.config.active_job.custom_serializers << ` API) because checking against String subclass passes, so fallback for custom serializer doesn't happen.

### Expected behavior
I expect an instance of `ActiveSupport::StringInquirer` to be serialized and serialized correctly.

Serialization should be as easy as

```ruby
class StringInquirerSerializer < ObjectSerializer # :nodoc:
  def serialize(argument)
    super("value" => argument.to_s)
  end

  def deserialize(argument)
    argument["value"].inquiry
  end

  private
    def klass
      ActiveSupport::StringInquirer
    end
end
```

so I don't see why this custom serializer (with taking into account the issue I mentioned above) wouldn't work. 

### Actual behavior
```
  1) Error:
BuggyJobTest#test_stuff:
ArgumentError: Job arguments to BuggyJob must be native JSON types, but "paid" is a ActiveSupport::StringInquirer.
See https://github.com/sidekiq/sidekiq/wiki/Best-Practices
To disable this error, add `Sidekiq.strict_args!(false)` to your initializer.


.../sidekiq-7.2.0/lib/sidekiq/job_util.rb:33:in `verify_json'
.../sidekiq-7.2.0/lib/sidekiq/client.rb:92:in `push'
.../sidekiq-7.2.0/lib/sidekiq/job.rb:361:in `client_push'
...
```

### System configuration
**Rails version**: 7.0.8, 7.1.2
**Ruby version**: 3.2.2
**Sidekiq version**: 7.2.0

**Comment by fatkodima** [comment]
When serializing, we could probably check if there are any existing custom serializers before trying serialize standard classes, so the `else` case should be the first here https://github.com/rails/rails/blob/550c5d235bb3fd8151d15438c4619b7d6b4a78b8/activejob/lib/active_job/arguments.rb#L73-L109

Seems like this would not introduce behaviour changes, but not sure about the real-world performance of such change, considering that most objects are of standard classes without custom serializers.

**Comment by viralpraxis** [comment]
> When serializing, we could probably check if there are any existing custom serializers before trying serialize standard classes, so the `else` case should be the first here
> 
> https://github.com/rails/rails/blob/550c5d235bb3fd8151d15438c4619b7d6b4a78b8/activejob/lib/active_job/arguments.rb#L73-L109
> 
> Seems like this would not introduce behaviour changes, but not sure about the real-world performance of such change, considering that most objects are of standard classes without custom serializers.

Could we just check argument's class against predefined list of `PERMITTED_TYPES` descendants?

Something like

```ruby
PERMITTED_TYPES_DESCENDANTS = [ActiveSupport::StringInquirer, ...]

def serialize_argument(argument) 
  case argument
  when *PERMITTED_TYPES_DESCENDANTS
    Serializers.serialize(argument) 
  when *PERMITTED_TYPES 
    argument
  ...
end


```

**Comment by fatkodima** [comment]
No, because we do not know what to include into `PERMITTED_TYPES_DESCENDANTS` since you can have custom classes inherited from a String, for example.

**Comment by viralpraxis** [comment]
> No, because we do not know what to include into `PERMITTED_TYPES_DESCENDANTS` since you can have custom classes inherited from a String, for example.

Absolutely. What I actually mean is that, I believe, there are 2 different issues:

1. Inability to provide custom serializers for `PERMITTED_TYPES` descendants
2. Inability to serialize of `ActiveSupport::StringInquirer` (and maybe some other rails-specific types) via latest Sidekiq. 

Fixing the first issue would allow to resolve the second one. ATM the latter can be fixed either by monkey-patching (which is undesirable), disabling `Sidekiq.strict_args` (which is undesirable) or completely removing StringInquirer from AJ jobs (which seems to be the best option but still undesirable)

**Comment by fatkodima** [comment]
With my approach, came up with the following new code for `serialize_argument` method:
```ruby
def serialize_argument(argument)
  if BigDecimal === argument && !ActiveJob.use_big_decimal_serializer
    ActiveJob.deprecator.warn(<<~MSG)
      Primitive serialization of BigDecimal job arguments is deprecated as it may serialize via .to_s using certain queue adapters.
      Enable config.active_job.use_big_decimal_serializer to use BigDecimalSerializer instead, which will be mandatory in Rails 7.2.

      Note that if your application has multiple replicas, you should only enable this setting after successfully deploying your app to Rails 7.1 first.
      This will ensure that during your deployment all replicas are capable of deserializing arguments serialized with BigDecimalSerializer.
    MSG
    argument
  elsif PERMITTED_TYPES.include?(argument.class) # optimization to avoid slow `has_serializer?` call (next branch)
    argument
  elsif Serializers.has_serializer?(argument)
    Serializers.serialize(argument)
  elsif PERMITTED_TYPES.any? { |type| argument.is_a?(type) }
    argument
  elsif GlobalID::Identification === argument
    convert_to_global_id_hash(argument)
  elsif Array === argument
    argument.map { |arg| serialize_argument(arg) }
  elsif ActiveSupport::HashWithIndifferentAccess === argument
    serialize_indifferent_hash(argument)
  elsif Hash === argument
    symbol_keys = argument.each_key.grep(Symbol).map!(&:to_s)
    aj_hash_key = if Hash.ruby2_keywords_hash?(argument)
      RUBY2_KEYWORDS_KEY
    else
      SYMBOL_KEYS_KEY
    end
    result = serialize_hash(argument)
    result[aj_hash_key] = symbol_keys
    result
  elsif arg.respond_to?(:permitted?) && arg.respond_to?(:to_h)
    serialize_indifferent_hash(argument.to_h)
  else
    raise SerializationError.new("Unsupported argument type: #{argument.class.name}")
  end
end
```

Performed a simple benchmark over this change:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "benchmark-ips"
  gem "activejob", path: "/local/copy/of/rails"
end

require "active_job"

class MyJob < ActiveJob::Base
  def perform(arguments)
  end
end

args = ["string", 1, { key: [1, 2, 1.2], key2: "string2"}]

Benchmark.ips do |x|
  x.report("old") do
    MyJob.new(args).serialize
  end

  x.report("new") do
    MyJob.new(args).new_serialize
  end

  x.compare!
end
```

Results:
```
Warming up --------------------------------------
                 old     3.952k i/100ms
                 new     1.993k i/100ms
Calculating -------------------------------------
                 old     35.799k (±12.7%) i/s -    177.840k in   5.063491s
                 new     28.237k (± 4.0%) i/s -    141.503k in   5.019194s

Comparison:
                 old:    35798.9 i/s
                 new:    28236.6 i/s - 1.27x  slower
```

Code became uglier and 27% slower (while still doing 28k operations per second, so not so slow). 

Not sure if this is an issue we should fix, considering that OP can just call `string.inquire` inside the job manually.

@byroot Wdyt?

**Comment by fatkodima** [comment]
> If you are dead set on doing this, custom serializers should (ideally) allow you to do it.

Yeah, the problem is that for custom classes (like `class MyString < String`, `StringInquier` in the issue) the custom serializer here https://github.com/rails/rails/blob/b7d9654f981120b3f525533c3e35f544d3d3171e/activejob/lib/active_job/arguments.rb#L107 won't kick in, because we will get a match for String here first https://github.com/rails/rails/blob/b7d9654f981120b3f525533c3e35f544d3d3171e/activejob/lib/active_job/arguments.rb#L75-L76

**Comment by casperisfine** [comment]
@fatkodima what about:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "benchmark-ips"
  gem "activejob"#, path: "/local/copy/of/rails"
end

require "active_job"

class MyJob < ActiveJob::Base
  def perform(arguments)
  end

  def serialize_opt
    {
      "job_class"  => self.class.name,
      "job_id"     => job_id,
      "provider_job_id" => provider_job_id,
      "queue_name" => queue_name,
      "priority"   => priority,
      "arguments"  => serialize_arguments_if_needed_opt(arguments),
      "executions" => executions,
      "exception_executions" => exception_executions,
      "locale"     => I18n.locale.to_s,
      "timezone"   => timezone,
      "enqueued_at" => Time.now.utc.iso8601(9),
      "scheduled_at" => _scheduled_at_time ? _scheduled_at_time.utc.iso8601(9) : nil,
    }
  end

  def serialize_arguments_if_needed_opt(arguments)
    if arguments_serialized?
      @serialized_arguments
    else
      serialize_arguments_opt(arguments)
    end
  end

  def serialize_arguments_opt(arguments)
    ActiveJob::Arguments.serialize_opt(arguments)
  end
end

module ActiveJob
  module Arguments
    extend self
    def serialize_opt(arguments)
      arguments.map { |argument| serialize_argument_opt(argument) }
    end

    def serialize_argument_opt(argument)
      case argument
      when nil, true, false, Integer, Float # Types that can hardly be subclassed
        argument
      when String == argument.class
        argument
      when GlobalID::Identification
        convert_to_global_id_hash(argument)
      when Array
        argument.map { |arg| serialize_argument(arg) }
      when ActiveSupport::HashWithIndifferentAccess
        serialize_indifferent_hash(argument)
      when Hash
        symbol_keys = argument.each_key.grep(Symbol).map!(&:to_s)
        aj_hash_key = if Hash.ruby2_keywords_hash?(argument)
          RUBY2_KEYWORDS_KEY
        else
          SYMBOL_KEYS_KEY
        end
        result = serialize_hash(argument)
        result[aj_hash_key] = symbol_keys
        result
      when -> (arg) { arg.respond_to?(:permitted?) && arg.respond_to?(:to_h) }
        serialize_indifferent_hash(argument.to_h)
      else
        if BigDecimal === argument && !ActiveJob.use_big_decimal_serializer
          ActiveJob.deprecator.warn(<<~MSG)
            Primitive serialization of BigDecimal job arguments is deprecated as it may serialize via .to_s using certain queue adapters.
            Enable config.active_job.use_big_decimal_serializer to use BigDecimalSerializer instead, which will be mandatory in Rails 7.2.

            Note that if your application has multiple replicas, you should only enable this setting after successfully deploying your app to Rails 7.1 first.
            This will ensure that during your deployment all replicas are capable of deserializing arguments serialized with BigDecimalSerializer.
          MSG
          return argument
        end

        Serializers.serialize(argument)
      end
    end
  end
end


args = ["string", 1, { key: [1, 2, 1.2], key2: "string2"}]
p MyJob.new(args).method(:serialize)

Benchmark.ips do |x|
  x.report("old") do
    MyJob.new(args).serialize
  end

  x.report("opt") do
    MyJob.new(args).serialize_opt
  end

  x.compare!
end
```

```
Warming up --------------------------------------
                 old    11.302k i/100ms
                 opt    11.257k i/100ms
Calculating -------------------------------------
                 old    112.326k (± 1.5%) i/s -    565.100k in   5.031965s
                 opt    109.093k (± 4.5%) i/s -    551.593k in   5.067862s

Comparison:
                 old:   112325.9 i/s
                 opt:   109093.5 i/s - same-ish: difference falls within error
```

Close to no perf impact.

**Comment by casperisfine** [comment]
Hum, wait, there is a bug in my version.

**Comment by fatkodima** [comment]
We also can have subclasses for Array or Hash 😅 
And this won't work now for child classes without custom serializers, which worked before.

**Comment by casperisfine** [comment]
> which worked before.

Which was a bug IMO. We can handle it by serializing as before and emitting a deprecation warning.

**Comment by casperisfine** [comment]
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "benchmark-ips"
  gem "activejob"#, path: "/local/copy/of/rails"
end

require "active_job"

class MyJob < ActiveJob::Base
  def perform(arguments)
  end

  def serialize_opt
    {
      "job_class"  => self.class.name,
      "job_id"     => job_id,
      "provider_job_id" => provider_job_id,
      "queue_name" => queue_name,
      "priority"   => priority,
      "arguments"  => serialize_arguments_if_needed_opt(arguments),
      "executions" => executions,
      "exception_executions" => exception_executions,
      "locale"     => I18n.locale.to_s,
      "timezone"   => timezone,
      "enqueued_at" => Time.now.utc.iso8601(9),
      "scheduled_at" => _scheduled_at_time ? _scheduled_at_time.utc.iso8601(9) : nil,
    }
  end

  def serialize_arguments_if_needed_opt(arguments)
    if arguments_serialized?
      @serialized_arguments
    else
      serialize_arguments_opt(arguments)
    end
  end

  def serialize_arguments_opt(arguments)
    ActiveJob::Arguments.serialize_opt(arguments)
  end
end

module ActiveJob
  module Arguments
    extend self
    def serialize_opt(arguments)
      arguments.map { |argument| serialize_argument_opt(argument) }
    end

    def serialize_argument_opt(argument)
      case argument
      when nil, true, false, Integer, Float # Types that can hardly be subclassed
        argument
      when String
        if argument.class == String
          argument
        else
          Serializers.serialize(argument)
        end
      when GlobalID::Identification
        convert_to_global_id_hash(argument)
      when Array
        argument.map { |arg| serialize_argument_opt(arg) }
      when ActiveSupport::HashWithIndifferentAccess
        serialize_indifferent_hash(argument)
      when Hash
        symbol_keys = argument.each_key.grep(Symbol).map!(&:to_s)
        aj_hash_key = if Hash.ruby2_keywords_hash?(argument)
          RUBY2_KEYWORDS_KEY
        else
          SYMBOL_KEYS_KEY
        end
        result = serialize_hash(argument)
        result[aj_hash_key] = symbol_keys
        result
      else
        if argument.respond_to?(:permitted?) && argument.respond_to?(:to_h)
          serialize_indifferent_hash(argument.to_h)
        elsif BigDecimal === argument && !ActiveJob.use_big_decimal_serializer
          ActiveJob.deprecator.warn(<<~MSG)
            Primitive serialization of BigDecimal job arguments is deprecated as it may serialize via .to_s using certain queue adapters.
            Enable config.active_job.use_big_decimal_serializer to use BigDecimalSerializer instead, which will be mandatory in Rails 7.2.

            Note that if your application has multiple replicas, you should only enable this setting after successfully deploying your app to Rails 7.1 first.
            This will ensure that during your deployment all replicas are capable of deserializing arguments serialized with BigDecimalSerializer.
          MSG
          argument
        else
          Serializers.serialize(argument)
        end
      end
    end
  end
end


args = ["string", 1, { key: [1, 2, 1.2], key2: "string2"}]
puts MyJob.new(args).serialize
puts MyJob.new(args).serialize_opt

Benchmark.ips do |x|
  x.report("old") do
    MyJob.new(args).serialize
  end

  x.report("opt") do
    MyJob.new(args).serialize_opt
  end

  x.compare!
end
```

Fixed version, similar perf.

> We also can have subclasses for Array or Hash 😅

Right, but that's pushing it a bit. String subclasses are rather common and invasive (`StringInquirer`, `SafeBuffer`, etc), Array and Hash sublcasses are more rare (execpt for HWIA but it's already handled).

We could handle them the same way in `when Array` and `when Hash` though.

**Comment by fatkodima** [comment]
Looks good 👍 Please, do open a PR 😅

**Comment by byroot** [comment]
I'm a bit swamped today, and this doesn't seem like a huge deal to me, feel free to take that code.
