### ISSUE TITLE
switch to dynamic database problem

### ISSUE THREAD

**Issue by zgid123** [rails/rails#50120]
### Steps to reproduce

Hi, I am using rails 7.1 and ruby 3.2.2. My business is multi-tenant: database per tenant. And also, the `db_config` must be fetched from other server, so I cannot use [this approach](https://guides.rubyonrails.org/active_record_multiple_databases.html#setting-up-your-application).

I created a class

```rb
class DatabaseService
  # rubocop:disable Style/ClassVars
  @@db_config = ActiveRecord::Base.connection_db_config.configuration_hash.deep_dup.freeze
  # rubocop:enable Style/ClassVars

  class << self
    def root_db_config
      @@db_config
    end

    def switch_database(db_config:)
      ActiveRecord::Base.establish_connection(db_config)

      return unless block_given?

      yield
    ensure
      # ActiveRecord::Base.close if block_given?
      # switch_root_database if block_given?
      ActiveRecord::Base.connection_pool.release_connection if block_given?
    end

    def switch_root_database
      ActiveRecord::Base.establish_connection(@@db_config)
    end
  end
end
```

Also, I created a middleware

```rb
# frozen_string_literal: true

class SwitchTenantDatabaseMiddleware
  def initialize(app)
    @app = app
  end

  def call(env)
    request = Rack::Request.new(env)

    domain = URI(request.referer).host
    tenant = get_tenant_by_domain(domain:)
    db_config = tenant['db_config'].symbolize_keys

    ActiveRecord::Base.connection_pool.with_connection do
      DatabaseService.switch_database(
        db_config: DatabaseService.root_db_config.merge(
          database: db_config[:database],
          username: db_config[:username],
          password: db_config[:password]
        )
      )
    end

    @app.call(env)
  ensure
    # DatabaseService.switch_root_database
    # ActiveRecord::Base.connection_pool.release_connection
    ActiveRecord::Base.connection.close
  end
end
```

### Expected behavior

Can connect to the database

### Actual behavior

Raise error `ActiveRecord::ConnectionNotEstablished: No connection pool for 'ActiveRecord::Base' found`

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

### Debug

- The ensure block is for trying to remove the connection from the pool to fix the bug, but it seems useless

- I log the `ActiveRecord::Base.connection_pool.stat` result to terminal, the result from the request before the one that raises error above is `{:size=>15, :connections=>3, :busy=>0, :dead=>0, :idle=>3, :waiting=>0, :checkout_timeout=>5.0}`, the size is still greater than the `connections`, but I still not understand why it still raise the error.

- When error, I checked this file `active_record/connection_adapters/abstract/connection_handler.rb`, the result of `connection_name_to_pool_manager[connection_name]` is `#<ActiveRecord::ConnectionAdapters::PoolManager:0x0000000108a4c910 @role_to_shard_mapping={:writing=>{}}>`, while the success one, the `:writing` will be an object instead of empty object.

Here the full backtrace

```
# [
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/activerecord/lib/active_record/connection_handling.rb:283:in `connection_pool'",
#   "app/services/database_service.rb:53:in `switch_database'",
#   "app/middlewares/switch_tenant_database_middleware.rb:22:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-3.0.8/lib/rack/etag.rb:29:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-3.0.8/lib/rack/conditional_get.rb:31:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-3.0.8/lib/rack/head.rb:15:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/activerecord/lib/active_record/migration.rb:654:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/activesupport/lib/active_support/callbacks.rb:101:in `run_callbacks'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/callbacks.rb:28:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/executor.rb:14:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/actionable_exceptions.rb:16:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sentry-rails-5.13.0/lib/sentry/rails/rescued_exception_interceptor.rb:9:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sentry-ruby-5.13.0/lib/sentry/rack/capture_exceptions.rb:13:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/railties/lib/rails/rack/logger.rb:37:in `call_app'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/railties/lib/rails/rack/logger.rb:24:in `block in call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/activesupport/lib/active_support/tagged_logging.rb:135:in `block in tagged'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/activesupport/lib/active_support/tagged_logging.rb:39:in `tagged'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/activesupport/lib/active_support/tagged_logging.rb:135:in `tagged'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/activesupport/lib/active_support/broadcast_logger.rb:240:in `method_missing'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/railties/lib/rails/rack/logger.rb:24:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/remote_ip.rb:92:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/request_id.rb:28:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-3.0.8/lib/rack/runtime.rb:24:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/activesupport/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/server_timing.rb:58:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/executor.rb:14:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/static.rb:25:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-3.0.8/lib/rack/sendfile.rb:114:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/actionpack/lib/action_dispatch/middleware/host_authorization.rb:141:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-cors-2.0.1/lib/rack/cors.rb:102:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-1fafbef7096e/railties/lib/rails/engine.rb:529:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma/configuration.rb:272:in `call'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma/request.rb:100:in `block in handle_request'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma/thread_pool.rb:378:in `with_force_shutdown'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma/request.rb:99:in `handle_request'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma/server.rb:443:in `process_client'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma/server.rb:241:in `block in run'",
#   ".rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma/thread_pool.rb:155:in `block in spawn_thread'"
# ]
```

**Comment by eileencodes** [comment]
Hi @zgid123 this isn't a bug in Rails. Your middleware is essentially clobbering the existing `ActiveRecord::Base` connection and that's not supported in a request. In your code, the connection is gone, it's not "switching" connection, it's "removing" the connection and creating a brand new one with a new config.

I don't have any plans to support this because it's dangerous to clobber connections in requests like this. You're also not returning the connection state at the end of your block. I strongly suggest using multiple databases as designed and finding another way to get the configurations. Hope that helps clarify how this is supposed to work.

**Comment by zgid123** [comment]
Thanks for your info. Could you help me about the connection pool? I tried to debug to know why the connection pool is not available while the size is greater than the total connection. Because the code base is too large for me to understand 😞

**Comment by zgid123** [comment]
I checked the activerecord code, it seems we cannot add more shard in runtime. My business is database per tenant, so whenever a tenant is created, we need to create new database for them. Can activerecord reload the config from database.yml in runtime? Or is there any workaround to add shard in runtime?

**Comment by zzak** [comment]
Hello @zgid123,

Unfortunately we are not able to provide support here and reserve the issue tracker specifically for bugs in the framework.

I recommend you start a new topic on [discuss](https://discuss.rubyonrails.org) if you're looking for help.

Thanks!

**Comment by sunil-sharma** [comment]
@zgid123 were you able to solve your issue with any other approach?

We have exactly same busn=iness use case and facing same issue.

**Comment by zgid123** [comment]
@sunil-sharma still no. I modify the `database.yml` whenever we start/restart the server to make it works. But it is not stable, to make it works stably, we need to restart the server whenever we have a new tenant.

I created a gem to serve this business problem here: https://github.com/zgid123/tenant_realm. It only contains my current business requirement, and I still not have enough time to improve this gem

**Comment by sunil-sharma** [comment]
Can you share sample database.yml and switching logic?
You can see my code here https://github.com/rails/rails/issues/52757

**Comment by zgid123** [comment]
@sunil-sharma all the code to switch db or load tenant are from my gem and my project already switched to that gem.

In my business, we have a different database and server to manage the tenant, in theory, you can use another database config and handle tenant in the same project. So using my gem, you need to pass the logic to get all the tenants' information

```rb
TenantRealm.configure do |config|
  config.fetch_tenant = lambda { |identifier|
    Tenant::Service.tenant(id: identifier)
  }

  config.fetch_tenants = lambda {
    Tenant::Service.tenants
  }

    config.dig_db_config = lambda { |tenant|
      tenant[:db_config]
    }

    config.identifier_resolver = lambda { |request|
      # get identifier from request
      # domain = request.referer || request.origin
      # domain ? URI(domain).host : nil
    }

    config.shard_name_from_tenant = lambda { |tenant|
      tenant[:slug]
    }
end
```

The response of tenant list must have `db config` inside that. And my gem will handle the logic to modify the database.yml for you. For more info, you can check the document of my gem
