### ISSUE TITLE
RuntimeError: can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by vill** [rails/rails#50154]
The `alias_attribute` method does not work after upgrading `Rails` from version `7.0.8` to version `7.1.2`. Perhaps everything went bad after [this request](https://github.com/rails/rails/pull/48533).

### Steps to reproduce
**Rails 7.0.8 - This works**
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.8"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :balance_transactions, force: true do |t|
    t.string :type, null: false
    t.string :old_field
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class BalanceTransaction < ApplicationRecord
  alias_attribute :new_field, :old_field
end

class BalanceTransaction
  class TopUp < BalanceTransaction
    self.abstract_class = true

    # Common validations, etc.
  end
end

class BalanceTransaction
  module Type
    class CashTopUp < BalanceTransaction::TopUp
    end
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    balance_transaction = BalanceTransaction::Type::CashTopUp.create!

    assert_equal 1, BalanceTransaction::Type::CashTopUp.count
  end
end
```
**Rails 7.1.2 - This doesn't work**
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :balance_transactions, force: true do |t|
    t.string :type, null: false
    t.string :old_field
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class BalanceTransaction < ApplicationRecord
  alias_attribute :new_field, :old_field
end

class BalanceTransaction
  class TopUp < BalanceTransaction
    self.abstract_class = true

    # Common validations, etc.
  end
end

class BalanceTransaction
  module Type
    class CashTopUp < BalanceTransaction::TopUp
    end
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    balance_transaction = BalanceTransaction::Type::CashTopUp.create!

    assert_equal 1, BalanceTransaction::Type::CashTopUp.count
  end
end
```
**Rails 7.1.2 - This works**
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :balance_transactions, force: true do |t|
    t.string :type, null: false
    t.string :old_field
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class BalanceTransaction < ApplicationRecord
  alias_attribute :new_field, :old_field
end

class BalanceTransaction
  class TopUp < BalanceTransaction
    self.abstract_class = true

    # Common validations, etc.
  end
end

class BalanceTransaction
  module Type
    class CashTopUp < BalanceTransaction::TopUp
    end
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    BalanceTransaction.new # <---- After this everything starts working

    balance_transaction = BalanceTransaction::Type::CashTopUp.create!

    assert_equal 1, BalanceTransaction::Type::CashTopUp.count
  end
end
```
**Rails 7.1.2 - This works**
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :balance_transactions, force: true do |t|
    t.string :type, null: false
    t.string :old_field
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class BalanceTransaction < ApplicationRecord
end

class BalanceTransaction
  class TopUp < BalanceTransaction
    self.abstract_class = true

    alias_attribute :new_field, :old_field # <--- Alias declaration moved here

    # Common validations, etc.
  end
end

class BalanceTransaction
  module Type
    class CashTopUp < BalanceTransaction::TopUp
    end
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    balance_transaction = BalanceTransaction::Type::CashTopUp.create!

    assert_equal 1, BalanceTransaction::Type::CashTopUp.count
  end
end
```
### Expected behavior
The `alias_attribute` method should create aliases without errors.

### Actual behavior
```
RuntimeError: can't add a new key into hash during iteration
    /usr/local/bundle/gems/activemodel-7.1.2/lib/active_model/attribute_methods.rb:376:in `block in aliases_by_attribute_name'
```
### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**Comment by rafaelfranca** [comment]
@vill was the fix for this issue backported? Can you check if https://github.com/rails/rails/pull/50701 fix your problem?

**Comment by rafaelfranca** [comment]
If you can confirm that issue is gone on 7-1-stable it would be great.

**Comment by rafaelfranca** [comment]
I just checked and 7-1-stable doesn't have the right fixes. I'll see to get them included.

**Comment by zzak** [comment]
I think this was fixed in #52844 but there was not a bugfix release of 7.1 which included it yet:
https://github.com/rails/rails/compare/v7.1.4.1...7-1-stable

If you can confirm by pointing your app at `7-1-stable` it would be appreciated.

**Comment by jrafanie** [comment]
I also see this still failing with 7-1-stable. It passes with 7-2-stable.

7-1-stable is currently:
```
commit 252723d69757ef16bda32b03199034a2c82e366e (grafted, HEAD -> 7-1-stable, origin/HEAD, origin/7-1-stable)
Author: Jean Boussier <jean.boussier@gmail.com>
Date:   Thu Oct 24 09:54:29 2024 +0200

    Avoid redefining IpAddr#as_json if it already exist

    Ref: https://github.com/ruby/ipaddr/pull/77
```



```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", :branch => "7-1-stable", :github => "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :balance_transactions, force: true do |t|
    t.string :type, null: false
    t.string :old_field
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class BalanceTransaction < ApplicationRecord
  alias_attribute :new_field, :old_field
end

class BalanceTransaction
  class TopUp < BalanceTransaction
    self.abstract_class = true

    # Common validations, etc.
  end
end

class BalanceTransaction
  module Type
    class CashTopUp < BalanceTransaction::TopUp
    end
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    balance_transaction = BalanceTransaction::Type::CashTopUp.create!

    assert_equal 1, BalanceTransaction::Type::CashTopUp.count
  end
end
```

```
  1) Error:
BugTest#test_association_stuff:
RuntimeError: can't add a new key into hash during iteration
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activemodel/lib/active_model/attribute_methods.rb:398:in `block in aliases_by_attribute_name'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activemodel/lib/active_model/attribute_methods.rb:208:in `alias_attribute'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:54:in `alias_attribute'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/model_schema.rb:634:in `block in load_schema!'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/model_schema.rb:625:in `each'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/model_schema.rb:625:in `load_schema!'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attributes.rb:264:in `load_schema!'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/encryption/encryptable_record.rb:127:in `load_schema!'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/model_schema.rb:567:in `block in load_schema'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/model_schema.rb:564:in `synchronize'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/model_schema.rb:564:in `load_schema'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/model_schema.rb:445:in `attribute_types'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:262:in `has_attribute?'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:103:in `alias_attribute_method_definition'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:88:in `block in generate_alias_attribute_methods'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:87:in `each'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:87:in `generate_alias_attribute_methods'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:76:in `block (4 levels) in generate_alias_attributes'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:75:in `each'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:75:in `block (3 levels) in generate_alias_attributes'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:74:in `each'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:74:in `block (2 levels) in generate_alias_attributes'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activesupport/lib/active_support/code_generator.rb:46:in `batch'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:73:in `block in generate_alias_attributes'
    /Users/joerafaniello/.gem/ruby/3.2.2/gems/mutex_m-0.2.0/lib/mutex_m.rb:77:in `synchronize'
    /Users/joerafaniello/.gem/ruby/3.2.2/gems/mutex_m-0.2.0/lib/mutex_m.rb:77:in `mu_synchronize'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:71:in `generate_alias_attributes'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:68:in `generate_alias_attributes'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods.rb:68:in `generate_alias_attributes'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/core.rb:792:in `init_internals'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/persistence.rb:1142:in `init_internals'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activemodel/lib/active_model/validations.rb:435:in `init_internals'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activemodel/lib/active_model/dirty.rb:366:in `init_internals'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/attribute_methods/dirty.rb:197:in `init_internals'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/timestamp.rb:103:in `init_internals'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/associations.rb:338:in `init_internals'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/autosave_association.rb:277:in `init_internals'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/transactions.rb:380:in `init_internals'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/touch_later.rb:50:in `init_internals'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/core.rb:450:in `initialize'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/inheritance.rb:76:in `new'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/inheritance.rb:76:in `new'
    /Users/joerafaniello/.gem/ruby/3.2.2/bundler/gems/rails-252723d69757/activerecord/lib/active_record/persistence.rb:54:in `create!'
    rails_issue50154.rb:55:in `test_association_stuff'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by zzak** [comment]
Indeed, that test still fails on 7-1-stable. I was able to dig up #50158 and #50701 but after trying various combinations of them, I was unable to get the test to pass and not break activerecord tests.

Also, 7.1.5 was the last bugfix release [I think](https://rubyonrails.org/maintenance), so even if we could find a way to fix this -- I'm not sure it will get merged. Perhaps it could land in the `7-1-stable` branch, but that is a big IF.

It's more likely that you'll have to find a monkey-patch until you can upgrade to 7.2.
