### ISSUE TITLE
ActiveRecord 7.1 regression in model scoping in callback when created from association

### ISSUE THREAD

**Issue by segiddins** [rails/rails#50368]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "rubygems"
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :versions, force: true do |t|
    t.references :api_key
    t.references :rubygem
    t.string :number
    t.string :platform
    t.boolean :latest, default: false
    t.boolean :indexed, default: false
  end

  create_table :rubygems, force: true do |t|
  end
  
  create_table :api_keys, force: true do |t|
  end
end

class Version < ActiveRecord::Base
  belongs_to :rubygem
  belongs_to :api_key
  
  after_save :reorder_versions, if: -> { saved_change_to_id? }
  delegate :reorder_versions, to: :rubygem
end

class Rubygem < ActiveRecord::Base
  has_many :versions
  
  def reorder_versions
      logger.info Version.all.to_sql

      versions_of_platforms = versions
        .group_by(&:platform)
        
      versions_of_platforms.each_value do |platforms|
        Version.find(platforms.max.id).update_column(:latest, true)
      end
    end
end

class ApiKey < ActiveRecord::Base
  has_many :versions
end

class BugTest < Minitest::Test
  def test_association_stuff
    gem1 = Rubygem.create!
    api_key = ApiKey.create!
    v1 = Version.create!(rubygem: gem1, platform: "ruby", indexed: true)
    v2 = Version.create!(rubygem: gem1, api_key:, platform: "ruby", indexed: true)
    
    api_key.versions.create_with(indexed: true).find_or_create_by!(
      rubygem: gem1, number: "0.1.0", platform: "ruby"
    )

    assert_equal 3, gem1.reload.versions.count
  end
end
```

### Expected behavior

On Rails 7.0.x, this test case passes
The logged `Version.all.to_sql` in the callback is `SELECT "versions".* FROM "versions"`

### Actual behavior

On Rails 7.1.2, the test case fails with

```
ActiveRecord::RecordNotFound: Couldn't find Version with 'id'=1 [WHERE "versions"."api_key_id" = ?]
    /Users/segiddins/.gem/ruby/3.2.2/gems/activerecord-7.1.0/lib/active_record/relation/finder_methods.rb:416:in `raise_record_not_found_exception!'
    /Users/segiddins/.gem/ruby/3.2.2/gems/activerecord-7.1.0/lib/active_record/relation/finder_methods.rb:522:in `find_one'
    /Users/segiddins/.gem/ruby/3.2.2/gems/activerecord-7.1.0/lib/active_record/relation/finder_methods.rb:499:in `find_with_ids'
    /Users/segiddins/.gem/ruby/3.2.2/gems/activerecord-7.1.0/lib/active_record/relation/finder_methods.rb:92:in `find'
    /Users/segiddins/.gem/ruby/3.2.2/gems/activerecord-7.1.0/lib/active_record/querying.rb:23:in `find'
    /Users/segiddins/.gem/ruby/3.2.2/gems/activerecord-7.1.0/lib/active_record/core.rb:245:in `find'
    Untitled.rb:59:in `block in reorder_versions'
    Untitled.rb:58:in `each_value'
    Untitled.rb:58:in `reorder_versions'
    Untitled.rb:46:in `reorder_versions'
```

And the logged query is `SELECT "versions".* FROM "versions" WHERE "versions"."api_key_id" = 1`

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**Comment by segiddins** [comment]
Potentially related to https://github.com/rails/rails/issues/44792#issuecomment-1739100120? Using `default_scoped` instead of `all` works across both rails versions

**Comment by fatkodima** [comment]
This started to fail after this change https://github.com/rails/rails/commit/023a3eb3c046091a5d52027393a6d29d0576da01#diff-18a561656864ea240daf46bdb1f50faace49f9ef74b90bcf667d9bbb17fce084R182 (cc @byroot)

Previously, `create!` was run in the same transaction, now `create!` is run in an inner transaction, see https://github.com/rails/rails/blob/9064735ec5cd3c679f8ffabc42532dd85223af58/activerecord/lib/active_record/relation.rb#L228-L229

Currently, you can fix it by calling `versions.reload.group_by(&:platform)`.

**Comment by byroot** [comment]
Hum, right, we can probably solve this by inlining the `create_or_find_by!` call and avoid that inner transaction?

**Comment by fatkodima** [comment]
Seems like no, because when something is raised inside a transaction (foreign key violation, for example), the transaction becomes invalid and no further operations can be done on it (like the `.find_by!` inside the `rescue`). With inner transaction, only "inner transaction becomes invalid" (savepoint is rolledback) and further SQL operations are working.

**Comment by p-schlickmann** [comment]
also happening on v.7.10 and v.7.11

v.7.0.8 is the lastest working version

**Comment by p-schlickmann** [comment]
I was able to fix this issue by just removing the inner transaction. See https://github.com/p-schlickmann/rails/commit/f2e59da0ff18e4743c88bc459c79ea4279756de0

I also ran the whole ActiveRecord test case sucessufully 🤔. But I wonder why that transaction was there in the first place?

1. The transaction just runs `create!`, which will fail fast.
2. In case it fails, we have a `rescue` block.
3. Why is there a rescue block for `create` (without `!`)?

Please let me know if I'm missing something obvious here, this is my first attempt on contributing to Rails 😀!

**Comment by fatkodima** [comment]
`rake test:postgresql TEST=test/cases/relations_test.rb` fails with these changes because of the reason I mentioned in my previous comment.

Also a small suggestion: when trying to write a test, try to stick with the existing models and produce the smallest possible test case.

**Comment by p-schlickmann** [comment]
Got it, makes sense.

Let me know if you have any suggestions on how we can fix this.

Honestly I'd rather have a rare race condition in 7.08 than having this regression in 7.1.x

**Comment by bparanj** [comment]
Here is the smallest possible test case:

```ruby
require "rubygems"
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# In-memory SQLite database setup
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

# Schema definition
ActiveRecord::Schema.define do
  create_table :versions, force: true do |t|
    t.references :api_key
    t.string :platform
  end

  create_table :api_keys, force: true do |t|
  end
end

# Model definitions
class Version < ActiveRecord::Base
  belongs_to :api_key
end

class ApiKey < ActiveRecord::Base
  has_many :versions
end

# Minimal test case
class BugTest < Minitest::Test
  def test_record_not_found
    api_key = ApiKey.create!
    Version.create!(platform: "ruby")

    # This line should raise ActiveRecord::RecordNotFound
    api_key.versions.find(1)
  end
end
```

**Comment by byroot** [comment]
Thanks for the reduced test case. I didn't have time to look at it today, but will try to fix this tomorrow (cc @casperisfine)

**Comment by casperisfine** [comment]
Alright, so the issue seem to be that on 7.1, when that callback is executed `Version` has a default scope applied, but it's not the case on 7.0.

I'm not too sure I understand why the extra transaction has an impact on the default scope though, but I'll keep digging.

**Comment by casperisfine** [comment]
In a way, I think the bug is much older than that, because `create_or_find_by!` do also apply a default scope to callbacks, which I don't think it should:

```ruby
# frozen_string_literal: true

require "rubygems"
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  if ENV["RAILS"] == "edge"
    gem "activerecord", path: "/Users/byroot/src/github.com/Shopify/rails"
  else
    gem "activerecord", "~> 7.0.0"
  end
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :versions, force: true do |t|
    t.references :api_key
    t.references :rubygem
    t.string :number
    t.string :platform
    t.boolean :latest, default: false
    t.boolean :indexed, default: false
  end

  create_table :rubygems, force: true do |t|
  end
  
  create_table :api_keys, force: true do |t|
  end
end

class Version < ActiveRecord::Base
  belongs_to :rubygem
  belongs_to :api_key
  
  after_save :reorder_versions, if: -> { saved_change_to_id? }
  delegate :reorder_versions, to: :rubygem
end

class Rubygem < ActiveRecord::Base
  has_many :versions
  
  def reorder_versions
      logger.info Version.all.to_sql

      versions_of_platforms = versions
        .group_by(&:platform)
        
      versions_of_platforms.each_value do |platforms|
        Version.find(platforms.max.id).update_column(:latest, true)
      end
    end
end

class ApiKey < ActiveRecord::Base
  has_many :versions
end

class BugTest < Minitest::Test
  def test_association_stuff
    Rubygem.connection.transaction do
      gem1 = Rubygem.create!
      api_key = ApiKey.create!
      v1 = Version.create!(rubygem: gem1, platform: "ruby", indexed: true)
      v2 = Version.create!(rubygem: gem1, api_key:, platform: "ruby", indexed: true)
    
      api_key.versions.create_with(indexed: true).create_or_find_by!(
        rubygem: gem1, number: "0.1.0", platform: "ruby"
      )

      Version.create!(rubygem: gem1, api_key:, platform: "ruby", indexed: true)

      assert_equal 3, gem1.reload.versions.count
    end
  end
end
```

So that's probably what we should fix.

**Comment by casperisfine** [comment]
Alright, I think I figured a proper fix: https://github.com/rails/rails/pull/50395

This is a fairly old bug so I'll have to backport it.

I also think that delegation need to be improved so it only apply to user defined methods.

**Comment by segiddins** [comment]
Ha, nice fix @casperisfine! Thanks for looking into this so quickly!
