### ISSUE TITLE
Using symbols when using 'to:' in routes.rb results in NoMethodError on startup

### ISSUE THREAD

**Issue by petru** [rails/rails#50465]
### Steps to reproduce
Creating routes using this syntax taken from the [API docs](https://api.rubyonrails.org/classes/ActionDispatch/Routing.html) 
```ruby
# In config/routes.rb
controller :blog do
  get 'blog/show',    to: :list
  get 'blog/delete',  to: :delete
  get 'blog/edit',    to: :edit
end
```

results in the following startup error:

```
22:06:26 web.1  | started with pid 2252567
22:06:26 css.1  | started with pid 2252568
22:06:27 web.1  | DEBUGGER: Debugger can attach via UNIX domain socket (/run/user/1001/rdbg-2252567)
22:06:27 web.1  | => Booting Puma
22:06:27 web.1  | => Rails 7.1.2 application starting in development 
22:06:27 web.1  | => Run `bin/rails server --help` for more startup options
22:06:27 web.1  | Exiting
22:06:27 web.1  | /home/ubuntu/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/actionpack-7.1.2/lib/action_dispatch/routing/mapper.rb:312:in `split_to': undefined method `include?' for an instance of Symbol (NoMethodError)
22:06:27 web.1  | 
22:06:27 web.1  |             if to&.include?("#")
22:06:27 web.1  |                  ^^^^^^^^^^
22:06:27 web.1  |       from /home/ubuntu/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/actionpack-7.1.2/lib/action_dispatch/routing/mapper.rb:220:in `normalize_options!'
```

### Expected behavior
Routes should be matched to their respective controller actions referenced by their symbols. 

### Actual behavior
Rails crashes on startup because **include?** is not a Symbol method. However, using **action:** instead of **to:** or providing strings such as **'controller#action'** works.

### System configuration
**Rails version**:
7.1.2
**Ruby version**:
3.3.0

**Comment by skipkayhil** [comment]
Hmm, so I found that 5726b1d1d7665c33830ad114f45258ecf772b7b6 did introduce a change that raises when `to`'s value is a symbol instead of a string. However, when I went to write a test I found that the referenced syntax raises a different error (once the `split_to` method is fixed):

```
ArgumentError: Missing :action key on routes definition, please check your routes.
```

I'll open a PR to restore the better error message, but I think this example in the docs should also be updated/removed because it doesn't look like it works

**Comment by bparanj** [comment]
I have verified this error.

```
rails s
=> Booting Puma
=> Rails 7.1.2 application starting in development 
=> Run `bin/rails server --help` for more startup options
Exiting
/home/ubuntu/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/actionpack-7.1.2/lib/action_dispatch/routing/mapper.rb:312:in `split_to': undefined method `include?' for an instance of Symbol (NoMethodError)

            if to&.include?("#")
```

**Comment by bparanj** [comment]
Here is a test case for this issue:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    controller :blog do
        get 'blog/show',    to: :list
      end    
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

Result:

```bash
gitpod /workspace/dawg (main) $ ruby 50465.rb
Fetching https://github.com/rails/rails.git
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/..........
/home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:312:in `split_to': undefined method `include?' for :list:Symbol (NoMethodError)

            if to&.include?("#")
                 ^^^^^^^^^^
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:220:in `normalize_options!'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:135:in `initialize'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:88:in `new'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:88:in `build'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:2021:in `add_route'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:1993:in `decomposed_match'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:1957:in `block in map_match'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:1951:in `each'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:1951:in `map_match'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:1699:in `match'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:772:in `map_method'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:725:in `get'
        from 50465.rb:27:in `block (2 levels) in <class:TestApp>'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/mapper.rb:923:in `controller'
        from 50465.rb:26:in `block in <class:TestApp>'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/route_set.rb:449:in `instance_exec'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/route_set.rb:449:in `eval_block'
        from /home/gitpod/.rvm/gems/ruby-3.2.2/bundler/gems/rails-dfc6adc2d2f9/actionpack/lib/action_dispatch/routing/route_set.rb:431:in `draw'
        from 50465.rb:25:in `<class:TestApp>'
        from 50465.rb:17:in `<main>'
```

**Comment by bparanj** [comment]
There is now a documentation PR related to this issue: https://github.com/rails/rails/pull/50523
