### ISSUE TITLE
ActiveStorage::DiskController fails for uploads when Content-Type / media type contains a parameter

### ISSUE THREAD

**Issue by alexandergitter** [rails/rails#50600]
`ActiveStorage::DiskController#update` returns a 422 error when the submitted content contains a parameter in its Content-Type / media type, for example `audio/ogg; codecs=opus`.

This issue appears to have been introduced in https://github.com/rails/rails/commit/5fb4703471ffb11dab9aa3855daeef9f592f6388

### Steps to reproduce
Here's a test case that fails in `ActiveStorage::DiskControllerTest`:

```ruby
test "directly uploading blob with content type parameters" do
  data = "Something else entirely!"
  blob = create_blob_before_direct_upload(
    byte_size: data.size, checksum: OpenSSL::Digest::MD5.base64digest(data), content_type: "audio/ogg; codecs=opus")

  put blob.service_url_for_direct_upload, params: data, headers: { "Content-Type" => "audio/ogg; codecs=opus" }
  assert_response :no_content
  assert_equal data, blob.download
end
```

### Expected behavior
The upload succeeds, since the content type from the uploaded content matches the content type in the direct upload token.

### Actual behavior
The request fails with 422 Unprocessable Content.

### System configuration
**Rails version**: 7.2.0.alpha (1702b6cbfd)

**Ruby version**: 3.2.2

**Comment by bparanj** [comment]
Here is the test case. I cannot reproduce this issue.

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails'
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem 'sqlite3'
end

require 'active_record/railtie'
require 'active_storage/engine'
require 'tmpdir'

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f

  config.root = __dir__
  config.hosts << 'example.org'
  config.eager_load = false
  config.session_store :cookie_store, key: 'cookie_store_key'
  config.secret_key_base = 'secret_key_base'
  

  config.logger = Logger.new($stdout)
  Rails.logger = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: 'Disk'
    }
  }
end

TestApp.routes.draw do
  default_url_options :host => "example.com"
end

ENV['DATABASE_URL'] = 'sqlite3::memory:'

Rails.application.initialize!

require ActiveStorage::Engine.root.join('db/migrate/20170806125915_create_active_storage_tables.rb').to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_one_attached :profile
end

require 'minitest/autorun'

class BugTest < Minitest::Test
  def test_upload_and_download
    user = User.create!(
      profile: {
        content_type: 'text/plain',
        filename: 'dummy.txt',
        io: ::StringIO.new('dummy')
      }
    )

    assert_equal 'dummy', user.profile.download
  end

  def create_blob_before_direct_upload(filename: 'hello.txt', byte_size: 0, checksum: 'abc',
                                       content_type: 'text/plain')
    ActiveStorage::Blob.create_before_direct_upload! filename:, byte_size:,
                                                     checksum:, content_type:
  end

  def test_directly_uploading_blob_with_content_type_parameters
    upload_data = 'Something else entirely!'
    blob = create_blob_before_direct_upload(
      byte_size: upload_data.size, checksum: OpenSSL::Digest::MD5.base64digest(upload_data), content_type: 'audio/ogg; codecs=opus'
    )
    # Upload a file to the blob
    blob.upload(StringIO.new(upload_data))

    download_data = blob.download

    assert_equal upload_data, download_data
  end
end
```

**Comment by alexandergitter** [comment]
@bparanj I believe your test case does not test `ActiveStorage::DiskController#update`, which is where this issue happens. You are calling `ActiveStorage::Blob#upload`.

**Comment by bparanj** [comment]
Please provide a test case to reproduce your problem.

**Comment by rafaelfranca** [comment]
He already did. See the description. You only need to put the test in the file he pointed at.

**Comment by bparanj** [comment]
Here is the modified test case:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f

  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }

  routes.draw do
    direct :main_app do
      ActiveStorage::Engine.routes.url_helpers.rails_blob_path(params[:id], only_path: true)
    end
  end
end


ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_one_attached :profile
end

require "minitest/autorun"

class DiskControllerTest < Minitest::Test

  def test_directly_uploading_blob_with_different_but_equivalent_content_type
    data = "Something else entirely!"
    user = User.create!
    user.profile.attach(
      io: StringIO.new(data), 
      filename: 'test.txt', 
      content_type: 'application/x-gzip'
    )

    put rails_blob_url(user.profile.blob), params: data, headers: { "Content-Type" => "application/x-gzip" }
    assert_response :no_content
    assert_equal data, user.profile.download
  end

  private

  def put(url, params: {}, headers: {})
    session = Rack::Test::Session.new(Rails.application)
    session.put(url, params, headers)
    @last_response = session.last_response
  end

  def last_response
    @last_response
  end

  def assert_response(type)
    response = last_response
    assert response.send("#{type}?"), "Expected response to be #{type}, but was #{response.status}"
  end

  def rails_blob_url(blob, disposition: :attachment)
    Rails.application.routes.default_url_options[:host] = 'localhost'
    Rails.application.routes.url_helpers.rails_blob_url(blob, disposition: disposition)
  end
end
```

I am getting 404:

```
Started PUT "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoiYmxvYl9pZCJ9fQ==--64d48bc30ced51a7b2646d0aadd1ed6493c25a84/test.txt?disposition=attachment" for 127.0.0.1 at 2024-01-05 16:54:20 +0000
E, [2024-01-05T16:54:20.293214 #7059] ERROR -- :   
ActionController::RoutingError (No route matches [PUT] "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoiYmxvYl9pZCJ9fQ==--64d48bc30ced51a7b2646d0aadd1ed6493c25a84/test.txt"):
  
test/cases/50600.rb:87:in `put'
test/cases/50600.rb:78:in `test_directly_uploading_blob_with_different_but_equivalent_content_type'
F

Failure:
DiskControllerTest#test_directly_uploading_blob_with_different_but_equivalent_content_type [test/cases/50600.rb:79]:
Expected response to be no_content, but was 404

bin/rails test test/cases/50600.rb:69

Finished in 0.221612s, 4.5124 runs/s, 4.5124 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by rafaelfranca** [comment]
Apply this diff in your local copy of Rails and you will get the error he is reporting

```diff
diff --git a/activestorage/test/controllers/disk_controller_test.rb b/activestorage/test/controllers/disk_controller_test.rb
index 4c5b24aa28..38e1d5e615 100644
--- a/activestorage/test/controllers/disk_controller_test.rb
+++ b/activestorage/test/controllers/disk_controller_test.rb
@@ -122,4 +122,14 @@ class ActiveStorage::DiskControllerTest < ActionDispatch::IntegrationTest
       params: "Something else entirely!", headers: { "Content-Type" => "text/plain" }
     assert_response :not_found
   end
+
+  test "directly uploading blob with content type parameters" do
+    data = "Something else entirely!"
+    blob = create_blob_before_direct_upload(
+      byte_size: data.size, checksum: OpenSSL::Digest::MD5.base64digest(data), content_type: "audio/ogg; codecs=opus")
+
+    put blob.service_url_for_direct_upload, params: data, headers: { "Content-Type" => "audio/ogg; codecs=opus" }
+    assert_response :no_content
+    assert_equal data, blob.download
+  end
 end
```

There is no need to try to reproduce in a script if it can be reproduced in the own Rails test suite.
