### ISSUE TITLE
Requiring `'active_support/core_ext/integer/time'` alone raises an exception

### ISSUE THREAD

**Issue by josegomezr** [rails/rails#50726]
### Steps to reproduce

In the latest rails update (7.1.2) our CI raises with:

```
+ bundle exec rake db:drop
rake aborted!
NoMethodError: undefined method `deprecator' for ActiveSupport:Module (NoMethodError)

  deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                          ^^^^^^^^^^^
Did you mean?  deprecate_constant
/home/jenkins/.bundle-rb3/gems/activesupport-7.1.2/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>'
/home/jenkins/.bundle-rb3/gems/activesupport-7.1.2/lib/active_support/core_ext/array/conversions.rb:8:in `<top (required)>'
<internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/home/jenkins/.bundle-rb3/gems/activesupport-7.1.2/lib/active_support/duration.rb:3:in `<top (required)>'
<internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/home/jenkins/.bundle-rb3/gems/activesupport-7.1.2/lib/active_support/core_ext/integer/time.rb:3:in `<top (required)>'
<internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/home/jenkins/workspace/scc-multibranch_PR-7225/glue/Rakefile:4:in `<top (required)>'
/home/jenkins/.bundle-rb3/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

When calling it manually:

```
$ irb.ruby3.2 
irb(main):001> require 'active_support/core_ext/integer/time'
/home/jenkins/.bundle-rb3/gems/activesupport-7.1.2/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)

  deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                          ^^^^^^^^^^^
Did you mean?  deprecate_constant
        from /home/jenkins/.bundle-rb3/gems/activesupport-7.1.2/lib/active_support/core_ext/array/conversions.rb:8:in `<top (required)>'
        from <internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:97:in `require'
        from <internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:97:in `require'
        from /home/jenkins/.bundle-rb3/gems/activesupport-7.1.2/lib/active_support/duration.rb:3:in `<top (required)>'
        from <internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:97:in `require'
        from <internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:97:in `require'
        from /home/jenkins/.bundle-rb3/gems/activesupport-7.1.2/lib/active_support/core_ext/integer/time.rb:3:in `<top (required)>'
        from <internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:40:in `require'
        from (irb):1:in `<main>'
        from /home/jenkins/.bundle-rb3/gems/irb-1.11.0/exe/irb:9:in `<top (required)>'
        from /usr/bin/irb.ruby3.2:25:in `load'
        from /usr/bin/irb.ruby3.2:25:in `<main>'
<internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': cannot load such file -- active_support/core_ext/integer/time (LoadError)
        from <internal:/usr/lib64/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from (irb):1:in `<main>'
        from /home/jenkins/.bundle-rb3/gems/irb-1.11.0/exe/irb:9:in `<top (required)>'
        from /usr/bin/irb.ruby3.2:25:in `load'
        from /usr/bin/irb.ruby3.2:25:in `<main>'
```

I went through the require file chain and it goes like:

- `Rakefile` requires [`active_support/core_ext/integer/time`](https://github.com/rails/rails/blob/v7.1.2/activesupport/lib/active_support/core_ext/integer/time.rb#L3)
- `active_support/core_ext/integer/time` requires  [`core_ext/numeric/time`](https://github.com/rails/rails/blob/v7.1.2/activesupport/lib/active_support/core_ext/numeric/time.rb#L3)
- `core_ext/numeric/time` requires [`active_support/duration`](https://github.com/rails/rails/blob/v7.1.2/activesupport/lib/active_support/duration.rb#L3)
- `active_support/duration` requires [`active_support/core_ext/array/conversions`](https://github.com/rails/rails/blob/v7.1.2/activesupport/lib/active_support/core_ext/array/conversions.rb#L108C46-L108C70)

where the error raises:

```ruby
# [...]
  deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
# [...]
```

Looks like `ActiveSupport.deprecator` from [`active_support/deprecator`](https://github.com/rails/rails/blob/v7.1.2/activesupport/lib/active_support/deprecator.rb) is not required/autoloaded anywhere when requiring `active_support/core_ext/integer/time` alone.

### Expected behavior
- Should not raise as the previous version (7.0.8)

### Actual behavior
- Raise an exception

### System configuration
**Rails version**: `rails 7.1.2`

**Ruby version**: `ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-linux-gnu]`

**Comment by matthewd** [comment]
You need to `require "active_support"` prior to requiring any individual files from the library.

**Comment by josegomezr** [comment]
Thanks @matthewd, is there a documentation link for this piece of knowledge?
