### ISSUE TITLE
Command rails server fails if all db configs have database_tasks: false

### ISSUE THREAD

**Issue by pjartarkar-mdsol** [rails/rails#50910]
### Steps to reproduce

Just put `database_tasks: false` in all configs in database.yml file, and try running `rails server`.

### Expected behavior
Server should run successfully.

### Actual behavior
rails server failed to run.
```ruby
=> Booting Puma
=> Rails 7.1.2 application starting in development 
=> Run `bin/rails server --help` for more startup options
Instrumentation: OpenTelemetry::Instrumentation::Faraday was successfully installed
Instrumentation: OpenTelemetry::Instrumentation::Rack was successfully installed
Instrumentation: OpenTelemetry::Instrumentation::ActionPack was successfully installed
Instrumentation: OpenTelemetry::Instrumentation::ActiveSupport was successfully installed
Instrumentation: OpenTelemetry::Instrumentation::Rails was successfully installed
Instrumentation: OpenTelemetry::Instrumentation::ConcurrentRuby was successfully installed
Instrumentation: OpenTelemetry::Instrumentation::Redis was successfully installed
Instrumentation: OpenTelemetry::Instrumentation::Mysql2 was successfully installed
Instrumentation: OpenTelemetry::Instrumentation::PG was successfully installed
Instrumentation: OpenTelemetry::Instrumentation::AwsSdk was successfully installed
Exiting
/Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/railtie.rb:151:in `block (3 levels) in <class:Railtie>': undefined method `name' for nil:NilClass (NoMethodError)

              db_config.name,
                       ^^^^^
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:62:in `block in on_load'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:61:in `each'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:61:in `on_load'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/railtie.rb:147:in `block (2 levels) in <class:Railtie>'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:94:in `block in execute_hook'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:77:in `each'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/application/finisher.rb:93:in `block in <module:Finisher>'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/initializable.rb:32:in `instance_exec'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/initializable.rb:32:in `run'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /Users/pjartarkar/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
        from /Users/pjartarkar/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /Users/pjartarkar/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /Users/pjartarkar/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /Users/pjartarkar/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
        from /Users/pjartarkar/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
        from /Users/pjartarkar/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
        from /Users/pjartarkar/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
        from /Users/pjartarkar/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/initializable.rb:60:in `run_initializers'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/application.rb:423:in `initialize!'
        from /Users/pjartarkar/Desktop/projects/myapp/config/environment.rb:5:in `<main>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/rack-2.2.8/lib/rack/builder.rb:116:in `eval'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/rack-2.2.8/lib/rack/builder.rb:116:in `new_from_string'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/rack-2.2.8/lib/rack/builder.rb:105:in `load_file'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/rack-2.2.8/lib/rack/builder.rb:66:in `parse_file'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/rack-2.2.8/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/rack-2.2.8/lib/rack/server.rb:249:in `app'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/rack-2.2.8/lib/rack/server.rb:422:in `wrapped_app'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:36:in `start'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:136:in `perform'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/command/base.rb:178:in `invoke_command'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/command/base.rb:73:in `perform'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/command.rb:71:in `block in invoke'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/commands.rb:18:in `<main>'
        from <internal:/Users/pjartarkar/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/Users/pjartarkar/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /Users/pjartarkar/.rvm/gems/ruby-3.2.2/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**Comment by eileencodes** [comment]
Hi @pjartarkar-mdsol, your title says `database_tasks: false` but your report says `database: false`. Which is correct? Also can you provide a sample application that reproduces the issue? Thanks!

**Comment by fatkodima** [comment]
Was able to reproduce. Indeed, the problem arises when we set `database_tasks` for all the databases, like
```yml
# config/database.yml
development:
  adapter: postgresql
  database: blog_development
  database_tasks: false
```

The fix is as simple as
```diff
diff --git a/activerecord/lib/active_record/railtie.rb b/activerecord/lib/active_record/railtie.rb
index 50d24b8a84..85f4106476 100644
--- a/activerecord/lib/active_record/railtie.rb
+++ b/activerecord/lib/active_record/railtie.rb
@@ -147,6 +147,7 @@ class Railtie < Rails::Railtie # :nodoc:
         config.after_initialize do |app|
           ActiveSupport.on_load(:active_record) do
             db_config = ActiveRecord::Base.configurations.configs_for(env_name: Rails.env).first
+            next if db_config.nil?

             filename = ActiveRecord::Tasks::DatabaseTasks.cache_dump_filename(
               db_config.name,
```

Considering that we do not dump schema caches for databases with `database_tasks: false`, we should not to try to load it too. But is it a realistic use case to have all databases managed by not Active Record (the reason to have `database_tasks: false` set)?

**Comment by pjartarkar-mdsol** [comment]
Hey @fatkodima , Yes we have use case where all databases has `database_tasks: false`. Its like an app doesn't have its own database but relies on data of other application.

**Comment by eileencodes** [comment]
I think the question is, do you want to be able to use the schema cache for these db configs? If so then the fix isn't to skip if `nil` but rather add `include_hidden: true`. Although, this task is pretty much useless if you're using multiple databases as it can only load for the default `ActiveRecord::Base` connection.

**Comment by rafaelfranca** [comment]
> Although, this task is pretty much useless if you're using multiple databases as it can only load for the default ActiveRecord::Base connection.

Not anymore. Matthew and Jean fixed this by mistake in https://github.com/rails/rails/pull/48716. See change on multi_db test in https://github.com/rails/rails/pull/50893

What I'm still to investigate is if we can just remove this initializer code now. It looks like it we can since as soon `define_attribute_methods` is called we will load the right schema cache if it file exists on disk.

But for 7.1, I prefer #50922.
