### ISSUE TITLE
counter_cache doesn't work with composite PKs

### ISSUE THREAD

**Issue by fragkakis** [rails/rails#50968]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :test_background_check_requests, force: true do |t|
    t.integer :candidate_id
    t.integer :account_id
    t.string :name
  end

  create_table :test_candidates, force: true, primary_key: %i[candidate_id account_id] do |t|
    t.integer :candidate_id
    t.integer :account_id
    t.integer :test_background_check_requests_count
    t.string :name
  end
end

class TestCandidate < ActiveRecord::Base
  self.primary_key = %i[candidate_id account_id]
  has_many :test_background_check_requests, query_constraints: [:candidate_id, :account_id], inverse_of: :test_candidate
end

class TestBackgroundCheckRequest < ActiveRecord::Base
  belongs_to :test_candidate, counter_cache: true, query_constraints: [:candidate_id, :account_id]
end

class BugTest < Minitest::Test
  def test_association_stuff
    test_candidate = TestCandidate.create!(candidate_id: 1, account_id: 1, name: "Foo Barson")
    test_candidate.test_background_check_requests.create!(candidate_id: 1, account_id: 1, name: "Background check request 1")

    assert_equal 1, TestBackgroundCheckRequest.count
    assert_equal 1, test_candidate.reload.test_background_check_requests_count
  end
end
```

### Expected behavior
It is expected that the creation of the `TestBackgroundCheckRequest` will succeed, and that the associated `TestCandidate` would have a `test_background_check_request_count` of `1`.

### Actual behavior

The creation of the `TestBackgroundCheckRequest` fails with the following exception:

```
3.2.2 :057 > candidate.test_background_check_requests.create!(candidate_id: 1, account_id: 1, name: "Background check request 1")
D, [2024-02-05T15:23:08.589637 #90419] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2024-02-05T15:23:08.589781 #90419] DEBUG -- :   TestBackgroundCheckRequest Create (0.2ms)  INSERT INTO "test_background_check_requests" ("candidate_id", "account_id", "name") VALUES (?, ?, ?) RETURNING "id"  [["candidate_id", 1], ["account_id", 1], ["name", "Background check request 1"]]
D, [2024-02-05T15:23:08.589958 #90419] DEBUG -- :   TRANSACTION (0.0ms)  rollback transaction
/Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:82:in `block (2 levels) in expand_from_hash': Expected corresponding value for ["candidate_id", "account_id"] to be an Array (ArgumentError)

              raise ArgumentError, "Expected corresponding value for #{key} to be an Array" unless ids_set.is_a?(Array)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:81:in `map'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:81:in `block in expand_from_hash'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:79:in `each'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:79:in `flat_map'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:79:in `expand_from_hash'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:25:in `build_from_hash'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/query_methods.rb:1530:in `build_where_clause'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/query_methods.rb:943:in `where!'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/counter_cache.rb:116:in `update_counters'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/locking/optimistic.rb:182:in `update_counters'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/persistence.rb:976:in `increment!'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/locking/optimistic.rb:64:in `increment!'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/callbacks.rb:436:in `increment!'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/associations/belongs_to_association.rb:106:in `update_counters'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/associations/belongs_to_association.rb:58:in `increment_counters'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/counter_cache.rb:203:in `block in _create_record'
	... 44 levels...
3.2.2 :058 > 
```

### System configuration
**Rails version**:
7.1.3
**Ruby version**:
3.2.2

**Comment by fatkodima** [comment]
Working on a fix.
