### ISSUE TITLE
no implicit conversion of String into Integer (TypeError) @env[name] 

### ISSUE THREAD

**Issue by luizkowalski** [rails/rails#51041]
### Steps to reproduce

I have a Rails app where the version is pointed to the `main` branch and just this morning, I noticed the following error popping up on my Sentry:

```ruby
TypeError: no implicit conversion of String into Integer (TypeError)

        @env[name]
             ^^^^
  from rack (3.0.9) lib/rack/request.rb:101:in `[]'
  from rack (3.0.9) lib/rack/request.rb:101:in `get_header'
  from rails (1a92af2b5140) actionpack/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
  from rails (1a92af2b5140) actionpack/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  from lograge (0.14.0) lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
  from rails (1a92af2b5140) railties/lib/rails/rack/logger.rb:28:in `call'
  from rails (1a92af2b5140) actionpack/lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
  from request_store (1.6.0) lib/request_store/middleware.rb:19:in `call'
  from rails (1a92af2b5140) actionpack/lib/action_dispatch/middleware/request_id.rb:33:in `call'
  from rack (3.0.9) lib/rack/method_override.rb:28:in `call'
  from rack (3.0.9) lib/rack/runtime.rb:24:in `call'
  from rails (1a92af2b5140) activesupport/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from rails (1a92af2b5140) actionpack/lib/action_dispatch/middleware/executor.rb:16:in `call'
  from rails (1a92af2b5140) actionpack/lib/action_dispatch/middleware/static.rb:27:in `call'
  from rack (3.0.9) lib/rack/sendfile.rb:114:in `call'
  from rails (1a92af2b5140) actionpack/lib/action_dispatch/middleware/assume_ssl.rb:24:in `call'
  from rails (1a92af2b5140) railties/lib/rails/engine.rb:536:in `call'
  from prometheus-client-mmap-1.1.1-x86_64 (linux) lib/prometheus/client/rack/exporter.rb:29:in `call'
  from rack (3.0.9) lib/rack/deflater.rb:47:in `call'
  from puma (6.4.2) lib/puma/configuration.rb:272:in `call'
  from puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
  from puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
  from puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
  from puma (6.4.2) lib/puma/server.rb:464:in `process_client'
  from puma (6.4.2) lib/puma/server.rb:245:in `block in run'
  from puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'

```

I reverted a couple of versions and tracked it down to this commit: https://github.com/rails/rails/commit/cd053bcedcec0f130a74a93abdfae3ca8dcd93c6

Before this commit, it works, with this commit and after, it triggers the error above

### System configuration
**Rails version**: latest from `main`

**Ruby version**: `3.3.0`

**Comment by fatkodima** [comment]
> from lograge (0.14.0) lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'

I think you should open a bug report in the `lograge`. It now incorrectly gets the `env` argument here https://github.com/roidrage/lograge/blob/2839d2c7786ba8b8cf1acb8ca705be1c3ee66e0d/lib/lograge/rails_ext/rack/logger.rb#L17, should be `env = args[1]`.

**Comment by luizkowalski** [comment]
Someone already did, I linked this issue there; thanks a lot @fatkodima, closing now
