### ISSUE TITLE
`ActiveRecord::Persistence#becomes` does not clone eager-loading state and can raise Strict Loading violations

### ISSUE THREAD

**Issue by seanpdoyle** [rails/rails#51217]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new($stdout)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text :type
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments, strict_loading: true
end

class Post::Special < Post
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_becomes_eager_loading
    comment = Comment.new

    Post.create! comments: [comment]
    post = Post.includes(:comments).last!

    assert_equal [comment], post.comments
    assert_equal [comment], post.becomes(Post::Special).comments
    # ActiveRecord::StrictLoadingViolationError: `Post::Special` is marked for strict_loading. The Comment association named `:comments` cannot be lazily loaded.
    #     activerecord/lib/active_record/core.rb:256:in 'ActiveRecord::Base.strict_loading_violation!'
    #     activerecord/lib/active_record/associations/association.rb:250:in 'ActiveRecord::Associations::Association#find_target'
    #     activerecord/lib/active_record/associations/collection_association.rb:274:in 'ActiveRecord::Associations::CollectionAssociation#load_target'
    #     activerecord/lib/active_record/associations/collection_proxy.rb:45:in 'ActiveRecord::Associations::CollectionProxy#load_target'
    #     activerecord/lib/active_record/associations/collection_proxy.rb:981:in 'ActiveRecord::Associations::CollectionProxy#=='
  end
end
```

### Expected behavior

Coercing an Active Record model instance from one class to a superclass through [#becomes](https://edgeapi.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-becomes) should preserve any eager-loading done on the instance. Interacting with the subsequent instance should not raise any eager loading violations.

### Actual behavior

Coercing an instance retrieved by queries with calls to [.includes](https://edgeapi.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-includes) does not clone that eager loading state into the newly returned instance. The `assert_equal [comment], post.becomes(Post).comments` line in test script above fails with the following:

```
Error:
BugTest#test_becomes_eager_loading:
ActiveRecord::StrictLoadingViolationError: `Post` is marked for strict_loading. The Comment association named `:comments` cannot be lazily loaded.
    /Users/seanpdoyle/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-3ecc26981476/activerecord/lib/active_record/core.rb:233:in `strict_loading_violation!'
    /Users/seanpdoyle/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-3ecc26981476/activerecord/lib/active_record/associations/association.rb:222:in `find_target'
    /Users/seanpdoyle/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-3ecc26981476/activerecord/lib/active_record/associations/collection_association.rb:270:in `load_target'
    /Users/seanpdoyle/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-3ecc26981476/activerecord/lib/active_record/associations/collection_proxy.rb:45:in `load_target'
    /Users/seanpdoyle/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-3ecc26981476/activerecord/lib/active_record/associations/collection_proxy.rb:968:in `=='
```

### System configuration
**Rails version**: `main`

**Ruby version**: `3.3.0`

**Comment by stevepolitodesign** [comment]
Also noting that calling `includes` on the class called by `becomes` does not work either:

```ruby
assert_equal [comment], post.becomes(Post.includes(:comments)).comments # <= This line fails
```

**Comment by stevepolitodesign** [comment]
The inverse also applies.  If we enable strict loading on a query, `post.becomes(Post).comments` will not raise.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new($stdout)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_becomes_eager_loading
    comment = Comment.new

    Post.create! comments: [comment]
    post = Post.strict_loading.last!

    assert_equal [comment], post.becomes(Post).comments # <= This line passes
    assert_equal [comment], post.comments # <= This line fails
  end
end
```

**Comment by dustinbrownman** [comment]
Just my 2 cents, but I think this is behaving as intended. According to [the docs](https://api.rubyonrails.org/v7.1.3/classes/ActiveRecord/Persistence.html#method-i-becomes), `becomes` returns an instance of the becoming class with the _attributes_ of the record, which doesn't necessarily include the associations. Maybe this can be worked around by manually setting the association.

```ruby
post = Post.includes(:comments).last!
new_post = post.becomes(Post)
new_post.comments = post.comments
post.comments
```

Perhaps this can become an enhancement on `becomes`, though I imagine it would be more complex to introspect the associations than it is to copy over the attributes.

**Comment by seanpdoyle** [comment]
This issue's bug script was resolved between the `8.1.1` release and the current `main`.

Using `git bisect`, I found https://github.com/rails/rails/pull/56228 (and https://github.com/rails/rails/pull/56228/commits/cc22e2c3ca0e1e33743230bcc7c645ced6ca3643), which short-circuits the `#becomes` call for the code sample shared above.

However, there is still an issue for more typical STI usage. I've re-opened this issue and updated the script to represent that issue.

**Comment by bogdan** [comment]
I believe it should be generalised further as the bug is related to loaded associations being lost when calling `becomes` not really involving `strict_loading`.

``` ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new($stdout)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text :type
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Post::Special < Post
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_becomes_eager_loading
    comment = Comment.new

    Post.create! comments: [comment]
    original = Post.preload(:comments).last!
    copied = original.becomes(Post::Special)

    assert_equal [comment], original.comments
    assert_predicate copied.comments, :loaded?
    assert_equal [comment], copied.comments
    # Expected #<ActiveRecord::Associations::CollectionProxy [#<Comment id: 1, post_id: 1>]> to be loaded?.
  end
end
```

**Comment by seanpdoyle** [comment]
I've executed the reproduction script shared in this issue's "Steps to reproduce" against today's `main`, and its tests are still failing.

**Comment by seanpdoyle** [comment]
I've executed the reproduction script shared in this issue's "Steps to reproduce" against today's `main`, and its tests are still failing in the same way that's described in the PR description and https://github.com/rails/rails/issues/51217#issuecomment-4005317034.

**Comment by bogdan** [comment]
@seanpdoyle please provide your feedback on #56295, maybe we can kickstart the review this way.
