### ISSUE TITLE
Running "rails new app" fails causes a JSON LoadError

### ISSUE THREAD

**Issue by lukehayes** [rails/rails#51256]
### Steps to reproduce
Run `rails new app`.

### Expected behavior
A new rails app should be created without error.

### Actual behavior
When runing `rails new app`  this error is generated:

```
Bundle complete! 14 Gemfile dependencies, 81 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle lock --add-platform=x86_64-linux
Writing lockfile to /home/luke/Desktop/app/Gemfile.lock
         run  bundle binstubs bundler
       rails  importmap:install
<internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- json (LoadError)
	from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/json.rb:49:in `init!'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/json.rb:42:in `install!'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache.rb:34:in `setup'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap.rb:68:in `setup'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap.rb:112:in `default_setup'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/setup.rb:5:in `<top (required)>'
	from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/luke/Desktop/app/config/boot.rb:4:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
       rails  turbo:install stimulus:install
<internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- json (LoadError)
	from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/json.rb:49:in `init!'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/json.rb:42:in `install!'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache.rb:34:in `setup'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap.rb:68:in `setup'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap.rb:112:in `default_setup'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/setup.rb:5:in `<top (required)>'
	from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/luke/Desktop/app/config/boot.rb:4:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'

```

Running anything like `rails server` inside the application causes this:

```
<internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- json (LoadError)
	from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/json.rb:49:in `init!'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/json.rb:42:in `install!'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache.rb:34:in `setup'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap.rb:68:in `setup'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap.rb:112:in `default_setup'
	from /home/luke/.local/share/gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/setup.rb:5:in `<top (required)>'
	from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/luke/Desktop/app/config/boot.rb:4:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'

```

### System configuration
**Rails version**:
`Rails 7.1.3.2`

**Ruby version**:
`ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]`

I will write a solution for this in the next comment. I just wanted to make a note of this issue here just in case someone else gets stuck like I did. It  might save them some time trying to work out why :+1:

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is a problem with the Ruby installation. It isn't Rails fault. Please do comment with the solution.

**Comment by lukehayes** [comment]
The solution I use for this is to just add `gem json` into the `Gemfile`.

**Comment by lukehayes** [comment]
@rafaelfranca Thanks for the tip - I will take a look at how I have it installed :+1:

**Comment by rafaelfranca** [comment]
The json gem is part of the Ruby stdlib so in theory it should be installed already. https://github.com/ruby/ruby/blob/master/tool/sync_default_gems.rb#L38
