### ISSUE TITLE
Missing Active Record encryption credential when using ActiveRecord::Encryption.without_encryption 

### ISSUE THREAD

**Issue by marvinthepa** [rails/rails#51297]
### Steps to reproduce

```ruby
class SchluesselBrett < ApplicationRecord
   encrypts :key 
   def destroy
     ActiveRecord::Encryption.without_encryption { super }
   end
end

Schluesselbrett.last.destroy
```
### Expected behavior
Destroy should work as there are no hooks that depend on the encrypted column.

We are using a custom key_provider that needs the user input of a Smartcard PIN every time an encrypted column is encrypted or decrypted.
Destruction of a model should work without decrypting it first so that the PIN is not necessary (we accept the fact that we have to ensure ourselves that no hooks will require the encrypted field to be decrypted).
In fact, the NullEncryptor that is used in without_encryption:

```ruby
        def without_encryption(&block)
          with_encryption_context encryptor: ActiveRecord::Encryption::NullEncryptor.new, &block
        end
```

does not make use of the default key provider (whose initialization is the cause of the backtrace below) anyway.

### Actual behavior
```
activerecord (7.1.3.2) lib/active_record/encryption/config.rb:43:in `block (2 levels) in <class:Config>'
activerecord (7.1.3.2) lib/active_record/encryption/context.rb:38:in `build_default_key_provider'
activerecord (7.1.3.2) lib/active_record/encryption/context.rb:25:in `key_provider'
activerecord (7.1.3.2) lib/active_record/encryption/configurable.rb:17:in `key_provider'
activerecord (7.1.3.2) lib/active_record/encryption/scheme.rb:92:in `default_key_provider'
activerecord (7.1.3.2) lib/active_record/encryption/scheme.rb:53:in `key_provider'
activerecord (7.1.3.2) lib/active_record/encryption/encrypted_attribute_type.rb:15:in `key_provider'
activerecord (7.1.3.2) lib/active_record/encryption/encrypted_attribute_type.rb:147:in `decryption_options'
activerecord (7.1.3.2) lib/active_record/encryption/encrypted_attribute_type.rb:90:in `block in decrypt'
activerecord (7.1.3.2) lib/active_record/encryption/scheme.rb:69:in `with_context'
activerecord (7.1.3.2) lib/active_record/encryption/encrypted_attribute_type.rb:15:in `with_context'
activerecord (7.1.3.2) lib/active_record/encryption/encrypted_attribute_type.rb:85:in `decrypt'
activerecord (7.1.3.2) lib/active_record/encryption/encrypted_attribute_type.rb:36:in `deserialize'
activemodel (7.1.3.2) lib/active_model/attribute.rb:175:in `type_cast'
activemodel (7.1.3.2) lib/active_model/attribute.rb:43:in `value'
activemodel (7.1.3.2) lib/active_model/attribute_set/builder.rb:43:in `fetch_value'
activerecord (7.1.3.2) lib/active_record/transactions.rb:421:in `block in restore_transaction_record_state'
activemodel (7.1.3.2) lib/active_model/attribute_set.rb:98:in `transform_values'
activemodel (7.1.3.2) lib/active_model/attribute_set.rb:98:in `map'
activerecord (7.1.3.2) lib/active_record/transactions.rb:420:in `restore_transaction_record_state'
activerecord (7.1.3.2) lib/active_record/transactions.rb:345:in `rolledback!'
activerecord (7.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:200:in `block in rollback_records'
activerecord (7.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:263:in `run_action_on_records'
activerecord (7.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:199:in `rollback_records'
activerecord (7.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:527:in `block in rollback_transaction'
activesupport (7.1.3.2) lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
activerecord (7.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:520:in `rollback_transaction'
activerecord (7.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:539:in `rescue in block in within_new_transaction'
activerecord (7.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:538:in `block in within_new_transaction'
activesupport (7.1.3.2) lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
activerecord (7.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
activerecord (7.1.3.2) lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
activerecord (7.1.3.2) lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
activerecord (7.1.3.2) lib/active_record/transactions.rb:305:in `destroy'
```

### Proposed solution

local workaround is something along the lines of:

```ruby
module ActiveRecord
  module Encryption
    module Contexts
...
      class_methods do
....  
        def without_encryption(&block)
          encryptor = ActiveRecord::Encryption::NullEncryptor.new
          key_provider = ActiveRecord::Encryption::NullKeyProvider.new
          ActiveRecord::Encryption.with_encryption_context(encryptor:, key_provider:, &block)
        end

...

    class NullKeyProvider
    end
```

I'm happy to try to provide a pull request if there is hope that it will be accepted.

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**:  3.2.2

**Comment by JoeDupuis** [comment]
One file repro:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :content
  end

end

class Post < ActiveRecord::Base
  encrypts :content
   def destroy
     ActiveRecord::Encryption.without_encryption { super }
   end
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create! content: :hello
    post.destroy
  end
end
```

**Comment by skipkayhil** [comment]
> I'm happy to try to provide a pull request if there is hope that it will be accepted.

Yes, PRs are welcome

**Comment by marvinthepa** [comment]
> One file repro:

This will not reproduce the bug mentioned above, as the create will already fail.

Use this instead:

```ruby
  class BugTest < Minitest::Test
    def test_association_stuff
      post = Post.create! 
      post.destroy
    end
  end
```

I am working on a pull request, but struggling a bit with the test right now.

**Comment by Edouard-chin** [comment]
I think this is similar to https://github.com/rails/rails/issues/54785 and https://github.com/rails/rails/issues/52748

I suggested a fix in https://github.com/rails/rails/pull/54826
