### ISSUE TITLE
Incompatible with nio4r 2.5.8 gem when running Bundle Install (Rails version 7.0.5.1)

### ISSUE THREAD

**Issue by huyhuynh-eh** [rails/rails#51293]
I'm using Macbook M3, OS Sonoma 14.4, ruby version is 2.7.8, rails 7.0.5.1, I'm facing this issue when run `bundle install` . I did install xcode version 15 , and using flag `-- --with-cflags=-Wno-implicit-function-declaration` . But the issue is remain the same. Can you help to resolve this issue. Thank you !

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/nio4r-2.5.8/ext/nio4r
/Users/huyhuynh/.rvm/rubies/ruby-2.7.8/bin/ruby -I /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0 -r ./siteconf20240310-16248-1vnj1e7.rb extconf.rb --with-cflags\=-Wno-error\=implicit-function-declaration
checking for unistd.h... yes
checking for linux/aio_abi.h... no
checking for linux/io_uring.h... no
checking for sys/select.h... yes
checking for port_event_t in poll.h... no
checking for sys/epoll.h... no
checking for sys/event.h... yes
checking for sys/queue.h... yes
checking for port_event_t in port.h... no
checking for sys/resource.h... yes
creating Makefile

current directory: /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/nio4r-2.5.8/ext/nio4r
make "DESTDIR=" clean

current directory: /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/nio4r-2.5.8/ext/nio4r
make "DESTDIR="
compiling bytebuffer.c
compiling monitor.c
compiling nio4r_ext.c
In file included from nio4r_ext.c:6:
./../libev/ev.c:573:48: warning: '/*' within block comment [-Wcomment]
/*#define MIN_INTERVAL  0.00000095367431640625 /* 1/2**20, good till 2200 */
                                               ^
./../libev/ev.c:2136:31: warning: 'extern' variable has an initializer [-Wextern-initializer]
  EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                              ^
In file included from nio4r_ext.c:6:
In file included from ./../libev/ev.c:3080:
./../libev/ev_kqueue.c:133:32: warning: left operand of comma operator has no effect [-Wunused-value]
                      assert (("libev: kqueue found invalid fd", 0));
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
In file included from ./../libev/ev.c:3080:
./../libev/ev_kqueue.c:139:28: warning: left operand of comma operator has no effect [-Wunused-value]
                  assert (("libev: kqueue found invalid fd", 0));
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
In file included from ./../libev/ev.c:3092:
./../libev/ev_poll.c:113:18: warning: left operand of comma operator has no effect [-Wunused-value]
        assert (("libev: poll returned illegal result, broken BSD kernel?", p < polls + pollcnt));
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
In file included from ./../libev/ev.c:3092:
./../libev/ev_poll.c:121:26: warning: left operand of comma operator has no effect [-Wunused-value]
                assert (("libev: poll found invalid fd in poll set", 0));
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:3568:12: warning: left operand of comma operator has no effect [-Wunused-value]
  assert (("libev: watcher has invalid priority", ABSPRI (w) >= 0 && ABSPRI (w) < NUMPRI));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:3571:14: warning: left operand of comma operator has no effect [-Wunused-value]
    assert (("libev: pending watcher not on pending queue", pendings [ABSPRI (w)][w->pending - 1].w == w));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:3582:16: warning: left operand of comma operator has no effect [-Wunused-value]
      assert (("libev: active index mismatch in heap", ev_active (ANHE_w (heap [i])) == i));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:3583:16: warning: left operand of comma operator has no effect [-Wunused-value]
      assert (("libev: heap condition violated", i == HEAP0 || ANHE_at (heap [HPARENT (i)]) <= ANHE_at (heap [i])));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:3584:16: warning: left operand of comma operator has no effect [-Wunused-value]
      assert (("libev: heap at cache mismatch", ANHE_at (heap [i]) == ev_at (ANHE_w (heap [i]))));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:3596:16: warning: left operand of comma operator has no effect [-Wunused-value]
      assert (("libev: active index mismatch", ev_active (ws [cnt]) == cnt + 1));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:3614:14: warning: left operand of comma operator has no effect [-Wunused-value]
    assert (("libev: negative fd in fdchanges", fdchanges [i] >= 0));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:3627:24: warning: left operand of comma operator has no effect [-Wunused-value]
              assert (("libev: io watcher list contains a loop", w != w2));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:3631:20: warning: left operand of comma operator has no effect [-Wunused-value]
          assert (("libev: inactive fd watcher on anfd list", ev_active (w) == 1));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:3632:20: warning: left operand of comma operator has no effect [-Wunused-value]
          assert (("libev: fd mismatch between watcher and anfd", ((ev_io *)w)->fd == i));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:3818:24: warning: left operand of comma operator has no effect [-Wunused-value]
              assert (("libev: negative ev_timer repeat value found while processing timers", w->repeat > EV_TS_CONST (0.)));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:3881:24: warning: left operand of comma operator has no effect [-Wunused-value]
              assert (("libev: ev_periodic reschedule callback returned time in the past", ev_at (w) >= ev_rt_now));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4043:12: warning: left operand of comma operator has no effect [-Wunused-value]
  assert (("libev: ev_loop recursion during release detected", loop_done != EVBREAK_RECURSE));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4228:22: warning: left operand of comma operator has no effect [-Wunused-value]
            assert (("libev: pipe_w not active, but pipe not written", ev_is_active (&pipe_w)));
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4402:12: warning: left operand of comma operator has no effect [-Wunused-value]
  assert (("libev: ev_io_start called with negative fd", fd >= 0));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4403:12: warning: left operand of comma operator has no effect [-Wunused-value]
  assert (("libev: ev_io_start called with illegal event mask", !(w->events & ~(EV__IOFDSET | EV_READ | EV_WRITE))));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4415:12: warning: left operand of comma operator has no effect [-Wunused-value]
  assert (("libev: ev_io_start called with corrupted watcher", ((WL)w)->next != (WL)w));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4431:12: warning: left operand of comma operator has no effect [-Wunused-value]
  assert (("libev: ev_io_stop called with illegal fd (must stay constant after start!)", w->fd >= 0 && w->fd < anfdmax));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4455:12: warning: left operand of comma operator has no effect [-Wunused-value]
  assert (("libev: ev_timer_start called with negative timer repeat value", w->repeat >= 0.));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4484:14: warning: left operand of comma operator has no effect [-Wunused-value]
    assert (("libev: internal timer heap corruption", ANHE_w (timers [active]) == (WT)w));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4553:16: warning: left operand of comma operator has no effect [-Wunused-value]
      assert (("libev: ev_periodic_start called with negative interval value", w->interval >= 0.));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4586:14: warning: left operand of comma operator has no effect [-Wunused-value]
    assert (("libev: internal periodic heap corruption", ANHE_w (periodics [active]) == (WT)w));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4625:12: warning: left operand of comma operator has no effect [-Wunused-value]
  assert (("libev: ev_signal_start called with illegal signal number", w->signum > 0 && w->signum < EV_NSIG));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4628:12: warning: left operand of comma operator has no effect [-Wunused-value]
  assert (("libev: a signal must not be attached to two different loops",
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:4747:12: warning: left operand of comma operator has no effect [-Wunused-value]
  assert (("libev: child watchers are only supported in the default loop", loop == ev_default_loop_ptr));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
In file included from nio4r_ext.c:6:
./../libev/ev.c:5334:14: warning: left operand of comma operator has no effect [-Wunused-value]
    assert (("libev: loop to be embedded is not embeddable", backend & ev_embeddable_backends ()));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
32 warnings generated.
compiling selector.c
selector.c:301:26: error: incompatible function pointer types passing 'VALUE (*)(VALUE *)' (aka 'unsigned long (*)(unsigned long *)') to parameter of type 'VALUE (*)(VALUE)' (aka 'unsigned long (*)(unsigned long)')
[-Wincompatible-function-pointer-types]
        return rb_ensure(func, (VALUE)args, NIO_Selector_unlock, self);
                         ^~~~
/Users/huyhuynh/.rvm/rubies/ruby-2.7.8/include/ruby-2.7.0/ruby/ruby.h:1992:24: note: passing argument to parameter here
VALUE rb_ensure(VALUE(*)(VALUE),VALUE,VALUE(*)(VALUE),VALUE);
                       ^
1 error generated.
make: *** [selector.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/nio4r-2.5.8 for inspection.
Results logged to /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/extensions/arm64-darwin-23/2.7.0/nio4r-2.5.8/gem_make.out

  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/ext/builder.rb:99:in `run'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/ext/builder.rb:51:in `block in make'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/ext/builder.rb:43:in `each'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/ext/builder.rb:43:in `make'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tempfile.rb:291:in `open'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:30:in `build'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/ext/builder.rb:169:in `block in build_extension'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `synchronize'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `build_extension'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/ext/builder.rb:210:in `block in build_extensions'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `each'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `build_extensions'
  /Users/huyhuynh/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/rubygems/installer.rb:844:in `build_extensions'
  /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/bundler-2.4.17/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/bundler-2.4.17/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/bundler-2.4.17/lib/bundler/source/rubygems.rb:202:in `install'
  /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/bundler-2.4.17/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/bundler-2.4.17/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/bundler-2.4.17/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/bundler-2.4.17/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/bundler-2.4.17/lib/bundler/worker.rb:62:in `apply_func'
  /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/bundler-2.4.17/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/bundler-2.4.17/lib/bundler/worker.rb:54:in `loop'
  /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/bundler-2.4.17/lib/bundler/worker.rb:54:in `process_queue'
  /Users/huyhuynh/.rvm/gems/ruby-2.7.8@2.7.8XXX/gems/bundler-2.4.17/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing nio4r (2.5.8), and Bundler cannot continue.

In Gemfile:
  bootstrap-kaminari-views was resolved to 0.0.5, which depends on
    rails was resolved to 7.0.5.1, which depends on
      actioncable was resolved to 7.0.5.1, which depends on
        nio4r


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```

**Comment by JoeDupuis** [comment]
This does not look like a Rails issue and it looks like it might already be fixed in a newer version of nio4r. 

Try `bundle update nio4r`. If that does not fix it, post your `Gemfile.lock`. There might be a gem preventing it from resolving a version with the fix.

**Comment by skipkayhil** [comment]
Closing as not a Rails issue, and we reserve the issue tracker for bugs in Rails.
