### ISSUE TITLE
Can't use Model.exists? with composite primary keys

### ISSUE THREAD

**Issue by djpate** [rails/rails#51295]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails'
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true, primary_key: %i[user_id account_id] do |t|
    t.integer 'user_id', null: false
    t.integer 'account_id', null: false
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    Post.create!(user_id: 1, account_id: 1)

    assert_equal [1, 1], Post.find([1, 1]).id
    assert_equal true, Post.exists?([1, 1])
  end
end

```

### Expected behavior
```exists?``` should return a boolean if a given row exist for this primary key, like it does for not composite keys.

### Actual behavior
```
NoMethodError: undefined method `include?' for 1:Integer

        elsif statement.include?("?")
                       ^^^^^^^^^
    /home/pate/.rvm/gems/ruby-3.1.2/gems/activerecord-7.1.3.2/lib/active_record/sanitization.rb:167:in `sanitize_sql_array'
    /home/pate/.rvm/gems/ruby-3.1.2/gems/activerecord-7.1.3.2/lib/active_record/sanitization.rb:37:in `sanitize_sql_for_conditions'
    /home/pate/.rvm/gems/ruby-3.1.2/gems/activerecord-7.1.3.2/lib/active_record/relation/query_methods.rb:1513:in `build_where_clause'
    /home/pate/.rvm/gems/ruby-3.1.2/gems/activerecord-7.1.3.2/lib/active_record/relation/query_methods.rb:943:in `where!'
    /home/pate/.rvm/gems/ruby-3.1.2/gems/activerecord-7.1.3.2/lib/active_record/relation/finder_methods.rb:437:in `construct_relation_for_exists'
    /home/pate/.rvm/gems/ruby-3.1.2/gems/activerecord-7.1.3.2/lib/active_record/relation/finder_methods.rb:366:in `exists?'
    /home/pate/.rvm/gems/ruby-3.1.2/gems/activerecord-7.1.3.2/lib/active_record/querying.rb:23:in `exists?'
    bug_report.rb:40:in `test_association_stuff'
```

### System configuration
**Rails version**:  7.1.3.2

**Ruby version**: 3.1

**Comment by JoeDupuis** [comment]
I've submitted a [PR](https://github.com/rails/rails/pull/51301) that could address this, It might not get accepted as [this clash with the existing api](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/relation/finder_methods.rb#L351), so I would not wait on it. 

Alternatively you could use the hash form. It's not super pretty, but it would work:

```ruby
Post.exists?(Post.primary_key => [[1, 1]])
```
