### ISSUE TITLE
`PessimisticLockingTest#test_no_locks_no_wait` gets `ERROR:  cached plan must not change result type`

### ISSUE THREAD

**Issue by yahonda** [rails/rails#51347]
Managed to reproduce CI error.
https://buildkite.com/rails/rails/builds/105748#018e558b-b895-43cc-aa80-71180e80d01b/1235-1330

### Steps to reproduce
```ruby
git clone https://github.com/rails/rails
cd rails/activerecord
bundle install
bundle exec rake db:postgresql:rebuild
ARCONN=postgresql bin/test test/cases/associations/nested_through_associations_test.rb test/cases/connection_management_test.rb test/cases/migration_test.rb test/cases/locking_test.rb -n "/^(?:NestedThroughAssociationsTest#(?:test_has_many_through_with_foreign_key_option_on_through_reflection)|ActiveRecord::ConnectionAdapters::ConnectionManagementTest#(?:test_cancel_asynchronous_queries_if_an_exception_is_raised)|MigrationTest#(?:test_instance_based_migration_up)|PessimisticLockingTest#(?:test_no_locks_no_wait))$/" --seed 38135
```

### Expected behavior
It should pass.

### Actual behavior
`PessimisticLockingTest#test_no_locks_no_wait` gets `ERROR:  cached plan must not change result type`.

```ruby
$ ARCONN=postgresql bin/test test/cases/associations/nested_through_associations_test.rb test/cases/connection_management_test.rb test/cases/migration_test.rb test/cases/locking_test.rb -n "/^(?:NestedThroughAssociationsTest#(?:test_has_many_through_with_foreign_key_option_on_through_reflection)|ActiveRecord::ConnectionAdapters::ConnectionManagementTest#(?:test_cancel_asynchronous_queries_if_an_exception_is_raised)|MigrationTest#(?:test_instance_based_migration_up)|PessimisticLockingTest#(?:test_no_locks_no_wait))$/" --seed 38135
Using postgresql
Run options: -n "/^(?:NestedThroughAssociationsTest#(?:test_has_many_through_with_foreign_key_option_on_through_reflection)|ActiveRecord::ConnectionAdapters::ConnectionManagementTest#(?:test_cancel_asynchronous_queries_if_an_exception_is_raised)|MigrationTest#(?:test_instance_based_migration_up)|PessimisticLockingTest#(?:test_no_locks_no_wait))$/" --seed 38135

# Running:

...#<Thread:0x000078a1a0d27b38 /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/locking_test.rb:809 run> terminated with exception (report_on_exception is true):
/home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:915:in `rescue in exec_cache': ERROR:  cached plan must not change result type (ActiveRecord::PreparedStatementCacheExpired)
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:893:in `exec_cache'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:865:in `execute_and_clear'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:66:in `internal_exec_query'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:630:in `select'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:71:in `select_all'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:222:in `select_all'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/querying.rb:62:in `_query_by_sql'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/querying.rb:51:in `find_by_sql'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/statement_cache.rb:150:in `execute'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/core.rb:434:in `cached_find_by'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/core.rb:255:in `find'
	from /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/locking_test.rb:788:in `block in test_no_locks_no_wait'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:536:in `block in within_new_transaction'
	from /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:533:in `within_new_transaction'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:223:in `block in transaction'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:387:in `with_connection'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_handling.rb:270:in `with_connection'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:222:in `transaction'
	from /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/locking_test.rb:812:in `block in duel'
/home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:903:in `exec_prepared': PG::FeatureNotSupported: ERROR:  cached plan must not change result type (ActiveRecord::StatementInvalid)
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:903:in `block (2 levels) in exec_cache'
	from /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1112:in `log'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:902:in `block in exec_cache'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:997:in `block in with_raw_connection'
	from /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:969:in `with_raw_connection'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:898:in `exec_cache'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:865:in `execute_and_clear'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:66:in `internal_exec_query'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:630:in `select'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:71:in `select_all'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:222:in `select_all'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/querying.rb:62:in `_query_by_sql'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/querying.rb:51:in `find_by_sql'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/statement_cache.rb:150:in `execute'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/core.rb:434:in `cached_find_by'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/core.rb:255:in `find'
	from /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/locking_test.rb:788:in `block in test_no_locks_no_wait'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:536:in `block in within_new_transaction'
	from /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:533:in `within_new_transaction'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:223:in `block in transaction'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:387:in `with_connection'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_handling.rb:270:in `with_connection'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:222:in `transaction'
	from /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/locking_test.rb:812:in `block in duel'
/home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:903:in `exec_prepared': ERROR:  cached plan must not change result type (PG::FeatureNotSupported)
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:903:in `block (2 levels) in exec_cache'
	from /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1112:in `log'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:902:in `block in exec_cache'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:997:in `block in with_raw_connection'
	from /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:969:in `with_raw_connection'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:898:in `exec_cache'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:865:in `execute_and_clear'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:66:in `internal_exec_query'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:630:in `select'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:71:in `select_all'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:222:in `select_all'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/querying.rb:62:in `_query_by_sql'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/querying.rb:51:in `find_by_sql'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/statement_cache.rb:150:in `execute'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/core.rb:434:in `cached_find_by'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/core.rb:255:in `find'
	from /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/locking_test.rb:788:in `block in test_no_locks_no_wait'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:536:in `block in within_new_transaction'
	from /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:533:in `within_new_transaction'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:223:in `block in transaction'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:387:in `with_connection'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_handling.rb:270:in `with_connection'
	from /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:222:in `transaction'
	from /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/locking_test.rb:812:in `block in duel'
Found 1 leaked connections
owner: #<Thread:0x000078a1a0d27ca0 /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/locking_test.rb:799 sleep>
backtrace:
["/home/yahonda/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:53:in `sleep'", "/home/yahonda/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:53:in `wait'", "/home/yahonda/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:53:in `ns_wait'", "/home/yahonda/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/abstract_lockable_object.rb:47:in `ns_wait_until'", "/home/yahonda/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/event.rb:87:in `block in wait'", "/home/yahonda/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'", "/home/yahonda/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'", "/home/yahonda/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'", "/home/yahonda/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/event.rb:84:in `wait'", "/home/yahonda/src/github.com/rails/rails/activerecord/test/cases/locking_test.rb:804:in `block (2 levels) in duel'", "/home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:536:in `block in within_new_transaction'", "/home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'", "/home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:533:in `within_new_transaction'", "/home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'", "/home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:223:in `block in transaction'", "/home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:387:in `with_connection'", "/home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_handling.rb:270:in `with_connection'", "/home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:222:in `transaction'", "/home/yahonda/src/github.com/rails/rails/activerecord/test/cases/locking_test.rb:801:in `block in duel'"]

E

Error:
PessimisticLockingTest#test_no_locks_no_wait:
ActiveRecord::PreparedStatementCacheExpired: ERROR:  cached plan must not change result type

    lib/active_record/connection_adapters/postgresql_adapter.rb:915:in `rescue in exec_cache'
    lib/active_record/connection_adapters/postgresql_adapter.rb:893:in `exec_cache'
    lib/active_record/connection_adapters/postgresql_adapter.rb:865:in `execute_and_clear'
    lib/active_record/connection_adapters/postgresql/database_statements.rb:66:in `internal_exec_query'
    lib/active_record/connection_adapters/abstract/database_statements.rb:630:in `select'
    lib/active_record/connection_adapters/abstract/database_statements.rb:71:in `select_all'
    lib/active_record/connection_adapters/abstract/query_cache.rb:222:in `select_all'
    lib/active_record/querying.rb:62:in `_query_by_sql'
    lib/active_record/querying.rb:51:in `find_by_sql'
    lib/active_record/statement_cache.rb:150:in `execute'
    lib/active_record/core.rb:434:in `cached_find_by'
    lib/active_record/core.rb:255:in `find'
    test/cases/locking_test.rb:788:in `block in test_no_locks_no_wait'
    lib/active_record/connection_adapters/abstract/transaction.rb:536:in `block in within_new_transaction'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
    lib/active_record/connection_adapters/abstract/transaction.rb:533:in `within_new_transaction'
    lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
    lib/active_record/transactions.rb:223:in `block in transaction'
    lib/active_record/connection_adapters/abstract/connection_pool.rb:387:in `with_connection'
    lib/active_record/connection_handling.rb:270:in `with_connection'
    lib/active_record/transactions.rb:222:in `transaction'
    test/cases/locking_test.rb:812:in `block in duel'

Error:
PessimisticLockingTest#test_no_locks_no_wait:
RuntimeError: Found 1 leaked connection after PessimisticLockingTest#test_no_locks_no_wait
    test/cases/test_case.rb:82:in `check_connection_leaks'
    test/cases/test_case.rb:38:in `after_teardown'


bin/test test/cases/locking_test.rb:787



Finished in 1.057243s, 3.7834 runs/s, 10.4044 assertions/s.
4 runs, 11 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]

**Comment by yahonda** [comment]
It still reproduces with the latest main branch.
