### ISSUE TITLE
counter_cache doesn't work with composite PKs (revisited)

### ISSUE THREAD

**Issue by fragkakis** [rails/rails#51465]
In the past I opened issue [#50968](https://github.com/rails/rails/issues/50968) about `counter_cache` not working with composite PKs. The corresponding PR fixed the error, but I still have a case in my codebase where I still get a different error.

### Steps to reproduce

Unfortunately I was not able to reproduce this with a script, so the script below does NOT reproduce the error. In any case, I am attaching it is because this is my mapping. The difference between my codebase and the script below is that I am running against Postgres, however I don't see how that could play a role.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :test_background_check_requests, force: true do |t|
    t.integer :candidate_id
    t.integer :account_id
    t.string :name
  end

  create_table :test_candidates, force: true, primary_key: %i[candidate_id account_id] do |t|
    t.integer :candidate_id
    t.integer :account_id
    t.integer :test_background_check_requests_count
    t.string :name
  end
end

class TestCandidate < ActiveRecord::Base
  self.primary_key = %i[candidate_id account_id]
  has_many :test_background_check_requests, query_constraints: [:candidate_id, :account_id], inverse_of: :test_candidate
end

class TestBackgroundCheckRequest < ActiveRecord::Base
  belongs_to :test_candidate, counter_cache: true, query_constraints: [:candidate_id, :account_id]
end

class BugTest < Minitest::Test
  def test_association_stuff
    test_candidate = TestCandidate.create!(candidate_id: 1, account_id: 1, name: "Foo Barson")
    test_candidate.test_background_check_requests.create!(candidate_id: 1, account_id: 1, name: "Background check request 1")

    assert_equal 1, TestBackgroundCheckRequest.count
    assert_equal 1, test_candidate.reload.test_background_check_requests_count
  end
end
```

### Expected behavior
I was expecting the creation to take place correctly, and the counter to increase.

### Actual behavior
I am getting the following exception:

```
Minitest::UnexpectedError: ArgumentError: Expected corresponding value for ["id", "account_id"] to be an Array
    activerecord (7.1.3.2) lib/active_record/relation/predicate_builder.rb:82:in `block (2 levels) in expand_from_hash'
    activerecord (7.1.3.2) lib/active_record/relation/predicate_builder.rb:81:in `map'
    activerecord (7.1.3.2) lib/active_record/relation/predicate_builder.rb:81:in `block in expand_from_hash'
    activerecord (7.1.3.2) lib/active_record/relation/predicate_builder.rb:79:in `each'
    activerecord (7.1.3.2) lib/active_record/relation/predicate_builder.rb:79:in `flat_map'
    activerecord (7.1.3.2) lib/active_record/relation/predicate_builder.rb:79:in `expand_from_hash'
    activerecord (7.1.3.2) lib/active_record/relation/predicate_builder.rb:25:in `build_from_hash'
    activerecord (7.1.3.2) lib/active_record/relation/query_methods.rb:1526:in `build_where_clause'
    activerecord (7.1.3.2) lib/active_record/relation/query_methods.rb:943:in `where!'
    activerecord (7.1.3.2) lib/active_record/counter_cache.rb:115:in `update_counters'
    activerecord (7.1.3.2) lib/active_record/locking/optimistic.rb:182:in `update_counters'
    activerecord (7.1.3.2) lib/active_record/persistence.rb:974:in `increment!'
    activerecord (7.1.3.2) lib/active_record/locking/optimistic.rb:64:in `increment!'
    activerecord (7.1.3.2) lib/active_record/callbacks.rb:436:in `increment!'
    activerecord (7.1.3.2) lib/active_record/associations/has_many_association.rb:100:in `update_counter'
    activerecord (7.1.3.2) lib/active_record/associations/has_many_association.rb:122:in `delete_or_nullify_all_records'
    activerecord (7.1.3.2) lib/active_record/associations/collection_association.rb:161:in `delete_all'
    activerecord (7.1.3.2) lib/active_record/associations/collection_proxy.rb:475:in `delete_all'
    test/services/candidates/copier_base_test.rb:602:in `block in <class:CopierBaseTest>'
```

### System configuration
**Rails version**: 
7.1.3.2 (branch `7-1-stable`)

**Ruby version**: 
3.2.2

**Comment by fatkodima** [comment]
It would be helpful if you can provide a working reproduction test script.

**Comment by Urchmaney** [comment]
@fragkakis running the script runs successfully with the rails gem pointing to the main branch. I get the error when rails gem version is changes to your version (7.1.3.2). The bug is in the version.

**Comment by fragkakis** [comment]
I'll close this, and reopen it when I am able to reproduce in a script.

Thank you all!
