### ISSUE TITLE
composite PKs: update_all doesn't work when .order is used in postgres

### ISSUE THREAD

**Issue by fragkakis** [rails/rails#51466]
When I call `update_all` on an `ActiveRecord::Collection` containing `.order_by` with a Postgres DB, I get an error. Note that the snippet works with an Sqlite database.

### Steps to reproduce

Run the following script

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 7.1.3"
  gem 'activerecord-import'
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

db_properties = {
  adapter: "postgresql",
  host: "localhost",
  username: "postgres",
  password: "postgres",
  database: "books"
}
# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(db_properties)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :test_background_check_requests, force: true do |t|
    t.integer :candidate_id
    t.integer :account_id
    t.string :name
  end

  create_table :test_candidates, force: true, primary_key: %i[candidate_id account_id] do |t|
    t.integer :candidate_id
    t.integer :account_id
    t.integer :test_background_check_requests_count
    t.string :name
  end
end

class TestCandidate < ActiveRecord::Base
  self.primary_key = %i[candidate_id account_id]
  has_many :test_background_check_requests, query_constraints: [:candidate_id, :account_id]
end

class TestBackgroundCheckRequest < ActiveRecord::Base
  belongs_to :test_candidate, counter_cache: true, query_constraints: [:candidate_id, :account_id]
end

class BugTest < Minitest::Test
  def test_association_stuff
    TestCandidate.create!(candidate_id: 1, account_id: 1, name: "Foo Barson 1")
    TestCandidate.create!(candidate_id: 2, account_id: 1, name: "Foo Barson 2")
    TestCandidate.create!(candidate_id: 3, account_id: 1, name: "Foo Barson 3")

    # Does not work
    TestCandidate.where(account_id: 1).order(:name).update_all(name: "Updated value")

    # Works
    # TestCandidate.where(account_id: 1).update_all(name: "Updated value")
  end
end
```

### Expected behavior

`update_all` should update the selected records.

### Actual behavior

The following error is raised:

```
Error:
BugTest#test_association_stuff:
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column test_candidates.["candidate_id", "account_id"] does not exist
LINE 1: ..."."[""candidate_id"", ""account_id""]" IN (SELECT "test_cand...
                                                             ^

    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `block (2 levels) in exec_no_cache'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1028:in `block in with_raw_connection'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.3.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1000:in `with_raw_connection'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:893:in `block in exec_no_cache'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.3.2/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1143:in `log'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:892:in `exec_no_cache'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:872:in `execute_and_clear'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:77:in `exec_delete'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `update'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/query_cache.rb:25:in `update'
    /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.3.2/lib/active_record/relation.rb:530:in `update_all'
    /Users/markosfragkakis/Library/Application Support/JetBrains/RubyMine2023.3/scratches/scratch_530.rb:61:in `test_association_stuff'
```

### System configuration
**Rails version**: 
7.1.3.2

**Ruby version**: 
3.2.2

**Comment by fatkodima** [comment]
This is already fixed by https://github.com/rails/rails/pull/49655.

In the meantime, you can use `gem 'rails', github: 'rails/rails', branch: '7-1-stable'`.
