### ISSUE TITLE
Failure/Error: require 'active_support/all', while loading spec_helper.rb

### ISSUE THREAD

**Issue by justpiyoosh** [rails/rails#51561]
### Steps to reproduce

```ruby
 Run RSpec tests with the command bundle exec rspec.
```

### Expected behavior
RSpec tests should run successfully without any errors.

### Actual behavior
An error occurs while loading spec_helper.rb with the following message:
```
An error occurred while loading spec_helper.
Failure/Error: require 'active_support/all'

NameError:
  uninitialized constant TZInfo::DateTime
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/tzinfo-2.0.6/lib/tzinfo/datetime_with_offset.rb:19:in `<module:TZInfo>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/tzinfo-2.0.6/lib/tzinfo/datetime_with_offset.rb:6:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/tzinfo-2.0.6/lib/tzinfo.rb:30:in `require_relative'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/tzinfo-2.0.6/lib/tzinfo.rb:30:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/activesupport-7.0.5.1/lib/active_support/values/time_zone.rb:3:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/activesupport-7.0.5.1/lib/active_support/core_ext/time/conversions.rb:5:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/activesupport-7.0.5.1/lib/active_support/core_ext/time/calculations.rb:4:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/activesupport-7.0.5.1/lib/active_support/core_ext/time.rb:4:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/activesupport-7.0.5.1/lib/active_support/time.rb:12:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/activesupport-7.0.5.1/lib/active_support/all.rb:4:in `<top (required)>'
# ./spec/spec_helper.rb:7:in `<top (required)>'
No examples found.


Finished in 0.00004 seconds (files took 0.47417 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

### System configuration
**Rails version**: 7.0.5.1

**Ruby version**: 3.2.2

Contents of spec/spec_helper.rb:
  ```
 # frozen_string_literal: true

require 'dotenv'
Dotenv.load('.env.test')

require 'rest-client'
require 'active_support/all'
require 'active_record_extended'
require 'capybara/rspec'
require 'database_cleaner/active_record'
require 'selenium/webdriver'
require 'webdrivers/chromedriver'
```

**Comment by fatkodima** [comment]
Can you create a sample app that reproduces the issue and hare with us?

**Comment by justpiyoosh** [comment]
The error is coming in a private repo, so I'm not sure if I will be able to create a sample app with the above error.

**Comment by fatkodima** [comment]
Closing for now, as I am pretty sure that this a problem with some custom setup. Also try if that works with rails 7.1 and updated gems.

If you will be able to create a sample app, we will reopen.

**Comment by justpiyoosh** [comment]
Sure.

**Comment by justpiyoosh** [comment]
Hi @fatkodima,

I've found the problem. It looks like we made our own Date class in the lib folder to add some new methods. When ActiveSupport loads and tries to load tzinfo, it hits a line in tzinfo/datetime_with_offset.rb:4
`
require 'date'
`
This makes our special date thingy load, and that's when everything starts failing.
