### ISSUE TITLE
procfile causes failure on Rails 8.0

### ISSUE THREAD

**Issue by rubys** [rails/rails#51829]
### Steps to reproduce

This works (note edge):

```
rails new demo --edge --css tailwind
cd demo
bin/dev
curl http://localhost:3000/
```

This also works (note bin/rails server):
```
rails new demo --main --css tailwind
cd demo
bin/rails server
curl http://localhost:3000/
```

This fails (main with bin/dev):

```
rails new demo --main --css tailwind
cd demo
bin/dev
curl http://localhost:3000/
```

### Expected behavior

![image](https://github.com/rails/rails/assets/4815/1d67d311-29e1-41b3-87b1-5a8dd747d25b)

### Actual behavior

```
Puma caught this error: key must be 16 bytes (ArgumentError)
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/message_encryptor.rb:307:in `key='
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/message_encryptor.rb:307:in `decrypt'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/message_encryptor.rb:261:in `read_message'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/messages/rotator.rb:25:in `read_message'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/message_encryptor.rb:245:in `block (3 levels) in decrypt_and_verify'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/messages/codec.rb:47:in `block in catch_and_ignore'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/messages/codec.rb:46:in `catch'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/messages/codec.rb:46:in `catch_and_ignore'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/message_encryptor.rb:244:in `block (2 levels) in decrypt_and_verify'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/messages/codec.rb:54:in `block in catch_and_raise'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/messages/codec.rb:53:in `catch'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/messages/codec.rb:53:in `catch_and_raise'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/message_encryptor.rb:243:in `block in decrypt_and_verify'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/messages/codec.rb:54:in `block in catch_and_raise'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/messages/codec.rb:53:in `catch'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/messages/codec.rb:53:in `catch_and_raise'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/message_encryptor.rb:242:in `decrypt_and_verify'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/encrypted_file.rb:109:in `decrypt'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/encrypted_file.rb:72:in `read'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/encrypted_configuration.rb:57:in `read'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/encrypted_configuration.rb:76:in `config'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/encrypted_configuration.rb:95:in `options'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/delegation.rb:166:in `method_missing'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activerecord/lib/active_record/railtie.rb:351:in `block (2 levels) in <class:Railtie>'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/lazy_load_hooks.rb:77:in `each'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activerecord/lib/active_record/base.rb:337:in `<module:ActiveRecord>'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activerecord/lib/active_record/base.rb:15:in `<main>'
/opt/homebrew/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
/opt/homebrew/Cellar/ruby/3.3.1/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.14/lib/zeitwerk/kernel.rb:34:in `require'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activerecord/lib/active_record/query_cache.rb:38:in `run'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/execution_wrapper.rb:28:in `before'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/callbacks.rb:385:in `block in make_lambda'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/callbacks.rb:179:in `block in call'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/callbacks.rb:668:in `block (2 levels) in default_terminator'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/callbacks.rb:667:in `catch'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/callbacks.rb:667:in `block in default_terminator'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/callbacks.rb:180:in `call'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/callbacks.rb:559:in `block in invoke_before'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/callbacks.rb:559:in `each'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/callbacks.rb:559:in `invoke_before'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/callbacks.rb:109:in `run_callbacks'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/execution_wrapper.rb:128:in `run'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/execution_wrapper.rb:124:in `run!'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/execution_wrapper.rb:77:in `block in run!'
<internal:kernel>:90:in `tap'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/activesupport/lib/active_support/execution_wrapper.rb:74:in `run!'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/actionpack/lib/action_dispatch/middleware/executor.rb:14:in `call'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/actionpack/lib/action_dispatch/middleware/static.rb:27:in `call'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/rack-3.0.11/lib/rack/sendfile.rb:114:in `call'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/actionpack/lib/action_dispatch/middleware/host_authorization.rb:143:in `call'
/opt/homebrew/lib/ruby/gems/3.3.0/bundler/gems/rails-4b4171b80e37/railties/lib/rails/engine.rb:536:in `call'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

### System configuration
**Rails version**:  --edge and --main

**Ruby version**: `ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]`

**Comment by rafaelfranca** [comment]
@dhh could this be the [`env.erb`](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/templates/env.erb.tt) file being loaded by foreman and using an non-existent `RAILS_MASTER_KEY`?

@rubys can you see if by deleting that file before starting the server it works?

**Comment by rubys** [comment]
Neither deleting `.env.erb` or `config/master.key` solves this problem.  I also wasn't seeing this problem on `--main` on Friday.

**Comment by skipkayhil** [comment]
Looks like the `.env.erb` gets rendered to `.env`, after removing that file `foreman` works again for me

**Comment by rubys** [comment]
Confirming that the following fixes the problem for me:

```
erb .env.erb > .env
```

**Comment by andrewn617** [comment]
Yeah, it seems `kamal init` is [being called before](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/app_base.rb#L732-L734) we create the `.env.erb` template. But even if I swap the order of those calls, it seems `kamal init` is [not template aware](https://github.com/basecamp/kamal/blob/12cad5458a4fdc14ffb182ae99673a0136852ab3/lib/kamal/cli/main.rb#L151).

**Comment by dhh** [comment]
Ah yeah, will add a call to evaluate .env.erb on first run. Then it'll yank the key from master.key into .env.

**Comment by morgoth** [comment]
@dhh I think the .env file picked up both by default by kamal and foreman might be a big source of confusion and bugs, vide https://github.com/basecamp/kamal/issues/233 and https://github.com/basecamp/kamal/discussions/420

Can we maybe differentiate somehow those 2 env files so they do not interfere with each other?

**Comment by dhh** [comment]
That seems like a fine fix for the default /bin/dev, which is where we use foreman out of the box through the bundlers. If you'd like to open some PRs to get that sorted, that would be great. Thanks!

**Comment by Flixt** [comment]
I was bitten by the definition of `bin/dev` from `rails/cssbundling-rails` here:

https://github.com/rails/cssbundling-rails/blob/02caad4e0613404d535f804ebffe70ee3fc496da/lib/install/dev#L11

I opened up https://github.com/rails/cssbundling-rails/pull/155.

If it is decided to merge this PR I'd be happy to also one PRs for https://github.com/rails/tailwindcss-rails, https://github.com/rails/jsbundling-rails, https://github.com/rails/dartsass-rails.

As mentioned in the PR I'm not entirely sure if this is the correct approach. It works and also seems to be fine to run foreman without loading `.env` for the purpose of local bundling. On the other hand there are people really having a hard time with the new defaults introduced by Kamal `.env`.

I'm referencing the same issues/discussion as in the PR here to get better cross references.

See other:
- https://github.com/rails/rails/issues/51829 (Original issue leading to this PR)
- https://github.com/ddollar/foreman/issues/702 (Foreman issue describing the `--env /dev/null` solution)
- https://github.com/basecamp/kamal/discussions/617 (Discussion explaining why `.env` in Kamal is dangerous)
- https://github.com/basecamp/kamal/issues/233 (Issue about supporting multiple environments in Kamal)
- https://github.com/basecamp/kamal/discussions/420 (Another discussion about Foreman & Kamal/MRSK incompatibility)

**Comment by Flixt** [comment]
Now, after sleeping a night, I think it is not a good thing at all that Kamal relies on a .env file for secrets. Configure foreman not to load the .env file may be a fix of some symptoms and probably brings some sanity but over all, I think, having production clear text secrets in a file on the root level is just bad.

Interestingly the dotenv gem used by Kamal already supports Command Substitution. So one can just have an .env file like this:

```
KAMAL_REGISTRY_PASSWORD=$(op read "op://MyVault/MyEntry/KAMAL_REGISTRY_PASSWORD")
RAILS_MASTER_KEY=$(op read "op://MyVault/MyEntry/RAILS_MASTER_KEY")
```

and it works fine for me.

I think we probably should make it possible to have the whole path for the files read as env being configurable in deploy.yml instead of just the ENV_VAR names. I'd be very happy to help out and open PRs.

**Comment by jdelStrother** [comment]
Other tools will also read .env by default - eg I have some [Storybook](https://storybook.js.org/docs/configure/environment-variables#using-env-files) config in there. Kamal's .env is only really expected to be used for Kamal, right? Perhaps Kamal's default path should change, rather than having to change every other tool to avoid potentially dangerous production secrets?

**Comment by djmb** [comment]
We'll change Kamal to read the env in from `.kamal/env` - see https://github.com/basecamp/kamal/pull/900

**Comment by jdelStrother** [comment]
@djmb awesome, thank you!
