### ISSUE TITLE
`ActiveSupport::BroadcastLogger` with `ActiveSupport::TaggedLogging`  throws  `no implicit conversion of String into Integer (TypeError)

### ISSUE THREAD

**Issue by jvillarejo** [rails/rails#51883]
### Steps to reproduce
I created a new rails application. 

`
$ rails new broadcast_logger
`

I add the configuration for `broadcast_logger` on `config/environments/development.rb` 

```ruby
  config.logger = ActiveSupport::Logger.new(STDOUT)
                                      .tap  { |logger| logger.formatter = ::Logger::Formatter.new }
                                      .then { |logger| ActiveSupport::TaggedLogging.new(logger) }
  environment_logger = ActiveSupport::Logger.new(Rails.root.join('log', "#{Rails.env}.log"))
                                      .tap  { |logger| logger.formatter = ::Logger::Formatter.new }
                                      .then { |logger| ActiveSupport::TaggedLogging.new(logger) }
                                      
  config.log_tags = [:request_id]

  Rails.logger = ActiveSupport::BroadcastLogger.new(config.logger, environment_logger)
```

Here is the sample App to reproduce it: 

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = ActiveSupport::Logger.new(STDOUT)
                                      .tap  { |logger| logger.formatter = ::Logger::Formatter.new }
                                      .then { |logger| ActiveSupport::TaggedLogging.new(logger) }
  environment_logger = ActiveSupport::Logger.new(Rails.root.join('log', "#{Rails.env}.log"))
                                      .tap  { |logger| logger.formatter = ::Logger::Formatter.new }
                                      .then { |logger| ActiveSupport::TaggedLogging.new(logger) }
                                      
  config.log_tags = [:request_id]

  Rails.logger = ActiveSupport::BroadcastLogger.new(config.logger, environment_logger)

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior
I expected that response was ok and the log would output to STDOUT and the logfile `log/development.log` 

### Actual behavior
I throws this error:

```ruby
And when making a request it throws this error:

```ruby
Puma caught this error: no implicit conversion of String into Integer (TypeError)
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.3.3/lib/action_dispatch/middleware/request_id.rb:28:in `[]='
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.3.3/lib/action_dispatch/middleware/request_id.rb:28:in `block in call'
<internal:kernel>:90:in `tap'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.3.3/lib/action_dispatch/middleware/request_id.rb:28:in `call'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-3.0.11/lib/rack/method_override.rb:28:in `call'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-3.0.11/lib/rack/runtime.rb:24:in `call'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.3.3/lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.3.3/lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.3.3/lib/action_dispatch/middleware/server_timing.rb:58:in `call'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.3.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.3.3/lib/action_dispatch/middleware/static.rb:25:in `call'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-3.0.11/lib/rack/sendfile.rb:114:in `call'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.3.3/lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.3.3/lib/rails/engine.rb:536:in `call'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
/home/pollo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

### System configuration
**Rails version**: 7.1.3.3

**Ruby version**: 3.2.2

**Comment by jvillarejo** [comment]
I debug a little bit more and somehow when configuring the broadcast log with logs without the tagged logger. It works fine.
And also when I use just a log with tagged logger, it works fine. 

The problem is with tagged logger and broadcast logger. 

Also I debugged the `ActionDispatch::RequestId and the problems seems that when configuring the `TaggedLogging` and `BroadcastLogger` it changes the arguments of the block.

```ruby
@app.call(env).tap do |_status, headers, _body|     
    headers[@header] = req.request_id
  end
```

With the `TaggedLogging` and `BroadcastLogger` the both the `_status` and `headers` is the `Array` composed of `[status, headers]` that why the line that set the request_id throw the error. `headers` is an array and `@header` is the key for the header `"x-request-id"` 

Without hte `TaggedLogging`, the arguments of the block are correctly decomposed. 

I could try to fix it if someone can guide me a little bit more.

**Comment by ruyrocha** [comment]
The headers are correctly set as `Rack::Headers`, not an `Array`, while running your reproduction script against the main `branch`.

This is the passing script for `7-1-stable` branch:

```ruby
class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  tagged_logger = ActiveSupport::TaggedLogging.new(ActiveSupport::Logger.new(STDOUT))
  config.logger = tagged_logger

  env_logger_file = Rails.root.join("tmp", "#{Rails.env}.log")

  environment_logger = ActiveSupport::Logger.new(env_logger_file).tap { |logger| ActiveSupport::TaggedLogging.new(logger) }

  config.log_tags = [:request_id]

  Rails.logger = ActiveSupport::BroadcastLogger.new(config.logger, environment_logger)

  routes.draw do
    get "/" => "test#index"
  end
end
```

Can you please give it a try?

**Comment by jvillarejo** [comment]
Hey @ruyrocha thanks for your respose. 

I tested with the stable branch and, it doesn't work. 

There is a problem in your sample file. 

When you use:
```ruby
  environment_logger = ActiveSupport::Logger.new(env_logger_file).tap { |logger| ActiveSupport::TaggedLogging.new(logger) }
```

You are using `tap` but `tap` doesn't return the block result. So the `environment_logger` isn't configured with the `TaggedLogging` 

I replaced the `tap` for `then` so the `environment_logger` variable is also a `TaggedLogging instance and it throws the same error. 

```
TypeError: no implicit conversion of String into Integer
```

**Comment by andre-rocha-hs** [comment]
Do we have any updates here?
I'm facing the same issue when trying to create a custom logger.

```
# lib/custom_logger.rb

class CustomLogger < ActiveSupport::BroadcastLogger
  class << self
    attr_accessor :logger    
    delegate :info, :warn, :debug, :error, :fatal, :tags, to: :logger
  end

  include ActiveSupport::TaggedLogging

  DEFAULT_TAGS = [Rails.env, "member-defense-network"].freeze

  attr_accessor :tags

  def initialize(logger, tags: [])
    super(logger)
    self.formatter = CustomFormatter.new
    self.formatter.extend ActiveSupport::TaggedLogging::Formatter
    @tags = tags
  end

  def debug(*args, &block)
    tagged(DEFAULT_TAGS + @tags) { super(*args, &block) }
  end

  def info(*args, &block)
    tagged(DEFAULT_TAGS + @tags) { super(*args, &block) }
  end

  def warn(*args, &block)
    tagged(DEFAULT_TAGS + @tags) { super(*args, &block) }
  end

  def error(*args, &block)
    tagged(DEFAULT_TAGS + @tags) { super(*args, &block) }
  end

  def fatal(*args, &block)
    tagged(DEFAULT_TAGS + @tags) { super(*args, &block) }
  end

  def tags
    DEFAULT_TAGS + @tags
  end
end

class CustomFormatter < Logger::Formatter
  def call(severity, time, progname, msg)
    formatted_severity = sprintf("%-5s",severity.to_s)
    formatted_time = time.strftime("%Y-%m-%d %H:%M:%S")
    "[#{formatted_severity} #{formatted_time} #{$$}]\n #{msg}\n"
  end
end
```

```
# config/initializers/custom_logger.rb

require Rails.root.join('lib',"custom_logger.rb")

file_logger = CustomLogger.new(Logger.new(Rails.root.join("log/#{Rails.env}.log")))
stdout_logger = CustomLogger.new(Logger.new(STDOUT))
broadcast_logger = ActiveSupport::BroadcastLogger.new
broadcast_logger.broadcast_to(stdout_logger, file_logger)
CustomLogger.logger = broadcast_logger

unless Rails.env.test?
  Rails.logger = CustomLogger.logger
end
```

**Comment by armstrjare** [comment]
This was happening because of #49745 

Resolved as a side-effect of [363abead1776d8a44123be0f4991db05acc3bb74](https://github.com/rails/rails/commit/363abead1776d8a44123be0f4991db05acc3bb74)
