### ISSUE TITLE
`PG::IndeterminateDatatype` on Rails 7.2 betas

### ISSUE THREAD

**Issue by lucasmazza** [rails/rails#52052]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # gem "rails", "~> 7.1.3"
  gem "rails", "7.2.0.beta2"

  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Execute `CREATE DATABASE rails_72_pg_bug` manually via psql.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "rails_72_pg_bug", host: "localhost", username: "FIXME", password: "FIXME")
ActiveRecord::Base.logger = Logger.new(STDOUT)


ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  def previous_posts
    self.class.where("(:id IS NULL) OR id < :id", id:)
  end
end

class BugTest < Minitest::Test
  def test_query
    3.times { Post.create! }
    post = Post.create!

    assert_equal 3, post.previous_posts.length
  end
end
```

### Expected behavior

The query works on Rails 7.1.x. 

### Actual behavior

```

  1) Error:
BugTest#test_query:
ActiveRecord::StatementInvalid: PG::IndeterminateDatatype: ERROR:  could not determine data type of parameter $1

    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_adapters/postgresql_adapter.rb:968:in `prepare'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_adapters/postgresql_adapter.rb:968:in `prepare_statement'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_adapters/postgresql_adapter.rb:908:in `block in exec_cache'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_adapters/abstract_adapter.rb:997:in `block in with_raw_connection'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0.beta2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_adapters/abstract_adapter.rb:969:in `with_raw_connection'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_adapters/postgresql_adapter.rb:907:in `exec_cache'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_adapters/postgresql_adapter.rb:874:in `execute_and_clear'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_adapters/postgresql/database_statements.rb:66:in `internal_exec_query'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_adapters/abstract/database_statements.rb:647:in `select'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_adapters/abstract/database_statements.rb:73:in `select_all'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_adapters/abstract/query_cache.rb:222:in `select_all'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/querying.rb:70:in `_query_by_sql'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/relation.rb:1431:in `block (2 levels) in exec_main_query'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_adapters/abstract/connection_pool.rb:393:in `with_connection'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/connection_handling.rb:296:in `with_connection'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/relation.rb:1430:in `block in exec_main_query'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/relation.rb:1452:in `skip_query_cache_if_necessary'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/relation.rb:1414:in `exec_main_query'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/relation.rb:1392:in `block in exec_queries'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/relation.rb:1452:in `skip_query_cache_if_necessary'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/relation.rb:1386:in `exec_queries'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/relation.rb:1167:in `load'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/relation.rb:336:in `records'
    /Users/lucas/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0.beta2/lib/active_record/relation/delegation.rb:98:in `length'
    rails_7_2_pg_bug.rb:39:in `test_query'
```

### System configuration
**Rails version**: 7.2.0.beta2

**Ruby version**: 3.3.0

**Comment by fatkodima** [comment]
This started to fail after https://github.com/rails/rails/pull/51139 (cc @byroot).

Previously, the generated query was `SELECT "posts".* FROM "posts" WHERE ((4 IS NULL) OR id < 4)`.
Now, the query is `SELECT "posts".* FROM "posts" WHERE (($1 IS NULL) OR id < $2)`, which is an invalid syntax for PostgreSQL to have bound values compared with `NULL`, unless we explicitly cast the bound variable, for example `SELECT "posts".* FROM "posts" WHERE (($1::integer IS NULL) OR id < $2)`.

I am not sure we can do anything about it. The query (especially the `:id IS NULL`, which looks like `4 is NULL`) makes little sense to me in any case.

**Comment by byroot** [comment]
Yeah. I also think Active Record is now doing what you'd expect (using bound values).

I can't think of any way to conditionally fallback to the old behaviour, and even that f we could I think it could be a footgun.

So I think we shouldn't do anything here.
