### ISSUE TITLE
ActionView: Rendering a template with strict locals should not rewrite ArgumentErrors

### ISSUE THREAD

**Issue by nhasselmeyer** [rails/rails#52227]
### Steps to reproduce
Raise an ArgumentError in a template that is rendered with strict locals.

Reproduction script:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "rails"
end

require "minitest/autorun"
require "action_view"

class StrictLocalsArgumentErrorTest < ActionView::TestCase
  helper do
    def helper_with_arg(arg)
    end
  end

  # red
  def test_actionview_does_not_touch_argument_errors_with_strict_locals
    err = assert_raises do
      render inline: <<~ERB
        <% # locals: () %>
        <%= helper_with_arg %>
      ERB
    end

    assert_match /in `helper_with_arg'/, err.backtrace.first
    # or something similar, I'm not sure what the best assertion would be
  end

  # green
  def test_actionview_does_not_touch_argument_errors_without_strict_locals
    err = assert_raises do
      render inline: <<~ERB
        <%= helper_with_arg %>
      ERB
    end

    assert_match /in `helper_with_arg'/, err.backtrace.first
  end
end
```

### Expected behavior
Rendering the template should raise an `ArgumentError` that points to the code that raised the exception (the `helper_with_arg` method and the template that incorrectly called it), e.g.
```
test.rb:17:in `helper_with_arg'
inline template:2:in `_inline_template__2760670737058980199_3460'
...
```

### Actual behavior
Rendering the template with strict locals raises an `ArgumentError` with the the following backtrace:
```
/path/to/actionview-7.1.3.4/lib/action_view/base.rb:254:in `rescue in _run'
/path/to/actionview-7.1.3.4/lib/action_view/base.rb:251:in `_run'
/path/to/actionview-7.1.3.4/lib/action_view/template.rb:261:in `block in render'
...
```

If the helper method was instead defined as `def helper_with_kwarg(kwarg:)`, the error message says `missing local: :kwarg` instead.

### System configuration
**Rails version**: 7.1.3.4

**Ruby version**: 3.1.2

---
ActionView should not touch this exception, because the current behaviour makes templates with strict locals a lot harder to debug.

I think the best behaviour here would be:
- check the exception's backtrace (something like ``argument_error.backtrace.first.match? /in `#{method}'$/``) and reraise the exception if it doesn't match
- or, if that becomes to complicated, don't modify the exception at all? I'd rather see correct backtraces and messages for errors raised within a template than getting slightly prettier exceptions for when I forget to pass a local.

**Comment by nhasselmeyer** [comment]
This still occurs on both the `7-2-stable` and the `main` branch.

I'd be willing to write a PR myself, but I want some input on what would be a good behavior

**Comment by flavorjones** [comment]
I've proposed a fix at https://github.com/rails/rails/pull/54133
