### ISSUE TITLE
I18n::InvalidLocaleData error with ruby 3.3.3 and rails 7.1.3.4 with macOS Sonoma 14.5

### ISSUE THREAD

**Issue by MaryamBasereh** [rails/rails#52242]
I have cloned a Ruby on Rails project from GitHub (https://github.com/FAIRMetrics/Metrics/tree/master/MetricsEvaluatorCode/Ruby) and am trying to install and run it on my machine as local server. But I keep getting the following error when I run the server (rails s): 

"I18n::InvalidLocaleData (can not load translations from ~/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/locale/en.yml: #<I18n::InvalidLocaleData: can not load translations from ~/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/locale/en.yml: #<ArgumentError: wrong number of arguments (given 2, expected 1)>>):
 
config/initializers/ruby3_patch.rb:12:in `rescue in load_yml'
config/initializers/ruby3_patch.rb:9:in `load_yml'
app/controllers/static_pages_controller.rb:17:in `home'".

### System configuration
My operating system is macOS Sonoma Version 14.5. 

**Rails version**: 7.1.3.4

**Ruby version**: 3.3.3

**Comment by fatkodima** [comment]
Closing this as it is very highly likely is not a problem in rails, but in some custom code.

If you can provide a minimal reproduction test script using one of the https://github.com/rails/rails/tree/main/guides/bug_report_templates templates or a sample rails app, we will reopen.
