### ISSUE TITLE
Uniqueness validation throws postgres error when enum with incorrect value is used as a scope

### ISSUE THREAD

**Issue by 4ndv** [rails/rails#52279]
### Steps to reproduce
- Create an enum attribute backed by postgres with `validate: true`
- Create an uniqueness validation for another attribute with `scope: :enum_name`
- Provide incorrect enum value

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "pg", "~> 1.1"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "ar_enum_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_enum :providers, %i[one two], force: true

  create_table :organizations, force: true do |t|
    t.enum :provider, enum_type: :providers, null: false
    t.string :external_id, null: false
  end
end

class Organization < ActiveRecord::Base
  enum :provider, { one: 'one', two: 'two' }, validate: true

  validates :external_id, uniqueness: { scope: :provider }
end

class BugTest < Minitest::Test
  def test_enum_stuff
    org = Organization.new(provider: :three, external_id: '123')

    assert_equal false, org.valid?
  end
end

```

### Expected behavior
Uniqueness validation does not fail with postgres error when incorrect scope enum value is provided

### Actual behavior
Uniqueness validation throws `ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation`

<details>
  <summary>Full error log</summary>
  
  ```
  BugTest#test_enum_stuff:
  ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input value for enum providers: "three"
  CONTEXT:  unnamed portal parameter $2 = '...'
  
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `block (2 levels) in exec_no_cache'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:1028:in `block in with_raw_connection'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:1000:in `with_raw_connection'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:893:in `block in exec_no_cache'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:1143:in `log'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:892:in `exec_no_cache'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:872:in `execute_and_clear'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `internal_exec_query'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:630:in `select'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:71:in `select_all'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/query_cache.rb:115:in `select_all'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:96:in `select_rows'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/relation/finder_methods.rb:369:in `block in exists?'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/relation.rb:1018:in `skip_query_cache_if_necessary'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/relation/finder_methods.rb:369:in `exists?'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/validations/uniqueness.rb:45:in `validate_each'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3.4/lib/active_model/validator.rb:155:in `block in validate'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3.4/lib/active_model/validator.rb:151:in `each'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3.4/lib/active_model/validator.rb:151:in `validate'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:426:in `block in make_lambda'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:706:in `catch'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:706:in `block in default_terminator'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:203:in `block in halting'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:598:in `block in invoke_before'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:598:in `each'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:598:in `invoke_before'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:109:in `run_callbacks'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:952:in `_run_validate_callbacks'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3.4/lib/active_model/validations.rb:441:in `run_validations!'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3.4/lib/active_model/validations/callbacks.rb:115:in `block in run_validations!'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:110:in `run_callbacks'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:952:in `_run_validation_callbacks'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3.4/lib/active_model/validations/callbacks.rb:115:in `run_validations!'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3.4/lib/active_model/validations.rb:366:in `valid?'
      /Users/lynx/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/validations.rb:72:in `valid?'
      ar-enum-bug.rb:41:in `test_enum_stuff'
  ```
</details>

### System configuration
**Rails version**: `7.1.3.4`, `main`

**Ruby version**: `3.3.3`

**PostgreSQL version**: `14.11`, `16.3`

**Comment by fatkodima** [comment]
I don't think this usecase can be solved by rails itself. 

I would suggest using a regular string/integer column for enum or enhance the uniqueness validation, via something like:
```ruby
validates :external_id, uniqueness: { scope: :provider }, if: -> { ['one', 'two'].include?(provider) }
```

**Comment by 4ndv** [comment]
> or enhance the uniqueness validation, via something like

Setting condition on uniqueness validation was pretty much what I've ended up with, but that solution seems a bit hacky for my taste.

> I don't think this usecase can be solved by rails itself.

This situation was not possible with enums defined with "validate: false" due to early `ArgumentError` when incorrect enum value is assigned, so the SQL query is always sent with known-good enum value.

In the case of `validate: true`, I don't think there is any point in the first place to send that query with invalid values, even if it's not backed by PG enum and will not cause StatementInvalid:

- If uniqueness check fails because there is matching records with incorrect values, the new record would be invalid anyway due to inclusion validation on enum
- If uniqueness check passes, the record is still invalid for the same reason

I understand that this case is a bit weird, but it's not entirely uncommon either.

**Comment by ghiculescu** [comment]
> * If uniqueness check fails because there is matching records with incorrect values, the new record would be invalid anyway due to inclusion validation on enum

This is not necessarily true, it's possible the app-level validations will change over time so records taht were previously valid no longer are (and vice versa).

**Comment by ghiculescu** [comment]
cc @mechnicov (author of https://github.com/rails/rails/pull/49100) in case you have any ideas.

**Comment by mechnicov** [comment]
What's about changing way of enum casting?

For example, if we have UUID and its format is wrong, we cast it as `nil`. It works such way

```ruby
MyModel.where(id: 123)
# SELECT my_models WHERE id = NULL;
```

As you see, we don't use `123` here. Why don't cast enum such way? If value doesn't match enum mapping, just execute it as `nil`

```ruby
Organization.new(provider: :three, external_id: '123')
```

**Comment by 4ndv** [comment]
> As you see, we don't use `123` here. Why don't cast enum such way? If value doesn't match enum mapping, just execute it as `nil`

If there is `allow_nil` present in validation and there is already matching record with `nil` in the enum, isn't uniqueness validation will be falsely errorneous?

**Comment by 4ndv** [comment]
> This is not necessarily true, it's possible the app-level validations will change over time so records taht were previously valid no longer are (and vice versa).

That's what I've meant, yes. It would be invalid from enum validation, so there is no need to perform SQL query to check uniqueness

**Comment by mechnicov** [comment]
> isn't uniqueness validation will be falsely errorneous?

I think no, because in this case `CREATE` or `UPDATE` will be executed using `NULL` value (as UUID now)

**Comment by schmijos** [comment]
I've got a workaround in place:

```rb
class ApplicationRecord < ActiveRecord::Base
  …

  def enum_values_queryable?
    defined_enums.all? do |name, mapping|
      value = self[name]
      value.blank? || mapping.value?(value)
    end
  end
end
```

Usable like this:

```rb
module Pricing
  class BasePrice < ApplicationRecord
    validates :organisation, uniqueness: { scope: %i[... pricing_mode ...], if: :enum_values_queryable? }
  end
end
```
