### ISSUE TITLE
Malformed request causes exception "invalid byte sequence in UTF-8"

### ISSUE THREAD

**Issue by xeron** [rails/rails#52284]
### Steps to reproduce

```
bundle exec rails new --skip-docker --skip-javascript --skip-jbuilder .
bundle exec rails s
curl -v http://localhost:3000/?%ADd+allow_url_include%3d1+%ADd+auto_prepend_file%3dphp://input
```

### Expected behavior

Rails returns a error to the client and doesn't trigger an exception (HTTP 400 maybe?).

### Actual behavior

Rails returns an HTTP 500 error to the client and triggers an exception:

```
Started GET "/?%ADd+allow_url_include%3d1+%ADd+auto_prepend_file%3dphp://input" for ::1 at 2024-07-06 11:10:08 -0700

ArgumentError (invalid byte sequence in UTF-8):

activesupport (7.1.3.4) lib/active_support/parameter_filter.rb:140:in `match?'
activesupport (7.1.3.4) lib/active_support/parameter_filter.rb:140:in `block in value_for_key'
activesupport (7.1.3.4) lib/active_support/parameter_filter.rb:140:in `any?'
activesupport (7.1.3.4) lib/active_support/parameter_filter.rb:140:in `value_for_key'
activesupport (7.1.3.4) lib/active_support/parameter_filter.rb:129:in `block in call'
activesupport (7.1.3.4) lib/active_support/parameter_filter.rb:128:in `each'
activesupport (7.1.3.4) lib/active_support/parameter_filter.rb:128:in `call'
activesupport (7.1.3.4) lib/active_support/parameter_filter.rb:84:in `filter'
actionpack (7.1.3.4) lib/action_dispatch/http/filter_parameters.rb:31:in `filtered_parameters'
actionpack (7.1.3.4) lib/action_controller/metal/instrumentation.rb:64:in `process_action'
actionpack (7.1.3.4) lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
activerecord (7.1.3.4) lib/active_record/railties/controller_runtime.rb:32:in `process_action'
actionpack (7.1.3.4) lib/abstract_controller/base.rb:160:in `process'
actionview (7.1.3.4) lib/action_view/rendering.rb:40:in `process'
actionpack (7.1.3.4) lib/action_controller/metal.rb:227:in `dispatch'
actionpack (7.1.3.4) lib/action_controller/metal.rb:309:in `dispatch'
actionpack (7.1.3.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.1.3.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:51:in `block in serve'
actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:124:in `each'
actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:124:in `find_routes'
actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.1.3.4) lib/action_dispatch/routing/route_set.rb:882:in `call'
rack (3.1.6) lib/rack/tempfile_reaper.rb:20:in `call'
rack (3.1.6) lib/rack/etag.rb:29:in `call'
rack (3.1.6) lib/rack/conditional_get.rb:31:in `call'
rack (3.1.6) lib/rack/head.rb:15:in `call'
actionpack (7.1.3.4) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
actionpack (7.1.3.4) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (7.1.3.4) lib/active_record/migration.rb:655:in `call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (7.1.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (7.1.3.4) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/actionable_exceptions.rb:16:in `call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (7.1.3.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (7.1.3.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (7.1.3.4) lib/active_support/tagged_logging.rb:135:in `block in tagged'
activesupport (7.1.3.4) lib/active_support/tagged_logging.rb:39:in `tagged'
activesupport (7.1.3.4) lib/active_support/tagged_logging.rb:135:in `tagged'
activesupport (7.1.3.4) lib/active_support/broadcast_logger.rb:240:in `method_missing'
railties (7.1.3.4) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.5.1) lib/sprockets/rails/quiet_assets.rb:17:in `call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/request_id.rb:28:in `call'
rack (3.1.6) lib/rack/method_override.rb:28:in `call'
rack (3.1.6) lib/rack/runtime.rb:24:in `call'
activesupport (7.1.3.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'
actionpack (7.1.3.4) lib/action_dispatch/middleware/server_timing.rb:58:in `call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/static.rb:25:in `call'
rack (3.1.6) lib/rack/sendfile.rb:114:in `call'
actionpack (7.1.3.4) lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
railties (7.1.3.4) lib/rails/engine.rb:536:in `call'
puma (6.4.2) lib/puma/configuration.rb:272:in `call'
puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
puma (6.4.2) lib/puma/server.rb:464:in `process_client'
puma (6.4.2) lib/puma/server.rb:245:in `block in run'
puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

### System configuration

**Rails version**: 7.1.3.4
**Ruby version**: 3.3.3

**Comment by justinko** [comment]
This issue is out of scope for Rails, but if you wanted to handle it in Rails, a middleware would be a good approach: https://dev.to/kputra/rails-fixing-invalid-query-parameters-invalid-encoding-5fda

**Comment by xeron** [comment]
This might be out of scope of rails, but I don't think framework users should be the ones handling this. It's either rails or rack.

Quick search over past similar issues shows that it was supposed to be fixed in rails and/or rack in the past:

https://github.com/rack/rack/issues/673
https://github.com/rack/rack/pull/713
https://github.com/rack/rack/pull/1797

https://github.com/rails/rails/pull/11795
https://github.com/rails/rails/commit/d59a24d543b4fd34d453e8209caae5fef315ea78

I'd love to see rails and rack developers agreeing on which layer should handle this.

**Comment by casperisfine** [comment]
Yeah, would make sense to do Rack sanitization by default like https://github.com/Shopify/rack-sanitizer

**Comment by glaszig** [comment]
i use this patch. it passes the value through when throwing up during regexp on invalid string.

```rb
module EncodingAgnosticParameterFilter
  private
    def value_for_key key, value, *args
      super key, value, *args
    rescue ArgumentError => e
      if e.message.include? "invalid byte sequence"
        value
      else
        raise e
      end
    end
end

ActiveSupport::ParameterFilter.prepend EncodingAgnosticParameterFilter
```

**Comment by glaszig** [comment]
probably duplicate of #52114.
