### ISSUE TITLE
"Polymorphic associations do not support computing the class." error when creating a record with a `has_one :through`

### ISSUE THREAD

**Issue by ghiculescu** [rails/rails#52304]
### Steps to reproduce

This is a regression between `7-2-stable` and `main`.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Gem passes:
  # gem "rails", "7.1.3.4"

  # 7.2 passes:
  # gem "rails", github: "rails/rails", branch: "7-2-stable"

  # Edge fails:
  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :sponsors, force: true do |t|
  end

  create_table :members, force: true do |t|
  end

  create_table :certificates, force: true do |t|
    t.integer :member_id
    t.integer :certificatable_id
    t.string :certificatable_type
  end
end

class Sponsor < ActiveRecord::Base
  has_one :certificate, as: :certificatable, validate: true
  has_one :member, through: :certificate
end

class Member < ActiveRecord::Base
end

class Certificate < ActiveRecord::Base
  belongs_to :member
  belongs_to :certificatable, polymorphic: true, validate: true, inverse_of: :certificate
end

class BugTest < Minitest::Test
  def test_association_stuff
    Sponsor.create!(member: Member.create!)
  end
end

```

### Expected behavior

Test should pass.

### Actual behavior

```
  1) Error:
BugTest#test_association_stuff:
ArgumentError: Polymorphic associations do not support computing the class.
    rails-69d904e60f78/activerecord/lib/active_record/reflection.rb:500:in `compute_class'
    rails-69d904e60f78/activerecord/lib/active_record/reflection.rb:439:in `_klass'
    rails-69d904e60f78/activerecord/lib/active_record/reflection.rb:431:in `klass'
    rails-69d904e60f78/activerecord/lib/active_record/reflection.rb:261:in `inverse_of'
    rails-69d904e60f78/activerecord/lib/active_record/autosave_association.rb:470:in `inverse_belongs_to_association_for'
    rails-69d904e60f78/activerecord/lib/active_record/autosave_association.rb:322:in `validate_single_association'
    rails-69d904e60f78/activerecord/lib/active_record/autosave_association.rb:228:in `block in define_autosave_validation_callbacks'
```

### System configuration
**Rails version**: `main`

**Ruby version**: 3.2

**Comment by ghiculescu** [comment]
btw I noticed that if you remove the `validate: true`s from the model definitions, the test passes. Maybe that's a helpful clue.

**Comment by casperisfine** [comment]
Let me know when you got a test added and I'll merge your fix.

**Comment by joshuay03** [comment]
@casperisfine I've added a regression test, it's ready for review 👍🏽
