### ISSUE TITLE
daterange with `.contains(Date)` results in malformed SQL ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  malformed range literal: "2024-07-17"

### ISSUE THREAD

**Issue by jdufresne** [rails/rails#52352]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails", branch: "main"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "postgresql", host: "localhost", database: "rails_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.daterange "dates", null: false
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_daterange_contains
    # Workaround
    assert_equal [], Post.where(Post.arel_table[:dates].contains(Arel.sql("#{ActiveRecord::Base.connection.quote(Date.today)}::date")))

    # Fails, but expect the same result.
    assert_equal [], Post.where(Post.arel_table[:dates].contains(Date.today))
  end
end
```

### Expected behavior

The ActiveRecord query `Post.where(Post.arel_table[:dates].contains(Date.today))` should understand date values and quote it appropriately. In this particular case, casting with `::date` would be sufficient.

### Actual behavior

```
-- create_table(:posts, {:force=>true})
D, [2024-07-17T09:18:53.432918 #281243] DEBUG -- :    (2.2ms)  DROP TABLE IF EXISTS "posts"
D, [2024-07-17T09:18:53.435653 #281243] DEBUG -- :    (2.3ms)  CREATE TABLE "posts" ("id" bigserial primary key, "dates" daterange NOT NULL)
   -> 0.0210s
D, [2024-07-17T09:18:53.463195 #281243] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.8ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
Run options: --seed 56033

# Running:

D, [2024-07-17T09:18:53.550021 #281243] DEBUG -- :   Post Load (0.5ms)  SELECT "posts".* FROM "posts" WHERE "posts"."dates" @> '2024-07-17'::date
D, [2024-07-17T09:18:53.552293 #281243] DEBUG -- :   Post Load (0.4ms)  SELECT "posts".* FROM "posts" WHERE "posts"."dates" @> '2024-07-17'
E

Finished in 0.008813s, 113.4724 runs/s, 113.4724 assertions/s.

  1) Error:
BugTest#test_daterange_contains:
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  malformed range literal: "2024-07-17"
LINE 1: ...T "posts".* FROM "posts" WHERE "posts"."dates" @> '2024-07-1...
                                                             ^
DETAIL:  Missing left parenthesis or bracket.

    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `block (2 levels) in exec_no_cache'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1004:in `block in with_raw_connection'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:976:in `with_raw_connection'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:893:in `block in exec_no_cache'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1120:in `log'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:892:in `exec_no_cache'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:872:in `execute_and_clear'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:66:in `internal_exec_query'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:647:in `select'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:73:in `select_all'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:222:in `select_all'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/querying.rb:70:in `_query_by_sql'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/relation.rb:1435:in `block (2 levels) in exec_main_query'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:407:in `with_connection'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/connection_handling.rb:310:in `with_connection'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/relation.rb:1434:in `block in exec_main_query'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/relation.rb:1456:in `skip_query_cache_if_necessary'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/relation.rb:1418:in `exec_main_query'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/relation.rb:1396:in `block in exec_queries'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/relation.rb:1456:in `skip_query_cache_if_necessary'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/relation.rb:1390:in `exec_queries'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/relation.rb:1167:in `load'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/relation.rb:336:in `records'
    /home/jon/.gem/ruby/3.3.4/bundler/gems/rails-55c4adeb36ef/activerecord/lib/active_record/relation.rb:1246:in `=='

1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration
**Rails version**:

edge

**Ruby version**:

ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]

---

### Workaround

Use something like `Arel.sql("#{ActiveRecord::Base.connection.quote(Date.today)}::date")` instead of relying on Rails to quote the value.

### Upstream Documentation

https://www.postgresql.org/docs/current/functions-range.html

> anyrange @> anyelement → boolean

**Comment by dgmstuart** [comment]
+1

I've gotten what I think is the same error on a numeric range type:

```
 ActionView::Template::Error:
              PG::InvalidTextRepresentation: ERROR:  malformed range literal: "15.3"
              DETAIL:  Missing left parenthesis or bracket.
              CONTEXT:  unnamed portal parameter $3 = '...'
```

It seems that although Postgres handles comparisons between ranges and single elements (https://www.postgresql.org/docs/14/functions-range.html), after upgrading to Rails 7.2 it's expecting both arguments to be ranges? Seems like maybe a bug?

In my code this causes the error:

```ruby
scope.where!("spots.length @> ?", length.to_f) if length
```

and this workaround seems to fix it:
```ruby
scope.where!("spots.length @> numrange(?, ?)", length.to_f, length.to_f)
```

...so I guess the equivalent workaround for your example might be something this?

```ruby
Post.arel_table[:dates].contains([Date.today..Date.today))
```

**Comment by dgmstuart** [comment]
Though on second look this Issue was raised before 7.2 was released?

**Comment by jdufresne** [comment]
Still an issue.
