### ISSUE TITLE
Fails to install from bundle.

### ISSUE THREAD

**Issue by wieczorek1990** [rails/rails#52486]
### Steps to reproduce

```shell
mkdir bundle
cd bundle
echo "source 'https://rubygems.org'" > Gemfile
echo "gem 'rails'" >> Gemfile
bundle install --path vendor/bundle
bundle exec rails new clinic
```

Output:
```
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching rake 13.2.1
Installing rake 13.2.1
Fetching concurrent-ruby 1.3.3
Installing concurrent-ruby 1.3.3
Fetching i18n 1.14.5
Installing i18n 1.14.5
Fetching minitest 5.24.1
Installing minitest 5.24.1
Fetching tzinfo 2.0.6
Installing tzinfo 2.0.6
Fetching zeitwerk 2.6.17
Installing zeitwerk 2.6.17
Fetching activesupport 6.1.7.8
Installing activesupport 6.1.7.8
Fetching builder 3.3.0
Installing builder 3.3.0
Fetching erubi 1.13.0
Installing erubi 1.13.0
Fetching mini_portile2 2.8.7
Installing mini_portile2 2.8.7
Fetching racc 1.8.1
Installing racc 1.8.1 with native extensions
Fetching nokogiri 1.13.10 (x86_64-darwin)
Installing nokogiri 1.13.10 (x86_64-darwin)
Fetching rails-dom-testing 2.2.0
Installing rails-dom-testing 2.2.0
Fetching crass 1.0.6
Installing crass 1.0.6
Fetching loofah 2.22.0
Installing loofah 2.22.0
Fetching rails-html-sanitizer 1.5.0
Installing rails-html-sanitizer 1.5.0
Fetching actionview 6.1.7.8
Installing actionview 6.1.7.8
Fetching rack 2.2.9
Installing rack 2.2.9
Fetching rack-test 2.1.0
Installing rack-test 2.1.0
Fetching actionpack 6.1.7.8
Installing actionpack 6.1.7.8
Fetching nio4r 2.7.3
Installing nio4r 2.7.3 with native extensions
Fetching websocket-extensions 0.1.5
Installing websocket-extensions 0.1.5
Fetching websocket-driver 0.7.6
Installing websocket-driver 0.7.6 with native extensions
Fetching actioncable 6.1.7.8
Installing actioncable 6.1.7.8
Fetching globalid 1.2.1
Installing globalid 1.2.1
Fetching activejob 6.1.7.8
Installing activejob 6.1.7.8
Fetching activemodel 6.1.7.8
Installing activemodel 6.1.7.8
Fetching activerecord 6.1.7.8
Installing activerecord 6.1.7.8
Fetching marcel 1.0.4
Installing marcel 1.0.4
Fetching mini_mime 1.1.5
Installing mini_mime 1.1.5
Fetching activestorage 6.1.7.8
Installing activestorage 6.1.7.8
Fetching date 3.3.4
Installing date 3.3.4 with native extensions
Fetching timeout 0.4.1
Installing timeout 0.4.1
Fetching net-protocol 0.2.2
Installing net-protocol 0.2.2
Fetching net-imap 0.3.7
Installing net-imap 0.3.7
Fetching net-pop 0.1.2
Installing net-pop 0.1.2
Fetching net-smtp 0.5.0
Installing net-smtp 0.5.0
Fetching mail 2.8.1
Installing mail 2.8.1
Fetching actionmailbox 6.1.7.8
Installing actionmailbox 6.1.7.8
Fetching actionmailer 6.1.7.8
Installing actionmailer 6.1.7.8
Fetching actiontext 6.1.7.8
Installing actiontext 6.1.7.8
Using bundler 1.17.3
Fetching method_source 1.1.0
Installing method_source 1.1.0
Fetching thor 1.3.1
Installing thor 1.3.1
Fetching railties 6.1.7.8
Installing railties 6.1.7.8
Fetching sprockets 4.2.1
Installing sprockets 4.2.1
Fetching sprockets-rails 3.5.2
Installing sprockets-rails 3.5.2
Fetching rails 6.1.7.8
Installing rails 6.1.7.8
Bundle complete! 1 Gemfile dependency, 48 gems now installed.
Bundled gems are installed into `./vendor/bundle`
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Zainicjowano puste repozytorium Gita w /Users/lukaszwieczorek/test/bundle/clinic/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/spring
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_6_1.rb
      create  config/initializers/permissions_policy.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
bundler: failed to load command: rails (/Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/bin/rails)
OpenSSL::Cipher::CipherError: couldn't set additional authenticated data
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.7.8/lib/active_support/message_encryptor.rb:170:in `auth_data='
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.7.8/lib/active_support/message_encryptor.rb:170:in `_encrypt'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.7.8/lib/active_support/message_encryptor.rb:148:in `encrypt_and_sign'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.7.8/lib/active_support/encrypted_file.rb:87:in `encrypt'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.7.8/lib/active_support/encrypted_file.rb:61:in `write'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.7.8/lib/active_support/encrypted_configuration.rb:29:in `write'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7.8/lib/rails/generators/rails/credentials/credentials_generator.rb:30:in `add_credentials_file_silently'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7.8/lib/rails/generators/rails/app/app_generator.rb:194:in `credentials'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7.8/lib/rails/generators/app_base.rb:165:in `public_send'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7.8/lib/rails/generators/app_base.rb:165:in `build'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7.8/lib/rails/generators/rails/app/app_generator.rb:386:in `create_credentials'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/thor-1.3.1/lib/thor/invocation.rb:134:in `block in invoke_all'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/thor-1.3.1/lib/thor/invocation.rb:134:in `each'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/thor-1.3.1/lib/thor/invocation.rb:134:in `map'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/thor-1.3.1/lib/thor/invocation.rb:134:in `invoke_all'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/thor-1.3.1/lib/thor/group.rb:232:in `dispatch'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/thor-1.3.1/lib/thor/base.rb:584:in `start'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7.8/lib/rails/commands/application/application_command.rb:26:in `perform'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7.8/lib/rails/command/base.rb:69:in `perform'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7.8/lib/rails/command.rb:48:in `invoke'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7.8/lib/rails/cli.rb:18:in `<top (required)>'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7.8/exe/rails:10:in `require'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7.8/exe/rails:10:in `<top (required)>'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/bin/rails:23:in `load'
  /Users/lukaszwieczorek/test/bundle/vendor/bundle/ruby/2.6.0/bin/rails:23:in `<top (required)>'
```

### Expected behavior
Does not fail with:

```shell
bundler: failed to load command: rails
```

### Actual behavior
Fails with error.

### System configuration
**Rails version**:
Rails 6.1.7.8
**Ruby version**:
ruby 2.6.10p210

**Comment by fatkodima** [comment]
Please upgrade ruby and rails.
