### ISSUE TITLE
Upgrading 7.1.3.4 to 7.2: Unrecognized ActiveSupport::Cache.format_version

### ISSUE THREAD

**Issue by omarzina** [rails/rails#52572]
### Steps to reproduce
- Rails app running rails version 7.1.3.4
- Change gemfile from `"rails", "~> 7.1"` to `"rails", "~> 7.2"`
- Run `bundle update`
- Run `bin/rails app:update`

### Expected behavior
- `bin/rails app:update` should update whatever it needs, maybe create a `new_defaults...` file, etc.

### Actual behavior

```
> bin/rails app:update
/gems/ruby/3.3.0/gems/activesupport-7.2.0/lib/active_support/cache.rb:769:in `default_serializer': Unrecognized ActiveSupport::Cache.format_version: 7.2 (ArgumentError)

            raise ArgumentError, "Unrecognized ActiveSupport::Cache.format_version: #{Cache.format_version.inspect}"
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /gems/ruby/3.3.0/gems/activesupport-7.2.0/lib/active_support/cache.rb:303:in `block in initialize'
	from /gems/ruby/3.3.0/gems/activesupport-7.2.0/lib/active_support/cache.rb:301:in `delete'
	from /gems/ruby/3.3.0/gems/activesupport-7.2.0/lib/active_support/cache.rb:301:in `initialize'
	from /gems/ruby/3.3.0/gems/motor-admin-0.4.27/lib/motor/assets.rb:15:in `new'
	from /gems/ruby/3.3.0/gems/motor-admin-0.4.27/lib/motor/assets.rb:15:in `<module:Assets>'
	from /gems/ruby/3.3.0/gems/motor-admin-0.4.27/lib/motor/assets.rb:4:in `<module:Motor>'
	from /gems/ruby/3.3.0/gems/motor-admin-0.4.27/lib/motor/assets.rb:3:in `<main>'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /gems/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /gems/ruby/3.3.0/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
	from /gems/ruby/3.3.0/gems/motor-admin-0.4.27/lib/motor.rb:70:in `<main>'
	from /gems/ruby/3.3.0/gems/motor-admin-0.4.27/lib/motor-admin.rb:3:in `require_relative'
	from /gems/ruby/3.3.0/gems/motor-admin-0.4.27/lib/motor-admin.rb:3:in `<main>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /gems/ruby/3.3.0/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
	from /usr/local/lib/ruby/3.3.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /usr/local/lib/ruby/3.3.0/bundler/runtime.rb:55:in `each'
	from /usr/local/lib/ruby/3.3.0/bundler/runtime.rb:55:in `block in require'
	from /usr/local/lib/ruby/3.3.0/bundler/runtime.rb:44:in `each'
	from /usr/local/lib/ruby/3.3.0/bundler/runtime.rb:44:in `require'
	from /usr/local/lib/ruby/3.3.0/bundler.rb:187:in `require'
	from /apife/config/application.rb:7:in `<main>'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /gems/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/command/actions.rb:15:in `require_application!'
	from /gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/commands/app/update_command.rb:24:in `configs'
	from /gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/commands/app/update_command.rb:15:in `perform'
	from /gems/ruby/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /gems/ruby/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/command/base.rb:178:in `invoke_command'
	from /gems/ruby/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/command/base.rb:73:in `perform'
	from /gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:71:in `block in invoke'
	from /gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:149:in `with_argv'
	from /gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:69:in `invoke'
	from /gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/commands.rb:18:in `<main>'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /gems/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
```

I checked the [file](https://github.com/rails/rails/blob/fb6c4305939da06efdf2893d99130e7829c53e8b/activesupport/lib/active_support/cache.rb#L767) `lib/active_support/cache.rb` file and it does not seem to have an entry for 7.2, but I really can't tell if that's the issue.

### System configuration
**Rails version**:
7.1.3.4 -> 7.2
**Ruby version**:
3.3.2

Let me know if you need more info.
Thanks!

**Comment by Earlopain** [comment]
There is indeed no cache format `7.2` and rails doesn't set this by itself. This is an issue with `motor-admin`. https://github.com/motor-admin/motor-admin-rails/issues/171 / https://github.com/motor-admin/motor-admin/issues/143

**Comment by byroot** [comment]
Closing as third party issue.
