### ISSUE TITLE
Regression: Cannot use Rails console if Rails application class is not in a module

### ISSUE THREAD

**Issue by aaronjensen** [rails/rails#52615]
We have 30 or so Rails applications that do not use with `SomeThing::Application` as the Rails application class. They simply declare a top level class such as `SomeThingApplication`. This was fine until Rails 7.2 where https://github.com/rails/rails/pull/50796 causes the console to fail to start.

### Steps to reproduce
Create a new rails app. Change the application class in `config/application.rb` to MyApplication without a module wrapping it.

```sh
bundle exec rails c
```

### Expected behavior
It should open a console

### Actual behavior
```
/Users/username/my-app/gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/commands/console/irb_console.rb:92:in `start': undefined method `underscore' for nil (NoMethodError)

        app_name = @app.class.module_parent_name.underscore.dasherize
                                                ^^^^^^^^^^^
        from /Users/username/my-app/gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/commands/console/console_command.rb:59:in `start'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/commands/console/console_command.rb:8:in `start'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/commands/console/console_command.rb:87:in `perform'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/command/base.rb:178:in `invoke_command'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/command/base.rb:73:in `perform'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:71:in `block in invoke'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:149:in `with_argv'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:69:in `invoke'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/railties-7.2.0/lib/rails/commands.rb:18:in `<main>'
        from <internal:/Users/username/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/username/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/username/my-app/gems/ruby/3.3.0/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
        from script/rails:12:in `<main>'
```

### System configuration
**Rails version**: 7.2.0

**Ruby version**: 3.3.4

**Comment by aaronjensen** [comment]
Caused by: https://github.com/rails/rails/pull/50796

Original discussion: https://github.com/rails/rails/issues/50770
