### ISSUE TITLE
`BIND="::" rails s` fails

### ISSUE THREAD

**Issue by ThisIsMissEm** [rails/rails#52658]
### Steps to reproduce

Attempt to start the built-in rails server listening bound to ipv6 interfaces:

```
$ BIND="::" rails s
```

Observe failure due to URL parsing (to do: add error trace)

### Expected behavior

Correctly binds the rails server to ipv6 interfaces.

### Actual behavior

Throws an error

### System configuration
**Rails version**: 7.1 (mastodon)

**Ruby version**: 3.3.4

### Additional Note:

Using the URL syntax for ipv6 loopback does work, but isn't technically the correct syntax.

```
BIND="[::]" rails s
```

**Comment by ThisIsMissEm** [comment]
On a fresh checkout of the Mastodon codebase, I get:
```shell
$ BIND='::' rails s 
=> Booting Puma
=> Rails 7.1.3.4 application starting in development 
=> Run `bin/rails server --help` for more startup options
[dotenv] Set ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY, ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT, and ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
[dotenv] Loaded .env.development
[dotenv] Set LOCAL_DOMAIN, WEB_DOMAIN, SINGLE_USER_MODE, SECRET_KEY_BASE, OTP_SECRET, VAPID_PRIVATE_KEY, VAPID_PUBLIC_KEY, DB_HOST, DB_PORT, DB_USER, DB_PASS, REDIS_URL, SIDEKIQ_REDIS_URL, S3_ENABLED, S3_ENDPOINT, S3_PROTOCOL, S3_HOSTNAME, S3_ALIAS_HOST, S3_BUCKET, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, STREAMING_API_BASE_URL, OIDC_ISSUER, OIDC_DISPLAY_NAME, OIDC_UID_FIELD, OIDC_CLIENT_ID, OIDC_CLIENT_SECRET, OIDC_REDIRECT_URI, OIDC_SECURITY_ASSUME_EMAIL_IS_VERIFIED, OIDC_SCOPE, OIDC_AUTH_ENDPOINT, OIDC_TOKEN_ENDPOINT, OIDC_USER_INFO_ENDPOINT, OIDC_JWKS_URI, OIDC_END_SESSION_ENDPOINT, and OIDC_IDP_LOGOUT_REDIRECT_URI
[dotenv] Loaded .env
[6016] Puma starting in cluster mode...
[6016] * Puma version: 6.4.2 (ruby 3.3.4-p94) ("The Eagle of Durango")
[6016] *  Min threads: 5
[6016] *  Max threads: 5
[6016] *  Environment: development
[6016] *   Master PID: 6016
[6016] *      Workers: 2
[6016] *     Restarts: (✔) hot (✖) phased
[6016] * Preloading application
Exiting
[redacted]/.rbenv/versions/3.3.4/lib/ruby/3.3.0/uri/rfc3986_parser.rb:130:in `split': bad URI(is not URI?): "tcp://:::3000" (URI::InvalidURIError)
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/3.3.0/uri/rfc3986_parser.rb:135:in `parse'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/3.3.0/uri/common.rb:185:in `parse'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/binder.rb:147:in `block in parse'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/binder.rb:146:in `each'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/binder.rb:146:in `parse'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/runner.rb:168:in `load_and_bind'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/cluster.rb:371:in `run'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/launcher.rb:194:in `run'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/rack/handler/puma.rb:76:in `run'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/server.rb:327:in `start'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/commands/server/server_command.rb:38:in `start'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/commands/server/server_command.rb:145:in `block in perform'
    from <internal:kernel>:90:in `tap'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/commands/server/server_command.rb:136:in `perform'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command/base.rb:178:in `invoke_command'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command/base.rb:73:in `perform'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command.rb:71:in `block in invoke'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command.rb:149:in `with_argv'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command.rb:69:in `invoke'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/commands.rb:18:in `<main>'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
    from [redacted]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by ThisIsMissEm** [comment]
@rafaelfranca could the difference be in `BIND` vs `BINDING` ?

**Comment by ThisIsMissEm** [comment]
Looks like it works with `BINDING="::"` but not `BIND="::"` — I'm honestly not sure the difference between these two environment variables, but `BIND` is what Mastodon has used in it's documentation for ages.

**Comment by rafaelfranca** [comment]
`BINDING` is the option that Rails supports. `BIND` seems to be mastodon specific https://github.com/mastodon/mastodon/blob/9ba7c90151463a6e4f7952317253fe8c113e9b0a/config/puma.rb#L12. It looks like they are using URI, so `[::]` is the correct syntax in that case.

Closing since this isn't an issue in Rails, but with the application code. Thank you for the issue

**Comment by ThisIsMissEm** [comment]
Oh! Good to know! I'd assumed it was a rails thing, will raise with the mastodon team., thanks!
