### ISSUE TITLE
7.2.X - bin/rails test command fails and generates ActiveRecord::DatabaseConnectionError when using mysql in development and parallel tests when # tests exceeds parallel minmum.

### ISSUE THREAD

**Issue by ccasabona** [rails/rails#52702]
On a new Rails 7.2.X app using mysql in development, running the command `bin/rails test` generates a `ActiveRecord::DatabaseConnectionError` exception under these conditions:

1. Parallel testing is enabled in test_helper.rb.
2. The number of tests is 51 or greater.
3. The app is generated under Rails 7.2.X.
4. The app uses mysql in development.

This app was new under Rails 7.2.0.  There are only 3 classes so far all of which were generated using the scaffold generator.  

This exception is possibly related to [52697](https://github.com/rails/rails/issues/52697).  I made a separate issue, however, in case it isn't.

As in 52697, setting `parallelize(workers: 1)` in class `ActiveSupport::TestCase ` fixes the issue.

This is not a problem on our legacy apps with dozens of classes (none generated under Rails 7) and thousands of tests that have been upgraded to Rails 7.2.0.  These apps use sqlite in development instead of mysql.  Parallel testing works as expected on these projects.

Rails 7.2.0, 7.2.1
Ruby 3.3.4
Mysql Ver 8.0.32 for macos10.15 on x86_64 (Homebrew)

This error listing is generated for each test:
```

Error:
GlobalsControllerTest#test_should_show_global:
DRb::DRbRemoteError: There is an issue connecting to your database with your username/password, username: blog_tester.

Please check your database configuration to ensure the username/password are valid.
 (ActiveRecord::DatabaseConnectionError)
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:31:in `rescue in new_client'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new_client'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:145:in `connect'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:154:in `block in reconnect'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:151:in `reconnect'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:662:in `block in reconnect!'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:661:in `reconnect!'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:763:in `block in verify!'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:754:in `verify!'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:771:in `connect!'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:977:in `block in with_raw_connection'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:976:in `with_raw_connection'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/mysql2/database_statements.rb:96:in `block in raw_execute'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:1119:in `log'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/mysql2/database_statements.rb:95:in `raw_execute'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:237:in `execute_and_free'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/mysql2/database_statements.rb:18:in `internal_exec_query'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:114:in `query'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:110:in `query_values'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:35:in `data_sources'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/schema_cache.rb:430:in `block in tables_to_cache'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:395:in `with_connection'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/schema_cache.rb:429:in `tables_to_cache'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/schema_cache.rb:313:in `data_source_exists?'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/schema_cache.rb:38:in `data_source_exists?'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/connection_adapters/schema_cache.rb:182:in `data_source_exists?'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/internal_metadata.rb:108:in `table_exists?'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:388:in `block in schema_up_to_date?'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:554:in `with_temporary_pool'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:385:in `schema_up_to_date?'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:400:in `block in reconstruct_from_schema'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:554:in `with_temporary_pool'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:399:in `reconstruct_from_schema'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/test_databases.rb:17:in `block in create_and_load_schema'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/test_databases.rb:14:in `each'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/test_databases.rb:14:in `create_and_load_schema'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.1/lib/active_record/test_databases.rb:8:in `block in <module:TestDatabases>'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/testing/parallelization/worker.rb:82:in `block in after_fork'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/testing/parallelization/worker.rb:81:in `each'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/testing/parallelization/worker.rb:81:in `after_fork'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/testing/parallelization/worker.rb:24:in `block in start'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/testing/parallelization/worker.rb:15:in `fork'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/testing/parallelization/worker.rb:15:in `start'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/testing/parallelization.rb:37:in `block in start'
    <internal:numeric>:237:in `times'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/testing/parallelization.rb:36:in `each'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/testing/parallelization.rb:36:in `map'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/testing/parallelization.rb:36:in `start'
    /Users/charlie/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.1/lib/active_support/testing/parallelize_executor.rb:19:in `start'


```

**Comment by chrisgeek** [comment]
I created a new app using sqlite and didn't encounter the error, I guess that confirms that this is specific to Mysql.
Rails 7.2
Ruby 3.3.1
Sqlite

**Comment by ccasabona** [comment]
That would explain why there is no problem on legacy apps that use sqlite.

I edited the issue to reflect that using mysql in development seems to be part of the problem.

**Comment by JoeDupuis** [comment]
I can't test on MacOS right now, but I wasn't able to reproduce this on linux using 
- 7.2.0
- 7.2.1 
- 7-2-stable

With mysql 8 or 15

I'll look into testing on a mac.
Are you able to reproduce the issue on a brand new test app? If so can you share it?

**Comment by ccasabona** [comment]
Thank you for looking in to this.  I am able to recreate this error on a new rails 7.2.1 app using MACOS 10.15 Catalina.  Here are the steps I used:

1.  Create new app using rails 7.2.1 called demo with

`rails new demo --database=mysql`
 `cd demo`
	
2.  Log in to your mysql server and create a databse called demo

```
create database demo;
use demo;
CREATE USER 'demo_user'@'localhost' IDENTIFIED BY 'Secret!@357';
GRANT ALL ON demo.* to 'demo_user'@'localhost';

create database demo_test;
use demo_test;
GRANT ALL ON demo_test.* to 'demo_user'@'localhost';
flush privileges;
exit;
	
```
3.  In the rails app, edit database.yml to refelect the above values.

```
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: demo_user
  password: Secret!@357
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: demo

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: demo_test
```

4.  Create 1 class using the scaffold generator.

```
rails g scaffold User name email
rails db:migrate
```
	
5.  The scaffold will generate 7 tests.  Running` bin/rails test` will work:

```
demo [main●] % rails test                        
Running 7 tests in a single process (parallelization threshold is 50)
Run options: --seed 10325

# Running:

.......

Finished in 0.401748s, 17.4239 runs/s, 27.3803 assertions/s.
7 runs, 11 assertions, 0 failures, 0 errors, 0 skips
```

6.  Open config/test.rb and configure parallel testing threshold:

	`config.active_support.test_parallelization_threshold = 6`
	
	Now running bin/rails test generates one ActiveRecord::DatabaseConnectionError for each test as described above in the initial comment for this issue.

Rails 7.2.1
Ruby 3.3.5
Ver 8.0.32 for macos10.15 on x86_64 (Homebrew)

**Comment by JoeDupuis** [comment]
Oh! I figured it out. 
I wasn't able to reproduce the issue because I was using the mysql root user and you are using a new user. 

Parallel tests don't use the `demo_test`. They create a separate db for each parallel worker : `demo_test_0`, `demo_test_1`, etc.

So you either need to run the tests with a user that can create those databases automatically. 

Or you need to create all those databases ahead of time and grant your user access to all of them. Note the hyphen in the databases names. You'll need to escape them with backticks  :

```
create database `demo_test-0`;
GRANT ALL ON `demo_test-0`.* to 'demo_user'@'localhost';
```

I recommend just giving your user the auth to create new databases;

**Comment by ccasabona** [comment]
Oh I see. It's operator error (meaning me).  Thanks for pointing out one of the finer points of using mysql in development.
