### ISSUE TITLE
hstore-backed columns not properly initialized when running parallel tests with eager loading enabled

### ISSUE THREAD

**Issue by gstokkink** [rails/rails#52711]
After upgrading to Rails 7.2.0, several of our tests in our test suite fail with the error message `TypeError: can't quote Hash`. These tests all manipulate hstore-backed columns. I've added some debugging statements to `HashLookupTypeMap#register_type` and `ModelSchema#type_for_column` and noticed the following:

```
Registered #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Hstore:0x000000032e090548> for OID 993636
Registered #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Hstore:0x000000033293bea0> for OID 993636
Registered #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Hstore:0x0000000332cddab8> for OID 993636

...

Running 2 tests in parallel using 2 processes
Started with run options --seed 45328

...

Type for OID 993636: #<ActiveModel::Type::Value:0x000000030bbd3b58>
Type for OID 993636: #<ActiveModel::Type::Value:0x000000030bbd0c50>

...

======================================================
===============     Test results       ===============
======================================================

Finished in 2.36021s
2 tests, 1 assertions, 0 failures, 1 errors, 0 skips

======================================================
=================== Grouped Errors  ==================
======================================================

Minitest::UnexpectedError:         TypeError: can't quote Hash

...
```

As you can see, the correct type is registered for the columns before the tests are being run, but during the test run the lookup returns the fallback type `ActiveModel::Type::Value` rather than the registered `ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Hstore` type.

When running the same tests using Rails 7.1.3.4 (can't run them in Rails 7.2.0 due to https://github.com/rails/rails/issues/52607):

```
Registered #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Hstore:0x000000015247a178> for OID 993636
Type for OID 993636: #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Hstore:0x000000015247a178>
Registered #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Hstore:0x0000000315676408> for OID 993636
Registered #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Hstore:0x00000003156baea0> for OID 993636

...

Running 2 tests in parallel using 2 processes
Started with run options --seed 4631

...

======================================================
===============     Test results       ===============
======================================================

Finished in 2.16041s
2 tests, 2 assertions, 0 failures, 0 errors, 0 skips

```

Here you can see that no lookups occur during the test run. A single lookup is performed before the tests start, and that returns the correct type.

This all seems very similar to what happened in https://github.com/rails/rails/issues/52607. That issue was resolved by reverting https://github.com/rails/rails/pull/49769, but I think there is a deeper underlying issue with schema loading/column type detection when running tests in parallel with eager loading enabled, which hasn't been addressed yet. Perhaps the column types need to be resolved before the forking takes place?

### Steps to reproduce

I haven't been able to create a minimal reproduction script yet unfortunately, I'll update this issue when I have one. Figured I'd create a ticket in advance in case other people run into this same issue.

### Expected behavior

Tests should run without errors.

### Actual behavior

Tests that manipulate an hstore-backed column fail with the following exception:

```
Minitest::UnexpectedError:         TypeError: can't quote Hash
            activerecord (7.2.1) lib/active_record/connection_adapters/abstract/quoting.rb:87:in `quote'
            activerecord (7.2.1) lib/active_record/connection_adapters/postgresql/quoting.rb:122:in `quote'
            activerecord (7.2.1) lib/arel/collectors/substitute_binds.rb:20:in `add_bind'
            activerecord (7.2.1) lib/arel/visitors/to_sql.rb:757:in `visit_ActiveModel_Attribute'
```

### System configuration
**Rails version**:

7.2.1

**Ruby version**:

3.3.4

**Comment by gstokkink** [comment]
Still working on the reproduction script (I can't get it to fail yet in a clean Rails application), but I've noticed that calling `Model.reset_column_information` in `parallelize_setup` fixes it. In that case the correct type gets looked up when running the tests.

**Comment by gstokkink** [comment]
Looks like https://github.com/rails/rails/pull/52703 fixes this (@ jonathanhefner FYI)
