### ISSUE TITLE
`remove_check_constraint` cannot be safely rolled back automatically from 7.1

### ISSUE THREAD

**Issue by wata727** [rails/rails#52743]
In PostgreSQL 12+, the best practice for safely adding a NOT NULL constraint to an existing column is to add a check constraint with `NOT VALID` and then run `VALIDATE CONSTRAINT`.

- [Explanation by strong_migration](https://github.com/ankane/strong_migrations/tree/v2.0.0?tab=readme-ov-file#setting-not-null-on-an-existing-column)
- [The official documentation mentions that table scans are skipped due to check constraints](https://www.postgresql.org/docs/12/sql-altertable.html#:~:text=Ordinarily%20this%20is%20checked%20during%20the%20ALTER%20TABLE%20by%20scanning%20the%20entire%20table%3B%20however%2C%20if%20a%20valid%20CHECK%20constraint%20is%20found%20which%20proves%20no%20NULL%20can%20exist%2C%20then%20the%20table%20scan%20is%20skipped.)

However, when the above steps are split into multiple migrations, there is an issue starting from 7.1 where rollback does not work properly.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"
require "debug"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "7.2.1"

  # works fine in 7.0
  # gem "rails", "7.0.8.4"

  # same issue found in main
  # gem "rails", github: "rails/rails", branch: "main"

  # works fine by https://github.com/rails/rails/pull/52345
  # gem "rails", github: "shayonj/rails", branch: "s/remove-reference-validate-check"

  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  host: "127.0.0.1",
  username: "postgres",
  password: "postgres"
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :payments, force: true do |t|
    t.decimal :amount
  end
end

class Payment < ActiveRecord::Base
end

class AddCheckConstraint < ActiveRecord::Migration::Current
  def change
    add_check_constraint :payments, "amount IS NOT NULL", name: "amount_is_not_null", validate: false
  end
end

class ValidateCheckConstraint < ActiveRecord::Migration::Current
  def change
    validate_check_constraint :payments, name: "amount_is_not_null"
  end
end

class AddNotNullConstraint < ActiveRecord::Migration::Current
  def change
    change_column_null :payments, :amount, false
    remove_check_constraint :payments, "amount IS NOT NULL", name: "amount_is_not_null", validate: false
  end
end

class BugTest < Minitest::Test
  def test_migration
    AddCheckConstraint.migrate(:up)
    ValidateCheckConstraint.migrate(:up)
    options = Payment.connection.check_constraints(:payments).first.options
    assert_equal({ name: "amount_is_not_null", validate: true }, options)

    # Imagine having to revert due to some problem
    AddNotNullConstraint.migrate(:up)
    AddNotNullConstraint.migrate(:down)
    options = Payment.connection.check_constraints(:payments).first.options
    assert_equal({ name: "amount_is_not_null", validate: false }, options)

    ValidateCheckConstraint.migrate(:down)
    ValidateCheckConstraint.migrate(:up)
    AddNotNullConstraint.migrate(:up)
    Payment.reset_column_information
    assert_equal([], Payment.connection.check_constraints(:payments))
    refute Payment.columns.last.null
  end
end

```

### Expected behavior

It works fine without any errors. This is the output in 7.0.8.4:

```
# Running:

==  AddCheckConstraint: migrating =============================================
-- add_check_constraint(:payments, "amount IS NOT NULL", {:name=>"amount_is_not_null", :validate=>false})
D, [2024-08-29T17:40:13.638859 #97833] DEBUG -- :    (2.8ms)  ALTER TABLE "payments" ADD CONSTRAINT amount_is_not_null CHECK (amount IS NOT NULL) NOT VALID
   -> 0.0029s
==  AddCheckConstraint: migrated (0.0029s) ====================================

==  ValidateCheckConstraint: migrating ========================================
-- validate_check_constraint(:payments, {:name=>"amount_is_not_null"})
D, [2024-08-29T17:40:13.643207 #97833] DEBUG -- :    (1.4ms)  ALTER TABLE "payments" VALIDATE CONSTRAINT "amount_is_not_null"
   -> 0.0043s
==  ValidateCheckConstraint: migrated (0.0043s) ===============================

==  AddNotNullConstraint: migrating ===========================================
-- change_column_null(:payments, :amount, false)
D, [2024-08-29T17:40:13.647904 #97833] DEBUG -- :    (1.5ms)  ALTER TABLE "payments" ALTER COLUMN "amount" SET NOT NULL
   -> 0.0022s
-- remove_check_constraint(:payments, "amount IS NOT NULL", {:name=>"amount_is_not_null", :validate=>false})
D, [2024-08-29T17:40:13.651109 #97833] DEBUG -- :    (1.4ms)  ALTER TABLE "payments" DROP CONSTRAINT "amount_is_not_null"
   -> 0.0032s
==  AddNotNullConstraint: migrated (0.0055s) ==================================

==  AddNotNullConstraint: reverting ===========================================
-- add_check_constraint(:payments, "amount IS NOT NULL", {:name=>"amount_is_not_null", :validate=>false})
D, [2024-08-29T17:40:13.655610 #97833] DEBUG -- :    (1.9ms)  ALTER TABLE "payments" ADD CONSTRAINT amount_is_not_null CHECK (amount IS NOT NULL) NOT VALID
   -> 0.0019s
-- change_column_null(:payments, :amount, true)
D, [2024-08-29T17:40:13.656864 #97833] DEBUG -- :    (1.1ms)  ALTER TABLE "payments" ALTER COLUMN "amount" DROP NOT NULL
   -> 0.0011s
==  AddNotNullConstraint: reverted (0.0057s) ==================================

==  ValidateCheckConstraint: reverting ========================================
D, [2024-08-29T17:40:13.661665 #97833] DEBUG -- :    (0.8ms)  ALTER TABLE "payments" VALIDATE CONSTRAINT "amount_is_not_null"
==  ValidateCheckConstraint: reverted (0.0031s) ===============================

==  ValidateCheckConstraint: migrating ========================================
-- validate_check_constraint(:payments, {:name=>"amount_is_not_null"})
D, [2024-08-29T17:40:13.662904 #97833] DEBUG -- :    (0.4ms)  ALTER TABLE "payments" VALIDATE CONSTRAINT "amount_is_not_null"
   -> 0.0012s
==  ValidateCheckConstraint: migrated (0.0012s) ===============================

==  AddNotNullConstraint: migrating ===========================================
-- change_column_null(:payments, :amount, false)
D, [2024-08-29T17:40:13.663744 #97833] DEBUG -- :    (0.8ms)  ALTER TABLE "payments" ALTER COLUMN "amount" SET NOT NULL
   -> 0.0008s
-- remove_check_constraint(:payments, "amount IS NOT NULL", {:name=>"amount_is_not_null", :validate=>false})
D, [2024-08-29T17:40:13.665126 #97833] DEBUG -- :    (0.6ms)  ALTER TABLE "payments" DROP CONSTRAINT "amount_is_not_null"
   -> 0.0014s
==  AddNotNullConstraint: migrated (0.0022s) ==================================

.

Finished in 0.032080s, 31.1721 runs/s, 124.6883 assertions/s.
1 runs, 4 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior

`remove_check_constraint` fails with the following error.  This is the output in 7.2.1. Similarly for the main branch.

```
# Running:

==  AddCheckConstraint: migrating =============================================
-- add_check_constraint(:payments, "amount IS NOT NULL", {:name=>"amount_is_not_null", :validate=>false})
D, [2024-08-29T17:42:19.429752 #97885] DEBUG -- :    (2.6ms)  ALTER TABLE "payments" ADD CONSTRAINT amount_is_not_null CHECK (amount IS NOT NULL) NOT VALID
   -> 0.0028s
==  AddCheckConstraint: migrated (0.0028s) ====================================

==  ValidateCheckConstraint: migrating ========================================
-- validate_check_constraint(:payments, {:name=>"amount_is_not_null"})
D, [2024-08-29T17:42:19.434150 #97885] DEBUG -- :    (1.2ms)  ALTER TABLE "payments" VALIDATE CONSTRAINT "amount_is_not_null"
   -> 0.0043s
==  ValidateCheckConstraint: migrated (0.0044s) ===============================

==  AddNotNullConstraint: migrating ===========================================
-- change_column_null(:payments, :amount, false)
D, [2024-08-29T17:42:19.436597 #97885] DEBUG -- :    (1.0ms)  ALTER TABLE "payments" ALTER COLUMN "amount" SET NOT NULL
   -> 0.0010s
-- remove_check_constraint(:payments, "amount IS NOT NULL", {:name=>"amount_is_not_null", :validate=>false})
E

Finished in 0.010987s, 91.0167 runs/s, 91.0167 assertions/s.

  1) Error:
BugTest#test_migration:
ArgumentError: Table 'payments' has no check constraint for amount IS NOT NULL
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1778:in `check_constraint_for!'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1308:in `remove_check_constraint'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/migration/default_strategy.rb:10:in `method_missing'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/migration.rb:1059:in `block in method_missing'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/migration.rb:1025:in `block in say_with_time'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/3.2.0/benchmark.rb:296:in `measure'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/migration.rb:1025:in `say_with_time'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/migration.rb:1048:in `method_missing'
    test.rb:53:in `change'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/migration.rb:994:in `exec_migration'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/migration.rb:978:in `block (2 levels) in migrate'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/3.2.0/benchmark.rb:296:in `measure'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/migration.rb:977:in `block in migrate'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:389:in `with_connection'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/migration.rb:976:in `migrate'
    /Users/kazuma.watanabe/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.2.1/lib/active_record/migration.rb:741:in `migrate'
    test.rb:65:in `test_migration'

1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
```

To avoid this error, you need to run `remove_check_constraint` with `validate: true`, but this is unsafe as it may acquire a long-term exclusive lock on a large table if it gets rolled back.

The only workaround is to explicitly define the `down` method, but that clearly seems redundant.

```ruby
class AddNotNullConstraint < ActiveRecord::Migration::Current
  def up
    change_column_null :payments, :amount, false
    remove_check_constraint :payments, "amount IS NOT NULL", name: "amount_is_not_null", validate: true
  end

  def down
    add_check_constraint :payments, "amount IS NOT NULL", name: "amount_is_not_null", validate: false
    change_column_null :payments, :amount, true
  end
end
```

Strictly speaking, it is debatable whether the `AddNotNullConstraint` should be able to be rolled back automatically, since it does not revert to the previous state even if it is rolled back, but considering the above scenario, I believe it would be more useful to have it be reversible.

Incidentally, this issue is fixed by https://github.com/rails/rails/pull/52345.

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.2.4

**Comment by fatkodima** [comment]
`:validate` is a valid option to `remove_check_constraint` - it means remove this check constraint only if it is valid. The same for foreign keys, which can be invalid too.

Rolling back migrations in production is a bad practice. People usually only migrate forward with new migrations, reverting the changes in the previous migrations.

Or, if you still want to rollback in production, there is a workaround with `up`/`down` methods discovered.

**Comment by jeromedalbert** [comment]
> `:validate` is a valid option to `remove_check_constraint` - it means remove this check constraint only if it is valid. The same for foreign keys, which can be invalid too.
> 
> Rolling back migrations in production is a bad practice. People usually only migrate forward with new migrations, reverting the changes in the previous migrations.
> 
> Or, if you still want to rollback in production, there is a workaround with `up`/`down` methods discovered.

Wondering if this use of `:validate` should be documented for `remove_check_constraint` and `remove_foreign_key`.

**Comment by wata727** [comment]
Thank you for your reply. If this behavior is intended, fair enough.
I agree that you shouldn't rollback migrations in production, however I always try to implement reversible migrations, so someone else might run into this issue too. The underlying issue may be confusing the distinction between options for reverting (e.g. `expression`) and options for the command.

> Wondering if this use of :validate should be documented for remove_check_constraint and remove_foreign_key then.

It might be a good idea to add documentation for these options, but it would mostly just be a copy of `add_check_constraint` and `add_foreign_key` - I'm not sure if this will solve the issue.

---

As my issue has been solved, closing this issue. Please feel free to continue discussing any additional related topics. Thank you for your feedback.
