### ISSUE TITLE
Cannot run `bin/rubocop --auto-gen-config` with default binstub

### ISSUE THREAD

**Issue by Uaitt** [rails/rails#52878]
### Steps to reproduce
1. `rails new example_app`
2. `cd example_app`
3. `bin/rubocop --auto-gen-config` will output:
     ```
    different prefix: "" and "/Users/lorenzozabot/example_app"
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/3.3.0/pathname.rb:534:in `relative_path_from'
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.66.1/lib/rubocop/cli/command/auto_generate_config.rb:159:in `relative_path_to_todo_from_options_config'
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.66.1/lib/rubocop/cli/command/auto_generate_config.rb:116:in `add_inheritance_from_auto_generated_file'
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.66.1/lib/rubocop/cli/command/auto_generate_config.rb:104:in `reset_config_and_auto_gen_file'
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.66.1/lib/rubocop/cli/command/auto_generate_config.rb:27:in `run'
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.66.1/lib/rubocop/cli/command.rb:11:in `run'
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.66.1/lib/rubocop/cli/environment.rb:18:in `run'
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.66.1/lib/rubocop/cli.rb:122:in `run_command'
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.66.1/lib/rubocop/cli.rb:127:in `execute_runners'
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.66.1/lib/rubocop/cli.rb:51:in `block in run'
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.66.1/lib/rubocop/cli.rb:81:in `profile_if_needed'
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.66.1/lib/rubocop/cli.rb:43:in `run'
    /Users/lorenzozabot/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.66.1/exe/rubocop:19:in `<top (required)>'
    bin/rubocop:8:in `load'
    bin/rubocop:8:in `<main>'
     ```

If I overwrite the bistunb with `bundle binstub rubocop --force` then I can correctly run `bin/rubocop --auto-gen-config`. 

The problem is probably in this line:
```rb
ARGV.push("--config", File.expand_path("../.rubocop.yml", __dir__))
```
Since if I comment it in the default binstub I can also safely run `bin/rubocop --auto-gen-config`.

### Expected behavior

I expect to be able to run `bin/rubocop --auto-gen-config` correctly.

### Actual behavior

With the default binstub, we cannot run `bin/rubocop --auto-gen-config`.

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.3.5

**Rubocop version**: 1.66.1

**Comment by mohits** [comment]
I think I had written about [this issue regarding binstubs on Windows](https://notepad.onghu.com/2024/fix-rails-main-on-windows-rubocop-error/) and filed this: https://github.com/rails/rails/issues/51618 which is closed. Are these different?

**Comment by Uaitt** [comment]
@mohits I don't think those issues are related 🤔.

Here:
- the issue happens when you explicitly run `bin/rubocop --auto-gen-config`, not when you run a generator.
- the issue is platform independent (probably). I reproduced it on Linux and MacOS, I didn't try Windows tho.
