### ISSUE TITLE
`ActionController::RoutingError` raised when using middleware with `recognize_path`

### ISSUE THREAD

**Issue by joshuay03** [rails/rails#52881]
**Note:** This only happens on `main`. Cannot replicate with `7.2.1`.

### Steps to reproduce

Follow the ["Contributing to the Rails Code" guide](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-code) up to the the ["Running an Application Against Your Local Branch" step](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#running-an-application-against-your-local-branch).

Create a file `lib/middleware/recognize_path_middleware.rb`:

```ruby
# frozen_string_literal: true

class RecognizePathMiddleware
  def initialize(app)
    @app = app
  end

  def call(env)
    p "Hello there"
    # comment this line out to get rid of the error on main, works fine with 7.2.1 though
    p Rails.application.routes.recognize_path(env['PATH_INFO'], method: env['REQUEST_METHOD'])
    @app.call(env)
  end
end
```

Add these lines in `config/application.rb`:

```ruby
require_relative "../lib/middleware/recognize_path_middleware"
config.middleware.insert 1, RecognizePathMiddleware
```

Start the puma server with `bundle exec bin/rails s` and navigate to `http://[::1]:3000`.

### Expected behavior

Should load root url with Rails logo.

### Actual behavior

Raises an `ActionController::RoutingError`. This is displayed on the page:

```
Puma caught this error: No route matches "/" (ActionController::RoutingError)
/.../rails/rails/actionpack/lib/action_dispatch/routing/route_set.rb:952:in `recognize_path_with_request'
/.../rails/rails/actionpack/lib/action_dispatch/routing/route_set.rb:923:in `recognize_path'
/.../rails/my-test-app/lib/middleware/recognize_path_middleware.rb:11:in `call'
/.../rails/rails/actionpack/lib/action_dispatch/middleware/host_authorization.rb:143:in `call'
/.../rails/rails/railties/lib/rails/engine.rb:536:in `call'
/.../rails/my-test-app/.bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
/.../rails/my-test-app/.bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
/.../rails/my-test-app/.bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/.../rails/my-test-app/.bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
/.../rails/my-test-app/.bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
/.../rails/my-test-app/.bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
/.../rails/my-test-app/.bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

Logs:

```
"Hello there"
"/"
"GET"
2024-09-12 06:54:47 +1000 Rack app ("GET /" - (::1)): #<ActionController::RoutingError: No route matches "/">
```

Logs from 7.2.1 for comparison:

```
"Hello there"
"/"
"GET"
{:controller=>"rails/welcome", :action=>"index"}
Started GET "/" for ::1 at 2024-09-12 06:53:19 +1000
  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC /*application='MyTestApp'*/
  ↳ lib/middleware/recognize_path_middleware.rb:11:in `call'
Processing by Rails::WelcomeController#index as HTML
  Rendering /.../.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /.../.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/templates/rails/welcome/index.html.erb (Duration: 0.4ms | GC: 0.0ms)
Completed 200 OK in 51ms (Views: 3.3ms | ActiveRecord: 0.0ms (0 queries, 0 cached) | GC: 0.0ms)
```

### System configuration
**Rails version**: 8.0.0.alpha

**Ruby version**: 3.3.4

**Comment by jhawthorn** [comment]
@joshuay03 could you check your reproduction? I see `TestMiddleware` rather than `RecognizePathMiddleware`, maybe you copied the wrong file? 😅

**Comment by joshuay03** [comment]
> @joshuay03 could you check your reproduction? I see `TestMiddleware` rather than `RecognizePathMiddleware`, maybe you copied the wrong file? 😅

Whoops, sorry about that. I've updated the title and description.
