### ISSUE TITLE
Syntax error on first db:migrate after upgrading to rails 6

### ISSUE THREAD

**Issue by xSlok** [rails/rails#52954]
### Steps to reproduce
after upgrating from rails 5.2 to rails 6.1 and ruby 2.7.2 to 3.3.5 I'm facing some weird errors syntax errors when running the initial migration. The application runs fine and even run the migrations if the table ar_internal_metadata has been created in the previous rails version (tried breaking the first migration and running db:migrate to see the difference between versions. On 5.2 it creates both schema_migrations and ar_internal_metadata, while on 6.1 it only creates schema_migrations and throws an exception)

The error I see when running rails db:migrate is this:
```
** Execute db:load_config
** Execute db:migrate
rails aborted!
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "("
LINE 1: ...ter varying, "created_at" timestamp with time zone(6) NOT NU...
                                                             ^
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:49:in `exec'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:49:in `block (2 levels) in execute'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-6.1.7.8/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block in execute'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-6.1.7.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-6.1.7.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-6.1.7.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-6.1.7.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-6.1.7.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-6.1.7.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `execute'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:322:in `create_table'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/internal_metadata.rb:49:in `create_table'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/migration.rb:1229:in `initialize'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/migration.rb:1086:in `new'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/migration.rb:1086:in `up'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/migration.rb:1061:in `migrate'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/tasks/database_tasks.rb:237:in `migrate'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <top (required)>'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/railties/databases.rake:90:in `each'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <top (required)>'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/railties-6.1.7.8/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/railties-6.1.7.8/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/railties-6.1.7.8/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/railties-6.1.7.8/lib/rails/command.rb:50:in `invoke'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/railties-6.1.7.8/lib/rails/commands.rb:18:in `<top (required)>'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
/home/user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
bin/rails:4:in `<main>'
```

and this is my gemfile

```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

ruby '3.3.5'

gem 'rails', '~> 6.1', '>= 6.1.7.8'
gem 'pg', '~> 1.5', '>= 1.5.8'
gem 'puma', '~> 3.7'
gem 'sassc-rails'
gem 'terser'
gem 'coffee-rails', '~> 4.2'
gem 'coffee-script-source', '1.8.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'recaptcha'
gem 'deep_cloneable', '~> 3.0'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'capybara'
  gem 'selenium-webdriver', '~> 3.142'
  gem 'database_cleaner-active_record'
  gem 'capybara-select2'
  gem 'webmock'
  gem 'factory_bot_rails'
  gem 'uniform_notifier'
  gem 'bullet'
  gem 'rails-controller-testing'
  gem 'fake_ftp', '~> 0.3.0'
  gem 'readapt'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'capistrano', '= 3.14.1', require: false
  gem 'capistrano-rails', '~> 1.3', require: false
  gem 'capistrano3-puma', require: false
  gem 'capistrano-rvm', require: false
  gem 'rufo'
  gem 'htmlbeautifier'
end

gem 'tzinfo-data'
gem 'twitter-bootstrap-rails'
gem 'rails-i18n', '~> 7.0', '>= 7.0.9'
gem 'jquery-ui-rails'
gem 'will_paginate'
gem 'will_paginate-bootstrap4'
gem 'will_paginate-bootstrap'
gem 'momentjs-rails'
gem 'datetime_picker_rails', '~> 0.0.7'
gem 'cpf_cnpj'
gem 'rest-client'
gem 'devise'
gem 'devise_token_auth'
gem 'pundit', '~> 2.0', '>= 2.0.1'
gem 'activesupport-decorators', '~> 2.1'
gem 'rufus-scheduler', '~> 3.4.0'
gem 'redis', '~> 4.0'
gem 'ros-apartment', require: 'apartment'
gem "sidekiq", "~> 6.4.0"
gem 'ros-apartment-sidekiq', require: 'apartment-sidekiq'
gem 'sidekiq-cron'
gem 'sidekiq-status'
gem 'activejob-uniqueness', require: 'active_job/uniqueness/sidekiq_patch'
gem 'sendgrid-ruby'
gem 'wkhtmltopdf-binary', '~> 0.12.6'
gem 'wicked_pdf'
gem 'correios-cep'
gem 'rspec-rails', '~> 6.1', '>= 6.1.5'
gem 'rails_db', '~> 2.3', '>= 2.3.1'
gem 'roo', '~> 2.7', '>= 2.7.1'
gem 'caxlsx'
gem 'caxlsx_rails'
gem 'combine_pdf', '1.0.15'
gem 'newrelic_rpm'
gem 'mini_magick'
gem 'aws-sdk-s3'
gem 'awesome_print'
gem 'dropbox_api', '~> 0.1.17'
gem 'fast_jsonapi'
gem 'date_validator', '~> 0.9.0'
gem 'audited', '~> 4.9'
gem 'exception_handler', '~> 0.8.0.0'
gem 'exception_notification'
gem 'slack-notifier'
gem 'httparty'
gem 'rack-cors'
gem 'dotiw', '~> 4.0', '>= 4.0.1'
gem 'ean'
gem 'discordrb', '~> 3.4'
gem 'rake', '= 13.0.3'
gem 'net-ftp'
gem 'net-sftp'
gem 'rubyzip'
gem 'ajax-datatables-rails'
gem 'rack-attack'
gem 'timecop'
gem "viacep"
gem 'oj', '3.12.3'
gem 'bigdecimal', '2.0.2'
gem "inertia_rails", "~> 3.2"
gem "vite_rails"
gem 'overmind', '~> 2.5', '>= 2.5.1'
```

### Expected behavior
Migration being run correctly

### Actual behavior
syntax error on something outside of my code

### System configuration
**Rails version**: 6.1.7.8

**Ruby version**: 3.3.5

**Comment by rafaelfranca** [comment]
Did you upgrade to 6.0 first? Rails upgrade process doesn't support skipping versions.

**Comment by xSlok** [comment]
Interesting. I did not. That's required even for minor versions? 6.0 before 6.1

**Comment by xSlok** [comment]
I was able to run the migration by manually creation that table, but that's obviously not the best solution
```
ActiveSupport.on_load(:active_record) do
  connection = ActiveRecord::Base.connection
  unless connection.table_exists?('ar_internal_metadata')
    connection.execute <<-SQL
        CREATE TABLE "ar_internal_metadata" (
        "key" character varying NOT NULL PRIMARY KEY,
        "value" character varying,
        "created_at" timestamp([6](https://bitbucket.org/Almmati/distribuidora_eficaz/pull-requests/5455/diff#Lconfig/initializers/rails_v6_hack.rbT6)) with time zone NOT NULL,
        "updated_at" timestamp(6) with time zone NOT NULL
      )
    SQL
  end
end
```

**Comment by rafaelfranca** [comment]
> Interesting. I did not. Is that required even for minor versions? 6.0 before 6.1

Yes. It is only not required for patch level

> I was able to run the migration by manually creation that table, but that's obviously not the best solution

Yes, that should not be the solution. It is possible that you are using some deprecated feature that was remove in 6.1

I remember between some version the time columns started to have default precision.

Maybe this one https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#rails-version-is-now-included-in-the-active-record-schema-dump
