### ISSUE TITLE
Can't run rails when parent directory contains Gemfile which includes rails

### ISSUE THREAD

**Issue by coezbek** [rails/rails#53080]
### Steps to reproduce

```
# Create new directory
mkdir demo
cd demo
# Create Gemfile with rails
bundle init
bundle add rails
# Create a subdir
mkdir subdir
cd subdir
# Try to run rails new with esbuild in the subdir
rails new app -j esbuild
```

Fails with the following error:
```
      create  
      create  README.md
<... snip ...>
      create  Gemfile
<...snip...>
      remove  config/initializers/new_framework_defaults_7_2.rb
         run  bundle install --quiet
         run  bundle lock --add-platform=x86_64-linux
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Writing lockfile to /home/coezbek/2024/rails-bug/subdir/app/Gemfile.lock
         run  bundle binstubs bundler
       rails  javascript:install:esbuild
<internal:/usr/share/rvm/rubies/ruby-3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- bootsnap/setup (LoadError)
        from <internal:/usr/share/rvm/rubies/ruby-3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/coezbek/2024/rails-bug/subdir/app/config/boot.rb:4:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>'
       rails  turbo:install stimulus:install
<internal:/usr/share/rvm/rubies/ruby-3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- bootsnap/setup (LoadError)
        from <internal:/usr/share/rvm/rubies/ruby-3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/coezbek/2024/rails-bug/subdir/app/config/boot.rb:4:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>'
```
There are two parts to the bug:

1. The `rails  javascript:install:esbuild` fails at all. It seems it is using the parent directory Gemfile which doesn't include `bootsnap`
2. The build does not stop when the task fails. It is marked as success.

```ruby
require 'minitest/autorun'
require 'fileutils'
require 'tmpdir'

class RailsAppCreationTest < Minitest::Test
  def setup
    @tmpdir = Dir.mktmpdir
  end

  def test_rails_new_with_esbuild
    Dir.chdir(@tmpdir) do
      # Initialize the Gemfile and add rails
      system('bundle init')
      system('bundle add rails')

      # Create a subdirectory and try to run rails new with esbuild
      subdir = File.join(@tmpdir, 'subdir')
      FileUtils.mkdir_p(subdir)

      Dir.chdir(subdir) do
        output = `rails new app -j esbuild 2>&1`
        assert($?.success?, "Expected rails new command to succeed, but it failed with output:\n#{output}")

        # Ensure the JavaScript file is created
        assert(File.exist?('app/app/javascript/application.js'), 'Expected app/javascript/application.js to be created')

        # Check that no "require': cannot load such file -- bootsnap/setup" error occurs in the output
        refute_match(/require': cannot load such file -- bootsnap\/setup/, output, "Unexpected bootsnap error found")
      end
    end
  end

  def teardown
    FileUtils.remove_entry @tmpdir
  end
end
```

### Expected behavior

- `rails new app -j esbuild` should succeed and create the app including esbuild being set up
- If a rails task fails during `rails new` execution should stop.
- If running in a subdirectory of a directory which contains a Gemfile is not supported, then rails should abort. 

### Actual behavior

- `rails` uses the Gemfile from parent directory.
- `rails` doesn't stop when the sub task `javascript:install:esbuild` fails

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.2.4

**Comment by yahonda** [comment]
Hi, I'm closing this issue because this is an exptected behavior. We need to create a new Rails application outside of the existing Rails application directory.

**Comment by coezbek** [comment]
@yahonda May I investigate, why `rails new` didn't abort (e.g. `exit 1`) when `javascript:install:esbuild` failed, or is this also expected?
