### ISSUE TITLE
"Cannot expire connection, it is owned by a different thread" in Rails 7.2 tests when `migration_error = :page_load` option is set

### ISSUE THREAD

**Issue by fwolfst** [rails/rails#53147]
### Steps to reproduce

See the repo to reproduce at https://github.com/betterplace/showcase_rails_7_2_connection_expiry_thread_bug and its README.

In the process of updating from Rails 7.1 to 7.2.1, our CI failed with "Cannot expire connection, it is owned by a different thread" errors, which were reproducible locally.

The error seems to only get thrown when you execute a single spec/specs in specific order and the setting 
```ruby
config.active_record.migration_error = :page_load
```

is set.

A prior similar error was found in https://github.com/rails/rails/issues/52973 and fixed in https://github.com/rails/rails/pull/53118 , but it didnt resolve this occurence.

### Expected behavior

Spec succeeds, or fails with actual expectation mismatch.

### Actual behavior

An error is thrown during spec execution:
```bash
Failures:

  1) Row with a row fights over threads and transactions
     Failure/Error:
       raise ActiveRecordError, "Cannot expire connection, " \
         "it is owned by a different thread: #{@owner}. " \
         "Current thread: #{ActiveSupport::IsolatedExecutionState.context}."

     ActiveRecord::ActiveRecordError:
       Cannot expire connection, it is owned by a different thread: #<Thread:0x000000010a5df4e8@puma srv tp 001 /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/puma-6.4.3/lib/puma/thread_pool.rb:113 sleep>. Current thread: #<Thread:0x000000010493b110 run>.
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-6662c51d6ee8/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:316:in `expire'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-6662c51d6ee8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:580:in `block (3 levels) in checkin'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:110:in `run_callbacks'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:913:in `_run_checkin_callbacks'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-6662c51d6ee8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:579:in `block (2 levels) in checkin'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/monitor.rb:202:in `synchronize'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/monitor.rb:202:in `mon_synchronize'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-6662c51d6ee8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:576:in `block in checkin'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-7.2.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-6662c51d6ee8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:575:in `checkin'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-6662c51d6ee8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:362:in `block in unpin_connection!'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-7.2.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `handle_interrupt'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-7.2.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `block in synchronize'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-7.2.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-7.2.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-6662c51d6ee8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:347:in `unpin_connection!'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-6662c51d6ee8/activerecord/lib/active_record/test_fixtures.rb:193:in `map'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-6662c51d6ee8/activerecord/lib/active_record/test_fixtures.rb:193:in `teardown_transactional_fixtures'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-6662c51d6ee8/activerecord/lib/active_record/test_fixtures.rb:148:in `teardown_fixtures'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-6662c51d6ee8/activerecord/lib/active_record/test_fixtures.rb:17:in `after_teardown'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-7.2.1/lib/active_support/current_attributes/test_helper.rb:10:in `after_teardown'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-7.2.1/lib/active_support/execution_context/test_helper.rb:10:in `after_teardown'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-rails-7.0.1/lib/rspec/rails/adapters.rb:76:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example.rb:352:in `call'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/hooks.rb:486:in `run'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example.rb:259:in `run'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example_group.rb:642:in `map'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example_group.rb:642:in `run_examples'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example_group.rb:607:in `run'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example_group.rb:608:in `block in run'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example_group.rb:608:in `map'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example_group.rb:608:in `run'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:121:in `map'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/configuration.rb:2092:in `with_suite_hooks'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:89:in `run'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:71:in `run'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rspec-core-3.13.1/exe/rspec:4:in `<top (required)>'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/bin/rspec:25:in `load'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/bin/rspec:25:in `<top (required)>'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:492:in `exec'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/exe/bundle:37:in `block in <top (required)>'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/exe/bundle:29:in `<top (required)>'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/bin/bundle:25:in `load'
     # /Users/iwishwewoulduselinux/.asdf/installs/ruby/3.2.0/bin/bundle:25:in `<main>'
     #
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

```

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.2.5 (but "only" reproduced in given repo with 3.2.0 by accident)

**Comment by byroot** [comment]
I'll have a look, but it would be very helpful if you could provide a small repo to reproduce the issue.

**Comment by byroot** [comment]
Also please provide the full error backtrace.

**Comment by fwolfst** [comment]
> I'll have a look, but it would be very helpful if you could provide a small repo to reproduce the issue.

Sure, it is still linked in the first line of the issue ;)
https://github.com/betterplace/showcase_rails_7_2_connection_expiry_thread_bug

**Comment by byroot** [comment]
> Sure, it is still linked in the first line of the issue ;)

🤦 I shouldn't look at issues before I finish my coffee.

**Comment by byroot** [comment]
Alright, I know have a good understanding of what is going on.

- `check_pending_migration` uses `with_temporary_pool`.
- So it creates a new temporary pool, which triggers the `!connection.active_record` subscription in `test_fixtures.rb` and automatically pins the pool with the Puma thread as owner.
- When `with_temporary_pool` is exited by Puma, the pool is disconnected, but remains pinned.
- So later when tearing down transactional fixtures, the unpinning fails because the pinned connection is owned by another thread.

I have a few ideas how to fix that, need to try them out and see what is cleaner.

**Comment by fwolfst** [comment]
> Got a fix: #53154

Gosh, the patch looks so innocent (besides the theft)! Will validate (and close ticket?) day after tomorrow (european friday). Awesome, thanks a lot!

**Comment by fwolfst** [comment]
Confirmed fix. Adding `gem 'activerecord', git: 'https://github.com/rails/rails', branch: '7-2-stable'` makes CI green.

**Comment by kasperite** [comment]
@byroot any idea when this fix will be released?

**Comment by ssunday** [comment]
@kasperite +1, this is blocking updating to Rails 7.2 for us

**Comment by ssunday** [comment]
Looks like 7.2.2 has it https://github.com/rails/rails/releases/tag/v7.2.2
