### ISSUE TITLE
Two of `TransactionCallbacksTest` raise `warning: redefining 'object_id' may cause serious problems` with Ruby 3.4.0dev

### ISSUE THREAD

**Issue by yahonda** [rails/rails#53266]
Managed to reproduce Rails Nightly CI failure at https://buildkite.com/rails/rails-nightly/builds/1142#0192783c-6957-440f-bb57-4e4abb1acece since https://github.com/ruby/ruby/commit/5792bd7149a30f7f43a739199d84603cc579f4e5

### Steps to reproduce
1. Install Ruby 3.4.0dev
2. Run these commands below
```ruby
git clone https://github.com/rails/rails/
cd rails/activerecord
bundle install
RAILS_STRICT_WARNINGS=1 ARCONN=sqlite3 bin/test test/cases/transaction_callbacks_test.rb -n /test_saving_two_records_that_override_object_id/
```

### Expected behavior
All of tests should pass.

### Actual behavior
Since Rails CI enables `RAILS_STRICT_WARNINGS=1`, these warnings raises `ActiveSupport::RaiseWarnings::WarningError` exception below.

```ruby
$ RAILS_STRICT_WARNINGS=1 ARCONN=sqlite3 bin/test test/cases/transaction_callbacks_test.rb -n /test_saving_two_records_that_override_object_id/
/home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.4.0+0/gems/minitest-5.25.1/lib/minitest/mock.rb:33: warning: redefining 'object_id' may cause serious problems
Using sqlite3
Run options: -n /test_saving_two_records_that_override_object_id/ --seed 35185

# Running:

/home/yahonda/src/github.com/rails/rails/activerecord/test/cases/transaction_callbacks_test.rb:524: warning: redefining 'object_id' may cause serious problems
E

Error:
TransactionCallbacksTest#test_saving_two_records_that_override_object_id_should_run_after_rollback_callbacks_for_both:
ActiveSupport::RaiseWarnings::WarningError: /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/transaction_callbacks_test.rb:524: warning: redefining 'object_id' may cause serious problems

    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/strict_warnings.rb:38:in 'ActiveSupport::RaiseWarnings#warn'
    test/cases/transaction_callbacks_test.rb:524:in 'Module#define_method'
    test/cases/transaction_callbacks_test.rb:524:in 'block in TransactionCallbacksTest#test_saving_two_records_that_override_object_id_should_run_after_rollback_callbacks_for_both'
    test/cases/transaction_callbacks_test.rb:523:in 'Class#initialize'
    test/cases/transaction_callbacks_test.rb:523:in 'Class#new'
    test/cases/transaction_callbacks_test.rb:523:in 'TransactionCallbacksTest#test_saving_two_records_that_override_object_id_should_run_after_rollback_callbacks_for_both'


bin/test test/cases/transaction_callbacks_test.rb:522

/home/yahonda/src/github.com/rails/rails/activerecord/test/cases/transaction_callbacks_test.rb:506: warning: redefining 'object_id' may cause serious problems
E

Error:
TransactionCallbacksTest#test_saving_two_records_that_override_object_id_should_run_after_commit_callbacks_for_both:
ActiveSupport::RaiseWarnings::WarningError: /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/transaction_callbacks_test.rb:506: warning: redefining 'object_id' may cause serious problems

    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/strict_warnings.rb:38:in 'ActiveSupport::RaiseWarnings#warn'
    test/cases/transaction_callbacks_test.rb:506:in 'Module#define_method'
    test/cases/transaction_callbacks_test.rb:506:in 'block in TransactionCallbacksTest#test_saving_two_records_that_override_object_id_should_run_after_commit_callbacks_for_both'
    test/cases/transaction_callbacks_test.rb:505:in 'Class#initialize'
    test/cases/transaction_callbacks_test.rb:505:in 'Class#new'
    test/cases/transaction_callbacks_test.rb:505:in 'TransactionCallbacksTest#test_saving_two_records_that_override_object_id_should_run_after_commit_callbacks_for_both'


bin/test test/cases/transaction_callbacks_test.rb:504



Finished in 0.029797s, 67.1218 runs/s, 0.0000 assertions/s.
2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.4.0dev (2024-10-10T03:53:11Z master 5792bd7149) +PRISM [x86_64-linux]

**Comment by yahonda** [comment]
These tests have been updated via https://github.com/rails/rails/commit/8d3ca97032d
