### ISSUE TITLE
[ActiveRecord] Store accessor breaks when using migration default hash value

### ISSUE THREAD

**Issue by democlitos** [rails/rails#53299]
Context: I'm working in an application running rails 7.0.4. After upgrading to 7.1.4, psych gem was added to the dependency tree, and seems to throw an error when a default hash value is used in the schema.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "7.1.4"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(
  adapter:    'postgresql',
  host:       'localhost',
  database:   'mydb',
  username:   'myuser',
  password:   '123456',
  port:       5432
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :stocks, force: true do |t|
    t.jsonb :data, default: {"amount"=>0.0}
  end
end

class Stock < ActiveRecord::Base
  store :data, accessors: [:amount, :name]

  after_initialize :set_default_stored_attributes

  private

  def set_default_stored_attributes
    self.name ||= 'Product'
  end
end

class BugTest < Minitest::Test
  def test_store
    stock = Stock.new

    assert_equal "Product", stock.name
  end
end
```

### Expected behavior

ActiveRecord should initialize the default value for the name attribute

### Actual behavior

Psych parser throws an error <code>no implicit conversion of Hash into String (TypeError)</code>

```
/usr/share/rvm/rubies/ruby-3.0.5/lib/ruby/3.0.0/psych.rb:457:in `parse': no implicit conversion of Hash into String (TypeError)
	from /usr/share/rvm/rubies/ruby-3.0.5/lib/ruby/3.0.0/psych.rb:457:in `parse_stream'
	from /usr/share/rvm/rubies/ruby-3.0.5/lib/ruby/3.0.0/psych.rb:391:in `parse'
	from /usr/share/rvm/rubies/ruby-3.0.5/lib/ruby/3.0.0/psych.rb:351:in `safe_load'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activerecord-7.1.4/lib/active_record/coders/yaml_column.rb:37:in `load'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activerecord-7.1.4/lib/active_record/coders/column_serializer.rb:37:in `load'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activerecord-7.1.4/lib/active_record/store.rb:275:in `load'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activerecord-7.1.4/lib/active_record/type/serialized.rb:22:in `deserialize'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activemodel-7.1.4/lib/active_model/attribute.rb:175:in `type_cast'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activemodel-7.1.4/lib/active_model/attribute.rb:43:in `value'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activemodel-7.1.4/lib/active_model/attribute_set.rb:51:in `fetch_value'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activerecord-7.1.4/lib/active_record/attribute_methods/read.rb:51:in `_read_attribute'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activemodel-7.1.4/lib/active_model/attribute_methods.rb:284:in `data'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activerecord-7.1.4/lib/active_record/store.rb:251:in `prepare'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activerecord-7.1.4/lib/active_record/store.rb:225:in `read'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activerecord-7.1.4/lib/active_record/store.rb:211:in `read_store_attribute'
	from /usr/share/rvm/gems/ruby-3.0.5/gems/activerecord-7.1.4/lib/active_record/store.rb:143:in `block (3 levels) in store_accessor'
```

### System configuration
**Rails version**: 7.1.4

**Ruby version**: 3.0.5

**Comment by justinko** [comment]
This is when the behavior changed: https://github.com/rails/rails/commit/185f2d718d4f971ef4d45c252ec2db3db6fb0f89#diff-935494b14b54c907fc1d206871d2a4797c490b80f2c86d61a7264131dd492e42L51

Basically, for a `jsonb` column, you want the default value to be JSON! Just wrap your default value to convert it: `JSON({"amount"=>0.0})`

**Comment by danpolyuha** [comment]
I've found a better solution:
```ruby
store :data, accessors: [:amount, :name], coder: ActiveRecord::Coders::JSON
```

[justinko](https://github.com/justinko)'s solution is great, but has a small flaw I didn't know how to fix: if you initialize a model without saving to DB, column will have string value.

**Comment by maxcodes** [comment]
for me, the issue was that I was using `store :data, accessors: [:amount, :name]` when I meant to use `store_accessor :data, :amount, :name`
