### ISSUE TITLE
New install: An error occurred while installing psych (5.1.2), and Bundler cannot continue.

### ISSUE THREAD

**Issue by BarberEngineering** [rails/rails#53306]
### Steps to reproduce
1. new install of ruby, sqlite3
2. Follow documentation
3. gem install rails
4. rails new blog
5. cd blog
6. ruby bin/rails serve <--- error

```ps
      remove  config/initializers/new_framework_defaults_7_2.rb
         run  bundle install --quiet
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: C:/Ruby/lib/ruby/gems/3.3.0/gems/psych-5.1.2/ext/psych
C:/Ruby/bin/ruby.exe extconf.rb
checking for pkg-config for yaml-0.1... not found
checking for yaml.h... no
yaml.h not found
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include=${opt-dir}/include
        --without-opt-include
        --with-opt-lib=${opt-dir}/lib
        --without-opt-lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby/bin/$(RUBY_BASE_NAME)
        --with-libyaml-source-dir
        --without-libyaml-source-dir
        --with-yaml-0.1-dir
        --without-yaml-0.1-dir
        --with-yaml-0.1-include=${yaml-0.1-dir}/include
        --without-yaml-0.1-include
        --with-yaml-0.1-lib=${yaml-0.1-dir}/lib
        --without-yaml-0.1-lib
        --with-yaml-0.1-config
        --without-yaml-0.1-config
        --with-pkg-config
        --without-pkg-config
        --with-libyaml-dir
        --without-libyaml-dir
        --with-libyaml-include=${libyaml-dir}/include
        --without-libyaml-include
        --with-libyaml-lib=${libyaml-dir}/lib
        --without-libyaml-lib

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

C:/Ruby/lib/ruby/gems/3.3.0/extensions/x64-mingw-ucrt/3.3.0/psych-5.1.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby/lib/ruby/gems/3.3.0/gems/psych-5.1.2
for inspection.
Results logged to
C:/Ruby/lib/ruby/gems/3.3.0/extensions/x64-mingw-ucrt/3.3.0/psych-5.1.2/gem_make.out

  C:/Ruby/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
C:/Ruby/lib/ruby/site_ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:28:in
`build'
C:/Ruby/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:193:in
`build_extension'
C:/Ruby/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in
build_extensions'
  C:/Ruby/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
C:/Ruby/lib/ruby/site_ruby/3.3.0/rubygems/ext/builder.rb:224:in
`build_extensions'
C:/Ruby/lib/ruby/site_ruby/3.3.0/rubygems/installer.rb:844:in
`build_extensions'
C:/Ruby/lib/ruby/site_ruby/3.3.0/bundler/rubygems_gem_installer.rb:109:in
`build_extensions'
C:/Ruby/lib/ruby/site_ruby/3.3.0/bundler/rubygems_gem_installer.rb:28:in
`install'
  C:/Ruby/lib/ruby/site_ruby/3.3.0/bundler/source/rubygems.rb:205:in `install'
C:/Ruby/lib/ruby/site_ruby/3.3.0/bundler/installer/gem_installer.rb:55:in
`install'
C:/Ruby/lib/ruby/site_ruby/3.3.0/bundler/installer/gem_installer.rb:17:in
`install_from_spec'
C:/Ruby/lib/ruby/site_ruby/3.3.0/bundler/installer/parallel_installer.rb:133:in
`do_install'
C:/Ruby/lib/ruby/site_ruby/3.3.0/bundler/installer/parallel_installer.rb:124:in
`block in worker_pool'
  C:/Ruby/lib/ruby/site_ruby/3.3.0/bundler/worker.rb:62:in `apply_func'
C:/Ruby/lib/ruby/site_ruby/3.3.0/bundler/worker.rb:57:in `block in
process_queue'
  <internal:kernel>:187:in `loop'
  C:/Ruby/lib/ruby/site_ruby/3.3.0/bundler/worker.rb:54:in `process_queue'
C:/Ruby/lib/ruby/site_ruby/3.3.0/bundler/worker.rb:90:in `block (2 levels) in
create_threads'

An error occurred while installing psych (5.1.2), and Bundler cannot continue.

In Gemfile:
  debug was resolved to 1.9.2, which depends on
    irb was resolved to 1.14.1, which depends on
      rdoc was resolved to 6.7.0, which depends on
        psych
         run  bundle lock --add-platform=x86_64-linux
```

### Expected behavior
Expectation is server would start the first time

### Actual behavior
You get the error above

### Current workaround for those that find this post when searching
> gem install psych
> bundle install in your project directory
> Profit

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.3.0

**Comment by JoeDupuis** [comment]
It's crashing because you're missing a dependency (libyaml).

**Comment by rafaelfranca** [comment]
Yes. This is a problem in your environment that is missing a system library to be able to install part of Ruby's stdlib.

While I'm at it, can I suggest you to give [devcontainers](https://guides.rubyonrails.org/getting_started_with_devcontainer.html) a try? The feature was added exactly for cases like this. You have no experience how to properly setup a Ruby environment and just want to build a Rails app.
