### ISSUE TITLE
Order-dependant test failure in railties with `GeneratorsTest#test_generator_suggestions_except_en_locale`

### ISSUE THREAD

**Issue by Earlopain** [rails/rails#53368]
### Steps to reproduce
Running with 31550306975da257c2eb02c16426e994f6cb5f6e
```
$ cd railties
# If someone could explain how to use minitest_bisect, that would be great :smile: 
$ bin/test --seed 27653
Run options: --seed 27653

# Running:

............................................................................................................................................................................................................E

Error:
GeneratorsTest#test_generator_suggestions_except_en_locale:
I18n::InvalidLocaleData: can not load translations from /home/earlopain/Documents/rails/tmp/d20241018-307935-921g0r/app/config/locales/en.yml: #<Errno::ENOENT: No such file or directory @ rb_sysopen - /home/earlopain/Documents/rails/tmp/d20241018-307935-921g0r/app/config/locales/en.yml>
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n/backend/base.rb:261:in `rescue in load_yml'
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n/backend/base.rb:253:in `load_yml'
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n/backend/base.rb:235:in `load_file'
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n/backend/base.rb:17:in `block in load_translations'
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n/backend/base.rb:16:in `each'
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n/backend/base.rb:16:in `load_translations'
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n/backend/simple.rb:84:in `init_translations'
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n/backend/simple.rb:50:in `available_locales'
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n/config.rb:45:in `available_locales'
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n/config.rb:51:in `available_locales_set'
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n.rb:374:in `locale_available?'
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n.rb:380:in `enforce_available_locales!'
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n/config.rb:36:in `default_locale='
    /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/i18n-1.14.5/lib/i18n.rb:74:in `default_locale='
    test/generators_test.rb:62:in `ensure in test_generator_suggestions_except_en_locale'
    test/generators_test.rb:62:in `test_generator_suggestions_except_en_locale'


bin/test test/generators_test.rb:48

.E

Error:
Rails::Command::RoutesTest#test_rails_routes_with_controller_search_key:
RuntimeError: rails command failed (1): bin/rails routes -c cart 2>&1
FrozenError: can't modify frozen Array: ["/home/earlopain/Documents/rails/tmp/d20241018-307935-921g0r/app/lib"]

    test/isolation/abstract_unit.rb:420:in `rails'
    test/commands/routes_test.rb:421:in `run_routes_command'
    test/commands/routes_test.rb:131:in `block in <class:RoutesTest>'
# And many more thereafter
```

### Extra details
I have traced this back to be caused by the following test https://github.com/rails/rails/blob/094aeca1378fd901510959a956fc887df745f153/railties/test/application/configuration/custom_test.rb. Stubbing this one out resolves the failures. I have no idea about what the solution would be, some global i18n state seems to be modified.

**Comment by zzak** [comment]
I think this fixes it if you want to send a PR:

```diff
diff --git a/railties/test/application/configuration/custom_test.rb b/railties/test/application/configuration/custom_test.rb
index 2690c86747..5158e90d0d 100644
--- a/railties/test/application/configuration/custom_test.rb
+++ b/railties/test/application/configuration/custom_test.rb
@@ -5,6 +5,8 @@
 module ApplicationTests
   module ConfigurationTests
     class CustomTest < ActiveSupport::TestCase
+      include ActiveSupport::Testing::Isolation
+
       def setup
         build_app
         FileUtils.rm_rf("#{app_path}/config/environments")
```

**Comment by Earlopain** [comment]
Yes that's it, thank you. #53377
