### ISSUE TITLE
Active Job duplicates job-related logging tags on retries

### ISSUE THREAD

**Issue by fractaledmind** [rails/rails#53443]
### Steps to reproduce

Run the test case script below:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "8.0.0.rc1"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "active_job"
require "minitest/autorun"

$buffer = []

class DefaultsError < StandardError; end

class RetryJob < ActiveJob::Base
  retry_on DefaultsError, attempts: 2

  def perform(raising, *)
    $buffer << [raising, executions]

    raise raising
  end
end

class BuggyJobTest < ActiveJob::TestCase
  def test_stuff
    out, err = capture_subprocess_io do
      perform_enqueued_jobs do
        assert_raises DefaultsError do
          RetryJob.perform_later DefaultsError
        end
      end
    end

    # The logs show job performed twice before being stopped
    lines = out.split("\n")

    assert_match(
      /Performing RetryJob \(Job ID: .{36}\)/,
      lines[0]
    )
    assert_match(
      /Performing RetryJob \(Job ID: .{36}\)/,
      lines[1]
    )
    assert_match(
      /Stopped retrying RetryJob \(Job ID: .{36}\)/,
      lines[2]
    )

    assert_equal(
      [[DefaultsError, 1], [DefaultsError, 2]],
      $buffer
    )

    # However, the logs aren't appropriately tagged, as retried jobs duplicate the job tags
    assert_match(
      /\[ActiveJob\] \[RetryJob\] \[.{36}\] Performing RetryJob \(Job ID: .{36}\) from Test\(default\) enqueued at .{30} with arguments: DefaultsError/,
      lines[0]
    )
    assert_match(
      /\[ActiveJob\] \[RetryJob\] \[.{36}\] Performing RetryJob \(Job ID: .{36}\) from Test\(default\) enqueued at .{30} with arguments: DefaultsError/,
      lines[1]
    )
    assert_match(
      /\[ActiveJob\] \[RetryJob\] \[.{36}\] Stopped retrying RetryJob \(Job ID: .{36}\) due to a DefaultsError \(DefaultsError\), which reoccurred on 2 attempts/,
      lines[2]
    )
    # logs look like this instead:
    # [ActiveJob] [RetryJob] [{{job_id}}] Performing RetryJob (Job ID: {{job_id}}) from Test(default) enqueued at {{timestamp}} with arguments: DefaultsError
    # [ActiveJob] [RetryJob] [{{job_id}}] [RetryJob] [{{job_id}}] Performing RetryJob (Job ID: {{job_id}}) from Test(default) enqueued at {{timestamp}} with arguments: DefaultsError
    # [ActiveJob] [RetryJob] [{{job_id}}] [RetryJob] [{{job_id}}] [RetryJob] [{{job_id}}] [RetryJob] [{{job_id}}] [RetryJob] [{{job_id}}] Stopped retrying RetryJob (Job ID: {{job_id}}) due to a DefaultsError (DefaultsError), which reoccurred on 2 attempts.
  end
end
```

[gist](https://gist.github.com/fractaledmind/353699ed05fa1151e5b5fec6bccefadc)

### Expected behavior

Active Job should only log one set of job-related tags, even on retries.

### Actual behavior

Active Job logs N job-related tags, one per retry. So, on the second performance after a retry, the log looks like:
```
 [ActiveJob] [RetryJob] [{{job_id}}] [RetryJob] [{{job_id}}] Performing RetryJob (Job ID: {{job_id}}) from Test(default) enqueued at {{timestamp}} with arguments: DefaultsError
```

The issue is the `[RetryJob] [{{job_id}}] [RetryJob] [{{job_id}}]`, which is duplicated. 

### System configuration
**Rails version**: Tested against both versions 8.0.0.rc1, 7.2.1.2, and 7.2.1.1

**Ruby version**: 3.3.4

**Comment by fractaledmind** [comment]
With more investigation, I see that this is due to the behavior of `perform_enqueued_jobs` in the test environment. I do not see this behavior if my test looks like this instead:
```ruby
def test_stuff
  ThreeStepRetryJob.perform_later DefaultsError
   out, err = capture_subprocess_io do
      flush_enqueued_jobs until enqueued_jobs.empty?
   end

# ...
```

`perform_enqueued_jobs` will begin performing a job when `enqueue` is called, and so on retries you dig deeper and deeper into the "job stack" before popping out. I realized this as I was about to create a new issue on the odd logs output by ActiveJob in tests. Here are the logs formatted to show the duplicate tags and the drilling:
```
[ActiveJob] [RetryJob] [ID]
  Performing RetryJob (Job ID: ID) from Test(default) enqueued at TIMESTAMP with arguments: DefaultsError
  perform_start

  [ActiveJob] [RetryJob] [ID]
    [RetryJob] [ID]
    Performing RetryJob (Job ID: ID) from Test(default) enqueued at TIMESTAMP with arguments: DefaultsError
    perform_start

    [ActiveJob] [RetryJob] [ID] 
      [RetryJob] [ID] 
      [RetryJob] [ID] 
      Performing RetryJob (Job ID: ID) from Test(default) enqueued at TIMESTAMP with arguments: DefaultsError
      perform_start

      [ActiveJob] [RetryJob] [ID] 
        [RetryJob] [ID] 
        [RetryJob] [ID] 
        [RetryJob] [ID] 
        Performing RetryJob (Job ID: ID) from Test(default) enqueued at TIMESTAMP with arguments: DefaultsError
        perform_start
    
        [ActiveJob] [RetryJob] [ID] 
          [RetryJob] [ID] 
          [RetryJob] [ID] 
          [RetryJob] [ID] 
          [RetryJob] [ID] 
          Performing RetryJob (Job ID: ID) from Test(default) enqueued at TIMESTAMP with arguments: DefaultsError
          perform_start

        [ActiveJob] [RetryJob] [ID] 
          [RetryJob] [ID] 
          [RetryJob] [ID] 
          [RetryJob] [ID] 
          [RetryJob] [ID] 
          Stopped retrying RetryJob (Job ID: ID) due to a DefaultsError, which reoccurred on 5 attempts.
          retry_stopped

        [ActiveJob] [RetryJob] [ID] 
          [RetryJob] [ID] 
          [RetryJob] [ID] 
          [RetryJob] [ID] 
          [RetryJob] [ID] 
          Error performing RetryJob (Job ID: ID) from Test(default) in 3.15ms: DefaultsError:
            inline.rb:568:in `step_1'
          perform

      [ActiveJob] [RetryJob] [ID] 
        [RetryJob] [ID] 
        [RetryJob] [ID] 
        [RetryJob] [ID] 
        Failed enqueuing RetryJob to Test(default): DefaultsError
        enqueue

      [ActiveJob] [RetryJob] [ID] 
        [RetryJob] [ID] 
        [RetryJob] [ID] 
        [RetryJob] [ID] 
        Retrying RetryJob (Job ID: ID) after 4 attempts in 3 seconds, due to a DefaultsError.
        enqueue_retry

      [ActiveJob] [RetryJob] [ID] 
        [RetryJob] [ID] 
        [RetryJob] [ID] 
        [RetryJob] [ID] 
        Error performing RetryJob (Job ID: ID) from Test(default) in 3.85ms: DefaultsError:
          inline.rb:568:in `step_1'
        perform

    [ActiveJob] [RetryJob] [ID] 
      [RetryJob] [ID] 
      [RetryJob] [ID] 
      Failed enqueuing RetryJob to Test(default): DefaultsError
      enqueue

    [ActiveJob] [RetryJob] [ID] 
      [RetryJob] [ID] 
      [RetryJob] [ID] 
      Retrying RetryJob (Job ID: ID) after 3 attempts in 3 seconds, due to a DefaultsError.
      enqueue_retry

    [ActiveJob] [RetryJob] [ID] 
      [RetryJob] [ID] 
      [RetryJob] [ID] 
      Error performing RetryJob (Job ID: ID) from Test(default) in 4.68ms: DefaultsError:
        inline.rb:568:in `step_1'
      perform

  [ActiveJob] [RetryJob] [ID] 
    [RetryJob] [ID] 
    Failed enqueuing RetryJob to Test(default): DefaultsError
    enqueue

  [ActiveJob] [RetryJob] [ID] 
    [RetryJob] [ID] 
    Retrying RetryJob (Job ID: ID) after 2 attempts in 3 seconds, due to a DefaultsError.
    enqueue_retry

  [ActiveJob] [RetryJob] [ID] 
    [RetryJob] [ID] 
    Error performing RetryJob (Job ID: ID) from Test(default) in 5.61ms: DefaultsError:
      inline.rb:568:in `step_1'
    perform

[ActiveJob] [RetryJob] [ID] 
  Failed enqueuing RetryJob to Test(default): DefaultsError
  enqueue

[ActiveJob] [RetryJob] [ID] 
  Retrying RetryJob (Job ID: ID) after 1 attempts in 3 seconds, due to a DefaultsError.
  enqueue_retry

[ActiveJob] [RetryJob] [ID] 
  Error performing RetryJob (Job ID: ID) from Test(default) in 31.73ms: DefaultsError:
    inline.rb:568:in `step_1'
  perform

[ActiveJob] Failed enqueuing RetryJob to Test(default): DefaultsError
enqueue
```

This too is "resolved" by using `flush_enqueued_jobs until enqueued_jobs.empty?`.

**Comment by zzak** [comment]
I think this is related to #49771
