### ISSUE TITLE
Active Job Integration Test Failure (sidekiq circular require)

### ISSUE THREAD

**Issue by zzak** [rails/rails#53460]
[[build ref](https://buildkite.com/rails/rails/builds/113116#0192cb2f-6afd-41d0-b885-8a10837f49f4)]

```
rake test:integration:sidekiq
/usr/local/bin/ruby -w -I"lib:test" /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb "test/integration/queuing_test.rb"
Using sidekiq
<internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37: warning: <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37: warning: loading in progress, circular require considered harmful - /usr/local/bundle/gems/sidekiq-7.3.4/lib/sidekiq.rb
	from /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6:in  `<main>'
	from /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6:in  `select'
	from /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:21:in  `block in <main>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /rails/activejob/test/integration/queuing_test.rb:3:in  `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /rails/activejob/test/helper.rb:13:in  `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /rails/activejob/test/support/integration/helper.rb:16:in  `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /tmp/d20241026-72-awtfe1/dummy/config/environment.rb:5:in  `<top (required)>'
	from /rails/railties/lib/rails/application.rb:440:in  `initialize!'
	from /rails/railties/lib/rails/initializable.rb:60:in  `run_initializers'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in  `tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in  `tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in  `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in  `call'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in  `each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in  `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in  `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in  `call'
	from /rails/railties/lib/rails/initializable.rb:50:in  `tsort_each_child'
	from /rails/railties/lib/rails/initializable.rb:50:in  `each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:421:in  `block in each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in  `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:422:in  `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in  `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in  `block in tsort_each'
	from /rails/railties/lib/rails/initializable.rb:61:in  `block in run_initializers'
	from /rails/railties/lib/rails/initializable.rb:32:in  `run'
	from /rails/railties/lib/rails/initializable.rb:32:in  `instance_exec'
	from /rails/railties/lib/rails/engine.rb:645:in  `block in <class:Engine>'
	from /rails/railties/lib/rails/engine.rb:645:in  `each'
	from /rails/railties/lib/rails/engine.rb:646:in  `block (2 levels) in <class:Engine>'
	from /rails/railties/lib/rails/engine.rb:692:in  `load_config_initializer'
	from /rails/activesupport/lib/active_support/notifications.rb:212:in  `instrument'
	from /rails/railties/lib/rails/engine.rb:693:in  `block in load_config_initializer'
	from /rails/railties/lib/rails/engine.rb:693:in  `load'
	from /tmp/d20241026-72-awtfe1/dummy/config/initializers/activejob.rb:2:in  `<main>'
	from /rails/activejob/test/support/integration/jobs_manager.rb:8:in  `current_manager'
	from /rails/activejob/test/support/integration/jobs_manager.rb:8:in  `new'
	from /rails/activejob/test/support/integration/jobs_manager.rb:13:in  `initialize'
	from /rails/activejob/test/support/integration/jobs_manager.rb:13:in  `require_relative'
	from /rails/activejob/test/support/integration/adapters/sidekiq.rb:3:in  `<main>'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in  `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /usr/local/bundle/gems/sidekiq-7.3.4/lib/sidekiq/api.rb:3:in  `<main>'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in  `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /usr/local/bundle/gems/sidekiq-7.3.4/lib/sidekiq.rb:149:in  `<main>'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in  `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /usr/local/bundle/gems/sidekiq-7.3.4/lib/sidekiq/rails.rb:8:in  `<main>'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in  `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /rails/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb:4:in  `<main>'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in  `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
/rails/activesupport/lib/active_support/testing/strict_warnings.rb:38:in `warn': <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37: warning: <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37: warning: loading in progress, circular require considered harmful - /usr/local/bundle/gems/sidekiq-7.3.4/lib/sidekiq.rb (ActiveSupport::RaiseWarnings::WarningError)
	from /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6:in  `<main>'
	from /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6:in  `select'
	from /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:21:in  `block in <main>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /rails/activejob/test/integration/queuing_test.rb:3:in  `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /rails/activejob/test/helper.rb:13:in  `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /rails/activejob/test/support/integration/helper.rb:16:in  `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /tmp/d20241026-72-awtfe1/dummy/config/environment.rb:5:in  `<top (required)>'
	from /rails/railties/lib/rails/application.rb:440:in  `initialize!'
	from /rails/railties/lib/rails/initializable.rb:60:in  `run_initializers'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in  `tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in  `tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in  `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in  `call'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in  `each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in  `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in  `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in  `call'
	from /rails/railties/lib/rails/initializable.rb:50:in  `tsort_each_child'
	from /rails/railties/lib/rails/initializable.rb:50:in  `each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:421:in  `block in each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in  `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:422:in  `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in  `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in  `block in tsort_each'
	from /rails/railties/lib/rails/initializable.rb:61:in  `block in run_initializers'
	from /rails/railties/lib/rails/initializable.rb:32:in  `run'
	from /rails/railties/lib/rails/initializable.rb:32:in  `instance_exec'
	from /rails/railties/lib/rails/engine.rb:645:in  `block in <class:Engine>'
	from /rails/railties/lib/rails/engine.rb:645:in  `each'
	from /rails/railties/lib/rails/engine.rb:646:in  `block (2 levels) in <class:Engine>'
	from /rails/railties/lib/rails/engine.rb:692:in  `load_config_initializer'
	from /rails/activesupport/lib/active_support/notifications.rb:212:in  `instrument'
	from /rails/railties/lib/rails/engine.rb:693:in  `block in load_config_initializer'
	from /rails/railties/lib/rails/engine.rb:693:in  `load'
	from /tmp/d20241026-72-awtfe1/dummy/config/initializers/activejob.rb:2:in  `<main>'
	from /rails/activejob/test/support/integration/jobs_manager.rb:8:in  `current_manager'
	from /rails/activejob/test/support/integration/jobs_manager.rb:8:in  `new'
	from /rails/activejob/test/support/integration/jobs_manager.rb:13:in  `initialize'
	from /rails/activejob/test/support/integration/jobs_manager.rb:13:in  `require_relative'
	from /rails/activejob/test/support/integration/adapters/sidekiq.rb:3:in  `<main>'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in  `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /usr/local/bundle/gems/sidekiq-7.3.4/lib/sidekiq/api.rb:3:in  `<main>'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in  `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /usr/local/bundle/gems/sidekiq-7.3.4/lib/sidekiq.rb:149:in  `<main>'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in  `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /usr/local/bundle/gems/sidekiq-7.3.4/lib/sidekiq/rails.rb:8:in  `<main>'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in  `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from /rails/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb:4:in  `<main>'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in  `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in  `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /rails/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb:4:in `<main>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /usr/local/bundle/gems/sidekiq-7.3.4/lib/sidekiq/rails.rb:8:in `<main>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /usr/local/bundle/gems/sidekiq-7.3.4/lib/sidekiq.rb:149:in `<main>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /usr/local/bundle/gems/sidekiq-7.3.4/lib/sidekiq/api.rb:3:in `<main>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /rails/activejob/test/support/integration/adapters/sidekiq.rb:3:in `<main>'
	from /rails/activejob/test/support/integration/jobs_manager.rb:13:in `require_relative'
	from /rails/activejob/test/support/integration/jobs_manager.rb:13:in `initialize'
	from /rails/activejob/test/support/integration/jobs_manager.rb:8:in `new'
	from /rails/activejob/test/support/integration/jobs_manager.rb:8:in `current_manager'
	from /tmp/d20241026-72-awtfe1/dummy/config/initializers/activejob.rb:2:in `<main>'
	from /rails/railties/lib/rails/engine.rb:693:in `load'
	from /rails/railties/lib/rails/engine.rb:693:in `block in load_config_initializer'
	from /rails/activesupport/lib/active_support/notifications.rb:212:in `instrument'
	from /rails/railties/lib/rails/engine.rb:692:in `load_config_initializer'
	from /rails/railties/lib/rails/engine.rb:646:in `block (2 levels) in <class:Engine>'
	from /rails/railties/lib/rails/engine.rb:645:in `each'
	from /rails/railties/lib/rails/engine.rb:645:in `block in <class:Engine>'
	from /rails/railties/lib/rails/initializable.rb:32:in `instance_exec'
	from /rails/railties/lib/rails/initializable.rb:32:in `run'
	from /rails/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /rails/railties/lib/rails/initializable.rb:50:in `each'
	from /rails/railties/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `call'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /rails/railties/lib/rails/initializable.rb:60:in `run_initializers'
	from /rails/railties/lib/rails/application.rb:440:in `initialize!'
	from /tmp/d20241026-72-awtfe1/dummy/config/environment.rb:5:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /rails/activejob/test/support/integration/helper.rb:16:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /rails/activejob/test/helper.rb:13:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /rails/activejob/test/integration/queuing_test.rb:3:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:21:in `block in <main>'
	from /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6:in `select'
	from /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6:in `<main>'
```

I'm assuming you can reproduce this locally with `RAILS_STRICT_WARNINGS=1`

**Comment by zzak** [comment]
cc @fatkodima In case you have time to investigate before I do

**Comment by fatkodima** [comment]
Thanks, will look tomorrow morning.
