### ISSUE TITLE
NoMethodError: undefined method `active_job' for Rails::Application::Configuration

### ISSUE THREAD

**Issue by matthewtusker** [rails/rails#53537]
### Steps to reproduce

We have a Rails app which was upgraded from 7.1.4.1 to 7.1.5. On startup we receive the following error:

```ruby
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5/lib/rails/railtie/configuration.rb:109:in `method_missing': undefined method `active_job' for #<Rails::Application::Configuration:0x00000000008ac0> (NoMethodError)
	from /app/vendor/bundle/ruby/3.2.0/gems/rails_logging-2.2.4/lib/rails_logging/railtie.rb:123:in `block in <class:Railtie>'
	from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.5/lib/active_support/lazy_load_hooks.rb:94:in `block in execute_hook'
	from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.5/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
	from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.5/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
	from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.5/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
	from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.5/lib/active_support/lazy_load_hooks.rb:77:in `each'
	from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.5/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5/lib/rails/application/finisher.rb:93:in `block in <module:Finisher>'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5/lib/rails/initializable.rb:32:in `instance_exec'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5/lib/rails/initializable.rb:32:in `run'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5/lib/rails/initializable.rb:60:in `run_initializers'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5/lib/rails/application.rb:426:in `initialize!'
	from /app/config/environment.rb:7:in `<top (required)>'
	from config.ru:5:in `require_relative'
	from config.ru:5:in `block (2 levels) in <top (required)>'
	from /app/vendor/bundle/ruby/3.2.0/gems/rack-3.1.8/lib/rack/builder.rb:108:in `eval'
	from /app/vendor/bundle/ruby/3.2.0/gems/rack-3.1.8/lib/rack/builder.rb:108:in `new_from_string'
```

We aren't using ActiveJob and don't plan to start using it any time soon.

This appears to be a regression similar to https://github.com/rails/rails/issues/35782, where a regression error has made `active_job` a required Gem.

### Expected behavior

The application should start

### Actual behavior

The application does not start

### System configuration
**Rails version**: 7.1.5

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
What is this line? 
```
from /app/vendor/bundle/ruby/3.2.0/gems/rails_logging-2.2.4/lib/rails_logging/railtie.rb:123:in `block in <class:Railtie>'
```

**Comment by matthewtusker** [comment]
🙃 It's a private Gem we use to set up logging. It's checking `Rails.application.config.active_job.queue_adapter`. Never mind!
