### ISSUE TITLE
Custom configuration does not allow three levels of nesting

### ISSUE THREAD

**Issue by sebastianludwig** [rails/rails#53540]
### Steps to reproduce

Add the following to `development.rb`

```
  config.x.a = "a"
  config.x.b.b = "b"
  config.x.c.c.c = "c"
```

### Expected behavior
The third value should be accessible via `Rails.configuration.x.c.c.c`. At least https://guides.rubyonrails.org/configuring.html#custom-configuration does not mention that the nesting may only be two levels.

### Actual behavior
```
development.rb:81:in `block in <top (required)>': undefined method `c=' for nil (NoMethodError)

  config.x.c.c.c = "c"
              ^^^^
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/railties-7.2.2/lib/rails/railtie.rb:256:in `instance_eval'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/railties-7.2.2/lib/rails/railtie.rb:256:in `configure'
	from /Users/sebastian/projects/Abrechnung2.0/config/environments/development.rb:3:in `<top (required)>'
	from /opt/homebrew/Cellar/ruby/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
```

### System configuration
**Rails version**: 7.2.2

**Ruby version**: 3.3.5

**Comment by zzak** [comment]
This is expected behavior, but maybe it should be documented there.

```ruby
config.x.c
#=> {}
config.x.c.class
#=> ActiveSupport::OrderedOptions
config.x.c.c
#=> nil
```

That's because the second call to `c` will hit OrderedOptions method_missing and this will return nil:
https://github.com/rails/rails/blob/9f8d180f7014b83b3eb8d3cf93fc093725b712b9/activesupport/lib/active_support/ordered_options.rb#L56

There are tests for this behavior:
https://github.com/rails/rails/blob/9f8d180f7014b83b3eb8d3cf93fc093725b712b9/activesupport/test/ordered_options_test.rb#L58-L61

I think we cannot change this behavior without breaking existing apps.

If you have complex custom config needs, then I suggest using [config_for](https://edgeapi.rubyonrails.org/classes/Rails/Application.html#method-i-config_for) but note it just creates a hash which you can't use `.` (dot) notation.
