### ISSUE TITLE
Rails 8.0.0 breaks usage of enums in models

### ISSUE THREAD

**Issue by Shannarra** [rails/rails#53703]
### Steps to reproduce

After an update from Rails 7 to Rails 8.0.0 the usage of `enum` inside a model stopped working as expected.

The following code works just fine in Rails 7:

```ruby
class MyModel < ApplicationRecord
  enum direction: {
         nonlinear: 3,
         positive: 2,  
         negative: 1,
         unknown: 0
       }
```

but using the exact same code, after the update to Rails 8.0.0, running the `rails db:setup` I get the following error:
```console
$ rails db:setup
Database 'myproject_development' already exists
Database 'myproject_test' already exists
rake aborted!
ArgumentError: wrong number of arguments (given 0, expected 1..2) (ArgumentError)
/home/shannarra/dev/rb/myproject/app/models/my_model.rb:2:in `<class:MyModel>'
/home/shannarra/dev/rb/myproject/app/models/my_model.rb:1:in `<main>'
/home/shannarra/dev/rb/myproject/db/seeds.rb:7:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)
```

### Expected behavior

Using `enum` should work as it did in previous Rails versions.

### Actual behavior
Using `enum` breaks the application after upgrading Rails to 8.0.0

### System configuration
**Rails version**:
Rails 8.0.0
**Ruby version**:
ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x86_64-linux]

**Comment by Earlopain** [comment]
Hi, this is expected. This version of defining enums has been deprecated in Rails 7.2 (https://github.com/rails/rails/pull/50987) and is now removed.

In Rails 8.0 you must now defined your enums like this:
```rb
enum :direction, {
         nonlinear: 3,
         positive: 2,  
         negative: 1,
         unknown: 0
       }
```
