### ISSUE TITLE
`ActiveRecord::Base.signed_id_verifier` not forward compatible from 7.1 to upward

### ISSUE THREAD

**Issue by beauraF** [rails/rails#53710]
### Steps to reproduce
I have created a [repository](https://github.com/beauraF/signed-id-bug-reproduction) with a [test](https://github.com/beauraF/signed-id-bug-reproduction/blob/main/test/models/user_test.rb) that reproduce the issue.

### Expected behavior
We are able to use a signed id generated with rails 7.2 in a process still running rails 7.1 without any issue.

### Actual behavior
Because of [this change](https://github.com/rails/rails/pull/49507), signed id generated with rails 7.2 will crash with a `ActiveSupport::MessageVerifier::InvalidSignature: mismatched digest` if used in a process still running rails 7.1. Leading to errors during a rolling rollout of 7.1 to 7.2/8.0 upgrade or in case of rollback.

I can work on a fix to make rails 7.1 forward compatible, but is that something you are interested in as rails 7.1 does not receive bug fix anymore?

### System configuration
**Rails version**: 7.1.5 / 7.2.2
**Ruby version**: 3.3.6

@byroot

**Comment by byroot** [comment]
FYI: https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case generally allow to create a single file executable repro.

**Comment by byroot** [comment]
> as rails 7.1 does not receive bug fix anymore?

We no longer pledge to do it, but we can still do it if we feel like it.

But in general I think the better solution is to add an option in 7.2 and up to keep generating the old format, so you can fully upgrade and then later flip the switch once all processes are ready for the new format.

**Comment by beauraF** [comment]
> FYI: https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case generally allow to create a single file executable repro.

Thanks @byroot. I tried them, but they seemed broken to me, because I had various errors. I was looking at them right now, trying to fix them, but I just figured out it's because I've always created them in our repository, which led them to use our `development.rb` file:

```ruby
doctolib  master [?] ⬢ v20.14.0 💎 v3.3.6 12,6s
➜ ruby foobar.rb
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
/Users/florent.beaurain/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/railtie/configuration.rb:109:in `method_missing': undefined method `active_storage' for an instance of Rails::Application::Configuration (NoMethodError)
	from /Users/florent.beaurain/Workspace/doctolib/doctolib/config/environments/development.rb:42:in `block in <top (required)>'
```

> But in general I think the better solution is to add an option in 7.2 and up to keep generating the old format, so you can fully upgrade and then later flip the switch once all processes are ready for the new format.

I thought it would come down to the same thing. Processes with the flag set to false won't be able to read ids coming from processes with the flag set to true. Unless we introduce a verifier to generate and a verifier to verify?

**Comment by byroot** [comment]
Both format should be able to be deserailized regardless of the value of the flag.

**Comment by AliSepehri** [comment]
I can confirm that the mentioned change is not forward compatible. Here are some details:

When url_safe is set to true, MessageVerifier uses two different methods to decode and encode:
```ruby
# lib/active_support/messages/codec.rb

def encode(data, url_safe: @url_safe)
  url_safe ? ::Base64.urlsafe_encode64(data, padding: false) : ::Base64.strict_encode64(data)
end

def decode(encoded, url_safe: @url_safe)
  url_safe ? ::Base64.urlsafe_decode64(encoded) : ::Base64.strict_decode64(encoded)
  ...
end
```

So during a rollout, new application instances use `::Base64.urlsafe_encode64(data, padding: false)` to encode, while the old instances still use `::Base64.strict_decode64(encoded)` to decode. This causes the old instances to break.

One possible solution is to use two different configurations for generating signed IDs and verifying signed IDs:
```ruby
signed_id_verifier = ActiveSupport::MessageVerifier.new secret, digest: "SHA256", serializer: JSON, url_safe: true

signed_id_generator = ActiveSupport::MessageVerifier.new secret, digest: "SHA256", serializer: JSON
```
and unify them again in the next major(?) version. Should I work on this fix?

**Comment by byroot** [comment]
@beauraF is working on it AFAIK.

**Comment by beauraF** [comment]
I started, but haven't had much time lately, I should be able to have another look on Saturday

**Comment by AliSepehri** [comment]
@byroot @beauraF Yesterday, I created a merge request to address this issue. Can I have your review on it?

**Comment by byroot** [comment]
Nevermind, I think I didn't read the PR quite correctly.
