### ISSUE TITLE
`<module:Expectations>': undefined method `infect_an_assertion' for module Minitest::Expectations (NoMethodError) with Minitest 5.25.3

### ISSUE THREAD

**Issue by yahonda** [rails/rails#53813]
Managed to reproduce CI failure at https://buildkite.com/rails/rails-nightly/builds/1409#01938e54-1a71-471d-a76d-12d038c0be02/1239-1243 

### Steps to reproduce

```ruby
git clone https://github.com/rails/rails
cd rails/activesupport
bundle update minitest --conservative
bin/test
```

### Expected behavior
It should pass.

### Actual behavior
It raises "`<module:Expectations>': undefined method `infect_an_assertion' for module Minitest::Expectations (NoMethodError)"

```ruby
$ bundle update minitest --conservative
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Resolving dependencies...
Using minitest 5.25.3 (was 5.25.1)
Bundle updated!
$ bin/test
/home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/minitest-5.25.3/lib/minitest/mock.rb:269:in `<module:Expectations>': undefined method `infect_an_assertion' for module Minitest::Expectations (NoMethodError)

  infect_an_assertion :assert_mock, :must_verify, :unary
  ^^^^^^^^^^^^^^^^^^^
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/minitest-5.25.3/lib/minitest/mock.rb:261:in `<top (required)>'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
	from /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/method_call_assertions.rb:3:in `<top (required)>'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
	from /home/yahonda/src/github.com/rails/rails/activesupport/test/abstract_unit.rb:16:in `<top (required)>'
	from /home/yahonda/src/github.com/rails/rails/activesupport/test/actionable_error_test.rb:3:in `require_relative'
	from /home/yahonda/src/github.com/rails/rails/activesupport/test/actionable_error_test.rb:3:in `<top (required)>'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/runner.rb:62:in `block in load_tests'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/runner.rb:60:in `each'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/runner.rb:60:in `load_tests'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/runner.rb:52:in `run'
	from /home/yahonda/src/github.com/rails/rails/tools/test.rb:18:in `<top (required)>'
	from bin/test:5:in `require_relative'
	from bin/test:5:in `<main>'
$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 263b7c4029..28cec71a21 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -367,7 +367,7 @@ GEM
     mini_magick (4.13.2)
     mini_mime (1.1.5)
     mini_portile2 (2.8.7)
-    minitest (5.25.1)
+    minitest (5.25.3)
     minitest-bisect (1.7.0)
       minitest-server (~> 1.0)
       path_expander (~> 1.1)
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x86_64-linux]

**Comment by yahonda** [comment]
`infect_an_assertion` has been added to Minitest v5.25.3 via 
https://github.com/minitest/minitest/commit/2d542ffa8045d40fed7fae733c6ab674a2ffbf09#diff-2a72d0121a0eb22e9f32a1ce654e5132391273007bf643b5ae68fbbc2800dea4R269

**Comment by yahonda** [comment]
I seem to recall that Rails has some that checks for the presence of assertion-related methods, but I'm not sure.

**Comment by skipkayhil** [comment]
https://github.com/minitest/minitest/issues/1022

It may be reproducible just by requiring `minitest/mock`

**Comment by yahonda** [comment]
Thanks for the information.

> It may be reproducible just by requiring minitest/mock

Right.

```ruby
$ ruby -v
ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x86_64-linux]
$ gem install minitest
Successfully installed minitest-5.25.3
Parsing documentation for minitest-5.25.3
Installing ri documentation for minitest-5.25.3
Done installing documentation for minitest after 0 seconds
1 gem installed
$ irb -w
irb(main):001> require 'minitest/mock'
/home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/minitest-5.25.3/lib/minitest/mock.rb:269:in `<module:Expectations>': undefined method `infect_an_assertion' for module Minitest::Expectations (NoMethodError)

  infect_an_assertion :assert_mock, :must_verify, :unary
  ^^^^^^^^^^^^^^^^^^^
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/minitest-5.25.3/lib/minitest/mock.rb:261:in `<top (required)>'
	from <internal:/home/yahonda/.rbenv/versions/3.3.6/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:141:in `require'
	from <internal:/home/yahonda/.rbenv/versions/3.3.6/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:141:in `rescue in require'
	from <internal:/home/yahonda/.rbenv/versions/3.3.6/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:135:in `require'
	from (irb):1:in `<main>'
	from <internal:kernel>:187:in `loop'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/exe/irb:9:in `<top (required)>'
	from /home/yahonda/.rbenv/versions/3.3.6/bin/irb:25:in `load'
	from /home/yahonda/.rbenv/versions/3.3.6/bin/irb:25:in `<main>'
<internal:/home/yahonda/.rbenv/versions/3.3.6/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- minitest/mock (LoadError)
	from <internal:/home/yahonda/.rbenv/versions/3.3.6/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from (irb):1:in `<main>'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb/workspace.rb:121:in `eval'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb/workspace.rb:121:in `evaluate'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb/context.rb:622:in `evaluate_expression'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb/context.rb:590:in `evaluate'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb.rb:1051:in `block (2 levels) in eval_input'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb.rb:1363:in `signal_status'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb.rb:1043:in `block in eval_input'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb.rb:1122:in `block in each_top_level_statement'
	from <internal:kernel>:187:in `loop'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb.rb:1119:in `each_top_level_statement'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb.rb:1042:in `eval_input'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb.rb:1023:in `block in run'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb.rb:1022:in `catch'
	from /home/yahonda/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb.rb:1022:in `run'
	... 4 levels...
irb(main):002>
```

**Comment by yahonda** [comment]
Opened https://github.com/rails/rails/pull/53814 to skip minitest v5.25.3
