### ISSUE TITLE
[activestorage] ActiveStorage::FileNotFoundError

### ISSUE THREAD

**Issue by jonas-jasas** [rails/rails#54028]
After file attachment `ActiveStorage::AnalyzeJob` always throws `ActiveStorage::FileNotFoundError`. My guess is that `ActiveStorage::AnalyzeJob` starts before file appear on a file system. Except this exception everything else works as expected, file get saved and attached.

### Steps to reproduce
- only in production environment (must be race condition related issue)
- good_job to handle background jobs 
- service: 'Disk'
- model with the `has_one_attached :img, dependent: :destroy`
- form with the file input
- submit form with the image
- Check background job status, should be  `ActiveStorage::FileNotFoundError: ActiveStorage::FileNotFoundError`

### Full trace
```
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/service/disk_service.rb:152:in `rescue in stream'
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/service/disk_service.rb:145:in `stream'
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/service/disk_service.rb:31:in `block in download'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in `block in instrument'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in `instrument'
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/service.rb:165:in `instrument'
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/service/disk_service.rb:30:in `download'
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/downloader.rb:32:in `download'
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/downloader.rb:13:in `block in open'
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/downloader.rb:24:in `open_tempfile'
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/downloader.rb:12:in `open'
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/service.rb:92:in `open'
/usr/local/bundle/gems/activestorage-8.0.1/app/models/active_storage/blob.rb:305:in `open'
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/analyzer.rb:35:in `download_blob_to_tempfile'
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/analyzer/image_analyzer/vips.rb:20:in `read_image'
/usr/local/bundle/gems/activestorage-8.0.1/lib/active_storage/analyzer/image_analyzer.rb:20:in `metadata'
/usr/local/bundle/gems/activestorage-8.0.1/app/models/active_storage/blob/analyzable.rb:52:in `extract_metadata_via_analyzer'
/usr/local/bundle/gems/activestorage-8.0.1/app/models/active_storage/blob/analyzable.rb:30:in `analyze'
/usr/local/bundle/gems/activestorage-8.0.1/app/jobs/active_storage/analyze_job.rb:11:in `perform'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/execution.rb:68:in `block in _perform_job'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:120:in `block in run_callbacks'
/usr/local/bundle/gems/i18n-1.14.6/lib/i18n.rb:353:in `with_locale'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:129:in `instance_exec'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:129:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:129:in `instance_exec'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:129:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:140:in `run_callbacks'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/execution.rb:67:in `_perform_job'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/instrumentation.rb:32:in `_perform_job'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/execution.rb:51:in `perform_now'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/instrumentation.rb:26:in `block in perform_now'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/railties/job_runtime.rb:13:in `block in instrument'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/instrumentation.rb:40:in `block in instrument'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:212:in `instrument'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/instrumentation.rb:39:in `instrument'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/railties/job_runtime.rb:11:in `instrument'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/instrumentation.rb:26:in `perform_now'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/logging.rb:32:in `block in perform_now'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/broadcast_logger.rb:241:in `method_missing'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/logging.rb:39:in `tag_logger'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/logging.rb:32:in `perform_now'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/execution.rb:29:in `block in execute'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:120:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/railtie.rb:95:in `block (4 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/reloader.rb:77:in `block in wrap'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/reloader.rb:74:in `wrap'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/railtie.rb:94:in `block (3 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:129:in `instance_exec'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:129:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:140:in `run_callbacks'
/usr/local/bundle/gems/activejob-8.0.1/lib/active_job/execution.rb:27:in `execute'
/usr/local/bundle/gems/good_job-4.6.0/app/models/good_job/job.rb:605:in `block (3 levels) in perform'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in `block in instrument'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in `instrument'
/usr/local/bundle/gems/good_job-4.6.0/app/models/good_job/job.rb:604:in `block (2 levels) in perform'
/usr/local/bundle/gems/good_job-4.6.0/lib/good_job/current_thread.rb:113:in `within'
/usr/local/bundle/gems/good_job-4.6.0/app/models/good_job/job.rb:562:in `block in perform'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:120:in `block in run_callbacks'
/usr/local/bundle/gems/good_job-4.6.0/app/models/good_job/batch.rb:80:in `within_thread'
/usr/local/bundle/gems/good_job-4.6.0/app/models/good_job/job.rb:747:in `reset_batch_values'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:129:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:140:in `run_callbacks'
/usr/local/bundle/gems/good_job-4.6.0/app/models/good_job/job.rb:556:in `perform'
/usr/local/bundle/gems/good_job-4.6.0/app/models/good_job/job.rb:299:in `block in perform_with_advisory_lock'
/usr/local/bundle/gems/good_job-4.6.0/app/models/concerns/good_job/advisory_lockable.rb:180:in `block in with_advisory_lock'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/relation.rb:1373:in `_scoping'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/relation.rb:548:in `scoping'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/scoping/default.rb:51:in `unscoped'
/usr/local/bundle/gems/good_job-4.6.0/app/models/concerns/good_job/advisory_lockable.rb:180:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/relation/delegation.rb:81:in `block in with_advisory_lock'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/relation.rb:1373:in `_scoping'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/relation.rb:548:in `scoping'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/relation/delegation.rb:81:in `with_advisory_lock'
/usr/local/bundle/gems/good_job-4.6.0/app/models/good_job/job.rb:293:in `perform_with_advisory_lock'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/relation/delegation.rb:81:in `block in perform_with_advisory_lock'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/relation.rb:1373:in `_scoping'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/relation.rb:548:in `scoping'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/relation/delegation.rb:81:in `perform_with_advisory_lock'
/usr/local/bundle/gems/good_job-4.6.0/lib/good_job/job_performer.rb:35:in `block in next'
/usr/local/bundle/gems/good_job-4.6.0/lib/good_job/capsule_tracker.rb:94:in `register'
/usr/local/bundle/gems/good_job-4.6.0/lib/good_job/job_performer.rb:34:in `next'
/usr/local/bundle/gems/good_job-4.6.0/lib/good_job/scheduler.rb:287:in `block (2 levels) in create_task'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/reloader.rb:77:in `block in wrap'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/local/bundle/gems/activesupport-8.0.1/lib/active_support/reloader.rb:74:in `wrap'
/usr/local/bundle/gems/good_job-4.6.0/lib/good_job/scheduler.rb:286:in `block in create_task'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/scheduled_task.rb:298:in `process_task'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/timer_set.rb:98:in `block in ns_post_task'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
<internal:kernel>:187:in `loop'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
/usr/local/bundle/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
```

### System configuration
**Rails version**: 8.0.1

**Ruby version**: 3.3.6

**Comment by jonas-jasas** [comment]
With the activestorage-8.0.2 issue still exists.

**Comment by jonas-jasas** [comment]
I guess this issue related or even the same https://github.com/rails/rails/issues/39107

**Comment by jonas-jasas** [comment]
This monkeypatch helped me
```
Rails.application.config.to_prepare do
  ActiveStorage::Blob.class_eval do
    # Override the method to run analyze synchronously
    def analyze_later
      analyze unless analyzed?
    end
  end
end
```
