### ISSUE TITLE
Unresolved or ambiguous specs + active_support/basic_object (LoadError) on upgrade

### ISSUE THREAD

**Issue by dvodvo** [rails/rails#54027]
### Steps to reproduce
upgrading from `gem "rails", "~> 7.1.3", ">= 7.1.3.2"`
then `gem 'rails', '~> 7.2', '>= 7.2.2.1'`
to `gem 'rails', '~> 8.0', '>= 8.0.1'`

running `rails app:update` on the latter upgrade fails

The first upgrade mentions
```
DEPRECATION WARNING: ActiveSupport::ProxyObject is deprecated and will be removed in Rails 8.0.
Use Ruby's built-in BasicObject instead.
 (called from <main> at /Users/dep/r/gal/config/application.rb:7)
```
which points to this line: `Bundler.require(*Rails.groups)`  
The warning is rather misleading for two reasons : 
1 - I failed to find any documentation relating to it
2 - stock new rails 8 apps have the same line.

the warnings also appear when running tests.

The upgrade process, on each iteration, highlighted also:
```
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      psych (>= 4.0.0)
```
while the former disappears when running `gem cleanup stringio`,
the latter keeps proposing itself after running `gem cleanup psych`:
```
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      psych (>= 4.0.0)
      Available/installed versions of this gem:
      - 5.2.2
      - 5.1.2
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Clean up complete
[xxx] gal % gem cleanup psych
Cleaning up installed gems...
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      psych (>= 4.0.0)
      Available/installed versions of this gem:
      - 5.2.2
      - 5.1.2
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Clean up complete
[xxx] gal % gem cleanup psych
Cleaning up installed gems...
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      psych (>= 4.0.0)
      Available/installed versions of this gem:
      - 5.2.2
      - 5.1.2
```
from gemfile.lock
```
    psych (5.2.2)
      date
      stringio

    rdoc (6.10.0)
      psych (>= 4.0.0)
```

`bundle update rails` returns the stack shown in 'Actual behavior' section.

```
rails -v  
Rails 8.0.1
```
but
` bin/rails s`
returns the stack shown below, with the application unstartable.

I found a resolution path accordingly, see below homonymous section title

### Expected behavior
expecting to see a number of changed config files suggested. server startable.

### Actual behavior

```
/Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- active_support/basic_object (LoadError)
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jbuilder-2.11.5/lib/jbuilder/jbuilder.rb:5:in `rescue in <main>'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jbuilder-2.11.5/lib/jbuilder/jbuilder.rb:1:in `<main>'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jbuilder-2.11.5/lib/jbuilder.rb:2:in `<main>'
	from <internal:/Users/dep/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/dep/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:55:in `each'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:44:in `each'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:44:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler.rb:187:in `require'
	from /Users/dep/r/gal/config/application.rb:7:in `<main>'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/command/actions.rb:15:in `require_application!'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/commands/app/update_command.rb:15:in `perform'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/command/base.rb:73:in `perform'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/command.rb:65:in `block in invoke'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/command.rb:143:in `with_argv'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/command.rb:63:in `invoke'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/commands.rb:18:in `<main>'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
/Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- active_support/proxy_object (LoadError)
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jbuilder-2.11.5/lib/jbuilder/jbuilder.rb:2:in `<main>'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jbuilder-2.11.5/lib/jbuilder.rb:2:in `<main>'
	from <internal:/Users/dep/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/dep/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:55:in `each'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:44:in `each'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:44:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler.rb:187:in `require'
	from /Users/dep/r/gal/config/application.rb:7:in `<main>'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/command/actions.rb:15:in `require_application!'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/commands/app/update_command.rb:15:in `perform'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/command/base.rb:73:in `perform'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/command.rb:65:in `block in invoke'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/command.rb:143:in `with_argv'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/command.rb:63:in `invoke'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/commands.rb:18:in `<main>'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/dep/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**:  upgrading to 8.0.1

**Ruby version**:  3.3.0

### Resolution path
• delete Gemfile.lock
• run `bundle`
• run `bundle update rails`
errors disappeared and application can run.

This does leave two issues:
1) the deprecation warning is misleading
2) rdoc and psych dependencies would leave users in the lurch: either some upstream spec is off and, possibly the error message is incomplete.

**Comment by zzak** [comment]
Just a wild guess, but maybe an issue with Ruby 3.3.0, are you using the latest patch level?

**Comment by dvodvo** [comment]
No.  I am treading slowly with this as it is going to affect a few apps.   I have my doubts as [the reference to rdoc is the most recent ](https://rubygems.org/gems/rdoc) and that sets the dependency at 4.0.0

I will add that similar behaviour occured on a second app running 3.3.0... Thus, I guess I will step through those versions in other apps and see what comes of it.

**Comment by zzak** [comment]
That is likely a bug in the version of Ruby you are using (and the bundled rubygems), please try upgrading and let us know.

> DEPRECATION WARNING: ActiveSupport::ProxyObject is deprecated and will be removed in Rails 8.0.

Is probably a warning coming from one of your gem dependencies, hence the stacktrace pointing to `Bundler.require`.

I don't think this is a bug in Rails, so I'm going to close it but please feel to comment if you run into trouble.
We also have [discuss](https://discuss.rubyonrails.org/c/rubyonrails-talk/7) where you can ask general questions and get help.

**Comment by gareth** [comment]
Just as an extra datapoint on this:

When I encountered this problem, it was because of an outdated `jbuilder` dependency. After upgrading (for me) from `2.11.5` to `2.13.0` the issue was resolved.

**Comment by slikstir** [comment]
Seconding Gareth - Jbuilder upgrade from 2.11.2 to 2.13.0 solved this for me.

**Comment by slikstir** [comment]
> Just as an extra datapoint on this:
> 
> When I encountered the `ActiveSupport::ProxyObject` deprecation warning, it was because of an outdated `jbuilder` dependency. After upgrading (for me) from `2.11.5` to `2.13.0` the issue was resolved.

Seconding Gareth - Jbuilder upgrade from 2.11.2 to 2.13.0 solved this for me.
