### ISSUE TITLE
.first_or_initialize doesn't set key/value on hstore column

### ISSUE THREAD

**Issue by mayanring** [rails/rails#9679]
This was tested on a new Rails 4 beta-1 install using Postgres.

When there isn't an existing Product that matches, I'd normally expect first_or_initialize to set the field specified in the 'where' clause. In this case, the match takes place on an hstore column.

So I would expect for:

``` ruby
@product = Product.where( "properties -> 'rating' = 'PG-13'" ).first_or_initialize
@product.rating == 'PG-13'  # this doesn't work; rating is nil
```

Sample code, test and output here:
https://gist.github.com/rynmng/5139435

**Comment by joevandyk** [comment]
This should be reopened. Failing test is at https://github.com/joevandyk/rails/commit/dfb956fc6a9363e2556abfc85e75b0bcf18b6b14

Output:
```
  1) Error:
PostgresqlHstoreTest#test_find_or_initialize_by:
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column hstores.language does not exist
LINE 1: SELECT  "hstores".* FROM "hstores" WHERE "hstores"."language...
                                                 ^
: SELECT  "hstores".* FROM "hstores" WHERE "hstores"."language" = 'fr' LIMIT 1
    /home/monkey/projects/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `async_exec'
    /home/monkey/projects/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `block in exec_no_cache'
    /home/monkey/projects/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
    /home/monkey/projects/rails/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/monkey/projects/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
    /home/monkey/projects/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `exec_no_cache'
    /home/monkey/projects/rails/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:588:in `execute_and_clear'
    /home/monkey/projects/rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
    /home/monkey/projects/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:351:in `select'
    /home/monkey/projects/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
    /home/monkey/projects/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    /home/monkey/projects/rails/activerecord/lib/active_record/querying.rb:39:in `find_by_sql'
    /home/monkey/projects/rails/activerecord/lib/active_record/relation.rb:638:in `exec_queries'
    /home/monkey/projects/rails/activerecord/lib/active_record/relation.rb:514:in `load'
    /home/monkey/projects/rails/activerecord/lib/active_record/relation.rb:243:in `to_a'
    /home/monkey/projects/rails/activerecord/lib/active_record/relation/finder_methods.rb:475:in `find_take'
    /home/monkey/projects/rails/activerecord/lib/active_record/relation/finder_methods.rb:105:in `take'
    /home/monkey/projects/rails/activerecord/lib/active_record/relation/finder_methods.rb:84:in `find_by'
    /home/monkey/projects/rails/activerecord/lib/active_record/relation.rb:224:in `find_or_initialize_by'
    /home/monkey/projects/rails/activerecord/lib/active_record/querying.rb:6:in `find_or_initialize_by'
    test/cases/adapters/postgresql/hstore_test.rb:146:in `test_find_or_initialize_by'
```

**Comment by senny** [comment]
@joevandyk thanks for confirming.

**Comment by joevandyk** [comment]
it's still a problem in 4-2-stable.

On Wed, Dec 23, 2015 at 9:38 AM, Ruby on Rails Bot <notifications@github.com

**Comment by rafaelfranca** [comment]
And in master?

**Comment by joevandyk** [comment]
Still happens on master.

**Comment by cdurante** [comment]
Bump. Similar issue, using first_or_create in Rails 5betaTrying to create new record from hash of attributes which includes an ```hstore``` column. 

*My code:*
Attribute hashes:

```Ruby
marvel = {
  name: 'Marvel',
  description: 'This is the standard shadow template of the marvel kit',
  shadow_params: {
    led: '0',
    pb: '0',
    pb_lambda: '0' }
}
arduino_lock = {
  name: 'arduino_lock',
  description: 'This is the standard shadow template of an Arduino lock',
  shadow_params: {
    door: 'closed',
    master_code: '424242',
    valid_codes: %w(254545 123456 654321)
  }
}
iphone = {
  name: 'iPhone',
  description: 'This is the standard shadow template of an iPhone for tracking',
  shadow_params: {
    location: {
      lat: '',
      lon: '',
      timestamp: ''
    }
  }
}
```

*Then doing a batch first or create on those hashes:*

```Ruby
[marvel, arduino_lock, iphone].each do |type|
  ThingType.where(type).first_or_create
end
```
**The SQL that is generated has the ```hstore``` attribute listed as a separate table instead of a column.**

```SQL
 SELECT "things".* FROM "things" WHERE "things"."name" = $1 AND "things"."description" = $2 AND "shadow_params"."led" = $3 AND "shadow_params"."pb" = $4 AND "shadow_params"."pb_lambda" = $5
 ```

**Resulting in the following ```ActiveRecord ```Error:**

```console
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "shadow_params"
LINE 1: ...me" = $1 AND "thing_types"."description" = $2 AND "shadow_pa...
```

**Comment by prathamesh-sonpatki** [comment]
@cdurante We can't query HStore columns using hash like syntax as of now. Please check this commit - https://github.com/prathamesh-sonpatki/rails/commit/ad08072249f85732abe4de408a0316c6b7bfaa99.

Because the hash like syntax does not work and we have to pass string query to `where` for querying HStore columns, `first_or_create` does not work with HStore columns. Because it expects the arguments to be a hash, not a string.

``` ruby
>> p = Profile.find_or_create_by("settings->'color' = 'Black'")
  Profile Load (1.3ms)  SELECT  "profiles".* FROM "profiles" WHERE (settings->'color' = 'Black') LIMIT $1  [["LIMIT", 1]]
ArgumentError: When assigning attributes, you must pass a hash as an argument.
```

It would be cool to allow hash like syntax for hstore columns though, but I think we will need to make changes in Arel first to build proper AST for HSTore columns. Currently it treats the hstore column name as second table name if passed in hash like syntax.

Here is sample AST for above query

```
#<Arel::SelectManager:0x007fedd233bdd8 @ctx=#<Arel::Nodes::SelectCore:0x007fedd233bd38 @source=#<Arel::Nodes::JoinSource:0x007fedd233bce8 @left=#<Arel::Table:0x007fedd23e0450 @name="profiles", @columns=nil, @aliases=[], @type_caster=#<ActiveRecord::TypeCaster::Map:0x007fedd23e04a0 @types=Profile (call 'Profile.connection' to establish a connection)>, @table_alias=nil>, @right=[]>, @top=#<Arel::Nodes::Top:0x007fedd233b568 @expr=#<Arel::Nodes::BindParam:0x007fedd233b5b8>>, @set_quantifier=nil, @projections=[#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007fedd23e0450 @name="profiles", @columns=nil, @aliases=[], @type_caster=#<ActiveRecord::TypeCaster::Map:0x007fedd23e04a0 @types=Profile (call 'Profile.connection' to establish a connection)>, @table_alias=nil>, name="*">], @wheres=[#<Arel::Nodes::And:0x007fedd233b6f8 @children=[#<Arel::Nodes::Grouping:0x007fedd233b720 @expr="settings->'color' = 'Black'">]>], @groups=[], @havings=[], @windows=[]>, @bind_values=[], @ast=#<Arel::Nodes::SelectStatement:0x007fedd233bd88 @cores=[#<Arel::Nodes::SelectCore:0x007fedd233bd38 @source=#<Arel::Nodes::JoinSource:0x007fedd233bce8 @left=#<Arel::Table:0x007fedd23e0450 @name="profiles", @columns=nil, @aliases=[], @type_caster=#<ActiveRecord::TypeCaster::Map:0x007fedd23e04a0 @types=Profile (call 'Profile.connection' to establish a connection)>, @table_alias=nil>, @right=[]>, @top=#<Arel::Nodes::Top:0x007fedd233b568 @expr=#<Arel::Nodes::BindParam:0x007fedd233b5b8>>, @set_quantifier=nil, @projections=[#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007fedd23e0450 @name="profiles", @columns=nil, @aliases=[], @type_caster=#<ActiveRecord::TypeCaster::Map:0x007fedd23e04a0 @types=Profile (call 'Profile.connection' to establish a connection)>, @table_alias=nil>, name="*">], @wheres=[#<Arel::Nodes::And:0x007fedd233b6f8 @children=[#<Arel::Nodes::Grouping:0x007fedd233b720 @expr="settings->'color' = 'Black'">]>], @groups=[], @havings=[], @windows=[]>], @orders=[], @limit=#<Arel::Nodes::Limit:0x007fedd233b590 @expr=#<Arel::Nodes::BindParam:0x007fedd233b5b8>>, @lock=nil, @offset=nil, @with=nil>>
```

It has `@left=#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007fcc66366868 @name="settings"` for representing `settings` which is a hstore column on profiles table.

**Comment by prathamesh-sonpatki** [comment]
`find_or_initialize` will always fail if we pass hash as argument for hstore because we will first try to find the record and *then* initialize new record as per current limitations of querying hstore columns.

``` ruby
> p = Profile.find_or_initialize_by(settings: { color: 'red' })
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "settings"
LINE 1: SELECT  "profiles".* FROM "profiles" WHERE "settings"."color...
                                                   ^
: SELECT  "profiles".* FROM "profiles" WHERE "settings"."color" = $1 LIMIT $2
```

And if we pass string query required for querying hstore columns then `assign_attributes` will complain because we passed string instead of hash.

```ruby
>> p = Profile.find_or_initialize_by("settings->'color' = 'blue'")
  Profile Load (0.4ms)  SELECT  "profiles".* FROM "profiles" WHERE (settings->'color' = 'blue') LIMIT $1  [["LIMIT", 1]]
ArgumentError: When assigning attributes, you must pass a hash as an argument.
```

cc @sgrif Should the second query work?

**Comment by schneems** [comment]
This hasn't been commented on since 2016 can we close this issue?

**Comment by ghiculescu** [comment]
I think so. If still an issue, let’s make a new issue or better yet, a PR.
